### ISSUE TITLE
Error in example queries on the home page?

### ISSUE THREAD

**Issue by coussej** [timescale/timescaledb#10]
Hi, 

I'm trying out timescaledb. I was trying out some queries similar to those on the home page, such as

```sql
SELECT date_trunc(time, '15 min') AS 15min, COUNT(device_id)
FROM logs
WHERE cpu_level > 0.9 AND free_mem < 1024
  AND time > now() - interval '24 hours'
GROUP BY 15min
ORDER BY COUNT(device_id) DESC LIMIT 25;
```

However, this gives an error on the `date_trunc` function: No function matches the given name and argument types. You might need to add explicit type casts.

Indeed, I cannot find a usage like the one above in the [postgres docs](https://www.postgresql.org/docs/9.6/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC). Am I missing something or are the examples wrong?

**Comment by akulkarni** [comment]
Good catch. Yes, those examples have the wrong syntax. Not sure how that happened, but will fix.

This should be the correct syntax:

 ```
SELECT date_trunc('minute', time) AS foo, COUNT(device_id)
FROM logs
WHERE cpu_level > 0.9 AND free_mem < 1024
  AND time > now() - interval '24 hours'
GROUP BY foo
ORDER BY COUNT(device_id) DESC LIMIT 25;
```

**Comment by coussej** [comment]
Thanks! If I end up writing an extended date_trunc function for handling intervals like the 15m in the example, I'll let you know!

**Comment by akulkarni** [comment]
Please do! That would be awesome.

**Comment by addon9** [comment]
i also get same stuff in this case what i should cheng? or there any syntax mistack?

SELECT data_trunc('hour', time) AS foo, trunc(avg(temperature), 2)avg_temp, trunc(min(temperature), 2) min_temp, trunc(max(temperature), 2) max_temp FROM conditions c WHERE c.device_id IN ( SELECT device_id FROM locations WHERE location LIKE 'field-%' ) GROUP BY "hour" ORDER BY "hour" ASC LIMIT 24;
