### ISSUE TITLE
Running ALTER EXTENSION UPDATE while already running latest version

### ISSUE THREAD

**Issue by Ormod** [timescale/timescaledb#1003]
**Relevant system information:**
 - TimescaleDB version (output of `\dx` in `psql`): 1.0.1
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**
Running ALTER EXTENSION UPDATE on an already created extension that's running the latest version causes an error to be returned:

defaultdb=> alter extension timescaledb update;
ERROR:  extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.

Note that in this case it was the first command issued on a new PG session.

**Expected behavior**
The default PG extension behavior is to always give out just a NOTICE.

**Comment by svenklemm** [comment]
Is this still happening on 1.2.x? I can't reproduce:
```
%  psql -h localhost gapfill -X -c 'ALTER EXTENSION timescaledb UPDATE;'
NOTICE:  version "1.3.0-dev" of extension "timescaledb" is already installed
ALTER EXTENSION
```

**Comment by cevian** [comment]
@svenklemm does it give an error if `-X` isn't passed in to psql?

**Comment by vdedyukhin** [comment]
This message appears after typing, for example, '\dx' command before ALTER EXTENSION timescaledb UPDATE;

**Comment by henrych4** [comment]
Not sure if it helps:

In my case, running `docker exec -it ${containerName} sh` first, then start instance by running `psql -U postgres -X` and finally execute `ALTER EXTENSION timescaledb UPDATE;` leads to error message "ERROR: extension "timescaledb" cannot be updated after the old version has already been loaded ..."

To make it works, the first two commands have to be executed in single line:
`docker exec -it ${containerName} psql -U postgres -X`. Then executing the ALTER command updates extension.

**Comment by cevian** [comment]
I think this has been fixed a while ago, please let me know if not.

**Comment by jaalsuca** [comment]
I currently experiencing the error. Someone can help me out!

**Comment by dberardo** [comment]
same problem here ... and of course if i try to kill the postgres service before running the command, then psql cannot even run .... sounds like a vicious circle :D

**Comment by LukasJerabek** [comment]
I thought I had similar problem, but in my case I was executing psql with --single-transaction, which caused this problem too. So be very careful about any circumstances that would wrap your update command.

**Comment by fabriziomello** [comment]
@LukasJerabek this is a two year old issue. I strongly recommend you open a new issue describing the problem you're facing step by step.

**Comment by LukasJerabek** [comment]
Sorry, maybe I was not clear, I have no problem because I solved it by not using --single-transaction, I just wanted to give hint to others.
