### ISSUE TITLE
Backup/restore all tables except (the only) hypertable

### ISSUE THREAD

**Issue by doomsower** [timescale/timescaledb#1024]
I'm trying to come up with procedure to make dump of production database and then restore it on dev machine. This database contains one huge hypertable (it's the only hypertable id db) and so restore takes really long time, but I don't need this data for dev purposes.

So I checked how blank database looks like, and how database with data looks like, and my pg_dump looks like this:
```
pg_dump $POSTGRES_HOST_OPTS -Fc -f dump.bak \
 --exclude-table-data='public.measurements' \
 --exclude-table-data='_timescaledb*' \
  --exclude-table='_timescaledb_internal._hyper*' \
  $POSTGRES_DATABASE
```

where `public.measurements` is my hypertable

Then I restore it like this:
```bash
psql --username "$POSTGRES_USER" -c "ALTER DATABASE ${POSTGRES_DB} SET timescaledb.restoring='on';"
psql --username "$POSTGRES_USER" -d $POSTGRES_DB -c "drop schema public cascade; create schema public;"
pg_restore --username "$POSTGRES_USER" -Fc -d $POSTGRES_DB /docker-entrypoint-initdb.d/dump.bak
psql --username "$POSTGRES_USER" -c "ALTER DATABASE ${POSTGRES_DB} SET timescaledb.restoring='off';"

# Recreate hypertable in case it's not in the dump
psql --username "$POSTGRES_USER" -d $POSTGRES_DB -c "SELECT create_hypertable('measurements', 'timestamp', if_not_exists => true);"
```

Everything gets restored as expected, but when I try to insert something into `public.measurements` hypertable, the insert fails with `ERROR:  could not open relation with OID 0`

I tried without turning `timescaledb.restoring` on and off, but it doesn't help.

Looks like I'm excluding something that I shouldn't exclude during pg_dump. Could someone help me with this?

**Comment by billyburly** [comment]
Last I checked the --exclude-table-data flag doesn't work with timescale. I forgot to create an issue for it. See: https://timescaledb.slack.com/messages/C63MYDZ35/convo/C63MYDZ35-1537369642.000100/

**Comment by mkarklins** [comment]
@billyburly did you manage to create in issue for it? Or @doomsower were you able to resolve this?

**Comment by doomsower** [comment]
@mkarklins I (not) solved it by extracting hypertable into separate db

**Comment by jtushman** [comment]
Has anyone figured out a path for this.  I think this is an important feature.  We should consider reopening this issue.  Or I can create a similar one

**Comment by mkarklins** [comment]
I haven't figured out this one my self. 

Given that the OP has found a workaround ( which relies on a unique use case ), and wouldn't care much about the issue - I think you could create a new one.

**Comment by davidkohn88** [comment]
So, I think to do this properly, the way to do it would be to do a dump with `--section=pre-data --section=post-data` of the entire database, then a `--section=data` dump that excludes based on schema (not based on tables or patterns of tables that include schema names because I'm not sure that that will work, you will want to make sure that you still dump the _timescaledb_catalog schema) and can exclude the entire `_timescaledb_internal` schema. To restore, you'll want run the timescaledb_pre_restore() function, then do a `--section= pre-data` restore from the first dump, a `--section=data` restore from the second, then a `--section=post-data` restore from the first, then run timescaledb_post_restore(). A bit of a process, but it should work and should still allow you to insert some data into the hypertable as example data or whatever after it's done.

**Comment by davidkohn88** [comment]
I think if you leave out the part where you exclude table data from the _timescaledb*, because that will exclude our catalog schema potentially as well and I also would not exclude-table but just exclude-table-data with the '_timescaledb_internal._hyper*' flag. So it would just be: 
```
pg_dump` $POSTGRES_HOST_OPTS -Fc -f dump.bak \
  --exclude-table-data='_timescaledb_internal._hyper*' \
  $POSTGRES_DATABASE
```

**Comment by davidkohn88** [comment]
Also, as a note here, @jtushman had asked about how to exclude just a hypertable's data but leave the continuous aggregates around, you can generate a list of exclude-table-data's with the following:
```sql 
select string_agg(format($$--exclude-table-data='%s.%s'$$,coalesce(cc.schema_name,c.schema_name), coalesce(cc.table_name, c.table_name)), ' \
')
FROM _timescaledb_catalog.hypertable h 
INNER JOIN _timescaledb_catalog.chunk c on c.hypertable_id = h.id 
LEFT JOIN _timescaledb_catalog.chunk cc on c.compressed_chunk_id = cc.id
WHERE h.schema_name = <foo> AND h.table_name = <bar> ;
```
You should then disable the jobs or add `--exclude-table-data='_timescaledb_config.bgw_job' so you don't end up with the jobs then invalidating data and deleting from the continuous aggregates without you expecting it.

**Comment by JefferyHus** [comment]
I find `--exclude-table-data` to not work as expected as of PG15. But when I use `--exclude-table` the dump proceeds as expected.
