### ISSUE TITLE
Postgres 9.6.10 fails to start `_SearchSysCache1`

### ISSUE THREAD

**Issue by arvindkumarc** [timescale/timescaledb#1027]
**Relevant system information:**
 - OS: Mojave 10.14.2
 - PostgreSQL 9.6.10 (Postgres.app)
 - TimescaleDB version (latest from homebrew)
 - Installation method: brew

**Describe the bug**
ERROR:  could not load library "/Applications/Postgres.app/Contents/Versions/9.6/lib/postgresql/timescaledb.so": dlopen(/Applications/Postgres.app/Contents/Versions/9.6/lib/postgresql/timescaledb.so, 10): Symbol not found: _SearchSysCache1
  Referenced from: /Applications/Postgres.app/Contents/Versions/9.6/lib/postgresql/timescaledb.so
  Expected in: /Applications/Postgres.app/Contents/Versions/9.6/bin/postgres
 in /Applications/Postgres.app/Contents/Versions/9.6/lib/postgresql/timescaledb.so

**To Reproduce**
1. Modify the postgresql.conf for the `shared_preloaded` to include `timescale`
2. Execute the `move_files.sh` after modifying the destination paths to match Postgres.app postgres db paths.

**Comment by RobAtticus** [comment]
It seems like Postgres.app may be missing the development headers that our extension relies on. Is it possible for you to switch to using brew for the installation of PostgreSQL as well, or is it an existing install?

**Comment by RobAtticus** [comment]
Also I believe I've heard reports of 9.6.10 being a bit broken, you could also try using 9.6.11 instead.

**Comment by RobAtticus** [comment]
Hey @arvindkumarc , any update on this issue?

**Comment by mfreed** [comment]
Closing out issue. Can re-open if more information is provided  (cc: @arvindkumarc )
