### ISSUE TITLE
Simple select 1 query scans all chunks

### ISSUE THREAD

**Issue by camallen** [timescale/timescaledb#1032]
I have a timescale db with an `events` hypertable. Running this query issues a seq scan across all the chunks `select 1 from events;`. This was surprising to me but could be an expected result.

I was using that query as a healthcheck on my application. I'm reporting this if other folks need help, i switched my healthy check query to `select 1` avoiding the hypertable to test the db connection instead. 

```
`explain select 1 from events;`
"Result  (cost=0.00..261702.67 rows=2692784 width=4)"
"  ->  Append  (cost=0.00..234774.83 rows=2692784 width=0)"
"        ->  Seq Scan on events  (cost=0.00..0.00 rows=1 width=0)"
"        ->  Seq Scan on _hyper_1_1_chunk  (cost=0.00..5077.46 rows=59046 width=0)"
"        ->  Seq Scan on _hyper_1_2_chunk  (cost=0.00..12.30 rows=230 width=0)"
......
```

using offical docker images
> PostgreSQL 10.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit
> timescaledb 1.0.0

Feel free to close this if it's expected behaviour.

**Comment by mfreed** [comment]
Because there is no WHERE predicate to constrain the query to a certain subset of chunks, that query is going to be pushed down an execute on each chunk.  So you are just seeing postgres' behavior of `select 1 from <table>` on each chunk.

What are you actually trying to do?  Just check that the DB is alive?

**Comment by camallen** [comment]
> What are you actually trying to do? Just check that the DB is alive?

Yes and the schema conforms to expectation, i.e. the correct table exists. I really should have combined this with a where clause to limit the scope of chunks to be scanned and/or tried to get it to do an index scan instead of seq scans. 

This was really a note, asking for clarity, thanks for doing that. Hopefully this saves someone time in the future so they don't repeat my mistake :)

Thanks for the prompt feedback, and I'm really enjoying the timescale solution you've all built.
