### ISSUE TITLE
postgres-11: extension not found while getting version

### ISSUE THREAD

**Issue by arefehtam** [timescale/timescaledb#1070]
I added a new extension (timescaledb) like this:

    CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;  

Then execute below command to see list of extensions:

    select * from pg_extension;

And then remove a row in pg_extension which was related to `timescaledb`.

After that an abnormal bug happened and cann't even reconnect to my database in `dbeaver`, even trying via command line, then  was only able to connect to db but again can not run any commands because it says:

    ERROR:  extension not found while getting version

I don't know what problem exactly happened and how to handle it. 

**Update:**

To be sure, every one can reproduce this error, I created a new database, then with super-user privilege, repeated above commands to create extension and remove it like before. There again, the same issue raised.

This is my spec:

- OS: centos7

- Postgres config comes from [pgtune][1]

- Postgres version:11

- Timescale version: 1.2 [follow this link for installation][1]

  [1]: http://pgtune.leopard.in.ua/
  [2]: https://docs.timescale.com/v1.2/getting-started/installation/rhel-centos/installation-yum

**Comment by mfreed** [comment]
Hi @arefehtam thanks for the report.  One question:  Why were you trying to delete that row from `pg_extension`?  I ask because the standard way to remove would be `DROP EXTENSION`.

We can look into this and if it's something either to fix/block, but just curious.

**Comment by RobAtticus** [comment]
Hey @arefehtam just wondering if you have some more info
