### ISSUE TITLE
Does Timescale support Agensgraph extension?

### ISSUE THREAD

**Issue by candysmurf** [timescale/timescaledb#1077]
I saw that you have an example of how to integrate PostGIS with thimescaledb. I'm wondering if I can do the same for [Agensgraph](https://github.com/bitnine-oss/agensgraph)? It's a multi-mode graph DB built on the top of Postgres.

Actually I got an error as below:
```sh
postgres=# CREATE EXTENSION agensgraph;
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/agensgraph.control": No such file or directory
```

**Comment by mfreed** [comment]
Hi @candysmurf that error looks more like an installation issue with Agensgraph?    I would make sure you've installed in the proper location and your paths are correct.

Perhaps you could run through the steps of installing Agensgraph on a clean Postgres database (i.e., before you install Timescale) and, once that succeeds, try to repeat the steps after Timescale is installed.

Cheers.

**Comment by candysmurf** [comment]
@mfreed, where should I install agensgraph? Agensgraph is built on the top of Postgres. I'm trying to integrate it as an extension to timescaledb. Where do I need to install agensgraph? I didn't see any doc for it. If you have one, would you link me there? thanks

**Comment by candysmurf** [comment]
@mfreed, any update? thanks

**Comment by mfreed** [comment]
Sorry, I'm not sure I understand.  Both TimescaleDB and Agensgraph are built as Postgres extensions.  Above you reported an error when you tried to install Agensgraph (`CREATE EXTENSION`); the error message suggests that it's not installed in the right path, or your permissions aren't correct:
```
postgres=# CREATE EXTENSION agensgraph;
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/agensgraph.control": No such file or directory
```
My initial reaction is this is just a problem with how you installed Agensgraph and nothing about TimescaleDB.  To determine that, I was asking you to try to install Agensgraph in a Postgres installation that you haven't yet installed TimescaleDB into either.

See the build instructions here about path management:  https://github.com/bitnine-oss/agensgraph

**Comment by candysmurf** [comment]
I would like to install agensgraph as timescaledb's extension, is it possible?

**Comment by candysmurf** [comment]
yes, it worked. thanks!
