### ISSUE TITLE
ALTER DATABASE name SET TABLESPACE --> can't do that because of background timescaledb workers

### ISSUE THREAD

**Issue by aaronkaplan** [timescale/timescaledb#1078]
**Relevant system information:**
 - OS: Ubuntu 18.04.2 LTS
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 11.2 (Ubuntu 11.2-1.pgdg18.04+1)
 - TimescaleDB version (output of `\dx` in `psql`):  timescaledb  1.2.0
 - Installation method: apt install

**Describe the bug**
when moving a database to a new tablespace, the background worker keeps it from doing so, since ``alter database set tablespace ...`` requires the background worker to be disconnected from the DB.

Similar to #1043

**To Reproduce**
1. psql template1
2. ``ALTER DATABASE name SET TABLESPACE new_tablespace``
3. See the error message, that there is still one connected client, it can't move the DB to a new tablespace
4. Restart postgresql without timescaledb background worker, try (2) again. It works now.

**Expected behavior**
Similar to #1043 it should stop the background worker for the time that the DB is moved to a new tablespace, then resume again. TBD... but that's probably what a postgresql DBA would expect.

**Actual behavior**
Could not move a DB to a new tablespace

**Comment by quetz** [comment]
Same problem if one tries to do `CREATE DATABASE ... WITH TEMPLATE existing_timescale_db;`

**Comment by mfreed** [comment]
Thanks for the continued reports @aaronkaplan @quetz .  If you find another other like issues, please do let us know!
