### ISSUE TITLE
TimescaleDB Background Worker Launcher open transaction

### ISSUE THREAD

**Issue by kmsarabu** [timescale/timescaledb#1087]
The TimescaleDB Background Worker Launcher keeps the transaction open indefinitely, preventing the vacuum process from purging removable rows. We are using timescaledb version 0.12.1 and the database version 10.3

testdb=#  select pid, application_name, xact_start, wait_event_type, wait_event, state from pg_stat_activity order by xact_start asc limit 1;
  pid   |            application_name            |          xact_start           | wait_event_type | wait_event |        state
        
--------+----------------------------------------+-------------------------------+-----------------+------------+-------------
--------
 188173 | TimescaleDB Background Worker Launcher | 2019-02-09 10:25:09.101302-05 | Extension       | Extension  | 

testdb=# vacuum full verbose scott.db_logs ;
INFO:  vacuuming "scott.db_logs"
INFO:  "machine_logs": found 0 removable, 22492309 nonremovable row versions in 143079 pages
DETAIL:  22464878 dead row versions cannot be removed yet.
CPU: user: 59.19 s, system: 4.31 s, elapsed: 67.63 s.
VACUUM

**Comment by davidkohn88** [comment]
Hi there @kmsarabu, if you restart the database does the BGW launcher end up in the same state? And also Also we have made significant bug fixes to the launcher since v0.12.1, so you might just want to update to the latest version and see if that fixes it.

**Comment by mfreed** [comment]
Hi @kmsarabu Following up to see if you continue to see any issues in a newer version of Timescale (e.g., 1.2.2)
