### ISSUE TITLE
Backup and Restore does not working

### ISSUE THREAD

**Issue by tobernguyen** [timescale/timescaledb#109]
This is the error log when I tried to restore from the backup of my timescaledb:

```
postgres=# CREATE DATABASE coin;
CREATE DATABASE
postgres=# \c coin
You are now connected to database "coin" as user "postgres".
coin=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE EXTENSION
coin=# ALTER DATABASE coin  SET timescaledb.restoring='on';
ALTER DATABASE
coin=# \! pg_restore -d coin -U postgres coin.bak
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 204; 1259 17702 TABLE _hyper_4_103_chunk postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  function get_partition_for_key(text, integer) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
    Command was: CREATE TABLE _hyper_4_103_chunk (
    CONSTRAINT partition CHECK (((get_partition_for_key(symbol, 32768) >= '0'::smallint) A...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "_hyper_4_103_chunk" does not exist
    Command was: ALTER TABLE _hyper_4_103_chunk OWNER TO postgres;


pg_restore: [archiver (db)] Error from TOC entry 205; 1259 17712 TABLE _hyper_4_104_chunk postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  function get_partition_for_key(text, integer) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
    Command was: CREATE TABLE _hyper_4_104_chunk (
    CONSTRAINT partition CHECK (((get_partition_for_key(symbol, 32768) >= '0'::smallint) A...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "_hyper_4_104_chunk" does not exist
    Command was: ALTER TABLE _hyper_4_104_chunk OWNER TO postgres;

....
(many many more similar lines)
```

My first attempt I didn't enter `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` but the log was exactly same as above.

**Comment by olofr** [comment]
This seems to be a version upgrade problem. Could it be that the db is dumped at < 0.1.0 and the restore db is at 0.0.12 or 0.1.0 ? In that case you need to use the method to migrate from another postgres (http://docs.timescale.com/getting-started/setup/migrate-from-postgresql#different-db) although the first step should be `pg_dump --schema-only --schema=public -f old_db.bak old_db`.  We strongly suggest moving to 0.1.0 as that supports future upgrades between versions. Please let us know if this solves your issue. Sorry for the inconvenience.

**Comment by cevian** [comment]
Sorry, I just realized that if you are dumping a hypertable `foo` the "2. Backing up Data to CSV" step in http://docs.timescale.com/getting-started/setup/migrate-from-postgresql#different-db should read: `psql -d old_db -c "\COPY (SELECT * FROM foo) TO old_db.csv DELIMITER ',' CSV"`

**Comment by tobernguyen** [comment]
@olofr Thanks for your response, I use the same version (latest version) for both instances. According to your suggestion, It seems that I should back the schema `public` only instead of backing up every schema right? However the backup and restore guide in here is misleading http://docs.timescale.com/api#backup. I followed exactly what it said and it does not work 😂 

@cevian Thanks, I think your method will work as that method reproduces the normal way we insert new records to timescaledb.

**Comment by olofr** [comment]
Are you still having issues @tobernguyen or did @cevians suggestion solve it ? If it still
doesn't work, could you please post the output of \dx from both machines ?

**Comment by tobernguyen** [comment]
@olofr I didn't have time to check @cevian suggestion, I just re-insert data programmatically. But I believe @cevian method is the same as my method. You can close this issue anytime.
