### ISSUE TITLE
Bug in ordered append optimization

### ISSUE THREAD

**Issue by nbouscal** [timescale/timescaledb#1090]
**Relevant system information:**
 - OS: Ubuntu 18.04.2
 - PostgreSQL version (output of `postgres --version`): 11.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.2.1
 - Installation method: apt install

**Describe the bug**
In some conditions, the query planner creates a very bad plan for the query below, such that the query never completes. This is on a brand new instance, with the data loaded in via `\copy` from a CSV. The `assets` table has 2901 rows, and the `fairs` table has 159,968,136 rows in six child tables. The `fairs` data is very unevenly distributed across assets, with the most common assets having >10 million entries and the least common having a few hundred. I worked through the issue on Slack with David Kohn, and found that disabling the ordered append optimization fixed the problem. We also found that adding a row that made a new chunk beyond the current leading one fixed it too, without requiring disabling the optimization. That means this issue is fortunately no longer a blocker for us.

Two aspects of the query plan differ across the test conditions: whether it uses an Append or a Merge Append, and whether it uses a Filter or an Index Cond on the most recent child table. The latter causes the performance issue; that child table has 18,124,280 rows, so running a filter on it for each row of the `assets` table takes a very long time.

**Query**
```sql
select assets.id, s.fair
from assets
left join lateral (
        select fair from fairs f
        where f.asset_id = assets.id
        order by f.ts desc
        limit 1
) s on true;
```

**Explains**

Default query, no analyze (because it would never complete): https://explain.depesz.com/s/sMj4
With `timescaledb.enable_ordered_append = false`: https://explain.depesz.com/s/Rbb
On our old Timescale v0.10.0 instance: https://explain.depesz.com/s/l8CM
After adding a new row to create a new child table: https://explain.depesz.com/s/er1y

**Comment by svenklemm** [comment]
@nbouscal do you still get the weird plan after running analyze?

**Comment by nbouscal** [comment]
Yes, I ran analyze, and again with stats set up to 5000 just in case. Also
I restarted Postgres after the analyze, so it shouldn’t be any kind of
weird plan caching or anything.
