### ISSUE TITLE
When sharding data to different pgserver can use in production?

### ISSUE THREAD

**Issue by naughtyGitCat** [timescale/timescaledb#1092]
Is this funcition in a schedule

**Comment by mfreed** [comment]
@naughtyGitCat Sorry, I'm not quite sure I understand what you are asking.

**Comment by naughtyGitCat** [comment]
sorry for poor English, When we can shard timescaleDB data to different postgres instance

**Comment by mfreed** [comment]
The currently available version of TimescaleDB uses a single primary.  We're actively working on a version that supports scale-out sharding, and should be making more announcements over the coming months.

**Comment by btstream** [comment]
Will this scale-out sharding solution be released to OSS version?
