### ISSUE TITLE
Empty debian oss packages

### ISSUE THREAD

**Issue by marco44** [timescale/timescaledb#1093]
**Relevant system information:**
 - OS: debian stretch
 - PostgreSQL version Debian 10.7-1.pgdg90+1
 - TimescaleDB version : couldn't get there :)

Installation method: apt install

I'm trying to install the OSS version. The oss packages seem empty:
```
root@server-0 ~# dpkg -L timescaledb-oss-postgresql-10
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/timescaledb-oss-postgresql-10
/usr/share/doc/timescaledb-oss-postgresql-10/changelog.gz
/usr/share/doc/timescaledb-oss-postgresql-10/copyright
root@server-0 ~# dpkg -L timescaledb-oss-1.2.1-postgresql-10 
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/timescaledb-oss-1.2.1-postgresql-10
/usr/share/doc/timescaledb-oss-1.2.1-postgresql-10/changelog.gz
/usr/share/doc/timescaledb-oss-1.2.1-postgresql-10/copyright
```

So of course the create extension fails with 
```
create extension timescaledb ;
ERROR:  extension "timescaledb" has no installation script nor update path for version "1.2.1"
```

Am I missing a package (I don't see which), or is something wrong with packaging ?

Regards

**Comment by RobAtticus** [comment]
It seems strange that the package is empty. But you do also need the loader package `timescaledb-loader-postgresql-10` for it to work. Will investigate why those packages are empty however.

**Comment by marco44** [comment]
I see that I forgot to mention… I have the timescaledb-loader-postgresql-10 package installed. And get 
```
mydb=> create extension timescaledb ;
ERROR:  extension "timescaledb" has no installation script nor update path for version "1.2.1"
```
Because I don't have the sql scripts for the extension

**Comment by RobAtticus** [comment]
Hi @marco44 -- thanks for the report. It does appear that due to a build misconfiguration our Debian OSS packages were missing the files they need to work :) I have re-built most of these and uploaded them to package cloud for the latest version (1.2.2). So if you want to try with that, it should work.

**Comment by marco44** [comment]
Hi, good news. Will do first thing monday morning :)

**Comment by marco44** [comment]
Done. It works. Thanks a lot
