### ISSUE TITLE
Timescale hypertables don't support ON CONFLICT ON CONSTRAINT upsert statement (breaking Hasura compatibility)

### ISSUE THREAD

**Issue by waterdrop01** [timescale/timescaledb#1094]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version: PostgreSQL 11.1
 - TimescaleDB version: 1.2.1
 - Installation method: docker `timescale/timescaledb:1.2.1-pg11`

**Describe the bug**
Here is my schema:
```sql
CREATE TABLE data (
    "timestamp" timestamp with time zone NOT NULL,
    "uuid" uuid NOT NULL
);

ALTER TABLE ONLY data
    ADD CONSTRAINT data_pkey PRIMARY KEY ("uuid", "timestamp");

SELECT create_hypertable('data', 'timestamp');
```

**To Reproduce**
Run this SQL
```sql
INSERT INTO "data" ( "timestamp", "uuid" ) VALUES ( "2019-03-06T16:46:46.988Z", "9db6dbe1-cd14-1d17-38c0-4d4a36679fd6" ) ON CONFLICT ON CONSTRAINT "data_pkey" DO NOTHING RETURNING *
```

**Expected behavior**
Expected to correctly insert/upsert data without error, as it is doing with **PostgreSQL 10.6** and timescale 1.2.1 (docker `timescale/timescaledb:1.2.1-pg10`).

**Actual behavior**
Postgres throws the following error: 
```
ERROR:  hypertables do not support ON CONFLICT statements that reference constraints
HINT:  Use column names to infer indexes instead.
```

Note: mention of my error in this file: https://github.com/timescale/timescaledb/blob/master/test/expected/upsert.out

**Comment by waterdrop01** [comment]
Note: Just had a feedback from the folks over at Hasura: https://github.com/hasura/graphql-engine/issues/1711#issuecomment-470429671

**Comment by waterdrop01** [comment]
note: It may not actually come from PG version, but only from Timescaledb version.

**Comment by waterdrop01** [comment]
Not being able to reference a constraint by its name is problematic. Is it long term design, or short term workaround?

having a feedback from Timescaledb team on this issue would be very valuable,

Thank you! :)

**Comment by waterdrop01** [comment]
Hi Timescaledb team,

I understand you may have other priorities, but any chance to get some feedback on this?

Thank you!

**Comment by j0h** [comment]
@waterdrop01 When using Postgres, it is preferred that you infer indexes. Please see the TIP section: https://www.postgresql.org/docs/11/sql-insert.html#SQL-ON-CONFLICT

> It is often preferable to use unique index inference rather than naming a constraint directly using ON CONFLICT ON CONSTRAINT constraint_name. Inference will continue to work correctly when the underlying index is replaced by another more or less equivalent index in an overlapping way, for example when using CREATE UNIQUE INDEX ... CONCURRENTLY before dropping the index being replaced.

My suggestion would be that you use `... ON CONFLICT ("uuid", "timestamp")...` instead.

**Comment by waterdrop01** [comment]
Thanks @j0h for your input. Hi @dianasaur323 :)

Would that make sense one of you go [on this thread](https://github.com/hasura/graphql-engine/issues/1711) and share your opinion with the hasura team on how to fix this issue? Bringing back compatibility between Hasura and Timescale is a big thing for both projects...

and It's been broken for almost 5 months :(

**Comment by dianasaur323** [comment]
Hi @waterdrop01 :) 

Thanks for bringing this up. We know the Hasura guys. Let me ping the person on our team who has the best relationship with them to see what's going on here.

**Comment by sulliwane** [comment]
Thanks a lot @dianasaur323, much appreciated. Looking to move forward on this question, and let me know if I can be of any help

**Comment by waterdrop01** [comment]
Thanks a lot @dianasaur323, much appreciated. Looking to move forward on this question, and let me know if I can be of any help (sorry, just mixed pro and personal github account ;)

**Comment by bboule** [comment]
hey @waterdrop01 thanks for sticking with this, I need to have a few conversations with the team, but I hope to get back with you and the hasura team as quickly as possible around how we proceed!!

**Comment by waterdrop01** [comment]
thanks @bboule. Please keep me updated, I'd love to see this issue fixed one way or another and I could help with testing if needed.

**Comment by waterdrop01** [comment]
Hi @bboule, did you have the chance to talk to the team over at Hasura about this issue, and agree on a fix? Thanks

**Comment by bboule** [comment]
hey @waterdrop01 apologies for the delayed response, we have looked at this and agree this is something we could fix, we are in the process of slotting this to a release (via our normal process).  Will need a little more time before we can discuss the when, but please stay tuned I will update you as soon as possible.

**Comment by waterdrop01** [comment]
sounds great @bboule! Can't wait to have this fixed ;) Again, would be happy to test if needed

**Comment by waterdrop01** [comment]
Hi @bboule, any progress on a fix for this issue?

**Comment by waterdrop01** [comment]
Hi @bboule , any update on this issue? thanks

**Comment by waterdrop01** [comment]
Hi @bboule and @dianasaur323, hope you are well. Do you still plan to fix for this issue?

**Comment by waterdrop01** [comment]
`timescale/timescaledb:1.7.1-pg12` and `asura/graphql-engine:v1.2.1` are still not working correctly together :(
```
2020-05-26 20:39:36.663 UTC [1589] ERROR:  hypertables do not support ON CONFLICT statements that reference constraints
2020-05-26 20:39:36.663 UTC [1589] HINT:  Use column names to infer indexes instead.
```

**Comment by nicolavs** [comment]
hi, any update would be awesome..

**Comment by waterdrop01** [comment]
Hi @bboule and @dianasaur323, hope you are well. Do you have a fix in the pipe for this issue? 

As per [this pull request](https://github.com/timescale/timescaledb/commit/23f9d3c0b0399c7bd2c365a2d51601b0f3b96ba4), @erimatnor wrote:
![Screenshot from 2020-09-21 15-04-14](https://user-images.githubusercontent.com/47316824/93770059-fc928a00-fc1b-11ea-8ad5-2d54c6ee84fa.png)

Being able to support upserts using `ON CONFLICT ON CONSTRAINT` would bring back compatibility with Hasura and make timescaledb friendlier to use.

This issue has been opened for 18 months, with little to no visibility on the community side :disappointed:

**Comment by erimatnor** [comment]
Hi @waterdrop01. Thanks for your continued interest in this issue. To quite honest, we aren't actively working on this limitation right now, due to other priorities set mostly be level of interest in particular user requests. FWIW, we are happy to accept community contributions to remove limitations like this. In the meantime, let me research how much of an effort it would take to fix this.

**Comment by waterdrop01** [comment]
Thanks @erimatnor for your feedback, appreciated. 

I'd love to contribute this fix, but my understanding of SQL and C are too limited I fear :(

I rephrased the issue's title. In fact It's more than just Hasura, all the other Graphql/pg middlewares (Prisma, Postgraphile, etc...) relying on constraints names won't work properly with Timescaledb because of this limitation.

**Comment by sulliwane** [comment]
Very much interested in having issue this fixed as well! Thanks @erimatnor @bboule @RobAtticus for your input :)

**Comment by ondrejspilkaABB** [comment]
Hello, any resolution to this issue?

**Comment by waterdrop01** [comment]
Hello, @erimatnor @dianasaur323 , did you guys plan to release a fix to this bug?

It's soon going to be **2 years** this issue is open. And the [official documentation page](https://docs.timescale.com/latest/using-timescaledb/writing-data#upsert) mentions:

![Screenshot from 2021-02-27 11-07-32](https://user-images.githubusercontent.com/47316824/109384276-02d41300-78ec-11eb-89f1-4f9ae193829d.png)

Your help would be much appreciated <3 <3 <3

**Comment by erimatnor** [comment]
@waterdrop01 thank you for the interest in this feature. This is still on our list of limitations that we'd like to address. However, we need to weigh this against other priorities and features that people are asking for. 

Now that 2.0 is out, with major new functionality, we will hopefully be able to start looking at the long tail of things like this. Community contributions are of course always welcome

**Comment by iosifnicolae2** [comment]
I'm having also this problem, any workaround to fix this problem temporarily?

**Comment by TAJD** [comment]
I've encountered this issue whilst moving my preexisting data pipelines over to our new TimescaleDB enabled database. 

I get an error: `ON CONFLICT DO UPDATE not supported on distributed hypertables`. This would be quite a useful feature for us and I look forwards to it being implemented in the future.

**Comment by waterdrop01** [comment]
@erimatnor Hey Erik, will Timescale decide to prioritize this feature this year?

**Comment by majozv** [comment]
@erimatnor Hi Erik, UPSERT on distributed hypertables would be useful for us even with limitations like not supported updates on "partitioning" columns...

**Comment by erimatnor** [comment]
@waterdrop01 @majozv Realize we've been silent on this one, but it's due to focusing on other priorities. We have many requests from users so we need to balance priorities :)

FWIW, though, we just started discussing if there's something we can do to make this work, the effort involved, etc. We'll keep you posted.

**Comment by ondrejspilkaABB** [comment]
I have to agree two years is quite a time for such an impactful small functionality.
But I also understand you have full hands with 2.0 release...

**Comment by waterdrop01** [comment]
Hi @NunoFilipeSantos, would you mind sharing the internal discussions regarding this issue? Thanks

**Comment by bilby91** [comment]
Looking forward to any update on this feature! We need this feature very badly :)

**Comment by moodgorning** [comment]
I would like to add some weight to this, We are currently running hasura on top of timescale and because of this limitation we have a request error rate of over 30%. Sur to the nature of our use case we can't avoid sending duplicate information to our DB, so what should be an on conflict update/ignore is producing countless errors per second.  
It would be very very to have this fixed/enhanced

**Comment by iroussos** [comment]
As of recently, TimescaleDB 2.8 hypertables support the ON CONFLICT ON CONSTRAINT UPSERT statement ([release notes](https://github.com/timescale/timescaledb/releases/tag/2.8.0)). This was our 3rd most requested feature to date, and we are thrilled to have it released.

I’m one of the PMs that worked on this release and I was wondering if you were able to give TimescaleDB 2.8 a try? If so, it would be great to get your feedback on this new feature and if it solved your problem.

**Comment by CaptainMack** [comment]
Just chiming in to say thank you @iroussos - I'll give TimescaleDB 2.8 a try!
