### ISSUE TITLE
time_bucket & time_bucket_gapfill return 8 days of data for 7 day interval

### ISSUE THREAD

**Issue by iabtyagi** [timescale/timescaledb#1099]
- OS: Alpine Docker
 - PostgreSQL version: 9.6
 - TimescaleDB version):  1.2.0
 - Installation method: Docker (timescale/timescaledb:latest-pg9.6)

I am trying to issue the following query (it is very similar to the query given as example for [time_bucket_gapfill](https://docs.timescale.com/v1.2/api#time_bucket_gapfill-examples))-

```
SELECT
    time_bucket_gapfill('1 day', time, now() - interval '7 days', now()) AS one_day,
    country,
    chart_type,
    genre_id,
    max(rank)
FROM ranks
WHERE
    entity_id='1196015787' AND
    country='US' AND
    time > now() - interval '7 days'
GROUP BY one_day, country, chart_type, genre_id;
```

Basically buckets of 1 day of the data from last 7 days. 
However, I am getting 8 buckets in response:

```
        one_day         | country | chart_type | genre_id | max 
------------------------+---------+------------+----------+-----
 2019-03-01 00:00:00+00 | US      |          0 |     6001 | 122
 2019-03-02 00:00:00+00 | US      |          0 |     6001 | 168
 2019-03-03 00:00:00+00 | US      |          0 |     6001 | 174
 2019-03-04 00:00:00+00 | US      |          0 |     6001 | 198
 2019-03-05 00:00:00+00 | US      |          0 |     6001 | 198
 2019-03-06 00:00:00+00 | US      |          0 |     6001 | 186
 2019-03-07 00:00:00+00 | US      |          0 |     6001 | 183
 2019-03-08 00:00:00+00 | US      |          0 |     6001 | 125
(8 rows)
```

Same response is received if I use `'1 week'` instead of `'7 days'` or if I use time_bucket `time_bucket('1 day', time) AS one_day`

The `time` column is of `TIMESTAMPTZ` type.

I expected it to return 7 rows.

**Comment by svenklemm** [comment]
if you use now() your bucket will start in the middle of the day and thats why it will return 8 days with the first and the last bucket not containing a complete day, if you want only 7 full days you need to adjust start parameter and where clause similar to this:

```
WHERE time > time_bucket('1d',now() - interval '7 days')

**Comment by iabtyagi** [comment]
I see. And, it makes sense. Thanks. The time_bucket_gapfill example doesn't make it clear.
However, I am still getting the same response.
Here is what I tried:

where clause same as suggested above:
`time > time_bucket('1d', now() - interval '7 days')`

and select:
`time_bucket('1 day', time, TIMESTAMPTZ '2019-03-03 00:00:00') AS one_day,`

Although, I am not sure now if I am using the origin parameter correctly. 

I do want my buckets to start at the start of the day. In fact, even more desirable will be that the ongoing day gets omitted. i.e. if today is 8th, the response contains 7 full days from the 1st to the 7th.

**Comment by iabtyagi** [comment]
Ok, I got it now.
Here is what works:

where clause as:
`WHERE time > time_bucket('1d', now() - interval '7 days') AND time < time_bucket('1d', now())`


select, if using time_bucket:
`SELECT time_bucket('1 day', time) AS one_day,`

select, if using time_bucket_gapfill:
`SELECT
    time_bucket_gapfill('1 day', time, date_trunc('day', now() - interval '7 days'), date_trunc('day', now())) AS one_day,`

Closing the issue but would appreciate a comment on whether it is the right way to do it.

**Comment by bodypumper** [comment]
Is time_bucket_gapfill related to time zone?
I used the millisecond stamp as the query condition, and the same problem occurred.
