### ISSUE TITLE
Ultra Low Latency | High Throughput |  Fast / Big Data | HPC | Real Time | Distributed Applications

### ISSUE THREAD

**Issue by sirinath** [timescale/timescaledb#11]
Is it possible to add optimisations where this could outperform DBs like https://www.onetick.com/, https://kx.com/, https://www.pipelinedb.com/

**Comment by mfreed** [comment]
We are continuing to add optimizations (both architecturally and via the query planner) to improve TimescaleDB's performance.  For example, this week @cevian added a new optimization for "merge appends" of time aggregates.  That's some query like:

```
SELECT date_trunc('minute', time) as minute, max(usage) FROM data 
GROUP BY minute 
ORDER BY minute DESC 
LIMIT 5
```
  
After his optimization, query performance improved by ~450% compared to Postgres' own query planner.  We'll probably write a post about this type of optimization in the next couple weeks.

Anyway, all I mean to say is that we're working on both performance optimizations and time-series specific functionality, so keep an eye out on future releases.

**Comment by mfreed** [comment]
On a related note, the above query is interesting because while it seems quite natural, some time-series databases don't support ORDER BY operations after GROUP BYs.
