### ISSUE TITLE
Creating millions of chunks in hypertable conversion transaction crashes db

### ISSUE THREAD

**Issue by bhuesemann** [timescale/timescaledb#1102]
**Relevant system information:**
 - OS: x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
Running on Win10 in a Virtualbox VM

 - PostgreSQL version (output of `postgres --version`): PostgreSQL 11.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.2.1
 - Installation method: vagrant (scripts attached)

**Describe the bug**
Conversion of a table into a hypertable using SQL from a JDBC DB Client yields a SQL error and database crash. After this the database is restarting, recovering and available. 

**To Reproduce**
1. Create Table
```
create table bigtable as 
select 
  cast (generate_series as bigint) id
  , trunc(generate_series / 1000) id1
  , mod(generate_series, 1000) id2
  , 'bigtable row: ' || generate_series as row_desc
from 
generate_series(1,1e7);
```
2. Migrate to hypertable
```
SELECT create_hypertable('bigtable', 'id', migrate_data => true, chunk_time_interval => 1);
```
**Expected behavior**
Conversion should finish appropriately. If the table is large it should process the migration in chunks without out of memory issues.

**Actual behavior**
Execution of step 2 aborts with error message:

```
SQL Error [57P03]: FATAL: the database system is in recovery mode
  FATAL: the database system is in recovery mode
  FATAL: the database system is in recovery mode
```
Database is crashing and restarts with recovery. The recovery is ending successfully and the database is available again without having the table migrated.

**Logs**
Log output: postgresql-Tue.log
```
2019-03-12 09:13:25.838 CET [6213] FATAL:  the database system is in recovery mode
2019-03-12 09:13:25.845 CET [6214] FATAL:  the database system is in recovery mode
2019-03-12 09:13:25.919 CET [6215] FATAL:  the database system is in recovery mode
2019-03-12 09:13:25.927 CET [6216] FATAL:  the database system is in recovery mode
2019-03-12 09:13:32.863 CET [6209] LOG:  database system was not properly shut down; automatic recovery in progress
2019-03-12 09:13:32.868 CET [6209] LOG:  redo starts at 0/17DE420
2019-03-12 09:14:15.441 CET [6209] LOG:  redo done at 0/7CFFFF88
2019-03-12 09:14:15.441 CET [6209] LOG:  last completed transaction was at log time 2019-03-12 09:12:34.219298+01
2019-03-12 09:14:23.813 CET [6111] LOG:  database system is ready to accept connections
2019-03-12 09:14:23.813 CET [6222] LOG:  TimescaleDB background worker launcher connected to shared catalogs
```

**Additional context**
[install_postgres.sh.txt](https://github.com/timescale/timescaledb/files/2956204/install_postgres.sh.txt)
[install_timescale.sh.txt](https://github.com/timescale/timescaledb/files/2956205/install_timescale.sh.txt)

**Comment by davidkohn88** [comment]
So, I think the big problem here is that your chunk time interval is 1, which means 1 row per chunk, which means you're going to be creating 10million chunks in a single transaction, which is a bit high. That said, we should probably be failing more gracefully there, so we'll look into it. In general if you have fewer than a million or two rows per chunk, they're probably too small, so maybe try a chunk_time _interval of, say, 1,000,000 or so and see how it goes.

**Comment by davidkohn88** [comment]
Thanks for the detailed report though!

**Comment by bhuesemann** [comment]
As proposed bigger chunk size makes more sense and finished ok.
```
SELECT create_hypertable('bigtable', 'id', migrate_data => true, chunk_time_interval => 10000);
```

**Comment by dianasaur323** [comment]
Sounds like this has been resolved. Closing.
