### ISSUE TITLE
Last batch record missing

### ISSUE THREAD

**Issue by ropieur** [timescale/timescaledb#1103]
**Relevant system information:**
 - OS: Ubuntu 16.04.5 LTS in Docker
 - PostgreSQLversion: psql (PostgreSQL) 10.6 (Ubuntu 10.6-1.pgdg16.04+1)
 - TimescaleDB version: plpgsql | 1.0
 - Installation method: "apt install"

**Describe the bug**
Inserting a large csv file results in a table with the last record of each batch missing.

**To Reproduce**
1. Execute timescaledb-parallel-copy with a large csv file (Personally 90,000,000 records - verified with wc -l command)
2. In psql, select count(*) from 'table-name'
2a. with default --batch-size, output is 89982000
2b. with --batch-size 4000, output is 89977500
3. In psql, select * from 'table-name' where 'primray-key-name' = 'id of last record of a batch' ; returns empty

**Expected behavior**
The number of inserted records should be the same as the number of records in CSV file

**Actual behavior**
Last record of each batch is not inserted

**Comment by erimatnor** [comment]
Thanks for the bug report @ropieur. I think you might want to move this issue to the parallel-copy repository: https://github.com/timescale/timescaledb-parallel-copy

**Comment by ropieur** [comment]
Not sure I have the right to move the ticket to another repo. I don't find the "transfer" functionality explained [here](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)

**Comment by RobAtticus** [comment]
Going to close since we now have the issue here: https://github.com/timescale/timescaledb-parallel-copy/issues/17

It should be fixed in the latest release of timescaledb-tools as well.
