### ISSUE TITLE
timescaledb extension doesn't show up after installation

### ISSUE THREAD

**Issue by lobbike** [timescale/timescaledb#1118]
**Relevant system information:**
 - OS:  Windows 10 x64
 - PostgreSQL version 11.2
 - TimescaleDB version 1.2.2
 - Installation method: EDB Enterprise installation, with .exe files

**Describe the bug**
I tried to upgrade from PG 10.7 to 11.2 on my local laptop, and everything went smoothly.
Great job on the tune-app!
Installation of timescaleDB returned success! Yet I couldn't install the extension on the database. The extension didn't show up in the 'pgadmin dropdown for creating extensions' list as well.

**To Reproduce**
Tried every variation of installing, I could think of, without success.

** Solution **
Finally I moved the timescaledb related files from
C:\Program Files\PostgreSQL\11\share --> C:\Program Files\PostgreSQL\11\share\extension
et voila, that worked!

Maybe the folder configuration in PG11.2 is different as in PG 10.7? 

Thanks,
Stefan

**Comment by RobAtticus** [comment]
Interesting, thanks for the update, I'm surprised this hasn't come up before.

I will update the installer because you're right, it should be in that `extension` folder

**Comment by RobAtticus** [comment]
Hey @lobbike, I updated the releases with a fixed installer. Don't know if you feel like retrying with that but hopefully it works now.

**Comment by lobbike** [comment]
> Hey @lobbike, I updated the releases with a fixed installer. Don't know if you feel like retrying with that but hopefully it works now.

thanks @RobAtticus. I migrated all my databases back already, so won't be testing it, but I trust you did a good job.
