### ISSUE TITLE
pg_dump/pg_restore process broken or badly documented

### ISSUE THREAD

**Issue by jbulow** [timescale/timescaledb#1136]
Ubuntu 18.04 with PostgreSQL 10 and timescaledb installed according to documentation

Restoring a tar-backup results an many errors like:

pg_restore: processing data for table "_timescaledb_internal._hyper_1_27_chunk"
pg_restore: [archiver (db)] Error from TOC entry 3836; 0 28727 TABLE DATA _hyper_1_27_chunk sbo_user
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "_timescaledb_internal._hyper_1_27_chunk" does not exist

...

**Comment by mfreed** [comment]
Did you follow these instructions when performing the backup/restore?

https://docs.timescale.com/v1.2/using-timescaledb/backup

**Comment by jbulow** [comment]
Almost, I used tar format for the backup.

**Comment by mfreed** [comment]
@jbulow In particular, did you follow the steps for 
```
ALTER DATABASE tutorial SET timescaledb.restoring='on';
```
etc.  Can you post *precisely* the commands you performed for both pg_dump and pg_restore, as well as the appropriate config & info of your setup?

Please see the desired format here:  https://github.com/timescale/timescaledb/issues/new?template=bug_report.md

Thanks!

**Comment by jbulow** [comment]
The problem went away when we upgraded postgres to version 11 and to timescale 1.2 (previous v0.9) and changed backup-format to "-Fc". This defect can be closed. I will collect better details next time I report a defect.
