### ISSUE TITLE
ERROR:  could not find function "ts_bgw_db_workers_restart" in file "/usr/lib/postgresql/10/lib/timescaledb.so

### ISSUE THREAD

**Issue by tomvantilburg** [timescale/timescaledb#1137]
**Relevant system information:**
 - OS: Ubuntu 18.10
 - PostgreSQL version:
PostgreSQL 10.7 (Ubuntu 10.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit
 - TimescaleDB version 1.2.2
 - Installation method: apt install & source

I have two postgres installations, 10 and 11, but using 10 in the configuration.

Made a fresh build (including correct pg_config path) and did `ALTER EXTENSION timescaledb UPGRADE;` to go from 0.8.0 to 1.2.2 but received:
`ERROR:  could not find function "ts_bgw_db_workers_restart" in file "/usr/lib/postgresql/10/lib/timescaledb.so" `
I did a successfull `DROP EXTENSION timescaledb;`  and tried to install a new timescaledb but received the same error.

Content of /usr/lib:
```
ls /usr/lib/postgresql/10/lib/timescaledb*
/usr/lib/postgresql/10/lib/timescaledb-0.10.1.so
/usr/lib/postgresql/10/lib/timescaledb-0.11.0.so
/usr/lib/postgresql/10/lib/timescaledb-0.12.0.so
/usr/lib/postgresql/10/lib/timescaledb-0.12.1.so
/usr/lib/postgresql/10/lib/timescaledb-1.0.0.so
/usr/lib/postgresql/10/lib/timescaledb-1.0.1.so
/usr/lib/postgresql/10/lib/timescaledb-1.1.0.so
/usr/lib/postgresql/10/lib/timescaledb-1.1.1.so
/usr/lib/postgresql/10/lib/timescaledb-1.2.0.so
/usr/lib/postgresql/10/lib/timescaledb-1.2.1.so
/usr/lib/postgresql/10/lib/timescaledb-1.2.2.so
/usr/lib/postgresql/10/lib/timescaledb.so
/usr/lib/postgresql/10/lib/timescaledb-tsl-1.2.0.so
/usr/lib/postgresql/10/lib/timescaledb-tsl-1.2.1.so
/usr/lib/postgresql/10/lib/timescaledb-tsl-1.2.2.so
```
(there are no symlinks)

**Comment by mfreed** [comment]
Did you restart the database after the upgrade?

**Comment by tomvantilburg** [comment]
That was it, I did reload but not restart. Fixed it. Thanks!
