### ISSUE TITLE
Support triggers on hypertable 

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#114]

**Comment by mfreed** [comment]
Triggers supported in 0.2.0 release:

https://github.com/timescale/timescaledb/releases/tag/0.2.0

**Comment by mfreed** [comment]
Full support for `INSERT AFTER` and `INSERT BEFORE`, as well as arbitrary naming, now part of 0.3.0 release.

https://github.com/timescale/timescaledb/releases/tag/0.3.0
