### ISSUE TITLE
Restoring from backup of config file after timescaledb-tune

### ISSUE THREAD

**Issue by reubenfirmin** [timescale/timescaledb#1140]
The configuration from a timescaledb-tune on my configuration resulted in a time series query on a large table that was BRIN indexed taking twice as long. I decided that I wanted to revert the settings, which was inconvenient given that there was no configuration backup made by timescaledb-tune.

**Comment by RobAtticus** [comment]
Hi @reubenfirmin, version 0.4.0 and later of `timescaledb-tune` has a `--restore` flag that will allow you restore previous config files. These files are backed up to a temporary directory, so they may not stick around for a long time. Perhaps you could try that and see if the backup still exists?

**Comment by mfreed** [comment]
Closing this issue out, please let me know if you encounter other problems @reubenfirmin and we can re-open.
