### ISSUE TITLE
Pg_prometheus disk usage is too large

### ISSUE THREAD

**Issue by gjpei2** [timescale/timescaledb#1162]
hi~
i am using timescale as my prometheus remote storage.my prometheus scrape_interval=10s
and every interval will have 60k metrics about 6MB ,but when i run it 20h ,it has 60GB data in my disk .i want know how can i reduce the disk occupation.
Please accommodate my English is poor

looking forward to your reply

**Comment by gjpei2** [comment]
at the same time ，prometheus local storage just use 1.3GB,so ,if timescale could compress the data like prometheus local storage? or has other way to reduce  the disk occupation. thanks!

**Comment by gjpei2** [comment]
prometheus.yml config is like
remote_write:
    - url: "http://xxx:9201/write"
      remote_timeout: 100s
      queue_config:
        capacity: 30000000
        max_shards: 2000
        max_samples_per_send: 10000
        batch_send_deadline: 3


postgres.conf
wal_buffers = 16MB	
max_wal_size = 8GB
min_wal_size = 4GB
random_page_cost = 1.1			# same scale as above
effective_cache_size = 193255MB
default_statistics_target = 500	# range 1-10000

**Comment by gjpei2** [comment]
in the base folder ,i find lots of data like 

1.1G	./17144.3
1.1G	./17144.4
419M	./17144.5
1.1G	./17145
1.1G	./17145.1
1.1G	./17145.2
1.1G	./17145.3
1.1G	./17145.4
1.1G	./17145.5
1.1G	./17145.6
1.1G	./17145.7
984M	./17145.8
1.1G	./17342
1.1G	./17342.1
1.1G	./17342.10
1.1G	./17342.11
1.1G	./17342.12
154M	./17342.13
1.1G	./17342.2
1.1G	./17342.3
1.1G	./17342.4
1.1G	./17342.5
1.1G	./17342.6
1.1G	./17342.7
1.1G	./17342.8
1.1G	./17342.9
3.4M	./17342_fsm
1.1G	./17346
1.1G	./17346.1
1.1G	./17346.2
1.1G	./17346.3

**Comment by mfreed** [comment]
We often recommend running TimescaleDB on top of ZFS; users often see 3-9x compression.

**Comment by gjpei2** [comment]
thanks.
