### ISSUE TITLE
DETAIL:  It is not possible to turn tables that use inheritance into hypertables.

### ISSUE THREAD

**Issue by qub01** [timescale/timescaledb#1166]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
rhel7
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
11.2
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
1.1.1
 - Installation method: [e.g., "using Docker", "apt install", "source"]
source
**Describe the bug**

**To Reproduce**
1.1) following migration manual and use option '--schema-only':  pg_dump --schema-only -f old_db.bak old_db
1.2) when it comes to the step "SELECT create_hypertable('conditions', 'time');" the error in the subject would show up
1.3) If the user keeps going, it would failed at the "psql -d new_db -c "\COPY conditions FROM old_db.csv CSV" complaining that 
```
ERROR:  invalid INSERT on the root table of hypertable "conditions"
HINT:  Make sure the TimescaleDB extension has been preloaded.
```
https://docs.timescale.com/v1.2/getting-started/migrating-data

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

when I remove the --schema-only option when using pg_dump to dump the whole database, everything works ok for data migration.

**Screenshots**

**Additional context**

**Comment by mfreed** [comment]
Hi @qub01 I'm having a little hard time explaining what you are trying to do?  Are you trying to migrate a DB using inheritance to a hypertable?  

A common approach people have for such migrations is to dump out the data from your existing table as a CSV, then reload the data into a hypertable using COPY/https://github.com/timescale/timescaledb-parallel-copy.  Have you tried that?

**Comment by qub01** [comment]
@mfreed Thanks Mike for the reply. I can migrate data by using timescaledb-parallel-copy. What I want to say is there might be an error in the official document as I am following the instruction of the manual (it does mention using psql to copy data as an alternative.

Thanks,
Ben

**Comment by mfreed** [comment]
@qub01 But I assume the error only occurs when somebody migrating from an existing table with inheritance, rather than a standard one?  Is that your point about the documentation?   Thanks!

**Comment by qub01** [comment]
@mfreed Yes, Mike. I am talking about the documentation. It does not write about such info. People might migrate data from timescaledb to timescaledb and see such error.

**Comment by codegrafix** [comment]
I got the same error following the documentation. Any hints?

**Comment by erimatnor** [comment]
The error messages are there to help the user understand the limitations of creating a hypertable. We will also tweak the documentation to clarify. https://github.com/timescale/docs.timescale.com-content/pull/644
