### ISSUE TITLE
SQL question:  Displaying time of max of temperature

### ISSUE THREAD

**Issue by scls19fr** [timescale/timescaledb#1168]
Hello,

I'm looking for a very simple SQL query to get maximum temperature and time when this temperature have been reached.

I had a look at documentation https://docs.timescale.com/v1.2/using-timescaledb/reading-data to find such a query but I haven't found a similar case.

I tried

    SELECT time, MAX(temperature) AS temperature_max FROM data_evt WHERE time>='2019-04-17'

But it raises an exception

    ERROR: «column data_evt.time» must appear in the GROUP BY clause or be used in an aggregate function

Any idea? 

I will provide if you think also that it can improve documentation a pull request.

Kind regards

**Comment by mfreed** [comment]
Hi @scls19fr in SQL, `max` is a function that operates on a group as an aggregation function, which is what the error is about (it's not specific/unique to TimescaleDB).

Try this instead:

```
SELECT time, temperature AS temperature_max FROM data_evt WHERE time>='2019-04-17'  ORDER BY temperature DESC LIMIT 1
```

**Comment by scls19fr** [comment]
Thanks @mfreed but I have found that SQL subquery fit better to my need (I'm not a SQL expert)

```sql
SELECT time, temperature as temperature_max FROM data_evt
WHERE
  temperature = (
  SELECT MAX(temperature)
  FROM data_evt
  WHERE time>='2019-04-17'
) ORDER BY time DESC LIMIT 1;
```

it returns maximum temperature and last time when it was reached.

I think this is a quite common request, especially for displaying information on dashboards.

Do you want me to add this to documentation?

Maybe at
https://docs.timescale.com/v1.2/using-timescaledb/reading-data#select
To more advanced SQL queries:
(before 
```
-- Information about each 15-min period for each location
-- over the past 3 hours, ordered by time and temperature
```
)

```sql
-- Return maximum temperature and time when it was reached
-- over the past 3 hours
SELECT 
  time, 
  temperature as temperature_max 
FROM 
  conditions 
WHERE 
  temperature = (
    SELECT MAX(temperature) 
    FROM conditions 
    WHERE time > NOW() - interval '3 hours'
  ) 
ORDER BY time DESC 
LIMIT 1;
```

**Comment by scls19fr** [comment]
PR for doc available at https://github.com/timescale/docs.timescale.com-content/pull/145

**Comment by perrygeo** [comment]
You can use `ORDER BY value DESC` to get the row with highest value without needing any aggregation or subqueries.

```
SELECT time, value
FROM data_evt
WHERE time > now() - interval '3 hours'
ORDER BY value desc
LIMIT 1;
```

@scls19fr - does this work for your case?

**Comment by scls19fr** [comment]
I won't say it doesn't work... it's just less obvious (but probably more efficient... but I haven't perform any benchmark)
