### ISSUE TITLE
Feature request: Materialized Hyperviews

### ISSUE THREAD

**Issue by narc-Ontakac2** [timescale/timescaledb#1180]
We are running Timescaledb and can do queries on a weeks data with the given hardware. To to long term reports we would like to have materialized views on the hypertable, that are themselves hypertables. These would best be by refreshable by chunk or autorefresh when the chunk is finished..

**Comment by mfreed** [comment]
Hi @narc-Ontakac2 : Thanks for the interest. We'll be releasing support for in-database continuous aggregations in v1.3 -- exposed as materialized hypertables -- which should be released within the next few weeks. Code should hit master branch within a few days.

**Comment by Speedkore** [comment]
Hi, i'm new to Timescaledb and i was wondering if i create a materialized view of an hypertable, i would lose the benefits of using hypertables quering the view instead the hypertable, then i found this issue in google. So right now, there's no point in doing it as i understand until 1.3

**Comment by mfreed** [comment]
Release - https://github.com/timescale/timescaledb/releases/tag/1.3.0
Overview Docs - https://docs.timescale.com/v1.3/using-timescaledb/continuous-aggregates
Tutorial - https://docs.timescale.com/v1.3/tutorials/continuous-aggs-tutorial
