### ISSUE TITLE
Question: Views over hyper tables

### ISSUE THREAD

**Issue by brettwooldridge** [timescale/timescaledb#1185]
Not sure this is the best place for a question, but I figured it would be easiest for future users to find the answer.

My company is looking to use TimescaleDB in a monitoring product.  However, we have a requirement that the user be able to select from one of several retention policies for a given monitor.  For example, ``3 months``, ``6 months``, ``12 months``, ``24 months``.

Our current thinking is that based on the selected "retention policy" we can store the monitor's data into a different hyper-table, one for each of the pre-defined durations (these are not user-definable durations, but presets).

The reason for separate hyper-tables is obvious, I think, being able to drop chunks from each of the tables based on the retention policy.

However, in terms of abstraction, we would like to be able to query across the separate hyper tables, all of which have identical schemas, as if they were a single table.

It seems that ``CREATE VIEW`` is an obvious candidate for this.

My question is, is this a common pattern?  Would a view work as expected in this case?  And lastly, what are the performance implications in terms of query performance?  For example, would using a view confuse the query planner/optimizer in any way?

**Comment by Muyoo** [comment]
Our situation is similar as yours. And we just create views over the hypertables, a hypertable joins a normal table or a hypertable joins anther hypertable. Fortunately, it works well for now.
About the query performance, in my opinion, ```EXPLAIN``` may help you and you will see PostgreSQL returns you a plan with the chunk tables.

Have a nice day!

**Comment by brettwooldridge** [comment]
@Muyoo Thanks for the reply.  We're going to go ahead with that approach.
