### ISSUE TITLE
Use of equals in docs

### ISSUE THREAD

**Issue by abrkn** [timescale/timescaledb#119]
http://docs.timescale.com/api#select

```
-- Number of data entries written in past 12 hours
SELECT COUNT(*) FROM conditions
  WHERE time = NOW() - interval '12 hours';
```

Why is `time = now() ...` used and not `time >= now() ...` used? If this the behavior, then a note explaining this would be helpful!

**Comment by mfreed** [comment]
That's a total documentation bug.  Will be fixed in the next documentation release.  Thanks for catching and bringing up.

**Comment by mfreed** [comment]
This is fixed in the latest release of the docs.  Thanks again.
