### ISSUE TITLE
How can the data collected by IOT automatically generate the data of 15 minutes, hours, days and weeks?

### ISSUE THREAD

**Issue by ghd258** [timescale/timescaledb#1202]
IOT collects data such as electricity meters, water meters and natural gas. Some of these data are cumulative measurements in time intervals, and some are instantaneous values. How to automatically generate 15 minutes, hours, days and weeks of aggregate data after calculation?

**Comment by ghd258** [comment]
![QQ图片20190506155602](https://user-images.githubusercontent.com/4811375/57212839-846ff800-7017-11e9-8142-39e40bbde7b4.png)

**Comment by mfreed** [comment]
Hi @ghd258 I'm not sure I fully understand your question, but TimescaleDB version 1.3 -- released today -- has added built-in support for continuous aggregations, where the database will automate the calculation of 15m, hour, day, etc. rollups.

**Comment by mfreed** [comment]
https://github.com/timescale/timescaledb/releases/tag/1.3.0
https://docs.timescale.com/v1.3/using-timescaledb/continuous-aggregates
