### ISSUE TITLE
Aggregate data on the fly?

### ISSUE THREAD

**Issue by cailin-lai** [timescale/timescaledb#1209]
Hi @mfreed,
It will be nice to have streaming aggregation feature in the coming v1.3.
Would it be an option to skip raw data to save the IO costs in the near future version?
You know the raw data might be saved by other servers in some cases(e.g. Elastic Search), that means TimescaleDB would be served as events aggregation processor and real-time alerting roles. It will be very nice that TimescaleDB can combine some of the PipelineDB features together. You know, Pipelinedb team will join to Confluent... 

Thanks to team,

Allen Lai

**Comment by mfreed** [comment]
Hi @cailin-lai , version 1.3 won't have the ability to drop raw data separately from the aggregated data, but that will be available in the following release.  (Our initial plan might not be to support *never* saving raw data, but could arbitrarily set the data retention for raw data to be quite small.)

Cheers!

**Comment by cailin-lai** [comment]
Good to hear! Thanks.
