### ISSUE TITLE
Creating a by chunk unique key on a non-partitioning column

### ISSUE THREAD

**Issue by narc-Ontakac2** [timescale/timescaledb#1210]
We are using timespaledb on our apache logs. To have a slim logs table we move all the big fields into dimension tables while loading. This works quite charming for fields like url_path and user_agent, which mostly stay constant over time.

Unfortunately there are also dimension tables that grow over time such as cookies and query_strings. I would like to turn these into hypertables without introducing **much** redundancy. To do this unique constraints on a by chunk basis would be helpful. It would allow me to do INSERTs with ON CONFLICT DO NOTHING.

**Comment by narc-Ontakac2** [comment]
Thinking about this I am not sure if it is a good idea. Since chunks are transparent this would lead to unpredictable behaviour with respect to duplicates.

**Comment by erimatnor** [comment]
Please join our Slack community if you have further questions.
