### ISSUE TITLE
It is suggested that the data acquisition and data processing functions of influxdb be used for reference.

### ISSUE THREAD

**Issue by ghd258** [timescale/timescaledb#1213]
It is suggested that the function of data acquisition and data processing of influxdb should be used for reference and development support, but colleagues say that influxdb has the function of automatically generating report data, and time scaledb does not have such function, hoping to improve the function.

**Comment by mfreed** [comment]
Hi @ghd258 I'm not sure exactly what you are asking.  Can you try to explain more?
