### ISSUE TITLE
Issue when drop/truncate parent table is done

### ISSUE THREAD

**Issue by vmanohar1** [timescale/timescaledb#1217]
See the following use case for V0.7.1 -
* Create a table (empty)
* Add proper constraints including at 2 triggers (row level + statement level - one each)
* Partition it with proper timestamp column
* Load data so that at least one chunk is created.
* Drop the 2 triggers on parent table.
* Truncate or drop parent table.
You get following type of error e.g.-
ERROR:  could not find tuple for trigger 69230391
CONTEXT:  SQL statement "
                DROP TABLE _timescaledb_internal._hyper_12_729_chunk 
There is dependency in pg_depend table that causes this.. 
What is the recommended way to fix that?
Also, will this happen in latest versions of timescale??
Thanks.

**Comment by cevian** [comment]
I believe this bug was fixed in https://github.com/timescale/timescaledb/commit/8b58500d766709853e411393f54c575252b8543f
Which was included starting in v10.1

You can try to run 
```
DELETE FROM pg_depend d 
WHERE d.classid = 'pg_trigger'::regclass 
AND NOT EXISTS (SELECT 1 FROM pg_trigger WHERE oid = d.objid);
```
To fix your current database.

Let me know whether that works.

**Comment by mfreed** [comment]
But we do strongly recommend upgrading to the latest / a recent version, as 0.7.1 was released in November 2017 and there have been a large number of functional and performance improvements, as well as stability and bug fixes, since then.

**Comment by vmanohar1** [comment]
We will verify. Thanks.

**Comment by ashchurova** [comment]
Thank you for the fix suggestion. That actually verified the query came up with for the fix.  I went a little further and filtered out orphan triggers only for timescale chunk tables:

```
DELETE FROM pg_depend d WHERE d.refobjid in (SELECT cl.relfilenode 
    FROM _timescaledb_catalog.chunk c, _timescaledb_catalog.hypertable h, pg_class cl
    where h.id = c.hypertable_id AND cl.relname=c.table_name AND h.table_name='parent-table-name') 
    AND NOT EXISTS (SELECT 1 from pg_trigger where oid=d.objid) 
    AND d.classid='pg_trigger'::regclass;
```
