### ISSUE TITLE
INSERT with RETURNING clause not handled or supported

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#122]
Inserting data into a hypertable like this:
```
INSERT INTO conditions VALUES('2017-04-15 23:43', 34.1, 'blue') RETURNING time, temp;
```
currently returns no rows. TimescaleDB should either return an "unsupported feature" error or handle this correctly.

**Comment by mfreed** [comment]
Fixed as part of https://github.com/timescale/timescaledb/releases/tag/0.3.0 (by @erimatnor)
