### ISSUE TITLE
Multiple date columns

### ISSUE THREAD

**Issue by tzachshabtay** [timescale/timescaledb#1224]
We have a database table with multiple date columns, and we'd like each to be partitioned differently.
Is this a supported scenario?
I saw that I can do `add_dimension` but if I understood correctly that's for a sub-partition scenario, right? So not helpful for a completely different partition.
Will calling `create_hypertable` multiple times on the same table work?
i.e:
```sql
SELECT create_hypertable('my_table', 'date1');
SELECT create_hypertable('my_table', 'date2');
SELECT create_hypertable('my_table', 'date3');
```
I assume not because it will create the same table name, so is there another way?

**Comment by mfreed** [comment]
@tzachshabtay  You can add_dimension, and it will create a 2D partitioning.  You cannot call `create_hypertable` multiple times on the same table.

That said, can you explain more about your overall use case / what you are trying to achieve?

**Comment by tzachshabtay** [comment]
@mfreed I have a table with 3 different date columns, and I want to treat those as 3 completely independent time-series (i.e people might query based on each of those dates separately). If I understand the dimensions correctly (like basically a combined index, right?) then it's not what I need.

**Comment by mfreed** [comment]
@tzachshabtay I don't think we support what you want, and the best you can do in one hypertable is to create secondary indexes on the second two time dimensions.  

It's obviously possible also to store the data three times (e.g., separately insert it into three separate hypertables that do partitioning on a different column, but our users will typically do the above vis-a-vis secondary indices.  Sorry.

**Comment by gajus** [comment]
I have been going issue by issue, and it sounds like the only option is to basically create 3 separate hypertables. That is a bummer.

**Comment by mhechthz** [comment]
Hi,

the described problem seems to be quite generic. I also have different time columns in a table (source timestamp and insert timestamp). Depending on the situation I want to use one or the other time column. 

The hypertable is on source timestamp, so it is not clear to me, what would be the most efficient configuration for fast selects on insert timestamp. I don't want to use more than one table.

**Comment by daBlesr** [comment]
Has there been any progress on the above? This problem is generic, Kafka Streams also has a sense of different timestamps to be windowed on for the same record.
