### ISSUE TITLE
CREATE INDEX WITH (timescaledb.transaction_per_chunk) does not play nicely with max_parallel_maintenance_workers > 0

### ISSUE THREAD

**Issue by jamessewell** [timescale/timescaledb#1226]
**Relevant system information:**
 - OS: NixOS
 - PostgreSQL version (output of `postgres --version`): 11.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.3
 - Installation method: source via/ nix

**Describe the bug**
Creating an index using WITH  (timescaledb.transaction_per_chunk)  fails with the following error:
```
postgres=# CREATE INDEX ON ts (time) WITH (timescaledb.transaction_per_chunk);
ERROR:  cannot take query snapshot during a parallel operation`
```

This can be fixed by setting max_parallel_maintenance_workers  to 0:

```
postgres=# set max_parallel_maintenance_workers = 0;
SET
postgres=# create index on ts (time) WITH (timescaledb.transaction_per_chunk);
CREATE INDEX
```

The default max_parallel_maintenance_workers  is 2 -> so this will be a common issue!

**To Reproduce**
See above

**Expected behavior**
See above
**Actual behavior**
See above

**Comment by dianasaur323** [comment]
@cevian Could we get someone to take a look at this?

**Comment by WarriorOfWire** [comment]
Issue exists on Timescale 1.4.1, observed on a table that is taking continuous inserts.

**Comment by dcj** [comment]
I just ran into this also....

**Comment by dianasaur323** [comment]
@dcj thanks for confirming - currently triaging.

**Comment by treystout** [comment]
same issue using Timescale 1.4.1 AMI on an EC2 instance.

**Comment by cevian** [comment]
Related to #1508.

**Comment by mfreed** [comment]
Hi @jamessewell Do you know if you still see this?  I noticed the related https://github.com/timescale/timescaledb/issues/1508 was marked as fixed in newer versions.

**Comment by NunoFilipeSantos** [comment]
Feel free to reopen it if you can still reproduce it on TimescaleDB 2.4.2.
