### ISSUE TITLE
"ERROR: invalid time_bucket_gapfill argument: bucket_width must be a simple expression", when using time_bucket_gapfill within a plpgsql function

### ISSUE THREAD

**Issue by rickbatka** [timescale/timescaledb#1231]
**Relevant system information:**
 - OS: docker image: "timescale/timescaledb:1.2.2-pg11" (Alpine Linux v3.9.2)
 - PostgreSQL version (output of `postgres --version`): "postgres (PostgreSQL) 11.2"
 - TimescaleDB version (output of `\dx` in `psql`): " timescaledb | 1.2.2   | public"
 - Installation method: Using Docker image: "timescale/timescaledb:1.2.2-pg11"

**Describe the bug**
When using time_bucket_gapfill inside a postgres function (`plpgsql`), I get the following error on the sixth (yes, always the sixth!) call to my function: 
```
"[22023] ERROR: invalid time_bucket_gapfill argument: bucket_width must be a simple expression"
```
Once the error happens, **all** subsequent calls to that function **from the same db connection** will fail. If I close and establish a new connection (or indeed, drop and recreate the function), I can use the function again, but again, only **exactly 5 times.**

The problem does seem to have something to do with being inside a postgres function, as my current workaround is that I have copy-pasted the body of the function out into a regular query and I no longer have the problem. Indeed, I can execute the query hundreds of times in succession on its own, but when it's inside the function I only get 5.

This was hard to track down :)

**To Reproduce**
I have written a minimal script to reliably reproduce the error in the "timescale/timescaledb:1.2.2-pg11" docker image. Save the script as "bucket_err.sql" and run:
```
docker run -it -v ${PWD}/bucket_err.sql:/docker-entrypoint-initdb.d/bucket-err.sql timescale/timescaledb:1.2.2-pg11
```

bucket_err.sql:
```
drop table if exists readings;
drop function IF EXISTS err_example;

CREATE TABLE readings
(
  observed     timestamp WITH TIME ZONE NOT NULL,
  name  text                     NOT NULL,
  reading        numeric
);

SELECT create_hypertable('readings', 'observed', chunk_time_interval => INTERVAL '1 hour');

CREATE OR REPLACE FUNCTION err_example(arg_bucket_start timestamp WITH TIME ZONE,
                                       arg_bucket_end timestamp WITH TIME ZONE,
                                       arg_time_step interval)
  RETURNS TABLE
          (
            bucket         timestamp WITH TIME ZONE,
            name        text,
            latest_reading numeric
          )
AS
$$
BEGIN
  RETURN QUERY
    WITH
      -- last observed reading per time bucket
      bucketed_gap_filled_data AS (
        SELECT r.name,
               time_bucket_gapfill(arg_time_step, r.observed, arg_bucket_start,
                                   arg_bucket_end) AS bucket,
               locf(last(r.reading, r.observed))  AS most_recent_reading
        FROM readings r
        WHERE r.observed >= arg_bucket_start
          AND r.observed < arg_bucket_end
        GROUP BY r.name, bucket
      )

    SELECT
      bucketed_gap_filled_data.bucket,
      bucketed_gap_filled_data.name,
      bucketed_gap_filled_data.most_recent_reading
    FROM bucketed_gap_filled_data;
END;
$$ LANGUAGE plpgsql;

-- These statements should execute without issue
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');
-- This statement fails:
select * from err_example('2019-01-01 00:00:00.000000'::timestamptz, '2019-02-01 00:00:00.000000'::timestamptz, INTERVAL '1 hour');

-- At this point, all subsequent calls to the function wil fail for the lifetime of this connection.
```

**Expected behavior**
time_bucket_gapfill can be used from within a postgres function with the same behavior as when using it outside a function.

**Actual behavior**
time_bucket_gapfill returns an error when called from a function more than exactly 5 times.

**Comment by svenklemm** [comment]
Thank you for the detailed bugreport. At 5 executions query plans in functions/prepared statements get changed into generic plans and dont go through all stages of normal query planning anymore.

**Comment by rickbatka** [comment]
Thanks for the follow-up! I see the issue was addressed and merged. Looking forward to the next release, and glad I could help in some small way.

**Comment by mfreed** [comment]
Thanks, @rickbatka.  We can only address such bugs in such a timely manner when we get such exact and detailed reports.   Thanks for your assistance in this manner!
