### ISSUE TITLE
Changing time column on exisiting Hypertable

### ISSUE THREAD

**Issue by singhnitesh** [timescale/timescaledb#1234]
Hi,
I am new at using TimescaleDB and PostgreSQL, and this is not an issue/bug report.
I wanted to know if I can change the time column after a hypertable has been created? If not then what would be the best way to go about this without loosing the underlying data.

Best Regards

**Comment by svenklemm** [comment]
You can change the time column between timestamp and timestamp without timezone if your timezone is set to UTC. What is the current datatype and what do you want to change it to?

**Comment by wolverine-1** [comment]
I am facing the same issue. In my case I have time column of type bigint (epoch millis) and I want to change it to timestampz. How can I do so ?

**Comment by mfreed** [comment]
Significant schema/type changes will likely require migrating your data to a new hypertable.  Closing our this issue for now.
