### ISSUE TITLE
can't DROP VIEW

### ISSUE THREAD

**Issue by neucloudzouaodi** [timescale/timescaledb#1237]
DROP VIEW device_summary ;

error:dropping a continous aggregate requires using CASCADE

I want to drop a view,but it's error

**Comment by cevian** [comment]
Have you tried:

DROP VIEW device_summary CASCADE;

**Comment by mfreed** [comment]
@neucloudzouaodi Our apologies, this was a docs bug.  The fix has already been merged and will be pushed at next docs release:

https://github.com/timescale/docs.timescale.com-content/pull/142

**Comment by neucloudzouaodi** [comment]
> Have you tried:
> 
> DROP VIEW device_summary CASCADE;

ok.thanks
