### ISSUE TITLE
not support pg10.1

### ISSUE THREAD

**Issue by qianfangyuan** [timescale/timescaledb#1238]
postgres=# select name,setting from pg_settings where name like '%version%';
        name        | setting 
--------------------+---------
 server_version     | 10.1
 server_version_num | 100001

timescaledb-1.3.0/src/compat.h:
![image](https://user-images.githubusercontent.com/9649317/58146156-7e208380-7c87-11e9-83be-0b73ff3485a7.png)

why not support pg10.1 ?

**Comment by davidkohn88** [comment]
Unfortunately, there were some odd backwards incompatible changes made to postgres interfaces for extensions, they usually try very hard not to do that, but something got missed, so given that there were security fixes in the later versions of 10, we went with the later versions for our compatibility. Is there a reason you need to run an older point version of Postgres?

**Comment by qianfangyuan** [comment]
I just want to know the details. Because you said that pg9, 10, and 11 are supported, but you didn't specify that they need to be on 10.1, not 10.1. Maybe you can mention these special versions in  the document.
