### ISSUE TITLE
Many tests fail with PG 11.3 

### ISSUE THREAD

**Issue by did-g** [timescale/timescaledb#1240]
Hi,

Since PG 925f46ffb82f0b25c94e7997caff732eaf14367d commit many tests are failing.

both timescale master and 1.3.x branch.

Regards
Didier

**Comment by mfreed** [comment]
Thanks for report @did-g .  We're working on it (you can see various PRs in review), looks like there were a bunch of meaningful changes between 11.2 and 11.3.  Thanks!

**Comment by did-g** [comment]
Fix in 1.3.1
