### ISSUE TITLE
Calculate derivative of a value over time

### ISSUE THREAD

**Issue by scls19fr** [timescale/timescaledb#1249]
Hello,

I'm looking for a method to calculate directly using SQL queries the derivative of a (float) value.
Unfortunately I haven't found in TimescaleDB doc an easy way to do this.
Maybe some help can be given here. I could, in return try to improve doc if you think such contribution could help others users.

Kind regards

**Comment by RobAtticus** [comment]
Could you give me a bit more an example of what you're looking for? Maybe some sample rows and what you'd expect the output to be?

**Comment by scls19fr** [comment]
2019-01-01 00:00:00.000 10.0
2019-01-01 00:00:01.000 12.0
2019-01-01 00:00:03.000 18.0

should output

2019-01-01 00:00:00.000 NaN
2019-01-01 00:00:01.000 2.0
2019-01-01 00:00:03.000 3.0

**Comment by svenklemm** [comment]
@scls19fr you want the difference to the previous column? you can achieve this with lag window function

**Comment by scls19fr** [comment]
In order to calculate numerically derivative you need to calculate 

- difference of sensors values
- difference of time columns

and divide elements of the first one calculation by the second one (in seconds)

**Comment by mfreed** [comment]
@scls19fr See the `lag` function here:  https://www.postgresql.org/docs/11/functions-window.html

**Comment by scls19fr** [comment]
Thanks @mfreed but `lag` will only calculate difference of sensors values.
I also need to calculate difference of time column and divide difference of sensors values by difference of time (in seconds)

**Comment by scls19fr** [comment]
Instead of calculating forward difference derivative, an other approach called three point derivative (standard version or endpoint version) seems to provide good numerical results.

https://www.shodor.org/refdesk/Resources/Algorithms/NumericalDifferentiation/ provides good information about pros and cons of each method.

https://wiki.postgresql.org/images/a/a2/PostgreSQL_Window_Functions.pdf provides PL/pgSQL code to calculate deivative (but also integral)
