### ISSUE TITLE
The column type is used instead of return type of `time_partitioning_func` in many functions

### ISSUE THREAD

**Issue by hedayat** [timescale/timescaledb#1250]
**Relevant system information:**
 - OS: Fedora 30
 - PostgreSQL version (output of `postgres --version`): 11
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.0
 - Installation method: Docker

**Describe the bug**
I created a hypertable with `time_partitioning_func` function to return the time value used in partitioning. However, functions such as `drop_chunks()`,`show_chunks()` and `set_chunk_time_interval()` doesn't work correctly as they are apparently looking into the type of the column rather than return value of `time_partitioning_func` function.

**To Reproduce**
1. Create a sample hypertable using `time_partitioning_func`:

```
CREATE TYPE report AS (last_seen timestamp with time zone, contents text);

CREATE TABLE customer_reports(reports report[] NOT NULL);

CREATE FUNCTION first_report_last_seen (report[])
RETURNS timestamptz
LANGUAGE SQL
IMMUTABLE
AS 'SELECT $1[1].last_seen';

SELECT create_hypertable(
    main_table => 'customer_reports',
    time_column_name => 'reports',
    time_partitioning_func => 'first_report_last_seen'
);
```

2. Now, try to run one of the mentioned functions, and it'll produce an error:
```
# SELECT set_chunk_time_interval('terminated_flows', interval '0.080000 hour');
ERROR:  invalid dimension type: "reports" must be an integer, date or timestamp
```

**Expected behavior**
The functions should properly work in this case.

**Actual behavior**
The error message appears and function doesn't do anything

**Comment by JLockerman** [comment]
Upping this to `bug`, `drop_chunks` does not handle this case gracefully, and causes an `Abort`.

**Comment by hedayat** [comment]
Just discovered yet another area in which TDB looks at the column type rather than partitioning function: if you try to ALTER the column type, TDB says that it should be an acceptable type; while it doesn't matter while the partitioning functions returns the appropriate type.

**Comment by JLockerman** [comment]
That is deliberately blocked for now, the way we handle custom time partition functions can't quite handle changing the column type yet.
