### ISSUE TITLE
Help: Partition for hypertable

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [timescale/timescaledb#1256]
We need a expert advise on designing database using timescale db. We have a below table, where we store all the device data, we use hypertable against timestamp column. We have 1000+ devices on this table, we make queries to this table always conjunctions with device_id in where statement like this.

select (sum)... from raw where device_id='1';
select (avg)... from raw where device_id='2';

Can we also use device_id as partition key to improve the scanning speed for postgresql? I see timescaledb documentation that hypertable already partition using timestamp, but we want to see if we can also apply device_id as normal postgresql partition + timestamp for hypertable partition. 
```sql
CREATE TABLE raw (
  id VARCHAR(50) not null,
  timestamp TIMESTAMP  NOT NULL,
  device_id VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  payload JSONB  not null default '{}'::jsonb,
  FOREIGN KEY (device_id) REFERENCES devices(id)
);

SELECT create_hypertable('raw', 'timestamp');
```

**Comment by RobAtticus** [comment]
You could partition on `device_id` but currently we don't recommend it. Usually if your time partition is well sized, then additionally partitioning on device does not always improve the query performance significantly. In particular, on the orders of 1000s of devices, you are probably fine just using the time partition.

In the future there may be improved optimizations for space partitioning, so you can re-evaluate later, but on all current versions I would just stick with time partitioning.

**Comment by mfreed** [comment]
In these cases, we also recommend looking into `reorder_chunk` and the automation around that:

https://docs.timescale.com/latest/api#reorder_chunk
https://docs.timescale.com/latest/api#add_reorder_policy

**Comment by gopalakrishnan-subramani** [comment]
Sorry to reopen closed question. 
What if we have 5000+ sensor data, each sensor has 150 parameters, the freq of acquisition is every 2 seconds, we end up in too many items in the table, can time partition still enough with reorder chunk?

**Comment by ricky-sb** [comment]
>This command can be particularly useful when data is often queried in an order different from that in which it was originally inserted. For example, data is commonly inserted into a hypertable in loose time order (e.g., many devices concurrently sending their current state), but one might typically query the hypertable about a specific device. **In such cases, reordering a chunk using an index on `(device_id, time)` can lead to significant performance improvement for these types of queries.**

With regards to the bolded part, in this case, would you *not* setup your hypertable with a space partition? And just set up a chunk policy? Or would you both setup a space partition and a chunk re-order policy?
