### ISSUE TITLE
PG 11 JIT failure

### ISSUE THREAD

**Issue by did-g** [timescale/timescaledb#1262]
Hi,
Many tests fail when
jit=on
jit_above_cost = 0
are set in postresql.conf

Requests with a RETURN clause like

`INSERT INTO "1dim" VALUES('2017-01-20T09:00:01', 22.5) RETURNING *;`

fail because  slot_compile_deform called from JIT llvm_compile_expr  is expecting either no TupleDesc or a TupleDesc with natts > d.fetch.last_var but TS is using a TupleDesc with nattrs == 0.

**Comment by dianasaur323** [comment]
@cevian mind having someone look at this?

**Comment by pmwkaa** [comment]
Fixed by https://github.com/timescale/timescaledb-private/pull/685
