### ISSUE TITLE
Roadmap questions about continuous aggregations

### ISSUE THREAD

**Issue by ghd258** [timescale/timescaledb#1268]
The first version of continuous aggregations has been released in TimescaleDB v1.3，But compared with the continuous  aggregations function of InfluxDB, it's still a lot worse. When will the future work be completed? 
Parallelized Materializations
Fully Up-to-date Views
Synchronous Invalidation
Support Filtered Aggregates
Data Retention Integration
Approximation Functions for Non-parallelizable Aggregates
The production environment is still not ideal for current functions.

**Comment by cevian** [comment]
Hi ghd258? Wondering which of these features you are looking for? Also what do you mean by `The production environment is still not ideal for current functions.`?

**Comment by ghd258** [comment]
For example, how to generate 15-minute data in real time and save it automatically

**Comment by cevian** [comment]
One example of a 15 minute view is: 
```
CREATE VIEW device_summary
WITH (timescaledb.continuous)
AS
SELECT
  time_bucket('15 minute', observation_time ) as bucket,
  device_id,
  avg(metric) as metric_avg,
FROM
  device_readings
GROUP BY bucket, device_id;
```
You can then query the `device_summary` view just like any other.

**Comment by cevian** [comment]
You can find more info here: https://docs.timescale.com/v1.3/using-timescaledb/continuous-aggregates

**Comment by ghd258** [comment]
![QQ图片20190603093949](https://user-images.githubusercontent.com/4811375/58770805-97a8c000-85e3-11e9-9b58-70d49940250b.png)

**Comment by ghd258** [comment]
CREATE VIEW iot_rpt_hour1
WITH (timescaledb.continuous) 
AS
SELECT
  time_bucket('1 hour', time) as time, 
  entcode,
  pointcode,
  item,
  day,
  month,
  first(realv,time) as startv, 
  last(realv,time) as lastv,
  last(realv,time)-first(realv,time) as bv,
  last(v,time) as v,
  last(tm,time) as tm
FROM
  iot_raw
GROUP BY time, entcode,
  pointcode,
  item,
  day,
  month;

**Comment by ghd258** [comment]
create  table "public"."iot_raw"
(
    "time" TIMESTAMPTZ  NOT NULL ,
    "entcode" varchar NOT NULL ,
    "pointcode" varchar NOT NULL ,
    "islj" smallint NOT NULL ,
    "item" varchar NOT NULL ,
    "day" varchar NOT NULL ,
    "month" varchar NOT NULL ,
    "v" numeric  NULL ,
    "realv" numeric  NULL ,
    "tm" varchar  NULL 
)
WITH (
    FILLFACTOR = 100,
    OIDS = FALSE
)
;

COMMENT ON TABLE "public"."iot_raw" IS '原始数据表';

CREATE INDEX CONCURRENTLY "raw_idx_time" 
ON "public"."iot_raw" ( "time" ) 
WITH (FILLFACTOR=100) ;

SELECT create_hypertable('iot_raw', 'time');
-----------------------------


create  table "public"."iot_rpt_m15"
(
    "time" TIMESTAMPTZ  NOT NULL ,
    "entcode" varchar NOT NULL ,
    "pointcode" varchar NOT NULL ,
    "item" varchar NOT NULL ,
    "day" varchar NOT NULL ,
    "month" varchar NOT NULL ,
    "isxn" smallint NOT NULL ,
    "startv" numeric  NULL ,
    "endv" numeric  NULL ,
    "v" numeric  NULL ,
    "bv" numeric  NULL ,
    "tm" varchar  NULL 
)
WITH (
    FILLFACTOR = 100,
    OIDS = FALSE
)
;

COMMENT ON TABLE "public"."iot_rpt_m15" IS '15分钟统计数据表';

CREATE INDEX CONCURRENTLY "rpt15_idx_time" 
ON "public"."iot_rpt_m15" ( "time" ) 
WITH (FILLFACTOR=100) ;

SELECT create_hypertable('iot_rpt_m15', 'time');
--------------------------------------
create  table "public"."iot_rpt_hour"
(
    "time" TIMESTAMPTZ  NOT NULL ,
    "entcode" varchar NOT NULL ,
    "pointcode" varchar NOT NULL ,
    "item" varchar NOT NULL ,
    "day" varchar NOT NULL ,
    "month" varchar NOT NULL ,
    "startv" numeric  NULL ,
    "endv" numeric  NULL ,
    "v" numeric  NULL ,
    "bv" numeric  NULL ,
    "tm" varchar  NULL 
)
WITH (
    FILLFACTOR = 100,
    OIDS = FALSE
)
;

COMMENT ON TABLE "public"."iot_rpt_hour" IS '小时统计数据表';

CREATE INDEX CONCURRENTLY "hour_idx_time" 
ON "public"."iot_rpt_hour" ( "time" ) 
WITH (FILLFACTOR=100) ;

SELECT create_hypertable('iot_rpt_hour', 'time');


-----执行下面这个出的错 --------


CREATE VIEW iot_rpt_hour1
WITH (timescaledb.continuous) 
AS
SELECT
  time_bucket('1 hour', time) as time, 
  entcode,
  pointcode,
  item,
  day,
  month,
  first(realv,time) as startv, 
  last(realv,time) as lastv,
  last(realv,time)-first(realv,time) as bv,
  last(v,time) as v,
  last(tm,time) as tm
FROM
  iot_raw
GROUP BY time, entcode,
  pointcode,
  item,
  day,
  month;

**Comment by ghd258** [comment]
Error: Unrecognized parameter namespace "timescaledb"

**Comment by lambdaq** [comment]
Hi, is there any roadmap of when will "Fully Up-to-date Views" be rollout?
