### ISSUE TITLE
Cannot set owner on continuous aggregation view

### ISSUE THREAD

**Issue by cloud-rocket** [timescale/timescaledb#1277]
**Relevant system information:**
 - OS: Google Container OS
 - PostgreSQL version (output of `postgres --version`): 11
 - TimescaleDB version (output of `\dx` in `psql`): 1;3
 - Installation method: Docker / Kubernetes

**Describe the bug**

Cannot set the owner of Continuous Aggregation view. 

**To Reproduce**
The  following query:
```
ALTER VIEW view_name OWNER TO new_owner
```
returns
```
NotSupportedError: cannot alter only SET options of a continuous aggregate
```

**Expected behavior**
Owner set

**Actual behavior**

Error returned

**Comment by k-rus** [comment]
@cloud-rocket thank you for the issue. 
Currently [ALTER VIEW only supports WITH option on continuous aggregate views](https://docs.timescale.com/v1.3/api#continuous_aggregate-alter_view) and other options are not available. We will look into this feature request.
Can you describe your use case? Why do you need this feature? 
Thank you.

**Comment by cloud-rocket** [comment]
Because I am creating views as a DB user with my personal username and password and then assigning a generic predefined role used as a role (not as a user).
