### ISSUE TITLE
AWS RDS Support

### ISSUE THREAD

**Issue by cswank** [timescale/timescaledb#128]
I have no idea how you'd do this, but is there any way to get this project on AWS RDS?

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeaturesExtensions

**Comment by stalltron** [comment]
Hi, please see the answer given here: https://github.com/timescale/timescaledb/issues/65
