### ISSUE TITLE
Table Properties “_timescaledb_cache” , _timescaledb_catalog, _timescaledb_internal，_timescaledb_config，_timescaledb_information" What are those doing?

### ISSUE THREAD

**Issue by ghd258** [timescale/timescaledb#1292]
Where should the actual business table be set up? Is it public or “_timescaledb_cache” , _timescaledb_catalog, _timescaledb_internal，_timescaledb_config，_timescaledb_information"?

Does anyone know what those settings are doing?Unlikely I couldn't find something that helps me understand this in Google. It is in Table Properties->Schema:

“_timescaledb_cache” , _timescaledb_catalog, _timescaledb_internal，_timescaledb_config，_timescaledb_information"

**Comment by svenklemm** [comment]
Those are internal schemas used by timescaledb that you shouldnt interact with directly. Your business table should be in public or any other schema you created.

**Comment by ghd258** [comment]
Thank you
