### ISSUE TITLE
Missing docs: how to scale horizontally

### ISSUE THREAD

**Issue by jensenbox** [timescale/timescaledb#13]
There seems to be many mentions of scaling horizontally with no clear description on how to make a system do that.

We need some docs on how this is done.

**Comment by RobAtticus** [comment]
We are currently working on our clustering implementation which will provide the horizontal scalability. When its ready for release we'll have more documentation on how to use it.

**Comment by tgirotto** [comment]
any news about clustering?

**Comment by Pratapkarn** [comment]
Any update on clustering ? By when it will be available.
