### ISSUE TITLE
docker for windows

### ISSUE THREAD

**Issue by nicolaslawdune** [timescale/timescaledb#130]
Hi,

I can't pull timescaledb with docker ( `docker pull timescale/timescaledb` ) from a windows platform.
It looks like there isn't a windows version image : 
`image operating system "linux" cannot be used on this platform`

**Comment by mfreed** [comment]
Hrm, we've tested and have had other people run on Windows.  Can you check if this might be your issue, i.e., I think you can configure Windows in docker to support Linux images:

https://forums.docker.com/t/docker-for-windows-image-operating-system-linux-cannot-be-used-on-this-platform/28936/8

**Comment by nicolaslawdune** [comment]
Thx for your quick response. Unfortunately, I use windows server 2016 including docker and switching docker mode is not simple.

[https://stackoverflow.com/questions/40995973/linux-docker-container-on-windows-server-2016](https://stackoverflow.com/questions/40995973/linux-docker-container-on-windows-server-2016)

Finally I install an ubuntu server and it works  :)

**Comment by mfreed** [comment]
I'm tempted to close this issue unless there is anything else?
