### ISSUE TITLE
Restoring from backup explodes on COPY _timescaledb_catalog.installation_metadata

### ISSUE THREAD

**Issue by VacuousCoder** [timescale/timescaledb#1318]
**Relevant system information:**
 - OS: Ubuntu 16.04
 - PostgreSQL version (output of `postgres --version`): 11.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.2.1
 - Installation method: apt

**Describe the bug**
I've got a master -> slave timescale setup. Taking a backup on the slave to then load into a vagrant for testing. Restoration explodes on the vagrant with this 

postgres@metrics:~$ /usr/bin/pg_restore -Fc -d time_series_warehouse /tmp/time_series_warehouse.bak
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3016; 0 289527 TABLE DATA installation_metadata postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "_timescaledb_catalog.installation_metadata" does not exist
    Command was: COPY _timescaledb_catalog.installation_metadata (key, value) FROM stdin;

WARNING: errors ignored on restore: 1

**To Reproduce**
1. Following the guide here to set up replication 
https://docs.timescale.com/v1.3/tutorials/replication

2. Then follow the guide here to pull a backup with pg_dump from the slave
https://docs.timescale.com/v1.3/using-timescaledb/backup
 
3. Spin up a 3rd box and try to restore the backup from the slave.

**Comment by VacuousCoder** [comment]
Here's a bit more info. I don't know where or how that installation_metadata piece gets set but it's missing on extension load.

```
root@metrics:/tmp# dpkg -l |grep -i timescaledb
ii  timescaledb-loader-postgresql-11   1.3.1~ubuntu16.04                                        amd64        The loader for TimescaleDB to load individual versions.
ii  timescaledb-postgresql-11          1.3.1~ubuntu16.04                                        amd64        An open-source time-series database based on PostgreSQL, as an extension.
ii  timescaledb-tools                  0.6.0~ubuntu16.04                                        amd64        A suite of tools that can be used with TimescaleDB.
root@metrics:/tmp# sudo -u postgres psql
psql (11.4 (Ubuntu 11.4-1.pgdg16.04+1))
Type "help" for help.

postgres=# \c time_series_warehouse;
You are now connected to database "time_series_warehouse" as user "postgres".
time_series_warehouse=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.3.1   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

time_series_warehouse=# SELECT * FROM _timescaledb_catalog.installation_metadata;
ERROR:  relation "_timescaledb_catalog.installation_metadata" does not exist
LINE 1: SELECT * FROM _timescaledb_catalog.installation_metadata;
```

**Comment by svenklemm** [comment]
This table got renamed between 1.2 and 1.3 you need to make sure the database you dump from is the same TimescaleDB version as the database you load into, or remove the offending table from the dump.

**Comment by VacuousCoder** [comment]
Thank you. I just saw that myself, updated everything, and ran an end to end test to confirm it's now working. Sorry for the issue and thanks for the reply.

**Comment by tmtron** [comment]
@svenklemm is there a way to know which version of timescaledb we must use for the restore operation when we have the dump file? i.e. I guess the timescale-db version might be stored in some meta table
