### ISSUE TITLE
PostgreSQL earlier version support (<9.6)

### ISSUE THREAD

**Issue by DenisPolygalov** [timescale/timescaledb#132]
Hi folks,
I'm trying to back-port timescaledb to the PostgreSQL 9.5. I was able to compile timescaledb.so with some modification of it's source code. I have shared_preload_libraries = 'timescaledb' in my postgresql.conf, but when I'm trying to create extension following happens:
% psql -U pgsql tsdb1
psql (9.5.7)
Type "help" for help.

tsdb1=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
ERROR:  syntax error at or near "CASCADE"
LINE 1: CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

Can you give me a hint on what is going on or the whole idea of the back-poring is unrealistic because timscaledb uses too many features specific to PostgreSQL 9.6? 
Thanks in advance.

**Comment by RobAtticus** [comment]
The `CASCADE` keyword was added to the syntax in 9.6. As TimescaleDB no longer has dependencies on other extensions, you can leave that word out and it should work.

Also it sounds like your changes might be useful for other people who may have to keep using 9.5 but want to use TimescaleDB. Please consider submitting a PR if you think it would be useful :)

**Comment by DenisPolygalov** [comment]
Not working too:
% psql -U pgsql tsdb1;
psql (9.5.7)
Type "help" for help.

tsdb1=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  syntax error at or near "PARALLEL"
tsdb1=#

PARALLEL does not exist in 9.5:
https://stackoverflow.com/questions/40796963/does-postgresql-query-partitions-in-parallel
I'm happy to release any changes but so far it doesn't seems to be working or useful for others. I'm impressed by your idea, and especially statements like "TimescaleDB connects with any and all third party tools that communicate with standard PostgreSQL connectors." but IMHO this is quite far from (our and many other's I'm sure) reality. In real life we are not "keep using 9.5", we "just finished migration _to_ 9.5" and in order just to try TimescaleDB I need a separated machine for PostgreSQL 9.6! Recompiling everything from source code is not an option for enterprise. Are you sure this kind of development strategy is OK for this project?

**Comment by erimatnor** [comment]
Thanks @DenisPolygalov for trying to port this to PostgreSQL v9.5. While we appreciate this effort, I'd like to point out that there are a number of features in v9.6 that we rely on (or plan to rely on in the future), like better vacuuming for big tables, parallel queries, etc. Even if you manage to get TimescaleDB to work on v9.5, it will probably be a worse experience than running on v9.6.

We understand that enterprise users sometimes lag when it comes to using the most recent software, and our efforts in supporting older versions are primarily driven by user demand as well as the ability to provide a good experience on those versions. Right now, however, supporting v9.5 is not on the horizon, but we will surely take any PRs you produce into consideration.

**Comment by DenisPolygalov** [comment]
Thanks for the response. Well, at least this information might be useful for someone... Again IMHO I think the true power of TimescaleDB will be the superior if users will be able to install PostgreSQL(9.6) + TimescaleDB + PostGIS + Mapnik without compiling anything on normal OS (RHEL, CentOS, FreeBSD). Add  here efficient and reliable backup and restore tools and you will have an enterprise-grade spatio-temporal database! So if possible please at least don't rush into things unique to PostgreSQL 10 ...

**Comment by vishal9565** [comment]
12.1

**Comment by vishal9565** [comment]
I am using psql 12.1 and getting the same error. 
    `CREATE EXTENSION IF NOT EXISTS timescaledb ;`
    `ERROR:  syntax error at or near "PARALLEL"`
What should I do.

**Comment by anilsambasivan** [comment]
Can you try without IF NOT EXISTS
Like  CREATE EXTENSION timescaledb ;
