### ISSUE TITLE
CREAT UNIQUE INDEX... WHERE IS NOT NULL does not work with INSERT...ON CONFLICT () DO UPDATE

### ISSUE THREAD

**Issue by est** [timescale/timescaledb#1328]
**Relevant system information:**
 - OS: CentOS 7 x86_64
 - PostgreSQL version: (11.3
 - TimescaleDB version: 1.3.1
 - Installation method: yum

1. create a hyper table

```
CREATE TABLE my_t (
    submit_time TIMESTAMPTZ NOT NULL,
    doc_id varchar(80),
    submit_info jsonb
)
create unique index  if not exists idx_doc_id on my_t (doc_id, submit_time) where doc_id is not null;
SELECT create_hypertable('my_t', 'submit_time');
```

and do a simple insert:

```
# INSERT INTO my_t (submit_time, submit_info) VALUES ('2019-07-01', '{}') ON CONFLICT (submit_time, doc_id) DO UPDATE SET submit_info = '{"a": 1}';
ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
```

However, `CREAT UNIQUE INDEX` without the `WHERE` works

```
# opstat=# INSERT INTO my_t (submit_time, submit_info) VALUES ('2019-07-01', '{}') ON CONFLICT (submit_time, doc_id) DO UPDATE SET submit_info = '{"a": 1}';
INSERT 0 1
```

Can we support `UNIQUE INDEX` with a `WHERE` condition?

**Comment by davidkohn88** [comment]
You must append the where clause on to the index specification in the on conflict clause in that case: so ```INSERT INTO my_t (submit_time, submit_info) VALUES ('2019-07-01', '{}') ON CONFLICT (submit_time, doc_id) WHERE doc_id is not null DO UPDATE SET submit_info = '{"a": 1}';``` should work.

**Comment by davidkohn88** [comment]
I'm going to close this as I believe that should address your problem, but feel free to reopen if it doesn't for some reason.
