### ISSUE TITLE
suggest to split the code repository of tsl directory

### ISSUE THREAD

**Issue by lalicw** [timescale/timescaledb#1329]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**
there is a tsl license added, but the code repository is in the same.
we suggest to move the tsl directory to another code repository like timescaledb-tsl, and the released code zip package is not in the same.
this action can help the guys which can only use apache license code and avoid to change the source code released zip like delete the tsl directory, and also avoid the legal risks.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by mfreed** [comment]
Hi @lalicw thank for you the suggestion, but we provide OSS-only binaries, simple directory structure to exclude tsl, and build flags to do so as well.  We know Postgres core, for example, uses our build flags to make sure that they only include OSS TimescaleDB.

For a host of software engineering and distribution reasons, we have decided to structure the software as you currently see.
