### ISSUE TITLE
The Api last() return the wrong logic value

### ISSUE THREAD

**Issue by ly85206559** [timescale/timescaledb#1334]
**Relevant system information:**
 - OS: Centor 7
 - PostgreSQL version (output of `postgres --version`):11
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.2
 - Installation method: Docker

**Describe the bug**
I want the last() fucntion can result like this:

if time bucket is 10 minutes, **I want get the last not null value in the last 10 minutes**

**To Reproduce**
1.I have a table like this:
time | f_1
-- | --
2019/7/5 8:03 | 21.4
2019/7/5 8:04 | 11.4
2019/7/5 8:16 | 32.2
2019/7/5 8:16 | 23.2
2019/7/5 8:18 | 21.2
2019/7/5 9:10 | 25.4
2019/7/5 8:19 | null
2019/7/5 8:05 | 10.5

2.This is the sql :
`SELECT
  time_bucket('10 minutes', time) AS period,
  last(f_1, time)
FROM data_value_sid_346
WHERE time > now() - interval '2 day'
GROUP BY period
ORDER BY period;`

**Expected behavior**
I get the result list like this:
peroid                              last
2019-07-05 08:00:00	10.5
2019-07-05 08:10:00	21.2
2019-07-05 09:10:00	25.4

**Actual behavior**
I get the result list like this:
peroid                              last
2019-07-05 08:00:00	10.5
2019-07-05 08:10:00	null
2019-07-05 09:10:00	25.4

**Comment by cevian** [comment]
wouldn't your case be solved by the query `SELECT time_bucket('10 minutes', time) AS period, last(f_1, time) FROM data_value_sid_346 WHERE time > now() - interval '2 day' AND f_1 IS NOT NULL GROUP BY period ORDER BY period;`?

**Comment by cevian** [comment]
@ly85206559 another words I think this is the correct behavior and you can get the result you want by adjusting your query.

**Comment by ly85206559** [comment]
@cevian yes,but if table is like this:
time | f_1 | f_2
-- | -- | --
2019/7/5 8:03 | 21.4 | 15.4
2019/7/5 8:04 | 11.4 | null
2019/7/5 8:16 | 32.2 | 14
2019/7/5 8:16 | 23.2 | 15
2019/7/5 8:18 | 21.2 | null
2019/7/5 9:10 | 25.4 | 20
2019/7/5 8:19 | null  | 15.2
2019/7/5 8:05 | 10.5 | 20

SELECT time_bucket('10 minutes', time) AS period, last(f_1, time),last(f_2,time) FROM data_value_sid_346 WHERE time > now() - interval '2 day' GROUP BY period ORDER BY period;

How can i get the correct result

**Comment by ly85206559** [comment]
> @ly85206559 another words I think this is the correct behavior and you can get the result you want by adjusting your query.

Firstly i also think change the query, but i finally find query can not be work 

if table is like this:
time | f_1 | f_2
-- | -- | --
2019/7/5 8:03 | 21.4 | 15.4
2019/7/5 8:04 | 11.4 | null
2019/7/5 8:16 | 32.2 | 14
2019/7/5 8:16 | 23.2 | 15
2019/7/5 8:18 | 21.2 | null
2019/7/5 9:10 | 25.4 | 20
2019/7/5 8:19 | null | 15.2
2019/7/5 8:05 | 10.5 | 20

SELECT time_bucket('10 minutes', time) AS period, last(f_1, time),last(f_2,time) FROM data_value_sid_346 WHERE time > now() - interval '2 day' GROUP BY period ORDER BY period;

How can i get the correct result

**Comment by dianasaur323** [comment]
@cevian do you mind closing this out?

**Comment by ly85206559** [comment]
@cevian OK,i close this question
