### ISSUE TITLE
exceeds temp_file_limit continuous aggregate

### ISSUE THREAD

**Issue by ryan-shaw** [timescale/timescaledb#1337]
**Relevant system information:**
 - OS: Ubuntu 16.04
 - PostgreSQL version (output of `postgres --version`): 9.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.2
 - Installation method: Docker

**Describe the bug**
We are migrating to the latest TimescaleDB install and during sync we realised an hour window of data from 10 days ago is missing, which have no resynced. We created a continuous aggregate to monitor the sync progress in hour windows, since we import the missing hour we are getting temp_file_limit errors for the continuous aggregate worker.

```INFO:  new materialization range not found for public.measurements (time column timestamp): no new data
INFO:  materializing continuous aggregate public.meas_cg_test: no new range to materialize
ERROR:  temporary file size exceeds temp_file_limit (1048576kB)
CONTEXT:  SQL statement "INSERT INTO _timescaledb_internal._materialized_hypertable_6 SELECT * FROM _timescaledb_internal._partial_view_6 AS I WHERE I.bucket >= '2019-06-21 09:00:00+00' AND I.bucket < '2019-07-08 11:00:00+00';"```

I set refresh_lag and refresh_interval  to -2w (2 * chunk size).

**To Reproduce**
Steps to reproduce the behavior:
Unsure

**Expected behavior**
A clear and concise description of what you _expected_ to happen.
No error

**Actual behavior**
A clear and concise description of what _actually_ happened.
Error

**Comment by gayyappan** [comment]
@ryan-shaw It would help to see the output from timescaledb_information.continuous_aggregates and timescaledb_information.continuous_aggregate_stats. 

I think that tweaking the max_interval_per_job setting for the continuous aggregate will help in your case. The continuous aggregate will process the updates in smaller batches (batch size = max_interval_per_job). It sounds like the bucket_width is 1 week. You could start with a max_interval_per_job = 1 week and try REFRESH MATERIALIZED VIEW and see if the REFRESH worked without the temp file limit error.

**Comment by mfreed** [comment]
I'm going to close out this issue.  Ryan, please feel free to re-open if you can provide more information; further, please note that significant changes have been made to continuous aggregates in 2.0.
