### ISSUE TITLE
COPY resulting in invalid results

### ISSUE THREAD

**Issue by aarondav** [timescale/timescaledb#134]
We have observed corrupt data as a result of COPY.

### Setup

We have a hypertable created as follows:

```
CREATE TABLE IF NOT EXISTS metrics (
  timestamp TIMESTAMP NOT NULL,
  metric TEXT NOT NULL,
  label0 TEXT,
  label1 TEXT,
  label2 TEXT,
  label3 TEXT,
  value DOUBLE PRECISION,
  tags JSONB
);

SELECT create_hypertable('metrics', 'timestamp');
```

We then copied in a few couple hundred thousand metrics from a CSV with a weird quote character with a command like this:

```
COPY metrics (metric, timestamp, value, label0, label1, label2, label3, tags) FROM STDIN DELIMITER ',' QUOTE '`' CSV
```

The COPY returns that it successfully inserted all the rows.

## Problem

If we `SELECT COUNT(*) FROM metrics`, we get the right data. But if we perform `SELECT COUNT(*) FROM metrics WHERE label0 = 'my-value'` where we know that that value was inserted as part of the copy, it returns 0 results. We can also group by label0 and observe 'my-value' in it.

Switching the `COPY` to an `INSERT INTO` resolves the issue (although dramatically reduces ingest speed).

**Comment by cevian** [comment]
Hi, 
Thanks for the report. I have 2 questions, if you don't mind.
1) Have you tried doing the COPY to a regular table in a DB without TimescaleDB installed? does everything work then?
2) Would it be possible for you to send a small portion of your CSV  (including 'my-value') to us (support@timescale.com) to help us debug.

Thanks.

**Comment by mfreed** [comment]
Hi @aarondav, wonder if you'd be able to share any more information?

**Comment by RobAtticus** [comment]
Hi @aarondav , was wondering if you ever got past this issue? Is there anything more we can do to help, or should I close this out?

**Comment by mfreed** [comment]
Closing out this issue as he hadn't heard similar complaint, and no further information since last July.  @aarondav if you have any more info, feel free to re-open.
