### ISSUE TITLE
time_bucket_gapfill does not infer from WHERE clause when casting timestamp to different timezone

### ISSUE THREAD

**Issue by KimSamba** [timescale/timescaledb#1345]
TimescaleDB version: 1.3.2

Currently, time_bucket_gapfill supports specific time zones:
```
SELECT time_bucket_gapfill('1 day', time AT TIME ZONE 'Japan') FROM table WHERE time between a AND b;
```
time_bucket_gapfill is supposed to infer `start` and `end` from the WHERE clause, but it still fire the error: 

```
ERROR:  invalid time_bucket_gapfill argument: ts needs to refer to a single column if no start or finish is supplied
HINT:  You can either pass start and finish as arguments or in the WHERE clause
SQL state: 22023
```

I get the same error when casting time as TIMESTAMPTZ.

**Comment by mfreed** [comment]
@KimSamba Can you quickly confirm which version of TimescaleDB you are running?

**Comment by KimSamba** [comment]
@mfreed I updated my initial post,

**Comment by svenklemm** [comment]
@KimSamba for infering start and stop from WHERE clause only direct column references are supported as 2nd argument to time_bucket_gapfill, using casts or any other expression will prevent infering start and stop and you have to specify them as 3rd and 4th argument to time_bucket_gapfill

**Comment by bboule** [comment]
@KimSamba I wanted to see how you were doing were you able to resolve your issue based on the information provided by @svenklemm ?

**Comment by KimSamba** [comment]
@bboule yes, i could solve by doing the following:
```
SELECT time_bucket_gapfill('1 day', time AT TIME ZONE 'Japan', a AT TIME ZONE 'Japan', b AT TIME ZONE 'Japan' ) FROM table WHERE time between a AND b
```
