### ISSUE TITLE
Advice: VALUES or subquery IN or JOIN Material Views

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [timescale/timescaledb#1347]
We have below scenarios for a simulation setup. 

1. 100K number of IoT Devices
2. 1 Million number of Unique Tag/Metric Names
3. There are multiple locations like zip code, state, counties, municipalities
4. Too many different type of devices [device-type] like temp, humidity, pressure, flow, valves etc. 
4. 2000+ unique tag type

We have one hypertable table  that consist of device_id, metric_name, value, timestamp.

We don't store location, device type , tag types into hypertable.

Now we need to pick a temperature from a particular county or a province/state or entire country of temperature meters type based on metric name "temperature".

We can go for a pseudo query like ,

select temperature from conditions where device_id in [select device_id from assets where state='CA'  or state='MN' and asset_type='temp-sensor'] and timestamp < something and timestamp > something_else;

or we could query with join

select temperature from conditions, assets
ON device_id = assets.device_id and (state='MN'  or state = 'MN') and asset_type='temp-sensor' and timestamp < something and timestamp > something_else;

We have hypertable for conditions, where as device_id used as  space partitions. 

Questions:

1. Will subquery in perform faster? Our past experience is not that good.
2. Can join over a table will be faster? We are looking for parallel execution due to timestamp and space partitions. 
3. We can also use JOINs with VALUES instead of IN query. 

Can you recommend something on this scale?

**Comment by dianasaur323** [comment]
Hi @gopalakrishnan-subramani! Thanks for your issue. I would recommend you hopping over to our Slack channel to ask these types of questions. I would try both and take a look at the query plan using EXPLAIN (ANALYZE, BUFFERS). IN performance has been optimized in recent releases, so you should be fine there....

**Comment by NunoFilipeSantos** [comment]
I believe this conversation moved to the Community Slack.
Closing.
