### ISSUE TITLE
Cannot create hypertable with partial unique constraint

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb#1358]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 11.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.2
 - Installation method: apt install

**Describe the bug**
On the following table, I want a partial unique constraint to enforce a single "active" row, which is to say a given device can only be at (any) location at any time. There's probably other ways to enforce this but it normally works for me. However TimescaleDB seems to hate this constraint. I'm a new user so this might be a normal limitation. Please let me know.

**To Reproduce**
1. Create this table
```sql
CREATE TABLE testTable
(
  tt_device MACADDR NOT NULL,
  tt_location MACADDR NOT NULL,
  tt_since TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tt_until TIMESTAMPTZ,
  tt_RSSI INTEGER,
  CONSTRAINT tt_pkey PRIMARY KEY (tt_device, tt_since)
);
```
2. Create the partial unique constraint
```sql
CREATE UNIQUE INDEX tt_unique
  ON testTable(tt_device)
  WHERE tt_until IS NULL;
```
3. attempt to create the hypertable
```sql
select create_hypertable('testTable', 'tt_since');
```

**Expected behavior**
Hypertable should be created.

**Actual behavior**
```sql
ERROR:  cannot create a unique index without the column "tt_since" (used in partitioning)
SQL state: TS103
```

**Additional context**
1. Drop the index
```sql
DROP INDEX tt_unique;
```
2. Hypertable can now be created

**Comment by sgichohi** [comment]
Hi @jflambert 

To define an index as UNIQUE or PRIMARY KEY, the time column and, if it exists, the partitioning column must be part of the index.

Please find more details here: https://docs.timescale.com/v1.3/using-timescaledb/schema-management#indexing

**Comment by jflambert** [comment]
Thank you @sgichohi. I see it's clear from the documentation so we can probably close this issue unless one of you guys thinks that this situation should actually be permitted.

Having said this, I take a little "offense" (not really :) at this statement: "That said, we find UNIQUE indexes in time-series data to be much less prevalent than in traditional relational data models." I deal with a lot of out-of-order and/or user-entered data and having these constraints in place allow for some basic sanity, as well as precise ON CONFLICT "upserts" based on the violated constraint.

**Comment by davidkohn88** [comment]
Totally understand that, I think we usually find that they involve the timeseries partitioning columns rather than a completely different set of columns, so hopefully that works for you.
