### ISSUE TITLE
Cannot create hypertable with BIGSERIAL primary key

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb#1359]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 11.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.2
 - Installation method: apt install

**Describe the bug**
I cannot seem to create a hypertable with a BIGSERIAL primary key. I'm a new user so this might be a normal limitation. Please let me know.

**To Reproduce**
1. Create this table
```sql
CREATE TABLE testTable
(
  tt_id BIGSERIAL PRIMARY KEY,
  tt_MAC MACADDR NOT NULL,
  tt_location MACADDR NOT NULL,
  tt_since TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tt_until TIMESTAMPTZ,
  tt_RSSI INTEGER
);
```
2. attempt to create the hypertable
```sql
select create_hypertable('testTable', 'tt_since');
```

**Expected behavior**
Hypertable should be created.

**Actual behavior**
```sql
ERROR:  cannot create a unique index without the column "tt_since" (used in partitioning)
SQL state: TS103
```

**Comment by sgichohi** [comment]
Similar to: https://github.com/timescale/timescaledb/issues/1358

To define an index as UNIQUE or PRIMARY KEY, the time column and, if it exists, the partitioning column must be part of the index.

**Comment by mfreed** [comment]
@jflambert For more context, using your running example, you created the partitioning using only `tt_since`.   We don't built global indexes over all your data (there can be terabytes), but instead build indexes local to each chunk.

But what we do know from the partitioning function is that each chunk has disjoint data according to the colum(s) it uses for partitioning.  So this is what helps with uniqueness:  If we know that chunks are unique/disjoint with regard to timestamp (or timestamp & MACaddr), and we locally have a unique index on timestamp (or timestamp & MACaddr), then transitively, we also ensure global uniqueness of timestamp (or timestamp & MACaddr).

This is why we require that all partitioning columns be part of the UNIQUE index.

Can you data model/application be designed to support that?

**Comment by jflambert** [comment]
@mfreed thanks for the explanation. I'll have to mull this over before I can give you a better answer.

I think part of my problem is that the error message is (too) generic for a newbie. Ideally it would even provide a link back to the documentation (I've seen other extensions do this). Maybe we can spin up a different issue for this.

**Comment by jflambert** [comment]
You guys can close this. It makes sense in hindsight, now that I have a bit more experience with the product. But either it isn't fully clear from the documentation or I completely missed that part while reviewing it.

**Comment by dianasaur323** [comment]
@jflambert okay, glad you go your question answered! I'll go ahead and close.
