### ISSUE TITLE
ConstraintAwareAppend does not exclude chunks in subquery

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#1360]
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version 11.2
 - TimescaleDB version 1.4.0
 - Installation method: source

**Describe the bug**
When there's a subquery and an order by clause, the ConstraintAwareAppend does not exclude chunks in v1.4.0

**To Reproduce**
Easiest way to reproduce is by explicitly setting timescaledb.enable_chunk_append to off, because that forces ConstraintAwareAppend in all cases. I have seen it in cases even with enable_chunk_append=on though, so this setting is just to easily reproduce it.

set timescaledb.enable_chunk_append=off;
drop table a cascade;
create table a (a int, b timestamptz);
select create_hypertable('a', 'b', chunk_time_interval=>interval '1d');
insert into a values (1, now()), (2,now()-interval '1d'), (3, now()-interval '2d');
explain select * from a where b >= now(); -- ok
explain select * from a where b >= now() order by a, b; -- ok
explain select * from (select * from a where b >= now() order by a, b) _; -- not ok

**Expected behavior**
Last query should exclude chunks as the other two queries before it also did.

**Actual behavior**
No chunks get excluded in the third query. 

**Screenshots**
N/A

**Additional context**
This looks like a regression, as this worked in earlier versions.

**Comment by svenklemm** [comment]
@fvannee do you have an example where constraint exclusion does not work with chunkappend?

**Comment by fvannee** [comment]
The ChunkAppend node correctly excludes chunks when the planner chooses it, but I have cases where, even with enable_chunk_append=on, the plan chooses a ConstraintAwareAppend node anyway. In the real database I have, it does so for a lot of queries even without tuning parameters. By turning off enable_bitmapscan/enable_seqscan I can reproduce the same with something like this:

set timescaledb.enable_chunk_append=on;
set enable_bitmapscan=off;
set enable_seqscan=off;
drop table a cascade;
create table a (a int, b timestamptz, c int);
select create_hypertable('a', 'b', chunk_time_interval=>interval '1d');
create index on a (a,b);
insert into a values (1, now(), 3), (2,now()-interval '1d', 2), (3, now()-interval '2d', 1);
explain select * from a where b >= now(); -- ok
explain select * from a where b >= now() order by a, b; -- ok
explain select * from (select * from a where a=1 and b >= now() order by a, b) _; -- not ok

**Comment by svenklemm** [comment]
yes I misunderstood, i thought this happens with chunkappend too, the planner won't use ChunkAppend to replace MergeAppend unless its an ordered append

**Comment by fvannee** [comment]
Ok, thanks! An additional question in that case: why doesn't it recognize this as an ordered append? It is ordered, right? Since a=1, column a is redundant in the sorting path.

**Comment by svenklemm** [comment]
Yes it should be converted to ordered append, but our check might be too strict and the conversion is not done.
