### ISSUE TITLE
possible memoryleak with hypertable trying to partition by time and space

### ISSUE THREAD

**Issue by mzirlinger** [timescale/timescaledb#1361]
**Relevant system information:**
 - OS: Ubuntu 18.04.2 LTS
 - PostgreSQL version: postgres (PostgreSQL) 11.4 (Ubuntu 11.4-1.pgdg18.04+1)
 - TimescaleDB version: 1.3.2
 - Installation method: TimescaleDB 1.3.2 (PostgreSQL 11) - Ubuntu 18.04 (EBS Backed) (ami-0e39087981bad58ea) - The ec2 ami from the documentation
- ec2-instance size: m5.xlarge

**Describe the bug**
I have a database with approximately 16 columns. I create a hypertable based on a date column and a space column. The date column is not universally unique. The space column has  only a few hundred distinct values. I then do postgres copy. The postgres copy never finishes. When running htop I see the memory consumption rise over time and after a few hours the postgres copy dies.

If I run postgres copy and partition based solely on the date column the data is successfully copied.

**To Reproduce**
1. Create a hypertable based on time and a space column
2. Run postgres copy
3. Run htop
4. Eventually the memory will run out

**Expected behavior**
Postgres copy will insert all of the data into the hypertable.

**Actual behavior**
Postgres copy eventually dies.

**Comment by davidkohn88** [comment]
Hi! Thanks for the report- we've been trying to reproduce but have been having a bit of trouble.  Can you please provide your settings for:
a) number of space partitions
b) work_mem settings
c) do you know the actual memory usage at the time that it died? 
d) the setting for `timescaledb.max_open_chunks_per_insert`
can you try lowering the setting for max_open_chunks_per_insert and see if that helps? 
Thanks!

**Comment by bboule** [comment]
@mzirlinger  any chance you could provide the additional info requested?  Let us know how we can help you move forward.

**Comment by mzirlinger** [comment]
Hi there,

I have had to put this on hold for the time being. I appreciate the help and will close this issue. I will open another issue in the future when I can investigate further and add the additional info requested.
