### ISSUE TITLE
[QUESTION/DOC] Can I add an external index which is not used for partitioning?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [timescale/timescaledb#1364]
Hi guys,

I'm not able to find this information on the docs, probably it's my fault. So I hope you will point me out to the correct solution.

So we have a current database deployed with timescaledb. 

It is partitioned based on event time and an alphabetical ID and it's working perfectly.

Given this, we are ingesting information in batch format. Sometimes an incident happen and we need to delete and reapply a file. For that we added a batch id.

Problem is this batch id has no index and even time can be really spread in months so it means that running a select count based on event time and batch id is not performant at all.

I was wondering if it's possible to add another index, which is not in the partition, but allows to run this query faster.

edit: I don't even know if it makes sense to have a feature like this.

**Comment by davidkohn88** [comment]
You can add an index on batch_id, but it can't be a unique index. It would be more useful for finding items with a given batch id rather than counting across all batch ids. A continuous aggregate might be more useful for queries like that.

**Comment by invasionofsmallcubes** [comment]
Hello @davidkohn88 .
So, yes, batch_id of course is not unique, any batch_id is associated with ~800k.
The query that I actually need to do is a `DELETE FROM batche WHERE batch_id = 1`.
Does it make sense to use this index to run a `DELETE`? Do you see any performance issues after deletion?

**Comment by mfreed** [comment]
Hi @invasionofsmallcubes Yes, you can add that index.  

Your delete will work, it will however process every chunk (but that's needed in the type of query you specify).  If you do a lot of deletes, make sure you are regularly vacuuming your chunks to avoid bloat.
