### ISSUE TITLE
dropdb: query failed: ERROR:  could not access file "$libdir/timescaledb-0.12.1": No such file or directory

### ISSUE THREAD

**Issue by k-bx** [timescale/timescaledb#1367]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version 10.9
 - TimescaleDB version 1.4.0
 - Installation method: apt/ppa

**Describe the bug**
After a recent `apt-get upgrade` I'm now getting this error when trying to run dropdb:

```
dropdb: query failed: ERROR:  could not access file "$libdir/timescaledb-0.12.1": No such file or directory
```

Seems like TimescaleDB upgraded to a more recent version (1.x), but dropdb still looks for the old library from somewhere.

**To Reproduce**

Try running dropdb

**Comment by k-bx** [comment]
Sorry, solved by doing:

```
$ PGPASSWORD=password psql -X -h localhost -U postgres postgres
psql (10.9 (Ubuntu 10.9-1.pgdg18.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# ALTER EXTENSION timescaledb UPDATE;
ALTER EXTENSION
```

**Comment by k-rus** [comment]
Great that you resolved your issue. Since [the instructions](https://docs.timescale.com/latest/using-timescaledb/update-db) describe this already, I close the issue.
