### ISSUE TITLE
Crash/Segfault after update to 1.4

### ISSUE THREAD

**Issue by rrb3942** [timescale/timescaledb#1368]
**Relevant system information:**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - PostgreSQL version (output of `postgres --version`): PostgreSQL 10.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.0
 - Installation method: rpm

**Describe the bug**
After updating to 1.4.0 from 1.3.0 we are getting random crashes in timescaledb. It seems to be linked to a query against a specific table.

We have our main data tables (which are hypertables) and on inserts they run a trigger that upserts (insert on conflict) into a set of summary tables (which are also hypertables). 

We have a monitoring app that runs against the summary tables. When this app is running it seems to trigger random crashes in timescaledb since updating. It does not crash every time, but we have disabled the monitoring system which seems to have stopped the crashing for now. I have yet to crash it manually running the same queries as the monitoring app.

I do see this error before every crash:
ERROR:  invalid child of chunk append: 133

[dmesg.txt](https://github.com/timescale/timescaledb/files/3424174/dmesg.txt)
[postgresql-Tue.txt](https://github.com/timescale/timescaledb/files/3424175/postgresql-Tue.txt)

**Comment by dianasaur323** [comment]
@svenklemm mind taking a quick look to triage? thank you~~
