### ISSUE TITLE
Multiple Continuous aggregation all views stop aggregating after wrongly attempt to create view whose name already exists

### ISSUE THREAD

**Issue by taalhach** [timescale/timescaledb#1370]
**Relevant system information:**
 - OS: Ubuntu 16.04
 - PostgreSQL version : pg-11
 - TimescaleDB version: 1.4.0
 - Installation method: Docker
 tag: 1.4.0-pg11-bitnami
digest:  sha256:ce8a399a1f02759ebb67bbae440f965efb7b01a8750231c38b52473a28ee6de8

After updating 1.4.0 i was creating multiple continuous aggregation views on one hypertables i observed that it works fine and updates itself automatically on every insertion until i try to create a new continuous aggregation view with name that already exists after that no view updates itself automatically  i have to refresh them  manually

1. create a continuous view on hypertable
2. insert into updates
3. select from view (its updated)
4. create another view with same name above
5. notice comes up and change the name and recreate view
6.  insert in hypertable
7. select *  from view
6. view is not updated

**Expected behavior**
Should update both view immediately
**Actual behavior**
Doesn't update

**Screenshots**
I did `select * from timescaledb_information.continuous_aggregate_stats` it shows null = in every columns of resulted table

![Screenshot from 2019-07-24 13-09-02](https://user-images.githubusercontent.com/31938266/61781249-7747f580-ae1d-11e9-82fb-12f18ebbfc0d.png)

**Comment by feikesteenbergen** [comment]
I did the same sequence of events you described, but I cannot reproduce it that way.

What strikes me in your screenshot is that the cagg for `sixhr` is still running as of the time of that screenshot.

Could you have a look in your PostgreSQL diagnostic logs to see any errors that point to the timescaledb background workers having issues?

**Comment by taalhach** [comment]
what about last two thw and tw views  their columns are null ?
let me look into logs

**Comment by taalhach** [comment]
i changed the docker image and did the setups again so its now working fine thank you for active support <3

**Comment by dianasaur323** [comment]
Wonderful! I'll close out now then.
