### ISSUE TITLE
can create continuous aggregate only on hypertables

### ISSUE THREAD

**Issue by neucloudzouaodi** [timescale/timescaledb#1374]
CREATE VIEW device_summary WITH ( timescaledb.continuous, timescaledb.max_interval_per_job = '1 hours' ) AS SELECT
time_bucket ( '30 minutes', TIMESTAMP ) AS bucket,
deviceid,
datapoint,
COUNT ( VALUE ) AS countvalue,
AVG ( VALUE ) AS avgvalue,
MAX ( VALUE ) AS MAXVALUE,
MIN ( VALUE ) AS MINVALUE,
FIRST ( VALUE, TIMESTAMP ) AS firstvalue,
LAST ( VALUE, TIMESTAMP ) AS lastvalue 
FROM
	device2 
GROUP BY
	bucket,
	deviceid,
	datapoint;

> ERROR:  can create continuous aggregate only on hypertables

timescaledb | 1.4.0 | public     | Enables scalable inserts and complex queries
for time-series data

I upgraded timescaledb1.3 to 1.4. After the upgrade is successful, create a continuous aggregation that cannot be successful. Why?

**Comment by dianasaur323** [comment]
@neucloudzouaodi sounds like you figured it out! :)
