### ISSUE TITLE
could not update timescaledb v1.3.0-dev to timescaledb v1.4.0

### ISSUE THREAD

**Issue by mandyqcx** [timescale/timescaledb#1375]
**Relevant system information:**
 - OS: [Centos 7.3]
 - PostgreSQL version : [11.1]
 - TimescaleDB version : [1.3.0-dev]
 - Installation method: [source]

**Describe the bug**
I could not update timescaledb v-1.3.0-dev to timescaledb v1.4.0. I have installed the version v1.4.0 of the Timescaledb extension.Then I executed "ALTER EXTENSION timescaledb UPDATE;" command after command "psql -X".However,it said, ERROR:  extension "timescaledb" has no update path from version "1.3.0-dev" to version "1.4.0".

The following is all the *.sql of Timescaledb  in the path, /usr/local/pgsql-11.1/share/extension,(/usr/local/pgsql-11.1 is the install path of PG)
-rw-r--r--. 1 postgres postgres  76455 Apr 24 05:48 timescaledb--0.10.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  86410 Jul 26 03:52 timescaledb--0.10.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  76146 Apr 24 05:48 timescaledb--0.10.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  86101 Jul 26 03:52 timescaledb--0.10.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres 111279 Apr 24 05:48 timescaledb--0.1.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 121202 Jul 26 03:52 timescaledb--0.1.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  74832 Apr 24 05:48 timescaledb--0.11.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  84791 Jul 26 03:52 timescaledb--0.11.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  71425 Apr 24 05:48 timescaledb--0.12.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  81392 Jul 26 03:52 timescaledb--0.12.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  71425 Apr 24 05:48 timescaledb--0.12.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  81392 Jul 26 03:52 timescaledb--0.12.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres 110562 Apr 24 05:48 timescaledb--0.2.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 120485 Jul 26 03:52 timescaledb--0.2.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres 110317 Apr 24 05:48 timescaledb--0.3.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 120240 Jul 26 03:52 timescaledb--0.3.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres 110158 Apr 24 05:48 timescaledb--0.4.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 120081 Jul 26 03:52 timescaledb--0.4.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres 110158 Apr 24 05:48 timescaledb--0.4.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 120081 Jul 26 03:52 timescaledb--0.4.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres 110158 Apr 24 05:48 timescaledb--0.4.2--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 120081 Jul 26 03:52 timescaledb--0.4.2--1.4.0.sql
-rw-r--r--. 1 postgres postgres  96816 Apr 24 05:48 timescaledb--0.5.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 106759 Jul 26 03:52 timescaledb--0.5.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  91288 Apr 24 05:48 timescaledb--0.6.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 101231 Jul 26 03:52 timescaledb--0.6.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  91288 Apr 24 05:48 timescaledb--0.6.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres 101231 Jul 26 03:52 timescaledb--0.6.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  82380 Apr 24 05:48 timescaledb--0.7.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  92335 Jul 26 03:52 timescaledb--0.7.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  81177 Apr 24 05:48 timescaledb--0.7.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  91132 Jul 26 03:52 timescaledb--0.7.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  80528 Apr 24 05:48 timescaledb--0.8.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  90483 Jul 26 03:52 timescaledb--0.8.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  76455 Apr 24 05:48 timescaledb--0.9.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  86410 Jul 26 03:52 timescaledb--0.9.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  76455 Apr 24 05:48 timescaledb--0.9.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  86410 Jul 26 03:52 timescaledb--0.9.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  76455 Apr 24 05:48 timescaledb--0.9.2--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  86410 Jul 26 03:52 timescaledb--0.9.2--1.4.0.sql
-rw-r--r--. 1 postgres postgres  70793 Apr 24 05:48 timescaledb--1.0.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  80760 Jul 26 03:52 timescaledb--1.0.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  71425 Apr 24 05:48 timescaledb--1.0.0-rc1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  81392 Jul 26 03:52 timescaledb--1.0.0-rc1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  71354 Apr 24 05:48 timescaledb--1.0.0-rc2--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  81321 Jul 26 03:52 timescaledb--1.0.0-rc2--1.4.0.sql
-rw-r--r--. 1 postgres postgres  70793 Apr 24 05:48 timescaledb--1.0.0-rc3--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  80760 Jul 26 03:52 timescaledb--1.0.0-rc3--1.4.0.sql
-rw-r--r--. 1 postgres postgres  70793 Apr 24 05:48 timescaledb--1.0.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  80760 Jul 26 03:52 timescaledb--1.0.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  69954 Apr 24 05:48 timescaledb--1.1.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  79921 Jul 26 03:52 timescaledb--1.1.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  69954 Apr 24 05:48 timescaledb--1.1.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  79921 Jul 26 03:52 timescaledb--1.1.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  68016 Apr 24 05:48 timescaledb--1.2.0--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  77983 Jul 26 03:52 timescaledb--1.2.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  68016 Apr 24 05:48 timescaledb--1.2.1--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  77983 Jul 26 03:52 timescaledb--1.2.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  68016 Apr 24 05:48 timescaledb--1.2.2--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  77983 Jul 26 03:52 timescaledb--1.2.2--1.4.0.sql
-rw-r--r--. 1 postgres postgres  72788 Jul 26 03:52 timescaledb--1.3.0--1.4.0.sql
-rw-r--r--. 1 postgres postgres  82999 Apr 24 05:48 timescaledb--1.3.0-dev.sql
-rw-r--r--. 1 postgres postgres  72788 Jul 26 03:52 timescaledb--1.3.1--1.4.0.sql
-rw-r--r--. 1 postgres postgres  72579 Jul 26 03:52 timescaledb--1.3.2--1.4.0.sql
-rw-r--r--. 1 postgres postgres  91075 Jul 26 03:52 timescaledb--1.4.0.sql
-rw-r--r--. 1 postgres postgres    365 Jul 26 03:51 timescaledb.control

Is this because I don't have a file called timescaledb--1.3.0-dev--1.4.0.sql? How can I update Timescaledb v-1.3.0-dev to Timescaledb v1.4.0?

**Comment by feikesteenbergen** [comment]
It seems you probably installed 1.3 from source while it was still being developed?

There's I guess two ways to solve this, the very safe option, however this will lose all your currently created hypertables:

Safe option, loses all your data however
=
If you want to keep your data, you should dump the data or copy it into a non-hypertable and import the data afterwards.
```
-- Note: This will drop all data in all hypertables!
BEGIN;
DROP EXTENSION timescaledb CASCADE;
--Commit/rollback here depending on what you want
CREATE EXTENSION timescaledb; -- should install version 1.4.0
```

The second option is a bit more adventurous, but will probably work, the upgrade scripts themselves do not differ that much from version to version (e.g. 1.2.0--1.4.0 has a few less DROP statements than 1.3.0--1.4.0), but you might get away with creating a copy/symlink from `timescaledb--1.3.0--1.4.0.sql` to `timescaledb--1.3.0-dev--1.4.0.sql`.

Most functions are created idempotently by using `CREATE OR REPLACE`, so even if a function is not dropped, it will be recreated correctly.

Adventurous option, keeps all your data
=
```bash
cd /usr/local/pgsql-11.1/share/extension
ln -s timescaledb--1.3.0--1.4.0.sql timescaledb--1.3.0-dev--1.4.0.sql
```
```sql
ALTER EXTENSION timescaledb UPDATE;
```

**Comment by mandyqcx** [comment]
Thanks for your advice.
I have tried the second option . But it does not worked.
```
postgres=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  relation "_timescaledb_catalog.continuous_agg" does not exist
```
So do I have to choose the first option? But I want to keeps all your data.

**Comment by dianasaur323** [comment]
We don't support upgrades from dev versions to live versions. You might consider dumping your data prior to doing any of this so that you don't lose your data.

**Comment by svenklemm** [comment]
1.3.0-dev is pre-1.3.0 so you should copy the 1.2.0 script instead

**Comment by mfreed** [comment]
Hi @mandyqcx How did that work for you?

**Comment by mandyqcx** [comment]
I have tried this way, actually I tried 1.2.0 ,1.2.1, 1.2.2, but they didn't word.
```
ln -s timescaledb--1.2.0--1.4.0.sql timescaledb--1.3.0-dev--1.4.0.sql

postgres=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  function "finalize_agg" already exists with same argument types
```

In the end , I drop extension timescaledb, and then execute "CREATE EXTENSION timescaledb;". And it worked.
