### ISSUE TITLE
cannot update from 1.3.2 to 1.4.0

### ISSUE THREAD

**Issue by nhooyr** [timescale/timescaledb#1377]
**Relevant system information:**
 - OS: Latest PG11 docker container
 - PostgreSQL version (output of `postgres --version`): 11.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.0
 - Installation method: Docker

**Describe the bug**
I cannot update from 1.3.2 to 1.4.0. I see the following logs constantly:

```
ERROR:  could not access file "$libdir/timescaledb-1.4.0": No such file or directory
```

There is no 1.4.0 file in my pkglibdir:

```
bash-4.4# ls /usr/local/lib/postgresql/timescaledb-*
/usr/local/lib/postgresql/timescaledb-1.1.0.so      /usr/local/lib/postgresql/timescaledb-1.2.2.so      /usr/local/lib/postgresql/timescaledb-tsl-1.2.0.so  /usr/local/lib/postgresql/timescaledb-tsl-1.3.1.so
/usr/local/lib/postgresql/timescaledb-1.1.1.so      /usr/local/lib/postgresql/timescaledb-1.3.0.so      /usr/local/lib/postgresql/timescaledb-tsl-1.2.1.so  /usr/local/lib/postgresql/timescaledb-tsl-1.3.2.so
/usr/local/lib/postgresql/timescaledb-1.2.0.so      /usr/local/lib/postgresql/timescaledb-1.3.1.so      /usr/local/lib/postgresql/timescaledb-tsl-1.2.2.so
/usr/local/lib/postgresql/timescaledb-1.2.1.so      /usr/local/lib/postgresql/timescaledb-1.3.2.so      /usr/local/lib/postgresql/timescaledb-tsl-1.3.0.so
```

Only 1.3.2.

When I enter the DB with psql and run a query it throws the same error but then after that the extension shows as loaded with `\dx` on version 1.4.0.

I cannot run `ALTER EXTENSION timescaledb UPDATE;` because when i run it, i get an error saying it's already loaded or if its the first command I run in a psql session, I get 

```
ERROR:  extension "timescaledb" has no update path from version "1.4.0" to version "1.3.2"
```

If I run `\dx` before it or pretty much any query, I get the not found error and then if I run the update command I get:

```
coder=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.
```

**Comment by nhooyr** [comment]
Nvm, somehow our images got mixed up, problem was deploying to 1.3.2 image.

**Comment by waterdrop01** [comment]
Hey @nhooyr , how did you sort your problem out?
I have the exact same problem...can't find the solution: https://github.com/timescale/timescaledb/issues/1425
Thanks!
