### ISSUE TITLE
Foreign key CONSTRAINTS not currently supported with hypertables

### ISSUE THREAD

**Issue by noyez** [timescale/timescaledb#138]
Hello -- my apologies if this has been addressed (i didn't see it in the github issues). 

I am not a db guru, so i don't understand all the nuances with timescaledb and PG interals, however, looking at your [data model example](http://docs.timescale.com/introduction/data-model) and your [paper, Figure 2](http://www.timescale.com/papers/timescaledb.pdf), you describe almost my exact usecase with one exception. My `sensor_data` table uses a foreign key for `device_id` into a `devices` table. But, foreign keys appear to cause `create_hypertable()` fail. 

    CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

    CREATE TABLE devices (
        id              SERIAL PRIMARY KEY,
        meta_data       JSON DEFAULT '[]'::JSON NOT NULL
    );

    -- Expanded from Figure 2 in your paper
    CREATE TABLE sensor_data (
        "time" timestamp with time zone NOT NULL,
        -- device_id TEXT NOT NULL,
        device_id INTEGER REFERENCES devices(id),  --<--< create_hypertable fails with this line
        location TEXT NULL,
        temperature NUMERIC NULL,
        humidity NUMERIC NULL,
        pm25 NUMERIC
    );

    SELECT create_hypertable('sensor_data', 'time');

I doubt that i am alone when wanting to have sensor_data from multiple devices where a `device_id` column references another table. Is this not possible with timescaledb, or should these tables be organized differently to achieve the same goal such that `device_id` is guaranteed to exist in `devices` table, or does the end-user need to eliminate the constraint on `sensor_data.device_id` to use timescaledb which would break the guarantee that `device_id` exists in `devices`? 

Thank you!

**Comment by cevian** [comment]
Hi noyez, I am actually working on this right now. Currently, you would have to eliminate the constraint. I am optimistic that I can resolve this issue for the next release. Will keep this issue updated with the status.

**Comment by akulkarni** [comment]
Just to be clear, this the right way to organize your data, and it should work today if you eliminate the FK constraint. But we are working on a fix to allow FK constraints as well.

**Comment by nmiculinic** [comment]
I've got the same issue, and something differs between versions 0.2.0 and 0.3.0. Foreign key kinda works on 0.2.0 (as in, it doesn't throw exception it's not a foreign key constraint) while on 0.3.0 I get ```sqlalchemy.exc.InternalError: (psycopg2.InternalError) constraint 16817 is not a foreign key constraint```

**Comment by mfreed** [comment]
@nmiculinic 0.3.0 actually introduced internal constraints into child tables in order to support UPSERTs, sounds like the FK stuff for SQLAlchemy became a little more touchy.

Hopefully the fix that Mat has been working on will solve your problem as well.

**Comment by mfreed** [comment]
Addressed by https://github.com/timescale/timescaledb/issues/138.

**Comment by mfreed** [comment]
Fixed in https://github.com/timescale/timescaledb/pull/198
Released in https://github.com/timescale/timescaledb/releases/tag/0.5.0
