### ISSUE TITLE
Continuous Agreggation is not killing the background task when view is dropped while aggregation is refreshing

### ISSUE THREAD

**Issue by devlucasc** [timescale/timescaledb#1386]
I created a continuous aggregation view. But I executed  `DROP VIEW xyz CASCADE` while the background agreggation job still running. I tried to recreate the aggregated view and I reached this error: `SQL Error [0A000]: ERROR: hypertable already has a continuous aggregate
  Dica: hypertables currently only support a single continuous aggregate. Drop the other continuous aggreagate to add a new one.` But the aggregate view didn't exist anymore. Someone can help me?

**Comment by gayyappan** [comment]
What happens if you try to drop the view again?

**Comment by devlucasc** [comment]
@gayyappan I can't delete too. `SQL Error [42P01]: ERROR: view "...." does not exist`.
I checked the dependences and I found two views: `"_timescaledb_internal"."_partial_view_13"` and `"_timescaledb_internal"."_direct_view_13"` and the trigger `ts_cagg_invalidation_trigger`. Can I drop them? It is safe?

**Comment by gayyappan** [comment]
@devlucasc 
you should **NOT** delete the ts_cagg_invalidation_trigger. 

You can drop the _timescaledb_internal._partial and _direct views. You will also need to delete the  entry for  the view from _timescaledb_catalog.

`select * from _timescaledb_catalog.continuous_agg where partial_view_name like '_partial_view_13'; `
--save the output from this row --
Then delete the corresponding row from _timescaledb_catalog.conitnuous_agg;

**Comment by devlucasc** [comment]
@gayyappan Thank u. This worked very well. Should I delete the bgw entry too in config table?
`select * from "_timescaledb_config".bgw_job where id = 1001`. Do you known if I need to kill some background process too using pkill/kill command?

**Comment by devlucasc** [comment]
@gayyappan The database was entered in recovery mode. It was necessary to delete the entry from bgw_job too. Now it's running correct. Its necessary to fix this in timescaleDB

**Comment by cevian** [comment]
Hi, I was able to reproduce this bug and am working on a fix. Thanks a lot for the report.
