### ISSUE TITLE
view bug

### ISSUE THREAD

**Issue by neucloudzouaodi** [timescale/timescaledb#1389]
I created a view. The data is Continuous Agreggation every 30 minutes. However, when my data stopped  insert, the last remaining data does not reach the data amount of an aggregation task, and the aggregation cannot be performed, which causes the data of my view to be missing.

REFRESH MATERIALIZED VIEW  device_summary
> INFO:  new materialization range not found for public.device2 (time column timestamp): not enough new data past completion threshold (1564566600000000)
  
  INFO:  materializing continuous aggregate public.device_summary: no new range to materialize
  
  INFO:  materializing continuous aggregate public.device_summary: no new range to materialize or invalidations found, exiting early

**Comment by neucloudzouaodi** [comment]
I also created two other views, 10 minutes and 60 minutes to aggregate the view of the task. The same problem, the final data is not Continuous  aggregated.

**Comment by k-rus** [comment]
According to [the documentation](https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates) the continuous aggregate is behind the maximum inserted time, thus the view doesn't contain the latest data. [Manual refresh](https://docs.timescale.com/latest/api#continuous_aggregate-refresh_view) is also affected by continuous aggregate parameters.
For example, `refresh_lag` controls how up-to-date the view will be.

It will be great if you follow the bug reporting template, so, e.g., the version of TSDB is clear and how you created the view. My guess is that the view behaves in correspondence to parameters, which were specified.

Note [slack support channel](https://slack.timescale.com/) is available for community help and support.

**Comment by neucloudzouaodi** [comment]
ok ,thanks
