### ISSUE TITLE
How to upgrade timescaledb on Postgresql 11.2

### ISSUE THREAD

**Issue by booncheow** [timescale/timescaledb#1396]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by mfreed** [comment]
Hi @booncheow without information or description as asked in the above form, it's hard to understand what your problem is.

Upgrade instructions can be found in our docs:  https://docs.timescale.com/latest/using-timescaledb/update-db

**Comment by booncheow** [comment]
We would like to upgrade timescaledb 1.3.0 to 1.4.0 on postgresql 11.2
Have installed timescaledb 1.4.0 extension.  

/export/home/dbadmin/postgresql/TESTPGDB13/lib$ psql -X
psql (11.2)
Type "help" for help.
dbadmin=# \c blee132
You are now connected to database "blee132" as user "dbadmin".
blee132=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.3.0   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)
blee132=#  ALTER EXTENSION timescaledb UPDATE;
ERROR:  could not load library "/export/home/dbadmin/postgresql/TESTPGDB13/lib/timescaledb-1.4.0.so": /export/home/dbadmin/postgresql/TESTPGDB13/lib/timescaledb-1.4.0.so: undefined symbol: is_dummy_rel
blee132=# \q

dbadmin<TESTPGDB13>@dxvsmtdbmgt002:/export/home/dbadmin/postgresql/TESTPGDB13/lib$ ls -l "/export/home/dbadmin/postgresql/TESTPGDB13/lib/timescaledb-1.4.0.so"
-rwxr-xr-x 1 dbadmin dbadmin 383312 Aug 12 02:08 /export/home/dbadmin/postgresql/TESTPGDB13/lib/timescaledb-1.4.0.so

where ./lib/timescaledb.so (1.3.0 version)
where ./share/extension/timescaledb.control (1.3.0 version)

Besides the error above, is there any support matrix between postgresql and timescaledb version?

**Comment by booncheow** [comment]
the link provided does not provide any info or fix for the error encountered? 

Could there be more steps or any missing steps?

**Comment by svenklemm** [comment]
@booncheow our package needs postgresql 11.4

**Comment by RobAtticus** [comment]
@booncheow also what install method (and OS) did you use to install in the first place? 1.4.0 and 1.4.1 should have downloaded and installed a new version of PostgreSQL (11.4+) when you tried.

**Comment by booncheow** [comment]
@svenklemm just to confirm timescaledb 1.4.0 package needs postgresql 11.4? and it does not work with any other postgresql 11 releases? is any there certification matrix such timescale x.x.x works with which postgresql x.x etc? 

thank you

**Comment by booncheow** [comment]
Much appreciated for the replies and help here.
