### ISSUE TITLE
Installation issue on Windows using EnterpriseDB PG version

### ISSUE THREAD

**Issue by Camelxx** [timescale/timescaledb#1398]
**Relevant system information:**
 - Windows server 2012
 - PostgreSQL v11.5.1
 - TimescaleDB v11.1.3.2

**Describe the bug**
When ruining CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE; pgAdmin Connection lost to server 
This is a new install of postgers server 

Timescale db setup
![image](https://user-images.githubusercontent.com/44997021/62917311-0f415b00-bd9c-11e9-9f81-e047403b947a.png)

In mypostgresql.conf
shared_preload_libraries = 'timescaledb'

Also installed 
Visual C++ Redistributable for Visual Studio 2015

**Comment by dianasaur323** [comment]
@Camelxx are you otherwise able to connect to postgresql with pgadmin?

**Comment by Camelxx** [comment]
Hi everyone, looks like there's a slight problem with PG 11.5 / TS 1.4.1, tested on a fresh install of Windows Server 2019. Following the installation steps exactly, we got stuck on creating the timescaledb extension in the tutorial database, with the following error: ERROR: Could not load library “C:/Program Files/PostgreSQL/11/lib/timescaledb-1.4.1.dll”: The specified module could not be found. This comes after having successfully set up PG with TS on several development machines, on both PG 9.6 and 11, with their respective TS counterparts. After digging a bit, and trying various other versions of the C++ runtime (as this is what most stackoverflow posts of a similar nature pointed to), as well as giving Dependecy Walker a go, it seemed that with PG 11.5 and TS 1.4.1 there were several dll files required that were not present. I managed to pick out one - ssleay32.dll from the PG bin folder. Uninstalling and then reinstalling PG 11.4 and TS 1.3.1, that specific DLL file showed up and everyting worked as expected. I tried numerous other ways to get 1.4.1 to work, including assigning more permissions to folders, running everyting I could As Administrator, and changing the user account under which the PG service runs to LocalMachine from NetworkService, before discovering it was missing DLL files. C++ build version according to PG was 1914, 64-bit

**Comment by RobAtticus** [comment]
I posted this in our slack where we had several similar reports:

I've been able to reproduce the issue. Installing TimescaleDB does indeed fail on a completely new server where I install from 11.5. It appears that some DLLs we are depending on were not included in EnterpriseDB's packaging, so I think we'll need to get in touch with them to figure out if its a problem on our end when packaging our extension or on their end.

However, the workaround I have is that by installing 11.4 first and then upgrading to 11.5, it does work. So if you want to install 11.4:
https://get.enterprisedb.com/postgresql/postgresql-11.4-3-windows-x64.exe

Then go back and re-install 11.5 and there shouldn't be any problems. You can create TimescaleDB after installing 11.4 and then upgrading, or after upgrading to 11.5.

If you aren't using EnterpriseDB's installer and are having the problem, please let me know

**Comment by suspended** [comment]
I can reproduce this issue on Windows 10 1903, Postgres 11.5 too. Rob's workaround works.

**Comment by cristihcd** [comment]
You would need `libeay32.dll` and `ssleay32.dll` from the bin folder of the 11.4 installation. 

Zip file downloadable from here: https://get.enterprisedb.com/postgresql/postgresql-11.4-1-windows-x64-binaries.zip

**Comment by gbulfon1** [comment]
Hi, I get same problem with pg 10.10.1 binaries and TS 10.1.4.2

**Comment by RobAtticus** [comment]
@gbulfon1 You may need to do a similar thing for PG10, start with 10.9 and then upgrade. This seems like the right binary:
https://get.enterprisedb.com/postgresql/postgresql-10.9-3-windows-x64.exe

**Comment by gbulfon1** [comment]
Thank you for the response. Rob, I am working with a binaries. I don't see 10.9 version into the Download PostgreSQL Binaries page (https://www.enterprisedb.com/download-postgresql-binaries) . Can you explain me where download ?

**Comment by RobAtticus** [comment]
@gbulfon1 Posted it in my previous comment, but here is the link to the .exe:
https://get.enterprisedb.com/postgresql/postgresql-10.9-3-windows-x64.exe

I basically just took the URL for 10.10 and changed it to 10.9. I don't think it is still currently linked anywhere

**Comment by gbulfon1** [comment]
I am sorry. I am need the binaries indeed installer. I can't use installer in this server. Look at reference page, its a binary (https://www.enterprisedb.com/download-postgresql-binaries). May be I am not understand you.

**Comment by RobAtticus** [comment]
I see, then in that case, the link is:
https://get.enterprisedb.com/postgresql/postgresql-10.9-3-windows-x64-binaries.zip

That gives you the same zip files, only for 10.9

**Comment by 0xADD1E** [comment]
I also encountered this, and was able to solve it with copying bin/libeay32.dll and bin/ssleay32.dll from an older archive. 

Does anyone know if this should be considered a bug with EnterpriseDB or if timescale itself should be shipping with these dependencies?

**Comment by SaynHolems** [comment]
well, I find that PostgreSQL v11.6 has the same BUG with v11.5.
So, we should copy these binaries `libeay32.dll` and `ssleay32.dll`  and add then into bin file of PostgreSQL
It troubled me for a long time from v11.5 to v11.6, wasting time to try other ways to repair the PostgreSQL, because I did not expect that the same problem will be retained after the version uploaded.

**Comment by tylerfontaine** [comment]
This seems to be related to a name change for these DLLs in OpenSSL 1.1.0 - https://mta.openssl.org/pipermail/openssl-users/2017-June/005977.html

And more here: https://github.com/openssl/openssl/issues/10332#issuecomment-549027653

It seems that EnterpriseDB started using the newer openSSL binaries (or possibly, upstream postgres did, and this just followed through into the windows packaging that EnterpriseDB does), and as such no longer has the libeay32.dll and ssleay32.dll files. It seems as if this change is late for the windows openSSL binaries, which might explain why it wasn't a problem until just recently.

**Comment by rishikesan-vunet** [comment]
Cannot load timescale in PG 11.9 using windows 7, Pg and timescale installation was smooth, but not able to enable the timescaledb extension. As mentioned in the earlier comments, I downloaded an 11.4 and added the missing DLLs in my 11.9 bin( those exact files were missing in here as well). But still cannot load, please  help

**Comment by hnazkani** [comment]
Same issue with Postgresql 13, Windows 10, timescaledb-postgresql-13_2.1.0-windows-amd64

**Comment by hnazkani** [comment]
Changing shared_preload_libraries (in postgresql/13/data/postgresql.conf ) from 
-->  #shared_preload_libraries = ' ' 
to 
--> shared_preload_libraries = 'timescaledb'
solved the issue for me, in case helpful for anybody. 
You will have to restart the postgresql server.

**Comment by erimatnor** [comment]
The need to preload the library is part of our installation instructions for Windows: https://docs.timescale.com/latest/getting-started/installation/windows/installation-windows

Seems like this resolves the issue. Please reopen the issue if the issue remains.

**Comment by Neoracle** [comment]
timescaledb=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not load library "C:/Program Files/PostgreSQL/15/lib/timescaledb-2.9.1.dll": The specified module could not be found.

Still can not create extension in PG 15.1.
Have copied ssleay32.dll and libeay32.dll into bin folder.
Also have shared_preload_libraries = 'timescaledb' in the postgresql.conf

Any help pls?

**Comment by Neoracle** [comment]
@erimatnor would you please re-open the issue?

**Comment by mahipv** [comment]
Hi,

We need version 1.1.1 of ssleay32.dll and libeay32.dll. 

Can you please confirm that the dlls copied are of  version 1.1.1?  If not, can you try with the version 1.1.1 libs from 

https://kb.firedaemon.com/support/solutions/articles/4000121705-openssl-3-0-and-1-1-1-binary-distributions-for-microsoft-windows

If  version is the issue, then this is same as https://github.com/timescale/timescaledb/issues/5125

**Comment by el-gif** [comment]
In my case with PG 15.1, timescaledb 2.9.1 and Windows 11 I could fix the error "FEHLER: konnte Bibliothek »C:/Program Files/PostgreSQL/15/lib/timescaledb-2.9.1.dll« nicht laden: The specified module could not be found." by copying version 1.1.1 of libcrypto-1_1-x64.dll and libssl-1_1-x64.dll to C:\Program Files\PostgreSQL\15\bin.
I obtained them from C:\Users\alexa\Downloads\openssl-1.1.1s\openssl-1.1\x64\bin after downloading OpenSSL 1.1.1 as suggested.
The version 3 of these files (libcrypto-3-x64 and libssl-3-x64), which already existed under the path C:\Program Files\PostgreSQL\15\bin, don't seem to have worked.

**Comment by mahipv** [comment]
Hi,
Thanks a lot for the confirmation. The PG15 windows packaging issue is being worked on.

**Comment by yuretz** [comment]
@mahipv Why is this closed if it's still an issue and how then should we find out when it is actually fixed?
