### ISSUE TITLE
Integrate with Pipelinedb?

### ISSUE THREAD

**Issue by pyros2097** [timescale/timescaledb#14]
Is it possible to add this postgres extension to pipelinedb and use the table/hyper to process continuous streams in pipelinedb thereby making the event data scalable in it and also being able to query it continously at a very large scale.
https://github.com/pipelinedb/pipelinedb

**Comment by stalltron** [comment]
We haven't tested integration with PipelineDB yet but once they release their extension, it shouldn't be that difficult.

**Comment by derekjn** [comment]
> We haven't tested integration with PipelineDB yet but once they release their extension, it shouldn't be that difficult.

We're working hard on the extension refactor, and we look forward to working with you guys to figure out an easy, legitimate way for users to synergize our extensions.

**Comment by balupton** [comment]
Hate to post on an old issue, but perhaps this issue has been lost in the sands of time. Has there been any status updates since April 2017?

**Comment by stalltron** [comment]
Hi @balupton we're still waiting on PipelineDB to refactor as a PostgreSQL extension. Uncertain as to their progress / status.

**Comment by joshhopkins** [comment]
Just heard from Jeff Ferguson | PipelineDB via email – they're actively working on the PostgreSQL extension refactor now and it should be completed this quarter.

**Comment by allan-simon** [comment]
https://www.pipelinedb.com/blog/pipelinedb-1-0-0-high-performance-time-series-aggregation-for-postgresql  pipelinedb is now an extension \o/

**Comment by eugene-bright** [comment]
The other side of the fence.
https://github.com/pipelinedb/pipelinedb/issues/1876

**Comment by windbender** [comment]
I too would LOVE LOVE LOVE this combination.  

Honestly, it might be worthwhile to consider merging these two projects. Keep them functional on their own via configuration, but maintain and release them together.

**Comment by pratikpparikh** [comment]
@derekjn @stalltron is this being looked at?

**Comment by dianasaur323** [comment]
@pratikpparikh @windbender @eugene-bright @allan-simon @joshhopkins @balupton It's been a while coming, but looking into whether or not it makes sense for us to integrate better here. Anyone willing to share use cases on when they need PipelineDB + TimescaleDB? Also, if you'd prefer to do this over a call, I'm available at diana at timescale.com

**Comment by pratikpparikh** [comment]
@dianasaur323 I have time on monday to connect via call or email.

**Comment by dianasaur323** [comment]
@pratikpparikh that would be great! Mind emailing me at diana at timescale.com so that I can schedule a time with you?

**Comment by joaocc** [comment]
Any news on this topic? Thanks!

**Comment by ancoron** [comment]
My use-cases:
Tracking data (e.g. from sensors) in TimescaleDB (and used for ad-hoc queries - detailed insights) but PipelineDB used for configured (= known queries) Dashboards and reporting. As you'd need the actual raw data to create useful views for a dashboard in an exploratory way, TimescaleDB is required.

Also you'd sometimes want to prove that the data in the generated reports are actually correct, which is why you'd need the raw data (or to fix some historical errors and rebuild the PipelineDB aggregates).

I am currently living with the triggers option but that feels inefficient.

**Comment by pratikpparikh** [comment]
my usecase is very similar to @ancoron more of a data lineage and master data management.

**Comment by jonathan-s** [comment]
Given that pipelinedb is now dead in the water(?), (the team joined confluent, and pipelinedb will be stuck at 1.0). I wonder how this will proceed. Will timescaledb pick up the features at pipelinedb?

**Comment by dianasaur323** [comment]
@jonathan-s we haven't decided to take up pipelinedb, but would love to see where the community takes this. That being said, definitely try out our new continuous aggregates feature to see if it meets part of your needs.

**Comment by ancoron** [comment]
There really is work going on to eliminate the need for PipelineDB and have continuous aggregates a first-class citizen as of 1.3.0: https://github.com/timescale/timescaledb/issues/1179#issuecomment-489739724

**Comment by joshhopkins** [comment]
PinelineDB [also recommends](https://www.pipelinedb.com/blog/pipelinedb-is-joining-confluent) Timescale's continuous aggregates as an alternative.

**Comment by hedayat** [comment]
It'd be great if timescaledb will also include pipelinedb aggregates:
http://docs.pipelinedb.com/aggregates.html

**Comment by dianasaur323** [comment]
Since we've released continuous aggregates and PipelineDB isn't going to be updating with new versions, I'm going to go ahead and close out!
