### ISSUE TITLE
how can i create a db and table and insert datas by using c++

### ISSUE THREAD

**Issue by NOCANNOBB** [timescale/timescaledb#1403]
how can i create a db and table and insert datas by using c++ programe,can someone give some Courses, i cannot find on internet

**Comment by mfreed** [comment]
Hi @NOCANNOBB ,

You connect to and interact with TimescaleDB in the same manner as PostgreSQL.  

For an example, please see some PG examples:

https://www.postgresql.org/docs/current/ecpg-cpp.html

**Comment by NOCANNOBB** [comment]
hi @mfreed
i followed this :
https://docs.timescale.com/latest/getting-started/creating-hypertables
create a table and transform it into a hypertable with create_hypertable, then insert 50000 data,but it cost 25s, its takes too long.its normally? i did like this:
for(int i = 0; i < 50000; i++)
{
     const char* SQL3 = "INSERT INTO conditions(time, location, temperature)VALUES (NOW(), 'office', 70.0);";
     if(ExecSQL(conn,SQL3)){
	}
}

**Comment by mfreed** [comment]
You are executed 50,000 *separate* SQL requests, and given your code, you might not even be reusing connections.

Strongly recommend for high throughput to create minibatches when inserting, e.g., 1000+ rows per INSERT.

**Comment by NOCANNOBB** [comment]
it's ok now,thanks for ur help
