### ISSUE TITLE
Unable to load timescaledb-1.3.2.dll when creating an EXTENSION

### ISSUE THREAD

**Issue by AnderssonDavid** [timescale/timescaledb#1410]
**Relevant system information:**
 - OS: [Windows 10 x64, ]
 - PostgreSQL version 11.5
 - TimescaleDB version 1.3.2
 - Installation method: I used the Setup.exe in the TimescaleDB ZIP folder

I have installed PostgreSQL 11.5 without any problems. Executing the TimescaleDB setup goes fine.
When I'm successfully connected to my database and enter "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;", in the commandline, I get the following error:

ERROR:  could not load library "C:/Program Files/PostgreSQL/11/lib/timescaledb-1.3.2.dll": The specified module could not be found.

When I manually browse to that folder, the file timescaledb-1.3.2.dll do exsist there. So the TimescaleDB setup has successfully copied the file there.

![Capture](https://user-images.githubusercontent.com/54407431/63524759-39fe8280-c505-11e9-912c-d7300f33e503.PNG)

**Comment by dianasaur323** [comment]
Looks like someone else had a similar issue that was solved by doing what is described in this issue: mind trying that? https://github.com/timescale/timescaledb/issues/510

**Comment by solugebefola** [comment]
Also #1398 for PostgreSQL 11.5 issues.  We are working on a fix 🔧

**Comment by solugebefola** [comment]
Are you using PostgreSQL from an EnterpriseDB distribution?

**Comment by AnderssonDavid** [comment]
@dianasaur323 I had these installed on my PC
![Installd_c++](https://user-images.githubusercontent.com/54407431/63572586-e2572a00-c58b-11e9-8861-174d9b95fa78.PNG)


@solugebefola 
"Are you using PostgreSQL from an EnterpriseDB distribution?"
A: Yes I was.

"Also #1398 "
Thank you. The workaround described by [RobAtticus](https://github.com/timescale/timescaledb/issues/1398#issuecomment-521376201) worked for me.
I uninstalled PG 11.5 and then installed PG 11.4-3 instead. 
![CreatedDB](https://user-images.githubusercontent.com/54407431/63572563-d4090e00-c58b-11e9-9252-5872ed5abfbe.PNG)
