### ISSUE TITLE
Can we enable sql trace for a specific postgresql session or at system wide?

### ISSUE THREAD

**Issue by booncheow** [timescale/timescaledb#1413]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by booncheow** [comment]
In oracle, to trace a specific session, we can run:
ALTER SESSION SET SQL_TRACE = TRUE; or
EXECUTE DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(sid,serial#,TRUE);

To enable SQL tracing at system wide,
alter system set events '10046 trace name context forever,level 12';

Does Postgresql server have similar features and commands?

**Comment by booncheow** [comment]
For now it appears if apps owner can run -- explain or explain analyze on the problematic query will be easier.

Thank you.

**Comment by bboule** [comment]
@booncheow am going to close this out as it seems like you have a solution, if you need more information please feel free to re-open
