### ISSUE TITLE
How to deal with time that is not always unique

### ISSUE THREAD

**Issue by TimonPost** [timescale/timescaledb#1415]
Hello, we have a time field, it may happen that the time of this field in specific cases is the same, and of course, that is not allowed. We have to make this unique somehow, is there something I have to pay attention to and do you have any tips?

**Comment by blagojts** [comment]
You can utilize a UNIQUE constraint on the time column? Also we suggest you visit our public slack (timescaledb.slack.com) for questions like this, where the community can answer more quickly.

**Comment by TimonPost** [comment]
Thanks for the answers, upsert will be usefull here, https://github.com/artiomchi/FlexLabs.Upsert, thanks for the help!
