### ISSUE TITLE
install two versions of TimescaleDB on same machine

### ISSUE THREAD

**Issue by bowguy** [timescale/timescaledb#1417]
**Relevant system information:**
 - OS: Windows Server 2016
 - PostgreSQL version "PostgreSQL 11.5, compiled by Visual C++ build 1914, 64-bit"
 - PostgreSQL version "PostgreSQL 9.6.5, compiled by Visual C++ build 1800, 64-bit"

 - TimescaleDB version 1.0.0
Trying to install TimescaleDB timescaledb-postgresql-11_1.4.1-windows-amd64 on the 11 version

**Describe the bug**
Conflict with the existing 9.6 version of TimescaleDB.

**To Reproduce**
Running setup.exe from timescaledb-1.4.1 gives:
 ERROR: could not copy file 'timescaledb.dll': open C:/PROGRA~1/POSTGR~1/9.6/lib/timescaledb.dll: The process cannot access the file because it is being used by another process.
Press ENTER/Return key to close...

Both versions running fine on different ports.

**Comment by bboule** [comment]
@JLockerman @cevian any thoughts?

**Comment by RobAtticus** [comment]
Hey @bowguy , sorry this is a bit late.

In order to get this to work, you need to pass a flag when you run `setup.exe` to point to the correct `pg_config`:
```
setup.exe --pgconfig="C:/path/to/pg11/bin/pg_config
```

This should find the correct PG instance.

**Comment by mfreed** [comment]
Is this a bug then @RobAtticus ?

**Comment by RobAtticus** [comment]
Left it as a bug until we get confirmation on whether my fix works or not.

**Comment by aimtsou** [comment]
Hi,

following on that, i want to have multiple timescaledb versions in one linux host. If i do 
./bootstrap -DPG_CONFIG=/path/to/pg_config

Will it be enough for installing it or there are going to be libraries and paths which overwrite each other?

**Comment by mfreed** [comment]
@aimtsou Have you followed @RobAtticus 's instructions?

**Comment by cevian** [comment]
@aimtsou I think that should work.

**Comment by cevian** [comment]
I believe this issue has been resolved by @RobAtticus's comment. If it persists please ping me or reopen issue.

**Comment by aimtsou** [comment]
@cevian: I think my question was not interpreted correctly. Supposing that we have 2 editions of Postgres in our host let's say 9.x and 11.x. By checking the 2 rpms of timescaledb I see these:

`rpm2cpio timescaledb-postgresql-9.6-1.5.1-0.el7.x86_64.rpm | cpio -idmv 
./usr/lib64/timescaledb/timescaledb--0.1.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.10.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.10.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.11.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.12.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.12.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.2.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.3.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.5.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.6.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.6.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.7.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.7.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.8.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc3--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.1.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.1.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.5.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.5.1.sql
./usr/lib64/timescaledb/timescaledb-1.5.1.so
./usr/lib64/timescaledb/timescaledb-tsl-1.5.1.so
./usr/lib64/timescaledb/timescaledb.control
./usr/lib64/timescaledb/timescaledb.so
9563 blocks`

By checking the rpm for version 11

`rpm2cpio timescaledb-postgresql-11-1.5.1-0.el7.x86_64.rpm | cpio -idmv 
./usr/lib64/timescaledb/timescaledb--0.1.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.10.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.10.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.11.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.12.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.12.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.2.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.3.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.4.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.5.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.6.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.6.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.7.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.7.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.8.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--0.9.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.0-rc3--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.0.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.1.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.1.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.2.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.3.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.1--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.4.2--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.5.0--1.5.1.sql
./usr/lib64/timescaledb/timescaledb--1.5.1.sql
./usr/lib64/timescaledb/timescaledb-1.5.1.so
./usr/lib64/timescaledb/timescaledb-tsl-1.5.1.so
./usr/lib64/timescaledb/timescaledb.control
./usr/lib64/timescaledb/timescaledb.so
9571 blocks`

So the rpm from version 9.x installs at the same path the libraries as the version from 11.x

```
ls -la ./usr/lib64/timescaledb/timescaledb.so   ../usr/lib64/timescaledb/timescaledb.so 
-rwxr-xr-x. 1 root root 41304 Nov 12 19:28 ./usr/lib64/timescaledb/timescaledb.so
-rwxr-xr-x. 1 root root 41280 Nov 12 19:21 ../usr/lib64/timescaledb/timescaledb.so
```

Although the libraries are different in size and hash. So how can you have 2 different versions of timescaledb in one host if they are overwriting each other? Providing the path to pg_config won't be enough. Am I right?
