### ISSUE TITLE
 "C:/Program Files/PostgreSQL/11/lib/timescaledb-1.4.1.dll":%1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Robinsir** [timescale/timescaledb#1426]
**Relevant system information:**
 - OS: [ Windows 10 x64, ]
 - PostgreSQL version : [11.5]
 - TimescaleDB version [1.4.1]
 - Installation method: [zip]

**Describe the bug**

postgres=# \c test1
您现在已经连接到数据库 "test1",用户 "postgres".
test1=# create extension if not exists timescaledb cascade;
错误:  无法加载库 "C:/Program Files/PostgreSQL/11/lib/timescaledb-1.4.1.dll": %1 is not a valid Win32 application.

My Postgre Version 
![image](https://user-images.githubusercontent.com/18422742/64142738-e282df80-ce3f-11e9-8603-b2e90c91a5bf.png)

**Comment by mfreed** [comment]
Hi @Robinsir :  Did you install Postgres via a build from EnterpriseDB, or something else?  Or could you say more about how you got both PG and TimescaleDB?

**Comment by Robinsir** [comment]
> Hi @Robinsir : Did you install Postgres via a build from EnterpriseDB, or something else? Or could you say more about how you got both PG and TimescaleDB?
> 
> (See #1398)

@mfreed Thank you very much for your reply. I downloaded both from the official website.
PG:https://get.enterprisedb.com/postgresql/postgresql-11.5-1-windows-x64.exe
TimescaleDB:https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-11_1.4.1-windows-amd64.zip
I'm trying to use the old version postgresql.

**Comment by Robinsir** [comment]
![image](https://user-images.githubusercontent.com/18422742/64146247-ca668c80-ce4e-11e9-8f4e-e9301ea77bfe.png)
finally, It works!
use https://get.enterprisedb.com/postgresql/postgresql-11.4-3-windows-x64.exe 
I try postgredb 11.1 and 11.5. It don't work,only 11.4.3 works.
It's a great project and I'll keep my eye on it.

**Comment by vivekanandsh** [comment]
Hello, 
This is really troublesome for using specific version. I installed PostgreSQL 11.6 and installed back 11.4.3 now Pgadmin4 not working.  
Better make and quck release for production with latest PG12 version compatible version TimescaleDB and release asap. 
Waiting for response.

**Comment by vivekanandsh** [comment]
I installed PostgreSQL 11.6  and installed Timescaledb-1.4.2  dint work.   Error is when try to create hypertable display **error saying din't load extension** 

Note : after running SQL command   **CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;** extension is installed/initiated successfully.   
Only when try to create hypertable says above error. 

I tried to to copy  ssleay32.dll and libeay32.dll from **postgresql-11.4-1-windows-x64-binaries\pgsql** to   Postgresql installed bin folder  **C:\Program Files\PostgreSQL\11\bin**  , till dint work.
Looks some major issue with PG version and timescaledb version.    Please fix and release asap. 
Until any work with postgresql-11.6-1-windows-x64 quickly let us know steps. 
Waiting for response.
