### ISSUE TITLE
Table corruption issue when dropping & adding column with same name

### ISSUE THREAD

**Issue by ryan-shaw** [timescale/timescaledb#1427]
**Relevant system information:**
 - OS: Docker ubuntu 16.04
 - PostgreSQL version (output of `postgres --version`): 9.6.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.1
 - Installation method: source

**Describe the bug**
When dropping and re-adding a column with the same name a corruption occurs within postgres internals resulting in an error similar to `ERROR:  attribute number 4 exceeds number of columns 3`

**To Reproduce**

On a clean database:
```sql
CREATE TABLE orig (
    id INT,
    timestamp TIMESTAMP
);

SELECT create_hypertable('orig', 'timestamp');

ALTER TABLE orig ADD COLUMN meta JSONB;

SELECT * FROM pg_attribute WHERE attname = 'meta';

-- Store relid for later
SELECT attrelid INTO attrelid FROM pg_attribute WHERE attname = 'meta';

ALTER TABLE orig DROP COLUMN meta;

-- View table attributes
--SELECT * FROM pg_attribute WHERE attrelid = (SELECT attrelid FROM attrelid);

ALTER TABLE orig ADD COLUMN meta JSONB;

CREATE INDEX tag_idx ON orig USING gin ((meta->'tag'));

INSERT INTO orig (id, timestamp, meta) VALUES (1, '2019-01-1', '{"test": 1}');
```

I ran this without the create_hypertable in vanilla postgres and it worked as expected

**Expected behavior**
No error

**Actual behavior**
Table corruption

**Comment by ryan-shaw** [comment]
Just to note I don't think jsonb or the index has anything to do with this- it's just how I uncovered the corruption

**Comment by svenklemm** [comment]
@ryan-shaw only the index is corrupt if you drop the index INSERTs should start working again
