### ISSUE TITLE
Continuous aggregates don't handle late arriving data well

### ISSUE THREAD

**Issue by andness** [timescale/timescaledb#1428]
When old data in a continuous aggregate is invalidated the subsequent recomputation of aggregates does not take into account `max_interval_per_job`. 

In my case I have a continuous aggregate covering 2 years of data, and because the source of the metrics are IoT devices out in the field which have variable connectivity we sometimes have metrics arriving very late. In one example the data was close to 2 months old.

When this happens the continuous aggregate refresh fails due to not having enough memory to process such a large set of data in one operation. The only workaround is to drop and recreate the continuous aggregate.

This prevents us from using continuous aggregates which is a big disappointment.

**Comment by gayyappan** [comment]
view defn:
``` create view collar_metric_hour with (timescaledb.continuous, timescaledb.refresh_lag = '0', timescaledb.refresh_interval = '1h') as
 select
   time_bucket('1h', time) as time,
   collar_id,
   sum(coalesce(charge_mah, 0)) as charge_mah,
   sum(coalesce(gprs_errors, 0)) as gprs_errors,
   min(battery_voltage) as min_battery,
   max(battery_voltage) as max_battery,
   coalesce(sum(hab_resting_time), 0) as resting_time,
   coalesce(sum(hab_walking_time), 0) as walking_time,
   coalesce(sum(hab_running_time), 0) as running_time,
   coalesce(sum(hab_grazing_time), 0) as grazing_time,
   coalesce(sum(hab_unknown_time), 0) as unknown_time,
   coalesce(sum(hab_walking_dist), 0) as walking_dist,
   coalesce(sum(hab_running_dist), 0) as running_dist,
   coalesce(sum(hab_step_counter), 0) as step_counter,
   coalesce(sum(hz_beacon_zone_time), 0) as zone_beacon,
   coalesce(sum(hz_in_sleep_time), 0) as zone_sleep,
   coalesce(sum(hz_no_zone_time), 0) as zone_no,
   coalesce(sum(hz_psm_zone_time), 0) zone_psm,
   coalesce(sum(hz_caution_zone_time), 0) as zone_caution,
   coalesce(sum(hz_max_zone_time), 0) as zone_max,
   min(rssi_min) as rssi_min,
   max(rssi_max) as rssi_max,
   avg(rssi_min) as rssi_min_avg,
   avg(rssi_max) as rssi_max_avg,
   min(gps_height_min) as gps_height_min,
   max(gps_height_max) as gps_height_max,
   min(baro_height_min) as baro_height_min,
   max(baro_height_max) as baro_height_max
 from collar_metric
 group by time_bucket('1h', time), collar_id;
```
Failing SQL with OOM
``` INSERT INTO _timescaledb_internal._materialized_hypertable_46 SELECT * FROM _timescaledb_internal._partial_view_46 AS I WHERE I."time" >= '2018-07-03 18:00:00+00' AND I."time" < '2019-08-31 09:00:00+00'  ```

**Comment by gayyappan** [comment]
stats output:
```
select * from timescaledb_information.continuous_aggregate_stats;
-[ RECORD 1 ]----------+------------------------------
view_name              | collar_metric_hour
completed_threshold    | 2019-08-30 13:00:00+00
invalidation_threshold | 2019-08-31 09:00:00+00
job_id                 | 1000
last_run_started_at    | 2019-08-31 13:47:23.738756+00
last_run_status        | Failed
job_status             | scheduled
last_run_duration      | 00:01:06.4288
next_scheduled_run     | 2019-08-31 18:48:30.167556+00
total_runs             | 738
total_successes        | 731
total_failures         | 7
total_crashes          | 0
```

**Comment by gayyappan** [comment]
@andness Could you add some information about the hypertable's chunk ranges?
\d+ <hypertable_name> gives you the names of the chunks
\d+ _timescaledb_internal.<chunk_name> shows the chunk details and that includes the range.
(don't need details for all the chunks , a couple will do).
Thanks.

**Comment by andness** [comment]
Unfortunately no, I'm afraid I had to delete the view because the refresh job was causing the server to become unresponsive due to memory pressure. If it will be very helpful to have this information I can recreate the view to get that data and then delete it immediately afterwards.

**Comment by gayyappan** [comment]
@andness Could you give me the chunk range  for the hypertable on which the continuous agg was defined i.e. collar_metric in your case.

**Comment by erimatnor** [comment]
Closing since TimescaleDB 2.0 is released with significant updates to continuous aggregates to address issues related to late-arriving data. PR #2926 aims to improve things further. Feel free to reopen if issues remain.
