### ISSUE TITLE
Timescale DB with negative refresh lag do not update themselves

### ISSUE THREAD

**Issue by baid86** [timescale/timescaledb#1431]
My table and view is like
```
CREATE TABLE metrices (
      etime  TIMESTAMPTZ       NOT NULL,
      mac         TEXT              NOT NULL,
      wlan            TEXT  NOT NULL,
      ap_grp            TEXT  NOT NULL,
      site            TEXT  NOT NULL,
      customer            TEXT  NOT NULL,
      msp            TEXT  NOT NULL,
      rx            INT  NOT NULL,
      tx            INT  NOT NULL,
      id            SERIAL,
      PRIMARY KEY(etime, mac)
);
SELECT create_hypertable('metrices', 'etime');


CREATE VIEW device_summary_hourly
WITH (timescaledb.continuous, timescaledb.refresh_lag='-1 hour') 
AS
SELECT
  time_bucket('1 hour', etime) as bucket, 
  mac,
  max(tx) - min(tx) as tx_spread,
  max(rx) - min(rx) as rx_spread,
  avg(tx) as tx_avg, 
  avg(rx) as rx_avg 
FROM
  metrices
GROUP BY bucket, mac;
```
So now I expect my table to updated with every insert as mentioned in API guide.

> if refresh_lag is set to -<bucket_width>, the continuous aggregate will run whenever new data is received,

If I update the view forcefully it works.

**Comment by blagojts** [comment]
Can you tell what you mean by "update the view forcefully"?

**Comment by gayyappan** [comment]
@baid86 Could you please post output from timescaledb_information.continuous_aggregates and timescaledb_information.continuous_aggregate_stats for the view here?
Also what is the output for ``` select max(etime)  from metrics; ```

**Comment by rmv04** [comment]
Hello,
I have the same problem. I have set the refresh_lag to -<bucket_width> and I expect that as soon as data are inserted in the hypertable, the continuous aggregate view will be refreshed immediatly. But it doesn't refresh, the view is only refreshed after the refresh_interval is ellapsed.
What does the documentation really means with:
`if refresh_lag is set to -<bucket_width>, the continuous aggregate will run whenever new data is received.`

**Comment by cevian** [comment]
@rmv04 @baid86 This is a documentation bug. Documentation should say `if refresh_lag is set to -<bucket_width>, the continuous aggregate will aggregate all the data in the table every time the background job runs (every refresh_interval, on average).` Please note we are planning to add a feature to provide fully up-to-date views in release 1.6.

**Comment by rmv04** [comment]
@cevian Thank you for your reply.

**Comment by mkindahl** [comment]
Documentation was updated to clarify how `refresh_lag` affect the view, so closing the issue. Changes to the semantics will be handled in a different issue.
