### ISSUE TITLE
Multiple continuous aggregates per hypertable fails

### ISSUE THREAD

**Issue by oJshua** [timescale/timescaledb#1440]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version: 11.5 (oss)
 - TimescaleDB version: 1.4.2
 - Installation method: using Docker (tag: 1.4.2-pg11-oss)

**Describe the bug**
I'm having an issue creating more than one continuous aggregate per hypertable.

**To Reproduce**
1. Create first continuous aggregate:
`
        CREATE VIEW candle5m
        WITH (
            timescaledb.continuous,
            timescaledb.refresh_lag = '-5m'
        )
        AS
        SELECT
            exchange,
            pair,
            time_bucket('5 min', time) AS bucket,
            min(low) as low,
            max(high) as high,
            first(open, time) as open,
            last(close, time) as close,
            sum(volume) as volume
        FROM candle
        GROUP BY bucket, exchange, pair 
`

2. Create second continuous aggregate:
`
        CREATE VIEW candle15m
        WITH (
            timescaledb.continuous,
            timescaledb.refresh_lag = '-15m'
        )
        AS
        SELECT
            exchange,
            pair,
            time_bucket('15 min', time) AS bucket,
            min(low) as low,
            max(high) as high,
            first(open, time) as open,
            last(close, time) as close,
            sum(volume) as volume
        FROM candle
        GROUP BY bucket, exchange, pair 
`

**Expected behavior**
Expected this to be supported in Timescale versions >= 1.4.0

**Actual behavior**
ERROR 0A000 - hypertables currently only support a single continuous aggregate. Drop the other continuous aggregate to add a new one.

**Additional context**
Hopefully I'm not missing anything in the docs!

**Comment by mfreed** [comment]
Hi @oJshua Just to make sure that's not the issue, can you paste the output of 

```\dx timescaledb```

Thanks!

**Comment by oJshua** [comment]
Oh wow, interesting! I guess I should pick another image or install it myself? 

`
                                    List of installed extensions
    Name     | Version | Schema |                            Description                            
-------------+---------+--------+-------------------------------------------------------------------
 timescaledb | 1.3.0   | public | Enables scalable inserts and complex queries for time-series data
(1 row)
`

**Comment by oJshua** [comment]
Marking this closed. Thanks for your help!

@RobAtticus am I configuring the docker image incorrectly?
