### ISSUE TITLE
could not load library timescaledb-1.4.2.dll The specified procedure could not be found.

### ISSUE THREAD

**Issue by edisonch** [timescale/timescaledb#1445]
Hi,
I have successfully install timescaledb in Windows 10 with Postgresql 10.7. I check all the needed dll for timescaledb is there (timescaledb.dll, timescaledb-1.4.2.dll, timescaledb-tsl-1.4.2dll). I have even restart Windows 10 to ensure everything is loaded properly.

However when I do create extension timescaledb cascade; it always spits out this error:

could not load library "C:/Program Files/PostgreSQL/10/lib/timescaledb-1.4.2.dll": The specified procedure could not be found.

I previously thought that VC 2015 is not installed however when I downloaded and tried to install, Windows 10 refused and said the VC is already installed.

Please Advise.

**Comment by ThomasGauthierr** [comment]
@edisonch I had the same issue with Postgresql **10.5**.
It worked perfectly after **upgrading to 10.10**.

**Comment by k-rus** [comment]
You need to upgrade PostgreSQL version. From [the docs](https://docs.timescale.com/latest/getting-started/installation/windows/installation-windows):
> Note: TimescaleDB requires PostgreSQL 9.6.3+, 10.9+, or 11.4+

**Comment by edisonch** [comment]
Thank you so much for pointing that fact out.
