### ISSUE TITLE
After create_hypertable() with migrate_data true, queries are EXTREMELY slow until VACUUM ANALYSE

### ISSUE THREAD

**Issue by laundmo** [timescale/timescaledb#1457]
**Relevant system information:**
 - OS: openSUSE 15.1 leap
 - PostgreSQL version: 10.6
 - TimescaleDB version: 1.0.0
 - Installation method: zypper in postgresql10-timescaledb

**Describe the bug**
After creating a hypertable using migrate_data True, queries are up to 100x slower than Vanilla PostgreSQL untill using VACUUM ANALYSE

**To Reproduce**
1. create Postgres table with suffecient data
2. SELECT create_hypertable( ... ,migrate_data => TRUE)
3. use any suffeciently complex query
4. compare time to before create_hypertable

**Expected behavior**
create_hypertable with migrate_data True shouldn't require VACUUM ANALYSE, possibly calling VACUUM ANALYS internally

**Actual behavior**
Apparently create_hypertable() with migrate_data True requires calling VACUUM ANALYSE before queries will complete in equal or faster time than PostgreSQL

**Screenshots**
not aplicable

**Additional context**
this may be resolved in a recent version of TimescaleDB, in that case this issue can be closed right away, and server as a reminder to anyone who googles for it.

**Comment by erimatnor** [comment]
AFAIK, it is normal that you'd have to ANALYZE your table to build statistics; in particular after importing a lot of data. Calling ANALYZE internally would just prolong the time it takes to import data.  Perhaps making a note in documentation is enough.

Closing, since the behavior is expected.
