### ISSUE TITLE
Could not load library '.../timescaledb-1.4.2.dll' unknown error 126

### ISSUE THREAD

**Issue by rafaelcamposufsc** [timescale/timescaledb#1458]
I'm setting up the timescaledb in a Windows 10 with PostgreSQL 11.5 and timescabledb 1.4.2. But when I try to create the extension by running  

`CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` 

I got the error 

`could not load library "[..]/PostgreSQL/11/lib/timescaledb-1.4.2.dll": unknown error 126`

The dll file is there but for some reason it cannot be loaded. I've already trying with Postgre 10.10 and got the same issue.

**Comment by darophi** [comment]
Running into same issue. Piggybacking to see if someone knows the resolution to this problem.

**Comment by resoftw** [comment]
check the dependency of the dll using http://dependencywalker.com/
I solved mine, it's the missing ssleay32.dll

**Comment by bboule** [comment]
@rafaelcamposufsc  and @darophi  can you confirm that the missing dll as pointed out by @resoftw fixes this issue for you as well or are you still seeing the issue?

**Comment by cristihcd** [comment]
see https://github.com/timescale/timescaledb/issues/1398#issuecomment-528731198

**Comment by cevian** [comment]
@rafaelcamposufsc did the suggestion in #1398 solve your issue?

**Comment by mkindahl** [comment]
As given in #1613 and #1398 missing to install libraries will cause this issue, in these issues it was missing `ssleay32.dll` and `libeay32.dll`. Closing issue as duplicate of #1613 and #1398. Please reopen if that is not the case.

**Comment by mkindahl** [comment]
As given in #1613 and #1398 missing to install libraries will cause this issue, in these issues it was missing `ssleay32.dll` and `libeay32.dll`. Closing issue as duplicate of #1613 and #1398. Please reopen if that is not the case.
