### ISSUE TITLE
ALTER COLUMN on partitioning column messes up chunk constraints

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#146]
Changing the type of a partitioning column does not update the corresponding constraints on chunks. This makes constraint exclusion fail and leaves the table in a bad state. For instance, here's the table schema of a chunk from a hypertable that had its `time` column changed from `TIMESTAMPTZ` to `TIMESTAMP` (not the mismatching column type and constraint type):

```
postgres=# \d _timescaledb_internal._hyper_1_1_chunk
  Table "_timescaledb_internal._hyper_1_1_chunk"
 Column |            Type             | Modifiers
--------+-----------------------------+-----------
 time   | timestamp without time zone |
 temp   | double precision            |
 color  | integer                     |
Indexes:
    "1-air_time_idx" btree ("time" DESC)
Check constraints:
    "constraint_1" CHECK ("time" >= '2017-07-23 02:00:00+02'::timestamp with time zone AND "time" < '2017-08-22 02:00:00+02'::timestamp with time zone)
```

Unless we can alter also the constraints on all chunks in a safe and performant way, we should probably block `ALTER COLUMN` on partitioning columns.

**Comment by mfreed** [comment]
Fixed in PR https://github.com/timescale/timescaledb/pull/159

**Comment by mfreed** [comment]
Released in https://github.com/timescale/timescaledb/releases/tag/0.5.0
