### ISSUE TITLE
typedef‘Hypertable’    redefinition

### ISSUE THREAD

**Issue by konglingkang123** [timescale/timescaledb#1461]
**Relevant system information:**
 - OS: [Red Hat Enterprise Linux Server release 6.5 (Santiago)]
 - PostgreSQL version (11.5]
 - TimescaleDB version （1.4.2）
 - Installation method: ["source"]

**Describe the bug**
when I compiling TimescaleDB  as the following：
[root@rac1 build]# git checkout 1.4.2
[root@rac1 build]# ./bootstrap   -DUSE_OPENSSL=0
[root@rac1 build]# cd ./build && make

then it output the error as the following:

[ 22%] Generating /root/soft/timescaledb/build/sql/timescaledb--0.4.1--1.4.2.sql
[ 23%] Generating /root/soft/timescaledb/build/sql/timescaledb--0.4.0--1.4.2.sql
[ 23%] Generating /root/soft/timescaledb/build/sql/timescaledb--0.3.0--1.4.2.sql
[ 24%] Generating /root/soft/timescaledb/build/sql/timescaledb--0.2.0--1.4.2.sql
[ 25%] Generating /root/soft/timescaledb/build/sql/timescaledb--0.1.0--1.4.2.sql
[ 25%] Built target sqlupdatescripts
Scanning dependencies of target sqlfile
[ 25%] Generating /root/soft/timescaledb/build/sql/timescaledb--1.4.2.sql
[ 25%] Built target sqlfile
[ 26%] Generating gitcommit.h
Scanning dependencies of target timescaledb
[ 26%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
[ 27%] Building C object src/CMakeFiles/timescaledb.dir/base64_compat.c.o
[ 28%] Building C object src/CMakeFiles/timescaledb.dir/func_cache.c.o
[ 28%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
[ 29%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
In file included from /root/soft/timescaledb/src/hypertable_cache.h:13,
                 from /root/soft/timescaledb/src/cache_invalidate.c:17:
/root/soft/timescaledb/src/hypertable.h:40: error：typedef‘Hypertable’重定义
/root/soft/timescaledb/src/dimension.h:83: 附注：‘Hypertable’的上一个声明在此
make[2]: *** [src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o] 错误 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by medranocalvo** [comment]
See https://github.com/timescale/timescaledb/pull/773.

**Comment by cevian** [comment]
See also #37 . Which version of GCC are you using?

**Comment by medranocalvo** [comment]
`gcc-4.3 (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]`: fails.
`gcc-4.7 (SUSE Linux) 4.7.2 20130108 [gcc-4_7-branch revision 195014]`: works.

**Comment by mfreed** [comment]
Hi @medranocalvo Realize that some folks are running very long LTS versions, but we have decided not to focus on making Timescale compile with very old compilers, e.g., gcc-4.3.4 was released in 2009.

Given overlap with prior reports, closing this out for now and marking as `enhancement` -- although to be honest, it's very low priority for us.
