### ISSUE TITLE
We have created a postgresql cluster with patroni, it is sucessfully created but when we i extends the database with timescaleDB using the command CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;  But it gives an error, we have configured the file postgresql.conf by adding shared_preload_libraries = 'timescaledb' but still it is not working with patroni

### ISSUE THREAD

**Issue by Pravin-kumbhar** [timescale/timescaledb#1463]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by Pravin-kumbhar** [comment]
The erro message is 
testdb=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.
This can be done by editing the config file at: /data/patroni2/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
    # Modify postgresql.conf:
    shared_preload_libraries = 'timescaledb'
Another way to do this, if not preloading other libraries, is with the command:
    echo "shared_preload_libraries = 'timescaledb'" >> /data/patroni2/postgresql.conf
(Will require a database restart.)
If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with:
    SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

**Comment by k-rus** [comment]
The issue was due to `shared_preload_libraries` needs to be set in Patroni configuration for PostgreSQL.

**Comment by Pravin-kumbhar** [comment]
thanks now it is working

**Comment by shreeramk** [comment]
@Pravin-kumbhar how you fixed it could you please explain?

If I manually add to postgresql.conf, on restarting patroni, it gets overwritten .

**Comment by roshan5595** [comment]
@shreeramk Im running into the same scenario.

**Comment by PotapenkoOleg** [comment]
Add this in postgresql section (NOT DCS !)
Doc is here: https://github.com/zalando/patroni/issues/1222
postgresql:
  listen: 192.168.0.15432
  connect_address: 192.168.0.1:5432
  data_dir: /opt/postgres/16/data/
  bin_dir: /usr/pgsql-16/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: rep_user
      password: postgres
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: rep_user
      password: postgres
  parameters:
    shared_preload_libraries: 'citus,pg_cron'
    unix_socket_directories: '/var/run/postgresql, /tmp'
    external_pid_file: '/var/run/postgresql/citus-patroni.pid'
    logging_collector: 'on'
    log_directory: '/opt/postgres/16/log'
    log_filename: 'citus-patroni.log'
