### ISSUE TITLE
locf returning NULL values

### ISSUE THREAD

**Issue by optijon** [timescale/timescaledb#1466]
Hi, 
I'm trying to populate missing values `locf` and I can't seem to get it to work. Can anyone tell me what I'm doing wrong? Here's the query:
```
SELECT time_bucket_gapfill('5 minutes', timestamp) 
    AS five_min, 
    avg((values->>'OAH')::DOUBLE PRECISION) as "OAH", 
    locf(
        avg((values->>'total')::DOUBLE PRECISION), 
        treat_null_as_missing => true
    )  AS "Total" 
    FROM data_values 
    WHERE  timestamp > '2019-05-25 08:35:00+00' 
       AND timestamp < '2019-05-30 11:55:00+00'  
    GROUP BY five_min ORDER BY five_min desc;
```
And the output looks something like this:
```
+------------------------+------------------+-----------------+
| five_min               | OAH              | Total           |
|------------------------+------------------+-----------------|
...
| 2019-05-30 10:55:00+00 | 72.0970916748047 | <null>          |
| 2019-05-30 10:50:00+00 | 71.2554244995117 | <null>          |
| 2019-05-30 10:45:00+00 | 71.0363235473633 | <null>          |
| 2019-05-30 10:40:00+00 | 71.1931228637695 | <null>          |
| 2019-05-30 10:35:00+00 | 71.1931228637695 | <null>          |
| 2019-05-30 10:30:00+00 | 70.8202667236328 | 100.0           |
| 2019-05-30 10:25:00+00 | 70.6398162841797 | <null>          |
...
```
If I add a a start and end date to the function which is outside of the bounds of my `WHERE` statement, it carries the  100.0 value forward for records existing outside of the `WHERE` bounds. It just doesn't seem to be ignoring `NULL` values like I'd expect within the `WHERE` bounds. I've also tried this with JSON data and regular column data and I get the same result. Any help would be greatly appreciated!

**Comment by svenklemm** [comment]
Hmm not sure I understand, locf needs to see an initial value to carry it forward, if it does not see that initial value it will carry forward NULL even if `treat_null_as_missing` is true, only after it has seen an initial value that option will make gapfilling not reset the value to NULL. There is an option to do the lookup for the initial value if its out of the bounds of your normal query. You can specify a subquery as an argument to locf to do the lookup.

https://docs.timescale.com/latest/api#locf

```
dev=# select time_bucket_gapfill(2, time,-2,8), locf(avg(v)::int) FROM (VALUES (0,0),(6,6)) v(time, v) WHERE time BETWEEN 0 AND 6 GROUP BY 1;
 time_bucket_gapfill | locf
---------------------+------
                  -2 |
                   0 |    0
                   2 |    0
                   4 |    0
                   6 |    6
(5 rows)

Time: 1.375 ms
dev=# select time_bucket_gapfill(2, time,-2,8), locf(avg(v)::int,prev:=(SELECT 42)) FROM (VALUES (0,0),(6,6)) v(time, v) WHERE time BETWEEN 0 AND 6 GROUP BY 1;
 time_bucket_gapfill | locf
---------------------+------
                  -2 |   42
                   0 |    0
                   2 |    0
                   4 |    0
                   6 |    6
(5 rows)
```

**Comment by svenklemm** [comment]
@optijon Ok i can reproduce now there seems to be a bug with treat_null_as_missing when the order is DESC, as a workaround you can do the gapfill in a subquery and do the ORDER BY DESC in the outer query.

```
dev=# select * FROM (select time_bucket_gapfill(4, time,-5,13), locf(avg(v)::int,treat_null_as_missing:=true) FROM (VALUES (0,0),(8,NULL)) v(time, v) WHERE time BETWEEN 0 AND 10 GROUP BY 1) i ORDER BY 1 DESC;
 time_bucket_gapfill | locf
---------------------+------
                  12 |    0
                   8 |    0
                   4 |    0
                   0 |    0
                  -4 |
                  -8 |
(6 rows)
```

**Comment by adam-s** [comment]
Can someone please add this to the documentation?

If `locf()` doesn't work, use `treat_null_as_mission:=true`.
