### ISSUE TITLE
VACUUM does not apply to chunks

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#147]
VACUUM / VACUUM ANALYZE / ANALYZE command do not apply down the inheritance hierarchy 

From https://www.postgresql.org/docs/9.6/static/ddl-inherit.html: `Commands that do database maintenance and tuning (e.g., REINDEX, VACUUM) typically only work on individual, physical tables and do not support recursing over inheritance hierarchies.`

The workaround for now is to run these commands `without explicit tables names` (so that they apply to all tables in the database)

**Comment by mfreed** [comment]
Addressed in 0.4.0 release:  https://github.com/timescale/timescaledb/releases/tag/0.4.0
