### ISSUE TITLE
unable to extend timescaledb 

### ISSUE THREAD

**Issue by Pravin-kumbhar** [timescale/timescaledb#1496]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by Pravin-kumbhar** [comment]
CREATE EXTENSION timescaledb; 
but get the error
ERROR:  cache lookup failed for function 1

**Comment by cevian** [comment]
This is a duplicate of #1494. Let's use that as the tracking issue.
