### ISSUE TITLE
Why a final aggregation is required even the aggregation results are already materialized?

### ISSUE THREAD

**Issue by sunbing81** [timescale/timescaledb#1497]
**Relevant system information:**
 - OS: ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 11.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.4
 - Installation method: apt install

**Describe the bug**
Here is a query plan for a simple `select * from what_ever_continuous_aggregation`:
```
GroupAggregate  (cost=104414.97..113806.19 rows=40000 width=48) (actual time=1459.880..2554.860 rows=1215665 loops=1)
  Group Key: _hyper_22_99_chunk.date, _hyper_22_99_chunk.lockid
  ->  Sort  (cost=104414.97..106637.78 rows=889122 width=72) (actual time=1459.848..1677.903 rows=1215665 loops=1)
        Sort Key: _hyper_22_99_chunk.date, _hyper_22_99_chunk.lockid
        Sort Method: external merge  Disk: 55904kB
        ->  Append  (cost=0.00..14476.73 rows=889122 width=72) (actual time=0.024..614.256 rows=1215665 loops=1)
              ->  Seq Scan on _hyper_22_99_chunk  (cost=0.00..8.80 rows=780 width=72) (actual time=0.023..0.025 rows=12 loops=1)
              ->  Seq Scan on _hyper_22_100_chunk  (cost=0.00..8.80 rows=780 width=72) (actual time=0.012..0.014 rows=7 loops=1)
              ->  Seq Scan on _hyper_22_101_chunk  (cost=0.00..8.80 rows=780 width=72) (actual time=0.013..0.013 rows=1 loops=1)
              ->  Seq Scan on _hyper_22_102_chunk  (cost=0.00..8.80 rows=780 width=72) (actual time=0.013..0.014 rows=6 loops=1)
              ->  Seq Scan on _hyper_22_103_chunk  (cost=0.00..9995.92 rows=886002 width=72) (actual time=0.091..471.008 rows=1215639 loops=1)
Planning Time: 1.034 ms
Execution Time: 2628.365 ms
```

Why a final `GroupAggregate` is required? Isn't the aggregation result already materialized somewhere?

**Comment by mfreed** [comment]
@sunbing81 Our continuous aggregations store "partialized" information in the aggregation, not finalized.  For example, the query is an average, it's internally storing the sum and count, not the average (which is computed at finalization time).

This allows us to, e.g., support updating the aggregate when data is received out-of-order, rather than needing to recompute everything.

**Comment by sunbing81** [comment]
Right, now I see why the continuous aggregation requires a parallelizable aggregation function.

Thanks for the explanation.

**Comment by Americas** [comment]
> @sunbing81 Our continuous aggregations store "partialized" information in the aggregation, not finalized. For example, the query is an average, it's internally storing the sum and count, not the average (which is computed at finalization time).
>
> This allows us to, e.g., support updating the aggregate when data is received out-of-order, rather than needing to recompute everything.

I'm not familiar with the internals of TimescaleDB yet, can you further explain what is happening here? In the example you give, if an average is simply stored as the sum and the count of the underlying data, why does this need to aggregate that data? Wouldn't a division suffice? Is out-of-order data updated into the aggregate or inserted into the aggregate? 

I'm still unsure why this aggregation step is needed, and it makes the execution time of a simple select to at least double, even when there is nothing to aggregate.

This feels especially unneeded as I am setting the aggregated view to have a refresh lag equal to it's ignore invalidation interval, so any data that appears out-of-order after that is simply ignored, and the aggregate won't ever change those rows.
