### ISSUE TITLE
Time column as integer type fails with default config ("PGRES_FATAL_ERROR:ERROR value 2592000000000 is out of range")

### ISSUE THREAD

**Issue by darrynv** [timescale/timescaledb#150]
Not sure where the value **2592000000000** is coming from? 

**Background**
CentOS Linux release 7.3.1611 (Core)
Zabbix 3.2
Postgres psql (9.6.3)
timescaledb.x86_64 0.3.0-0.el7.centos

**history (table in backend)**
             Table "public.history"
 Column |     Type      |        Modifiers        
--------+---------------+-------------------------
 itemid | bigint        | not null
 clock  | integer       | not null default 0
 value  | numeric(16,4) | not null default 0.0000
 ns     | integer       | not null default 0
Indexes:
    "history_1" btree (itemid, clock)
    "history_clock_idx" btree (clock DESC)

**Zabbix Server Log**
22713:20170808:232920.043 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  value "2592000000000" is out of range for type integer
CONTEXT:  SQL statement "
                ALTER TABLE _timescaledb_internal._hyper_1_1_chunk
                ADD CONSTRAINT constraint_1 CHECK(
                clock >= '0' AND clock < '2592000000000'
            )
            "
PL/pgSQL function _timescaledb_internal.chunk_add_constraints(integer) line 12 at EXECUTE
SQL statement "SELECT _timescaledb_internal.chunk_add_constraints(chunk_id)"
PL/pgSQL function _timescaledb_internal.chunk_create_table(integer) line 54 at PERFORM
SQL statement "SELECT _timescaledb_internal.chunk_create_table(NEW.id)"
PL/pgSQL function _timescaledb_internal.on_change_chunk() line 7 at PERFORM
SQL statement "WITH chunk AS (
        INSERT INTO _timescaledb_catalog.chunk (id, hypertable_id, schema_name, table_name)
        SELECT seq_id, h.id, h.associated_schema_name,
           format('%s_%s_chunk', h.associated_table_prefix, seq_id)
        FROM
        nextval(pg_get_serial_sequence('_timescaledb_catalog.chunk','id')) seq_id,
        _timescaledb_catalog.hypertable h
        WHERE h.id = hypertable_id
        RETURNING *
    )
    INSERT INTO _timescaledb_catalog.chunk_constraint (dimension_slice_id, chunk_id)
    SELECT slice_id_to_insert, chunk.id FROM chunk, unnest(slice_ids) AS slice_id_to_insert"
PL/pgSQL function _timescaledb_internal.chunk_create_after_lock(integer[],bigint[]) line 52 at SQL statement
SQL statement "SELECT _timescaledb_internal.chunk_create_after_lock(dimension_ids, dimension_values)"
PL/pgSQL function _timescaledb_internal.chunk_create(integer[],bigint[]) line 11 at PERFORM
SQL statement "SELECT * FROM _timescaledb_internal.chunk_create($1, $2)"
 [insert into history (itemid,clock,ns,value) values (23299,1502234959,132565275,99.032366);
]

**Comment by RobAtticus** [comment]
By default the chunk size is set to 30 days, represented as microseconds, which is where the 2592000000000 comes from. Since integer is only 32-bit this does not fit. TimescaleDB should probably pick a different default value if the time column is integer.

If you want to fix this and use the default value of 1 month, you can do this for now:
```sql
SELECT create_hypertable('history', 'clock', chunk_time_interval => 2592000)
```
(assuming the time column is `clock`)

**Comment by darrynv** [comment]
Thanks!

 I can confirm after dropping the databases, recreating it, enabling the extension than creating the hypertables with the **chunk_time_interval** you specified that I now see data being inserted into the tables.

**Comment by mfreed** [comment]
@darrynv This is now supported in today's 0.4.0 release.  Please let us know if you have any other issues (or we'll close this issue out).

https://github.com/timescale/timescaledb/releases/tag/0.4.0
