### ISSUE TITLE
'transaction_per_chunk' doesn't work for parallel index creation

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#1508]
PG11.2, TSDB 1.4.2, CentOs7.6, source build

`CREATE INDEX ON some_large_hypertable USING btree (a, b) WITH (timescaledb.transaction_per_chunk);`

**ERROR:  cannot take query snapshot during a parallel operation**

It looks like parallel index creation is not supported with 'transaction_per_chunk'. However, for many hypertables, Postgres will quickly pick such a plan, since the tables tend to be quite large. I'd imagine almost everyone trying this on real data will run into it.

Work-around is setting:
`alter table some_large_hypertable (parallel_workers = 0);`
But obviously this causes index creation to be a fair bit slower.

**Comment by svenklemm** [comment]
Closing this since this should be fixed in recent versions, feel free to reopen if the issue is still current.

**Comment by kasteph** [comment]
I'm seeing this issue on timescale-2.5 [on the CI](https://app.circleci.com/pipelines/github/filecoin-project/lily/3660/workflows/9da88ed7-e7d3-4637-9d5d-7201723e2a6b/jobs/16594?invite=true#step-114-8).

**Comment by svenklemm** [comment]
You are hitting a general limitation there. You cannot do parallel index creation as part of a transaction. This fails in postgres as well:
```
BEGIN;
CREATE INDEX CONCURRENTLY ON foo(time);
ERROR:  25001: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
LOCATION:  PreventInTransactionBlock, xact.c:3406
```
