### ISSUE TITLE
The continuous aggregate schedule time is set to future time due to system time change.

### ISSUE THREAD

**Issue by rogerdwan** [timescale/timescaledb#1511]
**Relevant system information:**
OS: official docker container(On mac)
PostgreSQL version: 11.4
TimescaleDB version 1.5.0
Installation method: Docker

**Describe the bug**
I'm not sure this should be a bug or not.
But there's a situation that will let continuous agg. job scheduler out of control.

**To Reproduce**
1. Create a continuous aggregates view.
2. Change the system time to the future time(eg. one year later).
3. Wait for the continuous agg. job to start a least once.
4. Change the system time to current time.
5. The job will not execute until time passed one year.

**Additional context**
There should be a method to reset the job scheduler to the correct time event if we change the system time.  
Since this is cause by the os level setting, I'll expect that there's a way to reschedule the background job.

**Comment by gayyappan** [comment]
You can do this in 1.5
SELECT alter_job_schedule(:job_id, next_start => ...);

**Comment by rogerdwan** [comment]
> @rogerdwan You can do this in 1.5
> SELECT alter_job_schedule(:job_id, next_start => ...);

Thank you!

**Comment by bboule** [comment]
Closing this item @rogerdwan if you still face an problem related to this issue please reopen
