### ISSUE TITLE
Cannot change compression settings on hypertable once set.

### ISSUE THREAD

**Issue by gumshoes** [timescale/timescaledb#1520]
TimescaleDB 1.5.0

**To Reproduce**
`ALTER TABLE myhist SET (timescaledb.compress, ...`
compress a chunk
decompress the same chunk
attempt to modify the compression settings:
`ALTER TABLE myhist SET (timescaledb.compress, ...`
observe the error:
`SQL Error [0A000]: ERROR: cannot compress internal compression hypertable`

**Workaround**
`select * from _timescaledb_catalog.hypertable;`
`update _timescaledb_catalog.hypertable set compressed = false where table_name = 'myhist';`

**Comment by cevian** [comment]
Another workaround is running `VACUUM FULL _timescaledb_catalog.hypertable;`. This should also be fixed by #1523 which will be released in 1.5.1

**Comment by mfreed** [comment]
Given the release on 1.5.1, closing this issue.  Please reopen if this doesn't solve your problem @gumshoes .
