### ISSUE TITLE
Windows installer source?

### ISSUE THREAD

**Issue by RSchwoerer** [timescale/timescaledb#1527]
Is the source, or at least the steps, the windows 'setup.exe' installer takes available?

Ideally I'd like to automate or silent the install. 
The step by step yes/no questions are awesome, but I'd like to skip all that and just deploy the binaries in the right places.

Does the installer do any other magic? Thanks.

**Comment by RobAtticus** [comment]
Hi @RSchwoerer, there are some flags that can make the process a bit more automated (and we're working on getting it fully automated):

```
--wait-before-exit (default true), whether to wait for user input before closing
--no-tune (default false), whether to skip timescaledb tune
--yes-tune (default false), run tune without asking
--tune-conf-path, path to postgresql.conf for tune to use
```

It does still ask about tuning settings, but I should have a fix for that relatively soon.

**Comment by RSchwoerer** [comment]
Excellent. Thanks.
I realized I should have tried `setup.exe --help`, which lists all of those (and more) 🤦‍♂️.

(for anyone else looking) I did find [this issue](https://github.com/timescale/timescaledb/issues/721#issuecomment-421595726) which lists where the files go. Maybe replicating something like that in the `README.txt` would help in the future.

**Comment by RobAtticus** [comment]
Hey @RSchwoerer , I've just updated new Windows binaries that include a few more flags. Something like this should give you an "unsupervised" install with tuning:
```
setup.exe --yes-tune --tune-flags="--yes --quiet" --wait-before-exit=false --tune-conf-path="path_to_postgresql.conf"
```

**Comment by RSchwoerer** [comment]
Great! That look like that would work. Thanks!

**Comment by RobAtticus** [comment]
Going to close for now, let me know if you have other issues or questions (and feel free to re-open).

**Comment by RSchwoerer** [comment]
@RobAtticus I was able to test this out with the 1.5.1 release and it works as advertised. Thanks for the help!
