### ISSUE TITLE
float rounding issues with interpolate

### ISSUE THREAD

**Issue by mmouterde** [timescale/timescaledb#1528]
- OS: Ubuntu 12.0-2.pgdg18.04+1
 - PostgreSQL version (output of `postgres --version`): 10.10
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.2
 - Installation method: using Docker

When I use interpolate, the value could vary with no reason.

![Screenshot from 2019-11-08 17-30-35](https://user-images.githubusercontent.com/733538/68493975-d9522c80-024d-11ea-8bd7-ee29cc8633e8.png)

Note that I use not-exact numeric type : double

seen with @cevian

**Comment by cevian** [comment]
Note: This is just float error. We should special-case interpolate where the y0 == y1 to just output y0.
