### ISSUE TITLE
Missing packages (Debian) for arm platforms

### ISSUE THREAD

**Issue by plaes** [timescale/timescaledb#1533]
Currently, the Debian packages (at least for current stable `buster` release) only exist for amd64 platform.

Would it be possible to also start pushing releases for armhf (and arm64) platforms?

**Comment by bboule** [comment]
@RobAtticus Please advise

**Comment by RobAtticus** [comment]
@bboule I think it shouldn't be too hard to do, as long as we run our testing on those platforms _before_ we get to the release process

**Comment by pymenow** [comment]
Looking forward to this on buster and later on bullseye. Please help make it happen @RobAtticus ! this is much needed for IOT

**Comment by mpw-eng** [comment]
[Disclaimer - I'm a real coding novice and just started learning how git works] - I've been using Timescaledb, Postgresql and Grafana on a Windows 10 host, and enjoy tinkering!  I'm now attempting to do the same on a Raspberry Pi4 and can't install timescaledb.  apt finds timescaledb-loader-postgresql-11, but not timescaledb-postgresql-11.  I'm not sure what "loader" even does?
Is there a timescaledb beta I can try on the rp4 armhf arch?

**Comment by tkirchm** [comment]
An apt installer would be great.

**Comment by TrentonBush** [comment]
Similar to mpw-eng, I'm also new at this, so take this with a grain of salt. But I wanted to document my build process in case it helps anyone else. I didn't see any arm64 builds available on apt so had to build from source. 

Host machine: raspberry pi 4 with aarch64 (arm64v8) kernel
OS: ubuntu server 20.04 64 bit
Compiler: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

```
sudo apt install postgresql-12 postgresql-server-dev-12 libkrb5-dev libssl-dev

git clone https://github.com/timescale/timescaledb.git timescaledb
cd timescaledb
git checkout 2.0.0

./bootstrap -DREGRESS_CHECKS=OFF -DWARNINGS_AS_ERRORS=OFF
cd ./build && make  
sudo make install
```

The instructions in the timescale docs were not quite complete, at least for my system. Specifically, I had to figure out a few things from error messages:
* libkrb5-dev and libssl-dev dependencies
* -DREGRESS_CHECKS=OFF
* -DWARNINGS_AS_ERRORS=OFF. The compiler threw a Werror anytime the strncpy function was used, hence the flag.

**Comment by DeoLeung** [comment]
would be best if there's an arm package on the debian registry, to simplify our ci build

**Comment by svenklemm** [comment]
We do have ARM64 packages now, is that what you are asking for?

**Comment by plaes** [comment]
> We do have ARM64 packages now, is that what you are asking for?

When I initially created this issue I was looking for 32-bit (armhf) Debian packages. So, in this sense it's not. But I have also lost the need for it.

**Comment by svenklemm** [comment]
OK I'm closing this then, feel free to reopen if other architectures beside arm64 are still needed.
