### ISSUE TITLE
Incorrect documentation for `timescaledb_information.hypertable`

### ISSUE THREAD

**Issue by ehamberg** [timescale/timescaledb#1534]
[The documentation for `timescaledb_information.hypertable`](https://docs.timescale.com/v1.4/api#timescaledb_information-hypertable) says that it returns `…bytes` columns, but it actually returns pretty-printed sizes such as “99 MB” on TimescaleDB 1.4. (This is also what the sample under the list of columns shows.)

I would actually like to get the values in bytes, but this doesn't seem to be available…

**Comment by erimatnor** [comment]
This seems to be fixed in the 1.5 version of the docs: https://docs.timescale.com/latest/api#utilities

W.r.t. getting values in bytes, you can use the `hypertable_relation_size()` function to get the raw bytes.

**Comment by ehamberg** [comment]
@erimatnor I might be misunderstanding something here, but it doesn't seem to be fixed. These columns are still in the docs, but they aren't returned from `timescaledb_information.hypertable` in 1.5 – including in the example below the table:

<img width="1194" alt="TimescaleDB Docs  API reference utilities" src="https://user-images.githubusercontent.com/16063/72433316-5394b500-3799-11ea-8072-9fcfa78d79a3.png">

`hypertable_relation_size()` does work for this, but it requires first listing the tables, and then querying per table. Not saying this is a problem, but there would be a (small) benefit in having this information in the information one gets from `timescaledb_information.hypertable` from the perspective of a service monitoring TimescaleDB tables in a database.

**Comment by erimatnor** [comment]
@ehamberg Yes, my bad. Thought I looked closely, but must have missed anyway.

**Comment by erimatnor** [comment]
Looks like this was fixed in https://github.com/timescale/docs.timescale.com-content/pull/270/files. Will be in the next release of the docs.

**Comment by erimatnor** [comment]
Closing this issue since docs for 1.6 was released with the fix.
