### ISSUE TITLE
Availability of Timescale/Postgres as Grafana data source?

### ISSUE THREAD

**Issue by matti** [timescale/timescaledb#154]
Is this being worked on somewhere already?

**Comment by mfreed** [comment]
Grafana Labs says they'll be releasing a postgres connector within the next couple months, which would work with Timescale (they released MySQL earlier this month).  We'll follow up.

Thanks for interest!

**Comment by svenklemm** [comment]
I've written a postgresql datasource for grafana and have opened a pullrequest see https://github.com/grafana/grafana/pull/9209

**Comment by svenklemm** [comment]
The pull request for the postgres datasource got merged so the next release of grafana will have postgres support.

**Comment by stalltron** [comment]
Grafana v4.6 is live! Thanks to @svenklemm for writing the PostgreSQL datasource included in the release: http://docs.grafana.org/guides/whats-new-in-v4-6/
