### ISSUE TITLE
Aggregate hypertable by many time-buckets

### ISSUE THREAD

**Issue by Slava96** [timescale/timescaledb#1541]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version 11.5
 - TimescaleDB version 1.5.1
 - Installation method: apt 

Have table 'statistics' with columns:
1. time - timestampz - default now()
2. input - text (metadata)
3. interaction - text (metadata)

Need to continuous count this data grouped by input and interaction and time buckets for 5 seconds, 30 seconds, 1 minute and 15 minutes. For each update produce record to Kafka with real-time count grouped by this 4 time buckets.

I think about creating continuous view per time_bucket, but stopped on joining results of this aggregations into one table.

Can you explain best practices to handle this use-case?

**Comment by bboule** [comment]
I would suggest you could create a continuous aggregate for each time bucket you want to capture, then on  cron you could count the records and insert the results to an intermediate table, and use something like Debezium to capture the change to that intermediate table to initiate the Kafka message with the count data.

**Comment by Slava96** [comment]
Many thanks!
It's good answer)

**Comment by jan4984** [comment]
@bboule continuous aggregate generate a view other than table. How Debezium can capture a view's changes?
