### ISSUE TITLE
Add Column to Compressed Hypertable

### ISSUE THREAD

**Issue by WarriorOfWire** [timescale/timescaledb#1543]
```
# alter table metrics_hypertable add column foo int;
ERROR:  operation not supported on hypertables that have compression enabled
```

- Compression on hypertables encourages retention windows that make it impractical to decompress one's tables.
- Schema is living and modified over months and years.  It must be possible to add columns.

It may be fine to support only plain `add column name type;` and disallow adding column constraints to compressed tables.

**Comment by WarriorOfWire** [comment]
@bboule This continues to block me from being able to use compression.  It's such a neat feature, is there anything I can do to help prioritize this?

**Comment by tmtron** [comment]
At least adding nullable columns should work - maybe that's easier to implement?

**Comment by WarriorOfWire** [comment]
This issue came up again today with a highly compressible table that takes a long time (minutes) to query due to the need to read cold chunks into memory.

Still would intensely like to see add nullable column support on compressed hypertables!

**Comment by jtushman** [comment]
what is the current work around.  Is there a way to temporally uncompress to add the column and then recompress ?

**Comment by WarriorOfWire** [comment]
Sure, if you can afford to decompress the _entire_ hypertable you can add the column.

Unfortunately the involved latency and storage requirements make this approach a non-starter for users like me.  There is no workaround I am aware of that meets the needs of a live column addition to a compressed hypertable.

**Comment by matinmlk** [comment]
This restriction is blocking us to use compression in timescaledb.

```
ALTER TABLE "[hyper table name]" ADD COLUMN "[column name]" DOUBLE PRECISION NULL;
ERROR:  operation not supported on hypertables that have compression enabled
```

If compression can be applied at chunk level not table wide for all chunks, it will give us the flexibility of adding a new nullable column to the table and compress it.

This code will make it possible to change the schema of the hypertable:

```
ALTER TABLE "[hyper table name]" SET (timescaledb.compress=false);
ALTER TABLE "[hyper table name]" ADD COLUMN "[column name]" DOUBLE PRECISION NULL;
ALTER TABLE "[hyper table name]" SET (timescaledb.compress=true);
```

Unfortunately, only if you don't have compressed chunk in the table this will work.

Only ways to make sure there is no compressed chunk in the table is :

1- Drop compressed chunks ( which is not always feasible ).
[drop_chunks();](https://docs.timescale.com/latest/api#drop_chunks)


2- Decompress chunks ( which is not always affordable ).
[decompress_chunk();](https://docs.timescale.com/latest/api#decompress_chunk)


Can we expect a change for this behavior in timescaledb?

**Comment by mfreed** [comment]
Just to keep folks in the loop - we've made progress here, and a PR for being able to add a column to a compressed hypertable was merged last month:

https://github.com/timescale/timescaledb/pull/2736

It will likely be part of our next release.  Thanks for patience!

**Comment by NunoFilipeSantos** [comment]
The feature is out on our 2.1 release. :)
You can find [the docs here](https://docs.timescale.com/latest/using-timescaledb/compression#decompress-chunkshttps://docs.timescale.com/latest/using-timescaledb/compression#decompress-chunks).
