### ISSUE TITLE
Install timescaledb on ubuntu 14.04

### ISSUE THREAD

**Issue by parthgandhi7** [timescale/timescaledb#155]
Is there any other way i can install timescale db on my Ubuntu 14.04.5 LTS other than building from source? Please guide me.

**Comment by RobAtticus** [comment]
You can use the Docker method if you don't want to install from source. We do not have an official package for 14.04 (though we would consider adding one), but I believe the 16.04 package could also be installed on 14.04.

**Comment by parthgandhi7** [comment]
Anyways i upgraded my server to 16.04 and then the apt installation worked perfectly fine. I previously tried installing through apt on ubuntu 14.04 but it din't work. Also build from source is a bit more complicated. Anyways its working for me now on 16.04.
