### ISSUE TITLE
I got an unknown fatal error

### ISSUE THREAD

**Issue by cossbow** [timescale/timescaledb#1559]
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.1
 - Installation method: yum

**Describe the bug**
dmest -T result:
`
[Fri Nov 29 09:56:32 2019] postmaster[32443]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:32 2019] postmaster[32442]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4
[Fri Nov 29 09:56:32 2019]  in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:33 2019] postmaster[32582]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:33 2019] postmaster[32583]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:34 2019] postmaster[32692]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:34 2019] postmaster[32693]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:36 2019] postmaster[334]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:36 2019] postmaster[332]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:37 2019] postmaster[457]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:37 2019] postmaster[458]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:39 2019] postmaster[581]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4
[Fri Nov 29 09:56:39 2019] postmaster[582]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:39 2019]  in timescaledb-1.5.1.so[7f0d7ad64000+62000]

[Fri Nov 29 09:56:40 2019] postmaster[717]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4
[Fri Nov 29 09:56:40 2019] postmaster[716]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:40 2019]  in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:41 2019] postmaster[854]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:41 2019] postmaster[855]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:43 2019] postmaster[958]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:43 2019] postmaster[959]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:43 2019] postmaster[1065]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:44 2019] postmaster[1080]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:44 2019] postmaster[1095]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:44 2019] postmaster[1110]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:45 2019] show_signal_msg: 1 callbacks suppressed
[Fri Nov 29 09:56:45 2019] postmaster[1150]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:46 2019] postmaster[1241]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:47 2019] postmaster[1282]: segfault at 0 ip 00007f0d7ada6fc8 sp 00007fff14d8bd10 error 4 in timescaledb-1.5.1.so[7f0d7ad64000+62000]
[Fri Nov 29 09:56:48 2019] postmaster[1472]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4 in timescaledb-1.5.1.so[7f5c58e6f000+62000]
[Fri Nov 29 09:56:48 2019] postmaster[1471]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4 in timescaledb-1.5.1.so[7f5c58e6f000+62000]
[Fri Nov 29 09:56:49 2019] postmaster[1553]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4 in timescaledb-1.5.1.so[7f5c58e6f000+62000]
[Fri Nov 29 09:56:49 2019] postmaster[1554]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4 in timescaledb-1.5.1.so[7f5c58e6f000+62000]
[Fri Nov 29 09:56:51 2019] postmaster[1690]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4
[Fri Nov 29 09:56:51 2019] postmaster[1689]: segfault at 0 ip 00007f5c58eb1fc8 sp 00007ffc86f8d860 error 4 in timescaledb-1.5.1.so[7f5c58e6f000+62000]
[Fri Nov 29 09:56:51 2019]  in timescaledb-1.5.1.so[7f5c58e6f000+62000]
`
This has happened to me before, at postgresql-11.5 & timescaledb-1.4.1

**Comment by bboule** [comment]
@JLockerman  was wondering if you might have the cycles to take a look at this?

@cevian

**Comment by cevian** [comment]
@cossbow what was the query being run and the table definitions?

**Comment by cevian** [comment]
@cossbow any way to get the debug symbols for timescledb installed under yum as well?

**Comment by mfreed** [comment]
Going to close issue for now. This is about an older verison of TimescaleDB at this point (1.5.1), and without more information, hard to determine cause.

@cossbow please feel free to re-open if you encounter on a newer version.  Thanks.
