### ISSUE TITLE
Error installing timescaledb from source with Postgres.app [MacOS]

### ISSUE THREAD

**Issue by zxs107020** [timescale/timescaledb#156]
```
MBP:~ user$ cd timescaledb
MBP:timescaledb user$ git checkout 0.3.0
Note: checking out '0.3.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d1f66c5... Release 0.3.0
MBP:timescaledb user$ make
/bin/sh: pg_config: command not found
Makefile:6: *** "TimescaleDB requires PostgreSQL 9.6".  Stop.
MBP:timescaledb user$ 
```
But postgres.app is installed and running fine

**Comment by mfreed** [comment]
Looks like it isn't finding the `pg_config` command line tool, even though Postgres.app suggests it should be included in the app.

https://github.com/PostgresApp/PostgresApp#command-line-utilities

@zxs107020 Can you manually check if you have the CLI util anywhere?  Might just be a path issue.

**Comment by zxs107020** [comment]
@mfreed how do I do that?

**Comment by mfreed** [comment]
Try to UNIX command `which`:
```
$ which pg_config
/usr/local/bin/pg_config
```
Is there a particular reason you are trying to install from source?  Something like `brew` or docker is generally much easier.

**Comment by zxs107020** [comment]
Well, there is no reason that I am installing from source except that I did not have homebrew. So I tried that method instead and am running into the following error when modifying the postgresql libraries:

MBP:~ user$ /usr/local/var/postgres/postgresql.conf
-bash: /usr/local/var/postgres/postgresql.conf: Permission denied

**Comment by RobAtticus** [comment]
You'll need to edit it with something like `vi`, `emacs`, or another text editor. You appear to be trying to run it.

**Comment by zxs107020** [comment]
@RobAtticus can you explain a little further? Im not quite sure I understand what you mean, edit what?

**Comment by RobAtticus** [comment]
Sure, you need to use a program that can edit files to change a line in the config file. So if you use `vi` for instance, you want to run:
`vi /usr/local/var/postgres/postgresql.conf`

This will open up the contents of the file and you change the line to update `shared_preload_libraries` to include `timescaledb`.

**Comment by mfreed** [comment]
Alternatively, if you aren't used to a UNIX-like editor (such as `vi` or `emacs`), you can open that file also in something like TextEdit.  

Run the TextEdit program, then open the above file `/usr/local/var/postgres/postgresql.conf`, change the `shared_preload_libraries`, and save the file again before exiting the text editor.

**Comment by zxs107020** [comment]
When I open the file with textedit, the file already includes `shared_preload_libraries = 'timescaledb'`... what do i do next?

**Comment by zxs107020** [comment]
When I try to restart posgresql using brew I get the following error: `Error: Formula `postgresql` is not installed.`

**Comment by mfreed** [comment]
Hi @zxs107020 :  It might be easier to handle these types of questions in our Slack channel:  https://slack-login.timescale.com/

**Comment by mfreed** [comment]
I'm going to close this out unless there is anything else?
