### ISSUE TITLE
Mismatch expected count rows for table versus continuous aggregate view

### ISSUE THREAD

**Issue by dinglemouse2250** [timescale/timescaledb#1572]
**Relevant system information:**
 - OS: Centos7
 - PostgreSQL version (output of `postgres --version`): 11.1
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.2
 - Installation method: source

**Describe the bug**
The materialized continuous aggregate view does not have all the records we expected to see. The last one is missing.

**To Reproduce**
1. Create table based on the NYC rides tutorial and populate with data
2. Make selection using time_bucket... see 14 rows
3. Create continuous aggregate view using exactly same select as step 2
4. REFRESH MATERIALIZED VIEW cagg_rides_view
5. The view has only 13 rows instead of the expected 14. (The most recent one is missing)

**Expected behavior**
After the REFRESH expected the row counts for the table and for the view to be same.

**Actual behavior**
Table 14 rows. View 13 rows.

**Screenshots**
NA

**Additional context**
Attached test output.
[select_vs_view.txt](https://github.com/timescale/timescaledb/files/3924221/select_vs_view.txt)

**Comment by cevian** [comment]
@dinglemouse2250 is the refresh_lag parameter set to -2 buckets. Otherwise the continuous aggregate view is expected to lag the raw data.

**Comment by cevian** [comment]
@dinglemouse2250 please refer to "How Far Behind Will Continuous Aggregates Be?" section on https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates

**Comment by dinglemouse2250** [comment]
The behaviour of the explicit REFRESH MATERIALIZED VIEW command is more complicated than I understood.

I didn't realise the refresh_lag etc parameters still applied for the explicit materialization case.
But I see now there is a note about this point: https://docs.timescale.com/latest/api#continuous_aggregate-refresh_view

BTW - documentation https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates says to set refresh_lag to **-1 buckets** to eliminate lags, (not -2 buckets like you wrote in above comment)

Thanks.
