### ISSUE TITLE
relcache reference is not owned by resource owner...

### ISSUE THREAD

**Issue by ouafnico** [timescale/timescaledb#1574]
**Relevant system information:**
 - OS: Debian Buster
 - PostgreSQL version : 11.5-1+deb10u1
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.2
 - Installation method: apt install

**Describe the bug**

After upgrading telegraf-pg version 1.10.4-with-pg (git: telegraf-with-pg 13c25331) to 
1.11.3-with-pg (git: telegraf-with-pg 5b4a3754), I got a lot of errors on telegraf like 

Error writing to output [postgresql]: ERROR: relcache reference _hyper_29_667_chunk_system_time_client_host_idx is not owned by resource owner Portal (SQLSTATE XX000)

Don't know if this is the best place to ask...

**Comment by k-rus** [comment]
Does the update include update of TimescaleDB? How have you done the update?

**Comment by k-rus** [comment]
Was the PG version updated together with Telegraf? [Here](https://docs.timescale.com/latest/using-timescaledb/update-db) is description how we recommend to upgrade TimescaleDB.

**Comment by ouafnico** [comment]
Timescaledb is installed by apt file from repository.
Indeed I've got 1.4.2 from psql but package is 1.5.1~debian10.

PG is updated too from apt repositories.

I will try your process :)

**Comment by ouafnico** [comment]
After upgrading (now I'm in 1.5.1), it still got the error.

On Telegraf-pg 11.1.3, telegraf says :

ERROR: relcache reference _hyper_29_667_chunk_system_time_client_host_idx is not owned by resource o
2019-12-05T15:36:16Z E! [agent] Error writing to output [postgresql]: ERROR: relcache reference _hyp

On postgresql log I got : 

STATEMENT:  copy "system" ( "time", "client", "host", "ipaddress", "type", "n_cpus", "n_users", "load1", "load5", "load15", "uptime", "uptime_format" ) from stdin binary;
telegraf@telegraf ERROR:  relcache reference _hyper_29_667_chunk_system_time_client_host_idx is not owned by resource owner Portal

**Comment by bboule** [comment]
@blagojts could I ask you to take a look at this? to see if the issue might be on the Telegraf side?

**Comment by cevian** [comment]
@ouafnico just to make sure you ran `ALTER EXTENSION timescaledb UPDATE;` in the database and \dx shows `1.5.1`

**Comment by ouafnico** [comment]
Hello
I did.

telegraf=> \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 pg_trgm     | 1.4     | public     | text similarity measurement and index searching based on trigrams
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.5.1   | public     | Enables scalable inserts and complex queries for time-series data

**Comment by blagojts** [comment]
Hello, @ouafnico I tried the following scenario to recreate your issue:
1. Installed TimescaleDB 1.4.2 on Debian Buster from apt
1. Tuned it with timescale-tune
1. Created a new db inside TimescaleDB, activated the TimescaleDB extension
1. Ran telegraf 1.11.3 with our plugin as an output, and the system plugin as an input (default config, other than the `table_template` being set to create a hypertable )
1. (all was ok, hypertable was created, data was inserted)
1. Upgraded TimescaleDB to 1.5.1 from apt, and did an `ALTER EXTENSION ...`
1. Ran Telegraf again, data continued to be inserted

Did you do something differently?

**Comment by ouafnico** [comment]
Hello

The process was the same.

On this server, timescaledb was originaly installed on version 1.3.2.
it was upgraded then to 1.4.1, then 1.4.2, and now 1.5.1.

I tried again this morning with your last telegraf-pg binairie (1.13.0).

Same :/

Jan 14 10:57:04 systemd[1]: Started Telegraf to TimeScaleDB.
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Starting Telegraf 1.13.0-with-pg
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Loaded inputs: cpu socket_listener http_listener_v2
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Loaded aggregators:
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Loaded processors:
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Loaded outputs: postgresql
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! Tags enabled: host=hidden
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"hidden", Flush Interval:30s
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! [inputs.socket_listener] Listening on tcp://[::]:hidden
Jan 14 10:57:04 telegraf-pg[16880]: 2020-01-14T09:57:04Z I! [inputs.http_listener_v2] Listening on 127.0.0.1:hidden
Jan 14 10:58:01 telegraf-pg[16880]: 2020-01-14T09:58:01Z E! Could not insert batch of rows in output db
Jan 14 10:58:01 telegraf-pg[16880]: ERROR: relcache reference _hyper_29_787_chunk_system_time_client_host_idx is not owned by resource owner Portal (SQLSTATE XX000)
Jan 14 10:58:01 telegraf-pg[16880]: 2020-01-14T09:58:01Z I! copy error: ERROR: relcache reference _hyper_29_787_chunk_system_time_client_host_idx is not owned by resource owner Portal (SQLSTATE XX000)
Jan 14 10:58:01 telegraf-pg[16880]: 2020-01-14T09:58:01Z E! [agent] Error writing to outputs.postgresql: ERROR: relcache reference _hyper_29_787_chunk_system_time_client_host_idx is not owned by resource owner Portal (SQLSTATE XX000)

**Comment by joeypoon** [comment]
Hiyo. Just want to chime in here as I have the exact same problem. I'm not sure if your cause is the same but I can reproduce this error when I add a before insert trigger to my hypertable where the function edits a value. No errors when I remove the trigger.

**Comment by ouafnico** [comment]
Tried again today, I still got the issue.

**Comment by NunoFilipeSantos** [comment]
@ouafnico please try our latest version (2.4.2) if the problem still persists feel free to reopen this issue.
