### ISSUE TITLE
Add support for Yugabyte Database

### ISSUE THREAD

**Issue by fire** [timescale/timescaledb#1578]
**Describe the bug**

Engineer TimescaleDB so it supports Yugabyte Database. https://github.com/yugabyte/yugabyte-db

**Why** 

Cluster databases are hard to create, but if Timescaledb reuses Yugabyte's work, Timescaledb is able to focus on timeseries while the database Yugabyte focuses on clustering.

**Additional context**

https://github.com/yugabyte/yugabyte-db/issues/3126

**Comment by mfreed** [comment]
Timescale now supports multinode scale out. 

Also Yugabyte to my understanding only supports the PG wire protocol and is not actually related to the actual Postgres codebase.

https://blog.timescale.com/blog/building-a-distributed-time-series-database-on-postgresql/

**Comment by fire** [comment]
According to https://docs.yugabyte.com/latest/api/ysql/extensions/#postgis it supports postgresql code like postgis. So this is wrong.

**Comment by mfreed** [comment]
https://docs.yugabyte.com/latest/api/ysql/extensions/#use-included-extensions

```
Note that since YugabyteDB’s storage architecture is not the same as that of native PostgreSQL, PostgreSQL extensions especially those that interact with the storage layer are not expected to work as-is on YugabyteDB. We intend to incrementally develop support for as many extensions as possible.
```

**Comment by hwinkel** [comment]
What does it mean closing the issue with the statement from YB? Does/Could  TimescaleDB work because it's not using the storage layer but only query layer or not?

**Comment by icodeiexist** [comment]
Hello, wish you a happy new year 2021, any plans to support an extension like timescaledb someday? I know there are serious architectural challenges there, but only the prospect sounds amazing. 
Thank you.
