### ISSUE TITLE
Approx Percentile / Histogram / Sketch Functions

### ISSUE THREAD

**Issue by pwebbitrs** [timescale/timescaledb#1580]
I have been looking at TimescaleDb as a potential replacement to an existing setup and so far it looks like a really good match, however i have noted a few things that seem to be missing.    

Primarily I am missing approximate statistics such as Histograms ( as in t-digest , HDR etc) and sketches.   For my use case specifically I would love to be able to natively get approximate percentiles from a time series.  I have looked around and this seems to be a bit of a gap in the postgres built in aggregations, and i see nothing in the time scale functions either.  

T-digest/hdr etc are quite accurate and do not require the data to be sorted, thus can be done without needing an ordered aggregate function. And they are very amenable to parallelisation. To me this feels very applicable to timescale.

Do you have plans for adding such functions to timescaledb in the future?  If not,  it it easy to add such a thing?

**Comment by mfreed** [comment]
Hi @pwebbitrs We have a prototype of tdigest working and hope to get released in the next couple of months.  Thanks.

**Comment by andrew-blake** [comment]
@mfreed are you be also considering the other types of probabilistic data structures, such as those found in PipelineDB ? e.g. HLL and Top-N ?

http://docs.pipelinedb.com/probabilistic.html

**Comment by pwebbitrs** [comment]
Hi @mfreed that is good to hear.  These kinds of structures are pretty essential these days.  Top-K is another one that is really important.   Thanks for the speedy response and I look forward to trying these out.

**Comment by tnolet** [comment]
@mfreed any news on this. I am in the market for a timeseries DB for the SaaS I run. Percentiles and rollups of percentiles are a must.

**Comment by svenklemm** [comment]
Closing this since this is provided by timescaledb-toolkit.
https://github.com/timescale/timescaledb-toolkit/tree/main/docs
