### ISSUE TITLE
Final Function of Aggrgate is running at the time of query execution, is it that the correct bahaviour ?

### ISSUE THREAD

**Issue by kamit-transient** [timescale/timescaledb#1582]
**Relevant system information:**
 - OS: Ubuntu 16.04
 - PostgreSQL version : 11.5 
 - TimescaleDB version :  1.5.0
 - Installation method: apt install

**Describe the bug**
I'm testing custom aggregate with timescaleDb's Continuous aggregate. But I can see that the **final function of the aggregate** is being run at the time of query execution.

**To Reproduce**
1. Create a custom aggregate and put some `RAISE NOTICE`  like RAISE NOTICE '[function_avg_combine] CALLED..';  in `final function`
2. Then run `Select query ` like `Select * from <ViewName>;`
3. See the Output

**Expected behavior**
The **final function of the aggregate** should run at the time, when continuous aggregate run, not at the time of querying the view.

**Actual behavior**
*Final Function is running at the time of Querying the view*

**Comment by davidkohn88** [comment]
That is the expected behavior, the final function runs at query time as aggregates are constrained to chunk boundaries, and may need to be combined across them at query time (among other reasons).
