### ISSUE TITLE
How to export entire database with schema + data for TimescaldB to Postgresql.

### ISSUE THREAD

**Issue by vivekanandsh** [timescale/timescaledb#1585]
**Relevant system information:**
 - OS: Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version` 10x): 
 - TimescaleDB version 1.1.4 
 - Installation method: zip file 

**Describe the bug**

From PostgreSQL DB conversion to TimescaleDB we know well.   Is there way to convert back TimescaleDB data back in to only PostgreSQL DB. 

Yes, we TimescaleDB  extension is part of PostgreSQL DB only , however data is stored in chunks.  
So, how to get back all chunk data back in to single table ( same as original PostgreSQL table) .

**Comment by mfreed** [comment]
@vivekanandsh Just treat the hypertable like any other table:

```
INSERT INTO pg_table SELECT * FROM hypertable;
```
or dump to CSV and then COPY back into the new table.

**Comment by bboule** [comment]
Hey @vivekanandsh  just wondering if this answers your question?  I am going to close the issue out however if it did not or if you have follow up please feel free to re-open.

**Comment by vivekanandsh** [comment]
Noted, thanks for clarification.
