### ISSUE TITLE
Drop column on hypertable makes compression not activable

### ISSUE THREAD

**Issue by ChristopherZellermann** [timescale/timescaledb#1590]
**Relevant system information:**
 - PostgreSQL version : 11.5
 - TimescaleDB version : 1.5.1
 - Installation method: docker with TimescaleDB's official 1.5.1-pg11 image

**Describe the bug**
For the full history, the bug has been described on Timescale's slack channel : https://timescaledb.slack.com/archives/C4GT3N90X/p1576592466079500
With the Timescale 1.5.1-pg11 version there is an issue for enabling the compression feature.
I noticed that I couldn't enable compression on my existing hypertable but if I created a new hypertable with the same fields and constraints it works well.

**To Reproduce**
```
CREATE TABLE public.mes (
	tstamp timestamptz NOT NULL,
	vunit_id int8 NOT NULL,
	identifierreading_id int8 NOT NULL,
	value float8 NULL,	
	CONSTRAINT mes_identifierreading_id_fk FOREIGN KEY (identifierreading_id) REFERENCES identifierreadingoverride(identifierreading_id),
	CONSTRAINT mes_vunit_id_fk FOREIGN KEY (vunit_id) REFERENCES vunit(vunit_id)
);
-- transform into hypertable
SELECT create_hypertable('mes', 'tstamp', chunk_time_interval => interval '7 day');
-- drop column no longer used
ALTER TABLE mes	DROP COLUMN vunit_id;
-- Enable compression segmented by identifierreading_id and order by tstamp desc 
ALTER TABLE mes SET (timescaledb.compress,timescaledb.compress_segmentby = 'identifierreading_id');	
-- -> ERROR: constraint mes_identifierreading_id_fk requires column value to be a segment_by column for compression
```
vunit_id and identifierreading_id are FKs to tables describing the devices and type of measures that are stored. As you can see I removed the vunit_id column, and the hypertable mes is now a simple (tstamp, device_id, value) hypertable.
And when I try to activate the compression feature I get the message :

> constraint mes_identifierreading_id_fk requires column value to be a segment_by column for compression 

Note that when I create a new hypertable like this, the compression feature is enabled without any issues :
```
CREATE TABLE public.mes2 (
	tstamp timestamptz NOT NULL,	
	identifierreading_id int8 NOT NULL,
	value float8 NULL,	
	CONSTRAINT mes_identifierreading_id_fk FOREIGN KEY (identifierreading_id) REFERENCES identifierreadingoverride(identifierreading_id)	
);
-- transform into hypertable
SELECT create_hypertable('mes2', 'tstamp', chunk_time_interval => interval '7 day');
-- Enable compression segmented by identifierreading_id and order by tstamp desc 
ALTER TABLE mes2 SET (timescaledb.compress,timescaledb.compress_segmentby = 'identifierreading_id');	
-- -> Everything OK
```

**Expected behavior**
I should be able to activate the compression feature on a hypertable even when I dropped a column that has a fk constraint on this hypertable beforehand.

**Actual behavior**
See error message above.

**Comment by bboule** [comment]
@ChristopherZellermann  thanks for the report, let us investigate will be back with you soon
