### ISSUE TITLE
Is it possible to create_hypertable() without table having column of type timestamp, Integer , DateTime?  What is solution for this. 

### ISSUE THREAD

**Issue by vivekanandsh** [timescale/timescaledb#1595]
Relevant system information:

OS: Windows 10 x64, etc]
PostgreSQL version : 10.x 
TimescaleDB version 1.1.4
Installation method: Installer 

Describe the bug

Hello all,   
How to partition table (in  postgresqlDB)  with table don't have column of type timestamp, Integer , DateTime integer  ?                     

  CREATE TABLE rep_backup
(
   type character varying(100) COLLATE pg_catalog."default" NOT NULL,
   id character varying(120) COLLATE pg_catalog."default" NOT NULL,
   data bytea NOT NULL,
   CONSTRAINT pk_replication_backups PRIMARY KEY (type, id)
)      
above table don't have any column of type timestamp, Integer , DateTime. 
Want to know  for above table hash partition is possible , if yes please guide how to do?  
Please provide sample example if possible. 
Urgent one help to clarify/reply asap.

**Comment by mfreed** [comment]
I'm a little uncertain ... for what are you trying to use TimescaleDB?  Is this somehow time-series data?

**Comment by vivekanandsh** [comment]
Mike, 
Thanks for quick reply. TimescaleDB want to use for PostgreSQLDB extension as we have more time related data and wan to partition. 
I have done for  partition for some tables already, only question is below table  don't have column of type  timestamp, Integer , DateTime.
CREATE TABLE rep_backup
(
type character varying(100) COLLATE pg_catalog."default" NOT NULL,
id character varying(120) COLLATE pg_catalog."default" NOT NULL,
data bytea NOT NULL,
CONSTRAINT pk_replication_backups PRIMARY KEY (type, id)
)
So, want to know can i do HASH partition ? As per documentation hash partition used as multi dimension  partition _**https://docs.timescale.com/latest/api#add_dimension**_ .
Just help me clarify, MUST need column of type  timestamp, Integer , DateTime  in table to create hypertable or without those those types using hash partition possible.  

Regards, Vivek

**Comment by mfreed** [comment]
Hypertables currently require some type of timestamp/integer/date.

You might consider with the above is you need to partition at all (what benefit do you get from it?) or use native PG partitioning.

**Comment by vivekanandsh** [comment]
May i know the timeline for the timescaledb version compatible for PostgreSQL 12.x.
Hope many looking for this version. :)

**Comment by loringao** [comment]
We have similar user scenarios, but there are  id(bigint) and create_time(timestamp),  it's business transcation data(not a IoT data) , we expect get the stable &high throughput from timescale，does it reasonable?

**Comment by k-rus** [comment]
> May i know the timeline for the timescaledb version compatible for PostgreSQL 12.x.
> Hope many looking for this version. :)

See discussion #1456

**Comment by NunoFilipeSantos** [comment]
We already support PG 12 and 13. :)
