### ISSUE TITLE
Can't create contiunous aggregate with bigint time column

### ISSUE THREAD

**Issue by semtexzv** [timescale/timescaledb#1597]
**Relevant system information:**
 - OS: Docker - `timescale/timescaledb:1.5.1-pg11`
 - PostgreSQL version (output of `postgres --version`): 11
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.1
 - Installation method: Docker

**Describe the bug**
Can't create continous aggregate using bigint as time column. Timescaledb complains that 
`[0A000] ERROR: first argument to time_bucket function should be a constant for continuous aggregate query`

**To Reproduce**
1. Create simple table:
```sql
create table test
(
    time  bigint,
    value float,
    primary key (time)
)
```
2. Make it a hypertable
```sql
select *
from create_hypertable('test', 'time', chunk_time_interval := 60 * 60 * 60)
```
3. Attempt to create continuos aggregate
```sql

create view test_rollup_5m
            WITH (timescaledb.continuous) --This flag is what makes the view continuous
as
select time_bucket(300::bigint, time) as bucket,
       sum(value)
from test
group by bucket;
```
4. Creation fails with `[0A000] ERROR: first argument to time_bucket function should be a constant for continuous aggregate query` error.

**Expected behavior**
TimescaleDB should create the continous aggregate view.

**Actual behavior**
TimescaleDB fails to create continuous aggregate view.

**Screenshots**
_None_

**Additional context**
_None_

**Comment by svenklemm** [comment]
As a workaround you can use the following syntax: 
```
create view test_rollup_5m
            WITH (timescaledb.continuous) --This flag is what makes the view continuous
as
select time_bucket(bigint '300', time) as bucket,
       sum(value)
from test
group by bucket;
```
