### ISSUE TITLE
Use an expression for time column (e.g., for time stored in JSON blob)

### ISSUE THREAD

**Issue by kskim80** [timescale/timescaledb#16]
Is it possible to modify timescaledb to use an expression for the time column?

**Comment by RobAtticus** [comment]
Can you clarify what you mean but using an expression?

**Comment by kskim80** [comment]
I mean that when make a hypertable one can use a Postgres' expression like the following:
```
SELECT create_hypertable('(conditions', 'json_attr->'time')::int8');
```
If the time values are stored in a json type column, we need this.

**Comment by RobAtticus** [comment]
Currently you cannot. Time must be stored as a column either using an int datatype or a timestamp datatype.

**Comment by mfreed** [comment]
Hi @kskim80  I believe this has been addressed with with https://github.com/timescale/timescaledb/pull/639 -- in that it allows you to define your own time functions -- which was part of our 1.1 release.

Closing this issue for now, feel free to re-open if doesn't solve your problems.
