### ISSUE TITLE
Can't create extension

### ISSUE THREAD

**Issue by IvarLeksa** [timescale/timescaledb#1600]
I've got various errors when execute CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE.
Relevant system information:

- Windows 10 Pro
- PostgreSql 11.5.1
- TimescaleDb 1.5.1

Also installed Microsoft Visual C++ 2015-2019 Redistributable.
In my postgrsql.config
```
shared_preload_libraries = 'timescaledb'
shared_buffers = 512MB
effective_cache_size = 6043MB
maintenance_work_mem = 1031389kB
work_mem = 6439kB
timescaledb.max_background_workers = 8
max_worker_processes = 15
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
wal_buffers = 16MB
min_wal_size = 4GB
max_wal_size = 8GB
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_connections = 100
max_locks_per_transaction = 64
autovacuum_max_workers = 10
autovacuum_naptime = 10
timescaledb.last_tuned = '2019-12-26T18:15:41+03:00'
timescaledb.last_tuned_version = '0.7.0'
```
According to https://github.com/timescale/timescaledb/issues/1398#issuecomment-528731198 I've added _libeay32.dll_ and _ssleay32.dll_ from PostgreSql 11.4.3 to my current installation.
When I execute `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE` I get error "Connection to the server has been lost.".
When I execute
```
SET timescaledb.allow_install_without_preload = 'on';
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
```
I get
```
ERROR:  loader version out-of-date
HINT:  Please restart the database to upgrade the loader version.
```
Restarting the database or rebooting the computer doesn't solve this problem.
What's wrong? What should I do? Can you help me?

**Comment by bboule** [comment]
@IvarLeksa  thank you for your report, I am sorry this is giving you trouble... We are going to have one of our engineers have a look at this issue and respond via this issue.

**Comment by IvarLeksa** [comment]
Hi, bboule!
Is there any good news on this issue?

**Comment by IvarLeksa** [comment]
> We are going to have one of our engineers have a look at this issue and respond via this issue.

@bboule 
Hi
Has one of your engineers already looked at this issue? When is he planning to respond?

**Comment by uweschmitt** [comment]
any updates? Have the same issue.

**Comment by 3242433424** [comment]
Any updates? Still having this issue

**Comment by Annie-create** [comment]
any update?

**Comment by jdsdc** [comment]
Having the same problem. Any update on this?

**Comment by mfreed** [comment]
Sorry for all the issues; Windows is not a common platform for us here =)

What versions of TimescaleDB and PG are people seeing this with, including when moving the .dlls into place.  Do you see any errors in the logs when you get "Connection lost"?

cc: @uweschmitt @3242433424 @Annie-create @jdsdc

**Comment by IvarLeksa** [comment]
Thank you for your work. Now I'm not interested in this issue. I've solved my problem using InfluxDB.

**Comment by NunoFilipeSantos** [comment]
We have Windows working for the latest 2.4.2 version, if you want to try it out.

**Comment by IG9TE** [comment]
i have the same problem, im using wsl 2 on windows 10
