### ISSUE TITLE
Cannot move compressed chunk to another tablespace

### ISSUE THREAD

**Issue by dewetburger430** [timescale/timescaledb#1605]
An error message is returned when trying to move compressed chunks between tablespaces. I executed the following commands:

```sql
select compress_chunk('_timescaledb_internal._hyper_199_64897_chunk');

select move_chunk(
    chunk => '_timescaledb_internal._hyper_199_64897_chunk'::regclass,
    destination_tablespace => 'longterm_store'::name,
    index_destination_tablespace => 'longterm_store'::name,
    reorder_index => '_timescaledb_internal.64897_129623_gaugedata_pkey'::regclass,
    verbose => TRUE
);
```

It works fine if I move the chunk to the second tablespace first and then compress it.

**Comment by bboule** [comment]
@dewetburger430 thanks for submitting this!!  We will start looking into this and get back with you ASAP.

**Comment by defigure** [comment]
https://github.com/timescale/timescaledb/blob/3efc59e8ac2be05d55b30d58fd37901b2211cab7/tsl/src/reorder.c#L180

That seems to be what's hit, is it because moving chunks it's implemented as a reorder operation? Is there a way to move the chunk without reordering (more like an alter table set tablespace that works on chunk tables)?

**Comment by defigure** [comment]
@bboule @erimatnor Could you provide any update on this? It's 5 months and this is really urgent and problematic for us. Could you comment on whether moving the underlying compress_hyper named chunk is safe?

**Comment by davidkohn88** [comment]
Apologies that this fell through the cracks, I don't see any reason why moving compressed chunks should be dangerous, as it's just modifying their tablespace. And I believe we thought you had figured out that workaround and were using it and so had not responded as that does seem like a good workaround.

**Comment by defigure** [comment]
We (had) lots of important data, and 6 months later we get the strong guarantee of a drive by "hmm that probably works what could go wrong." To be honest we were extremely disappointed by both the product and the company/team, and went through the large engineering effort to migrate our organization to a competitor database. In the end clearly it was the right thing to move away from timescale. We will write up all of our experiences and publish it as some point.

**Comment by defigure** [comment]
It seems like issue 2067 indicates that in fact it would not have been safe to just move the tablespace on the compressed chunks.

**Comment by pmwkaa** [comment]
@defigure Sorry for any inconvenience related to this, the issues is fixed in https://github.com/timescale/timescaledb/pull/2105. By altering tablespace or using move_chunk() will move both compressed and uncompressed chunks to the specified tablespace.
