### ISSUE TITLE
Not able to install timescale db on MacOS

### ISSUE THREAD

**Issue by ajit-kumar-azad** [timescale/timescaledb#161]
Hi There!

I used Homebrew installation on MacOS and it fails saying no available formula for postgresql@9.6. Here is the command output:

```
Ajits-MacBook-Pro:~ ajitkumar$ brew tap timescale/tap
Warning: Already tapped!
Ajits-MacBook-Pro:~ ajitkumar$ brew install timescaledb
==> Installing timescaledb from timescale/homebrew-tap
Error: No available formula for postgresql@9.6 (dependency of timescaledb)
Searching formulae...
Searching taps...
```
Following is the System s/w info:

```
System Version:	macOS 10.12.6 (16G29)
Kernel Version:	Darwin 16.7.0
```

**Comment by RobAtticus** [comment]
That's strange, I'm not having any issues here when I try. Can you try installing postgresql@9.6 by itself first?
`brew install postgresql@9.6`
Or if that doesn't work
`brew install postgresql`

Just make sure it is a 9.6.x version. You also try posting your `brew config` here and maybe something jumps out for why it is not working.

**Comment by ajit-kumar-azad** [comment]
I found that the problem was due to the version of Homebrew. I installed the latest version and both PostgreSQL and Timescale DB have been installed successfully. Thanks!

**Comment by RobAtticus** [comment]
Great! Will close then :)
