### ISSUE TITLE
Continuous aggregates with cumulative sum, gap fill and initiate sum

### ISSUE THREAD

**Issue by blenddata** [timescale/timescaledb#1610]
Hi everyone
consider following query

```
SELECT 
time_bucket_gapfill('1 day', datephysical,'2019-12-22' , '2020-01-04')::date AS date,
inventlocationid,
itemid,
wmslocationid,
inventstatusid,
sum(physicalinventory) physicalinventory,
(sum(sum(physicalinventory)) over (partition by inventlocationid,  
                                                itemid,  
                                                wmslocationid,  
                                                inventstatusid  
                                                order by time_bucket_gapfill('1 day', datephysical,'2019-12-22' , '2020-01-04')::date asc  
)) rs,  
COUNT(*) 
FROM inventtrans
WHERE inventlocationid='xxxx' and itemid='xxxx' AND datephysical between '2019-12-22' and '2020-01-04'
GROUP BY date,inventlocationid,itemid,wmslocationid,inventstatusid ORDER BY date;
```
![image](https://user-images.githubusercontent.com/50766350/71775963-35aba100-2f9e-11ea-953b-89f06f3bbca3.png)

As you can see query is working, but what am I trying to do is:
1- query should be a [Continuous aggregates view](https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates) 
2- I want to filter the view by date but `time_bucket_gapfill`  needs statics dates
3- Initiate sum: the first value of `rs `must be sum of past days

The result should be something like this:
```
| date                     | physicalinventory       | rs                      |
|--------------------------|-------------------------|-------------------------|
| first date to 2019-12-22 | sum(all until first) 10 | sum(all until first) 10 |
| 2019-12-22               | -3                      | 7                       |
| 2019-12-23               | -2                      | 5                       |
| 2019-12-24               | -1                      | 4                       |
| 2019-12-25               | 3                       | 7                       |
```

usage would be:
`select * from vw_invent where date between '2019-12-22' and '2020-01-04'`

I don't want to pre-aggregate  otherwise whats the point of using `timescale` :).
Appreciate any helps 👋

**Comment by blenddata** [comment]
I have created 3 views and it's working great
vw_init_trend: for init sum 
vw_invent_trans: union rest of transactions with initiated values
finally: my view 
now the problem is Number 2 (dynamic parameters for `time_bucket_gapfill`)

**Comment by techexplorer0310** [comment]
> I have created 3 views and it's working great
> vw_init_trend: for init sum
> vw_invent_trans: union rest of transactions with initiated values
> finally: my view
> now the problem is Number 2 (dynamic parameters for `time_bucket_gapfill`)

Hi, Were all the views you have created continuous aggregate? Have also similar use case but cont agg view does not allow using window query.

**Comment by NunoFilipeSantos** [comment]
@blenddata what TimescaleDB version are you using?

**Comment by NunoFilipeSantos** [comment]
Hi @blenddata! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it. 👍
