### ISSUE TITLE
Alter Continuous aggregate's As Clause( View's defining query)

### ISSUE THREAD

**Issue by kamit-transient** [timescale/timescaledb#1611]
Hi,

I need to get the schema of continuous aggregate,i.e. getting details of `WITH clause`  and also the `As clause` .

Say if my continuous aggregate is something like this:

```
CREATE VIEW continuous_aggregate_view( timec, minl, sumt, sumh )
WITH (timescaledb.continuous,
    timescaledb.refresh_lag = '-1h',
    timescaledb.refresh_interval = '30m')
AS
  SELECT time_bucket('1h', timec) as time_bicket, min(location) as min_location, sum(temperature) as sum_temperature
    FROM conditions
    GROUP BY time_bucket('1h', timec), location, humidity, temperature;

```

And I need to get `refresh_lag`, `refresh_interval`,`time_bicket`, `min_location ` etc. 

How can I get these informations? is there any meta command/select query etc.

**Comment by gayyappan** [comment]
`select view_definition from timescaledb_information.continuous_aggregates;` will give you the SELECT stmt that was used to create the continuous aggregate.
You will find the refresh_lag etc in this view.
