### ISSUE TITLE
One huge table or many smaller hypertables?

### ISSUE THREAD

**Issue by qrooel** [timescale/timescaledb#1616]
Hello,

first of all, thank you for excellent work!

I am struggling with some design problem, let's imagine a simple hypertable like this:

```
CREATE TABLE data_1 (
 time TIMESTAMPTZ NOT NULL,
 name VARCHAR NOT NULL,
 value DOUBLE PRECISION  NULL
);
```
In my case, one table has over 200 000 000 records and I have many of them for each client (200 in total).
Total rows count for all tables is around 2 000 000 000. Total data size is 450 GB (probably because of many indexes for each chunk). I am worried about chunks table (default 7 days chunk interval), it has grown to 65 000 records now.

I consider to migrate those tables into one huge table, schema below:
```
CREATE TABLE main_data (
 time TIMESTAMPTZ NOT NULL,
 name VARCHAR NOT NULL,
 value DOUBLE PRECISION  NULL,
 client_id INTEGER NOT NULL
);
```
Considering total data rows over 2 000 000 000+, will I still be able to count records by client_id, or to get last timestamp for client_id?

Could you explain me which schema is better? More query and disk space efficient? Did you run such tests or comparisons on your own? As far as I understand, I need more RAM to fit bigger chunk loading into memory, but what else?

Thank you for you answers!

**Comment by mmouterde** [comment]
From my experience, both are working. However, there is one key criteria to keep in mind : To share an hypertable, your data should be as **homogenous** as possible. 

- You should write with the same rate for all client_id
- You should write almost the same date range for all client_id in same time
- The duration between data points should be close from a client_id to another
- The duration between data points should be as regular as possible
- The global date min & max should be close
...

The less you are homogenous the more client_id will impact each others.

**Comment by qrooel** [comment]
@mmouterde you're right, thanks for reply.

**Comment by mfreed** [comment]
@qrooel With such a setup, if you commonly query by `client_id` for "deep and narrow" scans across larger time-regions of your data, I would consider using TimescaleDB's native compression with `client_id` as your `segmentby` field.  

(Or at least use `reorder_chunk` on the `client_id` so that data corresponding to the same client is all colocated on disk.)

Good luck!
