### ISSUE TITLE
Latest Timescaledb version not working for PostgreSQL 12.x  

### ISSUE THREAD

**Issue by vivekanandsh** [timescale/timescaledb#1619]
Latest Timescaledb version not working for PostgreSQL 12.x   
We are looking for the **timescaledb version which is compatible to PostgreSQL 12.x version**.
Please update on tentative timeline of availability.

**Comment by mfreed** [comment]
We are likely looking at a release (1.7) for PG12 in the Feb/March timeframe.

**Comment by HeikoOnnebrink** [comment]
in #1456 end of January / begin of February was announced and I am already waiting excited to download it .. is it delayed now?

**Comment by k-rus** [comment]
> in #1456 end of January / begin of February was announced and I am already waiting excited to download it .. is it delayed now?

Support PG12 will not make into 1.6 release and is planned for 1.7 release. The work is ongoing.
Thank you for linking this issue to the older one. I will close this issue as duplicate.
