### ISSUE TITLE
Backfilling continuous aggregate 

### ISSUE THREAD

**Issue by gebrits** [timescale/timescaledb#1621]
Say I want to create a continuous aggregate B based on table A. However, table A already contains a lot of data. Is it possible to backfill continuous aggregate B with already existing data from table A? If so, how?

**Comment by bboule** [comment]
Hey @gebrits when the system creates the continuous aggregate it will run  the aggregate for the entire table, so for example if I set this up to average out CPU utilization every 5 minutes, as part of the first run it will run this and populate the view with the results for all of the data already in the table, and then each subsequent run will grab and average over new data based on the setting you use in building the continuous aggregate  have a quick look here for more info: https://docs.timescale.com/latest/api#continuous_aggregate-create_view

**Comment by bboule** [comment]
hey @gebrits  I just wanted to check with you and see if my explanation made sense?  I am going to close this issue BUT if you need more info or still think there is something we can do to make this easier please re-open and @ mention me and we can revisit!!

**Comment by allllan** [comment]
Is it possible to backfill a continuous aggregate using data from a source other than a hyper table? Let’s say we create a continuous aggregate from a hyper table that has a retention policy of two days so there are only two days’ worth of data. But we have another database that has three months worth of data and we want to use that database to backfill the continuous aggregate. Is that possible?
