### ISSUE TITLE
amazon products are tracked every day. 15 million products items. Is timescaleDB applicable?[question]

### ISSUE THREAD

**Issue by zplzpl** [timescale/timescaledb#1625]
## track amazon products price and info;

* interval: 1 day
* 1 day 1 product 1 track data
* 15 million products items （4 GB data 1 day）
* keep data for nearly 1 year
* not update\delete

**timescaleDB applicable?**

**any suggestions on these questions?**
* chunk_time_interval
* compression interval
* any other suggestions?

## about "Compression", I tried it, and I feel that I am using it wrong.
* I used 4GB of data (uncompressed) and compressed it using the following method, but the storage grew to 24GB
* PostgreSQL 11.5, compiled by Visual C++ build 1914, 64-bit
* timescaleDB v1.5.1
* systemOS : windows 10 64bit

```
/* set_integer_now_func */
CREATE OR REPLACE FUNCTION unix_now() returns INTEGER LANGUAGE SQL STABLE as $$ SELECT extract(epoch from now())::INTEGER $$;
SELECT set_integer_now_func('product_snapshot_20191222', 'unix_now');
```

```$SQL
/* 2019-12-22 1 day data,4 GB */
ALTER TABLE product_snapshot_20191222 SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'item_id'
);

SELECT add_compress_chunks_policy('product_snapshot_20191222', INTEGER '604800');
```

```
                table_full_name                 | size
------------------------------------------------+-------
 _timescaledb_internal.compress_hyper_3_3_chunk | 24 GB
```

thanks.

**Comment by bboule** [comment]
@zplzpl  apologies for the delayed response... I just want to confirm you are reporting that compression seems to have made your storage space consumed (which seems to be the opposite of what we would expect).  Could you share the code you used to set up compression on your hypertable??  It would be helpful to understand the parameters you used in setting up compression!

**Comment by zplzpl** [comment]
I think I chose the wrong configuration: timescaledb.compress_segmentby = 'item_id'

**Comment by zplzpl** [comment]
data: 1 day

compress policy: 1 day timeunix
SELECT add_compress_chunks_policy('product_snapshot_20191222', INTEGER '604800');

ALTER TABLE product_snapshot_20191222 SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'item_id'
);
