### ISSUE TITLE
Choosing different GCC version while running bootstrap script

### ISSUE THREAD

**Issue by sawantshivaji1997** [timescale/timescaledb#1626]
**System information:**
 - OS: Centos 6.10
 - PostgreSQL version (output of `postgres --version`): psql (PostgreSQL) 11.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.1
 - Installation method: source

**Describe the bug**
I'm trying to compile the TimescaleDB from source on Centos 6.10.
Currently, I have deployed GCC 8.2 on my machine but on a different location (not in `/usr/bin`) and I have added its corresponding path in $PATH variable 
Here's the output of $PATH `/opt/gcc-8.2.0/bin/:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin`
So whenever I do `gcc --version` the output is: `gcc (GCC) 8.2.0`. so my default gcc is 8.2

Now when I run ./bootstrap, it selects GCC 4.4.7  (which is at location `/usr/bin`)
Here's the partial output:
`  # ./bootstrap`
`Build system already initialized in ./build`
`Do you want to remove it (this is IMMEDIATE and PERMANENT), y/n? y`
`-- The C compiler identification is GNU 4.4.7`
`-- Check for working C compiler: /usr/lib64/ccache/cc`
`-- Check for working C compiler: /usr/lib64/ccache/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- TimescaleDB version 1.5.1. Can be updated from version 1.5.0`
`-- Build type is Release`
`-- Install method is 'source'`
`-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN`
`-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success`
`-- Using compiler GNU`
`-- Found Git: /usr/bin/git (found version "2.1.1")`
`-- Using pg_config /usr/pgsql-11/bin/pg_config`
`-- Compiling against PostgreSQL version 11.5`

Is there any way by which I can point to GCC 8.2 while running the bootstrap script? My GCC 8.2 lies at the location `/opt/gcc-8.2.0/bin/`

**Comment by k-rus** [comment]
You need to provide compiler to CMake (which is not special for TimescaleDB). You can do it by setting `CC` variable, I believe. On Mac I do:
```
export CC=/usr/local/Cellar/gcc@6/6.5.0_2/bin/gcc-6
```

**Comment by sawantshivaji1997** [comment]
> You need to provide compiler to CMake (which is not special for TimescaleDB). You can do it by setting `CC` variable, I believe. On Mac I do:
> 
> ```
> export CC=/usr/local/Cellar/gcc@6/6.5.0_2/bin/gcc-6
> ```

Thanks :)....this worked
