### ISSUE TITLE
function create_hypertable does not exist

### ISSUE THREAD

**Issue by luvpreetsingh** [timescale/timescaledb#163]
I am using ubuntu 16.04 and postgres version 9.6.4

I installed timescale with apt and changed the postgresql.conf file as said in the installation process.

I followed the nyc taxi tutorial, and when importing table schemas, I get this ,

    NOTICE:  table "rides" does not exist, skipping
    DROP TABLE
    CREATE TABLE
    ERROR:  function create_hypertable(unknown, unknown, unknown, integer, create_default_indexes => boolean) does not exist
    LINE 1: SELECT create_hypertable('rides', 'pickup_datetime', 'paymen...
               ^
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
    CREATE INDEX
    CREATE INDEX
    CREATE INDEX
    CREATE INDEX
    CREATE TABLE
    INSERT 0 6 
    CREATE TABLE
    INSERT 0 6

I am getting that error, what does that mean ? Does it mean that the timescale library was not loaded in postgres ?

**Comment by luvpreetsingh** [comment]
I am also not getting any triggers when `\d rides` is run. 

    nyc_data=# \d rides
                          Table "public.rides"
            Column         |            Type             | Modifiers 
    -----------------------+-----------------------------+-----------
     vendor_id             | text                        | 
     pickup_datetime       | timestamp without time zone | not null
     dropoff_datetime      | timestamp without time zone | not null
     passenger_count       | numeric                     | 
     trip_distance         | numeric                     | 
     pickup_longitude      | numeric                     | 
     pickup_latitude       | numeric                     | 
     rate_code             | integer                     | 
     dropoff_longitude     | numeric                     | 
     dropoff_latitude      | numeric                     | 
     payment_type          | integer                     | 
     fare_amount           | numeric                     | 
     extra                 | numeric                     | 
     mta_tax               | numeric                     | 
     tip_amount            | numeric                     | 
     tolls_amount          | numeric                     | 
     improvement_surcharge | numeric                     | 
     total_amount          | numeric                     | 
    Indexes:
        "rides_passenger_count_pickup_datetime_idx" btree (passenger_count, pickup_datetime DESC)
        "rides_pickup_datetime_vendor_id_idx" btree (pickup_datetime DESC, vendor_id)
        "rides_rate_code_pickup_datetime_idx" btree (rate_code, pickup_datetime DESC)
        "rides_vendor_id_pickup_datetime_idx" btree (vendor_id, pickup_datetime DESC)

**Comment by mfreed** [comment]
Given that you closed this already, I assume is you figured this out, but my guess is that you never ran the `CREATE EXTENSION` command to actually load timescaledb?
