### ISSUE TITLE
Request: Continuous Aggregates create from latest data first

### ISSUE THREAD

**Issue by lambdaq** [timescale/timescaledb#1634]
Hi devs,

per [Slack discussion](https://timescaledb.slack.com/archives/C4GT3N90X/p1579239896003900), I have a large table with 1 year of data with a Continuous Aggregates view, the view has a missing column so I have to `drop` the view then re-create it. But as Continuous Aggregates always start from day 1, which is quite long time ago, it makes the whole physical view useless for quite a while.

I suggest when creating Continuous Aggregates, allow some option to aggregate the data from latest first. Then backwards to the oldest. This will make the view available sooner.

**Comment by Habam** [comment]
+1, This will be very useful. Since Continuous Aggregates doesn't pick up an insert which timestamp is 5 month before, every time I insert some legacy data in, I need to re-build the cagg view.

**Comment by trakout** [comment]
+1, 

Currently with a hypertable with billions of rows, I'm looking at a large amount of time to backfill. Setting `add_drop_chunks_policy` to a date in the future (ahead of `completed_threshold`) does not appear to make a difference like one might expect (backfilling does not skip ahead).

**Comment by erimatnor** [comment]
Continuous aggregates will see a major overhaul in 2.0. In short, we're separating the policy (automation) from the core functionality. This will give more control to users over how a continuous aggregate is refreshed. For instance, it will be possible to manually "refresh" a continuous aggregate across a certain region (like @Habam suggested).  As a complement, a policy can be created to automatically refresh starting at recent data (e.g., 1 week back) and moving forward from there, while old data can be refreshed manually (or not at all).

We just released 2.0-beta6 which contains this new functionality and we welcome any feedback. We're aiming for an RC at the end of the month so we'd really appreciate feedback on the new interfaces as soon as possible. Documentation on changes will be out later this week, but Docker images should already be available for those adventurous enough to try it out already now.

**Comment by erimatnor** [comment]
Closing since more flexibility to control the refreshing of a continuous aggregate will be available in 2.0 (which is currently available as a release candidate).

**Comment by ricardo-s-ferreira** [comment]
We hava a lot of data, so we are deleting raw data older then a period of time. We are not able to rebuild continuous aggregates from the first day. 
Now I need to add a new column, there are any option to allow to add new column to Continuous Aggregates?
