### ISSUE TITLE
Request:Support fo PostgreSQL 12 ?

### ISSUE THREAD

**Issue by EdwardMing** [timescale/timescaledb#1635]
Hello everyone,

Our project will update from PostgreSQL 10.11  to PostgreSQL 12 soon, but what a pity that timescaledb seems not support for it. So how long will it supports for pg12 ? 

Thanks.

**Comment by k-rus** [comment]
It is planned for 1.7. For further discussions see https://github.com/timescale/timescaledb/issues/1456

Closing as duplicate

**Comment by EdwardMing** [comment]
Thanks, and sorry for not  notice  it was a repetitive question.
