### ISSUE TITLE
drop_chunks() function results in deadlock

### ISSUE THREAD

**Issue by dewetburger430** [timescale/timescaledb#1638]
**Relevant system information:**
 - OS: CentOS 7.6.1860
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.0
 - Installation method: rpm install from repository

**Describe the bug**
A call to drop_chunks() seems to cause a deadlock occasionally. The following locks are present until I kill the drop_chunks task. Both locks are then cleared.

PID 0:
```
SELECT
    typinput='array_in'::regproc,
    typtype
FROM
    pg_catalog.pg_type
    LEFT JOIN (
        select
            ns.oid as nspoid,
            ns.nspname,
            r.r
        from
            pg_namespace as ns
            join (
                select
                    s.r,
                    (current_schemas(false))[s.r] as nspname
                from
                    generate_series(1, array_upper(current_schemas(false), 1)) as s(r)
            ) as r
        using ( nspname )
    ) as sp ON sp.nspoid = typnamespace
WHERE
    typname = $1
ORDER BY
    sp.r,
    pg_type.oid
DESC LIMIT 1
```
Drop chunks command run every hour:
```
select drop_chunks(schema_name => 'metric_v3', table_name => 'counterdata', older_than => interval '37d');
```

**To Reproduce**
This is difficult to reproduce reliably. I have a running system where datapoints are inserted at an average rate of 8000 points per second. The points are generated by 500 clients.

A maintenance task runs every hour to drop old chunks:
```
select drop_chunks(schema_name => 'metric_v3', table_name => 'counterdata', older_than => interval '37d');
```

**Expected behavior**
Most of the times the drop_chunks function returns after 1-2 seconds. I would expect this to always be the case.

**Actual behavior**
Some time drop_chunks locks until the function is cancelled.

**Screenshots**
The following screenshot shows the rate at which points are written to the database. It is clear that the deadlock situation happened a couple of times during the day. In each case the access to the database was locked such that no inserts could be completed. 
<img width="791" alt="Screenshot 2020-01-16 at 11 46 29" src="https://user-images.githubusercontent.com/57727889/72603511-d183c800-3921-11ea-9c7b-ea82cc190aba.png">

**Comment by gayyappan** [comment]
@dewetburger430  I don't see the locks being held by the drop_chunks process when the deadlock happens. Could you post the locks held by the deadlocking processes?

**Comment by dewetburger430** [comment]
I am not able to reproduce this issue at the moment. I will continue to try and reproduce it and post the info when I have it.

**Comment by dewetburger430** [comment]
We have found another query that caused a deadlock condition. I don't know why I did not see the other query listed as one of the locked processes. I have not been able to reproduce this issue since we have resolved the deadlock in our query.
