### ISSUE TITLE
Continuous Aggregates Need options to drop data

### ISSUE THREAD

**Issue by RJPhillips01** [timescale/timescaledb#1639]
Ubuntu 16.04
TimescaleDB version - 1.6
Docker
--------------------
In version 1.6 you've added additional functionality for continuous aggregates that allows us to ignore invalidation and therefore we can keep data in the cagg even if we drop the raw data. This is great but only if we have options to limit the amount of data we keep in the continuous aggregate.

For example - if we use a cagg to rollup to a 1 minute interval. If we have a lot of items we store data for we could quickly start hitting memory limits from having too much 1 minute data.

It would be nice to be able to use drop_chunks() on a continuous aggregate so that we can manage the data retention for rollups of different widths.

An example - if we have 100,000 stock symbols and we collect raw tick data for each into a hypertable we can then rollup to 1m intervals using a continuous agg. We can then drop the raw data after,say,  48 hours.  The problem is that after a couple of weeks we'll have too much 1 minute data

2 weeks * 7 days * 1440 minutes * 100,000 symbols > 2 Billion rows in our continuous agg view.

**Comment by RJPhillips01** [comment]
Just a thought on this:

I wonder if continuous aggregates could be enhanced in such a way that you have the option to persist / copy the data over to a standard hypertable periodically (and with a certain lag)? 

The data in the view can then be invalidated and dropped when the raw data is dropped but it will have copied / persisted that data over to a hypertable already. 

This would then open up functionality such as drop_chunks() on the persisted data hypertable plus allow for the creation of Indexes on the hypertable that could improve query performance further.

For example:

**raw_data_hypertable** - keep data for 48 hours
**materialized view** - rollup data to 1m intervals - lag 2 minutes / refresh every 2 minutes / data is dropped when raw data is dropped
**1m_rollup_hypertable** - data is copied over from the view every X minutes with a lag of Y minutes, drop_chunks() can be used to drop 1m data older than 7 days / Indexes can be created to speed up queying on this table

queries could then be run to pull data from **1m_rollup_hypertable**, we could then top up the frontend of the data using the cagg view and / or the raw data.

**Comment by jermudgeon** [comment]
It sounds like you're looking for a successor to rrdtool. Conveniently, so am I. :)

**Comment by ssube** [comment]
We're also using caggs to roll up metrics at a variety of buckets (5m, 15m, and 60m currently) and being able to `drop_chunks` for those individually would be tremendously helpful.

**Comment by hedayat** [comment]
A common use-case for this feature would be what PipelineDB called 'sliding windows': e.g. we want aggregation for last 30 days (so we want to continuously remove aggregated data which belongs to dates before that). 
It seems that currently TDB doesn't support it. Using the feature requested in this bug, it can be implemented manually but continuously dropping old data. Having a way to specify the desired time period on the cagg itself would be even better (so that it happens automatically)
