### ISSUE TITLE
How to install as pure Postgres extension?

### ISSUE THREAD

**Issue by ax-ushakov-93** [timescale/timescaledb#1641]
Hello.

Lastest `debian` x64 context.

How to install `timescaledb` as pure `postgres` extension on already installed `postgres` db (from official `postgres` sources)?

Can someone help with this question?

**Comment by mfreed** [comment]
https://docs.timescale.com/latest/getting-started/installation/debian/installation-apt-debian

**Comment by ax-ushakov-93** [comment]
From your link

> If you have another PostgreSQL installation not via apt, this will likely cause problems. If you wish to maintain your current version of PostgreSQL outside of apt, we recommend installing from source. 

How to get pure extension to be installed on already existed `postgresql` instance?

**Comment by wrobell** [comment]
@ax-ushakov-93, I am doing it that way
```
$ cd timescaledb-1.6.0
$ mkdir build
$ cd build
$ cmake .. -DREGRESS_CHECKS=OFF
$ make
$ sudo make install
```

**Comment by ax-ushakov-93** [comment]
Thank you for the answer, but, how to check installation? Do not pass flag
to cmake?

**Comment by ax-ushakov-93** [comment]
@wrobell 

Can you help?

```sh
mkdir build || true
cd build
cmake .. -DREGRESS_CHECKS=OFF
CMake Error: The source directory "/home/alexander/Desktop/timescaledb/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make
make: *** No targets specified and no makefile found.  Stop.
sudo make install
make: *** No rule to make target 'install'.  Stop.
```

**Comment by wrobell** [comment]
Can you please execute `pwd` before `cmake` command to show current working directory?

**Comment by ax-ushakov-93** [comment]
@wrobell 

Yes, problem was in `build/build`. I have installed - as it seems - extension successfully.

Can you suggest - how to check that it is installed properly?

**Comment by wrobell** [comment]
I would create a database, then the extension (please check relevant documentation) and check with
```
select * from pg_extension ;
```

**Comment by mfreed** [comment]
Or run the command `CREATE EXTENSION timescaledb` and then execute `\dx timescaledb`.  See if you have the proper extension installed.

**Comment by ax-ushakov-93** [comment]
```
$ sudo -u postgres psql
postgres=# create database demo;
```


```
$ sudo -u postgres psql demo
psql (11.6 (Debian 11.6-1.pgdg100+1))
Type "help" for help.

demo=# select * from pg_extension;
demo=# create extension timescaledb;
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /etc/postgresql/11/main/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /etc/postgresql/11/main/postgresql.conf 

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
	SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
demo=# 
```

I am totally wrong, yes?

**Comment by mfreed** [comment]
You need to edit the config file to add 'timescaledb' to shared_preload_libraries.  I believe if you also run timescaledb-tune, it will do this (as well as set other configs based on your server hardware).
