### ISSUE TITLE
hypertables wşith continuous aggregates do not drop_chunks() properly

### ISSUE THREAD

**Issue by RJPhillips01** [timescale/timescaledb#1644]
Timescaledb version 1.6

We've been evaluating timescale db recently - the continuous aggs are of particular interest to us. We've come across a big problem:

If we have a hypertable with raw data and create a continuous aggregate on it, when we run drop_chunks() on the raw hypertable data it doesn't cascade properly to the view.

we see that timescale is running a DELETE FROM on any continuous aggregates linked to the raw table. This degrades performance to the point that the database can lock up completely.

**To Reproduce**
create a simple hypertable with columsn such as:

time,
symbol,
measure

create a continuous aggregate on the hypertable to aggregate to 1 minute intervals and generate first,high,low,last

load some random data to the hypertable  - we tested about 12M rows spanning 12 hours

let the cagg get up to date

try to drop_chunks() from the hypertable - it may fail, it may take a long time and suceed, you may get bored and cancel it. (When cancelling we see a message showing that timescaledb is attempting to do a DELETE FROM to the materialized view hypertable)

if you drop the cagg and then attempt drop_chunks() then the data is dropped really fast.

**Expected behavior**
Would have thought the cascaded drops to the materialized view would be handled with a drop_chunks() command and not a DELETE FROM ....  

This bug makes continuous aggregates unusable for us right now.

In 1.6 you introduced the option to persist caggs after dropping raw data. If there was a way to drop data from the cagg independently of the raw data then that would provide a viable workaround but unfortunately that doesnt exist right now (we logged an issue for that also)

Thanks, Rich.

**Comment by bboule** [comment]
@RJPhillips01 can you provide the SQL used to create the Cont Agg specifically we are looking for the invalidation setting which enables the ability to remove the underlying data... also the commands used to set up the drop chunks policy again looking for cascade_to_materializations=>FALSE  parameter 

Just want to confirm you went about this in the proper fashion before we declare a bug.

Thanks

**Comment by gayyappan** [comment]
Steps to repro:
```
drop table ciscalc_ticks_temp cascade;
  
CREATE TABLE ciscalc_ticks_temp (
 ts        TIMESTAMP      NOT NULL,
 symbol    TEXT              NOT NULL,
 tick DOUBLE PRECISION NOT NULL,
 t_v DOUBLE PRECISION NOT NULL,
 t_vt DOUBLE PRECISION NOT NULL,
 d_v DOUBLE PRECISION NOT NULL,
 d_vt DOUBLE PRECISION NOT NULL
);
SELECT create_hypertable('ciscalc_ticks_temp', 'ts',chunk_time_interval => interval '10 minutes');
CREATE INDEX ON ciscalc_ticks_temp(symbol,ts DESC) WITH (timescaledb.transaction_per_chunk);


CREATE VIEW ciscalc_1m_rollup (symbol,ts,o,h,h_ts,l,l_ts,c,t_v,t_vt,d_v,d_vt)
WITH (
    timescaledb.continuous,
    timescaledb.refresh_lag = '3m',
    timescaledb.refresh_interval = '3m' )
AS
SELECT
        symbol,
        time_bucket('1m',ts) as ts,
        first(tick,ts) as o,
        max(tick) as h,
    last(ts,tick) as h_ts,
        min(tick) as l,
    first(ts,tick) as l_ts,
        last(tick,ts) as c,
        last(t_v,ts) as t_v,
        last(t_vt,ts) as t_vt,
        last(d_v,ts) as d_v,
        last(d_vt,ts) as d_vt
FROM    ciscalc_ticks_temp
GROUP BY time_bucket('1m',ts),symbol;

----- set the chunk interval for materialized hypertable ---
SELECT set_chunk_time_interval('_timescaledb_internal._materialized_hypertable_2', interval '10 minutes');
```
```
insert into ciscalc_ticks_temp
select generate_series('2020-01-13 00:00:00+0'::timestamptz,'2020-01-13 00:30:00+0','10s') , 'msft', 5000, 10, 10, 0, 0;
insert into ciscalc_ticks_temp
select generate_series('2020-01-20 08:00:00+0'::timestamptz,'2020-01-20 08:55:00+0','10s') , 'gog', 7000, 70, 7, 0, 0;
```
After cagg materialization is complete, try to drop chunks
select drop_chunks(interval '5 days', 'ciscalc_ticks_temp', cascade_to_materializations => TRUE);

the chunks on the materialization hypertable are not dropped . Instead the data is deleted from the table.
