### ISSUE TITLE
add_compress_chunks_policy fails with bigint time interval

### ISSUE THREAD

**Issue by siemib** [timescale/timescaledb#1653]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
```
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 4.4.161-1.el7.elrepo.x86_64
```
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
`11.6`
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
`1.6.0`
 - Installation method: [e.g., "using Docker", "apt install", "source"]
`Docker` image `timescale/timescaledb@sha256:7f1d2869dcb7a193b190286887d804a95f0c3eb0f503ea9a4df702efcdc8a125`

**Describe the bug**
Timescal fails to add compression policy on hypertable in which chunk time interval is specified as `BIGINT` or `INTEGER`

`[2020-01-24 12:32:04] [22023] ERROR: integer_now_func not set on hypertable test_table_1`

**To Reproduce**
```sql
CREATE TABLE IF NOT EXISTS test_table_1
(
    created_at bigint,
    data       TEXT
);

SELECT create_hypertable
           (
               'test_table_1',
               'created_at',
               chunk_time_interval => 86400000000000,
               if_not_exists => TRUE
           );



ALTER TABLE test_table_1
    SET (
        timescaledb.compress,
        timescaledb.compress_orderby = 'created_at DESC'
    );

SELECT add_compress_chunks_policy('test_table_1', 86400000000000);
```

**Expected behavior**
This should work as documented in [api docs](https://docs.timescale.com/latest/api#add_compress_chunks_policy-sample-usage)

**Comment by bboule** [comment]
Hey @siemib thanks for the report, is there any chance you could tail the logs out for us and add any relevant logs information as well?

**Comment by geoffreybennett** [comment]
I'm pretty sure that it is working as per the API docs and the reported error `integer_now_func not set on hypertable test_table_1` is correct. The [API docs](https://docs.timescale.com/latest/api#add_compress_chunks_policy) explicitly say: "hypertables with integer-based timestamps ... [require] the [integer_now_func](https://docs.timescale.com/latest/api#set_integer_now_func) to be set". I was able to reproduce the error and after calling set_integer_now_func() also able to call add_compress_chunks_policy() successfully.

**Comment by siemib** [comment]
Awesome. I'll try that.

**Comment by gayyappan** [comment]
Thanks @geoffreybennett. closing as not an issue.

**Comment by typecampo** [comment]
How did you manage to set the integer_now_func to use nanoseconds? Im trying to do something like this for simple testing and the chunks policy does not compress for every 2 min.

```
CREATE OR REPLACE FUNCTION unix_now() returns BIGINT LANGUAGE SQL STABLE as $$ SELECT extract(epoch from now())::BIGINT $$;
CREATE OR REPLACE FUNCTION unix_now_nano() returns BIGINT LANGUAGE SQL STABLE as $$ SELECT unix_now() * 1000000000::BIGINT $$;
SELECT set_integer_now_func('messages', 'unix_now_nano');
SELECT add_compress_chunks_policy('messages', BIGINT '120000000000');
```
