### ISSUE TITLE
Performing data down-sampling 

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [timescale/timescaledb#1659]
Does timescaledb supports data down-sampling queries. Does it has a build in first class query for data down-sampling.
And what about the performance. I will run down-sampling query on the database every 5 seconds. is it a slow operation to perform(on a reasonably large dataset)

I'm currently using griddb which has build in down-sampling operator and very fast.

**Comment by mfreed** [comment]
Hi @harshajayaweeraXHJ Is this want you want?

https://blog.timescale.com/blog/how-to-proactively-manage-long-term-data-storage-with-downsampling/

If not, can you detail a bit more the semantics you want?

**Comment by bboule** [comment]
@harshajayaweeraXHJ  I just wanted to follow up with you and see if the blog answered your questions or if there was some follow up we might provide?

**Comment by bboule** [comment]
@harshajayaweeraXHJ  I suspect you got what you needed on in the blog post... but just to add a little commentary here... you should find our down-sampling process performance in that we are making use of our continuous aggregates feature which is pre-computing the down sampled values and storing them in a materialized view, and you can generate this view to update on a frequency that suits your use case (making sure that your instance has access to enough resources to run the refresh based on your desired time interval).  

Going to close this out, and will invite you to re-open should you have additional questions.
