### ISSUE TITLE
Function distributed_exec always transactional

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#1660]
When using `distributed_exec` for executing statements that cannot be executed inside a transaction, an error is given. For example:

```
=> SELECT * FROM distributed_exec($$ CREATE Database test $$);
ERROR:  [dn2]: CREATE DATABASE cannot run inside a transaction block
```

This behavior is not possible to disable.

Suggested improvement is to add a parameter to `distributed_exec` allowing the distributed execution to run without a transactional context.

**Comment by harikrishnaroy** [comment]
@mkindahl Thanks for your help. But if i want to create a new database on the multinode. What is the possible way to do it. As I am trying to create a new database on the access node that is not reflecting on to the data nodes.

**Comment by mkindahl** [comment]
Without the suggested change, you would have to log into the data node and create the database explicitly there through a normal interface.
