### ISSUE TITLE
Unable to disable compression

### ISSUE THREAD

**Issue by jermudgeon** [timescale/timescaledb#1661]
**Relevant system information:**
 - OS: Debian 9.11
 - postgres (PostgreSQL) 10.11 (Debian 10.11-1.pgdg90+1)

 - TimescaleDB version  timescaledb | 1.6.0 
 - Installation method: apt install

**Describe the bug**
While investigating query plan optimization, I discovered that I cannot disable compression on a hypertable with no compressed chunks or compression policies.

**To Reproduce**
1. `alter table <table> SET (timescaledb.compress=true,timescaledb.compress_orderby='<col1>',timescaledb.compress_segmentby='<col2>');` `ALTER TABLE`
2. `# alter table <table> SET (timescaledb.compress=false);
ERROR:  constraint <constraint> requires column item_id to be a segment_by or order_by column for compression
HINT:  Only segment by and order by columns can be used in constraints on hypertables that are compressed.`
3. `ALTER TABLE <table> DROP CONSTRAINT <constraint>;` 
4. `ERROR: operation not supported on hypertables that have compression enabled`

**Expected behavior**
I expect that compression can be disabled.

**Actual behavior**
Compression cannot be disabled.

**Screenshots**

**Additional context**

**Comment by gayyappan** [comment]
I am unable to repro this: 
```
create table  table_constr( device_id integer,
                    timec integer ,
                    location integer ,
                   c integer constraint valid_cval check (c > 20) ,
                   d integer,
                    primary key ( device_id, timec)
);
select table_name from create_hypertable('table_constr', 'timec', chunk_time_interval=> 10);

test2=# ALTER TABLE table_constr set (timescaledb.compress, timescaledb.compress_segmentby = 'd');
ERROR:  constraint "table_constr_pkey" requires column "device_id" to be a timescaledb.compress_segmentby or timescaledb.compress_orderby column for compression
HINT:  Only columns specified in timescaledb.compress_segmentby and timescaledb.compress_orderby can be used in constraints on hypertables that are compressed.
test2=# ALTER TABLE table_constr set (timescaledb.compress=false);
ALTER TABLE
```

**Comment by gayyappan** [comment]
@jermudgeon Could you post a test case for this ?

**Comment by gayyappan** [comment]
@jermudgeon Could you provide a test case? I am not able to repro this issue.
```
create table  table_constr( device_id integer,
                    timec integer ,
                    location integer ,
                   c integer constraint valid_cval check (c > 20) ,
                   d integer,
                    primary key ( device_id, timec)
);
select table_name from create_hypertable('table_constr', 'timec', chunk_time_interval=> 10);

test2=# ALTER TABLE table_constr set (timescaledb.compress, timescaledb.compress_segmentby = 'd');
ERROR:  constraint "table_constr_pkey" requires column "device_id" to be a timescaledb.compress_segmentby or timescaledb.compress_orderby column for compression
HINT:  Only columns specified in timescaledb.compress_segmentby and timescaledb.compress_orderby can be used in constraints on hypertables that are compressed.
test2=# ALTER TABLE table_constr set (timescaledb.compress=false);
ALTER TABLE
```

**Comment by b4eEX** [comment]
@gayyappan the constraint has to be FK for it to not work. CHECKs seem okay.

**Comment by gayyappan** [comment]
@b4eEX Thanks, I am able to repro with a FK.
