### ISSUE TITLE
Compress Chunks Background Worker fails if owner role cannot log in

### ISSUE THREAD

**Issue by aaliddell** [timescale/timescaledb#1662]
**Relevant system information:**
 - OS: Whatever is in the Docker image
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.1
 - Installation method: Docker

**Describe the bug**
If tables are owned by a role that cannot login (has `NOLOGIN`), the background chunk compression worker will fail:

```
2020-01-30 01:16:46.368 UTC [21204] FATAL:  role "thing_owner" is not permitted to log in
2020-01-30 01:16:46.368 UTC [1] LOG:  background worker "Compress Chunks Background Job" (PID 21204) exited with exit code 1
```

This appears to be because the background worker is created with the user that owns the table? 

https://github.com/timescale/timescaledb/blob/1a387963465cb97e88fb362a271afaf3e7f319d2/src/bgw/job.c#L120

This same issue will show up for any other background workers that operate the same way.

**To Reproduce**

1. Create some role that is not allowed to login:

`create role thing_owner with nologin noinherit;`

2. Create a user that has the owner role:

`create user someone with password 'something' in role thing_owner;`

3. Change the database owner to this new role (this step probably isn't needed):

```
alter database <name of database> owner to thing_owner;
grant connect on database <name of database> to someone;
```

3. Disconnect and login as the new user.

4. Become the owner role and create a new table:

```
set role thing_owner;

create table something(
    time timestamptz not null default now(),
    val float not null,
);

select create_hypertable(
    main_table => 'something',
    time_column_name => 'time',
    chunk_time_interval => interval '1 day',
);
```

5. Create a chunk compression policy:

```
alter table something set (timescaledb.compress);
select add_compress_chunks_policy('something', interval '1d');
```

6. Wait for the chunk compression background worker to run and you should see the error above

**Expected behavior**
Chunks should be compressed.

The error getting thrown appears to originate from the [`InitializeSessionUserId`](https://github.com/postgres/postgres/blob/7559d8ebfa11d98728e816f6b655582ce41150f3/src/backend/utils/init/miscinit.c#L579) function, which is presume is getting called as the worker starts up as the owner of the table. As this role is marked `NOLOGIN`, this startup will fail.

I don't see a way around this without spawning the worker as a different role and transitioning internally to the correct role after startup. Unless Postgres has a method of starting a worker as a role that has `NOLOGIN` without doing the checks that apply to client connections.

The docs for `NOLOGIN` state the following:

> These clauses determine whether a role is allowed to log in; that is, whether the role can be given as the initial session authorization name during client connection

**Actual behavior**
See the description above.

**Comment by aaliddell** [comment]
There is a `InitializeSessionUserIdStandalone` function that is for workers with `IsBackgroundWorker` (or some other conditions). Is this suitable for the Timescale background workers, rather than using `InitializeSessionUserId`?

**Comment by erelin6613** [comment]
I experience the same issue. If it can help here is how I got here:
`CREATE ROLE val;`
`ALTER USER val with password 'password';`

**Comment by WireBaron** [comment]
We are requiring that hypertable owners must have LOGIN permission to make use of features that require background workers.  We did add a check to catch this and provide a more useful error here: https://github.com/timescale/timescaledb/pull/1709
