### ISSUE TITLE
ERROR:  [data01]: relation "query_id_seq" does not exist

### ISSUE THREAD

**Issue by gomex** [timescale/timescaledb#1663]
**Relevant system information:**
 - Docker: timescaledev/timescaledb:2.0.0-beta4-pg11 
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 11.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0-beta4
 - Installation method: using Docker

**Describe the bug**
I tried to use create_distributed_hypertable, but I got this error:

```
ERROR:  [data01]: relation "query_id_seq" does not exist
```

**To Reproduce**
1. SET ROLE testuser;
2. CREATE TABLE query
(
  id BIGSERIAL,
  time TIMESTAMP NOT NULL,
  orgid INTEGER,
  networkid INTEGER
);

3. SELECT create_distributed_hypertable('query', 'time', chunk_time_interval => 86400000000);
4. See error "ERROR:  [data01]: relation "query_id_seq" does not exist"

**Expected behavior**
The distributed_hypertable on data nodes.

**Actual behavior**
No distributed_hypertable was created.

**Screenshots**
N/A

**Additional context**
The data nodes were added:

```
SELECT * FROM timescaledb_information.data_node;
 node_name | owner |                          options                          | node_up | num_dist_tables | num_dist_chunks | total_di
st_size 
-----------+-------+-----------------------------------------------------------+---------+-----------------+-----------------+---------
--------
 data01 |    10 | {host=data01.domain.co,port=35000,dbname=database} | t       |               0 |                 | 
 data02 |    10 | {host=data02.domain.co,port=35000,dbname=database} | t       |               0 |                 | 
```

**Comment by pmwkaa** [comment]
Quick looks at it seems like it is a deparsing bug, which happens during `CREATE TABLE` deparsing by `create_distributed_hypertable()` call. Basically `BIGSERIAL` will be converted to `BIGINT` on data nodes. Apparently `deparse_columns()` or `format_type_with_typemod()` is to blame.

**Comment by MikeSchroll** [comment]
Hi @pmwkaa Does it mean that we can just change from using the 'convenience' function of the bigserial and instead do something like:

`CREATE SEQUENCE tablename_colname_seq;
CREATE TABLE tablename (
    colname bigint NOT NULL DEFAULT nextval('tablename_colname_seq')
);
ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;`
ref: https://www.postgresql.org/docs/9.3/datatype-numeric.html

and it will work fine? It's just that the parser is not correctly handling the expansion?

**Comment by MikeSchroll** [comment]
We've had success using this work-around.
