### ISSUE TITLE
[question] Compression API question

### ISSUE THREAD

**Issue by atumilovics-zabbix** [timescale/timescaledb#1667]
Hi,

We are working on TimescaleDB compression feature support in Zabbix.
By using your [API](https://docs.timescale.com/latest/api), we would like to have three more things:
1) get hypertable segmentation/orderby options;
2) get compress chunk policy time interval for hypertable;
3) check if chunk compression policy is configured for hypertable.

Maybe, the above information can be added to timescaledb_information views?
Right now we found that we can get required information from "_timescaledb_catalog.hypertable", "_timescaledb_catalog.hypertable_compression" and "_timescaledb_config.bgw_policy_compress_chunks".

**Example:**
Get compression time interval (integer):
`
SELECT (p.older_than).integer_interval
FROM _timescaledb_config.bgw_policy_compress_chunks p
INNER JOIN _timescaledb_catalog.hypertable h on (h.id = p.hypertable_id)
WHERE h.table_name='<table name>'
`
Get segmentby option of a hypertable:
`
SELECT attname
FROM _timescaledb_catalog.hypertable_compression c
INNER JOIN _timescaledb_catalog.hypertable h on (h.id = c.hypertable_id)
WHERE c.segmentby_column_index<>0 and h.table_name='<table name>'
`

However, we would like to clarify if we can rely on these table structure and they will not be changed in upcoming versions.

**Comment by k-rus** [comment]
@atumilovics-zabbix Thank you for using TimescaleDB and for your request.
The internal catalog tables might change between releases, so we don't advise to rely on them. However, it doesn't happen often. 
We will look to improve the information views and include the requested information.

**Comment by atumilovics-zabbix** [comment]
@k-rus Thank you!

**Comment by k-rus** [comment]
@atumilovics-zabbix We are looking to improve and reorganise the information views. If you have more requests or suggestions, welcome to post. It will be useful to have feedback from active users. Thank you.

(for now, you might want to rely on the internal catalog tables depending on what date you are target for your release)

**Comment by erimatnor** [comment]
The requested information will be available through official views in 2.0 (currently available as release candidate).
