### ISSUE TITLE
index of empty hyper chunk take up space

### ISSUE THREAD

**Issue by cossbow** [timescale/timescaledb#1676]
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): 11.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.2
 - Installation method: yum install

**Describe the bug**
After working months, some empty hyper chunk, contains no rows, bug index still take up dozens KB to hundreds MB space. 
I find 355 cases, total size 48GB. 
Can I clean and recycle the space?
My statistic sql was:
`
select oid,
relname "tableName",
 reltuples  "rowsCount" ,
 pg_size_pretty(pg_relation_size(oid)) "size",
pg_indexes_size(oid) "indexSize",
 pg_size_pretty(pg_indexes_size(oid)) "indexSizePretty"
from pg_class where relkind = 'r' 
and relnamespace = (select oid from pg_namespace where nspname='_timescaledb_internal') 
order by pg_relation_size(oid) desc;  
`

**Comment by erimatnor** [comment]
Thank for the bug report @cossbow. Is it possible for you to provide a way to reproduce this issue? How did you end up with empty chunks?

**Comment by cossbow** [comment]
> Thank for the bug report @cossbow. Is it possible for you to provide a way to reproduce this issue? How did you end up with empty chunks?
The problem occured when frequently updates cause index expansion; I used hypertable to store tens of millis schedule recoreds, updated frequently for each rows... 
I think it doesn't work in this scenario, but it's so convenient.

**Comment by erimatnor** [comment]
Did you try to run vacuum to cleanup the deleted data?
