### ISSUE TITLE
ERROR:  tried calling catalog_get when extension isn't loaded

### ISSUE THREAD

**Issue by shirshendubhowmick** [timescale/timescaledb#1681]
Suddenly started getting error:

`ERROR:  tried calling catalog_get when extension isn't loaded`

while creating new hypertables

There was no version upgrades made recently in the server.

**Comment by shirshendubhowmick** [comment]
Closing this issue to open a new issue, as this seems to be a possible bug.

**Comment by peterbecich** [comment]
https://github.com/timescale/timescaledb/issues/1682
