### ISSUE TITLE
timescaledb_information.compressed_chunk_stats - machine readable version

### ISSUE THREAD

**Issue by wrobell** [timescale/timescaledb#1683]
Is there a way to get `timescaledb_information.compressed_chunk_stats` output in machine readable version?

For example, to find average or maximum size of a compressed chunk.

**Comment by bboule** [comment]
hey @wrobell you might want to play around with something like 

SELECT hypertable_name, chunk_name, compression_status, uncompressed_total_bytes, compressed_total_bytes
FROM timescaledb_information.compressed_chunk_stats limit 300;

This will give you stats on some compressed chunks and from there you might generate a view that will apply some mix, max, avg functions on the data.  I am also marking this as a enhancement as we are currently looking at adding to our informational tables perhaps we might build something in like this going forward.  Let me know if you have any follow on questions?

**Comment by wrobell** [comment]
If I am not mistaken, the `*_total_bytes` columns are text in human readable form, i.e. `99 KB`, `100 MB` (or similar). Max of `(99 KB, 100 MB)` is going to be `99 KB`. The `avg` will not work at all.

**Comment by bboule** [comment]
@wrobell  I see your point I will add this as an enhancement to the informational tables we will get these request into the queue

**Comment by wrobell** [comment]
@bboule  thank you

**Comment by gayyappan** [comment]
Starting with 2.0, this information is available via functions chunk_compression_stats and hypertable_compression_stats. The size is in bytes.
