### ISSUE TITLE
Nothing works here, even the documentation for installation of timescaledb is fraud.

### ISSUE THREAD

**Issue by vishal9565** [timescale/timescaledb#1684]
I followed the original doc and it looks like they don't check before putting online. They called it a product. **Full of craps**

First I got cascade error and then parallel error which is exhausting. Please solve the piece of shit. And give the good documentation. I wasted 4 hours installing and reinstalling in ubuntu 16.4 lts

Give proper documetation

**Comment by mfreed** [comment]
@vishal9565 This report fails our community standards.

If you have a concrete issue/bug to report, please follow github issues and maintain the necessary level of professionality.
