### ISSUE TITLE
hypertable view in timescaledb_information returns "_timescaledb_internal._hyper_2_10_chunk" does not exist

### ISSUE THREAD

**Issue by zcavaliero** [timescale/timescaledb#1692]
- OS: Ubuntu 16.04,
 - PostgreSQL version (output of `postgres --version`): 11
 - TimescaleDB version (output of `\dx` in `psql`): 1.6
 - Installation method: apt install

I've built a continuous aggregation following this link: https://blog.timescale.com/blog/timescaledb-1-6-data-retention-policies-for-continuous-aggregates/
After setting up a step to delete the underlying data in the original table, I tried to do a Select * on the view timescaledb_information.hypertable. When I do that, I get the following error:
ERROR:  relation "_timescaledb_internal._hyper_2_10_chunk" does not exist
CONTEXT:  PL/pgSQL function hypertable_relation_size(regclass) line 12 at RETURN QUERY
SQL state: 42P01

When I run this:
SELECT * FROM _timescaledb_catalog.chunk
WHERE dropped=true

timescaledb_internal._hyper_2_10_chunk has the dropped flag set so I suspect it to get ignored by the hypertable_relation_size call, but I think it is trying to look for size information on that chunk anyways.

Thanks,

Zac

**Comment by mfreed** [comment]
Thanks for the report @zcavaliero .  Would you be able to include specific instructions/script on how we could try to reproduce the error?

Thanks!

**Comment by bboule** [comment]
@zcavaliero I wonder if there may be some form of race condition happening here ... Can you tell us if this still happening (either way we will investigate) but I wonder if there was some delay in the internal update after the drop happened ? Where your query beat the update of the internal table? If it is still happening it sounds bigger than that, but if it worked itself out over time that may be a different issue for us to look at!!! Thanks for the report!!

**Comment by zcavaliero** [comment]
@bboule it's still happening this morning unfortunately! 

@mfreed I have my DB setup using data from prometheus, but I assume this would happen with any kind of data that gets dropped and is still trying to get polled.

This is probably the closest set of instructions I can get to recreate:
Follow directions to setup prometheus data:  source:https://docs.timescale.com/latest/tutorials/prometheus-adapter

CREATE VIEW prometheus.one_hour_rollup
WITH (timescaledb.continuous)
AS
SELECT time_bucket('1 hour', time) AS bucket, labels_id, avg(value) AS one_hour_avg
FROM prometheus.metrics_values
GROUP BY bucket,labels_id;

ALTER VIEW prometheus.one_hour_rollup SET (timescaledb.ignore_invalidation_older_than = '7d');

SELECT drop_chunks(interval '7 days', 'metrics_values',cascade_to_materializations => false);

Once something gets dropped (you can change the interval to a couple hours or something to get the same effect I would think) this is the part of the hypertable view that ends up breaking:
select * from public.hypertable_relation_size('prometheus.metrics_values');

As I said before, I'm assuming that when hypertable_relation_size is called, that it isn't ignoring the "dropped" flag that is set.

Let me know if there is anything else I can help with and thanks for the speedy response!

**Comment by zcavaliero** [comment]
I think I figured out where the bug is. Please check out my pull request here: https://github.com/timescale/timescaledb/pull/1698

**Comment by bboule** [comment]
@zcavaliero  thank you for the work here will have a member of the engineering team take a look ASAP!!
