### ISSUE TITLE
refresh_lag timezone problem

### ISSUE THREAD

**Issue by ismailakpolat** [timescale/timescaledb#1695]
**Relevant system information:**
 - OS: cent os 11
 - PostgreSQL version : 11.2
 - TimescaleDB version : 1.6
 - Installation method: yum

**Describe the bug**
I have a continuous aggregate with refresh_lag = - 1 hour and bucket size = 1 hour and runs every 10 minutes. In version 1.5 it had no problem. Every 10 minutes data become updated. However after upgrading from 1.5 to 1.6, data always updated to be 3 hours before the current time. Timezone is +3 gmt and i tried changing refresh_lag to be -4 hour and my problem was solved. 

**To Reproduce**
1. Set timezone to +3 gmt
2. Create view:
CREATE VIEW anonymous_log.service_usage_info_hourly_summary( date, application_type, province, service_code, usage_count )
WITH ( timescaledb.continuous,
    timescaledb.refresh_lag = '-1h',
  	timescaledb.max_interval_per_job = '1 week',
  	timescaledb.refresh_interval = '10m',
  	timescaledb.ignore_invalidation_older_than = '60 day'
    )
AS
SELECT time_bucket('1 hour', log_timestamp) as date, application_type, province, service_code, count(*)
FROM anonymous_log.service_usage_info
GROUP BY date, application_type, province, service_code;

3. Check data after 1 hour nothing happens, after 2 hour nothing happens. Check data after 3 - 4 hour. You will see table contains data from 3 hour earlier.

Note: I also tried with refresh_lag = '-1d' same problem occurs. refresh_lag with -1m and so can be given for testing purposes.

**Expected behavior**
Every 10 minutes data to become live.

**Actual behavior**
Table contains data from 3 hours earlier.

**Comment by gayyappan** [comment]
@ismailakpolat  Could you post the table definition here? Looking for the datatype for "log_timestamp" column.

**Comment by ismailakpolat** [comment]
Something like this:

```sql
CREATE TABLE anonymous_log.service_usage_info (
	ip_address varchar(255) NULL,
	service_code int4 NOT NULL,
	operation_code int4 NULL,
	session_code varchar(255) NULL,
	log_timestamp timestamp NOT NULL,
	application_type int2 NOT NULL DEFAULT 1,
	province int4 NULL,
	id bigserial NOT NULL,
	CONSTRAINT service_usage_info_un UNIQUE (log_timestamp, id)
);
CREATE INDEX service_usage_info_log_timestamp_idx ON anonymous_log.service_usage_info USING btree (log_timestamp DESC);
```
