### ISSUE TITLE
Error adding timescaledb extension

### ISSUE THREAD

**Issue by amrithathorath** [timescale/timescaledb#1700]
I see the following error:

```
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: C:/Program Files/PostgreSQL/11/d
ata/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
        echo "shared_preload_libraries = 'timescaledb'" >> C:/Program Files/Post
greSQL/11/data/postgresql.conf

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without
 preloading, you can disable this check with:
        SET timescaledb.allow_install_without_preload = 'on';
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

My postgresql.conf config file has this:
```
# - Shared Library Preloading -
shared_preload_libraries = 'timescaledb'	# (change requires restart)
```

I'm running this on Windows (not using Docker images).

```
C:\Users\aaa>pg_config --version
PostgreSQL 11.7
```

PS: I've looked at the other issues raised on github and none of them helped me.
Any help is appreciated, thanks!

**Comment by laconical77** [comment]
If this was a fresh install of 11.7, you'll need to get libeay32.dll and ssleay32.dll from somewhere as they need to live in your PostgreSQL\11\bin directory and aren't included in the installer any more. See [here ](https://github.com/timescale/timescaledb/issues/1398) for more info.

**Comment by amrithathorath** [comment]
@laconical77 : I've first installed PostgreSQL 11.4 and then upgraded to 11.7.
I've made sure libeay32.dll and ssleay32.dll are present in bin folder and then installed successfully timescaledb. But I still see the same error.

**Comment by amrithathorath** [comment]
I'm just going to downgrade the version and use it.

**Comment by 3242433424** [comment]
i tried it with 11.4 too.  libeay32.dll and ssleay32.dll are in the bin Folder, but still getting 

FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: C:/Program Files/PostgreSQL/11/d
ata/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
        echo "shared_preload_libraries = 'timescaledb'" >> C:/Program Files/Post
greSQL/11/data/postgresql.conf

Please help
