### ISSUE TITLE
no installation script for timescaledb

### ISSUE THREAD

**Issue by mhechthz** [timescale/timescaledb#1701]
**Relevant system information:**
 - OS: Windows 7x64
 - PostgreSQL version 11.7 (installer.exe --> successful)
 - TimescaleDB version 1.6.0 (zip and setup.exe --> successful)
    but relevant dll's copied by hand to lib directory and timescaledb.control copied by hand to share/extensions, because setup didn't

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
--> 
ERROR:  FEHLER:  Erweiterung »timescaledb« hat kein Installationsskript und keinen Aktualisierungspfad für Version »1.6.0«
SQL state: 22023

What now?

**Comment by khaledsharie92** [comment]
Hello mhechthz did you found the solution? I Use also psql 11.6 and installed the timescaledb but **when i run :** CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
 **came the Error message:** »C:/Program Files/PostgreSQL/11/lib/timescaledb-1.6.0.dll« nicht laden: The specified module could not be found.

**Comment by k-rus** [comment]
Can you provide more details about your environment and how have you installed TimescaleDB?
Where have you installed PostgreSQL? Is it in `Program files`, which is default? Have you run `setup.exe` to install TimescaleDB as Administrator or normal user? Have you run `timescaledb-tune` as part of the installation?

I guess you cannot post what was the setup printed when you run it.

**Comment by cossbow** [comment]
I manual install the PostgreSQL, and also add to %Path%, when create extension got this tips, version 1.6.1 and 1.7.4 cannot, but older 1.4 can

**Comment by mfreed** [comment]
I think this is a duplicate of:  https://github.com/timescale/timescaledb/issues/1398

Closing for now, feel free to re-open if not.
