### ISSUE TITLE
Bgw job deletion not detected

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#1703]
A BGW job is deleted but the scheduler does not correctly process it. The scheduler repeatedly prints
messages like `scheduler detected that job 1026 was deleted when starting job`. Verified that the job was indeed deleted. So the problem is not that the job doesn't start but that the scheduler fails to remove it from the job list

Workaround: Either restart postgres or  running `SELECT _timescaledb_internal.restart_background_workers()`

We've had several reports including https://timescaledb.slack.com/archives/C63MYDZ35/p1582065874083200

**Comment by cevian** [comment]
Notes on the problem:

The jobs list get updated in `ts_update_scheduled_jobs_list` which only gets called by if `jobs_list_needs_update` is true. The `jobs_list_needs_update` flag gets set only by  `ts_bgw_job_cache_invalidate_callback`. So I think that doesn't get called for some reason.

Looking at `cache_invalidate_callback` I think there are two problems: If `relid` is InvalidOid we should be calling `cache_invalidate_all();` which I don't think we are. Also we should be calling `ts_bgw_job_cache_invalidate_callback();` from inside `cache_invalidate_all()`

For safety we should also be setting  `jobs_list_needs_update` flag to true after the deletion is detected during bgw startup at line 251 in scheduler.c

**Comment by mfreed** [comment]
Thanks for the report @jtushman

**Comment by jtushman** [comment]
Hey note:

I think this happened in a migration where i dropped the view and then created a similar one. i.e.:

DROP VIEW "weekly_events_view";

I *think* it also happens on dump/restore

**Comment by erimatnor** [comment]
Closing since it seems fixed.
