### ISSUE TITLE
Cannot copy AMI across regions

### ISSUE THREAD

**Issue by highway900** [timescale/timescaledb#1707]
I would like to be able to use the AMI you provide in the `ap-southeast-2` region 

I tried to copy the AMI but I get an error `An error occurred (InvalidRequest) when calling the CopyImage operation: You do not have permission to access the storage of this ami`

Is it possible to either update the permission or create a `ap-southeast-2` AMI for consumption?

Cheers.

**Comment by vinayuttam** [comment]
@highway900 Were you able to copy the AMI to a different region?
