### ISSUE TITLE
Got ERROR:  [dn1]: no connection to the server when trying to add datanode on access node

### ISSUE THREAD

**Issue by ldzhjn** [timescale/timescaledb#1708]
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0-beta4
 - Installation method: source

**Describe the bug**

I'm trying to build a three nodes timescaledb cluster using this tutorial.
https://docs.timescale.com/clustering/tutorials/clustering
When I ran this command on the access node
SELECT add_data_node('dn1', host=>'IP address');
ERROR:  [dn1]: no connection to the server

Meantime, when I try to connect to the remote data node on the access node using this command
psql -h IP
I can connect after inputing password

**Comment by bruno-villa** [comment]
Did you solve this problem? I am seeing the same running 2.0.0-rc2 on Docker. 
```
$ psql -U postgres -c "SELECT add_data_node('rep1', host => '11.196.144.195', port => '5432');"
ERROR:  no connection to the server
```
But the IP is correct and I can run `psql -U postgres -h 11.196.144.195 -p 5432` without issues.

**Comment by dibdutta** [comment]
Any update on this issue , not sure its closed without any proper resolution comments. I am seeing the issue for `timescaledb : 2.0.0-rc4`  too.
