### ISSUE TITLE
min and max aggregate fails on same select

### ISSUE THREAD

**Issue by rahulbsw** [timescale/timescaledb#1723]
### Relevant system information:

- OS: Centos 7 64bit
- PostgreSQL version (output of postgres --version): 11.6
- TimescaleDB version (output of \dx in psql): 2.0.0 Beta 4
- Installation method: "yum install"

### Describe the bug

Getting below error , when using min and max aggregate in same query in on distributed hybertable

`SQL Error [XX000]: ERROR: failed to set single row mode for SELECT "time" FROM public.<TABLE> WHERE _timescaledb_internal.chunks_in(public.<TABLE>.*, ARRAY[165, 167, 166]) AND (("time" IS NOT NULL)) ORDER BY "time" DESC NULLS FIRST`

```sql 
select min(time ),max(time)
from <table>
```

**Comment by rahulbsw** [comment]
Getting same error when I refresh Continues aggregate view manualy


```sql
REFRESH MATERIALIZED VIEW health_report;
```

`
SQL Error [XX000]: ERROR: failed to set single row mode for SELECT "time" FROM public.<table> WHERE _timescaledb_internal.chunks_in(public.<table>.*, ARRAY[47, 46, 45]) AND (("time" IS NOT NULL)) ORDER BY "time" ASC NULLS LAST
  Where: SQL statement "SELECT max("time"), min("time") FROM public.<table>"
`

**Comment by pmwkaa** [comment]
So the original issue is related to using the distributed hypertable with continuous aggs, is that correct? Or those are separate issues

**Comment by rahulbsw** [comment]
Original issue simple aggregation in time attribute on distributed hybertable is failing 
```sql
select min(time ),max(time)
from <table>
```

Another issue found when I was trying to create continuous agg i.e.

```SQL
CREATE VIEW health_report(fifteen_min,dim1,  sum_m1,cnt )
WITH (timescaledb.continuous,
    timescaledb.create_group_indexes=true
    timescaledb.refresh_lag = '-15m',
    timescaledb.refresh_interval = '5m')
AS
  SELECT time_bucket('15 minutes', time)  AS fifteen_min,
        dim1,
	sum(measure1) as sum_m1,
	count(measure1) as cnt
	from <table> wq 
	group by fifteen_min,dim1;

REFRESH MATERIALIZED VIEW health_report;
```

**Comment by akuzm** [comment]
Seems to be working correctly now, at least in the simplest case:
```
test=# select extversion from pg_extension where extname = 'timescaledb';
 extversion 
────────────
 2.5.0-dev
 
test=# create table two_aggs(ts timestamp, value float);
test=# select create_distributed_hypertable('two_aggs', 'ts');
test=# select * from timescaledb_information.hypertables where hypertable_name = 'two_aggs';
 hypertable_schema │ hypertable_name │ owner │ num_dimensions │ num_chunks │ compression_enabled │ is_distributed │ replication_factor │  data_nodes   │ tablespaces 
───────────────────┼─────────────────┼───────┼────────────────┼────────────┼─────────────────────┼────────────────┼────────────────────┼───────────────┼─────────────
 public            │ two_aggs        │ akuzm │              1 │          1 │ f                   │ t              │                  1 │ {data1,data2} │ 
(1 row)

test=# insert into two_aggs select now() + interval '1 second' * x, x from generate_series(1, 100) x;
test=# select min(ts), max(ts) from two_aggs;
            min             │            max             
────────────────────────────┼────────────────────────────
 2021-09-23 14:09:34.893538 │ 2021-09-23 14:11:13.893538
```

**Comment by NunoFilipeSantos** [comment]
Hi @rahulbsw! can you please try our latest TimescaleDB 2.5.0 and get back to us?

**Comment by NunoFilipeSantos** [comment]
Hi @rahulbsw ! 👋 If you can reproduce this on the latest TimescaleDB version, please feel free to reopen the issue.
