### ISSUE TITLE
Debian package repo: Binary packages have unnecessary dependency

### ISSUE THREAD

**Issue by blackbit42** [timescale/timescaledb#1731]
The [binary timescale packages for debian](https://packagecloud.io/timescale/timescaledb/debian/) have a dependency on postgresql-server-dev-11 even though there is no apparent reason for that.
I tried, the packages (both -oss and 'community') work just fine without postgresql-server-dev-11 installed.
I suspect that a build dependency was copied erroneously.

**Comment by RobAtticus** [comment]
I believe you are correct and I'll make sure this is corrected for future releases.

**Comment by svenklemm** [comment]
Closing since this is fixed in 1.7+
