### ISSUE TITLE
Debian package repo: TSL licensed packages should be in 'non-free', not in 'main'

### ISSUE THREAD

**Issue by blackbit42** [timescale/timescaledb#1732]
There are two sorts of packages of timescale provided for Debian systems. A 'community' version under [Timescale License](https://www.timescale.com/legal/licenses) and an 'open source' version under Apache 2.0 License.
Both packages are in the 'main' sub repository of [the Debian package repository](https://packagecloud.io/timescale/timescaledb/debian/) even though Timescale License doesn't comply with the [Debian Free Software Guidelines](https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines). The TSL packages should go into 'non-free' instead of 'main'.

**Comment by blackbit42** [comment]
Any update on this?

**Comment by svenklemm** [comment]
Closting this since I dont think DFSG rules apply to non-debian repositories.

**Comment by blackbit42** [comment]
Multiple debian package repository names exist to make it easy for users to understand what free software properties a package has, just from looking at the repository name.
When you say
> Closting this since I dont think DFSG rules apply to non-debian repositories.

what you really means is
> I can't be forced to do the right thing, so I won't. Having the package in 'main' looks better, I don't want to make it transparent that this is non-free software".

I am not impressed by this move.
