### ISSUE TITLE
Installer link 404

### ISSUE THREAD

**Issue by juanredondo** [timescale/timescaledb#1736]
I'm sorry if  it isn't the right place to report you this....

The link of windows comunity installer is broken:

[(https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-11_1.7.0-windows-amd64.zip)]

**Comment by mfreed** [comment]
Thanks for report @juanredondo .  This is a docs bug that has since be fixed, but waiting for docs-redployment:

https://github.com/timescale/docs.timescale.com-content/issues/332
