### ISSUE TITLE
Hypertable table storage parameters not applied to chunks

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#174]
Storage parameters that are set on a hypertable (https://www.postgresql.org/docs/9.6/static/sql-createtable.html#SQL-CREATETABLE-STORAGE-PARAMETERS) should be "inherited" by chunks. Currently they are not. Examples of such settings are autovacuum_vacuum_scale_factor, autovacuum_vacuum_threshold

**Comment by mfreed** [comment]
Released in version 0.9.
