### ISSUE TITLE
[Enhancement] Add Hypertable Name to show_chunks output

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#1742]
It would be useful to see the associated hypertable for the chunks in show_chunks(), especially when no hypertable is given.

Similarly, exposing the chunk name prefix in the timescaledb_information.hypertable would also be useful, to be able to quickly identify the hypertable a given chunk relates to.

**Comment by erimatnor** [comment]
TimescaleDB will have a `chunks` view that will show the hypertable name the chunk belongs to.
