### ISSUE TITLE
surprising set_chunk_time_interval behavior

### ISSUE THREAD

**Issue by patleb** [timescale/timescaledb#1752]
When `set_chunk_time_interval` is used to change the next chunk size, the actual range doesn't match what was set.

For example, we partitioned on a `BIGINT` column with an initial `time_interval` of 781 which gives a chunk range of `[0,781)`. Then, we filled the partition from 1 to 780 and used `set_chunk_time_interval` to set the next chunk value and we see the following behavior for different values of time_interval after filling the next chunk with another batch of 780:

```
783 --> [781,783)  --> size of 2, [783,1566) --> size of 783
782 --> [781,782)  --> size of 1, [782,1564) --> size of 782
781 --> [781,1562) --> size of 781
780 --> [781,1560) --> size of 779
779 --> [781,1558) --> size of 777
778 --> [781,1556) --> size of 775
777 --> [781,1554) --> size of 773
```

**Comment by davidkohn88** [comment]
This is expected behavior, the chunk following the change can be a bit smaller it's due to the way we align chunk ranges. The one after that one should be the expected size.

**Comment by patleb** [comment]
We have a very different definition of expected behavior. I'm in the process of implementing adaptive chunking size and the function wasn't described as having this undocumented behavior... so, naturally, I've written the functionality expecting the next chunk to have the size that I've set it to... which seemed like a reasonable assumption.

Is this behavior subject to be the official one or is the documented behavior supposed to be the one implemented (or will be implemented)? I'm asking because I have to take both behaviors into consideration if it's expected to change.

**Comment by davidkohn88** [comment]
I'll reopen this and let someone else respond, but I think this is the only behavior we have ever done, in general we cannot guarantee that the size of a chunk won't be smaller. For instance, we align chunks along space partitions, so if a space partition was created when it was 781, and then you change it, and another space partition is created in the same range as the old one, it will align with the boundaries of the old space partition. So in general we guarantee the chunk will be no larger than the size you set, but in some cases it can be smaller.

**Comment by patleb** [comment]
Thanks for the answer, this is exactly what I needed to know!
