### ISSUE TITLE
high cardinality and slow freq scenarios

### ISSUE THREAD

**Issue by zplzpl** [timescale/timescaledb#1754]
I want to try to use timescaledb to track business data.

My company operates an e-commerce platform with tens of millions of products;

Approximate data volume: 15Mil -20Mil item

Each product item has about: 15 metric

The frequency of crawling metrics is once a day

This means that every day:

15Mil * 15 ~ 20Mil * 15 metrics

Want to retain 365 days of data

Is timescaledb suitable for this scenario?

In this scenario, are there any suggestions for the machine configuration and timescaledb  configuration to use?

**Comment by mfreed** [comment]
20M items * 15 =  300,000,000 per day, or around 3500 per second in steady state.  With a year, that's roughly 110B metrics.  These numbers are certainly reasonable to store in TimescaleDB, especially when combined with our native compression techniques to reduce the storage overhead.

As to machine config:  Your insert is pretty modest, so the size of the server will depend more on the query load on the machine.  I would test storage capacity by at least loading up a week of data, turning on compression, and seeing the consumption.

Getting started

- https://docs.timescale.com/latest/getting-started/setup
- https://docs.timescale.com/latest/getting-started/exploring-cloud

Compression:
- https://docs.timescale.com/latest/using-timescaledb/compression

**Comment by zplzpl** [comment]
How choose the right columns for segmentby option?

high cardinality and slow freq scenarios.

segmentby item id,may not bring high compression.

**Comment by mfreed** [comment]
Do you typically also query by item_id?  Could you tell me more about your query patterns?

And by 15 metrics, I assume these are 15 different metrics?  So you only get one reading per metric per day?

Also curious -- do you bulk load at end of day or regular intervals, or is it continuous throughout the day?

**Comment by zplzpl** [comment]
**Do you typically also query by item_id?** 

YES 

**Could you tell me more about your query patterns?**

```
SELECT * FROM item_snapshot WHERE snapshot_time > EXTRACT(epoch FROM NOW() - interval '30 day');
```

**And by 15 metrics, I assume these are 15 different metrics?** 

YES，15 different metrics

**So you only get one reading per metric per day?**

Yes, because higher frequencies mean more costs.

 **do you bulk load at end of day or regular intervals, or is it continuous throughout the day?**

end of day.
But we will record it in the file first, and then import the file into tsdb.therefore, tsdb write speed does not need to be very high.
