### ISSUE TITLE
Changing and fine tuning chunk_time_interval

### ISSUE THREAD

**Issue by nmiculinic** [timescale/timescaledb#177]
What are the guidelines for chunk_time_interval? And can I change it on the database?

As most users, I'm mostly interested in the recent data, and I've put the chunk_time_interval to 1 day since I mostly use the last day data. However, I'm having some performance bottleneck and am debugging whether this could be the cause.

Also, I'm quite a beginner in database world, thus I'm unsure what buttons I need to tune and check

**Comment by mfreed** [comment]
Hi @nmiculinic:  A number of those questions and  "best practices" are discussed in more depth in our docs:

http://docs.timescale.com/api/api-timescaledb#create_hypertable-best-practices

And to your immediate question:  Yes, you can change the default chunk interval either at initial hypertable creation (`create_hypertable('tablename', 'time_column_name', chunk_time_interval => <VALUE IN MICROSECONDS>`) and change the interval while running for future intervals (`set_chunk_time_interval()`).  The docs go into more details.

Regarding performance debugging, happy to help.  Might be easier to do this over our [Slack group](https://slack-login.timescale.com/), though, so we can look at your setup together.

**Comment by nmiculinic** [comment]
Thank you for the information. I forgot to create an index on time column, and that's why I was suffering performance drops. It's all right for now at least.
