### ISSUE TITLE
Continuous Aggs last_run_success Shows False

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#1781]
**Relevant system information:**
 - OS: Centos 8
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: yum install

**Describe the bug**
In the continuous aggs stats views, the `last_run_success` field consistently shows "false" despite obvious successful runs, and no increase in failed run counts.

**To Reproduce**
1. Create a continuous agg
2. View the stats for that agg in the timescaledb_information catalogues
3. See the `last_run_success` column shows FALSE

**Expected behavior**
I would expect this to show TRUE unless the last run actually failed

**Actual behavior**
This shows FALSE even when the last run was successful.
**Screenshots**
<img width="704" alt="Screen Shot 2020-03-27 at 10 40 01 AM" src="https://user-images.githubusercontent.com/1923424/77776707-6ee33280-701c-11ea-8ee5-91ea84ab84a9.png">

**Additional context**
This appears to just be cosmetic, but the information is confusing, since all signs point to the cagg working as expected, except this columns.

**Comment by gayyappan** [comment]
@tylerfontaine Could you confirm that this happens only when you have a bgw job running for the cont. aggregate? i.e. last_run_success is false when the job_status is Running.

**Comment by tylerfontaine** [comment]
I dropped and re-added the job, because eventually these turned into TRUE, actually. But yes, the job status is running and showing last_run_success as FALSE

<img width="1260" alt="Screen Shot 2020-03-27 at 3 32 55 PM" src="https://user-images.githubusercontent.com/1923424/77798156-57b63c00-7040-11ea-8221-6525d94b71c9.png">

**Comment by RobinDeBaets** [comment]
I also have the same behaviour. This seems to happen when a continous aggregate can't process the updates on the hypertable within a single job (due to the `max_interval_per_job`) and needs to run multiple of them (consecutively).  
It does not seem to have any impact on the actual consistency of the data.
