### ISSUE TITLE
Augment query from cont agg with data from original table for accurate result over any time range

### ISSUE THREAD

**Issue by kdorsel** [timescale/timescaledb#1798]
- PostgreSQL version: 11.6
 - TimescaleDB version: 1.6.1

**Feature Request**
An automatic way of querying from an aggregate view and then augmenting the missing data from the original table to give a correct representation of the data given a specific time frame.

**Background**
I want an exact count of the number of events between two timestamps.
```
create tbl (ts timestamptz, evt text);
select count(*) from tbl where evt = 'myevent' and ts between startTs and endTs;
```

I want to use the aggregate functionality for performance and I create a continuous aggregate.

```
CREATE VIEW tbl_hourly
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 hour', ts) as bucket,
  evt,
  count(evt) as cnt
FROM tbl
GROUP BY bucket, evt;
```

Now querying directly from the view will (unless the timestamps line up perfectly) give erroneous results.

```
select sum(cnt)
from tbl_hourly
where evt = 'myevent' and ts between startTs and endTs;
```

For performance I would like to get the majority of the result from the aggregate view and add to it any missing information from either end from the original table.

```
with tf as (
	-- Input timeframe
	select '2020-02-03 02:01:00-05'::timestamptz as start, '2020-03-04 02:00:00-05'::timestamptz as stop
), src as (
	select min(bucket) as min, max(bucket) as max, sum(cnt) as cnt
	from tbl_hourly
        -- Trunc end ts to hour since our buckets are hourly
        -- and up to and NOT including that hour since only need a portion of it
	where evt = 'myevent' and
                    bucket >= (select start from tf) and
                    bucket < (select date_trunc('hour', stop) from tf)
)
-- Merging aggregate and original table
select count(evt) + (select cnt from src)
from tbl
where evt = 'myevent' and (
              ts >= (select start from tf) and ts < (select min from src) or
              ts > (select max + interval '1 hour' from src) and ts <= (select stop from tf)
            )
union
-- Comparing to original table only, will return one row if results are the same
select count(evt)
from tbl
where evt = 'myevent' and ts between (select start from tf) and (select stop from tf);
```

Is there a more refined way of doing this currently? Is there a way to add this functionality directly into timescale as a generalized function that is automatically created when the continuous aggregate is created?

**Comment by svenklemm** [comment]
This will be added in 1.7, see #1685

**Comment by kdorsel** [comment]
Although similar, from what I've read about real-time aggregates it is just a subset of what I'm describing here, but please correct me if I misunderstood.  Real-time aggregates are a great new feature, but I think they could become even more powerful.

Real-time aggregates only augment data from the last aggregated entry to the current time. For example given an aggregate table with hourly buckets, the new functionality would make this work:

```
select sum(cnt)
from tbl_hourly
where bucket >= date_trunc('hour', now() - interval '5 hour')
```

Although still give erroneous results given this second example. Since the lower bound does not fall exactly on an hourly bucket, the data from the lower bound to the next closest bucket is lost. The buckets are not pro-rated when the bounds fall in between them.

```
select sum(cnt)
from tbl_hourly
where bucket >= date_trunc('hour', now() - interval '5 hour 5 minute')
```
What this new functionality does is augment the aggregate only when the upper bound is between the end of the last (most recent) bucket and the future, but does not help if the any of the bounds fall in between buckets in the past.

Hopefully that explanation makes some sense. Here's an example that you can run to illustrate.

Given this initial setup.
```
create table tbl (ts timestamptz not null, evt text);
select create_hypertable('tbl', 'ts');

insert into tbl
select s.ts, 'x'
from generate_series('2020-04-04 08:00'::timestamptz, '2020-04-04 11:59:59'::timestamptz, '1 second') as s(ts);

CREATE VIEW tbl_hourly
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 hour', ts) as bucket,
  evt,
  count(evt) as cnt
FROM tbl
GROUP BY bucket, evt;
```

When the ts bounds play nice with the bucket size you get correct results.
```
select 'from tbl_hourly', sum(cnt) from tbl_hourly
where bucket between '2020-04-04 08:00:00' and '2020-04-04 10:59:59'
union
select 'from tbl', count(evt)
from tbl
where ts between '2020-04-04 08:00:00' and '2020-04-04 10:59:59';
```

> "from tbl"	10800
> "from tbl_hourly"	10800

When the ts bounds fall in between the hourly buckets the results become incorrect.
```
select 'from tbl_hourly', sum(cnt) from tbl_hourly
where bucket between '2020-04-04 08:30:00' and '2020-04-04 10:15:00'
union
select 'from tbl', count(evt)
from tbl
where ts between '2020-04-04 08:30:00' and '2020-04-04 10:15:00';
```

> "from tbl"	6301
> "from tbl_hourly"	7200


I solve this with a fully augmented aggregate/original query that works on any bounds.

```
with tf as (
	select '2020-04-04 08:30:00'::timestamptz as start, '2020-04-04 10:15:00'::timestamptz as stop
), src as (
	select min(bucket) as min, max(bucket) as max, sum(cnt) as cnt
	from tbl_hourly
	where evt = 'x' and
                    bucket >= (select start from tf) and
                    bucket < (select date_trunc('hour', stop) from tf)
)
select 'from tbl_hourly_augmented', count(evt) + (select cnt from src)
from tbl
where evt = 'x' and (
              ts >= (select start from tf) and ts < (select min from src) or
              ts >= (select coalesce(max + interval '1 hour', (select start from tf)) from src) and ts <= (select stop from tf)
            )
union
select 'from tbl', count(evt)
from tbl
where evt = 'x' and ts between (select start from tf) and (select stop from tf)
union
select 'from tbl_hourly', sum(cnt) from tbl_hourly
where evt = 'x' and bucket between (select start from tf) and (select stop from tf);
```

> "from tbl_hourly_augmented"	6301
> "from tbl_hourly"	7200
> "from tbl"	6301

** This augmented query is slightly different than the one in the original post as this one supports selecting time range smaller than the bucket size with the added coalesce.
