### ISSUE TITLE
Update num_slices in dimension table for open (time) dimensions

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#180]
Currently, the `num_slices` column in the `dimension` table is used for space dimensions to know the number of partitions to create. For time-like dimensions, the column is always NULL. 

For consistency, `num_slices` should reflect the number of slices created also in time-like dimensions. Thus, every time we create a new slice in a particular time-like dimension, we should also update  `num_slices`.

**Comment by dianasaur323** [comment]
@erimatnor Same question here - is this still relevant? Hard for me to tell given all the work that has happened since last year.

**Comment by svenklemm** [comment]
I dont think this relevant anymore also this would require a stronger lock on chunk creation on the dimension table which we probably want to avoid.
