### ISSUE TITLE
Downgrade timescale extension version

### ISSUE THREAD

**Issue by sshamsudheen** [timescale/timescaledb#1800]
**Relevant system information:**
 - OS: Linux ip-10-79-3-178 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - PostgreSQL version (output of `postgres --version`): psql (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 1.6.1   | public     | Enables scalable inserts and complex queries for time-series data
 - Installation method:apt-install

**Describe the bug**
Timescale db extension version 1.6.1 is running in my database, how can i downgrade that to a lower extenstion example to 1.5.1

**Comment by svenklemm** [comment]
Unfortunately you cannot downgrade the extension to a previous version.

**Comment by sshamsudheen** [comment]
I am able to downgrade it by the below step, let me know if this is not the correct way

1) verify the timescale extension 1.5.1 is available in your db instance
```
 ls /usr/share/postgresql/11/extension/
-rw-r--r-- 1 root root  97826 Mar 18 15:45 timescaledb--1.4.0--1.6.1.sql
-rw-r--r-- 1 root root  91075 Mar 18 15:45 timescaledb--1.4.0.sql
-rw-r--r-- 1 root root  97826 Mar 18 15:45 timescaledb--1.4.1--1.6.1.sql
-rw-r--r-- 1 root root  91079 Mar 18 15:45 timescaledb--1.4.1.sql
-rw-r--r-- 1 root root  97826 Mar 18 15:45 timescaledb--1.4.2--1.6.1.sql
-rw-r--r-- 1 root root  91079 Mar 18 15:45 timescaledb--1.4.2.sql
-rw-r--r-- 1 root root  87160 Mar 18 15:45 timescaledb--1.5.0--1.6.1.sql
-rw-r--r-- 1 root root 105413 Mar 18 15:45 timescaledb--1.5.0.sql
-rw-r--r-- 1 root root  86581 Mar 18 15:45 timescaledb--1.5.1--1.6.1.sql
-rw-r--r-- 1 root root 107969 Mar 18 15:45 timescaledb--1.5.1.sql
-rw-r--r-- 1 root root  81283 Mar 18 15:45 timescaledb--1.6.0--1.6.1.sql
-rw-r--r-- 1 root root 108644 Mar 18 15:45 timescaledb--1.6.0.sql
-rw-r--r-- 1 root root 108690 Mar 18 15:45 timescaledb--1.6.1.sql
-rw-r--r-- 1 root root    365 Apr  6 10:51 timescaledb.control
```


2) execute the create extension command with the necessary version

`create extension timescaledb version '1.5.1';
`
verify the available version and installed version
```
testsam=# select * from pg_available_extensions where name='timescaledb';
    name     | default_version | installed_version |                              comment
-------------+-----------------+-------------------+-------------------------------------------------------------------
 timescaledb | 1.6.1           | 1.5.1             | Enables scalable inserts and complex queries for time-series data
(1 row)
```

now i am able to downgrade the version.

**Comment by mfreed** [comment]
As of 2.3.1, TimescaleDB supports version downgrades.

https://docs.timescale.com/timescaledb/latest/overview/release-notes/#v2-3-1-2021-07-05
