### ISSUE TITLE
Using timescaledb with flask sqlalchemy

### ISSUE THREAD

**Issue by kashyapm94** [timescale/timescaledb#1817]
Hey,

I have created a db using flask sqlalchemy and I am trying to convert the existing tables to hypertables by using flask sqlalchemy. 

I found [https://stackoverflow.com/questions/50862609/creating-hypertables-through-sql-alchemy](url) on SO, where it says: 

> We currently do not offer any specific integrations with SQL Alchemy (broadly or specifically for creating hypertables)

I would like to know if any updates have been made on that front.

Thanks

**Comment by mfreed** [comment]
We have not released any specific tooling around SQL Alchemy, but certainly come across many users who use it with TimescaleDB. Are you running into any problems?
