### ISSUE TITLE
time_bucket_gapfill not taking start / end from where always

### ISSUE THREAD

**Issue by martinhanes** [timescale/timescaledb#1818]
**Relevant system information:**
 - OS: Debian
 - PostgreSQL version 9.6.17
 - TimescaleDB version 1.4.2
 - Installation method: apt

**Describe the bug**
When time_bucket_gapfill is used on statement which uses both:
- where clause
- group by clause

and **where condition is resolved statically as false**, then it produces error:
`ERROR: invalid time_bucket_gapfill argument: could not infer start boundary from WHERE clause`

**To Reproduce**
```
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z'
and false
group by 1;
```

**Expected behavior**
Empty resultset.

**Actual behavior**
Error.

**Additional context**
Note, the "false" condition in examples is simplified, in fact it is something like '1m' < '1h'::interval.

The need for such condition is to use in grafana - where I need to union two sets, which are disjunctive. For example (select .... where '1m' < '1h'::interval) union (select .... where '1m' >= '1h'::interval). And the variable on the left side of this condition is passed through UI. The where clause - both the condition and timestamps is provided by UI and there's no way I can obtain start and end variables as a macro, only the whole "between" macro.

- If selected without group by, and with false condition, it returns empty set as expected.
- if selected with group by and with false condition, which must be 'computed', it returns empty set as expected
- other trivial examples returned OK results
- only the last query returns error

```
--OK
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z';

--OK
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z'
group by 1;

--OK (empty result set)
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z'
and false;

--OK (empty result set)
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z'
and timestamp > '2050-01-01' --is false for some time, but can't be resolved statically
group by 1;

--ERROR: invalid time_bucket_gapfill argument: could not infer start boundary from WHERE clause
SELECT time_bucket_gapfill('10 min', "timestamp") as "time"
FROM sensor_data WHERE timestamp BETWEEN '2020-04-14T11:07:20.68Z' AND '2020-04-15T11:07:20.68Z'
and false
group by 1;
```

**Comment by svenklemm** [comment]
Ok this is a quite complex issue due to the order of operation certain query parts are executed. 
Expression AND false gets simplified to false by postgres and the gapfill code looks at the simplified version. Even if it wouldn't work at the simplified expression it would not produce the desired result because the WHERE clause gets executed before gapfill so if you filter everything in WHERE clause gapfill would insert tuples for the time range. To get the result you want you need to have the expression above gapfill. The following query would achieve the result you are looking for:
```
SELECT * FROM (select time_bucket_gapfill('1d',time) FROM metrics WHERE time > '2000-01-01' AND time < '2000-01-03' GROUP BY 1) gf1 WHERE false UNION ALL SELECT * FROM (select time_bucket_gapfill('1d',time) FROM metrics WHERE time > '2000-01-01' AND time < '2000-01-03' GROUP BY 1) gf2 WHERE true;
```

**Comment by martinhanes** [comment]
Hello @svenklemm, thanks for your detailed explanation. Albeit I knew postgres simplified expression with "and false", I wasn't aware that:
> Even if it wouldn't look at the simplified expression it would not produce the desired result because the WHERE clause gets executed before gapfill so if you filter everything in WHERE clause gapfill would insert tuples for the time range.
Thanks for sharing the detail with me! :-)

Also, the workaround works and I'm happy to report that it works in my scenario. I'd love Grafana to support looking at multiple aggregates (or raw table), out of the box, maybe they plan it in the future, however, until then, I have a working code, thanks one last time!

Martin
