### ISSUE TITLE
Make full use of multiple disks

### ISSUE THREAD

**Issue by AlanduzzZ** [timescale/timescaledb#1819]
PG & TimescaleDB info：

- PG version：11.7

- TimescaleDB version：1.6.1

- CentOS 7 Kernel：4.18.5-1.el7.elrepo.x86_64 #1 SMP Fri Aug 24 11:35:05 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

- CPU：16 Core

- Mem：32 GB

- Data Disk：1TB HDD *2（/dev/vdb，/dev/vdc）

- 5000 rows per second insertion speed

- 4KB per piece of data

I created two data disks as two table spaces and attached them to the same hypertable table, Then set the "time" column to time_column_name, and chunk_time_interval to 1 hour, finally add a "text" format column as an additional hash partitioning.

But I found that the utilization rate of the two disks is different by half.

What steps should I pay attention to? Is this phenomenon normal? 
Please help me, thanks!

The following figure is the disk read and write speed per second：

![image](https://user-images.githubusercontent.com/10544715/79342200-6cab2e80-7f5f-11ea-8f03-020a47a67bb1.png)

**Comment by NunoFilipeSantos** [comment]
Hi @AlanduzzZ! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it. 👍
