### ISSUE TITLE
Same query returns different records in Psql and Grafana Adapter

### ISSUE THREAD

**Issue by zevarito** [timescale/timescaledb#1821]
**Disclaimer**: Couldn't find a place to report bugs of Grafana/Postgres adapter, it might be actually related to it, please let me know where I can post issues for the adapter only to not spam this project, sorry about it and thanks.

**Relevant system information:**
 - OS: Ubuntu and OSX
 - PostgreSQL 11.7
 - TimescaleDB 1.6.1
 - Docker and also homebrew

**Describe the bug**
I was looking at some weird metrics in a Grafana dashboard, so I've write a very simple query to compare results between `psql` and Grafana/Postgres adapter and find out that they are not the same, `psql` return one more day.

**To Reproduce**

Giving this simple query:
```
select time,region from csse_coronavirus_metrics order by time desc limit 5;
```

Here is the result from `psql`:
```
        time         |       region       
---------------------+--------------------
 2020-04-14 00:00:00 | Zimbabwe
 2020-04-14 00:00:00 | Zambia
 2020-04-14 00:00:00 | Yemen
 2020-04-14 00:00:00 | Western Sahara
 2020-04-14 00:00:00 | West Bank and Gaza
(5 rows)
```
And here is the result in Grafana/Postgres explore for the same query:

```
2020-04-13 21:00:00 | Zimbabwe
2020-04-13 21:00:00 | Zambia
2020-04-13 21:00:00 | Yemen
2020-04-13 21:00:00 | Western Sahara
2020-04-13 21:00:00 | West Bank and Gaza
```

**Expected behavior**
Since I am querying through Grafana/Explore as a table and without time window macros results should be the same.

**Actual behavior**
`psql` return last day entry while Grafana/Postgres don't, or reconvert the column value to a past day?

**Screenshots**
Here is a [Coronavirus Worldwide Dashboard](https://masdatos.org/d/pzBeqsCZk/coronavirus-en-el-mundo?orgId=1&refresh=2h) and here is a link to the [Explore Playground](https://masdatos.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22PostgreSQL%22,%7B%22datasource%22:%22PostgreSQL%22,%22format%22:%22table%22,%22timeColumn%22:%22confirmed_count%22,%22metricColumn%22:%22none%22,%22group%22:%5B%5D,%22where%22:%5B%7B%22type%22:%22macro%22,%22name%22:%22$__unixEpochFilter%22,%22params%22:%5B%5D%7D%5D,%22select%22:%5B%5B%7B%22type%22:%22column%22,%22params%22:%5B%22confirmed_count%22%5D%7D%5D%5D,%22rawQuery%22:true,%22rawSql%22:%22select%20time,region%20from%20csse_coronavirus_metrics%20order%20by%20time%20desc%20limit%205;%22,%22table%22:%22csse_coronavirus_metrics%22,%22timeColumnType%22:%22int8%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

**Comment by feikesteenbergen** [comment]
Must be a timezone difference between the `psql` client and the Grafana.
The times all differ by 4 hours, and the records seem to be the same, except for the time.

Could you do the following on both:

```sql
SELECT current_setting('timezone');
```

Note: As you have not specified any other `ORDER BY` clause, your result set is not deterministic, if you want it to be you should add another column there, for example:

```sql
select time,region from csse_coronavirus_metrics order by time desc, region limit 5;
```

**Comment by zevarito** [comment]
@feikesteenbergen dumb of me, of-course it is the difference between UTC and my timezone that was set on the dashboard. Totally agree about the deterministic query. Thanks!
