### ISSUE TITLE
when change search_path to custom, timescaledb extension not working as expected

### ISSUE THREAD

**Issue by ZabdiAG** [timescale/timescaledb#1822]
**Relevant system information:**  
 - OS: macOS 10.15.3 (19D76) Kernel Darwin 19.3.0
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: using Docker

**Describe the bug**  
timescaledb functions are not recognizable when installed on custom schema and search_path set to custom schema

**To Reproduce**  
1. Run timescaledb as container and run psql command inside container:
```bash
$ docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg11
$ docker exec -it timescaledb psql -U postgres
```

2. Prepare database
```bash
postgres=# create database timescaledb;
postgres=# \c timescaledb;
timescaledb=# create schema custom;
timescaledb=# set search_path to custom;
timescaledb=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
timescaledb=# create table series(id text, record timestamp);
```
3. Run timescaledb function:
```bash
timescaledb=# select create_hypertable('series', 'record');
```
Error output on step 3:
```bash
ERROR:  function create_hypertable(unknown, unknown) does not exist
LINE 1: select create_hypertable('series', 'record');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

However, if we set search_path to public, custom, step three works
```bash
timescaledb=# set search_path to public, custom;
SET
timescaledb=# select create_hypertable('series', 'record');
NOTICE:  adding not-null constraint to column "record"
DETAIL:  Time dimensions cannot have NULL values
  create_hypertable
---------------------
 (1,custom,series,t)
(1 row)

```

**Comment by davidkohn88** [comment]
Yes, this behavior is expected. This is because the extensions functions are created in the public schema by default, if you would like to run them without public being in your search path you can call them by their schema qualified names, ie public.create_hypertable. You can also create the extension in a different schema.

**Comment by davidkohn88** [comment]
Please feel free to reopen if you have further questions there.

**Comment by ZabdiAG** [comment]
Hi David, thank you for your answer,

From my example, it already has installed Timescaledb extension on timescaledb database inside public schema as you mentioned. I Tried to change to custom schema using alter sql statement but there is an issue related [here](https://github.com/timescale/timescaledb/issues/276)

So, my best approach was to:
1. Delete extension on new database
```bash
timescaledb=# drop extension timescaledb;
```
2. Reinstall with schema defined
```bash
timescaledb=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE schema custom;
```

Now it works as expected when I change search_path to custom

Thank you!
