### ISSUE TITLE
Upgrade from PG 11 to PG 12 (pg_dump/pg_restore)

### ISSUE THREAD

**Issue by swiffer** [timescale/timescaledb#1833]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - Docker (latest-pg11 / latest-pg12)
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: using Docker

**Describe the bug**
I dumped a database via pg_dump and tried to restore on a new container with pg12 via pg_restore.
The process went fine, as written in the docs i've executed these commands:

```sql
SELECT timescaledb_pre_restore();

-- execute the restore (or from a shell)
\! pg_restore -Fc -d tutorial tutorial.bak

SELECT timescaledb_post_restore();
```

All the data restored successfully and all the queries querying data of the hypertable still work but the table seems to no longer be a hypertable. there is no entry in timescaledb_information -> hypertable.

**Comment by mfreed** [comment]
Did you upgrade first on the local machine to pg12?  I.e., were you simultaneously upgrading TimescaleDB and PostgreSQL, or did you do them serially:

- On PG11, upgrade TimescaleDB 1.6 -> 1.7
- On Timescale 1.7, upgrade PG 11 -> 12

**Comment by swiffer** [comment]
No, Upgraded to 1.7.0 First

**Comment by swiffer** [comment]
I think we can close this one. Ive had `set session_replication_role to replica;` in the init commands still set from my intial data loading.

**Comment by marksugar** [comment]
hi, @swiffer 
I use `timescale/timescaledb: 1.6.0-pg11` image.
I want to update to `timescale/timescaledb:1.7.0-pg12`
You mentioned the way to backup and restore in the above. There are detailed steps
consult!
thanks
