### ISSUE TITLE
Backup/restore not working as per document

### ISSUE THREAD

**Issue by sshamsudheen** [timescale/timescaledb#1835]
**Relevant system information:**
 - OS:  Linux ip-10-79-3-192 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - PostgreSQL version (output of `postgres --version`): psql (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: apt install

I followed the link (https://docs.timescale.com/latest/using-timescaledb/backup) to recover the DB from backing up the timescaledb.

pg_dump gives me the below output

```
pg_dump: NOTICE: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: NOTICE: there are circular foreign-key constraints on this table:
pg_dump:   chunk
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
```

may i know why the below message occurs 

```
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
```

DO i need to copy all the hypertables again

**Comment by mfreed** [comment]
The warning about circular foreign-key constraints is know but doesn't cause an error/issue, we will try to fix the warning in the future.

Can you post the explicit command you are using with `pg_dump`?

**Comment by sshamsudheen** [comment]
`pg_dump -h localhost -U uberadmin -p 5434  -Fc -f db_name.bak db_name`

**Comment by balajir24** [comment]
> The warning about circular foreign-key constraints is know but doesn't cause an error/issue, we will try to fix the warning in the future.
> 
> Can you post the explicit command you are using with `pg_dump`?

@mfreed But we are unable to pg_dump complete db. It is missing hyper table data. 

DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.

**Comment by nshah14285** [comment]
Same error message.
The command I am trying is:
`/usr/bin/pg_dump --enable-row-security -U test -W -h 127.0.0.1 -d test > test.sql`

**Comment by svenklemm** [comment]
@sshamsudheen are you sure the data is not included that, those are just warning that you can ignore. The warning gets produced when trying to copy the parent hypertable which has no data in timescaledb but after pg_dump will dump the individual children as well.

**Comment by sshamsudheen** [comment]
Data is successfully dumped. also i can see the constraints, indexes are also copied successfully.

**Comment by nshah14285** [comment]
@sshamsudheen Any idea about the issue reported at [1927](https://github.com/timescale/timescaledb/issues/1927) it is related to timescaledb pg_dump.

Thanks in Advance.
