### ISSUE TITLE
missing old libs since 1.7

### ISSUE THREAD

**Issue by HeikoOnnebrink** [timescale/timescaledb#1836]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PG 12
 - TimescaleDB version 1.7.0
 - Installation method: docker

**Describe the bug**
Up to now the timescale installation included also libraries from previous versions
When I install timescaledb 1.7 on top of PostgreSQL 12 I get only these 1.7 objects:

> Apr 16 21:59 timescaledb-1.7.0.so
Apr 16 21:59 timescaledb-tsl-1.7.0.so
Apr 16 19:42 timescaledb.so

When I install the same timescaledb 1.7 on top of and lower PostgreSQL version I get also older objects
Here e.g. when installed on top of PostgreSQL 11

> Apr 16 19:47 timescaledb-1.3.0.so
Apr 16 19:47 timescaledb-1.3.1.so
Apr 16 19:47 timescaledb-1.3.2.so
Apr 16 19:47 timescaledb-1.4.0.so
Apr 16 19:47 timescaledb-1.4.1.so
Apr 16 19:47 timescaledb-1.4.2.so
Apr 16 19:47 timescaledb-1.5.0.so
Apr 16 19:47 timescaledb-1.5.1.so
Apr 16 19:47 timescaledb-1.6.0.so
Apr 16 19:47 timescaledb-1.6.1.so
Apr 16 19:47 timescaledb-1.7.0.so
Apr 16 19:47 timescaledb-tsl-1.3.0.so
Apr 16 19:47 timescaledb-tsl-1.3.1.so
Apr 16 19:47 timescaledb-tsl-1.3.2.so
Apr 16 19:47 timescaledb-tsl-1.4.0.so
Apr 16 19:47 timescaledb-tsl-1.4.1.so
Apr 16 19:47 timescaledb-tsl-1.4.2.so
Apr 16 19:47 timescaledb-tsl-1.5.0.so
Apr 16 19:47 timescaledb-tsl-1.5.1.so
Apr 16 19:47 timescaledb-tsl-1.6.0.so
Apr 16 19:47 timescaledb-tsl-1.6.1.so
Apr 16 19:47 timescaledb-tsl-1.7.0.so
Apr 16 19:42 timescaledb.so
Feb 20 10:47 timetravel.so

Is this expected behaviour and related to the desupport of older PostgreSQL versions up from PG12?

I ran into issues when using pgupgrade to upgrade an older PostgreSQL db that contains timescaledb 1.6.1 to PG12 that contains due to above restrictions only timescaledb 1.7.
As a conclusion I first had to upgrade the sourcedb to timescaledb 1.7 before I could use pgupgrade to upgrade to PostgreSQL 12.

By default we have timescaledb extension activated in all databases. If there is some DB that cannot upgrade now they will stay on some older PostgreSQL version and thats OK as long as it is supported by the PostgreSQL community. 

Will your desupport of older (but still supported PostgreSQL versions) break the pgupgrade path at some point in the future (e.g. upgrade from PostgreSQL 9.6 with timescaledb 1.6.1 to PostgreSQL 13 with timescaledb 2.0)?

We need to understand these dependencies to know if it is better to remove timescaledb as a default extension to avoid unnecessary upgrade conflicts.. 

Would be cool to clearly understand the implications of your desupport announcement coming with 1.7 (or later with 2.0)

**Comment by k-rus** [comment]
PG 12 is only supported from 1.7, thus there is no libs for older TimescaleDB version as they don't work with PG 12.
@HeikoOnnebrink does it answer your question?

**Comment by HeikoOnnebrink** [comment]
Thats ok... but will future releases of timescaledb, e.g. 2.0, come along with 1.7 libs for the time until PostgreSQL version < 12 will be out of cummunity support? 
In this way you would ensure that any PostgreSQL version that is within community support still can upgrade to latest timescaledb version using pg_upgrade.

As an example ... 
PostgreSQL 10 final release is scheduled November 10, 2020.
PostgreSQL 10 contains timescaledb 1.7 (and I assume that there will not be a higher release due to your dessuport announcement)
Will we be able to upgrade from that PG 10 database to latest timescaleDB end of 2020 using pg_upgrade or will it fail because in the target DB are no more timescaledb 1.7 libs ...?

**Comment by k-rus** [comment]
Good question. 
When new version of PG is supported, it will be always necessary to match TimescaleDB release to a one, which supports PG, before upgrading to new PG version. I.e., if you want to move from PG10 v. 1.6.0 to PG12, it is necessary fist to upgrade to 1.7.0 and then to PG12.

**Comment by HeikoOnnebrink** [comment]
than I hope that there will be in the future always suach a "pg_upgrade path" from any community supported PostgreSQL version to latest upstream version of timescaledb ;-)

**Comment by mfreed** [comment]
I think this has been answered, so closing out the issue.  Feel free to reopen if needed, I also added a docs issue so we can clarify there:

https://github.com/timescale/docs.timescale.com-content/issues/385
