### ISSUE TITLE
Union All is broken on 1.7.0

### ISSUE THREAD

**Issue by dhodyn** [timescale/timescaledb#1837]
**Relevant system information:**
 - OS: Fedora 31
 - PostgreSQL version (output of `postgres --version`): 11.7 / 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: using Docker

**Describe the bug**
**union all** between a regulartable and hypertable is not working. where as **union** seems to be working fine. 
This works:
1. pg 11.x + timescaledb 1.6.1 - OK
2. pg 11.x + timescaledb 1.7.0 - returns only one row from the regulartable
3. pg 12.x + timescaledb 1.7.0 - returns an exception

> unexpected field count in "D" message

**To Reproduce**
```
create table regulartable (time timestamptz, value numeric);
create table hypertable (time timestamptz, value numeric);
select create_hypertable('hypertable', 'time');
insert into hypertable values(now(), 1);
insert into regulartable values(now(), 2);

select time, value from regulartable 
union all
select time, value from hypertable ;
```

**Expected behavior**
A final table with two rows with both the rows present. 

**Actual behavior**
Depending upon the PG version, either an error or incomplete data

**Additional context**
union seems to be working fine

**Comment by mfreed** [comment]
We have confirmed the regression, @dhodyn.  Thanks for the report and simple script to reproduce!

**Comment by hedayat** [comment]
I still have this problem with timescaledb 1.7.1
