### ISSUE TITLE
Cannot read pg_class without having selected a database

### ISSUE THREAD

**Issue by Dmitri191** [timescale/timescaledb#1847]
**Relevant system information:**
 - OS: 4.14.35-1902.301.1.el7uek.x86_64
 - PostgreSQL version: 12.2
 - TimescaleDB version: 1.7.0
 - Installation method: yum install timescaledb-postgresql-12.x86_64

We are testing timescaledb on our installation zabbix v.4.4. After migration table to hypertable 
 "SELECT create_hypertable('history', 'clock', chunk_time_interval => 86400, migrate_data => true);" we have errors in postgresql log:

> 2020-04-23 13:14:39 +07 [7561]: [2-1] user=,db=,app=,client= FATAL:  cannot read pg_class without having selected a database
> 2020-04-23 13:14:39 +07 [7563]: [1-1] user=,db=,app=,client= LOG:  terminating TimescaleDB job scheduler due to administrator command
> 2020-04-23 13:14:39 +07 [7563]: [2-1] user=,db=,app=,client= FATAL:  terminating connection due to administrator command
> 2020-04-23 13:14:39 +07 [7562]: [1-1] user=,db=,app=,client= LOG:  terminating TimescaleDB job scheduler due to administrator command
> 2020-04-23 13:14:39 +07 [7423]: [1-1] user=,db=,app=,client= FATAL:  cannot read pg_class without having selected a database
> 2020-04-23 13:14:39 +07 [7562]: [2-1] user=,db=,app=,client= FATAL:  terminating connection due to administrator command
> 2020-04-23 13:14:39 +07 [27506]: [17-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 7423) exited with exit code 1
> 2020-04-23 13:14:39 +07 [27506]: [18-1] user=,db=,app=,client= LOG:  background worker "TimescaleDB Background Worker Launcher" (PID 7561) exited with exit code 1
> 2020-04-23 13:14:39 +07 [27506]: [19-1] user=,db=,app=,client= LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 7563) exited with exit code 1
> 2020-04-23 13:14:39 +07 [27506]: [20-1] user=,db=,app=,client= LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 7562) exited with exit code 1
> 2020-04-23 13:15:39 +07 [16959]: [1-1] user=,db=,app=,client= LOG:  TimescaleDB background worker launcher connected to shared catalogs

Can you say about this error? It is normal? PostreSQL instance didn't down, it continues work, but error is embarassing.

1. Making "SELECT create_hypertable('history', 'clock', chunk_time_interval => 86400, migrate_data => true);". Elapsed time is about 20-40 minutes.
2. After end this command on postgresql log we see fatal error.

**Comment by k-rus** [comment]
@Dmitri191 Thank you for reporting! Was the table migrated into hypertable correctly?
Do you run logical replication on the database?

**Comment by Dmitri191** [comment]
@k-rus Yes. Table migrated into hypertable is correct. No error in stdout after complete migration. For example, function drop_chunks() execute correct, space had freed. Select query on this table is correct. 
No, on this database we have not logical replication.

**Comment by gayyappan** [comment]
@Dmitri191 
1) Is this a fresh installation of PG12.2 and timescaledb and timescaledb 1.7?
what does \dx show?
2) If this is not a new installation, could you describe your upgrade path?
3) Need more context here about the background errors that are reported here.  Do you have any new bgw errors in the logs? Do you have any bgw jobs?
4) Could you post the output for ` ps -ef | grep postgres | grep -i timescaledb`

**Comment by Dmitri191** [comment]
1. PG was upgrade from 9.6 version to 12.2. Timescaledb was istall on PG 12.2 in first time.
>Name        | Version |   Schema   |                            Description                            
>--------------------+---------+------------+-----------------------------------------------------------
>pg_buffercache     | 1.3     | public     | examine the shared buffer cache
>pg_repack          | 1.4.5   | public     | Reorganize tables in PostgreSQL databases with minimal locks
>pg_stat_statements | 1.7     | public     | track execution statistics of all SQL statements executed
>pgstattuple        | 1.5     | public     | show tuple-level statistics
>plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
>timescaledb        | 1.7.0   | public     | Enables scalable inserts and complex queries for time-series data
>(6 rows)
2. Described in 1.
3. No, after migration to hypertable we had not errors related with "Timescaledb Background", yet.
4. Output
> -bash-4.2$ ps -ef | grep postgres | grep -i timescaledb
postgres 16959 27506  0 Apr23 ?        00:00:02 postgres: zabbixtest: TimescaleDB Background Worker Launcher   
postgres 16960 27506  0 Apr23 ?        00:00:12 postgres: zabbixtest: TimescaleDB Background Worker Scheduler   
postgres 16961 27506  0 Apr23 ?        00:00:12 postgres: zabbixtest: TimescaleDB Background Worker Scheduler

**Comment by gayyappan** [comment]
@Dmitri191 Thank you for the information.
