### ISSUE TITLE
PG12.2 and FATAL:  extension "timescaledb" must be preloaded

### ISSUE THREAD

**Issue by maksitop** [timescale/timescaledb#1849]
CentOS Linux release 7.6.1810 (Core) 
PostgreSQL version 12.2
timescaledb-postgresql-12-1.7.0-0.el7.x86_64
#grep shared_preload_libraries /var/lib/pgsql/12/data/postgresql.conf
shared_preload_libraries = 'pg_stat_statements, timescaledb'

 #psql -U postgres -d db
db=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /var/lib/pgsql/12/data/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
        echo "shared_preload_libraries = 'timescaledb'" >> /var/lib/pgsql/12/data/postgresql.conf

(Will require a database restart.)

How can I fix the download situation?

**Comment by jsgithubwork** [comment]
does it work if you flip the order of the libraries? E.g.
`shared_preload_libraries = 'timescaledb, pg_stat_statements'
`

**Comment by maksitop** [comment]
No, it does not work.
Does not work and shared_preload_libraries = 'timescaledb' 
:-(

**Comment by maksitop** [comment]
Problem resolved!! :-)

**Comment by franckvallee** [comment]
Indeed I had the same issue because I activated the load prewarm option.
In that case, the file postgresql.auto.conf overwrite postgresqL.conf and this is the one that must be modified, in my case:
shared_preload_libraries = 'pg_prewarm,timescaledb'
