### ISSUE TITLE
Can't install TimescaleDB following the documentation, DEBIAN

### ISSUE THREAD

**Issue by CLKBlu3** [timescale/timescaledb#1852]
As stated in title, it seems like I cannot get TimescaleDB to install in my debian machine, by following the steps in the documentation:

**Relevant system information:**
 - OS: [Ubuntu 18, Debian dist]
 - PostgreSQL version (output of `postgres --version`): [ 12.2]
 - TimescaleDB version (output of `\dx` in `psql`): Can't install ...
 - Installation method: 

As said, I did follow the docs in 
[doc for debian installation](https://docs.timescale.com/latest/getting-started/installation/debian/installation-apt-debian ):
```
# Add our repository
sudo sh -c "echo 'deb https://packagecloud.io/timescale/timescaledb/debian/ `lsb_release -c -s` main' > /etc/apt/sources.list.d/timescaledb.list"
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
sudo apt-get update
```

**Describe the bug**
At the moment I execute the update command, I get the following output, with an error stating that there is no Release file in the repo:
```
Ign:7 https://packagecloud.io/timescale/timescaledb/debian bionic InRelease                      
Err:8 https://packagecloud.io/timescale/timescaledb/debian bionic Release   
  404  Not Found [IP: 52.8.105.102 443]
Reading package lists... Done                   
E: The repository 'https://packagecloud.io/timescale/timescaledb/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Expected behavior**
Expected to be able to install :)

**Comment by ontologiae** [comment]
Hi,
I have the same problem.
I found a solutions whith this page : https://packagecloud.io/timescale/timescaledb/install

**Comment by svenklemm** [comment]
This should work. Seems like something went wrong for you since your URLs are a mixture of Debian/Ubuntu URLs. Feel free to reopen if the issue still persists.

**Comment by VitorSDDF** [comment]
Same problem on ubuntu 20.07

**Comment by svenklemm** [comment]
There is a button next to the command to switch between debian and ubuntu version did you click the version matching your distribution.

**Comment by Christopher-RZ** [comment]
For those wondering, this is the said button:
![image](https://user-images.githubusercontent.com/98054046/224235461-1aec3c70-7f82-4625-a4bf-500875f91f64.png)

**Comment by sk75** [comment]
I am getting the same error on Ubuntu 23. Yes I have used the ubuntu button to switch from debian. 
The error I am getting is:
E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release' does not have a Release file.
The command and full output is:
root@myvbox:/home/my# apt update
Hit:1 http://au.archive.ubuntu.com/ubuntu lunar InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu lunar-updates InRelease
Hit:3 http://au.archive.ubuntu.com/ubuntu lunar-backports InRelease
Hit:4 http://au.archive.ubuntu.com/ubuntu lunar-security InRelease
Ign:5 https://packagecloud.io/timescale/timescaledb/ubuntu lunar InRelease
Err:6 https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release   
  404  Not Found [IP: 54.219.131.151 443]
Hit:7 https://apt.postgresql.org/pub/repos/apt lunar-pgdg InRelease        
Reading package lists... Done                       
E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by beadon** [comment]
> I am getting the same error on Ubuntu 23. Yes I have used the ubuntu button to switch from debian. The error I am getting is: E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release' does not have a Release file. The command and full output is: root@myvbox:/home/my# apt update Hit:1 http://au.archive.ubuntu.com/ubuntu lunar InRelease Hit:2 http://au.archive.ubuntu.com/ubuntu lunar-updates InRelease Hit:3 http://au.archive.ubuntu.com/ubuntu lunar-backports InRelease Hit:4 http://au.archive.ubuntu.com/ubuntu lunar-security InRelease Ign:5 https://packagecloud.io/timescale/timescaledb/ubuntu lunar InRelease Err:6 https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release 404 Not Found [IP: 54.219.131.151 443] Hit:7 https://apt.postgresql.org/pub/repos/apt lunar-pgdg InRelease Reading package lists... Done **E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu lunar Release' does not have a Release file.** N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
> # cat /etc/apt/sources.list.d/timescaledb.list deb https://packagecloud.io/timescale/timescaledb/ubuntu/ lunar main

Seeing a similar issue here.  Same OS, lunar.  It is not available as a package yet.

To resolve this, and install a version supported on Ubuntu jammy, change the line with "lunar"  to "jammy".

`deb [signed-by=/etc/apt/keyrings/timescale_timescaledb-archive-keyring.gpg] https://packagecloud.io/timescale/timescaledb/ubuntu/ jammy main`

From there, sudo apt update

and then:
`sudo apt install timescaledb-2-postgresql-15`

Note this is one version ahead of the currently posted instructions (here : https://docs.timescale.com/self-hosted/latest/install/installation-linux/ )

**Comment by sheecegardezi** [comment]
Use an older version of ubuntu. I can confirm that build for jammy works for bookworm, but its better to just build from source:

```
echo "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ jammy main" | tee /etc/apt/sources.list.d/timescaledb.list 
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | apt-key add -
```

**Comment by RobbieMcKinstry** [comment]
@svenklemm could you please reopen this issue? As far as I can tell, the tutorial doesn't quite work as intended, or at least it's unclear enough to serve as a footgun for new Timescale users.

For example, I'm new to Timescale, and I'm trying to install it using the Postgres:17 Docker image. (I don't want to use the Timescale-official image because I want to install other extensions, like `pg-cron`).

Here's a self-contained Docker time to reproduce the issue:

```
FROM postgres:17

RUN \
    apt-get update && \
    apt-get install -yq \
      # install everything needed to build an extension
      postgresql-server-dev-17 \
      gnupg \
      apt-transport-https \
      lsb-release \
      wget \
      git \
      make \
      gcc \
      libpq-dev \
      postgresql-17-cron 
RUN \
    # These next few steps were taken from the Timescale installation page.
    # Add the Timescale apt source.
    https://github.com/timescale/timescaledb/issues/1852
    echo "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main" | tee /etc/apt/sources.list.d/timescaledb.list && \
    # Install the GPG key.
    wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg && \
    apt update && \
      apt install timescaledb-2-postgresql-17 postgresql-client-17 && \
    # Tune our Postgres install for Timescale.
    timescaledb-tune && \
    # Restart Postgres
    systemctl restart postgresql && \
    # All Done!
    echo 'DING!'
```

Build the docker image with:

```bash
$ docker build .
```

The Dockerfile breaks when adding the Timescale package. Ostensibly `$(lsb_release -c -s)` isn't outputting the right format for the URL.
