### ISSUE TITLE
[Multinode Beta] Select with LIMIT is very very slow

### ISSUE THREAD

**Issue by rahulbsw** [timescale/timescaledb#1853]
**Relevant system information:**
 - OS: Centos 7 64bit
 - PostgreSQL version (output of postgres --version): 11.6
 - TimescaleDB version (output of \dx in psql): 2.0.0 Beta 4
 - Installation method: "yum install"
 - No of data nodes : 10 
 - Machine : Bare Metail 384GB RAM , 28 CPU , 10 TB each Data node

**Describe the bug**
   Select * from <distributed_hybertable> Limit 10 very very slow

**Expected behavior**
 expect to be in <10 ms 

**Actual behavior**
 took more than 6 minutes

**Screenshots**
<img width="952" alt="image" src="https://user-images.githubusercontent.com/5987540/80245180-15702280-861f-11ea-88de-6ec41f280d13.png">

**Comment by pmwkaa** [comment]
Could you please provide an `EXPLAIN` output for this?

**Comment by rahulbsw** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/5987540/82427090-7aac0d80-9a3d-11ea-920c-3c5b07746992.png">

**Comment by akuzm** [comment]
Do we have a reproducer for this? In the simplest case of a distributed hypertable with two data nodes, the LIMIT seems to be correctly pushed down to the data nodes:
```
test=# explain analyze select * from t limit 1;
                                                                     QUERY PLAN                                                                      
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Limit  (cost=100.00..100.05 rows=1 width=72) (actual time=10.426..10.429 rows=1 loops=1)
   ->  Custom Scan (AsyncAppend)  (cost=100.00..61868485.28 rows=1324271008 width=72) (actual time=10.424..10.426 rows=1 loops=1)
         ->  Append  (cost=100.00..61868485.28 rows=1324271008 width=72) (actual time=0.003..0.004 rows=1 loops=1)
               ->  Custom Scan (DataNodeScan) on t t_1  (cost=100.00..27623565.12 rows=662135504 width=72) (actual time=0.002..0.002 rows=1 loops=1)
               ->  Custom Scan (DataNodeScan) on t t_2  (cost=100.00..27623565.12 rows=662135504 width=72) (never executed)
 Planning Time: 104.882 ms
 Execution Time: 11.525 ms
(7 rows)

Time: 142,489 ms
```

**Comment by akuzm** [comment]
Can't seem to reproduce this on 2.7. The limit is pushed down to the data node, and the query completes in about 10 ms. Can reopen if we have a way to reproduce on 2.7.
