### ISSUE TITLE
Log level of materialization worker is too high

### ISSUE THREAD

**Issue by brian-from-quantrocket** [timescale/timescaledb#1858]
Platform: Docker: `timescale/timescaledb:1.7.0-pg12`

The background worker that materializes continuous aggregrates logs at `LOG` level:  

```
LOG:  materializing continuous aggregate mdagg_us_stk_tick_1min.last_size: no new range to materialize or invalidations found, exiting early
```

Is this the best log level to use? It gets rather noisy and you can't silence it without also silencing  `WARNING` and `ERROR`. I would suggest `INFO` or `NOTICE` as a better choice?

Optimal log levels can be fairly subjective to the use case so let me share mine. I am using TimescaleDB to store financial market data and using continuous aggregates to create 1-minute aggregates from the raw ticks. By default, the background worker will materialize data every 2 minutes (which seems about right), so this log information will show up in the logs that frequently, even in the substantial periods of time when there is no new tick data arriving because markets are closed and the background worker's task is a no-op. 

The background worker is just doing its job here so doesn't need to shout. As an end user, I appreciate having an audit trail but in this case would like to be able to tell the background worker, "keep up the great work, let me know if there are problems."

**Comment by erimatnor** [comment]
@brian-from-quantrocket Thanks for reporting this issue. We plan to overhaul the logging and other things around continuous aggregates. FWIW, though,  LOG was chosen according the rank in `client_min_messages` (https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-CLIENT-MIN-MESSAGES).  Both`NOTICE` and `INFO` means the client will see these messages with common client settings. `INFO`, in particular, is always sent to the client. 

Ideally, these messages wouldn't be needed or should probably be some kind of DEBUG level.

**Comment by svenklemm** [comment]
This should be fixed in 2.0 with the continuous aggregate refactorings. Feel free to reopen if the issue still exists.

**Comment by brian-from-quantrocket** [comment]
I've updated to Docker image `timescale/timescaledb:2.0.0-pg12` and it doesn't appear this issue has been addressed. The message text has changed but the message frequency is unchanged:

```
LOG:  refresh continuous aggregate range 2021-01-05 22:33:17.413467+00 , 2021-01-05 22:34:17.413473+00
```

This shows up at the frequency of the `schedule_interval` parameter in `add_continuous_aggregate_policy` (every 2 minutes in my example scenario outlined above). As in 1.x, the messages are logged even if there was no new data to materialize. Still just as noisy.

**Comment by brian-from-quantrocket** [comment]
This log message is originating from [here](https://github.com/timescale/timescaledb/blob/d043ff1e041f22814f3d923860df85c84e99dbaf/tsl/src/bgw_policy/job.c#L318-L319). 

By default, LOG messages will not be returned to the client (based on [client_min_messages](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-CLIENT-MIN-MESSAGES), which someone linked to above), but they *will* be written to the server log (based on [log_min_messages](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-MIN-MESSAGES)). Because LOG is ranked differently in client_min_messages vs log_min_messages (which seems like a mean trick by Postgres), LOG can't be disabled in the server log without also disabling NOTICE, WARNING, ERROR, which is probably not recommended.

I would suggest DEBUG1 as a better choice for this type of message that will be suitable for *both* client_min_messages and log_min_messages.
