### ISSUE TITLE
Windows release contains readme.txt.txt (Wrong file name)

### ISSUE THREAD

**Issue by SeppPenner** [timescale/timescaledb#1863]
**Relevant system information:**
 - OS: Windows general
 - PostgreSQL version: 12.x (Maybe also 11.x and older)
 - TimescaleDB version: 1.7.0 (and maybe older)
 - Installation method: setup.exe on Windows

**Describe the bug**
It's not a big bug, but the readme file is named `README.txt.txt` instead of `README.txt`.

**To Reproduce**
1. Go to https://docs.timescale.com/latest/getting-started/installation/windows/installation-windows
2. Download the windows installer zip file for Postgres 12.

**Expected behavior**
Rename `README.txt.txt` to `README.txt`.

**Actual behavior**
The readme file is named `README.txt.txt` instead of `README.txt`.

**Screenshots**
![image](https://user-images.githubusercontent.com/9639361/80492368-32c92780-8964-11ea-8e34-171260616eb8.png)

**Additional context**
None.

**Comment by k-rus** [comment]
@SeppPenner Thank you for reporting!

**Comment by RobAtticus** [comment]
Thanks, I have updated this so the next release should be correct!
