### ISSUE TITLE
Can I create hypertable if it dosen't exist

### ISSUE THREAD

**Issue by nmiculinic** [timescale/timescaledb#189]
For index I have:
```sql
CREATE INDEX IF NOT EXISTS table_idx ON table(time);
```
I cannot find something similar with hyper table, all I can find is:
```sql
SELECT create_hypertable(table, 'time', chunk_time_interval => 86400000000);
```

I'd love if I could create new hyper table if it doesn't exist already since I'm using DDL scripts to instantiate my table, and any new tables/etc. I require. 

P.S.
Also is there a way to write this huge chunk_time_interval nicer?

**Comment by RobAtticus** [comment]
Yes we do have a flag that allows you to do that:
`SELECT create_hypertable(table, 'time', chunk_time_interval => 86400000000, if_not_exists => TRUE);`

That will make it a hypertable if it is not already.

Regarding the large number for `chunk_time_interval`, we are discussing improving the API to allow something simpler like providing an interval type, e.g. `1 day` or similar.

**Comment by RobAtticus** [comment]
Here is the PR regarding chunk_time_interval: https://github.com/timescale/timescaledb/pull/181

**Comment by nmiculinic** [comment]
Thank you!
