### ISSUE TITLE
[Feature] Automatic synchronization of roles / users / permissions

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1895]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
When creating new roles, users or change permissions on the access node, it would be great to automatically (or semi-automatic, per command) sync them to the data nodes.

That way it is guaranteed, that the according permissions are available when executing queries.

**Possible Solutions**

1. Automatically intercept the create role or alter role commands and distribute them to the remote data nodes
2. Have a command, which when called explicitly, syncs the current set of roles to the data nodes

**Comment by erimatnor** [comment]
@noctarius Thanks for this feature request. This is indeed something that would be very useful and we've thought quite hard about how to solve it. Unfortunately, it is a difficult problem given how PostgreSQL deals with users and permission; roles in PostgreSQL are cluster-wide, i.e., they are shared objects across all databases, while data nodes and distributed hypertables exist at the database level. Given the complex dependencies between roles and other objects, it would be difficult to only synchronize the roles necessary for the given database. Instead, we probably need to synchronize the entire PostgreSQL instances in terms of roles and permissions, and while potentially possible, this quickly balloons to a much bigger issue than one might think at the outset. Essentially, it leads to the necessity to synchronize instances completely in terms of shared objects and making sure they stay in sync.

This is why we have punted on this for now, hoping that the common use case is to seed each instance with a set of roles initially and having relatively static roles configuration from there on. If roles need to be added dynamically, then we provide the `distributed_exec` call to make that easier. We do not, however, yet provide any safeguards that roles exist in an identical state across all nodes.

**Comment by noctarius** [comment]
I understand / agree it is not a simple issue, but clusters aren't simple ;-)

*distributed_exec* kind of works for now, but I see missing executions in the future. The alternative may be to have one command like *distributed_exec* (or something like *create_distributed_role*) which runs on all cluster members, including the access node :)

**Comment by erimatnor** [comment]
@noctarius FYI, we now offer automatic role synchronization on our hosted Cloud version of multi-node. There are some special assumptions we make on our hosted service (like enforcing a single database), which makes us able to offer this functionality. We are considering our options to make this available to the wider community in the future.

**Comment by erimatnor** [comment]
Due to complexity of supporting role synchronization with mutliple databases (which each can have a different view of the cluster), we are not planning to offer an automatic way of synchronizing roles for self-hosted installations. We recommend using `distributed_exec` in those scenarios.

Note that, as stated above, we offer role synchronization on Timescale Cloud since that is a controlled environment where we can make special assumptions.
