### ISSUE TITLE
[Feature] Automatically synchronize enabled PG extensions

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1896]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
When activating an extension on the access node, it should be enabled on the data nodes too.

An example for that would be pgcrypto for the *gen_random_uuid* function. Maybe a specific command or an options extension could help.

**Possible Solutions**

1. Automatically intercept the create extension command or provide an extension of it.

**Comment by erimatnor** [comment]
This seems related to bootstrapping of data nodes. I think a generic solution, like the ability to run a script on the data node when calling `add_data_node`, might be a more flexible solution.

**Comment by svenklemm** [comment]
multinode has been removed
