### ISSUE TITLE
[Feature] Foreign keys constraints on Distributed Hypertables

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1897]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
It be great to provide support for foreign key constraints on distributed hypertables, if actually possible.

**Comment by svenklemm** [comment]
multinode has been removed
