### ISSUE TITLE
[Feature] Remove the necessity to provide num_of_partitions parameter on add_dimension calls

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1898]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
When using *add_dimension* on a distributed hypertable, a parameter value for *num_of_partitions* must be provided. It should, however, be optional and default to the number of data nodes at the time of execution. 

It should also automatically increase with new nodes.

**Possible Solutions**

1. Make the parameter optional for distributed hypertables and default to the number of data nodes.

**Comment by svenklemm** [comment]
multinode has been removed
