### ISSUE TITLE
[Feature] Add parameter partition_multiplier to add_dimension

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1899]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**

Related to: https://github.com/timescale/timescaledb/issues/1898

When the number of partitions is automatically adjusted based on the number of data nodes, it'd be great to offer a multiplier. This multiplier would simply multiply the number of data nodes to achieve the same solution as for *add_dimension* with a specific *num_of_parameters* set on a single node setup. Achieving multiple partitions per data node.

**Possible Solutions**

Add a new parameter like *partition_multiplier*, only valid for distributed hypertables, to multiply the number of data nodes with the given value.

**Comment by svenklemm** [comment]
multinode has been removed
