### ISSUE TITLE
[Feature] Provide support for Compression on Distributed Hypertables

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1900]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
Compression is one of the major features when storing large amounts of information in TimescaleDB.

Unfortunately the functionality is limited to non distributed hypertables.

**Possible Solutions**

1. Provide support for it :-)

**Comment by erimatnor** [comment]
@noctarius This is something we're looking at. Beta4 should have basic support for manually compressing chunks though (with `compress_chunk` on the access node).

**Comment by noctarius** [comment]
Well maybe in the code, but not in reallife ;)

Using *compress_chunk* claims the compression property is missing, but executing the alter table command fails with "operation not supported on distributed hypertable".

```
clevabit.public> SELECT compress_chunk(i) from show_chunks('metrics', older_than => INTERVAL '3 days') i
[2020-05-15 12:08:37] [0A000] ERROR: chunks can be compressed only if compression property is set on the hypertable
```

**Comment by phemmer** [comment]
After testing manual compression on beta 6, it appears to work. Is manual compression something that would be considered stable when 2.0 is released? Or is it "use at your own risk"?

**Comment by phemmer** [comment]
For posterity, I [asked my question in the slack channel](https://timescaledb.slack.com/archives/CPSD82EMU/p1602768946082300) and got the response that manual compression is supported.

**Comment by shane-axiom** [comment]
This is partially implemented, issue title should be changed to:

Provide support for Compression Policies on Distributed Hypertables

**Comment by erimatnor** [comment]
@shane-axiom Compression policies should be supported on distributed hypertables. Please try this on the latest version if you haven't already. 

Feel free to re-open the issue if problems remain.
