### ISSUE TITLE
[Feature] Support running aggregations on data nodes

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1901]
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the functionality**
When executing more complex queries with aggregations like *avg* or *stddev_samp*, the data is filtered on the data node, sent to the access node and being aggregated there. That said, in my test query multiple 100k rows were transmitted instead of roughly 30 rows when aggregated.

**Possible Solutions**

It'd be better to provide, maybe specific, distributed versions of those aggregations, which can be executed on the data node first, intermediate results are being sent to the access node, where they're merged and a final aggregation step takes place.

I could imagine a version of *avg* like *distributed_avg*.

**Comment by erimatnor** [comment]
@noctarius we do support push-down aggregates. In some case, however, it is not possible to push down and in that case the aggregation happens on the access node.

Could you provide a reproducible example of the distributed hypertable creation, query and data (including EXPLAIN) that doesn't get pushed down? Without this information it is not possible to know why push-down doesn't happen.

**Comment by noctarius** [comment]
I can certainly try to get an example of that, but the data is probably the biggest issue. Rest is easy. Query and Explain output is already in Slack with @mkindahl  :)

**Comment by erimatnor** [comment]
Basic table schema and EXPLAIN will probably be a good start, even if we don't have the data set to reproduce on.

**Comment by noctarius** [comment]
Interesting thing, seems like after rebuilding with beta4 it is not that extreme anymore. It still, however, is about half as slow for about a month worth of data.

Anyhow, how do you prefer to get the information? The schema is quite vast, uses materialized and normal views, as well as functions ;)

The execution plans are also quite big. Just let me know how you prefer to get those. Slack's fine too :)

**Comment by noctarius** [comment]
PS: Even now, the aggregations are only executed on the access node. That said, the initial issue still exists ;)

**Comment by erimatnor** [comment]
Make sure you set `enable_partitionwise_aggregate=on` on the access node and then the aggregates should be pushed down in most cases. Otherwise, provide us with an EXPLAIN with the query plan and/or reach out on our support Slack.
