### ISSUE TITLE
hypertable_approximate_row_count returns 0 on distributed hypertable

### ISSUE THREAD

**Issue by noctarius** [timescale/timescaledb#1902]
**Relevant system information:**
PostgreSQL version: 11
TimescaleDB version: 2.0.0-beta4
Installation method: Helm chart (with image changed to 2.0.0-beta4-pg11)

**Describe the bug**
When executing *hypertable_approximate_row_count* on a distributed hypertable, the result seems to always be 0, which certainly is wrong in my case.

**To Reproduce**
1. Create a distributed hypertable
2. Generate test data
3. Execute *hypertable_approximate_row_count*
4. See estimated row count is 0

**Expected behavior**
Push the estimation request down to the data nodes and sum up the result on the access node. It's an estimation anyways, therefore async is fine and transactions don't matter.

**Actual behavior**
Result is always 0. My guess the estimation happens on the access node's local hypertable which is empty.

**Comment by pmwkaa** [comment]
@noctarius I guess this function should work out of the box after `ANALYZE` being executed on the access node

**Comment by pmwkaa** [comment]
We also done some refactoring and introduced support for compression and regular tables: https://github.com/timescale/timescaledb/issues/2252
