### ISSUE TITLE
Query hangs through Grafana

### ISSUE THREAD

**Issue by hc128168** [timescale/timescaledb#1903]
- OS: CentOS 7.7
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: timescaledb's yum repository

Before I created a hypertable for my existing table, grafana 6 could load 2.89M rows from that table (no join) and plot, and then I was curious whether timescaledb could improve it and so I created a hypertable for it, and asked grafana to plot again.  And on chrome, it gave me ["RESULT_CODE_INVALID_CMDLINE_URL"](https://support.google.com/chrome/answer/95669?visit_id=637250994415655853-966100188&p=e_awsnap&rd=1).  Then, I tried again with Firefox, and Firefox asked whether I wanted to stop loading the page every few seconds, after I asked Firefox to ignore ~7 times, the graph was plotted.

Questions:
1.  How can I drop the hypertable but not the original table?  So that I can verify it is indeed timescaledb slowing it down as the query seems fine:

>  Seq Scan on _hyper_4_3_chunk  (cost=0.00..72871.75 rows=2890872 width=37) (actual time=0.080..390.485 rows=2891450 loops=1)
   Filter: (("time" > '2020-05-13 09:00:00+08'::timestamp with time zone) AND ("time" < '2020-05-13 15:30:00+08'::timestamp with time zone))
   Buffers: shared hit=864 read=28636
 Planning Time: 1.805 ms
 Execution Time: 476.248 ms
(5 rows)

2.  What can I check to see if I misconfigured timescaledb, causing the issue?

**Comment by noctarius** [comment]
Have you told Grafana that it is a TimescaleDB Hypertable in the data source? And what is the generated SQL of the query?

**Comment by hc128168** [comment]
I am using the latest stable version of grafana -- 6.7.3 (7 is coming up next few weeks).

When I added the data source, TimescaleDB is not listed as a supported "time series" database nor SQL database.  So I just followed the [instruction](https://docs.timescale.com/latest/tutorials/tutorial-grafana) to select 'PostgresSQL' as the data source.  How can I tell Grafana that it is a TimescaleDB hypertable?

Generated SQL:
'
SELECT
  time,
  bid_price,
  ask_price,
  instrument_name
FROM tob_l2
WHERE
  time > '20200513 09:00:00+8' and time < '20200513 15:30:00+8'
ORDER BY 1
'

**Comment by noctarius** [comment]
No but the Postgresql data source has a switch to say "yes that's a timescale db" :)

On your link, see the third screenshot and the "timescaledb" being enabled

**Comment by hc128168** [comment]
oh, yes, I did enable TimescaleDB.

**Comment by mfreed** [comment]
@hc128168 Just to clarify, when you connect directly to the database via a tool in psql, you see the query taking < 500ms, but via Grafana it just hangs?  Do you see anything in Grafana logs?

**Comment by hc128168** [comment]
@mfreed yes around 500ms.  I just rebooted my machine (cold cache) and tried again -- 749ms.

And when I tried it with Grafana, it didn't hang but just took very very long time that Chrome threw error and firefox gave me warning few times.

I thought about that it could be Grafana's issue not TimescaleDB but before I migrated the table to hypertable, Chrome worked fine.

**Comment by dev-mull** [comment]
As for question 1.. You will have to copy the data to another table then rename the old hypertable to something else and rename the new table back to the original name. I validated that a create table as does not do any magic to create a hypertable.

CREATE TABLE new_table AS TABLE existing_hypertable;

ALTER TABLE table_name RENAME TO new_table_name;

**Comment by hc128168** [comment]
@erimatnor any info you need from me?

**Comment by svenklemm** [comment]
@hc128168 so the query is reasonably fast in psql but is not performing well in grafana? This seems more like a grafana issue then. To verify you can use your browser network tools and check if the time is spent on grafana server side or grafana client side.

**Comment by hc128168** [comment]
I ran again with top and noticed that postgres was busy for few seconds, and then grafana-server was busy for few seconds and then chrome was busy for tens of seconds and then got that error.  So I believe that the issue is on the rendering part.

Tho, it is still unclear to me why chrome was able to render days ago with the same set of data on the same machine.
