### ISSUE TITLE
"ERROR:  bogus varno: 65001" when query against view containing hypertables

### ISSUE THREAD

**Issue by frostwind** [timescale/timescaledb#1907]
**Relevant system information:**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: yum install

**Describe the bug**
When query against a view composed by two or more hypertables, it pops up "ERROR:  bogus varno: 65001" or "attribute number 2 exceeds number of columns 0" , depends on data set. Below simple test case can produce "ERROR:  bogus varno: 65001".

**To Reproduce**
Basically we have two tables with same structure, t1 and t2,  then we create view t_view on top of t1 and t2. Then we run a query to hit the error.

`Drop table t1 cascade;
Create table public.t1 (start_date date not null,end_date date not null, deviceid smallint not null, loading double  Precision not null) ;
SELECT create_hypertable('t1', 'start_date', chunk_time_interval=>interval '1 year', create_default_indexes=>false);
ALTER TABLE t1  SET (timescaledb.compress,timescaledb.compress_orderby='start_date',timescaledb.compress_segmentby='end_date');
Insert into t1 values ('2000-01-01','2002-01-01',100,0.1);
SELECT compress_chunk(i.chunk_name)  from timescaledb_information.compressed_chunk_stats i where hypertable_name='t1'::regclass and compression_status!='Compressed';

Drop table t2 cascade;
Create table public.t2 (start_date date not null,end_date date not null,deviceid smallint not null, loading double  Precision not null) ;
SELECT create_hypertable('t2', 'start_date', chunk_time_interval=>interval '1 year', create_default_indexes=>false);
ALTER TABLE t2  SET (timescaledb.compress,timescaledb.compress_orderby='start_date',timescaledb.compress_segmentby='end_date');
Insert into t2 values ('2013-01-01','2014-01-01',200,0.1);
SELECT compress_chunk(i.chunk_name)  from timescaledb_information.compressed_chunk_stats i where hypertable_name='t2'::regclass and compression_status!='Compressed';

Create or replace view t_view as 
 Select * from t1 
 Union all
 Select * from t2;

Explain (analyze,buffers,timing)  select deviceid, loading
	        from t_view tv , (
  VALUES (100),(200)) vals(v)
	      where start_date <= '2014-03-13'::date
	        and end_date >= '2014-03-13'::date and tv.deviceid=vals.v;

ERROR:  bogus varno: 65001
Time: 1.476 ms

select deviceid, loading
	        from t_view tv , (
  VALUES (100),(200)) vals(v)
	      where start_date <= '2014-03-13'::date
	        and end_date >= '2014-03-13'::date and tv.deviceid=vals.v;

 deviceid | loading 
----------+---------
(0 rows)

Time: 1.439 ms

`

**Expected behavior**
It should return without error no matter we use explain or not. 

**Actual behavior**
It pop up "ERROR:  bogus varno: 65001" or "attribute number 2 exceeds number of columns 0", depend on test dataset. But above simple test case can only reproduce "ERROR:  bogus varno: 65001". I have larger data set to reproduce "attribute number 2 exceeds number of columns 0" but I can not upload it.

**Screenshots**

**Additional context**

**Comment by frostwind** [comment]
Seems to be very similar as https://github.com/timescale/timescaledb/issues/1837,  if I create view with "UNION" instead of "UNION ALL", it does not pop up error "ERROR: bogus varno: 65001" or "attribute number 2 exceeds number of columns 0". Maybe we can close this ticket .

**Comment by svenklemm** [comment]
Thanks for the report, this is already fixed in master.
