### ISSUE TITLE
hypertable_relation_size doesn't work when hyper table is in a schema other than public

### ISSUE THREAD

**Issue by nathanielobrown** [timescale/timescaledb#1909]
**Relevant system information:**
 - OS: Digital Ocean hosted, so I don't know
 - PostgreSQL version: 11.7
 - TimescaleDB version: 1.6.0
 - Installation method: Digital Ocean hosted. Also happens locally with docker image

**Describe the bug**
I moved my waypoints table from "public" to "tenant." Everything works fine, except for this function to show the table size. The migration was done be creating a fresh hyper table and dumping and loading from CSV. This also happens with a totally fresh database running locally via docker.

**To Reproduce**
1. Create a hyper table (`waypoints`) inside a postgres schema (`tenant`)
2. Run `SELECT * FROM public.hypertable_relation_size ('tenant.waypoints')`

**Expected behavior**
We should see the table size

**Actual behavior**
`NULL`s are returned for all columns.

I just want to say that I LOVE timescaledb!

**Comment by svenklemm** [comment]
The query returns NULL if no chunks have been created yet but when there are chunks the query should work.

**Comment by nathanielobrown** [comment]
Ah, my bad my hypertable wasn't actually initialized. Now it works.

Thank you for the fast response!
