### ISSUE TITLE
time_bucket() wrong result

### ISSUE THREAD

**Issue by ramyzbeidy9** [timescale/timescaledb#1917]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version 12
 - TimescaleDB version timescaledb 1.7
 - Installation method: source

**Describe the bug**
time_bucket() method is generating wrong grouping of data. This is only reproduced in version 1.7.
The output is different than date_trunc.

**To Reproduce**

		SELECT 
			time_bucket('1 day', Time) AS OneDay,
			SUM(InRange) as InRange
		FROM Measurements
		WHERE NOT IsDeleted AND NOT IsDiscarded AND IngKey IS NOT NULL
		and time <= '2020-05-10'
		GROUP BY OneDay
		order by OneDay desc;
		
**Expected behavior**
the above query should be the same if we replace time_bucket with date_trunc.

**Actual behavior**
Grouping is different, with wrong results

**Screenshots**

time_bucket:
![image](https://user-images.githubusercontent.com/63997285/82324889-0fcde880-99e3-11ea-9924-c81c12daa4cb.png)

date_trunc:
![image](https://user-images.githubusercontent.com/63997285/82324999-33912e80-99e3-11ea-9df5-68b94fc34f14.png)

**NOTE this is only reproduced on timescaledb 1.7. 
Knowing that this will heavily impact all the continuous aggregates.

**Comment by svenklemm** [comment]
This is not a bug and documented behaviour, 

`TIMESTAMPTZ arguments are bucketed by the time at UTC. So the alignment of buckets is on UTC time. One consequence of this is that daily buckets are aligned to midnight UTC, not local time.`

See https://docs.timescale.com/latest/api#time_bucket
