### ISSUE TITLE
Case Sensitive table names

### ISSUE THREAD

**Issue by je1h** [timescale/timescaledb#1925]
Hi!

I have a requirement to support case sensitive table and column names.
While it's not an issue in PostgreSQL itself, I've got problem with TimescaleDB.

When I try 
`SELECT create_hypertable("MyTable", "timestamp", chunk_time_interval => 86400000000);`

the response is 
`ERROR:  column "MyTable" does not exist`.

Do I miss something?
Does TimescaleDB support case sensitive table naming?

Thanks.

TimescaleDB 1.7.1
PostgreSQL 11.7

**Comment by blagojts** [comment]
`SELECT create_hypertable('"MyTable"', 'timestamp')`

**Comment by svenklemm** [comment]
@je1h closing this. Feel free to reopen if you come across any issues with case sensitive identifiers.
