### ISSUE TITLE
ERROR:  permission denied for table _hyper_1_12_chunk

### ISSUE THREAD

**Issue by nshah14285** [timescale/timescaledb#1927]
Hello,

Using
 - OS: [Ubuntu 16.04]
 - PostgreSQL version (11.5)
 - TimescaleDB version (1.6.0~ubuntu16.04)

I cannot find a section in the official docs about permission handling with hypertables.

I have created hypertable in Postgres and trying to take a dump of all tables using pg_dump command having back_user with select permission.

Now whenever new table _hyper_1_xx_chunk created, pg_dump command throws an error `permission denied for table _hyper_1_13_chunk`.

After I give permission manually `grant select on all tables in schema _timescaledb_internal to back_user` pg_dump command runs successfully.

How can I fix this issue? Is there a way to apply permission automatically whenever a new _hyper_1_xx_chunk file create?

Because of this issue we were not able to take db dump daily.

Thanks.
Nishit Shah

**Comment by nshah14285** [comment]
Any update?

**Comment by mkindahl** [comment]
It is not very clear how your setup looks, but this looks more like a PostgreSQL issue rather than a TimescaleDB issue.

Have you checked the that you have default permissions set for the schema `_timescaledb_internal` (see [ALTER DEFAULT PRIVILEGES](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html)?

**Comment by nshah14285** [comment]
@mkindahl I'll check the privileges and update you.

**Comment by mkindahl** [comment]
I investigated this a little further. It seems like the permissions does not propagate from hypertables to chunks. This is not a problem when accessing the chunks through the hypertable, since that code avoids the permissions, but when accessing the chunks directly, as `pg_dump` does, it will not work.

```
CREATE TABLE conditions(
    time TIMESTAMPTZ NOT NULL,
    device INTEGER,
    temperature FLOAT
);
SELECT * FROM create_hypertable('conditions', 'time', chunk_time_interval => '7 days'::interval);
 hypertable_id | schema_name | table_name | created 
---------------+-------------+------------+---------
             1 | public      | conditions | t
(1 row)

INSERT INTO conditions
SELECT time, (random()*30)::int, random()*80 - 40
FROM generate_series('2018-12-01 00:00'::timestamp, '2018-12-14 00:00'::timestamp, '1h') AS time;
\z conditions
                               Access privileges
 Schema |    Name    | Type  | Access privileges | Column privileges | Policies 
--------+------------+-------+-------------------+-------------------+----------
 public | conditions | table |                   |                   | 
(1 row)

\z _timescaledb_internal.*chunk
                                          Access privileges
        Schema         |       Name       | Type  | Access privileges | Column privileges | Policies 
-----------------------+------------------+-------+-------------------+-------------------+----------
 _timescaledb_internal | _hyper_1_1_chunk | table |                   |                   | 
 _timescaledb_internal | _hyper_1_2_chunk | table |                   |                   | 
 _timescaledb_internal | _hyper_1_3_chunk | table |                   |                   | 
(3 rows)

GRANT SELECT ON conditions TO PUBLIC;
\z conditions
                                     Access privileges
 Schema |    Name    | Type  |       Access privileges       | Column privileges | Policies 
--------+------------+-------+-------------------------------+-------------------+----------
 public | conditions | table | super_user=arwdDxt/super_user+|                   | 
        |            |       | =r/super_user                 |                   | 
(1 row)

\z _timescaledb_internal.*chunk
                                          Access privileges
        Schema         |       Name       | Type  | Access privileges | Column privileges | Policies 
-----------------------+------------------+-------+-------------------+-------------------+----------
 _timescaledb_internal | _hyper_1_1_chunk | table |                   |                   | 
 _timescaledb_internal | _hyper_1_2_chunk | table |                   |                   | 
 _timescaledb_internal | _hyper_1_3_chunk | table |                   |                   | 
(3 rows)
```

Solution is probably to propagate permissions when doing a `GRANT` or `REVOKE` and to copy the permissions from the hypertable when creating a new chunk.

**Comment by nshah14285** [comment]
@mkindahl
I have tried (ALTER DEFAULT PRIVILEGES) on `_timescaledb_internal` and it worked.
Thank You that solved the problem with pg_dump command.
