### ISSUE TITLE
Query without ORDER BY returns rows, but if I add ORDER BY, it returns 0 rows

### ISSUE THREAD

**Issue by sscots** [timescale/timescaledb#1928]
- OS: RHEL 7.6
 - PostgreSQL version: 11.6
 - TimescaleDB version: 1.6.1
 - Installation method: unknown

If run a query without the ORDER BY syntax, it returns a number of rows. If I simply add the ORDER BY on just some of the selected columns it returns 0 rows. However some columns work on ORDER BY.

WORKING QUERY:
` EXPLAIN ANALYZE SELECT jobs.project, checkouts.licenseid, checkouts.tokens, checkouts.latest_time, checkouts.id
FROM jobs
JOIN checkouts ON checkouts.host = jobs.exec_host AND checkouts.latest_time = (SELECT MAX(timestamp)::timestamp FROM timestamps)
AND jobs.timestamp = (SELECT MAX(timestamp)::timestamp FROM timestamps)
`

RETURNS:
`Hash Join  (cost=1024584.87..1158873.98 rows=6868655 width=25) (actual time=399.932..443.064 rows=328476 loops=1)
   Hash Cond: ((jobs.exec_host)::text = (checkouts.host)::text)
   InitPlan 2 (returns $1)
     ->  Result  (cost=0.32..0.33 rows=1 width=8) (actual time=0.012..0.012 rows=1 loops=1)
           InitPlan 1 (returns $0)
             ->  Limit  (cost=0.29..0.32 rows=1 width=8) (actual time=0.011..0.011 rows=1 loops=1)
                   ->  Index Only Scan Backward using timestamps_pkey on timestamps  (cost=0.29..2977.96 rows=143758 width=8) (actual time=0.011..0.011 rows=1 loops=1)
                         Index Cond: ("timestamp" IS NOT NULL)
                         Heap Fetches: 1
   InitPlan 4 (returns $3)
     ->  Result  (cost=0.32..0.33 rows=1 width=8) (actual time=0.018..0.018 rows=1 loops=1)
           InitPlan 3 (returns $2)
             ->  Limit  (cost=0.29..0.32 rows=1 width=8) (actual time=0.016..0.016 rows=1 loops=1)
                   ->  Index Only Scan Backward using timestamps_pkey on timestamps timestamps_1  (cost=0.29..2977.96 rows=143758 width=8) (actual time=0.015..0.015 rows=1 loops=1)
                         Index Cond: ("timestamp" IS NOT NULL)
                         Heap Fetches: 1
   ->  Index Scan using time_exec_host on jobs  (cost=0.42..5695.45 rows=38097 width=17) (actual time=0.035..8.791 rows=19688 loops=1)
         Index Cond: ("timestamp" = $3)
   ->  Hash  (cost=1013093.11..1013093.11 rows=919254 width=31) (actual time=398.519..398.520 rows=50434 loops=1)
         Buckets: 1048576  Batches: 1  Memory Usage: 11324kB
         ->  Custom Scan (ChunkAppend) on checkouts  (cost=0.00..1013093.11 rows=919254 width=31) (actual time=260.656..391.178 rows=50434 loops=1)
               ->  Seq Scan on _hyper_25_68_chunk  (cost=0.00..1.39 rows=4 width=32) (actual time=0.026..0.026 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 31
               ->  Bitmap Heap Scan on _hyper_25_69_chunk  (cost=79.86..14142.66 rows=11652 width=31) (actual time=2.222..2.222 rows=0 loops=1)
                     Recheck Cond: (latest_time = $1)
                     ->  Bitmap Index Scan on _hyper_25_69_chunk_checkouts_latest_time_brin  (cost=0.00..76.94 rows=13668 width=0) (actual time=2.221..2.221 rows=0 loops=1)
                           Index Cond: (latest_time = $1)
               ->  Seq Scan on _hyper_25_70_chunk  (cost=0.00..1.06 rows=1 width=31) (actual time=0.005..0.005 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 5
               ->  Seq Scan on _hyper_25_71_chunk  (cost=0.00..52.01 rows=11 width=30) (actual time=0.222..0.222 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 2081
               ->  Seq Scan on _hyper_25_72_chunk  (cost=0.00..7.14 rows=8 width=31) (actual time=0.030..0.030 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 251
               ->  Seq Scan on _hyper_25_73_chunk  (cost=0.00..33.75 rows=2 width=31) (actual time=0.146..0.146 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 1340
               ->  Seq Scan on _hyper_25_74_chunk  (cost=0.00..1.01 rows=1 width=32) (actual time=0.004..0.004 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 1
               ->  Seq Scan on _hyper_25_75_chunk  (cost=0.00..5.20 rows=13 width=31) (actual time=0.025..0.025 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 176
               ->  Seq Scan on _hyper_25_76_chunk  (cost=0.00..1.14 rows=4 width=32) (actual time=0.005..0.005 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 11
               ->  Seq Scan on _hyper_25_77_chunk  (cost=0.00..1.09 rows=1 width=24) (actual time=0.004..0.004 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 7
               ->  Seq Scan on _hyper_25_78_chunk  (cost=0.00..1.04 rows=1 width=31) (actual time=0.005..0.005 rows=0 loops=1)
                     Filter: (latest_time = $1)
                     Rows Removed by Filter: 3
               ->  Bitmap Heap Scan on _hyper_25_98_chunk  (cost=170.86..13494.65 rows=11686 width=31) (actual time=4.880..4.880 rows=0 loops=1)
                     Recheck Cond: (latest_time = $1)
                     ->  Bitmap Index Scan on _hyper_25_98_chunk_checkouts_latest_time_brin  (cost=0.00..167.94 rows=12455 width=0) (actual time=4.880..4.880 rows=0 loops=1)
                           Index Cond: (latest_time = $1)
               ->  Bitmap Heap Scan on _hyper_25_101_chunk  (cost=155.37..12112.00 rows=10548 width=31) (actual time=4.427..4.427 rows=0 loops=1)
                     Recheck Cond: (latest_time = $1)
                     ->  Bitmap Index Scan on _hyper_25_101_chunk_checkouts_latest_time_brin  (cost=0.00..152.73 rows=11172 width=0) (actual time=4.426..4.426 rows=0 loops=1)
                           Index Cond: (latest_time = $1)
               ->  Bitmap Heap Scan on _hyper_25_103_chunk  (cost=159.75..12745.04 rows=10835 width=31) (actual time=4.502..4.502 rows=0 loops=1)
                     Recheck Cond: (latest_time = $1)
                     ->  Bitmap Index Scan on _hyper_25_103_chunk_checkouts_latest_time_brin  (cost=0.00..157.04 rows=11768 width=0) (actual time=4.502..4.502 rows=0 loops=1)
                           Index Cond: (latest_time = $1)
               ->  Bitmap Heap Scan on _hyper_25_104_chunk  (cost=174.11..15356.38 rows=11846 width=31) (actual time=4.903..4.903 rows=0 loops=1)
                     Recheck Cond: (latest_time = $1)
                     ->  Bitmap Index Scan on _hyper_25_104_chunk_checkouts_latest_time_brin  (cost=0.00..171.14 rows=14244 width=0) (actual time=4.902..4.902 rows=0 loops=1)
`

BROKEN QUERY:
`EXPLAIN ANALYZE SELECT jobs.project, checkouts.licenseid, checkouts.tokens, checkouts.latest_time, checkouts.id
FROM jobs
JOIN checkouts ON checkouts.host = jobs.exec_host AND checkouts.latest_time = (SELECT MAX(timestamp)::timestamp FROM timestamps)
AND jobs.timestamp = (SELECT MAX(timestamp)::timestamp FROM timestamps) ORDER BY checkouts.tokens;`

RETURNS:
` Gather Merge  (cost=1346719.10..2014551.72 rows=5723880 width=25) (actual time=20.567..22.902 rows=0 loops=1)
   Workers Planned: 2
   Params Evaluated: $1, $3
   Workers Launched: 2
   InitPlan 2 (returns $1)
     ->  Result  (cost=0.32..0.33 rows=1 width=8) (actual time=0.019..0.019 rows=1 loops=1)
           InitPlan 1 (returns $0)
             ->  Limit  (cost=0.29..0.32 rows=1 width=8) (actual time=0.016..0.016 rows=1 loops=1)
                   ->  Index Only Scan Backward using timestamps_pkey on timestamps  (cost=0.29..2977.96 rows=143758 width=8) (actual time=0.015..0.015 rows=1 loops=1)
                         Index Cond: ("timestamp" IS NOT NULL)
                         Heap Fetches: 1
   InitPlan 4 (returns $3)
     ->  Result  (cost=0.32..0.33 rows=1 width=8) (actual time=0.007..0.007 rows=1 loops=1)
           InitPlan 3 (returns $2)
             ->  Limit  (cost=0.29..0.32 rows=1 width=8) (actual time=0.005..0.005 rows=1 loops=1)
                   ->  Index Only Scan Backward using timestamps_pkey on timestamps timestamps_1  (cost=0.29..2977.96 rows=143758 width=8) (actual time=0.005..0.005 rows=1 loops=1)
                         Index Cond: ("timestamp" IS NOT NULL)
                         Heap Fetches: 1
   ->  Sort  (cost=1345718.42..1352873.27 rows=2861940 width=25) (actual time=2.322..2.322 rows=0 loops=3)
         Sort Key: checkouts.tokens
         Sort Method: quicksort  Memory: 25kB
         Worker 0:  Sort Method: quicksort  Memory: 25kB
         Worker 1:  Sort Method: quicksort  Memory: 25kB
         ->  Parallel Hash Join  (cost=1010959.07..1038795.93 rows=2861940 width=25) (actual time=2.274..2.275 rows=0 loops=3)
               Hash Cond: ((jobs.exec_host)::text = (checkouts.host)::text)
               ->  Parallel Index Scan using time_exec_host on jobs  (cost=0.42..5473.22 rows=15874 width=17) (never executed)
                     Index Cond: ("timestamp" = $3)
               ->  Parallel Hash  (cost=1006170.07..1006170.07 rows=383086 width=31) (actual time=0.001..0.001 rows=0 loops=3)
                     Buckets: 1048576  Batches: 1  Memory Usage: 0kB
                     ->  Parallel Custom Scan (ChunkAppend) on checkouts  (cost=531.85..1006170.07 rows=383086 width=31) (actual time=0.001..0.001 rows=0 loops=1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_152_chunk  (cost=531.85..36125.96 rows=13201 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_152_chunk_checkouts_latest_time_brin  (cost=0.00..523.93 rows=33339 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_144_chunk  (cost=470.59..35628.28 rows=13642 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_144_chunk_checkouts_latest_time_brin  (cost=0.00..462.40 rows=33048 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_145_chunk  (cost=459.48..34919.91 rows=13293 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_145_chunk_checkouts_latest_time_brin  (cost=0.00..451.50 rows=32397 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_148_chunk  (cost=452.90..34228.26 rows=13175 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_148_chunk_checkouts_latest_time_brin  (cost=0.00..445.00 rows=31747 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_149_chunk  (cost=449.65..34221.68 rows=13094 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_149_chunk_checkouts_latest_time_brin  (cost=0.00..441.80 rows=31751 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_143_chunk  (cost=444.03..33535.66 rows=12730 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_143_chunk_checkouts_latest_time_brin  (cost=0.00..436.40 rows=31104 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_141_chunk  (cost=441.86..33528.80 rows=12775 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_141_chunk_checkouts_latest_time_brin  (cost=0.00..434.20 rows=31104 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_142_chunk  (cost=441.80..32858.40 rows=12677 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_142_chunk_checkouts_latest_time_brin  (cost=0.00..434.19 rows=30456 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_146_chunk  (cost=436.32..32840.04 rows=12550 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_146_chunk_checkouts_latest_time_brin  (cost=0.00..428.79 rows=30454 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
                           ->  Parallel Bitmap Heap Scan on _hyper_25_151_chunk  (cost=431.95..32794.18 rows=12420 width=31) (never executed)
                                 Recheck Cond: (latest_time = $1)
                                 ->  Bitmap Index Scan on _hyper_25_151_chunk_checkouts_latest_time_brin  (cost=0.00..424.49 rows=30422 width=0) (never executed)
                                       Index Cond: (latest_time = $1)
`

**Comment by svenklemm** [comment]
There was a problem with parallel queries under certain conditions this should be fixed in timescaledb 1.7.1

**Comment by mfreed** [comment]
Hi @sscots Have you had a chance to see if the 1.7.1 release fixes this issue for you?

**Comment by sscots** [comment]
> Hi @sscots Have you had a chance to see if the 1.7.1 release fixes this issue for you?

Not yet. Should get to it later this week.

**Comment by svenklemm** [comment]
Closing this since this should be fixed in latest release. Feel free to reopen if this still happens with latest version.

**Comment by sscots** [comment]
It seems to be working now.
