### ISSUE TITLE
Continuous Aggregation job fails during autovacuum

### ISSUE THREAD

**Issue by niranjan92** [timescale/timescaledb#1935]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version : 11.7
 - TimescaleDB version 1.5.1
 - Installation method: "apt install"

**Describe the bug**
Facing this issue since more than a month. `autovacuum` job causes continuous aggregate jobs to fail.

**To Reproduce**
Have 2 continuous aggregation tables
```
tickdb# select * from timescaledb_information.continuous_aggregates;

-[ RECORD 1 ]--------------+--------------------------------------------------------------------------
view_name                  | ohlc_15min_view
view_owner                 | postgres
refresh_lag                | -00:15:00
refresh_interval           | 00:00:30
max_interval_per_job       | 5 days
materialization_hypertable | _timescaledb_internal._materialized_hypertable_11
view_definition            |  SELECT time_bucket('00:15:00'::interval, ticks."time") AS "interval",   +
                           |     ticks.isin,                                                          +
                           |     first(ticks.price, ticks."time") AS open,                            +
                           |     max(ticks.price) AS high,                                            +
                           |     min(ticks.price) AS low,                                             +
                           |     last(ticks.price, ticks."time") AS close,                            +
                           |     sum(ticks.qty) AS volume,                                            +
                           |     avg(ticks.price) AS avg                                              +
                           |    FROM ticks                                                            +
                           |   GROUP BY (time_bucket('00:15:00'::interval, ticks."time")), ticks.isin;
-[ RECORD 2 ]--------------+--------------------------------------------------------------------------
view_name                  | ohlc_3min_view
view_owner                 | postgres
refresh_lag                | -00:03:00
refresh_interval           | 00:00:15
max_interval_per_job       | 10 days
materialization_hypertable | _timescaledb_internal._materialized_hypertable_19
view_definition            |  SELECT time_bucket('00:03:00'::interval, ticks."time") AS "interval",   +
                           |     ticks.isin,                                                          +
                           |     first(ticks.price, ticks."time") AS open,                            +
                           |     max(ticks.price) AS high,                                            +
                           |     min(ticks.price) AS low,                                             +
                           |     last(ticks.price, ticks."time") AS close,                            +
                           |     sum(ticks.qty) AS volume,                                            +
                           |     avg(ticks.price) AS avg                                              +
                           |    FROM ticks                                                            +
                           |   GROUP BY (time_bucket('00:03:00'::interval, ticks."time")), ticks.isin;

....

```

The job fails everyday at 9 AM UTC. On checking system log, CPU and disk IO usage is high. 

`SELECT * FROM timescaledb_information.continuous_aggregate_stats;`
shows that job fails with 
```
last_run_status        | Failed
job_status             | running
last_run_duration      | 
next_scheduled_run     | -infinity
```

The issue happens only during the specific time of the day when the autovacuum job runs. `Disabling autovacuum fixes the issue` .

**Expected behavior**
- Continuous Aggregate job should run without any errors

**Actual behavior**
Continuous Aggregate job keeps failing without any error until autovacuum job completes

```
```

**Screenshots**
The aggregation jobs seem to be stuck in some loop consuming very high disk IO
- `sudo iotop` shows 
![iotop](https://user-images.githubusercontent.com/1474302/82931632-daa63500-9fa4-11ea-9860-446dacf642a2.png)

**Comment by gayyappan** [comment]
@nirnajan92 Does this eventually succeed? Have you checked locks and/or session activity to see if processes are getting blocked?

**Comment by niranjan92** [comment]
As the continuous aggregates are critical to the system, I haven't waited and checked if the jobs recover on their own. 

i used to 1) refresh materialized view or 2) delete older data of underlying table. I don't know if the above steps make any difference, but the jobs eventually recovered. 

I am not using any transactions/ locks on underlying table.  

I could not find any error logs related to this. 

The issue seems to be similar to https://github.com/timescale/timescaledb/issues/1689

**Comment by gayyappan** [comment]
@niranjan92 We made a lot of improvements to the background worker jobs used to run con. aggregates. Are you able to upgrade to 1.7.1? Do you see this on 1.7.1?

**Comment by niranjan92** [comment]
I did a fresh install of 1.7.1 on new machine and migrated my old data. Not getting any problems since 3 days. 

you can close this issue
