### ISSUE TITLE
timescaledb-tune not isntalled via ubuntu18/mint timescaledb-postgresql-12

### ISSUE THREAD

**Issue by pranasblk** [timescale/timescaledb#1951]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
`5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
`12.3` 
- TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
```
postgres-# \dx
                         List of installed extensions
    Name    | Version |   Schema   |                Description                
------------+---------+------------+-------------------------------------------
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
 plpython3u | 1.0     | pg_catalog | PL/Python3U untrusted procedural language
```

 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**
Attempt to invoke tune:
```
$ sudo timescaledb-tune
sudo: timescaledb-tune: command not found
# find / -name timescaledb-tune
not found
```

**To Reproduce**
1. Install PG12  separatly
2. Install Timescale 
3. Try to find 

**Expected behavior**
Should be available after installation as per messages:

```
RECOMMENDED: Run 'timescaledb-tune' (installed as part of the 
timescaledb-tools package, a recommended dependency) to update your 
config settings for TimescaleDB: 

  timescaledb-tune --quiet --yes
```

**Actual behavior**
 timescaledb-tune  not found

**Comment by k-rus** [comment]
Can you clarify how do you install TimescaleDB in the OP? What version?

**Comment by pranasblk** [comment]
Installed packages:

timescaledb-loader-postgresql-12/bionic,now 1.7.1~ubuntu18.04 amd64
[installed,automatic]
timescaledb-postgresql-12/bionic,now 1.7.1~ubuntu18.04 amd64 [installed]

**Comment by hojdars** [comment]
Also experiencing this on Linux Mint 19.3 Tricia, with Postresql 12, even without any Dockers. After performing this:

```
# Add our PPA
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt-get update

# Now install appropriate package for PG version
sudo apt install timescaledb-postgresql-12
```

the call to tune results in "not found" error:
```
timescaledb-tune: command not found
```

**Comment by svenklemm** [comment]
timescaledb-tune is in a separate package called timescaledb-tools

**Comment by hojdars** [comment]
The installation manual (https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu) still claims that `timescaledb-tune` gets installed with timescaledb though, which is clearly wrong. Which of timescaledb's packages manage the installation manual so I can report this issue @svenklemm ?
