### ISSUE TITLE
Dropping non hypertable references chuncks of hypertable after migration when using sequences

### ISSUE THREAD

**Issue by kdorsel** [timescale/timescaledb#1963]
**Relevant system information:**
 - OS: Windows Server 2016
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.1
 - Installation method: Windows exe

**Describe the bug**
Migrating data over to TimescaleDB.

```
alter table parts rename to parts_old;
create table parts (like parts_old including defaults including constraints);
select create_hypertable('parts', 'ts');
insert into parts select * from parts_old;
```
Check what hypertables exist. This is ok
```
select * from _timescaledb_catalog.hypertable where schema_name = 'public' and table_name like 'parts%';
```

id | schema_name | table_name | associated_schema_name | associated_table_prefix | num_dimensions | chunk_sizing_func_schema | chunk_sizing_func_name | chunk_target_size | compressed | compressed_hypertable_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8 | public | parts | _timescaledb_internal | _hyper_8 | 1 | _timescaledb_internal | calculate_chunk_interval | 0 | FALSE | NULL

Check the chunks of `parts`. This is ok.
```
SELECT show_chunks('parts');
```

|show_chunks|
|--|
|_timescaledb_internal._hyper_8_83_chunk|
|_timescaledb_internal._hyper_8_84_chunk|
|_timescaledb_internal._hyper_8_85_chunk|
|_timescaledb_internal._hyper_8_86_chunk|
|_timescaledb_internal._hyper_8_87_chunk|
|_timescaledb_internal._hyper_8_88_chunk|
|_timescaledb_internal._hyper_8_89_chunk|
|_timescaledb_internal._hyper_8_90_chunk|
|_timescaledb_internal._hyper_8_91_chunk|
|_timescaledb_internal._hyper_8_92_chunk|
|_timescaledb_internal._hyper_8_93_chunk|
|_timescaledb_internal._hyper_8_94_chunk|
|_timescaledb_internal._hyper_8_95_chunk|
|_timescaledb_internal._hyper_8_96_chunk|
|_timescaledb_internal._hyper_8_97_chunk|
|_timescaledb_internal._hyper_8_98_chunk|
|_timescaledb_internal._hyper_8_99_chunk|

Check the chunks of `parts_old`. This is ok.
```
SELECT show_chunks('parts_old');
```
```
table "parts_old" is not a hypertable
```

Now if I want to drop `parts_old`  I get this error.
```
drop table parts_old;
```

```
ERROR: ERROR: cannot delete table parts_old because other objects depend on it
DETAIL: Default value for column id of parts table depends on sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_83_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_84_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_85_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_86_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_87_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_88_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_89_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_90_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_91_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_92_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_93_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_94_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_95_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_96_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_97_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_98_chunk depends on the sequence parts_id_seq
The default value for column id of table _timescaledb_internal._hyper_8_99_chunk depends on the sequence parts_id_seq
HINT: Use DROP ... CASCADE to also delete the dependent objects.
```

The problem seems to stem from using a sequence as a default value in the table.

```
CREATE TABLE public.parts_old
(
    id integer NOT NULL DEFAULT nextval('parts_id_seq'::regclass),
   ...
);
```

Now if I try to remove the default
```
alter table parts_old alter column id drop default;
```

I still get the same error when trying to drop the table.

This can be replicated as follows:
```
create table test_old(id serial, ts timestamptz, data text);
create table test (like test_old including defaults including constraints);
select create_hypertable('test', 'ts');
drop table test_old;
```

I realize having a serial in timeseries is unusual and likely an edge case. However this should at least be noted in the documentation and even warn/prevent the creation on hypertables.

**Comment by svenklemm** [comment]
This is the expected behaviour and is not really related to your usage of hypertables because you get the exact same error if you leave out the create_hypertable command. You can work around this by creating the sequence explicitly before creating the test_old table so dropping test_old will not try to drop the sequence as well.
```
dev=# create table test_old(id serial, ts timestamptz, data text);
CREATE TABLE
Time: 18.084 ms
dev=# create table test (like test_old including defaults including constraints);
CREATE TABLE
Time: 21.272 ms
dev=# drop table test_old;
ERROR:  2BP01: cannot drop table test_old because other objects depend on it
DETAIL:  default value for column id of table test depends on sequence test_old_id_seq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
LOCATION:  reportDependentObjects, dependency.c:1188
Time: 2.056 ms
```
