### ISSUE TITLE
The cagg_watermark() function parameter should be using the materialization_id not the hypertable_id.

### ISSUE THREAD

**Issue by dcalde** [timescale/timescaledb#1971]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version: 12.2
 - TimescaleDB version: 1.7.0
 - Installation method: AWS AMI

**Describe the bug**
The `cagg_watermark()` function parameter should be using the materialization_id not the hypertable_id.

If multiple caggs are created against the same hypertable, the view should decided whether to query the hypertable vs the materialized tables based on the completed_threshold of the particular cagg, however it uses the completed_threshold of the _first_ created cagg against this hypertable.

TS essentially generates views for caggs like this:
```
CREATE VIEW tag_stats_5min(sensor_id, time_bucket, avg) AS
  SELECT _materialized_hypertable_42.sensor_id,
         _materialized_hypertable_42.time_bucket,
         _timescaledb_internal.finalize_agg('avg(numeric)'::text, NULL::name, NULL::name,
                                            '{{pg_catalog,numeric}}'::name[], _materialized_hypertable_42.agg_4_4,
                                            NULL::numeric)
  FROM _timescaledb_internal._materialized_hypertable_42
  WHERE (_materialized_hypertable_42.time_bucket <
         COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(11)),
                  '-infinity'::timestamp WITH TIME ZONE))
  GROUP BY _materialized_hypertable_42.sensor_id, _materialized_hypertable_42.time_bucket
  
  UNION ALL
  
  SELECT sensor_id, time_bucket('00:05:00'::interval, ts), avg(value)
  FROM my_hypertable
  WHERE (ts >= COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(11)),
                                  '-infinity'::timestamp WITH TIME ZONE))
  GROUP BY kucpi.c1, (time_bucket('00:05:00'::interval, kucpi.c2_utc));
```
The `cagg_watermark(hypertable_id)` function provides the timestamp threshold before or after which the either the materialized views or the raw table get queried. However different caggs are configured differently and as such have different threshold apply to them, yet this implementation merely return the threshold of the first cagg created.
```
CREATE FUNCTION cagg_watermark(hypertable_id oid) RETURNS bigint
  STABLE STRICT LANGUAGE SQL
AS $$
  SELECT watermark FROM _timescaledb_catalog.continuous_agg cagg
    LEFT JOIN _timescaledb_catalog.continuous_aggs_completed_threshold completed
      ON completed.materialization_id = cagg.mat_hypertable_id
  WHERE cagg.raw_hypertable_id = $1;
  $$;
```
If multiple cagg exist, the SELECT inside cagg_watermark returns multiple records but `RETURNS bigint` implicitely limits this to the first record.

I discovered this because I had created a cagg with a time_bucket of 365 days. I then created a cagg with a time_bucket of 5min. However querying the second cagg for any recent data, never fetched the data from the materialized views, but always the raw data. This is because cagg_watermark always returned 2019-12-31 as this is the correct completed_threshold of the first created cagg.

**Expected behavior**

the generated cagg view should choose the threshold based onte completed_threshold of the cagg itself, not another cagg.

**Comment by svenklemm** [comment]
This already fixed in 1.7.1. 

https://github.com/timescale/timescaledb/pull/1869
