### ISSUE TITLE
Timescale RPM package conflicts with lower version

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#1973]
**Relevant system information:**
 - OS: Centos 7.5
 - PostgreSQL version (output of `postgres --version`): 10.9 AND 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1 AND 1.7.1
 - Installation method: YUM

**Describe the bug**
We are upgrading Timescale and Postgresql to newer versions. However for normal upgrade process (upgrade postgres -> ingest data, etc) this would mean installing both packages at the same time. However despite packages having different names they for some reason refer to same location. THAT IS BAD. Packages should not do that as this leads to errors like below:

```
Transaction check error:
  file /usr/lib64/timescaledb/timescaledb.control from install of timescaledb-postgresql-12-1.7.1-0.el7.x86_64 conflicts with file from package timescaledb-postgresql-10-1.6.1-0.el7.x86_64
  file /usr/lib64/timescaledb/timescaledb.so from install of timescaledb-postgresql-12-1.7.1-0.el7.x86_64 conflicts with file from package timescaledb-postgresql-10-1.6.1-0.el7.x86_64
```

Packages should EITHER use different directories (i.e. `/usr/lib64/timescaledb-%{version}/`) OR have the same name (OR use `Replaces:` of rpmspec, so that one will DELETE another one). I am pretty sure it should be first one otherwise there is no way to run two version with two postgresql installations.

**To Reproduce**
1. Install Postgresql 10 + timescaledb10-1.6.x
2. Try to install Postgresql 12 + timescaledb12-1.7.x on same box
3. See error

**Expected behavior**
Multiple Postgresql versions with timescale extensions installed for them can be installed (as intended by standards)

**Actual behavior**
Failure.

**Comment by svenklemm** [comment]
Will be fixed for any subsequent releases. I've rebuilt 2.0.0-rc2 with the fix.

**Comment by akamensky** [comment]
@svenklemm it is not fixed, exact same issue exists in all releases of 2.x. Conflicts will be all over the place there.

**Comment by akamensky** [comment]
@svenklemm In version 2 it even fails to update within same version... WTF...

```

**Comment by svenklemm** [comment]
You need to be more specific than that i just tested upgrade 2.0.1 -> 2.1.0 -> 2.1.1 and i got no errors.
