### ISSUE TITLE
Query fails on compressed hypertable with: "PlaceHolderVar found where not expected""

### ISSUE THREAD

**Issue by darko408** [timescale/timescaledb#1981]
I'm using a Docker container on Linux RHEL 7.6, with TimescaleDb 1.7.1 and Postgres 11.8.
Have issue with the following query:

SELECT
        from_ts,
        to_ts,
        AVG(pkt_loss) AS pkt_loss_avg,
        AVG(rtt_avg) AS rtt_avg
    FROM
    (
        SELECT
            ts_bucket::timestamp AS from_ts,
            lead(ts_bucket::timestamp) over (partition by 1 ORDER BY ts_bucket::timestamp)::timestamp AS to_ts
        FROM
        REGEXP_SPLIT_TO_TABLE
        (
            '2019-03-21 01:00:00 | 2019-03-21 13:00:00 | 2019-03-22 01:00:00 | 2019-03-22 13:00:00 | 2019-03-23 01:00:00 | 2019-03-23 13:00:00', E'\\|'
        ) ts_bucket
    ) ts_bucket
    CROSS JOIN network n
    LEFT JOIN
    (
        SELECT
            d.network_id,
            CASE WHEN p.pkt_rx = 0 THEN 1 ELSE 0 END AS pkt_loss,
            p.rtt_avg,
            p.insert_ts
        FROM device d
        INNER JOIN ping p ON p.device_id = d.device_id
        WHERE d.network_id = 240
    ) data
    ON data.network_id = n.network_id
    AND data.insert_ts BETWEEN from_ts AND to_ts
    WHERE to_ts IS NOT NULL
    GROUP BY from_ts, to_ts
    ORDER BY from_ts;

The query is from some "legacy" code, and while it looks like it could benefit from some simplifications, it's a legitimate query that actually works with an uncompressed hypertable (see details further below). The issue seems very circumstantial, and disappears with some minor changes - like dropping the join on "network" table, or just using a raw "pkt_rx" value instead or derived "pkt_loss".

The following are steps to reproduce the issue. First, create the required tables (2 plain, 1 hypertable), according to the attached SQL file:

[create_test_tables.txt](https://github.com/timescale/timescaledb/files/4750141/create_test_tables.txt)

Then load data into those created tables from the corresponding attached CSV data files:

[network_test_data.txt](https://github.com/timescale/timescaledb/files/4750148/network_test_data.txt)
[device_test_data.txt](https://github.com/timescale/timescaledb/files/4750147/device_test_data.txt)
[ping_test_data.txt]
(https://github.com/timescale/timescaledb/files/4750149/ping_test_data.txt)

Now if the query above is performed while "ping" table is still uncompressed, one should get:

       from_ts       |        to_ts        |      pkt_loss_avg      |     rtt_avg      
---------------------+---------------------+------------------------+------------------
 2019-03-21 01:00:00 | 2019-03-21 13:00:00 | 0.00000000000000000000 | 127.636191050211
 2019-03-21 13:00:00 | 2019-03-22 01:00:00 |                        |                 
 2019-03-22 01:00:00 | 2019-03-22 13:00:00 | 0.00000000000000000000 | 94.8933335622152
 2019-03-22 13:00:00 | 2019-03-23 01:00:00 |                        |                 
 2019-03-23 01:00:00 | 2019-03-23 13:00:00 |                        |                 
(5 rows)

This is the corresponding execution plan:

Sort  (cost=33422.38..33422.88 rows=200 width=56) (actual rows=5 loops=1)
   Sort Key: ts_bucket.from_ts
   Sort Method: quicksort  Memory: 25kB
   ->  HashAggregate  (cost=33411.74..33414.74 rows=200 width=56) (actual rows=5 loops=1)
         Group Key: ts_bucket.from_ts, ts_bucket.to_ts
         ->  Hash Left Join  (cost=80.97..20775.24 rows=1263650 width=28) (actual rows=25 loops=1)
               Hash Cond: (n.network_id = d.network_id)
               Join Filter: ((p.insert_ts >= ts_bucket.from_ts) AND (p.insert_ts <= ts_bucket.to_ts))
               Rows Removed by Join Filter: 83
               ->  Nested Loop  (cost=64.83..15925.64 rows=1263650 width=20) (actual rows=10 loops=1)
                     ->  Seq Scan on network n  (cost=0.00..22.70 rows=1270 width=4) (actual rows=2 loops=1)
tual rows=5 loops=2) ->  Materialize  (cost=64.83..109.81 rows=995 width=16) (ac--More-- 
                           ->  Subquery Scan on ts_bucket  (cost=64.83..104.83 rows=995 width=16) (actual rows=5 loops=1)
                                 Filter: (ts_bucket.to_ts IS NOT NULL)
                                 Rows Removed by Filter: 1
                                 ->  WindowAgg  (cost=64.83..94.83 rows=1000 width=20) (actual rows=6 loops=1)
                                       ->  Sort  (cost=64.83..67.33 rows=1000 width=44) (actual rows=6 loops=1)
                                             Sort Key: ((ts_bucket_1.ts_bucket)::timestamp without time zone)
                                             Sort Method: quicksort  Memory: 25kB
                                             ->  Function Scan on regexp_split_to_table ts_bucket_1  (cost=0.00..15.00 rows=1000 width=44) (actual rows=6 loops=1)
               ->  Hash  (cost=16.12..16.12 rows=1 width=24) (actual rows=20 loops=1)
                     Buckets: 1024  Batches: 1  Memory Usage: 10kB
                     ->  Hash Join  (cost=13.26..16.12 rows=1 width=24) (actual rows=20 loops=1)
                           Hash Cond: (p.device_id = d.device_id)
l rows=40 loops=1)         ->  Append  (cost=0.00..2.70 rows=40 width=24) (actua--More-- 
                                 ->  Seq Scan on _hyper_1_1_chunk p  (cost=0.00..1.25 rows=20 width=24) (actual rows=20 loops=1)
                                 ->  Seq Scan on _hyper_1_2_chunk p_1  (cost=0.00..1.25 rows=20 width=24) (actual rows=20 loops=1)
                           ->  Hash  (cost=13.25..13.25 rows=1 width=8) (actual rows=5 loops=1)
                                 Buckets: 1024  Batches: 1  Memory Usage: 9kB
                                 ->  Seq Scan on device d  (cost=0.00..13.25 rows=1 width=8) (actual rows=5 loops=1)
                                       Filter: (network_id = 240)
                                       Rows Removed by Filter: 5

However,  let's compress the "ping" table like this:

ALTER TABLE ping SET (timescaledb.compress, timescaledb.compress_orderby = 'device_id, insert_ts DESC');

Now ensure that chunks are actually compressed:

DO $$
DECLARE
    temprow record;
BEGIN
FOR temprow IN
    SELECT chunk_name FROM timescaledb_information.compressed_chunk_stats temprow WHERE hypertable_name = 'ping'::regclass and compression_status = 'Uncompressed'
LOOP
    PERFORM compress_chunk(temprow.chunk_name);
END LOOP;
END $$;

But if we run that query again, now we get:

ERROR:  PlaceHolderVar found where not expected

**Comment by mfreed** [comment]
Thanks for the report, @darko408 !
