### ISSUE TITLE
Can we have something like Apache MADlib akka Big Data Machine Learning in SQL

### ISSUE THREAD

**Issue by sirinath** [timescale/timescaledb#2]
Is it possible to have functionality where you can directly do machine learning and Big Data, on changing TS data, in TSDB?

**Comment by cevian** [comment]
MADlib comes with a postgres extension. So you should be able to run it along-side TimescaleDB and it should interact with hypertables in the same way as regular tables. Although I am not sure that it contains any time-series specific machine learning algorithms. In general any tools that have a PostgresSQL connector should work with us. Unfortunately, we have not tested TimescaleDB with MADlib  ourselves yet.

**Comment by mfreed** [comment]
+sirinath Please let us know if you ever try running/testing MADlib on TimescaleDB.

**Comment by mfreed** [comment]
Closing out this question...
