### ISSUE TITLE
Unable to install any version older than 1.7.1 using ppa/apt

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb#2008]
I'm trying to replicate a bug I encountered going from pg11->pg12 which involves a history of timescale minor upgrades. But I'm completely unable to install TimescaleDB 1.6.1 in the first place. It must be pulling some 1.7.1 dependencies as you will see.

1. setup an Ubuntu 18.04 environment without any traces of postgres or timescaledb
2. run the following steps

```
echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c -s)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update

sudo add-apt-repository ppa:timescale/timescaledb-ppa -y

sudo apt install timescaledb-1.6.1-postgresql-11

sudo timescaledb-tune -yes
sudo service postgresql restart
sudo -u postgres psql -qxc "CREATE EXTENSION IF NOT EXISTS timescaledb;"
```

This will end up in an error:
`ERROR:  extension "timescaledb" has no installation script nor update path for version "1.7.1"`

At no point in time did I specify anything about 1.7.1, however I did notice the following packages getting pulled:

```
timescaledb-tools amd64 0.8.1~ubuntu18.04
timescaledb-loader-postgresql-11 amd64 1.7.1~ubuntu18.04
```

**Comment by jflambert** [comment]
Hmm I was able to workaround this problem like so

`sudo -u postgres psql -qxc "CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '1.6.1';"`

You guys can probably close this issue if this behaviour was expected.

**Comment by RobAtticus** [comment]
Hi @jflambert , yes that is the expected behavior. All older versions depend on the latest `loader` package, which defaults to the latest version for `CREATE EXTENSION` but is capable of loading older ones. So you have to specify when its not the latest.

I believe we have an issue open for updating our docs to make note of this

**Comment by RobAtticus** [comment]
Yep, here it is:
https://github.com/timescale/docs.timescale.com-content/issues/415

**Comment by svenklemm** [comment]
Instructions how to build specific version will be in docs after next docs update.
