### ISSUE TITLE
View optimisation question

### ISSUE THREAD

**Issue by markdchurchill** [timescale/timescaledb#2057]
So this is a combination of I assume a popular use-case, a pain in the butt piece of optimisation, and a sanity check. This isn't necessarily timescaledb specific, but I suspect these sort of cases are more likely to be hit with timescaledb.

Postgres 12.3, TS 1.7.1, docker: timescale/timescaledb:latest-pg12 @sha256:62850f3b364fcc0696b446a1d83bb68f891bc262eb721728533231b17fad93aa

I have a measurements table (time, labelid, value), with appropriate indexes and ~100M rows.

A common query I have is "time since last event". This is done with:
```
select 
  time, 
  time - lag(time) over (order by time)
from measurements join labelmetadata meta...
where meta.name = 'eg.conveyor.active'
and time between x and y
```
This is relatively performant. The most immediate problem is that this is structurally different from:
```
with cte_or_view as (
  select 
     time, 
     time - lag(time) over (order by time)
   from measurements join labelmetadata meta...
   where meta.name = 'eg.conveyor.active'
)
select * from cte_or_view where time between x and y
```
Building views to layer up interpretation is pretty desirable - in my case for exposing the information to grafana and reporting. Without being able to limit the size of the window, timescale plans to scan every chunk. Even adding a `over (order by time range 'z minutes' preceding') doesn't limit the scanned chunks, meaning this query takes minutes.

My current workaround is to use a table-returning-function to preserve the original semantics, which has decent performance, but seems quite clunky:
```
create function myfakeview(x timestamp, y timestamp)
   returns table(t timestamp, i interval) as
$body$
   select 
      time, 
      time - lag(time) over (order by time)
   from measurements join labelmetadata meta...
   where meta.name = 'eg.conveyor.active'
   and time between $1 and $2
$body$ language sql
```

I feel that 'the database' could be smarter about scanning to satisfy windowing functions in my case. Either an ordered scan until the window is satisfied, or respecting how a window range limitation limits the potential source rows. (Likely a postgres issue)

I could potentially find use of a 'hard' time window for queries - I have no idea how this would be shoehorned into psql, but essentially punching any hyper-dimension where clause down to the underlying hypertables with no respect for 'correct' query semantics - a pure performance-only approach to limit the window of considered source rows.

I am almost certain that I'm probably missing something obvious - this seems to be a super common use case, and my setup is doing a poor job.

**Comment by svenklemm** [comment]
Hmm for a view your query constraints should be passed down. But unless you are using PostgreSQL 12 CTEs are an optimization barrier and constraints will not be passed down. Which postgres version are you using?

**Comment by markdchurchill** [comment]
I'm on dockerised pg12.

I suspect the underlying issue is around that `select t, lag(t) where condition` only needs to consider source rows where condition is met, however `(select t,lag(t)) where condition` needs to consider rows that don't meet the condition.

To find that lag(t), which to be fair could be years in the past, a full scan is being performed, when it could perform an ordered scan and break early, or accept that between x and y with range z preceding will limit source rows to (x-z to y).

**Comment by svenklemm** [comment]
Queries have an order in which they are executed WHERE clause -> GROUP BY clause -> WINDOW functions, so whatever you filter in your where clause will never be seen by later steps, but if you move the window functions into a subquery and do the WHERE clause in the outer query you can circumvent that. There are alternative queries you can do to get the answer to your question which might perform better 
namely correlated subquery or lateral joins

```
select 
  time,
  time - (SELECT time FROM measurements m2 WHERE m2.time < m1.time ORDER BY time DESC LIMIT 1)  
from measurements m join labelmetadata meta...
where meta.name = 'eg.conveyor.active'
and time between x and y
```
You could pass in y into the correlated subquery to optimize the query further

**Comment by markdchurchill** [comment]
I hadn't considered the correlated subquery style, but it doesn't seem to help the planner out much, even with some additional restrictions. I've also tried a few different ways of specifying the windowing and limiting the frame, based on my knowledge of the data. The underlying problem I think still being that selection from a CTE/view with a window limited to eg `'15 min' preceding` is not being optimised any more than `unbounded preceding`.

Not being completely familiar with the timescale architecture - is this timescale being unaware of the potential restriction it could apply to the time dimension before it "passes the query" through to the underlying chunks, or is this a general postgres issue where it doesn't notice that a limited window frame can only expand the source rows under consideration a fixed amount?

Looks like I will have to pass these time range restrictions into the queries directly - which unfortunately prevents me from using views - and slightly complicates things with Grafana.

**Comment by svenklemm** [comment]
Hmm i guess i need some more concrete examples for what types of queries you are looking for but your first and 2nd query should result in the same execution plan. What is the EXPLAIN output for those queries?

**Comment by markdchurchill** [comment]
This is probably what I should have started with, but thought it was most likely me screwing something up:

```
create table testtable (
    time timestamp primary key,
    dummy double precision
);

select create_hypertable('testtable', 'time');

insert into testtable
select generate_series('2018-01-01', '2019-01-01', '5 minutes'::interval) as time, random() as dummy;

-- Query 1: A trivial indexed selection
explain (format json) with x as (select time, lag(time) over (order by time) from testtable where time between '2018-05-01' and '2018-05-15') select * from x;

-- Query2: A selection where lag(time) could, theoretically, be in the 1970s
explain (format json) with x as (select time, lag(time) over (order by time) from testtable) select * from x where time between '2018-05-01' and '2018-05-15';

-- Query 3: A selection where lag(time) could, at most, be '2018-05-01' - '30 minutes'
explain (format json) with x as (select time, lag(time) over (order by time range '30 minutes' preceding) from testtable) select * from x where time between '2018-05-01' and '2018-05-15';
```
It looks like there ends up being ~50 chunks of data.

Query 1 performs as expected. It considers a handful of chunks (18, 19, 20) that may contain the requested data.

Query 2 realises that lag(time) could be outside the selection, and it could be any amount of time previous. It (probably) needs to scan chunks 1 - 20, but it actually scans all 50.

Query 3 introduces what we know of the data (the lag reading will be within a few minutes), and this should limit the required chunks to ~17 - 20. Again, it scans all 50.

Now, doing this without using a hypertable in vanilla postgres is a bit hard for me to analyze - just a single index scan as expected. All queries perform an index scan - query 1 expects ~500 rows, the other querys expect the full number. It does take much longer to perform the explain (analyze) - perhaps indicating that this is an underlying postgres issue?

**Comment by svenklemm** [comment]
Oh i can see the problem now, the WHERE clause in your 2nd and 3rd query cannot be pushed down because it would alter the resultset. The in_range operator you mentioned is already defined by postgres but this operator allows you to use range in the OVER clause but doesnt have any interaction with the where clause.

**Comment by markdchurchill** [comment]
Yup, and unfortunately this is a really common scenario - a view with complex processing, where a small range is a reasonable thing to ask - but having to compute the entire result set before it is limited isn't feasible.

Query 2 could be optimised by an ordered scan. Query 3 could be optimised by recognising that the range limit on the window frame adds that amount to what needs to be scanned.

**Comment by svenklemm** [comment]
Yes while there are a few different ways to get those queries performant unfortunately none of them will work with a view.

**Comment by markdchurchill** [comment]
This is something that underlying optimisation is capable of doing better. Is this a timescaledb issue, or should I push upstream to postgres and their archaic mailing list setup? :P

**Comment by svenklemm** [comment]
Its a general issue and postgres is affected as well its just not as obvious from the plan unless you have a partitioned table. But an optimization for this type of query could either be implemented in postgres or in timescaledb.

**Comment by markdchurchill** [comment]
Alright, thanks for the feedback. I'll look into raising this on the postgres mailing list when I'm next back home.
