### ISSUE TITLE
running upgrade sql-scripts

### ISSUE THREAD

**Issue by beremour** [timescale/timescaledb#2070]
**Relevant system information:**
 - OS: Oracle Linux Server release 7.8
 - PostgreSQL version 11.8
 - TimescaleDB version 1.7.2
 - Installation method: yum upgrade

**Just a question**
Do upgrade scripts such as "timescaledb--1.7.1--1.7.2.sql" are run automatically during "yum upgrade" procedure ?

**Comment by svenklemm** [comment]
They are not, you need to run `ALTER EXTENSION timescaledb UPDATE;` in every database you use timescaledb in.
You can check the active version with `select extname, extversion from pg_extension where extname='timescaledb';`

**Comment by beremour** [comment]
ALTER EXTENSION timescaledb UPDATE; is done of cause and \dx command gives correct 1.7.2. I've just worried about should I run sql upgrade scripts manually or not.

**Comment by svenklemm** [comment]
No you should not, they are run as part of `ALTER EXTENSION timescaledb UPDATE;`

**Comment by beremour** [comment]
thank you very much.
