### ISSUE TITLE
Install fails on Windows 10

### ISSUE THREAD

**Issue by charlesbaynham** [timescale/timescaledb#2076]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7
 - Installation method: setup.exe

**Describe the bug**
`setup.exe` fails with error message

```
2020/07/10 20:20:18 ERROR: could not copy file 'timescaledb-1.7.1.dll': open C:/ProgramData/Strawberry/c/lib/postgresql/timescaledb-1.7.1.dll: The system cannot find the path specified.
```

**To Reproduce**
1. Attempt to install timescaledb on Windows 10

![image](https://user-images.githubusercontent.com/4397637/87190706-ddf24780-c2ea-11ea-80e9-8657b80eac55.png)

**Additional context**

You can hack around this problem by creating the directory in the error message and putting the .dll file there manually, then doing the same for the .control file.

**Comment by charlesbaynham** [comment]
Actually the hack doesn't work: postgres then fails to start with error 

```
>pg_ctl -D "C:\Program Files\PostgreSQL\12\data" start
waiting for server to start....2020-07-10 20:25:06.494 BST [12116] FATAL:  could not access file "timescaledb": No such file or directory
2020-07-10 20:25:06.496 BST [12116] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```

**Comment by k-rus** [comment]
It sounds that your issue is similar to https://github.com/timescale/timescaledb/issues/1302

TimescaleDB installer (`Setup.exe`) calls `pg_config` to find the location of PostgreSQL installation. Can you call `pg_config` from the folder with TimescaleDB installer? What does it return? Does it return a path related to `Strawberry`? If so, can you provide the location of `pg_config` in the targeted PostgreSQL to the installer?

**Comment by charlesbaynham** [comment]
Output below:

```
$ pg_config
BINDIR = C:/PROGRA~3/STRAWB~1/c/bin
DOCDIR = C:/ProgramData/Strawberry/c/share/doc/postgresql
HTMLDIR = C:/ProgramData/Strawberry/c/share/doc/postgresql
INCLUDEDIR = C:/PROGRA~3/STRAWB~1/c/include
PKGINCLUDEDIR = C:/PROGRA~3/STRAWB~1/c/include/POSTGR~1
INCLUDEDIR-SERVER = C:/PROGRA~3/STRAWB~1/c/include/POSTGR~1/server
LIBDIR = C:/PROGRA~3/STRAWB~1/c/lib
PKGLIBDIR = C:/ProgramData/Strawberry/c/lib/postgresql
LOCALEDIR = C:/ProgramData/Strawberry/c/share/locale
MANDIR = C:/ProgramData/Strawberry/c/share/man
SHAREDIR = C:/PROGRA~3/STRAWB~1/c/share/POSTGR~1
SYSCONFDIR = C:/ProgramData/Strawberry/c/etc/postgresql
PGXS = C:/ProgramData/Strawberry/c/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--host=x86_64-w64-mingw32' '--build=x86_64-w64-mingw32' '--prefix=/z/extlib/_2019Q2__' '--with-zlib' '--with-ldap' '--with-openssl' '--with-includes=/z/extlib/_2019Q2__/include' '--with-libraries=/z/extlib/_2019Q2__/lib' 'build_alias=x86_64-w64-mingw32' 'host_alias=x86_64-w64-mingw32' 'PKG_CONFIG=/bin/pkg-config' 'PKG_CONFIG_PATH=/z/extlib/_2019Q2__/lib/pkgconfig/'
CC = x86_64-w64-mingw32-gcc
CPPFLAGS = -I./src/include/port/win32 -DEXEC_BACKEND -I/z/extlib/_2019Q2__/include -I../../src/include/port/win32 -DWIN32_STACK_RLIMIT=4194304 -DBUILDING_DLL
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2
CFLAGS_SL =
LDFLAGS = -Wl,--allow-multiple-definition -Wl,--disable-auto-import -L/z/extlib/_2019Q2__/lib -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lssleay32 -leay32 -lz -lws2_32 -lm  -lws2_32
VERSION = PostgreSQL 11.3
```

**Comment by charlesbaynham** [comment]
pg_config apparantly lives in

```
$ which pg_config
/c/ProgramData/Strawberry/c/bin/pg_config
```

This is a clean install of postgresql from their website installer

**Comment by charlesbaynham** [comment]
Searching for `postgres` in Strawberry, I find directories at `C:\programdata\Strawberry\c\include\postgresql`, `C:\programdata\Strawberry\c\share\postgresql` and `C:\programdata\Strawberry\licenses\postgresql`

**Comment by charlesbaynham** [comment]
so nothing at `...\c\lib\postgresql` which I think causes the error

**Comment by k-rus** [comment]
@charlesbaynham I can see in [an early comment](https://github.com/timescale/timescaledb/issues/2076#issuecomment-657404458) that you have folder `C:\Program Files\PostgreSQL\12`, which contains proper installation of PG. This is where official PG installer from EDB installs PostgreSQL. I believe Strawberry is a product, which contains PG internally, and its `pg_config` is in the path.
Can you clarify what is your main installation of PostgreSQL, where you want to install TimescaleDB? I would expect it is the one in `C:\Program Files\PostgreSQL\12`, thus you will need to provide path to `pg_config`, which is supposed to be in ``C:\Program Files\PostgreSQL\12\bin`.

**Comment by k-rus** [comment]
I will clarify that it seems to me that you have at least two installations of PG on your machine. This creates your issue and the confusion.

**Comment by charlesbaynham** [comment]
Thanks @k-rus , that seemed to be the problem. I've reordered my PATH so that the proper postgres installation appears first and the installer then completes successfully.

**Comment by charlesbaynham** [comment]
Seems like Strawberry Perl had installed postgres for some reason and, as you pointed out, this was being picked up by the installer.

**Comment by k-rus** [comment]
Great to hear that it is fixed! Can this issue be closed?

**Comment by charlesbaynham** [comment]
Thanks for the help!
