### ISSUE TITLE
DISTINCT ON giving wrong result

### ISSUE THREAD

**Issue by andness** [timescale/timescaledb#2079]
**Relevant system information:**
 - OS: Linux Debian 4.9.168
 - PostgreSQL version: 11.5 (Debian 11.5-1.pgdg90+1)
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: apt-install

**Describe the bug**
I'm using a DISTINCT ON query to get the most recent value for each device according to time, but I'm getting incorrect query results. The table I'm querying looks like this:

```
create table collar_owner (
  time timestamptz not null,
  collar_id text not null,
  owner_number text,
  primary key(time, collar_id)
);
select create_hypertable(
               'collar_owner', 'time',
               create_default_indexes => false);
create index collar_owner_collar_time on collar_owner(collar_id, time desc);
```

For one particular collar_id, the entries in collar_owner are:
```
select * from collar_owner where collar_id = '36112';
           time            | collar_id | owner_number
---------------------------+-----------+--------------
 2019-06-19 10:41:13.08+00 | 36112     | 29
 2019-06-07 12:05:15+00    | 36112     | -1
```
So what I want is to get the most recent owner_number which is 29.

But when I run my DISTINCT ON query:
```
select distinct on (collar_id)
    '2020-07-12' as time,
    collar_id,
    owner_number
from collar_owner
where time < '2020-07-13' and collar_id = '36112'
order by collar_id, time desc
```

I get this:

```
    time    | collar_id | owner_number
------------+-----------+--------------
 2020-07-12 | 36112     | -1
```

If I copy the entire table to a non-hypertable using `insert into collar_owner2 select * from collar_owner` and then re-run the query against the new table, I get the correct result:

```
select distinct on (collar_id)
    '2020-07-12' as time,
    collar_id,
    owner_number
from collar_owner2
where time < '2020-07-13' and collar_id = '36112'
order by collar_id, time desc
```

I also noticed that if I drop the time column and query the hypertable version I get the right result:

```
select distinct on (collar_id)    
    collar_id,
    owner_number
from collar_owner
where time < '2020-07-13' and collar_id = '36112'
order by collar_id, time desc
```

Gives:

```
 collar_id | owner_number
-----------+--------------
 36112     | 29
```

**Comment by svenklemm** [comment]
Hmm I cant reproduce from the example you gave
```
dist=# select distinct on (collar_id)
dist-#     '2020-07-12' as time,
dist-#     collar_id,
dist-#     owner_number
dist-# from collar_owner
dist-# where time < '2020-07-13' and collar_id = '36112'
dist-# order by collar_id, time desc;
    time    | collar_id | owner_number
------------+-----------+--------------
 2020-07-12 | 36112     | 29
(1 row)

Time: 1.415 ms
dist=# select * from collar_owner;
           time            | collar_id | owner_number
---------------------------+-----------+--------------
 2019-06-19 12:41:13.08+02 | 36112     | 29
 2019-06-07 14:05:15+02    | 36112     | -1
(2 rows)

Time: 0.843 ms
```

**Comment by svenklemm** [comment]
@andness Not sure if this is the source for the behaviour in your queries but if you alias column of the result set to names already present as column names the result will not be ordered by your aliased expression but by the column

**Comment by andness** [comment]
Oops, my mistake, now I feel a little bit silly. The difference between the hyperatable and non-hypertable versions is probably just to the fact that the copied table gets inserted in order so the result just happens to come out right. Sorry for the noise, closing.
