### ISSUE TITLE
Background Worker Scheduler dies on startup, no other jobs get scheduled.

### ISSUE THREAD

**Issue by Sarke** [timescale/timescaledb#2086]
**Relevant system information:**
 - OS: Alpine 9.3.0
 - PostgreSQL version (output of `postgres --version`): PostgreSQL 11.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: using Docker

**Describe the bug**
Background jobs fail to run.

**To Reproduce**
Somehow a compress chunks job got deleted from `_timescaledb_config.bgw_policy_compress_chunks` but existed in `_timescaledb_config.bgw_job`.  This job was for an older hypertable that had been removed, so I am unsure of why it was left in this inconsistent state.

This can be done manually to reproduce.  Of note was that the job id was `1003`, which was the lowest of the listed jobs.

**Expected behavior**
One missing job should not disable the entire job system.

To be more resilient it should be able to try other jobs even though one is missing.

When running jobs in general, I usually run them in random order (when order is not important) so that if one is causing trouble, it will not hold up the other ones every time.

The Background Worker Scheduler should also be able to restart.

**Actual behavior**
One job, I assume because it was the lowest ID, failed on startup and killed the Background Worker Scheduler, so no other jobs would be scheduled or run.

**Logs**
```
2020-07-15 07:36:03.555 UTC [1] LOG:  database system is ready to accept connections
2020-07-15 07:36:03.557 UTC [27] LOG:  TimescaleDB background worker launcher connected to shared catalogs
2020-07-15 07:36:03.599 UTC [29] ERROR:  compress chunks policy for job with id "1003" not found
2020-07-15 07:36:03.601 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 29) exited with exit code 1
2020-07-15 07:36:03.604 UTC [30] LOG:  terminating TimescaleDB background job "Compress Chunks Background Job" due to administrator command
2020-07-15 07:36:03.607 UTC [30] FATAL:  terminating connection due to administrator command
2020-07-15 07:36:03.608 UTC [1] LOG:  background worker "Compress Chunks Background Job" (PID 30) exited with exit code 1
```

**Comment by mfreed** [comment]
Hi @Sarke there have been a bunch of changes to the background scheduler in 1.7.x.  Do you still see these issues in the latest (1.7.4)?  Thanks!

**Comment by Sarke** [comment]
I don't but I also don't have the conditions of the bug.  Try to delete a compress chunks policy manually and see if that makes the scheduler poop.

**Comment by mamcx** [comment]
This happens to me too and ALSO https://github.com/timescale/timescaledb/issues/733. 

If a delete the db, recreate it and instantly run the DDL scripts happens this, but if I wait/restart PG after creation and run the DDL happens "PANIC: stuck spinlock detected"

**Comment by NunoFilipeSantos** [comment]
@Sarke are you still observing this issue?

**Comment by NunoFilipeSantos** [comment]
Closing, feel free to reopen it again if you can reproduce it with our latest TimescaleDB 2.4.2 (PG 12 or PG13).
