### ISSUE TITLE
无法下载1.7.2

### ISSUE THREAD

**Issue by ghd258** [timescale/timescaledb#2099]
![QQ图片20200718103634](https://user-images.githubusercontent.com/4811375/87843000-49d44180-c8e3-11ea-8c55-fcd3cd92d8f8.jpg)

**Comment by k-rus** [comment]
Thank you for reporting! We will investigate what went wrong and upload Windows packages for 1.7.2.

**Comment by svenklemm** [comment]
Closing this since this should be resolved. Feel free to reopen if the issue is still relevant.
