### ISSUE TITLE
Divert reads away from data nodes

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2104]
When a node is unavailable, we should not only block new chunks from being created on it; we should also divert away reads from it. In other words, we should make sure the we set another "primary" data node for the chunks no the data node that is unavailable. The primary data node for a chunk is the foreign server referenced in the chunks foreign table.

**Comment by gregbacchus** [comment]
In a kubernetes setup, ideally there should be an operator that detects the loss of the node and automatically applies the cordon
