### ISSUE TITLE
`ERROR:  XX000: could not open relation with OID 0` when issuing `CREATE INDEX IF NOT EXISTS`

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/timescaledb#2112]
**Relevant system information:**
 - OS:Ubuntu 20.04 LTS
 - PostgreSQL version (output of `postgres --version`): PostgreSQL 12.3 (Ubuntu 12.3-1.pgdg20.04+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 1.7.2
 - Installation method: apt install

**Describe the bug**
When issuing a `CREATE INDEX IF NOT EXISTS` on a hypertable, a `ERROR:  XX000: could not open relation with OID 0` is raised.

**To Reproduce**
```sql
CREATE TABLE demo(inserted timestamptz not null);
CREATE UNIQUE INDEX IF NOT EXISTS demo_unique ON demo(inserted);
SELECT create_hypertable('demo', 'inserted');
CREATE UNIQUE INDEX IF NOT EXISTS demo_unique ON demo(inserted);
-- reconnect, to verify that the bug is not limited to the session that
-- created the table/index previously
\connect
CREATE UNIQUE INDEX IF NOT EXISTS demo_unique ON demo(inserted);
```

**Expected behavior**
A notice of that the index does not exist.

**Actual behavior**
A notice that the index does not exist, followed by an error:

```
CREATE TABLE
CREATE INDEX
 create_hypertable 
-------------------
 (1,public,demo,t)
(1 row)

psql:bug.sql:4: NOTICE:  relation "demo_unique" already exists, skipping
psql:bug.sql:4: ERROR:  could not open relation with OID 0
```

The error will cause the transaction to abort, or when using `psql --set ON_ERROR_STOP=1`, will
cause the script to stall at this point.

**Comment by svenklemm** [comment]
should be fixed by https://github.com/timescale/timescaledb/pull/2090, feel free to reopen if you can reproduce on master

**Comment by reutsharabani** [comment]
We ran into this in production today, we use the enterprise aws deployment. There is no option to upgrade (button is disabled) so I assume it will be resolved in next update? Thanks.
