### ISSUE TITLE
Add compression ratio to stats

### ISSUE THREAD

**Issue by bkief** [timescale/timescaledb#2124]
I'd like to see the compression ratio in `compressed_hypertable_stats`. I started on the code change, which should be modest. Any hesitation to taking the PR?

**Comment by gayyappan** [comment]
@bkief The compression ratio can be computed at query time.  Also, we are changing some of the view and function interfaces to work with the distributed/multi-node setup. This is probably not a good time for a PR that changes their definitions.

**Comment by erimatnor** [comment]
Closing this since it can be computed in the query.
