### ISSUE TITLE
Allow infinite refresh windows for continuous aggregates

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2129]
A manual refresh of a continuous aggregate using `refresh_continuous_aggregate` should allow using an infinite refresh window or a partly open-ended one in either direction. Note, however, that refreshing with an infinite  window relies on optimizations under-the-hood to make this a viable option: https://github.com/timescale/timescaledb/issues/2120

Infinite refresh windows are naturally expressed by passing a `NULL` as `window_start` and `window_end`. This translates internally to timestamps `-Infinity` and `+Infinity` (represented with `PG_INT64_MIN` and `PG_INT64_MAX` internally).

However, the internal code to materialize the continuous aggregate uses an SPI query that requires always specifying a start and end in the `WHERE ` clause. This should be changed so that there is no `WHERE` clause on time when both start and end are infinite, and use only one restriction on time when one is infinite.

**Comment by k-rus** [comment]
This depends on https://github.com/timescale/timescaledb/pull/2125, @erimatnor right?

**Comment by erimatnor** [comment]
> This depends on https://github.com/timescale/timescaledb/pull/2125, @erimatnor right?

Yes, although that issue is now closed. It is actually more generally about fixing various odd things with how we deal with time internally. Currently, our internal conversion functions don't check for infinite timestamps and fail instead.
