### ISSUE TITLE
drop_chunks fail with unexpected tuple lock status error

### ISSUE THREAD

**Issue by sezaru** [timescale/timescaledb#2140]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.2
 - Installation method: docker

**Describe the bug**
In my system, I have a "cron job" that will trigger some times per day and will run the following query in some tables:
`select drop_chunks(interval '#{interval}', '#{table_name}')`

Where `interval` and `table_name` are specified during runtime.

99% of the time this works great and the query is executed successfully.

But sometime it will fail with the following error:
`ERROR XX000 (internal_error) unexpected tuple lock status`

**To Reproduce**
I'm not so sure since it happens randomly, but at the same time, I have some suspicions.

My guess is that this is triggered if I'm running this query at the same time I'm writing some new data to the same table. Again, I'm not 100% sure but this error seems to happen more often when my system is loading and is heavily adding new data to these tables.

If that is the case, do I need to lock the table somehow to do the `drop_chunk` query safely? If that is the case, can I do it inside Postgres since it would be really hard to do that in a distributed environment?

**Comment by svenklemm** [comment]
Looks like this can happen when the tuple was deleted in a different sessions. Are you running multiple drop_chunks?

**Comment by sezaru** [comment]
You mean in parallel?

Yes, the drop_chunks queries can run in parallel if some cron jobs are triggered at the same time but only for different tables, it will never run drop_chunks for the same table at the same time.

**Comment by mkindahl** [comment]
Some quick investigations:
1. The error is printed inside `lock_result_ok_or_abort` when attempting to locate the dimension slice involved in the lookup.
2. The error is printed if the `lockresult` is `TM_WouldBlock` or some value not in `TM_Result` (uninitialized value?).
3. However, `TM_WouldBlock` can only be triggered if the wait policy is `LockWaitSkip`, and we are using `LockWaitBlock` everywhere (there is no mention of `LockWaitSkip` in the code).
4. Enumeration `LockWaitBlock` is first in the enumeration (hence zero), so `LockWaitSkip` could not be the result of a missing initialization of the wait policy.
5. Combining 2, 3, and 4 suggest that `lockresult` is uninitialized memory.

**Comment by mkindahl** [comment]
We have done a few changes to handling of locks in 1.7.3 and 1.7.4 (see #2261 and #2336) so not sure if this bug is still present. It would be good if we could verify that this bug is still present in 1.7.4.

**Comment by mkindahl** [comment]
Since we have made several fixes around tuple locking in 1.7.1 to 1.7.4 and there is no verification if this bug is still present in 1.7.4 I will close this bug. Please reopen if it turns out that it is still present in 1.7.4.
