### ISSUE TITLE
ERROR: operation not supported on hypertables that have compression enabled. How to fix the problem?

### ISSUE THREAD

**Issue by maksitop** [timescale/timescaledb#2145]
Hi!
PostgreSQL 11.6
TimescaleDB version 1.6.0

performing sql operation
ALTER TABLE trends ALTER COLUMN value_min TYPE DOUBLE PRECISION;
ALTER TABLE trends ALTER COLUMN value_min SET DEFAULT '0.0000';
ALTER TABLE trends ALTER COLUMN value_max SET DEFAULT '0.0000';
ALTER TABLE history ALTER COLUMN value TYPE DOUBLE PRECISION;
ALTER TABLE history ALTER COLUMN value SET DEFAULT '0.0000';  

I get an error
ERROR: operation not supported on hypertables that have compression enabled

SELECT count(*) 
FROM timescaledb_information.compressed_chunk_stats where compression_status like 'Uncompressed';
=156
SELECT count(*) 
FROM timescaledb_information.compressed_chunk_stats
=156

SELECT job_id, table_name
FROM _timescaledb_config.bgw_policy_compress_chunks p
INNER JOIN _timescaledb_catalog.hypertable h ON (h.id = p.hypertable_id);
=None

How to fix the problem?

**Comment by svenklemm** [comment]
alter table history set (timescaledb.compress=false);

**Comment by maksitop** [comment]
alter table history set (timescaledb.compress=false);  
-Ok

ALTER TABLE trends set (timescaledb.compress=false);
ERROR:  constraint trends_pkey requires column itemid to be a segment_by or order_by column for compression
HINT:  Only segment by and order by columns can be used in constraints on hypertables that are compressed.

**Comment by maksitop** [comment]
Updated to 1.7.2. Problem solved.
