### ISSUE TITLE
ERROR:  cannot execute an enterprise function with an invalid enterprise license

### ISSUE THREAD

**Issue by vitodsk** [timescale/timescaledb#2174]
Hello, I am trying to do the following:

SELECT add_drop_chunks_policy('apnea_cache', INTERVAL '90 days');

but I get the following error:
ERROR:  cannot execute an enterprise function with an invalid enterprise license

is that really an enterprise feature ? Seems one of the basic points for a time series db...

**Comment by k-rus** [comment]
What version of TimescaleDB do you use? You can also check in the docs if the function is enterprise in your version by selecting your version in the drop-down.

**Comment by k-rus** [comment]
cc @vitodsk

**Comment by vitodsk** [comment]
yes, well, I think the automated retention policy *is* an enterprice feature. That is what I was reading at least, do you have such info to confirm ?

**Comment by k-rus** [comment]
Automated retention policy, i.e., `add_drop_chunks_policy` is community since 1.7.0, see [the release notes](https://github.com/timescale/timescaledb/releases/tag/1.7.0)
