### ISSUE TITLE
Remove individual policy views in favor of unified policy view.

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb#2185]
Right now we have a couple of views (drop_chunk_policies, and reorder policies) in our information schema for tracking different types of policies.  The compression_settings and continuous_aggregates views may also make sense to be removed if they become redundant with the new policies view.

The documentation will also need to be updated where these views are referenced.

**Comment by erimatnor** [comment]
@WireBaron Is this done and can the issue be closed? Or, is this is open still to track documentation changes? (OTOH, don't we have separate issues for this in the docs repo?)
