### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by skovzhaw** [timescale/timescaledb#22]
Hey guys,

just thought of letting you know about your Docker instructions.

The first step for me was to pull the Docker image (https://github.com/timescale/timescaledb/#option-2---docker-hub). There is no information on how to run the docker image and what ports need to be open, and environmental parameters provided. I think the Readme should be updated.

Knowing Postgres, I opened 5432 port, and continued with your “getting started” installation guide:

• Setting up an empty database
• Creating a hypertable
• Creating an index
• Inserting data
• Querying data

All done with the psql tool. When I closed the psql session and reconnected again, the data was not there, and inserts were failing on missing “dblink” extension. I recommend updating the documentation here, either instructing people to "CREATE EXTENSION IF NOT EXISTS dblink CASCADE;” or having the docker image already instantiated with the necessary extensions.

Later I found the docker-run.sh script (https://github.com/timescale/timescaledb/blob/master/scripts/docker-run.sh) which helps tremendously in setting up the container. It survives closing the psql connection, as well as Docker container restarts (as it mounts the volume). I would highly recommend referencing to this script in your Readme and Getting Started documentation.

I hope this feedback helps a bit.

**Comment by RobAtticus** [comment]
Thanks for pointing this out! We are in the process of updating the README and when the instructions are there I will update with a pointer.

**Comment by RobAtticus** [comment]
Just pushed an update to our README with post-pull instructions, please check it out. Feel free to close the issue if its resolved for you :)
