### ISSUE TITLE
High Memory Usage with date_trunc and time_bucket across large result sets

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#2212]
**Relevant system information:**
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.2
 - Installation method: Timescale helm chart

**Describe the bug**
When querying across many rows (>2B), using date_trunc or time_bucket, the query's memory usage grows until it is killed by the linux OOMkiller.

This does NOT happen when avoiding date_trunc or time_bucket. There are a few as-yet unisolated variables:

date_trunc seems to always get oomkilled. time_bucket seems to get oomkilled when run parallelized, but sometimes not when run single-threaded.

There are compressed chunks, but may also happen with uncompressed chunks (this was not tested at scale).

It does seem to require iterating over a large number of rows. In this case, between ~2.5->4B rows.

**To Reproduce**
```sql select count(1)

from table tb

where

date_trunc('day', tb.timestamp_utc) = current_date;
```
2. Do this across a large hypertable with compressed chunks. The row counts tested against were ~2.5-4B rows.

You can see the memory usage of this PID grow until either system OOM happens, or the linux oomkiller kills it.
An example, from dmesg: 
`[Wed Aug  5 12:29:35 2020] [18270]  1000 18270  1926522  1608377    3209      10        0           614 postgres` - 1608377 4K pages, or about 6.4gb

**Additional context**

The problem goes away whenever date_trunc or time_bucket are removed from the query, e.g.

```sql
select
    count(*)
from
    table
where
    timestamp_utc >=  current_date - interval '1 day'
    and timestamp_utc <  current_date::timestamp;
```

So it seems to be in some interaction between date_trunc, time_bucket, parallelization, and/or compression. Or any combination of those.

**Comment by JLockerman** [comment]
just a note: without `date_trunc` the query should fall back to our `count` fastpath, and never need to decompress anything, and even with
```SQL
WHERE timestamp_utc >=  current_date - interval '1 day' and timestamp_utc <  current_date::timestamp```
it'll still prefilter based on the metadata. Something to check would be if another that requires full decompression also causes the problem e.g.
```SQL
WHERE timestamp_utc::TEXT != 'foo'
```

**Comment by svenklemm** [comment]
@tylerfontaine wasn't able to reproduce on a hypertable with 2.5 billion rows, can you provide more information about your environment (number of chunks, explain output, ...)
