### ISSUE TITLE
Database dump is missing time scale properties

### ISSUE THREAD

**Issue by vinayakbkulkarni** [timescale/timescaledb#2213]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 12.0
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.2
 - Installation method: apt install

**Describe the bug**
When trying to get pg_dump there are missing timescale properties.
This wors well when executed with the timescaledb docker.

**To Reproduce**
pg_dump <dbName> -h localhost -p 5432 -U <user> > dump/mydb.dump

**Expected behavior**
pg dump to have all timescaledb properties

**Actual behavior**
Missing properties

**Screenshots**

![Screenshot from 2020-08-10 13-38-09](https://user-images.githubusercontent.com/13833467/90097902-a4cb4e00-dd54-11ea-947b-75dcc5339bdc.png)

**Additional context**
Issue with apt package & works with docker
Installations done-
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
sudo apt-get update
sudo apt-get install postgresql-12 postgresql-contrib
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt-get update
sudo apt -y install timescaledb-postgresql-12
sudo timescaledb-tune
sudo service postgresql restart

**Comment by erimatnor** [comment]
The timescaledb properties are not real reloptions and won't show up in database dumps.
