### ISSUE TITLE
Maintenance mode for data nodes

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#2214]
When working with data nodes you want to be able to perform certain administrative actions on them.

- You might want to block creation of new chunks but still allow writes to the data node in order to replace the data node. 
- You might want to block writes to the data node completely if the disk is starting to fill up. In this case you have to rely on the replicas to the chunks on the data node.

However, these modes are mostly interesting when some sort of native replication is used. Blocking writes on a data node when there are no replicas will only prevent the system from ingesting new data, which can be accomplished in other ways (and might not even be desirable).

Instead, introduce some sort of "maintenance mode" for data nodes together with native replication and allow different flags to be set to handle the scenarios above.

When blocking the creation of new chunks on the data node, this will place the chunks on the data node "at risk" since they will eventually fill up and and no new chunks can be created. While this is happening, the replication factor is still not a problem, but it will be once the chunk fills up so it should be clear to the administrator what the situation is.

When blocking writes to a data node, the replication factor for writes is reduced, so this should be properly indicated to the administrator.

**Comment by svenklemm** [comment]
multinode has been removed
