### ISSUE TITLE
explicit usage of schema "public"

### ISSUE THREAD

**Issue by oldgreen** [timescale/timescaledb#222]
I can't create the `timescaledb` extension in my db, PostgreSQL complains: `ERROR:  schema "public" does not exist` (which is true). The schema `public` is used explicitly in sql/*.sql scripts (`CREATE OR REPLACE FUNCTION public.time_bucket(`...). Note that e.g. PostgreSQL wiki contains the following information: 

> it is recommended to remove the public schema

[https://wiki.postgresql.org/wiki/Database_Schema_Recommendations_for_an_Application](https://wiki.postgresql.org/wiki/Database_Schema_Recommendations_for_an_Application)

**Comment by RobAtticus** [comment]
Thanks for pointing that out. For some reason that function (`time_bucket`) is explicitly in `public` and others are not.

**Comment by RobAtticus** [comment]
PR for this is merged and should be in the next release

**Comment by RobAtticus** [comment]
Hi @oldgreen, if you could verify this is fixed in the recently released 0.6.0 and close the issue that'd be great!

**Comment by oldgreen** [comment]
I've now successfully created the `timescaledb` extension in a db without the schema `public` using TimescaleDB version 0.6.0. Thanks!
