### ISSUE TITLE
Docker-compose feature request

### ISSUE THREAD

**Issue by pythonmobile** [timescale/timescaledb#2224]
It would be nice to have a Grafana+timescaledb+promethius (or telegraf) docker compose file for people who want to keep away from kubernetes/helm:

https://dev.to/project42/install-grafana-influxdb-telegraf-using-docker-compose-56e9

I would be willing to help on the docker-compose part, but have absolutely no clue about the other tools.

**Comment by akulkarni** [comment]
I believe this may be what you are looking for? https://github.com/timescale/timescale-prometheus/blob/master/docker-compose.yml

cc @cevian

**Comment by akulkarni** [comment]
Hi @pythonmobile closing this issue for now, but please let me know if that link/project is not what you are looking for.
