### ISSUE TITLE
Timescaledb not working with sqlalchemy 

### ISSUE THREAD

**Issue by araura2000** [timescale/timescaledb#2226]
Hello. Recently I ran into an issue when trying to use timescaledb with sqlalchemy and psycopg2. I did a search online but could not find a viable solution. 

Env:
Python 3.6.7
PostgreSQL 12.3
SQLAlchemy 1.3.2
psycopg2 2.8.5
TimescaleDB extention 1.7.2

SQLAlchemy setup:
```
engine_pg = SA.create_engine('postgresql+psycopg2://{u}:{p}@{h}/{d}'.format(u='postgres', p='xxx', h='localhost', d='xxx'))
conn_pg = engine_pg.connect()
```

However, I ran into an error of psycopg2.errors.UndefinedFunction when running following queries. The same queries work fine if I run it on PostgreSQL directly though Navicat. 

```
conn_pg.execute('''CREATE TABLE public.conditions (
 time        TIMESTAMPTZ       NOT NULL,
 location    TEXT              NOT NULL,
 temperature DOUBLE PRECISION  NULL);''')
conn_pg.execute('''SELECT create_hypertable('public.conditions', 'time');''')
```

the create_hypertable function throws out an error: 
```
ProgrammingError: (psycopg2.errors.UndefinedFunction) function create_hypertable(unknown, unknown) does not exist
LINE 1: SELECT create_hypertable('public.conditions', 'time');
```

No matter I ran 

`conn_pg.execute('''CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;''') `

in advance or not I still got the same error.

Can anybody help me out? If timescaledb is not compatible with SQLAlchemy at this time, that's fine and I will find an alternative solution.

**Comment by k-rus** [comment]
https://github.com/timescale/timescaledb/issues/551 demonstrates that TimescaleDB can be used with SQLAlchemy.

Can you check if the extension was actually created in the database you are targeting? Do you have an opportunity to use `psql` against the database and check that the extension and the table were created? Also, I don't know if the connection is established to public schema or not. May be you need to prefix `create_hypertable` with the schema name, e.g., `public.create_hypertable`.

**Comment by araura2000** [comment]
Thanks! It works with the schema name as prefix.

**Comment by k-rus** [comment]
Great that it was an easy fix :)

**Comment by dorosch** [comment]
There is also a solution in the form of a third-party library)
https://pypi.org/project/sqlalchemy-timescaledb/
