### ISSUE TITLE
Move block_new_chunks and allow_new_chunks to internal namespace

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2236]
It was decided that this functionality should not be in 2.0 and instead removed or moved to the internal namespace pending further decision about this API.

**Comment by binakot** [comment]
Please, don't remove this feature. I believe it will be useful :octocat: 
Attach the discussion about it https://app.slack.com/client/T4GT3N2JK/CPSD82EMU/thread/CPSD82EMU-1603914781.148200
Later I will try to describe it more clear and probably draw a schema ;)
