### ISSUE TITLE
Update to version 0.5.0

### ISSUE THREAD

**Issue by raycheung** [timescale/timescaledb#225]
Testing on my Mac, the timescaledb was installed through brew. After upgrade to 0.5.0 with `brew upgrade`, I tried to update the extension but failed as follow. Please help.

```sql
timescale-dev=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  could not find function "dimension_calculate_open_range_default" in file "/usr/local/lib/postgresql/timescaledb.so"
timescale-dev=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 0.4.2   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)
```

**Comment by RobAtticus** [comment]
Hi, did you make sure to restart postgres (`brew services restart postgresql`) before trying to `ALTER EXTENSION`?

**Comment by mfreed** [comment]
We added some comments:  http://docs.timescale.com/latest/api/update-db

**Comment by mfreed** [comment]
Hi @raycheung Following on:  Did this issue get resolved with restarting postgres (or something else)?

**Comment by raycheung** [comment]
@mfreed Yes it worked. I thought `brew services` would have automatically restarted the daemon when the package changes, but it didn't this time. Thanks for the tip and it's all good now.
