### ISSUE TITLE
Make hypertable_approximate_row_count just return row count

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2252]
The function `hypertable_approximate_row_count` currently returns count and the schema+name of the table that was given as input. This latter two return values are unnecessary and make the function quite different from `count` that it is trying to provide an alternative for.

Thus, the function should be changed to just return the count, which also makes it easier to use in queries:

```
SELECT approximate_row_count(*)
FROM mytable;
```

**Comment by JH-D** [comment]
@erimatnor  @pmwkaa 
Hello, may I ask a question.
**What is the correct query method in 2.4.1?**

I make a distributed hypertable and insert billions rows, but the result is 0.
![图片](https://user-images.githubusercontent.com/7844108/132431714-97150e60-c9fe-4ac0-bfc8-36527a52cc95.png)
![图片](https://user-images.githubusercontent.com/7844108/132431849-bcad11e1-3410-481f-8c88-e888bd37fd5e.png)

## Relevant system information:
- Install method: docker, image is "timescale/timescaledb:latest-pg12"
- Postgresql version: PostgreSQL 12.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
- TimescaleDB version: 2.4.1
- Multi-node setup: 1 access node, 2 data node.
