### ISSUE TITLE
Fix AsyncAppend planner integration

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2264]

**Comment by erimatnor** [comment]
Can you please add a description to explain what this means?

**Comment by svenklemm** [comment]
I think this is about tree traversal. You are not supposed to iterate over the planner tree but AsyncAppend does which means the code will break for out of tree custom nodes.

**Comment by svenklemm** [comment]
Closing this since AsyncAppend has been removed as part of multinode removal
