### ISSUE TITLE
Support storing non-partialized data in cagg materialization table

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2274]

**Comment by netrounds-fredrik** [comment]
Not a lot of information in this issue yet :smiley:, but from the title I guess that it's related to what has been discussed in https://github.com/timescale/timescaledb/issues/1867.

**Comment by fabriziomello** [comment]
This was implemented by the following PRs:
- https://github.com/timescale/timescaledb/pull/4294
- https://github.com/timescale/timescaledb/pull/4269

And released in Timescale 2.7.0 - https://github.com/timescale/timescaledb/releases/tag/2.7.0
