### ISSUE TITLE
(docker) Can't upgrade from timescale-db:1.7.2 to 1.7.3

### ISSUE THREAD

**Issue by clambin** [timescale/timescaledb#2277]
**Relevant system information:**
 - OS: raspbian 10
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 11.9
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.3
 - Installation method: docker

**Describe the bug**
After upgrading from 1.7.2 to 1.7.3, I'm unable to use the timescaledb extension.  I'm getting the following error:

2020-08-29 12:49:49.501 UTC [51] ERROR:  could not access file "$libdir/timescaledb-1.7.2": No such file or directory

Indeed, looking in /usr/local/lib/postgresql in the 1.7.3 docker image, I see:

```
-rwxr-xr-x    1 root     root        533152 Nov 12  2019 timescaledb-1.5.1.so
-rwxr-xr-x    1 root     root        546576 Jan 15  2020 timescaledb-1.6.0.so
-rwxr-xr-x    1 root     root        400380 Apr  8 07:15 timescaledb-1.6.1.so
-rwxr-xr-x    1 root     root        402092 Apr 17 12:52 timescaledb-1.7.0.so
-rwxr-xr-x    1 root     root        402620 Jun  8 09:26 timescaledb-1.7.1.so
-rwxr-xr-x    1 root     root        408192 Aug 27 10:31 timescaledb-1.7.3.so
```

So, there's no 1.7.2 in the image, which I guess it needs to upgrade from 1.7.2 to 1.7.3?

**Comment by svenklemm** [comment]
@clambin  I've updated the docker images, can you try again?

**Comment by clambin** [comment]
yep.  that did the trick.  thanks!
