### ISSUE TITLE
Question: Querying data between two dates

### ISSUE THREAD

**Issue by TimJMartin** [timescale/timescaledb#2278]
Hi
I currently use PostgreSQL 12 to store around 800million features and am now looking for a better way to query the data using date fields and I think TimeScaleDB would be a good fit but I have some questions on the types of queries I could make. 

The database is an archive containing all previous versions of uniquely ID'd features. And the types of queries I currently would run are

SELECT * FROM archive.table1 WHERE validTo is NULL - this query gives me the current live view

SELECT * FROM archvie.table1 WHERE id = 'XYX' - would give me all the versions of a unique feature

SELECT * FROM archive.table1 WHERE validFrom>= '2014-02-01' AND validTo <  '2014-03-01'

Reading the docs I can see I can create the hypertable using two dimensions - a date field and the unique ID field and that would work well for queries 1 and 2 I think. But how would queries 3 run? 

Are there an examples of docs that I have not seen? Many thanks in advance

Tim

**Comment by mfreed** [comment]
Hi @TimJMartin it's a common question, but TimescaleDB has the ability to do rich indexing, in addition to dimensions.  Most of the time we recommend using a single time-based index (unless you are using our upcoming multi-node version in TimescaleDB 2.0).

So I would just create a time partition on your timestamp, then you could build other indexes that you want.  And if you commonly query on `id`, in addition to a composite index (id, timestamp DESC), you could also use it as your `segmentby` field when doing compress (or build a reorder policy on the above composite index).

**Comment by TimJMartin** [comment]
@mfreed many thanks for your response. Will give it a go and see how I get on
