### ISSUE TITLE
"Telemetry Reporter": out of background workers issue, when telemetry is disabled 

### ISSUE THREAD

**Issue by rajadayalansh** [timescale/timescaledb#2282]
**Relevant system information:**
 - OS: Ubuntu 18.04.4 LTS
 - PostgreSQL version:  postgres (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
 - TimescaleDB version:  timescaledb | 1.7.2   | public    
 - Installation method: "apt install"

Recently upgraded TimescaleDB from 1.6 to 1.7.2 and notice the "Telemetry Reporter": out of background workers warning

Tried setting Telemetry Reporter config to off and deleting bgw_job, but still see the logs filled with the warning as below.

2020-08-30 03:25:38.055 UTC [10061] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers
2020-08-30 03:25:38.055 UTC [10052] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers

Settings in Postgres provided below using PSQL

postgres=# show timescaledb.telemetry_level;
 timescaledb.telemetry_level
 off
(1 row)

postgres=# select * FROM _timescaledb_config.bgw_job;
 id | application_name | job_type | schedule_interval | max_runtime | max_retries | retry_period
(0 rows)

postgres=# show max_worker_processes;
 max_worker_processes
 13
(1 row)

postgres=# show timescaledb.max_background_workers ;
 timescaledb.max_background_workers
 8
(1 row)

**Comment by svenklemm** [comment]
If you delete the job entry from the bgw_job table those warnings should disappear (but the job entry will get readded during extension upgrades). Can you post result of `select * from _timescaledb_config.bgw_job;`

**Comment by rajadayalansh** [comment]
postgres=# select * FROM _timescaledb_config.bgw_job;
 id | application_name | job_type | schedule_interval | max_runtime | max_retries | retry_period
----+------------------+----------+-------------------+-------------+-------------+--------------
(0 rows)

postgres=# \q
postgres@tsdb-01:/home/ubuntu$ tail -f /var/log/postgresql/postgresql-eng-dev.log
2020-08-30 17:57:46.902 UTC [10052] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers
2020-08-30 17:57:47.513 UTC [10061] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers
