### ISSUE TITLE
setting timescaledb.telemetry_level=off in psql reverts to basic

### ISSUE THREAD

**Issue by rajadayalansh** [timescale/timescaledb#2283]
Relevant system information:

OS: Ubuntu 18.04.4 LTS
PostgreSQL version: postgres (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
TimescaleDB version: timescaledb | 1.7.2 | public
Installation method: "apt install"

Setting timescaledb.telemetry_level=off in psql reverts to basic

Output from psql provided below
postgres=# ALTER SYSTEM SET timescaledb.telemetry_level=off;
ALTER SYSTEM
postgres=# show timescaledb.telemetry_level;
 timescaledb.telemetry_level
 basic
(1 row)

**Comment by svenklemm** [comment]
@rajadayalansh  You need to reload the postgres configuration for your change to take effect:
```
dev=# alter system set timescaledb.telemetry_level to off;
ALTER SYSTEM
dev=# show timescaledb.telemetry_level ;
 timescaledb.telemetry_level 
-----------------------------
 basic
(1 row)

dev=# select pg_reload_conf();
 pg_reload_conf 
----------------
 t
(1 row)

dev=# show timescaledb.telemetry_level ;
 timescaledb.telemetry_level 
-----------------------------
 off
(1 row)
```

**Comment by nikkhils** [comment]
Sven has provided the response already. Closing this one.
