### ISSUE TITLE
TimescaleDB Telegraf output plugin causing segmentation fault on Patroni-Pgbackrest cluster.

### ISSUE THREAD

**Issue by gowtham500** [timescale/timescaledb#2302]
**Relevant system information:**
 - OS: CentOS 7.7. All nodes are 4 CORE , 32 GB RAM.
 - PostgreSQL version- 12.1 
-  Database - 3 node patroni-pgbackrest cluster. 4th node is a dedicated backup admin host.
-  patronictl version 1.6.1, pgBackRest 2.23
 - TimeScale Installation method: 
1. Downloaded timescale rpm  timescaledb_12-1.7.2-1.rhel8.x86_64 from https://yum.postgresql.org/12/redhat/rhel-8-x86_64/
2. Did a yum install -y timescaledb_12-1.7.2-1.rhel8.x86_64 on 3 nodes of patroni cluster.
3. Created a database tutorial and loaded extension

 - TimescaleDB version

tutorial=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description

-------------+---------+------------+---------------------------------------------------------------
----
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.7.2   | public     | Enables scalable inserts and complex queries for time-series d
ata
(2 rows)

**Describe the bug**

Segmentation Fault while telegraf output plugin flushes data into a patroni cluster. The issue does not occur on a standalone default setup. Segmentation fault occurs during every data flush from telegraf to postgresql

**To Reproduce**

1. Setup a 3 node patroni-pgbackrest cluster. This setup has a dedicated backup admin host as the 4th node.
2. Download the timescale extension as mentioned above and do a yum install all nodes.
3. I was trying to test the telegraf output plugin https://docs.timescale.com/latest/tutorials/telegraf-output-plugin.
Downloaded from telegraf rpm binary from https://docs.timescale.com/latest/tutorials/telegraf-output-plugin.
4. Install telegraf  on a 5th node. So basically we are sending montioring data of node 5 into a highly available postgresql cluster which has got timescaledb extension.
5. On the 5th node.
 telegraf -version
Telegraf 1.13.0-with-pg (git: telegraf-with-pg 9792b415)
5. Generate sample telegraf config file
telegraf --config telegraf.conf --test 
6. The outputs.postgresql section was updated to connect to the primary node.
7. Download timescaleb-tune from https://packagecloud.io/timescale/timescaledb/packages/el/7/timescaledb-tools-0.8.1-0.el7.x86_64.rpm
8. Copy the postgresql config file into a temp location and timescaledb-tune on that file.
timescaledb-tune --config-path /tmp/postgresql.conf.   
Now it will give recommendations and update the file.
9. Apply the recommendations through patroni's edit-config.
patronictl -c /etc/patroni/stampede.yml edit-config.
Save and restart through patronictl -c /etc/patroni-stampede.yml restart cluster_name

**Expected behavior**

Table cpu to be created in database tutorial with multiple rows being inserted every 10 seconds.

**Actual behavior**

1. Table CPU gets created in database tutorial.
2. The table is empty.
3. Telegraf output plugin tries to flush data after default 10 seconds.
4. Segmentation fault starts to appear in postgresql logs. Patroni responds to this by restarting postgresql and crashes at last.
5. Telegraf needs to be stopped to stop postgresql from crashing.

**Logs in DEBUG 5 mode**

2020-09-02 11:04:59.999 UTC [32517] db=,user=,app=,client= DEBUG:  server process (PID 32854) was terminated by signal 11: Segmentation fault
2020-09-02 11:04:59.999 UTC [32517] db=,user=,app=,client= DETAIL:  Failed process was running: copy "public"."cpu" ( "time", "cpu", "host", "usage_iowait", "usage_softirq", "usage_steal", "usage_guest", "usage_idle", "usage_system", "usage_nice","usage_irq", "usage_guest_nice", "usage_user" ) from stdin binary;
2020-09-02 11:04:59.999 UTC [32517] db=,user=,app=,client= LOG:  server process (PID 32854) was terminated by signal 11: Segmentation fault
2020-09-02 11:04:59.999 UTC [32517] db=,user=,app=,client= DETAIL:  Failed process was running: copy "public"."cpu" ( "time", "cpu", "host", "usage_iowait", "usage_softirq", "usage_steal", "usage_guest", "usage_idle", "usage_system", "usage_nice", "usage_irq", "usage_guest_nice", "usage_user" ) from stdin binary;
2020-09-02 11:04:59.999 UTC [32517] db=,user=,app=,client= LOG:  terminating any other active server processes

**Additional context**
1. Patroni setup is succesfull - restart, failover works well.
2. pgbackrest - archive and backup commands are succesfull as well.
###

**Comment by gowtham500** [comment]
Hello team,

Can you please let me know what info is required. I have provided all info up above.

**Comment by NunoFilipeSantos** [comment]
Hi @gowtham500  ! 👋 If you can reproduce this on the latest TimescaleDB version, please feel free to reopen the issue.
