### ISSUE TITLE
Refactor get_create_command used by backup tool

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2306]
There's a SQL function `_timescaledb_internal.get_create_command` that is used for an internal backup tool. The function recreates the original `create_hypertable` command.

This function has several limitations, including just being able to handle hypertables with up to two dimensions. It also, for some reason, takes a NAME as input instead of REGCLASS.

Multinode has deparsing support to do similar things when it creates hypertables on data nodes. This deparsing looks a lot more complete than the PLPGSQL-based get_create_command. Ideally,  the command should reuse the deparsing support for multinode.

**Comment by svenklemm** [comment]
multinode has been removed
