### ISSUE TITLE
Feature request: Allow adding column to compressed chunk

### ISSUE THREAD

**Issue by netrounds-fredrik** [timescale/timescaledb#2316]
In https://docs.timescale.com/latest/using-timescaledb/compression#future-work, it is stated that it is not possible to change the schema of a hypertable with compressed chunks:
> One of the current limitations of TimescaleDB is that once chunks are converted into compressed column form, we do not currently allow any further modifications of the data (e.g., inserts, updates, deletes) or the schema without manual decompression.

And sure enough, an `ALTER TABLE` gives the following error:
```
postgres=# ALTER TABLE test_table ADD COLUMN c int DEFAULT NULL;
ERROR:  operation not supported on hypertables that have compression enabled
```

I believe that the above example, where a new column is added to an existing table, is a quite common use-case, for example  because a new parameter is being collected. Since the column has a `NULL` default value, I assume that existing rows stored in the chunks should not have to be updated. If this assumption is true, would it be possible to add an exception to the no-further-modifications-rule for adding a `NULL` column?

**Comment by dhodyn** [comment]
as a workaround, we are always adding an extra column called "extracolumns" of the type [hstore](https://www.postgresql.org/docs/13/hstore.html) for tables which will be compressed so, that we can later _add more columns_ to the table by saving them as key-value pairs. But this has a major disadvantage that data is always text, and additional casting is needed when handling such data

**Comment by WarriorOfWire** [comment]
Hey @netrounds-fredrik feel free to +1 the existing issue for this:  https://github.com/timescale/timescaledb/issues/1543

Adding (nullable) and dropping columns (without space reclamation) has been a complete blocker since the initial release of compression for users like me with wide schema.

**Comment by netrounds-fredrik** [comment]
Ahh, I thought that I searched for existing issues, but appearantly I did not look hard enough. Closing this one as a duplicate of https://github.com/timescale/timescaledb/issues/1543.
