### ISSUE TITLE
Rename with-option continuous

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb#2322]
The current syntax is:
```sql
CREATE MATERIALIZED VIEW view_name
WITH (timescaledb.continuous) AS
```
Option `continuous` was meaningful when the creating view was also creating the policy to continuously update the materialisation. Now the policy is created separately:
```sql
SELECT add_refresh_continuous_aggregate_policy('view_name', start_interval, end_interval); 
```
which might be renamed into `add_continuous_aggregate_policy` in https://github.com/timescale/timescaledb/issues/2320.

Two suggestion were expressed for renaming: `hyperveiw` and `aggregation`, i.e.:
```sql
CREATE MATERIALIZED VIEW view_name
WITH (timescaledb.hyperview) AS
-- or
CREATE MATERIALIZED VIEW view_name
WITH (timescaledb.aggregation) AS
```

**Comment by erimatnor** [comment]
Closing for now since there was no clear agreement on changing.
