### ISSUE TITLE
Time Range Chunk Creation Error

### ISSUE THREAD

**Issue by osman-demirci** [timescale/timescaledb#2327]
After the last timescaledb update (1.7.2) create new chunk operation failed. When the operation executing throw an error was below. The database have two table space that is "ssd" and "default". Hyper table is on "default" tablespace.
The related foreign keys reference table and its constraints is on "ssd" tablespace. 

ERROR: syntax error at or near "USING"
  Where: PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 42 at EXECUTE

I solved this problem by migrate foreign keys reference table's primary key to "default" tablespace. But that the primary key must be "ssd" tablespace for avoiding performance problem. 

Finally, how can we solve this problem when the hyper table and reference table is different tablespace.
Thanks.

Database info
---------------------------------------
Postgressql version = 11.9
TimescaleDB version = 1.7.2
Database size = 4.3 telebayt
Active connection per second = 420

**Comment by svenklemm** [comment]
Can you provide a simple test case to reproduce the issue in a fresh database.

**Comment by erimatnor** [comment]
Is this issue fixed by https://github.com/timescale/timescaledb/pull/2604?

**Comment by NunoFilipeSantos** [comment]
We believe #2604 fixed this issue, closing it.
Feel free to reopen it if that is not the case.
