### ISSUE TITLE
Refresh policies with start and end interval smaller than a day will fail for hypertables with dates as time type

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#2330]
**Relevant system information:**
 - OS: Ubuntu 19.04
 - PostgreSQL version (output of `postgres --version`): 11.9
 - TimescaleDB version (output of `\dx` in `psql`): 2.0-dev (possibly earlier as well).
 - Installation method: source

**Describe the bug**
If a hypertable is created with a date as the time column and refresh policies are added that have an interval that is less than a day, the policy execution will fails when the times end up on the same date.

**To Reproduce**

```
CREATE TABLE date_table(time DATE NOT NULL, value FLOAT);
SELECT create_hypertable('date_table', 'time');
    create_hypertable    
-------------------------
 (9,public,date_table,t)
(1 row)

CREATE MATERIALIZED VIEW date_table_summary
  WITH (timescaledb.continuous, timescaledb.materialized_only=true)
    AS SELECT time_bucket('1 day', time) FROM date_table GROUP BY 1;
SELECT add_refresh_continuous_aggregate_policy('date_table_summary',
    start_interval => '1 day'::interval, end_interval => '1 hour'::interval ,
    schedule_interval => '1 day'::interval) AS job_id \gset
CALL run_job(:job_id);
```

**Expected behavior**
No error.

**Actual behavior**
Error generated when `NOW() - INTERVAL '1 day'` and `NOW() - INTERVAL '1 hour'` end up on the same date.

**Screenshots**

**Additional context**

**Comment by erimatnor** [comment]
I guess this is a lack of validation of policy parameters when creating the policy? Is this fixed? I see references PR that is now merged.

**Comment by erimatnor** [comment]
@mkindahl @gayyappan can this issue be closed now?
