### ISSUE TITLE
calculate gains & sort by it

### ISSUE THREAD

**Issue by bonesoul** [timescale/timescaledb#2342]
This is not an actually a bug, but I'm actually looking for a way or aggregate function to achieve this. I basically got a readings table and cagg's over them. I know I can read the very last leading by the last() function but what I instead need is a way to calculate gains;

- I want to first calculate the gains for the last reading (compared to the previous reading).
- Sort the results by the calculated gains.

So I'll be able to find the devices with most gains.

Is it possible?

**Comment by svenklemm** [comment]
You can use window-functions to do these calculations:

```
SELECT time,
  device_id,
  gain
FROM (
  SELECT time,
    device_id,
    value - lag(value) OVER (PARTITION BY device_id ORDER BY time) AS gain
  FROM metrics) AS sub
WHERE gain IS NOT NULL
ORDER BY gain DESC;
```

https://www.postgresql.org/docs/12/functions-window.html
