### ISSUE TITLE
query error: variable not found in subplan target list (when using PG 9.6.2)

### ISSUE THREAD

**Issue by JamesPS** [timescale/timescaledb#235]
I have a basic query failing with the error: variable not found in subplan target list.

Below is a psql session showing the bug, which seems to be related to using an aggregate function and a stable or volatile function in the where clause.

```
events=# \dx timescaledb
                                    List of installed extensions
    Name     | Version | Schema |                            Description                            
-------------+---------+--------+-------------------------------------------------------------------
 timescaledb | 0.5.0   | public | Enables scalable inserts and complex queries for time-series data
(1 row)

events=# create table ht_test (time timestamp with time zone, data integer);
CREATE TABLE
events=# select create_hypertable('ht_test', 'time');
 create_hypertable 
-------------------
 
(1 row)

events=# insert into ht_test values(now(), 1);
INSERT 0 1

events=# select count(*) from ht_test where time > now() - interval '1 hour';
ERROR:  variable not found in subplan target list

events=# select count(*) from ht_test where time > now();
ERROR:  variable not found in subplan target list

events=# select * from ht_test where time > now() - interval '1 hour';
             time              | data 
-------------------------------+------
 2017-10-04 14:45:59.030367-04 |    1
(1 row)

events=# select count(*) from ht_test where time > '2017-01-01';
 count 
-------
     1
(1 row)

events=# select count(*) from ht_test;
 count 
-------
     1
(1 row)

events=# select sum(data) from ht_test where time > now();
ERROR:  variable not found in subplan target list

events=# select data from ht_test where time > now();
 data 
------
(0 rows)

events=# select sum(data) from ht_test where data > abs(0.5);
 sum 
-----
   1
(1 row)

events=# select sum(data) from ht_test where data > random();
ERROR:  variable not found in subplan target list

```

**Comment by mfreed** [comment]
@JamesPS I forgot to thank you for reporting this bug yesterday, including detailed instructions for repeatability.  We hope to get out a fix soon.

**Comment by JamesPS** [comment]
No problem, I'm glad the instructions are useful.

Not sure a bug report is the right place for this, but I'm really excited about the product, it's like you guys read my mind when you announced it :-)

**Comment by mfreed** [comment]
No, github issues are a great place for bug reports.  Helps us track, and can link against the PRs/releases that fix them.

(As aside, always happy to also answer more detailed questions / provide more real-time support on our slack channel: http://slack-login.timescale.com/)

**Comment by cevian** [comment]
@JamesPS I am having trouble reproducing this error. Can you provide the output of `SELECT _timescaledb_internal.get_git_commit();`

**Comment by mfreed** [comment]
Hi @JamesPS.  We've tried to reproduce with TimescaleDB 0.5.0 running on Postgres 9.6.3 running natively on Ubuntu, natively on MacOS, and in docker running on MacOS, and couldn't reproduce any of these problems (it worked correctly in all three cases).

Can you share your PostgreSQL version, OS, any other other relevant info?  Thanks!

**Comment by JamesPS** [comment]
postgres (PostgreSQL) 9.6.2, OS is a modified version of gentoo 4.0.5

I had actually reproduced this on another install with the 0.4.0 version of the timescale plugin. The common denominator appears to be the 9.6.2 version of postgres. I can upgrade the database to the latest version of 9.6 and let you know if that resolves the issue.

**Comment by RobAtticus** [comment]
Hi @JamesPS were you able to reproduce this on later versions of PostgreSQL 9.6 and/or newer versions of TimescaleDB?

**Comment by JamesPS** [comment]
Hi, sorry for the delay. I was just able to confirm that the issue is not present in PG 9.6.6 with the 0.5.0 version of the plugin.

**Comment by RobAtticus** [comment]
I am going to close out this issue for now then. If you do see it again, please feel free to re-open!
