### ISSUE TITLE
Relax locking during refresh and invalidation processing

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2355]
The current locking during a refresh is quite conservative in order to simplify the code. However, this might also affect performance; for instance between concurrent inserts and refreshes and between different refresh processes.

In particular, the first transaction of a refresh moves the invalidation threshold.  Currently, it always serializes around an exclusive lock on the invalidation threshold table and this blocks inserts that try to read the threshold. While the first transaction of the refresh is short, it would be useful to relax this locking so that a read lock is taken first to read the threshold, and then a heavier lock is taken only if the threshold needs an update.

Similarly, the second transaction of the refresh serializes around a long on the materialized hypertable, which prevents concurrent refreshes of the same continuous aggregate. This could be improved to allow concurrent refreshes of non-overlapping regions.

**Comment by bendoerr** [comment]
These improvements would be amazing!

**Comment by fabriziomello** [comment]
This was implemented by #5809 and released in [2.12.0](https://github.com/timescale/timescaledb/releases/tag/2.12.0)
