### ISSUE TITLE
After restore the dump I got more indexes than the source DB

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [timescale/timescaledb#2358]
I had a timescaleDB on PG 9.6 and TS version is 0.9.2
I have upgraded it to 1.7.4

Then took the dump from that DB and restored it on a new TS DB.
PG version 12 and TS version  1.7.4

On source when I check the indexes it was showing 443
but on the target side, the restoration took more time, and when I check the number of indexes it was showing 745

Then I tried to dump the database with schema only and then restored. There the index count was correct.

Im not sure about this behavior. Can someone help me to understand this?

**Comment by NunoFilipeSantos** [comment]
Hi @BhuviTheDataGuy! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it.
