### ISSUE TITLE
create cagg using new syntax crashes in plpgsql block

### ISSUE THREAD

**Issue by gayyappan** [timescale/timescaledb#2371]
CREATE TYPE custom_type AS (high int, low int);

CREATE TABLE conditions_before (
      timec       TIMESTAMPTZ       NOT NULL,
      location    TEXT              NOT NULL,
      temperature DOUBLE PRECISION  NULL,
      humidity    DOUBLE PRECISION  NULL,
      lowp        double precision NULL,
      highp       double precision null,
      allnull     double precision null,
      highlow     custom_type null,
      bit_int     smallint,
      good_life   boolean
    );

SELECT table_name FROM create_hypertable( 'conditions_before', 'timec');

INSERT INTO conditions_before
SELECT generate_series('2018-12-01 00:00'::timestamp, '2018-12-31 00:00'::timestamp, '1 day'), 'POR', 55, 75, 40, 70, NULL, (1,2)::custom_type, 2, true;
INSERT INTO conditions_before
SELECT generate_series('2018-11-01 00:00'::timestamp, '2018-12-31 00:00'::timestamp, '1 day'), 'NYC', 35, 45, 50, 40, NULL, (3,4)::custom_type, 4, false;
INSERT INTO conditions_before
SELECT generate_series('2018-11-01 00:00'::timestamp, '2018-12-15 00:00'::timestamp, '1 day'), 'LA', 73, 55, NULL, 28, NULL, NULL, 8, true;

DO LANGUAGE PLPGSQL $$
DECLARE
  ts_version TEXT;
BEGIN
    CREATE MATERIALIZED VIEW IF NOT EXISTS  mat_ignoreinval
    WITH ( timescaledb.continuous, timescaledb.materialized_only=true,
           timescaledb.refresh_lag='-30 day',
           timescaledb.ignore_invalidation_older_than='30 days',
           timescaledb.max_interval_per_job = '100000 days')
    AS
      SELECT time_bucket('1 week', timec) as bucket,
    max(temperature) as maxtemp
      FROM conditions_before
      GROUP BY bucket;
--WITH NO DATA;

END $$;

=============================ERROR ========================
psql:1.sql:46: WARNING:  plancache reference leak: plan 0x55625f51f118 not closed
psql:1.sql:46: WARNING:  transaction left non-empty SPI stack
HINT:  Check for missing "SPI_finish" calls.
psql:1.sql:46: WARNING:  snapshot 0x55625f328a18 still active
psql:1.sql:46: NOTICE:  refreshing continuous aggregate "mat_ignoreinval"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
psql:1.sql:46: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:1.sql:46: fatal: connection to server was lost

**Comment by gayyappan** [comment]
we should probably complete the ddl creation and then execute the refresh separately.
Also verify PG transaction behavior for this case

**Comment by emacsway** [comment]
I see the same error for Timescaledb version 1.7.4 when I create CREATE INDEX  WITH (timescaledb.transaction_per_chunk) inside anonymous code block:

```
db=> DO
db-> $$
db$>     DECLARE
db$>     BEGIN
db$> 
db$>         CREATE INDEX index_name ON table_name (column_name) WITH (timescaledb.transaction_per_chunk) WHERE column_name IS NOT NULL;
db$> 
db$>     END
db$> $$ LANGUAGE plpgsql;
WARNING:  plancache reference leak: plan 0x559c25908390 not closed
WARNING:  transaction left non-empty SPI stack
HINT:  Check for missing "SPI_finish" calls.
WARNING:  snapshot 0x559c258aed40 still active
```
