### ISSUE TITLE
Deadlock in refresh materialized view

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2373]
psql:/src/test/sql/updates/setup.continuous_aggs.v2.sql:268: ERROR:  deadlock detected
DETAIL:  Process 77 waits for AccessExclusiveLock on relation 16629 of database 16384; blocked by process 80.
Process 80 waits for ShareLock on transaction 608; blocked by process 77.

**Comment by erimatnor** [comment]
This is a deadlock in the old materializer, which is being removed. Let's reopen if this is turns out to be an issue also with the new refresh procedure.
