### ISSUE TITLE
Do not show materialized hypertables in the hypertables view

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2383]
Materialized hypertables provide internal storage for continuous aggregates and are created as a side effect of creating a continuous aggregate. Therefore, they are not user-facing objects and it would clean up the hypertables view to only show hypertables that are directly created by the user.

Compression hypertables are similarly created as a side-effect of enabling compression and those internal hypertables are not shown in the hypertables view.

**Comment by tylerfontaine** [comment]
Would materialized hypertable size and chunk information be available elsewhere? 

Since this space usage is not otherwise accounted for like compressed hypertable size, I think it makes sense for these to still be included in the hypertable information view.
