### ISSUE TITLE
Improve parameter names in add_retention_policy

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb#2386]
Current definition of `add_retention_policy` is:
```sql
add_retention_policy(
    hypertable REGCLASS, 
    retention_window "any", 
    if_not_exists BOOL = false
)
```
The policy can be applied to a continuous aggregate or a hypertable (which one). Thus it is good to clarify this and improve the parameter name from `hypertable` to more meaningful.

Also it is good to propose the name for the retention lag parameter, which is good to implement.

**Comment by erimatnor** [comment]
The `hypertable` parameter is not `relation` and `retention_window` is `drop_after`. Closing since changes will be released in 2.0.
