### ISSUE TITLE
Inserting from Hypertable into another table does not work

### ISSUE THREAD

**Issue by akulkarni** [timescale/timescaledb#24]
E.g., this query does not work:

```
INSERT INTO rides_test (SELECT * from rides LIMIT 1);
```

**Comment by akulkarni** [comment]
However, this works (new_table needs to be table that does not exist prior to this command):

```
SELECT * INTO new_table FROM rides LIMIT 1;
```

**Comment by RobAtticus** [comment]
Could you try with the latest release (0.0.9-beta) when you have a chance?
