### ISSUE TITLE
Installation failed on Windows 10 - could not copy file 'timescaledb-1.7.4.dll'. Access is denied.

### ISSUE THREAD

**Issue by davarihn** [timescale/timescaledb#2406]
Timescaledb fails during installation on Windows 10:

- OS: Windows 10
- PostgreSQL: 12.4
- Timescaledb: 1.7.4
- Installation method: setup.exe

This is the error I'm getting:

ERROR: could not copy file 'timescaledb-1.7.4.dll': open C:/PROGRA~1/POSTGR~1/12/lib/timescaledb-1.7.4.dll: Access is denied.

![1](https://user-images.githubusercontent.com/45049016/93345806-dd998f80-f7f8-11ea-900b-292872602707.PNG)

This file exists in the timescaledb installation folder. 

I've checked/tried the following:

Have Visual C++ 2015-2019 redistributable X64 - 14.24.28127 installed.
Added the Postgres installation folder to windows PATH.
Checked the permissions for the dll file.
Copied the dll file manually to the destination folder (Program Files/PostgreSQL/12/lib).
Removed and reinstalled PostgreSQL and Timescaledb. 

I still get the same error. 

This is the output of pg_config:
![image](https://user-images.githubusercontent.com/45049016/93357308-c2814c80-f805-11ea-8f06-fc8dba48beae.png)

**Comment by k-rus** [comment]
Since PostgreSQL is installed in the programs folder, you need to run the timescaledb setup as administrator, otherwise it doesn't have permission to copy files.

**Comment by k-rus** [comment]
The manual copy is not enough and doesn't help to solve the issue.

**Comment by davarihn** [comment]
It worked! Thank you!
