### ISSUE TITLE
CPU peaks 100% after installing the extesion

### ISSUE THREAD

**Issue by linhhdinh** [timescale/timescaledb#241]
I installed `timescaledb` extension (v.0.5.0) for postgresql (v9.6) on 16.04 linux box and observes that postgres process occupies 100% CPU. I haven't seen this symptom before that. The server has low workload.

here is result of `top` command:
```
PID   USER      PR  NI    VIRT    RES    SHR S %CPU %MEM   TIME+   COMMAND
19885 postgres  20   0  192684   3916   1420 S 98.3  0.1   5689:04 x3606027128                                     
```

I run query `SELECT pid, datname, usename, query FROM pg_stat_activity` and find two weird queries

```
pid   datname   username  query
19882 postgres  postgres  select Fun013301 ('./x3606027128 &')
19901 postgres  postgres  select Fun013301 ('./ps3597605779 &')
```

function Fun013301 is not existed in postgres database. I cannot figure out what ./x3606027128 command is

**Comment by mfreed** [comment]
Can you say anything more of the workload on timescaledb at the time?  Inserts?  Concurrent query?  COPY commands?

Would you also be able to send the output of this command:  `https://github.com/timescale/timescaledb/blob/master/scripts/dump_meta_data.sql`  Email or slack is fine.

Thanks for the report!

**Comment by linhhdinh** [comment]
@mfreed  the CPU is back to normal now, I will send you the report when I catch the CPU peak 100%

**Comment by erimatnor** [comment]
@linhhdinh sounds like you are running the `dump_meta_data.sql` script from `master` on a `0.5.0` version of TimescaleDB. This won't work. Can you try running the script from the `0.5.0` release?

**Comment by mfreed** [comment]
My apologies for linking to the wrong file.  The correct link should be `https://github.com/timescale/timescaledb/blob/0.5.0/scripts/dump_meta_data.sql`

**Comment by linhhdinh** [comment]
I can run the script of branch `0.5.0`. When I use this script clear my db that installed `timescaledb` extension, the CPU usage jumps to 100%.

```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
```

**Comment by mfreed** [comment]
@linhhdinh I'm not sure I understand your last statement:  ```When I use this script clear my db that installed timescaledb extension, the CPU usage jumps to 100%```

Are you saying that the CPU was low, but *during executing this script*, the CPU jumps to 100%?  In those scenarios, what does `SELECT pid, datname, usename, query FROM pg_stat_activity` show?

**Comment by linhhdinh** [comment]
I closed this issue since I could not reproduce it on fresh installation of timescaledb on fresh linux box
