### ISSUE TITLE
Cannot change owner of continuous aggregate

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2414]
Trying to change the owner of a continuous aggregate generates an error.

```
postgres=# ALTER MATERIALIZED VIEW foo_1day OWNER TO foo;
ERROR:  cannot alter only SET options of a continuous aggregate
```

**Comment by erimatnor** [comment]
This is actually a duplicate of #1277

**Comment by erimatnor** [comment]
@mkindahl also note that we need to test the behavior of "refresh-on-drop" when owner of cagg is different from source hypertable.

**Comment by mkindahl** [comment]
> @mkindahl also note that we need to test the behavior of "refresh-on-drop" when owner of cagg is different from source hypertable.

This should be handled in #2413 rather than this issue.
