### ISSUE TITLE
[question] Missing packages/versions on postgresql.org

### ISSUE THREAD

**Issue by rockaut** [timescale/timescaledb#2432]
I would have a quick question: as the last two releases 1.7.4 and 1.7.3 where described as high priority I can't find the packages on postgesql.org yet. Latest there is 1.7.2 from July.

Are those even packaged and uploaded by yourself?

**Comment by mfreed** [comment]
We don't manage packages on postgres.org, those are built and uploaded by PG community members, not Timescale.

We recommend downloading/using instead the binaries we prepare, which can be found at https://docs.timescale.com/latest/getting-started/installation

**Comment by rockaut** [comment]
Great thanks @mfreed !
