### ISSUE TITLE
v13 support

### ISSUE THREAD

**Issue by devrimgunduz** [timescale/timescaledb#2434]
Hi,

PostgreSQL 13 is due tomorrow. When will you release v13 compatible version?

Regards, Devrim

**Comment by mfreed** [comment]
Hi @devrimgunduz We don't yet have any firm deadline, as we have primarily been focusing on our 2.0 release, for which RC is imminent.

**Comment by NunoFilipeSantos** [comment]
Closing this issue.
Epic here: timescale/timescaledb-private#852

**Comment by NunoFilipeSantos** [comment]
The PG 13 is on our next priorities to be released during the first quarter of the year.
