### ISSUE TITLE
drop_chuks invalidation error displays incorrect continuous aggregate name

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#2448]
**Relevant system information:**
 - PostgreSQL version (output of `postgres --version`): 12.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: Yum Repo

**Describe the bug**
When calling drop_chunks on a hypertable that has more than one continuous aggregate attached to it, if any one of those aggregates has an invalidation_older_than setting larger than the interval specified in the drop_chunks call, it errors, as expected:

`ERROR:  older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.cagg2`

But the name of the cagg given in this error is not necessarily the one that has the offending `ignore_invalidation_older_than` setting. It seems to use the most recently defined cagg instead of the one with the offending parameter.
**To Reproduce**
```sql
create table testdropchunks (time timestamp, name text, val int8);
select create_hypertable('testdropchunks', 'time');

insert into testdropchunks (time, name, val) VALUES
(now(), 'a', 23),
(now()-interval '3 weeks', 'b', 23);

CREATE VIEW dropmea
WITH ( timescaledb.continuous, timescaledb.ignore_invalidation_older_than = '2400 hours')
AS
    SELECT time_bucket('1day', time), avg(val), name
        FROM testdropchunks
        GROUP BY 1, name;
CREATE VIEW dropmez
WITH ( timescaledb.continuous, timescaledb.ignore_invalidation_older_than = '23 hours')
AS
    SELECT time_bucket('1day', time), avg(val), name
        FROM testdropchunks
        GROUP BY 1, name;

select drop_chunks(INTERVAL '1 days', 'testdropchunks', cascade_to_materializations=>false);
```
 

**Expected behavior**
The drop_chunks Should fail with

`ERROR:  older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.dropmea`

**Actual behavior**
The drop_chunks actually fails with

`ERROR:  older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.dropmez`

**Comment by erimatnor** [comment]
TimescaleDB 2.0 will no longer require setting ignore_invalidation_older_than before dropping chunks. In fact, this parameter will no longer exist.
