### ISSUE TITLE
Unsupported continuous aggregate when accounting for counter resets

### ISSUE THREAD

**Issue by franck102** [timescale/timescaledb#2479]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
psql (13.0, server 12.4 (Debian 12.4-1.pgdg100+1))
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.7.4   | public     | Enables scalable inserts and complex queries for time-series data

Installed using timescale-kubernetes helm charts.
promscale Version:0.1.0-beta.5

**Describe the bug**
I am unable to create a continuous aggregate view that stores hourly aggregates of a Prometheus counter metric.
Using the Timescale "Reading Data" docs I came up with this query:

```
CREATE VIEW "service:applications:hourly" WITH
(timescaledb.continuous, timescaledb.refresh_interval = '30 minutes') as
select time_bucket('1 hour', foo.time) bucket, sum(foo.value), foo.labels, foo.series_id
  from (select 
		  time, 
		  labels, series_id,
		  (CASE
		    WHEN value >= lag(value,1,0::DOUBLE PRECISION) OVER w
		      THEN value - lag(value,1,0::DOUBLE PRECISION) OVER w
		    ELSE value
		  END) AS "value"
  		FROM "service:applications:joined" 
  		window w AS (partition by series_id ORDER BY time asc) 
  		order by time asc) 
  	as foo
  group by bucket, labels, series_id
  order by series_id, bucket
```

but this yields:
```
SQL Error [0A000]: ERROR: invalid SELECT query for continuous aggregate
```
** What I would expect **
A more detailed error message, or some documentation that would help us understand what we need to change in the continuous statement to get it accepted.

Hourly (and daily, weekly...) aggregates of counters with resets was our primary motivation for considering TimescaleDB, what would be the recommended way to design this?

[ NB:
The version without a subquery:
```
  select 
  	time_bucket('1 hour', time) bucket, 
  	sum(CASE
	      WHEN value >= lag(value,1,0::DOUBLE PRECISION) OVER w
	        THEN value - lag(value,1,0::DOUBLE PRECISION) OVER w
	      ELSE value
	    END),
    labels,
    series_id
  from "service:applications:joined"
  group by bucket, labels, series_id
  window w AS (partition by series_id ORDER BY time asc)
  order by series_id, bucket
```

yields a different error:

```
SQL Error [42803]: ERROR: aggregate function calls cannot contain window function calls
```
]

**Comment by franck102** [comment]
Trying to break down the query by creating an intermediate view doesn't help:

```
CREATE VIEW "service:applications:increase" AS
select time, labels, series_id, (
    CASE
      WHEN value >= lag(value,1,0::DOUBLE PRECISION) OVER w
        THEN value - lag(value,1,0::DOUBLE PRECISION) OVER w
      ELSE value
    END
  ) AS "increase"
  FROM "service:applications:joined" window w AS (partition by series_id ORDER BY time asc) order by time asc
```

```
CREATE VIEW "service:applications:hourly" WITH
(timescaledb.continuous, timescaledb.refresh_interval = '30 minutes') as
select time_bucket('1 hour', time) bucket, sum(increase), labels, series_id
  from "service:applications:increase"
  group by bucket, labels, series_id
  order by series_id, bucket
```

yields
```
SQL Error [0A000]: ERROR: invalid SELECT query for continuous aggregate
```

**Comment by k-rus** [comment]
@franck102 Continuous aggregates are limited to select only from a hypertable and only one. Subqueries (and views) are not supported. Does it answer your question?

**Comment by franck102** [comment]
> @franck102 Continuous aggregates are limited to select only from a hypertable and only one. Subqueries (and views) are not supported. Does it answer your question?

Not quite, the query below uses a single hypertable and no subqueries, and it fails. Beyond that, how do we create continuous aggregates on counters that can contain resets?


```
select 
  	time_bucket('1 hour', time) bucket, 
  	sum(CASE
	      WHEN value >= lag(value,1,0::DOUBLE PRECISION) OVER w
	        THEN value - lag(value,1,0::DOUBLE PRECISION) OVER w
	      ELSE value
	    END),
    labels,
    series_id
  from "service:applications:joined"
  group by bucket, labels, series_id
  window w AS (partition by series_id ORDER BY time asc)
  order by series_id, bucket
```

**Comment by k-rus** [comment]
@franck102 You cannot create a continuous aggregates with ORDER BY, see section restrictions in [the documentation](https://docs.timescale.com/latest/api#continuous_aggregate-create_view). I believe window clauses are also not allowed, since it might require to access data from different group.

Don't you get meaningful error messages?

**Comment by franck102** [comment]
> @franck102 You cannot create a continuous aggregates with ORDER BY, see section restrictions in [the documentation](https://docs.timescale.com/latest/api#continuous_aggregate-create_view). I believe window clauses are also not allowed, since it might require to access data from different group.
> 
> Don't you get meaningful error messages?

No, the only error message I get is the one above.
I hadn't realize that the "<select_query> is of the form :" statement meant nothing but what is listed there is allowed.

This probably means we'll have to give up on continuous aggregates and roll our own pgcron job.
