### ISSUE TITLE
Creating table failed after enabling the timescaledb extension

### ISSUE THREAD

**Issue by ziXet** [timescale/timescaledb#249]
I'm getting "server closed the connection unexpectedly" error after executing the following commands in psql.
```
postgres=# create database test; 
CREATE DATABASE                  
postgres=# create extension timescaledb;
CREATE EXTENSION
postgres=# create table old_table (id integer);                        
CREATE TABLE                                  
postgres=# CREATE TABLE new_table (LIKE old_table);                              
server closed the connection unexpectedly                          
        This probably means the server terminated abnormally       
        before or while processing the request.                    
The connection to the server was lost. Attempting reset: Failed.
```
If I don't enable extension the "CREATE TABLE new_table (LIKE old_table)" would work without any issue. I still can enable the extension after creating the table but it's kinda annoying.

I'm running timescale 0.5 on docker.

**Comment by mfreed** [comment]
Hi @ziXet:  Thanks for the report!  

We pushed a fix to master for this problem a few days ago.  It will be part of the 0.6 release, which should go out later this week.

(I believe this is the PR that fixes the problem:  https://github.com/timescale/timescaledb/pull/230)

**Comment by ryan-shaw** [comment]
@mfreed Is this same issue as what I reported in slack earlier today?

I'm guessing the server crashed with seg fault here.

**Comment by mfreed** [comment]
@ryan-shaw If my memory serves me correctly, I think your issue was slightly different, but this merged PR should fix your problem:  https://github.com/timescale/timescaledb/pull/251

Will be in next release.

**Comment by RobAtticus** [comment]
Feel free to open a new issue with as much detail as you can.
