### ISSUE TITLE
Very Slow Bulk Insert Performance

### ISSUE THREAD

**Issue by RoryMMMM** [timescale/timescaledb#2512]
**Relevant system information:**
 - OS: Ubuntu 20
 - Postgres ver 12
 - TimescaleDB version: 1.7.4
 - Installation method: Docker image tagged timescale/timescaledb-postgis:1.7.4-pg12
- Running on server and allocated 40 cores, 90+ gigs of ram, raided HDD's

**Describe the bug**
When running database inserts from historical data into a tuned, up to date version of TimescaleDB, after several minutes the insert performance on TimescaleDB drops to about 1 row per second. 

**To Reproduce**
1. Start up fresh TimeScaleDB docker image using Docker-Compose file: 
```python
version: '3.2'
services:
  db:
      hostname: ${DB_HOST}
      image: timescale/timescaledb-postgis:${TIMESCALE_TAG}
      shm_size: 12g
      command: postgres -c shared_preload_libraries=timescaledb
      ports:
        - ${DB_EXT_PORT}:${DB_INT_PORT}
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_UID=${UID}
        - POSTGRES_GID=${GID}
      volumes:
        - ${DB_VOLUME}:/var/lib/postgresql/data
        - ./build/db/db_init:/docker-entrypoint-initdb.d/ 
        - ./build/db/db_init_data/:/tmp
        - ./config/tsdb_postgres.conf:/etc/postgresql.conf # Config created by Timescaledb-tuning script
      restart: unless-stopped
      
      stop_grace_period: 2m
      logging:
        driver: json-file
        options:
          max-size: 10m
```

2. Schema is setup on first init of DB. empty GPS data hypertable is created with indexes on GPS ID, GPS Position (postgis geometry) and message timestamp.
3. Optional: Continuous aggregates are created to show last known position for each GPS ID per hour/day. This was disabled in testing and didn't influence performance (that I could see).
4. Insert data using python psycopg2 library every 5 seconds. (Consume messages off rabbitmq, after x seconds insert all messages that have been consumed (generally a couple thousand). 
5. Measure performance by examining uninserted message queue size/rates (from rabbitmq), number of messages inserted (measured in python) and time taken to insert messages (measured in python). 

**Expected behavior**
I'm rebuilding my vanilla Postgres/Postgis DB using Timescaledb in the hopes of getting improved performance and reaping the benefits of continuous aggregates. My data is pretty much GPS points with associated data, a GPS ID and a timestamp. The data is about 1 gig a day, 100 msg per second and spans several years. I'm inserting data by having several workers (1 per historical month) read the raw data files, decoding them and handing over to a batch inserter. I'm expecting the data to arrive at the inserter in a semi-random time order (as in some messages from each month of the year). The inserter then does a bulk insert every couple of seconds and inserts several thousand rows. 

On startup the performance is several thousand rows per second (limited by the decoder) but after about 10 minutes of running insert performance drops considerably and eventually hits 1 row per second on insert (limited by the DB inserter). This is exactly the opposite behaviour as described in the [blog article](https://blog.timescale.com/blog/timescaledb-vs-6a696248104e/). If I run this on vanilla PG then the insert performance is always limited by the data decoder and is rock solid at several thousand per second.  

**Additional context**
Performance is measured by using the RabbitMQ management window which shows the rate that messages are decoded (and added to a message queue) and are inserted (removed off the queue after successful DB insert). 
Is the "unordered" nature of the data causing issues? Is there a better way to insert historical data in a random method (disabling indexes, creating hypertable after all inserts (although the data is around a gig/day)?

**Comment by RoryMMMM** [comment]
Okay, I've reduced the number of workers that are decoding data to 1. In this case the data going into the DB should be ordered in time. In this case I'm not seeing any slow down of inserts (after running for about 30 mins. Usual slow down was after 5-10 mins). So I'm guessing TSDB isn't great at handling unordered time data?

**Comment by davidkohn88** [comment]
Yes in general, you should be backfilling in at least loose time order or else it defeats many of the optimizations we do. Also, you should make sure you're using bulk inserts via the`execute_values` routine with psycopg2 or with a copy command.

**Comment by davidkohn88** [comment]
I'm going to close this, but if you need further info feel free to reopen. 
You can also join our community slack group (slack.timescale.com) to get help with things like this.
