### ISSUE TITLE
How can i test or use on windows?

### ISSUE THREAD

**Issue by ColinUestc** [timescale/timescaledb#252]
i found how to install timescaledb on windows in http://docs.timescale.com/latest/getting-started/installation/windows/installation-docker, but on docker there is not windows image and only has Linux image.

**Comment by mfreed** [comment]
Hi @ColinUestc:

We currently don't have a native build for Windows (although we are actually in the process of supporting such ***).  Right now we only support docker on Windows, where the docker container is actually running Linux internally.  Curious: is there a reason this isn't sufficient for you?

*** https://github.com/timescale/timescaledb/pull/228:  Timescale now compiles correctly in Visual Studio, this will be part of the shortly upcoming 0.6 release.  Full build/makefile support will not appear until the subsequent release, however (we've had to change build systems to support Windows).

**Comment by mfreed** [comment]
Will post updates to this in Issue #4 .
