### ISSUE TITLE
Miscellaneous cleanups

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb#2521]
Few code and API cleanups are good to do before final release of 2.0:

- [x] Remov column `schedule_interval` from `timescaledb_information.continuous_aggregates` view (@k-rus)
- [x] Rename argument `cagg` in `refresh_continuous_aggregate` into `continuous_aggregate` as in `add_continuous_aggregate_policy`. (@k-rus)
- [x] Remove modification time from invalidation log tables (@mkindahl )

**Comment by mkindahl** [comment]
Last item fixed. Closing.
