### ISSUE TITLE
Custom time types broken for hypertables in master

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#2523]
**Describe the bug**
On master branch there seems to have been an overhaul how custom types for timestamps are handled. In 1.x any custom type that was binary coercible was allowed to be a timestamp type. Now, this is only allowed for *implicitly* convertible types. So, somehow this condition has been both relaxed and made stricter at the same time. Non-binary coercible types that are implicitly convertible are allowed now. Binary coercible types that are not implicitly convertible (eg. either assignment or explicit) are now disallowed.
This actually breaks all of our tables as our custom type has a binary coercible, but assignment-level type conversion.

The code in the 2.x branch is like this:
```
/*
 * Try to coerce a type to a supported time type.
 *
 * To support custom time types in hypertables, we need to know the type's
 * boundaries in order to, e.g., construct dimensional chunk constraints. If
 * the type is IMPLICITLY coercible to one of the supported time types we can
 * just use the boundaries of the supported type. Thus, the custom time type
 * will inherit the time boundaries of the first compatible time type found.
 */
static Oid
coerce_to_time_type(Oid type)
{
	static const Oid supported_time_types[] = { DATEOID, TIMESTAMPOID, TIMESTAMPTZOID,
												INT2OID, INT4OID,	  INT8OID };

	int i;

	for (i = 0; i < lengthof(supported_time_types); i++)
	{
		Oid targettype = supported_time_types[i];

		if (can_coerce_type(1, &type, &targettype, COERCION_IMPLICIT))
			return targettype;
	}

	elog(ERROR, "unsupported time type \"%s\"", format_type_be(type));
	pg_unreachable();
}
```

In the 1.7.x branch, it is like this:
```
ts_type_is_int8_binary_compatible(Oid sourcetype)
{
	HeapTuple tuple;
	Form_pg_cast castForm;
	bool result;

	tuple =
		SearchSysCache2(CASTSOURCETARGET, ObjectIdGetDatum(sourcetype), ObjectIdGetDatum(INT8OID));
	if (!HeapTupleIsValid(tuple))
		return false; /* no cast */
	castForm = (Form_pg_cast) GETSTRUCT(tuple);
	result = castForm->castmethod == COERCION_METHOD_BINARY;
	ReleaseSysCache(tuple);
	return result;
}
```

**To Reproduce**
There is actually a test case in the regression tests that test this behavior. It seems it was altered at the same time this behavior was changed by @erimatnor in https://github.com/timescale/timescaledb/pull/2310/files  (see `test/custom_type.sql.in`). That commit adds an IMPLICIT cast to the custom type that was not there before - probably to make the test case pass with the new behavior.

Can this be changed such that at least it does not break existing databases after an upgrade? This means either changing `coerce_to_time_type` to accept EXPLICIT and/or ASSIGNMENT-level casts:
```
		if (can_coerce_type(1, &type, &targettype, COERCION_EXPLICIT)) // or COERCION_ASSIGNMENT which would fix our particular use case, but maybe there are other types out there that have an EXPLICIT binary compatible cast instead
```

Or changing it in a way that does not call `can_coerce_type` at all, but instead uses a similar check as on the 1.x branch, which only checks for binary coercibility, disregarding implicit/assignment/explicit completely.

**Comment by mfreed** [comment]
Thanks for the detailed report / question, @fvannee .  Team will discuss.

**Comment by fvannee** [comment]
Thanks @mfreed I made a small change to my post above to make clear that in our particular use case it is actually an ASSIGNMENT-level cast. Previously in 1.x IMPLICIT/ASSIGNMENT/EXPLICIT were all allowed. Now, only IMPLICIT is allowed. So for our use case, changing it to allow IMPLICIT/ASSIGNMENT would already work. However, maybe there are other custom types out there which have an EXPLICIT cast, so I'd still be careful about disallowing that.

Secondly, a minor point, the time at which this throws an error is at `INSERT`. It's perfectly possible to call `create_hypertable()` on a table with this custom type. It works. However, the corresponding `INSERT` into this table fails. I'd expect such a check for type compatibility to happen inside `create_hypertable` already. However, as I said, this is a minor point for me.

**Comment by erimatnor** [comment]
@fvannee Let me take a look at this. I recall there being a good reason for the change, but I need to go back and look at the context. Perhaps there was something I overlooked.

**Comment by erimatnor** [comment]
@fvannee can you share the definition of your custom type, in particular the CASTs defined on this type?

**Comment by fvannee** [comment]
Sure, the definition is here: https://github.com/fvannee/timestamp9/blob/master/src/timestamp9.sql

In general, `timestamp9` is binary compatible with Postgres `int8` type. It is counting the number of nanoseconds since an epoch date. We provide some conversions to/from `timestamp(tz)` too, but here of course we should note that the conversion to `timestamptz` actually loses some information, as Postgres `timestamptz` type is microseconds.
The cast that up until now has always been used for computing the time interval is the ASSIGNMENT-level cast to `int8`. We made this ASSIGNMENT, because we want an implicit conversion *from* `int8` to `timestamp9`, but not the other way around.

I think I understand part of your issue now too. Previously, TimescaleDb only supported conversions to `int8` type. This made it easy to make a decision which Timesacle supported type to cast a custom type to, as this was always `int8`. With this commit, it supports conversions to types like `timestamptz` too. However, timestamp9 provides *both* conversions and TimescaleDb should pick the conversion to `int8`, because that one is lossless, while the conversion to `timestamptz` is lossy. If it picks a conversion that users don't expect, the time_chunk_interval parameter will be interpreted in a very strange way, leading to chunks of weird sizes (time_chunk_interval will be an `int8` specifying an interval in number of nanoseconds).

I don't think it's the right solution to only pick `IMPLICIT` type conversions though, because:
- Even IMPLICIT conversions don't guarantee that they are lossless (sometimes lossy conversions might actually be fine for chunking purposes, but at the very least the parameter to `chunk_time_interval` when doing create_hypertable must have a value with a similar unit)
- It doesn't solve the main issue which type Timescale should convert a custom type too. Currently, it converts to the first one it can find. And because this changes from 1.x (always `int8`) to 2.x (`int8` is the last one it checks, so it will never be chosen if another conversion exists) this leads to compatibility issues too.

There are multiple ways around this then.. The simplest, that at least preserves compatibility with previous versions, is:
- Change `COERCION_IMPLICIT` to `COERCION_EXPLICIT`, and
- Change `supported_time_types` and put `int8` *first*, making sure it will be chosen if such a cast exists.
I *think* that preserves behavior from older branches, while also allowing other custom types that don't have casts to `int8`.

It's also worth considering recording the *base type* in catalog tables though. For example, you could think allowing something like (note the difference in how `chunk_time_interval` is specified):
```
-- create a hypertable with 1 hour chunks, using the timestamp9->int8 cast
SELECT create_hypertable('table', 'timestamp9_column', chunk_time_interval=>(1e9::3600)::bigint, base_type=>'int8')

-- create a hypertable with 1 hour chunks, using the timestamp9->timestamptz cast
SELECT create_hypertable('table', 'timestamp9_column', chunk_time_interval=>interval '1h', base_type=>'timestamptz')
```

These are all the casts on timestamp9 (but can also be found in the link above):

```
CREATE CAST (timestamp9 AS timestamptz)
WITH FUNCTION timestamp9_to_timestamptz(timestamp9) AS ASSIGNMENT;

CREATE CAST (timestamptz AS timestamp9)
WITH FUNCTION timestamptz_to_timestamp9(timestamptz) AS IMPLICIT;

CREATE CAST (timestamp9 AS timestamp)
WITH FUNCTION timestamp9_to_timestamp(timestamp9) AS ASSIGNMENT;

CREATE CAST (timestamp AS timestamp9)
WITH FUNCTION timestamp_to_timestamp9(timestamp) AS IMPLICIT;

CREATE CAST (timestamp9 AS date)
WITH FUNCTION timestamp9_to_date(timestamp9) AS ASSIGNMENT;

CREATE CAST (date AS timestamp9)
WITH FUNCTION date_to_timestamp9(date) AS IMPLICIT;

-- this cast is used for timescaledb hypertables
CREATE CAST (timestamp9 AS bigint)
WITHOUT FUNCTION AS ASSIGNMENT;

CREATE CAST (bigint AS timestamp9)
WITHOUT FUNCTION AS IMPLICIT;
```

**Comment by erimatnor** [comment]
@fvannee So, the main issue with casting custom time types is that the cast must also account for differences in the valid time ranges between the source and target type. To be able to, e.g., create correct CHECK constraints on chunks, TimescaleDB needs to know the valid time range of the custom time type. However, the only types it knows the ranges of are the officially supported ones, and therefore wee need to find a cast that works and then assume that the valid time range of the custom type is the same as the officially supported time type. This is the main thing that the referenced PR tried to do.

As an example, a `timestamptz` doesn't use to entire range of an `bigint`. In other words, some values that a `bigint` supports will not translate to valid timestamps. So, while both types use a `bigint` to store information internally, the semantics are quite different; a binary  cast from `bigint` to `timestamptz` may not produce a valid timestamp, although a cast in the opposite direction should produce a valid `bigint` time value. The cast must be done via a function that can also do a check that the value falls within a valid time range. 

I do agree the `IMPLICIT` conversion doesn't guarantee anything around not losing information or being within valid time ranges. We do need a way, however, to identify which of the supported time types the custom type should inherit ranges from. Although this presents issues, as you noted, when there are several possible casts and we are simply picking the first found in a list.

Thinking about it some more, I think the only possible solution here is to either allow custom time types to only support casts from/to one supported time type, or restrict it further so that we always assume the valid time range is always the same as `bigint`. But in that case, we can only support binary casts to `bigint` and no other types.

**Comment by fvannee** [comment]
> ... or restrict it further so that we always assume the valid time range is always the same as bigint. But in that case, we can only support binary casts to bigint and no other types.

That is the 1.x behavior, right? Only supporting custom types that are binary compatible with `bigint`. I'm fine with this behavior, because at least it doesn't break existing setups, but I can imagine you would like to support more custom types for 2.x.

What about adding this extra parameter to `create_hypertable` to let the user explicitly specify the base type to cast to and storing this info in the catalog? For upgrade scripts, you know that if it's a custom type, it must be `int8`, because that's all that was supported up until now. Newer tables should explicitly specify it upon creation. It doesn't solve the issue that the total range of eg. int8 can be different than the custom type if it's a function-style cast, but I guess that's a limitation that most people can live with. These boundaries are usually pretty far off from what people would be storing as data. You could even go as far as also recording minimum and maximum boundaries for the custom type in the catalog, but I'm not sure that is worth the effort.

**Comment by erimatnor** [comment]
@fvannee I think custom time types require further overhaul. Maybe adding a base type like you suggest is one way forward, but, TBH, it is probably not something we're going to do any time soon, and certainly not for the 2.0 release.

I think the main concern now is not breaking previous behavior unless really motivated. I submitted a PR that adds further restrictions to how we treat custom time types and I believe the behavior should now be the same as before: https://github.com/timescale/timescaledb/pull/2544

Would be great if you could verify with your custom time type (I did ran some basic tests myself with you time type, but it is always good to know if it works for your specific setup).

**Comment by fvannee** [comment]
Understandable. Thanks for the PR! I've tested it and it works for me.
One thing that would be really good if you could change it still is the following line in `dimension_interval_to_internal`. It checks whether a dimension interval is valid.

Current:
```
case INTERVALOID:
			if (IS_INTEGER_TYPE(dimtype))
				ereport(ERROR,
						(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
						 errmsg(
							 "invalid interval: must be an integer type for integer dimensions")));
```

Suggested:
```
		case INTERVALOID:
			if (!IS_TIMESTAMP_TYPE(dimtype))
				ereport(ERROR,
						(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
						 errmsg(
							 "invalid interval: must be an integer type for integer or custom type dimensions")));
```

This would then throw an error on `create_hypertable('t1', 'custom_type_column', chunk_time_interval=>interval '1d')`. Since we essentially require that custom types are integer-based types, it makes no sense that it is currently allowed to pass an `interval` type to `create_hypertable`.

**Comment by erimatnor** [comment]
@fvannee I added a commit to fix the check.

**Comment by fvannee** [comment]
Looks good, thanks!
