### ISSUE TITLE
Disable failing retention policies when upgrading to 2.0

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2530]
Prior to 2.0, it was possible to create a continuous aggregate on a hypertable that had a retention policy. This would make the retention policy fail, but this wasn't made clear. It was also possible to add retention policies after creating continuous aggregates, even if those policies wouldn't work due to conflicting `ignore_invalidation_older_than` settings.

Because of the above situation, it is not unlikely that a database that is upgraded to 2.0 will have retention policies running that are in conflict with continuous aggregates and would therefore always fail. If those retention policies are migrated to 2.0 they will start to work, with possibly unintended consequences. Therefore, we should check during extension update to 2.0 for such retention policies and disable them.

**Comment by k-rus** [comment]
One possible approach for disabling is to set `scheduled` to `false` in the migrated retention policy, so it will not run. And in any case it is important to create a note to the user.
