### ISSUE TITLE
Handle NOLOGIN users in multinode setup

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2537]
In a multinode setup, a role created with NOLOGIN on the access node must be created with LOGIN on data nodes so that the access node can connect to data nodes using the role.

However, it would be nice if this was made more transparent by, e.g. having roles be the same on each node and then always connect to data nodes as the session user and switching roles on data nodes in the same way session user and current user differs on the access node.

**Comment by nikkhils** [comment]
This has been handled via the `cloudutils` extension now. Closing.

**Comment by phemmer** [comment]
Can you provide details on this extension? Does it have a web page or repo to find out more about it?
