### ISSUE TITLE
Cagg Fails to Create When time bucket name, group by name, and underlying time column share a name

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#2546]
**Relevant system information:**
 - PostgreSQL version (output of `postgres --version`): 12.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: dnf install

**Describe the bug**
When creating a continuous aggregate, if the time_bucket is named the same as the underlying time column, and then grouped by that column by name, it errors with 

`ERROR:  no valid bucketing function found for continuous aggregate query`

If you use the `1` alias, it works as expected, or if you use a name different from the underlying column. It only fails when all 3 names are the same - the underlying time column, the `AS` name, and the group by name. (example in the reproduction section below)

**To Reproduce**
```sql
create table testcagg (time timestamp, val int);
select create_hypertable('testcagg', 'time');

insert into testcagg (time, val) VALUES
(now(), 1),
(now()-INTERVAL '1 day', 2);

create view cagg_error_test
with (timescaledb.continuous) AS 
select time_bucket(INTERVAL '1 hour', time) as time,
sum(val)
from testcagg
group by time;

create view cagg_doesnt_error_test
with (timescaledb.continuous) AS 
select time_bucket(INTERVAL '1 hour', time) as time,
sum(val)
from testcagg
group by 1;
```

**Expected behavior**
It should create the continuous aggregate.

**Actual behavior**
It fails to create the continuous aggregate with

`ERROR:  no valid bucketing function found for continuous aggregate query`

**Comment by svenklemm** [comment]
This is not a bug and expected. In the group by clause column names take precedence over aliases.

**Comment by tylerfontaine** [comment]
To clarify: This is postgres behavior, not inherent to timescaledb. It's a weird bit of inconsistency, but since it's in Postgress, agreed, not a timescale bug.
