### ISSUE TITLE
i didn't  created  EXTENSION timeseries?

### ISSUE THREAD

**Issue by Barolina** [timescale/timescaledb#2550]
**Relevant system information:**
 - OS: [e.g. Ubuntu 18]
 - PostgreSQL version (output of `postgres --version`): [e.g. 11.9]
 - TimescaleDB version
 - Installation method: [e.g., "apt install]

When  i make create EXTENSION ,  i have this  problem 

```MISTAKE: the" timescaledb " extension does not have an installation or update path defined for version "2.0.0-rc1" ````

**Comment by NeroVanbiervliet** [comment]
See #2549

**Comment by Barolina** [comment]
Thanks,  desided this  problem like  ``` CREATE EXTENSION timescaledb VERSION '1.7.4';```
