### ISSUE TITLE
Too new timescaledb-loader-postgresql-11 uploaded to ppa, unable to CREATE EXTENSION

### ISSUE THREAD

**Issue by WGH-** [timescale/timescaledb#2551]
http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu/dists/xenial/main/binary-amd64/Packages.xz

```
Package: timescaledb-loader-postgresql-11
Source: timescaledb-2-2.0.0-rc1-postgresql-11
Priority: optional
Section: database
Installed-Size: 66
Maintainer: Timescale <hello@timescale.com>
Architecture: amd64
Version: 2.0.0-rc1~ubuntu16.04-1
```

This version is the only timescaledb-loader-postgresql-11 version on the ppa right now.

The problem is that the loader package always tries to enable the latest known extension version, and apparently the new loader was uploaded, but the new TimescaleDB version was not (uploading RC versions that will be installed by default is a questionable thing in itself, but I don't want to discuss it here).

See also #2549 #2550 #2008 https://github.com/timescale/docs.timescale.com-content/issues/415

Workaround: `CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '1.7.4';` (or whatever version that you have installed).

You can also install more specific package called e.g. `timescaledb-1.7.4-postgresql-11` instead of `timescaledb-postgresql-11`, so the `CREATE EXTENSION` command won't be broken in future.

**Comment by svenklemm** [comment]
Packages should be fixed now. Feel free to reopen if the problem persists.
