### ISSUE TITLE
A crashed bug

### ISSUE THREAD

**Issue by cossbow** [timescale/timescaledb#2557]
**Relevant system information:**
 - OS: centos_8_1_x64
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.1
 - Installation method: yum

**Describe the bug**
I create a table like this:
`
create table daily
(
    r_id     bigint ,
    date       timestamp with time zone,
    price      int,
    selling    boolean not null         default true,
    breakfast  int,
    ext        varchar,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone,
    primary key (r_id, date)
);
select create_hypertable('daily', 'date', chunk_time_interval := interval '1 days');
select add_dimension('daily', 'r_id', number_partitions := 16);
`
and I copy data to table too, then my program got error at query "select", the SQL was:
`
select dpp.r_id, dpp.date, dpp.price, dpp.selling         
from daily dpp         
where                           
dpp.r_id in                 
(  ? , ? , ? , ? , ? , ? , ? , ? )                                         
and dpp.date in                 
(  ? , ? )                       
order by dpp.date asc
`
This was PostgreSQL return error message: "An I/O error occurred while sending to the backend."
And I also find in system log detail error(dmesg -T):
`
[Fri Oct 16 18:37:43 2020] postmaster[4535]: segfault at 0 ip 00007f0e38086089 sp 00007fff19225c30 error 4 in timescaledb-1.7.1.so[7f0e38040000+69000]
[Fri Oct 16 18:37:43 2020] Code: 0f 84 aa 00 00 00 48 8b 48 08 48 85 c9 0f 84 9d 00 00 00 31 c0 eb 13 66 2e 0f 1f 84 00 00 00 00 00 48 8b 49 08 48 85 c9 74 3f <49> 8b 36 48 8b 56 08 8b 7a 70 49 8b 57 48 48 8b 14 fa 8b 7a 08 39
[Fri Oct 16 18:37:43 2020] postmaster[4536]: segfault at 0 ip 00007f0e38086089 sp 00007fff19225c30 error 4 in timescaledb-1.7.1.so[7f0e38040000+69000]
[Fri Oct 16 18:37:43 2020] Code: 0f 84 aa 00 00 00 48 8b 48 08 48 85 c9 0f 84 9d 00 00 00 31 c0 eb 13 66 2e 0f 1f 84 00 00 00 00 00 48 8b 49 08 48 85 c9 74 3f <49> 8b 36 48 8b 56 08 8b 7a 70 49 8b 57 48 48 8b 14 fa 8b 7a 08 39
[Fri Oct 16 18:37:48 2020] postmaster[4628]: segfault at 0 ip 00007f0e38086089 sp 00007fff19225c30 error 4 in timescaledb-1.7.1.so[7f0e38040000+69000]
[Fri Oct 16 18:37:48 2020] Code: 0f 84 aa 00 00 00 48 8b 48 08 48 85 c9 0f 84 9d 00 00 00 31 c0 eb 13 66 2e 0f 1f 84 00 00 00 00 00 48 8b 49 08 48 85 c9 74 3f <49> 8b 36 48 8b 56 08 8b 7a 70 49 8b 57 48 48 8b 14 fa 8b 7a 08 39
[Fri Oct 16 18:37:49 2020] postmaster[4629]: segfault at 0 ip 00007f0e38086089 sp 00007fff19225c30 error 4 in timescaledb-1.7.1.so[7f0e38040000+69000]
[Fri Oct 16 18:37:49 2020] Code: 0f 84 aa 00 00 00 48 8b 48 08 48 85 c9 0f 84 9d 00 00 00 31 c0 eb 13 66 2e 0f 1f 84 00 00 00 00 00 48 8b 49 08 48 85 c9 74 3f <49> 8b 36 48 8b 56 08 8b 7a 70 49 8b 57 48 48 8b 14 fa 8b 7a 08 39
[Fri Oct 16 18:37:54 2020] postmaster[4732]: segfault at 0 ip 00007f0e38086089 sp 00007fff19225c30 error 4 in timescaledb-1.7.1.so[7f0e38040000+69000]
......
`
That's all I can find...

**Comment by gayyappan** [comment]
@cossbow Could you try this on a newer version of 1.7 and check if you still have an issue? 
Could you attach a stack trace or core dump if you still have issues?

**Comment by cossbow** [comment]
> @cossbow The error occur on production server,  i recreate table with only timestamp column (It works stabled in this case) at that time. But the coredump was missing now...

**Comment by gayyappan** [comment]
Closing this as we don't have information about the core dump.
Feel free to reopen if you run into this .
