### ISSUE TITLE
Query slow perfomance

### ISSUE THREAD

**Issue by himkool** [timescale/timescaledb#2580]
Os: Centos7
PostgresSQL version: 11
Timescale version: 1.6.0
Installed memory: 64Gb
**Query:**
select q1.*,dataTb.sum ,dataTb.sum_out_raw ,
           dataTb.avg ,dataTb.avg_d_out_er,dataTb.nodeip_interface from
           (select apl.neighbor_address ,apl.neighbor_port_mapping ,itfc.speed,itfc."desc"
           ,apl.ap_name,apl.ethernet_mac,apl.ap_ip_address,apl.controller_name
           ,concat(apl.neighbor_address,':',apl.neighbor_port_mapping)
           from nms.ap_inventory_list apl,nms.node node,   nms.node_snmp_interface itfc
           where node.foreign_id=itfc.node_id and apl.neighbor_address=node.node_ip
           and itfc."desc"=apl.neighbor_port)q1 left outer join
           (select nodeip_interface,sum(sum_in_octets_raw) , sum(sum_out_octets_raw) as sum_out_raw
           , Avg(avg_in_discards) ,Avg(avg_out_discards) AS avg_d_out_er
           from data.daily_interface_aggerigated_data   where time >='2020-09-01 00:00:00'
           AND time < '2020-10-01 00:00:00' and customer='Transnet'
           group by nodeip_interface )dataTb ON dataTb.nodeip_interface like ''||q1.concat||'%'

**Query explain plan:**
Nested Loop Left Join  (cost=471786.63..728745.62 rows=957 width=211)
  Join Filter: (_hyper_118_222621_chunk.nodeip_interface ~~ ((''::text || concat(apl.neighbor_address, ':', apl.neighbor_port_mapping)) || '%'::text))
  ->  Nested Loop  (cost=0.95..82896.35 rows=1 width=115)
        Join Filter: ((apl.neighbor_port)::text = itfc."desc")
        ->  Nested Loop  (cost=0.42..8841.58 rows=1055 width=114)
              ->  Seq Scan on ap_inventory_list apl  (cost=0.00..56.57 rows=1057 width=109)
              ->  Index Scan using node_node_ip_idx on node  (cost=0.42..8.30 rows=1 width=18)
                    Index Cond: ((node_ip)::text = (apl.neighbor_address)::text)
        ->  Index Scan using node_snmp_node_id_pk on node_snmp_interface itfc  (cost=0.53..69.76 rows=35 width=31)
              Index Cond: ((node_id)::text = (node.foreign_id)::text)
  ->  Finalize GroupAggregate  (cost=471785.68..640102.78 rows=191470 width=64)
        Group Key: _hyper_118_222621_chunk.nodeip_interface
        ->  Gather Merge  (cost=471785.68..622870.48 rows=1148820 width=112)
              Workers Planned: 6
              ->  Partial GroupAggregate  (cost=470785.58..482246.50 rows=191470 width=112)
                    Group Key: _hyper_118_222621_chunk.nodeip_interface
                    ->  Sort  (cost=470785.58..472376.62 rows=636415 width=64)
                          Sort Key: _hyper_118_222621_chunk.nodeip_interface
                          ->  Parallel Append  (cost=0.00..361577.42 rows=636415 width=64)
                                ->  Parallel Index Scan using _hyper_118_222621_chunk_daily_interface_aggerigated_data_time_i on _hyper_118_222621_chunk  (cost=0.29..8.31 rows=1 width=63)
                                      Index Cond: (("time" >= '2020-09-01 00:00:00+02'::timestamp with time zone) AND ("time" < '2020-10-01 00:00:00+02'::timestamp with time zone))
                                      Filter: (customer = 'Transnet'::text)

**Comment by mfreed** [comment]
Hi @himkool a few things:

1. Can you perhaps post the report with code block formatting (including for the SQL) so it's easier for folks o review?
1. In general, as it relates to EXPLAIN information, please follow these instructions to provide full information (including ANALYZE, COSTS, BUFFERS, etc.):  https://docs.timescale.com/latest/using-timescaledb/troubleshooting#explain
1. Finally, we unfortunately are not really able to often individual query performance optimization and tuning as github issues.  So unless this appears to be sometype of bug or perhaps incorrect planner decisions -- and if you think so, please identify in your post -- it probably isn't something well-suited for the github issues.  Thanks!
