### ISSUE TITLE
Nested Queries In Aggregate Views?

### ISSUE THREAD

**Issue by suparnlele** [timescale/timescaledb#2585]
Hi,
create view test_nested_query_view
WITH (timescaledb.continuous, timescaledb.refresh_lag = '0 hour', timescaledb.refresh_interval = '1 hour') AS
SELECT time_bucket(INTERVAL '1 hour', a.timestamp) AS timestamp, max(a.data) as data
from (select * from test)a group by time_bucket(INTERVAL '1 hour', timestamp);

This Query gives Error **invalid SELECT query for continuous aggregate**

So do such nested queries valid for continuous aggregates?

**Comment by gayyappan** [comment]
@suparnlele https://docs.timescale.com/latest/api#continuous_aggregate-create_view
The syntax specifies the use of a <hypertable>.  Subqueries are not supported.
