### ISSUE TITLE
Undefined file: 7 ERROR: could not access file "$libdir/timescaledb-tsl-1.7.0": No such file or directory

### ISSUE THREAD

**Issue by swiffer** [timescale/timescaledb#2587]
**Relevant system information:**
 - Docker: timescale/timescaledb:2.0.0-rc2-pg12
 - PostgreSQL version (output of `postgres --version`): 12
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0-rc2
 - Installation method: using Docker

**Describe the bug**
After upgrading to timescaledb 2.0.0-rc2 (docker image) im getting this error:

Undefined file: 7 ERROR: could not access file "$libdir/timescaledb-tsl-1.7.0": No such file or directory

**To Reproduce**

**Expected behavior**
A clear and concise description of what you _expected_ to happen.

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**

**Additional context**

**Comment by svenklemm** [comment]
Not all files for 1.7.0 were initially included in the docker images, i've rebuilt the images with 1.7.0 included. You can either use 1.7.4 image as intermediate step or redownload rc2 image which has the files now and try again.

**Comment by svenklemm** [comment]
Should be fixed in current docker images. Feel free to reopen if the issue persists.
