### ISSUE TITLE
Can I modify the type of "time"

### ISSUE THREAD

**Issue by fan233** [timescale/timescaledb#2590]
**Relevant system information:**
 - OS:  Windows 10 x64, etc
 - PostgreSQL version 12.4.1
 - TimescaleDB version 1.7.1

Hi, The type of 'time' on the document is 'timestamptz', Can I use 'int' to replace 'timestamptz'? Whether there will be other effects?

**Comment by mfreed** [comment]
You cannot ALTER your time column in this regard, as it would change all the definitions of chunk constraints.  To take the desired step, you should create a new hypertable and migrate your data.

(Note, in general, various features are easier to use when using a timestamp/timestamptz field.  See https://docs.timescale.com/latest/api#set_integer_now_func for example.

**Comment by fan233** [comment]
> You cannot ALTER your time column in this regard, as it would change all the definitions of chunk constraints. To take the desired step, you should create a new hypertable and migrate your data.
> 
> (Note, in general, various features are easier to use when using a timestamp/timestamptz field. See https://docs.timescale.com/latest/api#set_integer_now_func for example.

Thank you i get it.
