### ISSUE TITLE
drop_chunks needs to accept BIGINT

### ISSUE THREAD

**Issue by jgraichen** [timescale/timescaledb#260]
The `drop_chunks` functions should accept `BIGINT` like other timescale functions instead of just `INTEGER`.

I have several hypertables chunked on a `BIGINT` column (nanoseconds). Previously I had to use `_timescaledb_internal.drop_chunks_older_than` that accepted `BIGINT` values. Unfortunately the `drop_chunks` added in #231 only accept `INTEGER`. As of now I have reverted to use `_timescaledb_internal.drop_chunks_impl` directly.

**Comment by RobAtticus** [comment]
Thanks for the report, we just merged https://github.com/timescale/timescaledb/pull/261 so the next release should have this fixed

**Comment by RobAtticus** [comment]
Hey @jgraichen , don't know if you saw but this was released in 0.7.0 last week.

**Comment by jgraichen** [comment]
I've updated the extension and application and have not seen any issues. Thanks!
