### ISSUE TITLE
Continuous aggregate without policies get updated when chunks are dropped from the hypertable

### ISSUE THREAD

**Issue by gayyappan** [timescale/timescaledb#2609]
Applicable to master ( and 2.0 rc )
 Continuous aggregate is setup without a policy. When chunks are dropped from underlying hypertable, the continuous aggregate data is occasionally updated.
The data should be updated only for applicable policy ranges.

CREATE OR REPLACE FUNCTION test_int_now() returns INT LANGUAGE SQL STABLE as
    $$ SELECT 125 $$;

CREATE TABLE conditionsnm(time_int INT NOT NULL, device INT, value FLOAT);
SELECT create_hypertable('conditionsnm', 'time_int', chunk_time_interval => 10);

INSERT INTO conditionsnm
SELECT time_val, time_val % 4, 3.14 FROM generate_series(0,100,1) AS time_val;

SELECT set_integer_now_func('conditionsnm', 'test_int_now');

CREATE MATERIALIZED VIEW conditionsnm_4
    WITH (timescaledb.continuous, timescaledb.materialized_only = TRUE)
    AS
        SELECT time_bucket(7, time_int) as bucket,
            SUM(value), COUNT(value)
        FROM conditionsnm GROUP BY bucket WITH DATA;

CREATE VIEW see_cagg AS SELECT * FROM conditionsnm_4 WHERE bucket < 40 ORDER BY bucket;

**Comment by gayyappan** [comment]
```
test=#select drop_chunks('conditionsnm', 20);
                drop_chunks                
-------------------------------------------
 _timescaledb_internal._hyper_17_152_chunk
 _timescaledb_internal._hyper_17_153_chunk
(2 rows)

test=# SELECT * FROM see_cagg;  <---------------------- no change after 1st drop 
 bucket |  sum  | count 
--------+-------+-------
      0 | 21.98 |     7
      7 | 21.98 |     7
     14 | 21.98 |     7
     21 | 21.98 |     7
     28 | 21.98 |     7
     35 | 21.98 |     7
(6 rows)

test=# SELECT drop_chunks('conditionsnm',  30);
                drop_chunks                
-------------------------------------------
 _timescaledb_internal._hyper_17_154_chunk
(1 row)

test=# SELECT * FROM see_cagg;
 bucket |  sum  | count 
--------+-------+-------
      0 | 21.98 |     7
      7 | 21.98 |     7
     14 |  3.14 |     1   <------------- cagg data change.
     21 | 21.98 |     7
     28 | 21.98 |     7
     35 | 21.98 |     7
(6 rows)

```

**Comment by gayyappan** [comment]
Related to  issue #2592

**Comment by erimatnor** [comment]
Closing since PR was merged.
