### ISSUE TITLE
Old data is not being automatically dropped after add_drop_chunks_policy is applied

### ISSUE THREAD

**Issue by hartmutbehrens** [timescale/timescaledb#2611]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: apt install

**Describe the bug**
A automatic data retention policy was applied to a table as follows:
`SELECT add_drop_chunks_policy('timeseries.base', INTERVAL '32d');`

Compression was also enabled on the table using the following command:
`
ALTER TABLE timeseries.base SET (timescaledb.compress, timescaledb.compress_orderby = 'time DESC', timescaledb.compress_segmentby = 'tag');
SELECT add_compress_chunks_policy('timeseries.base', INTERVAL '7d');
`

However, when doing the following query, the `timeseries.base` table is shown to have more than 32 days worth of data:
`
 select distinct(date(time)) from timeseries.base where tag = 'some_tag_name';
`

**To Reproduce**
1. Create table:
`
CREATE TABLE timeseries.base (
  tag      TEXT NOT NULL,
  time     TIMESTAMPTZ NOT NULL,
  value    TEXT,
  status   BOOLEAN,
  timestep TEXT,
  constraint pk_tag_time primary key(tag, time));
`
`
SELECT create_hypertable('timeseries.base', 'time');
`
2. Add compression and data retention policies:
`
ALTER TABLE timeseries.base SET (timescaledb.compress, timescaledb.compress_orderby = 'time DESC', timescaledb.compress_segmentby = 'tag');
`
`
SELECT add_compress_chunks_policy('timeseries.base', INTERVAL '7d');
`
`
SELECT add_drop_chunks_policy('timeseries.base', INTERVAL '32d');
`
3. Accumulate more than 32 days worth of data.
4. Check that data older than 32 days is not being dropped:
`
 select distinct(date(time)) from timeseries.base where tag = 'some_tag_name';
`

**Expected behavior**
Data older than 32 days is dropped.

**Actual behavior**
Data older than 32 days is NOT being dropped.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mfreed** [comment]
Hi @hartmutbehrens  A clarification of `drop_chunks` and associated policies is that it only effects chunks whose _ending time_ is before the requested threshold, not all individual rows whose timestamps are < threshold.  

So if you had 2 chunks, the first from [50 days earlier, 40 days earlier] and the second from [40 days earlier, 30 days earlier], and you call `drop_chunks(hypertable, INTERVAL '32d')`, then it should drop the first chunk but leave the second chunk.

Can you clarify what you are seeing with that information?

**Comment by NunoFilipeSantos** [comment]
@hartmutbehrens if you can add more information, feel free to reopen this issue.
