### ISSUE TITLE
Conversion of cagg refresh arguments to smallint fails

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb#2614]
**Relevant system information:**
 - OS: MacOS
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 2.1.0-dev
 - Installation method: source

**Describe the bug**
Calling `refresh_continuous_aggregate` on time column of type `smallint` always fails due to implicit conversion error.

**To Reproduce**
```sql
CREATE TABLE smallint_tab (a smallint);
SELECT table_name FROM create_hypertable('smallint_tab', 'a', chunk_time_interval=> 10);
CREATE OR REPLACE FUNCTION integer_now_smallint_tab() returns smallint LANGUAGE SQL STABLE as $$ SELECT coalesce(max(a)::smallint, 0::smallint) FROM smallint_tab ; $$;
SELECT set_integer_now_func('smallint_tab', 'integer_now_smallint_tab');
CREATE MATERIALIZED VIEW mat_smallint( a, countb )
WITH (timescaledb.continuous, timescaledb.materialized_only=true)
as
SELECT time_bucket( SMALLINT '1', a) , count(*)
FROM smallint_tab
GROUP BY 1 WITH NO DATA;
call refresh_continuous_aggregate('mat_smallint',  3, 33);
```
**Expected behavior**
It is preferable that `refresh_continuous_aggregate` is successfully executed.

**Actual behavior**
The call leads to error:
```
ERROR:  invalid type of time argument
HINT:  The argument type should be compatible with type "smallint".
```

**Comment by erimatnor** [comment]
It is not possible to implicitly convert a 32 bit value to a 16 bit value. The same applies to converting a 64-bit value to a 32 bit or 16 bit value since it could be out of range.

To make this work we'd have to add special code to check that the larger integer is within range of the smaller integer and I am not sure this is worth it.
