### ISSUE TITLE
Using NOW() or CURRENT_TIMESTAMP gives "Error: cannot update/delete rows from chunk as it is compressed"

### ISSUE THREAD

**Issue by rhaenni** [timescale/timescaledb#2623]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version 12.2
 - TimescaleDB version 1.7.4
 - Installation method: windows binary setup

**Describe the bug**
Table with primary key as timestamp and chunk interval 14 days and compression enabled for chunks older than 30 days. Correctly shows latest 3 chunks (containing data less than 30 days old) being uncompressed. Trying to update data in uncompressed chunks results in  "Error: cannot update/delete rows from chunk as it is compressed" when using NOW() or CURRENT_TIMESTAMP but works fine when using hardcoded time strings.
 
FAILS: ```update lots_ht set removeddate=now() where removeddate is null and created_at > NOW() - INTERVAL '5 DAY' ```
FAILS: ```update lots_ht set removeddate=CURRENT_TIMESTAMP where removeddate is null and created_at > CURRENT_TIMESTAMP - INTERVAL '5 DAY' ```

WORKS: ```update lots_ht set removeddate='2020-11-05' where removeddate is null and created_at > '2020-11-01' ```

**To Reproduce**
1. Create Hypertable chunked by primary key timestamp
2. Enable compression for chunks older than X days
3. Try to update data in uncompressed chunks using NOW() or CURRENT_TIMESTAMP as primary key constraints

**Expected behavior**
NOW() and CURRENT_TIMESTAMP working correctly to UPDATE data in uncompressed chunks

**Actual behavior**
NOW() and CURRENT_TIMESTAMP throwing error when trying to update data in uncompressed chunks

**Comment by mfreed** [comment]
I worked with @rhaenni on this issue and workaround tonight in Slack.  

My guess issue is because `NOW()` doesn't use planning-time constraint exclusion and thus hits compressed chunks as well, and why using a fixed timestamp is fine.

**Comment by k-rus** [comment]
> My guess issue is because `NOW()` doesn't use planning-time constraint exclusion and thus hits compressed chunks as well, and why using a fixed timestamp is fine.

Correct, `now()` doesn't allow to exclude compressed chunks during query planning time.

**Comment by mfreed** [comment]
@k-rus Yes, I just think we should explore whether there is an easier work-around, given the UX implications.

**Comment by Firaenix** [comment]
Any updates or found any work arounds?

**Comment by svenklemm** [comment]
This should work with the now() optimization added in 2.7.0 https://github.com/timescale/timescaledb/pull/4340
