### ISSUE TITLE
When select 1 day, timestamp always start at 8 a.m

### ISSUE THREAD

**Issue by komorebi-san** [timescale/timescaledb#2629]
When I query for multiple days, lets say 2020-Nov-04 to 2020-Nov-09, timescale always start with 08:00 instead of 00:00 

```
select time_bucket('1 day',datetime) as timestamp, 
max(d15) - coalesce(lag(max(d15)) over (order by max(d15)))
as value 
from logging 
where datetime > '2020-11-04 00:00:00' 
GROUP BY timestamp order by timestamp asc;
```

![image](https://user-images.githubusercontent.com/8327827/98551560-69e7a080-22d8-11eb-88db-3965f465130c.png)

**Comment by shane-axiom** [comment]
Results are in your local time zone.

https://www.postgresql.org/docs/12/datatype-datetime.html
