### ISSUE TITLE
Installing via homebrew fails on Error: Empty installation

### ISSUE THREAD

**Issue by simPod** [timescale/timescaledb#263]
Hello. I'm trying to install timescaledb using homebrew:
```
~ $ brew tap timescale/tap

~ $ brew install timescaledb

==> Installing timescaledb from timescale/tap
==> Downloading https://timescalereleases.blob.core.windows.net/homebrew/timescaledb-0.6.0.tar.gz
######################################################################## 100.0%
==> make
==> make install DESTDIR=/private/tmp/timescaledb-20171018-56271-u8weta/timescaledb/stage
Warning: tried to install empty array to /usr/local/Cellar/timescaledb/0.6.0/lib/postgresql
Warning: tried to install empty array to /usr/local/Cellar/timescaledb/0.6.0/share/postgresql/extension
Error: Empty installation
```
I'm not sure the error is in my system. 

Might be related to https://github.com/timescale/timescaledb/issues/82

**Comment by RobAtticus** [comment]
Can you check what version of Homebrew you have?:
`brew --version`

Alternatively you could try updating to the latest Homebrew regardless (`brew update`) and seeing if that helps.

**Comment by RobAtticus** [comment]
Actually I am seeing the same issue on my machine, will investigate!

**Comment by simPod** [comment]
(It's 
```Homebrew 1.3.5
Homebrew/homebrew-core (git revision 5ec9c; last commit 2017-10-17)``` in other words latest)

Cool thanks!

**Comment by simPod** [comment]
The change must be somewhere here https://github.com/timescale/timescaledb/compare/c54dd6fd0866285ec9d0a1d28c080f19ac4bebe4...master

I suspect a change about makefiles. Tried to install from source using `make` but had no succes either

**Comment by RobAtticus** [comment]
Is that because you were upgrading from 0.4.1? When I run `brew install -v timescaledb` it seems to compile fine, it's the last step where it puts the resulting files in place that seems to have issues. I'm thinking it might be an issue with the change in brew of the formula from `postgresql` to `postgresql@9.6` but I'm not sure yet.

**Comment by simPod** [comment]
I had it uninstalled before installing via brew.

When installing from source, `make install` failed for me to but I'm currently unable to replicate because I upgraded postgres to 10 few hours ago.

**Comment by RobAtticus** [comment]
Thanks for this @simPod , I found that our formula was no longer doing the right thing on new versions of Homebrew. I've pushed an updated formula (as 0.6.0-1) and it should update/install correctly now. Let me know if you still have problems, otherwise feel free to close :)

**Comment by RobAtticus** [comment]
I will note that TimescaleDB does not currently work with PG10

**Comment by simPod** [comment]
I'm well aware of no PSQL10 support :). Will try it tomorrow and close eventually. Thanks!

**Comment by RobAtticus** [comment]
Cool just making sure. We are testing it out now that PG10 is released and hopefully we will have more on that soon!

**Comment by RobAtticus** [comment]
Reopening because my fix did not fully fix the problem.

**Comment by RobAtticus** [comment]
I have pushed a new fix, @simPod if you could test and see if it works, let me know.

**Comment by RobAtticus** [comment]
Closing for now because I believe it works, but feel free to reopen if something fails.

**Comment by simPod** [comment]
Works for me!
