### ISSUE TITLE
JIT performs poorly on multinode

### ISSUE THREAD

**Issue by WireBaron** [timescale/timescaledb#2633]
When considering multinode queries, we often produce plans with fairly expensive custom DataNodeScan nodes.  It is not uncommon for these values to be high enough to trigger JIT if JIT is enabled (which it is by default starting in PG12).

There are two problems with this.  First, our costing for multinode operations is artificially high to encourage Postgres to minimize the amount of rows transferred, so the JIT thresholds aren't necessarily accurate for these plans.  More importantly though, the costly work here is being done on the remote node, so there's no benefit to performing JIT on the access node for these types of plans.

This issue is magnified by unexpectedly high overhead being imposed by JIT on multinode queries.  Consider the TSBS cpu-max-all-8 benchmark as an example where we see approximately 160ms of JIT time being added to queries that only need ~40ms to run.

An obvious solution to this seems to be discouraging or disabling JIT on access nodes, but this might negatively impacts plans which require the AN to do some heavy processing on data after it fetches it from the data nodes.  There we may actually see a significant benefit from JIT.  A better solution would be if we could break the cost of a plan into it's local and remote components, and only apply JIT if the local cost exceeds the JIT thresholds.  However, this approach seems like it may be complicated to implement in Postgres.

**Comment by NunoFilipeSantos** [comment]
@WireBaron which TimescaleDB version are you using?

**Comment by svenklemm** [comment]
multinode has been removed
