### ISSUE TITLE
Compile error message "fatal error: openssl/ssl.h" on debian10 Arm64

### ISSUE THREAD

**Issue by aprilyush** [timescale/timescaledb#2634]
Compile the source code on raspberryPI4,The operating system is Debian 10. Postgresql-12-dev  
  
# Bootstrap the build system
`./bootstrap -DUSE_OPENSSL=0 -DREGRESS_CHECKS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`  

Error message：  
 `[ 91%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/connection.c.o
In file included from /usr/include/postgresql/12/server/libpq/libpq.h:20,
                 from /root/timescaledb/tsl/src/remote/connection.c:19:
/usr/include/postgresql/12/server/libpq/libpq-be.h:23:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
`

**Comment by svenklemm** [comment]
This is for an old version and the referenced code has been removed a while ago.
