### ISSUE TITLE
compress_chunk() fails with timeout on distributed chunk

### ISSUE THREAD

**Issue by pmwkaa** [timescale/timescaledb#2645]
``` SQL
select compress_chunk('_timescaledb_internal._dist_hyper_20_30_chunk');
ERROR:  async operation timed out
```

Source of the problem:

When executing remote function we expect it to finish within 1 hour, using hard-coded timeout value: https://github.com/timescale/timescaledb/blob/master/tsl/src/remote/async.h#L140 and then downgrade it to 1 min here: https://github.com/timescale/timescaledb/blob/master/tsl/src/remote/async.c#L644

**Comment by erimatnor** [comment]
Related to #2646
