### ISSUE TITLE
2.0.0-rc3 compilation appears to expect private postgresql headers

### ISSUE THREAD

**Issue by undisputed-seraphim** [timescale/timescaledb#2648]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12, 13.1
 - TimescaleDB version (output of `\dx` in `psql`): git 2.0.0-rc3
 - Installation method: source

**Describe the bug**
Running bootstrap cmake fails with message that `/usr/include/postgresql/12/server/nodes/parsenodes.h` can't be found.

```
CMake Error at src/build-defs.cmake:43 (file):
  file failed to open for reading (No such file or directory):

    /usr/include/postgresql/12/server/nodes/parsenodes.h
Call Stack (most recent call first):
  src/CMakeLists.txt:74 (include)


CMake Error at src/build-defs.cmake:44 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  src/CMakeLists.txt:74 (include)
```

On Ubuntu 20.04, I have libpq-dev and libpq5 installed, as well as the OS provided package for postgresql 12.

**To Reproduce**
1. Have Ubuntu 20.04, have libpq5, libpq-dev and postgresql installed.
2. Clone the repository at tag `2.0.0-rc3`
3. Run `./bootstrap -DREGRESS_CHECKS=OFF`
4. It fails

**Expected behavior**
CMake configures the project successfully.

**Actual behavior**
CMake fails configuration because it can't find certain files..

**Additional context**
It seems that the repository expects the source code of postgresql to be available somewhere, not just the dev headers.
Is that expected behavior? [It is not in the documentation](https://docs.timescale.com/latest/getting-started/installation/debian/installation-source) (install method 'source', PostgreSQL 12), which simply says "A standard PostgreSQL 12 installation with development environment (header files)".

So I have this standard installation and headers, but the source code is looking for other headers not visible to the user.

**Comment by k-rus** [comment]
@undisputed-seraphim Have you installed development headers of PostgreSQL? It is required for building any version of TimescaleDB. See the reader and docs/BuildSource.md

**Comment by undisputed-seraphim** [comment]
Hi, yes, I am sorry, it appears that the package I needed was `postgresql-server-dev-12`.
I couldn't find it before because I was looking for a "libpostgres..."-named library.
Compilation works now.

I will close this.
