### ISSUE TITLE
compression_settings view does not report information for compressed hypertables

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb#2660]
**Relevant system information:**
 - OS: macos docker `timescale/timescaledb:2.0.0-rc2-pg12`
 - PostgreSQL version: 12
 - TimescaleDB version: 2.0.0-rc2
 - Installation method: docker

**Describe the bug**
`timescaledb_information.compression_settings` does not display information for distributed hypertables.

**To Reproduce**
1. Create a distributed hypertable
2. Enable compression by running `ALTER TABLE ... SET (timescaledb.compress, ...)`
3. `SELECT * FROM timescaledb_information.compression_settings`

**Expected behavior**
The distributed hypertable should have an entry in the `compression_settings` view.

**Actual behavior**
The distributed hypertable does not have an entry in the `compression_settings` view.

**Additional context**
Example output
```SQL
> ALTER TABLE prom_data.test SET (
>    timescaledb.compress,
>    timescaledb.compress_segmentby = 'series_id',
>    timescaledb.compress_orderby = 'time, value'
> );
ALTER TABLE

> select * from timescaledb_information.compression_settings;
(0 rows)
```

**Comment by erimatnor** [comment]
I think this is basically a result of the same limitation that causes #2660
