### ISSUE TITLE
Can't change schema of hypertable with compression, even with all chunks in decompressed state.

### ISSUE THREAD

**Issue by arnevanacker** [timescale/timescaledb#2663]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`):12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0-rc3
 - Installation method: apt install

**Describe the bug**
Trying to add a column or index to a hypertable which has compression enabled errors out: "ERROR:  operation not supported on hypertables that have compression enabled"
Decompressing all chunks, pausing the compression policy and even deleting it don't solve the error.

**To Reproduce**
1. Enable compression on hypertable 'temp'
2. Wait for chunks to be compressed: chunk_compression_stats() to verify
3. Manually decompress all chunks: SELECT decompress_chunk(i) from show_chunks('temp') I;
4. Pause policy: SELECT alter_job(<job_id>, scheduled => false);
5. Try adding column: alter table temp add column col1 int;
6. See error
7. Remove policy: SELECT remove_compression_policy('temp');
8. Try adding column: alter table temp add column col1 int;
9. See error

**Expected behavior**
The alter table statement (adding a column, index or constraint) should be executed.

**Actual behavior**
Statement errors out with: "ERROR:  operation not supported on hypertables that have compression enabled"

**Additional context**
I was trying to optimise queries by changing and adding indexes to the hypertable and reached out via Slack.

**Comment by gayyappan** [comment]
@arnevanacker  Could you try disabling compression and then modify the schema?  
```ALTER TABLE <table_name> set (timescaledb.compress=false); ```

**Comment by arnevanacker** [comment]
> @arnevanacker Could you try disabling compression and then modify the schema?
> `ALTER TABLE <table_name> set (timescaledb.compress=false);`

That did the trick for me.
To be clear: I followed your suggestion without undoing the steps I listed in the issue.
I don't know whether only setting this value to false will suffice.

Thank you!

**Comment by gayyappan** [comment]
@arnevanacker  Good to know that worked for you. Yes, you  should disable compression after completing the steps you listed (i.e. decompressing chunks and disabling the policy ).  You will not be able to disable If the hypertable has compressed chunks.

**Comment by mfreed** [comment]
Created github issue in https://github.com/timescale/docs.timescale.com-content/issues/597
