### ISSUE TITLE
How to set a timezone in settings  for timescale?

### ISSUE THREAD

**Issue by Barolina** [timescale/timescaledb#2667]
My postgres  have a timezone 'Europe/MSK and the data is also stored in the same timezone.

How to set a timezone in the settings.
When I make a query with date conversion, I get one set of data. 
When I make a request without converting the date, I get a different request. 
But they must be the same, because the data is already stored in the timezone

**Comment by mfreed** [comment]
TimescaleDB's behavior here are the same as PostgreSQL.  If you are using a timestamptz type -- namely, you /are/ storing timezone information in your table, which we typically recommend -- then it will typically properly convert any timestamps returned based on the timezone specified by your client.

In other words, your client program has timezones settings when it connects to the database, and that will effect the timezone you see in returned data.

https://www.postgresql.org/docs/12/datatype-datetime.html#DATATYPE-TIMEZONES

**Comment by Barolina** [comment]
thanks you
