### ISSUE TITLE
COPY Command not working for large CSV/txt files of 1000000+ rows in Timescaledb rc1

### ISSUE THREAD

**Issue by francesco11112** [timescale/timescaledb#2677]
System Information

OS: Red Hat Enterprise Linux 8  
PostgreSQL 12
Timescale 2.0 rc1
Installation method Rhel/Centos dnf/yum repository install
Multinode info : One Access Node 9 Datanodes
16Gb RAM, 1To HDD, 2 Cores, each node 

BUG DESCRIPTION
When using COPY command on distributed hypertables for datasets of  (1 miilion)  1000000 + rows the command just hangs. No error message and no action or progress noted. Command eventually terminated by pressing 'Ctrl C'

Bacground Information
1) COPY command works on regular tables created on Access node for 1000000 rows
COPY readings FROM '/tmp/output.txt' DELIMITER ',' ;
COPY 6307100
2)  COPY command works on distributed hyper tables created on Access node for small datasets eg iris dataset (with a count column added for time) with 150 rows
COPY iris FROM '/tmp/iris.csv' DELIMITER ',' CSV ;
COPY 150
timeseries=# CREATE TABLE iris2(
timeseries(#   time INTEGER,
timeseries(#   sepal_length DOUBLE PRECISION,
timeseries(#   sepal_width DOUBLE PRECISION,
timeseries(#   petal_length  DOUBLE PRECISION,
timeseries(#   petal_width   DOUBLE PRECISION,
timeseries(#   class  TEXT );
CREATE TABLE
timeseries=# CREATE INDEX ON "iris2"(time DESC, sepal_length);
CREATE INDEX
timeseries=# SELECT create_distributed_hypertable('iris2', 'time', 'class',   chunk_time_interval => 7 );
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values
 create_distributed_hypertable
-------------------------------
(7,public,iris2,t)
(1 row)
timeseries=# COPY iris2 FROM '/tmp/iris_data2.csv' DELIMITER ',' CSV;
COPY 150
timeseries=# SELECT chunk_name, data_nodes
timeseries-# FROM timescaledb_information.chunks
timeseries-# WHERE hypertable_name = 'iris2';
       chunk_name        | data_nodes
-------------------------+------------
 _dist_hyper_7_169_chunk | {node9}
 _dist_hyper_7_170_chunk | {node9}
 _dist_hyper_7_171_chunk | {node9}
 _dist_hyper_7_172_chunk | {node9}
 _dist_hyper_7_173_chunk | {node9}
 _dist_hyper_7_174_chunk | {node9}
 _dist_hyper_7_175_chunk | {node9}
 _dist_hyper_7_176_chunk | {node9}
 _dist_hyper_7_177_chunk | {node2}
 _dist_hyper_7_178_chunk | {node2}
 _dist_hyper_7_179_chunk | {node2}
 _dist_hyper_7_180_chunk | {node2}
 _dist_hyper_7_181_chunk | {node2}
 _dist_hyper_7_182_chunk | {node2}
 _dist_hyper_7_183_chunk | {node2}
 _dist_hyper_7_184_chunk | {node2}
 _dist_hyper_7_185_chunk | {node3}
 _dist_hyper_7_186_chunk | {node3}
 _dist_hyper_7_187_chunk | {node3}
 _dist_hyper_7_188_chunk | {node3}
 _dist_hyper_7_189_chunk | {node3}
 _dist_hyper_7_190_chunk | {node3}
 _dist_hyper_7_191_chunk | {node3}
 _dist_hyper_7_192_chunk | {node3}
(24 rows)

3) INSERT command works on distributed hypertables for a small example taken from Timescale blog  " Building a distributed time-series database on PostgreSQL "

timeseries=# CREATE TABLE measurements (
timeseries(# time TIMESTAMPTZ NOT NULL,
timeseries(# device_id TEXT NOT NULL,
timeseries(#  temperature DOUBLE PRECISION NULL,
timeseries(#   humidity DOUBLE PRECISION NULL
timeseries(# );
CREATE TABLE
timeseries=# CREATE INDEX ON measurements(device_id, time DESC);
CREATE INDEX
timeseries=# SELECT create_distributed_hypertable('measurements', 'time', 'device_id');
 create_distributed_hypertable
-------------------------------
 (6,public,measurements,t)
(1 row)
timeseries=# INSERT INTO measurements VALUES
timeseries-# ('2019-07-01 00:00:00.00-05', 'A001', 70.0, 50.0),
timeseries-# ('2019-07-01 00:00:00.10-05', 'B015', 68.5, 49.7),
timeseries-# ('2019-07-01 00:00:00.05-05', 'D821', 69.4, 49.9),
timeseries-# ('2019-07-01 00:00:01.01-05', 'A001', 70.1, 50.0);
INSERT 0 4
timeseries=# SELECT chunk_name, data_nodes
timeseries-# FROM timescaledb_information.chunks
timeseries-# WHERE hypertable_name = 'measurements';
       chunk_name        | data_nodes
-------------------------+------------
 _dist_hyper_6_166_chunk | {node4}
 _dist_hyper_6_167_chunk | {node2}
 _dist_hyper_6_168_chunk | {node7}
(3 rows)

Preliminary Conclusion
From notes 2 and 3 we see using a distributed hypertable partitioned on time (and space) our commands COPY and INSERT work okay. The datasets ie chunks are distributed over multiple datanodes in the cluster
Thus we can conclude the multinode set up has been done and functions correctly for the 10 node cluster.

To Reproduce the Bug

1) Login to Timescaledb 
Start with a fresh install
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.0.0-rc1

Verify multinode correctly configured with appropriate number of datanodes
Access node host=192.168.1.70

timeseries=# SELECT * FROM timescaledb_information.data_nodes;
 node_name |  owner   |                     options                    
-----------+----------+-------------------------------------------------
 node1     | postgres | {host=192.168.1.71,port=5432,dbname=timeseries}
 node2     | postgres | {host=192.168.1.72,port=5432,dbname=timeseries}
 node3     | postgres | {host=192.168.1.73,port=5432,dbname=timeseries}
 node4     | postgres | {host=192.168.1.74,port=5432,dbname=timeseries}
 node5     | postgres | {host=192.168.1.75,port=5432,dbname=timeseries}
 node6     | postgres | {host=192.168.1.76,port=5432,dbname=timeseries}
 node7     | postgres | {host=192.168.1.77,port=5432,dbname=timeseries}
 node8     | postgres | {host=192.168.1.78,port=5432,dbname=timeseries}
 node9     | postgres | {host=192.168.1.79,port=5432,dbname=timeseries}
(9 rows)
2) Set up schema 
a) CREATE TABLE 
b) CREATE INDEX
c) Create  Distributed hypertable 	
 SELECT create_distributed_hypertable

3) Try out COPY command
Use dataset of 1000000+ rows
COPY readings FROM '/tmp/output_10.csv' DELIMITER ',' CSV ;
4) Actual behaviuor 
COPY command does nothing !  Just hangs
No error message sent to screen (stdout) 
Nothing found in logs

Expected behavior
Simple confirmation of successful copy  (after a short time delay of 1 minute max say for 1000000 rows) eg 
COPY 6307100

I can give more info on system version numbers etc if need be !!

**Comment by mfreed** [comment]
Just to be clear - you see COPY work for smaller file, just not with 1M rows? 

Note that COPY command is single threaded (and transactional), so in general will take significant longer than our parallel copy tool.  And because transactional, you shouldn't see the result by querying the DB until it's completely done.

What happens if you try to use this:

https://github.com/timescale/timescaledb-parallel-copy

**Comment by francesco11112** [comment]
Yes small files are okay but  1M+ rows are not okay !

COPY command was working reasonably in timescaledb-1.7-beta, eg 1M+ rows in 30 secs approx
Now in timescaledb-rc1 it can wait for 30 mins for 1M rows  and still not finish

I have not tried timescaledb-parallel-copy.
Can you use it on the Access node with distributed hypertables ?

**Comment by mfreed** [comment]
Yes, you can write to access node.  Hard to debug what issues you are seeing.  Please also make sure your input CSV is sorted in time order.

**Comment by francesco11112** [comment]
Good News Mike

I tried out timescale-parallel-copy and it worked for a large csv of 6M rows on Timescaledb Multinode rc1
I used the simplest configuration. But when I have some more time I will play around with the lots of "bells and whistles" it has. Unforunately on my set up plain old PostgreSQL COPY command never worked.

I am so grateful for your help

I show the details below 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


timeseries=# CREATE TABLE "temperatures3"(
timeseries(# time TIMESTAMP NOT NULL, value DOUBLE PRECISION,
timeseries(# sensor_id INTEGER
timeseries(# );
CREATE TABLE

timeseries=# SELECT create_distributed_hypertable('temperatures3', 'time');
 create_distributed_hypertable 
-------------------------------
 (17,public,temperatures3,t)
(1 row)

timeseries=# SELECT chunk_name, data_nodes FROM timescaledb_information.chunks WHERE hypertable_name = 'temperatures3';
         chunk_name         | data_nodes 
----------------------------+------------
 _dist_hyper_17_12816_chunk | {node1}
 _dist_hyper_17_12817_chunk | {node2}
 _dist_hyper_17_12818_chunk | {node3}
 _dist_hyper_17_12819_chunk | {node4}
 _dist_hyper_17_12820_chunk | {node5}
 _dist_hyper_17_12821_chunk | {node6}
 _dist_hyper_17_12822_chunk | {node7}
 _dist_hyper_17_12823_chunk | {node8}
 _dist_hyper_17_12824_chunk | {node9}
 _dist_hyper_17_12825_chunk | {node1}
 _dist_hyper_17_12826_chunk | {node2}
 _dist_hyper_17_12827_chunk | {node3}
 _dist_hyper_17_12828_chunk | {node4}
 _dist_hyper_17_12829_chunk | {node5}
 _dist_hyper_17_12830_chunk | {node6}
 _dist_hyper_17_12831_chunk | {node7}
 _dist_hyper_17_12832_chunk | {node8}
 _dist_hyper_17_12833_chunk | {node9}
 _dist_hyper_17_12834_chunk | {node1}
 _dist_hyper_17_12835_chunk | {node2}
 _dist_hyper_17_12836_chunk | {node3}
 _dist_hyper_17_12837_chunk | {node4}
 _dist_hyper_17_12838_chunk | {node5}
 _dist_hyper_17_12839_chunk | {node6}
 _dist_hyper_17_12840_chunk | {node7}
 _dist_hyper_17_12841_chunk | {node8}
 _dist_hyper_17_12842_chunk | {node9}
 _dist_hyper_17_12843_chunk | {node1}
 _dist_hyper_17_12844_chunk | {node2}
 _dist_hyper_17_12845_chunk | {node3}
 _dist_hyper_17_12846_chunk | {node4}
 _dist_hyper_17_12847_chunk | {node5}
 _dist_hyper_17_12848_chunk | {node6}
 _dist_hyper_17_12849_chunk | {node7}
 _dist_hyper_17_12850_chunk | {node8}
 _dist_hyper_17_12851_chunk | {node9}
 _dist_hyper_17_12852_chunk | {node1}
 _dist_hyper_17_12853_chunk | {node2}
 _dist_hyper_17_12854_chunk | {node3}
 _dist_hyper_17_12855_chunk | {node4}
 _dist_hyper_17_12856_chunk | {node5}
 _dist_hyper_17_12857_chunk | {node6}
 _dist_hyper_17_12858_chunk | {node7}
 _dist_hyper_17_12859_chunk | {node8}
 _dist_hyper_17_12860_chunk | {node9}
 _dist_hyper_17_12861_chunk | {node1}
 _dist_hyper_17_12862_chunk | {node2}
 _dist_hyper_17_12863_chunk | {node3}
 _dist_hyper_17_12864_chunk | {node4}
 _dist_hyper_17_12865_chunk | {node5}
 _dist_hyper_17_12866_chunk | {node6}
 _dist_hyper_17_12867_chunk | {node7}
 _dist_hyper_17_12868_chunk | {node8}
 _dist_hyper_17_12869_chunk | {node9}
(54 rows)


[timeseries1@timeseries1 go]$ timescaledb-parallel-copy --db-name "timeseries" --table "temperatures3" --file "/tmp/output_14.csv" --limit 0 --connection "host=192.168.1.70 user=postgres sslmode=disable" --skip-header
COPY 6307195

**Comment by erimatnor** [comment]
I think the issue here might be a memory leak in the COPY path for distributed hypertables. It should be fixed in #2698 and will be part of RC4, coming soon. @francesco11112 it would be great if you could try to load your CSV again with that new release candidate once it is out.
