### ISSUE TITLE
Can't install TimescaleDB on linuxmint  RELEASE=20

### ISSUE THREAD

**Issue by bilelkhedira** [timescale/timescaledb#2687]
**Relevant system information:**
 - OS: [linuxmint RELEASE 20]
 - PostgreSQL version 12
 - TimescaleDB version 1.7 (latest)
 - Installation method: [e.g., "apt install"]

**Describe the bug**
Not supported OS

**To Reproduce**
`bilel@bilel-Inspiron-15-3567:~$ curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.deb.sh | sudo bash
Detected operating system as LinuxMint/ulyana.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/timescale_timescaledb.list...curl: (22) The requested URL returned error: 404 

Unable to download repo config from: https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.list?os=LinuxMint&dist=ulyana&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
`

**System**
`bilel@bilel-Inspiron-15-3567:~$ cat /etc/linuxmint/info 
RELEASE=20
CODENAME=ulyana
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20 Ulyana"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_ulyana_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_ulyana_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 20 Cinnamon
bilel@bilel-Inspiron-15-3567:~$ cat /etc/debian_version
bullseye/sid
`
Thank you in advance

**Comment by NunoFilipeSantos** [comment]
Feel free to reopen it if you can't follow the instructions above.
