### ISSUE TITLE
Make histogram flexible in its choice of aggregation function

### ISSUE THREAD

**Issue by PaulGrimshaw** [timescale/timescaledb#272]
New to timescaledb, but very happy so far!

A common function we need is the histogram function, but being able to specify which aggregate function to use on the value.  It seems the histogram function in timescaledb always does a count, which is of course useful.  However, typically we like to also average the value in the given bin, which makes plotting on graphs very useful.  Is this possible currently?

e.g.
```
SELECT histogram(wind_speed, 0, 30, 30, 'avg')
FROM wind_turbine; 
```

**Comment by mfreed** [comment]
Thanks for the suggestion, @PaulGrimshaw.

(Others:  please upvote if additional interest.)

**Comment by PaulGrimshaw** [comment]
Any other thoughts on this?  It would be very useful, as count is just one (and not overly common) aggregate, and having histogram support others would be very powerful

**Comment by RobAtticus** [comment]
Hey @PaulGrimshaw I've taken a pass at adding this functionality (i.e. adding support for sum, min, max, avg) in the linked PR. Feel free to comment on that PR.

**Comment by RobAtticus** [comment]
I'm going to tentatively assign this 0.9.0 milestone

**Comment by cevian** [comment]
@PaulGrimshaw I am a bit confused, and wanted to clarify, in your example are you both bucketing by wind_speed and taking the average of the wind_speed within the bucket? So if you had a bucket for wind_speeds 1-10, the value of the average would always fall within 1-10? Is this a know statistical/graphing method? Alternatively, do you mean bucketing by one value while averaging another?

**Comment by PaulGrimshaw** [comment]
Yes your first assumption, on the same measure.

Not sure if it's a defined statistical procedure as such, but it's very common.  A standard use is to plot a trend line on an x/y chart to represent the a large amount of scatter. The mini/max/AVG would be different series. The count can then be added on the second axis.

**Comment by cevian** [comment]
Hi @PaulGrimshaw, ok I think I get where this is going. Would it be possible for you to provide an example of the plot? We are still having some difficulties visualizing and a concrete example would be immensely helpful for the docs. Thanks in advance.

**Comment by PaulGrimshaw** [comment]
Hi @cevian , see attached.  I have just superimposed the red "average line" that represents the 1ms binned average value for the plot.  This could also have been point plots, box and whisker, etc.

![image](https://user-images.githubusercontent.com/4194874/35669867-cd577782-0736-11e8-9d47-55cea58d71b2.png)

**Comment by cevian** [comment]
@PaulGrimshaw Hi. Thanks for that example makes things much more clear. Just one point of clarification: the y axis is active power -- is that a variable that is measured separately from wind speed? It seems to me that what you want here is to get a histogram bucketed by `wind speed` but the average is taken of a separate variable `active power` or am i misunderstanding and active power is derived mathematically from wind speed?

**Comment by RobAtticus** [comment]
Also @PaulGrimshaw if you want or think it might be helpful, we are reachable on Slack for more discussion:
http://slack-login.timescale.com/

**Comment by RobAtticus** [comment]
After thinking about it, I think I agree that what you actually want is something like:
```
SELECT histogram(wind_speed, 0, 30, 30, 'avg', active_power)
FROM wind_turbine; 
```

But maybe we're mistaken.

**Comment by PaulGrimshaw** [comment]
Looking at this, you are absolutely right!  Sorry, I made a mistake with how I specified it...

Glad you looked at the chart carefully!

`SELECT histogram(wind_speed, 0, 30, 30, 'avg', active_power)
FROM wind_turbine; ` 

Is exactly what we need!

**Comment by mfreed** [comment]
We had implemented something like this feature, but then concluded that it doesn’t make sense.  Closing this issue until/if there is other demand.
