### ISSUE TITLE
PostgreSQL 13 support

### ISSUE THREAD

**Issue by jprecuch** [timescale/timescaledb#2721]
**Relevant system information:**
 Hi TimescaleDB team. Are there already plans for supporting PostgreSQL 13 version? I couldn't find any note for that yet. 
Any progress or timeline for that? 

**Describe the request**
Add support for Postgresql 13 for timescaledb extension

**Comment by erimatnor** [comment]
Yes, PostgreSQL 13 is being worked on (there's already a draft PR). Targeted for end of January (tentative).

Closing since duplicate of https://github.com/timescale/timescaledb/issues/2434

**Comment by NunoFilipeSantos** [comment]
You can follow our planned efforts regarding PG13 here: https://github.com/timescale/timescaledb/issues/2779
