### ISSUE TITLE
timescaledb_information.chunks is_compressed not reporting correctly on access node

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#2724]
**Relevant system information:**
 - OS: Debian 9
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.4 (Debian 12.4-1.pgdg90+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 2.0.0-rc4
 - Installation method: apt from packagecloud.io

**Describe the bug**
Compressed tables report as `is_compressed=f` on the access node.

**To Reproduce**
```
create table test (time timestamptz, i int);

select create_distributed_hypertable('test','time');

alter table test set (timescaledb.compress);

insert into test values (now(), 1);

select compress_chunk(chunk_schema || '.' || chunk_name) from timescaledb_information.chunks where hypertable_name='test';

select is_compressed from timescaledb_information.chunks where hypertable_name='test';

```

**Expected behavior**
```
 is_compressed 
---------------
 t
(1 row)
```

**Actual behavior**
```
 is_compressed 
---------------
 f
(1 row)
```

**Additional context**
The data node however properly reports the state:
```
# select is_compressed from timescaledb_information.chunks where hypertable_name='test';
 is_compressed 
---------------
 t
(1 row)
```

**Comment by erimatnor** [comment]
For now, the compression status will be reported as NULL for distributed chunks according to this PR: https://github.com/timescale/timescaledb/pull/2742

The function `chunk_compression_stats()` can be used to get information about compressed chunks in the meantime.
