### ISSUE TITLE
Faster views and stats functions for distributed hypertables

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2726]
There are several functions for fetching remote stats and information from data nodes that take a table as argument (e.g., in schema+name) form. When this functions are used in views to get chunk information the view becomes very inefficient since there is often one remote call/query per chunk. A better solution would be to have a a way to push down a condition clause so that one fetches the stats for all chunks queried so that the result can be joined into a view on the access node.

**Comment by svenklemm** [comment]
multinode has been removed
