### ISSUE TITLE
Is upgrading from 0.12.x to 1.7x supported?

### ISSUE THREAD

**Issue by le-duane** [timescale/timescaledb#2745]
Hi,

The documentation only has instructions for upgrading from 1.x. Is upgrading from 0.12.1 supported?

If not, do you know what the recommended upgrade path is? I was looking to go the `ALTER EXTENSION timescaledb UPDATE;` route.

Thanks!

**Comment by k-rus** [comment]
The update of TimescaleDB is supported from 0.9 according to the documentation. See, for example, the version of documentation for [TimescaleDB 1.0](https://docs.timescale.com/v1.0/using-timescaledb/update-db). I believe you will need to have binaries of TimescaleDB for each version between your version and targeted version and they might be already in the extension folder. Also you will need to restart the database before updating to 1.5.0, see [release notes](https://github.com/timescale/timescaledb/releases/tag/1.5.0).

**Comment by le-duane** [comment]
Thanks so much for your response @k-rus!

Given your pointers, I ended up hopping through 1.5.1 to 1.7.1 with a vacuum full in between. This seemed to be the safest route since that was what was supported by the documentation at each version.

**Comment by k-rus** [comment]
I created a PR to clarify upgrade to which versions requires restart: https://github.com/timescale/docs.timescale.com-content/pull/633

Since this issue was answered I close it.
