### ISSUE TITLE
Does adding additional partition columns lead to better performance?

### ISSUE THREAD

**Issue by frnk01** [timescale/timescaledb#2750]
**Relevant system information:**
 - Azure
 - PostgreSQL version 11
 - TimescaleDB version: 1.3.2

Will large tables benefit of having multiple partition columns when running in Azure?

Let`s say a time column and a location column. The location column will probably contain up towards 1000 unique values and the table will in the long term have billions of rows.

Any feedback on this would be much appriciated.

**Comment by mfreed** [comment]
Please see our documentation here:  https://docs.timescale.com/latest/api#add_dimension  Thanks!
