### ISSUE TITLE
[Design advice] One hypertable per object, or one across all objects

### ISSUE THREAD

**Issue by ppseverin** [timescale/timescaledb#2759]
Hi,

I was looking to store and do a little bit of processing of market tick data for 28 different instruments. I started with only 2 instruments and store the data in 2 separate tables (one for each instrument). Now that I want to scale this for 28 instruments, I was reviewing some more efficient options for the database design and schemas. Thats when I came across with TimescaleDB.

I'm looking for suggestions/guidance for a good schema/design of the database. I would like to perform queries fast (1-2 seconds max) without making the VPS explode. Also, since my budget is limited, I prefer working with postgres (and I'm also more familiar with postgres). That's why I think that TimescaleDB is what I'm looking for.

I want to stream insert these market tick data of 28 instruments. With that said, my main question is: should I have one table per instrument or should I have one table for all instruments and use the instrument's name + other fields as indexes and/or primary keys? Which are the pros/cons of each option and which approach is more suittable for this task?

Thank you :)

**Comment by mfreed** [comment]
Hi @ppseverin You might want to see this design discussion around "one hypertable per metric" in our own design for Promscale, which talks about some of these tradeoffs in depth:  https://tsdb.co/prom-design-doc

Having separate hyprtables per instructions given greater flexibility and performance improvements, although a few limitations as well (primarily around much harder to query _across_ instruments in a single query, and probably wouldn't work as well if you started getting into thousands of instruments.

But a great read to start.
