### ISSUE TITLE
Extension does not support `ALTER EXTENSION SET SCHEMA`

### ISSUE THREAD

**Issue by asabil** [timescale/timescaledb#276]
Due to a previous error, I tried relocating the extension to the public schema with the following command:
```sql
ALTER EXTENSION timescaledb SET SCHEMA public;
```

This however fails with this error:
```
ERROR:  extension "timescaledb" does not support SET SCHEMA
```

**Comment by svenklemm** [comment]
Changing the schema of the extension would be very hard as all references to the current schema (eg in function bodies where we use fully qualified schemas)  would need to be adjusted too.
