### ISSUE TITLE
Support `tsrange` and similar time data

### ISSUE THREAD

**Issue by Kheldar** [timescale/timescaledb#277]
I have a use case where the main time column for my data is a `tsrange` - each row has a period during which it's active. 

The main set of queries I need to run on this all centre around "give me all the rows that were active during `time-period`" (i.e. they use the `&&`, `@>` and `<@` operators).

It'd be awesome if you supported partitioning on ranges, as a GIST index alone in Postgres don't give me the performance I need for the data-sizes I'm dealing with.

**Comment by hagmonk** [comment]
My use case is very similar, I have large tables utilizing `tsrange` to represent the timespan during which a particular fact was true. My typical query will join across several of these fact tables using a entity ID, building up a `tsrange` intersection that represents the time range over which *all* these facts were true for a given entity ID. That final `tsrange` can be manipulated in many different ways, such as aggregating across arbitrary window sizes, computing cumulative in/out counts, etc.

Right now I have to hoist all this data into an in-memory data grid to do the joins, as vanilla PostgreSQL (despite many, many optimizations and tricks) can't give us "real time" access to ad-hoc analytics on this data. TimescaleDB sounds really close to what we're after!

**Comment by mfreed** [comment]
Hi @Kheldar I believe this has been addressed with with https://github.com/timescale/timescaledb/pull/639 -- in that it allows you to define your own time functions -- which was part of our 1.1 release.

Closing this issue for now, feel free to re-open if doesn't solve your problems.

**Comment by Swoorup** [comment]
Idk how the pull request solves this problem. Does anyone have an example? tsranges could be variable, how are you using the partitioning function for `tstzrange`, `tsrange`?

**Comment by Swoorup** [comment]
Idk how the pull request solves this problem. Does anyone have an example? tsranges could have varying intervals, i,e a range could span over multiple partitions. How are you using the partitioning function for `tstzrange`, `tsrange`?  
@mfreed

**Comment by ccdavid** [comment]
> Idk how the pull request solves this problem. Does anyone have an example? tsranges could have varying intervals, i,e a range could span over multiple partitions. How are you using the partitioning function for `tstzrange`, `tsrange`? @mfreed
> 
> I have a table like the following, how would i create the hypertable based on `seen` column?
> 
> ```
> create table order_book_events
> (
>     pair text not null,
>     source_id text,
>     seen tsrange not null,
>     is_bid bool not null,
>     price decimal not null,
>     volume decimal not null
> );
> ```
> 
> Should I add upper bound and lower bound as 2 different dimensions?

Having the same problem. Pull request seems unrelated. Did you ever figure out?

**Comment by Swoorup** [comment]
> Having the same problem. Pull request seems unrelated. Did you ever figure out?
I didn't solve it unfortunately and don't think timescale works for this use case, since its based on some points in time and non-interval based.
