### ISSUE TITLE
CMake doesn't propagate CPPFLAGS and LDFLAGS used when building PostgreSQL

### ISSUE THREAD

**Issue by alexeyklyukin** [timescale/timescaledb#2777]
**Relevant system information:**
 - OS: macOS Big Sur 11.1
 - PostgreSQL version (output of `postgres --version`): 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0
 - Installation method: source

**Describe the bug**
Some PostgreSQL configure options make it link against external libraries and use external includes. Typically, PostgreSQL extensions use PGXS mechanism to propagate related CPPFLAGS and LDFLAGS when building extensions against the PostgreSQL version. It seems Timescale doesn't do it in the CMake equivalent.

**To Reproduce**
1. Install PostgreSQL with nls support (in my case, I did brew tap `petere/postgresql && brew install petere/postgresql@12 && brew link postgresql@12`
1. Install timescale from what seems to be the official tap: `brew tap timescale/tap && brew install timescaledb`

**Expected behavior**
`brew install timescaledb` installs timescaledb

**Actual behavior**
The following error is emitted by Homebrew:
```
Last 15 lines from /Users/oleksii/Library/Logs/Homebrew/timescaledb/02.build:
/usr/local/Cellar/postgresql@12/12.5/include/server/c.h:77:10: error: 'libintl.h' file not found [clang-diagnostic-error]
#include <libintl.h>
         ^
2 errors generated.
Error while processing /tmp/timescaledb-20201228-84489-1fvo4gz/timescaledb/tsl/src/data_node_dispatch.c.
make[2]: *** [tsl/src/CMakeFiles/timescaledb-tsl.dir/data_node_dispatch.c.o] Error 1
error: unknown warning option '-Wno-format-truncation' [clang-diagnostic-unknown-warning-option]
/usr/local/Cellar/postgresql@12/12.5/include/server/c.h:77:10: error: 'libintl.h' file not found [clang-diagnostic-error]
#include <libintl.h>
```

On my system, libintl is present at `/usr/local/opt/gettext/include/`; that directory is included in the output of 
`pg_config --cppflags` of the Postgres version I'm building against:
```
pg_config --cppflags
-I/usr/local/Cellar/icu4c/67.1/include -I/usr/local/opt/gettext/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/openldap/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/tcl-tk/include
```

**Additional context**
I'm quite surprised this is not happening more often with headers like readline or icu, or openssl. Perhaps this is also an issue with my system?

I've made a start at resolving this with https://github.com/timescale/timescaledb/pull/2776

**Comment by k-rus** [comment]
Thank you for reporting!

I add a note to relate it to https://github.com/timescale/timescaledb/issues/2770 so they can be fixed together.

**Comment by mkindahl** [comment]
This was fixed in https://github.com/timescale/timescaledb/pull/1505, so closing.
