### ISSUE TITLE
Docs still up-to-date?  Compression not working

### ISSUE THREAD

**Issue by rept** [timescale/timescaledb#2778]
Hi,

I installed AMI on AWS with TimescaleDB 2.0 and Postgres 12.

When I try the following from the docs here: https://docs.timescale.com/latest/using-timescaledb/compression#quick-start

```
CREATE TABLE con_details (LIKE deprecated_consumption_details INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES);

SELECT create_hypertable('con_details', 'date');

ALTER TABLE con_details SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'meter_id'
);

SELECT add_compression_policy('con_details', INTERVAL '7 days');
```

I'm getting

    SQL Error [42883]: ERROR: function add_compression_policy(unknown, interval) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 9

Also functions such as: 

    SELECT * FROM hypertable_detailed_size('con_details')
 
are giving me errors:

    ERROR: function hypertable_detailed_size(unknown) does not exist

**Comment by k-rus** [comment]
@rept Thank you for reporting. Can you run `\dx` in the database you execute the SQL code and post the result?

**Comment by k-rus** [comment]
@rept If I don't mistake there are no AMI with TimescaleDB 2.0. So I guess you are running an older version of TimescaleDB, which has different API.

**Comment by rept** [comment]
```
\dx
                                         List of installed extensions
        Name        | Version |   Schema   |                            Description
--------------------+---------+------------+-------------------------------------------------------------------
 hstore             | 1.6     | public     | data type for storing sets of (key, value) pairs
 pg_stat_statements | 1.7     | public     | track execution statistics of all SQL statements executed
 pgcrypto           | 1.3     | public     | cryptographic functions
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgres_fdw       | 1.0     | public     | foreign-data wrapper for remote PostgreSQL servers
 tablefunc          | 1.0     | public     | functions that manipulate whole tables, including crosstab
 timescaledb        | 1.7.4   | public     | Enables scalable inserts and complex queries for time-series data
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
(8 rows)
```

This is the AMI I used...  

TimescaleDB 2.0.0 (PostgreSQL 12) - Ubuntu 18.04 (EBS Backed) - ami-06479c10b25555960
An Ubuntu 18.04 instance with TimescaleDB installed and running

I don't understand why it's 1.7.4 since the AMI clearly said 2.0.0

![image](https://user-images.githubusercontent.com/1388221/103225373-0ec24980-492a-11eb-9eba-3a7884af33ff.png)

**Comment by k-rus** [comment]
@rept Thank you for the result of `\dx`. It clearly shows that the installed version of TimescaleDB is 1.7.4:

>  timescaledb        | 1.7.4   | public     | Enables scalable inserts and complex queries for time-series data

Thus the API is different than latest.

**Comment by rept** [comment]
> @rept If I don't mistake there are no AMI with TimescaleDB 2.0. So I guess you are running an older version of TimescaleDB, which has different API.

There is an AMI on AWS which states TimescaleDB 2.0.0 while it's in fact 1.7.4 (see previous screenshot).  No idea who maintains these or who put it up.

Thanks for the feedback though! ;-)

**Comment by k-rus** [comment]
@rept I believe the packages will be rebuilt. 
Thank you for reporting!

**Comment by rept** [comment]
Thanks!  Meanwhile I updated to TimescaleDB 2 and now it works of course.

**Comment by rept** [comment]
@k-rus think I found something not up to date in docs: 
https://docs.timescale.com/latest/api#show_chunks

    SELECT show_chunks();

Doesn't work, however if I use

    SELECT show_chunks('conditions');

It does work.  Version 2.0.0.  If you want me to open new issue, let me know.

**Comment by k-rus** [comment]
@rept Thank you! You are right it is not up-to-date. It is not possible to call `show_chunks` without specifying a table name from 2.0.

**Comment by k-rus** [comment]
I will fix it right away. If you find more of them, can you open issues in https://github.com/timescale/docs.timescale.com-content/issues ?

**Comment by rept** [comment]
Will do ;-)

**Comment by k-rus** [comment]
New AMIs were issued.
