### ISSUE TITLE
null geometry value in space x time partition scheme 

### ISSUE THREAD

**Issue by swadey** [timescale/timescaledb#278]
I have a table with time and optional location:
```CREATE TABLE messages (id uuid, time timestamp with time zone, type message_type, user_id uuid, location geometry(POINT, 4326))```

Which is then turned into a hypertable via:

```SELECT create_hypertable('messages', 'time', 'location', 8)```

Insertion of null values on location causes a constraint violation:
``` new row for relation "_hyper_1_2_chunk" violates check constraint "constraint_4"```

Any hints as to how this can be fixed?  A portion of rows in this table will have null values for location.

**Comment by ryan-shaw** [comment]
This looks like it is by design - https://github.com/timescale/timescaledb/pull/259

That pull request checks if the time partition column is set to NOT NULL, and may do the same of a space partition. So it might be better to design your application so that it doesn't have a space partition on the location column, you could add it to the ID column?

**Comment by swadey** [comment]
thx: understood.  This wasn't obvious to me from the docs so I wasn't sure if it was a bug or if it was an unstated assumption.

**Comment by erimatnor** [comment]
@swadey NULL values should be supported on space-partitioned columns. Could you give some more information on your setup and provide a way to reproduce? I couldn't reproduce the problem myself with the information you provided.

**Comment by swadey** [comment]
sure, what information do you need?

I'm running on docker via the official image with postgis.  I can create a time-only partitioned hypertable and ingest successfully.  When I run with the above `create_hypertable` call, I get the constraint violation.

**Comment by mfreed** [comment]
Hi @clime I assume that a SELECT on that data properly shows the NULL value in your evaluation?  If so, I might close our this story as solved.

(Thanks for testing out!)

**Comment by clime** [comment]
> Hi @clime I assume that a SELECT on that data properly shows the NULL value in your evaluation? If so, I might close our this story as solved.
> 
> (Thanks for testing out!)

Hello!

I checked and it does properly show the NULL value for location when selecting.
