### ISSUE TITLE
Add debug symbols to Windows Release build

### ISSUE THREAD

**Issue by k-rus** [timescale/timescaledb#2782]
The supplied binaries of TimescaleDB doesn't contain debug symbols for Windows, which doesn't allow to get the stack trace of a crash. It would be nice to allow getting stack trace on Windows, since some crashes are unique and are not reproduced on other platforms.

**Comment by NunoFilipeSantos** [comment]
@k-rus This looks like a good enhancement for us being able to better debug on Windows.
