### ISSUE TITLE
Failed to create a hypertable for a simple PostgreSQL table

### ISSUE THREAD

**Issue by rebryk** [timescale/timescaledb#2784]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version:12.0
 - TimescaleDB version 2.0.0
 - Installation method: using Docker

**Describe the bug**
Failed to create a hypertable.

**To Reproduce**
```
CREATE TABLE test_table (
    ts int NOT NULL,
    entry int
);

SELECT create_hypertable('test_table', 'ts', chunk_time_interval >= 1000);
```

**Expected behavior**
I expect timescaledb to create the hypertable.

**Actual behavior**
```
ERROR:  column "chunk_time_interval" does not exist
LINE 1: SELECT create_hypertable('test_table', 'ts', chunk_time_inte...
```

**Comment by tylerfontaine** [comment]
`SELECT create_hypertable('test_table', 'ts', chunk_time_interval >= 1000);`

Small typo there, the `>=` is transposed. Try:

`SELECT create_hypertable('test_table', 'ts', chunk_time_interval => 1000);`

**Comment by rebryk** [comment]
Argh. I've spent an hour on this!
Dude, thank you so much😉
