### ISSUE TITLE
Problem building from source on arm64 (apple m1)

### ISSUE THREAD

**Issue by hugojdb** [timescale/timescaledb#2794]
Hi,

I have version 12.5 of postgres using postgres.app:

when doing make install following error happens:

make install
[ 13%] Built target sqlupdatescripts
[ 13%] Built target sqlfile
[ 13%] Linking C shared module timescaledb-2.0.0.so
ld: can't link with a main executable file '/Applications/Postgres.app/Contents/Versions/12/bin/postgres' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/timescaledb-2.0.0.so] Error 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [all] Error 2

Any idea on how to fix this?

Thanks

**Comment by mfreed** [comment]
This somewhat looks like a linking problem against your postgres installation, not TimescaleDB.    Do you have the right "dev" libraries installed for PG?

**Comment by NunoFilipeSantos** [comment]
@hugojdb did you have a chance to check the libraries like Mike suggested?

**Comment by sebastibe** [comment]
Same issue here, trying to build against Postgres.app 12.5 on Mac OS. Any link referring to what are the right "dev" libraries for arm64?

**Comment by NunoFilipeSantos** [comment]
@sebastibe what libs you are using currently?

**Comment by psztoch** [comment]
arm64 architecture should be support by official timescale apt repository!

**Comment by svenklemm** [comment]
ARM64 is supported by our apt repository now.
