### ISSUE TITLE
Continuous aggregation over multiple metrics

### ISSUE THREAD

**Issue by pratapagiri** [timescale/timescaledb#2799]
We store data using multiple metrics (example: pv generation power and wind generation power) in different tables. We have a requirement to compute the total generation power (example: pv+wind). Can someone guide us on how to achieve this?

**Comment by mfreed** [comment]
You can perform a JOIN from the two (hyper)tables, and then just add them together in your SQL query.

(Nothing special to TimescaleDB here, just treat it like standard SQL.  If you are looking for help how to write a SQL statement like this, feel free to also ask on Community slack - github probably not the right forum - thanks!)

**Comment by k-rus** [comment]
Creating a continuous aggregate over several hypertables is not supported and the tracking issue with the request is https://github.com/timescale/timescaledb/issues/1446

**Comment by pratapagiri** [comment]
@mfreed  and @k-rus Thanks for your responses. I was looking for continuous aggregation over multiple hyper tables.
