### ISSUE TITLE
Improve query performance by enabling parallel plans on data nodes

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2807]
The standard way we transfer data between the access node and data nodes is using a CURSOR, which supports large data sets, rewind, and interleaving multiple queries on the same connection (e.g., when doing subqueries and/or joins, multiple cursors can be open over the same connection). However, when executing a query via a cursor, PostgreSQL cannot do parallel execution plans, which slows down query performance compared to a single node instance.

The data fetcher implementation for multi-node supports two modes to fetch data: rowbyrow and cursor. Row-by-row is faster and supports parallel queries on data nodes, but doesn't work for some queries that include sub-queries.

It would be good to have an "auto" mode that picks the best data fetcher depending on the query.

**Comment by akuzm** [comment]
Why the cursors do not support parallel operation: https://www.postgresql.org/message-id/flat/98760523-a0d2-8705-38e3-c4602ecf2448%402ndquadrant.com

In short, execution of cursor can be suspended and a user then can run arbitrary sql, and then resume execution. This kind  concurrency is not safe, postgres doesn't account for it.

**Comment by akuzm** [comment]
And the reason TS needs cursors is to multiplex several subqueries to the same data node on the same connection. This is needed e.g. if we later join these subqueries w/ a nested loop.
