### ISSUE TITLE
Make timescaledb 2.0.0 from source occurs error at catalog.c.o

### ISSUE THREAD

**Issue by thobi85** [timescale/timescaledb#2816]
**Relevant system information:**
 - OS: Docker - ARM64v8-postgres12.5-Alpine 
 - PostgreSQL version: 12.5
 - TimescaleDB version: 2.0.0
 - Installation method: source

**Describe the bug**
I'm trying to make a timescaledb 2.0.0 docker version for arm64v8.
In the creation of timescaledb I get the error shown below with the catalog.c.o

> #9 36.19 -- Build files have been written to: /build/timescaledb/build
> #9 36.22 TimescaleDB build system initialized in ./build. To compile, do:
> #9 36.22 cd ./build && make
> #9 36.22 + cd build
> #9 36.22 + make install
> #9 36.68 Scanning dependencies of target sqlupdatescripts
> #9 36.83 [  1%] Generating /build/timescaledb/build/sql/updates/post-update.sql.processed
> #9 36.95 [  2%] Generating /build/timescaledb/build/sql/timescaledb--2.0.0-rc4--2.0.0.sql
> #9 37.06 [  2%] Generating /build/timescaledb/build/sql/timescaledb--2.0.0-rc3--2.0.0.sql
> #9 37.17 [  3%] Generating /build/timescaledb/build/sql/timescaledb--2.0.0-rc2--2.0.0.sql
> #9 37.29 [  3%] Generating /build/timescaledb/build/sql/timescaledb--2.0.0-rc1--2.0.0.sql
> #9 37.40 [  4%] Generating /build/timescaledb/build/sql/timescaledb--1.7.4--2.0.0.sql
> #9 37.52 [  4%] Generating /build/timescaledb/build/sql/timescaledb--1.7.3--2.0.0.sql
> #9 37.64 [  5%] Generating /build/timescaledb/build/sql/timescaledb--1.7.2--2.0.0.sql
> #9 37.75 [  5%] Generating /build/timescaledb/build/sql/timescaledb--1.7.1--2.0.0.sql
> #9 37.87 [  6%] Generating /build/timescaledb/build/sql/timescaledb--1.7.0--2.0.0.sql
> #9 37.98 [  6%] Generating /build/timescaledb/build/sql/timescaledb--1.6.1--2.0.0.sql
> #9 38.10 [  7%] Generating /build/timescaledb/build/sql/timescaledb--1.6.0--2.0.0.sql
> #9 38.21 [  7%] Generating /build/timescaledb/build/sql/timescaledb--1.5.1--2.0.0.sql
> #9 38.33 [  8%] Generating /build/timescaledb/build/sql/timescaledb--1.5.0--2.0.0.sql
> #9 38.45 [  8%] Generating /build/timescaledb/build/sql/timescaledb--1.4.2--2.0.0.sql
> #9 38.57 [  9%] Generating /build/timescaledb/build/sql/timescaledb--1.4.1--2.0.0.sql
> #9 38.69 [  9%] Generating /build/timescaledb/build/sql/timescaledb--1.4.0--2.0.0.sql
> #9 38.80 [ 10%] Generating /build/timescaledb/build/sql/timescaledb--1.3.2--2.0.0.sql
> #9 38.92 [ 10%] Generating /build/timescaledb/build/sql/timescaledb--1.3.1--2.0.0.sql
> #9 39.04 [ 11%] Generating /build/timescaledb/build/sql/timescaledb--1.3.0--2.0.0.sql
> #9 39.15 [ 11%] Generating /build/timescaledb/build/sql/timescaledb--1.2.2--2.0.0.sql
> #9 39.27 [ 12%] Generating /build/timescaledb/build/sql/timescaledb--1.2.1--2.0.0.sql
> #9 39.39 [ 12%] Generating /build/timescaledb/build/sql/timescaledb--1.2.0--2.0.0.sql
> #9 39.51 [ 13%] Generating /build/timescaledb/build/sql/timescaledb--1.1.1--2.0.0.sql
> #9 39.63 [ 13%] Generating /build/timescaledb/build/sql/timescaledb--1.1.0--2.0.0.sql
> #9 39.75 [ 13%] Built target sqlupdatescripts
> #9 39.90 Scanning dependencies of target sqlfile
> #9 40.03 [ 13%] Generating /build/timescaledb/build/sql/timescaledb--2.0.0.sql
> #9 40.14 [ 13%] Built target sqlfile
> #9 40.31 Scanning dependencies of target timescaledb
> #9 41.93 [ 13%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
> #9 45.77 [ 14%] Building C object src/CMakeFiles/timescaledb.dir/func_cache.c.o
> #9 49.23 [ 14%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
> #9 51.90 [ 15%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
> #9 54.27 [ 15%] Building C object src/CMakeFiles/timescaledb.dir/catalog.c.o
> #9 55.98 In file included from /usr/local/include/postgresql/server/postgres.h:46,
> #9 55.98                  from /build/timescaledb/src/catalog.c:6:
> #9 55.98 In function 'catalog_database_info_init',
> #9 55.98     inlined from 'ts_catalog_database_info_get' at /build/timescaledb/src/catalog.c:364:3:
> #9 55.98 /build/timescaledb/src/catalog.c:344:2: error: 'strncpy' specified bound 64 equals destination size [-Werror=stringop-truncation]
> #9 55.98   344 |  StrNCpy(info->database_name, get_database_name(MyDatabaseId), NAMEDATALEN);
> #9 55.98       |  ^~~~~~~
> #9 59.98 cc1: all warnings being treated as errors
> #9 59.99 make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:135: src/CMakeFiles/timescaledb.dir/catalog.c.o] Error 1
> #9 60.00 make[1]: *** [CMakeFiles/Makefile2:1012: src/CMakeFiles/timescaledb.dir/all] Error 2
> #9 60.00 make: *** [Makefile:150: all] Error 2

When I choice instead of version 2.0.0 the version 1.7.4 everything is working fine.
Has something changed from version 1.7.4 to 2.0.0 ?

If its necessary I can share the Dockerfile with I use to create the Docker image.

regards
thobi

**Comment by k-rus** [comment]
@thobi85 I believe you are hitting the same issue as https://github.com/timescale/timescaledb/issues/2770
The work around is to provide `-DWARNINGS_AS_ERRORS=OFF` in bootstrap of TimescaleDB source.

**Comment by thobi85** [comment]
@k-rus Thx for you fast reply.
I added the command to the Dockerfile.
It still shows the warning at compiling, but goes ahead.
I will keep you updated if the compiling was successful.

**Comment by DmitrySidorow** [comment]
> @thobi85 I believe you are hitting the same issue as #2770
> The work around is to provide `-DWARNINGS_AS_ERRORS=OFF` in bootstrap of TimescaleDB source.

thankk you! also helped me with same problem

**Comment by NunoFilipeSantos** [comment]
@thobi85 were you able to compile?

**Comment by thobi85** [comment]
@NunoFilipeSantos yes i have successfully created the database.
You can find the Dockerfile in my github or the docker images at the docker hub.

**Comment by NunoFilipeSantos** [comment]
Great @thobi85 ! Closing this issue now.
We can continue discussing on #2770 .
