### ISSUE TITLE
PgAdmin error on TimescaleDB Database

### ISSUE THREAD

**Issue by vman84** [timescale/timescaledb#2817]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version: 11.10-2
 - TimescaleDB version: 2.0.0

I've correctly created an hypertable and I'm filling it with data. 
I can query from psql shell but I'm not able to access the database from PgAdmin tool.
When I try to use PgAdmin, I have the following error when I click on my database:
**INTERNAL SERVER ERROR**
_server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request._

![image](https://user-images.githubusercontent.com/77387968/104442735-c2b40d80-5595-11eb-867e-5cb804e1adfa.png)

As you can see, I'm able to query the hypertable:

![image](https://user-images.githubusercontent.com/77387968/104442789-dcedeb80-5595-11eb-868f-10b13cef566c.png)

Thanks in advance

**Comment by k-rus** [comment]
@vman84 Thank you for reporting. I believe you hit the same bug as in https://github.com/timescale/timescaledb/issues/2775
It was fixed, but haven't released yet. The plan is to include fix into 2.0.1.

I close this issue as duplicate.
