### ISSUE TITLE
Support adding dimension when data exists

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2818]
We should allow users to add dimensions when data already exists. The new dimension would have a single partition/slice for any existing chunks. Metadata for those chunks would have to be updated, including constraints on chunk tables.

Useful specifically for migrating a regular hypertable to a distributed hypertable.

**Comment by cevian** [comment]
Also useful for adding space partitions to a distributed hypertable. Use case: we have a lot of metric hypertables. Most of them should not be space partitioned to begin with. That way, different metrics go on different nodes in a round-robin fashion but a single metric, for a single time, is on one node. But, if one metric gets too big, it may become useful to partition that metric. The straightforward way to do that would be to add a space dimension to that particular metric.

**Comment by NunoFilipeSantos** [comment]
Thanks for the enhancement proposal @erimatnor !

**Comment by yaitskov** [comment]
+1. I don't see any value in add_dimension function until it can work with nonempty tables. If table should be empty then it is easy to drop table and create it from scratch with new dimension set.

Is there workaround?

**Comment by richardARPANET** [comment]
@yaitskov Will `add_dimension` work if I TRUNCATE the data, run `add_dimension` and re-populate the table?

**Comment by yaitskov** [comment]
@richardARPANET , It was working. I don't know about current bugs.
I haven't worked with timescale db for months.
As far as remember I use aliases - a meta table keeping relation between alias and real table.
Once table structure changes I create new table and reassign the alias.
You can play Hanoi game with a table if you want to keep physical name untouched ;)

**Comment by yaitskov** [comment]
As for me updating physical structure for adding/removing columns in a table with zillion rows is a dead end. An atomic table rename function (or swap names for 2 tables) would suit this use case better. It requires minimum work on system internals.
Background live synchronization is already doable on application side plus triggers.

**Comment by guikubivan** [comment]
Looks like this is now possible, but there's no mention of this functionality in https://docs.timescale.com/api/latest/hypertable/add_dimension/#add-dimension. Can we use this the same and assume it will work?
