### ISSUE TITLE
2.x max_interval_per_job setting

### ISSUE THREAD

**Issue by eldelto** [timescale/timescaledb#2823]
Hi,

I was wondering if in version 2.x there exists a similar parameter to the old `max_interval_per_job` to better distribute the amount of work a background job does per run to refresh a continuous aggregate? I've looked through the updated docs but couldn't find anything similar.

Currently we run out of memory when trying to backfill historical data into a continuous aggregate either by using `CALL refresh_continuous_aggregate` or by adding a policy that covers the whole data range.

Thanks for this great project by the way!

**Comment by NunoFilipeSantos** [comment]
Hi @eldelto let me verify internally your request.

**Comment by erimatnor** [comment]
@eldelto You should be able to run multiple calls on `refresh_continuous_aggregate` on separate time ranges to materialize less data in each call (similar to what `max_interval_per_job` was achieving). You can also write a custom policy (User-defined Action) to automate this yourself.

Still, even if you materialize a lot of data, the materializer shouldn't run out of memory (unless the query uses hash aggregation), so we might need to look at excessive memory usage in the materializer. Obviously, the materialization will still take a long time if you materialize a lot of data.

**Comment by eldelto** [comment]
@erimatnor I backfilled the historical data manually via multiple `refresh_continuous_aggregate` calls which worked out fine. Also the custom policy is a cool suggestion, thanks for that.

My query for the  continuous aggregate looks like this:
```sql
SELECT time_bucket(INTERVAL '1 day', timestamp_utc) AS time, 
       id, 
       count(*) AS count,
          AVG(i_value),
          MAX(i_value) - MIN(i_value) AS range
   FROM data
   WHERE i_value IS NOT NULL
   GROUP BY time, id;
```

With the corresponding query plan:
```
                                                       QUERY PLAN                                                        
--------------------------------------------------------------------------------------------------------------------------
 Finalize GroupAggregate  (cost=38009393.61..38020827.59 rows=40000 width=82)
   Group Key: (time_bucket('1 day'::interval, _hyper_1_19_chunk.timestamp_utc)), _hyper_1_19_chunk.id
   ->  Gather Merge  (cost=38009393.61..38018727.59 rows=80000 width=90)
         Workers Planned: 2
         ->  Sort  (cost=38008393.59..38008493.59 rows=40000 width=90)
               Sort Key: (time_bucket('1 day'::interval, _hyper_1_19_chunk.timestamp_utc)), _hyper_1_19_chunk.id
               ->  Partial HashAggregate  (cost=38004736.04..38005336.04 rows=40000 width=90)
                     Group Key: time_bucket('1 day'::interval, _hyper_1_19_chunk.timestamp_utc), _hyper_1_19_chunk.id
                     ->  Result  (cost=0.00..32254863.47 rows=383324838 width=42)
                           ->  Parallel Append  (cost=0.00..27463303.00 rows=383324838 width=42)
                                 ->  Parallel Seq Scan on _hyper_1_19_chunk  (cost=0.00..492907.65 rows=7370662 width=42)
...
```

This of course uses a form of hash aggregation but isn't it inherent to using continuous aggregates that you need some sort of grouping?

**Comment by iqbalaydrus** [comment]
We also ran across this issue as well, in our case the refresh hits the temp_file_limit
```
[2021-01-25 10:26:29] [53400] ERROR: temporary file size exceeds temp_file_limit (52428800kB)
[2021-01-25 10:26:29] Where: SQL statement "INSERT INTO _timescaledb_internal._materialized_hypertable_14 SELECT * FROM _timescaledb_internal._partial_view_14 AS I WHERE I.date_time >= '2020-09-01 00:00:00' AND I.date_time < '2021-01-25 00:00:00' ;"
```

**Comment by nikkhils** [comment]
@iqbalaydrus the default for `temp_file_limit` is -1 which means unlimited. Looks like your setup is trying to limit the size?

**Comment by iqbalaydrus** [comment]
@nikkhils @NunoFilipeSantos yes, I limited the `temp_file_limit` to avoid excess disk usage since the temp partition is different from postgres' data partition and has limited capacity. My point is, I could avoid increasing the`temp_file_limit` if the `max_interval_per_job` parameter was there since it would aggregate in smaller batches.

**Comment by iqbalaydrus** [comment]
@nikkhils @NunoFilipeSantos yes, I limited `temp_file_limit` config in postgres

**Comment by nikkhils** [comment]
@iqbalaydrus then will it be possible for you to try and increase it a bit to see if it helps your specific use case here?

**Comment by iqbalaydrus** [comment]
Unfortunately I don't use any continuous aggregates anymore. I decided to use a more manual approach by aggregating via apps.

**Comment by NunoFilipeSantos** [comment]
@iqbalaydrus thank you for letting us know. 👍
