### ISSUE TITLE
Add update test for repair dimension slices

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#2824]
In #1986, #1841, and a few others, there are tuple locking issues that can cause dimension slices to be removed when they are actually referenced by insert operations that later add constraints referring these slices.

In the fixes for this, we repair the dimension slice table by re-adding missing dimension slices referenced in the constraints, but we have no explicit test that this repair works for more complicated situations.

We should add update tests similar to those mentioned in #2065 but added to the update test. Note that the test should only break the dimension slice table for versions where the repair script is actually running during update.

**Comment by NunoFilipeSantos** [comment]
@mkindahl can you elaborate on what these complicated situations would be?

**Comment by mkindahl** [comment]
Constraints are parsed and are in several different forms. For example:

- `(("time" >= 3) AND ("time" < 6))`
- `(_timescaledb_internal.get_partition_hash(tag) < 1073741823)`

Since they can be of several different combinations, it is possible that errors are introduced in the parsing code that does not handle some specific situation. For example, the order of the comparisons, quotes or not quotes around column names, function calls on columns, different types of timestamps. This needs to be tested by constructing tables with different time types and different constraints, and then repair them.
