### ISSUE TITLE
Permission failure on cagg after upgrade

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#2825]
After upgrading from 1.7.4. to 2.0.0, queries on a cagg view using the non-owner user will fail. 

This is because the permissions on the view is not propagated when granting perms in 1.7.x, and the new `cagg_watermark` function queries the materialized table for max bucket requiring proper privileges.

We can solve this by either (1) propagate grants in an update script for legacy caggs or (2) execute the `cagg_watermark` function as view owner rather than the current user.

**Comment by NunoFilipeSantos** [comment]
@erimatnor what would be the safest approach (from a security stand point)?

**Comment by erimatnor** [comment]
@NunoFilipeSantos I think either approach is OK. This issue isn't strictly about security though, but rather fixing a bug/limitation. PR in #2845.
