### ISSUE TITLE
Using the AWS ami, cannot get access_node to use the passfile

### ISSUE THREAD

**Issue by murphycrosby** [timescale/timescaledb#2830]
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0
 - Installation method: ami-05f94dc4b55853f2b

**Describe the bug**
When walking through the steps for Password authentication (https://docs.timescale.com/latest/getting-started/setup-multi-node-basic/multi-node-self-managed#multi-node-auth-password), cannot get add_data_node to work with the passfile. If I supply the password in the call, it works fine. 

**To Reproduce**
1. Go to https://docs.timescale.com/latest/getting-started/setup-multi-node-basic/multi-node-self-managed#multi-node-auth-password
2. Follow steps 1,2,3,4
3. run SELECT add_data_node('timescale_db_data_1', host => 'xx.xxx.xx.xxx');
4. See error:
ERROR:  could not connect to "timescale_db_data_1"
DETAIL:  fe_sendauth: no password supplied

**Expected behavior**
```
NOTICE:  database "db" already exists on data node, skipping
NOTICE:  extension "timescaledb" already exists on data node, skipping
DETAIL:  TimescaleDB extension version on 10.200.11.143:5432 was 2.0.0.
                    add_data_node
-----------------------------------------------------
 (timescale_db_data_1,10.200.11.143,5432,axil,t,f,f)
(1 row)
```

**Actual behavior**
```
ERROR:  could not connect to "timescale_db_data_1"
DETAIL:  fe_sendauth: no password supplied
```

**Additional context**
1. passfile located at /etc/postgresql/12/main
2. Security set to `-rw-r--r-- 1 postgres postgres    28 Jan 14 16:25 passfile`
3. postgresql.conf has `password_encryption = 'scram-sha-256'`, and `timescaledb.passfile = '/etc/postgresql/12/main/passfile'`
4. Explicitly supplying the password works, but there are additional steps that make calls to the data nodes that don't allow a password parameter, so a file has to be used. e.g. distributed_exec

**Comment by resamaraschi** [comment]
Hi, I am facing the same issue "fe_sendauth: no password supplied". 
@murphycrosby : did you find any solution for this issue?
Thanks

**Comment by SachinMaharana** [comment]
Hi. Having the same exact issue. is there a way around this?

**Comment by pmwkaa** [comment]
@SachinMaharana @resamaraschi @murphycrosby please make sure that `passfile` is set to `chmod 0600`, this should be `-r-------`

**Comment by nikkhils** [comment]
Dmitry has provided the solution above. Closing this now.
