### ISSUE TITLE
Inserting millions of rows causes timescaledb to crash and restart

### ISSUE THREAD

**Issue by purcellchristopher** [timescale/timescaledb#284]
### Overview
When I try to populate my hyper-table with an initial dataset, my timescaledb container crashes and restarts.  What I found was:
* I was not able to import the 146,567,765 million rows using COPY to a hyper table
* I was able to import the 146,567,765 million rows using COPY to a standard table
* I was not able to use INSERT INTO from a standard table to a hyper table unless I limited it ~10,000,000 rows.

I am running on OS X using docker toolbox.

```
REPOSITORY                                                      TAG                 IMAGE ID            CREATED             SIZE
timescale/timescaledb                                           latest              76833c49fc56        36 hours ago        39.5MB
```

### Details

My first attempt was with COPY to a **_hypertable_** named metrics...  

`COPY metrics FROM '/tmp/facts';`
> ERROR:  out of memory
> DETAIL:  Failed on request of size 16.
> CONTEXT:  COPY metrics, line 693520: "2017-01-22 14:24:00.245	433	10	10760"

My second attempt was with COPY to a **_standard table_** named metric_baseline...
`COPY metric_baseline FROM '/tmp/facts';`
> COPY 146567765

My third attempt was to try an INSERT INTO metrics from metric_baseline
`insert into metrics select * from metric_baseline; `

> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.

My fourth attempt was to try the INSERT INTO metrics from metric_baseline with a limit
`insert into metrics select * from metric_baseline limit 1000000;`

> INSERT 0 1000000

My fifth attempt was to try the INSERT INTO metrics from metric baseline with a higher limit
`truncate table metrics;`

> TRUNCATE TABLE

`insert into metrics select * from metric_baseline limit 50000000; `

> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.

Here is a snippet of my timescaledb container log
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  server process (PID 62) was terminated by signal 9
DETAIL:  Failed process was running: insert into metrics select * from metric_baseline limit 20000000;
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2017-11-01 13:11:03 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 7/E2770F90
LOG:  invalid magic number 0000 in log segment 000000010000000800000078, offset 8200192
LOG:  redo done at 8/787D1F98
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

**Comment by ryan-shaw** [comment]
There is a memory leak with large copies - https://github.com/timescale/timescaledb/pull/274

Will be fixed in next release.

**Comment by mfreed** [comment]
@purcellchristopher Please let us know if you are still encountering this problem in the recent 0.6.1 release.  Thanks!

**Comment by mfreed** [comment]
@purcellchristopher  Just following up.  If you could close out the issue if it works for you, that would be appreciated.

**Comment by purcellchristopher** [comment]
I’ll run the test today.

Sent from my iPhone

On Nov 19, 2017, at 10:06 PM, Mike Freedman <notifications@github.com<mailto:notifications@github.com>> wrote:


@purcellchristopher<https://github.com/purcellchristopher> Just following up. If you could close out the issue if it works for you, that would be appreciated.
