### ISSUE TITLE
Continuous aggregate update

### ISSUE THREAD

**Issue by lucapaganotti** [timescale/timescaledb#2855]
**Relevant system information:**
 - OS: debian 9.3
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.5
 - TimescaleDB version (output of `\dx` in `psql`): List of installed extensions
   plpgsql     | 1.0       | pg_catalog | PL/pgSQL procedural language
   timescaledb | 2.0.0-rc4 | public     | Enables scalable inserts and complex queries for time-series data
 - Installation method: "docker image"

**Describe the bug**
It's not a real bug, but a help request, I'm new to timescaledb so please be patient:
I've setup a docker container that contains 3 tables, let's say A, B, C (A example)

```
CREATE TABLE public.A
(
    station int NOT NULL,
    dt      timestamp(1) without time zone NOT NULL,
    leq     double precision,
    laf     double precision,
    las     double precision,
    lai     double precision,
    pnl     double precision,
    lpeak   double precision,
    lmin    double precision,
    lmax    double precision,
    lceq    double precision,
    lzeq    double precision,
    ovl     double precision
)

TABLESPACE pg_default;

CREATE INDEX A_station_time_idx
    ON public.his USING btree
    (station ASC NULLS FIRST, dt DESC NULLS FIRST)
    TABLESPACE pg_default;
```

from each of these table an hypertable is created via SELECT create_hypertable via
`SELECT create_hypertable('A', 'mydt', migrate_data=>TRUE);
`
for tables A and B two materialized views each are created and for table C 4 materialized views are created as per 
```
CREATE materialized VIEW A_summary_hourly
WITH (timescaledb.continuous) AS
SELECT station,
       time_bucket(INTERVAL '1 hour', dt) AS bucket,
       10 * log(sum(power(10, leq/10)))   - 10 * log(3600) as hleq,
       10 * log(sum(power(10, laf/10)))   - 10 * log(3600) as hlaf,
       10 * log(sum(power(10, las/10)))   - 10 * log(3600) as hlas,
       10 * log(sum(power(10, lai/10)))   - 10 * log(3600) as hlai,
       10 * log(sum(power(10, pnl/10)))   - 10 * log(3600) as hpnl,
       10 * log(sum(power(10, lpeak/10))) - 10 * log(3600) as hlpeak,
       10 * log(sum(power(10, lmin/10)))  - 10 * log(3600) as hlmin,
       10 * log(sum(power(10, lmax/10)))  - 10 * log(3600) as hlmax,
       10 * log(sum(power(10, lceq/10)))  - 10 * log(3600) as hlceq,
       10 * log(sum(power(10, lzeq/10)))  - 10 * log(3600) as hlzeq,
       sum(ovl) as hovl
FROM his
GROUP BY station, bucket;
```

for each materialized view an continuous aggregate policy is created, each with it's own start_offset, end_offset and schedule_interval

```
SELECT add_continuous_aggregate_policy('A_summary_hourly',
    start_offset => null,
    end_offset => INTERVAL '1 h',
    schedule_interval => INTERVAL '15 min');
```

I then began to insert data, but the insert takes a very long time when the continuous aggregates policies are active, so I dropped them after stopping the running jobs.

I continued to insert data in the base table A, B, C to have a feasible case study, now I would like to restore / force the materialized views upate based on the inserted data, so I tried to

1. CALL run_job(ijob_id); where job_id is the job_id I get querying timescaledb_information.jobs, nothing happens and the materialized view contains always the same number of records
2. CALL refresh_continuous_aggregate with parameters continuous aggregate name, window_start and window_end, nothing happens as in point 1.

So my question are, can I force the materialized view re-population after I dropped the continuous aggregate policy base on all the inserted data ?

I will be very kind if someone could tell me more, I can give all the script I used to setup the db.

**To Reproduce**
See before

**Expected behavior**
Materialized views update

**Actual behavior**
Materialized views are not updated

**Screenshots**
No screenshots

**Additional context**
On specific request I can give all the relevant info

Thank you, have a nice day.

**Comment by NunoFilipeSantos** [comment]
Hi @lucapaganotti! Can you please update to TimescaleDB 2.5.0 and get back to us? Thank you!

**Comment by gayyappan** [comment]
Please feel free to reopen if you have any problems with this.

**Comment by juanvisoler** [comment]
I see the same behaviour in TimescaleDB 2.7.0 as PostgreSQL 14.

If I call `refresh_continuous_aggregate` in a window that has been already materialized, nothing happens.

Should there be an option to force the refresh?
