### ISSUE TITLE
No upgrade path from 2.0 beta3 to current version

### ISSUE THREAD

**Issue by justinasjaronis** [timescale/timescaledb#2856]
When trying to update 2.0 beta which was deployed using  timescaledev/timescaledb-2.0.0-beta3 image to current version (timescale-2.0.0),  ALTER EXTENSION timescaledb UPDATE throws following error:
 
extension "timescaledb" has no update path from version "2.0.0-beta3" to version "2.0.0"

I believe data migration between beta/RC versions wont be implemented?

Maybe there is some version-agnostic way to dump only the contents and regenerate indexes  when importing? Or the only way is to dump selectively useful data tables and import in new and clean database?

**Comment by erimatnor** [comment]
We support upgrades from release candidates but not betas, unfortunately.
