### ISSUE TITLE
PPA release for Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by gredin** [timescale/timescaledb#2896]
Any plan to release the package for Ubuntu 20.10?
Or do you limit Timescale releases to Ubuntu LTS?

The [documentation](https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu) is unclear about the latter point:
> Prerequisites
> Ubuntu 18.04 or later, except obsoleted versions. Check releases.ubuntu.com for list of non-obsolete releases.

**Comment by svenklemm** [comment]
Yes atm we only build ubuntu packages for LTS releases.

**Comment by erimatnor** [comment]
Closing since issue was answered.
