### ISSUE TITLE
create_hypertable fails with unique index

### ISSUE THREAD

**Issue by sentient-pmaher** [timescale/timescaledb#29]
Environment: running latest Docker image (0.0.9-beta) on Mac.

Running the SQL below causes an error on hypertable creation.
Creating a non-UNIQUE index works.
Using a PRIMARY KEY(ID) also fails.

DROP TABLE IF EXISTS number_facts ;
CREATE TABLE IF NOT EXISTS number_facts (
  id BIGINT NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE,
  value DOUBLE PRECISION NOT NULL
);
CREATE UNIQUE INDEX number_facts_u ON number_facts (id, ts) ; 
SELECT create_hypertable('number_facts', 'ts', 'id', 2);

ERROR: Cannot process index with definition (no index name match) CREATE UNIQUE INDEX number_facts_u ON /*TABLE_NAME*/ USING btree (id, ts)
  Where: PL/pgSQL function _timescaledb_internal.get_general_index_definition(regclass,regclass) line 28 at RAISE
SQL statement "SELECT 1
    FROM pg_index,
    LATERAL _timescaledb_meta_api.add_index(
        hypertable_row.id,
        hypertable_row.schema_name,
        (SELECT relname FROM pg_class WHERE oid = indexrelid::regclass),
        _timescaledb_internal.get_general_index_definition(indexrelid, indrelid)
    )
    WHERE indrelid = main_table"
PL/pgSQL function create_hypertable(regclass,name,name,integer,smallint,name,name,_timescaledb_catalog.chunk_placement_type,bigint) line 93 at PERFORM

**Comment by cevian** [comment]
This should be fixed once pr #32 is merged.
