### ISSUE TITLE
cannot create a unique index without the column "time" (used in partitioning)

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [timescale/timescaledb#2902]
I follwed this guide https://docs.timescale.com/latest/tutorials/quickstart-node

 `npx sequelize migration:generate --name add_hypertable`

then `migrate`

``` 
Sequelize CLI [Node: 14.5.0, CLI: 6.2.0, ORM: 6.5.0]

Loaded configuration file "config\config.json".
Using environment "development".
== 20210204185358-add_hypertable: migrating =======

ERROR: cannot create a unique index without the column "time" (used in partitioning)
``` 

...hypertable.js

``` 
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query("SELECT create_hypertable('page_loads', 'time');");
  },

  down: (queryInterface, Sequelize) => {
  }
};
``` 

the column time actually exists.. I don't understand this error message.

**Comment by rexfue** [comment]
How did you solve this problem?

**Comment by MA-MacDonald** [comment]
Im also running into this error when following the tutorial in the docs. What was the solution?
https://docs.timescale.com/latest/tutorials/quickstart-node

**Comment by RamneekKaur983** [comment]
@hp8wvvvgnj6asjm7  I am facing the same error. How did you resolve the issue?

**Comment by binakot** [comment]
It's a bug in the documentation. Now node's quick start is available here: https://docs.timescale.com/timescaledb/latest/quick-start/node/

And someone should create related issue directly in docs repo: https://github.com/timescale/docs

**Comment by RamneekKaur983** [comment]
I followed https://docs.timescale.com/timescaledb/latest/quick-start/node/ documentation only , the same error is coming up.

**Comment by pfried** [comment]
The issue is that your migration contains a primary key index which gets automaticall generated by the command. All indices need to contain the time column (what the error says). If you do not have timeseries data you cannot create a hypertable. Delete the primary key and it works

**Comment by MtnBiker** [comment]
Following @pfried I removed the "id" column created by Rails which was also the primary key. I removed using PGAdmin, but presumably could have done it in psql. I then was able to create the hypertable. Will see if I can continue from there.
