### ISSUE TITLE
Improve query performance by running ANALYZE !

### ISSUE THREAD

**Issue by Satishcalsoft-dev** [timescale/timescaledb#2904]
- PostgreSQL version: 12.4
 - TimescaleDB version: 1.7.4

Hi,

I have a table in which data is distributed in multiple chunks based on time only i.e. created hypertables for one day. I am trying to improve the performance of SELECT query. To achieve that I had to run **ANALYZE** periodically over the whole table. Since there isn't any updation or deletion  performed in the table, VACUUM seems inefficient in my case. Also, I cannot put multiple indexes either since it will decrease ingestion performance and it will take a large amount of disk space.

I am ingesting data into the table by order of time. The recent data will be stored in a successive hypertable.

**Question:**

> Will I get any performance improvement if I run ANALYZE on only the newly created hypertable by assuming that I already ran ANALYZE on all previous hypertables?

```
ANALYZE _timescaledb_internal._hyper_103_45_chunk;
```

> Or is it mandatory to run ANALYZE on the whole table to get best performance and why?

```
ANALYZE schema.table_name;
```
Thanks

**Comment by Satishcalsoft-dev** [comment]
Changes done in posgresql.conf:

- wal_level = minimal
- fsync = off
- synchronous_commit = off
- full_page_writes = off
- archive_mode = off

Also each table has `autovacuum_enabled = false`.

**Comment by mfreed** [comment]
If you run ANALYZE on the hypertable, it will propagate and run on all the chunks of the hypertable.  So similarly, if you instead run ANALYZE on individuals chunks, you don't need to run them on the parent hypertable again.

Hope that answers you question @Satishcalsoft-dev .  Closing the issue, but feel free to re-open if there are any problems.

**Comment by Satishcalsoft-dev** [comment]
I am not trying to run ANALYZE on all the chunks individually but trying to run analyze on only those hypertable which were generated after running the last ANALYZE.  Will that impact on my query performance?

**Comment by SHxKM** [comment]
> If you run ANALYZE on the hypertable, it will propagate and run on all the chunks of the hypertable. So similarly, if you instead run ANALYZE on individuals chunks, you don't need to run them on the parent hypertable again.

@mfreed - does this also apply when running `ANALYZE` manually, such as:

```
ANALYZE my_table
```
