### ISSUE TITLE
duplicate key constraint error

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [timescale/timescaledb#2905]
I was forced to use time as primary key, or otherwise I couldn't create a hypertable.
`ERROR: cannot create a unique index without the column "T" (used in partitioning)`
But my dataset has multiple events with the same timestamp.
Now when writing into the DB I get this error: 
```
original: error: duplicate key value violates unique constraint "5_5_test_pkey"
routine: '_bt_check_unique',
```

**Comment by hp8wvvvgnj6asjm7** [comment]
i used marked two rows as primary key, seems to be working now.

**Comment by svenklemm** [comment]
i hypertable is not required to have a primary key, so if your time is not unique you should drop the primary key constraint

**Comment by hp8wvvvgnj6asjm7** [comment]
https://docs.timescale.com/latest/tutorials/quickstart-node

This guide isn't working really... I get this error : 

```
sing environment "development".
== 20210205122220-add_hypertable: migrating =======

ERROR: cannot create a unique index without the column "time" (used in partitioning)

```

**Comment by solugebefola** [comment]
At what point in the tutorial are you running into the error?

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> At what point in the tutorial are you running into the error?

when creating the hypertable.
i marked all keys as non primary now its fixed:

```
'use strict';
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable('test', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: false,
        type: Sequelize.INTEGER
      },
      p: {
        primaryKey: false,
        type: Sequelize.FLOAT
      },
      q: {
        primaryKey: false,
        type: Sequelize.FLOAT
      },
      Q: {
        primaryKey: false,
        type: Sequelize.FLOAT
      },
      T: {
        primaryKey: false,
        type: Sequelize.DATE
      },
      m: {
        primaryKey: false,
        type: Sequelize.BOOLEAN
      },
      M: {
        primaryKey: false,
        type: Sequelize.BOOLEAN
      }
    });
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.dropTable('test');
  }
};

```

**Comment by mfreed** [comment]
@hp8wvvvgnj6asjm7 I'm not fully sure where we are?

Is there still any problems, i.e., should we just close the issue?

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> @hp8wvvvgnj6asjm7 I'm not fully sure where we are?
> 
> Is there still any problems, i.e., should we just close the issue?

thank you. I think I got a good start with this new db =)
