### ISSUE TITLE
time_bucket_gapfill combined with where column is null 

### ISSUE THREAD

**Issue by domienvandamme1** [timescale/timescaledb#2906]
```
select * from (  
SELECT
  time_bucket_gapfill(1,time,0,6) AS time,
  min(value) AS value
FROM (values (0,1),(5,6)) v(time,value)
GROUP BY 1 ORDER BY 1) where value is null
```
I would expect that this results in the gap rows, but it outputs every row

**Comment by NunoFilipeSantos** [comment]
@domienvandamme1 can you please try with our latest TimescaleDB 2.4.2 (PG 12 or PG13) and get back to us?

**Comment by NunoFilipeSantos** [comment]
Hi @domienvandamme1! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it. 👍
