### ISSUE TITLE
Unable to install TimescaleDB2.0.1 via yum on CentOS 7

### ISSUE THREAD

**Issue by xJosephTan** [timescale/timescaledb#2912]
Hi all, 

I was directed to raise my issue here from the Slack community and was wondering if anyone else is facing the same issue that I was facing.

**Time of event**:
- 5th Feb 2021 around 0600 UTC till now. 

**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): psql (PostgreSQL) 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.1
 - Installation method: yum

**Describe the bug**
I am trying to install TimescaleDB (the latest version) via yum as listed in the [official documentation](https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum). However, I was hit by an error after running `service postgresql-12 restart` 

I have also ran the command `sudo timescaledb-tune --pg-config="/usr/pgsql-12/bin/pg_config" --conf-path="/var/lib/pgsql/12/data/postgresql.conf"` to update `postgresql.conf` to include `timescaledb` as a parmater in `shared_preload_libraries` prior to the issue.

The error details are as follows: 
`Redirecting to /bin/systemctl start postgresql-12.service
Job for postgresql-12.service failed because the control process exited with error code. See "systemctl status postgresql-12.service" and "journalctl -xe" for details.`

` "systemctl status postgresql-12.service`:
```● postgresql-12.service - PostgreSQL 12 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-12.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2021-02-06 09:45:06 UTC; 3min 6s ago
     Docs: https://www.postgresql.org/docs/12/static/
  Process: 2481 ExecStart=/usr/pgsql-12/bin/postmaster -D ${PGDATA} (code=exited, status=1/FAILURE)
  Process: 2475 ExecStartPre=/usr/pgsql-12/bin/postgresql-12-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 2481 (code=exited, status=1/FAILURE)

systemd[1]: Starting PostgreSQL 12 database server...
postmaster[2481]: 2021-02-06 09:45:06.617 UTC [2481] FATAL:  could not access file "timescaledb": No such file or directory
systemd[1]: postgresql-12.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start PostgreSQL 12 database server.
systemd[1]: Unit postgresql-12.service entered failed state.
systemd[1]: postgresql-12.service failed.
```
` "systemctl status postgresql-12.service`:
```polkitd[557]: Registered Authentication Agent for unix-process:2459:487236 (system bus name :1.70 [/usr/bin/pkttyagent --notify-fd 5 --fallback],
systemd[1]: Starting PostgreSQL 12 database server...
-- Subject: Unit postgresql-12.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-12.service has begun starting up.
postmaster[2481]: 2021-02-06 09:45:06.617 UTC [2481] FATAL:  could not access file "timescaledb": No such file or directory
postmaster[2481]: 2021-02-06 09:45:06.618 UTC [2481] LOG:  database system is shut down
systemd[1]: postgresql-12.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start PostgreSQL 12 database server.
-- Subject: Unit postgresql-12.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-12.service has failed.
--
-- The result is failed.
systemd[1]: Unit postgresql-12.service entered failed state.
systemd[1]: postgresql-12.service failed.
polkitd[557]: Unregistered Authentication Agent for unix-process:2459:487236 (system bus name :1.70, object path /org/freedesktop/PolicyKit1/Authe
```

**Additional Observations**
1. On installation, it was noticed that I have received the warning message `Got an unexpected argument: -c` which I suspect could be the root cause of the issue 
 ![image](https://user-images.githubusercontent.com/62532722/107114237-43b5aa80-689f-11eb-9c9c-7ddea3f5c0b5.png)
2. There's no file related to `timescaledb` (based on filename) in my `LIBDIR`/`PKGLIBDIR` (/usr/pgsql-12/lib) and /usr/pgsql-12/share/extension
3. Removing `timescaledb` as a parmater in `shared_preload_libraries` allows me to start the postgresql-12 service, but without the TimescaleDB extension. 
4. Updating my PATH environmental variable to include my `LIBDIR` doesn't seem to resolve my issue, even after performing a remove-and-reinstall (via yum as well)
5. `timescaledb` was mentioned to be installed on my machine when executing the commands `yum list installed | grep timescaledb`
![image](https://user-images.githubusercontent.com/62532722/107115443-bdea2d00-68a7-11eb-8eb4-a4c09dd9015b.png)

**Expected behavior**
Postgresql 12 service should be started with TimescaleDB installed(viewable from `pg_extension`)

**Actual behavior**
Postgresql 12 service failed to start with `timescaledb` included as a parameter in `shared_preload_libraries` in `postgresql.conf`.

**Comment by svenklemm** [comment]
Hmm looks like the post install script is failing for you, any chance you can debug this further? The `-c` option mentioned in your logs is part of execution of `install` does your `install` not support it?

**Comment by xJosephTan** [comment]
That does seem to be the scenario. Thank you so much @svenklemm, I will proceed to close the issue
