### ISSUE TITLE
OrderedAppend/range partitioning optimization does not work with RLS

### ISSUE THREAD

**Issue by nrpeters** [timescale/timescaledb#2916]
**Relevant system information:**
 - OS: CentOS 8
 - PostgreSQL version (output of `postgres --version`): 12.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: yum

**Describe the bug**
The OrderedAppend range partitioning optimization mentioned in https://blog.timescale.com/blog/ordered-append-an-optimization-for-range-partitioning/ does not work with RLS (row level access via policies).

**To Reproduce**
1. Create a Timescale hypertable, add an index, and add rows to it
2. Create an RLS policy for the hypertable
3. Run `EXPLAIN ANALYZE SELECT ... WHERE ... ORDER BY ... LIMIT 1` on the table, where the ORDER BY is based on an index

**Expected behavior**
The range partitioning optimization mentioned in https://blog.timescale.com/blog/ordered-append-an-optimization-for-range-partitioning/ should work, so the output should show `Custom Scan (ChunkAppend)` and unneeded chunks should show as `never executed` in the output.

**Actual behavior**
`Custom Scan (ConstraintAwareAppend)` is shown and none of the chunks show as `never executed`.

**Comment by erimatnor** [comment]
Thank you for reporting this issue. Can you clarify what the problem is that you are experiencing. Is it RLS that doesn't work or is it the optimization that doesn't work? Is this a security issue or just an optimization that doesn't kick in (but things otherwise work)?

**Comment by npeters-novetta** [comment]
When RLS is used when running a query, the optimization does not work. So when the query from Step 3 runs as a super user, the optimization works (it skips chunks it does not need). When a RLS policy is enabled for the table and the query is _not run as a super user_, the optimization does not work.

**Comment by erimatnor** [comment]
Than you for the clarification.

**Comment by npeters-novetta** [comment]
When RLS is used when running a query, the optimization does not work. So when the query from Step 3 runs as a super user, the optimization works (it skips chunks it does not need). When a RLS policy is enabled for the table and the query is not run as a super user, the optimization does not work.

**Comment by nrpeters** [comment]
When RLS is used when running a query, the optimization does not work. So when the query from Step 3 runs as a super user, the optimization works (it skips chunks it does not need). When a RLS policy is enabled for the table and the query is not run as a super user, the optimization does not work.

**Comment by svenklemm** [comment]
This is working on master. Have you tried whether the plan is chosen without RLS? Did you run timescaledb-tune?
```
dev=> \d+ rls
                                            Table "public.rls"
 Column |           Type           | Collation | Nullable | Default | Storage | Stats target | Description
--------+--------------------------+-----------+----------+---------+---------+--------------+-------------
 time   | timestamp with time zone |           | not null |         | plain   |              |
 device | integer                  |           |          |         | plain   |              |
 value  | double precision         |           |          |         | plain   |              |
Indexes:
    "rls_time_idx" btree ("time" DESC)
Policies:
    POLICY "rls_dev1"
      TO low
      USING ((device = 1))
Triggers:
    ts_insert_blocker BEFORE INSERT ON rls FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
Child tables: _timescaledb_internal._hyper_19_37_chunk,
              _timescaledb_internal._hyper_19_38_chunk
Access method: heap

dev=> explain analyze select * from rls order by time desc limit 1;
                                                                              QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.29..0.34 rows=1 width=20) (actual time=0.034..0.036 rows=1 loops=1)
   ->  Custom Scan (ChunkAppend) on rls  (cost=0.29..341.02 rows=5701 width=20) (actual time=0.032..0.033 rows=1 loops=1)
         Order: rls."time" DESC
         ->  Index Scan using _hyper_19_38_chunk_rls_time_idx on _hyper_19_38_chunk  (cost=0.29..341.02 rows=5701 width=20) (actual time=0.030..0.030 rows=1 loops=1)
               Filter: (device = 1)
         ->  Index Scan using _hyper_19_37_chunk_rls_time_idx on _hyper_19_37_chunk  (cost=0.29..434.68 rows=7260 width=20) (never executed)
               Filter: (device = 1)
 Planning Time: 0.680 ms
 Execution Time: 0.087 ms
(9 rows)

Time: 1.705 ms
```

**Comment by svenklemm** [comment]
Closing this since RLS does work with ordered append queries.
