### ISSUE TITLE
Segmentation fault : background worker "parallel worker" (PID 326386) was terminated by signal 11

### ISSUE THREAD

**Issue by Ashutosh202** [timescale/timescaledb#2921]
System information:

OS: VERSION="20.04.1 LTS (Focal Fossa)"
PostgreSQL version: 12.5
TimescaleDB version: 2.0.1
Installation method: apt install

We are randomly getting Segmentation fault on production database instance. background worker "parallel worker" (PID 326386) was terminated by signal 11: Segmentation fault. No particular query is logged during this crash.

Error messages: 

2021-02-09 19:29:31 CST [325970]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 LOG:  duration: 4717.006 ms  execute pdo_stmt_00000068:
UPDATE report_products ....

2021-02-09 19:29:32 CST [3278058]: db=,user=,app=,client= LOG:  background worker "parallel worker" (PID 326386) was terminated by signal 11: Segmentation fault
2021-02-09 19:29:32 CST [3278058]: db=,user=,app=,client= LOG:  terminating any other active server processes
2021-02-09 19:29:32 CST [328669]: db=,user=,app=,client= WARNING:  terminating connection because of crash of another server process
2021-02-09 19:29:32 CST [328669]: db=,user=,app=,client= DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-09 19:29:32 CST [328669]: db=,user=,app=,client= HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-09 19:29:32 CST [328613]: db=,user=,app=,client= WARNING:  terminating connection because of crash of another server process
2021-02-09 19:29:32 CST [328613]: db=,user=,app=,client= DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-09 19:29:32 CST [328613]: db=,user=,app=,client= HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-09 19:29:32 CST [326348]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 WARNING:  terminating connection because of crash of another server process
2021-02-09 19:29:32 CST [326348]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-09 19:29:32 CST [326348]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-09 19:29:32 CST [326342]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 WARNING:  terminating connection because of crash of another server process
2021-02-09 19:29:32 CST [326342]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-09 19:29:32 CST [326342]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-09 19:29:32 CST [326341]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 WARNING:  terminating connection because of crash of another server process
2021-02-09 19:29:32 CST [326341]: db=liveDB,user=postgres,app=[unknown],client=127.0.0.1 DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.

Background trace:

Feb  9 17:25:14 m15268 kernel: [2001856.489482] postgres[326386]: segfault at 7fff06e49ff8 ip 0000561e8051a111 sp 00007fff06e4a000 error 6 in postgres[561e80472000+49f000]
Feb  9 17:25:14 m15268 kernel: [2001856.489494] Code: 48 83 ec 58 64 48 8b 04 25 28 00 00 00 48 89 45 c8 31 c0 48 8b 87 88 01 00 00 48 85 c0 74 67 8b 70 10 ba 01 00 00 00 8b 58 14 <e8> ba fb ff ff 41 89 c7 85 c0 0f 88 c7 01 00 00 8d 40 ff 48 98 48

#78192 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#78193 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage ()
#78194 0x0000561e80792163 in ReceiveSharedInvalidMessages ()
#78195 0x0000561e807955be in LockRelationOid ()
#78196 0x0000561e804ce23d in relation_open ()
#78197 0x0000561e80536623 in table_open ()
#78198 0x0000561e808ad354 in ?? ()
#78199 0x0000561e808aeb69 in SearchCatCache ()
#78200 0x0000561e808c0a24 in GetSysCacheOid ()
#78201 0x0000561e8056fc2a in get_namespace_oid ()
#78202 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#78203 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage ()
#78204 0x0000561e80792163 in ReceiveSharedInvalidMessages ()
#78205 0x0000561e807955be in LockRelationOid ()
#78206 0x0000561e804ce23d in relation_open ()
#78207 0x0000561e80536623 in table_open ()
#78208 0x0000561e808ad354 in ?? ()
#78209 0x0000561e808aeb69 in SearchCatCache ()
#78210 0x0000561e808c0a24 in GetSysCacheOid ()
#78211 0x0000561e8056fc2a in get_namespace_oid ()
#78212 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#78213 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage ()
#78214 0x0000561e80792203 in ReceiveSharedInvalidMessages ()
#78215 0x0000561e807955be in LockRelationOid ()
#78216 0x0000561e804ce23d in relation_open ()
#78217 0x0000561e80536623 in table_open ()
#78218 0x0000561e808ad354 in ?? ()
#78219 0x0000561e808aeb69 in SearchCatCache ()
#78220 0x0000561e808c0a24 in GetSysCacheOid ()
#78221 0x0000561e8056fc2a in get_namespace_oid ()
#78222 0x0000561e80570fa7 in LookupExplicitNamespace ()
#78223 0x0000561e80572a35 in get_ts_config_oid ()
#78224 0x0000561e808c2095 in check_TSCurrentConfig ()
#78225 0x0000561e808dd122 in ?? ()
#78226 0x0000561e808ddff0 in ?? ()
#78227 0x0000561e808e2cf0 in RestoreGUCState ()
#78228 0x0000561e8053e98f in ParallelWorkerMain ()
#78229 0x0000561e8072a77d in StartBackgroundWorker ()
#78230 0x0000561e80737aa8 in ?? ()
#78231 0x0000561e807384c5 in ?? ()
#78232 <signal handler called>
#78233 0x00007ffad8a070da in __GI___select (nfds=5, readfds=0x7fff07648d20, writefds=0x0, exceptfds=0x0, timeout=0x7fff07648c80) at ../sysdeps/unix/sysv/linux/select.c:41
#78234 0x0000561e80738b76 in ?? ()
#78235 0x0000561e8073a6e1 in PostmasterMain ()
#78236 0x0000561e804c2408 in main ()

**Comment by erimatnor** [comment]
@Ashutosh202 thank you for the bug report. Is it possible to provide a backtrace with debug symbols?

**Comment by Ashutosh202** [comment]
Here are some of the messages after enabling additional debugger. let me know if this is helpful.

#77359 0x0000561e807955be in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#77360 0x0000561e804ce23d in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#77361 0x0000561e80536623 in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#77362 0x0000561e808ad354 in CatalogCacheInitializeCache (cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:932
#77363 0x0000561e808aeb69 in SearchCatCacheInternal (v4=0, v3=0, v2=0, v1=140715302293632, nkeys=1, cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:1221
#77364 SearchCatCache (cache=0x561e82473180, v1=v1@entry=140715302293632, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#77365 0x0000561e808c0a24 in SearchSysCache (key4=0, key3=0, key2=0, key1=140715302293632, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#77366 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140715302293632, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0) at ./build/../src/backend/utils/cache/syscache.c:1244
#77367 0x0000561e8056fc2a in get_namespace_oid (nspname=0x7ffad59b9080 "_timescaledb_cache", missing_ok=<optimized out>) at ./build/../src/backend/catalog/namespace.c:3039
#77368 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#77369 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage (msg=0x7fff07647c70) at ./build/../src/backend/utils/cache/inval.c:595
#77370 0x0000561e80792163 in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x561e808b0dc0 <LocalExecuteInvalidationMessage>, resetFunction=resetFunction@entry=0x561e808b0190 <InvalidateSystemCaches>)
    at ./build/../src/backend/storage/ipc/sinval.c:90
#77371 0x0000561e808b05a7 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#77372 0x0000561e807955be in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#77373 0x0000561e804ce23d in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#77374 0x0000561e80536623 in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#77375 0x0000561e808ad354 in CatalogCacheInitializeCache (cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:932
#77376 0x0000561e808aeb69 in SearchCatCacheInternal (v4=0, v3=0, v2=0, v1=140715302293632, nkeys=1, cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:1221
#77377 SearchCatCache (cache=0x561e82473180, v1=v1@entry=140715302293632, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#77378 0x0000561e808c0a24 in SearchSysCache (key4=0, key3=0, key2=0, key1=140715302293632, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#77379 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140715302293632, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0) at ./build/../src/backend/utils/cache/syscache.c:1244
#77380 0x0000561e8056fc2a in get_namespace_oid (nspname=0x7ffad59b9080 "_timescaledb_cache", missing_ok=<optimized out>) at ./build/../src/backend/catalog/namespace.c:3039
#77381 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#77382 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage (msg=0x7fff07647f00) at ./build/../src/backend/utils/cache/inval.c:595
#77383 0x0000561e80792163 in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x561e808b0dc0 <LocalExecuteInvalidationMessage>, resetFunction=resetFunction@entry=0x561e808b0190 <InvalidateSystemCaches>)
    at ./build/../src/backend/storage/ipc/sinval.c:90
#77384 0x0000561e808b05a7 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#77385 0x0000561e807955be in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#77386 0x0000561e804ce23d in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#77387 0x0000561e80536623 in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#77388 0x0000561e808ad354 in CatalogCacheInitializeCache (cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:932

#77389 0x0000561e808aeb69 in SearchCatCacheInternal (v4=0, v3=0, v2=0, v1=140715302293632, nkeys=1, cache=0x561e82473180) at ./build/../src/backend/utils/cache/catcache.c:1221
#77390 SearchCatCache (cache=0x561e82473180, v1=v1@entry=140715302293632, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#77391 0x0000561e808c0a24 in SearchSysCache (key4=0, key3=0, key2=0, key1=140715302293632, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#77392 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140715302293632, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0) at ./build/../src/backend/utils/cache/syscache.c:1244
#77393 0x0000561e8056fc2a in get_namespace_oid (nspname=0x7ffad59b9080 "_timescaledb_cache", missing_ok=<optimized out>) at ./build/../src/backend/catalog/namespace.c:3039
#77394 0x00007ffad59b6123 in ?? () from /usr/lib/postgresql/12/lib/timescaledb.so
#77395 0x0000561e808b0eb7 in LocalExecuteInvalidationMessage (msg=0x7fff07648190) at ./build/../src/backend/utils/cache/inval.c:595
#77396 0x0000561e80792203 in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x561e808b0dc0 <LocalExecuteInvalidationMessage>, resetFunction=resetFunction@entry=0x561e808b0190 <InvalidateSystemCaches>)
    at ./build/../src/backend/storage/ipc/sinval.c:120
#77397 0x0000561e808b05a7 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#77398 0x0000561e807955be in LockRelationOid (relid=3079, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136


#77399 0x0000561e804ce23d in relation_open (relationId=relationId@entry=3079, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#77400 0x0000561e80536623 in table_open (relationId=relationId@entry=3079, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#77401 0x0000561e805fad9c in get_extension_oid (extname=0x7fea62e39bf7 "timescaledb", missing_ok=<optimized out>) at ./build/../src/backend/commands/extension.c:148
#77402 0x00007fea62e05e49 in ?? () from /usr/lib/postgresql/12/lib/timescaledb-2.0.1.so
#77403 0x00007fea62e0f8d4 in _PG_init () from /usr/lib/postgresql/12/lib/timescaledb-2.0.1.so
#77404 0x0000561e808cbaf6 in internal_load_library (libname=0x7fea62e8471b <error: Cannot access memory at address 0x7fea62e8471b>) at ./build/../src/backend/utils/fmgr/dfmgr.c:290
#77405 0x0000561e808cc520 in RestoreLibraryState (start_address=0x7fea62e8471b <error: Cannot access memory at address 0x7fea62e8471b>, start_address@entry=0x7fea62e846c0 <error: Cannot access memory at address 0x7fea62e846c0>)
    at ./build/../src/backend/utils/fmgr/dfmgr.c:789
#77406 0x0000561e8053e976 in ParallelWorkerMain (main_arg=<optimized out>) at ./build/../src/backend/access/transam/parallel.c:1356
#77407 0x0000561e8072a77d in StartBackgroundWorker () at ./build/../src/backend/postmaster/bgworker.c:841
#77408 0x0000561e80737aa8 in do_start_bgworker (rw=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:5870
#77409 maybe_start_bgworkers () at ./build/../src/backend/postmaster/postmaster.c:6095
#77410 0x0000561e807384c5 in sigusr1_handler (postgres_signal_arg=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:5232
#77411 <signal handler called>

#77412 0x00007ffad8a070da in __GI___select (nfds=nfds@entry=5, readfds=readfds@entry=0x7fff07648d20, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7fff07648c80)
    at ../sysdeps/unix/sysv/linux/select.c:41
#77413 0x0000561e80738b76 in ServerLoop () at ./build/../src/backend/postmaster/postmaster.c:1689
#77414 0x0000561e8073a6e1 in PostmasterMain (argc=5, argv=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:1398
#77415 0x0000561e804c2408 in main (argc=5, argv=0x561e823a8ee0) at ./build/../src/backend/main/main.c:228

**Comment by Ashutosh202** [comment]
I removed timescaleDB extension from prod and we are no longer seeing any database crash.  We want to use this in our production environment & get this issue fix. Please let me know if you need any additional information.

**Comment by NunoFilipeSantos** [comment]
@Ashutosh202 can you please try with our latest TimescaleDB 2.4.2 (PG 12 or PG13) and get back to us?

**Comment by NunoFilipeSantos** [comment]
Hi @Ashutosh202 ! 👋 If you can reproduce this on the latest TimescaleDB version, please feel free to reopen the issue.
