### ISSUE TITLE
High availability SELECT for multinode

### ISSUE THREAD

**Issue by hgiasac** [timescale/timescaledb#2923]
With multi-node setup, If one of data nodes is down. SELECT queries are unusable

```sql
SELECT * FROM conditions LIMIT 1;

ERROR:  could not connect to "timescaledb-data2"
DETAIL:  could not connect to server: Operation timed out
        Is the server running on host "timescaledb-data2" (125.235.4.59) and accepting
        TCP/IP connections on port 5432?
```

Can TimescaleDB have a unsafe mode to query data that excludes unreachable data nodes? Without it the native replication feature don't have much uses besides detach and delete data nodes

**Comment by erimatnor** [comment]
@hgiasac we might consider things like "unsafe" mode in the future. But I think a more likely scenario is that you use the built in chunk replication to "fail over" the query to another node. These are all future enhancements, however.

**Comment by nikkhils** [comment]
@hgiasac if you have replication factor set to > 1 then you can mark a down DN as "unavailable" by using the "alter_data_node" API. Once a DN is marked unavailable, further SELECT queries will use the other chunk replica automatically. The documentation has more details: https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-ha/#node-failures

Closing this now.
