### ISSUE TITLE
Feature Request: To allow usage of FIRST_VALUE and LAST_VALUE within TIME_BUCKET data similarly to MIN or MAX

### ISSUE THREAD

**Issue by ratermir** [timescale/timescaledb#2936]
The TIME_BUCKET is really useful function, but I need to use it  in manner that I didn't find how to do it. 
I need to find first and last value from the interval returned by TIME_BUCKET function (ordered by column used in TIME_BUCKET). 
Functions MIN, MAX, AVG work perfectly for valuef from within the interval, but I would appretiate the same n´beviour for functions FIRST_VALUE and LAST_VALUE. 

My ide is tha I specify something like 

```
SELECT 
   TIME_BUCKET('5 MIN', time_column) AS interv, 
   AVG(temperature) as avg_temp,                                    -- this works
   FIRST_VALUE(temperature) AS beg_temp,                            -- this does not work
   LAST_VALUE(temperature) AS end_temp                              -- this does not work
FROM sensors
GROUP BY interv
```

In such case default ordering could be the column used in TIME_BUCKET function.
Laternative could be to specify the order explicitely:

```
SELECT 
   TIME_BUCKET('5 MIN', time_column) AS interv,
   AVG(temperature) as avg_temp,
   FIRST_VALUE(temperature) OVER (ORDER BY time_column) AS beg_temp,
   LAST_VALUE(temperature) OVER (ORDER BY time_column) AS end_temp
FROM sensors
GROUP BY interv
```
Question is about using ` WINDOW ` in such queries. 
```
SELECT 
   TIME_BUCKET('5 MIN', time_column) AS interv,
   AVG(temperature) as avg_temp,
   FIRST_VALUE(temperature) OVER w AS beg_temp,
   LAST_VALUE(temperature) OVER w AS end_temp
FROM sensors
GROUP BY interv
WINDOW w AS (ORDER BY time_column)
```

I seeked for this but I didn't find anything useful.

**Comment by svenklemm** [comment]
We have a first and last aggregate function that should give you what you are looking for:
```
SELECT 
   TIME_BUCKET('5 MIN', time_column) AS interv, 
   AVG(temperature) as avg_temp,
   first(temperature,time_column) AS beg_temp,
   last(temperature,time_column) AS end_temp 
FROM sensors
GROUP BY interv
```

**Comment by ratermir** [comment]
It works, thank you. I missed these functions.

**Comment by RezaRahmati** [comment]
> We have a first and last aggregate function that should give you what you are looking for:
> 
> ```
> SELECT 
>    TIME_BUCKET('5 MIN', time_column) AS interv, 
>    AVG(temperature) as avg_temp,
>    first(temperature,time_column) AS beg_temp,
>    last(temperature,time_column) AS end_temp 
> FROM sensors
> GROUP BY interv
> ```

You are my savior 👍

**Comment by dgsardina** [comment]
The first and last methods are useful, but there is no simple way to avoid Null values in the output. Any way around it?

**Comment by svenklemm** [comment]
You can use aggregate filters together with first/last
```
SELECT 
   TIME_BUCKET('5 MIN', time_column) AS interv, 
   AVG(temperature) as avg_temp,
   first(temperature,time_column) FILTER(WHERE time IS NOT NULL) AS beg_temp,
   last(temperature,time_column) FILTER(WHERE time IS NOT NULL) AS end_temp 
FROM sensors
GROUP BY interv
```

**Comment by dgsardina** [comment]
@svenklemm you cannot imagine how much time I lost trying to find a solution... This should probably be in the examples for first and last in timescale docs!
Thank you for your help. I hope it will help the next one that tries finding this out
