### ISSUE TITLE
Timescaledb breaks ALTER TABLE on normal tables

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2937]
Broken on PG12 and PG13 didnt test other versions.

```
dev=# create table t(f1 int NOT NULL GENERATED ALWAYS AS IDENTITY);
CREATE TABLE
Time: 13.493 ms
dev=# alter table t alter COLUMN f1 DROP IDENTITY, ALTER COLUMN f1 SET DATA TYPE bigint;
ERROR:  XX000: cache lookup failed for relation 13476798
LOCATION:  getRelationTypeDescription, objectaddress.c:4178
Time: 14.718 ms
```

To reproduce:
create table t(f1 int NOT NULL GENERATED ALWAYS AS IDENTITY);
alter table t alter COLUMN f1 DROP IDENTITY, ALTER COLUMN f1 SET DATA TYPE bigint;

Without the extension installed the ALTER TABLE succeeds.

**Comment by jflambert** [comment]
sounds major. When was this introduced? I'm still using 2.0.0 and I haven't encountered this...

**Comment by svenklemm** [comment]
Pretty sure its in there since forever but it's actually an upstream bug. The bug is triggered by the `DROP IDENTITY` so most ALTER TABLE statements are probably fine and won't exhibit this behaviour.

https://www.postgresql-archive.org/pg-event-trigger-ddl-commands-fails-with-cache-lookup-failed-td6179828.html#a6185158

**Comment by svenklemm** [comment]
Fixed in PG14
https://github.com/postgres/postgres/commit/2d689babe3cb50dcb29f6ed595a61d56e518c0d8
