### ISSUE TITLE
Timescaledb vs Postgresql

### ISSUE THREAD

**Issue by xarisxaris** [timescale/timescaledb#2951]
I am trying to do a comparison on timescaledb vs postgresql on timeseries.I have data that consist of one million rows and 23 column(around 120mb).I am doing some queries(finding max,average,min etc) via python to a timescaledb database and a postgresql database with the same data inside.The thing is that postgresql seems to be faster than timescaledb .On timescaledb i created a table named 'nc_durhamwithorder' and then i converted it to hypertable using date2 .Then i imported the dataset.The data look like this:
![Screenshot from 2021-02-16 19-19-33](https://user-images.githubusercontent.com/17195067/108098360-f1893c00-708b-11eb-857c-dbabed3c342b.png)

Should i use time to convert to hypertable?Do i need to adjust something?I am sure i did something wrong but i dont know what!
Thanks in advance!

**Comment by erimatnor** [comment]
@xarisxaris There are many things that could explain the performance you are seeing. For instance:

* Small datasets typically see no performance advantage on TimescaleDB vs PostgreSQL (in fact, they might be slightly slower)
* How you setup partitioning
* Chunk size
* The queries run (they should typically be time-oriented restriction clause)
*  ...and so on.

I recommend you to reach out to our Slack community: https://slack.timescale.com/
