### ISSUE TITLE
Interval issue when upgrading to 2.0.1 

### ISSUE THREAD

**Issue by dboyleitrs** [timescale/timescaledb#2952]
**Relevant system information:**
 - OS: linux/amd64
 - PostgreSQL version (output of `postgres --version`): 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4 -> 2.0.1
 - Installation method: Docker image: `timescaledev/timescaledb-ha:pg12.5-ts2.0.1-p0`

I'm attempting to upgrade Timescale to 2.0.1 following the steps here:
https://docs.timescale.com/latest/update-timescaledb/update-tsdb-2

When I execute the `ALTER EXTENSION timescaledb UPDATE;` as the first command in a psql session, I am receiving the following output:
```
ERROR:  invalid input syntax for type interval: "null"
CONTEXT:  PL/pgSQL function inline_code_block line 5 at FOR over SELECT rows
```

**To Reproduce**
1. Start database cluster with docker image: `timescaledev/timescaledb-ha:pg12.5-ts1.7.4-p1`
2. Restart cluster with new image: `timescaledev/timescaledb-ha:pg12.5-ts2.0.1-p0`
3. Start psql shell with: `psql -X -d hub`
4. Issue: `ALTER EXTENSION timescaledb UPDATE;` 

**Expected behavior**
I expect the timescaledb extension update to succeed. 

**Actual behavior**
The error above occurs and when I check the version of the extensions it is still at 1.7.4.

**Comment by erimatnor** [comment]
@dboyleitrs Thank you for reporting this issue. Sounds like an issue with the update script. Do you have any more context information to give us, like the exact line in the update script that fails?

**Comment by dboyleitrs** [comment]
That's for the prompt reply. 
You can see in the error message that it's line 5 of the script.

**Comment by dboyleitrs** [comment]
I tried upgrading again with a newer image, but the same behavior still occurs. 
`timescaledev/timescaledb-ha:pg12.6-ts2.1.0-p0`

**Comment by aelg** [comment]
Think I saw something similar when updating with retention policies active (on integer based hypertable). Removing the retention_policy solved it for me.

**Comment by nrlulz** [comment]
It does seem to be related to drop chunks policies. I just ran into this error myself trying to upgrade from 1.7.5 to 2.1.0 on Ubuntu. I'm not sure if it was any or all of them, but I just removed all three and was then able to update.

This is what it looked like before:

```
phytochrome=# select * from timescaledb_information.drop_chunks_policies;
        hypertable        |  older_than   | cascade | job_id | schedule_interval | max_runtime | max_retries | retry_period | cascade_to_materializations 
--------------------------+---------------+---------+--------+-------------------+-------------+-------------+--------------+-----------------------------
 chrome_datareading       | (t,"6 mons",) | f       |   1027 | 1 day             | 00:05:00    |          -1 | 00:05:00     | f
 chrome_diagnosticreading | (t,"6 mons",) | f       |   1028 | 1 day             | 00:05:00    |          -1 | 00:05:00     | f
 chrome_eventlog          | (t,"7 days",) | f       |   1029 | 1 day             | 00:05:00    |          -1 | 00:05:00     | f
(3 rows)
```

**Comment by dboyleitrs** [comment]
I can verify what @aelg and @nrlulz said. We removed our drop chunks policies on our non-timestamp hypertables and the extension upgrade was able to complete without errors. 
Will there be a fix for this in the script or will we have to perform this additional step on our own?
