### ISSUE TITLE
Support Multinode: ON CONFLICT DO UPDATE

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#2963]
Multinode doesn't support `ON CONFLICT DO UPDATE` currently. The current code errors out as required but the error message is also not very helpful. 

This issue will track adding this support in `multinode` environments.

**Comment by mrendi29** [comment]
+1 for implementing this feature.

**Comment by satyabratsahoo** [comment]
+1 for implementing this feature. Really needed

**Comment by afraisse** [comment]
+1 for implementing this feature.

**Comment by krishnaprathap** [comment]
+1 for implementing this feature.

**Comment by dataisamazing** [comment]
+1 for implementing this feature.

**Comment by aatishk** [comment]
Yup. Another +1 as this is quite a necessity.

**Comment by NarcisseGag** [comment]
+1 for implementing this feature.

**Comment by sdj-incom** [comment]
+1 It would make a huge difference

**Comment by svenklemm** [comment]
multinode has been removed
