### ISSUE TITLE
[Upgrade to 2.0] Packet collision on CentOS 8

### ISSUE THREAD

**Issue by Andi2405** [timescale/timescaledb#2967]
I want to upgrade timescaledb from version 1.7.5 to 2.0.X in PostgreSQL 12 on Centos 8. When I execute `dnf install timescaledb-2-postgresql-12` there is an error like 

> File /usr/lib64/timescaledb-loader-pg12/timescaledb.control from installation of timescaledb-2-loader-postgresql-12-2.0.2-0.el8.x86_64 collides with the same file in timescaledb-loader-postgresql-12-1.7.5-0.el8.x86_64

Do I have to uninstall the old version of timescaledb first? I really do not want to destroy my database setup.

**Comment by Andi2405** [comment]
Can be fixed by downgrading to 1.7.4 before installing version 2.0 via dnf/yum

**Comment by svenklemm** [comment]
The conflict is only in the loader package and the 2.0 loader can load 1.7

**Comment by svenklemm** [comment]
@Andi2405 so if you downgrade to 1.7.4 you can install 2.0.2 without conflicts?

**Comment by Andi2405** [comment]
I saw that in version 1.7.5 the dependency to the timescaledb-loader was added. So when I downgraded to 1.7.4 (using autoremove) the loader was uninstalled and I could then straight forward install version 2.0

**Comment by svenklemm** [comment]
Thanks for the report. This should be fixed in 2.1.0. Feel free to reopen if you still experience the issue with the 2.1.0 loader package.
