### ISSUE TITLE
partition using derived values

### ISSUE THREAD

**Issue by bwgroff** [timescale/timescaledb#297]
I have a use case where I'd like to partition using a feature derived from the actual row values. A simple example would be partitioning based on `column % 2`. In our case, we would like to be able to partition using a SQL function (explicitly, `entry_type in (1, 3, 4, 8)` or similar).

Basically we need to roll up aggregates according to groups of `entry_types` and the underlying tables are several billion rows so our indexes make this task possible but not performant.

**Comment by mfreed** [comment]
Hi @bwgroff thanks for the request.  As you know, we don't currently support this type of functionality.

I'm curious about your last comment, though:  

> Basically we need to roll up aggregates according to groups of entry_types and the underlying tables are several billion rows so our indexes make this task possible but not performant.

Is this while using TimescaleDB?  For most users, time partitioning can be used to keep those tables much more modest when desired.  It would help to better understand the use case for your request, where time partitioning or hash partitioning on `entry_type` wouldn't be sufficient.

Thanks!

**Comment by mfreed** [comment]
Hi @bwgroff  I believe this has been fixed with https://github.com/timescale/timescaledb/pull/639, which was part of our 1.1 release.

Closing this issue for now, feel free to re-open if doesn't solve your problems.
