### ISSUE TITLE
update from version "1.7.5" to version "2.0.1"

### ISSUE THREAD

**Issue by tpedoussaut** [timescale/timescaledb#2976]
I'm running v1.7.5 and would like to upgrade to Timescale 2.0 (using Ubuntu PPA)

Following the doc, I end up with this error message:
ERROR: extension "timescaledb" has no update path from version "1.7.5" to version "2.0.1".

How could I find a correct path ? Via a 2.0.0 wihich I can't find anymore.

**Comment by svenklemm** [comment]
You need to upgrade to either 2.0.2 or 2.1.0

**Comment by erimatnor** [comment]
Closing since solution has been proposed.

**Comment by tpedoussaut** [comment]
I can confirm this update path is possible. The reason for the issue was availability on the PPA of 1.7.5 while 2.0.2 wasn't yet (still 2.0.1).
