### ISSUE TITLE
Questions regarding getting and setting chunk_time_interval

### ISSUE THREAD

**Issue by freol35241** [timescale/timescaledb#2985]
Hi, I have some questions, related to the `chunk_time_interval` used by TimescaleDB, that I have not managed to wrap my head around:

* How can I get the currently configured `chunk_time_interval`? I know that I can find the the `chunk_time_interval` that is being used for the current chunk for example by looking at the ranges returned by `chunk_relation_size_pretty()`, but as I understand it, that is not necessarily the latest configured `chunk_time_interval` (i.e. as updated by calling `set_chunk_time_interval()`). So, in other words: How could I get my hands on the latest configured (but not yet put in use) `chunk_time_interval`?

* If I call `create_hypertable()` repeatedly on the same table with different `chunk_time_interval`-parameters while setting `if_not_exists` to True, will the `chunk_time_interval` of the table be updated?

* If I create a new hypertable using `create_hypertable()` specifying a `chunk_time_interval` and then directly afterwards update the `chunk_time_interval` to something else using `set_chunk_time_interval()`, which `chunk_time_interval` will be used for the first chunk?

Thanks in advance!

**Comment by erimatnor** [comment]
You can see the currently configured chunk interval in the `timescaledb_information.dimensions` view. You need to be on a 2.0+ version of TimescaleDB for this to work.

You should only call `create_hypertable()` once on a table. I believe doing it several times should throw an error.

If you set a new chunk time interval it will apply to any future chunks that do not yet exist.
