### ISSUE TITLE
setup/timescaledb-tune.exe fails with unknown major PG version: PostgreSQL 13.2

### ISSUE THREAD

**Issue by ST-DDT** [timescale/timescaledb#2991]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version: `postgres (PostgreSQL) 13.2`
 - TimescaleDB version: `timescaledb-postgresql-13_2.1.0-windows-amd64.zip`
 - Installation method: Run `setup.exe`

**Describe the bug**

```txt
2021/02/27 00:10:09 WELCOME to TimescaleDB Windows installer!
2021/02/27 00:10:09 timescaledb-tune is a program that modifies your postgresql.conf configuration to be optimized for your machine's resources.
Do you want to run timescaledb-tune.exe now? [(y)es / (n)o]: y
Please enter the path to your postgresql.conf:
C:\Program Files\PostgreSQL\13\data\postgresql.conf
EXIT: unknown major PG version: PostgreSQL 13.2

2021/02/27 00:10:32 ERROR: could not run timescaledb-tune: error occurred with command './timescaledb-tune.exe --conf-path=C:\Program Files\PostgreSQL\13\data\postgresql.conf --color=false': exit status 1
Press ENTER/Return key to close...
```

**To Reproduce**
Fresh install of postgres 13.2
Download zip and run setup.exe, confirm "run timescaledb-tune.exe" with `y`

**Expected behavior**
The tune tool does not fail to tune the postgres.conf

**Actual behavior**
The tune tool fails with a strange error message. IIRC timescaledb is supposed to be compatible with 13.2 but not earlier versions.
`EXIT: unknown major PG version: PostgreSQL 13.2`

**Screenshots**
N/A

**Additional context**
Newly installed postgres installation.
If I skip the tune step, then the setup completes without issues and without tuning the conf ( I haven't tested whether the extension actually works in that setup ).

**Comment by Yonis-H** [comment]
Hey I got the same issue, did you find a solution yet?

**Comment by ST-DDT** [comment]
Unfortunately not

**Comment by Yonis-H** [comment]
I was thinking of downgrading postgreSQL to 11 instead of 13.2. what are your thoughts on it?

**Comment by danielgavrilov** [comment]
Seems like support for v13 has been merged just 5 days ago: https://github.com/timescale/timescaledb-tune/issues/74 https://github.com/timescale/timescaledb-tune/pull/77

But the `timescaledb-tools` package (containing `timescaledb-tune`) has not yet been published in all repositories (e.g. [homebrew](https://github.com/timescale/homebrew-tap/blob/master/timescaledb-tools.rb#L5) is still on `0.10.1` instead of the latest `0.11.0`)

If you have the Go runtime (1.12+), you can install the latest version of `timescaledb-tune` (`0.11.0`):

```
$ go get github.com/timescale/timescaledb-tune/cmd/timescaledb-tune
```

And then run it from your `$GOPATH`. I can confirm this worked for me.

Otherwise, you can wait until the latest version of `timescaledb-tools` is published to all repositories.

**Comment by Yonis-H** [comment]
@danielgavrilov thank you for your help but I'm not familiar with the `go get` command. Im new to this and this the 1st time trying to use timescaledb. how and where do i excite the command?

**Comment by svenklemm** [comment]
If you skip the timescaledb-tune step in the installation process everything should work.

**Comment by michaelward94** [comment]
I'm running into the exact same bug. 

- OS: Windows 10
- PostgreSQL version: ```postgres (PostgreSQL) 13.1```
-  TimescaleDB version: ```timescaledb-postgresql-13_2.1.0-windows-amd64```
- Installation method: ```setup.exe```

I can install Timescale by bypassing ```timescaledb-tune``` during setup, but postgres will not allow timescale as an extension because shared_preloaded_libraries needs to be updated by tune.

**Comment by RobAtticus** [comment]
New packages for Windows for PG13 have been uploaded with an upgraded version of tune.

**Comment by ST-DDT** [comment]
Now it works as expected. Thank you!

**Comment by aantix** [comment]
@RobAtticus I've tried even compiling from source for 2.1, but I still receive the following :

<img width="699" alt="image" src="https://user-images.githubusercontent.com/4600/110071464-b18baf80-7d41-11eb-8c73-21ed64bb9b1b.png">

Running Ubuntu 18..

**Comment by ST-DDT** [comment]
Timescale db does not support 13.0 and 13.1 due to a security (?) related bug in those versions. You have to upgrade to 13.2.

**Comment by yashnerkar** [comment]
I'm running into the exact same bug.

    OS: Windows 10
    PostgreSQL version: postgres (PostgreSQL) 15.0
    TimescaleDB version: timescaledb-postgresql-15-windows-amd64
    Installation method: setup.exe
