### ISSUE TITLE
unrecognized parameter "timescaledb.table_name"

### ISSUE THREAD

**Issue by Alphathon-LLC** [timescale/timescaledb#2993]
CREATE TABLE nse_futures_eod(
	"date" date NOT NULL,
	instrument varchar(6) NOT NULL,
	symbol varchar(10) NOT NULL,
	expiry date NOT NULL,
	"open" numeric NOT NULL,
	high numeric NOT NULL,
	low numeric NOT NULL,
	"close" numeric NOT NULL,
	settle_price numeric NOT NULL,
	volume int4 NOT NULL,
	traded_value numeric NOT NULL,
	oi int4 NOT NULL,
	oi_change int4 NOT NULL,
	CONSTRAINT futpkey PRIMARY KEY (date, symbol, expiry)
);
CREATE INDEX fut1 ON public.nse_futures_eod USING btree (date desc, expiry desc);
CREATE INDEX fut2 ON public.nse_futures_eod USING btree (symbol,expiry desc);
CREATE INDEX fut4 ON public.nse_futures_eod USING btree (symbol, date desc);
CREATE INDEX fut3 ON public.nse_futures_eod USING btree (date desc);

SELECT * FROM create_hypertable('nse_futures_eod', 'date', 'expiry');

create materialized VIEW  nse_futures_combined 
with (timescaledb.nse_futures_eod) as 
select date, symbol, sum(oi), sum(oi_change)
from nse_futures_eod 
group by date , symbol;

Getting Error:
unrecognized parameter "timescaledb.nse_futures_eod"

**Comment by svenklemm** [comment]
Seems like you are trying to create a continuous aggregate. The correct syntax for that would be:
```
create materialized VIEW nse_futures_combined
with (timescaledb.continuous) as
select date, symbol, sum(oi), sum(oi_change)
from nse_futures_eod
group by date , symbol;
```

**Comment by NunoFilipeSantos** [comment]
Thank you @svenklemm! Closing.
@Alphathon-LLC feel free to reopen.
