### ISSUE TITLE
Unable to create partial index - cache lookup failed

### ISSUE THREAD

**Issue by Pagehey** [timescale/timescaledb#2997]
Hi, I have an error when I try to create a partial index on an hypertable. No problem on other tables or without `WHERE` condition. 

I can't find anything else as relevant as the issue I originally posted (see below).

Could you please help me finding what is going on and how I could fix this. The only posts I founded were on old postgres archives and were talking about droping the table as a fix ... I can't believe there is no other solution.

thanks for your time.

When I try creating an index with: 
```sql
CREATE INDEX ON timescaled_items (time ASC, opinum_source_id)
    WHERE value > 0 AND kind = 'B_Volume_30m_Best'
```

It failed with: 
```sql
ERROR:  cache lookup failed for attribute 3 of relation 0
```

PG version: 
`PostgreSQL 12.6 (Ubuntu 12.6-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit` 

Timescaledb version: `1.7.4`.

```sql
SELECT * FROM pg_language;

  oid  | lanname  | lanowner | lanispl | lanpltrusted | lanplcallfoid | laninline | lanvalidator | lanacl 
-------+----------+----------+---------+--------------+---------------+-----------+--------------+--------
    12 | internal |       10 | f       | f            |             0 |         0 |         2246 | 
    13 | c        |       10 | f       | f            |             0 |         0 |         2247 | 
    14 | sql      |       10 | f       | t            |             0 |         0 |         2248 | 
 13577 | plpgsql  |       10 | t       | t            |         13574 |     13575 |        13576 | 

```

_Originally posted by @Pagehey in https://github.com/timescale/timescaledb/issues/1494#issuecomment-788993398_

**Comment by svenklemm** [comment]
This is fixed in master so upgrading to a recent 2.x release should fix this.

**Comment by erimatnor** [comment]
Closing since fixed. Please reopen if this turns out to not be the case.
