### ISSUE TITLE
The remote_txn.sql test fails intermittently in CI runs

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#3004]
The `remote_txn.sql` test tends to fail intermittently in CI runs. The diff looks like below:

```
@@ -231,14 +231,16 @@                                                           
                                                                                
 COMMIT;                                                                        
 WARNING:  kill event: waiting-commit                                           
-WARNING:  transaction rollback on data node "loopback" failed                  
-ERROR:  [loopback]: terminating connection due to administrator command        
+WARNING:  leak check: ERROR ["FATAL:  terminating connection due to administrator command
+SSL connection has been closed unexpectedly                                    
+"]      
```

It appears that after we kill the remote backend, it takes some more time to exit cleanly leading to additional diffs.

**Comment by nikkhils** [comment]
There is another failure in this `remote_txn.sql` test:

```
@@ -471,7 +471,7 @@                                                             
 -- platforms/environments we remove it from test output and show SQLSTATE instead.
 -- SQLSTATE should be 08006 connection_failure                                 
 \echo 'COMMIT SQLSTATE' :SQLSTATE                                              
-COMMIT SQLSTATE 08006                                                          
+COMMIT SQLSTATE 00000                                                          
 --the connection should be cleared from the cache                              
 SELECT node_name, connection_status, transaction_status, transaction_depth, processing
 FROM _timescaledb_internal.show_connection_cache() ORDER BY 1,4;
```

again got to do with connection going away cleanly in this case when in fact should have indicated a failed connection due to the kill event.

**Comment by NunoFilipeSantos** [comment]
Please check with @erimatnor Monday.

**Comment by NunoFilipeSantos** [comment]
https://github.com/timescale/timescaledb-private/issues/802

**Comment by nikkhils** [comment]
The `RegisterXactCallback` function in the test eventually does the following on the access node:

1) Send an async command to the remote node

2) Invoke the eventcallback, for example: `eventcallback(DTXN_EVENT_WAIT_COMMIT)` which kills the remote node backend

3) Wait for async responses for (1) from remote node and expect it to fail due to the killing of the remote backend in (2) above.

The above works most of the times but it's possible that (1) completes successfully and returns successful async response via (3) before the remote backend gets killed via (2). 

Need to find a way to slow down the remote backend such that (2) gets a chance to kill it when it's processing (1)

**Comment by nikkhils** [comment]
A good way to slow down the remote backend in (1) is to make it emit a lot of debug information while it's completing the transaction. That should provide (2) time to kill the remote backend in the midst of activity. 

Although this is not guaranteed to be a sure shot way to ensure predictability, it will surely make the test a little less flaky and that's an improvement IMO over what we have currently.

**Comment by nikkhils** [comment]
But the above method still leaves a window of unpredictability.

To ensure predictability, we want to kill the remote backend when it's in the midst of processing the transaction. To ensure that the access node sets the event handler and then takes an exclusive lock on the "remote_conn_xact_end" advisory lock via "debug_waitpoint_enable" function

The "RegisterXactCallback" callback on the remote backend tries to take this same advisory lock in shared more and waits. This allows the event handler enough time to kill this remote backend at the right time

Don't forget to release lock via debug_waitpoint_release on the access node otherwise the remote backend doesn't get a chance to respond to the SIGTERM appropriately!

**Comment by nikkhils** [comment]
The above approach is leading to hangs. The `CommitTransaction` function on the remote backend holds off interrupts during critical part of the commit processing. This "RegisterXactCallback" when it happens with interrupts held does not allow this backend to die and hence it keeps on trying to get the advisory lock.

**Comment by nikkhils** [comment]
Fixed the above issue and PR created: https://github.com/timescale/timescaledb/pull/3020

**Comment by nikkhils** [comment]
Sigh.. the following issue is still coming up on CI:

```
@@ -471,7 +471,7 @@                                                             
 -- platforms/environments we remove it from test output and show SQLSTATE instead.
 -- SQLSTATE should be 08006 connection_failure                                 
 \echo 'COMMIT SQLSTATE' :SQLSTATE                                              
-COMMIT SQLSTATE 08006                                                          
+COMMIT SQLSTATE 00000                                                          
 --the connection should be cleared from the cache                              
 SELECT node_name, connection_status, transaction_status, transaction_depth, processing
 FROM _timescaledb_internal.show_connection_cache() ORDER BY 1,4;
```

**Comment by nikkhils** [comment]
Fixed the above issue and PR ready for review: #3020

**Comment by jnidzwetzki** [comment]
The `SQLSTATE 00000` result in the `remote_txn` test occurred again in a CI run (474b09bdfc1f7bf2fe9039c07d6a97f34b9bd495)

```
diff -u /home/runner/work/timescaledb/timescaledb/tsl/test/expected/remote_txn.out /home/runner/work/timescaledb/timescaledb/build/tsl/test/results/remote_txn.out
--- /home/runner/work/timescaledb/timescaledb/tsl/test/expected/remote_txn.out	2023-03-06 00:07:58.899605311 +0000
+++ /home/runner/work/timescaledb/timescaledb/build/tsl/test/results/remote_txn.out	2023-03-06 00:16:00.79[38](https://github.com/timescale/timescaledb/actions/runs/4338670720/jobs/7575536103#step:19:39)16118 +0000
@@ -553,7 +553,7 @@
 -- platforms/environments we remove it from test output and show SQLSTATE instead.
 -- SQLSTATE should be 08006 connection_failure
 \echo 'COMMIT SQLSTATE' :SQLSTATE
-COMMIT SQLSTATE 08006
+COMMIT SQLSTATE 00000
 SELECT debug_waitpoint_release('remote_conn_xact_end');
  debug_waitpoint_release 
 -------------------------
```

See: https://github.com/timescale/timescaledb/actions/runs/4338670720/jobs/7575536103

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
