### ISSUE TITLE
Package Unavailable for ARM64 - Ubuntu 20.04

### ISSUE THREAD

**Issue by rainbowhat** [timescale/timescaledb#3008]
**Relevant system information:**
 - OS: Ubuntu 20.04 (ARM)
 - PostgreSQL 13
 - TimescaleDB version :  2.1.0
 - Installation method: apt install

Error : 
E: Unable to locate package timescaledb-2-postgresql-13

https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu

Ubuntu > APT > 13 (Version)

Unable to run "sudo apt install timescaledb-2-postgresql-13" command , i dont think it's available on APT yet for version 2.1.0 , any ETA it would be updated to ubuntu?

**Comment by svenklemm** [comment]
Ubuntu packages for PG13 are available. See our package test here: https://github.com/timescale/timescaledb/runs/2043910150?check_suite_focus=true

**Comment by rainbowhat** [comment]
> Ubuntu packages for PG13 are available. See our package test here: https://github.com/timescale/timescaledb/runs/2043910150?check_suite_focus=true

https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu
not sure what i'm missing out, i can't run it from the instruction from the link above. 
Trying out the code in the link you provided.

**Comment by rainbowhat** [comment]
> Ubuntu packages for PG13 are available. See our package test here: https://github.com/timescale/timescaledb/runs/2043910150?check_suite_focus=true

I found the issue,
64-bit (x86)
64-bit (Arm)

It doesn't work on 64-bit(ARM) 
Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
Amazon Web Services. 

I switched over to x86, it's working alright now 

@svenklemm

**Comment by psztoch** [comment]
My team wait for arm64 build too.

**Comment by AnnaKaminska** [comment]
My team also needs arm64 build.

**Comment by kryptish** [comment]
lol, just went trough a distro upgrade from stretch to buster to run postgresql-13 (as a requirement for timescaledb) just to land here =)... yes, please, need that arm64 build!

**Comment by rainbowhat** [comment]
> apt-get install -y libkrb5-dev

apt-get install -y libkrb5-dev fixed it for you? So you're running it ok with ARM64 ?

**Comment by jdsdc** [comment]
For anyone else who wants to install on ARM64 (Raspberry PI4)
Debian image from:  https://raspi.debian.net/tested-images/ 
I guess this would work on ubuntu too.

This works but suggestions for improvements would be appreciated

### Postgres Install

```
sudo apt update
sudo apt -y install postgresql-13 postgresql-client-13
sudo pg_ctlcluster 13 main start
sudo pg_ctlcluster 13 main status

psql -U postgres -h localhost
postgres=# ALTER USER postgres PASSWORD 'postgres';
postgres=# exit
```

### Postgres Third Party Install
```
sudo apt install postgresql-common
sudo apt install -y gnupg2 && sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
```

### Build and install Timescale

```
sudo apt install -y cmake
sudo apt install -y postgresql-13 postgresql-client-13 postgresql-server-dev-13
sudo apt install -y libssl-dev
sudo apt-get install -y libkrb5-dev

mkdir timescale_sources && cd timescale_sources
wget https://github.com/timescale/timescaledb/archive/refs/tags/2.4.2.zip (alteranatively checkout github repo)
unzip 2.4.2.zip -d .
cd timescaledb-2.4.2

./bootstrap
make
sudo make install
```

### Tune Timescale

```
wget https://golang.org/dl/go1.17.2.linux-arm64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.2.linux-arm64.tar.gz
export PATH=$PATH:/usr/local/go/bin
sudo ./go/bin/timescaledb-tune (Choose default values)

sudo pg_ctlcluster 13 main restart
```

### Verify Timescale

```
psql -U postgres -h localhost
postgres=# CREATE database verificationdb;
# Connect to new database
postgres=# \c verificationdb
verificationdb=# CREATE EXTENSION IF NOT EXISTS timescaledb;
# Verify extension version
verificationdb=# SELECT extversion FROM pg_extension where extname = 'timescaledb';

verificationdb=# CREATE TABLE conditions (
    time        TIMESTAMPTZ       NOT NULL,
    location    TEXT              NOT NULL,
    temperature DOUBLE PRECISION  NULL
);

verificationdb=# SELECT create_hypertable('conditions', 'time');
```

@rainbowhat

**Comment by pbowyer** [comment]
It would be _very helpful_ if the TimescaleDB team would add a note to the "Install via APT" page (and any others) saying that ARM64 builds are not available. It's taken a while to figure that out!

**Comment by klaustopher** [comment]
@svenklemm You took over this issue a few months ago. Is there any update on making an ARM64 debian package available? The manual compilation mentioned above by @jdsdc works, but it still feels a bit strange that in our docker builds for x86 we can just `apt install`, but in our ARM64 builds, we have to compile from source.

Any update would be appreciated.

**Comment by svenklemm** [comment]
@klaustopher ubuntu 20.04 arm64 packages are available now

**Comment by klaustopher** [comment]
Great, thank you!

**Comment by hieuhtr** [comment]
thank you!
