### ISSUE TITLE
hypertable (integer-based timestamps) compression bug

### ISSUE THREAD

**Issue by nathanloisel** [timescale/timescaledb#3009]
**System information:**
 - OS: Windows 10 x64
 - PostgreSQL version: 13.2
 - TimescaleDB version: 2.1.0
 - Installation method: 
   - Docker
   - Image: timescale/timescaledb
   - Tag: latest-pg13

**Bug description**
With a hypertable whose time is based on milliseconds, after running add_compression_policy with compress_after = 1000*60*60*24*365.25/6 (2 months), I see chunks less than 2 months old compressed.

**To Reproduce**
1. Run a [timescaledb docker image](https://hub.docker.com/r/timescale/timescaledb) version: latest-pg13
2. Connect to it with psql
3. Execute the following SQL queries

```
CREATE TABLE my_data (
  time BIGINT NOT NULL,
  device_id INTEGER NOT NULL,
  value1 INTEGER NOT NULL,
  value2 INTEGER NOT NULL,
  value3 INTEGER NOT NULL
);
/*
 chunk time interval is 1 day (86400000 = 1000*60*60*24)
 */
SELECT create_hypertable(
    relation => 'my_data',
    time_column_name => 'time',
    partitioning_column => 'device_id',
    number_partitions => 1,
    create_default_indexes => false,
    chunk_time_interval => 86400000
  );
ALTER TABLE my_data
SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'device_id'
  );

-- Generate timeserie with data all days between now and 2 years ago
INSERT INTO my_data (time, device_id, value1, value2, value3)
SELECT time,
  device_id,
  random() AS value1,
  random() * 100 AS value2,
  random() * 1000 AS value3
FROM generate_series(
    (extract(
      epoch
      from now()
    ) * 1000)::BIGINT - 86400000::BIGINT*365.25*2,
    (extract(
      epoch
      from now()
    ) * 1000)::BIGINT,
    (86400000)::BIGINT
  ) AS g1(time),
  generate_series(1, 4, 1) AS g2(device_id);

-- create the now to milliseconds function
CREATE OR REPLACE FUNCTION millis_now () returns BIGINT LANGUAGE SQL STABLE as $$
SELECT (
		extract(
			epoch
			from now()
		) * 1000
	)::BIGINT $$;
SELECT set_integer_now_func('my_data', 'millis_now');

-- compression policy: all chunk older than 2 months (= 60.875 days)
SELECT add_compression_policy('my_data', floor(86400000*365.25/6)::BIGINT);

-- wait a few minutes to let the compression work finish.
-- check that there are no compressed chunks between now and 2 months ago
SELECT c.chunk_name,
    to_timestamp(c.range_start_integer/ 1000) as date_start ,
    to_timestamp(c.range_end_integer/ 1000) as date_end ,
    to_timestamp((millis_now() - floor(86400000*365.25/6)::BIGINT) / 1000) as limit_date_to_compress,
    s.compression_status
from chunks_detailed_size('my_data') t
    LEFT JOIN timescaledb_information.chunks c ON c.chunk_name = t.chunk_name
    LEFT JOIN chunk_compression_stats('my_data') s ON s.chunk_name = t.chunk_name
WHERE c.range_end_integer > millis_now() - floor(86400000*365.25/6)::BIGINT
ORDER BY c.range_end_integer;
```

**Expected behavior**
The last query should return only Uncompressed chunks

**Actual behavior**
Some chunks with range_end_integer younger than 2 months get compressed.

**Additional context**
I tried it with time as nanoseconds and I got the same problem.
The bug is also present in version 2.0.

**Comment by xin-hedera** [comment]
we see the same issue with an `integer_now` function returning timestamp in nanos. While the compression policy is set to compress chunks relatively 1 week old and chunk time interval is set to 1 day, the compression job always compresses all chunks but the current one.

**Comment by xin-hedera** [comment]
This looks to be the root cause:

https://github.com/timescale/timescaledb/blob/0a39e2ebffe5c919591b77c7fbe0a9db70f7d333/tsl/src/bgw_policy/compression_api.c#L61

the int64 compress after is cast into int32, any value > 2^31 - 1 will cause the compression jobs behave not as expected.

**Comment by mkindahl** [comment]
@nathanloisel Thank you for the bug report.

@xin-hedera That does indeed look like the root cause. Note that there seems to be a typo: the code is a copy-paste from the previous function where the hypertable id is fetched, but here the actual value is an interval.
