### ISSUE TITLE
Creating timescale extension grants privileges to unexpected roles 

### ISSUE THREAD

**Issue by brunoroque06** [timescale/timescaledb#3011]
**Relevant system information:**
- Timescale Cloud (Aiven)
 - PostgreSQL version: 12.6
 - TimescaleDB version: 2.0.1

**Describe the bug**
Privileges to schemas/tables/sequences created by timescale when running `create extension timescaledb` are granted to every role which owns a database (this is an assumption; is it correct?).

**To Reproduce**
The following:
```
create role admin_prod with login password '123';
create database prod owner admin_prod;
```
(reconnect with `admin_prod`)
```
create extension timescaledb;
```
Now the schema privileges (as well as tables/sequences, which I will omit) are the following for the database `prod`:
```
(I)> \dn+
                                       List of schemas
┌─────────────────────────┬──────────┬─────────────────────────────┬────────────────────────┐
│          Name           │  Owner   │      Access privileges      │      Description       │
├─────────────────────────┼──────────┼─────────────────────────────┼────────────────────────┤
│ _timescaledb_cache      │ postgres │ postgres=U*C*/postgres     ↵│                        │
│                         │          │ =U/postgres                ↵│                        │
│                         │          │ admin_prod=U*C*/postgres   ↵│                        │
│                         │          │ tsdbadmin=U*C*/postgres     │                        │
...
(the remaining timescale schemas would have the same privileges)
```
Now if we run the same sql commands for a different environment, say `test`, we would get the following schema privileges in the `test` database:
```
(I)> \dn+
                                       List of schemas
┌─────────────────────────┬──────────┬─────────────────────────────┬────────────────────────┐
│          Name           │  Owner   │      Access privileges      │      Description       │
├─────────────────────────┼──────────┼─────────────────────────────┼────────────────────────┤
│ _timescaledb_cache      │ postgres │ postgres=U*C*/postgres     ↵│                        │
│                         │          │ =U/postgres                ↵│                        │
│                         │          │ admin_test=U*C*/postgres   ↵│                        │
│                         │          │ admin_prod=U*C*/postgres   ↵│                        │
│                         │          │ tsdbadmin=U*C*/postgres     │                        │
...
(the remaining timescale schemas would have the same privileges)
```

**Expected behavior**
Only the owner of the database is granted such privileges.

**Actual behavior**
Our `admin_prod` owns privileges in the `test` database, which is not intended from our perspective.

**Additional context**
This is a problem for us because we are creating/destroying environments dynamically (per pull request), and this is creating an inter environment dependency which does not let us drop roles while they still own the said privileges in another database (say dropping `admin_prod` while he still owns privileges in `test`).

**Comment by svenklemm** [comment]
This is not done as part of normal timescaledb but part of the support scripts implemented by aiven.
