### ISSUE TITLE
timescaledb-tune fails with error "unknown major PG version"

### ISSUE THREAD

**Issue by krishnaghatti** [timescale/timescaledb#3012]
**Relevant system information:**

-OS: macOS Big Sur (version 11.2.2)
-PostgreSQL version: postgres (PostgreSQL) 13.2_1
-TimescaleDB version: timescaledb 2.1.0
-Installation method: brew install timescaledb

**Describe the bug**
timescaledb-tune fails with error "unknown major PG version".

$ brew install timescaledb
..........................
completes succesfully and installs timescaledb and postgresql
$ timescaledb-tune
exit: unknown major PG version: PostgreSQL 13.2

**To Reproduce**
$ brew install timescaledb
$ timescaledb-tune

**Expected behavior**
The tune tool does not fail to tune the postgres.conf

**Actual behavior**
timescaledb-tune fails with error "unknown major PG version"

**Screenshots**
NA

**Additional context**
NA

**Comment by svenklemm** [comment]
The latest version of timescaledb-tune has support for PG13 and should be available on all release channels. Feel free to reopen if that is not the case.
