### ISSUE TITLE
installcheck fails 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [timescale/timescaledb#3015]
[jw@cn06 build]$ make VERBOSE=1 -j1 installcheck
/usr/bin/cmake -S/data/jw/timescaledb -B/data/jw/timescaledb/build --check-build-system CMakeFiles/Makefile.cmake 0
make  -f CMakeFiles/Makefile2 installcheck
make[1]: Entering directory '/data/jw/timescaledb/build'
/usr/bin/cmake -S/data/jw/timescaledb -B/data/jw/timescaledb/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /data/jw/timescaledb/build/CMakeFiles 0
make  -f CMakeFiles/Makefile2 test/CMakeFiles/installcheck.dir/all
make[2]: Entering directory '/data/jw/timescaledb/build'
make  -f test/CMakeFiles/regresscheck.dir/build.make test/CMakeFiles/regresscheck.dir/depend
make[3]: Entering directory '/data/jw/timescaledb/build'
cd /data/jw/timescaledb/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/timescaledb /data/jw/timescaledb/test /data/jw/timescaledb/build /data/jw/timescaledb/build/test /data/jw/timescaledb/build/test/CMakeFiles/regresscheck.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/data/jw/timescaledb/build'
make  -f test/CMakeFiles/regresscheck.dir/build.make test/CMakeFiles/regresscheck.dir/build
make[3]: Entering directory '/data/jw/timescaledb/build'
cd /data/jw/timescaledb/build/test && /usr/bin/cmake -E env TEST_PGUSER=default_perm_user TEST_PGHOST=localhost TEST_ROLE_SUPERUSER=super_user TEST_ROLE_DEFAULT_PERM_USER=default_perm_user TEST_ROLE_DEFAULT_PERM_USER_2=default_perm_user_2 TEST_ROLE_CLUSTER_SUPERUSER=cluster_super_user TEST_ROLE_1=test_role_1 TEST_ROLE_2=test_role_2 TEST_ROLE_3=test_role_3 TEST_ROLE_2_PASS=pass TEST_ROLE_3_PASS=pass TEST_DBNAME=single TEST_INPUT_DIR=/data/jw/timescaledb/test TEST_OUTPUT_DIR=/data/jw/timescaledb/build/test TEST_SCHEDULE=/data/jw/timescaledb/build/test/test_schedule PG_BINDIR=/usr/bin PG_REGRESS=/usr/lib64/pgsql/pgxs/src/test/regress/pg_regress TEST_PGPORT=55432 /data/jw/timescaledb/test/pg_regress.sh --host=localhost --dlpath=/data/jw/timescaledb/build/src --create-role=super_user,default_perm_user,default_perm_user_2,cluster_super_user,test_role_1,test_role_2,test_role_3 --dbname=single --launcher=/data/jw/timescaledb/test/runner.sh --inputdir=/data/jw/timescaledb/test --outputdir=/data/jw/timescaledb/build/test --port=55432 --temp-instance=/data/jw/timescaledb/build/test/testcluster --temp-config=/data/jw/timescaledb/build/test/postgresql.conf
TESTS
IGNORES
SKIPS
============== removing existing temp instance        ==============
============== creating temporary instance            ==============
============== initializing database system           ==============

pg_regress: initdb failed
Examine /data/jw/timescaledb/build/test/log/initdb.log for the reason.
Command was: "/usr/bin/initdb" -D "/data/jw/timescaledb/build/test/testcluster/data" --no-clean --no-sync > "/data/jw/timescaledb/build/test/log/initdb.log" 2>&1
make[3]: *** [test/CMakeFiles/regresscheck.dir/build.make:76: test/CMakeFiles/regresscheck] Error 2
make[3]: Leaving directory '/data/jw/timescaledb/build'
make[2]: *** [CMakeFiles/Makefile2:643: test/CMakeFiles/regresscheck.dir/all] Error 2
make[2]: Leaving directory '/data/jw/timescaledb/build'
make[1]: *** [CMakeFiles/Makefile2:569: test/CMakeFiles/installcheck.dir/rule] Error 2
make[1]: Leaving directory '/data/jw/timescaledb/build'
make: *** [Makefile:248: installcheck] Error 2
[jw@cn06 build]$

**Comment by fabriziomello** [comment]
@LutzWeischerFujitsu what is the content of `/data/jw/timescaledb/build/test/log/initdb.log` file?

**Comment by gayyappan** [comment]
Our CI builds work without errors. Please reopen if you are still running into this (with the information requested above)?
