### ISSUE TITLE
Support Multinode: Distributed hypertables - compressed chunks - Update/Delete on compressed chunks of does not return error

### ISSUE THREAD

**Issue by majozv** [timescale/timescaledb#3016]
When using compression on distributed hypertables and trying to perform an UPDATE or DELETE on compressed chunk, no error is returned.

Should be: SQL Error [errcode]: ERROR: cannot update/delete rows from chunk "_dist_hyper_5876_469_chunk" as it is compressed

(INSERT works OK, error message is returned in similar case)

**Comment by gayyappan** [comment]
The error message returned on master (2.5 ) for this case is:
```
distr=# update compressed set temp = 120 where device = 100;
ERROR:  [dn1]: transparent decompression only supports tableoid system column

distr=# delete from compressed where device = 100;
ERROR:  [dn1]: transparent decompression only supports tableoid system column

```
We need a better error for this case.

**Comment by majozv** [comment]
HI @pmwkaa, 
I can't confirm it because we are no longer using distributed hypertables and we have dropped our environment (migrating to single node environment). 
You can close it as obsolete.
Thanks 
M

**Comment by majozv** [comment]
This bug was observed on older version of TSDB
