### ISSUE TITLE
Reindex of distributed hypertable does not work

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3018]
Running `REINDEX TABLE <dist_hypertable>` on a distributed hypertable fails, probably because reindexing is recursed all chunks, which in the case of distributed hypertables are foreign tables that don't support indexes (and hence not `REINDEX` either).

We should therefore not recurse `REINDEX` to chunks on distributed hypertables.

**Comment by pmwkaa** [comment]
@erimatnor do you have an example how this operation fails? We actually block it now with proper message:
```
REINDEX TABLE disttable; 
ERROR:  operation not supported on distributed hypertable
```

Is the idea to make it work or to block `INDEX`, eg: `REINDEX INDEX <remote_chunk_index>` ?

**Comment by pmwkaa** [comment]
The issue is reproducible in case if dist hypertable has chunks

```
+REINDEX TABLE disttable;
+ERROR:  "_dist_hyper_1_1_chunk" is not a table or materialized view
```

**Comment by nikkhils** [comment]
REINDEX CONCURRENTLY has issues. Need test and investigation.

**Comment by pmwkaa** [comment]
Related issue: https://github.com/timescale/timescaledb/issues/3122
