### ISSUE TITLE
hypertable_detailed_size shows incorrect toast_bytes for table without TOAST fields

### ISSUE THREAD

**Issue by darkleaf** [timescale/timescaledb#3019]
**Relevant system information:**
 - OS: linux
 - PostgreSQL version: PostgreSQL 13.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit,
 - TimescaleDB version: 2.1.0

**Describe the bug**

I have a table with all fields are stored as 'plain'.
The `hypertable_detailed_size` function incorrectly shows not zero `toast_bytes`, 
but the `hypertable_compression_stats`  function shows 0 in the `before_compression_toast_bytes` field.

For a table with the same schema on Postgres 11 and timescale 1.7 the `hypertable_relation_size` function shows NULL for `toast_bytes`.

**Expected behavior**
The `hypertable_detailed_size` function shows correct data in the `toast_bytes` field.

**Actual behavior**
The `hypertable_detailed_size` function shows not zero in the `toast_bytes` field for a table without TOAST fields.

**Screenshots**
<img width="1673" alt="Снимок экрана 2021-03-11 в 15 43 43" src="https://user-images.githubusercontent.com/1124593/110782570-c22bb080-8280-11eb-830b-1a922f2d6867.png">

**Comment by erimatnor** [comment]
@darkleaf when a hypertable has compression enabled, and some chunks are compressed, you will have toasted fields (and thus a non-zero `toast_bytes`). Thus, `hypertable_detailed_size` reports the aggregate bytes over both compressed and uncompressed data. 

You can see that the toast bytes before compression was 0 while the toast bytes after compression is 214MB, which is also what is reported in `hypertable_detailed_size`.

**Comment by darkleaf** [comment]
Thanks for the explanation. Is there an analog for `hypertable_relation_size` from 1.7? I want to see stats only for uncompressed chunks.

**Comment by erimatnor** [comment]
There is no analogue for 1.7, unfortunately. We reworked these size functions for the 2.0 release, so if you'd like to use them I suggest you upgrade. 

Closing this issue since there doesn't seem to be a bug. Feel free to reopen if the situation changes.
