### ISSUE TITLE
 server process was terminated by signal 11: Segmentation fault

### ISSUE THREAD

**Issue by blockpete** [timescale/timescaledb#3033]
**Relevant system information:**
 - OS: docker 20.10.2 (on debian10)
 - PostgreSQL version (output of `postgres --version`): 11.11
 - TimescaleDB version 2.1.0
 - Installation method: Docker image 2.1.0-pg11

**Describe the bug**
An insert into a specific hypertable causes a segmentation fault. This does not happen an indentical system running the same database and schema.
dmesg: segfault at 10 ip 00007fdccbcc1ba8 sp 00007ffed15dd0d8 error 4 in timescaledb-2.1.0.so[7fdccbca8000+49000]
We deleted all rows and chunks for the table (not recreating it). Same effect. We tested on an different VM. Same effect. For this particular database. We have core dumps.

**To Reproduce**
Execute insert

**Expected behavior**
A succcesful insert.

**Actual behavior**
Insert causes postgresql to crash.

**Screenshots**
I

**Additional context**
We deleted all rows and chunks for the table (not recreating it). Same effect. We tested on an different VM. Same effect.  We have a core dump for analysis.

**Comment by svenklemm** [comment]
@blockpete can you post the exact query that causes the segfault, could you provide a stacktrace from a debug build.

**Comment by blockpete** [comment]
@svenklemm Could you please advise what the best way is to craete a stacktrace from a debug build in docker container ?

Here is the query:

INSERT INTO "buckets" (time,instrument,account,currency,exchange,expiry,trade_roll,trade_total_delta,trade_scalp,trade_theta,trade_vola,trade_total_pnl,trade_external_delta,fee,position_roll,position_total_delta,position_scalp,position_theta,position_vola,position_total_pnl,own_credit,own_size,market_credit,market_size)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
        ON CONFLICT (time,instrument,account,currency,exchange)
        DO UPDATE SET expiry = EXCLUDED.expiry, trade_roll = EXCLUDED.trade_roll, trade_total_delta = EXCLUDED.trade_total_delta, trade_scalp = EXCLUDED.trade_scalp, trade_theta = EXCLUDED.trade_theta, trade_vola = EXCLUDED.trade_vola, trade_total_pnl = EXCLUDED.trade_total_pnl, trade_external_delta = EXCLUDED.trade_external_delta, fee = EXCLUDED.fee, position_roll = EXCLUDED.position_roll, position_total_delta = EXCLUDED.position_total_delta, position_scalp = EXCLUDED.position_scalp, position_theta = EXCLUDED.position_theta, position_vola = EXCLUDED.position_vola, position_total_pnl = EXCLUDED.position_total_pnl, own_credit = EXCLUDED.own_credit, own_size = EXCLUDED.own_size, market_credit = EXCLUDED.market_credit, market_size = EXCLUDED.market_size

**Comment by blockpete** [comment]
I propose to close the issue a reindex of the database solved the issue. So I am not sure this should be reported as a bug as it can be treated as lack of database administration maintenance..

**Comment by erimatnor** [comment]
@blockpete The database should not segfault even though a workaround is available. However, until a core dump, backtrace, and/or a reproducible test case is available, we'll treat this as resolved. Please reopen if the situation changes.
