### ISSUE TITLE
Failing Jobs Run Forever, Ignoring max_retries

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#3035]
**Relevant system information:**
 - TimescaleDB version (output of `\dx` in `psql`): 2.1.0

**Describe the bug**
While the documentation describes being able to set a `max_retries` value for a background worker, the [scheduler code on failure
](https://github.com/timescale/timescaledb/blob/954c775275123d22e981261ad1043a287b6b432c/src/bgw/job_stat.c#L198-L278) doesn't seem to actually handle this value, resulting in failed jobs running forever. It does use the retry_interval to reschedule, but it does not ever halt job execution after any number of consecutive failures.

**To Reproduce**
```sql
--create working procedure
CREATE OR REPLACE PROCEDURE failure(job_id int, config jsonb) LANGUAGE PLPGSQL AS
$$
BEGIN
  RAISE NOTICE 'Executing action % with config %', job_id, config;
END
$$;


--add it as a job
SELECT add_job('failure','1h');


--alter its schedule so it runs once a second, with a max_retry of 4, and start it now. Alter job id as necessary
SELECT alter_job(1000, max_retries => 4, schedule_interval => interval '1 second', next_start => now());

--see it running
select * from timescaledb_information.job_stats;

--break the function - this has an unhandled select, which errors out when the procedure is called.
CREATE OR REPLACE PROCEDURE failure(job_id int, config jsonb) LANGUAGE PLPGSQL AS
$$
BEGIN
  RAISE NOTICE 'Executing action % with config %', job_id, config;
  select * from test;
END
$$;

--see it is now failing, and keeps running forever
select * from timescaledb_information.job_stats;
```

**Expected behavior**
I would expect that this job would be disabled after reaching max_retries

**Actual behavior**
The job runs forever.

**Comment by mohini-gupta** [comment]
(new to timescaledb)

I am facing the same issue. 

Also, when I query `call run_job(job_id)` , it shows error message: `function does not exists`.

**Comment by dk-bboyer** [comment]
I am currently having the same issue, has there been no movement on this?
