### ISSUE TITLE
Segmentation fault when selecting without limit

### ISSUE THREAD

**Issue by mglonnro** [timescale/timescaledb#3040]
**Relevant system information:**
 - 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
 - (PostgreSQL) 11.7 (Debian 11.7-2.pgdg90+1)
 - timescaledb | 2.1.0 
 - apt install

**Describe the bug**
I get a segmentation fault after this specific select:

(`downsampled_truewind_01` is a hypertable, the other two are materialized views.)

```
select                                                               
  c.bucket as time,
  c.boat_id,
  round(t.twa::numeric, 1), round(t.tws::numeric, 1), t.unique_number,
  round(c.cog::numeric, 1), round(c.sog::numeric, 1), c.unique_number,
  round(s.speed::numeric, 1)
from
  downsampled_truewind_01 t, downsampled_cogsog_01 c, downsampled_speedinwater_01 as s
where
  c.boat_id = t.boat_id and c.bucket = t.bucket and
  s.boat_id = t.boat_id and s.bucket = t.bucket and
  t.bucket >= '2020-08-07' and t.bucket <= '2020-08-09' and
  c.boat_id = 22 and
  (c.sog > 0.77 and c.sog < 50);
```

**IF** I add `LIMIT 1` to the end of that select, everything works as expected. With `LIMIT 2`, however, it segfaults again.

Attached the explain outputs for the select with and without the `limit`. 

[output.txt](https://github.com/timescale/timescaledb/files/6175330/output.txt)
[output_w_limit.txt](https://github.com/timescale/timescaledb/files/6175331/output_w_limit.txt)

**Comment by mkindahl** [comment]
Thank you for the bug report. Is it possible to get a stack trace from the core?

**Comment by mglonnro** [comment]
> Thank you for the bug report. Is it possible to get a stack trace from the core?

I don't know? This is on our production db with the apt version installed. If it's possible, then sure!

**Comment by mglonnro** [comment]
Sorry for not having a debug-enabled version to test with, but I upgraded to 2.1.1, and now `LIMIT 1`, `LIMIT 2`, and `LIMIT 3` work, but `LIMIT 4` crashes. How strange :)

**Comment by mglonnro** [comment]
As reported above, after the upgrade to 2.1.1, I still got the segfault. 

Now, however, a few days later, without having done any changes to anything myself, it suddenly works 👍 

I think there is nothing more I can dig up about this issue, so I'll just close it.
