### ISSUE TITLE
License issue when using CentOS RPMs

### ISSUE THREAD

**Issue by collini-flashstart** [timescale/timescaledb#3046]
Dear guys,

after installing CentOS RPM from timescaledb yum repository, I tried to compress a table and I got the following license issue:
"ERROR:  functionality not supported under the current "apache" license
HINT:  Upgrade your license to 'timescale' to use this free community feature."

Are there some issues using the RPM version?

Thank you so much, best regards!
Franz

**Comment by mfreed** [comment]
Hi @collini-flashstart Can you please provide the exactly link and/or instructions you used when installing (including the timescaledb version, etc.)

**Comment by collini-flashstart** [comment]
Dear Mike,

YES, sure happy to help.

I installed TimescaleDB from the RPM version:
https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum

I chose the right instructions for Postgresql 12 and proceeded to the installation.
Everything worked fine, except when using advaned features such as compression.

It says I need another type of license.

Thank you so much, with my best regards.

Francesco



Hi @collini-flashstart<https://github.com/collini-flashstart> Can you please provide the exactly link and/or instructions you used when installing (including the timescaledb version, etc.)

**Comment by collini-flashstart** [comment]
Dear Mike,

are there some updates about my issue?

Thank you so much, best regards.
Francesco

Da: Mike Freedman ***@***.***
Inviato: sabato 10 aprile 2021 18:40
A: timescale/timescaledb ***@***.***>
Cc: Francesco Collini, FlashStart ***@***.***>; Mention ***@***.***>
Oggetto: Re: [timescale/timescaledb] License issue when using CentOS RPMs (#3046)


Hi @collini-flashstart<https://github.com/collini-flashstart> Can you please provide the exactly link and/or instructions you used when installing (including the timescaledb version, etc.)

**Comment by ikzelf** [comment]
I have a similar/same problem. Installed Packages
Name         : timescaledb_12
Version      : 2.0.0
Release      : 1.rhel8
Architecture : x86_64
Size         : 4.1 M
Source       : timescaledb_12-2.0.0-1.rhel8.src.rpm

show timescaledb.license;
 timescaledb.license
---------------------
 apache

ALTER SYSTEM SET timescaledb.license = 'timescale';
ERROR:  could not access file "$libdir/timescaledb-tsl-2.0.0": No such file or directory

$ ls -l /usr/pgsql-12/lib/timescale*
-rwxr-xr-x. 1 root root 599952 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb-2.0.0.so
-rwxr-xr-x. 1 root root  52680 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb.so

How can I get this to work?

**Comment by leeweit** [comment]
> I have a similar/same problem. Installed Packages
> Name : timescaledb_12
> Version : 2.0.0
> Release : 1.rhel8
> Architecture : x86_64
> Size : 4.1 M
> Source : timescaledb_12-2.0.0-1.rhel8.src.rpm
> 
> The upstream repo is https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8-x86_64/
> 
> ## show timescaledb.license;
> timescaledb.license
> apache
> 
> ALTER SYSTEM SET timescaledb.license = 'timescale';
> ERROR: could not access file "$libdir/timescaledb-tsl-2.0.0": No such file or directory
> 
> $ ls -l /usr/pgsql-12/lib/timescale*
> -rwxr-xr-x. 1 root root 599952 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb-2.0.0.so
> -rwxr-xr-x. 1 root root 52680 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb.so
> 
> How can I get this to work?

same problem,Have you solved the problem,thanks.

**Comment by leeweit** [comment]
> I have a similar/same problem. Installed Packages
> Name : timescaledb_12
> Version : 2.0.0
> Release : 1.rhel8
> Architecture : x86_64
> Size : 4.1 M
> Source : timescaledb_12-2.0.0-1.rhel8.src.rpm
> 
> The upstream repo is https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8-x86_64/
> 
> ## show timescaledb.license;
> timescaledb.license
> apache
> 
> ALTER SYSTEM SET timescaledb.license = 'timescale';
> ERROR: could not access file "$libdir/timescaledb-tsl-2.0.0": No such file or directory
> 
> $ ls -l /usr/pgsql-12/lib/timescale*
> -rwxr-xr-x. 1 root root 599952 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb-2.0.0.so
> -rwxr-xr-x. 1 root root 52680 Dec 22 22:34 /usr/pgsql-12/lib/timescaledb.so
> 
> How can I get this to work?

same problem,Have you solved the problem,thanks.

**Comment by svenklemm** [comment]
You are not using the repository maintained by us but the postgres repository. 
You can find instructions to install the repo maintained by Timescale here: https://packagecloud.io/timescale/timescaledb/install#manual-rpm

This specific error should be reported to the postgres upstream repo.
