### ISSUE TITLE
OOM killer triggered when creatng a distributed hyper table of 90M rows

### ISSUE THREAD

**Issue by stephane-moreau** [timescale/timescaledb#3049]
**Relevant system information:**
 - OS: Azure Kubernetes - running docker images
 - PostgreSQL 12.6
 - TimescaleDB 2.1
 - Installation method: using timescaledev multinode

**Describe the bug**
Importing the Nyc Taxi data for 2019 and 2020 lead to OOM killer being triggered

**To Reproduce**
TimescaleDb is installed in a multi node env 3 AKS Nodes, running 1 access node and 3 data nodes
I tried to import the nyc data limiting to 2020 and 2019 with yellow and green cab only comming from 
https://github.com/toddwschneider/nyc-taxi-data

Every thing works fine when data is imported to a regular postgres table

Then I create an HyperTable based on pickup datetime, copying data from the regular trips data to the hypertable works fine too

If I create a distributed hypertable using pickup datetime for tmie serie and id as a distribution key, the copy of data (using insert into select) consumes the whole node memory and lead to a 137 error code in psql and a restart of the access node

Trips table contains 90M rows
If I copy a first 10M rows, the postgres process server side consumes up to 4Gb of RAM but does not give it back once insert is processed and as such a second insert statement lead to OOM killer freeing memory

**Expected behavior**
I would expect the distributed table to works as a regular hypertable allowing to spread the load of reading and writing accross multiple nodes

**Actual behavior**
OOM Killler retarting acces node and preventing data from being inserted

**Comment by erimatnor** [comment]
@stephane-moreau Thanks for reporting this issue. It would help if you provided a script or steps you took to run this. In particular, it would be good to know if you used `INSERT` or `COPY`, a single transaction or multiple ones, etc.

**Comment by stephane-moreau** [comment]
Data was loaded in a staging table using \COPY (from CSV) (on CSV per month - roughly 3 to 5 M rows per copy)
this staging table was a regular table

then the data was loaded into the distributed hypertable in one single transaction using an insert into select

The exact same load using insert into select was performed into the hypertable (not a distributed one) and every thing went fine
