### ISSUE TITLE
Update from v2.0.0 to v2.1.0 fails because of ALTER on continuous aggregate

### ISSUE THREAD

**Issue by dberardo-com** [timescale/timescaledb#3051]
**Relevant system information:**
 - PostgreSQL version: 12
 - TimescaleDB version: 2.0.0
 - Installation method: docker

**Describe the bug**
when performing the ALTER EXTENSION query, the following error is thrown:
```sql
ALTER EXTENSION timescaledb UPDATE
INFO:  cmd executed: ALTER MATERIALIZED VIEW "<view_name>" SET (timescaledb.materialized_only=false)
ERROR:  SELECT rule's target entry 1 has different column name from column "t"
DETAIL:  SELECT target entry is named "someName".
CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW "<view_name>"" SET (timescaledb.materialized_only=false) "
```
**To Reproduce**
1. Create a materialized view with a similar definition to this one:

```
 SELECT time_bucket('00:15:00'::interval, "<original_table>i".t) AS "someName",
    count("<original_table>".something) AS count,
   FROM "<original_table>"
  GROUP BY (time_bucket('00:15:00'::interval, "<original_table>".t)), "<original_table>".somethingElse;
```

**Expected behavior**
Update goes well

**Actual behavior**
Update fails

**Comment by svenklemm** [comment]
Can you provide a minimal test script to reproduce the issue in a new database. I couldnt reproduce with the information you provided.

**Comment by kimjj81** [comment]
I got the same error.

**Comment by kimjj81** [comment]
SELECT time_bucket('00:15:00'::interval, "<original_table>i".t) AS "someName" 
<=  In my case, 
SELECT time_bucket(......, measured_at) as measured_at 
...... group by time_bucket(......, measured_at)

'measured_at' are both in select and group by.  I think it is the cause of the error, right?
