### ISSUE TITLE
ERROR:  index attribute xxxxxxx1 not found in chunk

### ISSUE THREAD

**Issue by BowenGG** [timescale/timescaledb#3056]
**Relevant system information:**
 - Use the TimescaleDB cloud. PostgreDB version: 12.4 and 12.6

**Describe the bug**
I can create an index on column A and "INCLUDE" the same column A. I know this is improper but the query can be executed. However, after that, if we migrate the table to a hypertable with chunks, and then drop a column, then we will not be able to insert data to new chunks (new chunks can't be created). 
The below error is returned:
ERROR:  index attribute order_number1 not found in chunk
SQL state: XX000
Please note the "order_number1", which is not in the table. Is it internally converted due to the INCLUDE? 

In other words, there is a conflict if the below four facts are true:
1. you have index including the index key in itself. 
2. convert the table to hypertable with chunks.
3. drop a column from the table.
4. insert data into new chunk. 

**To Reproduce**
Can reproduce the issue by the below queries. You can execute the step 1-4 in any order. Once the last one is executed you will see the error. If you run the "drop column" at the last one, please insert a new data into new chunks to trigger this error. 

```--drop table public.orders_test_chunk;
CREATE TABLE public.orders_test_chunk
(
    order_number integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    column_test integer
)
TABLESPACE pg_default;

-- no matter in which order the below four queries are executed, it can make the error.
-- 1
CREATE INDEX order_number_orders_test_chunk
    ON public.orders_test_chunk USING btree
    (order_number ASC NULLS LAST)
    INCLUDE(order_number)
    TABLESPACE pg_default;
	
-- 2
SELECT create_hypertable('orders_test_chunk', 'date_created', chunk_time_interval => INTERVAL '1 day', migrate_data => true);

-- 3
alter table orders_test_chunk drop column column_test;
-- if the drop column is the last query, insert data into a new chunk to trigger the issue
-- insert into public.orders_test_chunk (order_number,date_created) values (10002, '2021-01-02 11:19:24.300');

-- 4
insert into public.orders_test_chunk (order_number,date_created) values (10001, '2021-01-01 11:19:24.300');
```

**Expected behavior**
Either it doesn't allow to create such an index, which includes itself index key, or this kind of index will not trigger the above error. 

**Actual behavior**
Will see the error:
ERROR:  index attribute order_number1 not found in chunk
SQL state: XX000

**Comment by hardikm10** [comment]
As I can check, this only happens when the column which is being indexed is also present in INCLUDE.
