### ISSUE TITLE
Timescaledb RPM packages are not compliant 

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#3057]
**Relevant system information:**
 - OS: Centos
 - PostgreSQL version (output of `postgres --version`): 12
 - TimescaleDB version (output of `\dx` in `psql`): 2
 - Installation method: YUM

**Describe the bug**
Upgrading from timescale 1.x to timescale 2.x package names become non-complaint and now contain major version in the middle of package name. Which causes issues in automation (i.e. Ansible). Resulting in needed to rewrite large parts of roles etc.

Why TF is the major version in the middle of the package name? The package name is currently `timescaledb-2-postgresql-12-2.0.1-0.el7.x86_64`. Having `2.0.1` is sufficient to show that it is timescale 2.x, that is what semantic versioning is for.

**To Reproduce**
N/A

**Expected behavior**
Consistent package naming

**Actual behavior**
Major version for some reason stuck in the middle of package name

**Additional context**
Anyone using automation (i.e. Ansible roles) to maintain Timescale will now need to rewrite this and in some cases even duplicate code to support changed package names on new systems AND same time unchanged package names on old systems.

**Comment by akamensky** [comment]
Seems there is not enough knowledge on YUM packaging here given this issue and #1973 which was closed, but is still present in 2.x releases.

**Comment by mfreed** [comment]
Hi @akamensky:   

First of all, I can assure you there was discussion about this very issue internally, particularly given concern about users automatically upgrading TimescaleDB and breaking existing deployments, given the API changes between the 1.x and 2.x lines (much like python 2 and 3 for API compatibility).  In other words, in this case, gave more weight to avoid breaking existing/production deployments than some additional effort needed around automation.

We do always welcome constructive feedback and input, however, as I'm sure we don't always get everything right.

That said, we do expect discussion and feedback to follow Timescale's Code of Conduct at all times:

 https://www.timescale.com/code-of-conduct

Behavior that contributes to a positive environment for our community include:
* Demonstrating empathy and kindness toward other people
* Giving and gracefully accepting constructive feedback

Behavior against the code of conduct includes the use of inappropriate language or other behavior deemed unprofessional or unwelcome in the community.

Thank you.

**Comment by akamensky** [comment]
My apologies for the language I used previously. Note taken.

I think the packaging issues are one of the major pain points in dealing with TimescaleDB. For a clean slate installation this may be not as visible, but upgrading from 1.3 through all 1.X versions and now moving to 2.X I've experienced multiple failures due to packaging.

**Comment by svenklemm** [comment]
Closing this since the package name was done intentionally due to the API changes so users have to make an explicit decision about the switch from 1.x to 2.x
