### ISSUE TITLE
Block all distributed hypertable DDLs and mutable operations on data nodes

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3065]
**Describe the bug**

Some DDL commands are blocked on data nodes when they target hypertables that are part of a larger distributed hypertable. For instance, `DROP <hypertable>` is blocked.

However, this does not extend to indexes or chunks on the hypertable. Nor does it apply to functions like `drop_chunks`. 

**To Reproduce**
1. Create a distributed hypertable on the AN
1. Insert some data to create at least one chunk
1. Log into one of the DNs and try to drop a chunk with `DROP <chunk>`
 
**Expected behavior**
All DDL and mutable operations should be blocked on data nodes when they involve a hypertable (or its subobjects) that is a member of a distributed hypertable.

**Actual behavior**
Some DDLs and mutable operations are allowed.

**Comment by svenklemm** [comment]
multinode has been removed
