### ISSUE TITLE
User missing after update from 1.7.5 to 2.0.x or later

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#3078]
**Relevant system information:**
 - OS: all
 - PostgreSQL version (output of `postgres --version`): all
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.x
 - Installation method: any

**Describe the bug**
When updating to 2.0.x (or later) permissions are lost on the following objects:

- `_timescaledb_catalog.hypertable`
- `_timescaledb_catalog.continuous_aggs_hypertable_invalidation_log`
- `_timescaledb_catalog.continuous_aggs_materialization_invalidation_log`
- `_timescaledb_catalog.chunk_data_node`
- `_timescaledb_catalog.continuous_agg`
- `_timescaledb_catalog.hypertable_data_node`
- `_timescaledb_catalog.hypertable_id_seq`
- `_timescaledb_catalog.remote_txn`
- `_timescaledb_config.bgw_job`
- `_timescaledb_config.bgw_job_id_seq`
- `_timescaledb_internal.compressed_chunk_stats`
- `_timescaledb_internal.hypertable_chunk_local_size`

**To Reproduce**
1. Install 1.7.5
2. Grant permissions to a new user `tsdbadmin` on any table above.
3. Run `ALTER EXTENSION UPDATE...` to update to a version 2.0.x or later.
4. Check permissions on the table and note that `tsdbadmin` is missing.

**Expected behavior**
Permissions granted on any of the above tables should remain after an update of the extension.

**Actual behavior**
Permissions are reset to the default.

**Comment by mkindahl** [comment]
Note that the permissions on the TimescaleDB-specific schemas are not needed for the extension to work correctly. The extension changes permissions internally when accessing the tables so it does not need any specific permissions to read those tables. However, if some other user wants to have access to those tables, they are not maintained when updating the extension.

There are two problems here:

- Some tables are created as part of the update. These are new tables does not exist on the pre-2.0 version. For these tables to get user permissions, it is necessary to set the default permissions for the schema.
- Some tables are re-created and here the permissions are not copied. Since they are created, they will get the default permissions for the schema&mdash;if default permissions for the schema is set up&mdash;but any other permissions will be lost.

**Comment by erimatnor** [comment]
I am not convinced this is an issue as described. In particular, I am not sure I agree with the expected behavior as described:  **Permissions granted on any of the above tables should remain after an update of the extension.**

These are internal catalog tables, but users shouldn't mess with permissions on those tables  in a similar way to how they shouldn't mess with permissions on PostgreSQL catalog tables.

In particular, issuing GRANTs on these objects seems especially error prone. For instance, if an update to the extension creates new catalog tables and objects, it will not have the GRANT that other objects have even if the GRANT survives the update on existing objects. So, even if we make sure the GRANTs survive altering the extension, the resulting behavior might not be what the user expects.

Also, as noted, the permissions aren't actually used during normal extension operation since we internally switch into a privileged user when modifying catalog entries in code.

I am curious to learn what actual issues we are solving by supporting user-based changes to privileges on catalog tables?

I would also like to understand what the behavior is of [altering the default privileges](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html). That seems more appropriate than GRANTing privileges on individual catalog tables since it would also cover new objects created by the extension (unless it is a new schema being created).

**Comment by mkindahl** [comment]
> I am not convinced this is an issue as described. In particular, I am not sure I agree with the expected behavior as described: **Permissions granted on any of the above tables should remain after an update of the extension.**
> 
> These are internal catalog tables, but users shouldn't normally have to mess with privileges on those tables in a similar way to how they shouldn't mess with permissions on PostgreSQL catalog tables. I am curious to learn what actual issues we are solving by supporting user-based changes to privileges on catalog tables?

The problem is quite straightforward: being able to take a backup (and restore) without requiring superuser privileges.

For the purpose of the discussion, we can assume that a dedicated user `tsdbadmin` is created that should be able to take a backup of the system using `pg_dump` (and a different user with write permissions should be able to restore the tables using `pg_restore`, if we want to handle that as well). We still want the tables to be owned by the extension installer, which is again a different user, but which has superuser privileges (typically `postgres`).

> In particular, issuing GRANTs on these objects seems especially error prone. For instance, if an update to the extension creates new catalog tables and objects, it will not have the GRANT that other objects have even if the GRANT survives the update on existing objects. So, even if we make sure the GRANTs survive altering the extension, the resulting behavior might not be what the user expects.

This is just a repetition of what the bug describes. This *is* the problem. Granting privileges on the tables does not survive an update.

> Also, as noted, the permissions aren't actually used during normal extension operation since we internally switch into a privileged user when modifying catalog entries in code. Instead, the catalog tables have restrictive permission to not leak information and to prevent accidental modifications or modifications with bad intent.

Yes, but that is not the purpose of adding specific user privileges to the tables (in this case).

> I would also like to understand what the behavior is of [altering the default privileges](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html). That seems more appropriate than GRANTing privileges on individual catalog tables since it would also cover new objects created by the extension (unless it is a new schema being created).

Granting privileges on specific tables for the purpose of handling backup and restore raises the question of *which* tables and also the question on what happens to privileges on tables that are created during an update (or tables that are created as part of normal operation, e.g., inserting data into hypertables).

Since you want to have a dedicated user that can take backups of the system, it is natural to issue grants for all tables and sequences in the schema:

```
GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_catalog TO tsdbadmin;
GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_config TO tsdbadmin;
GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_internal TO tsdbadmin;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA _timescaledb_catalog TO tsdbadmin;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA _timescaledb_config TO tsdbadmin;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA _timescaledb_internal TO tsdbadmin;
```

Since you want the permissions to be there also after an update, or if new tables are created, it is natural alter the default privileges on the schema:

```
ALTER DEFAULT PRIVILEGES IN SCHEMA _timescaledb_catalog
      GRANT SELECT ON tables TO tsdbadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA _timescaledb_config
      GRANT SELECT ON tables TO tsdbadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA _timescaledb_internal
      GRANT SELECT ON tables TO tsdbadmin;
```

However, this do not work as expected after an update of the extension. Permissions are lost.
