### ISSUE TITLE
Upgrade to timescale 2.1.1, running for a very long time before failing (very similar, but not the same as, issue #2795)

### ISSUE THREAD

**Issue by dwalthour** [timescale/timescaledb#3084]
**Relevant system information:**
 - OS: Centos 8
 - PostgreSQL version (output of `postgres --version`): 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.72 upgrading to 2.1.1
 - Installation method: dnf install, using 'ALTER EXTENSION timescaledb UPDATE' to upgrade to 2.1.1

**Describe the bug**
The update command would run for 24-36 hours and then fail without a clear reason.

**To Reproduce**
I have no idea exactly how to reproduce this behavior as it appears to be some aspect of my setup or database.

**Expected behavior**
That it would update in a matter of seconds.

**Actual behavior**
It ran for 24-36 hours and failed without updating the database.

**Additional context**
I actually got help from issue #2795 and solved the problem by setting the max_parallel_workers = 0.

However, the purpose of this issue report is to let the timescale team as well as other users know of this potential behavior.  

I would suggest that you add a statement or warning box to the upgrade documentation that strongly encourages potential upgraders to set max_parallel_workers = 0 before the upgrade and to restore it to its previous value afterward.

**Comment by gayyappan** [comment]
We fixed slowdowns in upgrade and are now on timescale version 2.5.  Please open a new issue if anyone has upgrade problems with newer versions of timescale.
