### ISSUE TITLE
[Feature Request] Add PPA release for Ubuntu 20.10

### ISSUE THREAD

**Issue by mysterious-ben** [timescale/timescaledb#3089]
**Issue:**
Currently, ppa:timescale/timescaledb-ppa doesn't have a release for Ubuntu 20.10. The latest available release is for Ubuntu 20.04. Thus, it's not possible to properly `apt install` TimescaleDB on the latest Ubuntu.

**Proposed solution:**
It'd be great to have a release for Ubuntu 20.10. As PostgreSQL does have a release for Ubuntu 20.10, I don't see any reason why TimescaleDB wouldn't.

**Alternative solutions:**
To my best knowledge, there are only two alternatives:
- build both PostgreSQL and TimescaleDB from source, which I have never tried to do; or
- downgrade to Ubuntu 20.04 - which would be a rather big effort.

**Comment by k-rus** [comment]
Thank you for reporting. Will it work for you do something like the following?
```bash
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt update
```
Then you run the sudo apt install with TimescaleDB.

**Comment by RobAtticus** [comment]
@mysterious-ben It seems to have slipped my mind to add 20.10 to the list of releases. Given that it will be obsolete soon, I might be inclined to skip it.

One alternative is to use timescaledb from the focal repo instead via:
```
sudo add-apt-repository --force-distro=focal ppa:timescale/timescaledb-ppa
```

I think that should be fine, but let me know if not.

**Comment by RobAtticus** [comment]
Sorry, I misread a stackoverflow post and that flag appears to be a suggestion rather than an actual flag.

The correct command would be:
```
sudo add-apt-repository "deb http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu focal main"
```

**Comment by NunoFilipeSantos** [comment]
That's the correct solution. @k-rus solution was my mistake.

**Comment by mysterious-ben** [comment]
Thanks for a quick reply!

@RobAtticus Your solution seems to be working: I was able to add the repo using your command! I haven't tried installing TimescaleDB yet as I ended up using a TimescaleDB docker container.

Regarding the initial issue: I'm personally won't be switching to Ubuntu 21.04 just yet because it switches to python 3.9. I think it'd be cleaner to have a TimescaleDB release for Ubuntu 20.10. It'd be consistent with Postgres and would make life a bit easier for new users. On the other hand, it's not critical: there is a workaround and Ubuntu 20.10 is rarely used in production. So... It's up to you to decide whether it's worth the effort.

**Comment by svenklemm** [comment]
Closing this since Ubuntu 20.10 is no longer supported by Ubuntu. You can have a look at our CI package test to see full list of versions we currently build for: 
https://github.com/timescale/timescaledb/blob/main/.github/workflows/apt-packages.yaml
