### ISSUE TITLE
 Adding tablespaces on data node is ignored for the chunks of a distributed hypertable

### ISSUE THREAD

**Issue by xuelin-wang** [timescale/timescaledb#3092]
**Relevant system information:**
 - OS:Ubuntu 18.04
 - PostgreSQL version 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.1
 - Installation method: apt install

**Describe the bug**
The configuration is multinode setup with 1 access node and 2 data nodes. A distributed hypertable was created. Each data node created two disks  and two namespaces for the table (one namespace per disk). After creation, insert into the table from access node only uses one of the disk on one of the data node. 

**To Reproduce**
1. Create a hyper distributed hyper table with one space dimension and one time dimension.
2. Create two tablespaces for the table in one data node.
3. Insert data into the hypertable
4. Sometimes, all the data goes to one table space and the other table space is not used.

**Expected behavior**
data should go to both table spaces.

**Actual behavior**
Sometimes only one of the tablespace receives data

**Screenshots**
N/A

**Additional context**
Slack thread:
https://timescaledb.slack.com/archives/CPSD82EMU/p1617645442099500

**Comment by xuelin-wang** [comment]
hypertable_schema |      hypertable_name       |     chunk_schema      |      chunk_name       | primary_dimension |  primary_dimension_type  |      range_start       |       range_end        | range_start_integer | range_end_integer | is_compressed | chunk_tablespace | data_nodes 
-------------------+----------------------------+-----------------------+-----------------------+-------------------+--------------------------+------------------------+------------------------+---------------------+-------------------+---------------+------------------+------------
 vdata             | history_data_record | _timescaledb_internal | _dist_hyper_2_1_chunk | event_time        | timestamp with time zone | 2021-03-04 00:00:00+00 | 2021-03-11 00:00:00+00 |                     |                   | f             |                  |      
 vdata             | history_data_record | _timescaledb_internal | _dist_hyper_2_3_chunk | event_time        | timestamp with time zone | 2021-03-11 00:00:00+00 | 2021-03-18 00:00:00+00 |                     |                   | f             |                  |      
 vdata             | history_data_record | _timescaledb_internal | _dist_hyper_2_5_chunk | event_time        | timestamp with time zone | 2021-04-01 00:00:00+00 | 2021-04-08 00:00:00+00 |                     |                   | f             |                  |      
(3 rows)
white_check_mark
eyes
raised_hands




k-rus:ttiger:
I don’t see that any tablespaces are used. It seems that they are ignored on the data node. Can you post the result of select * from _timescaledb_catalog.tablespace;?

select * from _timescaledb_catalog.tablespace;
 id | hypertable_id | tablespace_name 
----+---------------+-----------------
  1 |             2 | disk1
  2 |             2 | disk0
  3 |             2 | disk2

and the hypertable entry:
id | schema_name |         table_name          | associated_schema_name | associated_table_prefix | num_dimensions | chunk_sizing_func_schema |  chunk_sizing_func_name  | chunk_target_size | compression_state | compressed_hypertable_id | replication_factor 
----+-------------+-----------------------------+------------------------+-------------------------+----------------+--------------------------+--------------------------+-------------------+-------------------+--------------------------+--------------------
  2 | vdata       | history_data_record  | _timescaledb_internal  | _dist_hyper_2           |              2 | _timescaledb_internal    | calculate_chunk_interval |                 0 |                 0 |

**Comment by k-rus** [comment]
Thank you for reporting!
Silently ignoring tablespaces, which are created locally on data nodes, is not expected. However, even if it will work to utilize them, it will unlikely to give desired result, since the same hash function is used for selecting data nodes and for selecting tablespaces, so all chunks, which reach on data node, will be placed in the same tablespaces.

It is likely that the first thing is to return an error instead of silent ignore of tablespaces on data node, and then do proper fix.

**Comment by k-rus** [comment]
@xuelin-wang I have tested I see that tablespaces are used after they are attached to local hypertable on the data node.

So I am wonder, were the chunks created before tablespaces were attached to the local hypertable? In such case the chunk will be not be in newly attached tablespace and it is necessary to move it by calling `move_chunk`.

**Comment by k-rus** [comment]
> So I am wonder, were the chunks created before tablespaces were attached to the local hypertable? In such case the chunk will be not be in newly attached tablespace and it is necessary to move it by calling `move_chunk`.

It is likely the case. Thus closing the issue. It can be re-open if necessary.

**Comment by kmonroe0723** [comment]
Is there a way to query _timescale_catalog or _timescaledb_internal  or another table/view which will display all the tables in the database and what tablespace they reside?

**Comment by jnidzwetzki** [comment]
Hello @kmonroe0723,

You can use the catalog of PostgreSQL to determine this information. By using the following query, you get an overview of all tables and the tablespace used:

```sql
 SELECT schemaname, tablename, tablespace FROM pg_tables;
```

If the `tablespace` attribute is empty, the default table space is used.

**Comment by kmonroe0723** [comment]
Thank you.  I was under the impression that would only show me chunks.
