### ISSUE TITLE
time_bucket_gapfill within generate_series and lateral join

### ISSUE THREAD

**Issue by saasrack** [timescale/timescaledb#3099]
**Relevant system information:**
 - PostgreSQL version 12
 - TimescaleDB 2.0.1

**Issue**
I have a query where I'm trying to get for example data from today and yesterday for comparison. This actually works fine by doing a `generate_series` with `lateral join` and `time_bucket`. However, I would like to have interpolation in place for both days for example. But due to the limitation on the `time_bucket_gapfill` `start` and `finish` argument that only allows simple expression I have difficulties to find workarounds.

**To Reproduce**

```
SELECT timestamp,
    sensor_temperature,
    CASE
       WHEN step = 0
           THEN 'today'
       ELSE (-intervals)::text
    END AS timeline
FROM (
    SELECT step, (now() - (step || 'day')::interval)::timestamp as testTimestamp, (step || 'day') ::interval AS intervals FROM generate_series(0, 1) g(step)
) g_offsets
JOIN LATERAL (
    SELECT time_bucket_gapfill('1 hour', datetime + intervals, '2021-04-08T22:00:00.000Z', testTimestamp)::timestamptz AS timestamp,
           interpolate(avg(sensor_temperature)::float) as sensor_temperature
    FROM (
        SELECT g.datetime at time zone 'Europe/Berlin' at time zone 'utc' as datetime, g.data_1 as sensor_temperature
        FROM sensors g
        WHERE g.datetime BETWEEN '2021-04-08T22:00:00.000Z'::timestamptz - intervals AND '2021-04-09T22:00:00.000Z'::timestamptz - intervals AND g.sensor_id = '123'
        GROUP BY g.datetime, g.data_1
        ORDER BY 1
    ) sub
    GROUP BY timestamp
) l
ON true

```
I have tried to have some sort of pre-calculated, pre-formatted `testTimestamp` timestamp in the SELECT of the generated series but without luck. Maybe there is someone who might have a solution for this. Thank you.

**Comment by erimatnor** [comment]
@saasrack this sounds like an interesting use case, but I am not 100% sure I understand what the issue is and what it is you'd like to do. Could you please describe the behavior of your current query, the undesirable outcome, and then what the desirable outcome would be?

**Comment by k-rus** [comment]
@saasrack  Have you considered to utilize [CTEs](https://www.postgresql.org/docs/12/queries-with.html) to prepare the example data in steps?

**Comment by saasrack** [comment]
What I'm trying to achieve is to have a graph overlay of todays data and yesterdays data. Something like this which compares data from today and the same day a week before:

![image](https://user-images.githubusercontent.com/13893051/114462453-56bc6200-9be3-11eb-9bfa-2c60d5ad1046.png)


Hi have found a quirky workaround by changing the timestamp of the subquery subtracting it from the interval to keep the start and finish of the time_bucket_gapfill the same. But it seems like that the gapfill only work in the first iteration.


````
SELECT timestamp,
    sensor_temperature,
    CASE
       WHEN step = 0
           THEN 'today'
       ELSE (-intervals)::text
    END AS timeline
FROM (
    SELECT step, 
        (step || 'day') ::interval AS intervals, 
        '2021-04-08T22:00:00.000Z' as startDate,
        '2021-04-09T22:00:00.000Z' as endDate,
    FROM generate_series(0, 1) g(step)
) g_offsets
JOIN LATERAL (
    SELECT 
        time_bucket_gapfill('1 hour', datetime, startDate, endDate)::timestamptz AS timestamp,
        interpolate(avg(sensor_temperature)::float) as sensor_temperature
    FROM (
        SELECT 
            g.datetime + intervals as datetime,  <----- adding by interval
            g.data_1 as sensor_temperature
        FROM sensors g
        WHERE 
            g.datetime BETWEEN startDate::timestamptz - intervals   <----- subtracting by interval
            AND endDate::timestamptz - intervals   <----- subtracting by interval
            AND g.sensor_id = '123'
        GROUP BY g.datetime, g.data_1
        ORDER BY 1
    ) sub
    GROUP BY timestamp
) l
ON true
````

**Comment by k-rus** [comment]
Thank you for explaining your use case. To me it sounds that `time_bucket_gapfill` should be applied first to fill gaps in the data according the original timestamps, then the result can be converted to be periodical with only hours or week days  instead of timestamps and corresponding labels.

I don't really see a need to change `time_bucket_gapfill`. Instead it should be used differently according ot its expected usage.
