### ISSUE TITLE
guidance on partitioning, chunk time interval, parallelism

### ISSUE THREAD

**Issue by tr8dr** [timescale/timescaledb#31]
Can you provide some guidance on the use of partitions and chunk_time_interval in terms of implications for layout and performance?   There was no documentation that I could find on the chunk_time_interval.  Found it in one of the sample sets provided. 

Also are Postgres / your extensions able to run parallel scans across chunks (if the query is across chunks or requires a join with a different time series table)?   Have recent versions of Postgres carried over some of the capabilities of green plum (which is now open sourced)?

I am testing the database on data where have 1 sample (with 110 measures) per second 24x7.  Given the large # of samples and that most queries I would do would be within a given day historically it seemed to make sense to chunk on the day.   I also have a categorical variable that divides the data set into 10 distinct sets.  Hence I initially created the hyper table with:

```SQL
SELECT create_hypertable('measures', 'stamp', 'instrument', 10, chunk_time_interval => 86400000000); 
```
Based on a comment in one of the example sets have been led to believe that the chunk_time_interval is expressed in microseconds.

I also created another table, which would be joined with this for specific queries with the same attributes.   The resulting performance of these tables (querying within 1 historical day of data) was very poor.     I had noticed that the performance  using:

```SQL
SELECT create_hypertable('measures', 'stamp', 'instrument', 2); 
```
with default chunk size and 2 partitions was an order or two of magnitude faster.  I don't know enough about the data structures as to posit why there is such a significant performance difference.  One table contained 300 million rows (on 2 x 7 years of data) and the other 20 million rows (on 1 x 1 year of data).   Ultimately both tables would have 10 (instruments) x 7 (years) or possibly more instruments in the future.

Finally I should mention that I was testing this on an OS X 10.12.4 Mac with reasonably fast CPU (a higher end core i7), 32GB of memory with 4G dedicated to postgres, single disk for data, no stripping.    Eventually would move to a linux box with a stripped disk array and with higher memory allocation.

**Comment by cevian** [comment]
Thanks for the issue. We will work on correcting our documentation. The basic idea for chunk_time_interval (which is indeed in microseconds) is to set it so that a single chunk fits in memory. So the default of 30 days should work well for you. The number of partitions depends on the number of disks(tablespaces) you have. So should actually be 1 for your use case. 

You should have at least one index starting with your time column to make your queries faster.

I would be very interested (and would greatly appreciate) the explain (analyze on, verbose on) output of your misbehaving join query on the 1-day-chunk setup. You can email me at mat@timescaledb.com if you don't feel comfortable making that public. I also understand if you are not comfortable sharing that at all.

**Comment by tr8dr** [comment]
ok, the partitioning 1:1 to physical device makes sense to me, less so if is logical device.  Does postgres / timescaledb make use of parallel reads and scanning per table space?    Would parallelism across tablespaces be superior to the simpler alternative in setting up the database across striped disks (and simply get higher disk read bandwidth).   Can postgres / timescaledb do k-way parallel scanning / processing across table spaces if the query allows, such that table spaces would be a superior approach?

As for the 10 partition setup, I don't have that now, took some hours to load.    I can run statistics on the 2 partition versus 1 partition (as will move the DB to the 1 partition configuration for testing).    I could also change the 1mo default chunking to 1 day and see how this behaves.   There were 2 variables: partitioning and chunking previously.

**Comment by cevian** [comment]
Yes, the partitioning should be 1:1 for a physical device if not striped. For striped disks, 1 partition per logical device probably makes sense (as well as an adjustment to effective_io_concurrency). AFAIK, Postgress parallelism is best aimed at cpu-intensive, not io-intensive applications, and is not tablespace-optimized yet. So, the striped approach is probably best.

**Comment by mfreed** [comment]
Our updated docs now includes a more in-depth discussion of this:

http://docs.timescale.com/api/api-timescaledb#create_hypertable-best-practices

**Comment by mfreed** [comment]
Will be closing this off unless there are any other questions?

**Comment by candlerb** [comment]
I think [the FAQ](https://docs.timescale.com/latest/faq#-how-are-hypertable-chunks-determined-across-the-space-dimension-partition-keys-a-id-partitions-a-) could be clearer when it says:

> All hypertable chunks are **partitioned automatically across time**, which is necessary for right-sizing the chunks such that the B-trees for a table's indexes can reside in memory during inserts to avoid thrashing that would otherwise occur while modifying arbitrary locations in those trees.

(emphasis mine).  The words "automatically" and "right-sizing" suggested to me that the chunk size was automatically chosen, but it seems not, according to [chunking best practices](http://docs.timescale.com/latest/api/api-timescaledb#create_hypertable-best-practices)

> The current release of TimescaleDB **does not perform adaptive time intervals** (although this is in the works). So, users must configure it when creating their hypertable by setting the ​chunk_time_interval​ (or use the default of 1 month)

**Comment by candlerb** [comment]
There is further conflicting wording [here](https://www.timescale.com/how-it-works.html):

> Chunks are dynamically created by the runtime and sized to optimize performance. In the time dimension, users may specify the interval for future chunks, **or TimescaleDB can dynamically adapt the interval** to optimize performance based on system capacity. Right-sized chunks ensure that the multiple B-trees for a table’s indexes can reside in memory during inserts to avoid thrashing.

I can understand that "sized to optimize performance" might require manual sizing, but then it says explicitly that TimescaleDB can dynamically adapt the interval.

**Comment by candlerb** [comment]
Also in the [white paper](http://www.timescale.com/papers/timescaledb.pdf):

> TimescaleDB performs such time/space partitioning automatically based on table *sizes*, rather than an approach based on static time intervals more commonly practiced (e.g., by creating a separate table per day).
> ...
> TimescaleDB avoids the need to make this choice by managing data partitioning automatically.

**Comment by mfreed** [comment]
Yes, sorry for the confusion, we'll clear up some language.  (The adaptive chunking exists currently in a public branch on github, just not merged yet.)

**Comment by RedShift1** [comment]
> Our updated docs now includes a more in-depth discussion of this:
> 
> http://docs.timescale.com/api/api-timescaledb#create_hypertable-best-practices

Link is dead

**Comment by candlerb** [comment]
Presumably is now: https://docs.timescale.com/latest/using-timescaledb/hypertables#best-practices

All mention of dynamic chunk sizing appears to have gone.
