### ISSUE TITLE
Windows Zip Install Error 

### ISSUE THREAD

**Issue by RJKrimetz** [timescale/timescaledb#3117]
**Relevant system information:**
 - Windows 10 x64
 - PostgreSQL version 13
 - TimescaleDB version 2.1.1
 - Zip installer

**Describe the bug**
When I run the setup application file I do not get the correct output instead a cmd prompt appears and asks to run "timescaledb-tune.exe". After doing this I get the error message...

"ERROR: could not copy file 'timescaledb-2.1.1.dll': open C:/PROGRA~1/POSTGR~1/13/lib/timescaledb-2.1.1.dll: Access is denied."

I have all of the prerequisites, and "timescaledb" is added to the pg config file in my version of postgres.

Haven't been able to find a solution, thanks so much in advance!

**Comment by k-rus** [comment]
@RJKrimetz Do you run TimescaleDB Setup with Administrative privileges? Since PostgreSQL is installed in `Program Files` it is necessary to run the setup with elevated privileges.

**Comment by RJKrimetz** [comment]
That fixed it, thank you so much!
