### ISSUE TITLE
Continuous aggregations query samples don't work

### ISSUE THREAD

**Issue by sergey-mm** [timescale/timescaledb#3119]
**Relevant system information:**
 - OS: macos 10.14.6
 - PostgreSQL version (output of `postgres --version`): 13.2
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.0
 - Installation method: brew

**Describe the bug**
[This page](https://docs.timescale.com/latest/tutorials/tutorial-use-timescale-prometheus-grafana) has examples for `Continuous aggregations` queries. I tried to run them, but have some errors

**To Reproduce**
1. Run a query from an example
```sql 
CREATE VIEW metrics_5mins
WITH (timescaledb.continuous,
   timescaledb.ignore_invalidation_older_than='2d',
   timescaledb.refresh_lag = '-30m',
   timescaledb.refresh_interval = '5m')
AS
   SELECT time_bucket('5 minutes', time) as bucket,
       labels_id,
       avg(value) as avg,
       max(value) as max,
       min(value) as min
       FROM
           metrics_values
       GROUP BY bucket, labels_id;
```

**Expected behavior**
Create a view

**Actual behavior**
```
ERROR:  cannot create continuous aggregate with CREATE VIEW
HINT:  Use CREATE MATERIALIZED VIEW to create a continuous aggregate.
```
```
ERROR:  unrecognized parameter "timescaledb.ignore_invalidation_older_than"
```
```
ERROR:  unrecognized parameter "timescaledb.refresh_lag"
```
```
ERROR:  unrecognized parameter "timescaledb.refresh_interval"
```

**Comment by xJosephTan** [comment]
Seems from [here](https://docs.timescale.com/latest/api#continuous_aggregate-create_view) and [here](https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates) that you should be using `CREATE MATERIALIZED VIEW` instead of `CREATE VIEW`

**Comment by erimatnor** [comment]
@sergey-mm Thank you for reporting this issue. If you look at the top of the page of those docs, you will find a sunset notice explaining that they involve an old way of storing Prometheus data that uses an older version of TimescaleDB.

I suggest filing an issue against the [documentation repo](https://github.com/timescale/docs.timescale.com-content) if you have suggestions on how this can be clarified further.

In the meantime, @xJosephTan is right that you should replace `CREATE VIEW` with `CREATE MATERIALIZED VIEW` to make it work with a newer version of TimescaleDB.
