### ISSUE TITLE
drop_chunk_indexes functionality

### ISSUE THREAD

**Issue by MikeSchroll** [timescale/timescaledb#312]
I'd like to see a feature which can drop indexes from older chunks.

I would specify table, interval, and index name to be dropped for chunks older than that time interval.

Use case: Imagine that I want to allow users to search data from the last 3 days only... but I am doing drop_chunks interval 30 days. This feature would save me 27 days of index storage that isn't useful.

**Comment by svenklemm** [comment]
In 2.0 you can use a user-defined action to implement this functionality
