### ISSUE TITLE
No Gap Fill with bucket size bigger then inserted interval of data

### ISSUE THREAD

**Issue by saasrack** [timescale/timescaledb#3120]
**Relevant system information:**

PostgreSQL version 12
TimescaleDB 2.2.0

**Describe the bug**
Gapfill seems not working as I would expect. I have data in timescaledb for every quarter of an hour. If I have a gap of for example 8 hours I expect that `time_bucket_gapfill` with a bucket width of `1h` would fill those gaps using data left within a range.

**Observation**
If I have a bucket size smaller than 15 minutes the gap filling is almost working but not for bigger bucket sizes.

**To Reproduce**
```
SELECT
	time_bucket_gapfill('1h', datetime, '2021-04-10T22:00:00', '2021-04-12T22:00:00') AS day,
	deviceId,
	avg(sensor_temperature) AS value,
	interpolate(avg(sensor_temperature)),
	locf(avg(sensor_temperature))
FROM sensors
WHERE datetime BETWEEN '2021-04-10T22:00:00' AND '2021-04-12T22:00:00' AND deviceId = '123'
GROUP BY day, deviceId
ORDER BY day;
```

**Expected behavior**
All gaps filled regardless of bucket size

**Actual behavior**
with `time_bucket_gapfill('1h', datetime, '2021-04-10T22:00:00', '2021-04-12T22:00:00')`

![image](https://user-images.githubusercontent.com/13893051/114780890-44bff800-9d78-11eb-82bb-89d29001b4c3.png)

with `time_bucket_gapfill('5min', datetime, '2021-04-10T22:00:00', '2021-04-12T22:00:00')`

![image](https://user-images.githubusercontent.com/13893051/114781115-89e42a00-9d78-11eb-87c0-e06d729ba97e.png)
![image](https://user-images.githubusercontent.com/13893051/114781309-cc0d6b80-9d78-11eb-9c22-5782105287d7.png)

**Comment by saasrack** [comment]
From the issue #1453 I found out that there is no interpolation on `null` values but only if a record is really missing. This is kind of unfortunate. Although a working workaround is to have in the `WHERE` filtering out with `IS NOT NULL`, but this would also eliminate existing data which are not `null`.

I didn't expect this. Currently I also working with Azure Timeseries Insights which is able to interpolate `null` values.

Is there a workaround to have interpolation on null values or is anything planned to support this?

**Comment by k-rus** [comment]
> Is there a workaround to have interpolation on null values or is anything planned to support this? Something like with `locf` having `treat_null_as_missing`.

For the feature request I refer to the issue you already discovered https://github.com/timescale/timescaledb/issues/1453 Welcome to vote the for the feature.

For the work around, can you think to split your query into join of two subqueries, where one uses interpolate and gapfill with `IS NOT NULL` work around, and another selects columns with values.

**Comment by saasrack** [comment]
Closed. Duplicate #1453
