### ISSUE TITLE
`SELECT DISTINCT` pushdown on space-time partitioning columns in multi-node should remove Sort/Unique upper nodes

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#3121]
Consider the below

```
SELECT create_distributed_hypertable('hyper', 'time', 'device', chunk_time_interval => 200);
```

Ideally, if we do SELECT DISTINCT device on such a table, we shouldn't need to run a HashAgg or Unique node on the access node since we know that the responses from the data nodes are unique already (given that we spread the data across data nodes according to the "device" key"). So, it would be sufficient to just append the results from each data node, which would be much more efficient.

So, the intuition would be that if the DISTINCT covers all the partitioning keys OR the space dimension (if such a dimension exists), then the query requires no unique processing on the access node.

Similarly, if you partition only on time, you should be able to push down SELECT DISTINCT time without unique processing on the access node.

**Comment by svenklemm** [comment]
multinode has been removed
