### ISSUE TITLE
Correlated subqueries dont work on distributed hypertables

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3129]
Example Query:
```
SELECT *, (SELECT time FROM hyper t WHERE t.device=g.device LIMIT 1 ) FROM generate_series(1,3) g(device)
```
Error message:
```
ERROR:  [data_node_1]: bind message supplies 0 parameters, but prepared statement "" requires 1
```

**Comment by erimatnor** [comment]
I believe this should be fixed, at least it wasn't reproducible on 2.6.1. I believe [this PR could have fixed it](https://github.com/timescale/timescaledb/pull/3852). Closing until there's more information on how and on which version to reproduce this issue. @svenklemm
