### ISSUE TITLE
why schedular job not work?

### ISSUE THREAD

**Issue by breezexjc** [timescale/timescaledb#3131]
when I use the command "SELECT add_retention_policy('conditions', INTERVAL '24 hours');" to create a scheduler task to delete data, the job information was successfully saved in the library, but the scheduler did not take effect, and the task did not run on time.  Is there any possible reason?

**Comment by mkindahl** [comment]
@breezexjc It is hard to tell from the information above. You should check `job_stats` to figure out what is wrong. See [Data Retention](https://docs.timescale.com/latest/using-timescaledb/data-retention#data-retention) chapter in the documentation for more information.

You will probably have more success in resolving your problem if you go to the [TimescaleDB Community Slack](https://slack.timescale.com/).
