### ISSUE TITLE
No ppa for Ubuntu 17.10

### ISSUE THREAD

**Issue by scls19fr** [timescale/timescaledb#315]
Hello,

I'm using Ubuntu 17.10
According http://docs.timescale.com/latest/getting-started/installation/linux/installation-apt
I'm trying to follow the instructions

```
# Add our PPA
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt-get update
# To install
sudo apt install timescaledb
```

But `sudo apt-get update` raises

    Err:11 http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu artful Release
      404  Not Found

Any idea?

Kind regards

**Comment by RobAtticus** [comment]
Hi thanks for pointing that out. I missed that Ubuntu 17.10 was out officially so i didn't upload the packages. This should be fixed in a few minutes.

**Comment by mfreed** [comment]
@scls19fr Let us know if that fixed your problem?  If so, please close out the issue.  Thanks!

**Comment by scls19fr** [comment]
I can install it. Will try it in the next days. Thanks
