### ISSUE TITLE
Error compatibility after make with postgres 13.1

### ISSUE THREAD

**Issue by shab2** [timescale/timescaledb#3161]
postgres@db-cyberft-1:/distrib/postgres-13.1/timescaledb
[PCFT_PLATINA]$ cd ./build && make
Scanning dependencies of target sqlupdatescripts
[  1%] Generating /distrib/postgres-13.1/timescaledb/build/sql/updates/post-update.sql.processed
[  1%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.1.1--2.2.0.sql
[  2%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.1.0--2.2.0.sql
[  2%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.2--2.2.0.sql
[  3%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.1--2.2.0.sql
[  3%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.0--2.2.0.sql
[  4%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.0-rc4--2.2.0.sql
[  4%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.0-rc3--2.2.0.sql
[  5%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.0-rc2--2.2.0.sql
[  5%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.0.0-rc1--2.2.0.sql
[  6%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.5--2.2.0.sql
[  6%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.4--2.2.0.sql
[  7%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.3--2.2.0.sql
[  7%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.2--2.2.0.sql
[  8%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.1--2.2.0.sql
[  8%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.7.0--2.2.0.sql
[  9%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.6.1--2.2.0.sql
[  9%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.6.0--2.2.0.sql
[ 10%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.5.1--2.2.0.sql
[ 10%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.5.0--2.2.0.sql
[ 11%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.4.2--2.2.0.sql
[ 11%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.4.1--2.2.0.sql
[ 12%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.4.0--2.2.0.sql
[ 12%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.3.2--2.2.0.sql
[ 12%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.3.1--2.2.0.sql
[ 13%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.3.0--2.2.0.sql
[ 13%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.2.2--2.2.0.sql
[ 14%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.2.1--2.2.0.sql
[ 14%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.2.0--2.2.0.sql
[ 15%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.1.1--2.2.0.sql
[ 15%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--1.1.0--2.2.0.sql
[ 15%] Built target sqlupdatescripts
Scanning dependencies of target sqlfile
[ 15%] Generating /distrib/postgres-13.1/timescaledb/build/sql/timescaledb--2.2.0.sql
[ 15%] Built target sqlfile
Scanning dependencies of target timescaledb
[ 15%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
In file included from /distrib/postgres-13.1/timescaledb/src/agg_bookend.c:18:
/distrib/postgres-13.1/timescaledb/src/compat.h:43:2: error: #error "Unsupported PostgreSQL version"
 #error "Unsupported PostgreSQL version"
  ^~~~~
make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:63: src/CMakeFiles/timescaledb.dir/agg_bookend.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by saasrack** [comment]
Isn't 13.2 required? https://docs.timescale.com/latest/release-notes

**Comment by fvannee** [comment]
Only version 13.2 and above is supported by TimescaleDb, see https://github.com/timescale/timescaledb/releases/tag/2.1.0

**Comment by mkindahl** [comment]
As @fvannee notes, we do not support versions prior to 13.2. Closing issue.
