### ISSUE TITLE
Support remote EXPLAIN for inserts, deletes, and updates

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3168]
On distributed hypertables, it is possible to enable remote explains by setting a GUC (`timescaledb.enable_remote_explain`). However, this only emits the remote explain for `SELECT` queries when a `DataNodeScan` node is used. It would be useful to see the remote EXPLAIN also for INSERT, UPDATE, and DELETE queries.

**Comment by svenklemm** [comment]
multinode has been removed
