### ISSUE TITLE
How to leverage indexes properly

### ISSUE THREAD

**Issue by simPod** [timescale/timescaledb#317]
I'm doing something wrong with timescale. My query takes ~30s for, in my opinon, fairly low amount of total (~120KK) rows in DB.

I have created hypertable with 1 day chunk time interval `SELECT create_hypertable('records', 'created_at', chunk_time_interval=>86400000000);`
 I think I got this part right as the `ANALYZE` command outputs 3 chunks so it searches only through the necessary data.

```sql
SELECT
  sum(bits),
  created_at
FROM records
WHERE created_at >= '2017-11-12 04:45' AND created_at <= '2017-11-14 04:45'
AND some_other_id = 4
GROUP BY created_at
ORDER BY created_at ASC;
```
I have those two indices:
```sql
records_created_at_idx INDEX records (created_at ASC);
records_some_other_id_created_at_index INDEX records (some_other_id ASC, created_at ASC);
```
But when I run `EXPLAIN ANALYZE` it seems that it doesn't leverage those indexes and instead does Parallel Seq Scan (`Filter: ((created_at >= '2017-11-12 04:45:00'::timestamp without time zone) AND (created_at <= '2017-11-14 04:45:00'::timestamp without time zone) AND (some_other_id = 4))
`)
```
Finalize GroupAggregate  (cost=1250118.21..1250129.21 rows=200 width=12) (actual time=27685.036..27686.576 rows=577 loops=1)
  Group Key: records.created_at
  ->  Sort  (cost=1250118.21..1250121.21 rows=1200 width=12) (actual time=27685.013..27685.569 rows=4039 loops=1)
        Sort Key: records.created_at
        Sort Method: quicksort  Memory: 286kB
        ->  Gather  (cost=1249934.83..1250056.83 rows=1200 width=12) (actual time=27680.773..27682.853 rows=4039 loops=1)
              Workers Planned: 6
              Workers Launched: 6
              ->  Partial HashAggregate  (cost=1248934.83..1248936.83 rows=200 width=12) (actual time=27656.443..27656.626 rows=577 loops=7)
                    Group Key: records.created_at
                    ->  Result  (cost=0.00..1204809.10 rows=8825147 width=12) (actual time=0.126..24517.067 rows=7541359 loops=7)
                          ->  Append  (cost=0.00..1116557.63 rows=8825147 width=12) (actual time=0.125..22581.920 rows=7541359 loops=7)
                                ->  Parallel Seq Scan on records  (cost=0.00..0.00 rows=1 width=12) (actual time=0.001..0.001 rows=0 loops=7)
                                      Filter: ((created_at >= '2017-11-12 04:45:00'::timestamp without time zone) AND (created_at <= '2017-11-14 04:45:00'::timestamp without time zone) AND (some_other_id = 4))
                                ->  Parallel Seq Scan on _hyper_1_2_chunk  (cost=0.00..543607.27 rows=4602955 width=12) (actual time=0.122..15519.306 rows=3979685 loops=7)
                                      Filter: ((created_at >= '2017-11-12 04:45:00'::timestamp without time zone) AND (created_at <= '2017-11-14 04:45:00'::timestamp without time zone) AND (some_other_id = 4))
                                      Rows Removed by Filter: 796917
                                ->  Parallel Seq Scan on _hyper_1_3_chunk  (cost=0.00..203878.74 rows=440727 width=12) (actual time=1.158..3712.608 rows=320420 loops=7)
                                      Filter: ((created_at >= '2017-11-12 04:45:00'::timestamp without time zone) AND (created_at <= '2017-11-14 04:45:00'::timestamp without time zone) AND (some_other_id = 4))
                                      Rows Removed by Filter: 1404631
                                ->  Parallel Seq Scan on _hyper_1_5_chunk  (cost=0.00..369071.62 rows=3781464 width=12) (actual time=0.337..1770.476 rows=3241255 loops=7)
                                      Filter: ((created_at >= '2017-11-12 04:45:00'::timestamp without time zone) AND (created_at <= '2017-11-14 04:45:00'::timestamp without time zone) AND (some_other_id = 4))
Planning time: 0.452 ms
Execution time: 27687.188 ms
```
Why? How can I let timescale use the indeces for filtering results? Thanks!

**Comment by mfreed** [comment]
Hi @simPod.  

If the predicate (filter) will match on more like something like 5-10% of all the rows in the table, the Postgres planner will use a sequential scan rather an index scan, as it can often save I/O operations.  In the case above, it looks like your filter actually doesn't remove much at all (e.g., chunk 2 only removed ~800K rows from scan over ~4M rows).  Maybe a large fraction of the rows actually have `some_other_id = 4`?

You can always force timescale/postgres to perform an index scan for testing by setting in `psql` the following command:

```
SET enable_seqscan = OFF;
```

I think your main question, however, is why a scan of ~9M rows takes 30s?  Would need to dig a bit deeper into your setup.  You might also want to try turning off multiple workers and comparing performance -- we've found mixed performance when chunks are particularly small, given that it can't (yet) parallelize *across* chunks, only within chunks.

Also, happy to answer these more type of debugging Q&A on our [Slack channel](http://slack-login.timescale.com).  Cheers!

**Comment by simPod** [comment]
Thank you for response. You are basically right, most of rows have some_other_id = 4. Will get in touch via slack.
