### ISSUE TITLE
A upgrade  problem

### ISSUE THREAD

**Issue by DimeSnow** [timescale/timescaledb#3172]
Hello, I'm going to upgrade the version of PostgreSQL from 12 to 13. 
So it means that I have installed a 12 version PG with timescale.When I was installing Postgres for PG13, I was prompted：
exit: unknown major PG version: PostgreSQL 13.2 (Ubuntu 13.2-1.pgdg18.04+1)
Is this because my wubantu already has the previous 12 versions of timescaledb? Or does timescaledb not support PG13 under Linux. I have successfully upgraded in windows.

**Comment by mkindahl** [comment]
Hello @DimeSnow,

The error you're getting is not related to TimescaleDB at all, it has to do with installing PG13. TimescaleDB does supports PG13, but only starting with TimescaleDB 2.1, so you first need to update the TimescaleDB extension to 2.1 and then upgrade the PG installation to PG13.

You can see more about this in https://docs.timescale.com/latest/update-timescaledb.
