### ISSUE TITLE
Grafana time_bucket high resolution

### ISSUE THREAD

**Issue by jameswinegar** [timescale/timescaledb#3177]
This might be an issue for grafana package, but the error I'm hitting is in TimescaleDB logic.

**Relevant system information:**
Installed from AMI in us-east-1, Postgres 12, Ubuntu 18.04

**Describe the bug**
```
SELECT
  $__timeGroupAlias("time",$interval),
  avg(measure) AS "Measure",
FROM iot_data
WHERE
  $__timeFilter("time") AND
  device = '$device'
GROUP BY 1
ORDER BY 1
```

When the interval variable is above 100ms query works fine; however, when we use an interval of 10ms or 1ms we encounter the following error:

`pg: period must be greater then 0` (submitted a PR to fix the grammar)

When I run the equivalent query in psql the query runs fine.

**To Reproduce**
Change interval variable in Grafana

**Expected behavior**
I expect results to return instead of returning an error

**Actual behavior**
`pg: period must be greater then 0` 

**Screenshots**

<img width="301" alt="Screen Shot 2021-04-29 at 10 06 21 PM" src="https://user-images.githubusercontent.com/8434889/116643726-50461e00-a937-11eb-87a4-bda8ca42bfab.png">
<img width="321" alt="Screen Shot 2021-04-29 at 10 06 15 PM" src="https://user-images.githubusercontent.com/8434889/116643729-50461e00-a937-11eb-84f6-7da07158d541.png">
<img width="315" alt="Screen Shot 2021-04-29 at 10 06 32 PM" src="https://user-images.githubusercontent.com/8434889/116643655-2ab91480-a937-11eb-80e0-e54fbedd3701.png">

**Additional context**

**Comment by erimatnor** [comment]
@jameswinegar This sounds like a problem with the how Grafana generates the SQL statement. I don't think there's anything we can do on the database side of things. I would recommend checking with the Grafana project instead.

**Comment by jameswinegar** [comment]
Fixed in https://github.com/grafana/grafana/pull/33853

Will be in Grafana 8.0.0
