### ISSUE TITLE
TRUNCATE table in a loop

### ISSUE THREAD

**Issue by pafiti** [timescale/timescaledb#3182]
When using TRUNCATE in a loop, it seems that TRUNCATE only works one time and does not do anything after.
We are using PostgresSQL 13.2 with Timescale 2.2
Here is the code to reproduce the same issue

```
DO $$
DECLARE 
  n_record   int;
BEGIN
  CREATE TABLE IF NOT EXISTS test_truncate ( id int );
  FOR i IN 1..10 LOOP
    INSERT INTO test_truncate ( id ) SELECT * FROM generate_series( 1, 100 );
    SELECT COUNT(*) INTO n_record FROM test_truncate;
    RAISE NOTICE 'Before Truncate : %', n_record;
  
    TRUNCATE test_truncate;
--    DELETE FROM test_truncate;
  
    SELECT COUNT(*) INTO n_record FROM test_truncate;
    RAISE NOTICE 'After Truncate : %', n_record;
  
  END LOOP;
  DROP TABLE test_truncate;
END $$; 
```

**Comment by mkindahl** [comment]
@pafiti Thank you for the bug report. Could you elaborate on what output you get and what output you expect? It is not clear from the example.

**Comment by pafiti** [comment]
Yes sure.
The output for the database where TimescaleDb runs is the following :
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 100
Before Truncate : 200
After Truncate : 200
Before Truncate : 300
After Truncate : 300
Before Truncate : 400
After Truncate : 400
Before Truncate : 500
After Truncate : 500
Before Truncate : 600
After Truncate : 600
Before Truncate : 700
After Truncate : 700
Before Truncate : 800
After Truncate : 800
Before Truncate : 900
After Truncate : 900

The output in another database (same script / same postgres instance)
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0
Before Truncate : 100
After Truncate : 0

As you can see, the second logs are ok -> Number of rows after truncate is 0 while it is not the case within the timescale database.

**Comment by DavidPavlicek** [comment]
Hi, we have similar issue... truncate within function call is ignored when timescale is active. Without timescale, same code runs OK - table is truncated.

**Comment by fabriziomello** [comment]
@pafiti @DavidPavlicek I'm working on another issue (#3580) that seems will also fix it.
