### ISSUE TITLE
Inserts and queries fail on distributed hypertables that have array columns of custom types

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3190]
**Relevant system information:**

The bug relates to distributed hypertables (version 2.0+)

**Describe the bug**

When a table has an array of a custom type as a column, inserts and queries fail by default on distributed hypertables. This is because the connection uses binary mode and arrays are serialized with the OID of the element type in the header. The OID of a custom type can differ across databases (and thus data nodes).

**To Reproduce**
Will add example later.

**Expected behavior**
Inserts and queries should not fail.

**Actual behavior**
Inserts and queries fail with errors like `ERROR:  wrong element type: 21074 vs 21066`.

**Proposed fix**

The code should check for arrays of custom types in the target list and either revert to text serialization for all column types or try to use text just for the array type.

**Comment by akuzm** [comment]
Newer versions of posgres started to ignore this error (I think since 13), so it's less of a problem now.

```
	/*
	 * From a security standpoint, it doesn't matter whether the input's
	 * element type matches what we expect: the element type's receive
	 * function has to be robust enough to cope with invalid data.  However,
	 * from a user-friendliness standpoint, it's nicer to complain about type
	 * mismatches than to throw "improper binary format" errors.  But there's
	 * a problem: only built-in types have OIDs that are stable enough to
	 * believe that a mismatch is a real issue.  So complain only if both OIDs
	 * are in the built-in range.  Otherwise, carry on with the element type
	 * we "should" be getting.
	 */
```

**Comment by svenklemm** [comment]
Seems to work in recent versions.
