### ISSUE TITLE
How to migrate tags from influx to timescale and represent them in Grafana as tag variables

### ISSUE THREAD

**Issue by aimtsou** [timescale/timescaledb#3197]
**Relevant system information:**
 - OS: Cent OS 7
 - PostgreSQL version 12.5
 - TimescaleDB version 2.2.0
 - Grafana version v7.4.3
 - InfluxDB 1.7.7
 - Installation method: Compiled the plugin and installed

**Describe the issue**
I have tried to migrate a database from influx to timescaledb. My influx database has jolokia metrics and certain tags (more on that later). So what I did is I used the outflux tool to migrate the data from one database to the other. The command I used:

`./outflux migrate mydb --input-server https://server1:1234 --input-user user --input-pass test --output-conn='host=server2 port=1234 dbname=test user=test password=test sslmode=verify-full' --retention-policy test`

My database seems to have been migrated, the extension was enabled and hypertables were created. The problem is I cannot see data in Grafana. I can see the tables and the columns but I cannot see any data. Querying the data in postgres with classic SQL works.

What I have read so far:
https://docs.timescale.com/timescaledb/latest/tutorials/grafana/grafana-variables/#creating-a-variable
https://docs.timescale.com/timescaledb/latest/tutorials/nyc-taxi-cab/#mission-gear-up

What I did in influx is the following:
`SELECT mean("TotalPhysicalMemorySize") FROM "MemoryStats" WHERE ("cluster" =~ /^$cluster$/ AND "host" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), "host", "application" fill(null)`

As you see cluster and host are variables which come from a set of tags and are defined in the Variables of the dashboard by executing:

`SHOW TAG VALUES WITH KEY=cluster`

Then I had a list of cluster and I could filter which one I want. I provide a sample query build in query builder:

```
SELECT
  "time" AS "time",
  "ProcessCpuLoad"
FROM "jvmCpuUsage"
WHERE
  $__timeFilter("time")
ORDER BY 1
```

Consequently, my questions are:
1) Should I have used the tags as json field during the migration?
2) How should I display the data in Grafana in a similar way with what I did in influx?
3) Have I missed such an example in the documentation?
4) Is there another way to achieve this result?

I see that a `select * from measurement` in influx displays the same record as a `select * from table` in postgres but I doubt the representation inside the databases is the same.

**Comment by erimatnor** [comment]
@aimtsou If you have a feature request, please post this request to the Outflux repo: https://github.com/timescale/outflux

Otherwise, I suggest joining the TimescaleDB Slack community so that you can ask your question there. Unfortunately, we cannot answer general support questions in GitHub issues.

**Comment by aimtsou** [comment]
@erimatnor: This is not a feature request but I would say an improvement of documentation with another example. Outflux is a part of timescaledb docs.
