### ISSUE TITLE
Dropping a specific chunk

### ISSUE THREAD

**Issue by 120bits** [timescale/timescaledb#3218]
Hi 

How can I drop a specific chunk?  I need to free up some space and drop_chunk is taking huge time. Each chunk is around 150GB in size.

![image](https://user-images.githubusercontent.com/21069692/118070135-9309ec00-b362-11eb-87d2-2fc556db11e8.png)

Thanks.

**Comment by 120bits** [comment]
I realize I can do this,

`drop table _timescaledb_internal._hyper_54_4835_chunk`

It took 51 mins top drop that chunk. Any reasoning why does it take that long?

**Comment by binakot** [comment]
You shouldn't delete chunks directly. This can lead to an inconsistent state of the hypertable in TimescaleDB. In time series, it is customary to delete data older than some time. There is a function for this https://docs.timescale.com/api/latest/hypertable/drop_chunks/

Do you have external references from this hypertable to other tables? And what else is your database doing, perhaps disks or hardware in general under constant load, which is why droping a table is so long.

**Comment by 120bits** [comment]
There is not enough load on the database server to justify the time taking for drop_chunks to finish. Before I deleted the chunks directly, I tried using the drop_chunk and it was taking too long to execute. It actually froze the database for sometime and I couldn't even connect from pgadmin. I have a cron job that runs once day to drop chunks older than 24 hours. It had worked before, just this time it didn't or it didn't complete.

**Comment by nikkhils** [comment]
@120bits it's not recommended to delete the chunk directly because it can leave the hypertable metadata inconsistent.

**Comment by 120bits** [comment]
Thank you for your all comments. 

I still don't get it why does is it taking so long to drop chunks? I check the system load, like 10% CPU usage with barely any IO wait. It took almost 7hours to drop 200GB chunk. I had to stop writes to that table just make sure. I deleted all the chunks manually and then had to re create the table with new chunk policy.

**Comment by nikkhils** [comment]
@120bits can you please check the `pg_locks` view output the next time you run drop chunks? It's possible that there's an issue in acquiring the lock required to drop the chunk.

**Comment by svenklemm** [comment]
As erik mentioned you can drop a specific chunk with `DROP TABLE <chunk>;`
