### ISSUE TITLE
Remote transactions cleanup/healing job fails on every run

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#3219]
**Relevant system information:**
 - OS: Centos 7.5
 - PostgreSQL version: `12.6`
 - TimescaleDB version (output of `\dx` in `psql`): `2.1.0`
 - Installation method: `yum`

**Describe the bug**
Cleanup of unfinished transactions always fails/stops at the very first transaction that causes error, which in turn causes it to not cleanup anything and the number of unfinished transactions keeps building up.

**To Reproduce**
1. Have a distributed hypertable with a constant non-stop flow of data (in our case about 40MB/s [bytes, not bits] of inbound data for writing in one table)
2. Have a maintenance job configured as per https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-maintenance/#multi-node-maintenance-tasks
3. Check logs
4. Check `select count(*) from _timescaledb_catalog.remote_txn;`

**Expected behavior**
The number of remote transactions over time should be a saw pattern (such as build up until the cleanup job runs which finishes/heals all/most of the unfinished transactions). The logs should not have any errors unless something critical happens.

**Actual behavior**
The number of remote transaction over time keeps building up and never being flushed. The configured maintenance task fails with following entries in logs intermixed (note that tx ids are changing, but in some cases are repeating non-stop i.e. stuck on one bad transaction) (note timestamps are removed and hostnames are edited):

```
[22822] LOG:  job 1000 threw an error
[22822] ERROR:  [datanode01.domain.name]: prepared transaction with identifier "ts-1-540621498-20818-20824" is busy
[22822] CONTEXT:  SQL function "data_node_maintenance" statement 1
[37139] LOG:  background worker "User-Defined Action [1000]" (PID 22822) exited with exit code 1

[22833] LOG:  job 1000 threw an error
[22833] ERROR:  [datanode03.domain.name]: prepared transaction with identifier "ts-1-540625107-20762-20824" does not exist
[22833] CONTEXT:  SQL function "data_node_maintenance" statement 1
[37139] LOG:  background worker "User-Defined Action [1000]" (PID 22833) exited with exit code 1
```

**Additional context**
This is causing growing disk space usage on access node (some of databases on access node grew to 300GB+ in size just because of the size of forever-growing `_timescaledb_catalog.remote_txn`

I do think that the job should skip TX if it is busy/does not exist/some other issue. And should continue to the cleanup of transactions that it can process still. Otherwise (as noticed by performance metrics) the inserts become even slower for distributed setup (from ~100ms per 1000 rows to ~150ms with remote_txn size being over 200GB).

**Comment by pmwkaa** [comment]
@akamensky Thanks for report, AFAIK this table is never cleaned up and the idea was that some kind of background cleaning process should do this automatically. This table is used on the access node to record remote transaction ids and then do prepared transactions abort in case of 2PC failures. As a temporary solution I believe it should be safe to manually delete old data from that table for now

**Comment by akamensky** [comment]
@pmwkaa that is actually not correct. It is cleaned when the maintenance task runs. The problem is that maintenance task fails constantly. Please check the report. That's what it is about.

**Comment by pmwkaa** [comment]
@akamensky sorry if I misunderstood. My understanding was that the `remote_txn `table keeps growing in size, because you were unable to properly run maintenance task, since it keeps failing and not able to clean up as much data as needed. Is that correct?

**Comment by akamensky** [comment]
Yes, the main point of this ticket is the maintenance jobs failing and not doing anything. If that matters I found another thing is that even if I pause all data ingest and all querying and run maintenance, which is then likely to succeed (since no live transactions are present), then the disk space is still used and vacuuming of table is not working:

```
2021-05-14 08:48:25.569 TZ [1331] ERROR:  canceling autovacuum task
2021-05-14 08:48:25.569 TZ [1331] CONTEXT:  automatic vacuum of table "db_name._timescaledb_catalog.remote_txn"
```

**Comment by nikkhils** [comment]
Hi @akamensky 

The error below:

```
ERROR:  [datanode01.domain.name]: prepared transaction with identifier "ts-1-540621498-20818-20824" is busy
```

indicates that there's a backend running on `datanode01` currently trying to do something with this prepared transaction. You could run `pg_stat_activity` on `datanode01` to check if that's the case.

**Comment by akamensky** [comment]
@nikkhils as I mentioned above we cannot afford to stop all transactions as the data is being ingested to the database in a real-time and as the constant stream. The transactions are created by the ingest of data. So stopping them means stopping ingest = losing data, which is a no go on our end. And without this healing the size of table keeps growing to rather large size. 

The point is that one transaction blocks the maintenance job from cleaning the rest of them. So imagine there are 50000 transactions in that table. The first one is still active. The rest are not active anymore. Then the maintenance job fails on very first transaction. Next time it runs there is already 100000 transactions and again the very first one is still active. That basically makes this maintenance job useless and just spam the log with errors.

**Comment by erimatnor** [comment]
@akamensky I think the only solution to this problem is to try and figure out which backend/transaction is holding a lock on the data node and then make sure that the lock is released. It would be valuable for use to know, however, why that transaction is blocked. It could be, e.g., a deadlock.

**Comment by nikkhils** [comment]
@akamensky I did not suggest to stop the data ingestion. I suggested querying `datanode01` to identify why we are getting `prepared transaction with identifier "ts-1-540621498-20818-20824" is busy` error on it. Erik is suggesting the same above.

**Comment by akamensky** [comment]
Sorry for misunderstanding. I will check it and report what transaction it is.

As I also mentioned this happens when only ingest is running, which would suggest that these transactions are generated by ingest process. The ingest itself is batch INSERTs that comes from kafkaconnect process.

**Comment by erimatnor** [comment]
@akamensky Any progress in finding out which backend was holding the blocking transaction or did this issue resolve itself?

**Comment by akamensky** [comment]
@erimatnor the issue is not resolved yet, we still have the same problem. We currently cannot find time to investigate this issue deeper. But will get back to this soon.

**Comment by akamensky** [comment]
@erimatnor like I speculated above, this is coming from all the data ingest. There are no other queries in the cluster. All those blocked transactions are inserts from kafkaconnect.

FWIW I also see that writing this data saturates disk IO on access node. Because this is a table and this table is stored on disk rather than in-memory.

**Comment by rwilliams-r7** [comment]
We are also having the same problem and it is causing large performance problems. Is there any help on this problem?

**Comment by nikkhils** [comment]
There might a race condition here:

1) AN regular backend is running an INSERT and generates a 2PC with some identifier $ID1
2) AN regular backend sends a "PREPARE TRANSACTION $ID1" to datanode 1
3) Background worker on AN runs a remote_txn_heal job which queries datanode1 to get a list of active prepared transactions in which datanode1 returns $ID1
4) AN regular backend sends a "COMMIT PREPARED $ID1" to datanode1
5) Background worker on AN checks status of $ID1 locally and then decides to send "COMMIT PREPARED $ID1" to datanode1. Now datanode1 will ERROR out with `prepared transaction with identifier $ID1 does not exist` because $ID1 does not exist on it anymore
6) In some variation of (5) it might be possible that this new "COMMIT PREPARED $ID1" interferes with the regular original datanode1 "COMMIT PREPARED $ID1" handling leading to `prepared transaction with identifier $ID1 is busy` error.

**Comment by nikkhils** [comment]
So, I checked the `remote_txn_resolution` function closely and the COMMIT decision is indeed decided based on an entry being present in the `remote_txn` table. So the race condition is there even with the entry present here. The XID check logic via `XidInMVCCSnapshot` is only used to check for ongoing txns so it’s not a big issue. 

Now that I look more, I think the main issue is not the presence of these transient errors. The main issue is due to the presence of in-progress transactions. The current logic in `remote_txn_heal_data_node` DOES NOT cleanup the `remote_txn` table if there are ANY in-progress transactions. In a very busy system, we will see in-progress transactions almost all the time so the logic is clearly not great. 

We should basically track the GIDs which have been cleaned up via ABORT/COMMIT in a list and clean those up out of the `remote_txn` table to keep it's size under check.
