### ISSUE TITLE
The first query is very slow

### ISSUE THREAD

**Issue by carbonhe** [timescale/timescaledb#3223]
I have more than one billion data, and it takes a few minutes when there is no hot query (the second query is fast), is this normal for timescale?

**Comment by binakot** [comment]
I got the same experience on every run of new timescale single-node or distributed hypertable. I think the problem is in a planner's statistics, but I'm not sure. It would be cool if Timescale extensions after creating a new hypertable execute some synthetic query (some kind of ping or `select 1`) to fix that.

**Comment by pmwkaa** [comment]
@carbonhe Could you please provide more details, such as TimescaleDB version and the `EXPLAIN` command output (on the first run, if possible)

**Comment by carbonhe** [comment]
@pmwkaa The main information is as follows：
- TimescaleDB version is 2.2.0
- The entire typertable about 1.7 billion rows
- The query sql is
    ```sql
          select "Time",                   
              "MeasureValue",        
              "SampleFreqNr",        
              "EngUnitId",
              "DatTypeNr",
              "SigTypeNr",
              "SyncNr"
          from "BenchmarkTable"
          where "PointOnlyCode" = '3240'
              and "Time" >= '2010-01-13 01:00:00'
              and "Time" < '2010-01-14 01:00:00'
          order by "Time" desc;

- There are about 86000 result rows for the above query sql 
- There are about 93 million rows for the above query interval (ignore the query condition `"PointOnlyCode" = '3240'`) 
- The first `EXPLAIN` output:
     ```
   Custom Scan (ChunkAppend) on "BenchmarkTable"  (cost=0.43..1572357.19 rows=9423 width=42) (actual time=834.520..1207746.710 rows=1440 loops=1)
   Order: "BenchmarkTable"."Time" DESC
   Buffers: shared hit=1481 read=360052
   ->  Index Scan Backward using "_hyper_1_1633_chunk_BenchmarkTable_query_idx" on _hyper_1_1633_chunk  (cost=0.43..33704.04 rows=203 width=42) (actual time=834.518..23443.575 rows=30 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=32 read=7502
   ->  Index Scan Backward using "_hyper_1_1632_chunk_BenchmarkTable_query_idx" on _hyper_1_1632_chunk  (cost=0.43..163681.45 rows=974 width=42) (actual time=249.263..133626.162 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37507
   ->  Index Scan Backward using "_hyper_1_1631_chunk_BenchmarkTable_query_idx" on _hyper_1_1631_chunk  (cost=0.43..163667.15 rows=973 width=42) (actual time=60.498..123979.264 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1630_chunk_BenchmarkTable_query_idx" on _hyper_1_1630_chunk  (cost=0.43..163669.94 rows=976 width=42) (actual time=179.264..111964.795 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1629_chunk_BenchmarkTable_query_idx" on _hyper_1_1629_chunk  (cost=0.43..163671.93 rows=984 width=42) (actual time=173.773..145949.710 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1628_chunk_BenchmarkTable_query_idx" on _hyper_1_1628_chunk  (cost=0.43..163668.43 rows=977 width=42) (actual time=127.255..100517.485 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1627_chunk_BenchmarkTable_query_idx" on _hyper_1_1627_chunk  (cost=0.43..163672.78 rows=986 width=42) (actual time=218.148..147567.453 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1626_chunk_BenchmarkTable_query_idx" on _hyper_1_1626_chunk  (cost=0.43..163671.88 rows=983 width=42) (actual time=208.197..107633.355 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1625_chunk_BenchmarkTable_query_idx" on _hyper_1_1625_chunk  (cost=0.43..163672.76 rows=986 width=42) (actual time=221.829..135861.921 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1624_chunk_BenchmarkTable_query_idx" on _hyper_1_1624_chunk  (cost=0.43..163673.76 rows=988 width=42) (actual time=216.048..127783.409 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=154 read=37505
   ->  Index Scan Backward using "_hyper_1_1623_chunk_BenchmarkTable_query_idx" on _hyper_1_1623_chunk  (cost=0.43..65603.09 rows=393 width=42) (actual time=50.729..49416.437 rows=60 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
        Buffers: shared hit=63 read=15003
        Planning:
        Buffers: shared hit=1241 read=74
        Planning Time: 512.759 ms
        JIT:
        Functions: 44
        Options: Inlining true, Optimization true, Expressions true, Deforming true
        Timing: Generation 29.858 ms, Inlining 16.906 ms, Optimization 338.692 ms, Emission 150.278 ms, Total 535.734 ms
        Execution Time: 1207778.740 ms

- The second `EXPLAIN` output:
   ```
  Custom Scan (ChunkAppend) on "BenchmarkTable"  (cost=0.43..1572357.19 rows=9423 width=42) (actual time=488.046..3359.778 rows=1440 loops=1)
   Order: "BenchmarkTable"."Time" DESC
   Buffers: shared hit=361533
   ->  Index Scan Backward using "_hyper_1_1633_chunk_BenchmarkTable_query_idx" on _hyper_1_1633_chunk  (cost=0.43..33704.04 rows=203 width=42) (actual time=488.045..547.781 rows=30 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=7534
   ->  Index Scan Backward using "_hyper_1_1632_chunk_BenchmarkTable_query_idx" on _hyper_1_1632_chunk  (cost=0.43..163681.45 rows=974 width=42) (actual time=0.285..294.747 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37661
   ->  Index Scan Backward using "_hyper_1_1631_chunk_BenchmarkTable_query_idx" on _hyper_1_1631_chunk  (cost=0.43..163667.15 rows=973 width=42) (actual time=0.226..297.827 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1630_chunk_BenchmarkTable_query_idx" on _hyper_1_1630_chunk  (cost=0.43..163669.94 rows=976 width=42) (actual time=0.238..304.801 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1629_chunk_BenchmarkTable_query_idx" on _hyper_1_1629_chunk  (cost=0.43..163671.93 rows=984 width=42) (actual time=0.227..296.130 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1628_chunk_BenchmarkTable_query_idx" on _hyper_1_1628_chunk  (cost=0.43..163668.43 rows=977 width=42) (actual time=0.227..300.772 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1627_chunk_BenchmarkTable_query_idx" on _hyper_1_1627_chunk  (cost=0.43..163672.78 rows=986 width=42) (actual time=0.231..295.976 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1626_chunk_BenchmarkTable_query_idx" on _hyper_1_1626_chunk  (cost=0.43..163671.88 rows=983 width=42) (actual time=0.225..297.543 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1625_chunk_BenchmarkTable_query_idx" on _hyper_1_1625_chunk  (cost=0.43..163672.76 rows=986 width=42) (actual time=0.258..297.510 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1624_chunk_BenchmarkTable_query_idx" on _hyper_1_1624_chunk  (cost=0.43..163673.76 rows=988 width=42) (actual time=0.241..307.316 rows=150 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=37659
   ->  Index Scan Backward using "_hyper_1_1623_chunk_BenchmarkTable_query_idx" on _hyper_1_1623_chunk  (cost=0.43..65603.09 rows=393 width=42) (actual time=0.248..119.140 rows=60 loops=1)
         Index Cond: (("Time" >= '2010-01-13 01:00:00'::timestamp without time zone) AND ("Time" < '2010-01-14 01:00:00'::timestamp without time zone) AND (("PointOnlyCode")::text = '3240'::text))
         Buffers: shared hit=15066
         Planning:
         Buffers: shared hit=175
         Planning Time: 2.749 ms
         JIT:
         Functions: 44
         Options: Inlining true, Optimization true, Expressions true, Deforming true
         Timing: Generation 7.701 ms, Inlining 8.397 ms, Optimization 327.172 ms, Emission 151.863 ms, Total 495.133 ms
         Execution Time: 3367.752 ms


The first query takes about 20 minutes, I think is too long.Is this normal for timescale?

**Comment by pmwkaa** [comment]
Not sure, but seems like 93 millions records is quite a big number. Also you can notice that on the first run it does a lot reads and places pages into the shared buffer, while the second run completely uses it.

Are those queries executed right after the PostgreSQL instance started? (machine started)

**Comment by nikkhils** [comment]
As mentioned above, the second time the EXPLAIN output contains:

```
Buffers: shared hit=361533
```

this means the data that is required to satisfy the query is already in the shared buffers due to the first SELECT operation. The shared buffer cache after Postgres start or restart will build up over time with the hotly accessed content. So this is normal and expected behavior. One way to populate this cache would be to run a set of selected queries on [re]startup on your setup.

**Comment by nikkhils** [comment]
@carbonhe thanks a lot for reporting this issue. As you can see this is standard PostgreSQL shared buffer cache behavior. Please feel free to re-open or create a new issue in the light of any new information.

**Comment by carbonhe** [comment]
@nikkhils  Thanks for your answer. I think I should look for other solutions for the slow first query.

**Comment by Doyle-net** [comment]
I also have this problem。“timescale query is slow”。
TimescaleDB：2.6.0
