### ISSUE TITLE
[bug] data loss with high number of inserts

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#3224]
**Relevant system information:**
 - OS: `Centos 7.5`
 - PostgreSQL version (output of `postgres --version`): `12.6`
 - TimescaleDB version (output of `\dx` in `psql`): `2.1.0`
 - Installation method: `yum`

**Setup**
1. Multinode TimescaleDB with 1 Access node (physical host 28 cores, 256 GB RAM, SSD storage) and 3 Data nodes (physical, 16 cores, 128 GB RAM, SSD storage)
2. Distributed hypertable partitioned by timestamp without timezone field and by "text" field as space dimension (3 partitions)
3. Kafkaconnect sink (Confluent JDBC sink) that reads data off of Kafka and writes to TimescaleDB configured to run 20 tasks (= number of topic partitions)
4. Relevant Kafka topic is quite high in traffic, about 100k records per second, but only 4 fields (columns). Topic has 20 partitions (to parallelize writes to database) 

**Describe the bug**
We noticed that there are periods of data missing in TimescaleDB in this setup. Each gap is about 40 seconds and they are spread throughout the day and gap size and their frequency depend on the amount of traffic (as it is not a flat line, but fluctuates throughout the day). There is no any errors in the logs and no abnormal behavior in any component of the system.

We verified by using another instance of JDBC kafkaconnect sink writing to another storage type that the data has no gaps in it. Which rules out both Kafka and kafkaconnect as source of issue (as same kafka topic serves as a source of data for both sinks and sinks are actually same, just different configuration pointing to different DBs).

Another note is that we noticed the buildup of unfinished remote transactions (`_timescaledb_catalog.remote_txn` table) throughout the day, in the amounts that clearly exceed the number of read queries from users, which means it comes from written data.

**To Reproduce**
Not sure if it will be possible to reproduce in other environments as not even sure what causes this issue. But the setup is given above.

**Expected behavior**
All data present in database.

**Actual behavior**
Data has gaps, with width and frequency that correlate (increase) with amount of writes per second.

**Additional context**
I believe this is a critical issue since this is a data loss without any error in what otherwise should be ACID compliant database.

**Comment by pmwkaa** [comment]
It would be great if it is possible to provide additional details on this or share new findings in the future. You noticed data loss specific to the distributed hypertable only, right? Are you using compression?

**Comment by akamensky** [comment]
I'll provide findings as we get them as still investigating this issue. 

We are not using compression.

We noticed this right after migration to distributed setup.

**Comment by nikkhils** [comment]
Hi @akamensky 

As you hinted yourself, this could be related to the remote txns healing issue that you mentioned via #3219. When that issue gets resolved then pending 2PC transactions will get cleaned/healed up on the datanodes making the rest of the data visible. You can check for pending 2PC on datanodes by using the `pg_prepared_xacts` view.

**Comment by akamensky** [comment]
@nikkhils thanks. We will check on our side. We potentially identified an error that's not related to timescale and are working to fix it to see whether that is the cause for some of missing data. You can put this issue on hold for now and I will update here as soon as we have the results.

**Comment by akamensky** [comment]
We identified and fixed the architectural issue on our side that was causing data loss. 

VERY slow inserts into distributed hypertables have been major contributing factor to this issue. However I see some work being done on that front.

Can close this issue as invalid.
