### ISSUE TITLE
Cannot install timescaledb

### ISSUE THREAD

**Issue by peedrr** [timescale/timescaledb#3245]
**Relevant system information:**
 - OS: macOS 11.2.3
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): n/a (not listed)
 - Installation method: homebrew, for both postgresql & timescaledb

**Describe the bug**
I am following along with [the tutorial](https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/post-install-setup/#setup) to get started with timescaledb and I cannot extend the 'tutorial' database with timescaledb:
```
postgres=# \c tutorial 
You are now connected to database "tutorial" as user "postgres".
tutorial=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not access file "$libdir/timescaledb-2.1.1": No such file or directory
```
I have confirmed the library is in the correct location:
```
$ exa -lhaG /usr/local/lib/postgresql | grep timescaledb
.rwxr-xr-x  497k peteh 19 May 11:14  timescaledb-2.2.1.so
.rwxr-xr-x  510k peteh 19 May 11:14  timescaledb-tsl-2.2.1.so
.rwxr-xr-x   80k peteh 19 May 11:14  timescaledb.so
```
([exa](https://the.exa.website/) is just a funky ls)

I have confirmed that I am connected to the same version of PostgreSQL that has the timescaledb libraries:
```
$ which postgres
/usr/local/bin/postgres
$ /usr/local/bin/postgres -V
postgres (PostgreSQL) 13.3
```
```
tutorial=# SELECT version();
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.3 on x86_64-apple-darwin20.4.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit
(1 row)

tutorial=# 
```

I am new to both postgresql and timescaledb so I'm not sure what else I should check.

Many thanks.

**Comment by jonatas** [comment]
Hello @peedrr! I installed it a few days ago and I remember I have a similar issue. The way I fixed was by relinking it in homebrew:

```
brew unlink postgresql; brew link postgresql
```

Thank you can restart the postgres service just for a sanity check:

```
brew services restart postgresql
```

**Comment by peedrr** [comment]
@jonatas - thanks for your response. I unlinked/relinked via homebrew, then restarted the PostgreSQL service for good measure. Something changed, although I'm not sure I can have complete confidence in what I experienced:

When I initially connected to the 'tutorial' database and tried to apply the timescaledb extension, I got the same error message as before:
```
postgres=# \c tutorial 
You are now connected to database "tutorial" as user "postgres".
tutorial=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not access file "$libdir/timescaledb-2.1.1": No such file or directory
```
However `\dx` now lists timescaledb as an installed extension:
```
tutorial=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.1.1   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)
```
and when I attempted to extend the database again, I got the following message:
```
tutorial=# CREATE EXTENSION IF NOT EXISTS timescaledb;
NOTICE:  extension "timescaledb" already exists, skipping
CREATE EXTENSION
```
So it looks like the extension is in place, but I'm not sure why it initially complained that it could not read from the library.

But this is progress and, for now, I'll assume all is good and I'll close the issue here on github.

@nikkhils - thanks for the suggestion. I actually discovered the Slack channel after submitting this issue on here, so I linked the issue into the Slack channel. Thanks for the heads-up.

**Comment by jonatas** [comment]
Great that you moved forward @peedrr! Enjoy!
