### ISSUE TITLE
Aggregates with DISTINCT are not supported

### ISSUE THREAD

**Issue by jameswinegar** [timescale/timescaledb#3247]
Given that #3000 was introduced in 2.2.0 it should make sense to allow DISTINCT in continuous aggregates where the DISTINCT column is indexed.

The below query is a prototypical example that is now enabled due to the distinct query where we can track utilization of devices across the ecosystem quickly. 

```
CREATE MATERIALIZED VIEW runs_view WITH
  (timescaledb.continuous)
AS
SELECT
  time_bucket('300.0s',"time") AS "time",
  count(distinct(runid)) AS "Distinct Run IDs"
FROM data_table
GROUP BY 1
WITH NO DATA
```

```
ERROR:  aggregates with FILTER / DISTINCT / ORDER BY are not supported
```

**Comment by nikkhils** [comment]
@jameswinegar thanks for suggesting this enhancement. We will triage this in the near future.

**Comment by alessani** [comment]
It would be amazing to have this feature

**Comment by svenklemm** [comment]
This is supported since 2.7.0.
```
postgres@i3247[1300539]=# CREATE MATERIALIZED VIEW runs_view WITH
i3247-#   (timescaledb.continuous)
i3247-# AS
i3247-# SELECT
i3247-#   time_bucket('300.0s',"time") AS "time",
i3247-#   count(distinct(runid)) AS "Distinct Run IDs"
i3247-# FROM data_table
i3247-# GROUP BY 1
i3247-# WITH NO DATA;
CREATE MATERIALIZED VIEW
Time: 32.210 ms
```

**Comment by arfathyahiya** [comment]
@svenklemm Trying to create CAgg

```sql
CREATE MATERIALIZED VIEW users_5m
with (timescaledb.continuous) AS
SELECT
	time_bucket('5 minutes', u."timestampUTC") AS bucket,
	COUNT(DISTINCT (user)) AS user_count

FROM users u
GROUP BY bucket
with no data;
```
Gives me  the following error
SQL Error [0A000]: ERROR: only immutable functions supported in continuous aggregate view
  Hint: Make sure all functions in the continuous aggregate definition have IMMUTABLE volatility. Note that functions or expressions may be IMMUTABLE for one data type, but STABLE or VOLATILE for another.

this is my timescaledb stats
![Image](https://github.com/user-attachments/assets/00526a14-08cb-40af-a4c1-75fcee7cbbfa)
