### ISSUE TITLE
Minor TimescaleDB upgrade in multi node setup

### ISSUE THREAD

**Issue by dratzke** [timescale/timescaledb#3254]
Hi,

I would like to do a minor upgrade from TimescaleDB 1.6.1 -> 1.7.5  with PostgreSQL 11 (PG11)  in a multi node (1 write node, 1 read node) setup.

Is it possible to run several nodes with same PG11 and different TimescaleDB extensions? I would like to perform a `rolling upgrade` procedure but I can't find any hints in the documentation that physical replications is supported between different nodes with same PG11 but different TimescaleDB extensions

Thanks and Regards

**Comment by nikkhils** [comment]
Hi @dratzke 

I do hope you have a staging/testing environment to test out the upgrade steps before moving on to production.

Can you please elaborate on 1 write node, 1 read node setup and physical replication used in your case?

In general, it's recommended to upgrade the data nodes first one by one. Once all the data nodes have been updated, then the access node should be updated last.
