### ISSUE TITLE
Unexpected behavior while installing timescaledb using windows zip installer

### ISSUE THREAD

**Issue by hydroleap-admin** [timescale/timescaledb#3276]
**Relevant system information:**
 - OS: Windows
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): none
 - Installation method: Windows ZIP installer

**Describe the bug**
postgresql-x64-13 service failed to start after adding in 'timescaledb' into shared_preload_libraries.

**To Reproduce**
1. Fresh installation of postgresql.
2. Under windows services, we can see that postgres is running as intended.
![image](https://user-images.githubusercontent.com/84163289/119473190-83849d00-bd7d-11eb-8502-23a5021fb797.png)
3. Next I install timescaldb and with timescaledb-tune.exe option enabled.
4. I restart postgresql. An error occured.
![image](https://user-images.githubusercontent.com/84163289/119473625-ed9d4200-bd7d-11eb-8ffa-1965d8729019.png)
5. If I remove 'timescaledb' from shared_preload_libraries, then postgresql can start again without any issues.

**Expected behavior**
I should be able to follow the installation guide in timescaledb and extend the database with TimescaleDB.

**Actual behavior**
An error that prevents postgresql from starting.

**Screenshots**
As shown above.

**Additional context**
I have the following prerequisites:
1. ![image](https://user-images.githubusercontent.com/84163289/119474201-7caa5a00-bd7e-11eb-9a1b-45ee3c2e1860.png)
2. running psql -V gives me psql (PostgreSQL) 13.3
3. running pg_config gives me
![image](https://user-images.githubusercontent.com/84163289/119474465-c3984f80-bd7e-11eb-82a9-6dbf656b1810.png)
4. I ran all installation with admin rights.

Any advice would be appreciated. Thank you.

**Comment by mfundul** [comment]
@hydroleap-admin I have reproduced the issue. It appears the timescaledb download link in the documentation is for PostgreSQL 12. Please try using https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-13_2.2.1-windows-amd64.zip and see if this fixes the issue for you.

**Comment by hydroleap-admin** [comment]
Hi yes the link is now working. Before this, I had downgraded to postgresql 12 to install timescaledb. Thank you for the prompt update!
