### ISSUE TITLE
Unable to segment_by other column than foreign key column

### ISSUE THREAD

**Issue by dthemg** [timescale/timescaledb#3280]
Hi

I am working with the following use case:
A large number of users that each have their own separate time series. Each measurement in the time series has been made with a device, that has some accompanying metadata.

To create a db for this, I did the following:
```
CREATE TABLE devices (
  id              VARCHAR     NOT NULL,
  brand           VARCHAR,
  model           VARCHAR,
  serial_number   VARCHAR,
  mac             VARCHAR,
  firmware        VARCHAR,
  UNIQUE (id),
  PRIMARY KEY (id)
);
CREATE TABLE measurements (
  time                                 TIMESTAMPTZ         NOT NULL,
  measurement_location   VARCHAR,
  measurement_value       DOUBLE PRECISION    NOT NULL,
  device_id,                        VARCHAR             NOT NULL,
  customer_id                    VARCHAR             NOT NULL,
  FOREIGN KEY (device_id) REFERENCES devices (id)
);
SELECT create_hypertable('measurements', 'time');
ALTER TABLE measurements SET (
  timescaledb.compress,
  timescaledb.compress_segmentby='customer_id'
);
```
I wanted to segment by the customer id - since all measurements for a user is what generally will be queried.

However, when I do this I get the following error:
`ERROR:  column "device_id" must be used for segmenting
DETAIL:  The foreign key constraint "measurements_device_id_fkey" cannot be enforced with the given compression configuration.`

Why is it that I must use the foreign key for my segmentation? Is there another better way to accomplish what I want to do here?

**Comment by mfundul** [comment]
You should check out the documentation [here](https://docs.timescale.com/api/latest/compression/). The relevant line is this:
```
Constraints are restricted to compression SEGMENTBY columns when applicable. Otherwise they are unsupported.
```
The problem here is that the foreign key is a constraint, and it can only be applied if it's restricted to a `SEGMENTBY` column. I am afraid there is no way to avoid including the `device_id` in the `SEGMENTBY` clause.
