### ISSUE TITLE
Cannot install older TimescaleDB versions in CentOS 8

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3281]
**Relevant system information:**
 - OS: CentOS Linux release 8.3.2011
 - postgres (PostgreSQL) 13.3
 - Timescale 2.2.0
 - Installation method: `dnf`

**Describe the bug**
When I try to install an older timescaleDB rpm package I get mismatched version of the loader and the installation fails.

**To Reproduce**
1. Add TimescaleDB's third party repository and PostgreSQL PGDG
2. Run `dnf install timescaledb-2-postgresql-13-2.2.0-0.el8`
3. See mismatched versions of packages:
```
[root@localhost ~]# dnf install timescaledb-2-postgresql-13-2.2.0-0.el8
timescale_timescaledb                                              226  B/s | 833  B     00:03    
timescale_timescaledb-source                                       316  B/s | 819  B     00:02    
Dependencies resolved.
===================================================================================================
 Package                              Arch     Version               Repository               Size
===================================================================================================
Installing:
 timescaledb-2-postgresql-13          x86_64   2.2.0-0.el8           timescale_timescaledb   445 k
Installing dependencies:
 postgresql13                         x86_64   13.3-2PGDG.rhel8      pgdg13                  1.5 M
 postgresql13-libs                    x86_64   13.3-2PGDG.rhel8      pgdg13                  413 k
 postgresql13-server                  x86_64   13.3-2PGDG.rhel8      pgdg13                  5.5 M
 timescaledb-2-loader-postgresql-13   x86_64   2.3.0-0.el8           timescale_timescaledb   121 k
 timescaledb-tools                    x86_64   0.11.0-0.el8          timescale_timescaledb   2.8 M

Transaction Summary
===================================================================================================
Install  6 Packages
```
4. Cannot install extension:
```
postgres=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  extension "timescaledb" has no installation script nor update path for version "2.3.0"
```
**Expected behavior**
Expect to be able to install older versions.

**Comment by mfundul** [comment]
Maybe has to do with this line?
https://github.com/timescale/release-build-scripts/blob/6f780a207292f277fe5858db0769e101eb133bbc/rpm/timescaledb.spec#L17

**Comment by svenklemm** [comment]
This is expected.  Even though you can install multiple versions you can only have 1 loader so the default version you install will be determined by the version of the loader package and the loader package has the file with the metadata about the extension including the version to install when it is not explicitly specified.

You can create specific version with following command:
```
create extension timescaledb version "2.1.0";
```
