### ISSUE TITLE
Cannot upgrade timescale with ALTER EXTENSION

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3286]
**Relevant system information:**
 - OS: CentOS Linux release 8.3.2011
 - postgres (PostgreSQL) 13.3
 - Timescale 2.2.0 `=>` Timescale 2.3.0
 - Installation method: `dnf`

**Describe the bug**
When I execute `ALTER EXTENSION timescaledb UPDATE TO "2.3.0";` it fails with:
```
postgres=# ALTER EXTENSION timescaledb UPDATE TO "2.3.0";
ERROR:  extension "timescaledb" version mismatch: shared library version 2.3.0; SQL version 2.2.0
CONTEXT:  parallel worker
```

**To Reproduce**
1. Create a dataset (I created 1 compressed hypertable, ~500M rows, ~10GB on disk)
2. Change `postgresql.conf` as such:
```
parallel_tuple_cost = 0.001
parallel_setup_cost = 1.0
force_parallel_mode = on
```
3. Restart the postgresql service
4. Execute `ALTER EXTENSION timescaledb UPDATE TO "2.3.0";`
5. See error

**Expected behavior**
Expected the upgrade to work.

**Additional context**
Setting `max_parallel_workers = 0` in `postgresql.conf` fixes the issue.
For some reason, parallel execution of the upgrade process itself seems to trigger this bug.

A possible workaround could maybe be to inject `SET max_parallel_workers = 0;` in the upgrade scripts. E.g. in this specific case adding it as the first line of the file `/usr/pgsql-13/share/extension/timescaledb--2.2.0--2.3.0.sql` fixes the issue.

**Comment by mjf** [comment]
I can verify that patching the `/usr/pgsql-13/share/extension/timescaledb--2.2.[01]--2.3.0.sql` files works and the extension get updated.
