### ISSUE TITLE
Better handling of partition placement when expanding cluster

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3287]
Currently, we set the number of partitions used equal to the number of data nodes, and increase the number of partitions when new data nodes are added. The downside of this approach is that we introduce a break between the new and old partition placement, reducing the ability to push down queries.

A better approach would be to support over-partitioning, so that we can move entire partitions when adding new nodes. For instance, we could overpartition by a factor of 3 by default, so with 2 data nodes, we'd have 6 partitions in total. Adding a new node means we can move an entire partition (or the most recent chunks in a partition) to the new node without breaking partition boundaries and still being able to push down queries.

**Comment by svenklemm** [comment]
multinode has been removed
