### ISSUE TITLE
Creating a separate schema for timescaledb

### ISSUE THREAD

**Issue by vjpr** [timescale/timescaledb#330]
There are a bunch of functions added to the public schema. I was wondering if its possible to do `CREATE EXTENSION timescaledb SCHEMA timescale` to have the functions added to that schema, and still be able to create hypertables in the `public` schema.

Related: https://github.com/timescale/timescaledb/issues/276

---

At the moment I get:

```sql
SELECT create_hypertable('public.foo', 'received_at') - function create_hypertable(unknown, unknown) does not exist
```

I have also tried running:

```sql
ALTER DATABASE my_database SET search_path = public,postgis,timescale
```

---

So this works - but haven't checked if the hypertable functionality works yet.

```sql
SELECT timescale.create_hypertable('foo', 'received_at')
```

**Comment by RobAtticus** [comment]
As far as I know (and just tested), `CREATE EXTENSION timescaledb SCHEMA timescale` should work just fine. You do have to then prefix it with `timescale.` for the function calls as you found out, but otherwise everything should work as expected. If it doesn't that's a bug.

**Comment by vjpr** [comment]
> You do have to then prefix it with timescale. for the function calls as you found out

You can use search paths...

```
ALTER DATABASE my_database SET search_path = public,postgis,timescale
```

**Comment by RobAtticus** [comment]
Sorry, forgot to mention that's true as well. Anyway, glad it worked for you :)

**Comment by Muyoo** [comment]
I've tons of data in the database in production, and now I have to change the extension schema in runtime to manage the function privileges. How can I change the extension schema please? I've tried 'ALTER EXTENSION SET SCHEMA', but I got the 'unsupported' message.

**Comment by gtors** [comment]
@Muyoo have you found a solution?
