### ISSUE TITLE
Documentation: function restore_timescaledb() does not exist

### ISSUE THREAD

**Issue by morukutsu** [timescale/timescaledb#331]
Hello,
I'm evaluating TimescaleDB and currently I'm testing the backup/restore features.
Following: http://docs.timescale.com/latest/using-timescaledb/backup, the basic restore code gives me an error:
`
CREATE DATABASE
ALTER DATABASE
CREATE EXTENSION
ERROR:  function restore_timescaledb() does not exist
LINE 1: SELECT restore_timescaledb();
`

It seems like the data has been restored correctly, though.
Looks like the "restore_timescaledb()" function have been deleted.

Are the docs up to date regarding backup and restore? 
Thanks!

**Comment by erimatnor** [comment]
Hi @morukutsu. This function was removed since it is no longer needed. But I guess a docs update is still in process. Sorry for the confusion. I will leave this issue open until docs have been updated.

**Comment by morukutsu** [comment]
I see, thanks for the quick reply!

**Comment by mfreed** [comment]
This change has been deployed to docs.  Thanks!

http://docs.timescale.com/latest/using-timescaledb/backup
