### ISSUE TITLE
Alter hypertable partitioning column

### ISSUE THREAD

**Issue by kartik-zc** [timescale/timescaledb#3318]
We have a table in production which has `created_at` and `reported_at` timestamp columns.
On this table, we have made hypertable 
```SELECT create_hypertable('events', 'created_at');```

We want to alter the `partitioning_column` such that we can use `reported_at` as new partitioning column.

Timescale db docs doesn't mention anything related to altering existing hypertable partitioning column.

Are there any plans in future to include such future? Also, for the time being, to suffice my teams requirement is there any way to acheive that? Or, I will have to go a long way of creating a duplicate table with same data and applying ```SELECT create_hypertable('events', 'reported_at');```

Please let me know if any futher details are required from my side.

**Comment by erimatnor** [comment]
You can add additional partitioning columns using [`add_dimension`](https://docs.timescale.com/api/latest/hypertable/add_dimension/#parallelizing-queries-across-multiple-data-nodes). But it currently doesn't work if you already have data in the hypertable as that would require rewriting all the date in the new partitioning scheme.

**Comment by erimatnor** [comment]
Closing since question answered with pointer to documentation. If, for some reason, this didn't answer the request, feel free to reopen.
