### ISSUE TITLE
Real-Time Aggregation: ERROR: cannot create continuous aggregate with CREATE VIEW

### ISSUE THREAD

**Issue by sharpkids** [timescale/timescaledb#3319]
**Relevant system information:**
- OS: Ubuntu 20.04
- PostgreSQL 12.7
- TimescaleDB 2.2.0
- Installation method: apt install

**Describe the bug**
Following the following blog post (https://blog.timescale.com/blog/achieving-the-best-of-both-worlds-ensuring-up-to-date-results-with-real-time-aggregation/, I am receiving this error while trying to create view cpu_1h using "CREATE VIEW cpu_1h..." command. I tried searching for this error and was unable to find any information except actual source code (https://github.com/timescale/timescaledb/blob/master/src/process_utility.c). Just looking for some direction here as real-time aggregation obviously works for other people.

**To Reproduce**
1. Follow the steps in the blog post to create table, hypertable and populate table with data
2. Create cpu_1h view 

**Expected behavior**
Command "CREATE VIEW cpu_1h..."  executed successfully

**Actual behavior**
Receiving error:
ERROR: cannot create continuous aggregate with CREATE VIEW
Hint: Use CREATE MATERIALIZED VIEW to create a continuous aggregate

**Comment by Rotario** [comment]
I think continuous aggregates only work with MATERIALIZED VIEWs I'm afraid, have you tried changing the SQL command to 
```
CREATE MATERIALIZED VIEW cpu_1h 
   WITH (timescaledb.continuous, 
         timescaledb.refresh_lag = '30m',
         timescaledb.refresh_interval = '30m')
   AS
      SELECT 
         time_bucket('1 hour', time) AS hour,
         hostname, 
         histogram(usage_user, 0.0, 1.0, 5) AS hist_usage_user,
         histogram(usage_system, 0.0, 1.0, 5) AS hist_usage_system,
         histogram(usage_iowait, 0.0, 1.0, 5) AS hist_usage_iowait
      FROM cpu
      GROUP BY hour, hostname;
```

**Comment by gayyappan** [comment]
We modified the apis for continuous aggregates in Timescaledb 2.0. 
The current syntax is ` CREATE MATERIALIZED VIEW ...`

https://docs.timescale.com/timescaledb/latest/getting-started/create-cagg/#step-define-view
