### ISSUE TITLE
Insert into compressed chunk with primary key fails

### ISSUE THREAD

**Issue by frans-vanbree** [timescale/timescaledb#3323]
**Relevant system information:**
 - OS: Ubuntu 18.04.5 LTS
 - PostgreSQL version (output of `postgres --version`): PostgreSQL 12.6 (Ubuntu 12.6-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.0
 - Installation method: [e.g., "using Docker", "apt install", "source"]: AMI for 2.2.0, then upgraded to 2.3.0 using APT

**Describe the bug**
Inserting a record into a chunk that has been compressed fails:

ERROR:  insert into a compressed chunk that has primary or unique constraint is not supported
SQL state: 0A000

This should be possible with v2.3.0. See #3230. 

Also primary keys are not a restriction according to:
https://docs.timescale.com/api/latest/compression/#restrictions

Note the table has a primary key (consisting of three fields), an (autogenerated?) index on the Date field and no foreign keys:

![image](https://user-images.githubusercontent.com/71381647/121524160-4fed7800-c9f7-11eb-835f-240093b4de39.png)

Concrete statement:

insert into hm.event (eventconfig_id, eventproperty_id, date, value, value_f, insert_id)
select * from hm.event where date between '2019-04-14 00:00:00+00' and '2020-04-08 00:00:00+00'
limit 1;

It should have been inserted in chunk "_hyper_6_799_chunk":

![image](https://user-images.githubusercontent.com/71381647/121523834-f127fe80-c9f6-11eb-845d-7ec97046d256.png)

**Expected behavior**
The new record should have been inserted without error

**Actual behavior**
An exception was thrown

**Comment by gayyappan** [comment]
We do not support inserts on compressed chunks that have unique constraints or primary key constraints yet. Looks like this information is missing in this doc link.
It is on our road map, but not yet supported.

**Comment by andnig** [comment]
Do you have a workaround for this missing feature at the moment? 
We would need a unique constraint at least on all uncompressed chunks of a compression-enabled table, but could live without the constraint on compressed chunks. Is it possible to remove constraints on compressed chunks but keep them on uncompressed ones?

**Comment by finckalp** [comment]
Any news on that ? This is quite a large-issue because it basically means that as soon as the compression delay is reached ('compress_after'), **any table with constraint is forced to become read-only** because all INSERTS fail. Sure the decompress -> write -> re-compress works for manual back-filling but for example for IoT with devices disconnected from the network for a long time and internal memory, it doesn't...

I think @andnig solution would be a really large step towards fixing this issue and maybe easier than full constraints support.

**Comment by wiebeytec** [comment]
I don't know if I'm speaking for people, but we've been in contact with Timescaledb engineers about `ON CONFLICT DO NOTHING` and there is progress. I imagine that touches this ticket as well.

**Comment by svenklemm** [comment]
This should work since at least version 2.10.0. Please reopen if it doesnt work in recent versions.

**Comment by SystemParadox** [comment]
Sorry my mistake. However, without `ON CONFLICT`:

```
ERROR: insert into a compressed chunk that has primary or unique constraint is not supported
```

**Comment by svenklemm** [comment]
Oh i was wrong about this being in 2.10.0. 2.10.0 did some refactoring but did not remove the restrictions on constraints. This will be in 2.11. You can try in nightly docker image: timescaledev/timescaledb:nightly-pg15
