### ISSUE TITLE
What chunk Interval should I use?

### ISSUE THREAD

**Issue by 120bits** [timescale/timescaledb#3328]
Hi,

I have 24 Million rows written every hour. I have been playing with different chunk policy. I had it 24 hours. I want to keep the data retention for 2 days. I switched to  6 hours. I'm running timescaledb on a EC2 instance, m5.2xlarge. 

One other reason is the drop_chunk takes long time to delete the chunks. Every midnight I have cronjob that deletes anything older than 36 hours. It takes long time to delete older chunks.

I need to know what chunk interval should I use in this case. And what should be the drop chunk interval should be?

Thanks,

**Comment by gayyappan** [comment]
drop_chunk should be a quick operation. I suspect some activity on the chunk is blocking drop_chunk operation. Have you checked lock activity when drop_chunks is executed?

**Comment by 120bits** [comment]
I'm looked at the activities, I see when I run the drop_chunk operation. It says "Lock: relation"

**Comment by NunoFilipeSantos** [comment]
Hi @120bits! Can you please move this question to our community Slack? Thank you. 👍
