### ISSUE TITLE
Cannot drop a continuous aggregate materialized view

### ISSUE THREAD

**Issue by mccarthysean** [timescale/timescaledb#3353]
**Relevant system information:**
 - OS: Alpine 10.2.1_pre1 "timescale/timescaledb:2.3.0-pg13" Docker image
 - PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
 - TimescaleDB version 2.3.0
 - Installation method: using Docker

**Describe the bug**
I'm trying to drop a continuous aggregate materialized view with the following:
```sql
DROP MATERIALIZED VIEW IF EXISTS time_series_mv_24_hour_interval;
ERROR:  trigger "ts_cagg_invalidation_trigger" for table "time_series" does not exist
```

How I successfully created the table in the beginning:
```sql
create materialized view public.time_series_mv_24_hour_interval
WITH (timescaledb.continuous) AS 
	SELECT time_bucket('24 hour', timestamp_utc) as timestamp_utc, 
            gateway, 
            avg(dgp) as dgp
	FROM time_series
	group by 
            time_bucket('24 hour', timestamp_utc),
            gateway
;
```

In addition (a second bug), I'm trying to create a new, similar materialized view with a different time window, and it's failing as well:
```sql
create materialized view public.time_series_mv_2_hour_interval
WITH (timescaledb.continuous) AS 
	SELECT time_bucket('2 hour', timestamp_utc) as timestamp_utc, 
            gateway, 
            avg(dgp) as dgp
	FROM time_series
	group by 
            time_bucket('2 hour', timestamp_utc),
            gateway
;

ERROR:  trigger "ts_cagg_invalidation_trigger" for relation "_hyper_29_553_chunk" already exists
SQL state: 42710
```

**Additional context**
I recently created a backup with `ts-dump` on PostgreSQL v11 (with TimescaleDB v2.3.0) and restored it on PostgreSQL v13 with `ts-restore`.

**Comment by mccarthysean** [comment]
How can I just remove all my continuous aggregate materialized views, along with any "triggers" and hypertables, so I can kind of "start fresh"? I think my main tables/hypertables are fine. I'd just like to drop all my views and materialized views...

**Comment by mccarthysean** [comment]
FYI, I solved the problem by copying, then drop-cascading the underlying table, which removed the dependent continuously-aggregating materialized view. Then I renamed the copied table and rebuilt the continuously-aggregating materialized view. 

This didn't fix the TimescaleDB bug, but it did solve my problem, I think.

**Comment by lukeramsden** [comment]
I use [graphile-migrate](https://github.com/graphile/migrate), which means during my initial development phase, my migrations do a lot of cascade deletes. I'm also having trouble with Caggs not being dropped properly when I drop my hypertables with `CASCADE`:

```
error: cannot drop the partial/direct view because it is required by a continuous aggregate
```

Not sure what's causing this. My solution is to drop all my Caggs _first_, right at the start of my migrations, and then hypertables are dropped later on.

**Comment by mfundul** [comment]
Is dumping from PostgreSQL v11 and restoring to PostgreSQL v13 supported?

**Comment by afiskon** [comment]
> I recently created a backup with ts-dump on PostgreSQL v11 (with TimescaleDB v2.3.0) and restored it on PostgreSQL v13 with ts-restore.
@mccarthysean sorry it took us long to figure out what's going on.

This looks like a bug in ts-dump / ts-restore, and as @mfundul noticed we are not even sure if it supports such backuping-restoring. Please note that timescale/timescaledb repository corresponds to the TimescaleDB core (i.e. only the extension). We do test the compatibility with standard PostgreSQL tools, however the team doesn't support timescale/timescaledb-backup and has next to no knowledge of this tool.

If you still have this problem, please re-open an issue in https://github.com/timescale/timescaledb-backup
