### ISSUE TITLE
Increase query with time bucketing throws an error

### ISSUE THREAD

**Issue by olebowle** [timescale/timescaledb#3359]
**Relevant system information:**
 - OS: CentOS 7.9.2009
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.0
 - Installation method: [yum Installation](https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/#yum-installation)

**Describe the bug**
Trying to use the [advanced analytic-query Increase](https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/advanced-analytic-queries/#increase) for a counter (e.g. `in_octet`) with time bucketing leads to the error:
`multiple window function calls per column not supported`.

AFAIC there are not really multiple window functions (I think `last(in_octets, 1)` is fine here) called. It's the same function stated multiple times. I tried working around using `WITH` statement, but didn't get far. Workarounds appreciated!

**To Reproduce**
```sql
-- OK
SELECT
time_bucket_gapfill('5m', time) AS time,
last(in_octets, 1) - lag(last(in_octets, 1)) OVER w AS "Inbound"
FROM modems
WHERE time BETWEEN '2021-06-23T00:00:00.000Z' AND '2021-06-24T00:00:00.000Z' AND external_id = 100047
GROUP BY 1
WINDOW w AS (ORDER BY 1);

-- OK
SELECT
time_bucket_gapfill('5m', time) AS time,
last(in_octets, 1) - lag(last(in_octets, 1)) OVER (ORDER BY 1) AS "Inbound"
FROM modems
WHERE time BETWEEN '2021-06-23T00:00:00.000Z' AND '2021-06-24T00:00:00.000Z' AND external_id = 100047
GROUP BY 1;


-- see: https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/advanced-analytic-queries/#increase
-- ERROR: multiple window function calls per column not supported
SELECT
time_bucket_gapfill('5m', time) AS time,
(CASE WHEN last(in_octets, 1) >= lag(last(in_octets, 1)) OVER w THEN last(in_octets, 1) - lag(last(in_octets, 1)) OVER w WHEN lag(last(in_octets, 1)) OVER w IS NULL THEN NULL ELSE last(in_octets, 1) END) AS "Inbound"
FROM modems
WHERE time BETWEEN '2021-06-23T00:00:00.000Z' AND '2021-06-24T00:00:00.000Z' AND external_id = 100047
GROUP BY 1
WINDOW w AS (ORDER BY 1);

-- ERROR: multiple window function calls per column not supported
SELECT
time_bucket_gapfill('5m', time) AS time,
(CASE WHEN last(in_octets, 1) >= lag(last(in_octets, 1)) OVER (ORDER BY 1) THEN last(in_octets, 1) - lag(last(in_octets, 1)) OVER (ORDER BY 1) WHEN lag(last(in_octets, 1)) OVER (ORDER BY 1) IS NULL THEN NULL ELSE last(in_octets, 1) END) AS "Inbound"
FROM modems
WHERE time BETWEEN '2021-06-23T00:00:00.000Z' AND '2021-06-24T00:00:00.000Z' AND external_id = 100047
GROUP BY 1;
```

**Expected behavior**
All queries should be executed without an error.

**Actual behavior**
The last two queries lead to the error `multiple window function calls per column not supported` even though it's the same window function just stated multiple times.

**Comment by erimatnor** [comment]
Isn't the issue that you are using `last()` and `lag()` in the same window?

**Comment by olebowle** [comment]
Am I not supposed to do that? I mean in the first two examples I also use both `last()` and `lag()` and didn't throw an error. AFAIK if I want to use `time_bucket_gapfill` I need an aggregation function (in this case `last()`). But I also need the prior value (i.e.`lag()`) to do a subtraction, since `in_octet` is a monotonic counter. As I mentioned if there is a better way of doing the increase query with time bucketing I'm glad to try it.

**Comment by olebowle** [comment]
Ok, I think I got it working using the `WITH` statement:
```sql
WITH data AS (
  SELECT time_bucket_gapfill('5m', time) AS time,
    last(in_octets, 1) AS cur,
    lag(last(in_octets, 1)) OVER (ORDER BY 1) AS prev
  FROM modems
  WHERE time BETWEEN '2021-06-23T00:00:00.000Z' AND '2021-06-24T00:00:00.000Z' AND external_id = 100047
  GROUP BY 1
) SELECT time, (CASE WHEN cur >= prev THEN cur - prev WHEN prev IS NULL THEN NULL ELSE cur END) AS "Inbound" FROM data;
```

**Comment by akuzm** [comment]
Good that we have a workaround. I have no idea why we can't have an arbitrary number of window functions above the gapfill. @svenklemm maybe you know this? Should we close this issue and recommend the workaround, or can we enhance this?

**Comment by svenklemm** [comment]
We will get this for free with PG15 cause PG won't push targetlist changes into customnodes anymore unless explicitly enabled.  We can surely enhance this, also the limit is not on the number of window functions but on the number of window functions per targetlist column. The reason is postgres pushing targetlist changes in our node after the node is initialized which will conflict with our constructed targetlist.  We try to adjust targetlist after the fact but the code is not prepared to handle targetlist expression splitting which is what would be needed to handle these cases correctly. But since we get this for free with PG15 enhancing this might not be time well spent.

https://github.com/postgres/postgres/commit/955b3e0f

**Comment by nikkhils** [comment]
Closing this as per Sven's comment (that we will get it for free in PG15).
