### ISSUE TITLE
Crashes consistently on Arm 32 bit architecture when inserting into hypertable. 

### ISSUE THREAD

**Issue by vegabook** [timescale/timescaledb#336]
I have just downloaded version 0.7 under Armbian (Debian-stretch based) for a CubieTruck board. I installed Postgres 9.6 off the repos on a virgin Armbian re-install. Machine is clean as a whistle. 

Compiled timescaledb 0.7 after downloading the tarball. 

Followed instructions in the tutorial rigorously, three times. Each time, same thing - crashes the server. 

```
nvidia@tegra-ubuntu:~$ ssh tbrowne@192.168.1.192
tbrowne@192.168.1.192's password: 
  ____      _     _      _                   _    
 / ___|   _| |__ (_) ___| |_ _ __ _   _  ___| | __
| |  | | | | '_ \| |/ _ \ __| '__| | | |/ __| |/ /
| |__| |_| | |_) | |  __/ |_| |  | |_| | (__|   < 
 \____\__,_|_.__/|_|\___|\__|_|   \__,_|\___|_|\_\
                                                  

Welcome to ARMBIAN 5.35 user-built Debian GNU/Linux 9 (stretch) 4.13.16-sunxi   
System load:   1.03 0.38 0.14  	Up time:       1 min		
Memory usage:  2 % of 2011MB 	IP:            192.168.1.192
CPU temp:      38°C           	
Usage of /:    1% of 112G   	

[ General system configuration (beta): armbian-config ]

Last login: Tue Nov 28 22:51:51 2017 from 192.168.1.101

tbrowne@cubietruck:~$ psql
psql (9.6.6)
Type "help" for help.

tbrowne=# drop database tutorial;
ERROR:  database "tutorial" does not exist
tbrowne=# create database tutorial;
CREATE DATABASE
tbrowne=# \c tutorial
You are now connected to database "tutorial" as user "tbrowne".
tutorial=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE EXTENSION
tutorial=# CREATE TABLE conditions (
tutorial(#   time        TIMESTAMPTZ       NOT NULL,
tutorial(#   location    TEXT              NOT NULL,
tutorial(#   temperature DOUBLE PRECISION  NULL,
tutorial(#   humidity    DOUBLE PRECISION  NULL
tutorial(# );
CREATE TABLE
tutorial=# 
tutorial=# SELECT create_hypertable('conditions', 'time');
 create_hypertable 
-------------------
 
(1 row)

tutorial=# INSERT INTO conditions(time, location, temperature, humidity)
tutorial-#   VALUES (NOW(), 'office', 70.0, 50.0);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

I'm sure you're not targeting arm32 architecture but I thought at least it should work on this little device? Maybe lots of IoT use cases for timeseries data? Happy to put up an account for you if you want to ssh into the Cubie and try it out for yourself. 

Personally will be targeting much bigger boxes but I like doing dev work on these weak CPUs because I get a much better idea of relative performance.

**Comment by vegabook** [comment]
Just so you can see the server is fine outside of timescale insert:

```
tbrowne@cubietruck:~$ sudo service postgresql restart
[sudo] password for tbrowne: 
tbrowne@cubietruck:~$ psql
psql (9.6.6)
Type "help" for help.

tbrowne=# \c tutorial;
You are now connected to database "tutorial" as user "tbrowne".
tutorial=# create table test (field1 varchar(10), field2 float);
CREATE TABLE
tutorial=# insert into test values("sensor", 3.14);
ERROR:  column "sensor" does not exist
LINE 1: insert into test values("sensor", 3.14);
                                ^
tutorial=# insert into test values('sensor', 3.14);
INSERT 0 1
tutorial=# select * from test;
 field1 | field2 
--------+--------
 sensor |   3.14
(1 row)

tutorial=# 
```

**Comment by jbrain** [comment]
I've been running into this same issue on Rasbian 9(Stretch) + Postgresql 9.6.6. Compiling from source, make log below.

No warnings or errors are logged and no crash is indicated but the initial hypertable-chunk child table is not created on ARM64, below I've attached the debug output of the create_hypertable() step. Using the same instructions I am able to successfully compile, install and create the demo tables + hypertables on AMD64/Fedora 26 so I'm fairly certain the procedure is correct.

`Linux 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux`
`PostgreSQL 9.6.6 on armv8l-unknown-linux-gnueabihf`

makefile:
[CMakeOutput.log](https://github.com/timescale/timescaledb/files/1515023/CMakeOutput.log)
postgresql log output "SELECT create_hypertable(...)" (debug5):
[postgresql.log](https://github.com/timescale/timescaledb/files/1515080/postgresql.log)

**Comment by vegabook** [comment]
Original bug report was on a BTRFS file system on the Cubie. Can confirm that bug exists on ext4 too - identical behaviour.

**Comment by cevian** [comment]
@vegabook Happy to look into this for you. Can you email me the login info for Cubie: mat@timescale.com  Thanks!

**Comment by RobAtticus** [comment]
Hey @vegabook I edited your post to remove the sensitive info. No guarantee that some botnet hasn't already logged in though. :(
