### ISSUE TITLE
SkipScan not being used by the query planner

### ISSUE THREAD

**Issue by mschwore** [timescale/timescaledb#3374]
**Relevant system information:**
 - OS: CentOS 7.9.2009
 - PostgreSQL version (output of `postgres --version`): 12.7
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.1
 - Installation method: yum install

**Describe the bug**
The planner is not using SkipScan. I used the devices_small dataset from the tutorials and the following query:

```
SELECT DISTINCT ON (device_id) * FROM readings ORDER BY device_id, time desc
```

Here's the explain output from the query
```
explain SELECT DISTINCT ON (device_id) * FROM readings ORDER BY device_id, time desc;
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=0.42..49930.60 rows=200 width=122)
   ->  Index Scan using _hyper_1_1_chunk_readings_device_id_time_idx on _hyper_1_1_chunk  (cost=0.42..47430.60 rows=1000000 width=122)
(2 rows)
```

And the definition of the table from the tutorial dataset. The device_id column is a text column which I don't think matters.
```
\d readings
                             Table "public.readings"
       Column        |           Type           | Collation | Nullable | Default 
---------------------+--------------------------+-----------+----------+---------
 time                | timestamp with time zone |           | not null | 
 device_id           | text                     |           |          | 
 battery_level       | double precision         |           |          | 
 battery_status      | text                     |           |          | 
 battery_temperature | double precision         |           |          | 
 bssid               | text                     |           |          | 
 cpu_avg_1min        | double precision         |           |          | 
 cpu_avg_5min        | double precision         |           |          | 
 cpu_avg_15min       | double precision         |           |          | 
 mem_free            | double precision         |           |          | 
 mem_used            | double precision         |           |          | 
 rssi                | double precision         |           |          | 
 ssid                | text                     |           |          | 
Indexes:
    "readings_device_id_time_idx" btree (device_id, "time" DESC)
    "readings_time_idx" btree ("time" DESC)
```

**Expected behavior**
The SkipScan plan should be used.

**Actual behavior**
The planner uses an Index Scan.

**Comment by NunoFilipeSantos** [comment]
@svenklemm can you please have a look?

**Comment by jameswinegar** [comment]
Not sure why this is labeled `need-more-info`, but I'd expect a skip scan to be used when there is an index on the column on interest only, and not coupled with `time`.  Your `readings_device_id_time_idx` index has a lot of data in it while having an index on just `device_id` would be much more efficient to search through.

**Comment by svenklemm** [comment]
I dont see anything wrong with the example and I was not able to reproduce. Since SkipScan may not be chosen depending on cost did you run ANALYZE?
Can you post a self-contained minimal example to reproduce the issue in a clean database?

**Comment by svenklemm** [comment]
```
create table readings(time timestamptz, device_id text, battery_level float);
select create_hypertable('readings','time');
create index ON readings (device_id,time desc);

insert into readings select '2000-01-01',1,random() from generate_series(1,1000);
analyze readings;
explain select distinct ON (device_id) * from readings ORDER BY device_id, time desc;
```
```
                                                               QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=0.15..0.19 rows=1 width=18)
   ->  Custom Scan (SkipScan) on _hyper_37_4_chunk  (cost=0.15..0.19 rows=1 width=18)
         ->  Index Scan using _hyper_37_4_chunk_readings_device_id_time_idx on _hyper_37_4_chunk  (cost=0.15..41.02 rows=1000 width=18)
(3 rows)
```

**Comment by mschwore** [comment]
Hi @svenklemm 

I tried your example from your last comment and did not see skipscan work either. This is starting to feel like I've made some sort of setup problem. I also upgraded to timescaledb 2.3.1 since I submitted this issue.

`psql -U postgres
Password for user postgres: 
psql (12.7)
Type "help" for help.

postgres=# create database skipscan;
CREATE DATABASE
postgres=# \c skipscan
You are now connected to database "skipscan" as user "postgres".
skipscan=# create table readings(time timestamptz, device_id text, battery_level float);
CREATE TABLE
skipscan=# create extension timescaledb;
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.3.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

CREATE EXTENSION
skipscan=# select create_hypertable('readings','time');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
   create_hypertable   
-----------------------
 (1,public,readings,t)
(1 row)

skipscan=# create index on readings(device_id,time desc);
CREATE INDEX
skipscan=# insert into readings select '2000-01-01',1,random() from generate_series(1,1000);
INSERT 0 1000
skipscan=# analyze readings;
ANALYZE
skipscan=# explain select distinct on (device_id) * from readings order by device_id, time desc;
                                                           QUERY PLAN                                                           
--------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=0.28..31.74 rows=1 width=18)
   ->  Index Scan using _hyper_1_1_chunk_readings_device_id_time_idx on _hyper_1_1_chunk  (cost=0.28..29.24 rows=1000 width=18)
(2 rows)
`

Here's the RPMs I have installed on my machine:

`rpm -qa | grep -ni postgres
198:timescaledb-2-oss-postgresql-12-2.3.1-0.el7.x86_64
593:postgresql12-libs-12.7-1PGDG.rhel7.x86_64
739:postgresql12-contrib-12.7-1PGDG.rhel7.x86_64
761:timescaledb-2-loader-postgresql-12-2.3.1-0.el7.x86_64
885:postgresql12-server-12.7-1PGDG.rhel7.x86_64
1632:postgresql12-12.7-1PGDG.rhel7.x86_64
1720:postgresql-jdbc-9.2.1002-8.el7_8.noarch`

**Comment by mschwore** [comment]
Alright, my problem was I was using the "oss"/Apache license version of timescale. I moved to the TSL version and skipscan works as expected. 

I admit I did not put much care into which version to download and play with!
