### ISSUE TITLE
Continuous aggregates refresh policy at time aligned by schedule_interval?

### ISSUE THREAD

**Issue by WuBingzheng** [timescale/timescaledb#3375]
In my scenes, the metrics are inserted into DB in-time-order strictly, and I want merge them daily by continuous aggregate, and execute by an automation policy. I think this is very common.

I want the policy to be executed at the very beginning of every day, to merge last day's data. However I find that the policy execution time is not aligned by schedule_interval (the 3rd argument of add_continuous_aggregate_policy). And the time changes because of the execution cost time.

So if I want to merge the data as soon as possible (at the beginning per day), the `schedule_interval` can not be set to `1 day`. But if set to `1 minute`, then the policy will be executed for 24*60 times per day, while only 1 time is necessary.

What's the best practice for this?

Should I merge the data manual by `CALL refresh_continuous_aggregate` daily (e.g. crontab job)?

Thanks,
Wu

**Comment by erimatnor** [comment]
@WuBingzheng Unfortunately, it is not possible to run a job at a specific CRON-like schedule. This is a current limitation of our background scheduling framework. You might be able to do that with an external scheduling process however, like a CRON job.

You can, of course, execute the policy more frequently as you suggest. This will wast a bit of resources, but note that the continuous aggregate refresh won't actually do anything if it is already up-to-date in the area you are refreshing. So, refreshing an up-to-date area is cheap.

**Comment by erimatnor** [comment]
https://github.com/timescale/timescaledb/issues/2966
