### ISSUE TITLE
Size of the chunks increase without being decompressed if decompress_chunk(i) fails in middle 

### ISSUE THREAD

**Issue by hardikm10** [timescale/timescaledb#3376]
**Relevant system information:**
OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: Docker / timescale/timescaledb:2.3.0-pg12
 - PostgreSQL version (output of `postgres --version`): 12.7
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.0
 - Installation method: [e.g., "using Docker", "apt install", "source"] :  "Using Docker"

**Describe the bug**
If `select decompress_chunk(i) FROM show_chunks('<hypertable>') i` fails in the middle because there was 'a chunk' which was already decompressed, the chunks on which it has acted upon (before the failure) still shows as compressed (which is expected) but their size increases somehow( which isn't expected).  Upon repeated execution of the above failing command, the size increase continuously with the status still remain as 'compressed'

**To Reproduce**
```
drop table sensor_data;

create table sensor_data( 
time timestamptz not null, 
sensor_id integer not null, 
cpu double precision null,
temperature double precision null );

select from create_hypertable('sensor_data','time');

INSERT INTO sensor_data
	SELECT
		time + (INTERVAL '1 minute' * random()) AS time,
		sensor_id,
		random() AS cpu,
		random()* 100 AS temperature
	FROM
		generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '1 minute') AS g1(time),
		generate_series(1, 100, 1 ) AS g2(sensor_id)
	ORDER BY
		time;
```
```
SELECT *,pg_size_pretty(total_bytes) FROM chunks_detailed_size('sensor_data');
     SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data');
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 51 MB
 _hyper_1_2_chunk | 97 MB
 _hyper_1_3_chunk | 97 MB
 _hyper_1_4_chunk | 87 MB
 ```
```
alter table sensor_data set (timescaledb.compress, 
timescaledb.compress_orderby = 'time DESC');

defaultdb=> select compress_chunk(i) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;                   
------------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
 _timescaledb_internal._hyper_1_2_chunk
 _timescaledb_internal._hyper_1_3_chunk
(3 rows)

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 11 MB
 _hyper_1_2_chunk | 20 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```
```
select decompress_chunk('_timescaledb_internal._hyper_1_2_chunk');
            decompress_chunk
----------------------------------------
 _timescaledb_internal._hyper_1_2_chunk

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 11 MB
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```
```
select decompress_chunk(i) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;
ERROR:  chunk "_hyper_1_2_chunk" is not compressed

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 41 MB <== notice here that the size is increased
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)

select chunk_name,is_compressed from timescaledb_information.chunks;
    chunk_name    | is_compressed
------------------+---------------
 _hyper_1_1_chunk | t <== the status is still shown as compressed.
 _hyper_1_2_chunk | f
 _hyper_1_3_chunk | t
 _hyper_1_4_chunk | f
(4 rows)
```
Also if it's repeated, the chunk size increases again. Ex:
```
SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 72 MB <== the size increased again, and status is still 't' in metadata
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```

**Expected behavior**
If the idea is to fail the complete transaction, the size of the chunks before failure should not increase. 

**Actual behavior**
Size of the chunks before the command fails increases and is repeatable

**Comment by erimatnor** [comment]
@hardikm10 did you check whether a full vacuum would reclaim this disk space?

**Comment by hardikm10** [comment]
@erimatnor yes, `vacuum full <hypertable>` doesn't reclaims the disk space.

**Comment by gayyappan** [comment]
@hardikm10  What is the output for

 ``` select count(*) from _timescaledb_internal._hyper_1_1_chunk ? ```

```select * from _timescaledb_catalog.chunk where id = 1 ```

**Comment by hardikm10** [comment]
```
select count(*) from _timescaledb_internal._hyper_1_1_chunk;
 count
-------
     0
```
```
select * from _timescaledb_catalog.chunk where id = 1;
 id | hypertable_id |      schema_name      |    table_name    | compressed_chunk_id | dropped | status
----+---------------+-----------------------+------------------+---------------------+---------+--------
  1 |             1 | _timescaledb_internal | _hyper_1_1_chunk |                   5 | f       |      1
(1 row)
```

**Comment by sb230132** [comment]
Hi hardikm10,
Thanks for reproducible testcase. Iam able to reproduce the issue.
In short the issue is, decompress_chunk() does following in same order:
for each chunk returned by show_chunk:
   1. decompresses the compressed chunk in this case its '_hyper_1_1_chunk'.
   2. Remove entry from _timescaledb_catalog.compression_chunk_size.
   3. Update status of is_compressed flag to false in timescaledb_information.chunks.
   4. Drop the chunk.
 
On 2nd call to decompress_chunk, a non compressed chunk is passed, which causes decompress_chunk to fail. However, postgres, seems to undo changes done in timescaledb catalog tables, leaving the previously decompressed chunk ('_hyper_1_1_chunk') as is. Thus each time below query is executed,
select decompress_chunk(i) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;
timescaledb decompressed 1st chunk '_hyper_1_1_chunk' and fails for next chunk, thus increasing the chunk size each time.

Will come up with a solution sooner.

**Comment by sb230132** [comment]
Here is a workaround:
select decompress_chunk(i, if_compressed => TRUE) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;

**Comment by sb230132** [comment]
We can observe a similar issue on vanilla postgres without having timescaledb extension.

Create a table with UNIQUE CONSTRAINT
```
test=# create table sensor_data(
test(#   time timestamptz not null,
test(#   sensor_id integer not null,
test(#   cpu double precision null,
test(#   temperature double precision null,
test(#   UNIQUE(time)
test(# );
CREATE TABLE
test=# 
```

Now check size of table

```
test=# select pg_relation_size('sensor_data');
 pg_relation_size 
------------------
                0
(1 row)
```

Insert into table with UNIQUE CONSTRAINT violation
```
test=# 
test=# INSERT INTO sensor_data SELECT time + (INTERVAL '1 minute' * random()) AS time, sensor_id, random() AS cpu, random()* 100 AS temperature
test-#     FROM generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '1 minute') AS g1(time), generate_series(1, 100, 1 ) AS g2(sensor_id) ORDER BY time;

ERROR:  duplicate key value violates unique constraint "sensor_data_time_key"
DETAIL:  Key ("time")=(2022-08-18 06:16:30.900106+05:30) already exists.
test=# 
```

Table has 0 records.
```
test=# select count(*) from sensor_data;
 count 
-------
     0
(1 row)
```

Check table size:
```
test=# select pg_relation_size('sensor_data');
 pg_relation_size 
------------------
        100900864
(1 row)
```

Run VACUUM to clean up dead tuples
```
test=# vacuum "sensor_data";
VACUUM
```

Check size of table.
```
test=# select pg_relation_size('sensor_data');
 pg_relation_size 
------------------
                0
(1 row)
```
VACUUM process gets triggered automatically for postgresql tables, but not for compressed hypertable. However in this duration if user queries for table size, postgres reports a wrong value.

Coming to original PR issue: Decompression of chunk produces lot of dead tuples, which is not cleaned up. And thus when we query size of compressed chunks, we see increase in size.

A similar issue #4578 will fix the cleanup of dead tuples which is the cause of increase in size of  chunk which is not even decompressed.
To avoid these type of problems, user should use the 2nd parameter in decompress_chunk().
