### ISSUE TITLE
continuous aggregate works at current time bucket?

### ISSUE THREAD

**Issue by WuBingzheng** [timescale/timescaledb#3378]
In my scene, there are many (about 100K per day) metric points every day. They are inserted in-time-order strictly.
I want to merge them daily. Meanwhile there are frequent queries for the last 30 days data as well as today's real-time data.

From your document it seems that continuous aggregate can NOT be executed on the current time bucket, which will disable querying current bucket's real-time data.

For example, now it's 23:00, then to response the query, timescaleDB must query last-30-days-merged-data AND merge today's-raw-data in realtime which is about 100K points. This is very slow, and this is also a waste because it merge almost the same data for a day for every queries.

So here is my proposal, can timescaleDB allow to merge current time bucket's data, with raw-data real-time query still enabled. Then I can merge today's data every minute. For example, now it's 23:00, I have merged today's data between 00:00-23:00. For the queries happening at 23:00:12, timescaleDB query last-30-days-merged-data, AND today's-23-hours-merged-data, AND 12-seconds-raw-data.

Influxdb works like this.

Thanks,
Wu

**Comment by erimatnor** [comment]
I am not sure I fully understand your questions, but this applies to continuous aggregates:

* You can materialize any buckets you wish in a continuous aggregate. 
* A refresh will only materialize whole buckets covered by the refresh window (i.e., you cannot refresh half a bucket).
* Real-time aggregation  (if enabled) will union materialized buckets with buckets computed from raw data in real time


The example you provide seems possible under these limitations. You'd have to continuously refresh your continuous aggregate to ensure that a full bucket is materialized as soon as possible after a new bucket is "opened". The only issue is that your daily buckets must align with the start and end of the day in your time zone. Unfortunately, however, `time_bucket` currently only supports bucketing in the UTC time zone. There's an effort to fix this.
