### ISSUE TITLE
Support for domain-based timestamp columns

### ISSUE THREAD

**Issue by msqr** [timescale/timescaledb#338]
Hello,

First I'd like to say thanks for all the hard work that's gone into timescaledb thus far; I've been watching the project evolve for some time now, and am excited to finally get a chance to evaluate it for a project.

I ran into an issue, however. I have a database I'd like to use a hypertable on, but the current definition uses a domain that is a `timestamptz`, like this:

```sql
CREATE DOMAIN common.ts
    AS timestamp with time zone
    DEFAULT now();

CREATE TABLE datum.da_datum (
    ts common.ts NOT NULL,
    ...
)
```

When I tried to create a hypertable, I receive this error:

```sql
SELECT create_hypertable('datum.da_datum', 'ts');
ERROR:  illegal type for column "ts": common.ts
CONTEXT:  PL/pgSQL function _timescaledb_internal.dimension_type(regclass,name,boolean) line 19 at RAISE
```

The domain is used pervasively throughout various tables and functions in this database, making converting the `ts` column definition to a plain `timestamptz`, so I wondered if it would be an easy thing for timescaledb to support?

**Comment by mfreed** [comment]
Hi @msqr I believe this has been fixed with https://github.com/timescale/timescaledb/pull/639, which was part of our 1.1 release.

Closing this issue for now, feel free to re-open if doesn't solve your problems.
