### ISSUE TITLE
Can't get time for time bucket aggregates

### ISSUE THREAD

**Issue by abogdanov37** [timescale/timescaledb#3382]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version "PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit"
 - TimescaleDB version 2.1.1
 - Installation method:"using Docker",

**Describe the bug**
I can't implement "plot".  Plot is the method to reduce data count for client
To do that I
1. use `time_bucket` to create intervals
2. for each interval I use `min(time) AS ft, max(time) as lt, first(doublevalue, time), last(doublevalue, time), min(doublevalue),  max(doublevalue)`. That give me first and last point wit time and min and max points **without** time

The question is how to get time for max and min value on interval

**To Reproduce**
1. Create a table 
```
CREATE TABLE data
(
    pointid bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    doublevalue double precision
)

SELECT create_hypertable('data','time','pointid',10);
```
2. Fill the table `data`
3. Use the example query
```
SELECT pointid, time_bucket('10 minutes', time) AS interval,
  min(time) AS ft, max(time) as lt, first(doublevalue, time), last(doublevalue, time), min(doublevalue),  max(doublevalue)
  FROM data 
  WHERE pointid=1 and time > now() - INTERVAL '1 day'
  GROUP BY pointid, interval
  ORDER BY interval 
```

**Comment by erimatnor** [comment]
It might be possible to implement a simple aggregate function `time_of_max()`, which returns the timestamp of the max value. Otherwise it might be possible with a window function, but I would try to seek help from our community on Slack https://slack.timescale.com/,
