### ISSUE TITLE
time_bucket_gapfill returning wrong data with compression enabled

### ISSUE THREAD

**Issue by fdmontero** [timescale/timescaledb#3383]
**Relevant system information:**
 - OS:  Red Hat Enterprise Linux 8.4 (Ootpa)
 - PostgreSQL version (output of `postgres --version`): [e.g. 13.2, 12.0]
 - TimescaleDB version 2.3.0 (same behaviour with 2.1.0)
 - Installation method: "yum install"

**Describe the bug**
When executing a query invioving time_bucket_gapfill with compression enabled on database it returns results like if the query was called several times.
I execute the query: 
`select tag, time_bucket_gapfill( ('2021-05-31'::timestamptz - '2021-05-01'::timestamptz) / 299, timestamp) as ts, interpolate(avg(value)) AS value, 0, json_object('{}') FROM observations
 WHERE tag='MER:G2HLA20CF010JT02.DACA.PV' AND timestamp BETWEEN '2021-05-01' AND '2021-05-31'
 GROUP BY ts, tag;`
I would expect to get only 300 points. Instead I got 11,100 records starting on 2021-04-30 repeating every 300 points.
2021-04-30 22:42:32 ... 2021-05-30 22:42:32 (300 records) 2021-04-30 22:42:32 ... 2021-05-30 22:42:32 (300 records) .. and so on up to 11,100 records.
**To Reproduce**
1. In a table with data enable compression: ` ALTER TABLE observations SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC', timescaledb.compress_segmentby = 'tag');`
2. Add a compression_policy: `SELECT add_compression_policy('observations', INTERVAL '3 days');`
2. Perform query: `select tag, time_bucket_gapfill( ('2021-05-31'::timestamptz - '2021-05-01'::timestamptz) / 299, timestamp) as ts, interpolate(avg(value)) AS value, 0, json_object('{}') FROM observations
 WHERE tag='MER:G2HLA20CF010JT02.DACA.PV' AND timestamp BETWEEN '2021-05-01' AND '2021-05-31'
 GROUP BY ts, tag;`

**Expected behavior**
I would expect to get only 300 points from 2021-05-01 to 2021-05-31

**Actual behavior**
I got 11,100 records starting on 2021-04-30 repeating every 300 points.
2021-04-30 22:42:32 ... 2021-05-30 22:42:32 (300 records) 2021-04-30 22:42:32 ... 2021-05-30 22:42:32 (300 records) .. and so on up to 11,100 records.

**Additional context**
If I use `time_bucket`instead of `time_bucket_gapfill` it returns only 300 hundred records in proper dates as expected.

**Comment by NunoFilipeSantos** [comment]
Hi @fdmontero, can you please try on TimescaleDB 2.4.1?

**Comment by NunoFilipeSantos** [comment]
Hi Hi @fdmontero! 👋 If you can reproduce this on the latest TimescaleDB version, please feel free to reopen the issue.
