### ISSUE TITLE
Disable ASCII art on startup

### ISSUE THREAD

**Issue by anirudhmurali** [timescale/timescaledb#3397]
During the startup of timescaledb container, the ASCII art is always printed:

![image](https://user-images.githubusercontent.com/3096325/124657752-8a481900-dec0-11eb-8428-0290c5e11f90.png)

Is there any way to silence these logs or set log level to avoid this?

**Comment by Amskee** [comment]
The highlighted note is for disabling anonymous reports and not the ASCII art as per previous line

**Comment by erimatnor** [comment]
This information is printed at the WARNING level. You'd have to mute warnings (preferably temporarily) for this to go away.
