### ISSUE TITLE
10/5000  How to ensure HA of a cluster

### ISSUE THREAD

**Issue by jiajia154569836** [timescale/timescaledb#3399]
If the AccessNode fails, how can you ensure the high availability of the cluster? Can there be a method to change from a node to a primary node or a dual-master configuration policy? If there is a guarantee of high availability on the above ask how to configure whether there is documentation.

**Comment by erimatnor** [comment]
The current design relies on using a standby for the access node, using streaming replication. See these docs for a discussion of different approaches: https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/enable-native-replication/#native-replication
