### ISSUE TITLE
Documentation for attach_tablespace

### ISSUE THREAD

**Issue by nathansgreen** [timescale/timescaledb#341]
Currently there seems to be little in the the way of how to configure multiple tablespaces in the documentation. There is a note under `Using TimescaleDB -> Hypertables -> Best Practices` that mentions this feature, but there are no details about how this works. I noticed in the source code a function called `attach_tablespace` that seems to be the correct thing to use, but I can't find it referenced in the documentation anywhere.

**Comment by mfreed** [comment]
We are in the midst of a "docs sprint", and will publish some updated details about attaching and detaching tablespaces soon.  Thanks for the interest!

**Comment by RobAtticus** [comment]
@nathansgreen the API references have been added, e.g., here is `attach_tablespace`:
http://docs.timescale.com/latest/api#attach_tablespace

We will be adding additional documentation soon with more detail on how to use them. Feel free to close the issue when you see fit.
