### ISSUE TITLE
Throughput degradation with multi-node when upgrading 2.1 to 2.3

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#3413]
**Relevant system information:**
 - OS: `Centos 7.5`
 - PostgreSQL version (output of `postgres --version`): `12.7`
 - TimescaleDB version (output of `\dx` in `psql`): `2.3.1`
 - Installation method: `yum`

**Describe the bug**

We have upgraded TimescaleDB from 2.1.x to 2.3.1. Immediately after upgrade we see significant drop in throughput of data ingest.

In our setup the ingest is continuous with more or less stable data rates. The data ingest is organized via Kafkaconnect JDBC sinks (from data flow in Kafka). Day before upgrade and day after upgrade data rates are very close (within 2%). But after upgrade we started lagging on data ingest. 

We were looking to upgrade due to supposed throughput improvements as per #3025. TimescaleDB has already been a bottleneck for data ingest in our system, but after upgrade it only got worse.

**To Reproduce**
1. Have 40 field message stream of ~120k records per second in Kafka that you want to ingest along with other data streams that total to ~600k records per second (all of which is ingested to timescale)
2. Have timescaledb running on 2.1.x
3. Note throughput and lag
4. Upgrade timescaledb to 2.3.1
5. Note throughput and lag change post-upgrade

**Expected behavior**
Performance does not get worse (worst case scenario), or get better.

**Actual behavior**
Throughput is much less immediately after upgrade.

**Screenshots**

Grafana chart of kafkaconnect lag (which translates to data lag in timescaledb) before upgrade (July 15):

![Screenshot from 2021-07-16 11-28-01](https://user-images.githubusercontent.com/985805/125887380-e9c10579-0450-49a2-92e3-e60a3452d213.png)

After upgrade (July 16):

![Screenshot from 2021-07-16 11-28-14](https://user-images.githubusercontent.com/985805/125887417-585db2c2-e20d-4251-b4d0-f9d4c1392c3a.png)

Data rates of this same topic before upgrade (July 15):

![Screenshot from 2021-07-16 11-33-35](https://user-images.githubusercontent.com/985805/125887738-9a2a473d-9384-4c59-9e39-b78f9133547f.png)

After upgrade (July 16):

![Screenshot from 2021-07-16 11-34-02](https://user-images.githubusercontent.com/985805/125887767-23ff3f1b-3f48-4da9-a91e-17bb5ba689a8.png)

**Comment by svenklemm** [comment]
@akamensky  Can you try if the regression disappears with `set timescaledb.enable_distributed_insert_with_copy to false;`. Can you also give more information about the exact queries you are tracking there?

**Comment by akamensky** [comment]
@svenklemm Will try this setting. Does it need to be enable on all nodes or only access node? Does it require restart?

As for the queries - at the time the throughout checked it is all just batch inserts. No other queries running at the time.

**Comment by akamensky** [comment]
@svenklemm, set in `postgresql.conf` and reloaded config. We will need to observe for 24 hours as we missed this peak of the lag/traffic today (changed config after it already passed).

Meantime something to note -- AN is writing a lot of data to the disk. It saturates RAID1 of SATA3 SSDs. Average disk IO util on AN is 80-90%, which I believe may be also causing issues with throughput. All of that IO is metadata tables of TimescaleDB (currently using at about 290 GB of disk space). The disk space usage was similar in 2.1, but disk IO was nowhere this high.

**Comment by akamensky** [comment]
@svenklemm, verified today, changing that option to `false` has no effect. We will have to rollback to 2.1 as this is breaking our data requirements.

**Comment by akamensky** [comment]
As was requested on Slack, our system is:

- 1 AN / 3 DNs
- AN - 20c/40t CPU Xeon Gold 6138 (HT enabled), 256 GB RAM, RAID1 of Samsung 860 1TB SSDs (total 1TB space)
- DNs - 16c/32t CPU Xeon D-1581, 128 GB RAM, RAID10 of Intel 4TB SSDs (total 8TB space)
- `Is Kafkaconnect still using direct INSERTs? I know that was one of your bottlenecks previously` -- yes, Kafkaconnect is a 3rd party application (by Confluent), so we cannot change it to run something else.

Though that information I think not really relevant to the issue here, the same performance degradation should be seen in other envs as well.

**Comment by nikkhils** [comment]
@akamensky can you please disable `timescaledb.enable_distributed_insert_with_copy` by setting it to `FALSE` in your setup and let us know if the performance degradation goes away?

**Comment by akamensky** [comment]
@nikkhils Please see above. It has already been done before and the result was posted above as well.

**Comment by nikkhils** [comment]
@akamensky ok, thanks for following up. We will continue to discuss this internally.

**Comment by erimatnor** [comment]
@akamensky From that code, it looks like the Kafka importer is inserting one row at a time, unless there's some other piece of code that appends additional columns to the insert statement. Row-by-row is obviously pretty bad for performance.

Can you confirm that it is _not_ using upserts?

**Comment by svenklemm** [comment]
multinode has been removed
