### ISSUE TITLE
LOG:  server process (PID 34464) was terminated by signal 11: Segmentation fault

### ISSUE THREAD

**Issue by vijay0801** [timescale/timescaledb#3414]
Hi ALL
We have a timescale multi node setup in our environment where we have 1 access node and 7 data node .
Whenever we are running load test our access node is failing with
LOG:  server process (PID 34464) was terminated by signal 11: Segmentation fault
And database is going in recovery mode for 1-2 min then its coming back online.
at the same specific time i found var_log_message throwing this
kernel: postgres[35849]: segfault at 10 ip ########## sp ########## error 4 in timescaledb-tsl-2.3.0.so[##########+80000]

we are facing this issue in every load run.
round about 4-5 times in 3 hour job run everyday.
firsty it was happening at much higher rate than we figured out it was due to max_lock_per_transaction parameter and ram utilisation was going max at rapid speed
after fixing that now we are facing same database going in recovery mode but at slower rate and ram utilisation is also not at all maxing but still db is failing and going in recovery mode

**Comment by svenklemm** [comment]
Can you try upgrading to 2.3.1 and see if the issue persists. Can you get a coredump of the crash to get more information about the circumstances when the crash happens.

**Comment by vijay0801** [comment]
Hi 
We tried updating timescaledb to 2.3.1 but still facing the same issue after update.
LOG:  server process (PID XXXXX) was terminated by signal 11: Segmentation fault


and faced a new issue whille doing a db restore of earlier date on access node we found that data on data node was gone.
can you help us understand what would be the reason for this

**Comment by vijay0801** [comment]
Hi 
We tried updating timescaledb to 2.3.1 but still facing the same issue after update.
LOG:  server process (PID XXXXX) was terminated by signal 11: Segmentation fault

This time we did not do any load test etc still we got this issue during droping distributed hypertable with drop command and DB was down for 1 min with same error than again it came back,
we were not able to replicate this again as we tried drop again and it worked without failing/crashing

**Comment by vijay0801** [comment]
can you please share process to get a coredump that you asked for we tried to enable but is not working

**Comment by bubu11e** [comment]
Hi, we encountered the same issue during a benchmark with timescale 2.5.0. However, we did not manage to reproduce it.

Here are some informations : 
 - OS: Debian 10
 - PostgreSQL version (output of `postgres --version`): 13.4
 - TimescaleDB version (output of `\dx` in `psql`): 2.5.0
 - Installation method: apt install using Timescale Debian repositories

Cluster is composed of one access node and two datanodes running on baremetal servers.

Here are some the log from postgresql : 

    2021-10-29 08:51:55.286 UTC,,,24061,,617ac34e.5dfd,21,,2021-10-28 15:35:42 UTC,,0,LOG,00000,"server process (PID 13576) was terminated by signal 11: Segmentation fault","Failed proces
s was running: SELECT _prom_catalog.insert_metric_row($1, $2::TIMESTAMPTZ[], $3::DOUBLE PRECISION[], $4::BIGINT[])",,,,,,,,"","postmaster"

And the Syslog : 

    [Fri Oct 29 08:52:11 2021] show_signal_msg: 200 callbacks suppressed
    [Fri Oct 29 08:52:11 2021] postgres[13576]: segfault at 10 ip 00007f33ff6d641e sp 00007fff611411f0 error 4 in timescaledb-tsl-2.5.0.so[7f33ff686000+5d000]
    [Fri Oct 29 08:52:11 2021] grsec: From 146.59.249.173: Segmentation fault occurred at 0000000000000010 in /usr/lib/postgresql/13/bin/postgres[postgres:13576] uid/euid:110/110 gid/egid:117/117, parent /usr/lib/postgresql/13/bin/postgres[postgres:24061] uid/euid:110/110 gid/egid:117/117
    [Fri Oct 29 08:52:11 2021] postgres[14002]: segfault at 10 ip 00007f33ff6d641e sp 00007fff611411f0 error 4
    [Fri Oct 29 08:52:11 2021] postgres[13818]: segfault at 10 ip 00007f33ff6d641e sp 00007fff611411f0 error 4 in timescaledb-tsl-2.5.0.so[7f33ff686000+5d000]
    [Fri Oct 29 08:52:11 2021] postgres[13723]: segfault at 10 ip 00007f33ff6d641e sp 00007fff611411f0 error 4 in timescaledb-tsl-2.5.0.so[7f33ff686000+5d000]
    [Fri Oct 29 08:52:11 2021]  in timescaledb-tsl-2.5.0.so[7f33ff686000+5d000]

**Comment by mfundul** [comment]
@vijay0801 can you also share your PG version and Timescale installation method?

**Comment by mkindahl** [comment]
> can you please share process to get a coredump that you asked for we tried to enable but is not working

What installation method did you use? Timescale extension is typically built with debug symbols, so installing, for example `coredumpctl` would allow you to inspect crashes.

**Comment by NunoFilipeSantos** [comment]
Closing. @vijay0801 if you can come back with the information @mkindahl requested, please feel free to reopen the issue. 👍
