### ISSUE TITLE
Can not install timescaledb on Ubuntu 21.04 - hirsute Release does not have a Release file

### ISSUE THREAD

**Issue by hakanu** [timescale/timescaledb#3415]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc] Ubuntu 21.04
 - PostgreSQL version (output of `postgres --version`): [e.g. 13.2, 12.0] 13.3 (Ubuntu 13.3-0ubuntu0.21.04.1)
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"] apt install

**Describe the bug**
I follow these steps
https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/#installation-apt-ubuntu

After adding 3rd party ppa repo, `sudo apt-get update` throws this error:

```
E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

ANd naturally I get this later:

```
sudo apt install timescaledb-2-postgresql-13
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package timescaledb-2-postgresql-13
```

**To Reproduce**
1. Have fresh Ubuntu 21.04 installed
2. Follow install steps at https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/#installation-apt-ubuntu
3. at the update command you will see the failure

**Expected behavior**
Installation to happen smoothly

**Actual behavior**
Installation is not going forward

**Comment by svenklemm** [comment]
We have not yet released packages for Ubuntu 21.04. You should be able to use packages for previous ubuntu version: https://askubuntu.com/questions/293203/how-can-i-add-a-ppa-from-a-previous-release

**Comment by hakanu** [comment]
Thanks for fast reply. Added `focal` (20.04) instead of `hirsute`. That doesn't seem to have psql-13 version. Am i doing something wrong?

![Screenshot from 2021-07-16 21-43-15](https://user-images.githubusercontent.com/403473/126006463-7f540e62-d3e2-410b-99a7-74f0193f62fc.png)

```bash
sudo apt-get install timescaledb-postgresql-13 -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package timescaledb-postgresql-13 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  timescaledb-2-loader-postgresql-13

E: Package 'timescaledb-postgresql-13' has no installation candidate
```

**Comment by NunoFilipeSantos** [comment]
@hakanu this should be fixed now, thank you.
Feel free to reopen this issue if that is not the case.
