### ISSUE TITLE
Can star schema gain query performance from TimescaleDB?

### ISSUE THREAD

**Issue by HereticSK** [timescale/timescaledb#342]
I am trying to build a financial database using a star schema. The typical query pattern looks something like:
```SQL
SELECT dim_date.ISO_date, dim_asset.symbol, fact_ohlc.volume
FROM dim_date, dim_asset
WHERE
        dim_date.date_key = fact_sales.date_key
        AND dim_asset.asset_key = fact_ohlc.asset_key
        AND dim_date.date_key > '2017-05-21'
        AND dim_symbol.industry_code = 'X'
```

This data bears the typical charateristics of time series data (time-centeric, append-only) , and thus should be a perfect use case for TimescaleDB. 

But after reading the whole documentation, I found examples about creating hypertables usually use a timestamptz column as partition keys. But in a star schema, fact tables are often created with integer surrogate key as foreign keys referencing a dimension table surrogate key.

I can convert a fact table into a hypertable anyway, using the integer surrogate date key as partition key. But my question is: can this design improve query performance when I query that table using joins to the date dimension table? Since most of the predicates are specified on the dimension table rather than directly on the fact table. Is the query optimizer smart enough to handle that? Or is there any design strategis or indexing strategies to do this?

Thank you.

**Comment by mfreed** [comment]
Hi @HereticSK :  Thanks for the question.  To be honest, we haven't sufficiently explored when and where TimescaleDB can improve star schemas (and small changes that may significantly improve performance, such as ensuring that time predicates are specified on the fact table).

If you are interested, happy to explore this further with you in our [Slack channel](http://slack-login.timescale.com).  Cheers!

**Comment by thongpv3** [comment]
I have the same interest

**Comment by mfreed** [comment]
[Closing out for lack of discussion / concrete enhancement request]
