### ISSUE TITLE
Deadlock while calling drop_chunks 

### ISSUE THREAD

**Issue by akamensky** [timescale/timescaledb#3423]
**Relevant system information:**
 - OS: `Centos 7.5`
 - PostgreSQL version (output of `postgres --version`): `12.7`
 - TimescaleDB version (output of `\dx` in `psql`): `2.3.1`
 - Installation method: `yum`

**Describe the bug**
Deadlock while inserting data and dropping chunks at the same time.

```
2021-07-20 01:00:02.697 TZ [2031] DETAIL:  Process 2031 waits for ShareLock on transaction 1618883558; blocked by process 410127.
        Process 410127 waits for ShareLock on transaction 1618883408; blocked by process 2031.
        Process 2031: SET TIME ZONE 'UTC';SELECT drop_chunks(format('%I.%I', hypertable_schema, hypertable_name)::regclass, INTERVAL '2 days') FROM timescaledb_information.hypertables;
        Process 410127: INSERT INTO "public"."table_name" ("col1","col2","col3","col4","col5","col6","col7","col8","col9") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
2021-07-20 01:00:02.697 TZ [2031] HINT:  See server log for query details.
2021-07-20 01:00:02.697 TZ [2031] CONTEXT:  while locking tuple (0,13) in relation "dimension_slice"
2021-07-20 01:00:02.697 TZ [2031] STATEMENT:  SET TIME ZONE 'UTC';SELECT drop_chunks(format('%I.%I', hypertable_schema, hypertable_name)::regclass, INTERVAL '2 days') FROM timescaledb_information.hypertables;
```

**To Reproduce**
1. No idea, this did not happen for awhile
2. Table is partitioned by 1 hour
3. Data dropped after 48 hours

**Expected behavior**
No deadlock

**Actual behavior**
A deadlock as above, drop has failed.

**Additional information**
This only happened after we upgraded from 2.1.x to 2.3.1. We've been on 2.1 for a while (since it was released) and did not see this happening. Setup is exactly same, so probably something was introduced in 2.1->2.3.1 that is causing this.

**Comment by erimatnor** [comment]
@akamensky can you provide additional information on whether this is a single-node or multi-node system. In case of the latter, did this happen on the access node or a data node?

**Comment by akamensky** [comment]
Multinode. 1 AN, 3 DNs. drop_chinks is called from cronjob on access node by superuser (postgres).

**Comment by erimatnor** [comment]
@akamensky are you doing backfill in such a way that you might actually try to drop chunks that you are simultaneously inserting into?

I believe that a deadlock can occur if you drop chunks in a different order than you insert. E.g., drop chunk A, B and insert into B, A. We've tried to avoid a global lock between inserts and drop_chunks as that would affect performance.

**Comment by akamensky** [comment]
We almost never do backfill. All inserts are pretty much real-time (relative to the primary index timestamp, that is if primary index timestamp is "p" then now()-p is at most a few seconds, commonly under a second). At the same time the hypertable is bucketed by 1 hour intervals and we drop only chunks older than 48 hours. Under these I am quite sure that the chunks being dropped are not being written into.

**Comment by erimatnor** [comment]
@akamensky OK, it is good to know that you aren't dropping and inserting into the same chunks. That leaves another possibility: namely order of locking on shared dimension slices.

In a time-space partitioned table, two chunks can share the same dimension_slices if they belong to the same space partition but don't overlap in time. So, if you have two space partition slices A and B, then the same ordering issue can occur between drops and inserts even if the two processes aren't dealing with the same chunks. For instance, the INSERT process inserts into two chunks that reference slices A and B (in that order), and a drop_chunks process drops chunks that reference the same slices, but in order B, A.

Will see if someone can reproduce this. But I am not sure much changed between related to this locking between the versions you mention.

**Comment by akamensky** [comment]
Thanks, what you say makes sense. Though not exactly sure on the terminology of dimension slices that you use. If this helps to narrow it down -- all hypertables in our database have exactly 1 space dimension (a string type column) and a separately created btree index on that same column (because since some 1.x version timescale extension does not automagically create index on space dimension columns as it used to).

**Comment by akamensky** [comment]
This just happened again in our staging environment (where the same cronjob is executed every hour as opposed to once a day in prod).

```
2021-07-22 07:00:01.879 UTC [12242] LOG:  connection received: host=[local]
2021-07-22 07:00:01.881 UTC [12242] LOG:  connection authorized: user=postgres database=dbname application_name=psql
2021-07-22 07:00:03.009 UTC [12242] ERROR:  deadlock detected
2021-07-22 07:00:03.009 UTC [12242] DETAIL:  Process 12242 waits for ShareLock on transaction 779361481; blocked by process 29739.
        Process 29739 waits for ShareLock on transaction 779361480; blocked by process 12242.
        Process 12242: SET TIME ZONE 'UTC';SELECT drop_chunks(format('%I.%I', hypertable_schema, hypertable_name)::regclass, INTERVAL '1 hours') FROM timescaledb_information.hypertables;
        Process 29739: INSERT INTO "public"."table_name" (<redacted>) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
2021-07-22 07:00:03.009 UTC [12242] HINT:  See server log for query details.
2021-07-22 07:00:03.009 UTC [12242] CONTEXT:  while locking tuple (1,8) in relation "dimension_slice"
2021-07-22 07:00:03.009 UTC [12242] STATEMENT:  SET TIME ZONE 'UTC';SELECT drop_chunks(format('%I.%I', hypertable_schema, hypertable_name)::regclass, INTERVAL '1 hours') FROM timescaledb_information.hypertables;
```

Sice we've seen the decrease in throughput after upgrading to 2.3.1, I suspect that whatever caused that decrease in throughput also increased the likelihood of such "race-condition"

**Comment by NunoFilipeSantos** [comment]
@akamensky can you please try against our latest TimescaleDB version (2.4.2) and get back to us?

**Comment by nikkhils** [comment]
@akamensky can you please try against our latest TimescaleDB version (2.6) and get back to us?

**Comment by konskov** [comment]
Hello @jmkbo, thank you for reaching out about this. 

Could you please share some information about the following to help debug this issue:
* Could you provide your hypertable definition? Mainly to see your chunk size and whether you are using space partitioning, as is the case in the original issue. Also, do you have compression enabled?
* How are you performing the bulk inserts? Meaning, what is the command you are using? (a large `INSERT` command, COPY..?)
* Is it possible to share the log messages and the deadlock message you are seeing?

Thank you!

**Comment by konskov** [comment]
@jmkbo if I understand this correctly, you are reading chunks that correspond to the most recent 15 minutes (trying to perform multiple simultaneous reads of the past 15 minutes of data), and dropping chunks older than 14 minutes (`PERFORM drop_chunks('element_state', INTERVAL '14 minutes');`)? 

Can you try to see whether there are overlapping ranges of chunks being read and dropped? meaning, are you trying to simultaneously read from the chunk you are trying to delete? Or are you dropping and reading unrelated chunks? 

It would also be good to know what `relation 30431 of database` is. Thanks!

**Comment by mkindahl** [comment]
> Yes, that's correct. I'm trying to read from the same chunks I'm trying to delete - my expectation (hope?) was that one thread would block for the other, not that they would deadlock. e.g. if the deletion gets there first, the query waits and then finds no data, and if the query gets there first, then the deletion just waits.

Yes, this is how I think it should work as well.

> This test is designed to expose that condition, because it's a common pattern I expect in real usage. Clients won't have knowledge of the retention period so they won't be able to limit their queries by it, so they will often request data that's older than the retention period.
> 
> Relation 30431 no longer exists:
> 
> ```
> # SELECT relname FROM pg_class WHERE OID=30431;
>  relname 
> ---------
> (0 rows)
> ```
> 
> I was guessing that relation was one of the chunks being deleted, but I don't know how to prove it. Do you have any suggestions for gathering more data?

There are multiple objects involved here and we had issues before where the deadlock was caused because of an attempt to lock indexes. For that reason, it would be good to know what relation was involved. It might require attaching a debugger and halt before printing the deadlock message (function is `DeadlockReport`), if that is possible.

Alternative is if you have a script that you use to reproduce the issue that you can send to us. Then we can try that here and get the information.

> `2022-11-15 23:33:51.007 UTC [1288127] CONTEXT:  while locking tuple (0,68) in relation "dimension_slice"`

This is also a hint we can use to figure out where the deadlock is, but that is quite complicated, so if you have any of the above, it would be a great help.

**Comment by pscott31** [comment]
I don't know if it is strictly related but an issue we have been having today feels quite similar to this. We have been having the retention policy running conflicting with our grafana probe agent:

```
023-02-06 23:05:07.926 UTC [4015796] ERROR:  deadlock detected
2023-02-06 23:05:07.926 UTC [4015796] DETAIL:  Process 4015796 waits for AccessExclusiveLock on relation 6221406 of database 5876743; blocked by process 2926975.
        Process 2926975 waits for AccessShareLock on relation 6221412 of database 5876743; blocked by process 4015796.
        Process 4015796: CALL _timescaledb_internal.policy_retention()
        Process 2926975: SELECT
        table_name,
        table_bytes,
        index_bytes,
        toast_bytes,
        total_bytes
        FROM (
            SELECT
              pg_catalog.pg_namespace.nspname           AS schema_name,
              relname                                   AS table_name,
              (hypertable_detailed_size(pg_catalog.pg_class.oid)).*

            FROM pg_catalog.pg_class
              JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid
          ) t
        WHERE schema_name = 'public'
```

It was quite regular,  4 or 5 times a day - but we didn't notice until it deadlocked with our actual application which was doing a COPY INTO:

```
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db ERROR:  deadlock detected
2023-02-08 23:17:38.352 UTC [4171079] vega@data_node_db DETAIL:  Process 4171079 waits for AccessShareLock on relation 6351231 of database 5876743; blocked by process 4171223.
        Process 4171223 waits for AccessExclusiveLock on relation 6351225 of database 5876743; blocked by process 4171079.
        Process 4171079: copy (select * from market_data where synthetic_time >= (SELECT vega_time from blocks where height = 1847701) order by synthetic_time) to '/home/vega/vega_home/state/data-node/networkhistory/snapshotscopyto/vega-stagnet1-202301232253-1847701-1848000-historysnapshot/market_data'
        Process 4171223: CALL _timescaledb_internal.policy_retention()
```

Doing a bit of reading it seems that the AccessExclusiveLock is likely to come from `drop_chunks` inside ` _timescaledb_internal.policy_retention()`. I guess if there are multiple chunks to drop and it tries to do them in one transaction, it could deadlock with a transaction that was reading from the chunks in a different order?

**Comment by jnidzwetzki** [comment]
Hello @pscott31,

Thanks for reaching out. Could you share more details about the table schema used and the exact commands executed when the deadlock occurs? According to the logfile, the retention policy is called on `2023-02-06 23:05:07.926` and the copy command seems to be executed on `2023-02-08 23:17:38.352`. You mention that the problem occurs several times per day. So, I assume that both log entries are from different deadlocks. Could you provide us with the executed commands from one occurrence? This would help us, together with the table schema, to reproduce the behavior.
