### ISSUE TITLE
Add Column to Compressed Hypertable with DEFAULT NULL

### ISSUE THREAD

**Issue by jameswinegar** [timescale/timescaledb#3429]
Extension of #1543 with associated PR #2736
```
ALTER TABLE table_name
  ADD COLUMN column_name INTEGER DEFAULT NULL
```

`ERROR:  cannot add column with constraints or defaults to a hypertable that has compression enabled`

Adding a default nullable column should have limited write impact, and allows us to evolve the table schema as needed.

**Comment by gayyappan** [comment]
We don't support the DEFAULT syntax yet with compressed hypertables. 
ALTER TABLE ... ADD COLUMN  does exactly the same thing. Here's a test on a compressed hypertable.

```
test=#ALTER TABLE test1 ADD COLUMN new_col2 integer  ;
test=# INSERT INTO test1  SELECT '2018-03-04 2:00', 100, 400, 'hello' ;
INSERT 0 1
test=# select count(*) from test1 where new_col2 is null;
 count 
-------
     2
(1 row)

**Comment by jameswinegar** [comment]
@gayyappan my table size is ~1 TB compressed. Any thoughts on performance of this? If it's a no-op then that's great

**Comment by jameswinegar** [comment]
It works just fine to use `ALTER TABLE table_name ADD COLUMN column_name data_type`
