### ISSUE TITLE
Maintenance procedure in multidatabase multinode setup

### ISSUE THREAD

**Issue by thedolphin** [timescale/timescaledb#3433]
**Relevant system information:**
 - OS: docker image pg13.3-ts2.3.0-latest
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.0
 - Installation method: using Docker

**Describe the bug**
More then one database in multinode setup causes maintenance procedure to stop working with message "ERROR:  [datanode1]: prepared transaction belongs to another database".

Seems the [query](https://github.com/timescale/timescaledb/blob/dd3e422964f9a0d8a913d03ae2da2ad64799f3f8/tsl/src/remote/txn_resolve.c#L39) has to be more specific and include database name

**To Reproduce**
Install TSDB in multinode
Create two or mode databases with distributed hypertabes, execute [maintenance task](https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/maintenance-tasks/)

**Expected behavior**
Maintenance procedure works without errors

**Actual behavior**
Maintenance procedure stops with error "ERROR:  [datanode1]: prepared transaction belongs to another database".

**Comment by pmwkaa** [comment]
Thanks for posting! seems like a bug
