### ISSUE TITLE
A TimescaleDB issue in PostgreSQL upgrade

### ISSUE THREAD

**Issue by dumm1** [timescale/timescaledb#3438]
Hello,

My currently running PostgreSQL version is 10.9 with TimescaleDB version 1.4.0-0.
I attempted to upgrade PostgreSQL version to PostgreSQL13. 
While I ran "pg_upgrade -check", I got an error log. It says,
could not load library "$libdir/pgcrypto": ERROR:  could not access file "$libdir/pgcrypto": No such file or directory
could not load library "$libdir/timescaledb-1.4.0": ERROR:  could not access file "$libdir/timescaledb-1.4.0": No such file or directory

I think it was due to , PostgreSQL13 was installed with TimescaleDB 1.4.0.  
I'm not sure if 1.4.0 could be installed on PostgreSQL13 since below link only provides the installation for v1.4 on PostgreSQL11.

Thus I installed PostgreSQL11. Then "yum install timescaledb-postgresql-11-1.4.0-0.el7.x86_6".
Unfortunately, I got another error.
Transaction check error:
  file /usr/lib64/timescaledb/timescaledb-1.4.0.so from install of timescaledb-postgresql-11-1.4.0-0.el7.x86_64 conflicts with file from package timescaledb-postgresql-10-1.4.0-0.el7.x86_64
  file /usr/lib64/timescaledb/timescaledb-tsl-1.4.0.so from install of timescaledb-postgresql-11-1.4.0-0.el7.x86_64 conflicts with file from package timescaledb-postgresql-10-1.4.0-0.el7.x86_64
  file /usr/lib64/timescaledb/timescaledb.so from install of timescaledb-postgresql-11-1.4.0-0.el7.x86_64 conflicts with file from package timescaledb-postgresql-10-1.4.0-0.el7.x86_64

Below is what I already have in /usr/lib64/timescaledb/
# ll
total 3632
-rw-r--r-- 1 root root  86410 Jul 19  2019 timescaledb--0.10.0--1.4.0.sql
-rw-r--r-- 1 root root  86101 Jul 19  2019 timescaledb--0.10.1--1.4.0.sql
-rw-r--r-- 1 root root 121202 Jul 19  2019 timescaledb--0.1.0--1.4.0.sql
-rw-r--r-- 1 root root  84791 Jul 19  2019 timescaledb--0.11.0--1.4.0.sql
-rw-r--r-- 1 root root  81392 Jul 19  2019 timescaledb--0.12.0--1.4.0.sql
-rw-r--r-- 1 root root  81392 Jul 19  2019 timescaledb--0.12.1--1.4.0.sql
-rw-r--r-- 1 root root 120485 Jul 19  2019 timescaledb--0.2.0--1.4.0.sql
-rw-r--r-- 1 root root 120240 Jul 19  2019 timescaledb--0.3.0--1.4.0.sql
-rw-r--r-- 1 root root 120081 Jul 19  2019 timescaledb--0.4.0--1.4.0.sql
-rw-r--r-- 1 root root 120081 Jul 19  2019 timescaledb--0.4.1--1.4.0.sql
-rw-r--r-- 1 root root 120081 Jul 19  2019 timescaledb--0.4.2--1.4.0.sql
-rw-r--r-- 1 root root 106759 Jul 19  2019 timescaledb--0.5.0--1.4.0.sql
-rw-r--r-- 1 root root 101231 Jul 19  2019 timescaledb--0.6.0--1.4.0.sql
-rw-r--r-- 1 root root 101231 Jul 19  2019 timescaledb--0.6.1--1.4.0.sql
-rw-r--r-- 1 root root  92335 Jul 19  2019 timescaledb--0.7.0--1.4.0.sql
-rw-r--r-- 1 root root  91132 Jul 19  2019 timescaledb--0.7.1--1.4.0.sql
-rw-r--r-- 1 root root  90483 Jul 19  2019 timescaledb--0.8.0--1.4.0.sql
-rw-r--r-- 1 root root  86410 Jul 19  2019 timescaledb--0.9.0--1.4.0.sql
-rw-r--r-- 1 root root  86410 Jul 19  2019 timescaledb--0.9.1--1.4.0.sql
-rw-r--r-- 1 root root  86410 Jul 19  2019 timescaledb--0.9.2--1.4.0.sql
-rw-r--r-- 1 root root  80760 Jul 19  2019 timescaledb--1.0.0--1.4.0.sql
-rw-r--r-- 1 root root  81392 Jul 19  2019 timescaledb--1.0.0-rc1--1.4.0.sql
-rw-r--r-- 1 root root  81321 Jul 19  2019 timescaledb--1.0.0-rc2--1.4.0.sql
-rw-r--r-- 1 root root  80760 Jul 19  2019 timescaledb--1.0.0-rc3--1.4.0.sql
-rw-r--r-- 1 root root  80760 Jul 19  2019 timescaledb--1.0.1--1.4.0.sql
-rw-r--r-- 1 root root  79921 Jul 19  2019 timescaledb--1.1.0--1.4.0.sql
-rw-r--r-- 1 root root  79921 Jul 19  2019 timescaledb--1.1.1--1.4.0.sql
-rw-r--r-- 1 root root  77983 Jul 19  2019 timescaledb--1.2.0--1.4.0.sql
-rw-r--r-- 1 root root  77983 Jul 19  2019 timescaledb--1.2.1--1.4.0.sql
-rw-r--r-- 1 root root  77983 Jul 19  2019 timescaledb--1.2.2--1.4.0.sql
-rw-r--r-- 1 root root  72788 Jul 19  2019 timescaledb--1.3.0--1.4.0.sql
-rw-r--r-- 1 root root  72788 Jul 19  2019 timescaledb--1.3.1--1.4.0.sql
-rw-r--r-- 1 root root  72579 Jul 19  2019 timescaledb--1.3.2--1.4.0.sql
-rwxr-xr-x 1 root root 379104 Jul 19  2019 timescaledb-1.4.0.so
-rw-r--r-- 1 root root  91075 Jul 19  2019 timescaledb--1.4.0.sql
-rw-r--r-- 1 root root    365 Jul 19  2019 timescaledb.control
-rwxr-xr-x 1 root root  41344 Jul 19  2019 timescaledb.so
-rwxr-xr-x 1 root root 118320 Jul 19  2019 timescaledb-tsl-1.4.0.so

Many people suggest applying "rpm -e" to remove the conflicted packages when they have the "Transaction check error".
I'm afraid if I remove timescaledb-postgresql-10-1.4.0-0.el7.x86_64, "pg_upgrade -check" will print the error for timescaledb-1.4.0 of PostgreSQL10.

How do you deal with the PostgreSQL with TimescaleDB upgrade in the scenario like mine?

**Comment by nikkhils** [comment]
@dumm1 this is a major version upgrade. So major version upgrades are typically done by doing a `pg_dump` followed by `pg_restore`. Please refer to PostgreSQL documentation for major version upgrades. 

The following documentation should help 

https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/update-timescaledb-2/#compatibility

**Comment by nikkhils** [comment]
Please feel free to create another issue if the above brings forth anything timescale specific.
