### ISSUE TITLE
postgres segmentation fault on query with "ORDER BY"

### ISSUE THREAD

**Issue by AlekseiSaff** [timescale/timescaledb#3439]
**Relevant system information:**
 - OS: CentOS 7.9
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.1
 - Installation method: Docker

**Describe the bug**
A query with ORDER BY value is crashing database

SELECT
    data->>'valuation_time'         AS val_time,
    jsonb_array_elements(data->'greek_positions')->>'expiry' AS expiry,    
    (jsonb_array_elements(data->'greek_positions')->>'vega')::decimal AS vega
FROM data__lt_pm_portfolio_pnl
WHERE
    ingested_at >= '1627022100000000000' and 
         ingested_at <= '1627022160000000000'
ORDER BY ingested_at DESC

2021-07-24 03:44:13.605 UTC [1] LOG:  server process (PID 43) was terminated by signal 11: Segmentation fault
2021-07-24 03:44:13.605 UTC [1] DETAIL:  Failed process was running: SELECT
data->>'valuation_time'         AS val_time,
jsonb_array_elements(data->'greek_positions')->>'expiry' AS expiry,
(jsonb_array_elements(data->'greek_positions')->>'vega')::decimal AS vega
FROM data__lt_pm_portfolio_pnl
WHERE
ingested_at >= '1627022100000000000' and
ingested_at <= '1627022160000000000'
ORDER BY ingested_at DESC

Without "order by"  it works fine. And it's happening not all the time only on a specific data set

**To Reproduce**
execute query

**Expected behavior**
Query should return set of data

**Actual behavior**
PG fails with segmentation fault

**Screenshots**
none

**Additional context**

**Comment by pmwkaa** [comment]
@AlekseiSaff Hey Aleksei, do you think you can share a backtrace for the crash?

**Comment by AlekseiSaff** [comment]
@pmwkaa thanks for your reply. For sure.
But do you mean core file?
I'm not sure about backtrace in docker. If you can point me how to collect I definitely can do that

**Comment by pmwkaa** [comment]
Core file might be large, I guess just seeing a backtrace of the crash could also be useful

**Comment by AlekseiSaff** [comment]
Happy to share backtrack, but no sure how to collect it 
As we are in docker

**Comment by AlekseiSaff** [comment]
@pmwkaa this one?

[root@lt-hkg1-pvm02 pg]# gdb /tmp/pg/postgres -c /tmp/pg/core.16018 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /tmp/pg/postgres...done.
[New LWP 16018]

warning: Could not load shared library symbols for 19 libraries, e.g. /usr/lib/libxml2.so.2.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?

warning: Can't read pathname for load map: Input/output error.
Core was generated by `postgres:'.
Program terminated with signal 11, Segmentation fault.
#0  0x000056430fb220e9 in getKeyJsonValueFromContainer ()
(gdb) bt
#0  0x000056430fb220e9 in getKeyJsonValueFromContainer ()
#1  0x000056430fb27b29 in jsonb_object_field ()
#2  0x00007f51587eba9b in ?? ()
#3  0x00007f515e4a1208 in ?? ()
#4  0x00007f515e3a1858 in ?? ()
#5  0x00007f515e3a1840 in ?? ()
#6  0x00007f515e3a17d8 in ?? ()
#7  0x00007f515e3a1cfd in ?? ()
#8  0x00007f515e3a1d00 in ?? ()
#9  0x00007f515e4ae300 in ?? ()
#10 0x000056430f960ef4 in ExecEvalFuncArgs ()
#11 0x000056430f961c72 in ExecMakeFunctionResultSet ()
#12 0x000056430f9824f8 in ExecProjectSRF ()
#13 0x000056430f9825c4 in ExecProjectSet ()
#14 0x000056430f982d96 in ExecResult ()
#15 0x000056430f9591a2 in standard_ExecutorRun ()
#16 0x00007f61c6b894a5 in ?? ()
#17 0x00000000ffffffff in ?? ()
#18 0x00007ffc962bfbe0 in ?? ()
#19 0x0000000000000000 in ?? ()
(gdb)

**Comment by AlekseiSaff** [comment]
It seems like I don't have that issue on PG+TSDB on a bare metal.
so now I'm unsure what to do cause my main production DB is inside of the docker and we have that issue there

**Comment by pmwkaa** [comment]
Yeah it's hard to tell whats going on right now, do you think you can make a small case which can reproduce the issue?

**Comment by AlekseiSaff** [comment]
I have a set of data that can reproduce this issue.

**Comment by nikkhils** [comment]
@AlekseiSaff if will be great if you can share the data/steps so that we can reproduce it ourselves as well.

**Comment by NunoFilipeSantos** [comment]
@AlekseiSaff if you can provide more information feel free to reopen the issue.
