### ISSUE TITLE
Tablespace for primary key constraint that is different from table's tablespace lost on hypertable

### ISSUE THREAD

**Issue by msqr** [timescale/timescaledb#344]
Hello,

I have a table defined like below that I'd like to convert to a hypertable:

```sql
CREATE TABLE da_datum_hyper (
    ts timestamp with time zone NOT NULL,
    node_id bigint NOT NULL,
    source_id character varying(64) NOT NULL,
    jdata jsonb,
    CONSTRAINT da_datum_hyper_pkey PRIMARY KEY (node_id, ts, source_id)
        USING INDEX TABLESPACE tsindex
)
TABLESPACE tsdata;
```

Note how the primary key's tablespace `tsindex` differs from the table's tablespace `tsdata`. When I turn this into a hypertable, however, the chunk primary key constraint does not preserve the associated index tablespace `tsindex` as expected. The chunks look like this:

```sql
CREATE TABLE _timescaledb_internal._hyper_1_10_chunk (
  CONSTRAINT "10_10_da_datum_hyper_pkey" PRIMARY KEY (node_id, ts, source_id),
  CONSTRAINT constraint_10 CHECK (ts >= '2012-11-16 13:00:00+13'::timestamp with time zone AND ts < '2013-05-15 12:00:00+12'::timestamp with time zone)
)
INHERITS (da_datum_hyper);
```

While I was expecting to see

```sql
  CONSTRAINT "10_10_da_datum_hyper_pkey" PRIMARY KEY (node_id, ts, source_id) USING INDEX TABLESPACE tsindex,
```
Is it possible to preserve the tablespace of the index backing the primary key constraint of a hypertable (that differs from its table's tablespace)?

**Comment by dianasaur323** [comment]
@davidkohn88 believes this might not be an issue anymore, but let's reconfirm before closing

**Comment by NunoFilipeSantos** [comment]
@msqr were you able to confirm this is not an issue anymore?

**Comment by msqr** [comment]
I just tested this out in Timescale 1.7.4 and the issue is resolved. Thanks!

**Comment by NunoFilipeSantos** [comment]
Thank you for letting us know.
Closing.
