### ISSUE TITLE
Segfault with TRUNCATE TABLE

### ISSUE THREAD

**Issue by micw** [timescale/timescaledb#3444]
**Relevant system information:**
 - OS: K8S on debian 10
 - Official docker image, occurs with 2.3.1-pg13, 2.3.1-pg12 and also previous versions I tested

**Describe the bug**
On our CI system, a fresh timescale instance is started on every run. Each test truncates tables prior to run. In ~80% of the runs, this leads to a segfault of postgres/timescale.

**To Reproduce**

I could not reproduce it outside of our CI system, so I assume it's a mixture of the environments and the commands run against the database. So I just can describe the settings and provide additional information on request.

Table structure:
* normal postgres table "devices"
* timescale table "device_messages" that references devices
* Initially I had "truncate devices cascade" in my tests which was always the command the triggered the segfault
* I changed it to "truncate device_messages", after that, this triggered the segfault.

**Comment by pmwkaa** [comment]
Hey @micw, do you think you can provide us a crash backtrace if possible?

**Comment by micw** [comment]
Sure. How can I get/create one? A challenge is that the container is stopped by CI shortly after failure - but maybe I can delay this a bit by catching the error.

**Comment by NunoFilipeSantos** [comment]
Hi @micw! Can you please try TimescaleDB 2.5.0 and get back to us?

**Comment by micw** [comment]
Today I reverted my commit to our test base that uses "delete" rather than "truncate", so the issue should re-appear in the next few days. If it does, I switch to 2.5.0 to see if it's better.

**Comment by micw** [comment]
Unfortunately, the error does not occur anymore. I will excessively use truncate in future tests to see if I can reprodice it again.

**Comment by NunoFilipeSantos** [comment]
Thank you! Closing. 
If this issue resurfaces again, feel free to reopen it.
