### ISSUE TITLE
insert with SELECT  does not work for a distributed hypertable

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3447]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.0-dev
 - Installation method: source

**Describe the bug**

**To Reproduce**
1. Create a multi-node set-up:
```
SELECT * FROM add_data_node('dist_policy_data_node_1', host => 'localhost', database => 'dist_policy_data_node_1');
SELECT * FROM add_data_node('dist_policy_data_node_2', host => 'localhost', database => 'dist_policy_data_node_2');
SELECT * FROM add_data_node('dist_policy_data_node_3', host => 'localhost', database => 'dist_policy_data_node_3');
```
2. Create 2 distributed hypertables:
```
CREATE TABLE conditions (time bigint NOT NULL, device int, temp float);
SELECT create_distributed_hypertable('conditions', 'time', chunk_time_interval => 10, replication_factor => 2);

CREATE TABLE measurements (time int NOT NULL, device int, temp float);
SELECT create_distributed_hypertable('measurements', 'time', chunk_time_interval => 10, replication_factor => 2);
```
3. Insert the data in the following manner:
```
INSERT INTO conditions
SELECT t, ceil(abs(timestamp_hash(to_timestamp(t)::timestamp))%4)::int,
       abs(timestamp_hash(to_timestamp(t)::timestamp))%40
FROM generate_series(1, 100, 1) t;

INSERT INTO measurements
SELECT * FROM conditions;
```
4. See error: `ERROR:  request already in progress`

**Expected behavior**
The final `INSERT INTO` should succeed.

**Actual behavior**
I get an exception: `ERROR:  request already in progress`

**Comment by phemmer** [comment]
As a dirty workaround, you can do this in 2 steps:
```sql
CREATE TEMP TABLE foo_tmp AS SELECT ...;
INSERT INTO foo SELECT * FROM foo_tmp;
```

Not suitable for all scenarios, but it works for my use case.

**Comment by nikkhils** [comment]
Here's the EXPLAIN output:

```
postgres=# EXPLAIN INSERT INTO measurements                                                                                SELECT * FROM conditions;
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (HypertableInsert)  (cost=100.00..3408785.57 rows=30198982 width=16)
 Insert on distributed hypertable measurements
   ->  Insert on measurements  (cost=100.00..3408785.57 rows=30198982 width=16)
         ->  Custom Scan (DataNodeCopy)  (cost=100.00..3408785.57 rows=30198982 width=16)
               ->  Custom Scan (ChunkDispatch)  (cost=100.00..3408785.57 rows=30198982 width=16)
                     ->  Append  (cost=100.00..3408785.57 rows=30198982 width=16)
                           ->  Custom Scan (DataNodeScan) on conditions conditions_1  (cost=100.00..1776967.63 rows=16472172 width=16)
                           ->  Custom Scan (DataNodeScan) on conditions conditions_2  (cost=100.00..1480823.03 rows=13726810 width=16)
(8 rows)
```

So what happens is that the `DataNodeCopy` sets up a connection to the datanode in `COPY_IN` mode. 
When the execution reaches the `DataNodeScan` it tries to set up a connection to enable a CURSOR to "SELECT * from conditions" from the SAME datanode. The current code expects that there should be only ONE connection to a datanode for a given transaction. Here, clearly, we need two separate connections. 

The connection cache should not return the earlier connection because it's in `COPY_IN` mode and should create a new (READ ONLY) connection for the CURSOR.

**Comment by nikkhils** [comment]
For now, we detect the case that the source hypertable and the SELECT hypertable are BOTH distributed and avoid using COPY if that's the case.
