### ISSUE TITLE
Syntax for enabling compression is inconsistent

### ISSUE THREAD

**Issue by elbaro** [timescale/timescaledb#3448]
**Describe the bug**

Enabling the compression for the first time works:
```
ALTER TABLE table_name SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'col1, col2'
);
```

However, applying the same sql the second time results in the error:

```
DETAIL:  The timescaledb.compress_orderby option was previously set and must also be specified in the updated configuration.
```

So in the first execution, compress_orderby is implicitly set to the time column by default.
The second execution complains that it requires explicitly setting compress_orderby to the time column.

**Expected behavior**
Idempotent execution

**Actual behavior**
The second run fails.

**Comment by svenklemm** [comment]
Fixed by #4375
