### ISSUE TITLE
Possibility to use timescaleDB with Presto

### ISSUE THREAD

**Issue by dberardo-com** [timescale/timescaledb#3452]
Hi community,

i was thinking whether it could be valuable to connect timescaleDB to an existing Presto engine using the JDBC connector.

My question would be: would it still be possible to use timescale specific (non SQL standard) queries in Presto (like time_bucket) or would it not work ?

I will post the same question to the Presto github project,

thanks

**Comment by mfreed** [comment]
The timescale specific functions are still "SQL standard", in that they are just UDFs (and don't change the SQL syntax).  So this should "just work".  Please let us know if you run into any issues.

**Comment by dberardo-com** [comment]
thanks for the clarification @mfreed . 

So if i understand correctly, UDFs need to be defined as plugins in Presto is this right? Or are they simply "passed through" to the DB to be executed?

In the second case, could you please share a piece of documentation on the matter?

Thanks a lot

**Comment by dberardo-com** [comment]
also, here the reference to the issue i have open on prestoDB: https://github.com/prestodb/presto/issues/16542#issuecomment-890641081

**Comment by nikkhils** [comment]
@dberardo-com The UDFs should be simply passed through from timescale point of view. If Presto does anything additional then it would need to be reported there. 

On the whole, this looks like it needs some testing and playing around with. Please do let us know the outcome.

**Comment by dberardo-com** [comment]
sure i will, although honestly i wonder why am i the first one trying this out :D

**Comment by nikkhils** [comment]
Please feel free to open another issue if there is anything timescaledb specific.
