### ISSUE TITLE
Conflict in v2.4 packages for Ubuntu

### ISSUE THREAD

**Issue by hongquan** [timescale/timescaledb#3454]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12.0
 - TimescaleDB version 2.4.0
 - Installation method: "apt install" from ppa:timescale/timescaledb-ppa2.

**Describe the bug**
The v2.4 is packaged as two files, `timescaledb-2-loader-postgresql-12`, `timescaledb-2-postgresql-12`. But they cannot be installed due to containing the same internal file.

**To Reproduce**
1. Add ppa:timescale/timescaledb-ppa2
2. Run `sudo apt install timescaledb-2-postgresql-12`
3. See error:
```
Unpacking timescaledb-2-postgresql-12 (2.4.0~ubuntu20.04) ...
dpkg: error processing archive /var/cache/apt/archives/timescaledb-2-postgresql-12_2.4.0~ubuntu20.04_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/postgresql/12/lib/pgxs/src/test/perl/AccessNode.pm', which is also in package timescaledb-2-loader-postgresql-12 2.4.0~ubuntu20.04
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/timescaledb-2-postgresql-12_2.4.0~ubuntu20.04_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Expected behavior**
Packages are installed successfully.

**Actual behavior**

Failed with error:

```
Unpacking timescaledb-2-postgresql-12 (2.4.0~ubuntu20.04) ...
dpkg: error processing archive /var/cache/apt/archives/timescaledb-2-postgresql-12_2.4.0~ubuntu20.04_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/postgresql/12/lib/pgxs/src/test/perl/AccessNode.pm', which is also in package timescaledb-2-loader-postgresql-12 2.4.0~ubuntu20.04
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/timescaledb-2-postgresql-12_2.4.0~ubuntu20.04_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Screenshots**

**Additional context**

v2.2 is installed successfully.

**Comment by EraYaN** [comment]
`timescaledb-2-2.3.0-postgresql-13` and `timescaledb-2-2.3.1-postgresql-13` also install successfully.

**Comment by swiffer** [comment]
same here

**Comment by nikkhils** [comment]
Thanks for the report @hongquan. This is a packaging issue and we are working on fixing this.

**Comment by mfundul** [comment]
Moving from ppa to packagecloud should fix this issue. Check the [latest documentation](https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/##installation-apt-ubuntu) on how to do that.
