### ISSUE TITLE
Missing package `timescaledb-2-loader-postgresql-12`

### ISSUE THREAD

**Issue by raffomania** [timescale/timescaledb#3459]
**Relevant system information:**
 - OS: Ubuntu 20.04.2 LTS
 - PostgreSQL version (output of `postgres --version`): 12
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.1
 - Installation method: apt install

**Describe the bug**
When installing timescale 2.3.1 with postgres 12, the installation errors out because the loader package is missing.

**To Reproduce**
We're using the timescale PPA like so:
```
add-apt-repository -y ppa:timescale/timescaledb-ppa
```

When running `apt install -y timescaledb-2-2.3.1-postgresql-12`, the following error occurs:
```
The following packages have unmet dependencies:
 timescaledb-2-2.3.1-postgresql-12 : Depends: timescaledb-2-loader-postgresql-12 (>= 2.3.1~) but it is not installable
```

**Expected behavior**
The installation should be successful. The package `timescaledb-2-loader-postgresql-12` should be available in the PPA.

**Actual behavior**
The package is not available and the installation fails.

**Comment by k1ng440** [comment]
```
The following packages have unmet dependencies:
 timescaledb-2-2.3.1-postgresql-13 : Depends: timescaledb-2-loader-postgresql-13 (>= 2.3.1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by EraYaN** [comment]
I have a feeling it was an overreaction to https://github.com/timescale/timescaledb/issues/3454 and some packages were pulled, the main package for pg 13 is also gone.

**Comment by svenklemm** [comment]
The location for ubuntu packages has changed and they are now hosted on packagecloud. Docs will be updated soon to reflect it.

https://github.com/timescale/docs/pull/234/

**Comment by raffomania** [comment]
The docs imply that packagecloud is only needed for versions >= 2.4. If this is true, installing 2.3 from the PPA should still work, right? Or should I open a PR to adjust the docs?

**Comment by raffomania** [comment]
It also seems like version 2.3 is not published on packagecloud yet, leaving us with no way to install 2.3 at this time.

Every job in our CI is failing since over a week because of this and we can't think of anything short of building the packages ourselves to fix it. Are there other workarounds?

**Comment by svenklemm** [comment]
2.3.1 and 2.4.0 are on packagecloud, if you want to install a different previous versions they are still available through PPA but in either case you need the packagecloud repository too because the loader package is only on packagecloud.

So if you need a version < 2.3.1 you need both repos. For >= 2.3.1 you only need packagecloud.

**Comment by raffomania** [comment]
Thanks, our apt package list was an older version, we have now located the 2.3 package in packagecloud. 
I'm closing this issue, thanks again for the support. 

> So if you need a version < 2.3.1 you need both repos. For >= 2.3.1 you only need packagecloud.

I think you'd probably help some people by putting this sentence into the docs :)
