### ISSUE TITLE
Draining of nodes

### ISSUE THREAD

**Issue by wilfriedroset** [timescale/timescaledb#3463]
[2.4 blog post](https://blog.timescale.com/blog/move-fast-but-dont-break-things-introducing-the-experimental-schema-with-new-experimental-features-in-timescaledb-2-4/) introduces `move_chunk` and `copy_chunk` as experimental functions which is great.

In a production use case, users might need to remove temporarily (kernel upgrade, rolling reboot) a node from the multi node setup. To do that properly a node needs to be drained from all of its chunks as well as preventing it to receive new one in the process. `move_chunk` can be used but it can rapidly become cumbersome and error prone.

Do you plan to ease this use case with a `drain` function?
Something like
```
CALL timescaledb_experimental.drain_node(‘data_node_n’,);
```
This function would:
* prevent the access node from creating new chunk on `data_node_n`
* `move_chunk` on all chunks hosted on `data_node_n`
  * this can be _best-effort smart_ to avoid overcrowding a node or collocating several identical chunk

We can even go further and plan for re-including the node in the setup with a `rebalance` or `rebalance_node`

**Comment by phemmer** [comment]
If there's going to be an automatic rebalancer (and I think such would be a good thing), then I think this would best be handled with a "node state" paradigm. Meaning a node would be in one of 5 states that would control the behavior of chunk access & balancing.

|           | Read existing chunks | Write new chunks | Rebuild chunks |
|-----------|----------------------|------------------|----------------|
| Healthy   | ✓                    | ✓                |                |
| Read-only | ✓                    |                  |                |
| Draining  | ✓                    |                  | ✓              |
| Offline   |                      |                  |                |
| Failed      |                      |                  | ✓              |

The "read-only", "draining", and "failed" states would be states manually set by an admin. Offline would be a temporary state where we expect the node to come back, and so the chunks on it shouldn't be rebuilt.

Also when in draining mode, I don't think it has to be restricted to just `move_chunk`. If another node in the cluster has the same chunk(s), those chunks could be copied from that node instead (and then subsequently deleted from the draining node). Basically "rebuild" just means "put chunk X on node Y", and it doesn't matter which node it gets the chunk from.

**Comment by wilfriedroset** [comment]
In the offline case, the access node would need to know if a chunk is _complete_ or not. Let's take an example:
* We have a 1 accessnode + 3 datanodes setup with replication factor=2
* `chunkN`  and `chunkN'` (replicated chunk) are hosted on `dnX` and `dnY`
* `dnY` goes offline for a small time then come back online while the cluster still taking writes
* my understanding is that `chunkN'` would need to be rebuilt as I will miss the  data written while `dnY` was offline.
* So the definition of the offline state should become: Offline would be a temporary... and so _most of_ the chunks on it shouldn't be rebuilt only the _latest_ chunks would need to be.

**Comment by erimatnor** [comment]
The drain case has certainly been discussed and is part of our design. However, the actual draining is probably logic that fits better in an orchestration framework. You need to decide on things like where should you "drain" all the chunks to (i.e., there's a chunk scheduling issue"). For instance, in a replication scenario, you don't want to copy a chunk to a node that already has a copy. Or, you could argue that there is nothing to drain if all chunks are already replicated.

Our intention at this point is to provide the APIs necessary to build higher-level orchestration on top of the database, but leave the actual orchestration outside the database. You also need things like "cordoning a node" (in Kubernetes terminology) in order to ensure that no new objects (e.g., chunks) are placed on the data node while it is being drained.

At this point it would be really useful for us to get input on the APIs that would be useful given the scenarios you are looking at. Feel free to give input on that in the issue.

**Comment by phemmer** [comment]
> The drain case has certainly been discussed and is part of our design. However, the actual draining is probably logic that fits better in an orchestration framework. You need to decide on things like where should you "drain" all the chunks to (i.e., there's a chunk scheduling issue"). For instance, in a replication scenario, you don't want to copy a chunk to a node that already has a copy. Or, you could argue that there is nothing to drain if all chunks are already replicated.

I feel like the reasons you mention are justification of why this should be built into timescaledb, and not external. After all timescaledb already has to solve many of these problems when deciding where to put new chunks as they're created. It's aware of the available nodes & the replication factor.
