### ISSUE TITLE
duplicate key value violates unique constraint after restore when create index

### ISSUE THREAD

**Issue by alx696** [timescale/timescaledb#3467]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.1
 - Installation method: apt installapt install

**Describe the bug**
After [restore](https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup/#procedure-restoring-your-database-from-backup) , when `create index if not exists asset_data_idx_j_id_btree on asset_data using btree ((j->'asset_id'));` :
```
ERROR: duplicate key value violates unique constraint "chunk_index_chunk_id_index_name_key" (SQLSTATE 23505)
```

**To Reproduce**

Server A(Docker Tiimescale):
1. `./ts-dump --db-URI=postgresql://postgres:password@127.0.0.1:51510/postgres --dump-dir=sjzdb`

Server B(apt install, have old table and data):
2. `sudo -u postgres psql`
3. `DROP SCHEMA public CASCADE;`
4. `CREATE SCHEMA public;`
5.  `./ts-restore --db-URI=postgresql://postgres:postgres@127.0.0.1:5432/postgres --dump-dir=sjzdb`
6.  `create index if not exists asset_data_idx_j_id_btree on asset_data using btree ((j->'asset_id'));`
7.  Error

![2021-08-10 13-21-12 的屏幕截图](https://user-images.githubusercontent.com/2497908/128812369-2d288d31-e8ab-4434-86f1-8f97181e736b.png)

**Expected behavior**
No Error when `create index if not exists`

**Actual behavior**
```
duplicate key value violates unique constraint "chunk_index_chunk_id_index_name_key" (SQLSTATE 23505)
```

**Additional context**

Server A query:
![2021-08-10 13-17-46 的屏幕截图](https://user-images.githubusercontent.com/2497908/128812219-a7149625-f2fb-4117-8a2a-25076382d503.png)
![2021-08-10 13-18-25 的屏幕截图](https://user-images.githubusercontent.com/2497908/128812230-17c295e2-60b3-4ece-b46d-2603c39c0fae.png)

Server B query:
![2021-08-10 13-19-04 的屏幕截图](https://user-images.githubusercontent.com/2497908/128812263-2741e42f-7788-447c-8e5d-62a8f87db37b.png)
![2021-08-10 13-19-26 的屏幕截图](https://user-images.githubusercontent.com/2497908/128812270-f7042cf1-e2d1-4cfb-a71d-7c29378eba6b.png)

If truncate table asset_data, no error.

**Comment by cheerfulstoic** [comment]
I just ran into this and found that if I tweaked the index name (like adding a `_` at the end) it created fine...

**Comment by erimatnor** [comment]
@feikesteenbergen Any idea if this is a timescaledb-backup issue?

**Comment by feikesteenbergen** [comment]
timescaledb-backup is only a wrapper around `pg_dump`, so it would not be the most obvious suspect.

What could be however, is that there is some kind of corruption on the source (an index for example), we can try to determine that by ensuring we don't use the index.

*Using indexes*
```sql
select
    chunk_id,
    index_name,
    schema_name,
    table_name
from
    _timescaledb_catalog.chunk_index
join
    _timescaledb_catalog.hypertable as h on hypertable_id = h.id
where
    table_name ilike '%asset_data%';
```

*Not using indexes*
```sql
begin;
set local enable_indexonlyscan to off;
set local enable_indexscan to off;
set local enable_bitmapscan to off;

select
    chunk_id,
    index_name,
    schema_name,
    table_name
from
    _timescaledb_catalog.chunk_index
join
    _timescaledb_catalog.hypertable as h on hypertable_id = h.id
where
    table_name ilike '%asset_data%';
rollback;
```

@alx696 could you execute both these pieces of SQL and tell us if they tell a different story?

**Comment by alx696** [comment]
@feikesteenbergen I'll try later. I have many tables, and errors will occur on one table at random.

**Comment by nikkhils** [comment]
@alx696 did you get a chance to try out the above pieces of sql?
