### ISSUE TITLE
Minor Documentation typos

### ISSUE THREAD

**Issue by campeterson** [timescale/timescaledb#347]
Just a couple minor issues in the Docs

Under the [Cumulative Sum](http://docs.timescale.com/latest/using-timescaledb/reading-data#cumulative-sum) section, the first row:

    SELECT host, sum(sum(temperature)) OVER(ORDER BY location)

should be:

    SELECT location, sum(sum(temperature)) OVER(ORDER BY location)

---

Also, in the [Moving Average](http://docs.timescale.com/latest/using-timescaledb/reading-data#moving-average) section, this row:

    WHERE location = 'garage' and time > NOW() - '1 day'

should be:

    WHERE location = 'garage' and time > NOW() - interval '1 day'

**Comment by solugebefola** [comment]
Thanks for the heads up!

**Comment by mfreed** [comment]
Deployed to docs:

http://docs.timescale.com/latest/using-timescaledb/reading-data#cumulative-sum
http://docs.timescale.com/latest/using-timescaledb/reading-data#moving-average
