### ISSUE TITLE
The hint for "no data nodes can be assigned to the hypertable" error ("Add data nodes to the database.") is not informative enough

### ISSUE THREAD

**Issue by emres** [timescale/timescaledb#3479]
**Relevant system information:**
 - OS: [Debian GNU/Linux version 10.10 ("buster")](https://www.debian.org/releases/buster/)
 - PostgreSQL version: 12.7
 - TimescaleDB version: 2.3.1
 - Installation method: "apt install"

**Describe the bug**
The **hint** for `no data nodes can be assigned to the hypertable` **error** (`Add data nodes to the database.`) is not informative enough.

I hit this case a few hours ago, when I tried to create a **distributed hypertable** on our 3-node (1 Access Node + 2 Data Nodes) TimescaleDB set-up. 

Timescale complained with the following:

`no data nodes can be assigned to the hypertable`

And suggested that I take the following action:

`HINT:  Add data nodes to the database.`

This **hint** can be very **_misleading_** because I had _already added data nodes for that database._ 

Only after a while, I realized that the problem could be about permissions/privileges, and running an SQL command such as `GRANT USAGE ON FOREIGN SERVER "ts-dn-01", "ts-dn-02" TO tsdb_energytix_user ;` solved the problem.

If the hint provided by TimescaleDB told me that not being able to assign data nodes could be related to such and such privilege/permission to such and such user, it would save me a lot of time.

**To Reproduce**
1. Create a new database on a multi-node set up.
2. Add data nodes.
2. **Do not** _grant usage on foreign server(s)_ for the relevant database role/user.
3. Create a table.
4. Create a distributed hypertable based on the table created in the previous step.
5. Observe the `no data nodes can be assigned to the hypertable` error.

**Expected behavior**
I'd expect the **hint** to tell me that not being able to assign data nodes can be also related such and such privilege/permission to such and such user, e.g. check `GRANT USAGE ON FOREIGN SERVER ...` step, etc.  it would save me a lot of time.

**Comment by mkindahl** [comment]
Thank you for the bug report @emres. It would indeed be easier to understand if the hint contained the reason for the failure.
