### ISSUE TITLE
`./bootstrap` doesn't run if `build` (from failed bootstrap) already exists

### ISSUE THREAD

**Issue by vjpr** [timescale/timescaledb#349]
```
$ ./bootstrap
./bootstrap: line 13: cmake: command not found
TimescaleDB build system initialized in ./build. To compile, do:
cd ./build && make

$ sudo apt-get install cmake

$ ./bootstrap
Build system already initialized in ./build

$ cd build && make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by mfreed** [comment]
Just remove the `build` directory and try again, it should work.

But thanks for the report; we should fix the bootstrap file to handle this
case directly (so I'll leave this issue open until we do).

**Comment by mfreed** [comment]
Has been *actually* fixed in: https://github.com/timescale/timescaledb/pull/358 Will be released in upcoming 0.8.0.

**Comment by RobAtticus** [comment]
0.8.0 has been released so this should work going forward. Please re-open if you have issues.

**Comment by EvanCarroll** [comment]
We can actually check if cmake exists and not create the directory if it doesn't. Or, even try to install it.
