### ISSUE TITLE
File not found - timescaledb.control

### ISSUE THREAD

**Issue by Rafael-006** [timescale/timescaledb#3492]
**Relevant system information:**
 - OS: Ubuntu 20.04.2 LTS
 - PostgreSQL version 13.4
 - Installation method: apt install

**Describe the bug**
I am following the official documentation to do a first time installation of timescaledb in my local machine. Everything worked fine for installation however i face an error when running migration for a table. I followed the quick start guide for node application.

Link for installation guide - [https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/#installation-apt-ubuntu](url)

Link for node application quick start - [https://docs.timescale.com/timescaledb/latest/quick-start/node/](url)

**Expected behavior**
Expected the migration to work

**Actual behavior**
Following error is returned while running migration,

`ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/timescaledb.control": No such file or directory
`

**Screenshots**
![Screenshot from 2021-08-17 18-13-37](https://user-images.githubusercontent.com/54441907/129727761-4fd48c27-f9d6-4486-8b06-498fb8f67348.png)

**Comment by svenklemm** [comment]
The control file is part of the loader package. Can you reinstall timescaledb-2-postgresql-13-loader.

**Comment by Rafael-006** [comment]
> The control file is part of the loader package. Can you reinstall timescaledb-2-postgresql-13-loader.

i tried uninstalling and reinstalling the timescaledb-2-postgresql-13-loader but that didn't work

**Comment by svenklemm** [comment]
Oh wait I see your error message references PG12 but you stated you are using PG13. Seems like you might have installed the extension for the wrong version. So you would have to reinstall timescaledb-2-postgresql-12-loader

**Comment by Rafael-006** [comment]
> Oh wait I see your error message references PG12 but you stated you are using PG13. Seems like you might have installed the extension for the wrong version. So you would have to reinstall timescaledb-2-postgresql-12-loader

Well that worked.

I had both 12 and 13 version of postgresql installed. I removed version 12 and tried but couldn't get that work. Then removed version 13 and installed the version 13 again.

Now i installed the TimescaleDB and able to run the migration.

Thanks.
