### ISSUE TITLE
Calling copy_chunk procedure within another procedure leads to the connection being terminated with error

### ISSUE THREAD

**Issue by TroyDey** [timescale/timescaledb#3495]
**Relevant system information:**
 - OS: Alpine, timescale/timescaledb:2.4.0-pg13, Host: OS X Catalina
 - PostgreSQL version (output of `postgres --version`): 13.3
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.0
 - Installation method: Docker

**Describe the bug**
Calling timescaledb_experimental.copy_chunk procedure within a procedure leads to this error:

WARNING:  transaction left non-empty SPI stack
HINT:  Check for missing "SPI_finish" calls.
WARNING:  snapshot 0x7fd931f07338 still active
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

After reconnecting to the database and examining timescaledb_experimental.chunk_replication_status the chunk is shown as replicated.  You can also directly log into the target data node and directly query the chunk.

**To Reproduce**
1. Setup a multi-node timescale cluster using docker.  I used docker-compose to launch 1 container for the access node and 3 containers for the data nodes.
2. Create a database.
3. Run the below script.
4. The script will fail and get disconnected, reconnect and examine the timescaledb_experimental.chunk_replication_status  table to see the chunk successfully copied.

```sql
-- Database needs to be created first

-- Create timescale extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Add the data nodes
SELECT add_data_node('dn1', host => 'tsdb-data1', password => 'password');
SELECT add_data_node('dn2', host => 'tsdb-data2', password => 'password');
SELECT add_data_node('dn3', host => 'tsdb-data3', password => 'password');

-- Authenticate to the data nodes
CREATE USER MAPPING FOR postgres SERVER dn1 OPTIONS (user 'postgres', password 'password');
CREATE USER MAPPING FOR postgres SERVER dn2 OPTIONS (user 'postgres', password 'password');
CREATE USER MAPPING FOR postgres SERVER dn3 OPTIONS (user 'postgres', password 'password');

-- Create a basic hypertable
CREATE TABLE metric (ts TIMESTAMPTZ NOT NULL, val FLOAT8 NOT NULL, dev_id INT4 NOT NULL);
SELECT create_distributed_hypertable('metric', 'ts', 'dev_id', chunk_time_interval => INTERVAL '1 hour', replication_factor => 2);

-- Insert some data to generate chunks
INSERT INTO metric (ts, val, dev_id) SELECT s.*, 3.14+1, 1 FROM generate_series('2021-08-17 00:00:00'::timestamp, '2021-08-17 00:02:00'::timestamp, '1 s'::interval) s;

-- Chunk the replication status
-- Should show desired_num_replicas = 2 and num_replicas = 2 and non_replica_node contains one data node, this seems to always be dn3
SELECT * FROM timescaledb_experimental.chunk_replication_status;

-- Create our sproc
CREATE OR REPLACE PROCEDURE copy_chunk_wrapper()
AS $proc$
BEGIN
    -- The way timescale names chunks as they are created is currently always the same
    -- This is the simplist possible version of this sproc
    CALL timescaledb_experimental.copy_chunk('_timescaledb_internal._dist_hyper_1_1_chunk', 'dn1', 'dn3');
END
$proc$
LANGUAGE PLPGSQL;

-- Call the sproc
-- The following output will be generated and the connection terminated
-- WARNING:  transaction left non-empty SPI stack
-- HINT:  Check for missing "SPI_finish" calls.
-- WARNING:  snapshot 0x7fd931f07338 still active
-- server closed the connection unexpectedly
--         This probably means the server terminated abnormally
--         before or while processing the request.
-- The connection to the server was lost. Attempting reset: Failed.
CALL copy_chunk_wrapper();

-- Reconnect and see that the chunk was indeed copied to dn3
SELECT * FROM timescaledb_experimental.chunk_replication_status;
```

**Expected behavior**
Call to copy_chunk within procedure succeeds

**Actual behavior**
Fails with "transaction left non-empty SPI stack"

**Additional context**
I was experimenting with creating a procedure to automatically recopy chunks to a failed data node that had to be temporarily removed from the cluster and ran across this error.

**Comment by mkindahl** [comment]
The problem occurs because the `copy_chunk` and `move_chunk` uses plumbing transaction commands (e.g., `CommitTransactionCommand()` and `StartTransactionCommand()`) from inside a PG procedure. Since these manipulate the SPI context, it will break when put inside PL/SQL procedures. We should instead use `SPI_commit` and friends.
