### ISSUE TITLE
duplicate key value violates unique constraint on extension update

### ISSUE THREAD

**Issue by jw1u1** [timescale/timescaledb#3506]
**Relevant system information:**
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - PostgreSQL version (output of `postgres --version`): 12.8
 - TimescaleDB version (output of `\dx` in `psql`):  installed_version | 1.7.5, default_version   | 2.3.0
 - Installation method: yum

**Describe the bug**
 ALTER EXTENSION timescaledb UPDATE;
ERROR:  duplicate key value violates unique constraint "saved_privs_tmpnsp_tmpname_key"
DETAIL:  Key (tmpnsp, tmpname)=(_timescaledb_catalog, tablespace_id_seq) already exists.

**To Reproduce**
1. install püostgres 10 with timescaledb 1.7.4
2. upgrade to  timescaledb 1.7.5
2. pg_upgrade to Postgres 12
3. Install timescaledb 2.3.0 for Pg 12
4. psql -X -c "ALTER EXTENSION timescaledb UPDATE;"

**Comment by jw1u1** [comment]
default version  2.4.1 does update properly

**Comment by mkindahl** [comment]
@jw1u1 Thanks for the bug report. This seems to be issue #3331, which was fixed in 2.3.1, so please try that version, or later, instead.
