### ISSUE TITLE
Allow restoring to a lower timescaledb version database with ts-restore

### ISSUE THREAD

**Issue by alex88** [timescale/timescaledb#3522]
Trying to debug a performance regression I was trying to restore our database into a docker container using a lower timescaledb version but I wasn't unable to becuase of this error:

```
2021/08/25 10:56:19 Error creating extension in correct schema and at correct version: ERROR: extension "timescaledb" has no installation script nor update path for version "2.4.0" (SQLSTATE 22023)
```

It would be nice to be able to do so since exporting/reimporting the data manually can be a long process especially when the involved tables depends on other tables.

This it the slack discussion regarding [this issue](https://timescaledb.slack.com/archives/C4GT3N90X/p1629915107018800?thread_ts=1629900377.002700&cid=C4GT3N90X)

**Comment by svenklemm** [comment]
Closing this since ts-restore has been deprecated. You can downgrade to the previous version with `ALTER EXTENSION timescaledb UPDATE TO "<previous>";`
