### ISSUE TITLE
Support for fillfactor table parameter

### ISSUE THREAD

**Issue by Anthares** [timescale/timescaledb#353]
Hi,

As suggested by mat on the slack channel, I'm filing this issue.

As per some Postgres experts, fillfactor is one of the most important parameter when it comes to performance. It allows to leave some space in data pages for records updates and reduces the number of pages needed to be read by the database to retrieve the right version of the record (due to Postgres' MVCC model).
But currently, this parameter is not cascaded to chunks. And trying to set it manually after chunk creation results in an error message.

We are planning to migrate to timescale in a near future, this feature is really important to us.
Can you provide an ETA to allow us adapt our migration plan if necessary ?

Thanks,

Regards,

Anthares

My test case is the following :
```SQL
CREATE TABLE public.fillfactor_test(
  id bigserial NOT NULL,
  creation_date timestamp,
  CONSTRAINT fillfactor_test_pk PRIMARY KEY (id, creation_date)
)
WITH (FILLFACTOR=75);

SELECT create_hypertable('fillfactor_test', 'creation_date', chunk_time_interval => interval '1 day');

insert into fillfactor_test(creation_date) values (now());
```
The resulting chunk (as displayed in pgAdmin):
```SQL
CREATE TABLE _timescaledb_internal._hyper_27_2835_chunk (
-- Inherited from table test_fillfactor:  id bigint NOT NULL DEFAULT nextval('test_fillfactor_id_seq'::regclass),
-- Inherited from table test_fillfactor:  creation_date timestamp without time zone NOT NULL,
  CONSTRAINT "2835_1429_test_fillfactor_pk" PRIMARY KEY (id, creation_date),
  CONSTRAINT constraint_2138 CHECK (creation_date >= '2017-12-07 01:00:00'::timestamp without time zone AND creation_date < '2017-12-08 01:00:00'::timestamp without time zone)
)
INHERITS (public.test_fillfactor)
WITH (
  OIDS=FALSE
);
```

**Comment by erimatnor** [comment]
Hi @Anthares. Support for `fillfactor` (and other storage parameters) is now in the reference PR above. This is part of a larger set of changes to how we deal with chunks and related objects, so we aren't yet sure if this will make it into the next release (0.8.0) or a release that follows.

**Comment by Anthares** [comment]
Hi @erimatnor !
Thanks for the reply, we will check milestone 0.8.0 or next one :)

**Comment by Anthares** [comment]
Hi guys,

Since 0.8.0 is out, I was wondering if you have any clue if this can be part of 0.8.x or 0.9.0 ?
I checked status of PR #357 and fix regarding reloptions is no longer part of it.
We are still heavily testing timescale with the goal of going to production ASAP, but not having the ability of cascading those options to chunks still seems a no-go to us regarding our workload.

Anyway, thanks for the job already done :)

**Comment by RobAtticus** [comment]
Yes unfortunately that did not make 0.8.0 because of time constraints (we wanted 0.8.0 to go out with enough time before the holidays). Our intention would then be to have it in the next feature release (0.9.0) I believe.

**Comment by Anthares** [comment]
OK, thanks for the reply.

As far as I can see, you seems to make something like a feature release by month, so we can expect this to be out by the end of January ? No pressure, juste asking for us to sync we our release plan.

**Comment by RobAtticus** [comment]
That seems reasonable. We don't specifically schedule the releases a month apart, but we also don't want to wait too long and keep users from getting the latest features easily. The holidays might slow it down a bit but I would expect a feature release in Jan

**Comment by erimatnor** [comment]
Reopening this issue since closed by PR https://github.com/timescale/timescaledb/pull/357. However, the fix was moved out of that PR and into a separate PR https://github.com/timescale/timescaledb/pull/375

**Comment by RobAtticus** [comment]
Hi @Anthares , 0.9.0 went out earlier this week and this PR made it in. Please test it out and feel free to close the issue if all is well

**Comment by Anthares** [comment]
Hi @erimatnor @RobAtticus,
I just checked the test case I reported and it is working fine.
I also checked an `alter table fillfactor_test set (FILLFACTOR=90);` and it's okay too.
Thanks for the work done :)
