### ISSUE TITLE
create_distributed_hypertable() fails when using custom type & non-public schema.

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3543]
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: Debian 10/Buster
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 13.4 (Debian 13.4-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt

**Describe the bug**
When attempting to create a distributed hypertable in a non-public schema containing a custom type, an error is returned:
```
ERROR:  [datanode1]: type "uint8" does not exist
```

**To Reproduce**
1. Install [pguint](https://github.com/petere/pguint)
2. `create schema myschema`
3. `create table myschema.test (time timestamp, a uint8)`
4. `select create_distributed_hypertable('"myschema"."test"', 'time')`

**Expected behavior**
success

**Actual behavior**
```
ERROR:  [datanode1]: type "uint8" does not exist
```

**Screenshots**

**Additional context**
Works fine if not distributed, or not in an alternate schema. For example:

##### schema=public function=create_hypertable ✓
```
=> create table test (time timestamp, a uint8);
CREATE TABLE
=> select create_hypertable('test', 'time');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
  create_hypertable  
---------------------
 (138,public,test,t)
(1 row)
```

##### schema=public function=create_distributed_hypertable ✓
```
=> create table test (time timestamp, a uint8);
CREATE TABLE
=> select create_distributed_hypertable('test', 'time');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
 create_distributed_hypertable 
-------------------------------
 (139,public,test,t)
(1 row)
```

##### schema=myschema function=create_hypertable ✓
```
=> create table myschema.test (time timestamp, a uint8);
CREATE TABLE
=> select create_hypertable('"myschema"."test"', 'time');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
   create_hypertable   
-----------------------
 (142,myschema,test,t)
(1 row)
```

##### schema=myschema function=create_distributed_hypertable ✗
```
=> create table myschema.test (time timestamp, a uint8);
CREATE TABLE
=> select create_distributed_hypertable('"myschema"."test"', 'time');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
ERROR:  [datanode1]: type "uint8" does not exist
```

**Comment by gayyappan** [comment]
@phemmer Have you tried manually creating uint8 type on **all** the data nodes and then executing create_distributed_hypertable? Does that work?

**Comment by phemmer** [comment]
The extension (and data type) is installed on all nodes. Note the test above labeled "schema=public function=create_distributed_hypertable".

**Comment by gayyappan** [comment]
@phemmer Could you post the output for `show search_path` for both cases : create_distributed_hypertable that  succeeds and the one that fails ?

**Comment by phemmer** [comment]
I'm not sure how to do that for the remote node. From the message output above, it looks like it's failing on the data node, not the access node. I can manually connect to the DB on that node, but I don't know how to replicate the same environment as what timescaledb has when it connects.

For the access node where I'm running the statements, it's:
```
=> show search_path;
   search_path   
-----------------
 "$user", public
(1 row)
```

**Comment by phemmer** [comment]
Thought of a way to get `search_path` from the remote nodes:
```
=> call distributed_exec($$ create table sp (search_path text) $$);

=> call distributed_exec($$ insert into sp select current_setting('search_path') $$);
```
Then on each data node:
```
=> select * from sp;
         search_path         
-----------------------------
 "$user", public, pg_catalog
(1 row)
```

**Comment by phemmer** [comment]
Ok, so I found the issue.

I set `log_statement = all`, and I see the following statements being executed when it establishes the connection:
```
LOG:  statement: SET search_path = pg_catalog;SET datestyle = ISO;SET intervalstyle = postgres;SET extra_float_digits = 3;
LOG:  statement: SET TIMEZONE = 'GMT'
LOG:  statement: SELECT extversion FROM pg_extension WHERE extname = 'timescaledb'
LOG:  statement: SELECT * FROM _timescaledb_internal.set_peer_dist_id('ef362ddd-2a35-4d1e-84de-ed8d2b27f88c')
```

The reason why the `call distributed_exec()` doesn't detect it, and show that search path, is because it's temporarily overridden:
```
LOG:  execute <unnamed>: SET search_path = "$user", public, pg_catalog
LOG:  execute <unnamed>:  insert into myschema.sp select current_setting('search_path')
LOG:  execute <unnamed>: SET search_path = pg_catalog
LOG:  execute <unnamed>: PREPARE TRANSACTION 'ts-1-158496-235664-16386'
LOG:  execute <unnamed>: COMMIT PREPARED 'ts-1-158496-235664-16386'
```

And when calling `create_distributed_hypertable()` it is not being overridden:
```
LOG:  statement: START TRANSACTION ISOLATION LEVEL REPEATABLE READ
LOG:  execute <unnamed>: SET SCHEMA 'myschema';
LOG:  execute <unnamed>: CREATE TABLE "myschema"."test" ("time" timestamp without time zone NOT NULL, "a" uint8) USING "heap" ;
ERROR:  type "uint8" does not exist at character 82
STATEMENT:  CREATE TABLE "myschema"."test" ("time" timestamp without time zone NOT NULL, "a" uint8) USING "heap" ;
LOG:  execute <unnamed>: ROLLBACK TRANSACTION
```

**Comment by phemmer** [comment]
I just ran across this function in the code, which has a documentation comment that seems highly relevant:
https://github.com/timescale/timescaledb/blob/dd3e422964f9a0d8a913d03ae2da2ad64799f3f8/tsl/src/fdw/deparse.c#L665-L685

So maybe the solution is as simple as swapping `format_type_with_typemod()` with `deparse_type_name()` in `deparse_columns()`:
https://github.com/timescale/timescaledb/blob/d0426ff23488abb8a1e7f684f7a9e8c86017411a/tsl/src/deparse.c#L177-L180

**Comment by nikkhils** [comment]
@phemmer thanks for the accurate analysis! We will try to get this in for the next release
