### ISSUE TITLE
Background worker fails, on PG13.4, if the registered procedure has commit.

### ISSUE THREAD

**Issue by gayyappan** [timescale/timescaledb#3545]
Steps to reproduce:
Create a table conditions with compression enabled and some uncompressed chunks.

CREATE TABLE conditions (
      time        TIMESTAMPTZ       NOT NULL,
      location    TEXT              NOT NULL,
      location2    char(10)              NOT NULL,
      temperature DOUBLE PRECISION  NULL,
      humidity    DOUBLE PRECISION  NULL
    );
select create_hypertable( 'conditions', 'time', chunk_time_interval=> '31days'::interval);
alter table conditions set (timescaledb.compress, timescaledb.compress_segmentby = 'location', timescaledb.compress_orderby = 'time');
insert into conditions
select generate_series('2018-12-01 00:00'::timestamp, '2018-12-31 00:00'::timestamp, '1 day'), 'POR', 'klick', 55, 75;

---create custom procedure to compress the chunks ---
CREATE OR REPLACE PROCEDURE my_policy(dummy integer, config jsonb)
AS $$
DECLARE
    r regclass;
BEGIN
    FOR r IN
        SELECT *
        FROM show_chunks('conditions') 
    LOOP
        PERFORM compress_chunk( r );
       COMMIT;   ----> works if commit is disabled
    END LOOP;
END;
$$ LANGUAGE PLPGSQL;

select add_job( 'my_policy', '24h');

**Job fails with following errors in the log file when the background worker runs it **

2021-09-02 15:21:43.847 EDT [18881] CONTEXT:  SQL statement "SELECT compress_chunk( r )"
    PL/pgSQL function my_policy(integer,jsonb) line 11 at PERFORM
2021-09-02 15:21:43.853 EDT [18881] LOG:  job 1002 threw an error
2021-09-02 15:21:43.853 EDT [18881] ERROR:  portal snapshots (0) did not account for all active snapshots (1)
2021-09-02 15:21:43.853 EDT [18881] CONTEXT:  PL/pgSQL function my_policy(integer,jsonb) line 12 at COMMIT

**Comment by gayyappan** [comment]
This is probably related to: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=84f5c2908dad81e8622b0406beea580e40bb03ac

**Comment by mkindahl** [comment]
Seems related to this: https://github.com/timescale/timescaledb/pull/3510, which fixes https://github.com/timescale/timescaledb/issues/3495

**Comment by fabriziomello** [comment]
@mkindahl there are some good reason to don't use the entire SPI api?? I mean use SPI_connect, SPI_exec, etc...

**Comment by mgagliardo91** [comment]
Also running into this issue, please update on an ETA of the fix if you have one. This breaks the https://github.com/timescale/timescaledb-extras/blob/master/backfill.sql job as it cannot call `COMMIT` from the scope of the background worker.

**Comment by fabriziomello** [comment]
@mgagliardo91 I think by tomorrow we'll merge the PR that fix this issue: https://github.com/timescale/timescaledb/pull/3574

**Comment by fabriziomello** [comment]
PR merged: https://github.com/timescale/timescaledb/pull/3574
