### ISSUE TITLE
Follow the doc, but the test practice shows performance much slower

### ISSUE THREAD

**Issue by JH-D** [timescale/timescaledb#3547]
Especially the "**Each truck and its last known location**" test case, the page said can be Real-time, **but in practice the test even can't finished after hours**, can see the benchmark database's SELECT process is keep running.

![图片](https://user-images.githubusercontent.com/7844108/131935703-2483b894-ab4c-4b6b-a742-a8fa563f32dd.png)

Introduction page: https://blog.timescale.com/blog/how-to-benchmark-iot-time-series-workloads-in-a-production-environment/
In practice test steps: https://github.com/timescale/tsbs/issues/177

**Comment by gayyappan** [comment]
see https://github.com/timescale/tsbs/issues/177 for followup.

**Comment by NunoFilipeSantos** [comment]
Closing. Discussion on timescale/tsbs#177 .
