### ISSUE TITLE
Spikes of the slow queries

### ISSUE THREAD

**Issue by john9x** [timescale/timescaledb#3548]
Hello!

We try to migrate our data from MySQL to TSDB but I faced with next problem.
Sometimes one type of query executes dramatically slow (5, 15, 30, 60 seconds!) and I don't understand why. 
I don't see any IO bottlenecks or something else. And when I execute request manually it executes fast.
May be you can help me.

Query example, insignificant fields are omitted
```
duration: 38046.571 ms  execute S_2: SELECT fields
        FROM bucket_1
        WHERE source_id=10043496  AND '2021-09-03 07:30:07' > get_time AND (CAST('2021-09-03 07:00:07' AS timestamp) IS NULL OR get_time > CAST('2021-09-03 07:00:07' AS timestamp))
        ORDER BY get_time DESC LIMIT 1
```

hypertable
```
select * from create_hypertable('bucket_1','get_time', chunk_time_interval => INTERVAL '7 days');
```

DDL,  insignificant fields are omitted
```
CREATE TABLE bucket_1 (
	source_id int4 NOT NULL,
	get_time timestamp NOT NULL
);
CREATE INDEX bucket_1_get_time_idx ON bucket_1 USING btree (get_time DESC);
CREATE INDEX bucket_1_src_get_time_desc_idx ON bucket_1 USING btree (source_id, get_time DESC);
```
query plan
```
                                                                                         QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..1.71 rows=1 width=166) (actual time=0.014..0.015 rows=0 loops=1)
   ->  Result  (cost=0.56..12.03 rows=10 width=166) (actual time=0.013..0.013 rows=0 loops=1)
         ->  Index Scan using _tr_b_1_h_2039_chunk_bucket_1_src_get_time_desc_idx on _tr_b_1_h_2039_chunk  (cost=0.56..11.73 rows=10 width=52) (actual time=0.013..0.013 rows=0 loops=1)
               Index Cond: ((source_id = 10043496) AND (get_time < '2021-09-03 07:30:07'::timestamp without time zone) AND (get_time > '2021-09-03 07:00:07'::timestamp without time zone))
 Planning Time: 0.419 ms
 Execution Time: 0.053 ms
(6 rows)

```

hypertable_detailed_size
```
table_bytes |index_bytes|toast_bytes|total_bytes |node_name|
------------+-----------+-----------+------------+---------+
273090740224|98488057856|42421174272|413999980544|         |
```

Server 8 core, 32Gb 
Ubuntu 20.04.3
PG 13
TSDB 2.4.1

**Comment by john9x** [comment]
When we try to execute more queries like this one in parallel PG eats all CPU time, all IOPS and LA jumps to the sky. :(

BTW I forgot one thing -  chunks older than 7 months is compressed.
```
ALTER TABLE bucket SET (timescaledb.compress, timescaledb.compress_orderby = 'get_time ASC', timescaledb.compress_segmentby = 'source_id');
```

**Comment by erimatnor** [comment]
The query plan doesn't show any slowness. Could you please provide the explain of a plan/execution that shows the slow behavior?

**Comment by john9x** [comment]
> Could you please provide the explain of a plan/execution that shows the slow behavior?

Unfortunately, no. All EXPLAINs that I did looks normal. Difference depends on queried time interval.
When I remove from query NULL workaround `CAST('2021-09-03 07:00:07' AS timestamp) IS NULL OR` performance increasing significantly. But still I see random queries with 5 - 10 - 20 seconds execution time, very much less, but nevertheless.

We have a few query types:

- get last value for source - `source_id=X ORDER BY get_time DESC LIMIT 1`
- last value before given time - `source_id=X AND get_time>Y AND get_time<Z ORDER BY get_time DESC LIMIT 1`
- next value after given time - `source_id=X AND get_time>Y AND get_time<Z  ORDER BY get_time ASC LIMIT 1`

In MySQL our data stored at 16 tables partitioned by source_id hash (50 partitions) and median execution time of all queries is near 1 ms, 99 percentile - 50ms, max 200 ms.
In PG + TSDB all data joined to one hypertable and median execution is 5 - 20 ms depends on query, 99percentile - 500ms, max - 5-20 seconds.
5-20 ms is acceptable, but 5-20 seconds...
