### ISSUE TITLE
Syncrhonize Timescale db to handle with custom intervals 

### ISSUE THREAD

**Issue by ohadkorenok** [timescale/timescaledb#3552]
Hey, I am willing to collect weird time intervals using continous aggregations, such as 37 minutes and my intervals will start every day at 00:00.
So for example, I am willing to have an interval starts each day at 00:00, 00:37, 01:14... until 23:26, and then start all over from 00:00, 00:37... and so forth until 23:26 again.

Of course that I would like to make them at the same view and not create every day a new hyper table for this.

How can i make this up using timescaledb?

I have looked it up at the docs and wasn't sure what should I use... Is it refresh policies? Origin? offsets?

Thank you very much, help is super appreciated
Ohad

**Comment by erimatnor** [comment]
You can automate continuous aggregate refreshing with a policy. To ask further questions related to the usage of continuous aggregates I would recommend our [Slack community](https://slack.timescale.com).
