### ISSUE TITLE
 [error] failed copying `timescaledb_toolkit.control` to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by enthusiastics** [timescale/timescaledb#3561]
I'm following the instruction to setup timescaledb and timescaledbtoolset on aws .. However, I got this error: 

```
ubuntu@ip-32.421.12.93:~/timescale-analytics/extension$ cargo pgx install --release && cargo run --manifest-qpath ../tools/post-install/Cargo.toml -- pg_config
building extension with features `pg13`
"cargo" "build" "--release" "--features" "pg13" "--no-default-features"
    Finished release [optimized + debuginfo] target(s) in 0.11s

```

> installing extension
>       Copying control file to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`
>       [error] failed copying `timescaledb_toolkit.control` to `/usr/share/postgresql/13/extension/timescaledb_toolkit.control`: Operation not permitted (os error 1)
> 

Sure, I could sudo copy myself... But i'm not sure if any other error would occur if I do this step...

sudo cargo does not work....

**Comment by enthusiastics** [comment]
I'm trying sudo su becoming root and rerun all the installations again

**Comment by enthusiastics** [comment]
if i used sudo user all the way... the i got error when trying to do initdb...

**Comment by erimatnor** [comment]
If the current user doesn't have permission to install in the target location, you need to install as a user that has the proper permissions.

Closing since not a timescaledb extension issue.
