### ISSUE TITLE
use a docker that already installed timescale-toolkit 

### ISSUE THREAD

**Issue by enthusiastics** [timescale/timescaledb#3563]
I could run with 

`docker container  run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=fdfwueuhqidagduasgsuasdgy -e PGDATA=/pgdata -v ~/pgdata:/pgdata timescale/timescaledb:latest-pg13
`

to launch a timescaledb instance with success, however, I figured that timescale-toolkit is not installed... so i am then looking for a version with timescale-toolkit installed. So i found this high availability function and try:

`
docker container  run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=fdfwueuhqidagduasgsuasdgy -e PGDATA=/pgdata -v ~/pgdata:/pgdata timescale/timescaledb-ha:pg13-latest
`

However,  it failed by looking at 
```
~$ docker container exec -it timescaledb bash
Error response from daemon: Container 61549e85257d6898b4d5470918fdff64a10c5e4e81a008990a5660cbc4c25e74 is not running
```

I would like to ask which docker image has timescale-toolkit available and runnable?

**Comment by erimatnor** [comment]
We currently do not bundle timescaledb_toolkit in the official Docker image but might do it in the future. Timescale Cloud has it pre-installed.

You can also open a request in the timescaledb-docker repo.
