### ISSUE TITLE
trying to setup timescaledb-ha edition

### ISSUE THREAD

**Issue by enthusiastics** [timescale/timescaledb#3564]
I'm trying to setup timescaledb high availability edition with the following command on a aws ubuntu instance... However, I got this error... could anyone help?

    (base) ubuntu@ip-321-12-32-154:~$ sudo docker run -ti --user 1000:1000 --volume=/tmp/vmount:/home/postgresql/pgdata --rm -e POSTGRES_PASSWORD=sdafasd -e PGDATA=/home/postgresql/pgdata timescale/timescaledb-ha:pg13-latest
    chmod: changing permissions of '/home/postgresql/pgdata': Operation not permitted
    The files belonging to this database system will be owned by user "postgres".
    This user must also own the server process.
    
    The database cluster will be initialized with locale "C.UTF-8".
    The default database encoding has accordingly been set to "UTF8".
    The default text search configuration will be set to "english".
    
    Data page checksums are disabled.
    
    fixing permissions on existing directory /home/postgresql/pgdata ... initdb: error: could not change permissions of directory "/home/postgresql/pgdata": Operation not permitted

**Comment by erimatnor** [comment]
This issue isn't related to the TimescaleDB extension. Please file a bug in, e.g., the [timescaledb-docker-ha](https://github.com/timescale/timescaledb-docker-ha) repo if you think there is an issue with that image.
