### ISSUE TITLE
timescaledb extract continuous aggregate as another hypertable

### ISSUE THREAD

**Issue by enthusiastics** [timescale/timescaledb#3578]
From what I understood so far, the internal implementation of created continuous aggregate (CAGG) is by using another hypertable. But the result is demonstrated to us using a materialized view. I would like to ask is it possible to explicitly create such hypertable. So that I could Create another CAGG on top of the previous CAGG?

**Comment by erimatnor** [comment]
The internal implementation stores data in a non-final form. You could SELECT from the cagg and insert into a new hypertable with a query similar to:

```
INSERT INTO new_hypartable FROM SELECT * FROM cagg;
```
