### ISSUE TITLE
Alter table alter type on distributed hypertable

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3582]
**Relevant system information:**
 - OS: Debian 10/Buster
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 13.4 (Debian 13.4-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt

**Describe the bug**
Attempting to change the data type of a distributed hypertable results in `ERROR:  operation not supported on distributed hypertable`

**To Reproduce**
1. `create table test (time timestamp, v int);`
2. `select create_distributed_hypertable('test','time');`
3. `alter table test alter v type bigint;`

**Expected behavior**
Success

**Actual behavior**

    ERROR:  operation not supported on distributed hypertable

**Additional context**
[The documentation](https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/alter/) indicates that ALTER is supported, and gives no indication of any limitations.

I also [raised the issue in the slack channel](https://timescaledb.slack.com/archives/CPSD82EMU/p1631621121081600), and was directed to report it here.

**Comment by nikkhils** [comment]
Let's see if the documenrtation needs a sample ALTER TYPE command as well.
