### ISSUE TITLE
Cannot install timescaledb on Ubuntu 18.04.5 LTS x86_64. Unable to locate package

### ISSUE THREAD

**Issue by mtomeh-clgx** [timescale/timescaledb#3583]
Relevant system information:

OS: Ubuntu 18.04.5 LTS x86_64
PostgreSQL version : Postgres 12.8
TimescaleDB version:  1.7.5
Installation method: sudo apt install timescaledb-2-loader-postgresql-12
Describe the bug :  Package not found. Error: 

~> sudo apt install timescaledb-2-postgresql-12
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package timescaledb-2-postgresql-12

I follow these steps
https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/#installation-apt-ubuntu

Please advise. Thank you!

**Comment by svenklemm** [comment]
If you want to install 1.7 ubuntu packages in addition to packagecloud you also need to add the ppa.

https://legacy-docs.timescale.com/v1.7/getting-started/installation/ubuntu/installation-apt-ubuntu

1.7 is a very old version and you should consider upgrading to latest version.

**Comment by mtomeh-clgx** [comment]
I was trying to upgrade from 1.7 to 2.4. so current version timescaleDB is 1.7 on one machine (that's why I referenced 1.7 in the issue).  However, even on separate a fresh postgres server without timescaledb installed, we're getting the same issue. One observation is when  running "sudo apt update" it shows error with "public key " for  timescaledb. see output below:

Get:7 https://packagecloud.io/timescale/timescaledb/ubuntu bionic InRelease [23.2 kB]
Err:7 https://packagecloud.io/timescale/timescaledb/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E7391C94080429FF
Reading package lists... Done
.
.
W: GPG error: https://packagecloud.io/timescale/timescaledb/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E7391C94080429FF
E: The repository 'https://packagecloud.io/timescale/timescaledb/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by svenklemm** [comment]
Did you import the gpg keys? We test package installation nightly and there were no errors recently. 

https://github.com/timescale/timescaledb/blob/master/.github/workflows/apt-packages.yaml
https://github.com/timescale/timescaledb/actions/runs/1239664978
