### ISSUE TITLE
Can't restore one chunk from backup

### ISSUE THREAD

**Issue by 01012** [timescale/timescaledb#3584]
**Relevant system information:**
 - OS: docker container (Alpine), host Debian GNU/Linux 10 (buster) 
 - PostgreSQL version (output of `postgres --version`): 10.16
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: using Docker timescale/timescaledb-postgis:1.7.4-pg10

**Describe the bug**
I have an issue with one hypertable and specifically with one chunk. I'm trying to drop this chunk and restore from backup and after that i could select data from this chunk from hypertable:
`SELECT ST_AsText("Location"), "DateAt" FROM "MyTable" where "DateAt" >= '2021-06-28' and "DateAt" < '2021-06-30';`
 but this chunk ceases to be part of hypertable. I am trying to use functions to work with hypertables, but I get the error:
`SELECT reorder_chunk('_timescaledb_internal._hyper_1_54_chunk', 'conditions_device_id_time_idx');`
`ERROR: "_hyper_1_54_chunk" is not a chunk` 
`SELECT show_chunks('"MyTable"');` 
 chunk is not listed

**To Reproduce**
1. `pg_dump -U postgres  -t _timescaledb_internal._hyper_1_54_chunk Database -Fc | gzip -7 > /backup/onetable.dump.gz`
2. `DROP TABLE _timescaledb_internal._hyper_1_54_chunk;`
3. `pg_restore -U postgres -d Database ./onetable.dump`
4. `SELECT reorder_chunk('_timescaledb_internal._hyper_1_54_chunk', 'conditions_device_id_time_idx');`
`ERROR: "_hyper_1_54_chunk" is not a chunk`
5. `SELECT show_chunks('"MyTable"'); ` chunk is not listed

**Expected behavior**
After restore chunk becomes part of hypertable

**Actual behavior**
After restore chunk relate to hypertable but not part of hypertable

**Comment by svenklemm** [comment]
Hmm if you only dump the data of a chunk but not the metadata you should not have dropped the table like that. You should have instead called truncate on the chunk and then load data from backup.

**Comment by 01012** [comment]
Thanks a lot!
