### ISSUE TITLE
Multinode join not pushing condition to remote

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3585]
**Relevant system information:**
 - OS: Debian 10/Buster
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 13.4 (Debian 13.4-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt

**Describe the bug**
When a query uses filter against a lookup table, the filter condition is not evaluated prior to dispatching the query to the remote, causing the remote to do a scan across more data than it needs.

This is difficult to explain, so the below example would make more sense.

**To Reproduce**
```sql
create table t1 (time timestamp, fkey int, val int);

create table t2 (fkey int, foo int);

select create_distributed_hypertable('t1', 'time', partitioning_column=>'fkey');

insert into t2 values (1,1),(2,2);

insert into t1 values (now(), 1, 1),(now(), 2, 2),(now(), 3, 3);

explain verbose select count(*) from t1 where fkey in (select fkey from t2 /* optional conditions here */);
```
^ There are other ways to write that final query, but I figure a subquery should make it super obvious to the query planer what is being done.

**Expected behavior**
The query sent to the remote should include a filter on `fkey` such as `WHERE fkey IN (1,2)`;

**Actual behavior**
The query sent to the remote retrieves all rows, regardless of the `fkey` value.

```sql
explain verbose select count(*) from t1 where fkey in (select fkey from t2);
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=3033754.82..3033754.83 rows=1 width=8)
   Output: count(*)
   ->  Hash Join  (cost=142.75..2954518.47 rows=31694538 width=0)
         Inner Unique: true
         Hash Cond: (t1.fkey = t2.fkey)
         ->  Custom Scan (AsyncAppend)  (cost=100.00..2435477.66 rows=63389076 width=4)
               Output: t1.fkey
               ->  Append  (cost=100.00..2435477.66 rows=63389076 width=4)
                     ->  Custom Scan (DataNodeScan) on public.t1 t1_1  (cost=100.00..1059266.14 rows=31694538 width=4)
                           Output: t1_1.fkey
                           Data node: ded4077
                           Chunks: _dist_hyper_2916_4002_chunk
                           Remote SQL: SELECT fkey FROM public.t1 WHERE _timescaledb_internal.chunks_in(public.t1.*, ARRAY[4212])
                     ->  Custom Scan (DataNodeScan) on public.t1 t1_2  (cost=100.00..1059266.14 rows=31694538 width=4)
                           Output: t1_2.fkey
                           Data node: ded4086
                           Chunks: _dist_hyper_2916_4003_chunk
                           Remote SQL: SELECT fkey FROM public.t1 WHERE _timescaledb_internal.chunks_in(public.t1.*, ARRAY[4223])
         ->  Hash  (cost=40.25..40.25 rows=200 width=4)
               Output: t2.fkey
               ->  HashAggregate  (cost=38.25..40.25 rows=200 width=4)
                     Output: t2.fkey
                     Group Key: t2.fkey
                     ->  Seq Scan on public.t2  (cost=0.00..32.60 rows=2260 width=4)
                           Output: t2.fkey
```

**Additional context**
In the real world, I have a query that takes several minutes when I try to do this. If I instead manually explode the subquery, and then add a `WHERE mycol IN (...)` to the query on the data node, it completes in under a second.

Being able to use this type of query is important as lookup tables are common in database design. In addition, the telegraf timescaledb plugin uses this scheme for storing tags, which means this will be very common for anyone using it.  
In fact this is basically a blocker for us deploying telegraf, as we cannot query the data if it's going to take several minutes.

**Comment by phemmer** [comment]
From trying to find a workaround for this, I think this may not be timescaledb issue, but general postgres limitation.  
I'm assuming timescaledb essentially operates with the data nodes as FDWs, and is just using the postgres query planner to figure out what query to push to the remote nodes. So I don't know what influence timescaledb has over the query planner, and if this is something timescaledb can control if postgres can't do it natively.

So I'm not sure where that leaves this issue. If it's a bug report, feature request, or question.  
Though I feel like telegraf (and lookup tables in general) is a big enough use case that this is something that should be supported if possible.

**Comment by erimatnor** [comment]
There are many potential push-downs that can be done that we do not support at this point, but it is something we aim to continuously work on. Ideally, you'd push down the whole JOIN, but that requires also the table you are joining with being distributed and partitioned in a way that allows for joins on individual nodes.

**Comment by akuzm** [comment]
A similar issue that mentions a workaround: https://github.com/timescale/timescaledb/issues/4305

**Comment by phemmer** [comment]
closing as multinode is deprecated (I also gave up on it a long time ago)
