### ISSUE TITLE
`ts_insert_blocker` trigger goes missing after a `ts-dump` / `ts-restore`

### ISSUE THREAD

**Issue by cheerfulstoic** [timescale/timescaledb#3589]
**Relevant system information:**
 - OS: `timescale/timescaledb:2.2.0-pg13` Docker image.  Output of `uname -a`: `Linux timescaledb-0 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 Linux`
 - PostgreSQL version (output of `postgres --version`): `postgres (PostgreSQL) 13.2`
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.0
 - Installation method: using Docker

**Describe the bug**

I ran a `ts-dump` and `ts-restore` of my database and noticed that afterward I was missing the following line when doing `\d table_name`:

```
Triggers:
    ts_insert_blocker BEFORE INSERT ON water_switch FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
```

I asked about it in [this Slack thread](https://timescaledb.slack.com/archives/C4GT3N90X/p1631187023326200) and there wasn't a clear answer as to why.  It seems like it's not a huge problem for the moment, though.

Since I hadn't saved the logs at the time I couldn't see if there were errors.  David suggested that the next time I tried it I should save the logs and if the same thing happened and there were no errors that I should open an issue.  It did and I've made [this gist](https://gist.github.com/cheerfulstoic/9972a120cba3a9fa106944a471bf6532) of the log output.

I've noticed this when doing a dump / restore on five different databases in five different namespaces in our kubernetes clusters.

**To Reproduce**

1.) Check `\d table_name` in a hypetable to see that the trigger is there
2.) Connect to PostgreSQL / TimescaleDB in docker container in kubernetes via port mapping: `kubectl port-forward -n namespace timescaledb-0 5432:5432`
3.) ts-dump --db-URI=postgresql://postgres:<password>@localhost/<database> --dump-dir=<local_path>
4.) ts-restore --db-URI=postgresql://postgres:<password>@localhost/<database> --dump-dir=<local_path>
5.) Check `\d table_name` and see that trigger is missing

**Expected behavior**
Trigger is restored

**Actual behavior**
Trigger is missing

**Comment by RafiaSabih** [comment]
Closing since ts-dump/ts-restore are deprecated.
