### ISSUE TITLE
How to get timestamp associated with percentile(x) value using timescale db time_bucket?

### ISSUE THREAD

**Issue by sprasoon** [timescale/timescaledb#3591]
I need find percentile(50) value and its timestamp using timescale db time-bucket. Finding P50 is easy but I don't know how to get the time stamp.

    Select time_bucket('120 sec',timestamp_utc) as interval_size,
    first(timestamp_utc,int_val) as minTime,
    min(int_val) as minVal,
        
    last(timestamp_utc,int_val) as maxTime,
    max(int_val) as maxVal,
    
    -- timestamp of percentile value below.
    percentile_disc(0.5) within group (order by int_val) as medianVal
            
    from timeseries.raw
    where timestamp_utc > NOW() - INTERVAL '10 min'
    AND tag_id = 59560544877390423
    group by interval_size
    order by interval_size desc

**Comment by nikkhils** [comment]
Hi @sprasoon can you please discuss this on Timescale community slack channels? You can join here: https://timescaledb.slack.com/join/shared_invite/zt-w8oilh9u-BloBaSaPlAoklVFyLRySCQ#/shared-invite/email

**Comment by afiskon** [comment]
@sprasoon this seems to be a basic PostgreSQL GROUP BY query without anything specific to TimescaleDB, unless I'm missing something:

```
26267 (master) =# select * from conditions;
    day     |  city  | temperature
------------+--------+-------------
 2021-06-14 | Moscow |          26
 2021-06-15 | Moscow |          22
 2021-06-16 | Moscow |          24
 2021-06-17 | Moscow |          24
 2021-06-18 | Moscow |          27
 2021-06-19 | Moscow |          28
 2021-06-20 | Moscow |          30
 2021-06-21 | Moscow |          31
 2021-06-22 | Moscow |          34
 2021-06-23 | Moscow |          34
 2021-06-24 | Moscow |          34
 2021-06-25 | Moscow |          32
 2021-06-26 | Moscow |          32
 2021-06-27 | Moscow |          31
(14 rows)

Time: 0.930 ms
26267 (master) =# select time_bucket('7 days', day) as bucket, percentile_disc(0.5) WITHIN GROUP ( ORDER BY temperature ) from conditions GROUP BY bucket;
   bucket   | percentile_disc
------------+-----------------
 2021-06-14 |              26
 2021-06-21 |              32
(2 rows)
```

Please see PostgreSQL documentation for more details, e.g. https://www.postgresql.org/docs/current/functions-aggregate.html
