### ISSUE TITLE
Debian 11: 2.4.2 undefined symbol: EnsurePortalSnapshotExists

### ISSUE THREAD

**Issue by Marmelatze** [timescale/timescaledb#3606]
**Relevant system information:**
 - OS: Debian 11
 - PostgreSQL version (output of `postgres --version`): 13.3-1
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.2
 - Installation method: apt install

**Describe the bug**
`CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` results in the error:

```
/usr/lib/postgresql/13/lib/timescaledb-tsl-2.4.2.so: undefined symbol: EnsurePortalSnapshotExists
```

**To Reproduce**
1. apt install postgresql-13
1. apt install timescaledb-2-postgresql-13
2. timescaledb-tune --quiet --yes
3. systemctl restart postgresql
4. execute "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"

**Expected behavior**
Extension should be loaded.

**Actual behavior**
Extension is not loaded.

**Additional context**
Downgrading to 2.4.1 fixed the problem for me

**Comment by svenklemm** [comment]
Thank you for the bugreport. This should be fixed now.
