### ISSUE TITLE
User defined functions do not instantly send messages via postgres NOTIFY feature

### ISSUE THREAD

**Issue by Haybu** [timescale/timescaledb#3611]
I created a user-defined function to test a use case that sends a periodic notification (messages using Postgres NOTIFY feature). I have an app that connects to the database and listens to a channel (named test). I registered a user-defined action (procedure) to emit a message with a scheduler every 5 sec, like this

```
CREATE OR REPLACE PROCEDURE my_user_defined_action(job_id int, config jsonb) LANGUAGE PLPGSQL AS
$$
BEGIN
	PERFORM pg_notify('test', 'A message from user defined action');
END
$$;

SELECT add_job('my_user_defined_action','5 seconds', config => '{"param":"some-unused-value"}'); 
```
I don’t get the messages delivered (flushed) right away on my app side. However, if I issue a `NOTIFY test ‘some message` manually in a command line and on a different process, all “queued” messages start to show up.

The job stats table shows successful execution of the scheduled action. It seems the procedure is performing the message notification however not transferred somehow, I wonder what causes a message to not be instantly delivered.

**Comment by nikkhils** [comment]
Hi @Haybu

The jobs are being run in background worker processes. So the notify payload gets added to the notification queue appropriately. However some additional tweaking might be required in the background worker job running handling to make this work.

**Comment by nikkhils** [comment]
Hi @Haybu, this seems to be standard PG behavior. I tried the following with 2 PSQL sessions and I see similar async behavior between both:

Session1
```
postgres=# LISTEN virtual;                                                                                                LISTEN
```

Session2
```
postgres=# LISTEN virtual;                                                                                                LISTEN
```

Now, in session1 I execute a lot of NOTIFY commands:

Session1
```
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
```

I do NOT see them getting delivered simultaneously on the other side. Now if I run a NOTIFY on the other session, then it gets all these notificaitions:

Session2
```
postgres=# NOTIFY virtual;
NOTIFY
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24625.
Asynchronous notification "virtual" received from server process with PID 24635.
```

To summarize, this seems to be standard PG behavior and I am not sure what timescale can do additionally here.

**Comment by nikkhils** [comment]
@Haybu am closing this because this is standard PG behavior.
