### ISSUE TITLE
Cannot bucket by seconds, minutes, hours with time_bucket_ng

### ISSUE THREAD

**Issue by MA-MacDonald** [timescale/timescaledb#3621]
**Relevant system information:**
 - OS: Windows 10 x64
 - PostgreSQL version: 13.3
 - TimescaleDB version: 2.4.2

**Describe the bug**
Cannot bucket by  seconds, minutes, hours with `timescaledb_experimental.time_bucket_ng`

**To Reproduce**
```sql
--SELECT timescaledb_experimental.time_bucket_ng('1 seconds','2021-08-01');
-- SELECT timescaledb_experimental.time_bucket_ng('1 minutes','2021-08-01');
SELECT timescaledb_experimental.time_bucket_ng('1 hours','2021-08-01');
```

**Expected behavior**
The docs state `time_bucket_ng` can be bucketed by seconds, minutes, hours, days and weeks

**Actual behavior**
```
ERROR:  interval must be either days and weeks, or months and years
SQL state: 22023
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7886459/134793622-0752a73f-7fe1-4c31-8954-c250744ba204.png)

**Additional context**
```sql
SELECT timescaledb_experimental.time_bucket_ng('1 seconds','2021-08-01');  --errors
SELECT timescaledb_experimental.time_bucket_ng('1 minutes','2021-08-01'); --errors
SELECT timescaledb_experimental.time_bucket_ng('1 hours','2021-08-01');  --errors
SELECT timescaledb_experimental.time_bucket_ng('1 days','2021-08-01');  --works
```

**Comment by mj563436** [comment]
@MA-MacDonald  May I ask why is this closed?
