### ISSUE TITLE
DISTINCT ON causes error when using with array of single value and order by second parameter

### ISSUE THREAD

**Issue by binakot** [timescale/timescaledb#3629]
Currently I'm using PostgreSQL 12.8 with TimescaleDB 2.2.0. 

Yesterday I test the migration to the latest TimescaleDB version and got the error with few queries.

I create the repo to reproduce the problem: https://github.com/binakot/timescaledb-error-distinct-on-single-object-array-and-second-order-by.

---

## Summary

```sql
SELECT DISTINCT ON (id) * FROM test
WHERE id IN (2)
ORDER BY id ASC, time DESC;
```

When we use `DISTINCT ON` with `IN array` of single object and second condition in `ORDER BY` then query doesn't work:

```sql
ERROR:  column not present in index: 1
```

The most interesting that the next queries work:

```sql
SELECT DISTINCT ON (id) * FROM test
WHERE id IN (2,3) -- few values in array
ORDER BY id ASC, time DESC;
```

```sql
SELECT DISTINCT ON (id) * FROM test
WHERE id IN (2)
ORDER BY id ASC; -- no second condition
```

It happens in hypertables only. For default tables of PostgreSQL problem doesn't happen.

**Comment by phemmer** [comment]
I wonder if this is at all related to #3498. The query parser for `select distinct` seems to be fairly broken.

**Comment by nikkhils** [comment]
@svenklemm please take a look at this issue with `SELECT DISTINCT ON`:

```
CREATE TABLE test (a int, time timestamptz NOT NULL);
SELECT table_name FROM create_hypertable('public.test', 'time');
INSERT INTO test SELECT i, '2020-04-01'::date-10-i from generate_series(1,20) i;
EXPLAIN SELECT DISTINCT ON (a) * FROM test WHERE a in (2) ORDER BY a ASC, time DESC;
ERROR:  column not present in index: 1
```

Do note that `EXPLAIN SELECT DISTINCT ON (a) * FROM test WHERE a in (1,2) ORDER BY a ASC, time DESC;` works fine.

**Comment by sebvett** [comment]
I've also got this problem (was just about to ask on StackOverflow when I found this Issue). To add to the weirdness, the same [style of] query works on a different hypertable!
---
I'm using a `DISTINCT ON` query, very similar to [TSDB's own example from a blog post](https://blog.timescale.com/blog/how-we-made-distinct-queries-up-to-8000x-faster-on-postgresql/), but it fails for a single item list. 

    SELECT DISTINCT ON (tank_uid) tank_uid FROM mx_data WHERE tank_uid IN ('abc123') ORDER BY tank_uid, time DESC;
    ERROR:  column not present in index: 10
    SELECT DISTINCT ON (tank_uid) * FROM mx_data WHERE tank_uid IN ('abc123') ORDER BY tank_uid, time DESC;
    ERROR:  column not present in index: 10

Removing the `ORDER BY time` criterion results in the query working (but returning the first reading, not latest)

    SELECT DISTINCT ON (tank_uid) tank_uid FROM mx_data WHERE tank_uid IN ('mx001896') ORDER BY tank_uid DESC;
     tank_uid
    ----------
     abc123

Adding anything else to the list results in the query working

    SELECT DISTINCT ON (tank_uid) tank_uid FROM mx_data WHERE tank_uid IN ('abc123', '') ORDER BY tank_uid, time DESC;
     tank_uid
    ----------
     abc123

    SELECT DISTINCT ON (tank_uid) tank_uid FROM mx_data WHERE tank_uid IN ('abc123', 'bcd234') ORDER BY tank_uid, time DESC;
     tank_uid
    ----------
     abc123
     bcd234

Running the same style of query on a different hypertable works as expected

    SELECT DISTINCT ON (meter_uid) meter_uid FROM meter_data WHERE meter_uid IN ('cba321') ORDER BY meter_uid, time DESC;
     meter_uid
    -----------
     cba321

I would assume there was a difference in hypertable configuration, but the configuration of both is very similar (As I understand, a `UNIQUE` index on non-nullable columns is equivalent to a `PRIMARY KEY`?). 

                                 Table "public.mx_data"
          Column       |            Type             | Collation | Nullable | Default
    -------------------+-----------------------------+-----------+----------+---------
     time              | timestamp without time zone |           | not null |
     [...]
     tank_uid          | text                        |           | not null |
     [...]
    Indexes:
        "mx_data_tank_uid_time_idx" UNIQUE, btree (tank_uid, "time" DESC)
        "mx_data_time_idx" btree ("time" DESC)
    Number of child tables: 32 (Use \d+ to list them.)

                              Table "public.meter_data"
        Column     |            Type             | Collation | Nullable | Default
    ---------------+-----------------------------+-----------+----------+---------
     time          | timestamp without time zone |           | not null |
     meter_uid     | text                        |           | not null |
    [...]
    Indexes:
        "meter_data_pkey" PRIMARY KEY, btree (meter_uid, "time")
        "meter_data_time_idx" btree ("time" DESC)
    [...]
    Number of child tables: 53 (Use \d+ to list them.)

Happy to provide more details about the hypertables if requested. Extra info, in the event it's useful: The meter_data table was converted to a hypertable after populating the data

**Comment by mcanu** [comment]
Any update on this issue? We are having the same issue with the `distinct on` and is blocking our migration to the `2.3.1` version.

**Comment by binakot** [comment]
I did the temporary hotfix for broken queries while waiting for a patch ;)

May be it can be helpful for someone:

```sql
-- from
SELECT DISTINCT ON (id) * FROM test
WHERE id IN (2)
ORDER BY id ASC, time DESC;

-- to
WITH temp AS (
  SELECT * FROM test
  WHERE id IN (2)
  ORDER BY id ASC, time DESC
)
SELECT DISTINCT ON (id) FROM temp;
```
