### ISSUE TITLE
[Question] Realtime aggregation of Timeseries

### ISSUE THREAD

**Issue by pratapagiri** [timescale/timescaledb#3640]
We have multiple devices and timeseries for each device. These devices fall under different geographic regions. For example- each region may have 10000 devices. Is it possible to aggregate (sum) timeseries region-wise for a given Time start and Time End (real-time)?

**Comment by afiskon** [comment]
@pratapagiri If this is something derivable from the data you saved, of course, you can calculate this! Please note, however, that this is an issue tracker, not a support forum. Please address your question to our Slack https://timescaledb.slack.com/ Provide the schema of your database with some sample of the data and give a little more details on what you want to calculate.
