### ISSUE TITLE
[Question] Timescaledb sizing calculator

### ISSUE THREAD

**Issue by pratapagiri** [timescale/timescaledb#3641]
Is possible to calculate the memory size based on measurements per second and retention period (days) for a metric in IOT data?

**Comment by afiskon** [comment]
@pratapagiri Not 100% sure if I understood the question. If this is something derivable from the data you saved, of course, you can calculate this!

In any case, please note, that this is an issue tracker, not a support forum. Please address your question to our Slack https://timescaledb.slack.com/ Provide the schema of your database with some sample of the data and give a little more details on what you want to calculate. Our community is great and I'm certain somebody will help you with this in no time!
