### ISSUE TITLE
pgdata keeps growing on access node in a cluster containing only distributed hypertables

### ISSUE THREAD

**Issue by csroli** [timescale/timescaledb#3659]
**Relevant system information:**
 - OS: Debian GNU/Linux 10
 - PostgreSQL version: 12.7
 - TimescaleDB version: 2.4.0
 - Installation method: multi node helm chart, with timescale/timescaledb-ha:pg12.7-ts2.4.0-p2 Docker image

**Describe the bug**
Disk utilization keeps growing on access node containing only distributed hypertables.

**To Reproduce**
Have a 3 node cluster with only distributed hypertables created by the user.

**Expected behavior**
/var/lib/postgres/pgdata directory doesn't grow faster on the access node than it grows on the data nodes.

**Actual behavior**
We have a rather small 3 node installation with 1 access and 2 data nodes.  According to the docs I tought that the access node will not store any data. And a node can be an access node or a data node, not both.

>  Distributed hypertables and regular hypertables look very similar, with the main difference being that distributed chunks are not stored locally

We have fresh data on the data nodes too, so I guess the distribution is working. pg_database_size outputs on a table:
AN:  4330 MB
DN0: 283 MB
DN1: 670 MB

I didn't find any way to list or analyze the hypertables on the access node or at least they didn't work. For example __timescaledb_catalog.hypertable_ and _timescaledb_information.hypertables_ relations are empty. 

I think it can be some bad configuration on my side or data loss affecting the configurations. Can you help me track down this issue?

**Comment by pmwkaa** [comment]
I believe PostgreSQL might not return occupied storage right away to the OS.  Also you can take a look at the remote transaction table to ensure it is been properly cleaned up: `select count(*) from _timescaledb_catalog.remote_txn;`
