### ISSUE TITLE
Provide debian package containing debug symbols

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3669]
**Relevant system information:**
 - OS: Debian 10/Buster
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 13.4 (Debian 13.4-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt

**Describe the bug**
Debug symbols are not available

**To Reproduce**
1. get a core file of a postgres process with timescaledb in the stack
2. open with gdb
3. attempt to view the stack trace

**Expected behavior**
gdb should show the context for timescaledb frames

**Actual behavior**
GDB complains about missing symbols for timescaledb

**Additional context**
I am currently experiencing a segfault in timescaledb. However because debug symbols are not available, I am unable to submit a bug report on the issue as I cannot reproduce it outside of the current environment. This means I would have to recompile timescaledb myself, package it, and release it to our production environment, which will be a major PITA.

Standard practice (at least for Debian) is to have a "-dbgsym" package. For example `postgresql-13-dbgsym`. TimescaleDB should either follow this practice, or include the symbols in the main package.

**Comment by svenklemm** [comment]
Next release should also publish debug packages.

**Comment by phemmer** [comment]
Awesome. Thanks guys (and/or girls)!
