### ISSUE TITLE
Slowly query

### ISSUE THREAD

**Issue by 847365031** [timescale/timescaledb#3691]
Limit  (cost=0.42..1136.98 rows=1000 width=32) (actual time=12.648..6235.575 rows=1000 loops=1)
  ->  Result  (cost=0.42..1601.83 rows=1409 width=32) (actual time=12.646..6235.193 rows=1000 loops=1)
        ->  Index Scan using _hyper_8_94_chunk_tb_json_data_stationguid_dcollectdate_idx on _hyper_8_94_chunk  (cost=0.42..1584.22 rows=1409 width=1573) (actual time=12.638..6233.117 rows=1000 loops=1)
              Index Cond: (((stationguid)::text = '568e3c4d-777f-4778-a8e7-16d056796f45'::text) AND (dcollectdate > '2021-10-10 00:00:00'::timestamp without time zone) AND (dcollectdate < '2021-10-11 00:00:00'::timestamp without time zone))
Planning Time: 1.415 ms
Execution Time: 6235.905 ms

**Comment by NunoFilipeSantos** [comment]
Hi @847365031 ! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it. 👍
