### ISSUE TITLE
Enabling distributed compression within a procedure doesn't actually enable compression.

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3705]
**Relevant system information:**
 - OS: Debian 10/Buster
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 13.4 (Debian 13.4-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt

**Describe the bug**
Enabling compression on a distributed hypertable from within a procedure doesn't actually enable compression.

**To Reproduce**
```sql
create table test (time timestamp, v int);
select create_distributed_hypertable('test','time');
create procedure test_set_compression() language plpgsql as $$
    begin
        alter table test set (timescaledb.compress);
    end;
$$;
call test_set_compression();
insert into test values (now(), 0);
select compress_chunk(show_chunks) from show_chunks('test');
```

**Expected behavior**
success

**Actual behavior**
```
ERROR:  [datanode1]: compression not enabled on "test"
DETAIL:  It is not possible to compress chunks on a hypertable that does not have compression enabled.
HINT:  Enable compression using ALTER TABLE with the timescaledb.compress option.
```

**Additional context**
```
# select compression_enabled from timescaledb_information.hypertables where hypertable_name='test';
 compression_enabled 
---------------------
 t
(1 row)
```

Seems like this might be related to #3663 which was fixed in #3673. However I'm not sure if that fix was restricted to just `drop` statements, or if it would cover this case as well.

**Comment by pmwkaa** [comment]
@phemmer I can confirm that it works after #3673 been merged. I've also made a PR that includes your test case, just in case.
