### ISSUE TITLE
Unable to update records in uncompressed chunk of hypertable with prepared statements

### ISSUE THREAD

**Issue by hleung2021** [timescale/timescaledb#3719]
**Relevant system information:**
 - OS: Ubuntu 18.04, CentOS Linux release 7.9.2009 (Core)
 - PostgreSQL version (output of `postgres --version`): 12.8
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1, 2.3.1, 2.0.1
 - Installation method: apt install, AWS AMI image

**Describe the bug**
When I update records in an uncompressed chunk of a hypertable, I get an error saying update failed because I cannot update/delete rows from a chunk that has been compressed. However, the record that I am trying to update is not in the chunk referenced in the error message. 

**To Reproduce**
I have a simple Java program to reproduce the problem. The program uses JDBC and executes all inserts and updates with the same connection. I will describe the sequence of operations below. I have also attached the test program.

1. Create a hypertable with this definition:
```
create table test_ht (
  id int,
  time timestamptz NOT NULL,
  x varchar(10),
  PRIMARY KEY (id, time)
);
SELECT create_hypertable('test_ht', 'time', chunk_time_interval => INTERVAL '1 month');
ALTER TABLE test_ht SET (                                                                 
  timescaledb.compress,
  timescaledb.compress_segmentby = 'id'
);
```
2. Insert 1 row into the table with timestamp = '2021-01-01 00:00:00+00:00'. 
```
insert into test_ht (id, time, x) values (1, '2021-01-01 00:00:00+00:00', 'a');
```
3. Compress the chunk that contains the record added. The parameter to the compress_chunk function is the schema and name of the chunk, which is different for each test.  
```
SELECT public.compress_chunk('_timescaledb_internal._hyper_9_8_chunk');
```
4. Insert 1000 records, all with timestamp '2021-02-22T08:00:00+00:00'. I do that in a loop. 
```
insert into test_ht (id, time, x) values (2, '2021-02-22 08:00:00+00:00', 'a');
insert into test_ht (id, time, x) values (3, '2021-02-22 08:00:00+00:00', 'a');
...
...
insert into test_ht (id, time, x) values (1000, '2021-02-22 08:00:00+00:00', 'a');
insert into test_ht (id, time, x) values (1001, '2021-02-22 08:00:00+00:00', 'a');
```
4. Update each of the records that has timestamp '2021-02-22 08:00:00+00:00' by changing the value of column `x` to a different character. Each row is updated one at a time. 
```
update test_ht set x = 'x' where time='2021-02-22T08:00:00+00:00' and id = 2;
update test_ht set x = 'x' where time='2021-02-22T08:00:00+00:00' and id = 3;
...
...
update test_ht set x = 'x' where time='2021-02-22T08:00:00+00:00' and id = 100;
update test_ht set x = 'x' where time='2021-02-22T08:00:00+00:00' and id = 101;
```

**Expected behavior**
I expect all insert and update statements to be executed successfully. All updates are done on record with timestamps in February, which is not in the compressed chunk. 

Here are the two chunks created in the hypertable after executing the above operations:
```
scopedb=> select chunk_schema,chunk_name,range_start, range_end,is_compressed from timescaledb_information.chunks c where c.hypertable_schema = 'scopedb' AND c.hypertable_name = 'test_ht';
     chunk_schema      |     chunk_name     |      range_start       |       range_end        | is_compressed 
-----------------------+--------------------+------------------------+------------------------+---------------
_timescaledb_internal | _hyper_43_54_chunk | 2020-12-04 00:00:00+00 | 2021-01-03 00:00:00+00 | t
_timescaledb_internal | _hyper_43_56_chunk | 2021-02-02 00:00:00+00 | 2021-03-04 00:00:00+00 | f
(2 rows)
```

**Actual behavior**
Here is the error I got:
```
java.sql.BatchUpdateException: Batch entry 5 update test_ht set x = 'x' where time='2021-02-22 03:00:00-05' and id = 7 was aborted: ERROR: cannot update/delete rows from chunk "_hyper_43_54_chunk" as it is compressed  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:199)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:531)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
	at com.vmturbo.scope.replay.TestHT.loadData(TestHT.java:106)
	at com.vmturbo.scope.replay.TestHT.main(TestHT.java:123)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot update/delete rows from chunk "_hyper_43_54_chunk" as it is compressed
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1403)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1428)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:506)
	... 5 more
```
The chunk referenced in the error message is the one that was compressed, but it contains only 1 record that has a timestamp in January. The record I am trying to upgrade has timestamp in February, which is in the chunk `_hyper_43_56_chunk`.

I have tried the test described above with varying number of records in the 2 chunks. The tests fails with a relatively smaller number of rows in the compressed chunk compared to the uncompressed chunk.

If I have 1000 records in the uncompressed chunk, the test fails with up to 566 records in the first chunk. If I have 567 or more rows in the first (compressed) chunk, the test program can complete without errors. 

If I have 10,000 records in the uncompressed chunk, the test fails when there are less than or equal 566 records in the first chunk.

If I have 100,000 records in the uncompressed chunk, the test fails when there are less than or equal 574 records in the first chunk.

For step #4 of the steps to reproduce, if I update all records in one update statement, there are no errors. 
e.g. 
```
update test_ht set x = 'x' where time='2021-02-02 00:00:00+00'
```

Test Program:
[test.zip](https://github.com/timescale/timescaledb/files/7375768/test.zip)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by svenklemm** [comment]
This works  with recent improvements to chunk exclusion in timescaledb. Feel free to reopen if you can reproduce this with 2.7.0

**Comment by laocaixw** [comment]
**This problem still occurs occasionally with 2.7.0**

We use this docker image:  timescale/timescaledb-ha:pg14.3-ts2.7.0-p2

When we use PreparedStatements to delete by time colume, this problem occurs occasionally,

When we delete by other colume, this problem will definitely occur.

**Comment by koundinyagoparaju** [comment]
I still get this issue in Timescaledb 2.9.3 and Postgres 15.2
