### ISSUE TITLE
delete_data_node() does not work correctly.

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3725]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12.8
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.2
 - Installation method: source

**Describe the bug**
`delete_data_node()` does not work correctly.

**To Reproduce**
1. create a data node:
```
postgres=# SELECT * FROM add_data_node('dist_policy_data_node_1', host => 'localhost', database => 'dist_policy_data_node_1');
        node_name        |   host    | port |        database         | node_created | database_created | extension_created 
-------------------------+-----------+------+-------------------------+--------------+------------------+-------------------
 dist_policy_data_node_1 | localhost | 5432 | dist_policy_data_node_1 | t            | t                | t
(1 row)
```
2. delete the data node:
```
postgres=# SELECT * FROM delete_data_node('dist_policy_data_node_1', force => true);
 delete_data_node 
------------------
 t
(1 row)

```
3. add the data node again and see the error:
```
postgres=# SELECT * FROM add_data_node('dist_policy_data_node_1', host => 'localhost', database => 'dist_policy_data_node_1');
NOTICE:  database "dist_policy_data_node_1" already exists on data node, skipping
NOTICE:  extension "timescaledb" already exists on data node, skipping
DETAIL:  TimescaleDB extension version on localhost:5432 was 2.5.0-dev.
ERROR:  cannot add "dist_policy_data_node_1" as a data node
DETAIL:  ERROR:  node is already a data node
```

**Additional context**
We need `delete_data_node()` to work for the distributed isolation tests.

**Comment by cbisnett** [comment]
This confused me as well, but it is specified in the API documentation. Obviously not ideal if the database contains data and if you're trying to move it to another access node.

From: https://docs.timescale.com/api/latest/distributed-hypertables/delete_data_node/
> It is not possible to use add_data_node to add the same data node again without first deleting the database on the data node or using another database. This is to prevent adding a data node that was previously part of the same or another distributed database but is no longer synchronized.

**Comment by erimatnor** [comment]
Closing this as it is expected behavior, and enhancement is proposed in #3876.
