### ISSUE TITLE
You cannot insert into a compressed chunk of a distributed hypertable after creating a Continuous Aggregate

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3729]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12.8
 - TimescaleDB version (output of `\dx` in `psql`): 2.5.0-dev
 - Installation method: suorce

**Describe the bug**
You cannot insert into a compressed chunk of a distributed hypertable after creating a Continuous Aggregate.

**To Reproduce**
Same problem as https://github.com/timescale/timescaledb/issues/3410

**Comment by svenklemm** [comment]
Should be fixed by https://github.com/timescale/timescaledb/pull/3724
