### ISSUE TITLE
chunk_relation_size function adds toast_bytes to table_bytes

### ISSUE THREAD

**Issue by davidkmoat** [timescale/timescaledb#373]
It seems that the chunk_relation_size function adds toast_bytes to table_bytes and always reports 8192 for toast_bytes for some reason? ie:

output of chunk_relation_size: 
```[
  {
    "partitioning_hash_functions" : "{NULL}",
    "ranges" : "{\"[1513555200000000,1513641600000000)\"}",
    "partitioning_columns" : "{date}",
    "toast_bytes" : 8192,
    "chunk_id" : 931,
    "index_bytes" : 11935744,
    "total_bytes" : 63270969344,
    "partitioning_column_types" : "{date}",
    "table_bytes" : 63259025408,
    "chunk_table" : "\"_timescaledb_internal\".\"_hyper_1_931_chunk\""
  }
]
```

vs output of normal sizing functions for the same chunk: 

```[
  {
    "index" : "11 MB",
    "table_name" : "_hyper_1_931_chunk",
    "index_bytes" : 11935744,
    "table_bytes" : 49987584,
    "total" : "59 GB",
    "row_estimate" : 113629,
    "toast_bytes" : 63209046016,
    "oid" : 54835475,
    "total_bytes" : 63270969344,
    "table" : "48 MB",
    "table_schema" : "_timescaledb_internal",
    "toast" : "59 GB"
  }
]
```

Not a huge deal, but a slightly odd bug there.

**Comment by RobAtticus** [comment]
So it actually appears the issue is the wrong value of toast bytes is being shown. I don't see toast bytes being added to table bytes:
total - index - toast = table
63270969344 - 11935744 - 8192 = 63259025408
63259033600 - 8192 = 63259025408
63259025408 = 63259025408
