### ISSUE TITLE
postgresql upgrade results in error `TimescaleDB label is for internal use only`

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#3760]
**Relevant system information:**
 - OS: Debian 10
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 14.0 (Debian 14.0-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.5.0
 - Installation method: apt

**Describe the bug**
When attempting to upgrade from PostgreSQL 13 to 14, and using `pg_upgrade`, the process generates an error:

From `pg_upgrade_dump_235085.log`:
```
command: "/usr/lib/postgresql/14/bin/pg_restore" --host /tmp --port 50432 --username postgres --create --exit-on-error --verbose --dbname template1 "pg_upgrade_dump_235085.custom" >> "pg_upgrade_dump_235085.log" 2>&1
pg_restore: connecting to database for restore
pg_restore: creating DATABASE "edgestats"
pg_restore: connecting to new database "edgestats"
pg_restore: creating SECURITY LABEL "DATABASE "edgestats""
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 110846; 0 0 SECURITY LABEL DATABASE "edgestats" edgestats
pg_restore: error: could not execute query: ERROR:  TimescaleDB label is for internal use only
Command was: SECURITY LABEL FOR "timescaledb" ON DATABASE "edgestats" IS 'dist_uuid:ef362ddd-2a35-4d1e-84de-ed8d2b27f88c';
```

**To Reproduce**
1. Start from a postgres 13 installation
2. Run `pg_upgrade`

**Expected behavior**
Database to be upgraded

**Actual behavior**
```
pg_restore: error: could not execute query: ERROR:  TimescaleDB label is for internal use only
```

**Comment by greenweeds** [comment]
Another report of this issue in Slack https://timescaledb.slack.com/archives/C68KG4F6G/p1636467384069600?thread_ts=1635427829.035400&cid=C68KG4F6G

**Comment by NunoFilipeSantos** [comment]
@greenweeds the report you linked was on MST. Currently, MST does not support PG14.

**Comment by mkindahl** [comment]
@phemmer We are using some particular security labels for internal purposes&mdash;specifically to mark a node as member of a distribution cluster&mdash;but this seems to create issues in the restore. Do you get this error for an access node, a data node, or a plain timescaledb instance?

**Comment by phemmer** [comment]
This particular error came from an access node, as that's what I tried upgrading first. Do not know if the data nodes would have experienced the same issue.

**Comment by mkindahl** [comment]
@phemmer Did you use `timescaledb_pre_restore()` before attempting the restore?

**Comment by phemmer** [comment]
This was an upgrade, not a restore. The database has to be shut down before you run `pg_upgrade`, thus running things isn't even possible.
