### ISSUE TITLE
Make sure stats on distributed hypertables are auto-updated

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3770]
Statistics for distributed hypertables are updated when a user runs `ANALYZE` on the table, but not when auto-vacuum is run. The reason for this is that we intercept the `ANALYZE` call to run vacuum on distributed hypertables, while auto-vacuum is a custom code path that does not include this interception.

One question to resolve is whether the FDW API for vacuum is covered by auto-vacuum. In that case, the FDW API could be one way to get distributed hypertables autovacuumed. The issue here though, is that only chunks are real foreign tables.

**Comment by nikkhils** [comment]
So, FDW doesn't seem to have an API for vacuum. The reason is because vacuum is a PG specific activity and it doesn't make sense to expose an API for that at the FDW level since FDW is supposed to work with disparate data sources.

**Comment by nikkhils** [comment]
The consensus for now is to add a section in the `Multi-node maintenance tasks` documentation section. 

```
CREATE OR REPLACE PROCEDURE distributed_hypertables_analyze(job_id int, config jsonb)
LANGUAGE plpgsql AS
$$
DECLARE r record;
BEGIN
FOR r IN SELECT hypertable_schema, hypertable_name FROM timescaledb_information.hypertables
              WHERE is_distributed ORDER BY 1, 2
LOOP
EXECUTE 'ANALYZE ' || quote_ident(r.hypertable_schema) || '.' || quote_ident(r.hypertable_name);
END LOOP;
END
$$;

SELECT add_job('distributed_hypertables_analyze', '12h');
```

@erimatnor can you please point me to the location where we can make documentation change PRs?

**Comment by NunoFilipeSantos** [comment]
In the near future we should aim to automatically set this up for the user for a simpler way of using MN instead of an extra "hurdle".

**Comment by akuzm** [comment]
> `SELECT hypertable_schema, hypertable_name FROM timescaledb_information.hypertables WHERE is_distributed ORDER BY 1, 2`

Maybe it makes sense to add `ORDER BY random()` here, so that we are always making progress even if the job is failing or there is some persistent error on one of the tables.

**Comment by SHxKM** [comment]
@nikkhils @NunoFilipeSantos @akuzm  How can this be called manually on all nodes inside a single session? (not scheduled)


```
CALL distributed_exec($$ ANALYZE public.table_name $$)
```

Does not seem to have an effect.
