### ISSUE TITLE
Do I need autovacuum for INSERT's-only table?

### ISSUE THREAD

**Issue by daemonserj** [timescale/timescaledb#3772]
Hi.
I have one big table with retention policy 1week. 
There are bullk INSERT's, some SELECT's and no UPDATE/DELETE's.
After 1 week I suppose chunks are dropped.
Is this space need to be vacuum-ed ?
Why timescaledb-tune autovacuum settings are so aggressive ?
autovacuum_naptime = 10
autovacuum_max_workers = 10

Can I disable autovacuum for this table in my case ?

**Comment by NunoFilipeSantos** [comment]
Hi @daemonserj can you post this question on our community Slack? It helps us with knowledge sharing. Thank you.
