### ISSUE TITLE
Compression policy fails if the table uses integer and not bigint

### ISSUE THREAD

**Issue by CaptainCuddleCube** [timescale/timescaledb#3773]
**Relevant system information:**
 - OS:  Ubuntu 18.04.5
 - PostgreSQL PostgreSQL 12.8 
 - TimescaleDB version 2.5.0
 - Installation method: AWS Image

**Describe the bug**

The `show_chunks` function's `older_than` argument needs the data to be the same type as the time column. 

However, in the `_timescaledb_internal.policy_compression_integer` function, it casts values to BIGINT. So if your time column is an INT, the compression policy will fail. 

In the below code link, the `lag_integer` value is a BIGINT. 
https://github.com/timescale/timescaledb/blob/20543bf66b4de035d7890cdb642eed4cef2fed53/sql/policy_internal.sql#L89

**To Reproduce**
Create a table with an `INTEGER` time column, use `set_integer_now_func` to set the function type, and then add a compression policy.

You will start seeing errors in the logs:
```
2021-11-02 11:19:30.087 UTC [12436] ERROR:  invalid time argument type "bigint"
2021-11-02 11:19:30.087 UTC [12436] HINT:  Try casting the argument to "integer".
2021-11-02 11:19:30.087 UTC [12436] CONTEXT:  PL/pgSQL function _timescaledb_internal.policy_compression_integer(integer,integer,bigint,integer,boolean,boolean) line 17 at FOR over SELECT rows
	SQL statement "CALL _timescaledb_internal.policy_compression_integer(
	            job_id, htid, lag_integer,
	            maxchunks, verbose_log, recompress_enabled )"
	PL/pgSQL function _timescaledb_internal.policy_compression(integer,jsonb) line 62 at CALL
```

**Comment by victor-sudakov** [comment]
Looks like the upgrade to timescaledb-2-postgresql-12 2.5.0 has broken our Zabbix 5.0.17 depoyment. The database is not being cleaned up anymore with the error:

ERROR: invalid time argument type "bigint"

**Comment by CaptainCuddleCube** [comment]
@victor-sudakov I temporarily fixed the issue by putting an explicit `::INT` cast in the function:

https://github.com/timescale/timescaledb/blob/20543bf66b4de035d7890cdb642eed4cef2fed53/sql/policy_internal.sql#L89

so that it looks like :
```
FROM show_chunks( htoid, older_than => lag_integer::INT) SHOW (oid)
```

**Comment by victor-sudakov** [comment]
>  timescaledb/sql/policy_internal.sql

Excuse me @CaptainCuddleCube , where is that file? Cannot find it on a zabbix server.

**Comment by CaptainCuddleCube** [comment]
So, it's part of the Timescale Extension.

You can just run the patched `_timescaledb_internal.policy_compression_integer` procedure against the database and it will change it.

Just ensure you have backups before making any changes 😉

**Comment by victor-sudakov** [comment]
It should be easier to `alter extension timescaledb update to '2.4.2';`

**Comment by kev009** [comment]
Can this be backpatched to 2.5.1?
