### ISSUE TITLE
Continuous aggregate view not working on Foreign table(s) using "postgres_fdw"?

### ISSUE THREAD

**Issue by driekus77** [timescale/timescaledb#3785]
I'm using postgres_fdw to access our raw_data from our assets database. 

Read about Continuous aggregate view and am hoping to use these views to aggregate our raw data, which is per 1 minute, to 15 minutes bucket. So I want to create an cagg view in our Assets database over a postgres_fdw to a public_rawdata schema table.

I think its a limit by design and I'm hoping to hear an alternative ;-)

When I try to create the cagg view I always get:
[0A000] ERROR: invalid continuous aggregate view

PostgreSQL Version: 13.4
TimescaleDB Version: 2.4.2

Kind regards,
Henry

**Comment by mkindahl** [comment]
Hello @driekus77 !
It is not entirely clear how you define the continuous aggregate, but it seems like you're trying to define a continuous aggregate on a non-hypertable. Unfortunately, continuous aggregates only work on hypertables. Please see [Create a continuous aggregate](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/create-a-continuous-aggregate/#create-a-continuous-aggregate) in the documentation for more information.

**Comment by NunoFilipeSantos** [comment]
Hi @driekus77! Has @mkindahl suggestion helped you?  If so can you please close the issue? Thank you!

**Comment by mkindahl** [comment]
@driekus77 Closing this issue since it seems this is not a supported feature. If you think it was closed in error, please re-open it.

**Comment by driekus77** [comment]
Sorry all, Was busy with other stuff. NP just leave this closed for now. 

The simple workarround was/is to create the view(s) in the same database as the hypertable(s).

Kind regards,
Henry
