### ISSUE TITLE
error when try to get hypertable size in 2.x and hypertable name startes with capital letter

### ISSUE THREAD

**Issue by rahulbreezo** [timescale/timescaledb#3798]
**Relevant system information:**
 - OS: Docker image of 2.3 with postgis and postgres
 - PostgreSQL version 12.0
 - TimescaleDB version (output of `\dx` in `psql`): 2.3
 - Installation method: Docker

**Describe the bug**
When I try to get size of hypertable it give me error

```
local=# SELECT hypertable_size('Measurements') ;
ERROR:  relation "measurements" does not exist
LINE 1: SELECT hypertable_size('Measurements') ;
```

**To Reproduce**
Just try to get size of hypertable whose name starts with capital letter. works fine with hypertable whose name starts with small letter.

**Expected behavior**
Should give me size of hyper table

**Actual behavior**

Throwing error that relation does not exist.

**Comment by mkindahl** [comment]
This is normal behaviour and is how [PostgreSQL treats identifiers](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). If you need to preserve case, you need to double-quote the identifier inside the string.

```
mats=# \d
                   List of relations
 Schema |           Name            |   Type   | Owner 
--------+---------------------------+----------+-------
 public | Conditions                | table    | mats
 public | account                   | table    | mats
 public | account_account_id_seq    | sequence | mats
 public | conditions                | table    | mats
 public | conditions_stats          | view     | mats
 public | conditions_summary_daily  | view     | mats
 public | conditions_summary_hourly | view     | mats
 public | ledger                    | table    | mats
 public | ledger_ledger_id_seq      | sequence | mats
 public | tag_data                  | table    | mats
(10 rows)

mats=# select 'Conditions'::regclass;
  regclass  
------------
 conditions
(1 row)

mats=# select '"Conditions"'::regclass;
   regclass   
--------------
 "Conditions"
(1 row)

mats=# select 'Conditions'::regclass::int;
  int4  
--------
 170597
(1 row)

mats=# select '"Conditions"'::regclass::int;
  int4  
--------
 170793
(1 row)
```
