### ISSUE TITLE
Add schedule_interval parameter to policies

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#3806]
Some policies are missing the `schedule_interval` parameter, which then defaults to 1 day, which is very surprising if you have a very short `drop_after`/`compress_after` interval (say 1 hour). With such a short period, the effect would be that chunks are not compressed or dropped until after 24 hours.

Changing the default value for the schedule interval parameter and base it on the policy interval (`drop_after` / `compress_after`) would probably be more natural and less surprising. As an intermediate step, it is probably good to make sure that the schedule interval can be set for all policies, and some policies are missing this currently.

## Tasks

- [x] Add `schedule_interval` to `add_retention_policy`
- [x] Add `schedule_interval` to `add_compression_policy`

**Comment by glep207** [comment]
As a workaround you could ptobably create a custom job instead of using add_xxx_policy, but a proper fix would be nice.
