### ISSUE TITLE
have a problem  after bootstrap  when cd ./build && make

### ISSUE THREAD

**Issue by wangbincmss** [timescale/timescaledb#381]
cd ./build && make
[time@node0 timescaledb]$ cd build/
[time@node0 build]$ make
Scanning dependencies of target sqlfile
[  2%] Generating timescaledb--0.8.0.sql
[  2%] Built target sqlfile
Scanning dependencies of target sqlupdatefile
[  4%] Generating timescaledb--0.7.1--0.8.0.sql
[  4%] Built target sqlupdatefile
[  6%] Generating gitcommit.h
Scanning dependencies of target timescaledb
[  8%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
[ 10%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
[ 13%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
**In file included from /home/time/timescaledb/src/hypertable_cache.h:6,
                 from /home/time/timescaledb/src/cache_invalidate.c:13:
/home/time/timescaledb/src/hypertable.h:13: error: redefinition of typedef ‘HeapTuple’
/opt/prefix/include/postgresql/server/access/htup.h:70: note: previous declaration of ‘HeapTuple’ was here
make[2]: *** [src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o] Error 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [all] Error 2**

**Comment by RobAtticus** [comment]
Hi @wangbincmss , can you re-run `./bootstrap` and paste the output here? In particular, I would like to know what C compiler it is using. Should be the first line, but the whole output is fine. E.g.,
```
-- The C compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 0.9.0-dev. Can be updated from version 0.8.0
-- Build type is Release
-- Found Git: /usr/local/bin/git (found version "2.15.0")
-- Using pg_config /usr/local/bin/pg_config
-- Compiling against PostgreSQL version 10.1
-- Found PostgreSQL source in /Users/robatticus/postgres
-- Using pg_regress /usr/local/lib/postgresql/pgxs/src/test/regress/pg_regress
-- Using objdump /usr/local/bin/gobjdump
-- Using pgindent /Users/robatticus/postgres/src/tools/pgindent/pgindent
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/robatticus/workspace/timescaledb/build
TimescaleDB build system initialized in ./build. To compile, do:
cd ./build && make
```

**Comment by mnik247** [comment]
I have same problem.
Try build on CentOS 6:
16:33:51 [root@bg /home/nik/pg_timescaledb/timescaledb] # ./bootstrap
-- The C compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 0.8.0. Can be updated from version 0.7.1
-- Build type is Release
-- Found Git: /usr/bin/git (found version "1.7.1")
-- Using pg_config /usr/bin/pg_config
-- Compiling against PostgreSQL version 9.6.6
-- Using pg_regress /usr/pgsql-9.6/lib/pgxs/src/test/regress/pg_regress
-- Using objdump /usr/bin/objdump
-- Install pgindent to be able to format C code: https://github.com/postgres/postgres/tree/master/src/tools/pgindent
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nik/pg_timescaledb/timescaledb/build
TimescaleDB build system initialized in ./build. To compile, do:
cd ./build && make
16:33:55 [root@bg /home/nik/pg_timescaledb/timescaledb] # cd ./build && make
Scanning dependencies of target sqlfile
[  2%] Generating timescaledb--0.8.0.sql
[  2%] Built target sqlfile
Scanning dependencies of target sqlupdatefile
[  4%] Generating timescaledb--0.7.1--0.8.0.sql
[  4%] Built target sqlupdatefile
[  6%] Generating gitcommit.h
Scanning dependencies of target timescaledb
[  8%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
[ 10%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
[ 13%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
In file included from /home/nik/pg_timescaledb/timescaledb/src/hypertable_cache.h:6,
                 from /home/nik/pg_timescaledb/timescaledb/src/cache_invalidate.c:13:
/home/nik/pg_timescaledb/timescaledb/src/hypertable.h:13: error: redefinition of typedef ‘HeapTuple’
/usr/pgsql-9.6/include/server/access/htup.h:70: note: previous declaration of ‘HeapTuple’ was here
make[2]: *** [src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o] Error 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [all] Error 2

**Comment by RobAtticus** [comment]
We've seen problems with GCC compilers prior to the 5.0 release, which yours looks like it is (4.4.7). Is it possible for you to update the compiler to a more recent version?

**Comment by mnik247** [comment]
@RobAtticus Thanks. Fixed make with use Red Hat Developer Toolset (DTS)-4 + cmake3
17:43:00 [root@bg /home/nik/pg_timescaledb/timescaledb] # ./bootstrap
-- The C compiler identification is GNU 5.3.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 0.8.0. Can be updated from version 0.7.1
-- Build type is Release
-- Found Git: /usr/bin/git (found version "1.7.1")
-- Using pg_config /usr/bin/pg_config
-- Compiling against PostgreSQL version 9.6.6
-- Using pg_regress /usr/pgsql-9.6/lib/pgxs/src/test/regress/pg_regress
-- Using objdump /opt/rh/devtoolset-4/root/usr/bin/objdump
-- Install pgindent to be able to format C code: https://github.com/postgres/postgres/tree/master/src/tools/pgindent
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nik/pg_timescaledb/timescaledb/build
TimescaleDB build system initialized in ./build. To compile, do:
cd ./build && make
17:43:07 [root@bg /home/nik/pg_timescaledb/timescaledb] # cd ./build && make
Scanning dependencies of target sqlfile
[  2%] Generating timescaledb--0.8.0.sql
[  2%] Built target sqlfile
Scanning dependencies of target sqlupdatefile
[  4%] Generating timescaledb--0.7.1--0.8.0.sql
[  4%] Built target sqlupdatefile
[  6%] Generating gitcommit.h
Scanning dependencies of target timescaledb
[  8%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
[ 10%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
[ 13%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
[ 15%] Building C object src/CMakeFiles/timescaledb.dir/catalog.c.o
[ 17%] Building C object src/CMakeFiles/timescaledb.dir/chunk.c.o
[ 19%] Building C object src/CMakeFiles/timescaledb.dir/chunk_constraint.c.o
[ 21%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch.c.o
[ 23%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch_info.c.o
[ 26%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch_plan.c.o
[ 28%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch_state.c.o
[ 30%] Building C object src/CMakeFiles/timescaledb.dir/chunk_index.c.o
[ 32%] Building C object src/CMakeFiles/timescaledb.dir/chunk_insert_state.c.o
[ 34%] Building C object src/CMakeFiles/timescaledb.dir/compat.c.o
[ 36%] Building C object src/CMakeFiles/timescaledb.dir/constraint_aware_append.c.o
[ 39%] Building C object src/CMakeFiles/timescaledb.dir/copy.c.o
[ 41%] Building C object src/CMakeFiles/timescaledb.dir/dimension.c.o
[ 43%] Building C object src/CMakeFiles/timescaledb.dir/dimension_slice.c.o
[ 45%] Building C object src/CMakeFiles/timescaledb.dir/dimension_vector.c.o
[ 47%] Building C object src/CMakeFiles/timescaledb.dir/event_trigger.c.o
[ 50%] Building C object src/CMakeFiles/timescaledb.dir/executor.c.o
[ 52%] Building C object src/CMakeFiles/timescaledb.dir/extension.c.o
[ 54%] Building C object src/CMakeFiles/timescaledb.dir/guc.c.o
[ 56%] Building C object src/CMakeFiles/timescaledb.dir/histogram.c.o
[ 58%] Building C object src/CMakeFiles/timescaledb.dir/hypercube.c.o
[ 60%] Building C object src/CMakeFiles/timescaledb.dir/hypertable.c.o
[ 63%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_cache.c.o
[ 65%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_insert.c.o
[ 67%] Building C object src/CMakeFiles/timescaledb.dir/indexing.c.o
[ 69%] Building C object src/CMakeFiles/timescaledb.dir/init.c.o
[ 71%] Building C object src/CMakeFiles/timescaledb.dir/parse_analyze.c.o
[ 73%] Building C object src/CMakeFiles/timescaledb.dir/parse_rewrite.c.o
[ 76%] Building C object src/CMakeFiles/timescaledb.dir/partitioning.c.o
[ 78%] Building C object src/CMakeFiles/timescaledb.dir/planner.c.o
[ 80%] Building C object src/CMakeFiles/timescaledb.dir/planner_utils.c.o
[ 82%] Building C object src/CMakeFiles/timescaledb.dir/process_utility.c.o
[ 84%] Building C object src/CMakeFiles/timescaledb.dir/scanner.c.o
[ 86%] Building C object src/CMakeFiles/timescaledb.dir/sort_transform.c.o
[ 89%] Building C object src/CMakeFiles/timescaledb.dir/subspace_store.c.o
[ 91%] Building C object src/CMakeFiles/timescaledb.dir/tablespace.c.o
[ 93%] Building C object src/CMakeFiles/timescaledb.dir/trigger.c.o
[ 95%] Building C object src/CMakeFiles/timescaledb.dir/utils.c.o
[ 97%] Building C object src/CMakeFiles/timescaledb.dir/version.c.o
[100%] Linking C shared module timescaledb.so
[100%] Built target timescaledb

**Comment by RobAtticus** [comment]
@wangbincmss did you have the same issue? Can you post the output of `./bootstrap` if you didn't?

**Comment by RobAtticus** [comment]
I am going to close this issue @wangbincmss , if you still are having this problem please re-open.
