### ISSUE TITLE
can't drop_chunks where hypertable  contains massive data.

### ISSUE THREAD

**Issue by chennailong** [timescale/timescaledb#3810]
first，i'm not good at english (i'm an chinese IT user).
my timescale 2( on postgres-13) , contains two datanodes, one accessnode.
my tsdb hava some hypertable , one hypertable contain 800 million record, 40 million records was generated every day。
so，i hava a sql for drop_chunks。

-------------
postgres=# SELECT drop_chunks('subs061008501501_s', '2021-09-18'::date);

-------------

it didn't work for long long time. so, i can't drop chunks while hypertable contain more then 200 million record.
do you have some minds? tell me ,thanks,borth.

**Comment by gayyappan** [comment]
@chennailong It sounds like that the drop_chunks function was blocked by some other process that was accessing the chunk (maybe a SELECT query, or insert/delete etc). Have you checked lock activity?
 https://wiki.postgresql.org/wiki/Lock_Monitoring

Trouble shooting questions are best directed to our support slack channel: timescaledb.slack.com

**Comment by chennailong** [comment]
i had checked lock activity , that's okay.
it happend when i dropping chunks(SELECT drop_chunks('subs060215280005_m', older_than => DATE '2021-10-17'); ); 

i have some small hypertables, i dropped chunks on small hypertable successfully.
It failed when I drop chunks if hypertable contains massive data;

can i show your my sql for create hypertable?

-------------------------------
SELECT create_distributed_hypertable('station_sub23482349872234', 'data_time', chunk_time_interval => INTERVAL '24 HOUR', data_nodes => '{"tsdb41","tsdb42"}');
------------------------------

i don't known how to do that.

**Comment by erimatnor** [comment]
@chennailong To be able to understand the issue, we need a way to reproduce it or at least have some information about what is blocking the process that is dropping chunks.

**Comment by chennailong** [comment]
when i drop_chunks on hypertables, it'll get a lock(AccessExclusiveLock).
how can i do that,? i want to drop_chunks. (SELECT drop_chunks('subs060215280005_m', older_than => DATE '2021-09-19'); )

**Comment by afiskon** [comment]
@chennailong I'm sorry but the provided information is not enough for the dev-team to perform any actions.

Ideally, we would like to have minimal steps to reproduce, e.g (1) create one access node, two data nodes (2) create a distributed hypertable (3) fill it like this with generate_series() (4) maybe, open a second session (5) execute the following queries, see - it blocks, although it shouldn't.

If you have any difficulties troubleshooting the issue, please join the community Slack channel https://timescaledb.slack.com Please, re-open the issue when additional information will be available.

**Comment by vryzhevsky** [comment]
I have same issue

My installation:
One access node
Four data nodes

One table has about 100,000 rows
Second table has about 1 million rows

I apply function drop_chunks to both tables.
First runs successfully
Second runs very long time and ends with error like "transaction rollback on data node datanode1 failed"

**Comment by SHxKM** [comment]
@vryzhevsky did you manage to solve this issue? we have the same issue as you. 1 access node, 2 data nodes.
