### ISSUE TITLE
Monotonic-ish data or compression/data-retention, pick one?

### ISSUE THREAD

**Issue by Fuuzetsu** [timescale/timescaledb#3822]
We have a use-case that's as follows: we run financial on historical market data and during the simulations, we write out various metrics (say, current profit etc). This means that the timestamps we want to use and query have no relation to real-time and that we'll be writing the timestamps very out of order. For example, in the same second, we may receive metrics from different sims each with very different times, call these market_time:

* 2018-01-01 01:02:03
* 2021-06-05 05:06:07
* 2019-08-03 06:06:06

We can create a hypertable using this like:
```sql
CREATE TABLE sim_metric (
  sim_id bigint NOT NULL,
  market_time timestamptz NOT NULL,
  -- real time of the metric: let's us tell how "fresh" the metric may be
  wall_time timestamptz NOT NULL,
  -- whatever metrics go below
  profit double precision NOT NULL
);
SELECT create_hypertable('sim_metric', 'market_time', chunk_time_interval => INTERVAL '30 days');
```

We start to see a problem at this stage already: if we have simulations for data from 2015 to 2020, that's about 60 chunks that are going to be updated all the time rather than keeping a "most recent" chunk in memory.

It gets worse: we can't really compress the chunks either because it's going to want to write to them. There's also no way to do data retention policy: it makes no sense to drop data that's older than say 7 days market time because that just instantly drops all the data.

All queries are performed with the market_time: we only ask "show me profit between 2015 and 2016 for this simulation". We don't care about the wall time as it's not relevant when the sim actually ran.

We _can_ make continuous aggregations on sim_metric using market_time which is great because it's a lot of data and these are really necessary.

----

On the flip side, we may want to consider instead using `wall_time` for the hypertable. This allows us very easy data retention (drop any metrics ingested 14 days ago) and compression (compress chunks 1 day old). The most important part stops working though: querying becomes slow (show me data between 2015 and 2016) and we can't do continous aggregates (because the hypertable dimension is now wall_time, not market_time).

----

I tried doing `add_dimension` with hope to "sets" of chunks: every day we get a new chunk set based on wall_time and this set itself is split into some `market_time` chunks. But it doesn't work, continous aggregates seem to require using the "main" dimension, not just any. I'm unsure if this makes sense to start with, I'm bit unclear on the dimension stuff.

----

How can one deal with this use-case? Am I forced to choose between either data retention/compression/fast deletion OR being able to query in any reasonable amount of time? I need to be able to say "drop anything older than 2 weeks" on say 150M row table without it taking days as it does in vanilla postgres while keeping the queries fast.

**Comment by Fuuzetsu** [comment]
Here's what I ended up settling on after few days of trying different things.

* make hypertables on wall_time
* set the chunk interval to something low, I'm have 15 minutes now but 5 minutes worked fine too.
* add compression with `orderby` on `market_time` -- this is the trick
* add compression policy with low interval time, say 5 minutes

This allows querying by market time to be fast on compressed chunks. Querying uncompressed data is slow but there should only really be about 20 minutes of it until it gets compressed and reordered in the process.

This gives compression (yay), data retention (yay), ability to search only relevant chunks by wall_time (we know the wall time of a particular sim so all other chunks don't need exploring, yay) but slow queries on most recent inserts (nay... maybe lower intervals are in order but I worry a little about planning time as number of chunks increases).

**Comment by gayyappan** [comment]
@Fuuzetsu Glad to hear that it worked. Just want to add that our slack channel is a better forum for asking schema design questions. ( timescaledb.slack.com )

**Comment by Fuuzetsu** [comment]
> @Fuuzetsu Glad to hear that it worked. Just want to add that our slack channel is a better forum for asking schema design questions. ( timescaledb.slack.com )

Thanks but it's impossible to do a Google search and find something from a Slack channel so it felt better to ask somewhere more discoverable.

**Comment by Fuuzetsu** [comment]
By the way, this "works" but as I said it makes queries very slow on recent data: actually they get unacceptably slow. So I'd appreciate input if my method is the only real way or if there's something else and any info about gotchas etc. I'm not really happy with my "solution".

**Comment by Fuuzetsu** [comment]
After having even more data in the database, it more or less stopped being usable completely, with fairly basic SELECT queries effectively spinning the CPU and rendering the database useless. So I guess the workaround I envisioned has failed. We're considering using redshift or something instead because I'm out of ideas...
