### ISSUE TITLE
Add test for concurrent continuous aggregate refresh operations

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3838]

**Comment by NunoFilipeSantos** [comment]
dismissed.

**Comment by mfundul** [comment]
We already have a test [here](https://github.com/timescale/timescaledb/blob/2.5.1/tsl/test/isolation/specs/continuous_aggs_concurrent_refresh_dist_ht.spec). It is already part of our CI/CD. Some future work would be to try and identify race conditions by adding debug waitpoints at key points in the code.
