### ISSUE TITLE
Foreign Table partition

### ISSUE THREAD

**Issue by sergiojgm** [timescale/timescaledb#384]
Would like to know if its possible to set chunks/partitions as a FOREIGN TABLE does?

Basically spread the partitions over a cluster of servers?

**Comment by erimatnor** [comment]
This currently isn't possible, since it also involves consistency/transaction issues when inserting in multiple foreign tables in a single transaction. We are, however, working on a clustered version of TimescaleDB that will allow scale-out across multiple servers.
