### ISSUE TITLE
Kerberos / GSS authentication not supported by current Postgres Docker image

### ISSUE THREAD

**Issue by jackbucinskas** [timescale/timescaledb#3843]
**Relevant system information:**
 - OS: Linux x86_84
 - PostgreSQL version (output of `postgres --version`): 13.4
 - TimescaleDB version (output of `\dx` in `psql`): 2.5.0
 - Installation method: Docker

**Describe the bug**
Unable to start TimescaleDB Postgres 13 image (timescale/timescaledb:2.5.0-pg13) due to gss not being included by default with Alpine Linux 

**To Reproduce**
Try and start a TimescaleDB Docker container with a `pg_hba.conf` file that contains `gss` as an authentication method.
```
2021-11-23 14:22:05.902 AEDT [1] LOG:  invalid authentication method "gss": not supported by this build
2021-11-23 14:22:05.902 AEDT [1] CONTEXT:  line 115 of configuration file "/var/lib/postgres/data/pg_hba.conf"
```

**Expected behavior**
Postgres Docker image successfully builds with the tag `--with-gssapi` and successfully read `pg_hba.conf` that contains a gss entry

**Actual behavior**
TimescaleDB Postgres fails to start due to gss not being included by default with Postgres on Alpine Linux

**Additional context**
Is it possible to build the Postgres image with Debian "Bullseye" or with the tag `--with-gssapi` included as an env variable?

This is a working Postgres database directory & config with current image: `postgres/postgres:13.4`

**Comment by svenklemm** [comment]
This is an upstream change so you would have to report this to upstream. The timescaledb-ha image uses the postgres ubuntu packages which have GSS support.
