### ISSUE TITLE
How to compile TimescaleDB in Intranet environment ?

### ISSUE THREAD

**Issue by demons-joker** [timescale/timescaledb#3844]
**Relevant system information:**
 - OS: centos 3.10.0-1062.18.1.el7.x86_64
 - PostgreSQL version (output of `postgres --version`): 9.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: source

**Describe the bug**
Because there is no public network environment can not be compiled on the server,
 so it can only be compiled on the same machine in order to make an RPM package to install to the Intranet environment

**Comment by svenklemm** [comment]
What is the error you are getting or at which stage does it hang?

**Comment by demons-joker** [comment]
Thank you for your reply,i have solved this problem
