### ISSUE TITLE
Upgrade from 0.10.0 to 2.5.0 (NotSupportedError: logging cannot be turned off for hypertables)

### ISSUE THREAD

**Issue by amujef** [timescale/timescaledb#3847]
Hello there.
My project is running in 0.10.0 version.
Now, i want to do same thing in new machine with postgresql and timescaledb 2.5.0
i use ```  ALTER TABLE mytable set unlogged ```
but when i run this command by django migrations an exception occured:
```
django.db.utils.NotSupportedError: logging cannot be turned off for hypertables
```

what should i do? why we cannot set a table to unlogged? what can i do instead of this?

**Comment by amujef** [comment]
@NunoFilipeSantos i update the issue

**Comment by NunoFilipeSantos** [comment]
What PostgreSQL version are you using?

**Comment by gebrits** [comment]
Not OP but seeing the same issue `logging cannot be turned off for hypertables`

PG version: PostgreSQL 14.1 (Ubuntu 14.1-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
Timescale version: 2.5.0

**Comment by svenklemm** [comment]
Unlogged hypertables are currently not supported. There is an open issue to add support for it: https://github.com/timescale/timescaledb/issues/836
