### ISSUE TITLE
[Enhancement]: Handle GRANT/REVOKE on objects that belong to distributed hypertables

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3850]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Command processing, Multi-node

### What does the enhancement do?

When a user GRANTs or REVOKEs privileges on objects that belong to distributed hypertables, the system should forward those statements to the data nodes that have similar objects on their local versions of the hypertable.

Objects affected might include:

- Sequences
- Indexes

### Implementation challenges

It is necessary to identify objects that belong to distributed hypertables, possibly by walking the object dependency graph in PostgreSQL.

**Comment by svenklemm** [comment]
multinode has been removed
