### ISSUE TITLE
[Enhancement]: flexible way to include custom DB configuration in docker container

### ISSUE THREAD

**Issue by ilveroluca** [timescale/timescaledb#3870]
### What type of enhancement is this?

Configuration

### What subsystems and features will be improved?

Configuration

### What does the enhancement do?

Provide a simple way for users of the Docker image to include custom configuration settings that override the defaults and/or the ones created with tstune.

At the moment [it seems](https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/docker-config/#docker-config) that the way to configure the server is to edit the postgresql.conf file in the PGDATA directory after the database cluster has been created.

### Implementation challenges

I suggest modifying the default generated postgresql.conf file to include an `include_dir` directive pointing to a valid in the container (e.g., `/etc/timescaledb/conf.d/`) where users could mount their overriding configuration files when the container is launched.  This change would make it simple to, for instance, manage extra configuration in Kubernetes ConfigMap objects.

**Comment by svenklemm** [comment]
You can configure postgres settings via `-c setting=value`. This is functionality inherited from the postgres container and documented there: https://hub.docker.com/_/postgres

**Comment by svenklemm** [comment]
This seems more like a documentation issue so i'm closing this but i created a ticket for this in our docs repo: https://github.com/timescale/docs/issues/632.
