### ISSUE TITLE
[Bug]: PG Upgrade from 12->13 fails with error

### ISSUE THREAD

**Issue by hardikm10** [timescale/timescaledb#3901]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

Attempting to upgrade from PG12 to PG13 but was faced with the below error :

---loadable_libraries.txt---
could not load library "$libdir/timescaledb-2.5.0": ERROR: extensible node type "ConstraintAwareAppend" already exists 
In database: _timescaledb
We've seen such instances before and the resolution is to match their version of TimescaleDB across all of the databases they have. But in this case, this didn't work and the below error came  :

```
Error while upgrading extensions: ERROR:  functionality not supported under the current "timescale" license
HINT:  Upgrade your license to 'timescale' to use this free community feature.
CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW custom_metric_readings_cagg_project_nums SET (timescaledb.materialized_only='t') "
PL/pgSQL function inline_code_block line 21 at EXECUTE

<psycopg2.extensions.Diagnostics object at 0x7fe86c0caa30>
```

For context, the service had two databases:

defaultdb : 2.4.2
_timescaledb : 2.5.0 (this database I believe is used by the platform for internal purposes)

Some scenarios that were tested:
1. Downgrade the timescaledb extension on _timescaledb to 2.4.2 to match defaultdb. Perform upgrade to PG13. Fails
2. DROP EXTENSION timescaledb on the _timescaledb instance. Perform upgrade to PG13. Fails

### TimescaleDB version affected

2.4.2

### PostgreSQL version used

12.9

### What operating system did you use?

MST

### What installation method did you use?

Other

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

**Comment by mkindahl** [comment]
The problem occurs because if you have two shared libraries, in this case with different versions, that both try to register custom scan nodes, one of the registrations will fail with the above error.
