### ISSUE TITLE
[Enhancement]: Distribute ALTER commands on objects that a distributed hypertable depends on

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3905]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Command processing, Multi-node, Distributed hypertable, Data node

### What does the enhancement do?

When altering objects that belong to distributed hypertables, like indexes and sequences, they are not forwarded to data nodes. For instance, altering and index like this:

```sql
ALTER INDEX my_hypertable_idx SET (fillfactor=60);
```

Will only apply this to the access node's index. This does nothing as that index only serves as a template and holds no data.

### Implementation challenges

One either needs to walk the PostgreSQL dependency graph or use TImescaleDB metadata to figure out if the object being altered is used by a distributed hypertable.

**Comment by erimatnor** [comment]
Related to #3850

**Comment by svenklemm** [comment]
multinode has been removed
