### ISSUE TITLE
Error with BIGINT time column in create_hypertable() when not explicitly specified?

### ISSUE THREAD

**Issue by surendrakumar-gadde** [timescale/timescaledb#392]
Hi,

 I tried to create hypertable on BIGINT column (Time stored in UTC number) it returns below error

ERROR:  chunk_time_interval needs to be explicitly set for time columns of type SMALLINT, INTEGER, and BIGINT
CONTEXT:  PL/pgSQL function _timescaledb_internal.time_interval_specification_to_internal(regtype,anyelement,interval,text,boolean) line 20 at RAISE
PL/pgSQL function _timescaledb_internal.time_interval_specification_to_internal_with_default_time(regtype,anyelement,text,boolean) line 3 at RETURN
PL/pgSQL function public.create_hypertable(regclass,name,name,integer,name,name,anyelement,boolean,boolean,regproc) line 65 at assignment

Below is the table creation script

drop table conditions;
CREATE TABLE conditions (
 time        BIGINT    NOT NULL,
 location    TEXT              NOT NULL,
 temperature DOUBLE PRECISION  NULL
);

SELECT create_hypertable('conditions', 'time');

TimescaleDB version 0.8.0
Postgres :9.6.6
OS : MAC

**Comment by surendrakumar-gadde** [comment]
Any updates on this bug? 
should i convert my UTC BIGINT column to TIMESTAMP ?
We need to make decision to use this extension of TimeSerise data storage.

**Comment by RobAtticus** [comment]
Sorry I misread this earlier when I saw it. This actually isn't a bug. What it's telling you is you need to be explicit with the `chunk_time_interval` because TimescaleDB has no way of knowing what units your BIGINT represents (e.g. it could be seconds, milliseconds, microseconds, etc).

So, if your BIGINT column represents milliseconds and you want a chunk time of a day you'd do:
```
SELECT create_hypertable('conditions', 'time', chunk_time_interval => 86400000);
```

If your BIGINT represents seconds:
```
SELECT create_hypertable('conditions', 'time', chunk_time_interval => 86400);
```

And so on. Hope that helps!

**Comment by solugebefola** [comment]
Here is the API for the function in the docs http://docs.timescale.com/v0.8/api#create_hypertable

**Comment by surendrakumar-gadde** [comment]
Thanks, it works.  I missed this API docs, thought that it is not a mandatory field.

**Comment by kamakhyarjun** [comment]
Hi,

I am trying to create hypertable on logging_events which is as below :

postgres=# \d+ logging_event
                                                                    Table "public.logging_event"
      Column       |          Type          | Collation | Nullable |                  Default                  | Storage  | Compression | Stats target | Description 
-------------------+------------------------+-----------+----------+-------------------------------------------+----------+-------------+--------------+-------------
 timestmp          | bigint                 |           | not null |                                           | plain    |             |              | 
 formatted_message | text                   |           | not null |                                           | extended |             |              | 
 logger_name       | character varying(254) |           | not null |                                           | extended |             |              | 
 level_string      | character varying(254) |           | not null |                                           | extended |             |              | 
 thread_name       | character varying(254) |           |          |                                           | extended |             |              | 
 reference_flag    | smallint               |           |          |                                           | plain    |             |              | 
 arg0              | character varying(254) |           |          |                                           | extended |             |              | 
 arg1              | character varying(254) |           |          |                                           | extended |             |              | 
 arg2              | character varying(254) |           |          |                                           | extended |             |              | 
 arg3              | character varying(254) |           |          |                                           | extended |             |              | 
 caller_filename   | character varying(254) |           | not null |                                           | extended |             |              | 
 caller_class      | character varying(254) |           | not null |                                           | extended |             |              | 
 caller_method     | character varying(254) |           | not null |                                           | extended |             |              | 
 caller_line       | character(4)           |           | not null |                                           | extended |             |              | 
 event_id          | bigint                 |           | not null | nextval('logging_event_id_seq'::regclass) | plain    |             |              | 
Indexes:
    "logging_event_pkey" PRIMARY KEY, btree (event_id)
Referenced by:
    TABLE "logging_event_exception" CONSTRAINT "logging_event_exception_event_id_fkey" FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
    TABLE "logging_event_property" CONSTRAINT "logging_event_property_event_id_fkey" FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
Access method: heap

The command for create the hypertable is as below: SELECT create_hypertable('logging_event','timestmp',chunk_time_interval => 86400000);

the error is : cannot create a unique index without the column "timestmp" (used in partitioning)

can you anyone help me with this?
