### ISSUE TITLE
[Bug]: Shipping schema-related statements to data nodes does not always work

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#3927]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Multi-node

### What happened?

Looks like the recent shipping of `CREATE SCHEMA` statements to datanodes is not always a great idea.
Bug1:

1) Create another extension on the AN, which is not the timescaledb extension. The new extensions should create new_schema on the AN. 
2) The test then tries to do a GRANT USAGE ON SCHEMA new_schema TO testrole which the timescaledb extension tries to ship to the datanode.
3) Datanode errors out with [dn2]: schema "new_schema" does not exist'

Bug2:
If the new extension is created on data nodes addition then it too errors out with:
ERROR:  [dn1]: cannot insert multiple commands into a prepared statement

Ideally, schema-related commands should not be shipped while an extension is created or updated. Also, there should be a way to disable shipping of DDL commands completely to address the second case above.

### TimescaleDB version affected

Master

### PostgreSQL version used

All versions

### What operating system did you use?

On All

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
No need. Easily reproducible.
```

### How can we reproduce the bug?

```bash
Repro steps mentioned above
```

**Comment by nikkhils** [comment]
Decision:
* If extension is being installed or updated then don't ship commands that are part of the extension handling process to datanodes

Discussion:
* Consider if we should disable DDL shipping to datanodes by default? There seem to a lot of use cases that we haven't thought about fully yet

**Comment by erimatnor** [comment]
@nikkhils Did we fix this? I guess we are no longer doing this by default at least.

**Comment by jfjoly** [comment]
https://github.com/timescale/timescaledb/issues/3927 should fix this issue.
