### ISSUE TITLE
A way to install without Docker?

### ISSUE THREAD

**Issue by lumberg72** [timescale/timescaledb#393]
Hi,
I've been reading up on TimescaleDB and have been excited to try it out. Finally decided to take the plunge. I figured... it's just pg extension... should be easy enough to install and try out, so why not. Boy was I wrong.

First, in the timescale installation instructions, it is presumed that we all know what the heck this "docker" thing is. So I googled it and determined it is yet another install manager. OK, fine... so I'll install it.  Well I go to their website and after several click and looking around, finally get to the Windows version. Download the 200 MB file and run it to install. Nope.
It tells me that it requires Windows 10 Pro and higher.  Apparently Windows 10 Home doesn't cut it. I have developed everything under the sun on this machine and never ever required Windows Pro.
So anyway... after some googling around, I find that I can get an older version called "Docker Toolbox" to run on Windows Home edition.  After several dead links, I finally make my way to that version and download another 200 MB file. Install that and run it.  Then I get some errors saying that virtualization is not enabled on my machine. After some more research, I find out that I have to go make bios changes for this!  OK....
Of course my laptop has 'special' ways of getting to the bios... so after yet more googling around, I figure out how to get into my bios and make the change. I do that,  try the docker stuff again... and now getting some new obscure error that I am definitely not going to figure out.

Is all of this just to install a pg extension??  Or is Docker also required to actually USE timescale too?
Is there some other way to install this?  I really want to check it out, but I'm frustrated already.

Thanks

**Comment by RobAtticus** [comment]
Sorry that it was an unpleasant experience trying Docker.

There is a way to install TimescaleDB from source on Windows:
http://docs.timescale.com/v0.8/getting-started/installation/windows/installation-source-windows

Windows support is still relatively new (0.8.0 was the first release with support) so we haven't finished all the niceties for packaging but we will soon.

Also the README on the repo has abbreviated instructions for installing on Windows.

**Comment by lumberg72** [comment]
Thanks for the tips! I'll look into that.

**Comment by lumberg72** [comment]
Success.
The build/install instructions have a few errors and omissions. Here are some notes that might help someone else.

After all the Git stuff...

Download and install "Build Tools for Visual Studio 2017" from https://www.visualstudio.com/downloads/

Trying to run the bootstrap.bat file, it was unable to find 2 executables that I needed to add to the PATH windows env variable.
cmake.exe (which was found at "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin")

... and...
pg_conf which was found at PG_HOME\bin

Then bootstrap ran fine.  Then I ran MSBuilder from within Visual Studio Build Tools 2017 (opened the console by clicking "launch" from the menu).
Then it built.


The timescale directions say that the timescaledb.dll is in build. But I actually found it in build/Debug

The timescale directions say to copy timescaledb.control to the pg/lib directory. But I found out later that it actually needed to go to pg's share/extensions dir.

**Comment by mfreed** [comment]
Thanks very much for this feedback, @lumberg72!

**Comment by cricket007** [comment]
Related to your Docker problems. 

Windows 10 Home [does not have HyperV](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements), which [Docker for Windows requires to run](https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install). 

Docker Machine runs VirtualBox, which if you have ever used a VM on your machine (such as trying out a Linux distribution), you would have had to enable virtualization anyway. 

You could have used Virtualbox or VMware to setup a Linux installation of Postgres w/ TImescaleDB

**Comment by lumberg72** [comment]
Thanks for the tips. I learned a bit of that through my trial & error and just got frustrated that, after all that, I still failed (there seems to be a bit of old/outdated information out there about that took me on some detours).

But all-in-all, compiling it instead wasn't too bad so I'm happy with the outcome.

**Comment by RobAtticus** [comment]
Closing this because these tips have been addressed. We are also updating our docs to provide instructions for using an easy binary installation, mentioned here:
https://github.com/timescale/timescaledb/issues/395#issuecomment-372363245

Thanks again!
