### ISSUE TITLE
[Enhancement]: Add option to compile without telemetry

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3931]
### What type of enhancement is this?

Configuration

### What subsystems and features will be improved?

Telemetry

### What does the enhancement do?

Add the possibility to compile TimescaleDB entirely without telemetry. Telemetry should be compiled in by default.

- To be able to make a performance comparison and see if telemetry collection affect performance.
- To be able to guarantee that no telemetry is sent out, regardless of how it is deployed.

### Implementation challenges

* The notice message when installing the extension should be different when Telemetry is not compiled into the code. This might affect test output as well.
* Metadata can be available even when Telemetry is not enabled, so moving metadata functionality out of Telemetry module needs to be done.
* Many tests mix metadata access and telemetry. Several tests need to be split to separate tests for Telemetry functionality from other tests.

**Comment by mkindahl** [comment]
Blocked by #4009 so fixing that first.
