### ISSUE TITLE
[Enhancement]: Extend telemetry to report table categories and deeper stats

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#3932]
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Telemetry

### What does the enhancement do?

Break down telemetry into the different kinds of relations:

* Regular tables
* Hypertables 
   - compressed
   - uncompressed
* Distributed hypertables
   - compressed
   - uncompressed
* Chunks
   - compressed 
   - uncompressed
* Materialized views
* Continuous aggregates

And, for each of these categories, report

* Approximate number of rows
* Data size
* Data size if compression would not have been enabled (pre-compression size)

### Implementation challenges

All the stats should be quick to gather, or otherwise we shouldn't include them.

**Comment by nikkhils** [comment]
Points of discussion:

* Should we do batch processing?
* Should we create a matview of the stats and then refresh it?
