### ISSUE TITLE
POLL:  For what additional platforms should we offer binary releases?

### ISSUE THREAD

**Issue by mfreed** [timescale/timescaledb#395]
We often get various requests to offer a binary releases, with clear package management, for different platforms.  It would be useful to get feedback from the community as to what platforms they'd like a native binary package for.

So, please signify your interest with a thumbs-up in the comments below.  (Or suggest a new platform if we missed it.)

**Comment by mfreed** [comment]
Debian

**Comment by mfreed** [comment]
Windows

**Comment by mfreed** [comment]
RedHat

**Comment by mfreed** [comment]
SUSE Linux

**Comment by mfreed** [comment]
Windows 64-bit

**Comment by mfreed** [comment]
Windows x64

**Comment by mfreed** [comment]
Windows x32

**Comment by mfreed** [comment]
Mac OS X

**Comment by oldgreen** [comment]
You may want to have a look at pkgsrc: http://pkgsrc.org/#platforms

**Comment by lumberg72** [comment]
CentOS

**Comment by mfreed** [comment]
@lumberg72 Are you having problems installing on CentOS via our yum instructions?  http://docs.timescale.com/v0.8/getting-started/installation/linux/installation-yum

**Comment by lumberg72** [comment]
@mfreed Oh, no. Sorry, I hadn't even looked yet. I'm just doing some initial prototyping in Windows. If all goes well, I'll deploy it to a CentOS machine.... and just thought, "yeah, I'll want the binaries for that".  But since you already have it, I'll delete my CentOS comment to help keep a clean poll :)

**Comment by cactus** [comment]
You might consider changing RedHat to RedHat/CentOS. I bet more people run CentOS than upstream RedHat/RHEL.

**Comment by RobAtticus** [comment]
@cactus - We actually support CentOS already:
http://docs.timescale.com/v0.8/getting-started/installation/linux/installation-yum

I actually believe this will work on RHEL too but haven't confirmed.

**Comment by cactus** [comment]
Ah. My apologies. I thought the poll was looking for overall usage, not just *additional* platforms.

**Comment by RobAtticus** [comment]
No worries!

**Comment by BACtaki** [comment]
Windows x64

**Comment by RobAtticus** [comment]
Thanks @BACtaki but Windows x64 is already listed ^ (4th reply)

**Comment by vdedyukhin** [comment]
Oracle Linux

**Comment by dquang** [comment]
Windows 64. 

Building from source on Windows 64 is a nightmare and normally come out with a huge size binary in my experience (I am not a IT-Developer though).

I have tried docker (installed docker, pulled the package but it simply did not work, only docker running normally).

**Comment by RobAtticus** [comment]
Thanks @dquang, just to clarify are you talking about our binary specifically or binaries for Win64 in general? Looking at our dll it only appears to be 100-200kb

**Comment by dquang** [comment]
Thanks @RobAtticus for your reply. My point was: just make a binary available for Win64. As a user, it is a nightmare for us to make it ourself.

About the size: I just talking about it in general. For example, I have built from source a program called PgModeller and got the binary with 1GB when installed. However, the developer makes it cost only 51MB. That is the different between a professional developer and a user.

**Comment by mterron** [comment]
Alpine linux? Building from source works perfectly fine so no big deal.

**Comment by thinkwelltwd** [comment]
I'd be glad for CentOS 6 support.  Have nearly 200 v6 machines running PG 10.2 on which I'd also like to use timescaledb.

**Comment by RobAtticus** [comment]
@thinkwelltwd If you got PG 10.2 to install on there, you can likely install via the RPM (which is built on centos7) or build from source.

**Comment by thinkwelltwd** [comment]
> If you got PG 10.2 to install on there , you can likely install via the RPM (which is built on centos7) or build from source.

v6 is one of the [officially supported platforms](https://yum.postgresql.org/10/redhat/rhel-6.9-x86_64/). I'm sure I can build from source, but isn't the point of packaging to avoid that?

**Comment by RobAtticus** [comment]
@thinkwelltwd Have you tried our current binaries?
http://docs.timescale.com/v0.8/getting-started/installation/linux/installation-yum

If it works, I will work on making sure going forward that it continues to work and update the docs to note it can work on CentOS 6. I just haven't personally tested it myself.

**Comment by RobAtticus** [comment]
Currently we say CentOS 7 because we had a lot of people try building on source with CentOS 6 with old versions of GCC that did not work. So to be safe I went with the CentOS version that had a working version of GCC.

**Comment by thinkwelltwd** [comment]
CentOS 7 binaries don't work on CentOS 6 as the glibc library version is mismatched.

```
[root@system x86_64]# rpm -ivh timescaledb_10-0.8.0-1.rhel7.x86_64.rpm 
error: Failed dependencies:
	libc.so.6(GLIBC_2.14)(64bit) is needed by timescaledb_10-0.8.0-1.rhel7.x86_64
```
> So to be safe I went with the CentOS version that had a working version of GCC.

Ok, that makes sense. I've used [Developer Toolset](http://mirror.centos.org/centos/6/sclo/x86_64/rh/) to get various recent versions of GCC. I don't know if that would be an option in your build prcoess or not. 

If there was an official RPM then "a lot of people building on source with CentOS 6" could just be referred to the v6 binary :grin:

**Comment by RobAtticus** [comment]
Thanks for the info, I'll take a look into supporting the older version then :)

**Comment by aharonh** [comment]
How about supporting the arm64 achitecture for various linuxes?

**Comment by peterbeasley** [comment]
Another vote for arm64

**Comment by RobAtticus** [comment]
For all of those waiting for Debian binaries, wait no more :) We now have binaries available for Debian 7, 8, and 9:

http://docs.timescale.com/v0.9/getting-started/installation/linux/installation-apt-debian

**Comment by RobAtticus** [comment]
For those looking for Windows x64 binaries, we have an initial release that we'd like some people to try. We're providing a .zip that contains all the necessary files + a setup.exe that will detect where to install the files. You need to have the `pg_config` binary in your PATH for this to work, or supply it as a flag to the binary. If you'd like to try it out, please download here:
https://timescalereleases.blob.core.windows.net/windows/timescaledb-0.9.0-windows-amd64.zip

**Comment by RobAtticus** [comment]
The aforementioned Windows installation instructions are located here now:
http://docs.timescale.com/latest/getting-started/installation/windows/installation-windows

**Comment by hongquan** [comment]
We are looking forward to use TimescaleDB on ARMv7 (BeagleBone), running Debian 9.
