### ISSUE TITLE
[Bug]: Cannot upgrade from v2.0.1 to v2.4.2, 2.5.0 or 2.5.1

### ISSUE THREAD

**Issue by sirber** [timescale/timescaledb#3953]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

I'm on PostgreSQL v12 on Windows 10. I'm trying to upgrade from Timescale v2.0.1 to v.2.5.1. The DLL installed fine, but I cannot run the last step to upgrade my database. I get the following error:

'''
ERROR:  cannot drop table _timescaledb_catalog.chunk because other objects depend on it
DETAIL:  view chunks_ts depends on table _timescaledb_catalog.chunk
view chunks_tstz depends on table _timescaledb_catalog.chunk
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
'''

I thied v2.4.2 and v2.5.0 whitout success.

### TimescaleDB version affected

2.0.1

### PostgreSQL version used

12.9

### What operating system did you use?

Windows 10 x64

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  cannot drop table _timescaledb_catalog.chunk because other objects depend on it
DETAIL:  view chunks_ts depends on table _timescaledb_catalog.chunk
view chunks_tstz depends on table _timescaledb_catalog.chunk
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

### How can we reproduce the bug?

```bash
I'm not sure, I grabbed a backup from a production server, which I'm trying to upgrade.
```

**Comment by svenklemm** [comment]
Seems like you created a view (chunks_ts and chunks_tstz) based on internal catalog tables which prevents the upgrade.  You should drop the view, do the upgrade and then recreate the views.

**Comment by sirber** [comment]
You're right! I wasn't aware of those.

![image](https://user-images.githubusercontent.com/3911428/147936335-092849a6-22bf-490b-b452-bbf19374f9e9.png)

**Comment by sirber** [comment]
I'm working on this, I"ll be back as soon as possible. Thanks!

**Comment by sirber** [comment]
The upgrade (to v2.5.1) did not throw an error:
![image](https://user-images.githubusercontent.com/3911428/147939715-1e19fe40-6e33-4984-8bc9-c6663b6652a2.png)

and the database show 2.5.1.
![image](https://user-images.githubusercontent.com/3911428/147939867-13734858-46ad-42ad-bcd5-bcb57e44545b.png)

Thank you!
