### ISSUE TITLE
[Bug]: Incorrect chunks sizes returned by chunk_compression_stats()

### ISSUE THREAD

**Issue by brahimyacine** [timescale/timescaledb#3982]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Other

### What happened?

We have noticed an inconsistency between the values of the **chunk_compression_stats' after_compression_total_bytes**  column and the **chunks_detailed_size's total_bytes** column.

We wonder if **chunk_compression_stats' after_compression_total_bytes**  is supposed to return the size of chunks just after the end of their compressions or should track the evolution of chunks sizes that could change after eventual insertions in  compressed chunks ? 

We think that after insertion in a chunk already compressed the size of the latter is not updated in chunk_compression_stats, which can be confusing because the sizes of chunks returned by the latter function are no longer correct, unlike the information returned by the function chunks_detailed_size which seems to be updated after new insertions.

You will find below an example that describes the problem:
We've obtained the results below by executing the following query called **Q1**: 
```
SELECT compression_stats.chunk_name,
       tsdbinfo.range_start, 
       tsdbinfo.range_end,
       pg_size_pretty(chunksizes.total_bytes) as real_size,
       chunk.status as chunk_status,
       pg_size_pretty(compression_stats.before_compression_total_bytes) as before_compression_size,
       pg_size_pretty(compression_stats.after_compression_total_bytes) as after_compression_size,
       (compression_stats.after_compression_total_bytes*100.0)/compression_stats.before_compression_total_bytes as percentage_of_compression 
FROM chunk_compression_stats('conditions') as compression_stats 
LEFT JOIN timescaledb_information.chunks AS tsdbinfo ON compression_stats.chunk_name = tsdbinfo.chunk_name
LEFT JOIN chunks_detailed_size('conditions') AS chunksizes ON compression_stats.chunk_name = chunksizes.chunk_name
LEFT JOIN _timescaledb_catalog.chunk chunk ON compression_stats.chunk_name = chunk.table_name
ORDER BY range_start DESC;
```

1. We started by inserting 27.5m rows in the **conditions** distributed hypertable.. The execution of **Q1** returns: 
```
       chunk_name       |      range_start       |       range_end        | real_size | chunk_status | before_compression_size | after_compression_size | percentage_of_compression 
------------------------+------------------------+------------------------+-----------+--------------+-------------------------+------------------------+---------------------------
 _dist_hyper_1_84_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 2333 MB   |            0 |                         |                        |                          
 _dist_hyper_1_85_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 1013 MB   |            0 |                         |                        |                          
```
2. After that we've manually compressed the above chunks by running `compress_chunk` function. The execution of **Q1**  after compression returns:
```
       chunk_name       |      range_start       |       range_end        | real_size | chunk_status | before_compression_size | after_compression_size | percentage_of_compression 
------------------------+------------------------+------------------------+-----------+--------------+-------------------------+------------------------+---------------------------
 _dist_hyper_1_84_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 79 MB     |            1 | 2333 MB                 | 79 MB                  |        3.4030554495100699
 _dist_hyper_1_85_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 58 MB     |            1 | 1013 MB                 | 58 MB                  |        5.6961537275222849
```
We notice that the after_compression_size corresponds well to real_size.

3. After that we've tried to insert 1m more rows in the compressed chunks (without recompressing the chunks again).  The execution of **Q1** gives the result bellow:
```
       chunk_name       |      range_start       |       range_end        | real_size | chunk_status | before_compression_size | after_compression_size | percentage_of_compression 
------------------------+------------------------+------------------------+-----------+--------------+-------------------------+------------------------+---------------------------
 _dist_hyper_1_84_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 282 MB    |            3 | 2333 MB                 | 79 MB                  |        3.4030554495100699
 _dist_hyper_1_85_chunk | 2022-01-10 00:00:00+00 | 2022-01-11 00:00:00+00 | 223 MB    |            3 | 1013 MB                 | 58 MB                  |        5.6961537275222849
```
We notice at this point the inconsistency between  the **after_compression_size** value and **real size** value.
PS: 
chunk_status 3 means that the chunk need to be recompressed

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Ubuntu 20.04 LTS x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by duncan-tsdb** [comment]
Nice bug report! We have done some work recently on compression, so we'll have to check to make sure the meta table values are getting updated.

**Comment by gayyappan** [comment]
Please use chunks_detailed_size to get the exact size of the tables/chunks. This reads the tables to get the sizes.

For performance reasons, chunk_compression_stats is updated only when a) compress_chunk is executed or b) the compression policy job touches the specific chunk. This is used as a cache to estimate before/after compression sizes.

**Comment by brahimyacine** [comment]
Thanks for the reply,
I better understand now why the after_compression_total_bytes values are not getting updated after insertion in compressed chunks.

**Comment by gayyappan** [comment]
Clarify documentation https://github.com/timescale/docs/pull/723
