### ISSUE TITLE
[Bug]: <Title>Problem installing on centos7

### ISSUE THREAD

**Issue by sickel** [timescale/timescaledb#3989]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Other

### What happened?

I have installed postgresql14 from the pgdg14 repository. On first attempt to install timescaledb, I installed from the same repo. That worked fine, but at it turned out to be the Apache-2 licensed version with some missing features, so I tried to deinstall it and reinstall from the timescaledb repository.

The installation went well and I've got /usr/pgsql-14/lib/timescaledb-2.5.1.so 

Then ran timescaledb-tune and got postgresql.conf set up with shared_preload_libraries = 'timescaledb' (an a few other relevant settings). Then on restart, postgresql did not come up, complaining it could not find  timescaledb.

Then I have tried to set shared_preload_libraries = 'timescaledb-2.5.1', then I got another error message:  FATAL:  loader version out-of-date.  HINT:  Please restart the database to upgrade the loader version.

 By softlinking timescaledb-2.5.1.so to timescaledb.so, I saw the same behaviour. 

By commenting out shared_preload_libraries = "timescaledb" I got the system up again, but without timescaledb support.

I have tried to do the same things on postgresql-12 on the same machine but with the same result. 

This may be a packaging issue with the pgdg supplied timescaledb rpms, but in all cases it ends up making timescaledb unstartable. I have the feeling something is left over from the pgdg installation.

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

centos7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
on centos7:

set up dpkg repo
install postgresql 14 and timescaledb2 for postgresql 14 from the dpkg repo
remove timescaledb2 
set up timescaledb repo
install timescaledb2 for postgresql 14 from the timescaledb repo
```

**Comment by svenklemm** [comment]
did you install `timescaledb-2-postgresql-14`? the timescaledb version included in the pgdg repository is not built by us so there is not much we can do here. You should follow https://docs.timescale.com/install/latest/self-hosted/installation-redhat/#installing-self-hosted-timescaledb-on-red-hat-based-systems to install timescaledb.

**Comment by sickel** [comment]
timescaledb-2-postgresql-14 was the one I installed after understanding that using the pgdg version was a mistake.

**Comment by sickel** [comment]
Turned out a removal of timescaledb-2-postgresql-14 and reinstallation solved the problem. Seems like something was not cleaned out properly when timescaledb_14 was removed. 

Just for info, I had no active timescaledb tables in the cluster when I did this.
