### ISSUE TITLE
[Feature]: a guc to disable forwarding of DDL commands to data nodes

### ISSUE THREAD

**Issue by pmwkaa** [timescale/timescaledb#4001]
### What problem does the new feature solve?

Upcoming 2.6 release will have multi-node support for `CREATE SCHEMA` forwarding, we need a way to disable this functionality if it will cause a problems for a user

### What does the feature do?

Disables DDL forwarding to data nodes. So user will have to use `distributed_exec` or manually create necessary distributed objects

**Comment by erimatnor** [comment]
DDL forwarding should also be disabled any time you alter or install an extension by checking the internal variable `creating_extension`.
