### ISSUE TITLE
[Bug]: set_chunk_time_interval fails on materialized hyper table of a continuous aggregate 

### ISSUE THREAD

**Issue by yalon** [timescale/timescaledb#4002]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

We have a downsampling use case where we want to use continuous aggregates to keep downsampled data from the main hypertable.

Based on the [docs](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/materialized-hypertables/), I should be able to call set_chunk_time on the underlying materialized table but unfortunately that fails due to permissions issues although I'm running the DDLs as the same user who created the hypertable.

`
metrics=# select set_chunk_time_interval((select materialization_hypertable_name from timescaledb_information.continuous_aggregates where view_name='my_main_hypertable')::regclass, interval '2 hour');
ERROR:  relation "_materialized_hypertable_4" does not exist
`

I see there was a previous related ticket (#2630) that discusses a similar issue, but here this isn't related to upgrades as the database in the version defined below.

Please advise - without setting the chunk time we risk having a lot of partitions on a downsampled table.

### TimescaleDB version affected

2.5.0,2.5.1

### PostgreSQL version used

13.4

### What operating system did you use?

TImescaleDB managed service

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### How can we reproduce the bug?

```bash
1. Create a hypertable.
2. Create a materialized view with a continuous aggregate.
3. Call set_chunk_time_interval on the materialized table of the continuous aggregate.
```

**Comment by akuzm** [comment]
Maybe the name should be qualified with the internal schema name, i.e. `_timescaledb_internal._materialized_hypertable_4`? If you run `select '_timescaledb_internal._materialized_hypertable_4'`, does it work?

**Comment by yalon** [comment]
Thanks @akuzm! It does work, or at least doesn't complain :)
I suggest giving this perhaps as an example in the doc I linked above?

Thanks again for the quick response and resolution.
