### ISSUE TITLE
[Bug]: time_bucket_gapfill behavior inconsistent/broken in pg 13

### ISSUE THREAD

**Issue by chadshowalter** [timescale/timescaledb#4004]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill, Other

### What happened?

When using time_series_gapfill and including a constant in the group by clause, behavior is inconsistent between postgres 11 and postgres 13, and seems broken.  I'm using docker desktop 4.3.2 (72729) on a MAC.  See below for steps to reproduce.

```
create database test;

create table metrics (
    ts timestamp,
    device_id integer,
    metric1 real,
    unique (ts, device_id)
);

SELECT public.create_hypertable('metrics', 'ts', chunk_time_interval := INTERVAL '1 week',
                                create_default_indexes := FALSE);

insert into metrics (ts, device_id, metric1)
values ('2021-01-01 12:00:00', 1, 500.0),
       ('2021-01-01 12:05:00', 1, 500.0),
       ('2021-01-01 12:15:00', 1, 500.0);

select time_bucket_gapfill('PT5M', ts) AS bucket,
       device_id,
       ''::TEXT AS grouping,
       sum(metric1) / 1 as avg_metric1
FROM metrics
WHERE ts >= '2021-01-01 12:00:00' AND ts < '2021-01-01 12:20:00'
GROUP BY 1, 2, 3;
```

### postgres 11, timescaledb 2.3.1 results:
```
"bucket","device_id","grouping","avg_metric1"
"2021-01-01 12:00:00.000000","1","","500"
"2021-01-01 12:05:00.000000","1","","500"
"2021-01-01 12:10:00.000000","1","",
"2021-01-01 12:15:00.000000","1","","500"
```
### postgres 13, timescaledb 2.3.1 (and 2.5.1) results:
```
"bucket","device_id","grouping","avg_metric1"
"2000-01-01 00:00:00.000000","0","","0"
"2000-01-01 00:00:00.000000","0","","0"
"2000-01-01 00:00:00.000000","0","","0"
"2021-01-01 12:00:00.000000","0","",
"2021-01-01 12:05:00.000000","0","",
"2021-01-01 12:10:00.000000","0","",
"2021-01-01 12:15:00.000000","0","",
```

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

13.5

### What operating system did you use?

Mac OS X 12.1

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Run timescaledb 2.3.1 on pg 11 and get expected results.


docker run -d --rm --name timescaledb -p 5555:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.3.1-pg11
```

Run timescaledb 2.3.1 (or 2.5.1, current latest) on pg 13 and get unexpected results.

```
docker run -d --rm --name timescaledb -p 5555:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.5.1-pg13
```
```

**Comment by akuzm** [comment]
Fixed in TimescaleDB 2.6 (to be released in February) by this commit https://github.com/timescale/timescaledb/commit/a7608871452bd685ae8f87c3b554f929bdb9e575 , see also https://github.com/timescale/timescaledb/issues/3834

**Comment by chadshowalter** [comment]
Do you have a workaround to suggest for those of us attempting to upgrade to pg 13 prior to the availability of this release?

**Comment by akuzm** [comment]
> Do you have a workaround to suggest for those of us attempting to upgrade to pg 13 prior to the availability of this release?

@svenklemm maybe you have some suggestions for a workaround?

**Comment by svenklemm** [comment]
The following query should work:
```
select bucket, device_id, '' AS grouping, avg_metric1 FROM (
select time_bucket_gapfill('PT5M', ts) AS bucket,
  device_id,
  sum(metric1) / 1 as avg_metric1
FROM metrics
WHERE ts >= '2021-01-01 12:00:00' AND ts < '2021-01-01 12:20:00'
GROUP BY 1, 2
) gf;
```
Alternatively you can put the gapfill in CTE

**Comment by chadshowalter** [comment]
Thanks!  Your suggestions are cleaner that what I'm currently doing:
```
select 
       bucket,
       split_part(grp, '_', 1) as device_id, 
       split_part(grp, '_', 2) as grouping, 
       avg_metric1
from (
select time_bucket_gapfill('PT5M', ts) AS bucket,
       device_id || '_' || ''::TEXT grp,
       sum(metric1) / 1 as avg_metric1
FROM metrics
WHERE ts >= '2021-01-01 12:00:00' AND ts < '2021-01-01 12:20:00'
GROUP BY 1, 2) q;
```

**Comment by chadshowalter** [comment]
@akuzm I just discovered that I get a segmentation fault when I include an additional aggregation in my query on pg13 timescaledb 2.5.1.  I get this consistently when running the docker image after creating the dataset I use in my example above.

```
select
       bucket,split_part(grp, '_', 1) as device_id,
       split_part(grp, '_', 2) as grouping,
       avg_metric1
from (
select time_bucket_gapfill('PT5M', ts) AS bucket,
       device_id || '_' || ''::TEXT grp,
       sum(metric1) / 1 as sum_metric1,
       avg(metric1) / 1 as avg_metric1
FROM metrics
WHERE ts >= '2021-01-01 12:00:00' AND ts < '2021-01-01 12:20:00'
GROUP BY 1, 2) q;
```
gives
```
2022-01-25 16:29:09.058 UTC [1] LOG:  server process (PID 77) was terminated by signal 11: Segmentation fault
2022-01-25 16:29:09.058 UTC [1] DETAIL:  Failed process was running: select
               bucket,split_part(grp, '_', 1) as device_id,
               split_part(grp, '_', 2) as grouping,
               avg_metric1
        from (
        select time_bucket_gapfill('PT5M', ts) AS bucket,
               device_id || '_' || ''::TEXT grp,
               sum(metric1) / 1 as sum_metric1,
               avg(metric1) / 1 as avg_metric1
        FROM metrics
        WHERE ts >= '2021-01-01 12:00:00' AND ts < '2021-01-01 12:20:00'
        GROUP BY 1, 2) q
```

I do not see this behavior in the nightly build.  However, are you able to reproduce and to confirm that this is the same bug, and that it has been fixed?

**Comment by akuzm** [comment]
> However, are you able to reproduce and to confirm that this is the same bug, and that it has been fixed?

Yes, this query hits the same assertion in older versions.
