### ISSUE TITLE
Duplicate indexes on <dimension, range_start, range_end> of dimension_slice catalog table

### ISSUE THREAD

**Issue by maksm90** [timescale/timescaledb#401]
Hi!

I have noticed that the table **dimension_slice** in **_timescaledb_catalog** schema has almost identical indexes on the triple of dimention, range_start, range_end columns.

```
# \d _timescaledb_catalog.dimension_slice;
                                   Table "_timescaledb_catalog.dimension_slice"
    Column    |  Type   | Collation | Nullable |                             Default                              
--------------+---------+-----------+----------+------------------------------------------------------------------
 id           | integer |           | not null | nextval('_timescaledb_catalog.dimension_slice_id_seq'::regclass)
 dimension_id | integer |           | not null | 
 range_start  | bigint  |           | not null | 
 range_end    | bigint  |           | not null | 
Indexes:
    "dimension_slice_pkey" PRIMARY KEY, btree (id)
    "dimension_slice_dimension_id_range_start_range_end_key" UNIQUE CONSTRAINT, btree (dimension_id, range_start, range_end)
    "dimension_slice_dimension_id_range_start_range_end_idx" btree (dimension_id, range_start, range_end)
```

As I know, unique index _dimension_slice_dimension_id_range_start_range_end_key_ created via unique constraint statement entirely functionally covers the _dimension_slice_dimension_id_range_start_range_end_idx_ index created manually as near as I can guess.

Is second index unnecessary?

**Comment by erimatnor** [comment]
@maksm90 thanks for reporting this issue. And yes, you are right, this extra index is unnecessary. Incidentally, we have already fixed this and it will be in an upcoming release.
