### ISSUE TITLE
[Bug]:  Data corruption in 1.7.4

### ISSUE THREAD

**Issue by ferfebles** [timescale/timescaledb#4011]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Background worker

### What happened?

Launched VACUUM FULL but the WAL archive (not pg_xlog, the archived WAL) got filled.

Error in postgres log:
 ERROR:  catalog is missing 15 attribute(s) for relid 3926181

Stoped Postgres to disable archiving and to be able to end the VACUUM FULL.

After starting again we see some errors in the log:

ERROR:  invalid attribute number 9 for bgw_job:
LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 15780) exited with exit code 1

And then, every few seconds we can see the errors:
ERROR:  invalid attribute number -2 for bgw_job_stat
CONTEXT:  automatic vacuum of table "pistac._timescaledb_internal.bgw_job_stat"
ERROR:  invalid attribute number -2 for bgw_job_stat
CONTEXT:  automatic vacuum of table "pistac._timescaledb_internal.bgw_job_stat"
ERROR:  invalid attribute number -2 for bgw_job_stat
.....

Postgres starts without problems, but when we try to show the tables in the database we get this error:
psql=# \dt
ERROR:  invalid attribute number -5 for hypertable

 

### TimescaleDB version affected

1.7.4

### PostgreSQL version used

 PostgreSQL 12.5

### What operating system did you use?

Ubuntu 18.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

**Comment by RafiaSabih** [comment]
Thanks @ferfebles for reporting this issue. We really appreciate your taking time out to file it. But in order to help you with this, we would need more information like the schema of the tables involved, any DDL queries you suspect, if you can provide some steps to reproduce the issue, etc.

**Comment by NunoFilipeSantos** [comment]
@ferfebles can you please upgrade to TimescaleDB 2.5.1 and get back to us?

**Comment by ferfebles** [comment]
Sorry guys but we had to get the database working today, so I spent the Sunday recovering the server from the Friday backup. It was almost 1TB of data. It took a few hours but everything is working ok.

We are seriously considering the upgrade.

**Comment by NunoFilipeSantos** [comment]
Thank you @ferfebles ! We hope you enjoy our new features!
