### ISSUE TITLE
[Enhancement]: Import chunk compression stats to access node

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4027]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Compression, Distributed hypertable

### What does the enhancement do?

When compressing a  chunk on a distributed hypertable, the chunk is compressed on the data node and that is also where the compression stats for the chunk is stored. Therefore, the access node lacks the compression stats for the chunk. 

The enhancement would change this to import the compression stats to the access node when the chunk is compressed.

### Implementation challenges

The compression stats table for the chunk includes the chunk ID of the main chunk and the auxiliary compressed chunk. On the access node, the latter doesn't exist and the main chunk ID is also different. This has to be accounted for when importing the stats. 

To store the stats on the access node, the main chunk ID has to be translated to the local ID and the compressed chunk ID should be set to, e.g., NULL (indicating that this is a remote compressed chunk).

**Comment by svenklemm** [comment]
multinode has been removed
