### ISSUE TITLE
[Enhancement]: ANALYZE should analyze distributed hypertables

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4046]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Command processing, Distributed hypertable

### What does the enhancement do?

Running a "global" `ANALYZE` will not import stats for distributed hypertables, although such tables can be individually analyzed with `ANALYZE disttable` at which point stats will be imported from data nodes.

For convenience, the global `ANALYZE` should also include distributed hypertables.

### Implementation challenges

Importing stats from data nodes could be costly and might slow down `ANALYZE`. In some cases, data nodes might not respond due to temporary failures and that might break `ANALYZE`. Ideally,  in those failure scenarios, the global `ANALYZE` should probably succeed but raise a notice/warning that a distributed hypertable couldn't be analyzed.

**Comment by 65278** [comment]
Since analyze and vacuum are handled in the same codepath, do you also want this for global vacuum?

**Comment by erimatnor** [comment]
@65278 Not sure how to handle vacuum. Ideally, distributed hypertables should be analyzed like any other tables, but there are caveats as pointed out under "Implementation challenges". Also note that autovacuum still runs on data nodes. On the access node, we simple need to import the statistics from the data nodes.

Right now, none of this happens "automatically", which is the problem.

**Comment by 65278** [comment]
I've made this work, but a warning for a specific table is not really in the cards. One data node can hold multiple tables, and we could only raise a warning per data node.
The only place where we can warn per table is at the import of statistics, as those are done per `relid`.

**Comment by SHxKM** [comment]
> although such tables can be individually analyzed with `ANALYZE disttable` at which point stats will be imported from data nodes.

Does anyone have any way to reach this so called `disttable` name in order to run `ANALYZE`?

**Comment by svenklemm** [comment]
multinode has been removed
