### ISSUE TITLE
[Bug]: time_bucket_ng CAGG with TimestampTz Column

### ISSUE THREAD

**Issue by aarondglover** [timescale/timescaledb#4061]
### What type of bug is this?

Incorrect result, Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

ERROR: `continuous aggregate view must include a valid time bucket function`

```
CREATE MATERIALIZED VIEW myagg
    WITH (
            timescaledb.continuous
            ) AS
SELECT
    timescaledb_experimental.time_bucket_ng('1 Days', "timestamp") AS ts
    ,SUM("value"::NUMERIC) AS SUM_VALUE
FROM myHyperTable
GROUP BY
    device_id
    ,ts
WITH DATA;
```

Perplexed by this error I confirmed that the select statement works as expected. Also confirmed that simple usage of "time_bucket_ng()" is supported in CAGGs (Continuous Aggregates)

I found in the slack channel that this issue is because the column used in the time_bucket_ng function is of type

`timestamp with time zone / timestamptz`

Trying to cast the column to a timestamp (instead of timestamptz) with the following

```
timescaledb_experimental.time_bucket_ng('1 Days', "timestamp"::timestamp) AS ts

ERROR:  time bucket function must reference a hypertable dimension column
```

1.  I would expect CAGGs that use the time_bucket_ng() function to work if the hypertable time dimension column is a `timestamptz`
2. The error message should be clearer about the problem.

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

13.5

### What operating system did you use?

Timescale Managed DB ????

### What installation method did you use?

Other

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### How can we reproduce the bug?

```bash
1. Create a hypertable with time dimension column being a timestamptz 
2. Attempt to create a CAGG using timescaledb_experimental.time_bucket_ng using the afforementioned table and timestamptz column
```

**Comment by afiskon** [comment]
Hi @aarondglover 

Although time_bukcet_ng() supports timestamptz, CAGGs can't use time_bucket_ng() with timestamptz in version 2.5.0. This is a documented behavior, please see the table at the end of https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/#sample-usage

The upcoming release 2.6.0 will support this.
