### ISSUE TITLE
[Enhancement]: Roll up multiple uncompressed chunks into single compressed chunk

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4079]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Compression, Partitioning

### What does the enhancement do?

For high-ingest use cases (e.g., Promscale), it would be beneficial to be able to have small chunk sizes for uncompressed data in order to keep, e.g., index sizes small. However, having many small chunks can be bad for query performance so to offset that performance issue it would be good to be able to roll up several uncompressed chunks into one compressed chunk, which will still have a relatively small footprint in terms of disk space.

The Promscale team should be able to give more information on the performance benefits.

### Implementation challenges

Check with @cevian and @antekresic for recommendations on implementation.

### Why

When you combine the compressed chunks the performance should be better.

### How

- [ ] ...

**Comment by jfjoly** [comment]
@cevian assigning to you , please add others who will work on that or link to another issue.
