### ISSUE TITLE
dynamic pruning of search tree

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#408]
I noticed @erimatnor implemented a feature a while ago to do pruning of search trees dynamically, in order to allow searching in only a subset of the partitions when you have queries with non-constant values in the WHERE-clause.

This feature seems to work mostly well for single queries dealing with non-constant functions. Though, from what I can see in the code (and from my experience in using it), it does not seem to be able to prune dynamic values in nested loops. For example, something I am interested in is similar to the following:

`select * from (select sensor_id, sensor_time from interesting_times) t cross join lateral (select * from time_series_table ts where ts.time between sensor_time-interval '1 day' and sensor_time order by time desc limit 1) gr;`

Above query retrieves times and id's (of some sensor, for example) from some table and tries to find the state of that sensor at that time. Because this 'time' is not known at planning time, the search tree is not pruned. Also, the method previously implemented by @erimatnor prunes at ca_append_begin, which I think cannot take into account this nested loop situation, because ca_append_begin is only executed once.

Then again, I don't know if it is possible to prune further at ca_append_exec and whether this would be worth the overhead. In my specific case outlined above, I think it would make a big difference, because it would be able to select just 1 chunk to search through instead of searching through all chunks of data.

Does anyone know 1) if it is possible to implement 2) if it is worth implementing, and 3) what roughly the required steps would be to implement this?

**Comment by erimatnor** [comment]
Hi @fvannee. Thanks for requesting this feature. Dynamic pruning currently doesn't work for JOINs, but is certainly something we would like to support. 

Regarding implementation, I believe this needs to be implemented in the `join_pathlist_hook` as opposed to the `rel_pathlist_hook`, which the current pruning uses.

I will add this to our list of potential optimizations that we'd like to support. We have to prioritize features based on demand, though. We're of course happy to receive contributions.

**Comment by msqr** [comment]
I recently came across this situation as well (using a lateral join) and realized the same as @fvannee. I ended up using a pl/pgsql function that performed the loop manually via one query for the data to loop over and then another for each iteration, and then the iteration query was able to make use of partition pruning. This approach always performed much better in my use cases.

I also just noticed that [Postgres 11 has been improving](https://www.postgresql.org/docs/11/static/release-11.html#id-1.11.6.5.5.3.2) in this area as well (query-time pruning).

**Comment by esatterwhite** [comment]
I'm also trying to use a lateral join and seeing this behavior. Would love to see the improvement as well

**Comment by esatterwhite** [comment]
We also use CTEs quite a bit to do things like this as another example
```sql
WITH unread AS (
  SELECT
    MIN(unread_messages.message_timestamp) as min_ts
  , MAX(unread_messages.message_timestamp) as max_ts
  , ARRAY_AGG(message_id) as message_ids
  FROM unread_messages
  WHERE unread_messages.conversation_id = '3e1ea7df-daa5-4941-bf58-bc418974f623'
  GROUP BY conversation_id
)
SELECT events.event_content 
FROM unread
INNER JOIN events on id = ANY(message_ids)
WHERE events.created_at between unread.min_ts and unread.max_ts
```
