### ISSUE TITLE
remote_connection test failure on postgres REL_14_STABLE

### ISSUE THREAD

**Issue by akuzm** [timescale/timescaledb#4096]
This test is going to start failing on the next PG release. Noticed it on the prerelease tests that use a development snapshot as well. 
Here is how it looks:
```
SELECT test.remote_async_tests();
- remote_async_tests 
---------------------
- 
-(1 row)
-
-\echo 'End Of Test'
-End Of Test
+ERROR:  failed to panic @ line 230
```
Link: https://github.com/timescale/timescaledb/runs/5181345428?check_suite_focus=true#step:16:30

The reason seems to be [this commit](https://github.com/postgres/postgres/commit/ae27b1acc43d58badad356a4da8fc0c72d46d7fb) that subtly changed how the connection loss is handled, so now we don't get an exception where we used to.

**Comment by svenklemm** [comment]
I think I fixed the offending test in https://github.com/timescale/timescaledb/pull/4270
