### ISSUE TITLE
Install for Windows 11 "This version of %1 is not compatible with the version of Windows you're running. "

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [timescale/timescaledb#4097]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Packaging

### What happened?

Windows 11 with all current patches
Timescale 2.5.0
PostGreSql 14.1 build 1914 64 bit currently installed.
Trying to update to 2.5.1
C:\Users\Super\Downloads\timescaledb-postgresql-14_2.5.1-windows-amd64\timescaledb>setup.exe -pgconfig I:\PostgreSQL\14\bin\pg_config.exe
2022/02/13 11:12:14 WELCOME to TimescaleDB Windows installer!
2022/02/13 11:12:14 ERROR: could not get `pg_config --pkglibdir`: fork/exec I:\PostgreSQL\14\bin\pg_config.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Press ENTER/Return key to close...

Did try https://github.com/timescale/timescaledb/issues/3418

C:\Users\Super\Downloads\timescaledb-postgresql-14_2.5.1-windows-amd64\timescaledb>timescaledb-tune.exe -pg-config I:\PostgreSQL\14\bin\pg_config.exe -conf-path E:\PostgreSQL\14\data\postgresql.conf
←[31;1mexit: ←[0mcould not execute `I:\PostgreSQL\14\bin\pg_config.exe --version`: fork/exec I:\PostgreSQL\14\bin\pg_config.exe: This version of %! (MISSING)is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Windows 11  Version 10.0.22000.493

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
1
```

### How can we reproduce the bug?

```bash
1
```

**Comment by horzsolt** [comment]
Hi @SuperDaveOsbourne thanks for submitting this issue. We are going to look at it.

**Comment by horzsolt** [comment]
@SuperDaveOsbourne I tried to reproduce the problem several times, but I was able to do the update, didn't hit the issue (I used the same PG setup, locations, windows version). 
Can you please manually execute `pg_config --version` in the `I:\PostgreSQL\14\bin` directory and after this launch the same command from another, arbitrary location and paste your result here?

**Comment by SuperDaveOsbourne** [comment]
Ran windows compatibility tool on pg_config.exe for windows 7 and it seems to work now.
