### ISSUE TITLE
[Bug]: ERROR:  chunk not found

### ISSUE THREAD

**Issue by vtkageyama** [timescale/timescaledb#4101]
### What type of bug is this?

Other

### What subsystems and features are affected?

Backup

### What happened?

I made backup and restore using pg_dump/pg_restore follwing the documentation:
https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/

After restore I try select on table and show me the error:

restore=# select * from history limit 1;
ERROR:  chunk not found
DETAIL:  schema_name: _timescaledb_internal, table_name: _hyper_1_5262_chunk

### TimescaleDB version affected

2.5.2

### PostgreSQL version used

12.8

### What operating system did you use?

CentOS Linux release 7.9.2009 (Core)

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
restore=# \d+ history
                                      Table "public.history"
 Column |       Type       | Collation | Nullable | Default | Storage | Stats target | Description
--------+------------------+-----------+----------+---------+---------+--------------+-------------
 itemid | bigint           |           | not null |         | plain   |              |
 clock  | integer          |           | not null | 0       | plain   |              |
 value  | double precision |           | not null | 0.0000  | plain   |              |
 ns     | integer          |           | not null | 0       | plain   |              |
Indexes:
    "history_clock_idx" btree (clock DESC)
    "public_history_itemid1_idx" btree (itemid, clock, value, ns)
Triggers:
    ts_insert_blocker BEFORE INSERT ON history FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
Child tables: _timescaledb_internal._hyper_1_5262_chunk,
              _timescaledb_internal._hyper_1_5305_chunk,
              _timescaledb_internal._hyper_1_5316_chunk,
              _timescaledb_internal._hyper_1_5326_chunk,
              _timescaledb_internal._hyper_1_5336_chunk,
              _timescaledb_internal._hyper_1_5347_chunk,
              _timescaledb_internal._hyper_1_5359_chunk,
              _timescaledb_internal._hyper_1_5368_chunk,
              _timescaledb_internal._hyper_1_5378_chunk,
              _timescaledb_internal._hyper_1_5387_chunk,
              _timescaledb_internal._hyper_1_5401_chunk,
              _timescaledb_internal._hyper_1_5412_chunk,
              _timescaledb_internal._hyper_1_5422_chunk,
              _timescaledb_internal._hyper_1_5432_chunk,
              _timescaledb_internal._hyper_1_5443_chunk
Access method: heap
Options: autovacuum_vacuum_scale_factor=0.05
```

### How can we reproduce the bug?

```bash
Backup:
pg_dump -Fc -d pg_xp_zabbixdb -j 10 -v  -f /data/backup/dump


Restore:
CREATE DATABASE restore;
\c restore

CREATE EXTENSION IF NOT EXISTS timescaledb;
SELECT timescaledb_pre_restore();

\! pg_restore -j 30 -d restore -v /data/backup/dump/
```

**Comment by vtkageyama** [comment]
I'm using same server to testing backup and restore.

For backup: what is the OS + PG version + Timescale version?
A: CentOS Linux release 7.9.2009 (Core) +  12.8 + 2.5.2

For restore: what is the OS + PG version + Timescale version?
A: CentOS Linux release 7.9.2009 (Core) +  12.8 + 2.5.2

Are you backing up and restoring on the same timescale version?
A: yes.

**Comment by gayyappan** [comment]
pg_restore -j option does not work with timescaledb.

See: https://github.com/timescale/timescaledb/issues/698

Please try the workaround suggested there. 
1. Restore the timescaledb_catalog first 
2. Restore the data.
