### ISSUE TITLE
[Bug]: time_bucket_gapfill() returns values before start date

### ISSUE THREAD

**Issue by deepesh15** [timescale/timescaledb#4107]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

I'm trying to bucket fires data into buckets of 3 days, and I'm providing start date from 2021, and the results should also start from 2021, but I'm getting values for 2020 as well.

Query:
```SQL
SELECT
  COUNT(*) AS fires,
  time_bucket_gapfill(
    '3 day',
    "Fires"."recorded_at",
    TIMESTAMP '2021-01-01T18:30:00Z',
    TIMESTAMP '2021-01-06T18:29:59Z'
  ) AS datetime
FROM
"Fires"
WHERE
"Fires"."recorded_at" BETWEEN '2021-01-01T18:30:00Z' AND '2021-01-06T18:29:59Z'
GROUP BY
  datetime;
```

### TimescaleDB version affected

2.4.2

### PostgreSQL version used

13.4

### What operating system did you use?

Ubuntu 20.04

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
Output :-

 fires |        datetime        
-------+------------------------
   500 | 2020-12-31 00:00:00+00
  1500 | 2021-01-03 00:00:00+00
   500 | 2021-01-06 00:00:00+00

```
![image](https://user-images.githubusercontent.com/39853188/154451023-98054a48-e5b6-4fc0-8609-4bbc4b0e3905.png)

**Comment by horzsolt** [comment]
Hi @deepesh15 thanks for submitting the issue. Can you please share with us the "Fires" table definition and some test data (if possible), so that we can reproduce the issue locally.

**Comment by svenklemm** [comment]
The result is correct, the returned values are bucketed by the gapfill interval that's why it is lower than the start value supplied as argument.

```
sven@dev[637565]=# select time_bucket('3day','2021-01-01T18:30:00Z'::timestamp);
     time_bucket
---------------------
 2020-12-31 00:00:00
(1 row)
```

**Comment by sudoStatus200** [comment]
@svenklemm  As oer docs `start` option in `time_bucket_gapfill`  says this `The start of the gapfill period` in docs, 

does not this mean there should be no date before the supplied `start date`  , as gapfill should not gapfill anything before supplied date ?

**Comment by svenklemm** [comment]
Maybe the docs are a bit unclear but the start option will be aligned to the bucket start of your bucketing interval.
So If you bucket by '1 hour' and your start is '12:30' you might still get values from between '12:00' and '12:30' because time_bucket('1 hour', '12:30') is '12:00'.
