### ISSUE TITLE
[Bug]: GitHub Release 2.6.0

### ISSUE THREAD

**Issue by EtienneM** [timescale/timescaledb#4114]
### What type of bug is this?

Other

### What subsystems and features are affected?

Build system, Other

### What happened?

I noticed the commit 9e7fbf7f6982bad80cd0129d38dcf6273baad2a2 last week, with a Git tag [2.6.0](https://github.com/timescale/timescaledb/releases/tag/2.6.0). But I don't see the associated GitHub release (https://github.com/timescale/timescaledb/releases). Is something wrong with this release? Or the release process of this version is still ongoing?

Thanks :) 

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

any

### What operating system did you use?

any

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

**Comment by akuzm** [comment]
The release is still being prepared, we will create a GitHub release when it's ready.
