### ISSUE TITLE
[Bug]: Cannot use time_bucket_ng when creating continuous aggregate

### ISSUE THREAD

**Issue by AuspeXeu** [timescale/timescaledb#4115]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

```
CREATE MATERIALIZED VIEW readings_week
WITH (timescaledb.continuous) AS
  SELECT
    site_id,
    meter_id,
    timescaledb_experimental.time_bucket_ng('1 week', timestamp) AS bucket,
    SUM(value)
  FROM readings
  GROUP BY bucket, meter_id, site_id
WITH NO DATA;
```

Executes with error `ERROR: continuous aggregate view must include a valid time bucket function`

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

12

### What operating system did you use?

timescale/timescaledb:2.5.1-pg12

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by afiskon** [comment]
@AuspeXeu thanks for the report. Please provide minimal steps to reproduce the issue and/or the schema of the `readings` table.

**Comment by AuspeXeu** [comment]
Of course, sorry.

```
CREATE TABLE "readings" (
  "meter_id" INT NOT NULL,
  "site_id" INT NOT NULL,
  "timestamp" TIMESTAMPTZ NOT NULL,
  "value" DOUBLE PRECISION NOT NULL
);
```

**Comment by afiskon** [comment]
@AuspeXeu I'm afraid that's not a bug.

1. "timestmap" is TimestampTz. time_bucket_ng() can be used with TimestampTz in continuous aggregates only in TimescaleDB 2.6.0+ (going to be announced very soon). Please see the table at the end of https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/#sample-usage
2. Even in TimescaleDB 2.6.0 you should specify the timezone argument for time_bucket_ng() when dealing with TimestampTz

**Comment by AuspeXeu** [comment]
@afiskon if I understood correctly, my query should work on version 2.6.0. However, I am still getting the same error.
