### ISSUE TITLE
[BUG] time_bucket offset examples all report SQL Error with continuous aggregates

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [timescale/timescaledb#4116]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Any of the examples of offset for time_bucket result in error SQL Error [XX000]: ERROR: continuous aggregate view must include a valid time bucket function.

Following the examples on the documentation pages or the online YouTube videos all result in valid bucket function errors.

Postgresql 14.1 TimescaleDb 2.51 on Windows 11.

```
`DROP materialized view IF exists sixty_five_mv;
create materialized view sixty_five_mv
with (timescaledb.continuous,timescaledb.create_group_indexes) as
SELECT time_bucket(interval '30m', quote_date,  TIMESTAMP '2017-12-31')  as bucket,symbol,
FIRST(open_price,quote_date) as open_price,
LAST(close_price, quote_date) as close_price,
MIN(low_price) as low_price,
MAX(high_price) as high_price,
SUM(volume) as volume,
from five_mins_ht 
group by bucket,symbol
with no data;` 
```

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Windows 11  Version 10.0.22000.493

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
SQL Error [XX000]: ERROR: continuous aggregate view must include a valid time bucket function
```

**Comment by gayyappan** [comment]
Continuous aggregates do not support time_bucket with offset.
(See supported SELECT query here)
https://docs.timescale.com/api/latest/continuous-aggregates/create_materialized_view/#create-materialized-view-continuous-aggregate
