### ISSUE TITLE
Unexpected disk writes on AN during INSERT

### ISSUE THREAD

**Issue by 2779382063** [timescale/timescaledb#4118]
_Use this template for reporting bugs in the docs._

Using version 2.5.1, when inserting a large amount of data into the distributed hypertable, it is found that the AN node also writes the same data as the DN node. The iops of the AN node is higher than that of the DN node, resulting in performance degradation. It stands to reason that the AN node only records metadata and does not write to the disk. The test found that the AN node is also writing to the disk frantically. Why? 

# Describe the bug

[Provide as much detail as you can]

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by nikkhils** [comment]
@2779382063 is the data being inserted via many individual transactions? In that case, yes, the AN will also generate WAL because it tracks the inserts via a local `remote_txn` table. It will help to bunch up multiple inserts into one large single transaction on the AN to help reduce the WAL traffic on it.

**Comment by erimatnor** [comment]
@2779382063 Please provide a way to reproduce this issue. As @nikkhils points out, some writes will happen on the AN for bookkeeping purposes, but it should be nowhere close to the writes going to data nodes. Make sure that you don't use single-row INSERT statements. Use COPY if possible.

**Comment by 2779382063** [comment]
is a single-line insert method for writing ，Write 100 million data, according to the data directory of pg, it is found that the directory data size of the written library is: the data in the AN node is greater than 1G, and the data in a single DN node is less than 1G. The amount of data written by the AN node is too large, and it is a single node, resulting in a decrease in distributed performance 

//test program ：go run cj.go -s 100000000
package main
 
import (
   "context"
   "fmt"
   "os"
   "flag"
   "sync"
   "time"
   "math/rand"
 
 //  "github.com/jackc/pgx/v4"
   "github.com/jackc/pgx/v4/pgxpool"
)
 
func go_process() {
 
        ctx := context.Background()
        connStr := "host='172.16.3.180' port=5432 user=mn_tsdb password=pass11word dbname=tsdb2 sslmode=disable"
        dbpool, err := pgxpool.Connect(ctx, connStr)
        if err != nil {
                fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
                os.Exit(1)
        }
        defer dbpool.Close()
 
        var ts time.Time
        var source  string
        var temp  int
        queryInsertMetadata := `INSERT INTO weather1 (ts,source,temp) VALUES ($1,$2,$3);`
 
        //fmt.Printf("Inserted sensor (%s, %s) into database \n", sensorTypes[i], sensorLocations[i])
        for i := 0; i < psnum; i++ {
                ts = time.Now()
                source = fmt.Sprintf("%d", rand.Intn(10000))
                temp = rand.Intn(100)
                _, err := dbpool.Exec(ctx, queryInsertMetadata,ts,source,temp)
                if err != nil {
                        fmt.Fprintf(os.Stderr, "Unable to insert data into database: %v\n", err)
                        os.Exit(1)
                }
        }
        wg.Done()
}
var wg sync.WaitGroup
//var unum,psnum  int
var snum,psnum int
//ctx := context.Background()
//connStr := "host='172.16.3.180' port=5432 user=mn_tsdb password=pass11word dbname=tsdb2 sslmode=disable"
//dbpool, err := pgxpool.Connect(ctx, connStr)
 
func main() {
 
  //  flag.IntVar(&unum,"u",1000,"")
    flag.IntVar(&snum,"s",50000000,"")
    flag.Parse()
    // 输出结果
    psnum = snum / 32
 
  // ctx := context.Background()
  // connStr := "host='172.16.3.180' port=5432 user=mn_tsdb password=pass11word dbname=tsdb2 sslmode=disable"
  // dbpool, err := pgxpool.Connect(ctx, connStr)
  // if err != nil {
//              fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
//              os.Exit(1)
  // }
  // defer dbpool.Close()
 
 
    wg.Add(32)
    for i := 0; i < 32; i++ {
        go go_process()
    }
    //wg.Done()
    wg.Wait()
}

**Comment by erimatnor** [comment]
@2779382063 We don't recommend doing row-by-row inserts as this leads to poor performance. It might also explain some of the WAL generated on the access node, since it needs to write bookkeeping information for every distributed transaction. 

There are a couple of things you can try:

* Insert many rows in a single insert or copy statement
* Try to use COPY instead of INSERTs
* At the very least, wrap the INSERTS in a bigger transaction (BEGIN/END)

**Comment by 2779382063** [comment]
In the distributed hypertable, the above program is used to write a large amount of data for pressure testing, and it is found that the data written to the disk of the AN node is larger than that of the DN node, resulting in a write bottleneck of the AN node. The AN node should not only record metadata, why does the disk write Is the input bigger than the data node?
The following is the size of the disk space where 1 AN node and 3 DN nodes write the table before and after data writing.

cd /data/pgsql/data/base
[root@pcx-b-01 base]# du -h
Before writing:
AN:
9.6G ./18373
DN1:
723M ./35609
DN2:
736M ./35441
DN3:
744M ./35777

After writing:
AN:
10G ./18373
DN1:
787M ./35609
DN2:
801M ./35441
DN3:
810M ./35777

**Comment by nikkhils** [comment]
@2779382063 it's because the AN has to track ALL txns happening on all the 3 DNs.

Can you please modify the `go_process` function to use the following (pseudo code shown below, please adapt appropriately)

```
tx, err := db.BeginTx(ctx, nil)

for i := 0; i < psnum; i++ {
            ts = time.Now()
            source = fmt.Sprintf("%d", rand.Intn(10000))
            temp = rand.Intn(100)
            _, err :=  tx.ExecContext(ctx, queryInsertMetadata,ts,source,temp)
            if err != nil {
                    fmt.Fprintf(os.Stderr, "Unable to insert data into database: %v\n", err)
                    os.Exit(1)
            }
    }

err = tx.Commit()
```

The above will bunch up `psnum` number of INSERTs into one single transaction. This should help reduce the number of entires on the AN considerably.

**Comment by pmwkaa** [comment]
Additionally it worth to checkout the multi-node maintenance:
https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-maintenance/

By running this function access node will delete unnecessary information about completed transactions and free up space as well

**Comment by nikkhils** [comment]
@2779382063 please let us know if bunching up inserts in bigger transactions helps your case.

**Comment by NunoFilipeSantos** [comment]
Hi @2779382063 ! 👋 Please let us know if the help provided was sufficient for your case. Feel free to reopen this issue.

**Comment by 2779382063** [comment]
The help provided above does improve the insertion performance. One AN node and 3 DN nodes can write 150 million per second, but this speed is not enough for the pursuit of millions of concurrent writes. What other improvements are there? Allow me to achieve a greater amount of concurrency?
By the way, is there any plan to scale out the AN node in the future?

**Comment by 2779382063** [comment]
The help provided above does improve the insertion performance, but this speed is not enough for the pursuit of millions of concurrent writes. What other improvements are there? Allow me to achieve a greater amount of concurrency?
By the way, is there any plan to scale out the AN node in the future?

**Comment by NunoFilipeSantos** [comment]
@erimatnor can you help here? Thanks.
