### ISSUE TITLE
[Bug]: Cannot use time_bucket_ng when creating continuous aggregate

### ISSUE THREAD

**Issue by AuspeXeu** [timescale/timescaledb#4130]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

```
CREATE MATERIALIZED VIEW readings_week
WITH (timescaledb.continuous) AS
  SELECT
    site_id,
    meter_id,
    timescaledb_experimental.time_bucket_ng('1 week', timestamp) AS bucket,
    SUM(value)
  FROM readings
  GROUP BY bucket, meter_id, site_id
WITH NO DATA;
```

Executes with error `ERROR: continuous aggregate view must include a valid time bucket function`

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

12

### What operating system did you use?

timescale/timescaledb:2.5.1-pg12

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by svenklemm** [comment]
This is a current limitation the following should work:
```
CREATE MATERIALIZED VIEW readings_week
WITH (timescaledb.continuous) AS
  SELECT
    site_id,
    meter_id,
    timescaledb_experimental.time_bucket_ng('1 week', timestamp, 'Europe/Berlin') AS bucket,
    SUM(value)
  FROM readings
  GROUP BY bucket, meter_id, site_id
WITH NO DATA;
```
