### ISSUE TITLE
[Feature]: cascading caggs

### ISSUE THREAD

**Issue by AuspeXeu** [timescale/timescaledb#4132]
### What problem does the new feature solve?

Let's assume we have a value being sampled at 1 minute intervals and we want to have continuous aggregates over hours, days, weeks, months, and years.

Right now, all these different let's call them resolutions of the data have to be based on the same underlying hypertable which contains values sampled at 1 minute intervals. Obviously, it could be much cheaper if the cagg with the more coarse resolution e.g. year would simply be based on the month cagg as the month cagg is already a much smaller result set than the base table which is sampled at 1 minute intervals.

### What does the feature do?

Allow continous aggregates to reference continous aggregates.

**Comment by jfjoly** [comment]
Thanks @AuspeXeu for suggesting the enhancement ! 
This may be similar to https://github.com/timescale/timescaledb/issues/1400

What kind of aggregate functions are you using for your continuous aggregates ?
An aggregate on top of another aggregate may give surprising results for instance with `avg()`

**Comment by AuspeXeu** [comment]
It's very similar, yes. I am using `sum()` as aggregator.

**Comment by friedhelmvictor** [comment]
I second this feature. It's basically the same as #1400.

Of course cascading averages are not the same as an average of the underlying raw data, but I would trust that users know this.
In fact, I can imagine the resulting inaccuracy may even be acceptable for some use cases.

In cases where you build cascades of `first()`,`last()`,`min()`,`max()` and `sum()` there isn't a problem though. In many financial use cases (i.e. OHLCV data) that is what's needed, and would save lots of time.

Is this just about changing permissions? Or is there a deeper technical reason for not allowing cascading caggs?
If the former, a cautious approach could be some configuration setting that allows this, and still preventing it in default configurations.

**Comment by nikkhils** [comment]
@AuspeXeu @friedhelmvictor I am closing this since #1400 is tracking this enhancement.
