### ISSUE TITLE
[Bug]: refresh_continuous_aggregate without start and end on aggregates using time_bucket_ng

### ISSUE THREAD

**Issue by AuspeXeu** [timescale/timescaledb#4133]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

First, I create a continuous aggregate as such

```
CREATE MATERIALIZED VIEW readings_week
WITH (timescaledb.continuous) AS
  SELECT
    site_id,
    meter_id,
    timescaledb_experimental.time_bucket_ng('1 week', timestamp, 'Europe/Berlin') AS bucket,
    SUM(value)
  FROM readings
  GROUP BY bucket, meter_id, site_id
WITH NO DATA;
```

However, when I want to trigger the initial population of the view using:

```
CALL refresh_continuous_aggregate('readings_week', NULL, NULL);
```

It executes with error `ERROR:  origin must be before the given date`

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

12

### What operating system did you use?

timescale/timescaledb:2.6.0-pg12

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by mfundul** [comment]
Revelant comment from @afiskon https://github.com/timescale/timescaledb/issues/4117#issuecomment-1047512830

**Comment by nikkhils** [comment]
@AuspeXeu did you have a chance to look at @afiskon's comment?
