### ISSUE TITLE
[Enhancement]: Auto-disable 2pc on access node when in ready-only mode

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4134]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Distributed hypertable, Multi-node

### What does the enhancement do?

When an access node is in read-only mode, transactions will fail due to 2pc trying to write records to the `remote_txn` bookkeeping table.
```
ERROR: cannot assign TransactionIds during recovery
```

However, in read-only mode, 2pc shouldn't be necessary and we could automatically disable 2pc in this case.

**Comment by nikkhils** [comment]
@erimatnor we already have a check for this in `dist_txn_xact_callback` function. We avoid 2PC if `xactReadOnly` is set to `on`. Do we have a test case for where this fails?

**Comment by erimatnor** [comment]
> @erimatnor we already have a check for this in `dist_txn_xact_callback` function. We avoid 2PC if `xactReadOnly` is set to `on`. Do we have a test case for where this fails?

There was a user reporting that this didn't work.

**Comment by svenklemm** [comment]
multinode has been removed
