### ISSUE TITLE
[Flaky test] snapshot tests are constantly failing

### ISSUE THREAD

**Issue by pmwkaa** [timescale/timescaledb#4153]
### Which test is flaky?

remote_connection

### Since when has the test been flaky?

February 11

### Link to the failed test run

https://github.com/timescale/timescaledb/runs/5454671249?check_suite_focus=true

### Log output

```bash
-\echo 'End Of Test'
-End Of Test
+ERROR:  XX000: failed to panic
+LOCATION:  test_node_death, async.c:230
```

### Reason for flakiness

Might be related to `PQcancel` changes in the upstream:

https://github.com/postgres/postgres/commit/5987feb70b5bbb1fc4e64d433f490df08d91dd45
https://github.com/postgres/postgres/commit/f3f467b8f69b673fb73d15bf5ccd3a2027403d7b

**Comment by pmwkaa** [comment]
I was able to reproduce the issue against latest snapshot build locally.

Also I was able to identify commit, which is introduced it:  https://github.com/postgres/postgres/commit/51ee561f5671cd92f6dcaacf043985c497a82fc1, this commit was backported to PG12-13

**Comment by svenklemm** [comment]
This has been fixed quite a while ago.
