### ISSUE TITLE
[Bug]: Query planner gets confused when filtering on domain types while scanning compressed chunks

### ISSUE THREAD

**Issue by niksajakovljevic** [timescale/timescaledb#4179]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Query planner

### What happened?

If we define the following PG domain type: 
`CREATE DOMAIN my_uuid UUID`

And we define the following hypertable `t`: `CREATE TABLE t (time timestamptz, x my_uuid);`

And set the following compression settings:

` ALTER TABLE t SET (timescaledb.compress, timescaledb.compress_segmentby='', timescaledb.compress_orderby='x');`

If we have compressed chunks to scan and run an explain:
 `EXPLAIN SELECT * FROM t where x = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid`

We would notice that our filter `x = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid` would not be used when scanning compressed chunks which would lead to decompressing the whole chunk instead of only specific segment which could be determined by compression min/max metadata for `x` column.

If instead of domain type we use plain PG type, eg : `UUID`, the query planner produces the optimal plan.

An example of query plan when using domain type:

```
 ->  Custom Scan (DecompressChunk) on _hyper_1_2_chunk  (cost=0.06..3587.56 rows=62256000 width=353)
         Filter: ((trace_id)::uuid = (('00000000-0000-0000-0000-1a6ef6292365'::uuid)::trace_id)::uuid)
         ->  Seq Scan on compress_hyper_7_6_chunk  (cost=0.00..3587.56 rows=62256 width=676)
   ->  Custom Scan (DecompressChunk) on _hyper_1_3_chunk  (cost=0.06..3587.56 rows=62256000 width=353)
         Filter: ((trace_id)::uuid = (('00000000-0000-0000-0000-1a6ef6292365'::uuid)::trace_id)::uuid)
         ->  Seq Scan on compress_hyper_7_8_chunk  (cost=0.00..3587.56 rows=62256 width=676)
```

An example of query plan without domain type:
```
 Custom Scan (DecompressChunk) on _hyper_1_4_chunk  (cost=0.29..20.48 rows=70000 width=251) (actual time=0.773..0.795 rows=0 loops=1)
         Filter: (trace_id = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid)
         Rows Removed by Filter: 1000
         ->  Seq Scan on compress_hyper_4_7_chunk  (cost=0.00..20.48 rows=70 width=676) (actual time=0.119..0.164 rows=1 loops=1)
               Filter: ((_ts_meta_min_1 <= 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid) AND (_ts_meta_max_1 >= 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid))
               Rows Removed by Filter: 298
```

I tried specifying filter in different ways: 
- `x = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::uuid`
- `x = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'`
- `x = 'a499920a-34f0-70c6-cb5a-6cb28c1addb0'::my_uuid`

However it didn't work. The only fix for me was to not use domain type.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu

### What installation method did you use?

Docker

### What platform did you run on?

Other

**Comment by svenklemm** [comment]
For this to work your custom type needs to have some supporting operators defined.
