### ISSUE TITLE
[Bug]: Gapfill outputting strange results

### ISSUE THREAD

**Issue by dchun** [timescale/timescaledb#4194]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

I have a table I am trying to gapfill on a daily basis. When I run the gapfill function with only one record returned it works as expected but when two or more results are included I get strange results. These are sample records in my database:

| id   | date       | outstanding | ticker_id | created_at                 | updated_at                 |
| ---- | ---------- | ----------- | --------- | -------------------------- | -------------------------- |
| 2814 | 2021-11-02 | 1174930172  | 7611      | 2022-03-20 17:33:11.593464 | 2022-03-20 17:33:11.593464 |
| 2815 | 2022-01-28 | 1165004913  | 7611      | 2022-03-20 17:33:11.593464 | 2022-03-20 17:33:11.593464 |

When I run the following query it works as expected:
```sql
SELECT
	time_bucket_gapfill ('1 day', s.date) AS day,
	locf (s.outstanding)
FROM
	shares s
WHERE
        s.ticker_id = 7611 AND
	s.date BETWEEN '2022-01-26' AND '2022-01-30'
GROUP BY
	day,
	s.outstanding
ORDER BY
	day
```
I get the following:
| day        | locf       |
| ---------- | ---------- |
| 2022-01-26 |            |
| 2022-01-27 |            |
| 2022-01-28 | 1165004913 |
| 2022-01-29 | 1165004913 |
| 2022-01-30 | 1165004913 |

However, when I change the start date to include the previous record like soo:
```sql
SELECT
	time_bucket_gapfill ('1 day', s.date) AS day,
	locf (s.outstanding)
FROM
	shares s
WHERE
        s.ticker_id = 7611 AND
	s.date BETWEEN '2021-11-01' AND '2022-01-30'
GROUP BY
	day,
	s.outstanding
ORDER BY
	day
```

I don't get unique dates with forward filled shares nor are the shares fields correct. I get the following:
| day        | locf       |
| ---------- | ---------- |
| 2021-11-01 |            |
| 2021-11-01 |            |
| 2021-11-02 |            |
| 2021-11-02 | 1174930172 |
| 2021-11-03 |            |
| 2021-11-03 | 1174930172 |
| 2021-11-04 |            |
| 2021-11-04 | 1174930172 |
| 2021-11-05 |            |
| 2021-11-05 | 1174930172 |
| 2021-11-06 |            |
| 2021-11-06 | 1174930172 |
| 2021-11-07 | 1174930172 |
| 2021-11-07 |            |
| 2021-11-08 | 1174930172 |
| 2021-11-08 |            |
| 2021-11-09 |            |
| 2021-11-09 | 1174930172 |
| 2021-11-10 | 1174930172 |
| 2021-11-10 |            |
| 2021-11-11 |            |
| 2021-11-11 | 1174930172 |
| 2021-11-12 |            |
| 2021-11-12 | 1174930172 |
| 2021-11-13 | 1174930172 |
| 2021-11-13 |            |
| 2021-11-14 |            |
| 2021-11-14 | 1174930172 |
| 2021-11-15 |            |
| 2021-11-15 | 1174930172 |
| 2021-11-16 |            |
| 2021-11-16 | 1174930172 |
| 2021-11-17 |            |
| 2021-11-17 | 1174930172 |
| 2021-11-18 | 1174930172 |
| 2021-11-18 |            |
| 2021-11-19 |            |
| 2021-11-19 | 1174930172 |
| 2021-11-20 | 1174930172 |
| 2021-11-20 |            |
| 2021-11-21 | 1174930172 |
| 2021-11-21 |            |
| 2021-11-22 |            |
| 2021-11-22 | 1174930172 |
| 2021-11-23 |            |
| 2021-11-23 | 1174930172 |
| 2021-11-24 |            |
| 2021-11-24 | 1174930172 |
| 2021-11-25 | 1174930172 |
| 2021-11-25 |            |
| 2021-11-26 | 1174930172 |
| 2021-11-26 |            |
| 2021-11-27 |            |
| 2021-11-27 | 1174930172 |
| 2021-11-28 | 1174930172 |
| 2021-11-28 |            |
| 2021-11-29 |            |
| 2021-11-29 | 1174930172 |
| 2021-11-30 | 1174930172 |
| 2021-11-30 |            |
| 2021-12-01 | 1174930172 |
| 2021-12-01 |            |
| 2021-12-02 | 1174930172 |
| 2021-12-02 |            |
| 2021-12-03 |            |
| 2021-12-03 | 1174930172 |
| 2021-12-04 |            |
| 2021-12-04 | 1174930172 |
| 2021-12-05 | 1174930172 |
| 2021-12-05 |            |
| 2021-12-06 | 1174930172 |
| 2021-12-06 |            |
| 2021-12-07 | 1174930172 |
| 2021-12-07 |            |
| 2021-12-08 |            |
| 2021-12-08 | 1174930172 |
| 2021-12-09 |            |
| 2021-12-09 | 1174930172 |
| 2021-12-10 |            |
| 2021-12-10 | 1174930172 |
| 2021-12-11 | 1174930172 |
| 2021-12-11 |            |
| 2021-12-12 | 1174930172 |
| 2021-12-12 |            |
| 2021-12-13 | 1174930172 |
| 2021-12-13 |            |
| 2021-12-14 | 1174930172 |
| 2021-12-14 |            |
| 2021-12-15 | 1174930172 |
| 2021-12-15 |            |
| 2021-12-16 | 1174930172 |
| 2021-12-16 |            |
| 2021-12-17 | 1174930172 |
| 2021-12-17 |            |
| 2021-12-18 |            |
| 2021-12-18 | 1174930172 |
| 2021-12-19 | 1174930172 |
| 2021-12-19 |            |
| 2021-12-20 | 1174930172 |
| 2021-12-20 |            |
| 2021-12-21 | 1174930172 |
| 2021-12-21 |            |
| 2021-12-22 | 1174930172 |
| 2021-12-22 |            |
| 2021-12-23 | 1174930172 |
| 2021-12-23 |            |
| 2021-12-24 |            |
| 2021-12-24 | 1174930172 |
| 2021-12-25 | 1174930172 |
| 2021-12-25 |            |
| 2021-12-26 |            |
| 2021-12-26 | 1174930172 |
| 2021-12-27 | 1174930172 |
| 2021-12-27 |            |
| 2021-12-28 | 1174930172 |
| 2021-12-28 |            |
| 2021-12-29 |            |
| 2021-12-29 | 1174930172 |
| 2021-12-30 |            |
| 2021-12-30 | 1174930172 |
| 2021-12-31 |            |
| 2021-12-31 | 1174930172 |
| 2022-01-01 |            |
| 2022-01-01 | 1174930172 |
| 2022-01-02 |            |
| 2022-01-02 | 1174930172 |
| 2022-01-03 | 1174930172 |
| 2022-01-03 |            |
| 2022-01-04 | 1174930172 |
| 2022-01-04 |            |
| 2022-01-05 |            |
| 2022-01-05 | 1174930172 |
| 2022-01-06 |            |
| 2022-01-06 | 1174930172 |
| 2022-01-07 |            |
| 2022-01-07 | 1174930172 |
| 2022-01-08 | 1174930172 |
| 2022-01-08 |            |
| 2022-01-09 |            |
| 2022-01-09 | 1174930172 |
| 2022-01-10 | 1174930172 |
| 2022-01-10 |            |
| 2022-01-11 |            |
| 2022-01-11 | 1174930172 |
| 2022-01-12 |            |
| 2022-01-12 | 1174930172 |
| 2022-01-13 |            |
| 2022-01-13 | 1174930172 |
| 2022-01-14 | 1174930172 |
| 2022-01-14 |            |
| 2022-01-15 |            |
| 2022-01-15 | 1174930172 |
| 2022-01-16 |            |
| 2022-01-16 | 1174930172 |
| 2022-01-17 |            |
| 2022-01-17 | 1174930172 |
| 2022-01-18 |            |
| 2022-01-18 | 1174930172 |
| 2022-01-19 | 1174930172 |
| 2022-01-19 |            |
| 2022-01-20 | 1174930172 |
| 2022-01-20 |            |
| 2022-01-21 |            |
| 2022-01-21 | 1174930172 |
| 2022-01-22 |            |
| 2022-01-22 | 1174930172 |
| 2022-01-23 | 1174930172 |
| 2022-01-23 |            |
| 2022-01-24 |            |
| 2022-01-24 | 1174930172 |
| 2022-01-25 |            |
| 2022-01-25 | 1174930172 |
| 2022-01-26 |            |
| 2022-01-26 | 1174930172 |
| 2022-01-27 |            |
| 2022-01-27 | 1174930172 |
| 2022-01-28 | 1174930172 |
| 2022-01-28 | 1165004913 |
| 2022-01-29 | 1165004913 |
| 2022-01-29 | 1174930172 |
| 2022-01-30 | 1174930172 |
| 2022-01-30 | 1165004913 |

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

12.10

### What operating system did you use?

MacOS 10.13.6

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

**Comment by fabriziomello** [comment]
@dchun thanks for reaching out.

Seems your query isn't entire correct because you're grouping by the `shares.outstanding` column and `locf` is used to get last seen value in an `aggregation group`. Have a look into the documentation: https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/locf

Perhaps what you want is something like:

```sql
SELECT
  time_bucket_gapfill ('1 day', s.date) AS day,
  locf(last(s.outstanding, date))
FROM
  shares s
WHERE
  s.ticker_id = 7611 AND
  s.date BETWEEN '2021-11-01' AND '2022-01-30'
GROUP BY
  day
ORDER BY
  day;
```

**Comment by dchun** [comment]
@fabriziomello you are a genius! That solved my problem. Thanks!
