### ISSUE TITLE
[Bug]: Compression and Vacuum does not free actual disk space

### ISSUE THREAD

**Issue by FabioLugatoDerga** [timescale/timescaledb#4203]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

Hello there,

We have an Hypertable that looks like this:
![image](https://user-images.githubusercontent.com/92850452/160879560-ddabb8d1-3947-424a-b737-55e33e3421f9.png)
and created like this:
`SELECT create_hypertable('measurements', 'time')`

and compressed like this:

`ALTER TABLE measurements_numeric SET (
  timescaledb.compress,
  timescaledb.compress_orderby = 'time DESC',
  timescaledb.compress_segmentby = 'device'
)
SELECT add_compression_policy('measurements_numeric', INTERVAL '2 weeks')`

Running:
`select * from hypertable_compression_stats('measurements')`

I get something like:
![image](https://user-images.githubusercontent.com/92850452/160880643-4f6d2bb8-ee94-4bf4-b76c-5d19419bb064.png)
![image](https://user-images.githubusercontent.com/92850452/160880868-051d1859-9bec-4001-a8fd-4bdbdbc00cb8.png)

So it does look good on paper but here is the problem:
**The actual space on disk does not decrease by any amount**
We can't really understand why the table is compressed but there are no actual disk space savings.

Btw, only that one table takes up a lot of space, all the others in the DB don't, but that's totally normal.

We tried to manually VACUUM and VACUUM FULL and did not reclaim any additional disk space.
We even tried to reboot the virtual machine (any cache out there?) but still no improvements.

Thanks in advance to everyone,
regards

### TimescaleDB version affected

2.3.0

### PostgreSQL version used

13

### What operating system did you use?

Ubuntu 20.04 LTS

### What installation method did you use?

Docker

### What platform did you run on?

On-prem/Self-hosted

**Comment by maxhertrampf** [comment]
Not the question but it seems like that in your data a series is not actually determined by only "device" but also by "variable".

To get better compression ratio, you should add "variable" to your "segment_by" columns.

See https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression/ -> search for "entity-attribute-value".

And since you closed the issue, can you say what helped? ☺️

**Comment by FabioLugatoDerga** [comment]
Thanks for the advices,.

- we will segment also by variable and not only by device 
- turns out that all the data in there were uncompressed chunks and that we were writing a huge amount of data per second, way more than we expected. Once we surpassed the 2 weeks mark it started compressing data and now everything is fine.
