### ISSUE TITLE
feature request: LOCF 

### ISSUE THREAD

**Issue by Sigi-Bereuter** [timescale/timescaledb#421]
We ware fetching data from Db to R-Studio for doing machine learning.
A linear regression affords that you have a value for every column (feature) in every row, but often you do not have a value for every column (feature) at every timestamp.
In R we do a "Last Observation Carry Forward" to bring the data in this shape before we run the Analysis.
Since this is time consuming it would be nice to already do this when querying from the DB.

**Comment by mfreed** [comment]
Hi @Sigi-Bereuter:

LOCF, as part of gap filling, was just merged into the repository and will be part of the next 1.2 release:

https://github.com/timescale/timescaledb/pull/938/commits/97c0381975336d2055fae823cbaed98502f79102
