### ISSUE TITLE
[Bug]: Recreating material view significantly improves query performance

### ISSUE THREAD

**Issue by parliament718** [timescale/timescaledb#4216]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I have found that dropping and recreating a continuous aggregate signficantly improves query performance. This is unexpected behavior.

Here is how reproduce it every time:

1. I create my tables as such (I'm collecting financial tick data)

```
CREATE TABLE trades (
   "time" TIMESTAMPTZ,
   market_key TEXT,
   side TEXT,
   price DOUBLE PRECISION,
   amount DOUBLE PRECISION,   
   cost DOUBLE PRECISION   
);

SELECT create_hypertable('trades', 'time');

CREATE MATERIALIZED VIEW one_min_candles
WITH (timescaledb.continuous) AS
   SELECT
      time_bucket('1 min', time) AS bucket,
      market_key,
      FIRST(price, time) AS "open",
      MAX(price) AS high,
      MIN(price) AS low,
      LAST(price, time) AS "close",
      SUM(amount) AS volume      
   FROM trades
   GROUP BY bucket, market_key;

SELECT add_continuous_aggregate_policy('one_min_candles',
    start_offset => INTERVAL '2 min',
    end_offset => INTERVAL '0 sec',
    schedule_interval => INTERVAL '5 sec');

```

2. Next I run a data-collection service that runs until I have about 1M trades, resulting in 200K one minute candles
3. I run the query:

```
select count(*) from one_min_candles;
```
Results take about 3.5s on 200k rows. Attached is the **before-recreate** query plan.

4. Next I drop the continous aggregate 

```
SELECT remove_continuous_aggregate_policy('one_min_candles');
DROP MATERIALIZED VIEW one_min_candles;

--Then recreate the continous aggregate and policy using same queries in Step 1
```

5. Now I re-run the query 

```
select count(*) from one_min_candles;
```
Results now take about 700ms. Attached is the **after-recreate** query plan.

The queries return the same data, but it's significantly faster after dropping and recreating the continous aggregate. The query plan in the later case is also much shorter. 

Side note: I'm also experiencing fluctuations in the time it takes to execute this query as the data is being populated.
I query every 3 seconds as it's populating and it starts off fast and as the data grows the query understandably starts taking longer and longer, until about 3-4s and then suddenly there's a drop back to 400ms, and then continue to grow again to about 3s and then suddenly a drop again.  I'm not really sure what that's happening. 

Before Recreating:
![before-recreate](https://user-images.githubusercontent.com/3580270/161766289-5d71783a-b416-4e70-b10a-5436901b28ee.png)

After Recreating:
![after-recreate](https://user-images.githubusercontent.com/3580270/161766322-97552a14-6cce-4aeb-8e84-845d99f514f8.png)

### TimescaleDB version affected

2.60

### PostgreSQL version used

14.2

### What operating system did you use?

MacOS Big Sur (11.6)

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

**Comment by akuzm** [comment]
I think the reason is that in the first case, the continuous aggregate doesn't contain the historical data. Your policy only refreshes it from 2 minutes back from current time. When you recreate it, it is refreshed for all historical data (`start_offset => NULL`). I think it can be refreshed manually after loading the historical data, by calling [refresh_continuous_aggregate](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/refresh-policies/#manually-refresh-a-continuous-aggregate).

You can tell wherether the result comes from the cagg vs the main table by looking at `rows` for `*SELECT 1*` vs `*SELECT 2*` in the `EXPLAIN ANALYZE` output.

**Comment by konskov** [comment]
It seems there is no further discussion going on for this issue, so I’m closing it. @parliament718, please feel free to reopen if you think it requires further discussion. Thanks!
