### ISSUE TITLE
[Bug]: Compression policy job delaying to start

### ISSUE THREAD

**Issue by henriquegelio** [timescale/timescaledb#4217]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Background worker, Compression, Configuration, Policy

### What happened?

Hello all,

In the company I work for, we are currently using TimescaleDB version 2.5 with a Docker environment for testing purposes (latest-pg12 tag).

We have a test environment that runs a `JDBCDatabaseContainer` from `testcontainers` and we perform some integration tests on it.

Some of our tests add a compression policy using the process described [here](https://docs.timescale.com/api/latest/compression/add_compression_policy/#add-compression-policy).

As we have a hypertable with a `bigint` timestamp, our test also set the `integer_now_func`, as described in the docs.

Briefly, our test sets the compression policy on a given hypertable, and try to verify the `timescaledb_information.job_stats` view, in order to check the status of the job. Basically, if the job status is Success, then the test checks for compressed chunks and finishes.

The strange behavior comes because in this test scenario, as soon as we call `add_compression_policy`, the job can be found at 
`timescaledb_information.jobs` but has a null value on `next_start`. Also, it does not show up on `timescaledb_information.job_stats`. Exactly after 1 minute, the `next_start` value gets set correctly and the job runs, making it possible to find it on `timescaledb_information.job_stats`.

We are trying to understand where this "1 minute delay" comes from. We have already tried to increase the number of background workers / parallel jobs, with no success.

We have also tried to use `alter_job()` to set a specific `next_start` value, but nothing happens. The job runs only after 1 minute of having set the `add_compression_policy()`. Same way, we have tried to call `run_job`, passing the job_id found on `timescaledb_information.jobs`. The jobs actually gets executed, but nothing changes on those views.

The big question is: Is this behavior expected? If so, is there a way we can change this "delay" (by setting an environment variable, for example)?

One interesting fact: If we call the `add_compression_policy` on an environment with docker/timescale that already has a database created, in our local machine, the job gets run instantly and those views get updated. This "1 minute delay" happens only on a container built with testcontainers for testing purposes.

Important to say that before each test is run, we create a new database / hypertable and enable the compression. This led us to guess there might be some "minimal" time after the database creation which the background jobs must wait before running, but we are not sure. As said above, this delay does not happen on a docker environment where the database / hypertables are already created.

We tried to find more information about how the background workers / scheduler work in the timescale docs, but no luck atm.

Any help on this matter would be much appreciated. If there is any information / log we can send to help understanding this issue, please let me know.

Example of [JDBCDatabaseContainer](https://javadoc.io/doc/org.testcontainers/postgresql/1.11.1/org/testcontainers/containers/PostgreSQLContainer.html) (currently we implemented our own TimescaleDBContainer based on this)

[JDBC Testcontainers](https://www.testcontainers.org/modules/databases/jdbc/)

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

12

### What operating system did you use?

Ubuntu 21.10

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by konskov** [comment]
Hi @henriquegelio , thanks for reaching out. 

It looks like the cause of the delay you are experiencing could be [this line](https://github.com/timescale/timescaledb/blob/ff945a7a9449ee3b2b6c1b7cb78f8fa87dbdaa4e/src/loader/bgw_launcher.c#L89).
So maybe using a debug build for testing could help you get rid of the 1 minute delay.

**Comment by henriquegelio** [comment]
> Hi @henriquegelio , thanks for reaching out.
> 
> It looks like the cause of the delay you are experiencing could be [this line](https://github.com/timescale/timescaledb/blob/ff945a7a9449ee3b2b6c1b7cb78f8fa87dbdaa4e/src/loader/bgw_launcher.c#L89). So maybe using a debug build for testing could help you get rid of the 1 minute delay.

Hi @konskov , thanks for the quick response.

If we understood this correctly, this delay is caused because the background worker launcher waits for 1 minute to start running jobs, after the database is created, right?

If we're on the same page here, the only way to get rid of this delay seems to be re-compiling timescaledb and using a custom image, cause we would be able to build it as a debug build, is that correct?

As we are using a docker hub image tag, we wouldn't like to have a custom image for testing purposes, as we were expecting this issue to be configurable through an environment variable or something like this, but it doesn't seem possible as far as we can tell.

If this is the only way to do so, would you kindly point us to a recommended procedure of doing this?

TBH, we are considering "force running" the job by getting the job_id from the information view and calling `run_job()`, further ensuring that the chunks are compressed, which are really the purpose of some of our tests. Kind of "ignoring" the background scheduler.

**Interesting fact:**
We kind of reproduced this behavior on the local environment (which also uses docker), by creating a database from scratch.
Then we created a hypertable, enabled the compression and called `add_compression_policy()` on it.
The job became "idle" (with a null `next_start` value) for exactly 45 seconds, and not 1 minute as expected after the database has been created, so we're not sure if the delay is directly caused by that line.

This is another clue that is convincing us to use `run_jobs` as mentioned above, but we're trying to exhaust possibilities first.

Thanks in advance for you kind help.

**Comment by konskov** [comment]
Hi @henriquegelio As I have not been able to reproduce the issue that you are facing, I don’t know if I can suggest other options that would work for you. Would it be possible to provide more specific reproduction steps? Thanks!

**Comment by henriquegelio** [comment]
Hey @konskov , sorry for the delay.

We will try to provide you a bash script to execute the same test steps in order to show the issue we are facing, as I am not allowed to share pieces of code.

I kindly ask you to give me one or two days so I can reach you guys back here with the reproduction steps.

The workaround for the moment was to use run_job as specified, but we understand this is not ideal and will try to give you more details about the issue in the next hours.

We're also open to any other suggestion other than using the views as we are doing above.

**Comment by henriquegelio** [comment]
Hi @konskov ,

Once again, I apologize for the delay.

Bellow is a bash script with the reproduction steps to face the issue we have described above.

In a few words, it'll create a docker container with timescale and perform the same steps we're doing in our compression tests.
In this example we've provided just the initial steps until we face the described issue, that is, just so we can show you the delay to have the compression job updated in the views. In our original tests we also check for chunk compression status, and some other details.

As it builds up a docker container, it's important to have docker installed. There is a -h option with more information.
In case of any questions, please let me know so I can help :)

Thanks again for taking the time to help us!

[example_script.zip](https://github.com/timescale/timescaledb/files/8608381/example_script.zip)

**Comment by konskov** [comment]
Hi @henriquegelio thanks a lot for your help in investigating this issue! Indeed the delay is caused by [that line](https://github.com/timescale/timescaledb/blob/ff945a7a9449ee3b2b6c1b7cb78f8fa87dbdaa4e/src/loader/bgw_launcher.c#L89)... We are considering adding a GUC to make that configurable as you have suggested. Until then, I think that the options in the meantime are to either use a debug build that will eliminate this delay, or use `run_job`.

**Comment by konskov** [comment]
I accidentally closed the issue, sorry!

**Comment by henriquegelio** [comment]
> Hi @henriquegelio thanks a lot for your help in investigating this issue! Indeed the delay is caused by [that line](https://github.com/timescale/timescaledb/blob/ff945a7a9449ee3b2b6c1b7cb78f8fa87dbdaa4e/src/loader/bgw_launcher.c#L89)... We are considering adding a GUC to make that configurable as you have suggested. Until then, I think that the options in the meantime are to either use a debug build that will eliminate this delay, or use `run_job`.

Hey @konskov, very glad we could help by any means.

Thanks a lot in advance for the feature / fix provided, we can see it was already merged. Looking forward to the next release.

In the meantime, we're using `run_jobs`as stated above.

no worries about the issue closure.

Thank you :)
