### ISSUE TITLE
[Bug]: Compression job fails but cannot tell the cause

### ISSUE THREAD

**Issue by buchupally** [timescale/timescaledb#4238]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

A compression job on one of the tables failed a couple of times recently. "SELECT * FROM timescaledb_information.job_stats;" shows the failure but looking at the documentation there seems to be no way to tell what the actual error is that caused the failure. Postgresql shows this at the end...

2022-04-14 21:28:47.215 UTC [21563] LOG:  job 1009 threw an error

There seems to be a lot of WAL activity during the compression, we see a lot of WAL files being written (again from postgresql logs)...

INFO: 2022/04/14 21:24:54.364404 FILE PATH: 0000000200000505000000DB.lz4
INFO: 2022/04/14 21:24:54.411795 FILE PATH: 0000000200000505000000DA.lz4
2022-04-14 21:24:54.592 UTC [940] LOG:  checkpoints are occurring too frequently (7 seconds apart)
2022-04-14 21:24:54.592 UTC [940] HINT:  Consider increasing the configuration parameter "max_wal_size".

this is not normal to the system it only seems to happen during the failed compression job run.

The last time this happened we did notice that one of the chunks which was already compressed was 2 orders of magnitude bigger than the rest while there was no significant increase in data volume to justify that size. So we decompressed the chunk, ran a "vacuum full" on the entire table which reduced the size of the chunk to a more normal size. We then recompressed that chunk and the compression job worked again.

Are there any logs we can enable to get more information to track compression job failures?

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

11.8

### What operating system did you use?

Ubuntu 18.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

**Comment by horzsolt** [comment]
Hi @buchupally thanks for reporting this issue. On job execution failure timescaledb logs a one-liner error message (the one you pasted above) and rethrows the job execution failure to Postgres, so the actual failure is logged by Postgres. This is the current behavior, which unfortunately doesn't provide the necessary details and I think this is something that we should improve in the future.

**Comment by NunoFilipeSantos** [comment]
Hi @buchupally ! 👋 We're closing this issue for now, feel free to reopen it if you can provide more information. Thank you! 😃
