### ISSUE TITLE
[Bug]: Cannot re-add data node after deleting it

### ISSUE THREAD

**Issue by sentinel09** [timescale/timescaledb#4276]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Access node, Data node

### What happened?

Trying to create multi-node cluster (access node + 2 data nodes) using official TimescaleDB docker image `timescale/timescaledb:2.5.0-pg12` (tried also `timescale/timescaledb:2.6.1-pg12`).
Adding node with next query works fine:
`SELECT add_data_node('dn1', host => 'dw-dev-timescaledb-dn-1', bootstrap => 'false');`
However, after successfully deleting this node with:
`SELECT delete_data_node('dn1', if_exists => 'true', force => 'true');`
And trying to re-add it:
`SELECT add_data_node('dn1', host => 'dw-dev-timescaledb-dn-1', bootstrap => 'false');`
I am getting next error running query on data node:
```
SQL Error [TS174]: ERROR: cannot add "dn1" as a data node
  Detail: ERROR:  node is already a data node
```

And getting this output on dn1:
```
2022-04-26 22:57:11.001 UTC [744] ERROR:  node is already a data node
2022-04-26 22:57:11.001 UTC [744] STATEMENT:  SELECT _timescaledb_internal.validate_as_data_node()
```

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

12.0

### What operating system did you use?

Alpine Linux v3.15

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
SELECT add_data_node('dn1', host => 'dw-dev-timescaledb-dn-1', bootstrap => 'false');
SELECT delete_data_node('dn1', if_exists => 'true', force => 'true');
SELECT add_data_node('dn1', host => 'dw-dev-timescaledb-dn-1', bootstrap => 'false');
```

**Comment by konskov** [comment]
Hi @sentinel09, thank you for reaching out. Could you provide more details about your setup and what you did to help us reproduce the issue?

**Comment by sentinel09** [comment]
Hi @konskov,
This issue might be closed. I just figure out, that it's important to read NOTE and IMPORTANT parts of documentation.
Thank you!
