### ISSUE TITLE
[Flaky test] dist_hypertable-14

### ISSUE THREAD

**Issue by konskov** [timescale/timescaledb#4278]
### Which test is flaky?

dist_hypertable-14

### Since when has the test been flaky?

April 26, perhaps earlier

### Link to the failed test run

https://github.com/timescale/timescaledb/runs/6164564916?check_suite_focus=true, https://github.com/timescale/timescaledb/runs/6182646271?check_suite_focus=true

### Log output

```bash
Varies
```

**Comment by mkindahl** [comment]
Fails here as well https://github.com/timescale/timescaledb/runs/6827486034?check_suite_focus=true

**Comment by mkindahl** [comment]
Fails here as well: https://github.com/timescale/timescaledb/runs/7129308963?check_suite_focus=true

**Comment by mkindahl** [comment]
Fails [here](https://github.com/timescale/timescaledb/runs/8185103046?check_suite_focus=true) as well, but the error is "relation "disttable" does not exist" on line 27 (`VACUUM disttable`).

**Comment by jnidzwetzki** [comment]
A related one:

```
+WARNING:  [db_dist_hypertable_3]: canceling statement due to user request
```

https://github.com/timescale/timescaledb/actions/runs/5261542022/jobs/9509768970
