### ISSUE TITLE
[Bug]: time_bucket_gapfill throws 'invalid time_bucket_gapfill argument' error when called through a rest endpoint

### ISSUE THREAD

**Issue by YBenarab** [timescale/timescaledb#4279]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Gapfill

### What happened?

I have a Spring Boot application with a REST endpoint that runs a query against my database. The database I use is PostgreSQL with TimescaleDB. The query I have uses time_bucket_gapfill function in order to get buckets of data back so that I can build my timeline chart.

My data is stored in UTC and I want to always fetch the data in the local timezone of the client. To achieve that, I am using AT TIME ZONE 'UTC' AT TIME ZONE 'clients timezone'. This is how the query looks:

````
SELECT e.timestamp AS timestamp_start, e.timestamp + (:numOfHours * INTERVAL '1 hour') AS timestamp_end, TO_CHAR(e.timestamp, :category) AS category, elevation_count, user_count                              
FROM (
SELECT time_bucket_gapfill(CAST(:numOfHours * INTERVAL '1 hour' AS INTERVAL), time AT TIME ZONE 'UTC' AT TIME ZONE :timezone, :start AT TIME ZONE :timezone, :end AT TIME ZONE :timezone) AS timestamp,
                            log_type,
                            COALESCE(SUM(CASE WHEN log_type = 'Elevation' THEN 1 ELSE 0 END), 0) elevation_count,
                            COALESCE(COUNT(DISTINCT device_id), 0) user_count
FROM log_aod
JOIN device USING (device_id)
WHERE time >= :start
AND time < :end
                            AND type = 'Elevation'
               GROUP BY timestamp, log_type) e                 
ORDER BY e.timestamp, log_type ASC
````

This is the full query, the problem I’m experiencing is related to the sub-select:

`SELECT time_bucket_gapfill(CAST(:numOfHours * INTERVAL '1 hour' AS INTERVAL), time AT TIME ZONE 'UTC' AT TIME ZONE :timezone, :start AT TIME ZONE :timezone, :end AT TIME ZONE :timezone) AS timestamp`

When I use AT TIME ZONE here in the sub-select, it works and it gives me the correct result, however it can’t handle multiple REST calls right after each other. When I call the endpoint that uses this query 3-4 times in a row I get the following error:

ERROR: missing time_bucket_gapfill argument: could not infer start from WHERE clause

If I remove the AT TIME ZONE part or move it up to the outer select, I don’t get this problem no matter how many times and how often I hit the endpoint, however I need it in the sub-select to get the correct result.

I tried to move it to the WHERE clause but it still gave the same error and the data came out wrong so that’s not an option.
Just to be clear, the error only appears when the query is triggered through a REST endpoint, not if I run it directly on the database.

UPDATE: It has something to do with "**_:timezone_**". For some reason this only happens when the timezone is passed down as a parameter, if i hardcode it, it works fine. But obviously I'm gonna need to pass it down because the timezone depends on the client.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14.2

### What operating system did you use?

x86_64-pc-linux-gnu

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
2022-04-28 06:51:29 UTC | ERROR | [dispatcherServlet] | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [SELECT e.timestamp AT TIME ZONE ? AT TIME ZONE 'UTC' AS timestamp_start, e.timestamp AT TIME ZONE ? AT TIME ZONE 'UTC' + (? * INTERVAL '1 hour') AS timestamp_end,
       TO_CHAR(e.timestamp, ?) AS category, elevation_count, user_count
FROM (SELECT time_bucket_gapfill(CAST(? * INTERVAL '1 hour' AS INTERVAL), time AT TIME ZONE 'UTC' AT TIME ZONE ?,
             ? AT TIME ZONE ?, ? AT TIME ZONE ?) AS timestamp,
    log_type,
    COALESCE(SUM(CASE WHEN log_type = 'Elevation' THEN 1 ELSE 0 END), 0) elevation_count,
    COALESCE(COUNT(DISTINCT device_id), 0) user_count
FROM log_aod
JOIN device USING (device_id)
WHERE time >= ?
    AND time < ?
    AND log_type = 'Elevation'
    GROUP BY timestamp, log_type) e
ORDER BY e.timestamp, log_type ASC
]; ERROR: invalid time_bucket_gapfill argument: start must be a simple expression; nested exception is org.postgresql.util.PSQLException: ERROR: invalid time_bucket_gapfill argument: start must be a simple expression] with root cause
org.postgresql.util.PSQLException: ERROR: invalid time_bucket_gapfill argument: start must be a simple expression
```

### How can we reproduce the bug?

```bash
The issue can be reproduced by creating a database with the two tables (table definition will be posted below), then create a simple spring boot application uses the query posted in the explanation and call the endpoint a few times quickly in a row, then you'll get the error.

This is my table definitions.

CREATE TABLE log_aod
(
                               log_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
                                "time" timestamp without time zone NOT NULL,
                                username character varying(255),
                                device_id integer NOT NULL,
                                source character varying(255),
                                log_type character varying(255),
                                CONSTRAINT log_aod_pkey PRIMARY KEY (log_id, "time")
)

CREATE TABLE device
(
                                device_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
                                mongo_id character(24) NOT NULL,
                                org_id integer NOT NULL,
                                computer_name character varying(255) NOT NULL,
                                CONSTRAINT device_pkey PRIMARY KEY (device_id),
                                CONSTRAINT device_mongo_id_key UNIQUE (mongo_id)
)
```

**Comment by svenklemm** [comment]
Could you provide reproduction steps that do not require creating spring boot application and are ideally just a self-contained sql script.
