### ISSUE TITLE
[Enhancement]: Allow non-superusers to create distributed restore points

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4282]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Multi-node

### What does the enhancement do?

Regular PG restore points can be created by non-superusers if granted `EXECUTE` on `pg_create_restore_point`. It should work the same way when creating distributed restore points. 

Currently, `create_distributed_restore_point` seems to be limited to superusers since there is no check for EXECUTE permissions.

### Implementation challenges

If possible, Having `EXECUTE` on `create_distributed_restore_point` should allow creating distributed restore points even if the user does not have `EXECUTE` on `pg_create_restore_point`. Still, this could be a privilege leak since `pg_create_restore_point`  is called underneath the hood.

**Comment by svenklemm** [comment]
multinode has been removed
