### ISSUE TITLE
CASCADE not cascading to hypertable catalog

### ISSUE THREAD

**Issue by MarkRichardsEsquire** [timescale/timescaledb#429]
if i have created a hypertable on a table in schema sname and i run "drop schema <sname> cascade" there is still a row in _timescaledb_catalog.hypertable that thinks the hyper chunk(s) still exists.

i dont know how else the _timescaledb_* schemas will or won't be effected by this. my fix so far is if i drop rec(s) in question from _timescaledb_catalog.hypertable then everything is fine.

something like this:

adb=# create schema x;
adb=# create table x.foo ( time timestamp, bar integer );
adb=# select create_hypertable('x.foo', 'time', chunk_time_interval => interval '1 week');
adb=# drop schema x cascade;
NOTICE:  drop cascades to table x.foo
adb=# select * from _timescaledb_catalog.hypertable where schema_name = 'x';
 id  | schema_name | table_name | associated_schema_name | associated_table_prefix | num_dimensions
-----+-------------+------------+------------------------+-------------------------+----------------
 180 | x           | foo        | _timescaledb_internal  | _hyper_180              |              1
adb=# create schema x;
adb=# create table x.foo( time timestamp, bar integer );
adb=# select create_hypertable('x.foo', 'time', chunk_time_interval => interval '1 week');
ERROR:  hypertable x.foo already exists
CONTEXT:  PL/pgSQL function public.create_hypertable(regclass,name,name,integer,name,name,anyelement,boolean,boolean,regproc) line 46 at RAISE

**Comment by erimatnor** [comment]
I believe this should be fixed by https://github.com/timescale/timescaledb/pull/411 and https://github.com/timescale/timescaledb/pull/418.

Both these fixes should be in version 0.9, which will be released very soon.

**Comment by mfreed** [comment]
@MarkRichardsEsquire 0.9.0 was released yesterday, which should fix this.  Please let me know if you continue to see this issue, or please otherwise close the issue?  Thanks!

https://github.com/timescale/timescaledb/releases/tag/0.9.0
