### ISSUE TITLE
[Bug]: superuser required for pg_dump

### ISSUE THREAD

**Issue by jgpruitt** [timescale/timescaledb#4292]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Backup

### What happened?

I have added a test to promscale to ensure that the backup/restore process works. We want to be able to backup and restore without requiring superuser access. When I run pg_dump using a non-superuser, it fails when attempting to dump the compressed hypertable with the following error:

ERROR:  permission denied for table _compressed_hypertable_10
LOCK TABLE _timescaledb_internal._compressed_hypertable_10 IN ACCESS SHARE MODE

While a number of roles have read access to the hypertable, non of these privileges "cascade" to the backing compressed table.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4974668/166245118-5dc4f85f-9a0c-4695-a1b7-1bd084c8761c.png">

Is this by design? How can a non-superuser dump the database?

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.2

### What operating system did you use?

macOS x86

### What installation method did you use?

Docker

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
1. create a hypertable
2. configure it for compression
3. grant select on the hypertable to a non-superuser
4. attempt to pg_dump the database as that non-superuser
```

**Comment by svenklemm** [comment]
@jgpruitt If you grant the permissions after enabling compressions the pg_dump should work.

**Comment by nikkhils** [comment]
Ideally, the GRANT on the main hypertable should also percolate to the compressed chunks.

**Comment by sb230132** [comment]
Followed same steps as mentioned;
1. create a hypertable
2. configure it for compression
3. grant select on the hypertable to a non-superuser
4. attempt to pg_dump the database as that non-superuser

Could not reproduce the issue with pg_dump. Please check that required permissions are there for hypertable as well as compressed hypertable.


```
tsdb=# 
tsdb=# create user nonsuper;
CREATE ROLE
tsdb=# 
tsdb=# create table foo (a integer, b integer, c integer);
CREATE TABLE
tsdb=# 
tsdb=# select table_name from create_hypertable('foo', 'a', chunk_time_interval=> 10);
NOTICE:  adding not-null constraint to column "a"
DETAIL:  Time dimensions cannot have NULL values.
 table_name 
------------
 foo
(1 row)

tsdb=# alter table foo set (timescaledb.compress);
ALTER TABLE
tsdb=# grant select on foo to nonsuper;
GRANT
tsdb=#  select schema_name, table_name from _timescaledb_catalog.hypertable;
      schema_name      |        table_name         
-----------------------+---------------------------
 _timescaledb_internal | _compressed_hypertable_11
 public                | foo
(2 rows)


tsdb=# select relacl from pg_class where relname like 'foo';
                              relacl                               
-------------------------------------------------------------------
 {bharathysatish=arwdDxt/bharathysatish,nonsuper=r/bharathysatish}
(1 row)

tsdb=# select relacl from pg_class where relname like '_compressed_hypertable_11';
                              relacl                               
-------------------------------------------------------------------
 {bharathysatish=arwdDxt/bharathysatish,nonsuper=r/bharathysatish}
(1 row)

```

```
bin/pg_dump -d tsdb -U nonsuper > /dev/null
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   chunk
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
```

Let me know what am i missing.
