### ISSUE TITLE
[Bug]: Disk space not getting released

### ISSUE THREAD

**Issue by rahulverma2391** [timescale/timescaledb#4302]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Platform/OS

### What happened?

Hi Team... i am using postgres 13.4 on which i have installed Timescale extension 2.3.1 for timeseries database.
On deleting rows in my database, space is not getting released on disk.
Autovacuumming is on, still on deleting the rows disk space utilization goes up than going down.
              name              | setting
--------------------------------+---------
 autovacuum_vacuum_scale_factor | 0.2
 autovacuum_vacuum_threshold    | 50

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

13.4

### What operating system did you use?

centos 7

### What installation method did you use?

Source

### What platform did you run on?

Amazon Web Services (AWS)

**Comment by NunoFilipeSantos** [comment]
Hi @rahulverma2391 ! 👋 Can you try with our latest version (2.6.1) and get back to us? Thank you. 🙂

**Comment by mkindahl** [comment]
@rahulverma2391 Thank you for the bug report. Autovacuum executes a vacuum in a background worker, so have you checked if an explicit call of `VACUUM FULL` actually reduces the disk usage? If it does, then next step is to check if autovacuum actually ran to exclude that possible failure.

**Comment by nikkhils** [comment]
@rahulverma2391 any further updates here?

**Comment by fabriziomello** [comment]
Hey @rahulverma2391, did u had a chance to check our last comments?

**Comment by NunoFilipeSantos** [comment]
Hi @rahulverma2391 ! 👋 We're closing this issue for now, feel free to reopen it if you can provide more information. Thank you! 😃
