### ISSUE TITLE
[Enhancement]: Allow Push-Down of Filters Containing a Sub-Select to Data Nodes

### ISSUE THREAD

**Issue by TroyDey** [timescale/timescaledb#4305]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Distributed hypertable

### What does the enhancement do?

A common use case is to store a small set of metadata in a separate table which can be quickly filtered to produce a set of ID's with which to query a larger data table using an index.

```sql
SELECT 
  time_bucket(60, timestamp), 
  avg(value) 
FROM metric 
WHERE 
  tag_id IN (SELECT id FROM tag WHERE name = 'hostname' AND value IN ('foo', 'bar', 'baz')) 
  AND timestamp BETWEEN 1651017600 AND 1651103999 
GROUP BY 1
ORDER BY 1 ASC;
```

In the normal case the small tag table is quickly scanned, perhaps using an index, producing a set of ID's which can then be used to perform a nested loops join on an index, assuming tag_id is indexed, on the metric table.

When the table is a distributed hypertable however this formulation results in poor performance.  This is because Timescale currently is unable perform distributed joins.  Specifically in the above case each data node could end up shipping a large number of records to the access node where most of those records will then be removed by the filter on tag_id.

The enhancement request would be to allow for a distributed join in the specific case of a filter containing a sub-select on a table stored on the access node.  This sub-select would result in a small table that could then be pushed down to the data nodes which could then perform the join (hopefully using an index) and ship a much smaller set of records to the access node.

See the discussion on the forum [here](https://www.timescale.com/forum/t/distributed-hypertable-poor-performance-for-simple-bucketed-aggregation/498) for more details.

**Comment by svenklemm** [comment]
As a workaround you can do the following:
To get timescaledb to pushdown the result of a subselect you create an immutable function like so:

```
CREATE OR REPLACE FUNTION push() RETURNS int[]  LANGUAGE SQL IMMUTABLE
AS $$
  SELECT array_agg(distinct device_id) FROM metrics;
$$;
```

And then use it in a query like this:
```
SELECT * FROM metrics_dist WHERE device_id=ANY(push());
```

This will materialize the function result on the access node and push it down to the data nodes.

**Comment by jfjoly** [comment]
@TroyDey were you able to test the workaround, does it improve your query performances?

**Comment by TroyDey** [comment]
Thanks for suggestion, I was able to rearrange the query to use ANY with a sub-select, no need for the function.

```sql
SELECT 
  time_bucket(60, timestamp), 
  avg(value) 
FROM metric 
WHERE 
  tag_id = ANY((SELECT array_agg(id) FROM tag WHERE name = 'hostname' AND value IN ('foo', 'bar', 'baz'))::int[]) 
  AND timestamp BETWEEN 1651017600 AND 1651103999 
GROUP BY 1
ORDER BY 1 ASC;
```

Checking the explain plan for the remote SQL it does indeed use the index with this operator on the data nodes, and overall improves query performance by 1.5-2x.  Being able to use a regular sub-select would still be nice from a readability perspective, but otherwise this works for me.

**Comment by rijnhard** [comment]
Just going to say this is a VERY useful feature.
most of the time when you need to join into a giant hypertable it is one of two use cases:
1. assist in filtering
2. add additional info to the output. 

This provides an alternative to the first use case, so that you don't have to join the data, but can rather do a subselect and pass the results down to do the filtering on the data nodes. 

For the second use case, that should be a separate issue (if even needed), but for completeness, you can flip it around and do a subselect that only queries the hypertable (which should run on the data nodes) and then join on that result (which needs to fed up to the access node anyway)

**Comment by akuzm** [comment]
I think we can consider this implemented in some sense after adding parameterized data node scans https://github.com/timescale/timescaledb/pull/4820 It doesn't implement the original proposal of sending the results of subquery to the data nodes, but still can improve the performance several times over. We're tracking some subsequent improvements in a private repo: https://github.com/timescale/eng-database/issues/335

There are also plans to support joins with a reference table that is replicated to all data nodes: https://github.com/timescale/eng-database/issues/323 (sorry, it's in private repo again, maybe we need to move them here...)
