### ISSUE TITLE
[Enhancement]: Allow Continous Aggregates to be Distributed

### ISSUE THREAD

**Issue by TroyDey** [timescale/timescaledb#4308]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Continuous aggregate

### What does the enhancement do?

Continuous Aggregates are a very useful feature, but when dealing with extremely large distributed hypertables a continuous aggregate may be too slow to be useful as it will need to reside entirely on the access node and the work of querying it cannot be split up among the data nodes.  It would be useful in these cases to have the option to distribute the continuous aggregate amongst the data nodes as you would a normal distributed hypertable. 

### Implementation challenges

- Managing the metadata around the continuous aggregate and where its chunks are will likely be challenging.
- In addition keeping the continuous aggregate up to date will also likely become more difficult once it is distributed.
- My guess would be that forcing the continuous aggregate to be distributed on the same key as the distributed hypertable it is based on would be helpful.
- Partial aggregates or stats_agg will likely be needed here as well.

**Comment by svenklemm** [comment]
multinode has been removed
