### ISSUE TITLE
[Enhancement]: Optimize index creation for compressed hypertables

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#4314]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Compression

### What does the enhancement do?

Instead of creating an index for every segmentby column we should create a composite index all the segmentby columns. This would improve space efficiency and query performance.

**Comment by kgyrtkirk** [comment]
this change have altered the auto-created indexes on compressed tables; for existing tables it didn't seem to have provided an upgrade path

users could manually add the missing index:
* look for the compressed ht name
```
select h0.schema_name||'.'||h0.table_name,h1.schema_name||'.'||h1.table_name from _timescaledb_catalog.hypertable h0 join _timescaledb_catalog.hypertable h1 on (h0.compressed_hypertable_id = h1.id);
```
* add the composite index directly to the compressed HT
