### ISSUE TITLE
Cannot insert into table (hypertable) with multiple primary keys

### ISSUE THREAD

**Issue by portnoy31191** [timescale/timescaledb#432]
I started using timescaledb on either version 0.6.0 or 0.6.1 (not sure which). I have a few tables which each have primary keys of two columns: time and something else. Everything was working fine for a while and multiple hypertable rollovers completed successfully. Then, I upgraded to 0.8.0. It seemed to work fine as well until the next rollover was triggered. When it became time for the next rollover, the following error occurred upon INSERT.

>ERROR:  multiple primary keys for table <hyper_chunk> are not allowed
>CONTEXT:  SQL statement " ALTER TABLE _timescaledb_internal.<hyper_chunk> ADD CONSTRAINT "<pkey>" PRIMARY KEY (something_else, "time") "
PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 27 at EXECUTE
>SQL statement "SELECT _timescaledb_internal.chunk_constraint_add_table_constraint(chunk_constraint_row)"
>PL/pgSQL function _timescaledb_internal.create_chunk_constraint(integer,oid) line 15 at PERFORM`

This is on an ubuntu 16.04 server.

**Comment by mfreed** [comment]
There have been some meaningful changes to our internal representations over the last three versions.

Do you see the same issue if you define them as UNIQUE columns, as opposed to explicitly as PRIMARY KEYS?  i.e., do you need anything more than just UNIQUE enforcement and indexes?

**Comment by RobAtticus** [comment]
Hey @portnoy31191, I'm going to close this issue for now. If you are still seeing it on the latest version (0.9.2), please re-open or re-file. Happy to help if we can
