### ISSUE TITLE
[Bug]: Still asks for previous version after upgrading from 2.6.0 to 2.6.1

### ISSUE THREAD

**Issue by dmilith** [timescale/timescaledb#4334]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

ERROR:  could not access file "$libdir/timescaledb-2.6.0": No such file or directory

after I did successful alter / upgrade to 2.6.1

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

13.7

### What operating system did you use?

FreeBSD 13.0 arm64/aarch64

### What installation method did you use?

Source

### What platform did you run on?

Other

**Comment by konskov** [comment]
Hello there @dmilith, thanks for reaching out. Could you provide some more information on the issue you're facing: 
* The specific steps you followed to upgrade
* The steps after the upgrade (what operations did you perform after the upgrade, did you see this error message attempting to do what?)

Thank you!

**Comment by svenklemm** [comment]
The timescaledb installation is per database. Did you upgrade all your databases?

**Comment by nikkhils** [comment]
@dmilith can you please answer the above queries?

**Comment by NunoFilipeSantos** [comment]
Hi @dmilith ! 👋 We're closing this issue for now, feel free to reopen it if you can provide more information. Thank you! 😃
