### ISSUE TITLE
Creating timescaledb extension causes Segmentation Fault on existing non-timescale view/function

### ISSUE THREAD

**Issue by djfsheehan** [timescale/timescaledb#4355]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Query executor

### What happened?

On an existing Postgres 11.7 installation I installed the timescaledb library and created the extension. I installed it from the debian package - see below. No timescale hypertables were created and no functions were called.

A few hours later the server reported being in recovery mode and on examination of the logs it appeared an existing working view (created before timescaledb was installed) had created a segmentation fault which triggered the recovery mode. Since timescale extension was the only the change to the server, I dropped the extension and the view then executed successfully again. Note the view is a little unusual since it selects from a function and that function truncates a table and inserts and updates rows before returning the data to the view.

NOTE: on a copy of the same database on Postgres 14 and the latest version of timescaledb the same view did not cause a seg fault.

My question is 1) are there known issues of the timescaledb extension causing crashes of non-timescale views/functions etc ? 2) Any suggestions how I might get around this issue since I am very keen to use timescaledb on Postgres 11.

wget --content-disposition https://packagecloud.io/timescale/timescaledb/packages/ubuntu/bionic/timescaledb-2-2.3.1-postgresql-11_2.3.1~ubuntu18.04_amd64.deb/download.deb

root@ip-172-31-0-171:~# sudo apt install ./timescaledb-2-2.3.1-postgresql-11_2.3.1~ubuntu18.04_amd64.deb

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

11.7

### What operating system did you use?

Ubuntu 18.04 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

### Relevant log output and stack trace

```bash
2022-05-18 17:32:18 UTC [13385]: [46-1] db=,user=,app=,client=LOG:  server process (PID 25523) was terminated by signal 11: Segmentation fault
2022-05-18 17:32:18 UTC [13385]: [47-1] db=,user=,app=,client=DETAIL:  Failed process was running: SELECT * FROM bids.vw_vcchourlydatafvd
2022-05-18 17:32:18 UTC [13385]: [48-1] db=,user=,app=,client=LOG:  terminating any other active server processes
```

### How can we reproduce the bug?

```bash
Not sure possible at this time unless I can find the specific attribute of the view that causes the crash, but might also be data driven.
```

**Comment by erimatnor** [comment]
@djfsheehan Thanks for the bug report. We are no longer doing updates to 2.3.x and we also dropped PostgreSQL 11 support a while ago. I suggest you update to a recent version of TimescaleDB and PostgreSQL and then feel free to reopen this bug report in case it still is an issue.
