### ISSUE TITLE
missing compressed hypertable

### ISSUE THREAD

**Issue by SephVelut** [timescale/timescaledb#4361]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

`SELECT decompress_chunk('_timescaledb_internal._hyper_1_11_chunk');`

```
Error occurred during SQL query execution

Reason:
SQL Error [XX000]: ERROR: missing compressed hypertable
```

Same error with `SELECT decompress_chunk(i) from show_chunks('schema.table') i;`

`select show_chunks('schema.table')` shows the chunk.

`SELECT remove_compression_policy('schema.table');`
`ERROR: compression policy not found for hypertable "table"`

Tried `ALTER TABLE schema.table SET (timescaledb.compress=false);`. No error, but no resolution when then trying decompress_chunk again.

Had to truncate the table and now the chunks appear to be gone. But since something has gone terribly wrong I can't trust that assumption and will have to wipe the whole database instance. Will try to hold off doing that for a while for issue debugging purposes.

### TimescaleDB version affected
2.6.1

### PostgreSQL version used
14.3

### What operating system did you use?
Ubuntu 21

### What installation method did you use?
Deb/Apt

### What platform did you run on?
Google Cloud Platform (GCP)

**Comment by felipenogueirajack** [comment]
I had this same error. In my case, it happens when I tried to decompress a chunk in a hypertable without any chunk being previously compressed.
