### ISSUE TITLE
Truncating a compressed chunk does not work, but does not return an error

### ISSUE THREAD

**Issue by jayadevanm** [timescale/timescaledb#4362]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

Executing TRUNCATE on a compressed chunk returns `TRUNCATE TABLE` but table does not get truncated.

### TimescaleDB version affected

2.5.1 

### PostgreSQL version used

13.5

### What operating system did you use?

Ubuntu 

### What installation method did you use?

Docker

### What platform did you run on?

Microsoft Azure Cloud

### Relevant log output and stack trace

```bash
cscore=# TRUNCATE TABLE   _timescaledb_internal._hyper_314_130697_chunk;
TRUNCATE TABLE
Time: 211.563 ms
cscore=# SELECT COUNT(*) FROM _timescaledb_internal._hyper_314_130697_chunk;
 count 
-------
     1
(1 row)

Time: 177.186 ms
```

### How can we reproduce the bug?

```bash
DROP TABLE IF EXISTS myt;
CREATE TABLE myt (ts timestamptz PRIMARY KEY  , id INTEGER);
SELECT  create_hypertable('myt','ts');
ALTER TABLE myt SET (
  timescaledb.compress
);
INSERT INTO myt VALUES (now(),1);
SELECT compress_chunk(i, if_not_compressed => true) 
  FROM show_chunks('myt') i;
TRUNCATE TABLE   _timescaledb_internal._hyper_314_130697_chunk;
/* We get a response TRUNCATE TABLE */
SELECT COUNT(*) FROM _timescaledb_internal._hyper_314_130697_chunk;
/* Expected 0 , got 1 */
SELECT decompress_chunk(i) FROM show_chunks('myt') i;
TRUNCATE TABLE    _timescaledb_internal._hyper_314_130697_chunk;
SELECT COUNT(*) FROM _timescaledb_internal._hyper_314_130697_chunk;
/* Now we get 0, as expected */
```

**Comment by erimatnor** [comment]
Hi @jayadevanm, thank you for the bug report. I was able to reproduce this bug:

```sql
CREATE TABLE myt (ts timestamptz PRIMARY KEY  , id INTEGER);
SELECT  create_hypertable('myt','ts');
ALTER TABLE myt SET (
  timescaledb.compress
);
INSERT INTO myt VALUES (now(),1);
SELECT compress_chunk(i, if_not_compressed => true) 
  FROM show_chunks('myt') i;

SELECT c AS chunk FROM show_chunks('myt') c \gset
TRUNCATE TABLE :chunk;
SELECT count(*) FROM :chunk;
```

**Comment by mfundul** [comment]
I think the best course of action here could be to disallow `TRUNCATE TABLE` on chunks. Doing a `DROP TABLE` on a chunk should work fine. I don't think there is much value in keeping a truncated chunk around, instead of dropping it. Thoughts?

**Comment by jayadevanm** [comment]
> I think the best course of action here could be to disallow `TRUNCATE TABLE` on chunks. Doing a `DROP TABLE` on a chunk should work fine. I don't think there is much value in keeping a truncated chunk around, instead of dropping it. Thoughts?

Yes, that would work in my case. If we drop a chunk directly using DROP TABLE, will that cause a problem - as the metadata may still refer to it?
