### ISSUE TITLE
[Bug]: Autorefresh of continuous aggregates not working, based on issue #3796

### ISSUE THREAD

**Issue by kaarenilsen** [timescale/timescaledb#4382]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Auto refresh of continuous aggregates using SELECT add_continuous_aggregate_policy not working.

Calling refresh_continuous_aggregate manually do work, but not continous  updating. I have found that when trying to wrap refresh_continous_aggregate inside a procudure (or function) I get the same error message as in our logs. So I was thinking that that might be related

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

13.5

### What operating system did you use?

Windows 10

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
[XX000] ERROR: portal snapshots (1) did not account for all active snapshots (2) Where: SQL function "same_errormessage_as_add_continuous_aggregate_policy" statement 1
```

### How can we reproduce the bug?

```bash
CREATE TABLE conditions(
    time TIMESTAMP NOT NULL,
    device_id INTEGER,
    temperature FLOAT,
    humidity FLOAT
);

SELECT * FROM create_hypertable('conditions', 'time', 'device_id', 12);

INSERT INTO conditions
SELECT time, (random()*3 + 1)::int, random()*80 - 40, random()*100
FROM generate_series(now() - INTERVAL '28 days', now(), '1 hour') AS time;

CREATE MATERIALIZED VIEW conditions_summary_hourly
WITH (timescaledb.continuous) AS
SELECT device_id,
       time_bucket(INTERVAL '1 hour', "time") AS bucket,
       AVG(temperature),
       MAX(temperature),
       MIN(temperature)
FROM conditions
GROUP BY device_id, bucket
WITH NO DATA;


CREATE or replace PROCEDURE same_errormessage_as_add_continuous_aggregate_policy()
LANGUAGE SQL
AS $$
call refresh_continuous_aggregate('conditions_summary_hourly', '2022-01-01', '2022-02-01');
$$;

call same_errormessage_as_add_continuous_aggregate_policy();

-- Gives the following error: [XX000] ERROR: portal snapshots (1) did not account for all active snapshots (2) Where: SQL function "same_errormessage_as_add_continuous_aggregate_policy" statement 1
```

**Comment by svenklemm** [comment]
Can you try upgrading to postgres 13.7 i think this was an issue with a specific postgres version.

**Comment by svenklemm** [comment]
I could reproduce on latest version and on PG14.

**Comment by RafiaSabih** [comment]
This should be fixed by recent TimescaleDB version.
