### ISSUE TITLE
feature request: LONG-WIDE Reshaping

### ISSUE THREAD

**Issue by Sigi-Bereuter** [timescale/timescaledb#440]
I'm doing analytics in R and therefore fetching Timeseries Data from DB Tables.
A common problem is that e.g. Regression Algorithms require to have the data in a Matrix with one Row per Timestamp but the Db has multiple Lines per timestamp. This is because the DB Schema is in LONG-Shape - meaning we have 3 Columns  Timestamp,MetricName,Value. The R-Matrix must be in WIDE-Shape meaning one row per Timestamp with Timestamp columns and additionally as many columns as MetricNames in the Dataset (each column containing the Value at that Timestamp).

In R we use a function ReShape() - which we would like to already apply by TimeScaleDB when returning the Result. 
Note: The feature request [LOCF ](https://github.com/timescale/timescaledb/issues/421) is related to this, since when converting from LONG to WIDE you will need the LOCF option most of the time to fill missing MetricValues at a certain timestamp..

**Comment by mfreed** [comment]
Hi @Sigi-Bereuter can you be a little more explicit about what you want?

For example, on one hand, I could imagine a fairly simple function that does a `GROUP BY` to create a group over multiple rows (say, by timestamp), and then just generate a "wide row" by converting <metricName: value> tuples into columns.

But when you start talking about LOCF, it sounds like you want something different.  I.e., possible define a priori to set the desired metric name columns (as opposed to just generating this dynamically based on what data is available in the group), and further, for missing names, use something like LOCF to get the latest (as opposed to returning a NULL).

So is that the functionality you want?  Or something slightly different?   I'm making no promises about when this would go on our roadmap, but it's also good to fully understand the feature request :)

Thanks!

**Comment by Sigi-Bereuter** [comment]
Hi Mike !

Thanks for your questions, I try to explain it:
Concerning LONG->WIDE reshaping it's you got the point exactly - you woul do a GROUP BY Timestamp and then you create as much columns as you get distinct metricsNames over all groups. So e.g. in timestamp t1 you may have metrics m1,m2,m3 , in t1->m2,m4, in t3->m1,m2,m5,m7.
The resulting Matrix would have 3 rows (t1,t2,t3) and 6 Columns (m1,m2,m3,m4,m5,m7).

 Now LOCF comes into play since some Values will be null since there were no oberservations at some timestamps (e.g. t1->m4,m5,m7) . What LOCF does is simply go to those null Values and look back in the timestamps until it finds a Value for this metric at an earlier timestamp (Last Oberservation) and if yes fill this into the null values.

The Result is a complete Matrix which is already created on the DB side what should be much more performant then pulling all data to R to do this transformation. 

As mentioned in R we have Reshape() and LOCF functions , They have some parameters which could be starting point (in case this feature maskes it into a release some day)

If you have more questions, don't hesitate.
Thx

**Comment by Sigi-Bereuter** [comment]
Here the Codesnippet from R with the steps to do:
Explanation: 
`longData `is the Table read from the DB containing the Columns `MetricName ,Value,Timestamp`

1. Make table [distinct](https://www.rdocumentation.org/packages/dplyr/versions/0.7.3/topics/distinct) since we could have duplicates in the data which would cause problem with spread function.
`longUnique <- distinct(longData,Timestamp,MetricName,.keep_all = TRUE)`

2. Create Wide Table with [spread](https://www.rdocumentation.org/packages/tidyr/versions/0.8.0/topics/spread)
`wideData <- spread(longUnique,MetricName,Value)`

3. Do [LOCF ](https://www.rdocumentation.org/packages/zoo/versions/1.8-1/topics/na.locf)on each column where it is desired
```
wideData$m1 <- na.locf(wideData$m1, na.rm = FALSE)
wideData$m2 <- na.locf(wideData$m2 ,na.rm = FALSE)
wideData$m3 <- na.locf(wideData$m3, na.rm = FALSE)
wideData$m4 <- na.locf(wideData$m4 ,na.rm = FALSE)
wideData$m5 <- na.locf(wideData$m5, na.rm = FALSE)
wideData$m6 <- na.locf(wideData$m6, na.rm = FALSE)
wideData$m7 <- na.locf(wideData$m7 ,na.rm = FALSE)

Actually I added the link to the functions distinct,spread,locf just that you can read the purpose and general functionality, but not because I need all there options.

**Comment by Sigi-Bereuter** [comment]
Thanks @oldgreen for the hint, postreSQL crosstab function seems to exactly what we do with spread (WIDE->LONG) in R.
I must admit that I do not know a lot of PostgresSQL up to now, so we could close the feature request as it seems to me.
What still is left open is the LOCF function, which is a typically problem you have when analyzing  timeseries data. So maybe timescaledb can combine the existing crosstab function with a new LOCF  feature since you usually need both function when preparing timeseries data for analysis.

**Comment by mfreed** [comment]
Hi @Sigi-Bereuter :  As I posted in response to your issue https://github.com/timescale/timescaledb/issues/421, LOCF has be merged and will be in the next TimescaleDB release (version 1.2).
