### ISSUE TITLE
[Bug]: pg_restore fails with "pg_restore: error: could not read from input file: end of file"

### ISSUE THREAD

**Issue by CaptainStiggz** [timescale/timescaledb#4410]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Backup

### What happened?

Hi, not entirely sure if this is a bug or not, but wanted to solicit some feedback. 

I have a ~10.5GB sql backup file generated by an ex-employee. The backup file was created using the instructions [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/#restore-your-entire-database-from-backup), and stored as a `.sql` file. 

When I try to use `pg_restore` according to the instructions on the same page, it fails with the following:
`pg_restore: error: could not read from input file: end of file`

If I open the file, I see a series of valid SQL commands to create all the tables and constraints, followed by a ton of what looks like base64-encoded text. 

Is this the expected format of the backup file? I'm trying to discern if my backup file is corrupted or if there's an issue with the restore command.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.1

### What operating system did you use?

Ubuntu 18.04.6

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

**Comment by pmwkaa** [comment]
@CaptainStiggz Hey, it is hard to tell if the dump is correct and finished properly without looking at it. Does those encoded strings placed after some command? like COPY, etc. Was it a multi-node environment by any chance?

**Comment by nikkhils** [comment]
@CaptainStiggz was the backup created using a `pg_dump` command like below?

`pg_dump -Fc -f exampledb.bak exampledb`

**Comment by NunoFilipeSantos** [comment]
Hi @CaptainStiggz! 👋 We're closing this issue, feel free to reopen it if you can provide more information. Thank you!
