### ISSUE TITLE
Incorrect documentation?

### ISSUE THREAD

**Issue by cemremengu** [timescale/timescaledb#442]
Sorry I couldn't find a place to submit a PR for this so creating an issue:

On page http://docs.timescale.com/v0.8/using-timescaledb/hypertables

A hypertable with only `temperature` column is created however next examples (insert, update etc.) also include a `humidity` column.

**Comment by mfreed** [comment]
Thanks for the report, @cemremengu .  The subsection right after creating a hypertable on that docs page shows how to alter a hypertable (with the following command:

```
ALTER TABLE conditions
   ADD COLUMN humidity DOUBLE PRECISION NULL;
```

http://docs.timescale.com/v0.8/using-timescaledb/hypertables#alter

This is where we got the `humidity` column used in our later example.  I can see, however, how that would be easily missed if you only read the section on `CREATE TABLE`.

Regardless, did you find this *confusing* or were you just making the suggestion that our docs should be internally consistent (rightly so)?

Thanks!

**Comment by mfreed** [comment]
I'm going to close this issue for now, as the docs example is actually correct.  But feel free to make some suggestions @cemremengu .  Thanks!
