### ISSUE TITLE
[Feature]: <Composite Key Support>

### ISSUE THREAD

**Issue by vishnumurthy-nd** [timescale/timescaledb#4422]
### What problem does the new feature solve?

The database is supporting time column as primary key. But required support for composite key (combining timestamp with other column) as primary key.

### What does the feature do?

Composite key to be support. For example when 2 devices send the data at same time stamp the data uniqueness is maintained with device id as we are storing time stamp without time zone. This is already functional in postgres. 

But while creating the hyper table only one column can be referenced as primary key that 2 records with same timestamp will not be persisted and requires the support for composite key.

Let me know is there any option to achieve this functionality.

**Comment by erimatnor** [comment]
You can try to partition in multiple dimensions, e.g., add a space partitioning column. For instance, you can partition on <time, device>. That will allow <time, device> as primary key. Note however, that the same device cannot send two values with the same timestamp in that case.

**Comment by mindrunner** [comment]
Maybe I misunderstand the question, but I think this is easily possible:

```
        CREATE TABLE "values" ("deviceId" character varying NOT NULL, "time" TIMESTAMP WITH TIME ZONE NOT NULL, "value" double precision NOT NULL, CONSTRAINT "PK_358d4ebb1b184b910c8db4dd2df" PRIMARY KEY ("deviceId", "time"))
        SELECT create_hypertable('values', 'time')
```

this will result in being able to store values for multiple `deviceId`s having the same timestamb, but will rerect any insert for a given `deviceId` with an already existing timestamp.

**Comment by vishnumurthy-nd** [comment]
Thanks... It solved the problem
