### ISSUE TITLE
Separate pre- and post-PG13 finalize function

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#4427]
# Goal

Ensure that when upgrading from PG13 to versions later than PG13 continuous aggregates are still able to work correctly.

# Background

The numeric format changed between PG13 and PG14 to include infinities (https://github.com/postgres/postgres/commit/a57d312a7706321d850faa048a562a0c0c01b835), which means that the serialized format that is used by continuous aggregates will not work after upgrading to PG14.

# Problem

The main reason for this is because the existing function to finalize continuous aggregates `_timescaledb_internal.finalize_agg` is compiled with the current version of PostgreSQL, which means that for versions before PG14 it will behave different from version PG14 or later. Since there is no way to capture this change while running `pg_upgrade`, this will work fine but the 

This means that when performing an upgrade, it will succeed, but the resulting partial aggregate will be incompatible with the new function. Typically, an error will be generated as shown in #4369, but it is unclear if there are any corner-cases that could run successfully but generate the wrong result.

If upgrading to the finals form using the solution provided by #4424 would eliminate the problem, but for large amounts of data, this might be prohibitive since the migration can be very expensive. For similar reasons, the solution in #4376 might not be sufficient, even though it is cheaper and can be executed in-place.

# Proposal

For versions PG14 and later, use the name `_timescaledb_internal.finalize_agg_14` and for version before PG14, use `_timescaledb_internal.finalize_agg`. This will allow a clear separations for the finalize function before and after PG14 and will allow continuous aggregates to continue to be used.

However, both functions need to be available and loaded, which means that it might be necessary to either ensure that two shared libraries can be loaded in parallel, or that the old defininition of `numeric` is made available in TimescaleDB.

**Comment by mfundul** [comment]
Non-numeric aggregate functions definitely affected by this problem:
```
1. var_pop(int8)
2. var_samp(int8)
3. variance(int8)
4. stddev_pop(int8)
5. stddev_samp(int8)
6. stddev(int8)
```
Non-numeric aggregate functions **potentially** affected by this problem (depends on compiler support for `HAVE_INT128`):
```
1. var_pop(int4)
2. var_pop(int2)
3. var_samp(int4)
4. var_samp(int2)
5. variance(int4)
6. variance(int2)
7. stddev_pop(int4)
8. stddev_pop(int2)
9. stddev_samp(int4)
10. stddev_samp(int2)
11. stddev(int4)
12. stddev(int2)
```
