### ISSUE TITLE
Upgrade tests between PG versions

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#4428]
# Goal

Ensure that we have a CI test that checks that upgrades between PostgreSQL versions work correctly.

# Background

The numeric format changed between PG13 and PG14 to include infinities (https://github.com/postgres/postgres/commit/a57d312a7706321d850faa048a562a0c0c01b835), which means that the serialized format that is used by continuous aggregates will not work after upgrading to PG14.

# Problem

There are no upgrade tests that tests that the same result if produced after upgrading to a new PostgreSQL version.

# Proposal

Use the existing upgrade tests between TimescaleDB versions and test that they generate the same result after running `pg_upgrade` when using the same TimescaleDB version.

**Comment by svenklemm** [comment]
Duplicate of #3868

**Comment by fabriziomello** [comment]
Closes as completed in https://github.com/timescale/timescaledb/pull/6951
