### ISSUE TITLE
[Bug]: Website lacks command in installation instructions

### ISSUE THREAD

**Issue by ilka-schulz** [timescale/timescaledb#4431]
### What type of bug is this?

Other

### What subsystems and features are affected?

Packaging

### What happened?

Your installation instructions for Debian lack the code for step 3. There is just an empty code box on your website...

https://docs.timescale.com/install/latest/self-hosted/installation-debian/

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

14.1

### What operating system did you use?

Debian 11

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
[...]

2. Run the PostgreSQL repository setup script:

/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

3. Add the TimescaleDB third party repository:


4. Install Timescale GPG key

wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | apt-key add -

5. Update your local repository list:

[...]
```

### How can we reproduce the bug?

```bash
1. go to https://docs.timescale.com/install/latest/self-hosted/installation-debian/
2. see section `Installing self-hosted TimescaleDB on Debian-based systems`
3. see step 3
```

**Comment by Rajakavitha1** [comment]
Hi @jacobprall !!! I lookup the source docs and we do have the instructions looks like there is an issue in rendering the <tab> tags. 
<img width="758" alt="Screenshot 2022-06-16 at 3 20 55 PM" src="https://user-images.githubusercontent.com/37059749/174044552-f8b64c62-5eeb-4e02-a8cc-84ce9db28088.png">

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if the issue persists.
