### ISSUE TITLE
data_node_bootstrap test is flaky

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#4435]
### Which test is flaky?

data_node_bootstrap 

### Link to the failed test run

https://github.com/timescale/timescaledb/runs/6837308385?check_suite_focus=true

### Log output

```bash
+++ /home/runner/work/timescaledb/timescaledb/build/tsl/test/results/data_node_bootstrap.out	2022-06-10 20:08:35.266287365 +0000
@@ -75,7 +75,7 @@
 SELECT * FROM add_data_node('bootstrap_test', host => 'localhost', database => 'bootstrap_test');
 NOTICE:  database "bootstrap_test" already exists on data node, skipping
 NOTICE:  extension "timescaledb" already exists on data node, skipping
-ERROR:  cannot add "bootstrap_test" as a data node
+ERROR:  database exists but has wrong collation
 \set ON_ERROR_STOP 0
 DROP DATABASE bootstrap_test;
```

### Reason for flakiness

Seems to be related to recent factorings to add PG15 support

**Comment by CruxBox** [comment]
Hi, I was trying to replicate this by building from scratch. I built PG14.3 from scratch but when running CMakeLists.txt, the 'PG_VERSION_MAJOR' turns out to be 15 which doesn't allow me to continue with bootstrapping.
Do I use the EXPERIMENTAL option while bootstrapping?

Can I get any leads here?

**Comment by svenklemm** [comment]
cmake will use pg_config to locate your postgres installation but you can overwrite it by pointing it to specific installation at bootstrap.
```
./bootstrap -DCMAKE_BUILD_TYPE="Release" -DPG_CONFIG=/usr/local/pg14_opt/bin/pg_config
```

**Comment by CruxBox** [comment]
My bad, I was building from postgre's main branch. Used a release-tag now.
PG_CONFIG isn't an issue anymore. But I can't tell the difference between PG_SRC_DIR and PG_PATH when bootstrapping. I can tell from the logs that it isn't inferring it.

In the pipeline you shared, the PG build job is skipped, I could have used that to tell what these variables meant

**Comment by jchampio** [comment]
I'm seeing an additional `DETAIL` line in my local reproduction:
```
DETAIL:  Expected collation "" but it was "en_US.UTF-8".
```

@svenklemm Looks like [`ReleaseSysCache()` is called on the underlying tuple](https://github.com/timescale/timescaledb/blob/ed55654/tsl/src/data_node.c#L112) in `get_database_info()`, but we haven't actually copied the fields to memory we own. If I compile Postgres with `-DCATCACHE_FORCE_RELEASE` I can reproduce similar errors every test run.

**Comment by svenklemm** [comment]
Great find, i suspected something like that but it's weird that the flakyness only started recently while we never copied the values.
