### ISSUE TITLE
[Feature]: time_bucket_ng_gapfill()

### ISSUE THREAD

**Issue by lafrech** [timescale/timescaledb#4455]
### What problem does the new feature solve?

`time_bucket_ng` doesn't have a `time_bucket_ng_gapfill` equivalent like `time_bucket` does.

[AuspeXeu](https://github.com/AuspeXeu) commented [on 5 Oct 2021](https://github.com/timescale/timescaledb/issues/414#issuecomment-934357746) to ask for it.

[NunoFilipeSantos](https://github.com/NunoFilipeSantos) commented [on 6 Oct 2021](https://github.com/timescale/timescaledb/issues/414#issuecomment-936008266) to say an issue should be filed.

Here it is.

### What does the feature do?

Same as `time_bucket` but for `time_bucket_ng`.

**Comment by svenklemm** [comment]
Duplicate of #4005

**Comment by lafrech** [comment]
🤦 Sorry about the duplicate. Somehow #4005 didn't show up in my search.
