### ISSUE TITLE
[Enhancement]: Allow SkipScan to work with text_pattern_ops indexes

### ISSUE THREAD

**Issue by mschwore** [timescale/timescaledb#4479]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

SkipScan

### What does the enhancement do?

Allow SkipScan to work with indexes that use the text_pattern_ops option (See https://www.postgresql.org/docs/12/indexes-opclass.html)

The text_pattern_ops is useful for using the index with LIKE queries but I would also want SkipScan to work on the text_pattern_ops index as well.

Here is a code snippet using text_pattern_ops that does not choose a plan with SkipScan:

```
create table readings(time timestamptz, device_id text, battery_level float);
select create_hypertable('readings','time');
create index ON readings (device_id text_pattern_ops,time desc);

insert into readings select '2000-01-01',1,random() from generate_series(1,1000);
analyze readings;
explain select distinct ON (device_id) * from readings ORDER BY device_id, time desc;
```

Creating the `readings` table without the text_pattern_ops option allows SkipScan to work (but LIKE queries no longer use the index)

**Comment by jnidzwetzki** [comment]
Hello @mschwore,

Thanks for reaching out. I would like to reproduce the behavior you mentioned. Could you provide us the schema of the _readings_ table that you mentioned (i.e., the used `CREATE TABLE` statement or the output of `\d+ readings`)?

**Comment by svenklemm** [comment]
text_pattern_ops indexes do not support sort operations which is a requirement for any index used by skipscan. This would require an upstream change to make those indexes usable by sort operations.
