### ISSUE TITLE
Timescale implicitly making ORDER BY case sensitive

### ISSUE THREAD

**Issue by approxit** [timescale/timescaledb#448]
By reading the docs we are assured that TimescaleDB is only extension for PostgreSQL and besides the additional features rest of functionality is just PostgreSQL. So... Changing only docker image from `postgres` to `timescale/timescaledb` should not change anything. But it does. Unfortunately.

Default PostgreSQL `ORDER BY` method is case insensitive, but with default TimescaleDB we're getting `ORDER BY` method that is case sensitive. It looks like a very minor difference, unless your application strongly depends on case insensitive method. For me is a undesired and unexpected behavior.

Simplest example for default PostgreSQL:
```
$ docker run -d --rm --name postgres_example postgres
$ docker exec postgres_example psql -U postgres -c "SELECT * FROM (VALUES ('A'), ('b'), ('C')) as foo(name) ORDER BY foo.name ASC;"
 name 
------
 A
 b
 C
(3 rows)
```
The very same example but with default TimescaleDB:
```
$ docker run -d --rm --name timescale_example timescale/timescaledb
$ docker exec timescale_example psql -U postgres -c "SELECT * FROM (VALUES ('A'), ('b'), ('C')) as foo(name) ORDER BY foo.name ASC;"
 name 
------
 A
 C
 b
(3 rows)
```

Note that TimescaleDB orders letters as upper case first and then lower case. Examples can be reproduced on different versions of images for PostgreSQL and TimescaleDB. Difference happens when TimescaleDB is on the board.

**Comment by cevian** [comment]
This actually appears to be a `debian` vs `alpine` issue and not a `postgres` vs `timescale` issue.  Timescale's Docker image is actually based on the `postgres:alpine` image not `postgres` image. That image has same behavior as Timescale: 
```
$ docker run -d --rm --name postgres_example postgres:alpine
$ docker exec timescale_example psql -U postgres -c "SELECT * FROM (VALUES ('A'), ('b'), ('C')) as foo(name) ORDER BY foo.name ASC;"
 name
------
 A
 C
 b
(3 rows)
``` 

Have you tried using a different default collation than UTF-8 (e.g. latin1)?

**Comment by davidkohn88** [comment]
I wouldn't necessarily recommend using a different default collation for the database if you can avoid it, managing default collations is a bit crazy, I usually use the C collation as default as it's the only one that's portable and guaranteed to be the same across servers and if I need a different collation for specific column I'll add that to the column def, or if it's for a specific query, then I'll add it to the query itself ie `SELECT name COLLATE "en_US" ...`. 

If you can find a collation that you can install that meets your needs, then just install that collation and collate the column that way. But in this case it might be easier to just do `...ORDER BY UPPER(foo.name) ASC` in your query. (This does add some possible problems with repeated keys with different capitalization, but you can add another order by clause to fix that if needed).

**Comment by approxit** [comment]
I actually did not expect that `alpine` version can make that difference. Thanks for pointing that out. Thanks for answers too. I'll follow the best approach that suites my cases.

Issue is not related with TimescaleDB itself, so this issue can be closed, and discussion can be moved to linked issue on postgres docker-library repo.
