### ISSUE TITLE
[Bug]: Adding boolean column with default value doesn't work on compressed table

### ISSUE THREAD

**Issue by janko** [timescale/timescaledb#4486]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

When I try to add a boolean column with a default value to an existing table that has compression enabled, the alter table command fails with an error from Timescale, saying it cannot add a column with "non-constant default expression" on a compressed hypertable.

When I look at the [Modify a schema](https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/modify-a-schema/#add-a-nullable-column) page in documentation, it appeared this should be supported. I understand why a non-constant expression wouldn't work, but I used the default of `false`, which *is* a constant expression 🤔 

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.4

### What operating system did you use?

Mac OS X 11.6 M1

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```
ERROR:  cannot add column with non-constant default expression to a hypertable that has compression enabled
```

### How can we reproduce the bug?

```sql
CREATE TABLE records (time timestamp NOT NULL);
SELECT create_hypertable('records', 'time');
ALTER TABLE records SET (timescaledb.compress = true);
ALTER TABLE records ADD COLUMN col boolean DEFAULT false NOT NULL;
```

**Comment by RafiaSabih** [comment]
https://github.com/timescale/timescaledb/pull/4537
