### ISSUE TITLE
[Bug]: Postgres Db crashes after few days with workload | Kubernetes

### ISSUE THREAD

**Issue by this-is-r-gaurav** [timescale/timescaledb#4498]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Data ingestion

### What happened?

We have been running timescale for more than two week on kubernetes using timescale-single helm chart. But after few days it crashes on the system.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

13.7

### What operating system did you use?

Ubuntu 20.04, K8s 1.20.15

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Warning  Unhealthy  19s (x24209 over 10d)  kubelet  Readiness probe failed: /var/run/postgresql:5432 - rejecting connections
```
When i exec into the container i can't see the socket file in /var/run

### How can we reproduce the bug?

```bash
- Install timescale with backup disabled using timescale helm chart. https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single
- Connected with Promscale.
- Run workload for few days through prometheus, pushing large records to prometheus continuously(say at a period of 30s )
```

**Comment by this-is-r-gaurav** [comment]
Hi @jnidzwetzki Its still occurring with latest chart as well, sorry for taking that long.

I have used this image timescale/timescaledb-ha:pg14.4-ts2.7.1-p0

**Comment by jnidzwetzki** [comment]
Hello @this-is-r-gaurav,

Thank you very much for your reply. Might it be possible for you to share the used table structure, some sample data, and the logfile of PostgreSQL that contains the error?

I would also recommend upgrading to TimescaleDB 2.7.2, as version 2.7.1 contains a memory leak that might cause OOM situations on long-running connections (see #4507), which could be the reason for the failed readiness probe after a few days.

**Comment by this-is-r-gaurav** [comment]
Closing the issue, as i have no longer access to those clusters.

**Comment by Novaneith** [comment]
Hello, I currently have the same issue. The chart started to show this error after a few days of running workload but was stable for much longer before that.
I'm using timescaledb-single:0.27.4
