### ISSUE TITLE
[Bug]: PostgreSQL killed by OOM killer after upgrading TimescaleDB to 2.7.1

### ISSUE THREAD

**Issue by hongquan** [timescale/timescaledb#4507]
### What type of bug is this?

Other

### What subsystems and features are affected?

Query executor

### What happened?

After I upgrade to v2.7.1, PostgreSQL get out-of-memory error and get killed by OOM killer. This never happen with TimescaleDB v2.7.0 and earlier.

### TimescaleDB version affected

2.7.1

### PostgreSQL version used

14.4

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
- Upgrade TimescaleDB with `apt upgrade`.
- Run the `ALTER EXTENSION timescaledb UPDATE;` query.
- Wait for some hours.
```

**Comment by jnidzwetzki** [comment]
Hello @hongquan,

Thanks for reaching out. I would like to reproduce the problem with Timescale 2.7.1. Would it be possible for you to share the schema used and the last relevant lines from the syslog/PostgreSQL log that cover the OOM situation?

Are you running queries on the database or is the error caused by one of the background jobs? If queries are executed, could you share the executed queries?

**Comment by hongquan** [comment]
@jnidzwetzki Our application is a Django application, in IoT field. Here is the part of schema that uses TimescaleDB:

```sql
--
-- Create model TSMeasure
--
CREATE TABLE "farm_tsmeasure" (
  "measured_at" timestamp with time zone NOT NULL PRIMARY KEY, 
  "bird_in" integer NULL CHECK ("bird_in" >= 0), 
  "bird_out" integer NULL CHECK ("bird_out" >= 0), 
  "voltage" double precision NULL, 
  "electric_current" double precision NULL, 
  "power" double precision NULL, 
  "electrical_energy" double precision NULL, 
  "ampli_1_left" double precision NULL, 
  "ampli_1_right" double precision NULL, 
  "ampli_2_left" double precision NULL, 
  "ampli_2_right" double precision NULL, 
  "ampli_3_left" double precision NULL, 
  "ampli_3_right" double precision NULL, 
  "ampli_4_left" double precision NULL, 
  "ampli_4_right" double precision NULL, 
  "crop_id" integer NULL, 
  "node_id" integer NULL, 
  "room_id" integer NULL
);
--
-- Create model TSCondition
--
CREATE TABLE "farm_tscondition" (
  "measured_at" timestamp with time zone NOT NULL PRIMARY KEY, 
  "temperature" double precision NULL, 
  "humidity" double precision NULL, 
  "brightness" double precision NULL, 
  "carbonic" smallint NULL CHECK ("carbonic" >= 0), 
  "moisture" double precision NULL, 
  "dielectric" double precision NULL, 
  "soil_temperature" double precision NULL, 
  "soil_electrical_conductivity" double precision NULL, 
  "electrical_conductivity" double precision NULL, 
  "hydrogen_power" double precision NULL, 
  "solution_temperature" double precision NULL, 
  "solution_salinity" double precision NULL, 
  "crop_id" integer NULL, 
  "node_id" integer NULL, 
  "room_id" integer NULL
);
--
-- Create index farm_tsmeasure_node_index on field(s) room, node, -measured_at of model tsmeasure
--
CREATE INDEX "farm_tsmeasure_node_index" ON "farm_tsmeasure" (
  "room_id", "node_id", "measured_at" DESC
) 
WHERE 
  (
    NOT ("room_id" IS NULL) 
    AND NOT ("node_id" IS NULL)
  );
--
-- Create index farm_tscondition_node_index on field(s) room, node, -measured_at of model tscondition
--
CREATE INDEX "farm_tscondition_node_index" ON "farm_tscondition" (
  "room_id", "node_id", "measured_at" DESC
) 
WHERE 
  (
    NOT ("room_id" IS NULL) 
    AND NOT ("node_id" IS NULL)
  );
--
-- Raw SQL operation
--
SELECT 
  create_hypertable(
    'farm_tscondition', 'measured_at', 
    chunk_time_interval => INTERVAL '1 hour'
  );
--
-- Raw SQL operation
--
SELECT 
  create_hypertable(
    'farm_tsmeasure', 'measured_at', 
    chunk_time_interval => INTERVAL '1 hour'
  );
--
-- Raw SQL operation
--
CREATE MATERIALIZED VIEW farm_tscondition_10m WITH (timescaledb.continuous) AS 
SELECT 
  node_id, 
  crop_id, 
  room_id, 
  time_bucket(
    INTERVAL '10 minutes', measured_at
  ) AS time_start, 
  AVG(temperature) AS avg_temperature, 
  AVG(humidity) AS avg_humidity, 
  AVG(brightness) AS avg_brightness, 
  AVG(carbonic) AS avg_carbonic, 
  AVG(moisture) AS avg_moisture, 
  AVG(dielectric) AS avg_dielectric, 
  AVG(soil_temperature) AS avg_soil_temperature, 
  AVG(soil_electrical_conductivity) AS avg_soil_electrical_conductivity, 
  AVG(electrical_conductivity) AS avg_electrical_conductivity, 
  AVG(hydrogen_power) AS avg_hydrogen_power, 
  AVG(solution_temperature) AS avg_solution_temperature, 
  AVG(solution_salinity) AS avg_solution_salinity 
FROM 
  farm_tscondition 
WHERE 
  node_id IS NOT NULL 
  AND room_id IS NOT NULL 
GROUP BY 
  node_id, 
  crop_id, 
  room_id, 
  time_start WITH NO DATA;
SELECT 
  add_continuous_aggregate_policy(
    'farm_tscondition_10m', start_offset => INTERVAL '1 h', 
    end_offset => INTERVAL '10 m', schedule_interval => INTERVAL '10 m'
  );
CREATE MATERIALIZED VIEW farm_tsmeasure_10m WITH (timescaledb.continuous) AS 
SELECT 
  node_id, 
  crop_id, 
  room_id, 
  time_bucket(
    INTERVAL '10 minutes', measured_at
  ) AS time_start, 
  -- For bird, we are counting, so the sum is more meaningful than average.
  SUM(bird_in) AS sum_bird_in, 
  SUM(bird_out) AS sum_bird_out, 
  AVG(voltage) AS avg_voltage, 
  AVG(electric_current) AS avg_electric_current, 
  AVG(power) AS avg_power, 
  AVG(electrical_energy) AS avg_electrical_energy, 
  AVG(ampli_1_left) AS avg_ampli_1_left, 
  AVG(ampli_1_right) AS avg_ampli_1_right, 
  AVG(ampli_2_left) AS avg_ampli_2_left, 
  AVG(ampli_2_right) AS avg_ampli_2_right, 
  AVG(ampli_3_left) AS avg_ampli_3_left, 
  AVG(ampli_3_right) AS avg_ampli_3_right, 
  AVG(ampli_4_left) AS avg_ampli_4_left, 
  AVG(ampli_4_right) AS avg_ampli_4_right 
FROM 
  farm_tsmeasure 
WHERE 
  node_id IS NOT NULL 
  AND room_id IS NOT NULL 
GROUP BY 
  node_id, 
  crop_id, 
  room_id, 
  time_start WITH NO DATA;
SELECT 
  add_continuous_aggregate_policy(
    'farm_tsmeasure_10m', start_offset => INTERVAL '1 h', 
    end_offset => INTERVAL '10 m', schedule_interval => INTERVAL '10 m'
  );
ALTER TABLE 
  "farm_tsmeasure" 
ADD 
  CONSTRAINT "farm_tsmeasure_crop_id_3dfd561d_fk_farm_crop_id" FOREIGN KEY ("crop_id") REFERENCES "farm_crop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE 
  "farm_tsmeasure" 
ADD 
  CONSTRAINT "farm_tsmeasure_node_id_fe716720_fk_farm_node_id" FOREIGN KEY ("node_id") REFERENCES "farm_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE 
  "farm_tsmeasure" 
ADD 
  CONSTRAINT "farm_tsmeasure_room_id_675ed512_fk_farm_room_id" FOREIGN KEY ("room_id") REFERENCES "farm_room" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "farm_tsmeasure_crop_id_3dfd561d" ON "farm_tsmeasure" ("crop_id");
CREATE INDEX "farm_tsmeasure_node_id_fe716720" ON "farm_tsmeasure" ("node_id");
CREATE INDEX "farm_tsmeasure_room_id_675ed512" ON "farm_tsmeasure" ("room_id");
ALTER TABLE 
  "farm_tscondition" 
ADD 
  CONSTRAINT "farm_tscondition_crop_id_09a48628_fk_farm_crop_id" FOREIGN KEY ("crop_id") REFERENCES "farm_crop" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE 
  "farm_tscondition" 
ADD 
  CONSTRAINT "farm_tscondition_node_id_94d38da4_fk_farm_node_id" FOREIGN KEY ("node_id") REFERENCES "farm_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE 
  "farm_tscondition" 
ADD 
  CONSTRAINT "farm_tscondition_room_id_ce266840_fk_farm_room_id" FOREIGN KEY ("room_id") REFERENCES "farm_room" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "farm_tscondition_crop_id_09a48628" ON "farm_tscondition" ("crop_id");
CREATE INDEX "farm_tscondition_node_id_94d38da4" ON "farm_tscondition" ("node_id");
CREATE INDEX "farm_tscondition_room_id_ce266840" ON "farm_tscondition" ("room_id");
```

The source code of this application is forked and modified a bit (just some strings and DB name) to run as several web instances. When the OOM occured, I don't know which query, in which web instance, resulted in.

Here is the log, collected by `journalctl` around the time the error occured:

[postgresql-oom.log.gz](https://github.com/timescale/timescaledb/files/9082927/postgresql-oom.log.gz)

**Comment by stl-leonid-kalmaev** [comment]
we have the same problem, the database is used for zabbix 6.0

**Comment by jnidzwetzki** [comment]
Hello @stl-leonid-kalmaev,

Thanks for reaching out. Do you have ever faced OOM issues with your database running TimescaleDB 2.7.0? If not, might it also be possible for you to share the table structure, some sample data, and queries that you use? This might help us to reproduce the problem.

**Comment by stl-leonid-kalmaev** [comment]
There were no problems with version 2.7.0, the memory leak started after the upgrade to 2.7.1 
The usual installation with zabbix is used, no additions were made.
[zabbix.schema.gz](https://github.com/timescale/timescaledb/files/9095279/zabbix.schema.gz) 
.

**Comment by jnidzwetzki** [comment]
Hello @stl-leonid-kalmaev,

Thanks for getting back to us. Might it be possible for you to share the last relevant lines from the Syslog/PostgreSQL log that cover the OOM situation?

**Comment by hongquan** [comment]
Thank you @wrobell 
I downgraded TimescaleDB to v2.7.0 to avoid this problem. Our system is serving some farms and I got complaint for disruption. Now things run smoothly again (after downgrading).

**Comment by hongquan** [comment]
@jnidzwetzki Unfortunately, the PostgreSQL log on my server was rotated and delete the part of the day when OOM occurred. Due to my setup, the log is full of "out of background workers" message so it is rotated very fast.

**Comment by svenklemm** [comment]
The backend that was killed was running this query:
```
select distinct
 g.graphid, g.name, g.width, g.height, g.yaxismin, g.yaxismax, g.show_work_period, g.show_triggers, g.graphtype,
 g.show_legend, g.show_3d, g.percent_left, g.percent_right, g.ymin_type, g.ymin_itemid, g.ymax_type, g.ymax_itemid, g.discover
from graphs g,
  graphs_items gi,
  items i,
  item_discovery id
where g.graphid=gi.graphid and gi.itemid=i.itemid and i.itemid=id.itemid and id.parent_itemid=45465;
```

@stl-leonid-kalmaev can you provide EXPLAIN output for that query.

**Comment by victor-sudakov** [comment]
> @stl-leonid-kalmaev can you provide EXPLAIN output for that query.

No problem, please see below. @stl-leonid-kalmaev and I don't think however that this query was the culprit. It was just unlucky to happen when the server was already pressed for memory.

```                                                                                                                           QUERY PLAN                                                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Unique  (cost=54.30..54.40 rows=2 width=124)
   ->  Sort  (cost=54.30..54.31 rows=2 width=124)
         Sort Key: g.graphid, g.name, g.width, g.height, g.yaxismin, g.yaxismax, g.show_work_period, g.show_triggers, g.graphtype, g.show_legend, g.show_3d, g.percent_left, g.percent_right, g.ymin_type, g.ymin_itemid, g.ymax_type, g.ymax_itemid, g.discover
         ->  Nested Loop  (cost=5.18..54.29 rows=2 width=124)
               ->  Nested Loop  (cost=4.89..53.63 rows=2 width=8)
                     ->  Nested Loop  (cost=4.61..52.24 rows=4 width=16)
                           ->  Bitmap Heap Scan on item_discovery id  (cost=4.32..19.02 rows=4 width=8)
                                 Recheck Cond: (parent_itemid = 45465)
                                 ->  Bitmap Index Scan on item_discovery_2  (cost=0.00..4.32 rows=4 width=0)
                                       Index Cond: (parent_itemid = 45465)
                           ->  Index Only Scan using items_pkey on items i  (cost=0.29..8.30 rows=1 width=8)
                                 Index Cond: (itemid = id.itemid)
                     ->  Index Scan using graphs_items_1 on graphs_items gi  (cost=0.29..0.34 rows=1 width=16)
                           Index Cond: (itemid = i.itemid)
               ->  Index Scan using graphs_pkey on graphs g  (cost=0.28..0.33 rows=1 width=124)
                     Index Cond: (graphid = gi.graphid)
(16 rows)

```

**Comment by 3a6u9ka** [comment]
OOM occurs when all available server memory is exhausted. After updating to 2.7.1, the postmaster postgresql process starts eating up all available memory and, as a result, the "OOM Killer" kills the postgresql process. Processes like "postgres: zabbix zabbix 127.0.0.1(56074)" start eating all available memory.
Rollback to version 2.7.0 solves the problem.
This is a graph of memory usage on the server. After the update, all available memory began to be eaten up over time during the operation of the zabbix server with the postgresql database.
Restarting the zabbix server service frees up memory.

![image](https://user-images.githubusercontent.com/33462723/179694065-ecb60064-7c0f-4a4d-b596-220b4f210ad9.png)

![image](https://user-images.githubusercontent.com/33462723/179694811-e13c1175-304a-4992-81c7-31ab7d95c798.png)

**Comment by victor-sudakov** [comment]
> Restarting the zabbix server service frees up memory.

@3a6u9ka  Did you actually mean restarting the zabbix server process, or did you mean restarting postgres?

**Comment by victor-sudakov** [comment]
> @victor-sudakov I mean restarting zabbix server with command: systemctl restart zabbix_server.

And this frees up memory? So it's not the postgres+timescaledb eating up memory but the zabbix server process?

**Comment by 3a6u9ka** [comment]
@victor-sudakov  During zabbix service reboot restarted postmaster processes with command: postgres: zabbix zabbix 127.0.0.1(56074). Seven processes on second image. This process leak all memory in system.

**Comment by victor-sudakov** [comment]
> During zabbix service reboot restarted postmaster processes

OK, I see. Thank you.

**Comment by trooster** [comment]
Same exact problem here with version TimescaleDB 2.7.1 (PostgreSQL 13.7 & Zabbix 5.4).

**Comment by mnordstr** [comment]
> Same exact problem here with version TimescaleDB 2.7.1 (PostgreSQL 13.7 & Zabbix 5.4).

+1, with TS 2.7.1, Postgres 14.4, Zabbix 6.2

I get a little more time when using only one db syncer in Zabbix (StartDBSyncers=1), I guess using only one long-lived connection to Postgres.

**Comment by victor-sudakov** [comment]
> There is a memory leak in our function telemetry. As a temporary workaround you can disable function telemetry like so:
> 
> ```
> ALTER DATABASE <db> SET timescaledb.telemetry_level to no_functions;
> ```

Looks like it has fixed the memory leak for us. What's the downside of this workaround?

**Comment by svenklemm** [comment]
It means you will not send telemetry about function usage to us, no downside other than that.

**Comment by Adi-86** [comment]
> ALTER DATABASE <db> SET timescaledb.telemetry_level to no_functions;

I've got the same issue when I want to upgrade to the primary key in Zabbix datadatabase. But when using this I this error:

ALTER DATABASE zabbix SET timescaledb.telemetry_level to no_functions;                                                                                                            ERROR:  invalid value for parameter "timescaledb.telemetry_level": "no_functions"
HINT:  Available values: off, basic.
