### ISSUE TITLE
Tag 2.5.1 no longer points to a commit that builds 2.5.1

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/timescaledb#4509]
### What type of bug is this?

Other

### What subsystems and features are affected?

Build system

### What happened?

When compiling TimescaleDB from sources using tag `2.5.1`, we end up with `timescaledb-2.6.0-dev.so`

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

all

### What operating system did you use?

NA

### What installation method did you use?

Source

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

Tag 2.5.1 used to point to commit [a2530ab](https://github.com/timescale/timescaledb/commit/a2530ab).
Nowadays, it points to commit [00ad3d8](https://github.com/timescale/timescaledb/commit/00ad3d8), which does not build 2.5.1, and does not to any branch of the this repository.

### How can we reproduce the bug?

```bash
git clone git@github.com:timescale/timescaledb.git /tmp/scratch/
git checkout 2.5.1
grep version version.config 

Output:
version = 2.6.0-dev
update_from_version = 2.5.0
downgrade_to_version = 2.5.0
```

**Comment by splitice** [comment]
Thank you, this broke our builds too!

**Comment by splitice** [comment]
2.5.2 tag is functional FYI

**Comment by svenklemm** [comment]
Thanks for the report this is fixed now.
