### ISSUE TITLE
[Bug]:  Planner chunk exclusion not working in VIEWs

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#4524]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Query planner

### What happened?

When querying a view on a hypertable constraints on dimensions are not used for plan time chunk exclusion. 

### TimescaleDB version affected

main

### PostgreSQL version used

14.4

### What operating system did you use?

Archlinux 2022.07.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
explain SELECT * from v2 where time > now() - '168h'::interval;
                                  QUERY PLAN
-------------------------------------------------------------------------------
 HashAggregate  (cost=4.10..4.15 rows=4 width=18)
   Group Key: metrics."time", metrics.device
   ->  Custom Scan (ChunkAppend) on metrics  (cost=0.00..4.07 rows=4 width=18)
         Chunks excluded during startup: 3
         ->  Seq Scan on _hyper_1_4_chunk  (cost=0.00..1.02 rows=1 width=18)
               Filter: ("time" > (now() - '168:00:00'::interval))
(6 rows)
```

### How can we reproduce the bug?

```bash
create table metrics(time timestamptz,device text, value float);
SELECT create_hypertable('metrics','time');
INSERT INTO metrics select '2000-01-01','a',0.5;
INSERT INTO metrics select '2001-01-01','b',0.5;
INSERT INTO metrics select '2002-01-01','b',0.5;
INSERT INTO metrics select now(),'b',0.5;
CREATE VIEW v2 AS SELECT time, device, avg(value) from metrics group by 1,2;
EXPLAIN SELECT * from v2 where time > now() - '168h'::interval;
```

**Comment by disorder** [comment]
Hi, I've found this issue and tried to upgrade to 2.8.1 but it seems to persist.  I have a hypertable "data" that can be simplified to columns "time" and "count".  Then I make continuous aggregate "data_bucket" that processes these columns to "bucket" (e.g. 5 minutes) and "count" ("sum(count)").  All of the tables has compression enabled.

Now when I run "select min(time) from data;" I can get a result relatively quickly but when I run "select min(bucket) from data_bucket;" it takes a long time.  It seems to be related to exclusion - when I run "explain (costs off) select min(bucket) from data_bucket;" it says and seems to scan every chunk in continuous aggregate but excludes chunks on underlying hypertable:

```
         ->  Subquery Scan on "*SELECT* 1"
               ->  Custom Scan (ChunkAppend) on _materialized_hypertable_17
                     Chunks excluded during startup: 0
...
         ->  Subquery Scan on "*SELECT* 2"
...
                     ->  Custom Scan (ChunkAppend) on data
                           Chunks excluded during startup: 674
```

Any pointers will be appreciated.  This seems to affect more complex queries, rendering them unusably slow.
