### ISSUE TITLE
TABLESAMPLE handling

### ISSUE THREAD

**Issue by captainpete** [timescale/timescaledb#453]
Hi there,

Expected 1,000 rows from below query, ended up with 939,000.
Low-impact, as I can re-sample from returned rows so there is an easy workaround.

```
CREATE EXTENSION tsm_system_rows;
SELECT COUNT(*) FROM events TABLESAMPLE SYSTEM_ROWS(1000);
EXPLAIN SELECT * FROM events TABLESAMPLE SYSTEM_ROWS(1000) ORDER BY t;
```

```
                                       QUERY PLAN
----------------------------------------------------------------------------------------
 Sort  (cost=32241.49..32426.49 rows=74001 width=1072)
   Sort Key: events.t
   ->  Append  (cost=0.00..5959.51 rows=74001 width=1072)
         ->  Sample Scan on events  (cost=0.00..1.11 rows=1 width=1072)
               Sampling: system_rows ('1000'::bigint)
         ->  Sample Scan on _hyper_4_4_chunk  (cost=0.00..27.60 rows=1000 width=1072)
               Sampling: system_rows ('1000'::bigint)
         ->  Sample Scan on _hyper_4_5_chunk  (cost=0.00..27.60 rows=1000 width=1072)
               Sampling: system_rows ('1000'::bigint)
         ->  Sample Scan on _hyper_4_6_chunk  (cost=0.00..27.60 rows=1000 width=1072)
               Sampling: system_rows ('1000'::bigint)
         ->  Sample Scan on _hyper_4_7_chunk  (cost=0.00..27.60 rows=1000 width=1072)
               Sampling: system_rows ('1000'::bigint)
         ->  Sample Scan on _hyper_4_8_chunk  (cost=0.00..27.60 rows=1000 width=1072)
               Sampling: system_rows ('1000'::bigint)
```

**Comment by captainpete** [comment]
From what I can tell, this might be working exactly as expected. Is there a preferred way of sampling across a hypertable?

**Comment by erimatnor** [comment]
Hi @captainpete. Thanks for reporting this issue. Right now we are not doing anything special for `TABLESAMPLE` over what regular PostgreSQL inheritance provides. It seems that PostgreSQL simply recurses the sampling to each subtable, something we certainly might want to think about doing differently.

**Comment by svenklemm** [comment]
Since the builtin tablesample methods all work on fractions they exhibit the correct behaviour on hypertables. For the tsm_system_rows extension that is not true but the returned result is consistent with the result returned for postgres natively partitioned tables.
