### ISSUE TITLE
[Bug]: Unable to upgrade TS 1.7.5 to any newer 2.x version

### ISSUE THREAD

**Issue by croessner** [timescale/timescaledb#4550]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

We use a Zabbix Server with PostgreSQL 12 and TimescaleDB. The system is running on Rocky 8. Packages are automatically updated. Currently we have this:

- postgresql12-12.11-1PGDG.rhel8.x86_64
- postgresql12-contrib-12.11-1PGDG.rhel8.x86_64
- postgresql12-server-12.11-1PGDG.rhel8.x86_64
- timescaledb-postgresql-12-1.7.5-0.el8.x86_64
- timescaledb-2-loader-postgresql-12-2.7.2-0.el8.x86_64

```
su - postgres
Last login: Wed Jul 27 10:53:43 CEST 2022 on pts/0
[postgres@zabbix ~]$ psql -X
psql (14.4, server 12.11)
Type "help" for help.

postgres=# \c zabbix
psql (14.4, server 12.11)
You are now connected to database "zabbix" as user "postgres".
zabbix=# alter extension timescaledb update to '2.0.0';
ERROR:  extension "timescaledb" has no update path from version "1.7.5" to version "2.0.0"
zabbix=# alter extension timescaledb update to '2.0.1';
ERROR:  extension "timescaledb" has no update path from version "1.7.5" to version "2.0.1"
zabbix=# alter extension timescaledb update to '2.0.2';
ERROR:  extension "timescaledb" has no update path from version "1.7.5" to version "2.0.2"
zabbix=# alter extension timescaledb update to '2.1.0';
ERROR:  extension "timescaledb" has no update path from version "1.7.5" to version "2.1.0"

```

```
zabbix=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.7.5   | public     | Enables scalable inserts and complex queries for time-series data

```

No matter what I try, it seems to be impossible to upgrade to version 2. We would need 2.6.1 at the end.

What we wanted to do is upgrade PG12 to PG14 with TimescaleDB-2.6.1. But because we did not recognize that TS was already very old (while auto-updates were installing newer versions...), we can not import the backup from the current PG12/TS1 version into PG14/TS2. So we wanted to upgrade PG12/TS1 to PG12/TS2.6.1 and do a new backup; then restore this on PG14/TS2.6.1. That was the plan ;-)

### TimescaleDB version affected

1.7.5

### PostgreSQL version used

12

### What operating system did you use?

Rocky 8 latest

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Error messages already provided above.
```

### How can we reproduce the bug?

```bash
Using PG12 with TimescaleDB 1.7.5 and try upgrading to newer version.
```

**Comment by svenklemm** [comment]
You need to install the appropriate package to make the upgrade path available. To get the latest version the following will install the package:
```
dnf install timescaledb-2-postgresql-12-2.7.2
```
After installing the package you can run `ALTER EXTENSION timescaledb UPDATE;`
