### ISSUE TITLE
[Bug]: extension "timescaledb" has no update path from version "2.7.2" to version "2.6.1"

### ISSUE THREAD

**Issue by anshibanov** [timescale/timescaledb#4551]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

I want to downgrade timescaledb from 2.7.2 to 2.6 because zabbix can't work with 2.7 ((
When i command in psql
```
extension "timescaledb" has no update path from version "2.7.2" to version "2.6.1"

```
I get error: `extension "timescaledb" has no update path from version "2.7.2" to version "2.6.1"`

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

13

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
Try downgrade from 2.7 to 2.6
```

**Comment by svenklemm** [comment]
This is not supported. Downgrade is only supported to the previous version. So to get from 2.7.2 to 2.6.0 you need to visit every intermediate version. To downgrade you would need to visit these versions in order: 2.7.1 2.7.0 2.6.1 2.6.0

**Comment by rb3198** [comment]
Facing the same issue while trying to downgrade from `2.15.0` to `2.14.2`, despite the fact that these are consecutive versions @svenklemm
