### ISSUE TITLE
[Bug]: Loading hypertable with space dimension on time column causes memory leak

### ISSUE THREAD

**Issue by ninjaltd** [timescale/timescaledb#4560]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

Inserting a moderately sized data set (~30M rows) into a hypertable with a space dimension on a time column seems to trigger a memory leak and cause system to go OOM and kill postgres.

### TimescaleDB version affected

2.7.1

### PostgreSQL version used

14.4

### What operating system did you use?

Debian GNU/Linux 11 (bullseye)

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
-- Create a table with the following schema:

CREATE TABLE public.inet_sessions (
    id bigint NOT NULL,
    auth_log_id integer,
    session_id text,
    unique_id text,
    username text,
    nas_ip text,
    nas_port text,
    calling_station_id text,
    ipaddr text,
    termcause text,
    session_start timestamp without time zone not null,
    session_end timestamp without time zone,
    session_length integer,
    flags integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    service_id integer
);

-- CREATE hypertable as follows. 

SELECT create_hypertable('inet_sessions', 'session_start', 'session_end', 4, chunk_time_interval => INTERVAL '1 month');

-- Load a very large data set in using COPY (30M rows). 

-- Unfortunately I can't share my data set as it's got confidential information in it ...

But if you randomize combinations of session_start and session_end I'd be confident you'd be able to reproduce this.

And of course it's possible what I'm doing isn't supported, but I'd not have expected it to cause this.
```

**Comment by hermanekt** [comment]
Hi,

i have exact same versions like you, im using zabbix 6.2 (unsuported timescaledb in zabbix, can be override in zabbix). I try upgrade extension and this maybe helps, i still need more data for approve this solution:)

Tom

**Comment by hermanekt** [comment]
Hi,

i can confirm bug is fixed in 2.7.2. Great job:)
Thank you
<img width="1328" alt="271vs272" src="https://user-images.githubusercontent.com/10741768/182451175-73bfd58f-23d1-44d6-be57-9e50b7eff40d.png">

**Comment by ninjaltd** [comment]
I can still reproduce OOM with 2.7.2 in slightly different scenario:

TABLE creation:

CREATE TABLE public.inet_session_usages (
    id bigint NOT NULL,
    inet_session_id integer NOT NULL,
    bytes_in bigint,
    bytes_out bigint,
    created_at timestamp with time zone,
    year_created integer,
    month_created integer,
    day_created integer,
    hour_created integer,
    minute_created integer,
    created_at_svc_tz timestamp without time zone
);

HYPERTABLE creation:

SELECT create_hypertable('inet_session_usages', 'created_at_svc_tz', 'inet_session_id', 4, chunk_time_interval => INTERVAL '1 day')

This table is ~300M rows.  Dies pretty quickly on the load.

[z@hadar][~] % ./dbdatasync  
loading inet_session_usages ...
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
invalid socket

**Comment by ninjaltd** [comment]
Can we re-open this please?  Or do you want me to log another bug?
