### ISSUE TITLE
[Bug]: unsupported expression argument node type 112 when calling `_timescaledb_internal.get_partition_hash`

### ISSUE THREAD

**Issue by AlmiS** [timescale/timescaledb#4575]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

When calling the `_timescaledb_internal.get_partition_hash` function from a procedure or immutable function, the query fails with the error message `Query 1 ERROR: ERROR:  unsupported expression argument node type 112`.
I could not find any additional info in the logs.

I initially ran into this bug on 2.7.0 and thought it might be related to: #4489. Therefore i tried upgrading to 2.7.2 where this issue should be fixed, but it seems to not fix this. 

### TimescaleDB version affected

2.7.0 - 2.7.2

### PostgreSQL version used

14.4

### What operating system did you use?

MAC OS 11.6.2

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Query 1 ERROR: ERROR:  unsupported expression argument node type 112
```

### How can we reproduce the bug?

```bash
CREATE OR REPLACE FUNCTION my_function(IN partition_key integer) RETURNS integer
AS 'select _timescaledb_internal.get_partition_hash($1);'
LANGUAGE SQL;

CREATE OR REPLACE FUNCTION my_immutable_function(IN partition_key integer) RETURNS integer
AS 'select _timescaledb_internal.get_partition_hash($1);'
LANGUAGE SQL
IMMUTABLE;

CREATE OR REPLACE PROCEDURE my_procedure(IN partition_key integer)
AS $$
DECLARE
    partition_hash integer; 
BEGIN
	-- Need to do some things based on partition hash
	select _timescaledb_internal.get_partition_hash(partition_key) INTO partition_hash; -- this eventually fails with the unsupported node type error	
END;
$$ LANGUAGE PLPGSQL;

SELECT my_function(1); -- This will not fail
SELECT my_immutable_function(1); -- This will always fail with: Query 1 ERROR: ERROR:  unsupported expression argument node type 112
CALL my_procedure(1); -- This will eventually fail with same error as above
```

**Comment by fabriziomello** [comment]
@AlmiS thanks for reporting... I've provided a fix for it in https://github.com/timescale/timescaledb/pull/4583 that will be shipped in next major or minor release.
