### ISSUE TITLE
[Enhancement]: Make DataNodeScan node Async capable

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4587]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Query executor

### What does the enhancement do?

PostgreSQL 14 introduced support of asynchronous execution of plan nodes. This is useful for foreign scans when a node is waiting on I/O and another part of the plan can be executed instead. For example, when executing an Append plan, the execution can move on to the next node in the append when one is blocked.

In TimescaleDB, similar asynchronous execution is implemented by wrapping the Append node in a custom AsyncAppend node. This is awkward and it is better to adopt the official PG approach since that allows the async support to work better with other PostgreSQL plan nodes.

### Implementation challenges

Asynchronous execution was introduced in PG14, so it might be a challenge to support this in older versions of PG. We might need to keep the AsyncAppend node around until support for all the older versions is removed.

**Comment by erimatnor** [comment]
Another challenge is that PG hard-codes async support to only work with the ForeignScan node, so it doesn't matter if other nodes signal async support.

**Comment by svenklemm** [comment]
multinode has been removed
