### ISSUE TITLE
[Enhancement]: Make DataFetcher more asynchronous

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4588]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Multi-node, Query executor

### What does the enhancement do?

The DataFetcher is responsible for fetching data from remote data nodes (DNs) during query execution. Currently, there are two data fetcher implementations: row-by-row and cursor fetchers. 

While the fetchers are asynchronous in the sense that they start the query on each data node asynchronously, they aren't really asynchronous when they fetch data from a DN. For example, the cursor fetcher fetches batches of tuples from DNs, and when a batch is processed a new request is sent to the DN for more data. But the node is blocking waiting for the next tuple after the FETCH request is sent, which means at least one round-trip.

One idea to improve this is to logically split the batching across two buffers and it can request data for one buffer while processing the data in the other buffer locally. Roughly, it would work like this (assuming a single DN for the sake of the example):

1. Fill both buffers with data
2. Start processing the buffer that is filled first
3. Once the buffer is fully processed (empty) it sends an asynchronous request for new data 
4. Start processing the other buffer
5. Fill the empty buffer as data arrive, interleaving with local processing of the other buffer
6. Repeat from step (3) when a buffer is empty

Would be good to combine this functionality with general async node support in issue https://github.com/timescale/timescaledb/issues/4587

### Implementation challenges

The row-by-row fetcher only sends one initial request for "all" data, so it is unclear how much of a benefit this would be. Still, a socket could still be blocked waiting for more data from a DN.

**Comment by svenklemm** [comment]
multinode has been removed
