### ISSUE TITLE
[Bug]: segfault in shared library

### ISSUE THREAD

**Issue by cstradtman** [timescale/timescaledb#4608]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

while running postgres crashes with
`postgres[19563]: segfault at 1a0 ip 00007fc9124b45b4 sp 00007ffc4891eb20 error 4 in timescaledb-tsl-2.7.2.so[7fc91246f000+8a000]`
haven't been able to correlate it with an action.

### TimescaleDB version affected

2.7.1 and 2.7.2

### PostgreSQL version used

12.12

### What operating system did you use?

Ubuntu 18.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
I'm not sure,  since it just comes and goes while the system is in production, I can't really give any steps.
```

**Comment by mfundul** [comment]
Hello @cstradtman , thank you for reporting this issue! Can you attempt to generate a core dump so that we can retrieve a backtrace from your system? You can follow [these](https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD) instructions.

**Comment by konskov** [comment]
Hi again @cstradtman, any news on this issue? Have you been able to get a coredump in the meantime?
