### ISSUE TITLE
Data Retention Page is disappear

### ISSUE THREAD

**Issue by chaintng** [timescale/timescaledb#463]
I read this docs: https://docs.timescale.com/v0.9/faq

But the link to data-retention cannot be accessed
http://docs.timescale.com/using-timescaledb/data-retention

**Comment by RobAtticus** [comment]
Thanks, we will fix! The correct link should be:
https://docs.timescale.com/latest/using-timescaledb/data-retention

**Comment by RobAtticus** [comment]
Thanks for pointing this out, the docs have been updated and should work. I will close this out.
