### ISSUE TITLE
[Bug]: Could not load library "C:/Program Files/PostgreSQL/13/lib/timescaledb-2.7.2.dll": The specified procedure could not be found.

### ISSUE THREAD

**Issue by Suvitruf** [timescale/timescaledb#4632]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Can't enable extension.

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

13.1

### What operating system did you use?

Windows 10

### What installation method did you use?

Zip installer.

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
Could not load library  "C:/Program Files/PostgreSQL/13/lib/timescaledb-2.7.2.dll": The specified procedure could not be found.
```

### How can we reproduce the bug?

1. Postgres 13 installed
2. Install Timescale https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-13_latest-windows-amd64.zip
3. Call `CREATE EXTENSION IF NOT EXISTS timescaledb;`
4. Error: Could not load library "C:/Program Files/PostgreSQL/13/lib/timescaledb-2.7.2.dll": The specified procedure could not be found.

**Comment by mfundul** [comment]
Thank you for reporting this issue. Can you share your Windows Environment Variables and the contents of the `C:/Program Files/PostgreSQL/` folder?

**Comment by Suvitruf** [comment]
> Thank you for reporting this issue. Can you share your Windows Environment Variables and the contents of the `C:/Program Files/PostgreSQL/` folder?

envs:

```
PS C:\Users\Suvitruf> Get-ChildItem Env: | Format-Table -Wrap -AutoSize

Name                      Value
----                      -----
ALLUSERSPROFILE           C:\ProgramData
APPDATA                   C:\Users\Suvitruf\AppData\Roaming
AV_APPDATA                C:\Users\Suvitruf\AppData\Roaming
ChocolateyInstall         C:\ProgramData\chocolatey
ChocolateyLastPathUpdate  132540660323089246
CommonProgramFiles        C:\Program Files\Common Files
CommonProgramFiles(x86)   C:\Program Files (x86)\Common Files
CommonProgramW6432        C:\Program Files\Common Files
COMPUTERNAME              DESKTOP-2KRIA7K
ComSpec                   C:\WINDOWS\system32\cmd.exe
DriverData                C:\Windows\System32\Drivers\DriverData
HOMEDRIVE                 C:
HOMEPATH                  \Users\Suvitruf
LOCALAPPDATA              C:\Users\Suvitruf\AppData\Local
LOGONSERVER               \\DESKTOP-2KRIA7K
NUMBER_OF_PROCESSORS      24
OneDrive                  C:\Users\Suvitruf\OneDrive
OneDriveConsumer          C:\Users\Suvitruf\OneDrive
OPENSSL_CONF              C:\Program Files\PostgreSQL\psqlODBC\etc\openssl.cnf
OS                        Windows_NT
Path                      C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\bin;C:\Users\Suvitruf\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Suvitruf\AppData\Local\Programs\Python\Python37;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\
                          ProgramData\chocolatey\bin;C:\Program Files\PostgreSQL\13\bin;C:\Program Files\Git\cmd;C:\Python27;C:\Program Files\nginx-1.18.0;C:\Program Files\Aladdin\eToken\PKIClient\x32;C:\Program Files\Aladdin\eToken\PKIClient\x64;C:\Program Files\dotnet\;C:\GTK3-Runtime-Win64\bin;D:\programs\install\DS4;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOW
                          S\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Blender 3.0.0;C:\Program Files\WireGuard\;C:\Program Files\PostgreSQL\13\bin;D:\programs\installed\dependencies;C:\Users\Suvitruf\.windows-build-tools\python27\;C:\Users\Suvitruf\AppData\Local\Microsoft\Win
                          dowsApps;C:\Users\Suvitruf\AppData\Roaming\npm;C:\Users\Suvitruf\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Suvitruf\.dotnet\tools;C:\Users\Suvitruf\AppData\Local\Microsoft\WindowsApps;
PATHEXT                   .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
PGCLIENTENCODING          UTF8
PROCESSOR_ARCHITECTURE    AMD64
PROCESSOR_IDENTIFIER      AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL           25
PROCESSOR_REVISION        2100
ProgramData               C:\ProgramData
ProgramFiles              C:\Program Files
ProgramFiles(x86)         C:\Program Files (x86)
ProgramW6432              C:\Program Files
PSModulePath              C:\Users\Suvitruf\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                    C:\Users\Public
SESSIONNAME               Console
SystemDrive               C:
SystemRoot                C:\WINDOWS
TEMP                      C:\Users\Suvitruf\AppData\Local\Temp
TMP                       C:\Users\Suvitruf\AppData\Local\Temp
USERDOMAIN                DESKTOP-2KRIA7K
USERDOMAIN_ROAMINGPROFILE DESKTOP-2KRIA7K
USERNAME                  Suvitruf
USERPROFILE               C:\Users\Suvitruf
windir                    C:\WINDOWS
```

C:/Program Files/PostgreSQL/
![explorer_crBOueXWix](https://user-images.githubusercontent.com/1946939/185438040-a0106da2-fd42-496e-bd86-5f7fffebc7cf.png)

C:/Program Files/PostgreSQL/13
![explorer_mvMV0yh3L4](https://user-images.githubusercontent.com/1946939/185438033-e46f6554-1f9f-410b-b9bf-3ddc67c15f11.png)

**Comment by mfundul** [comment]
I will attempt to reproduce the issue, one suspicion I have is that PG 13.1 is too old, and that the binary you installed is only compatible with PG 13.8. In that case, you would need to recompile timescaledb from source or upgrade your postgresql version. This is still a theory at this point though.

**Comment by mfundul** [comment]
Ok, so I've verified with @svenklemm that the minimum supported version for PostgreSQL 13 is 13.2, and you need to upgrade to the latest PG13 version, or try another suggestion from my previous post.

**Comment by Suvitruf** [comment]
> Ok, so I've verified with @svenklemm that the minimum supported version for PostgreSQL 13 is 13.2, and you need to upgrade to the latest PG13 version, or try another suggestion from my previous post.

Updated Postgres to 13.8 and timescale extension installed without any problem. Thanks.

Would be nice to mention info about min Postgres version in the docs)
