### ISSUE TITLE
XX000: SubPlan found with no parent plan

### ISSUE THREAD

**Issue by mwahlhuetter** [timescale/timescaledb#4640]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

When inserting into a hypertable with a `RETURNING` clause, using a subselect that references another table and the hypertable itself, the error 
```
ERROR:  SubPlan found with no parent plan
SQL state: XX000
```
is raised.

A practical occurence of the error is described in this issue hasura/graphql-engine#8234

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.4

### What operating system did you use?

Debian 10.2.1-6 20210110, 64-bit

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE standard_table (
	standard_id integer PRIMARY KEY,
	name text not null
);

CREATE TABLE hypertable (
    time timestamptz not null,
    name text not null,
	standard_id integer not null REFERENCES standard_table (standard_id)
);

select * from create_hypertable('hypertable', 'time');

INSERT INTO standard_table (standard_id, name)
VALUES (1, 'standard_1');

INSERT INTO hypertable (time, name, standard_id)
VALUES (now(), 'hypertable_1', 1);
	
-- this insert throws an error
-- ERROR:  SubPlan found with no parent plan
-- SQL state: XX000
INSERT INTO hypertable (time, name, standard_id)
VALUES (now(), 'hypertable_2', 1)
RETURNING *, EXISTS (
  SELECT *
  FROM standard_table
  WHERE standard_table.standard_id = hypertable.standard_id
);
```

**Comment by akuzm** [comment]
Thanks for reporting! Can confirm that it reproduces with the given script.

**Comment by mwahlhuetter** [comment]
Thank you very much for the super fast resolving of this issue!
