### ISSUE TITLE
[Bug]: OOM on large copy/selects

### ISSUE THREAD

**Issue by mrksngl** [timescale/timescaledb#4657]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Access node

### What happened?

When selecting a huge dataset using `COPY (SELECT * FROM …) TO STDOUT (FORMAT BINARY)`, the access node uses a very large amount of memory, finally running into an OOM condition.

I guess there is a relation on how much chunks of a hypertable are involved:
 * in one hypertable, I have a total of 850GiB (this is the size when dumping binary data). It used an unexpectedly high amount of memory but finished the job and released memory afterwards.
 * for a second hypertable, memory consumption was rising much faster, hitting the memory limit (of 50GiB, btw) after writing out only some 250GiB to stdout.

Both tables have the same chunk time interval and are both partitioned by time and space.
Difference is, that the second hypertable has way less data per chunk (about 1/10 compared to the first).
This means, that after writing those 250GiB, it already accessed way more chunks than when writing out all those 850GiB of the first table.

This might be related to #4576 which was fixed in #4611. On the other hand, the issue and also the fix only mention inserts.

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

14.4

### What operating system did you use?

Ubuntu 18.04 (Spilo Docker Image)

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

1) put lots of data in a (distributed, idk?) hypertable. Maybe the data of #4576 will do.
2) Use a `COPY (SELECT * FROM ...) TO STDOUT (FORMAT BINARY)` to read the whole table.

The effect can be aggravated when reading lots of chunks in a small time, i.e. you could use a small chunk time interval.

**Comment by konskov** [comment]
Hi @mrksngl, thank you for reporting this. We believe that this also will be addressed by #4611 which will be included in the upcoming release

**Comment by konskov** [comment]
Closing this issue for now, please revisit this once 2.8.0 is released to let us know if it persists then 🙏

**Comment by mrksngl** [comment]
Will do. Looking forward for the release.

**Comment by mrksngl** [comment]
Copied some 1.1TiB of one of the databases that made trouble. Memory of the access node (actually of all nodes) stayed very calm, so it seems to be fixed.
