### ISSUE TITLE
UPSERT in CTE causes error/crash

### ISSUE THREAD

**Issue by jgranstrom** [timescale/timescaledb#468]
Doing an upsert with `INSERT ... ON CONFLICT ...` on a hypertable works well for basic queries but fails when inside a common table expression.

Tested with:
- timescale 0.6, pg 9.5
- timescale 0.8, pg 10
- timescale 0.9, pg 10.3

All using the official docker images.

Same symptoms for all tested versions, data or no data, fresh table or old table, and for `DO NOTHING` and `DO UPDATE` respectively.

To reproduce:

```sql
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- create table
CREATE TABLE IF NOT EXISTS test_hyper (
   metric_id int not null,
   time timestamptz not null,
   value numeric not null
);

-- create hypertable and unique index
select create_hypertable('test_hyper', 'time');
create unique index test_index on test_hyper(metric_id, time DESC);

-- Case 1: insert cte using unique index inference for conflict target
---> ERROR:  unexpected failure to find arbiter index
with insert_cte as (
  insert into test_hyper(metric_id, time, value)
  values (1, NOW(), 0)
  on conflict (metric_id, time) do nothing
)
select 1;

-- Case 2: insert cte without specified conflict target
---> Server crashes!
with insert_cte as (
  insert into test_hyper(metric_id, time, value)
  values (1, NOW(), 0)
  on conflict do nothing
)
select 1;
```

Specifying constrained columns results in `unexpected failure to find arbiter index`. Leaving it out for `DO NOTHING` seems to cause a segmentation fault, query process ends with exit code `11`.

**Comment by erimatnor** [comment]
@jgranstrom thanks for the really useful bug report. Working on the issue now.

**Comment by RobAtticus** [comment]
Thanks @jgranstrom , this should be fixed in the just released 0.9.1. Let us know if it isn't, otherwise feel free to close.

**Comment by jgranstrom** [comment]
I just tested with 0.9.1 and the issue is definitely resolved. Thank you!

**Comment by saosebastiao** [comment]
Hello, currently I am experiencing this exact error with postgres 11 and timescaledb 1.1.1. Is there a chance this fix was missed for different versions?

**Comment by gajus** [comment]
Same issue. Server keeps crashing with

> unexpected failure to find arbiter index

error.

Here is the actual error/ query:

https://gist.github.com/gajus/fb71ae081c0d6bbc67eace89d101e151#file-index_error-sql-L1

**Comment by mfreed** [comment]
https://github.com/timescale/timescaledb/pull/1018

**Comment by mfreed** [comment]
Update:  PR to fix has been merged in https://github.com/timescale/timescaledb/pull/1026. 

Has been released as part of version https://github.com/timescale/timescaledb/releases/tag/1.2.0

**Comment by mfreed** [comment]
I'm going to close out this issue given the above emoji's, but please feel free to re-open if this was in fact not fixed.
