### ISSUE TITLE
[Bug]: Cannot create Caggs from procedure

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/timescaledb#4697]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I was developing a PLPGSQL procedure to loop over a table and create Caggs (on other hypertables) from the entries. On running the procedure, I receive `ERROR: CREATE MATERIALIZED VIEW ... WITH DATA cannot be executed from a function` as error. But, if I create a plain `MATERIALIZED VIEW` (i.e., without the `WITH (timescaledb.continuous)`), it works fine.

I expect the behaviour to allow creating Caggs in Procedures.

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.5

### What operating system did you use?

Mac OS 12.5.1

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
2022-09-13 07:39:31.803 UTC [1773] CONTEXT:  PL/pgSQL function _prom_catalog.test_temp(text,text,interval) line 3 at SQL statement
2022-09-13 07:39:31.803 UTC [1773] STATEMENT:  call _prom_catalog.test_temp('test', 'go_goroutines', '5 minute'::interval)
2022-09-13 07:42:19.898 UTC [1778] ERROR:  CREATE MATERIALIZED VIEW ... WITH DATA cannot be executed from a function
2022-09-13 07:42:19.898 UTC [1778] CONTEXT:  SQL statement "CREATE MATERIALIZED VIEW test.go_goroutines WITH (timescaledb.continuous, timescaledb.materialized_only=true, timescaledb.compress=true) AS
```

### How can we reproduce the bug?

```bash
This was my Caggs query


CREATE OR REPLACE PROCEDURE _prom_catalog.test(rollup_schema TEXT, table_name TEXT, resolution INTERVAL)
  AS
$$
  BEGIN
    CREATE MATERIALIZED VIEW test.go_goroutines WITH (timescaledb.continuous, timescaledb.materialized_only=true, timescaledb.compress=true) AS
    SELECT
      timezone(
          'UTC',
          time_bucket('5 minute'::interval, time) AT TIME ZONE 'UTC' + '5 minute'::interval
        ) as time,
      series_id,
      sum(value) as sum,
      count(value) as count,
      min(value) as min,
      max(value) as max
    FROM prom_data.go_goroutines
    GROUP BY 1, 2;
  END
$$
LANGUAGE plpgsql;
```

**Comment by cevian** [comment]
I think the solution here is to change
```
if (!stmt->into->skipData)
			PreventInTransactionBlock(args->context == PROCESS_UTILITY_TOPLEVEL,
									  "CREATE MATERIALIZED VIEW ... WITH DATA");
```
(in process_create_table_as) to
```
		if (!stmt->into->skipData)
			PreventInTransactionBlock((args->context == PROCESS_UTILITY_TOPLEVEL || args->context == PROCESS_UTILITY_QUERY_NONATOMIC) && !IsTransactionBlock(),
									  "CREATE MATERIALIZED VIEW ... WITH DATA");
```
(inspired by isAtomicContext in standard_ProcessUtility)
