### ISSUE TITLE
[Bug]: Bulk insert fails

### ISSUE THREAD

**Issue by mrksngl** [timescale/timescaledb#4728]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Data ingestion, Distributed hypertable, Multi-node

### What happened?

When checking whether #4576 is solved with 2.8.0, I got a new error when having a distributed setup.

I set up an access node and a single data node using the `timescaledb:2.8.0-pg14` docker image.
I copy the same data that were used by the author of the issue referenced above. The only thing I changed is to use a distributed hypertable.

I experienced one of the following two situations:
 * Either the COPY does not fail but is painfully slow. It completely stalls now and then and in the end takes 4x the time needed compared to copying the same data in a non-distributed ht.
 * Or (this actually happens way more often) it transfers all data to the access node but then terminates the connection with the message below.

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.5

### What operating system did you use?

timescaledb:2.8.0-pg14 docker image

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
ERROR:  XX000: epoll_ctl() failed: Operation not permitted
LOCATION:  WaitEventAdjustEpoll, latch.c:1083
WARNING:  01000: AbortTransaction while in ABORT state
LOCATION:  AbortTransaction, xact.c:2681
WARNING:  01000: transaction rollback on data node "dn0" failed
LOCATION:  dist_txn_xact_callback_abort, dist_txn.c:182
ERROR:  XX000: epoll_ctl() failed: Operation not permitted
LOCATION:  WaitEventAdjustEpoll, latch.c:1083
ERROR:  XX000: epoll_ctl() failed: Operation not permitted
LOCATION:  WaitEventAdjustEpoll, latch.c:1083
Time: 32905,319 ms (00:32,905)
ERROR:  42P01: relation "public.inet_session_usages_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.inet_session_usages_id_seq'...
                                 ^
LOCATION:  RangeVarGetRelidExtended, namespace.c:428
Time: 7,981 ms
```

### How can we reproduce the bug?

```bash
CREATE DATABASE test;
\c test
CREATE TABLE inet_session_usages (
    id bigint NOT NULL,
    inet_session_id integer NOT NULL,
    bytes_in bigint,
    bytes_out bigint,
    created_at timestamp with time zone,
    year_created integer,
    month_created integer,
    day_created integer,
    hour_created integer,
    minute_created integer,
    created_at_svc_tz timestamp without time zone
);
SELECT add_data_node('dn0', '172.17.0.3'); -- change as needed
SELECT create_distributed_hypertable('inet_session_usages', 'created_at_svc_tz', chunk_time_interval => INTERVAL '1 day');
create unique index inet_session_usages_session_id_idx on inet_session_usages (created_at_svc_tz DESC, inet_session_id);

# change address/credentials as needed
wget -O - https://tyl.spirit.net.au/~z/inet_session_usages.sql.xz | xz -d - | psql -h 172.17.0.2 -U postgres test
```

**Comment by mrksngl** [comment]
Note: the last error `42P01: relation "public.inet_session_usages_id_seq" does not exist` is not related to this bug, it is rather something wrong with the input data or schema.

I actually tested with another dataset.
But the dataset used in the issue is good enough for provoking that `epoll_ctl` error.

**Comment by akuzm** [comment]
The tentative fix was added here https://github.com/timescale/timescaledb/pull/4671, but we still need to add proper tests for this.
