### ISSUE TITLE
How to build docker images with additional extensions like plpython

### ISSUE THREAD

**Issue by thaxy** [timescale/timescaledb#473]
Hello,

I am looking for a way to install the ``plpython`` extension to the ``timescaledb`` docker image. Unfortunately, I am a bit lost here. I cannot find the ``Dockerfile`` inside this repository.

I can only find already compiled version of ``postgres`` including ``plpython``, but without ``timescaledb``.

I am really stuck here and would appreciate a point in the right direction.

**Comment by RobAtticus** [comment]
Hey @thaxy , our Dockerfile is located in this repo:
https://github.com/timescale/timescaledb-docker

I think you can use that to build a version with `plpython` in a similar to the way we built it with timescaledb+postgis (see `postgis` directory in that repo)

**Comment by thaxy** [comment]
I have added the extension to my docker image. 

```
FROM timescale/timescaledb:0.9.0-pg10

RUN apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing \
    python3 \
    postgresql-plpython3
```
When I try to add the extension with:
```
postgres=# CREATE EXTENSION plpython3u;
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/plpython3u.control": No such file or directory
```

Bu when I search for the files I can find them within a different directory:
```
/ # find / -name '*plpy*'
/usr/lib/postgresql/plpython3.so
/usr/share/postgresql/extension/plpython3u.control
/usr/share/postgresql/extension/plpython3u--1.0.sql
/usr/share/postgresql/extension/plpython3u--unpackaged--1.0.sql
```

I guess I am really close.

**Comment by familywald** [comment]
Just create a symlink in your Dockerfile.  Should do the trick.

RUN ln -s source target
