### ISSUE TITLE
[Bug]:  Cannot assign owner of hypertable in cloud 

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#4750]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

On cloud, tsdbadmin cannot assign ownership of it's own hypertable to a user it created. The error is `ERROR:  permission denied for schema _timescaledb_internal`

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.5

### What operating system did you use?

Cloud

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```bash
tsdb=> create role test_role1;
CREATE ROLE
tsdb=> grant  test_role1 to tsdbadmin;
GRANT ROLE
tsdb=> create table test5(t timestamptz);
CREATE TABLE
tsdb=> select create_hypertable('test5', 't');
NOTICE:  adding not-null constraint to column "t"
DETAIL:  Time dimensions cannot have NULL values.
 create_hypertable
--------------------
 (8,public,test5,t)
(1 row)

tsdb=> insert into test5 values (now());
INSERT 0 1
tsdb=> alter table test5 owner to test_role1;
ERROR:  permission denied for schema _timescaledb_internal
```

The underlying cause is that to grant ownership of table T in schema S to user U, U needs CREATE permission on S.
But in cloud newly created users don't get CREATE permissions on  _timescaledb_internal. The perms are:
```
 _timescaledb_internal    | postgres  | postgres=UC/postgres    +|
                          |           | tsdbadmin=UC/postgres   +|
                          |           | =U/postgres             +|
```

Please note that test_role1 can create a new hypertable just fine and even get its chunks put into _timescaledb_internal (even though those create permissions are missing. Those chunks end up being owned by  test_role1 .
```

**Comment by svenklemm** [comment]
Hmm this sounds like an issue with the permission setup on cloud then and not an issue with timescaledb.
