### ISSUE TITLE
[Feature]: Forcefully remove data nodes

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#4752]
### What problem does the new feature solve?

We currently don't allow forcefully removing data nodes when it would lead to permanent data loss. This is to prevent accidental data corruption of distributed hypertables. However, there are situations where removing a data node is necessary even if data loss would occur. For example, the data node was lost and the distributed hypertable needs to be dropped on the data node to clean up the data. There might be other tables in the database (on the access node) that are still valid (including regular PG tables), so dropping the whole DB is not an option in those circumstances.

### What does the feature do?

It allows cleaning up metadata on the access node even though a data node is lost.

### Implementation challenges

There's already a "force" option in `delete_data_node()`, but it allows forceful removal only when losing replica chunks but there are still enough replicas to retain a complete data set. We might need to redefine (or expand) the semantics of this option, introduce another option, or have a GUC that allows more dangerous forceful removal. The latter is a problematic solution as the behavior of `delete_data_node()` would change depending on the setting of this GUC, which can be confusing.

**Comment by malikkirchner** [comment]
That would be very helpful. We canceled the contract for a data node and now we cannot manage the distributed tables anymore. Data loss is not a real problem to us, because we can re-populate the table from dumps. The current 'fix' of copying everything to a new DB is quite annoying.

**Comment by svenklemm** [comment]
multinode has been removed
