### ISSUE TITLE
Retention Policy Not working

### ISSUE THREAD

**Issue by abgarg2022** [timescale/timescaledb#4753]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Policy

### What happened?

Below are the available chunks
        start_ts        |         end_ts         |    chunk_name    | range_start_integer | range_end_integer | is_compressed
------------------------+------------------------+------------------+---------------------+-------------------+---------------
 2022-07-28 00:00:00+00 | 2022-08-04 00:00:00+00 | _hyper_1_2_chunk |       1658966400000 |     1659571200000 | t
 2022-08-25 00:00:00+00 | 2022-09-01 00:00:00+00 | _hyper_1_1_chunk |       1661385600000 |     1661990400000 | t
 2022-09-01 00:00:00+00 | 2022-09-08 00:00:00+00 | _hyper_1_5_chunk |       1661990400000 |     1662595200000 | t
 2022-09-08 00:00:00+00 | 2022-09-15 00:00:00+00 | _hyper_1_6_chunk |       1662595200000 |     1663200000000 | t
 2022-09-15 00:00:00+00 | 2022-09-22 00:00:00+00 | _hyper_1_7_chunk |       1663200000000 |     1663804800000 | f
 2022-09-22 00:00:00+00 | 2022-09-29 00:00:00+00 | _hyper_1_8_chunk |       1663804800000 |     1664409600000 | f

When executed Retention Policy setup as below
 job_id |     application_name      | schedule_interval | max_runtime | max_retries | retry_period |      proc_schema      |     proc_name      |  owner   | scheduled |                         config                         |          next_start           | hypertable_schema | hypertable_name
--------+---------------------------+-------------------+-------------+-------------+--------------+-----------------------+--------------------+----------+-----------+--------------------------------------------------------+-------------------------------+-------------------+-----------------
   1003 | Retention Policy [1003]   | 1 day             | 00:05:00    |          -1 | 00:05:00     | _timescaledb_internal | policy_retention   | postgres | t         | {"drop_after": 1663007399000, "hypertable_id": 1}      | 2022-09-27 08:01:12.762937+00 | public            | ab_xy
(4 rows)

Expection is that all chunks prior to 14 days interval will be dropped. But this is not happening. Please guide.

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

12

### What operating system did you use?

Ubuntu 22.04 LTS

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Status of Jobs

 hypertable_schema | hypertable_name | job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
-------------------+-----------------+--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------

 public            | ab_xy           |   1000 | 2022-09-25 18:50:34.251609+00 | -infinity                     | Failed          | Scheduled  | 00:00:00.011593   | 2022-09-26 15:46:49.263202+00 |         48 |               0 |             48
```

**Comment by svenklemm** [comment]
Seems like your retention policy never actually had a successful run. Can you check the postgres log for any failures?

**Comment by abgarg2022** [comment]
> Seems like your retention policy never actually had a successful run. Can you check the postgres log for any failures?

Latest Run logs

 hypertable_schema | hypertable_name | job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
-------------------+-----------------+--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------
public            | ab_xy           |   1003 | 2022-09-26 08:44:00.000651+00 | 2022-09-26 08:44:00.008839+00 | Success         | Scheduled  | 00:00:00.008188   | 2022-09-27 08:44:00.008839+00 |          2 |               2 |              0

**Comment by abgarg2022** [comment]
Enabled logs now

2022-09-26 15:40:59.546 UTC,"postgres","ioc",1146978,"[local]",6331c7fc.118062,1,"CALL",2022-09-26 15:40:44 UTC,22/25,0,DEBUG,00000,"Executing policy_retention with parameters {""drop_after"": 1663007399000, ""hypertable_id"": 1}",,,,,,"call run_job(1003);",,,"psql"
2022-09-26 15:40:59.546 UTC,"postgres","ioc",1146978,"[local]",6331c7fc.118062,2,"CALL",2022-09-26 15:40:44 UTC,22/25,0,DEBUG,00000,"rehashing catalog cache id 35 for pg_namespace; 9 tups, 4 buckets",,,,,,"call run_job(1003);",,,"psql"
2022-09-26 15:41:01.543 UTC,,,1146881,,6331c7b6.118001,184,,2022-09-26 15:39:34 UTC,,0,DEBUG,00000,"received inquiry for database 0",,,,,,,,,""
2022-09-26 15:41:01.543 UTC,,,1146881,,6331c7b6.118001,185,,2022-09-26 15:39:34 UTC,,0,DEBUG,00000,"writing stats file ""/var/run/postgresql/12-main.pg_stat_tmp/global.stat""",,,,,,,,,""
2022-09-26 15:41:01.543 UTC,,,1146881,,6331c7b6.118001,186,,2022-09-26 15:39:34 UTC,,0,DEBUG,00000,"writing stats file ""/var/run/postgresql/12-main.pg_stat_tmp/db_0.stat""",,,


Status post Job run still the same:

        start_ts        |         end_ts         | hypertable_name |    chunk_name    | range_start_integer | range_end_integer | is_compressed
------------------------+------------------------+-----------------+------------------+---------------------+-------------------+---------------
 2022-07-28 00:00:00+00 | 2022-08-04 00:00:00+00 | ab_xy           | _hyper_1_2_chunk |       1658966400000 |     1659571200000 | t
 2022-08-25 00:00:00+00 | 2022-09-01 00:00:00+00 | ab_xy           | _hyper_1_1_chunk |       1661385600000 |     1661990400000 | t
 2022-09-01 00:00:00+00 | 2022-09-08 00:00:00+00 | ab_xy           | _hyper_1_5_chunk |       1661990400000 |     1662595200000 | t
 2022-09-08 00:00:00+00 | 2022-09-15 00:00:00+00 | ab_xy           | _hyper_1_6_chunk |       1662595200000 |     1663200000000 | t
 2022-09-15 00:00:00+00 | 2022-09-22 00:00:00+00 | ab_xy          | _hyper_1_7_chunk |       1663200000000 |     1663804800000 | f
 2022-09-22 00:00:00+00 | 2022-09-29 00:00:00+00 | ab_xy           | _hyper_1_8_chunk |       1663804800000 |     1664409600000 | f

**Comment by abgarg2022** [comment]
@svenklemm , can you please guide.

**Comment by svenklemm** [comment]
Can you post the output of:
```
SELECT * from timescaledb_information.jobs;
SELECT * from timescaledb_information.job_stats;
```

**Comment by abgarg2022** [comment]
@svenklemm 
Please find details as follows:

SELECT * from timescaledb_information.jobs;
 job_id |     application_name      | schedule_interval | max_runtime | max_retries | retry_period |      proc_schema      |     proc_name      |  owner   | scheduled |                         config                         |          next_start           | hypertable_schema | hypertable_name
--------+---------------------------+-------------------+-------------+-------------+--------------+-----------------------+--------------------+----------+-----------+--------------------------------------------------------+-------------------------------+-------------------+-----------------
      1 | Telemetry Reporter [1]    | 24:00:00          | 00:01:40    |          -1 | 01:00:00     | _timescaledb_internal | policy_telemetry   | postgres | t         |                                                        | 2022-09-29 20:35:16.285359+00 |                   |
   1002 | Reorder Policy [1002]     | 4 days            | 00:00:00    |          -1 | 00:05:00     | _timescaledb_internal | policy_reorder     | postgres | t         | {"index_name": "ts_kv_dev_ts_idx", "hypertable_id": 1} | 2022-09-30 09:54:19.076429+00 | public            | ts_kv
   1000 | Compression Policy [1000] | 1 day             | 00:00:00    |          -1 | 01:00:00     | _timescaledb_internal | policy_compression | postgres | t         | {"hypertable_id": 1, "compress_after": 1663352999000}  | 2022-09-29 08:40:00.044781+00 | public            | ts_kv
   1003 | Retention Policy [1003]   | 1 day             | 00:05:00    |          -1 | 00:05:00     | _timescaledb_internal | policy_retention   | postgres | t         | {"drop_after": 1663007399000, "hypertable_id": 1}      | 2022-09-29 15:34:00.04324+00  | public            | ts_kv
(4 rows)


SELECT * from timescaledb_information.job_stats;
 hypertable_schema | hypertable_name | job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
-------------------+-----------------+--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------
 public            | ts_kv           |   1000 | 2022-09-28 08:40:00.031013+00 | 2022-09-28 08:40:00.044781+00 | Success         | Scheduled  | 00:00:00.013768   | 2022-09-29 08:40:00.044781+00 |         51 |               3 |             48
 public            | ts_kv           |   1003 | 2022-09-28 15:34:00.034398+00 | 2022-09-28 15:34:00.04324+00  | Success         | Scheduled  | 00:00:00.008842   | 2022-09-29 15:34:00.04324+00  |          5 |               5 |              0
 public            | ts_kv           |   1002 | 2022-09-26 09:54:19.068836+00 | 2022-09-26 09:54:19.076429+00 | Success         | Scheduled  | 00:00:00.007593   | 2022-09-30 09:54:19.076429+00 |         10 |              10 |              0
                   |                 |      1 | 2022-09-28 20:35:15.948639+00 | 2022-09-28 20:35:16.285359+00 | Success         | Scheduled  | 00:00:00.33672    | 2022-09-29 20:35:16.285359+00 |         46 |              46 |              0
(4 rows)

**Comment by svenklemm** [comment]
Your retention policy is for the hypertable `ts_kv` and you have no retention policy for the hypertable `ab_xy`.

**Comment by abgarg2022** [comment]
> Your retention policy is for the hypertable `ts_kv` and you have no retention policy for the hypertable `ab_xy`.

@svenklemm 
Earlier was from test database, latest details from Prod database shared now(ts_kv).

**Comment by svenklemm** [comment]
Can you share `SELECT * FROM timescaledb_information.chunks WHERE hypertable_name='ts_kv';`

**Comment by abgarg2022** [comment]
> SELECT * FROM timescaledb_information.chunks WHERE hypertable_name='ts_kv';

@svenklemm 

Here you go :

 hypertable_schema | hypertable_name |     chunk_schema      |    chunk_name     | primary_dimension | primary_dimension_type | range_start | range_end | range_start_integer | range_end_integer | is_compressed | chunk_tablespace | data_nodes
-------------------+-----------------+-----------------------+-------------------+-------------------+------------------------+-------------+-----------+---------------------+-------------------+---------------+------------------+------------
 public            | ts_kv           | _timescaledb_internal | _hyper_1_1_chunk  | ts                | bigint                 |             |           |       1661385600000 |     1661990400000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_2_chunk  | ts                | bigint                 |             |           |       1658966400000 |     1659571200000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_3_chunk  | ts                | bigint                 |             |           |       1638403200000 |     1639008000000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_4_chunk  | ts                | bigint                 |             |           |          1209600000 |        1814400000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_5_chunk  | ts                | bigint                 |             |           |       1661990400000 |     1662595200000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_6_chunk  | ts                | bigint                 |             |           |       1662595200000 |     1663200000000 | t             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_7_chunk  | ts                | bigint                 |             |           |       1663200000000 |     1663804800000 | f             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_8_chunk  | ts                | bigint                 |             |           |       1663804800000 |     1664409600000 | f             |                  |
 public            | ts_kv           | _timescaledb_internal | _hyper_1_15_chunk | ts                | bigint                 |             |           |       1664409600000 |     1665014400000 | f             |                  |
(9 rows)

**Comment by svenklemm** [comment]
Did you configure an integer_now function for that hypertable? https://docs.timescale.com/api/latest/hypertable/set_integer_now_func/#set-integer-now-func

**Comment by abgarg2022** [comment]
> Did you configure an integer_now function for that hypertable? https://docs.timescale.com/api/latest/hypertable/set_integer_now_func/#set-integer-now-func

@svenklemm 

Yes, it exists.

ioc=# \df unix_now
                         List of functions
 Schema |   Name   | Result data type | Argument data types | Type
--------+----------+------------------+---------------------+------
 public | unix_now | bigint           |                     | func
(1 row)

**Comment by abgarg2022** [comment]
Since no followup has been received, closing this.
