### ISSUE TITLE
[Bug]: Error column "chunk_time_interval" does not exist

### ISSUE THREAD

**Issue by Katikatikou** [timescale/timescaledb#4755]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable

### What happened?

Hello, 

We want to study TimescaleDB as a replacement for influxDB, I pulled the timescaledb-ha latest from docker, the timescaledb version is 2.8.0 and postgres version is 14.5.

I ran the three following commands : 

` CREATE TABLE machines (id SERIAL PRIMARY KEY, type TEXT NOT NULL);
CREATE TABLE cpu_data (time TIMESTAMPTZ NOT NULL, machine_id INTEGER REFERENCES machines (id),  value DOUBLE PRECISION );
SELECT create_hypertable('cpu_data', 'time', if_not_exists => TRUE, chunk_time_interval ==> INTERVAL '1 day');`

I am getting the following error 

ERROR:  column "chunk_time_interval" does not exist
LINE 1: ...rtable('cpu_data', 'time', if_not_exists => TRUE, chunk_time...

Do you know if I did anything wrong? 

Thanks in advance for your help
Salah

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.5

### What operating system did you use?

Ubuntu 14.5-1

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
example=# SELECT create_hypertable('cpu_data', 'time', if_not_exists => TRUE, chunk_time_interval ==> INTERVAL '1 day');
ERROR:  column "chunk_time_interval" does not exist
LINE 1: ...rtable('cpu_data', 'time', if_not_exists => TRUE, chunk_time...
```

### How can we reproduce the bug?

```bash
` CREATE TABLE machines (id SERIAL PRIMARY KEY, type TEXT NOT NULL);
CREATE TABLE cpu_data (time TIMESTAMPTZ NOT NULL, machine_id INTEGER REFERENCES machines (id),  value DOUBLE PRECISION );
SELECT create_hypertable('cpu_data', 'time', if_not_exists => TRUE, chunk_time_interval ==> INTERVAL '1 day');`
```

**Comment by svenklemm** [comment]
You have a typo in your SQL command:
`chunk_time_interval ==> INTERVAL '1 day'` should be `chunk_time_interval => INTERVAL '1 day'`

**Comment by Katikatikou** [comment]
Thanks a lot sorry for the stupid mistake :/
