### ISSUE TITLE
[Flaky test] pg_dump

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#4766]
### Which test is flaky?

pg_dump

### Since when has the test been flaky?

September 28, 2022

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/3141452205/jobs/5104632804

### Log output

```bash
diff -u /mnt/d/a/timescaledb/timescaledb/test/expected/pg_dump.out /mnt/d/a/timescaledb/timescaledb/build_wsl/test/results/pg_dump.out
--- /mnt/d/a/timescaledb/timescaledb/test/expected/pg_dump.out	2022-09-28 08:00:25.766247200 +0000
+++ /mnt/d/a/timescaledb/timescaledb/build_wsl/test/results/pg_dump.out	2022-09-28 08:10:51.512805600 +0000
@@ -277,382 +277,10 @@
 pg_dump:   chunk
 pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
 pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
+dropdb: error: database removal failed: ERROR:  database "db_pg_dump" is being accessed by other users
+DETAIL:  There is 1 other session using the database.
+createdb: error: database creation failed: ERROR:  database "db_pg_dump" already exists
 \c :TEST_DBNAME
 SET client_min_messages = ERROR;
 CREATE EXTENSION timescaledb CASCADE;
```

### Reason for flakiness

Session do not have time to disconnect.

**Comment by jnidzwetzki** [comment]
Same test, other error:

```
ERROR:  source database "db_pg_dump" is being accessed by other users
```

Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/5249803454/jobs/9483023437

**Comment by jnidzwetzki** [comment]
Another `ERROR:  source database "db_pg_dump" is being accessed by other users`

https://github.com/timescale/timescaledb/actions/runs/5261600258/jobs/9509897416

**Comment by mkindahl** [comment]
> Another `ERROR: source database "db_pg_dump" is being accessed by other users`
> 
> https://github.com/timescale/timescaledb/actions/runs/5261600258/jobs/9509897416

This can happen if one process is not shutting down fast enough. There is a small window between the process reporting as disconnected and actually being disconnected, which can trigger this error.

**Comment by lkshminarayanan** [comment]
The failure reported in the issue description, has occurred in PG14 on Windows but the logs are lost so there is nothing much to do.

All the other reported failures are only in latest PG12 and we are already in the process of removing PG12 support. So, the consensus is to wait until PG12 has been removed and then probably close it if there is no reported failure for sometime.

**Comment by mkindahl** [comment]
Still flaky

https://github.com/timescale/timescaledb/actions/runs/6890326254/job/18743140580?pr=6316

**Comment by fabriziomello** [comment]
Another flakiness execution
https://github.com/timescale/timescaledb/actions/runs/6982244302/job/19001030210?pr=6347
