### ISSUE TITLE
[Bug]: Realtime aggregates do not work on CAGG with Timezone

### ISSUE THREAD

**Issue by pfried** [timescale/timescaledb#4769]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I do have measurements in a hypertable "Measurement", I then created a CAGG by

    CREATE MATERIALIZED VIEW measurement_tenant_monthly_europe_berlin WITH (timescaledb.continuous) AS
    SELECT tenant_id,
           time_bucket('1 month', time, 'Europe/Berlin') AS time,
           SUM(metric) AS metric
    FROM "Measurement"
    GROUP BY 1, 2
    WITH NO DATA;

and also a policy

    SELECT add_continuous_aggregate_policy('measurement_tenant_monthly_europe_berlin', start_offset => INTERVAL '63 days', end_offset => INTERVAL '1 day', schedule_interval => INTERVAL '15 min');

I would expect the cagg to return real time data, so the bucket for September (now) should contain also the latest data not yet materialized in the cagg, but it does only return what is in the table and not the data coming in after the policy ran. I verified this by refreshing the cagg manually which then returns the correct data. Timescale cloud also shows that the Realtime is enabled

*Note 1: I switched over recently from time_bucket_ng*
*Note 2: I do have other CAGGs with the experimental time_bucket_ng running on the same server*

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

13.8

### What operating system did you use?

Timescale cloud

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```bash
Create a Hypertable
Create a CAGG with the specs above (timezone + bucket 1 month)
Create a CAGG policy

Insert data in real time window

Query the CAGG -> New data will not show up
```

**Comment by svenklemm** [comment]
I could not reproduce the bug. Can you post a minimual self-contained example that showcases the unexpected behaviour.

**Comment by pfried** [comment]
@svenklemm Thank you for your time you put into this, really appreciate it. Coming back to this now as I was on the road. I was not able to reproduce the issue today either (I am actually reliefed by that). But since we observed the issue originally (also not only by me but also checked by my collegue) we will keep an eye out if that happens again. Hopefully it was just some kind of hickup or error on our side
