### ISSUE TITLE
[Feature]: OLTP

### ISSUE THREAD

**Issue by ChenpiDog** [timescale/timescaledb#4776]
### What problem does the new feature solve?

Does timescaledb belong to oltp or olap?

### What does the feature do?

I want to know the classification of timescaledb.

**Comment by svenklemm** [comment]
This is the bugtracker for timescaledb and not meant for generic questions. The [Forum](https://www.timescale.com/forum/) or [Slack](https://slack.timescale.com/) is a better place to ask this question.
