### ISSUE TITLE
gap filling: fill previous?

### ISSUE THREAD

**Issue by est** [timescale/timescaledb#480]
Taken from [the gap filling doc](http://docs.timescale.com/v0.9/using-timescaledb/reading-data#gap-filling)

        date    | volume
    ------------+--------
     2017-09-30 |      0
     2017-09-29 |  11315
     2017-09-28 |   8216
     2017-09-27 |   5591
     2017-09-26 |   9182
     2017-09-25 |  14359
     2017-09-24 |      0
     2017-09-23 |      0
     2017-09-22 |   9855

http://docs.timescale.com/v0.9/using-timescaledb/reading-data#gap-filling

Now I dont want to `fill(0)`, I need `fill(previous)` like this:

        date    | volume
    ------------+--------
     2017-09-30 |      0
     2017-09-29 |  11315
     2017-09-28 |   8216
     2017-09-27 |   5591
     2017-09-26 |   9182
     2017-09-25 |  14359
     2017-09-24 |  14359
     2017-09-23 |  14359
     2017-09-22 |   9855

How can this be done?

**Comment by est** [comment]
I found this clever windowing function hack

https://stackoverflow.com/a/19012333/41948

**Comment by cevian** [comment]
We plan to improve this functionality shortly, but for now you can use the method here: https://www.joyofdata.de/blog/locf-linear-imputation-postgresql-tutorial/

**Comment by mfreed** [comment]
@est This capability can now be found using our `time_bucket_gapfill` and `locf` functionality, first released in version 1.2.

https://docs.timescale.com/v1.2/api#locf

**Comment by est** [comment]
@mfreed thanks!

**Comment by slidenerd** [comment]
Instead of using any form of averaging or previous value substitution, I am querying the external API to update the missing data by detecting gaps with a task queue, in such a scenario if I had say 1 million 1m data points and I wanted 5m data points from it, do I have to run over the whole database again to generate 5m data points or can I run over the last chunk or so
