### ISSUE TITLE
Error when restoring from backup: `data_trunc` not found

### ISSUE THREAD

**Issue by addon9** [timescale/timescaledb#481]
postgres=# \l
                              List of databases
     Name     |  Owner   | Encoding | Collate | Ctype |   Access privileges   
--------------+----------+----------+---------+-------+-----------------------
 bhavit_check | postgres | UTF8     | en_IN   | en_IN | 
 nyc_data     | postgres | UTF8     | en_IN   | en_IN | 
 nys_data     | postgres | UTF8     | en_IN   | en_IN | 
 postgres     | postgres | UTF8     | en_IN   | en_IN | 
 template0    | postgres | UTF8     | en_IN   | en_IN | =c/postgres          +
              |          |          |         |       | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_IN   | en_IN | =c/postgres          +
              |          |          |         |       | postgres=CTc/postgres
 weather      | postgres | UTF8     | en_IN   | en_IN | 
(7 rows)

postgres=# \c weather
You are now connected to database "weather" as user "postgres".
weather=# SELECT data_trunc ('hour', time) "hour", trunc(avg(temperature),2) avg_temp, trunc(min(temperature), 2) min_temp, trunc(max(temperature), 2) max_temp FROM conditions c WHERE c.device_id IN (SELECT device_id FROM locations WHERE location LIKE 'field-%') GROUP BY "hour" ORDER BY "hour" ASC LIMIT 24;
ERROR:  function data_trunc(unknown, timestamp with time zone) does not exist
LINE 1: SELECT data_trunc ('hour', time) "hour", trunc(avg(temperatu...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
weather=#

**Comment by cevian** [comment]
There is a typo in your query. The function is `date_trunc` not `data_trunc`.

**Comment by cevian** [comment]
@addon9 did that resolve your problem? ok to close?

**Comment by addon9** [comment]
yeah, so sorry that was my mistake.. thank you
