### ISSUE TITLE
Compression : compress_after parameter configuration issue

### ISSUE THREAD

**Issue by abgarg2022** [timescale/timescaledb#4811]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Compression

### What happened?

Considering today is 11 Oct 2022, when we try to update compress_after parameter in Automated Job scheduler for compression as per below, it does not work.
------Epoch Time till 30th Sept
select 
(EXTRACT(epoch from to_timestamp(concat(to_char(now() - INTERVAL '11 days', 'YYYY-MM-DD'), ' 23:59:59'), 'YYYY-MM-DD HH24:MI:SS'))*1000)::bigint;
---1664562599000

------To Compress all chunks till 30th Sep
select 
to_timestamp(concat(to_char(now() - INTERVAL '11 days', 'YYYY-MM-DD'), ' 23:59:59'), 'YYYY-MM-DD HH24:MI:SS');
---2022-09-30 23:59:59.000 +0530 

---Interval Integer for 11 days considering today is 11th Oct
select (86400000)*11::BIGINT as "11_days";
----output--950400000

But the Job does not give any result based on below condition in policy_compression_execute procedure, when execute for 👍1664562599000 --> this works
👍950400000 --> this does not work
 

SELECT
      show.oid, ch.schema_name, ch.table_name, ch.status
    FROM
      public.show_chunks('ts_kv', older_than => 1664562599000::BIGINT) AS show(oid)
      INNER JOIN pg_class pgc ON pgc.oid = show.oid
      INNER JOIN pg_namespace pgns ON pgc.relnamespace = pgns.oid
      INNER JOIN _timescaledb_catalog.chunk ch ON ch.table_name = pgc.relname AND ch.schema_name = pgns.nspname 
      AND ch.hypertable_id = 1
    where 1=1
		and       ch.dropped IS FALSE
      AND (ch.status = 0 OR ch.status = 3)
;

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

12

### What operating system did you use?

Ubuntu 22.04 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
By running above queries
```

**Comment by fabriziomello** [comment]
@abgarg2022 can u provide a reproducible test case of this problem???

**Comment by abgarg2022** [comment]
Execute below to reproduce


CREATE TABLE IF NOT EXISTS public.ts_kv
(
    entity_id uuid NOT NULL,
    key integer NOT NULL,
    ts bigint NOT NULL,
    bool_v boolean,
    str_v character varying(10000000) COLLATE pg_catalog."default",
    long_v bigint,
    dbl_v double precision,
    json_v json,
    CONSTRAINT ts_kv_pkey PRIMARY KEY (entity_id, key, ts)
);

SELECT create_hypertable('ts_kv', 'ts', chunk_time_interval => 86400000);

ALTER TABLE ts_kv SET (timescaledb.compress, timescaledb.compress_segmentby = 'entity_id,key');

CREATE INDEX ts_kv_key_idx on public.ts_kv using btree (key);

CREATE INDEX ts_kv_dev_ts_idx ON ts_kv(entity_id, ts desc) WITH  (timescaledb.transaction_per_chunk);


Insert attached Files data.
[data-1665984672676.zip](https://github.com/timescale/timescaledb/files/9797166/data-1665984672676.zip)


Add Compression policy 
SELECT add_compression_policy('ts_kv', BIGINT '68400000');

2 days compress interval 
SELECT alter_job(id,config:=jsonb_set(config,'{compress_after}', '172800000')) FROM _timescaledb_config.bgw_job WHERE id = :job_id;

SELECT alter_job(:job_id, next_start => '2022-10-18 11:00:00.000 +0530');

**Comment by abgarg2022** [comment]
@fabriziomello 

I think it is due to _timescaledb_internal.subtract_integer_from_now 
Can you please check?

**Comment by abgarg2022** [comment]
Since no followup has been received, closing this.
