### ISSUE TITLE
 CREATE EXTENSION IF NOT EXISTS timescaledb; ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/timescaledb.control": No such file or directory

### ISSUE THREAD

**Issue by srinivassantosham** [timescale/timescaledb#4819]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Configuration

### What happened?

i am trying to install timescaledb with mac system 
and following the documentation of 1)
https://docs.timescale.com/install/latest/self-hosted/installation-macos/)
here is extensions are not configured 
2) Homebrew --here is extensions are not configured
3)[ ](https://docs.timescale.com/install/latest/installation-docker/)here is extensions are not configured
timescaledb version 2.8.1
postgresql 14.5

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

mac 10.15.7

### What installation method did you use?

Docker, Homebrew, Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
postgres=# CREATE database tsdb;
ERROR:  database "tsdb" already exists
postgres=# CREATE database srinu;
CREATE DATABASE
postgres=# \c srinu
You are now connected to database "srinu" as user "postgres"srinu-# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

Now I trying to timescaledb exytensions
srinu=# EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/timescaledb.control": No such file or directory
```

### How can we reproduce the bug?

```bash
I refer to 3 ways
homebrew
docker 
timescaledb
 
changed the config file also
Adding this one ----> shared_preload_libraries = 'timescaledb'
```

**Comment by srinivassantosham** [comment]
Could you please help me and let me know the update
actually i am new domain  of this TimescaleDB

**Comment by fabriziomello** [comment]
Hey @srinivassantosham, thanks for reaching out. How is the result of the following query?

```sql
SELECT * FROM pg_available_extensions WHERE name ~ 'timescaledb';
```
