### ISSUE TITLE
ERROR:  variable not found in subplan target list on PG15 

### ISSUE THREAD

**Issue by sb230132** [timescale/timescaledb#4834]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

TimescaleDB 2.9.0 when compiled against PG15 causes few regresscheck tests to fail with below error:
ERROR:  variable not found in subplan target list

### TimescaleDB version affected

2.9.0

### PostgreSQL version used

15.0

### What operating system did you use?

Mac OS X

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Run below tests:

rowsecurity-15
compression
compression_bgw
modify_exclusion
```

**Comment by mfundul** [comment]
Simplest reproduction thus far:
```sql
CREATE TABLE foo (a integer, b integer, c integer, d integer);

SELECT table_name FROM create_hypertable('foo', 'a', chunk_time_interval=> 10);

INSERT INTO foo values( 3 , 16 , 20, NULL);

UPDATE foo SET c = 40
WHERE  a = (SELECT 3);
```

**Comment by mfundul** [comment]
Related fix in PostgreSQL https://github.com/postgres/postgres/commit/64387c540805e392d051cf484ebcf937a9bd8b1b
