### ISSUE TITLE
[Enhancement]: Add EL9 Distribution Support

### ISSUE THREAD

**Issue by Vonng** [timescale/timescaledb#4839]
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Build system

### What does the enhancement do?

Add rpm packages for EL9:

* Red Hat Enterprise Linux 9
* CentOS 9s or Rocky9

```bash
yum install timescaledb-2-postgresql-15
```

Timescaledb have official EL7 / EL8 [support](
https://docs.timescale.com/install/latest/self-hosted/installation-redhat/), while EL9 rpms are missing. Other popular extensions such as PostGIS / Citus already have EL9 / PG15 support. Looking forward to see timescaledb on EL9 / PG15

### Implementation challenges

Compile it on el9 just as el8 will do the trick.

**Comment by svenklemm** [comment]
EL/9 packages are available now

**Comment by Vonng** [comment]
It seems that there's a `citus_15` in pgdg yum repo. while citus official repo for el9 seems empty and the install script returns will following message:

```
$ curl https://install.citusdata.com/community/rpm.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8695  100  8695    0     0  31849      0 --:--:-- --:--:-- --:--:-- 31849
Detected operating system as rocky/9.
Unfortunately, your operating system distribution and version are not supported by this script.

Please contact us via https://www.citusdata.com/about/contact_us with any issues.
```
