### ISSUE TITLE
Multinode HA: handle DML to chunks when target DN is down

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#4846]
### What problem does the new feature solve?

https://github.com/timescale/product/issues/288 lays down the requirements for Datanode HA. We want to allow both read and write queries when a datanode (DN) goes down. 

One way to allow write queries when DN goes down is to track which chunk on that down DN is being written to and to mark that.

### What does the feature do?

Instead of tracking dirty chunks explicitly on AN, we will remove the metadata on the AN which associates this down DN with such a dirty chunk. Since we will remove metadata on the AN, any future queries will never go to this DN for this data avoiding the issue of stale data fetches completely.

When the DN comes back, the rebalancer microservice in TSC (Timescale Cloud) will kick in automatically and will refresh these chunks on the DN. That will need changes in [copy_chunk/move_chunk functionality](https://github.com/timescale/timescaledb/issues/4847). 

The DN can also when it comes back tell the AN about its chunk and AN can also cleanup [stale chunks](https://github.com/timescale/timescaledb/issues/4848) that ways on it.

Hat tip to @pmwkaa for this overall idea of removing metadata on the AN as the way to track the dirtied chunks. 

This issue will only track the AN handling of the removing metadata part.

**Comment by jfjoly** [comment]
Note on the behavior: when a DN is unavailable, new chunks will be created on the "surviving" nodes. The replication factor may be below the desired one until all DNs come back online.
