### ISSUE TITLE
Multinode: Enhance copy_chunk/move_chunk to truncate/remove an existing chunk

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#4847]
### What type of enhancement is this?

API improvement

### What subsystems and features will be improved?

Access node, Data node, Multi-node

### What does the enhancement do?

https://github.com/timescale/timescaledb/issues/4846 plans to remove metadata on Access -node (AN) for down datanode (DN) visavis a chunk that gets written to while its down.

When DN comes back, rebalancer service in Timescale Cloud (TSC) will call "copy_chunk" to refresh a stale chunk. We need to modify `copy_chunk` to take a parameter and drop/truncate an existing target chunk on the DN while doing the copy.

**Comment by pmwkaa** [comment]
There is no need for this feature anymore, since we are doing automatic drop of stale chunks, when data nodes become available: https://github.com/timescale/timescaledb/pull/4971
