### ISSUE TITLE
Windows x64 PostgreSQL service does not start up

### ISSUE THREAD

**Issue by cliff-pennalligen** [timescale/timescaledb#485]
Firstly, thankyou for releasing a Windows x64 binary!

Sorry if I've missed something obvious, anyway I downloaded this and ran the setup.exe successfully (after modifying PATH).  But after adding timescaledb to shared preload libraries, the PostgreSQL service stops immediately after restarting with the following error (event viewer):
2018-03-27 08:24:49.537 NZDT [2288] FATAL:  could not load library "C:/Program Files/PostgreSQL/10/lib/timescaledb.dll": The specified module could not be found.

... but the file is there.

Here are some more details:
Windows: 7 Professional x64 SP1 (don't ask)
PosgreSQL: 10.3-1-windows-x64
Timescale downloaded: timescaledb-postgresql-10_0.9.0-windows-amd64

**Comment by RobAtticus** [comment]
Can you make sure that our other DLL files are there too? Namely `timescaledb-0.9.0.dll`?

**Comment by cliff-pennalligen** [comment]
Yes timescaledb-0.9.0.dll is also in the lib folder

**Comment by RobAtticus** [comment]
Doing some googling I have seen people use http://www.dependencywalker.com/ to find out if dependent `.dll`s are missing. Maybe see if that is useful? Unfortunately I am not super familiar with this problem, but hopefully can help. You can also drop into our Slack and DM me: http://slack-login.timescale.com/

**Comment by cliff-pennalligen** [comment]
RobAtticus thanks for your assistance.  Have tried dependency walker and many other things but I think I'll have to leave this as we have limited dev/IT capability.  Even if I solve it, the next guy who comes across a different postgreSQLism will be stumped.  I like the timeseries DB idea very much though, keen to see how this goes.

**Comment by RobAtticus** [comment]
Thanks for letting us now @cliff-pennalligen . Hopefully you do decide to try again, and we can find a solution to the problem.

**Comment by sanpa1977** [comment]
Hi RobAtticus, I am facing the same problem on a Windows 2016 Server System. I could however setup everything successfully on a Windows 10 Pro System. I tried with both -0.9.0 and 0.9.1. The message is same as reported by cliff-pennalligen in the Event Log is "FATAL:  could not load library "C:/Program Files/PostgreSQL/10/lib/timescaledb.dll": The specified module could not be found."

**Comment by sanpa1977** [comment]
Hello @cliff-pennalligen  and @RobAtticus. I think I figured out the reason for this error. The system needs  Visual C++ Redistributable for Visual Studio 2015 (https://www.microsoft.com/en-us/download/details.aspx?id=48145). Once this is installed the PostgreSQL Service starts without any problem. The reason why it was working on my Windows 10 System is because I had Visual Studio 2017 installed on it. I hope this would be helpful. Thanks

**Comment by RobAtticus** [comment]
@sanpa1977 Ah, thank you for that tip. We will add that to our docs as a prerequisite so that others know. I also had VS2017 installed so I had that dependency without knowing. Thanks!

**Comment by cliff-pennalligen** [comment]
@RobAtticus , @sanpa1977, thanks for posting, I've installed Visual C++ Redistributable for Visual Studio 2015 and it's all working now!

**Comment by tuomohopia** [comment]
I still keep getting this error:
```
** (Postgrex.Error) ERROR XX000 (internal_error) could not load library "C:/Program Files/PostgreSQL/10/lib/timescaledb-1.4.2.dll": The specified procedure could not be found.
```

Trying to run migrations on Ecto, Elixir. I have the C++ redistributable installed.

**Comment by HayasyLL** [comment]
I get this error too, when creating extension in a new db.
OS: win7 SP1, I have installed VS2019.

**Comment by AlaiY95** [comment]
im getting this error also... I've tried with the Postgres 13 and 14 with the respective timescaledb setup. works on my mac but not on my windows pc
