### ISSUE TITLE
Propagate grants when adding a data node

### ISSUE THREAD

**Issue by sb230132** [timescale/timescaledb#4856]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Multi-node

### What happened?

With PG15 by default a role or user does not have ```CREATE``` grant on public schema. One needs to explicitly GRANT those privileges.

When executing `add_data_node` in a database and the target database does not exist, existing grants in the database on the access node are not propagated to the database on the data node. Since `GRANT` statements are propagated to all existing data nodes, it means that the permissions will be different depending on whether the `GRANT` is executed before or after `add_data_node`.

To solve this, when running `add_data_node`, existing grants should be propagated to the database on the data node.

Note, however, that this assumes that the role already exists on the data node and will give an error if that is not the case. This would be expected: creating roles on the remote data node should be avoided since it can affect the entire node, not just the created database.

Refer https://github.com/timescale/timescaledb/pull/4844#discussion_r998224718 for more details.

### TimescaleDB version affected

2.9.0

### PostgreSQL version used

15.0

### What operating system did you use?

Mac OS X

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

On a PG15 server, run these statement to create a non-superuser `some_user`:

```sql
CREATE USER some_user;
GRANT CREATE ON SCHEMA public TO some_user;
SELECT add_data_node('dn1', host => 'localhost', database => 'dn1');
SET ROLE some_user;
CREATE TABLE disttable(time timestamp, temp decimal(10,2));
SELECT * FROM create_distributed_hypertable('disttable', 'time', 'temp');
```

**Comment by svenklemm** [comment]
multinode has been removed
