### ISSUE TITLE
[Bug]: PostgreSQL killed by OOM killer 

### ISSUE THREAD

**Issue by Adi-86** [timescale/timescaledb#4858]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Platform/OS, Other

### What happened?

I would like to upgrade the history tables in the Zabbix database to primary keys, but PostgreSQL with TimescaleDB extension gets an out-of-memory error and gets killed by the OOM killer. The TimescaleDB extension was 2.8, but I noticed in another post It might be fixed if rolling back to version 2.7.0. I also changed the value of "vm.overcommit_memory = 2" and tuned "vm.overcommit_ratio to 80" to avoid killing the process by the Linux kernel, But, the issue is still persistent 

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.5

### What operating system did you use?

Debian 11 bullseye x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/system-postgresql.slice/postgresql@14-main.service,task=postgres,pid=242635,uid=111
```

### How can we reproduce the bug?

```bash
\set ON_ERROR_STOP on

\copy (select * from history_uint_old) TO '/tmp/history_uint.csv' DELIMITER ',' CSV;

CREATE TEMP TABLE temp_history_uint (
        itemid                   bigint                                    NOT NULL,
        clock                    integer         DEFAULT '0'               NOT NULL,
        value                    numeric(20)     DEFAULT '0'               NOT NULL,
        ns                       integer         DEFAULT '0'               NOT NULL
);

\copy temp_history_uint FROM '/tmp/history_uint.csv' DELIMITER ',' CSV

DO $$
DECLARE
        tsdb_version_major      INTEGER;
        chunk_tm_interval       INTEGER;
        jobid                   INTEGER;
BEGIN
        SELECT substring(extversion, '^\d+') INTO tsdb_version_major FROM pg_extension WHERE extname='timescaledb';

        IF (tsdb_version_major < 2)
        THEN
                SELECT (upper(ranges[1]) - lower(ranges[1])) INTO chunk_tm_interval FROM chunk_relation_size('history_uint')
                        ORDER BY ranges DESC LIMIT 1;

                IF NOT FOUND THEN
                        chunk_tm_interval = 86400;
                END IF;

                PERFORM create_hypertable('history_uint', 'clock', chunk_time_interval => chunk_tm_interval, migrate_data => true);
        ELSE
                PERFORM create_hypertable('history_uint', 'clock', chunk_time_interval => (
                        SELECT integer_interval FROM timescaledb_information.dimensions WHERE hypertable_name='history_uint_old'
                ), migrate_data => true);
        END IF;

        INSERT INTO history_uint SELECT * FROM temp_history_uint ON CONFLICT (itemid,clock,ns) DO NOTHING;

        PERFORM set_integer_now_func('history_uint', 'zbx_ts_unix_now', true);

        ALTER TABLE history_uint
        SET (timescaledb.compress,timescaledb.compress_segmentby='itemid',timescaledb.compress_orderby='clock,ns');

        IF (tsdb_version_major < 2)
        THEN
                PERFORM add_compress_chunks_policy('history_uint', (
                                SELECT (p.older_than).integer_interval
                                FROM _timescaledb_config.bgw_policy_compress_chunks p
                                INNER JOIN _timescaledb_catalog.hypertable h ON (h.id=p.hypertable_id)
                                WHERE h.table_name='history_uint_old'
                        )::integer
                );
        ELSE
                SELECT add_compression_policy('history_uint', (
                        SELECT extract(epoch FROM (config::json->>'compress_after')::interval)
                        FROM timescaledb_information.jobs
                        WHERE application_name LIKE 'Compression%%' AND hypertable_schema='public'
                                AND hypertable_name='history_uint_old'
 )::integer
                ) INTO jobid;

                IF jobid IS NULL
                THEN
                        RAISE EXCEPTION 'Failed to add compression policy';
                END IF;

                PERFORM alter_job(jobid, scheduled => true, next_start => now());
        END IF;

END $$;

UPDATE config SET compression_status=1;
```

**Comment by Adi-86** [comment]
You can find the Zabbix guide for Database upgrade to primary keys here:
https://www.zabbix.com/documentation/6.0/en/manual/appendix/install/db_primary_keys#postgresql-timescaledb

**Comment by fabriziomello** [comment]
@Adi-86 where exactly is the OOM happening?? Without a complete reproducible test case is hard to figure out what's the problem.

One thing I noticed is you're creating a hypertable over an existing table named `history_uint`, is this table empty?? Asking cause you're setting the `migrate_data => true` in the hypertable creation.

Another thing is why you're importing to a regular table and then issuing an INSERT?? Why not simple use the COPY over the created hypertable???

**Comment by Adi-86** [comment]
@fabriziomello Thank you for reaching out! :) I encounter the error 4 hours after performing the command. first I need to rename the existing tables using "history_pk_prepare.sql"
Then, I would run TimescaleDB hypertable migration scripts that are:
"history_pk"
"history_pk_log"
"history_pk_str"
"history_pk_text"
"history_pk_uint"
I have attached the scripts as well
![Github](https://user-images.githubusercontent.com/99492569/196806650-f4bff81d-896c-4735-ad9e-b732894f2980.jpg)
[PostgreSQL.TimescaleDB.zip](https://github.com/timescale/timescaledb/files/9824452/PostgreSQL.TimescaleDB.zip)

Thanks!

**Comment by fabriziomello** [comment]
@Adi-86 I'm still not able to reproduce your scenario because the lack of information. 

By "reproducible test case" I mentioned in my last comment I meant all SQL commands (table structures, data, queries, etc) that I can copy from the issue and paste in my Postgres environment that I can achieve the problem that you're facing. Is fine to attach a zip with everything but in your last comment you didn't provide everything. For example I can't find the "/tmp/history.csv" file, "history_old" table, "history" table, etc...
