### ISSUE TITLE
Using id in creating hypertable

### ISSUE THREAD

**Issue by johnreytanquinco** [timescale/timescaledb#487]
Does this requires to be `time` in converting table into Hypertable?
`SELECT create_hypertable('test',  'id');`

And this is the error message im getting.
`ERROR:  integer dimensions require an explicit interval`

**UPDATE:**
Ive read in the docuentation that `time` is required as time partitioning in the `create_hypertable` and also notice this TIP, but doesnt seems to work.

> TIP:The time column in create_hypertable must be defined as NOT NULL. If this is not already specified on table creation, create_hypertable will automatically add this constraint on the table when it is executed.

I am getting:
```
db=# SELECT create_hypertable('test', 'time');
NOTICE:  adding NOT NULL constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values
ERROR:  cannot create a unique index without the column "time" (used in partitioning)
```

**UPDATE 2:**
I have set the column `time` into` NOT NULL`., but still getting:
`ERROR:  cannot create a unique index without the column "time" (used in partitioning)`

```
 Column |            Type             | Modifiers | Storage  | Stats target | Description 
--------+-----------------------------+-----------+----------+--------------+-------------
 id     | bigint                      | not null  | plain    |              | 
 test   | character varying(255)      |           | extended |              | 
 time   | timestamp without time zone | not null  | plain    |              | 
Indexes:
    "test_pkey" PRIMARY KEY, btree (id)

```

**Comment by mfreed** [comment]
The create_hypertable call can work with general integer arguments, but it must understand the semantics, i.e., you need to specify the interval range with which it performs partitions.  Please see:  http://docs.timescale.com/v0.9/api#create_hypertable

```
For integer types, the chunk_time_interval must be set explicitly, as the database does not otherwise understand the semantics of what each integer value represents (a second, millisecond, nanosecond, etc.). So if your time column is the number of milliseconds since the UNIX epoch, and you wish to each chunk to cover 1 day, you should specify chunk_time_interval => 86400000.
```

You can specify something like:

`SELECT create_hypertable('test', 'id', chunk_time_interval => 100000);`

That said, many of the insert and query performance of timescale rely on the fast that values are insert-mostly to the latest intervals.  So if you commonly do full scans over the entire input set (i.e., your query doesn't specify some `id` range), or if you commonly update randomly-selected `id`'s, you'll sacrifice much of this performance.

So, the general question is why you need such `id`'s.

**Comment by johnreytanquinco** [comment]
I have added **UPDATE 2** adding time in my column.
And for your question:
>So, the general question is why you need such id's.
My other table name has already `time` column included which reads not the current time, but others.

**Comment by johnreytanquinco** [comment]
It works in one table but not in the other.
```
test=# SELECT create_hypertable('test2', 'id', chunk_time_interval => 604800000);
ERROR:  cannot create a unique index without the column "id" (used in partitioning)
```

**Comment by mfreed** [comment]
Can you post the output of `\d+` for the table `test2`?  

My guess is that you have some field that's listed as UNIQUE, but timescaleDB only supports UNIQUE constraints that have the partitioning key as their prefix.  See this on indexing:  http://docs.timescale.com/v0.9/using-timescaledb/schema-management#indexing

But again, not typical to try to use a unique / series ID as the partitioning key.  Please see this for a better explanation:  https://blog.timescale.com/time-series-data-why-and-how-to-use-a-relational-database-instead-of-nosql-d0cd6975e87c

**Comment by johnreytanquinco** [comment]
Your right. The fix was I just exclude the index when creating the table. Its working as expected. Thanks again for your helo @mfreed . Appreciate it!
