### ISSUE TITLE
[Bug]: "Invalid child of chunk" on specific ctid filtering

### ISSUE THREAD

**Issue by ronnyas** [timescale/timescaledb#4872]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Partitioning, Query executor

### What happened?

Selecting rows in a table where ctid is less/greater than X is not possible in combination of refrencing a time colum, but works on its own. My guess is a bug in timescales partitioning strategy. 

Querying `SELECT something FROM some_hypertable WHERE time > now() - INTERVAL '1 year' AND ctid > '(1,1)'::tid` returns `ERROR:  invalid child of chunk append: Node (26)`

However, these will run fine:
`SELECT * FROM some_hypertable WHERE ctid > '(1,1)'::tid`
`SELECT * FROM some_hypertable WHERE ctid = '(1,1)'::tid AND some_column = 'xyz'`
`SELECT * FROM some_hypertable WHERE ctid > '(1,1)'::tid OR some_column = 'xyz'`
`SELECT * FROM some_hypertable WHERE time > NOW() - INTERVAL '5 years'  AND ctid = '(10,0)'::tid;`

### TimescaleDB version affected

2.8.0 

### PostgreSQL version used

14.5

### What operating system did you use?

Ubuntu 22.04 x86_64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

ERROR:  invalid child of chunk append: Node (26)

### How can we reproduce the bug?

```bash
create table public.some_hypertable (
  time timestamp without time zone,
  some_column bigint
);

select create_hypertable('some_hypertable', 'time');

insert into some_hypertable (time, some_column) values (now(), 1);
insert into some_hypertable (time, some_column) values (now(), 2);
insert into some_hypertable (time, some_column) values (now(), 3);

select * from some_hypertable where time > now() - interval '5 years'  and ctid < '(1,1)'::tid;
```

**Comment by akuzm** [comment]
As a workaround, try `set timescaledb.enable_chunk_append to off;`. It's going to have worse performance though.

`Node (26)` is `TidRangeScan`, probably something we'll have to support in chunk append scan.
