### ISSUE TITLE
Converting regular table to hypertable (zero copy and downtime)

### ISSUE THREAD

**Issue by kokizzu** [timescale/timescaledb#493]
On the [tutorial](http://docs.timescale.com/v0.9/getting-started/migrating-data#same-db) there's a way to copy old table schema to new table, create hypertable, then reinsert the data. But is there a way to convert old table to hypertable without creating new table and reinserting the data?

**Comment by erimatnor** [comment]
@kokizzu With version 0.9, we added the option to migrate data when creating a hypertable: http://docs.timescale.com/v0.9/api#create_hypertable

Note, however, that this can take a long time in case you have lots of data and the table will be locked during this time.

**Comment by kokizzu** [comment]
locking means the table cannot be inserted at all 

OR

the insert processed in journal and will be executed later after conversion finished?

**Comment by davidkohn88** [comment]
Unfortunately, it means the former, you also can't read from it during the locked period, I believe it's an exclusive lock. 
There are some potential workarounds for this, but they don't maintain all features, one question is, do you need to be able to do updates/deletes during the migration or are inserts enough? 

In that case what I'd recommend is creating a hypertable with the same schema and pointing inserts at it, making a view that does the union all of the hypertable and the old table, then transferring the data from the old table to the hypertable using delete returning *  (with some where clauses if you want to do it in parallel) and then when the migration is done you can drop the old table and view and just point back at the hypertable for everything.  If you need to do deletes/updates during the period, you can probably write some triggers that would work. It's a bit of a difficult process, will mark this as an enhancement you'd like to see and we'll see what we can do.

**Comment by kokizzu** [comment]
yes, i only need insert and select until the migration completed. thank you ^^)b

**Comment by erimatnor** [comment]
@kokizzu I am closing this issue since it seems to be resolved, clarified.
