### ISSUE TITLE
Add explicit error when MERGE command is used with hypertables

### ISSUE THREAD

**Issue by iroussos** [timescale/timescaledb#4930]
### What problem do we want to solve?

As discussed in https://github.com/timescale/timescaledb/issues/4929, the new [MERGE command](https://www.postgresql.org/docs/current/sql-merge.html) (introduced in PG 15) fails with an error when used with hypertables.

Currently a generic catch-all error is presented which is not only confusing, but straightforward wrong (it will be thrown even if the extension is available and preloaded):

```
ERROR:  invalid INSERT on the root table of hypertable "conditions"
HINT:  Make sure the TimescaleDB extension has been preloaded.
```

Before adding full support for MERGE (which at the moment we don't know how much effort it will require), we want to make sure that we present a properly descriptive error to TimescaleDB users. 

```
ERROR:  The MERGE command does not support hypertables in this version 
HINT:  Check https://github.com/timescale/timescaledb/issues/4929 for more information and current status
```

**Comment by iroussos** [comment]
@horzsolt assigning to you to decide who should work on this as part of https://github.com/timescale/timescaledb-private/issues/972

**Comment by iroussos** [comment]
The question is how easy is it to identify when MERGE command is used with hypertables? Seems pretty straight forward, but could this delay our plans for PG15 support?

**Comment by iroussos** [comment]
@charislam can you help us with some feedback on the error message we should have in this case?

We want to inform TimescaleDB users that the newly introduced [MERGE command](https://www.postgresql.org/docs/current/sql-merge.html) does not work with hypertables right now (2.9.0) (but it works for normal tables). 

The idea is to inform them on use of the command (for that small 99%+ that doesn't check release announcements :-) ). My quick proposal:

```
ERROR:  The MERGE command does not support hypertables in this version 
HINT:  Check https://github.com/timescale/timescaledb/issues/4929 for more information and current status
```

Seems weird to link to a github issue in there. Maybe we should skip the hint (?)

PS. We'll most probably add support for it around 2.10.0

FYI @nenadmalic (and any ideas on wording)

**Comment by charislam** [comment]
Hi @iroussos text looks fine to me, no suggestions there. I actually like the hint, it feels more responsive than just saying "nope, this doesn't work". As it's a temp measure I think linking to a GitHub issue is fine

**Comment by theblinkingusb** [comment]
Thanks for this one - just came across the error and having the github issue there was helpful. Upgraded and now g2g.
