### ISSUE TITLE
brew install timescaledb installs wrong architecture

### ISSUE THREAD

**Issue by trueb2** [timescale/timescaledb#4949]
### What type of bug is this?

Other

### What subsystems and features are affected?

Packaging, Platform/OS

### What happened?

With a fresh brew install, tap, and install timescaledb, the timescaledb-tools are the wrong architecture on macOS.

![Screen Shot 2022-11-09 at 11 15 26 AM](https://user-images.githubusercontent.com/8592049/200897058-1c5afb1d-54f4-4568-b2cd-94f897332ced.png)

As a workaround, I `brew uinstall timescaledb-tools --ignore-dependencies` and install manually from https://github.com/timescale/timescaledb-tune. No problems with the rest of the installation as far as I can tell so far.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Mac OS 12.6

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
217  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"\n
  218  rm -rf /opt/homebrew
  219  sudo rm -rf /opt/homebrew
  220  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"\n
  221  brew tap timescale/tap
  222  brew install timescaledb
  223  timescaledb-tune --quiet --yes
  224  which timescaledb-tune
  225  file /opt/homebrew/bin/timescaledb-tune
```

### How can we reproduce the bug?

```bash
Follow the self hosted install instructions.

https://docs.timescale.com/install/latest/self-hosted/installation-macos/#install-self-hosted-timescaledb-using-homebrew
```

**Comment by konskov** [comment]
hi @trueb2 , on macos Monterey 12.5.1/M1 these steps all work fine...

**Comment by trueb2** [comment]
That was an M1 Ultra on a Max Studio

**Comment by shhnwz** [comment]
Hi @trueb2 , Please share the output of shell command `uname -a`

**Comment by shhnwz** [comment]
Hi @trueb2 ,

Thanks for creating this issue.
Mach-O also supports x86_64 binary, all you need to install Homebrew for arch x86_64 and switch your session to x86_64 to run timescaledb-tune.
