### ISSUE TITLE
Docker Version of Timescale DB

### ISSUE THREAD

**Issue by collegeimprovements** [timescale/timescaledb#495]
Hi Guys,

TimescaleDB is awesome. Thanks a lot for open-sourcing it and pushing it forward continuously.

Since TimescaleDB is itself a Postgres-extension, Can we just take the base images of Postgres and then run some commands to install libraries to install timescaledb and then run `create extension timescaledb if not exists` instead of using `timescaledb`'s official docker-images? 

e.g.
```
FROM postgres:10.3
RUN ... #installation of essential packages required by timescaledb
RUN ...
```
Maybe we can put the essential commands in `init` files!

The reason why we prefer the mentioned way is, simply explicit is better than implicit (elixir-lang-philosophy).

Would that be possible ? Or maybe i'm having wrong expectations or assumptions!

**Comment by erimatnor** [comment]
@collegeimprovements I am actually not 100% sure what you are asking, but you can certainly build your own Docker images. Our Docker images are built from this repo: https://github.com/timescale/timescaledb-docker and you can base your changes off of that. Starting from the Postgres image is also possible, but more work.

**Comment by mfreed** [comment]
And you of course can install TimescaleDB directly from source or a binary extension, not going through docker at all, e.g., http://docs.timescale.com/v0.9/getting-started/installation/linux/installation-apt-ubuntu

**Comment by collegeimprovements** [comment]
Thanks @erimatnor @mfreed. 
I was searching for an easy way where i can keep Postgres as the base-image and add timescale-db with some volume-mappings of conf-files and init files. I have very limited postgres knowledge.

Seems like it's not that straight forward. I'll try once again, and if I can't do that, i'll use `timescaledb` images.

**Comment by erimatnor** [comment]
@collegeimprovements Using the (Debian) PostgreSQL base image is certainly possible if you, for instance, install the Debian packages of TimescaleDB at runtime or compile your own binaries that you mount into the container. However, that seems like more trouble than it is worth, and adding this on top of the PostgreSQL image is essentially what the TimescaleDB image provides you anyway.

**Comment by manigandham** [comment]
@collegeimprovements 

What you're asking is exactly what the `timescale/timescaledb` container does. Here's the Dockerfile: https://github.com/timescale/timescaledb-docker/blob/master/Dockerfile

You can always use that file and merge in any other changes you need to create your own container with more extensions if necessary.

**Comment by collegeimprovements** [comment]
sure @solugebefola. Thanks!
