### ISSUE TITLE
[Bug]: continuous aggregates lag behind one period 

### ISSUE THREAD

**Issue by k1th** [timescale/timescaledb#4950]
### What type of bug is this?

Other

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Question regarding continuous aggregates and their refresh policies:
For a hypertable with an interval of 1 day and additional dimension of 50 for a string field, we have aggregates by day that we’d like to update up until the start of the current day with materialized_only  (example: 2022-11-05). We noticed that the refresh policy is only refreshing up until the start of the previous day, so the max() of the bucket timestamp is 2022-11-04 01:00:00.000 +0100

This means that in the morning we’re unable to work with the previous day’s data. In the past we worked around this by aggregating by hour and summing up the hour values in the subsequent processing…

The aggregate is defined with GROUP BY time_bucket('1 day', deliveryprocessedts)  without timezone, so it should align to UTC..
The policy is defined as
```
start_offset => INTERVAL '3 day',
end_offset => INTERVAL '1 hour',
schedule_interval => INTERVAL '1 hour');
```
When querying the watermark with
 ```
SELECT COALESCE(
    _timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(123)),
    '-infinity'::timestamp with time zone
);
```
we get 2022-11-05 01:00:00.000 +0100
(Our local TZ is Europe/Berlin)

So what does this mean? Why is the watermark <most recent data> + 1 aggregation window?

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

12.12

### What operating system did you use?

Ubuntu 20.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Create any aggregate and and policy to refresh. Either wait for policy or call job manually.
```

**Comment by konskov** [comment]
hello @k1th, let us use the following example to see if I understand you correctly: 

```
-- hypertable with chunk size 1 day
CREATE TABLE conditions (
  time timestamptz NOT NULL,
  location TEXT NOT NULL,
  location2 char(10) NOT NULL,
  temperature DOUBLE PRECISION NULL
);

select create_hypertable('conditions', 'time', chunk_time_interval => interval '1 day');
-- create some chunks with data from one month ago until current day
INSERT INTO conditions (time, location, location2, temperature)
SELECT generate_series(now() - interval '30 days', now(), '1 day') as time, 'NYC', 'nycity',
generate_series(1, 31, 1);

-- cagg 
CREATE MATERIALIZED VIEW conditions_summary_daily
WITH (timescaledb.continuous, timescaledb.materialized_only = true, timescaledb.finalized=false) AS
SELECT location,
   time_bucket(INTERVAL '1 day', time) AS bucket,
   AVG(temperature),
   MAX(temperature),
   MIN(temperature)
FROM conditions
GROUP BY location, bucket
WITH NO DATA;

-- refresh the cagg 
CALL refresh_continuous_aggregate('conditions_summary_daily', now() - interval '3 days', now() - interval '1 hour'); 
-- now query the cagg: 
select * from conditions_summary_daily ;
 location |         bucket         | avg | max | min 
----------+------------------------+-----+-----+-----
 NYC      | 2022-11-08 02:00:00+02 |  29 |  29 |  29
 NYC      | 2022-11-09 02:00:00+02 |  30 |  30 |  30
(2 rows)
```
And the watermark is 
```
SELECT COALESCE(                                                                                                                                                                         _timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(4)),                                                                                                                '-infinity'::timestamp with time zone                                                                                                                                                    );
        coalesce        
------------------------
 2022-11-10 02:00:00+02
(1 row)
 ```
 > We noticed that the refresh policy is only refreshing up until the start of the previous day, so the max() of the bucket timestamp is 2022-11-04 01:00:00.000 +0100

It is not refreshing until the start of the previous day, it is refreshing until the end of the previous day (or start of the current day if you prefer to think of it that way). I think you are confused by the fact that when you query the cagg for the max(bucket), the value returned for the bucket is its start time. 

The watermark is 1 + bucket size because it represents the end of the bucket. Meaning that you have materialized data up until `2022-11-10 02:00:00+02` in this case, which is the end of the previous bucket and the start of the current one. Note, the watermark is an internal property, as you can see it is in an internal schema. 

I am closing this issue as there is not anything unexpected here, it is just the way continuous aggregates work.
For more questions around how continuous aggregates behave, apart from the documentation, our community slack and forum is a better place to ask and get more help. 

However, if I am misunderstanding the issue here, please feel free to reopen. Thanks!

**Comment by k1th** [comment]
@konskov 
You‘re right. We’re interpreting the output wrongly. 
We query for the bucket to determine if the day has been aggregated fully. Our expectation was that there should be some data in today’s bucket already, signaling for us that the policy has done its work. Would this only happen when enabling real time aggregates?

**Comment by k1th** [comment]
@konskov makes sense now. Thank you. 👍🏻
