### ISSUE TITLE
Graceful command exit using CTRL+C on MN

### ISSUE THREAD

**Issue by vineethapai** [timescale/timescaledb#4958]

**Comment by nikkhils** [comment]
Also check that setting `statement_timeout` on AN also cancels queries gracefully on the DNs

**Comment by pmwkaa** [comment]
Might be related https://github.com/timescale/Support-Dev-Collab/issues/682

**Comment by horzsolt** [comment]
@erimatnor , @nikkhils do you think this will fix that test [failure](https://github.com/timescale/timescaledb/issues/4972)?

**Comment by svenklemm** [comment]
multinode has been removed
