### ISSUE TITLE
Occasional timescaledb extension load errors when using C# Npgsql client lib.

### ISSUE THREAD

**Issue by gumshoes** [timescale/timescaledb#496]
C# client using Npgsql 3.2.7
PostgreSQL 9.6.8 on Debian 8.9
Timescaledb 0.9.1

Initial connections and queries work fine but sometimes subsequent queries (the app is threaded and uses Npgsql connection pool) fail.

PostgreSQL log:
```2018-04-05 21:09:10 BST [98917-1] FATAL:  extension "timescaledb" must be preloaded
2018-04-05 21:09:10 BST [98917-2] HINT:  Please preload the timescaledb library via shared_preload_libraries.

        This can be done by editing the postgres config file
        and adding 'timescaledb' to the list in the shared_preload_libraries config.
                # Modify postgresql.conf:
                shared_preload_libraries = 'timescaledb'
```

Setting `NoResetOnClose=true`
http://www.npgsql.org/api/Npgsql.NpgsqlConnectionStringBuilder.html#Npgsql_NpgsqlConnectionStringBuilder_NoResetOnClose

or `Pooling=false` is a workaround.

**Comment by cevian** [comment]
We can't reproduce. If anyone has any more info/way to reproduce please post here.

**Comment by manigandham** [comment]
We see this too. Npgsql uses its own connection pooling by default and this sends a `DISCARD ALL` statement prepended to the next query to reset the session: http://www.npgsql.org/doc/performance.html#pooled-connection-reset

It seems that discard command is affecting the extension settings...

**Comment by cevian** [comment]
@manigandham If you have any suggestions on how to reproduce please post it here. I haven't been able to reproduce even with Npgsql running. Can you provide a program and/or dataset (or any other clues)?

**Comment by sanpa1977** [comment]
@cevian : I am able to replicate the issue when i run a time_bucket based query for 1 hour grouping for a dataset containing data for a year with a timestamp interval of 1 minute. If i select a lesser period then there is no error. If i restart postgresql service and run the large dataset query the same error occurs again. NoResetOnClose seems to resolve the problem and it does not reoccur after that.

**Comment by wallies** [comment]
I dont know if this helps or not, but we are running timescaledb 0.9.1 and we were seeing this issue.
We had shared_preload_libraries = 'timescaledb' line in our postgresql.conf file. I ran 
echo "shared_preload_libraries = 'timescaledb'" >> /var/lib/postgresql/data/postgresql.conf and rebooted the databases and it started working for all queries. I have no idea why this started working. 

We also didnt see this issue on an instance we have that is timescaledb 0.8.0, it is only when we upgraded to 0.9.1 that we saw this issue.

**Comment by gumshoes** [comment]
Just encountered this with Microsoft Power BI Version: 2.57.5068.721 64-bit (April 2018)
PostgreSQL 9.6.8 on Debian 8.9
Timescaledb 0.9.1
`DataSource.Error: PostgreSQL: XX000: extension "timescaledb" must be preloaded`

With timescaledb 0.8.0 this did not happen.

**Comment by cjrh** [comment]
@gumshoes Would you be able to try timescaledb 0.9.0? If that is also fine, it would suggest that the culprit might be in 0.9.1 only (perhaps fc056377923c3e827472e64abbf17245733b4a7c ?)

**Comment by Artimi** [comment]
I've encountered this error too. I'm using python client `asyncpg 0.15.0` that use connection pool too. We are running dockerized Timescaledb 0.9.1-pg10.
```
  File "/home/artimis/.virtualenvs/mondrian/lib/python3.6/site-packages/asyncpg/pool.py", line 405, in fetch
    return await con.fetch(query, *args, timeout=timeout)
  File "/home/artimis/.virtualenvs/mondrian/lib/python3.6/site-packages/asyncpg/connection.py", line 359, in fetch
    return await self._execute(query, args, 0, timeout)
  File "/home/artimis/.virtualenvs/mondrian/lib/python3.6/site-packages/asyncpg/connection.py", line 1303, in _execute
    query, args, limit, timeout, return_status=return_status)
  File "/home/artimis/.virtualenvs/mondrian/lib/python3.6/site-packages/asyncpg/connection.py", line 1311, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/home/artimis/.virtualenvs/mondrian/lib/python3.6/site-packages/asyncpg/connection.py", line 1333, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 203, in bind_execute
asyncpg.exceptions.InternalServerError: extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the postgres config file 
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /path/to/config/file 

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
	SET timescaledb.allow_install_without_preload = 'on';
```

**Comment by gumshoes** [comment]
@cjrh sadly I won't be able to try with 0.9.0.
At the moment things we care about are working for us when setting `NoResetOnClose=true` with npgsql.

**Comment by cevian** [comment]
@manigandham @gumshoes @wallies @cjrh Thank you, thank you, thank you. I was finally able to reproduce this problem locally (it related to parallel workers). A PR to fix this should be coming shortly.
