### ISSUE TITLE
[Bug]: Unable to cancel or kill running query

### ISSUE THREAD

**Issue by aaronjwood** [timescale/timescaledb#4963]
### What type of bug is this?

Locking issue, Performance issue, Other

### What subsystems and features are affected?

Continuous aggregate, Query executor

### What happened?

We have this query which makes use of caggs:
```
SELECT intvl AS time
, sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>"", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>", sum("<MASKED>") AS "<MASKED>"
	FROM (
	  SELECT time_bucket_gapfill('18000s', time) AS intvl
	      , locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.000001", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.00001", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.0001", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.001", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.01", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 0.1", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 1.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 10.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 100.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 1000.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 10000.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency 100000.0", locf(max("<MASKED>"), treat_null_as_missing=>true) as "Latency +Inf", <MASKED>, "<MASKED>"
	  FROM "<MASKED>-60min"

	  WHERE time >= '2022-10-26T18:00:00.000Z' AND time < '2022-11-10T19:00:00.000Z'
	  AND "<MASKED>" LIKE '<MASKED>'

	  GROUP BY <MASKED>, "<MASKED>"
	         , intvl
	  WINDOW w AS(
	      PARTITION BY <MASKED>, "<MASKED>"
	      ORDER BY time_bucket_gapfill('18000s', time)
	      ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
	  )
	  ORDER BY intvl
	) AS subquery

	GROUP BY intvl
	ORDER BY intvl
	OFFSET 1;
```

Disregard the complexity and performance characteristics of this for now, it's not good and we know that :) The problem that we're seeing is that we are unable to cancel or kill this query when we need to via `pg_cancel_backend` or `pg_terminate_backend`. These calls return immediately and successfully but the query remains running for a long time. The process handling the query can be seen via `top` as well, and while I know it's not the right thing to do we tried a `kill <PID>` on the postgres process handling the query which also had no effect.

I am not well-versed in the internals or postgres or timescale, but I had found some information online a while back that discussed similar problems that were due to the query using too many locks. Looking at the lock count for this query via it's PID shows that it uses a few hundred locks, but even when we tuned the database to increase `max_locks_per_transaction` nothing changed. 

The only other relevant information I could find was around the `CHECK_FOR_INTERRUPTS()` [macro](https://docs.huihoo.com/doxygen/postgresql/miscadmin_8h_source.html). As far as I know there should be no reason for the database to not cancel/kill a query unless there's a bug in the database itself (going off of postgres dev discussions here). I am wondering if timescale is not making use of this macro in all the spots that it should.

Maybe my analysis above is wrong, but the behavior we see with this query is consistent.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14

### What operating system did you use?

Base image of official timescale container

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

With a matching schema and cagg setup that the query would work with run the query for a 15 day time window once that time window is filled with data. The query is of course extremely slow and takes a huge amount of memory to run but the real problem is not being able to cancel/kill it.

**Comment by aaronjwood** [comment]
Something interesting to note: maybe 1 out of 10 times the query is stoppable, the rest of the times it keeps running. I'd also like to add that my observation of it being unstoppable could be one of two things:
1. It is truly unstoppable and the query eventually finishes in 30+ minutes
2. It is stoppable but the query is actually stopped after 30+ minutes and does not actually finish to completion

I have not yet found proof to distinguish which of the above scenarios is the one we're actually hitting.

**Comment by konskov** [comment]
Hi @aaronjwood, thank you for reaching out to us. 

I have not yet tried to reproduce the issue you are facing, will get back to you again, some initial comments though:

As you are probably already aware of, `pg_terminate_backend` and `pg_cancel_backend` send the respective signals to the process with the supplied pid, and then the process is terminated at "a convenient time". So this could also be an issue with regular PG queries. 
Could you please run `pg_blocking_pids` supplying the pid of the long-running query and check what the returned processes are running?
Also, the fact that the query you are using is suboptimal is something to take into consideration too..
