### ISSUE TITLE
How to remove extension in a database

### ISSUE THREAD

**Issue by johnreytanquinco** [timescale/timescaledb#497]
I accidentally configured timescaledb in a wrong database and when I try to backup it using the dbuser I am getting an error message.

```
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema _timescaledb_cache
pg_dump: [archiver (db)] query was: LOCK TABLE _timescaledb_cache.cache_inval_hypertable IN ACCESS SHARE MODE
```
How can I remove/disable this extension from the database?

**Comment by mfreed** [comment]
Have you tried the command `DROP EXTENSION timescaledb;` when you are connected to the database in which you have it installed?

**Comment by johnreytanquinco** [comment]
Oh thank you so much @mfreed ! That was a quick fix!
