### ISSUE TITLE
[Bug]: I don't download timescaledb with yum

### ISSUE THREAD

**Issue by haccolo1** [timescale/timescaledb#4975]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

I don't download with command : yum install -y  timescaledb-2-postgresql-14
![image](https://user-images.githubusercontent.com/83392757/201806697-209961fe-fbff-4154-8b83-46df41eaea84.png)

### TimescaleDB version affected

.

### PostgreSQL version used

14

### What operating system did you use?

Centos 7

### What installation method did you use?

Other, Not applicable

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
help me download timescaledb with yum
```

**Comment by horzsolt** [comment]
Hi @haccolo1 
Thanks for reaching out. I tried the installation on a clean CENTOS system, and it went well without any issues. Based on the error message you pasted above, I think your system couldn't reach the network to download the installation packages. Please check your local network settings and try the installation again, it should work.

**Comment by haccolo1** [comment]
> Hi @haccolo1 Thanks for reaching out. I tried the installation on a clean CENTOS system, and it went well without any issues. Based on the error message you pasted above, I think your system couldn't reach the network to download the installation packages. Please check your local network settings and try the installation again, it should work.
hello Sir, thanks for reply. I have problem password authentication for multi-node, I also take result " failed: fe_sendauth: no password supplied " for command  "CALL distributed_exec($$ CREATE ROLE testrole PASSWORD 'internalpass' LOGIN $$); "

**Comment by haccolo1** [comment]
Hi @horzsolt , thanks for reply. I have problem password authentication for multi-node, I also take result " failed: fe_sendauth: no password supplied " for command "CALL distributed_exec($$ CREATE ROLE testrole PASSWORD 'internalpass' LOGIN $$); "

**Comment by mkindahl** [comment]
> Hi @horzsolt , thanks for reply. I have problem password authentication for multi-node, I also take result " failed: fe_sendauth: no password supplied " for command "CALL distributed_exec($$ CREATE ROLE testrole PASSWORD 'internalpass' LOGIN $$); "

Hi @haccolo1,

Could you please file that as a separate issue? It would require more information to sort out what problem you're running into and it would be good to close this issue if the original problem that seemed to be related to network issues was resolved.

**Comment by horzsolt** [comment]
Since there is nothing to do with the original problem, I am closing it now.
