### ISSUE TITLE
[Bug]: TS fails when deleting rows

### ISSUE THREAD

**Issue by amilajack** [timescale/timescaledb#4981]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Adaptive chunking, Data node

### What happened?

selecting chunks passes:
```sql
select * from t where col is null
```

but deleting fails:
```sql
delete from t where col is null
```

with error:
```
unexpected chunk type 4 for chunk _hyper_1_10_chunk
```

the hypertable `t` has a compression policy.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

ubuntu x86_64

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
unexpected chunk type 4 for chunk _hyper_1_10_chunk
```

### How can we reproduce the bug?

```bash
unsure if this is reproducible but here's what I did

1. create hypertable
2. enable hypertable w/ compression 
3. delete rows
```

**Comment by konskov** [comment]
hi @amilajack , thank you for reaching out. I have not been able to reproduce the issue so far. 
Could you please provide some more information on your setup so we can construct a reproduction case for this issue or ideally some reproduction steps? 

It would be useful to know the following, if it's possible to share: 
* Your hypertable definition. 
* I also understand you are using multinode, can you confirm that's the case? 
* Your compression settings

Thank you!

**Comment by amilajack** [comment]
I've truncated the table to workaround this
