### ISSUE TITLE
undefined dblink_disconnect

### ISSUE THREAD

**Issue by zedalaye** [timescale/timescaledb#5]
Using today's head :

tutotsdb=# select setup_db();
ERREUR:  n'a pas pu charger la bibliothèque « /usr/lib/postgresql/9.6/lib/timescaledb.so » : /usr/lib/postgresql/9.6/lib/timescaledb.so: undefined symbol: dblink_disconnect

(ERROR: cannot load library /usr/lib/...)

**Comment by zedalaye** [comment]
Same error with make installcheck :
```
03:59:51 {master} ~/Sources/TimescaleDB$ PGPASSWORD=pgpass make installcheck
/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/9.6/bin'    --inputdir=test --outputdir=test --launcher=test/runner.sh --host=localhost --port=5432 --user=postgres --load-language=plpgsql --load-extension=dblink --load-extension=postgres_fdw --load-extension=hstore --load-extension=timescaledb --dbname=contrib_regression_timescaledb alternate_users create_hypertable ddl ddl_errors ddl_single delete drop_chunks drop_rename_hypertable insert insert_single pg_dump sql_query tablespace timestamp update
(using postmaster on localhost, port 5432)
============== dropping database "contrib_regression_timescaledb" ==============
DROP DATABASE
============== creating database "contrib_regression_timescaledb" ==============
CREATE DATABASE
ALTER DATABASE
============== installing plpgsql                     ==============
CREATE LANGUAGE
============== installing dblink                      ==============
CREATE EXTENSION
============== installing postgres_fdw                ==============
CREATE EXTENSION
============== installing hstore                      ==============
CREATE EXTENSION
============== installing timescaledb                 ==============
ERROR:  could not load library "/usr/lib/postgresql/9.6/lib/timescaledb.so": /usr/lib/postgresql/9.6/lib/timescaledb.so: undefined symbol: dblink_disconnect
command failed: "/usr/lib/postgresql/9.6/bin/psql" -X -c "CREATE EXTENSION IF NOT EXISTS \"timescaledb\"" "contrib_regression_timescaledb"
/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/pgxs.mk:272 : la recette pour la cible « installcheck » a échouée
make: *** [installcheck] Erreur 2
```

**Comment by cevian** [comment]
Did you set shared_preload_libraries = 'dblink,timescaledb' in postgresql.conf?

**Comment by zedalaye** [comment]
Yes I did. It "worked" the first time with I created the 'tutotsdb' database but I got other errors. I disconnected the session and when I tried to launch the regression tests I got this error.

**Comment by cevian** [comment]
Yeah. This really sounds like a shared_preload_libraries issue. When  you install extensions it loads the appropriate libraries in that backend (which is why it worked the first time) but we need the libraries to be preloaded in all backends hence the config option.  Let me know if it does not resolve the issue though. I do think a restart is probably necessary to change this option. 

Alternatively you can explicitly load the library in the backend you are interacting with (https://www.postgresql.org/docs/9.6/static/sql-load.html). You'd first need to load dblink then timescaledb.

**Comment by zedalaye** [comment]
Using "load" did the trick so I agree, a full restart will surely resolve this issue.
