### ISSUE TITLE
[Enhancement]: HA of "append type" INSERTS and SELECTS for distributed hypertables

### ISSUE THREAD

**Issue by TroyDey** [timescale/timescaledb#5000]
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Distributed hypertable, Multi-node

### What does the enhancement do?

There have been discussions around the HA aspects of data nodes in various place and other issues (referenced at the end), but I wanted to provide a proposal for a very limited form of HA that would still fit a common use case.  

**Current State:**

Currently if a data node goes down the entire system becomes unable to service either reads or writes.  The access node will automatically reconnect to a data node when it comes back online which means that if the outage is very short, say a second or two, it may not be too painful, but if the outage is longer the system is basically non-functional.  The only way to bring the system back up is for a system administrator to detach the data node from all distributed hypertables and delete the data node.  The knock on effect of this is that once the data node is back online you need to re-replicate all the data to it which may not be feasible for a very large system.  This proposal is to support a very narrow use case for HA of reads and writes.  

**Specific Use Case:**

The specific use case is to support a system that ingests a very high rate (1 Hz) of metrics (100's-1000), provides near instantaneous access to the most recent (last hour) of data, fast access to moderate term data (1-4 weeks), and only stores data for a short time (1 month).  There are no UPDATE, DELETE, schema changes, or backfills.  The reads are basic aggregations and joins.  The writes are only inserts with latest data.  Occasional small amounts of missed or eventually consistent data are acceptable.  Having under replicated chunks is acceptable due to the short retention period.

**The READ Use Case:**

Using the native replication features of distributed hypertables allows us to ensure that chunks exist on multiple data nodes.  In the case of a data node being down the system can then read the data it needs from other data nodes that have a replica of the chunk(s) in question.  Native replication currently ensures that the data is written to all replicas of a chunk which should mean that when a data node goes down the remaining replicas are consistent.  

**The WRITE Use Case:**

Only writing to the current open chunk.  No UPDATE, DELETE on any chunks, no INSERT on old (closed) chunks.  If a data node goes down continue to allow INSERT to the open chunk or any newly created chunks, otherwise throw an error for any other DML or DDL.  When the data node comes back online the open chunks it had at the time of failure are dropped and it begins to receive new chunks once they are created.  There is no re-replication of the dropped chunks, no re-balancing of chunks.  In addition to allowing the system to continue to process INSERTS to open chunks it allows the data node to rejoin the system without having to drop all of its data, only the chunks it had open at the time of failure.

**Related Requests:**

- Discusses this issue more generally #3463 
- Discusses the idea of a maintenance mode or cordoning a data node #2102 #2103 #2214

### Implementation challenges

The read path should be fairly straightforward since we already know which nodes the chunk and its replicas are on.  For the write path the access node need to track which data nodes have which chunks, and what the open chunks are on each data node.  In the event of a failure the access node would need to preserve which chunks the failed data node had at the time of failure.  When the data node comes back online the access node would need to tell the data node to drop the chunks that were open at the time of failure.  

A more general implementation could be to track, for the failed data node, whether the chunks it has are clean or dirty and then force it to drop any dirty chunks when it comes back online.  This would lead to more under replicated chunks, but could allow more DML operations to take place even when the data node is down.  There could be a flag to enable or disable this behavior.  If there are consistency concerns perhaps there could be a configuration property to control what level of consistency is desired, allowing a tradeoff between HA and consistency.

**Comment by svenklemm** [comment]
multinode has been removed
