### ISSUE TITLE
[Enhancement]: Support Data Tiering on Distributed Hypertables

### ISSUE THREAD

**Issue by TroyDey** [timescale/timescaledb#5001]
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Distributed hypertable

### What does the enhancement do?

Support data tiering on distributed hypertables to place older data on slower storage.  Currently the move_chunk function used to do this only works on regular hypertables, distributed hypertables have a different implementation of the move_chunk function.  We are currently working around this by writing our own data tiering job which we distribute and run on each individual data node.  This works because from a data node's perspective the table it has is a regular hypertable.  It would be nice if this functionality was more user friendly to setup and maintain in general, but particularly for distributed hypertables.

**Comment by svenklemm** [comment]
multinode has been removed
