### ISSUE TITLE
[Enhancement]: Reduce DN query string length by making chunk_in() take ranges of chunk IDs

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#5010]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Distributed hypertable

### What does the enhancement do?

A query on a distributed hypertable sends a list of the chunk IDs to include in the query via the `chunks_in` function. When the list of chunk IDs is large, the array of chunk IDs passed to `chunks_in` can be quite large resulting in a very long query string. This could be optimized by having the chunks_in function take an array of int4range types instead.

So, instead of 

```
SELECT "time", device, temp,  FROM public.disttable WHERE _timescaledb_internal.chunks_in(public.disttable.*, ARRAY[6, 7, 8, 11,12])
```
the remote query becomes:

```
SELECT "time", device, temp,  FROM public.disttable WHERE _timescaledb_internal.chunks_in(public.disttable.*, ARRAY['[6, 8]', '[11,12]')
```

Perhaps better, one could also skip the array and use a multi-range data type:

```
SELECT "time", device, temp,  FROM public.disttable WHERE _timescaledb_internal.chunks_in(public.disttable.*, '{[6, 8], [11,12]}')
```

Obviously the benefit is biggest when there are many chunks queried that are adjacent in their chunk IDs.

### Implementation challenges

Generating the ranges on the AN is more complicated than just sending the raw IDs. Likely, the IDs need to be sorted first. When querying a single (or a few) chunks, there might be little benefit of using int4ranges.

**Comment by erimatnor** [comment]
Here's the EXPLAIN from a prototype using multirange type:

```
Custom Scan (AsyncAppend)  (cost=100.00..4545317.00 rows=41180400 width=20)
   Output: hyper."time", hyper.device, hyper.temp
   ->  Append  (cost=100.00..4545317.00 rows=41180400 width=20)
         ->  Custom Scan (DataNodeScan) on public.hyper hyper_1  (cost=100.00..2892910.00 rows=27453600 width=20)
               Output: hyper_1."time", hyper_1.device, hyper_1.temp
               Data node: data_node_1
               Chunks: _dist_hyper_1_2_chunk, _dist_hyper_1_3_chunk, _dist_hyper_1_4_chunk, _dist_hyper_1_5_chunk, _dist_hyper_1_8_
chunk, _dist_hyper_1_9_chunk, _dist_hyper_1_11_chunk, _dist_hyper_1_12_chunk, _dist_hyper_1_13_chunk, _dist_hyper_1_15_chunk, _dist
_hyper_1_17_chunk, _dist_hyper_1_18_chunk, _dist_hyper_1_20_chunk, _dist_hyper_1_21_chunk, _dist_hyper_1_22_chunk, _dist_hyper_1_23
_chunk, _dist_hyper_1_25_chunk, _dist_hyper_1_27_chunk, _dist_hyper_1_29_chunk, _dist_hyper_1_30_chunk, _dist_hyper_1_32_chunk, _di
st_hyper_1_33_chunk, _dist_hyper_1_35_chunk, _dist_hyper_1_36_chunk, _dist_hyper_1_38_chunk, _dist_hyper_1_39_chunk, _dist_hyper_1_
41_chunk, _dist_hyper_1_42_chunk, _dist_hyper_1_44_chunk, _dist_hyper_1_45_chunk
               Remote SQL: SELECT "time", device, temp FROM public.hyper WHERE _timescaledb_internal.chunks_in(public.hyper.*, '{[1
,30]}')
         ->  Custom Scan (DataNodeScan) on public.hyper hyper_2  (cost=100.00..1446505.00 rows=13726800 width=20)
               Output: hyper_2."time", hyper_2.device, hyper_2.temp
               Data node: data_node_2
               Chunks: _dist_hyper_1_1_chunk, _dist_hyper_1_6_chunk, _dist_hyper_1_7_chunk, _dist_hyper_1_10_chunk, _dist_hyper_1_1
4_chunk, _dist_hyper_1_16_chunk, _dist_hyper_1_19_chunk, _dist_hyper_1_24_chunk, _dist_hyper_1_26_chunk, _dist_hyper_1_28_chunk, _d
ist_hyper_1_31_chunk, _dist_hyper_1_34_chunk, _dist_hyper_1_37_chunk, _dist_hyper_1_40_chunk, _dist_hyper_1_43_chunk
               Remote SQL: SELECT "time", device, temp FROM public.hyper WHERE _timescaledb_internal.chunks_in(public.hyper.*, '{[1
,15]}')
(13 rows)
```

This compresses the chunk IDs really well when they are in a range. This is typically the case on multi-node setups where you have one distributed hypertable. However, that's not always the case and then the local chunk IDs of one hypertable might not be align into a range and a multi-range will add a lot of overhead instead as every ID becomes `[1,1], [3,3], ...`

**Comment by erimatnor** [comment]
Ideally, one would like to have something that only compresses the chunk IDs when possible, but does not add overhead otherwise:

```
_timescaledb_internal.chunks_in(public.hyper.*, 1-2, 4-7, 10, 12-14,18 ')
```
However, that probably requires parsing a text field or inventing a custom type.

**Comment by svenklemm** [comment]
multinode has been removed
