### ISSUE TITLE
[Bug]: Support TRUNCATE/DROP on distributed chunks

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#5019]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing, Multi-node

### What happened?

Issuing a `DROP <chunk>` on a distributed hypertable only drops the local chunk (foreign) table on the access node and doesn't actually drop the chunk(s) on data nodes. This  causes an issue if data is later inserted into the same chunk region since the chunk will be fail to be created on the data nodes due to a conflict with the old (no-dropped) chunk.

`TRUNCATE <chunk>` has a similar issue just raising an error that it is not supported.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.6

### What operating system did you use?

Ubuntu 22.10

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
postgres=# select show_chunks('hyper');
                 show_chunks                 
---------------------------------------------
 _timescaledb_internal._dist_hyper_1_1_chunk
(1 row)

postgres=# select * from _timescaledb_internal._dist_hyper_1_1_chunk;
          time          | device | temp 
------------------------+--------+------
 2022-10-17 19:01:00+02 |      1 |    1
(1 row)

postgres=# TRUNCATE _timescaledb_internal._dist_hyper_1_1_chunk;
ERROR:  cannot truncate foreign table "_dist_hyper_1_1_chunk"

postgres=# DROP TABLE _timescaledb_internal._dist_hyper_1_1_chunk;
ERROR:  "_dist_hyper_1_1_chunk" is not a table
HINT:  Use DROP FOREIGN TABLE to remove a foreign table.
postgres=# DROP FOREIGN TABLE _timescaledb_internal._dist_hyper_1_1_chunk;
DROP FOREIGN TABLE

postgres=# INSERT INTO hyper VALUES ('2022-10-17 19:01:00+02', 1, 1);
ERROR:  chunk creation failed on data node "data_node_1"
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
