### ISSUE TITLE
Fix Dist Caggs refresh when DN is down

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#5026]
When a DN is down, the refresh of a Dist Cagg fails currently. 

* What we really care about is whether all chunks in the refresh range actually has a replica. This might not be true even when replication_factor > 1. If one of the chunks doesn't have a replica on a node that is still available, this command should fail.

* If a chunk is truncated, we should only add invalidations on the nodes where the chunk exists. The right thing to do here is to find all the nodes that have a chunk in the range and run the command only on those nodes. But that's obviously more complicated.

* When refreshing we need to get the ranges to refresh. If a DN is down we might not get those invalidated ranges from that node, which means we might not refresh in that range.

We can also take a look at some more review comments related to this from Erik on https://github.com/timescale/timescaledb/pull/4966

**Comment by svenklemm** [comment]
multinode has been removed
