### ISSUE TITLE
Querying partition on a hypertable

### ISSUE THREAD

**Issue by arriqaaq** [timescale/timescaledb#503]
I have created a simple table in postgres, and have added a timestamptz field, my configuration being 2CPU with 8GB  RAM, and have inserted nearly 400 million records into the table. I have given a chunk size of 1 hour, which I assume acts like a partition. Could I know how to query for a particular hour partition and not scan through all the rows?

Also documentation on the setup would help for new postgres users. All my queries which have group by clauses are taking more than 10 mins, and I hardly see the CPU being utilized. Could you guys suggest what I am doing wrong?

P.S I am planning to use Timescaledb instead of druid with a load of 100 million records in a day

**Comment by arriqaaq** [comment]
Any ideas anyone? Near a billion records chunked day wise and still can't query data for a day, trying with a 52G RAM, 16 core CPU machine, with postgres tuned using pgtune. Guys need help understanding this

@kev009 @cevian

**Comment by RobAtticus** [comment]
I am not sure I follow why you can't query for a particular day. Usually you would do this by doing a WHERE clause, e.g.,:
`SELECT * FROM hypertable WHERE timestamp >= '2016-01-01 00:00:00' AND time < '2016-01-02 00:00:00'`

The planner knows to exclude the chunks/partitions that don't have any data related to that date so the query will only look at those that do rather than the whole table.

**Comment by arriqaaq** [comment]
Hey @RobAtticus ,

Basically I'm writing data in chunks of an hour, and when I EXPLAIN ANALYZE my query to partition an hour's data, it still reads from multiple chunks.

I've just load tested this timescaledb @1billion rows, and querying has drastically slowed down to 30-40 minutes for simple bucketing/windowing functions. 

pgtuned my configuration, RAM 60 Gigs, 16 core machine, don't see much difference on a bigger machine too. Trying to understand how to use it efficiently

**Comment by RobAtticus** [comment]
I guess we'll need more information. For example, if you could give the output of:
`SELECT * FROM chunk_relation_size_pretty('hypertable_name');`

Along with the `\d+ hypertable_name` and the `EXPLAIN ANALYZE` of the query you're trying. It should definitely be excluding the chunks if they contain times not relevant to the WHERE query.

Will cc @davidkohn88 and @cevian so they are aware as well

**Comment by RobAtticus** [comment]
@arriqaaq , any follow up on this?

**Comment by RobAtticus** [comment]
I'm going to close this, please feel free to re-open if there is more to discuss.
