### ISSUE TITLE
[Bug]: 'chunks_detailed_size()' returns exception because of missing relation to internal chunk table

### ISSUE THREAD

**Issue by bruegth** [timescale/timescaledb#5051]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

chunks_detailed_size() returned with an exception that the Table not exists.

Unfortunately I can't say if the table exists or not at this moment because of DataRetention Settings.

I wondering that the table not exists even with this if statement here: https://github.com/timescale/timescaledb/blob/2.3.x/sql/size_utils.sql#L319
  

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

11

### What operating system did you use?

Ubuntu 18.04

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
"exception": {
      "ClassName": "Npgsql.PostgresException",
      "Message": "42P01: relation \"_timescaledb_internal._hyper_2_125_chunk\" does not exist",
      "Data": {
        "Severity": "ERROR",
        "InvariantSeverity": "ERROR",
        "SqlState": "42P01",
        "MessageText": "relation \"_timescaledb_internal._hyper_2_125_chunk\" does not exist",
        "Where": "SQL function \"chunks_local_size\" statement 1\nPL/pgSQL function chunks_detailed_size(regclass) line 23 at RETURN QUERY",
        "File": "namespace.c",
        "Line": "418",
        "Routine": "RangeVarGetRelidExtended"
      },
}
```

### How can we reproduce the bug?

```bash
I can't reproduce this Bug. Come up twice since 8 months.
```

**Comment by sb230132** [comment]
Hi @bruegth 
I understand that the issue seem to happen randomly which is even harder for us to diagnose the problem.
chunks_detailed_size() fetches all chunks associated with a hypertable and return the statistics. I dont see any possibility of
this function returning an incorrect chunk name. 

However it would be good to know more details about this issue, by knowing what does these tables hold in your setup. _timescaledb_catalog.hypertable and _timescaledb_internal.hypertable_chunk_local_size

**Comment by svenklemm** [comment]
2.3.1 is a very old version can you reproduce this on a more recent version?

**Comment by bruegth** [comment]
@svenklemm 
Me:
> ```shell
> I can not reproduce this Bug. Come up twice since 8 months.
> ...
> So since 2022-05-25 'chunks_detailed_size()' was called 170 times and two calls of them returning the exception above.
> ```

You:
> 2.3.1 is a very old version can you reproduce this on a more recent version?

Okay, I will change the version and come back in 8 months to you, hopefully then the version of today is not too old again ;-)

Joking apart, did you see any commits between 2.3.1 and current version, that could maybe fix that exception in that function?

But otherwise, feel free to close this issue, because I see it that is nearly impossible to get an idea how this could happen.

**Comment by svenklemm** [comment]
Hmm I guess this could potentially happen if a retention policy is running while you call chunks_detailed_size. Have to doublecheck. Do you have retention policies?

**Comment by bruegth** [comment]
> Hmm I guess this could potentially happen if a retention policy is running while you call chunks_detailed_size. Have to doublecheck. Do you have retention policies?

Yes I have a data retention policy on that table. Mostly a timespan between 30 - 100 weeks.

**Comment by fabriziomello** [comment]
@bruegth in release 2.9.0 we improved the performance of this functions avoiding unneeded projections and relation size calculations and this change also make this function call less susceptible to race conditions. See the PR #4794

**Comment by bruegth** [comment]
Okay, for older versions I now handle exception accordingly.
