### ISSUE TITLE
[Bug]: compress_chunk/decompress_chunk giving error: "must be owner of hypertable"

### ISSUE THREAD

**Issue by shhnwz** [timescale/timescaledb#5056]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

Customer has defined a custom role "user_for_inserts"; hypertable created as "tsdbadmin" user, also "tsdbadmin" defined compression policy (add_compression_policy(..)) and granted necessary privileges so that "user_for_inserts" can perform data ingestions.

However, when "user_for_inserts" attempts to decompress_chunk('chunk_name'), presented with error:

`ERROR:  must be owner of hypertable "long_term_raw_data"`

**Script to reproduce the error:**
[create_test_schema_and_user_for_inserts.sql.txt](https://github.com/timescale/timescaledb/files/10176283/create_test_schema_and_user_for_inserts.sql.txt)

### TimescaleDB version affected

2.7.1

### PostgreSQL version used

14.5

### What operating system did you use?

 Ubuntu 20.04 x64

### What installation method did you use?

Source

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
\timing
-- initally connected as tsdbadmin
create schema test_schema;

create role user_for_inserts with login password 'pass123';

grant usage on schema "_timescaledb_internal" to user_for_inserts;

grant usage on schema test_schema to user_for_inserts;

drop table test_schema.long_term_raw_data cascade;

create table test_schema.long_term_raw_data (
time timestamptz not null,
value double precision );

select from create_hypertable('test_schema.long_term_raw_data','time', chunk_time_interval=> interval '1 day');

alter table test_schema.long_term_raw_data set (timescaledb.compress);

select add_compression_policy('test_schema.long_term_raw_data', interval '5d');

grant select, insert, update on table test_schema.long_term_raw_data to user_for_inserts;

-- connect now as user_for_inserts
\c defaultdb user_for_inserts;

insert into test_schema.long_term_raw_data
select g.t, random() * 100 + 1
from generate_series(now() - interval '3 weeks', now(), interval '500 ms') as g(t);

--- wait a little (all but most recent chunks compressed by policy)
select * from timescaledb_information.chunks
where hypertable_name = 'long_term_raw_data';

--- attempt to decompress a chunk while connected as user_for_inserts
select decompress_chunk('_timescaledb_internal._hyper_14_54_chunk');
-- -- results in the following error 
-- ERROR:  must be owner of hypertable "long_term_raw_data"
```

**Comment by shhnwz** [comment]
For an Index creation, User or Role must be owner or member of owner. 

Verification:
=======

```
postgres=# create table sensor (id integer, time timestamp, cpu integer);
CREATE TABLE
postgres=# grant select, insert, update on table sensor to user_for_inserts;
GRANT
postgres=# \c postgres user_for_inserts
You are now connected to database "postgres" as user "user_for_inserts".
postgres=> create index on sensor(cpu);
2023-01-02 21:03:39.503 IST [249193] ERROR:  must be owner of table sensor
2023-01-02 21:03:39.503 IST [249193] STATEMENT:  create index on sensor(cpu);
ERROR:  must be owner of table sensor

```

Conclusion
=======

As per initial design COMPRESSION and DECOMPRESSION privileges must follow privileges of CREATE INDEX. This is working as per design. All we need is to document it.

**Comment by fabriziomello** [comment]
@shhnwz are u planning to send a PR to the docs team about this issue?
