### ISSUE TITLE
ERROR:  cannot drop view timescaledb_information.jobs because other objects depend on it

### ISSUE THREAD

**Issue by Nes-U** [timescale/timescaledb#5057]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

I have a postgresql 13 with timescaledb extension 2.7.2, i can't update the extension to 2.8 : 

# ALTER EXTENSION timescaledb UPDATE;
ERROR:  cannot drop view timescaledb_information.jobs because other objects depend on it
DETAIL:  view _timescaledb_config.bgw_policy_compress_chunks depends on view timescaledb_information.jobs
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

Any idea to resolve this problem ?

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

13.9

### What operating system did you use?

RedHat 8.4

### What installation method did you use?

RPM

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
Update Timescaledb from version 2.7.2 to 2.8 
dnf update timescaledb*
open postgres session : 
ALTER EXTENSION timescaledb UPDATE;
```

**Comment by SachinSetiya** [comment]
Hi @Nes-U ,

I am assuming you have used -X flag in psql 
`Connect to psql using the -X flag. This prevents any .psqlrc commands from accidentally triggering the load of a previous TimescaleDB version on session startup.`

Can you please confirm it ? In the mean time I will try to reproduce it.

**Comment by Nes-U** [comment]
Yes, i confirm that the -X flag was used in psql

**Comment by jnidzwetzki** [comment]
Hello @Nes-U,

In older TimescaleDB versions, there was a view called `_timescaledb_config.bgw_policy_compress_chunks`. This view should not exist in TimescaleDB 2.7.2 and should have been [migrated and removed](https://github.com/timescale/timescaledb/blob/a4356f342f1732857a1d8057f71219b50f1919b2/sql/updates/1.7.5--2.0.0-rc1.sql#L254) in previous upgrades. Maybe an error occurred during one of these upgrades, which prevented this view from being removed.

I suggest the following to solve the problem:

* Create a backup of this database
* Query the view and see if there are any old compression policies defined
* Run the missing commands from the old upgrade script:
```sql
ALTER EXTENSION timescaledb DROP TABLE _timescaledb_config.bgw_policy_compress_chunks;
DROP TABLE IF EXISTS _timescaledb_config.bgw_policy_compress_chunks;
```
* Perform the upgrade to TimescaleDB 2.8.1
* Check the compression policies and [add](https://docs.timescale.com/api/latest/compression/add_compression_policy/) (if there are any) missing compression policies based on the output of the view query

**Comment by d2inco** [comment]
This worked for me -- although it was a "DROP VIEW... _timescaledb_config.bgw_policy_compress_chunks" instead of "DROP TABLE"

Thank you!  It's been plaguing us for months.
