### ISSUE TITLE
[Bug]: <CREATE MATERIALIZED VIEW doesn't work for timescaledb_14-2.8.1-1.rhel7.x86_64 package which in postgresql repo>

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5064]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

Hello

We installed timescaledb_14-2.8.1-1.rhel7.x86_64.rpm from https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.2-x86_64/ in postgresql 14.5 env

Also add timescaledb to shared_preload_libraries and restarted postgresql and create extension

Once we try to run "CREATE MATERIALIZED VIEW" script of https://docs.timescale.com/getting-started/latest/create-cagg/create-cagg-basics/ showed below error ""

testdb=# CREATE MATERIALIZED VIEW stock_candlestick_daily
testdb-# WITH (timescaledb.continuous) AS
testdb-# SELECT
testdb-#   time_bucket('1 day', "time") AS day,
testdb-#   symbol,
testdb-#   max(price) AS high,
testdb-#   first(price, time) AS open,
testdb-#   last(price, time) AS close,
testdb-#   min(price) AS low
testdb-# FROM stocks_real_time srt
testdb-# GROUP BY day, symbol;
ERROR:  functionality not supported under the current "apache" license
HINT:  Upgrade your license to 'timescale' to use this free community feature.

According https://www.timescale.com/forum/t/upgrade-your-license-to-timescale-to-use-this-free-community-feature/677, we try to add "timescaledb.license_key: 'CommunityLicense'" in configuration file, but still doesn't work, could you please advise how could we configure then can let timescaledb_14-2.8.1-1.rhel7.x86_64.rpm from https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.2-x86_64/ works same as timescale repo packages please? Thank you

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
1. # yum localinstall /tmp/timescaledb_14-2.8.1-1.rhel7.x86_64.rpm
Examining /tmp/timescaledb_14-2.8.1-1.rhel7.x86_64.rpm: timescaledb_14-2.8.1-1.rhel7.x86_64
Marking /tmp/timescaledb_14-2.8.1-1.rhel7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package timescaledb_14.x86_64 0:2.8.1-1.rhel7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================
 Package                                     Arch                                Version                                    Repository                                                         Size
====================================================================================================================================================================================================
Installing:
 timescaledb_14                              x86_64                              2.8.1-1.rhel7                              /timescaledb_14-2.8.1-1.rhel7.x86_64                               11 M

Transaction Summary
====================================================================================================================================================================================================
Install  1 Package

Total size: 11 M
Installed size: 11 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : timescaledb_14-2.8.1-1.rhel7.x86_64                                                                                                                                              1/1
  Verifying  : timescaledb_14-2.8.1-1.rhel7.x86_64                                                                                                                                              1/1

Installed:
  timescaledb_14.x86_64 0:2.8.1-1.rhel7

Complete!


2. #vim /home/sunyi/bg_d2_s23456y_manual_deployment/msp-scm/roles/dco.common.patroni_cluster/templates/postgresql14.yml.j2

        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron,timescaledb'
		
3. create extension timescaledb;

4.
https://docs.timescale.com/getting-started/latest/create-hypertable/

https://docs.timescale.com/getting-started/latest/add-data/

 CREATE MATERIALIZED VIEW stock_candlestick_daily
 WITH (timescaledb.continuous) AS
 SELECT
   time_bucket('1 day', "time") AS day,
   symbol,
   max(price) AS high,
   first(price, time) AS open,
   last(price, time) AS close,
   min(price) AS low
 FROM stocks_real_time srt
 GROUP BY day, symbol;
```

**Comment by jnidzwetzki** [comment]
Hello @yinan8128,

I downloaded the source package of the mentioned RPM from this [URL](https://download.postgresql.org/pub/repos/yum/srpms/14/redhat/rhel-7-x86_64/). According to the build instructions (`timescaledb.spec`), it contains only the Apache-licensed functions (it is compiled with `-DAPACHE_ONLY=1`). So, the license of the build can not be changed.

We also offer TimescaleDB packages for Red Hat Enterprise Linux 7. These packages contain the features that are licensed under the _Timescale License_. You can find the installation instructions for these packages at [this URL](https://docs.timescale.com/install/latest/self-hosted/installation-redhat/).
