### ISSUE TITLE
[Bug]: Scheduled job not start

### ISSUE THREAD

**Issue by KeChen136** [timescale/timescaledb#5068]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

i have created a refresh policy like,

SELECT add_continuous_aggregate_policy('public.xxxxx',
  start_offset => null,
  end_offset => null,
  schedule_interval => INTERVAL '5 minute');

I can find the job and associated id from timescaledb_information.jobs, but the job has never been started.

### TimescaleDB version affected

2.7.2

### PostgreSQL version used

12.11

### What operating system did you use?

CentOS 7

### What installation method did you use?

Not applicable

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
i'm not sure it is a bug, looks more likely a configuration issue to me. but has no idea how to fix it
```

**Comment by jnidzwetzki** [comment]
Hello @KeChen136,

Thank you very much for reaching out. Could you check if you see job/worker related error messages (e.g., `failed to start a background worker`) in the logfile of your PostgreSQL server?  If you see such messages, it would be great if you could post those messages for further diagnosis. 

Have you already followed our job troubleshooting tips, which are described in the [TimescaleDB documentation](https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/troubleshooting/)?

Please note that setting `end_offset` to `NULL` [is not recommended](https://docs.timescale.com/api/latest/continuous-aggregates/add_continuous_aggregate_policy/). However, this setting should not prevent the job from starting.

**Comment by KeChen136** [comment]
Thanks for the quick response. I don't see any words mentioning background worker in the log. i don't even see the job id is mentioned at all.

**Comment by KeChen136** [comment]
still not working after start_background_workers(); I tried to find record in the posgres log, but didn't see any msg related to scheduled job.

**Comment by jnidzwetzki** [comment]
Hello @KeChen136,

Thank you for the update. Could you send us the output of the following query for further investigation?

```sql
SELECT * FROM timescaledb_information.jobs;
```

In addition, might it be possible to share the log file (`postmaster.log`) of your PostgreSQL server? The log file would be very helpful for further troubleshooting.

**Comment by KeChen136** [comment]
from timescaledb_information.jobs, i can see following,

1008,Refresh Continuous Aggregate Policy [1008],0 years 0 mons 0 days 0 hours 1 mins 0.0 secs,0 years 0 mons 0 days 0 hours 0 mins 0.0 secs,-1,0 years 0 mons 0 days 0 hours 1 mins 0.0 secs,_timescaledb_internal,policy_refresh_continuous_aggregate,volfuture_reader,true,"{""end_offset"": ""01:00:00"", ""start_offset"": ""1 day"", ""mat_hypertable_id"": 38}",,_timescaledb_internal,_materialized_hypertable_38
1,Telemetry Reporter [1],0 years 0 mons 0 days 24 hours 0 mins 0.0 secs,0 years 0 mons 0 days 0 hours 1 mins 40.0 secs,-1,0 years 0 mons 0 days 1 hours 0 mins 0.0 secs,_timescaledb_internal,policy_telemetry,postgres,true,,,,

However, timescaledb_information.job_stats is completely empty, has no history of scheduled job no matter whether it succeeded or failed.

**Comment by jnidzwetzki** [comment]
Hello @KeChen136,

Thank you for also checking the contents of the `timescaledb_information.job_stats` table. An empty table indicates that the jobs have not started on your system. The logfile of the PostgreSQL server should contain more detailed information about why a job cannot be started. So, it would be great if you could provide the log file once it is available for further investigation.
