### ISSUE TITLE
Windows Install issues

### ISSUE THREAD

**Issue by bowguy** [timescale/timescaledb#507]
I followed the windows install instructions at:
http://docs.timescale.com/v0.9/getting-started/installation/windows/installation-windows
All instructions went fine until I tried:
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
which resulted in:
ERROR: current extension name is missing
SQL state: XX000
Any ideas?  Thanks

**Comment by RobAtticus** [comment]
What version of PostgreSQL are you trying to install with? We have seen that issue with 9.6.2 and typically upgrading to the latest 9.6 release (9.6.8) fixed the issue.

**Comment by bowguy** [comment]
Wow.  Beta1.  Didn't realize this.  I will upgrade and try again.
Thanks

**Comment by bowguy** [comment]
That fixed it. Thanks

**Comment by pratikpparikh** [comment]
@RobAtticus i am facing this with 0.10.1 and postgres 10.3, what would be solution
