### ISSUE TITLE
continuous aggregate (at least min max) on time dimension

### ISSUE THREAD

**Issue by WalkerWalker** [timescale/timescaledb#5076]
### What problem does the new feature solve?

This to me is still a continuous aggregate, but on time dimension. I might want to know some information on the time dimension in certain time bucket.  For example, the first and the last timestamp.

### What does the feature do?

This to me is still a continuous aggregate, but on time dimension.

Just taking the example from the [official doc in continuous aggregate](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/about-continuous-aggregates/) and modifying a bit
The following would tell me the min and max timestamp of certain location.
```
SELECT 
    location,
    max(time), 
    min(time)
FROM temperatures
GROUP BY location;
```

Or even better, The following would tell me the min and max timestamp of certain location on each day. 
```
SELECT 
    time_bucket('1 day', time) as day,
    location,
    max(time), 
    min(time)
FROM temperatures
GROUP BY day, location;
```

Would it be possible to do?

**Comment by iroussos** [comment]
Thank you @WalkerWalker, you can do the second one. just try it out :-) 

Rewriting your query to use the table from our [real-time stock trade data tutorial ](https://docs.timescale.com/getting-started/latest/add-data/) (group by symbol instead of location):

```
tsdb=> \d stocks_real_time
                    Table "public.stocks_real_time"
   Column   |           Type           | Collation | Nullable | Default
------------+--------------------------+-----------+----------+---------
 time       | timestamp with time zone |           | not null |
 symbol     | text                     |           | not null |
 price      | double precision         |           |          |
 day_volume | integer                  |           |          |

[..]

tsdb=> CREATE MATERIALIZED VIEW daily_max_min_time_per_symbol WITH (timescaledb.continuous)
tsdb-> AS SELECT
tsdb->     time_bucket('1 day', time) as day,
tsdb->     symbol,
tsdb->     max(time),
tsdb->     min(time)
tsdb-> FROM stocks_real_time
tsdb-> GROUP BY day, symbol;

NOTICE:  refreshing continuous aggregate "daily_max_min_time_per_symbol"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
CREATE MATERIALIZED VIEW

tsdb=> SELECT * FROM daily_max_min_time_per_symbol WHERE symbol = 'GOOG' order by day;
          day           | symbol |          max           |          min
------------------------+--------+------------------------+------------------------
 2022-08-03 00:00:00+00 | GOOG   | 2022-08-03 23:59:39+00 | 2022-08-03 12:42:54+00
 2022-08-04 00:00:00+00 | GOOG   | 2022-08-04 23:59:14+00 | 2022-08-04 08:00:27+00
 2022-08-05 00:00:00+00 | GOOG   | 2022-08-05 23:59:20+00 | 2022-08-05 08:00:10+00
 2022-08-08 00:00:00+00 | GOOG   | 2022-08-08 23:59:01+00 | 2022-08-08 08:00:09+00

[..]
```

The first query is currently not supported because we need a time bucket function to be included in the continuous aggregate definition, otherwise the query would always execute against the entire hypertable each time.

**Comment by WalkerWalker** [comment]
ah, great.  With the second one in place, we can easily and quickly query the overall min and max from the MATERIALIZED VIEW.  Thanks!

**Comment by WalkerWalker** [comment]
A side question
```
SELECT tableoid::regclass, max(time), min(time) FROM data_store_mmt_ppg GROUP BY tableoid
```
return the first and last timestamp of each chunk?
