### ISSUE TITLE
[Bug]: max_background_workers configuration

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5077]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Hello

timescaledb.max_background_workers (int)
Max background worker processes allocated to TimescaleDB. Set to at least 1 + number of databases in Postgres instance to use background workers. Default value is 16.
https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-config/

For max_background_workers configuration, for example, there are totally 10 databases in Postgres instance but only 1 database is timescaleDB(created extension), max_background_workers should be at least 2 or 11 please? Thank you

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
N.A
```

**Comment by jnidzwetzki** [comment]
Hello @yinan8128,

Thanks for reaching out. From a technical point of view, you need at least one background worker per database with a loaded timescaledb extension. So, the value should be set to at least 2 on your system.
