### ISSUE TITLE
TimescaleDB cloud services in cluster mode, SSL Certificate verification faild

### ISSUE THREAD

**Issue by BennisonDevadoss** [timescale/timescaledb#5084]
### What type of bug is this?

Configuration, Unexpected error

### What subsystems and features are affected?

Access node, Data node

### What happened?

Recently, I have been trying to run the timescaleDB in cluster mode, To do that, I have been following the official document of timescaleDB. I have just created the three instances on the timescaleDB cloud. one for the access node and others for the data node.

First I logged in to the access node service (Which is one of the three instances in my cloud)

SELECT add_data_node('dn1', host => 'wyauh1bnaf.eme3aez07s.tsdb.cloud.timescale.com', port => 38274, password => 'yyyxxxyyyxx');

When I go run the add_data_node query, I got an error.

DETAIL:  connection to the server at "wyauh1bnaf.eme3aez07s.tsdb.cloud.timescale.com" (3.83.34.152), port 38274 failed: SSL error: certificate verify failed

If you know the answer to the SSL certification failed error, please let me know.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

12

### What operating system did you use?

Ubuntu 20.04 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
SELECT add_data_node('dn1', host => 'wyauh1bnaf.eme3aez07s.tsdb.cloud.timescale.com', port => 38274, password => 'yyyxxxyyyxx');

DETAIL:  connection to the server at "wyauh1bnaf.eme3aez07s.tsdb.cloud.timescale.com" (3.83.34.152), port 38274 failed: SSL error: certificate verify failed
```

### How can we reproduce the bug?

```bash
If we run the add_data_node query, the bug can be reproduced
```

**Comment by lkshminarayanan** [comment]
Hi @BennisonDevadoss, Our latest cloud offering provides an option to create a multi node service. If you use that, the multiple instances of Access Node and Data Nodes will be automatically set up for you as per your requirement. You can find more info about that here - https://docs.timescale.com/cloud/latest/cloud-multi-node/

Is that something you are looking for?

**Comment by BennisonDevadoss** [comment]
Thaks for your update @lkshminarayanan, I have followed document as you have mentioned, Even though I got that error "SSL Certificate Verification failed". Is there any other way to find the solution.

**Comment by lkshminarayanan** [comment]
Hi @BennisonDevadoss, did you make sure to select `Multi-node` architecture under `Advanced Configuration` when creating the service? Also, can you please let me know which exact step throws the "SSL Certificate Verification failed" error when you follow the steps given at [Setting up multi-node on Timescale Cloud](https://docs.timescale.com/cloud/latest/cloud-multi-node/#setting-up-multi-node-on-timescale-cloud)?

**Comment by BennisonDevadoss** [comment]
While running the add_data_node query I got the SSL certificate verification failed error. 

`SELECT add_data_node('dn1', host => 'wyauh1bnaf.eme3aez07s.tsdb.cloud.timescale.com', port => 38274, password => 'yyyxxxyyyxx');
`
When I run the above step, I got this error.

**Comment by fabriziomello** [comment]
@BennisonDevadoss here is not the better channel to get help for Timescale Cloud. You should open a ticket in your cloud console instead.
