### ISSUE TITLE
[Flaky test] Active replication slot in dist_move_chunk

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#5087]
### Which test is flaky?

dist_move_chunk

### Since when has the test been flaky?

December 13, 2022

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/3683760340/jobs/6232708029

### Log output

```bash
diff -u /__w/timescaledb/timescaledb/tsl/test/expected/dist_move_chunk.out /__w/timescaledb/timescaledb/build/tsl/test/results/dist_move_chunk.out
--- /__w/timescaledb/timescaledb/tsl/test/expected/dist_move_chunk.out	2022-12-13 08:52:27.476495040 +0000
+++ /__w/timescaledb/timescaledb/build/tsl/test/results/dist_move_chunk.out	2022-12-13 09:00:21.473366254 +0000
@@ -304,314 +304,4 @@
 
 CALL copy_wrapper('_timescaledb_internal._dist_hyper_1_3_chunk', :'DATA_NODE_3', :'DATA_NODE_2');
 CALL move_wrapper('_timescaledb_internal._dist_hyper_1_2_chunk', :'DATA_NODE_2', :'DATA_NODE_1');
-SELECT chunk_name, replica_nodes, non_replica_nodes
    .
    .
    .
-DROP DATABASE :DATA_NODE_3;
+ERROR:  [db_dist_move_chunk_2]: replication slot "ts_copy_4_2" is active for PID 20903
```

**Comment by mkindahl** [comment]
https://github.com/timescale/timescaledb/actions/runs/3874122170/jobs/6605056821

**Comment by akuzm** [comment]
It's the flakiest test of the week:
```
ci_stats=> select url from job natural join test where job_date > now() - interval '1 week' and test_name = 'dist_move_chunk' and test_status = 'failed';
                                     url                                     
─────────────────────────────────────────────────────────────────────────────
```
 https://github.com/timescale/timescaledb/actions/runs/3911527137/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3915863354/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3930781286/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3930781286/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3930781292/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3934836578/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3938470188/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3938470194/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3938539925/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3947122272/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3947122272/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3948918004/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3948918000/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3957809865/attempts/1
 https://github.com/timescale/timescaledb/actions/runs/3963468960/attempts/1

**Comment by jnidzwetzki** [comment]
https://github.com/timescale/timescaledb/actions/runs/4379943887/jobs/7666442863

**Comment by jnidzwetzki** [comment]
https://github.com/timescale/timescaledb/actions/runs/5249736210/jobs/9482872584

**Comment by svenklemm** [comment]
multinode has been removed
