### ISSUE TITLE
[Bug]: unable to specify table schema in add_compression_policy

### ISSUE THREAD

**Issue by LukasJerabek** [timescale/timescaledb#5088]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

If I specify table in add_compression_policy e.g.:

`SELECT add_compression_policy('snapshots', INTERVAL '30 days');`
 it automatically assumes it is public schema. and I get an error:
`Error: pq: function add_compression_policy(unknown, interval) does not exist`
If I specify the schema I need e.g.:
`SELECT add_compression_policy('statements_history.snapshots', INTERVAL '30 days');`
then I get an error:
`Error: pq: function add_compression_policy(unknown, interval) does not exist`

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14

### What operating system did you use?

Rocky linux 8

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Error: pq: function add_compression_policy(unknown, interval) does not exist
```

### How can we reproduce the bug?

```bash
1. create schema other than public
2. create table and make it hypertable
3. try use add_compression_policy on that table.
```

**Comment by sb230132** [comment]
Hi @LukasJerabek 
By default server does a lookup of database objects in schemas specified as part of search path.

Please see that below should work.

```
create schema db;
set search_path to db, public;
create table test_strict (time timestamptz not null, a int, b int);
select create_hypertable('test_strict', 'time');
alter table test_strict set (timescaledb.compress);
select add_compression_policy('test_strict', INTERVAL '30 days');
```

**Comment by LukasJerabek** [comment]
You are right, it was a problem of setting search_path in a tool I use for migrations. Thank you.
