### ISSUE TITLE
Failure to load timescaledb.dll

### ISSUE THREAD

**Issue by bowguy** [timescale/timescaledb#510]
I have two machines that I am trying to install timescaledb.  The first is a Windows 10 PC.  Followed the zip install directions and everything worked perfectly.

The other is a Windows Server 2016 Standard.  I ran the setup.exe from the zip installer and it showed the proper message for a good install.  I changed the line in postgresql.conf to:
shared_preload_libraries = 'timescaledb'

Then I tried to restart postgres and it failed with this message in the event logs:
2018-04-24 09:54:22 PDT FATAL:  could not load library "C:/Program Files/PostgreSQL/9.6/lib/timescaledb.dll": The specified module could not be found.

The file is in the location specified.

Both installs of PostgreSQL are
"PostgreSQL 9.6.5, compiled by Visual C++ build 1800, 64-bit"

Thanks for any help

**Comment by RobAtticus** [comment]
Can you make sure that this exists on your machine?:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Not sure if Win Server 2016 comes with that by default

**Comment by bowguy** [comment]
That seems to have fixed it.
Thanks!

**Comment by amarRajp** [comment]
ERROR:  extension "timescaledb" does not support postgres version 10.0
