### ISSUE TITLE
[Bug]: How to create hyper table by monthly and range is first day of month to last day of month

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5105]
### What type of bug is this?

Other

### What subsystems and features are affected?

Partitioning

### What happened?

Hello,

How to create hyper table by monthly and range is first day of month to last day of month please?

For example:  we create a table with some 2022 December records and 2022 November records, how to set one chunk is 20221101 to 20221130, and another chunk is 20221201 to 20221231 please? Thank you

`CREATE TABLE test_hypertable(
 tid integer,
 bid integer,
 aid integer,
 delta integer,
 mtime timestamp without time zone,
 filler character(22));
 
SELECT create_hypertable('test_hypertable','mtime',chunk_time_interval => INTERVAL '1 month');

INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '1 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '2 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '3 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '4 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '5 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '6 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '7 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '8 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '9 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '10 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '11 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '12 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '13 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '14 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '15 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '16 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '17 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '18 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '19 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '20 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '21 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '22 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '23 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '24 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '25 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '26 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '27 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '28 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '29 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '30 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '31 day'); 

select i FROM show_chunks('test_hypertable') i;
                     i
-------------------------------------------
 _timescaledb_internal._hyper_65_179_chunk
 _timescaledb_internal._hyper_65_180_chunk
(2 rows)

select max(mtime), min(mtime) from _timescaledb_internal._hyper_65_179_chunk;
            max             |            min
----------------------------+----------------------------
 2022-12-18 14:24:55.658221 | 2022-11-24 14:24:55.952612
(1 row)

audit_timescaledb=# select max(mtime), min(mtime) from _timescaledb_internal._hyper_65_180_chunk;
            max             |            min
----------------------------+----------------------------
 2022-11-23 14:24:55.957731 | 2022-11-18 14:24:57.159788
(1 row)`

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
`
CREATE TABLE test_hypertable(
 tid integer,
 bid integer,
 aid integer,
 delta integer,
 mtime timestamp without time zone,
 filler character(22));
 
SELECT create_hypertable('test_hypertable','mtime',chunk_time_interval => INTERVAL '1 month');

INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '1 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '2 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '3 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '4 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '5 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '6 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '7 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '8 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '9 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '10 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '11 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '12 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '13 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '14 day');
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '15 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '16 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '17 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '18 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '19 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '20 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '21 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '22 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '23 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '24 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '25 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '26 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '27 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '28 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '29 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '30 day'); 
INSERT INTO test_hypertable (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '31 day'); 

select i FROM show_chunks('test_hypertable') i;
                     i
-------------------------------------------
 _timescaledb_internal._hyper_65_179_chunk
 _timescaledb_internal._hyper_65_180_chunk
(2 rows)

select max(mtime), min(mtime) from _timescaledb_internal._hyper_65_179_chunk;
            max             |            min
----------------------------+----------------------------
 2022-12-18 14:24:55.658221 | 2022-11-24 14:24:55.952612
(1 row)

audit_timescaledb=# select max(mtime), min(mtime) from _timescaledb_internal._hyper_65_180_chunk;
            max             |            min
----------------------------+----------------------------
 2022-11-23 14:24:55.957731 | 2022-11-18 14:24:57.159788
(1 row)
`
```

**Comment by lkshminarayanan** [comment]
Hi @yinan8128! Thank you for raising this issue. We currently do not support setting custom start and end times for individual chunks and it is not possible to set the range to calendar months either. 

From a user perspective, your query execution and its performance will be mostly identical irrespective of the individual chunks' ranges. Do you have any specific reason for wanting to do this?
