### ISSUE TITLE
[Bug]: <chunk after compression is autovacuum_enabled=false>

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5107]
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression

### What happened?

Hello,

We found that the chunk after compression is autovacuum_enabled=false, is it normal please?

pgbench -i -s 10 -d audit_timescaledb -U audit_user -h localhost -p 5432

psql
\c audit_timescaledb
CREATE INDEX idx_pgbench_history_aid on pgbench_history(aid);

SELECT create_hypertable('pgbench_history','mtime');
NOTICE:  adding not-null constraint to column "mtime"
DETAIL:  Time dimensions cannot have NULL values.
       create_hypertable
--------------------------------
 (133,public,pgbench_history,t)
(1 row)

INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '1 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '2 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '3 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '4 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '5 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '6 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '7 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '8 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '9 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '10 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '11 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '12 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '13 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '14 day');
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '15 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '16 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '17 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '18 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '19 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '20 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '21 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '22 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '23 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '24 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '25 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '26 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '27 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '28 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '29 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '30 day'); 
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (1, 1, 1, 1, CURRENT_TIMESTAMP- interval '31 day'); 

delete from pgbench_history;

select i FROM show_chunks('pgbench_history') i;
                     i
--------------------------------------------
 _timescaledb_internal._hyper_133_255_chunk
 _timescaledb_internal._hyper_133_256_chunk
 _timescaledb_internal._hyper_133_257_chunk
 _timescaledb_internal._hyper_133_258_chunk
 _timescaledb_internal._hyper_133_259_chunk
(5 rows)

\d+ _timescaledb_internal._hyper_133_259_chunk;
                                     Table "_timescaledb_internal._hyper_133_259_chunk"
 Column |            Type             | Collation | Nullable | Default | Storage  | Compression | Stats target | Description
--------+-----------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 tid    | integer                     |           |          |         | plain    |             |              |
 bid    | integer                     |           |          |         | plain    |             |              |
 aid    | integer                     |           |          |         | plain    |             |              |
 delta  | integer                     |           |          |         | plain    |             |              |
 mtime  | timestamp without time zone |           | not null |         | plain    |             |              |
 filler | character(22)               |           |          |         | extended |             |              |
Indexes:
    "_hyper_133_259_chunk_idx_pgbench_history_aid" btree (aid)
    "_hyper_133_259_chunk_pgbench_history_mtime_idx" btree (mtime DESC)
Check constraints:
    "constraint_199" CHECK (mtime >= '2022-11-17 00:00:00'::timestamp without time zone AND mtime < '2022-11-24 00:00:00'::timestamp without time zone)
Inherits: pgbench_history
Access method: heap

ALTER TABLE pgbench_history SET (
  timescaledb.compress,
  timescaledb.compress_orderby = 'mtime DESC'
);

SELECT compress_chunk(i, if_not_compressed=>true)
FROM show_chunks('pgbench_history') i;
               compress_chunk
--------------------------------------------
 _timescaledb_internal._hyper_133_255_chunk
 _timescaledb_internal._hyper_133_256_chunk
 _timescaledb_internal._hyper_133_257_chunk
 _timescaledb_internal._hyper_133_258_chunk
 _timescaledb_internal._hyper_133_259_chunk
(5 rows)

select * from chunk_compression_stats('pgbench_history');
     chunk_schema      |      chunk_name      | compression_status | before_compression_table_bytes | before_compression_index_bytes | before_compression_toast_bytes | before_compression_total_bytes| after_compression_table_bytes | after_compression_index_bytes | after_compression_toast_bytes | after_compression_total_bytes | node_name
-----------------------+----------------------+--------------------+--------------------------------+--------------------------------+--------------------------------+--------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------
 _timescaledb_internal | _hyper_133_255_chunk | Compressed         |                           8192 |                          32768 |                              0 |                          40960|                             0 |                             0 |                          8192 |                          8192 |
 _timescaledb_internal | _hyper_133_256_chunk | Compressed         |                           8192 |                          32768 |                              0 |                          40960|                             0 |                             0 |                          8192 |                          8192 |
 _timescaledb_internal | _hyper_133_257_chunk | Compressed         |                           8192 |                          32768 |                              0 |                          40960|                             0 |                             0 |                          8192 |                          8192 |
 _timescaledb_internal | _hyper_133_258_chunk | Compressed         |                           8192 |                          32768 |                              0 |                          40960|                             0 |                             0 |                          8192 |                          8192 |
 _timescaledb_internal | _hyper_133_259_chunk | Compressed         |                           8192 |                          32768 |                              0 |                          40960|                             0 |                             0 |                          8192 |                          8192 |
(5 rows)

select * from hypertable_compression_stats('pgbench_history');
 total_chunks | number_compressed_chunks | before_compression_table_bytes | before_compression_index_bytes | before_compression_toast_bytes | before_compression_total_bytes | after_compression_table_bytes | after_compression_index_bytes | after_compression_toast_bytes | after_compression_total_bytes | node_name
--------------+--------------------------+--------------------------------+--------------------------------+--------------------------------+--------------------------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------
            5 |                        5 |                          40960 |                         163840 |                              0 |                         204800 |   0 |                             0 |                         40960 |                         40960 |
(1 row)

\d+ _timescaledb_internal._hyper_133_259_chunk;
                                     Table "_timescaledb_internal._hyper_133_259_chunk"
 Column |            Type             | Collation | Nullable | Default | Storage  | Compression | Stats target | Description
--------+-----------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 tid    | integer                     |           |          |         | plain    |             |              |
 bid    | integer                     |           |          |         | plain    |             |              |
 aid    | integer                     |           |          |         | plain    |             |              |
 delta  | integer                     |           |          |         | plain    |             |              |
 mtime  | timestamp without time zone |           | not null |         | plain    |             |              |
 filler | character(22)               |           |          |         | extended |             |              |
Indexes:
    "_hyper_133_259_chunk_idx_pgbench_history_aid" btree (aid)
    "_hyper_133_259_chunk_pgbench_history_mtime_idx" btree (mtime DESC)
Check constraints:
    "constraint_199" CHECK (mtime >= '2022-11-17 00:00:00'::timestamp without time zone AND mtime < '2022-11-24 00:00:00'::timestamp without time zone)
Inherits: pgbench_history
Access method: heap
Options: autovacuum_enabled=false

**Comment by lkshminarayanan** [comment]
Hi @yinan8128! 

This is expected and correct. After compression, the data that used to be in `_timescaledb_internal._hyper_133_259_chunk` would have moved into a compressed chunk and this source chunk will be empty. As this chunk is empty, there is no need to autovacuum and it is disabled. The source chunk stays empty during the entire duration it is in compressed state. If you choose to decompress the chunk, the data will be restored to the source chunk, along with the autovacuum value and in this case  `_timescaledb_internal._hyper_133_259_chunk` value will be restored to true. I'll close this issue as this is an expected behaviour but please let us know if you need any further clarification on this.
