### ISSUE TITLE
Crash at create_hypertable on ARMv6

### ISSUE THREAD

**Issue by bertmelis** [timescale/timescaledb#511]
I'm running a fresh Debian Stretch 32-bit installation on a ARMv6 (Raspberry Pi). I installed Postgresql 9.6 using apt and built Timescale from source (v 0.9.1).
Then I just followed the tutorial on the Timescale website.

The server crashes when running `SELECT create_hypertable('conditions', 'time');`
The cli it gives the following:
```
tutorial=# SELECT create_hypertable('conditions', 'time');
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
```

The log shows this
```
LOG:  server process (PID 7902) was terminated by signal 11: Segmentation fault
DETAIL:  Failed process was running: SELECT create_hypertable('conditions', 'time');
...further info about restarting etc
```

I know ARM is not a supported platform... But it also could be fixed with a minor fix. I'm open to suggestions and further debugging info.

**Comment by mfreed** [comment]
Hi @bertmelis Any chance you can build with debug symbols on and generate a core dump during the crash?  Would be highly useful if you can send it our way (e.g., email to us at support@ and send the dump via send.firefox.com).

Thanks!

**Comment by bertmelis** [comment]
I've sent the link to the coredump to support@

I'm standby for further information.

**Comment by mfreed** [comment]
@bertmelis Fixes to some 32-bit architecture issues have been released in the recent 0.9.2 version.  Please let us know if these solve your problems.

**Comment by bertmelis** [comment]
The issue is gone on version 0.9.2

Many thanks for the work!

**Comment by jsteenkamp** [comment]
@bertmelis be interested in any comments on performance on Raspberry Pi. I have [Model 3 B+](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/) which is ARMv8 64 bit. Thanks.
