### ISSUE TITLE
timescale and schema_triggers extensions do not work together..

### ISSUE THREAD

**Issue by vmanohar1** [timescale/timescaledb#512]
I am using V0.7.1 timescale version.
I notice  that https://github.com/CartoDB/pg_schema_triggers and timescale extensions do not work together.. 
(1) with - shared_preload_libraries = 'timescaledb,schema_triggers', you get failure in starting the instance --->
"FATAL:  a ProcessUtility hook is already installed.
LOG:  database system is shut down"
(2) If you reverse the order in the config (from 1 above), it will start instance but when you do 1 insert in timescaled table, it kills PG process(es). Better way in that case is to restart PG instance..
Please review at the earliest and suggest a possible fix for it.. Thanks.

**Comment by cevian** [comment]
This is caused by a problem in Carto https://github.com/CartoDB/pg_schema_triggers/pull/5
