### ISSUE TITLE
[Bug]: pgBouncer no longer operates on Hypertables?

### ISSUE THREAD

**Issue by bruegth** [timescale/timescaledb#5122]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Command processing, Other

### What happened?

|Insert | Select | Result|
| -----------| ------------ | ----- |
| pgBouncer | pgBouncer | okay |
| pgBouncer | timescale | wrong (no) |
| timescale | pgbouncer | wrong (no) |
| timescale | timescale | okay |

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

11

### What operating system did you use?

Ubuntu focal

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Use postgres in front of timescale 

Make Insert and Select Statements in all combinations.
```

**Comment by lkshminarayanan** [comment]
Hi @bruegth, thank you filing the bug. Does the issue also occur with the latest versions of PostgreSQL/timescaledb? 
Also, can also you please let us know the version of pgbouncer you used, so that we can try reproducing it?

**Comment by bruegth** [comment]
I will test it with current version next year. pgBouncer Version 1.17 and 1.18 was used.

**Comment by lkshminarayanan** [comment]
Hi @bruegth, I tried insert and select queries with pgBouncer 1.17, Postgres 11.18 and timescale 2.3.1 but I'm unable to reproduce the issue. I did try all combinations as you've mentioned in the bug but I was able to read the rows inserted via pgbouncer without it and vice versa. I also tried reproducing with the latest versions - postgres 15.1 and timescale 2.9.0 - things work as expected there as well.

It might be possible that a particular configuration is triggering this issue. Can you share your postgres/pgbouncer config with us? It will also be helpful if you can share the exact queries you used reproduce the issue.

**Comment by bruegth** [comment]
I also can't reproduce this error on an fresh installation.
The Instance which shows this error was migrated from timescale 1.5.3-pg11 to 2.3.1-pg11.

Here a strange behavior of timescaledb_information view on that Instance (different number of chunks when connected thru pgBouncer):
![image](https://user-images.githubusercontent.com/1318408/210223736-58306056-f718-4fd3-a235-a6d43e8e5dfd.png)

pgBouncer ini:
[pgbouncer.ini.txt](https://github.com/timescale/timescaledb/files/10331179/pgbouncer.ini.txt)

postgres.conf:
[postgres.conf.txt](https://github.com/timescale/timescaledb/files/10331185/postgres.conf.txt)

postgres startup (with upgrade script):
[postgres_startup.txt](https://github.com/timescale/timescaledb/files/10331252/postgres_startup.txt)

Maybe something related to access rights after migration?

**Comment by bruegth** [comment]
![image](https://user-images.githubusercontent.com/1318408/210239937-0b113ebe-d760-4e6d-ae76-22fe44ec2405.png)

pgBouncer and Timescale running on same host in different containers.

Maybe same as https://github.com/pgbouncer/pgbouncer/issues/642

**Comment by lkshminarayanan** [comment]
Hi @bruegth! Is it possible for you to upgrade to the latest version of Timescale and test if the issue still occurs?

**Comment by bruegth** [comment]
@lkshminarayanan 
Yes, but not so fast because that instance used for production and we need to follow upgrade path 2.3.1-pg11 -> 2.3.1-pg13 -> 2.9.0-pg13
So estimated date until 2.9.0 on that instance will be approx. in summer this year.

**Comment by bruegth** [comment]
@lkshminarayanan Thanks for your support, pgBouncer.ini was wrong.
