### ISSUE TITLE
[Bug]: When performing a clean install on Windows, some files are missing for PG15

### ISSUE THREAD

**Issue by benneharli** [timescale/timescaledb#5125]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Build system, Packaging, Platform/OS

### What happened?

Refer to this post: https://timescaledb.slack.com/archives/C5X6UVB24/p1671581588175699

### TimescaleDB version affected

2.9.0

### PostgreSQL version used

15.1

### What operating system did you use?

Windows 10

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
1. Install PG 15 from EDB
2. Install TS 2.9.0
```

**Comment by svenklemm** [comment]
We test our package installation in CI and no files seem  to be missing.
https://github.com/timescale/timescaledb/actions/runs/3768910545

You can find the code for the windows package test here: https://github.com/timescale/timescaledb/blob/main/.github/workflows/windows-packages.yaml

**Comment by benneharli** [comment]
Sorry, I guess I wasn't being 100% clear. The issue is as such not files missing in the TimescaleDB installer. You include the files you always did. The issue is, that you're relying on libraries, which are no longer included in the Windows installer from EnterpriseDB.

The happened "back then" as shown in the linked post. The error message is not that clear though.

Link to installer: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

Select the 15.1 installer

The files missing from the /bin directory are: libcrypto-1_1-x64.dll, libssl-1_1-x64.dll

So the issue is, that you either rely on libraries which are now deprecated in the installers delivered by EnterpriseDB, or that you liaise with EnterpriseDB to get the two files included again in their distribution.

![image](https://user-images.githubusercontent.com/11926159/209485842-b329c0f9-ce03-4646-b41e-59a002031240.png)

**Comment by bmotmans** [comment]
The problem is that the version of libssl and libcrypto shipped with PG15 on Windows is different than the ones TimescaleDB is compiled with.

PG15 ships with libssl-3-x64.dll and libcrypto-3-x64.dll
TimescaleDB 2.9.1 links to libcrypto-1_1-x64.dll and libssl-1_1-x64.dll

The workaround for this problem is fairly simple: Install PG14 + copy the missing dll's from the bin folder to the PG15 bin folder.

![image](https://user-images.githubusercontent.com/261057/209945974-6adfa1c1-8d3a-4ece-9ed3-861fc23e59fb.png)

**Comment by horzsolt** [comment]
@benneharli (and anyone who faces the same issue), the missing dependencies can be downloaded from here:
https://wiki.openssl.org/index.php/Binaries (if there is no existing PG14 instance available to copy the missing files from).

@svenklemm The tests passed as the image Github [provides ](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md)for Windows has OpenSSL 1.1.1 pre-installed. So it means we should update our Windows packaging for PG15. I will create an internal Github issue for this effort.

**Comment by mahipv** [comment]
Currently openssl 1.1.1 is a prerequisite on windows installation, it has been updated in the docs.
https://docs.timescale.com/self-hosted/latest/install/installation-windows/#prerequisites
