### ISSUE TITLE
[Bug]: CAGG on CAGG Error

### ISSUE THREAD

**Issue by ssmoss** [timescale/timescaledb#5126]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

When attempting to create a CAG using a `1 HOUR` bucket based on a CAG with a `5 MINUTE` bucket the following error is thrown:
```
[2022-12-24 23:40:15] [22P01] ERROR: floating-point exception
[2022-12-24 23:40:15] Detail: An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
```

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14.6

### What operating system did you use?

psql (15.1 (Ubuntu 15.1-1.pgdg20.04+1), server 14.6 (Ubuntu 14.6-1.pgdg20.04+1))

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
[2022-12-24 23:40:15] [22P01] ERROR: floating-point exception
[2022-12-24 23:40:15] Detail: An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
```

### How can we reproduce the bug?

```bash
DROP MATERIALIZED VIEW IF EXISTS bug_timescaledb_table_1h;
DROP MATERIALIZED VIEW IF EXISTS bug_timescaledb_table_5m;
DROP TABLE             IF EXISTS bug_timescaledb_table;

CREATE TABLE bug_timescaledb_table (
    recorded_at    TIMESTAMPTZ NOT NULL,

    a VARCHAR(50),
    b VARCHAR(50),

    c REAL,
    d REAL,
    e REAL,

    f REAL,
    g REAL,
    h REAL
);

SELECT CREATE_HYPERTABLE(
    'bug_timescaledb_table',
    'recorded_at',
    chunk_time_interval => INTERVAL '30 DAY'
);

CREATE MATERIALIZED VIEW bug_timescaledb_table_5m
    WITH (timescaledb.continuous) AS
        SELECT
            TIME_BUCKET('5 MINUTE', recorded_at, 'US/Pacific') AS recorded_at,
            a AS a,
            MIN(c) AS c_min
        FROM bug_timescaledb_table
        GROUP BY 1, 2
        WITH NO DATA;

CREATE MATERIALIZED VIEW bug_timescaledb_table_1h
    WITH (timescaledb.continuous) AS
        SELECT
            TIME_BUCKET('1 HOUR', recorded_at, 'US/Pacific') AS recorded_at,
            a AS a,
            MIN(c_min) AS c_min
        FROM bug_timescaledb_table_5m
        GROUP BY 1, 2
        WITH NO DATA;
```
The error will be thrown when attempting to create `bug_timescaledb_table_1h`.

**Comment by fabriziomello** [comment]
@ssmoss the PR #5130 fixes the problem. The current workaround is not use the `Timezone` in the `time_bucket` function for your case.

**Comment by ssmoss** [comment]
@fabriziomello Thank you so much or fixing this so quickly. Also thanks for the work around note but for me I am going to need the timezone as the main purpose for this is to do weekly, monthly, and yearly roll ups. Figures crossed this get released soon!

**Comment by ssmoss** [comment]
@fabriziomello I am not sure this is totally fixed yet:

```
[0A000] ERROR: cannot create continuous aggregate with incompatible bucket width Detail: Time bucket width of "public.timescaledb_1y" [1 year] should be multiple of the time bucket width of "public.timescaledb_1mon" [1 mon].
[0A000] ERROR: cannot create continuous aggregate with incompatible bucket width Detail: Time bucket width of "public.timescaledb_1y" [1 year] should be multiple of the time bucket width of "public.timescaledb_1d" [1 day].
```

I tried to make a CAGG using a `1 YEAR` bucket from both a `1 MONTH` and `1 DAY` bucket and the above error was generated. Going from raw -> 5m -> 1h -> 1day -> 1month all worked as expected.
