### ISSUE TITLE
[Bug]: timescaledb hypertable insert into too slow

### ISSUE THREAD

**Issue by seunofk** [timescale/timescaledb#5129]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Query executor

### What happened?

Hello. Team.

To test timescale db performance, after creating a dummy table with 100 million date data through pgbench, hypertable is created and data is being inserted through insert into select.
But it's too slow.
I'm not sure what the problem is.
When I run insert into, I know that it is performed on 1 cpu, but I don't understand why it is running for so long.
Is there anything that can be improved?

Server Spec is CPU 48 Core, Memory 256 GB, SDD 10TB.
Other services are not used for timescale db performance test.

Thanks,

### TimescaleDB version affected

2.9.0-dev

### PostgreSQL version used

14.2

### What operating system did you use?

CentOS 7.9

### What installation method did you use?

RPM

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
--105819287
select count(*) from public.pgbench_history;

-- Create Dummy 1 table to use Ramdom function by date based on mtime (3min 3s)
CREATE TABLE test_ori_1 
as
select * from public.pgbench_history;

-- Vacuum is mandatory after Ctas 
vacuum (verbose, PARALLEL 16) test_ori_1;

--100 million date changes(9min 53s)
update test_ori_1
SET mtime = NOW() - '1 day'::INTERVAL * ROUND(RANDOM() * 10000);

--create hypertable
SELECT create_hypertable('test_ori_1_time', 'mtime');

-- insert into running (3 hours 30 minutes elapsed In progress)
insert into test_ori_1_time select * from test_ori_1;
```

### How can we reproduce the bug?

```bash
.
```

**Comment by fabriziomello** [comment]
Hey @seunofk thanks for reaching out. What parameters did you used in `pgbench` to initialize the data??

**Comment by seunofk** [comment]
Hi. @fabriziomello 

Thanks for the comment.

The option I used is this

pgbench -h localhost -p 5432 -U postgres -c 32 -n -j 32 -t 90000000 postgres

After running pg_bench, I run vacuum separately.

**Comment by seunofk** [comment]
Hi. @fabriziomello

Thanks for the comment.

The option I used is this

pgbench -h localhost -p 5432 -U postgres -c 32 -n -j 32 -t 90000000 postgres

After running pg_bench, I run vacuum separately.

**Comment by fabriziomello** [comment]
> 
> pgbench -h localhost -p 5432 -U postgres -c 32 -n -j 32 -t 90000000 postgres
> 

Actually I need the options you used to `initialize` the pgbench database (create tables and generate data) using `-i`, `-s`, etc.

**Comment by seunofk** [comment]
> 
sorry I am late.

I created pgbench in the normal way.

pgbench -h localhost -p 5432 -U postgres -i postgres

The -s option is not used. 

Thanks.

**Comment by seunofk** [comment]
@fabriziomello 

sorry I am late.

I created pgbench in the normal way.

pgbench -h localhost -p 5432 -U postgres -i postgres

The -s option is not used.

Thanks.

**Comment by fabriziomello** [comment]
@seunofk did u tried different chunk sizes changing the chunk time interval??? Have a look in this [session in docs](https://docs.timescale.com/api/latest/hypertable/create_hypertable/#sample-usage) specially scrolling down to the `Best practices` section.

Another way to improve the ingestion performance is using our parallel copy tool: https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/ingest-parallel-copy/

**Comment by alteest** [comment]
Great support. No help, just close ticket!
