### ISSUE TITLE
SUM of int4s becomes int8 in cagg

### ISSUE THREAD

**Issue by pehlert** [timescale/timescaledb#5138]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

The following statements create a simple cagg for the `events` table's `running_time_delta` column:

```
CREATE TABLE "public"."events" (
    "timestamp" timestamp NOT NULL,
    "running_time_delta" int4 NOT NULL
);

SELECT create_hypertable('events', 'timestamp');

CREATE MATERIALIZED VIEW continuous_running_time WITH (timescaledb.continuous) AS
    SELECT time_bucket(INTERVAL '1 day', timestamp) AS bucket,
        SUM(running_time_delta) AS running_time
    FROM events
    GROUP BY bucket;
 ```

Interestingly in the cagg view, `running_time` is represented as `int8`, unlike the originally aggregated column `running_time_delta` which is `int4`.

This may or may not be a bug, but as I couldn't find anything on the matter in the documentation, I wanted to double-check.
This is causing trouble for us as the Node.JS postgres driver does not automatically convert `int8` to `Number` while it does so for int4, so the types are not fully interchangeable, even below the max value for 4 byte integers.

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14

### What operating system did you use?

Multiple

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
see above
```

**Comment by svenklemm** [comment]
This is expected behaviour since the sum aggregate function for int4 is defined as returning bigint by postgres.

```
sven@idx[2628392]=# \df sum
                         List of functions
   Schema   | Name | Result data type | Argument data types | Type
------------+------+------------------+---------------------+------
 pg_catalog | sum  | numeric          | bigint              | agg
 pg_catalog | sum  | double precision | double precision    | agg
 pg_catalog | sum  | bigint           | integer             | agg
 pg_catalog | sum  | interval         | interval            | agg
 pg_catalog | sum  | money            | money               | agg
 pg_catalog | sum  | numeric          | numeric             | agg
 pg_catalog | sum  | real             | real                | agg
 pg_catalog | sum  | bigint           | smallint            | agg
(8 rows)

Time: 11.563 ms
sven@idx[2628392]=# SELECT pg_typeof(sum(1::int4));
 pg_typeof
-----------
 bigint
(1 row)

```

**Comment by pehlert** [comment]
I wonder how our code can have possibly worked before then, but this is makes it pretty clear ;-) 
Thanks a lot for the response and the useful `pg_typeof` function!
