### ISSUE TITLE
add optional "reference" functionality in "create_hypertable"

### ISSUE THREAD

**Issue by nikkhils** [timescale/timescaledb#5140]
We need to be able to create special type of distributed hypertables which are basically regular Postgres tables that are replicated uniformly (meaning entire content is replicated) to all the Datanodes. These are called as "Reference Tables" (RT).

RT is a special type of distributed hypertable. It does not need a time or space dimension columns. In RT, data is replicated to all DNs and is not hash partitioned by either time and/or space dimensions. We will enhance the create_hypertable API to include an additional optional argument reference.

```
CREATE OR REPLACE FUNCTION @extschema@.create_hypertable(
    relation                REGCLASS,
    ...
    distributed             BOOLEAN = NULL,
    reference               BOOLEAN = NULL 
) 
```

* If the reference argument is set to true then it has to additionally specify the distributed option as well. 
* Additionally, if replication_factor is specified then we will error out since the data needs to be present on all DNs uniformly. 
* All other time/space dimension columns references, we error out if they are specified along with reference argument. 
* Compression or freezing will NOT be allowed on RT objects.

**Comment by nikkhils** [comment]
New proposal is to create dimensionless distributed hypertables without using any additional options like reference. The semantics of dimensionless distributed hypertables will be that they will have replication factor set to the current number of datanodes.

Erik suggests that for such dimensionless distributed hypertables, we do not create even one chunk the way the current implementation does. Instead, we route all changes to the same root table itself. We can do this by entering the root table entry in the chunk metadata. The alternative requires further investigation.

**Comment by svenklemm** [comment]
multinode has been removed
