### ISSUE TITLE
[Bug]: cmake is required to build TimescaleDB. Please install

### ISSUE THREAD

**Issue by wereket** [timescale/timescaledb#5142]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Build system

### What happened?

cmake is required to build TimescaleDB. Please install via your system's preferred method.

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

15

### What operating system did you use?

voidlinux

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
build from source
```

**Comment by lkshminarayanan** [comment]
Hi @wereket! 

This is expected - [CMake](https://cmake.org/) version 3.4 or greater is required to build TimescaleDB. Please refer to our [Building from Source](https://github.com/timescale/timescaledb/blob/main/docs/BuildSource.md) doc for a list of all requirements and steps to be followed to build and install TimescaleDB from source. Thank you!

**Comment by wereket** [comment]
I am sorry, I tough I had installed cmake
it works now after installing cmake
