### ISSUE TITLE
[Bug]: Adding column to compressed table fails if NULL is used as constraint

### ISSUE THREAD

**Issue by ikkala** [timescale/timescaledb#5151]
### What type of bug is this?

Incorrect result, Unexpected error

### What subsystems and features are affected?

Command processing, Compression

### What happened?

Following error occur in case of the following statement:

```
ALTER TABLE table1 ADD COLUMN column1 jsonb NULL;

ERROR: cannot add column with constraints to a hypertable that has compression enabled
```

On the other hand, following works:
`ALTER TABLE table1 ADD COLUMN column1 jsonb;
`

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

13.9

### What operating system did you use?

Docker image timescale/timescaledb-ha:pg13.9-ts2.8.1-p3

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE "table1" (
  "ts" timestamptz NOT NULL,
  "column0" bigint NULL
);
SELECT create_hypertable(
  'table1',
  'ts'
);

ALTER TABLE table1 SET (
  timescaledb.compress
);
SELECT add_compression_policy('table1', INTERVAL '1d');

-- The following fails:
ALTER TABLE table1 ADD COLUMN column1 jsonb NULL;
```

**Comment by fabriziomello** [comment]
Good catch @ikkala! Thanks for reporting, providing a fix for it!
