### ISSUE TITLE
[Enhancement]: Extend enabling compression on a continuous aggregrate with 'segmentby' and 'orderby' parameters

### ISSUE THREAD

**Issue by emizero** [timescale/timescaledb#5161]
### What type of enhancement is this?

API improvement, Performance

### What subsystems and features will be improved?

Compression, Continuous aggregate

### What does the enhancement do?

Extend "ALTER MATERIALIZED VIEW" with the 'segmentby' and 'orderby' parameters when enabling compression.
segmentby parameter is crucial for performance when caggs are especially large.  At the moment trying the query results in the error below.

```
ALTER MATERIALIZED VIEW test_table_cagg SET (
  timescaledb.compress = true,
  timescaledb.compress_segmentby = 'device_id'
);
ERROR:  unrecognized parameter "timescaledb.compress_segmentby"
```

Currently, there is a workaround that allows us to enable compression directly on the internal hypertable for the continuous aggregate.
```
ALTER TABLE _timescaledb_internal._materialized_hypertable_71 SET (                              
  timescaledb.compress = true,
  timescaledb.compress_segmentby = 'device_id'
);
ALTER TABLE
```

### Implementation challenges

Unknown at the moment

**Comment by kgyrtkirk** [comment]
@fabriziomello: it would probably make sense to cover all options in the compression with clause [here](https://github.com/timescale/timescaledb/blob/5d12a3883d80f026252eaac8416143de6cd5653d/src/compression_with_clause.c#L24-L42); however that raises the question - does all of them make sense for an MV as well?

If they do make sense - then I would probably need to add some end-markers to [CompressHypertableOption](https://github.com/timescale/timescaledb/blob/5d12a3883d80f026252eaac8416143de6cd5653d/src/compression_with_clause.h#L16) and [ContinuousAggViewOption](https://github.com/timescale/timescaledb/blob/5d12a3883d80f026252eaac8416143de6cd5653d/src/ts_catalog/continuous_agg.h#L44) enums.
