### ISSUE TITLE
Can't install TimeScaleDB to Not finding Postgres when installing TimescaleDB on Windows

### ISSUE THREAD

**Issue by Rama258** [timescale/timescaledb#517]
I can't install TimeScaleDB successfully .. I read the prerequestities but I didn't understand the third step 
which is : Make s**ure all relevant binaries are in your PATH: pg_config, cmake, MSBuild**

how can I make sure ?
when i tried to install Postgsql the message error was : **could not get `pg_config --pkglibdir`: exec: "pg_config": executable file not found in %PATH%**
Please can anyone help me

**Comment by RobAtticus** [comment]
You'll need to edit the the PATH environmental variable on Windows. Here's a page that describes the procedure for various versions of Windows:
https://www.java.com/en/download/help/path.xml

In particular, you'll need to add the path to PostgreSQL's binaries to the list of places in the PATH variable. Usually this is something like C:\Program Files\PostgreSQL\postgres\bin, but it will depend on your setup and you may have to find pg_config yourself via Windows Explorer first

**Comment by Rama258** [comment]
Thank you very much :)
You mean I have to install **PostgreSQL** first

**Comment by Rama258** [comment]
Thank you very much .. it works :)

**Comment by RobAtticus** [comment]
Great, going to close this out :)

**Comment by arul67800** [comment]
I installed two versions of postgresql viz.12 and 13 and i want to enable timeseries in 12..but when executing setup.exe..this error pops up..how to tell setup exe the correct path of postgresql 12
