### ISSUE TITLE
[Bug]: relation "public.entitybooleanstates" does not exist

### ISSUE THREAD

**Issue by HafeezRahmaan** [timescale/timescaledb#5174]
### What type of bug is this?

Incorrect result, Other

### What subsystems and features are affected?

Query executor

### What happened?

i have created a table by name of public."EntityBooleanStates"
when i try to convert to hypertable using query: SELECT create_hypertable('public.EntityBooleanStates', 'time')
i got error ERROR:  relation "public.entitybooleanstates" does not exist
create_hypertable function is converting table to lower case and i am unable to create hypertable

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14.1

### What operating system did you use?

Ubuntu 22.04.1 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  relation "public.entitybooleanstates" does not exist
LINE 1: SELECT create_hypertable('public.EntityBooleanStates', 'time...
                                 ^
SQL state: 42P01
Character: 26
```

### How can we reproduce the bug?

```bash
CREATE TABLE public."EntityBooleanStates" (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp without time zone DEFAULT now() NOT NULL,
    "deletedAt" timestamp without time zone,
    version integer NOT NULL,
    key character varying NOT NULL,
    value boolean NOT NULL,
    "time" timestamp without time zone NOT NULL,
    "entityId" uuid NOT NULL,
    "eventIds" text[],
    "requestId" character varying,
    "cursorId" integer NOT NULL
);
SELECT create_hypertable('public.EntityBooleanStates', 'time');
```

**Comment by fabriziomello** [comment]
@HafeezRahmaan this is not a bug, it is an expected Postgres behavior.

Identifiers in Postgres are case insensitive by default. To make identifiers case sensitive you should use _double quoted identifiers_: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

To make your example work you should double quote your case sensitive identifier, for example:
```sql
SELECT create_hypertable('public."EntityBooleanStates"', 'time');
```

**Comment by HafeezRai** [comment]
This works Thanks a lot
