### ISSUE TITLE
 ERROR: could not get pg_config: exec: "pg_config": executable file not found in %PATH% Press ENTER/Return key to close...

### ISSUE THREAD

**Issue by fphinix** [timescale/timescaledb#5178]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

installing timescale db, and i have restarted my pc after i added path env variables in my windows. it still shows this error when i try to set up the zip file in timescale db

ERROR: could not get pg_config: exec: "pg_config": executable file not found in %PATH%

Press ENTER/Return key to close...

P.S. i have installed postgresql, and set the path variable to "C:\Program Files\PostgreSQL\15\bin" still not working. I am on windows 11

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

15

### What operating system did you use?

Windows11

### What installation method did you use?

Other

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
1. Download and install PostgreSQL from www.postgresql.org. You might need to add the pg_config file location to your path. 
2. In the Windows Search tool, search for system environment variables. The path should be C:\Program Files\PostgreSQL\<version>\bin.
3. Download the TimescaleDB installation .zip file from Windows releases.
4. Locate the downloaded file on your local file system, and extract the files.
5. In the extracted TimescaleDB directory, right-click the setup.exe file and select Run as Administrator to start the installer.
```

**Comment by fabriziomello** [comment]
@fphinix Postgres 15 is not supported yet. You should use Postgres 12, 13 or 14. Also TSDB 2.5.0 is not supported anymore and recommend you use the last one 2.9.1.

**Comment by fabriziomello** [comment]
yes it is @fphinix
