### ISSUE TITLE
[Bug]: Cannot update 1 day candle for the day before

### ISSUE THREAD

**Issue by mgeorgiev1-zen** [timescale/timescaledb#5192]
### What type of bug is this?

Other

### What subsystems and features are affected?

Continuous aggregate

### What happened?

We have 1min, 1hour and 1day hierarchical CAggs. The 1min and 1hour aggs are refreshing, but the 1day bucket hangs when the end of refresh period is the day before now. Also queries to it are slow (5-6seconds). Here is the code:

```
CREATE MATERIALIZED VIEW one_min_candle
WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 min', time) AS bucket,
        symbol,
        FIRST(bid, time) AS "open_bid",
        FIRST(ask, time) AS "open_ask",
        LAST(bid, time) AS "close_bid",
        LAST(ask, time) AS "close_ask",
        MAX(bid) AS high_bid,
        MAX(ask) AS high_ask,
        MIN(bid) AS low_bid,
        MIN(ask) AS low_ask,
        LAST(volume, time) AS day_volume
    FROM ticks
    GROUP BY bucket, symbol
WITH NO DATA;

CREATE MATERIALIZED VIEW one_hour_candle
WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 hour', bucket) AS bucket,
        symbol,
        FIRST(open_bid, bucket) AS "open_bid",
        FIRST(open_ask, bucket) AS "open_ask",
        LAST(close_bid, bucket) AS "close_bid",
        LAST(close_ask, bucket) AS "close_ask",
        MAX(high_bid) AS "high_bid",
        MAX(high_ask) AS "high_ask",
        MIN(low_bid) AS "low_bid",
        MIN(low_ask) AS "low_ask",
        LAST(day_volume, bucket) AS "day_volume"
    FROM one_min_candle
    GROUP BY 1, 2
WITH NO DATA;

CREATE MATERIALIZED VIEW one_day_candle
WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 day', bucket) AS bucket,
        symbol,
        FIRST(open_bid, bucket) AS "open_bid",
        FIRST(open_ask, bucket) AS "open_ask",
        LAST(close_bid, bucket) AS "close_bid",
        LAST(close_ask, bucket) AS "close_ask",
        MAX(high_bid) AS "high_bid",
        MAX(high_ask) AS "high_ask",
        MIN(low_bid) AS "low_bid",
        MIN(low_ask) AS "low_ask",
        LAST(day_volume, bucket) AS "day_volume"
    FROM one_hour_candle
    GROUP BY 1, 2
WITH NO DATA;
```

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14.6

### What operating system did you use?

Ubuntu 22.04.1 LTS x86-64

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
wal size: 50GB
temp_file_limit: 5GB
work_mem: 32MB
shared_buffers: 4GB (1/4 of 16GB RAM).
chunk_time_interval: 1hour (we get ~1GB new live data per hour)

We have 4800 different symbols.
Insert data with 3000-5000 records per second for 2-3 days interval.
Refresh time buckets.
```

**Comment by RafiaSabih** [comment]
Thank you for taking the time report this issue.
However to better understand the issue I need to reproduce this, for this I need more information,

- schema of the ticks table
- some sample data that is enough to reproduce the issue

**Comment by mgeorgiev1-zen** [comment]
Hello and sorry for delayed answer.
This is the schema of the table and 400k records of sample data. As you'll notice (timestamp col) this is the amount of data we get for just 30minutes (resulting in millions for the whole day). To reproduce the issue you would need data for a couple of days at least.

[ticks schema.txt](https://github.com/timescale/timescaledb/files/10520576/ticks.schema.txt)
[ticks_202301271551.csv](https://github.com/timescale/timescaledb/files/10520571/ticks_202301271551.csv)

Kind regards!

**Comment by jnidzwetzki** [comment]
Hello @mgeorgiev1-zen,

Thanks for providing the sample data. I would like to reproduce the behavior in my local environment. You mention that "_the 1day bucket hangs_". Does it mean that the content of the CAGG is outdated or does it mean a query that accesses the CAGG will hang forever? 

If the content of the CAGG is only outdated, does a [manual refresh](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/refresh-policies/#manually-refreshing-a-continuous-aggregate) of the CAGG help or will it still return outdated data afterward?

**Comment by mgeorgiev1-zen** [comment]
Hello @jnidzwetzki,

What I meant is that when I performed manual refresh, the query hangs forever. I could not be sure if the data is updated or not, but querying the bucket takes unusually long - 9-10 seconds.

**Comment by jnidzwetzki** [comment]
Hello @mgeorgiev1-zen,

Thanks for the information. I would like to understand the problem with the CAGG better. Could you open two PostgreSQL sessions to the affected database and do the following:

* In the first session, a manual refresh of the 1hour CAGG.
* In the second session, execute the following queries and provide us with the output? The output should contain the locks that are currently active in the database and the PostgreSQL processes that are executed:

```sql
SELECT pid, application_name, backend_type, state, wait_event FROM pg_stat_activity;
SELECT pid, database, relation, relation::regclass, mode, granted, waitstart FROM pg_locks ORDER BY pid;
```

This data will help us to understand why the CAGG can not be refreshed.
