### ISSUE TITLE
[Bug]: v2.9.1 no available in Ubuntu 18.04

### ISSUE THREAD

**Issue by Xima** [timescale/timescaledb#5200]
### What type of bug is this?

Other

### What subsystems and features are affected?

Platform/OS

### What happened?

v2.9.1 is not available for Ubuntu 18.04 on apt package when v2.9.0 is.

Is there a specific reason ?

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu 18.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Try to update package with apt
```

**Comment by akuzm** [comment]
Turns out we decided to not build it because 18.04 is EOL in 3 month. Is it possible for you to build from source? Here's how to do that: https://docs.timescale.com/install/latest/self-hosted/installation-source/ You might need to install some additional packages: `apt install git cmake postgresql-server-dev-12 libkrb5-dev`

**Comment by Xima** [comment]
Thanks for your answer. I understand. (still I would say that the hotfix should still be available IMHO).

We will probably update our servers to the new LTS

**Comment by nshah14285** [comment]
Hello,

We are using Ubuntu 18.04 OS, Postgresql 11 and Timescaledb 1.7 on live server.
We are planning to upgrade Postgresql 11 to Postgresql 15 on live server but as there is no build of Timescaledb 2.11 for Ubuntu 18.04 we were not able to upgrade Postgresql version.

It would be great if you provide the build for Ubuntu 18.04 version as I believe there are many system admins who will face this issue when they try to upgrade the Timescaledb on Ubuntu 18.04. 


Thank You.
