### ISSUE TITLE
[Bug]: "ERROR:  tried calling catalog_get when extension isn't loaded" again

### ISSUE THREAD

**Issue by flixman** [timescale/timescaledb#5203]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Data node

### What happened?

I have a timescale running on a container, happily for ~300 days. Yesterday, after a reboot, got this message and everything seems to be stuck: "ERROR:  tried calling catalog_get when extension isn't loaded"

I have gone through the issues (both open and closed) and I have checked that I am not short of space, and that  "show timescaledb.restoring;" returns "off".

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14.2

### What operating system did you use?

Debian 11.6

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
db_1           | 
db_1           | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1           | 
db_1           | 2023-01-19 19:26:00.305 UTC [1] LOG:  starting PostgreSQL 14.2 (Ubuntu 14.2-1.pgdg21.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, 64-bit
db_1           | 2023-01-19 19:26:00.314 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1           | 2023-01-19 19:26:00.322 UTC [1] LOG:  could not create IPv6 socket for address "::": Address family not supported by protocol
db_1           | 2023-01-19 19:26:03.421 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1           | 2023-01-19 19:26:03.467 UTC [14] LOG:  database system was shut down at 2023-01-19 19:25:03 UTC
db_1           | 2023-01-19 19:26:03.517 UTC [1] LOG:  database system is ready to accept connections
db_1           | 2023-01-19 19:26:03.525 UTC [20] LOG:  TimescaleDB background worker launcher connected to shared catalogs
db_1           | 2023-01-19 19:26:03.661 UTC [23] ERROR:  tried calling catalog_get when extension isn't loaded
db_1           | 2023-01-19 19:26:03.673 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 23) exited with exit code 1
```

### How can we reproduce the bug?

```bash
I do not know :-/
```

**Comment by RafiaSabih** [comment]
I am sorry you are facing this, and thanks for taking the time to report this.
Could you please tell what is the telemetry status?
In case it is active, can you try restarting it with telemetry off.
