### ISSUE TITLE
[Feature]: facets

### ISSUE THREAD

**Issue by gedw99** [timescale/timescaledb#5209]
### What problem does the new feature solve?

I need to do facets and facet based search 

### What does the feature do?

You can progressively create joins on data 
For each facet the count changes in the gui as the query is changed

**Comment by mkindahl** [comment]
@gedw99 Thanks for suggesting a new feature. It is not, however, very clear what it is you are actually suggesting. If you could give a concrete example of what you're trying to solve (we love actual code), it will be easier to understand what you're trying to do, and maybe we will be able to provide better help.

**Comment by gedw99** [comment]
Amazon shopping is the most well known example 

if your shopping for a TV you see all the facets on the left lane such as screen size, display tech, etc .

The same can be applied to time series data in that time is one of the facets but also any tags that are applicable to the developers use case .

Hope this helps a bit ?

**Comment by mkindahl** [comment]
This sounds like you want to have a column in the database containing tags, or fields with values.

This is usually modeled in SQL using either [JSON](https://www.postgresql.org/docs/15/functions-json.html) or using [HSTORE](https://www.postgresql.org/docs/15/hstore.html) (that can handle key-value pairs). If you use JSON, then you can do something like this:

```sql
SELECT * FROM gadgets WHERE facet->'screen_size' > 12;
```

Does this answer your question?

**Comment by gedw99** [comment]
thanks @mkindahl 

This is definitely a start :) This is why i love timescale - its SQL and works with your existing data.

Now i am wondering if there is a way to try this out quickly. 
IS there some example, in this repo or other, where i can start up a docker (with timescale and postres) and pump some test  time series data in and then pump in some facts like in your example to work up something ?

**Comment by mkindahl** [comment]
Well... this is very dependent on the kind of gadgets that you want to store in your database, what connectors you are using, and a bunch of other things. It is not specific to Timescale either, so if you search for "e-commerce", "example", "postgres", and your favorite language you will find a bunch of applications that implement what you're after.

**Comment by gedw99** [comment]
Thanks !! 

Will check out your tips and build a little teat harness.

**Comment by gedw99** [comment]
https://bun.uptrace.dev/postgres/faceted-full-text-search-tsvector.html#creating-a-table is a good starter

**Comment by mkindahl** [comment]
Good that you found some information. I will close this issue since it seems there is needed from our end, but feel free to ask for reopening the issue if you think it is necessary. Good luck on your venture!
