### ISSUE TITLE
[Enhancement]: Improve AutoFetcherType fetcher type selection

### ISSUE THREAD

**Issue by jnidzwetzki** [timescale/timescaledb#5219]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Multi-node

### What does the enhancement do?

The AutoFetcherType setting currently [selects](https://github.com/timescale/timescaledb/blob/552950d221b332c6e0cbc2682e39022f2b972f32/src/planner/planner.c#L513) the `CursorFetcher` as soon as more than one distributed hypertable is involved in a query. If distributed native joins should be supported in the future between >= 2 distributed hypertables, it would be good to improve this selection and use the faster `CopyFetcher` for these queries as well.

The following solutions are possible:
* Lift the restriction of the `CopyFetcher` and support more than one copy fetcher per DN in a query.
* Make the selection of the fetcher type based on the chosen query plan. A pushed-down join on two distributed hypertables would result in one DataNodeScan node per DN. This information could be used to select the fetcher type instead of counting the involved tables in a query. Counting tables and checking the query type is not reliable. Because based on the query, it can not be decided if a join will be pushed down or not (i.e., how many `DataNodeScans` are performed per DN). This information is only available after query planning.

**Comment by svenklemm** [comment]
multinode has been removed
