### ISSUE TITLE
[Bug]: Background Worker Scheduler crashes with out of on_proc_exit slots after ~14 hours"

### ISSUE THREAD

**Issue by S-imo-n** [timescale/timescaledb#5233]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

Periodically every aprox. 14h we get an error on our DBs (see log below).
This issue happens on all our systems (DEV/INT/PROD) in more or less the same frequency, so we believe there are no external factors at play, like connections, inserts, or whatsoever. But it is an internal problem in the DB.

We also tried upgrading from Timescale 2.6.1 to 2.9.1 and upgrade PG from 12.13 to 14.6, but both did not do anything regarding this error.

Do you know of anything that could cause such a behaviour?

2023-01-26 22:34:42.268 UTC,,,1312,,63d23096.520,1,,2023-01-26 07:49:42 UTC,9/0,0,FATAL,54000,"out of on_proc_exit slots",,,,,,,,,"","TimescaleDB Background Worker Scheduler",,0
2023-01-26 22:34:42.272 UTC,,,1278,,63d23095.4fe,25,,2023-01-26 07:49:41 UTC,,0,LOG,00000,"background worker ""TimescaleDB Background Worker Scheduler"" (PID 1312) exited with exit code 1",,,,,,,,,"","postmaster",,0

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14.6 & 12.13

### What operating system did you use?

PostgreSQL 14.6 (Ubuntu 14.6-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-01-26 22:34:42.268 UTC,,,1312,,63d23096.520,1,,2023-01-26 07:49:42 UTC,9/0,0,FATAL,54000,"out of on_proc_exit slots",,,,,,,,,"","TimescaleDB Background Worker Scheduler",,0
2023-01-26 22:34:42.272 UTC,,,1278,,63d23095.4fe,25,,2023-01-26 07:49:41 UTC,,0,LOG,00000,"background worker ""TimescaleDB Background Worker Scheduler"" (PID 1312) exited with exit code 1",,,,,,,,,"","postmaster",,0
```

### How can we reproduce the bug?

```bash
Not sure if you can. We do not "produce" the issue, it just comes up.
```

**Comment by konskov** [comment]
hi @S-imo-n, thank you for reaching out. To clarify, did you encounter this with both versions 2.6.1 and 2.9.1 of TimescaleDB or only after upgrading to 2.9.1?

**Comment by S-imo-n** [comment]
Hi @konskov 
we had the error with TS 2.6.1 & PG 12.13. This led us into upgrading our landscape, but the error still persists with TS 2.9.1 & PG 14.6.

**Comment by nikkhils** [comment]
Hi @S-imo-n 

Are you using any additional custom PostgreSQL extensions along with timescaledb?

**Comment by S-imo-n** [comment]
Thank you all for your replies!
Another lead came up, perhaps SQLAlchemy has something to do with it. We will investigate and probably come back to you tomorrow with the results.

**Comment by mblsf** [comment]
Hi @nikkhils
 
Yes, we are using Oracle_FDW and Multicorn as FDW for SAP HANA.
We will remove these extensions and check if the problem persists.

Thanks for the hint.

**Comment by mblsf** [comment]
Hi @nikkhils,

we have removed all extensions and the problem still exists.

Some additional informations:
We are using TimescaleDB as part of the zalando/spilo docker image.
It seems that any connection to the database that lasts longer than 14 hours and 45 minutes is dropped.
Maybe the scheduler keeps connections open for that long and the connection drop causes the crash.

**Comment by konskov** [comment]
hi @mblsf,
You are correct, the TimescaleDB scheduler doesn’t set a time limit on the connection. It is expected to be alive and connected to the database, as long as the extension is installed in it. Otherwise the background jobs/policies API will not work. So if any connection lasting longer than a certain interval is dropped, you can try calling `restart_background_workers()` once the scheduler exits so it can resume its operation.

**Comment by nikkhils** [comment]
@mblsf how is the long-lasting connection dropped?

**Comment by mblsf** [comment]
@konskov Thanks, restarting the scheduler worked. Is there any reason why automatic restart in case of a crash is disabled in [scheduler.c](https://github.com/timescale/timescaledb/blob/main/src/bgw/scheduler.c) ?

@nikkhils We don't currently know why this is happening and need to investigate further. We'll keep you in touch.

**Comment by mblsf** [comment]
We have new information on this issue:

It only occurs when using timescaledb as part of the spilo docker image set up by the postgres operator in k8s
The crash could be reproduced by sending SIGHUP to postgres for 15 times using the command "kill -1 [PID of postgres]" 

It seems to be send automatically to postgres by partroni or the operator every 59 minutes, which in our environment will cause the scheduler to crash after 14 hours and 45 minutes .

I also tried to set bgw_restart_time to 1 in scheduler.c but it seems not to have no effect.

**Comment by mblsf** [comment]
I found the reason for the issue and how to reproduce the issue using a custom spilo docker image build with the argument 
TIMESCALEDB_APACHE_ONLY=false 

1. Download the source of spilo from https://github.com/zalando/spilo/archive/refs/tags/2.1-p9.tar.gz, extract the archive and build the custom image:
docker build postgres-appliance/. -t custom-spilo-15:2.1-p9 --build-arg TIMESCALEDB_APACHE_ONLY=false

2. Start custom-spilo docker container
docker run custom-spilo-15:2.1-p9 > /dev/null 2>1 &

3. Shell into container (get container_id using docker ps)
docker exec -it {container_id] /bin/bash

4. Activate preloading of timescaledb libraries:
echo "shared_preload_libraries = 'timescaledb'" >> /home/postgres/pgdata/pgroot/data/postgresql.conf

5. Switch from Apache to timescale license:
echo "timescaledb.license = 'timescale'" >> /home/postgres/pgdata/pgroot/data/postgresql.conf

6. Switch to user postges (su postgres) and restart db:
pg_ctl restart

7. Create a db with ts extension using the following 3 commands:
psql -c "create user tse"
psql -c "create database tse"
psql tse -c "create extension timescaledb"

8. check that Scheduler is running 
ps -ef | grep Scheduler | grep -v grep

9. Send SIGHUP for about 20 times to postgres process (get pid using ps -ef | grep postgresql | grep -v grep)
kill -1 [pid of postgres]

10. The Scheduler process should now have been crashed, check the postgres logfile for the following entries:
2023-02-15 10:15:44.718 UTC,,,924,,63ecb0af.39c,18,,2023-02-15 10:15:11 UTC,,0,LOG,00000,"received SIGHUP, reloading configuration files",,,,,,,,,""
2023-02-15 10:15:44.719 UTC,,,939,,63ecb0af.3ab,1,,2023-02-15 10:15:11 UTC,5/0,0,FATAL,54000,"out of on_proc_exit slots",,,,,,,,,""
2023-02-15 10:15:44.722 UTC,,,924,,63ecb0af.39c,19,,2023-02-15 10:15:11 UTC,,0,LOG,00000,"background worker ""TimescaleDB Background Worker Scheduler"" (PID 939) exited with exit code 1",,,,,,,,,""


However, the Scheduler does not crash when the step 5, switching from Apache to timescale license, is skipped.

**Comment by S-imo-n** [comment]
Hi :)
any updates?
Can we give you more information?
Ty Simon

**Comment by mahipv** [comment]
Was able to reproduce the issue on ubuntu with the following steps, without the docker

1. Start the server

2. Change the license in the conf file
echo "timescaledb.license = 'timescale'" >> /home/mahi/gitroot/postgresql/data/postgresql.conf

3.create extension timescaledb;

4. Session 1: send SIGHUP to the postgres process repeatedly (defaault 2 sec interval) 
watch kill -9 <pid of the postgress process>

5. Session 2: Check the log
watch tail -20 ./logfile

In about 10 tries, the following entry appears in the logfile. This happens 

2023-03-06 05:51:07.585 IST [6902] LOG:  received SIGHUP, reloading configuration files
...
2023-03-06 05:51:23.620 IST [6902] LOG:  received SIGHUP, reloading configuration files
2023-03-06 05:51:23.622 IST [8910] FATAL:  out of on_proc_exit slots
2023-03-06 05:51:23.624 IST [6902] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 8910) exited with exit code 1

**Comment by mahipv** [comment]
For every SIGHUP is sent with timescaledb.license = 'timescale' in the conf file,
the tsl_module_init is called. This adds a "on exit" callback into the on_proc_exit_list
using on_proc_exit().

The on_proc_exit_list is an array of MAX_ON_EXITS 20 entries and it gets filled up after
20 SIGHUPs, which causes the error.

**Comment by S-imo-n** [comment]
@mahipv 
Thank you very much for your investigation!
It relieves me, that you can produce the issue as well.
The explanation you gave seems fitting.

Is there a chance the logic can be changed, so that we resolve the problem?
