### ISSUE TITLE
Provide a way to get approximate row count for hypertable

### ISSUE THREAD

**Issue by viragkothari** [timescale/timescaledb#525]
Below command for regular tables in postgres
`SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = <table_name>`
select count(*) works for an exact count but it takes a longer time for table with huge no of rows

**Comment by fvannee** [comment]
The following query provides the information you're looking for.

```
SELECT h.schema_name,
    h.table_name,
    h.id AS table_id,
    h.associated_table_prefix,
    row_estimate.row_estimate
   FROM _timescaledb_catalog.hypertable h
     CROSS JOIN LATERAL ( SELECT sum(cl.reltuples) AS row_estimate
           FROM _timescaledb_catalog.chunk c
             JOIN pg_class cl ON cl.relname = c.table_name
          WHERE c.hypertable_id = h.id
          GROUP BY h.schema_name, h.table_name) row_estimate
ORDER BY schema_name, table_name;
```

**Comment by viragkothari** [comment]
Works great, Thanks!

**Comment by viragkothari** [comment]
Would be good to add to docs.

**Comment by fvannee** [comment]
Agreed

**Comment by mfreed** [comment]
Re-opening issue as a enhancement, as we could expose this as an easier utility function to users.

**Comment by RobAtticus** [comment]
This has been merged in and will be in the upcoming 0.10.0 release (sometime in the next few weeks).

Thanks all!

**Comment by solugebefola** [comment]
The SQL statement has also been added to the current version of the docs(http://docs.timescale.com/v0.9/using-timescaledb/reading-data#approximate-row-count)

**Comment by jflambert** [comment]
Unfortunately this won't work with compressed tables.

**Comment by sarfata** [comment]
> http://docs.timescale.com/v0.9/using-timescaledb/reading-data#approximate-row-count
I did not see the function in this version of the doc.

But it is available in the most recent doc: [`hypertable_approximate_row_count`](https://docs.timescale.com/latest/api#hypertable_approximate_row_count)
