### ISSUE TITLE
Unused rows retrieved from compressed chunks when condition on segmentby column uses text/bytea non-equality operators

### ISSUE THREAD

**Issue by nevillegrech** [timescale/timescaledb#5286]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

Unused rows are retrieved from compressed chunks in the secscan query plan operator when condition on segmentby column does not use _compressed_...<seg_col>...meta_sequence_num_idx. A simple filter condition is missing in this step which causes performance to degrade by an order of magnitude on selective conditions.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Ubuntu 21.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```
Aggregate  (cost=767.53..767.54 rows=1 width=8) (actual time=21.651..21.652 rows=1 loops=1)
  Output: sum(_hyper_11_36_chunk.data)
  ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_11_36_chunk  (cost=0.03..10.03 rows=303000 width=4) (actual time=21.649..21.650 rows=0 loops=1)
        Output: _hyper_11_36_chunk.data
        Filter: ((_hyper_11_36_chunk.segment)::text ~~ '%4%'::text)
        Rows Removed by Filter: 302401
        ->  Seq Scan on _timescaledb_internal.compress_hyper_12_37_chunk  (cost=0.00..10.03 rows=303 width=40) (actual time=0.004..0.030 rows=303 loops=1)
"              Output: compress_hyper_12_37_chunk.""timestamp"", compress_hyper_12_37_chunk.segment, compress_hyper_12_37_chunk.data, compress_hyper_12_37_chunk._ts_meta_count, compress_hyper_12_37_chunk._ts_meta_sequence_num, compress_hyper_12_37_chunk._ts_meta_min_1, compress_hyper_12_37_chunk._ts_meta_max_1"
Planning Time: 0.217 ms
Execution Time: 21.675 ms
```

### How can we reproduce the bug?

The issue can be recreated using a simple select like below on a compressed hypertable segmented by <segment_by_column>:

`explain (analyze, verbose, timing) select ... from <compressed_hypertable> where pred(<segment_by_column>)`

Where `pred` is not a simple equality or range operator. For example `substr(<segment_by_column>, 1, 1) = '\xFF'`. This kind of query will take the plan above.

Note that the filter condition is performed *after* the parallel seq scan on the compressed table, but since the column is also available in the compressed table in an uncompressed state (since it is a segmentby column), the filter could also be performed in the seqscan operator. (technically, the filter doesn't need to be done in the custom scan step but realistically this will not make such a performance impact).

In cases where the predicate is selective, it could improve performance of these kinds of queries by an order of magnitude.

A full example is available below:
```
create table deleteme as
    select generate_series as timestamp, 1 as segment, 0 as data from generate_series('2008-03-01 00:00'::timestamp,
                              '2008-03-04 12:00', '1 second');

SELECT create_hypertable('deleteme', 'timestamp', migrate_data => true);

ALTER TABLE deleteme SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'segment'
);

select compress_chunk(i) from show_chunks('deleteme') i;

explain (analyze, verbose, timing) select sum(data) from deleteme where segment::text like '%4%';
```

Note that if the final line uses a filter on Integer such as `segment & 255 = 4`, the filter condition on the inner seqscan is applied correctly

**Comment by konskov** [comment]
hello @nevillegrech, thank you for reaching out. Version 2.5.0 is relatively old, have you tried to reproduce this with the latest version of timescaleDB? Also, if possible, could you please provide reproduction steps for the example you have used? Thank you!

**Comment by nevillegrech** [comment]
@konskov I've updated the issue with a minimal example to trigger that triggers the bug.

**Comment by nevillegrech** [comment]
Possibly related: https://github.com/timescale/timescaledb/issues/3351

**Comment by mkindahl** [comment]
@nevillegrech Thanks for the reproduction case. Trivial to reproduce.
