### ISSUE TITLE
[Bug]: redhat timescaledb-2-postgresql-15 version(2.9.2)

### ISSUE THREAD

**Issue by d-sooter** [timescale/timescaledb#5288]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Build system, Platform/OS

### What happened?

Adding timescaledb to my docker image works but the version installed in 2.9.1 i imagine the latest version (2.9.2) has not yet been uploaded. 

Im using the following to install it:
microdnf install -y timescaledb-2-postgresql-15

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

15.1

### What operating system did you use?

ubi8

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
microdnf install -y timescaledb-2-postgresql-15
```

**Comment by konskov** [comment]
hi @d-sooter thank you for reaching out. We do have [rpm packages for 2.9.2](https://packagecloud.io/app/timescale/timescaledb/search?q=2.9.2&filter=all&filter=rpms&dist=) available on packagecloud so not sure if this is a timescaledb issue...

**Comment by konskov** [comment]
were you able to install timescaledb version 2.9.1 but not version 2.9.2?

**Comment by d-sooter** [comment]
So if i build my docker image using 

microdnf install -y timescaledb-2-postgresql-15

then version 2.9.1 is available and not 2.9.2

**Comment by d-sooter** [comment]
Now version 2.9.3 is being picked up.

**Comment by dberardo-com** [comment]
is there any official guide on how to install timescaledb using microdnf ? and is v2.10 already available ?
