### ISSUE TITLE
Postgresql 10.4.1

### ISSUE THREAD

**Issue by markatosi** [timescale/timescaledb#529]
So I "discovered" TimescaleDB today and decided to test it out and during the package install it said it needed newer version pf postgresql... I had 10.1 so i did an apt update and now I have 10.4.1 :-) which apparently isn't supported by the package yet.

dpkg: dependency problems prevent configuration of timescaledb-postgresql-10:
 timescaledb-postgresql-10 depends on postgresql-10 (<< 10.4); however:
  Version of postgresql-10 on system is 10.4-1.pgdg90+1.

Can i just compile the source or should I wait for a new package

**Comment by RobAtticus** [comment]
You can compile from source, or if you're willing to wait a little bit (couple of hours at most) we should have a version ready soon :)

**Comment by RobAtticus** [comment]
Make sure if you do compile from source to use a tagged commit

**Comment by markatosi** [comment]
I’m highly allergic to building my own if it’s going to be available in a package in a few hours :-)

**Comment by RobAtticus** [comment]
@markatosi Okay new binaries should be available, let me know if the problem persists (and which platform)

**Comment by markatosi** [comment]
Are the new binaries available though the mechanism described on https://docs.timescale.com/v0.9/getting-started/installation/linux/
or are they located somewhere on this git?

**Comment by RobAtticus** [comment]
Yes, they should be published for Ubuntu/Debian/RedHat unless something went wrong.

**Comment by markatosi** [comment]
Hmm so i downloaded the following unless the version number has changed and received the same error when trying to install in debian 9

wget https://timescalereleases.blob.core.windows.net/debian/timescaledb-postgresql-10_0.9.2~debian9_amd64.deb

I also tried increasing the minor version by one but that didn't exist

**Comment by RobAtticus** [comment]
Strange, I just tried on a fresh debian 9 Docker image and it worked fine (PG 10.4.1 and TS 0.9.2)

Maybe dpkg is caching something related to the old file? You can also try:
https://timescalereleases.blob.core.windows.net/debian/timescaledb-postgresql-10_latest~debian9_amd64.deb

But I tried both and they worked.

**Comment by markatosi** [comment]
The "latest" link you sent works! Yay.  The other one still doesn't. If you guys use a CDN the updated file probably hasn't propagated yet to which ever server i'm really getting it from.

Thanks so much for your assistance. I'll be testing on Centos 7 later as well

**Comment by RobAtticus** [comment]
Great, thanks, you might be right. Since we're using Azure perhaps it hasn't updated everywhere.

Let us know if t here any more problems, but I'm going to close this for now

**Comment by RobAtticus** [comment]
You're right, I didn't finish uploading those. Try again with that file or `timescaledb-0.9.2-postgresql-10-0.x86_64.rpm`

**Comment by markatosi** [comment]
Perfect. You can close this one now
