### ISSUE TITLE
[Bug]: Adding a column to an existing table requires locks and in practice requires writes to that table to be stopped

### ISSUE THREAD

**Issue by fmstephe** [timescale/timescaledb#5298]
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Other

### What happened?

We would like to add columns to existing hypertables. These columns are inexpensive to add in vanilla Postgres and look like

ALTER TABLE existing_table ADD COLUMN IF NOT EXISTS new_column TEXT;

However, because this operation takes table locks in practice we need to cease all write to this table (which is a customer visible service downtime) in order to add a new column.

We would like to be able to add a new column like this without needing to stop writes.

### TimescaleDB version affected

v2.9.1

### PostgreSQL version used

14.6

### What operating system did you use?

The OS used by timescale cloud

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```bash
Create a table, with some columns and begin writing to that table at a reasonably high frequency.

While the writes are happening add a new nullable column, with no default value, to the table. With a high probability the ALTER will fail due to locking.
```

**Comment by shhnwz** [comment]
Hi @fmstephe ,

Thanks for reporting this issue. We tried to recreate the scenario in-house, below are our observation so far.
Both Vanilla Postgres Table and Timescale Hypertable showed same behavior. 

Steps
- Started long insert or open transaction into both the tables 
- Issued DDL (ALTER ADD COL) to both the tables in parallel.

Observation:
DDL were blocked till the long INSERT TXN not completed. Once its over then DDL processed successfully without any error.

Let me know if I missed any step/s in scenario reproduction. 

What error was reported in your system, log will be of great help?
