### ISSUE TITLE
Weird issue with hypertable and template on centos 7

### ISSUE THREAD

**Issue by markatosi** [timescale/timescaledb#530]
I'm using postgresql 10.4.1 on debian 9 and centos 7

I'm not sure if this is a timescale issue but it is odd. I create a database which I'm going to use as a template database. I'm using it as a template but not declaring it as such. 

The database has a hypertable defined. When I create the new database Debian 9 the hypertable is "present". 

When i do the same in CentOS 7 the table is there but it's lost it's hypertable status so to speak.
I can issue the select statement to create the hypertable and it'll work then but i don't need to do this on my debian system as it just works from the start. 

create database timescale_db WITH TEMPLATE timescale_test OWNER postgres;
INSERT INTO conditions(time, location, temperature)
  VALUES (NOW(), 'office', 70.0);

[timescale_test.txt](https://github.com/timescale/timescaledb/files/1993566/timescale_test.txt)

**Comment by RobAtticus** [comment]
I don't see where you're calling `create_hypertable` in that txt file.

**Comment by markatosi** [comment]
I did look at the dump of the database (the text file) and I didn't see anything that would lead me to believe that it should work but it does in fact work on my debian postgres instance.

**Comment by markatosi** [comment]
I think that the dump file must be incorrect and this is only working on my debian instance because I created the database template there. Duh. sorry to have bothered you

**Comment by RobAtticus** [comment]
Always happy to answer questions.

We do provide scripts in our `scripts` folder for dumping and restoring a single highertable (e.g., `ts_dump.sh`) if you need that. You may also only need to add the `create_hypertable` statement at the end to make it work on another box.

**Comment by markatosi** [comment]
I was using a different postgresql client on my windows VM to dump the database once i used pg_admin 4 it resolved my issue.

**Comment by RobAtticus** [comment]
Sounds good, going to close this out.
