### ISSUE TITLE
pg_dump produces ALTER TABLE ONLY statements on hypertable chunks that can not be replayed by psql

### ISSUE THREAD

**Issue by markope** [timescale/timescaledb#531]
trying to do `psql -d mydb -f mydump.sql` produces these errors

psql:dump4.sql:407478: ERROR:  Operation not supported on chunk tables.
psql:dump4.sql:407638: ERROR:  ONLY option not supported on hypertable operations

They refer to these commands respectively in the dump file:
``` 
ALTER TABLE ONLY _timescaledb_internal._hyper_2_10_chunk
ADD CONSTRAINT "10_4_storage_track_pkey" PRIMARY KEY (pod_id, update_storage_tsp);

ALTER TABLE ONLY pod.storage_track
ADD CONSTRAINT storage_track_pkey PRIMARY KEY (pod_id, update_storage_tsp);
```

**Comment by AndyMender** [comment]
Which version of TimescaleDB and PostgreSQL? I was doing dump & restore the day before yesterday and everything worked extremely smoothly for 75 full databases (PostgreSQL 9.6.x and TimescaleDB 0.9.2). Did you follow the instructions in the official documentation?
https://docs.timescale.com/v0.9/using-timescaledb/backup

**Comment by markope** [comment]
I used
postgres version 10.3
timescaledb version 0.9.2

and no, I did not use the backup recommendation of timescaledb. (I did not know about id)
I'l try again with the `ALTER DATABASE tutorial SET timescaledb.restoring='on';` setting. 

Also for my purpose I prefer an sql dump from pg_dump not the binary dump format.

I'l try again and let you know.
Thanks

**Comment by markope** [comment]
ok, checked it. With the special setting it works !
Thanks !

**Comment by mohag** [comment]
> Which version of TimescaleDB and PostgreSQL? I was doing dump & restore the day before yesterday and everything worked extremely smoothly for 75 full databases (PostgreSQL 9.6.x and TimescaleDB 0.9.2). Did you follow the instructions in the official documentation? https://docs.timescale.com/v0.9/using-timescaledb/backup

This seems to be the new version: https://docs.timescale.com/self-hosted/latest/backup-and-restore/pg-dump-and-restore/

**Comment by RedShift1** [comment]
> > Which version of TimescaleDB and PostgreSQL? I was doing dump & restore the day before yesterday and everything worked extremely smoothly for 75 full databases (PostgreSQL 9.6.x and TimescaleDB 0.9.2). Did you follow the instructions in the official documentation? https://docs.timescale.com/v0.9/using-timescaledb/backup
> 
> This seems to be the new version: https://docs.timescale.com/self-hosted/latest/backup-and-restore/pg-dump-and-restore/

Link doesn't work anymore, I believe this is the correct link now: https://docs.timescale.com/self-hosted/latest/backup-and-restore/logical-backup/
