### ISSUE TITLE
[Bug]: deadlock caused by concurrent decompression and update of the referenced table

### ISSUE THREAD

**Issue by rnovatorov** [timescale/timescaledb#5325]
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Compression

### What happened?

Hi,

My use case:

I am working on a data-warehouse service one of responsibilities of which is to fetch timeseries data collected from energy devices and save it to a hypertable for long-term storage and analysis.

Most of the saved data is afterwards compressed to reduce storage space. Sometimes there is a need to backfill the previously collected data, which requires temporary decompression. Both compression and decompression are handled using `compress_chunk` and `decompress_chunk`, so there is no compression policies involved.

The problem:

I encounter deadlocks while trying to concurrently update a table which holds device info and decompress for subsequent backfill a table which holds the timeseries data and references the first table.

I think I have extracted all the relevant bits of the implementation in the reproduction instruction. Please feel free to ask for more info if you think that something is missing.

A possible solution:

I have got rid of the deadlocks by moving the updatable parts of the referenced table to a separate table which is not referenced by a hypertable. I am not sure whether it is a bug at all, but it definitely took me by surprise, so maybe it is worth mentioning somewhere in the docs.

This issue might be somewhat related to #4800.

### TimescaleDB version affected

2.9.2

### PostgreSQL version used

14.6

### What operating system did you use?

Arch Linux

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-02-14 20:03:22.878 UTC [78] ERROR:  deadlock detected at character 12
2023-02-14 20:03:22.878 UTC [78] DETAIL:  Process 78 waits for RowExclusiveLock on relation 17781 of database 13777; blocked by process 77.
	Process 77 waits for AccessExclusiveLock on relation 17781 of database 13777; blocked by process 78.
	Process 78: UPDATE
	    devices
	SET
	    name = 'bar'
	WHERE
	    id = 1;
	Process 77: SELECT
	    decompress_chunk (show_chunks ('readings'));
2023-02-14 20:03:22.878 UTC [78] HINT:  See server log for query details.
2023-02-14 20:03:22.878 UTC [78] STATEMENT:  UPDATE
	    devices
	SET
	    name = 'bar'
	WHERE
	    id = 1;
```

### How can we reproduce the bug?

```sql
-- setup.sql

BEGIN;

-- create a referenced table
CREATE TABLE devices (
    id INT,
    name TEXT,
    PRIMARY KEY (id)
);

-- populate the referenced table
INSERT INTO devices (id, name)
    VALUES (1, 'foo');

-- create a table to be partitioned
CREATE TABLE readings (
    device_id INT,
    time TIMESTAMP WITH TIME ZONE,
    value FLOAT,
    FOREIGN KEY (device_id) REFERENCES devices (id)
);

-- convert it to a hypertable
SELECT
    create_hypertable ('readings', 'time');

-- enable compression
ALTER TABLE readings SET (timescaledb.compress, timescaledb.compress_segmentby
    = 'device_id');

-- create a chunk
INSERT INTO readings (device_id, time, value)
    VALUES (1, '2000-01-01 00:00:00+00', 42.0);

-- compress the chunk
SELECT
    compress_chunk (show_chunks ('readings'));

END;
```

```sql
-- deadlock.sql

-- session 1
BEGIN;

-- acquire AccessShareLock on devices
SELECT
    id
FROM
    devices
WHERE
    name = 'foo';

-- session 2
BEGIN;

-- acquire ShareRowExclusiveLock on devices, wait for AccessExclusiveLock on
-- devices, blocked by session 1
SELECT
    decompress_chunk (show_chunks ('readings'));

-- session 1
-- wait RowExclusiveLock on devices, blocked by session 2, deadlock
UPDATE
    devices
SET
    name = 'bar'
WHERE
    id = 1;
```

**Comment by WalkerWalker** [comment]
Oh my god.  I encounter the exact same bug today.  Just asked for help [on slack](https://timescaledb.slack.com/archives/C4GT3N90X/p1676565579293369)

Essentially decompressing the hypertable needs AccessExclusiveLock of the reference table.   I feel/hope this should not be the case.

**Comment by shhnwz** [comment]
Hello @WalkerWalker  and @rnovatorov ,
Thanks for the extensive analysis, we observed that multiple sites reported this issue. For the sake of simplicity we have clubbed them to a single issue. You can track the progress under this link https://github.com/timescale/timescaledb/issues/5342
