### ISSUE TITLE
psycopg2 copy_to not working with hypertables

### ISSUE THREAD

**Issue by thaxy** [timescale/timescaledb#533]
Hi,

I am not sure if you care but I noticed that the ``psycopg2`` [copy_to](http://initd.org/psycopg/docs/cursor.html#cursor.copy_to) command does not work with hypertables, only with chunks.

```
import sys
with connection.cursor() as cursor:
     cursor.copy_to(sys.stdout, 'my_hypertable', sep=',')
```
Returns no data while ``\copy (SELECT * FROM my_hypertable) TO STDOUT`` works.

I am using
```
psycopg2-binary==2.7.4
timescaledb:0.9.2-pg10
```
Feel free to close the issue since this seems to be more ``psycopg2`` related.

**Comment by LeeHampton** [comment]
Interesting, it seems like the client isn't recognizing `my_hypertable` as a hypertable. Out of curiosity, if you run `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` in the same session as your `psychopg2` copy query, what is the output if any and does that make the copy work? 

I will try to reproduce with `psychopg2` as well.

**Comment by thaxy** [comment]
Thanks for your reply. It's the same behaviour. The exported file is empty.

```
with connection.cursor() as cursor:
            cursor.execute(
                '''
                CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;           
                '''
            )
            cursor.copy_to(sys.stdout, 'my_hypertable', sep=',')
```

**Comment by davidkohn88** [comment]
I believe this is a limitation of inherited tables in Postgres. For now, I'd use psycopg2's  `copy_expert` instead.

**Comment by thaxy** [comment]
I got the same problem with ``copy_expert``.
`cursor.copy_expert('COPY my_hypertable TO STDOUT WITH CSV HEADER;', sys.stdout)` returns only the headers but no data. Does the ``copy_expert`` command work for you?

**Comment by davidkohn88** [comment]
Sorry, you can use copy expert to do the `select * from my_hypertable` inside of the copy command.

**Comment by thaxy** [comment]
@davidkohn88 Maybe I don't understand it right but I am not able to make the ``copy_expert`` work. Nothing gets printed to STDOUT.

`cursor.copy_expert('SELECT * FROM my_hypertable',  sys.stdout)`

**Comment by davidkohn88** [comment]
I think you need to specify the full copy statement with copy expert, so something like `cursor.copy_expert('COPY (SELECT * FROM my_hypertable) TO STDOUT', sys.stdout)` should work better for you. http://initd.org/psycopg/docs/cursor.html#cursor.copy_expert

**Comment by mfreed** [comment]
Closing this for now; please feel free to re-open if continue to see issues.
