### ISSUE TITLE
[Flaky test] bgw_launcher doesn't see wait_event_changed

### ISSUE THREAD

**Issue by jchampio** [timescale/timescaledb#5330]
### Which test is flaky?

bgw_launcher

### Since when has the test been flaky?

February 14, 2023

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/4175600633/jobs/7233369995

### Log output

```bash
diff -u /home/runner/work/timescaledb/timescaledb/test/expected/bgw_launcher.out /home/runner/work/timescaledb/timescaledb/build/test/results/bgw_launcher.out
--- /home/runner/work/timescaledb/timescaledb/test/expected/bgw_launcher.out	2023-02-14 15:55:10.826147051 +0000
+++ /home/runner/work/timescaledb/timescaledb/build/test/results/bgw_launcher.out	2023-02-14 15:56:26.894945058 +0000
@@ -142,7 +142,7 @@
 AND datname = :'TEST_DBNAME_2';
  wait_event_changed 
 --------------------
- t
+ f
 (1 row)
 
 -- Test stop
```

**Comment by mkindahl** [comment]
https://github.com/timescale/timescaledb/actions/runs/4293598537/jobs/7482111370

**Comment by mkindahl** [comment]
https://github.com/timescale/timescaledb/actions/runs/5962846019/job/16174855866?pr=5994

**Comment by mkindahl** [comment]
Still flaky:

https://github.com/timescale/timescaledb-private/actions/runs/7692733531/job/20960152112?pr=1030
