### ISSUE TITLE
[Flaky test] Update tests appear to time out

### ISSUE THREAD

**Issue by jchampio** [timescale/timescaledb#5333]
### Which test is flaky?

update_test

### Since when has the test been flaky?

February 14, 2023

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/4175600653/jobs/7230751553

### Log output

```bash
(Probably better to look at the logs in the linked job.)
```

### Reason for flakiness

It looks like ten seconds might not be enough time for the database to come up when the CI is under load. I don't see an obvious failure in the logs, other than giving up.

**Comment by svenklemm** [comment]
Update tests have seen major rewrite since then so hopefully this should be fixed.
