### ISSUE TITLE
FIRST value with hierarchical continuous aggregates

### ISSUE THREAD

**Issue by martymcflysenior** [timescale/timescaledb#5341]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

When using FIRST on a hierarchical continuous aggregate, the result is not accurate. Setup a Materialized View with timescaledb.continuous for _ohlcv_1d based on the _ohlcv_1m. Attempted using FIRST function to get the FIRST open price of the day and the query: SELECT * FROM _ohlcv_1d WHERE symbol = 'MSFT' AND date::DATE = '2023-02-15' shows a result that is not FIRST. 

### TimescaleDB version affected

2.9.3

### PostgreSQL version used

14

### What operating system did you use?

OS X

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
CREATE TABLE IF NOT EXISTS public.raw_trade_data
(
    symbol text COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    volume double precision,
    "time" timestamp with time zone NOT NULL
)

SELECT public.create_hypertable('raw_trade_data', 'time');   

CREATE MATERIALIZED VIEW IF NOT EXISTS _ohlcv_1m
	WITH (timescaledb.continuous) AS
		SELECT time_bucket('1 minute'::interval, time) as date,
		symbol, 
		FIRST(price, time) AS open, 
		MAX(price) AS high, 
		MIN(price) AS low, 
		LAST(price, time) AS close,
		LAST(volume, time) AS volume
    FROM raw_trade_data
    GROUP BY 1,2 WITH DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS _ohlcv_1d
WITH (timescaledb.continuous) AS
	SELECT time_bucket('1 day'::interval, date) as date,
	symbol,
	FIRST(_ohlcv_1m.open::numeric, date) AS open
FROM _ohlcv_1m
GROUP BY time_bucket('1 day'::interval, date),symbol
WITH DATA;

SELECT * FROM _ohlcv_1d WHERE symbol = 'MSFT' AND date::DATE = '2023-02-15'

Not Accurate Result:
“2023-02-15 19:00:00-05”	“MSFT”	269.32

SELECT
_ohlcv_1m.date, _ohlcv_1m.symbol, _ohlcv_1m.open
FROM _ohlcv_1m
WHERE _ohlcv_1m.symbol IN ('MSFT')
AND _ohlcv_1m.date BETWEEN '2023-02-15 4:00'::timestamptz AND '2023-02-15 9:30'::timestamptz
GROUP BY 1,2,3
ORDER BY symbol,date ASC
LIMIT 1

Accurate Result:
“2023-02-15 04:00:00-05”	“MSFT”	271.8
```

### How can we reproduce the bug?

```bash
1. Create hypertable for tick data (raw_trade_data)
2. Setup a Materialized View with timescaledb.continuous for _ohlcv_1m based on tick data
3. Use timescale version 2.9.3 for hierarchical continuous aggregates
4. Setup Materialized View with timescaledb.continuous for _ohlcv_1d based on the _ohlcv_1m
5. Expect to use FIRST function on the new hierarchical continuous aggregate (_ohlcv_1d) in order to get the first open price of the day. Example: FIRST(_ohlcv_1m.open::numeric, date) AS open
6. Result when SELECTING:
SELECT * FROM _ohlcv_1d WHERE symbol = 'MSFT' AND date::DATE = '2023-02-15'
is not accurate. 
Not Accurate Result:
“2023-02-15 19:00:00-05”	“MSFT”	269.32

Notice the time which is not the first of the day.
```

**Comment by shhnwz** [comment]
Hi @martymcflysenior ,

Thanks for reporting this issue. To confirm this as a bug we need to reproduce this in-house.  It would be great if you could provide the DDL for _ohlv_1d.

**Comment by martymcflysenior** [comment]
@shhnwz, please see below: 

tsdb=# \d
                      List of relations
 Schema |        Name         |       Type        |  Owner   
--------+---------------------+-------------------+----------
 public | _ohlcv_1d           | view              | postgres
 public | _ohlcv_1m           | view              | postgres
 public | _ohlcv_2m           | view              | postgres
 public | raw_trade_data      | table             | postgres

Please let me know if there's anything else I can provide.

**Comment by jnidzwetzki** [comment]
Hello @martymcflysenior,

Thank you for updating the issue and providing all these details. I tried to reproduce the behavior with a small self-generated test dataset but I was not able to reproduce the behavior so far. Might it be possible to share some test data (e.g., by adding some `INSERT` statements to the issue description) so that I can reproduce the issue locally?

**Comment by martymcflysenior** [comment]
No problem. I'll get a full working example.
