### ISSUE TITLE
Exact boundaries of histogram buckets and min/max values

### ISSUE THREAD

**Issue by mbgonicus** [timescale/timescaledb#535]
The (documentation about the histogram function) has left me with open questions regarding the exact boundaries of the min/max values and the histogram intervals. Regarding the example there:

```sql
SELECT device_id, histogram(battery_level, 20, 60, 5)
  FROM readings
  GROUP BY device_id
  LIMIT 10;
```

1. Are values that are equal to 20 or to 60 included in the buckets? The documentation implies that, but I think it should be stated explicitly.
2. Depending on that, what are the exact intervals of the buckets? This example expects 5 buckets within the interval from 20 to 60. I expect the bucket size to be (60 - 20) / 5 = 8. So the bucket intervals are (each including): [20..27], [28..35], ..., [52..59]? Thus the value of 60 is not included. If it was included, the bucket size cannot be 8, but 41 / 5. I guess the question could be reduced to: if a value is exactly "between" to buckets, will it be put into the lower or the higher interval?

This might be defined by the "mathematical definition of a histogram", but I think the documentation should express explicitly
1. If the min and max values are included or excluded,
2. how the buckets are constructed and what their exact intervals/boundaries are,
3. what the specific buckets/boundaries in that example are.

If someone tells me the answer, I'm willing to provide a PR for the documentation.

ps: I was unable to get the answer by reading [histogram.c](https://github.com/timescale/timescaledb/blob/master/src/histogram.c).

**Comment by RobAtticus** [comment]
Hi @mbgonicus , sorry meant to answer this earlier:

1) The min value is included is included in the buckets, but the max is not. That is, the buckets are inclusive on their lower boundary but exclusive on the upper boundaries. 

2) So for your example it would:
[20,28), [28,36), [36,44), [44,52), and [52,60). 

In the result there are also "extra" buckets for anything < the lower bound and anything >= to the upper bound.

**Comment by mbgonicus** [comment]
Thank you @RobAtticus  that clears it.

Can I make pull requests to the documentation? The git repo for the documentation seems to be empty and I'm unable to find it in the main repo. Or is it just part of the website?

**Comment by solugebefola** [comment]
This is now in the latest version of the docs.  @mbgonicus if it looks good to you, I'll close this issue.

**Comment by mbgonicus** [comment]
@solugebefola Yes, it clarifies all open questions I had. Thank you very much!
