### ISSUE TITLE
Creating a unique index without the partitioning constraints

### ISSUE THREAD

**Issue by cailin-lai** [timescale/timescaledb#536]
Hi Guys,
The following error message raised when executing create_hypertable on a time column w/o any indexes. e.g.
create table request_info(
    req_id text not null,
    app_id  int not null,
    account_id int not null,
    url_id int not null,
    req_time timestamp not null,
    trace_id text,
    total_time int
  
);
select create_hypertable('request_info','req_time');
**ERROR:  cannot create a unique index without the column "req_time" (used in partitioning)**

It actually can be resolved by adding the time column to PK or CONSTRAINT as prefix, but, it seems not a good design since the time column (or combine with other data key) may not be unique in concurrent case, that means we've to combine a uuid key (e.g. req_id) to avoid this limitation, it might make index size to be bigger...
Any thoughts to avoid this limitation?

Thanks,

Cailin

**Comment by LeeHampton** [comment]
@cailin-lai , I'm actually having trouble reproducing this in a clean PostgreSQL session. Did you make any other alterations between the `create table` you posted here and the `create_hypertable()` call? 

You should be able to create a hypertable without any issues based on the DDL for `request_info` above. 

If that error actually arises from a later attempt to create a unique constraint on a hypertable field, that makes sense -- you'll need the time column as a prefix. TimescaleDB does not globally index fields for hypertables -- they are local for each chunk. By requiring a prefix on the time-partitioning field we ensure that we don't have to look into every hypertable to make sure a field is unique. If the unique constraint is a compound index on both req_time AND the other field, that still allows for duplicate timestamps -- you just can't have a duplicate timestamp,other_field pair.

**Comment by AndyMender** [comment]
I usually create hypertable-compatible tables the following way:
```sql
CREATE TABLE IF NOT EXISTS 'table_name' (
time TIMESTAMPTZ NOT NULL,
{COLUMNS},
UNIQUE ({CONSTRAINTS}));
```
Notice the `UNIQUE` block at the very end of the query. This enforces creation of a unique index for at least the 'time' column. A subsequent call then works:
```sql
SELECT create_hypertable('table_name', 'time');
```
I typically create a compound unique index for 'time' and 'id'.

**Comment by cailin-lai** [comment]
Thanks @LeeHampton  and @AndyMender for the reply.
@LeeHampton, it still can be reproduced in my environment (pg 10.3 on CentOS Linux release 7.4) if I just create a hyper table on a table without any unique constraints. Well, I tried on another machine, same steps are fine with pg-9.6.3 on a CentOS Linux release 7.2 box. Probably, it comes from something like environments? 
@AndyMender, yes, the error message indeed disappears in case of adding a unique index combined with time and unique id(e.g. req_id), for my case.

**Comment by VishalRam** [comment]
Any update on this post? 
@cailin-lai  - Did the issue get resolved? I'm facing the same issue.

**Comment by soccerdroid** [comment]
Having the same issue with a Django model table, but every table has an id column which is unique. Any suggestion/ idea of how can I solve this issue?

**Comment by cailin-lai** [comment]
@RobAtticus , it was the latest version v0.9.2. Sorry for the delayed response, since I've moved TimescaleDB to another box  (CentOS 7.2) and it works well, like I mentioned above, it only happens on CentOS 7.4 for me.

**Comment by cailin-lai** [comment]
Hi  @VishalRam, 
It works well on CentOS 7.2, the issue happens on CentOS 7.4 for me. So I just changed my box.

**Comment by soccerdroid** [comment]
Worked it out by altering the table: first I deleted the id column, the created the hypertable and then restored the id column. Why can I do this? Because at the end I can still have a hypertable with a column with a unique constraint.

**Comment by EamonZhang** [comment]
Centos 7.5 
postgresql 10.6
timescaledb   1.0.0

same to you

**Comment by est** [comment]
Is it possible to enforce uniqueness of one field through out one chunk of partition?

**Comment by SeppPenner** [comment]
The error "cannot create a unique index without the column "xy" (used in partitioning)" normally only occurs if you use one column that is not used within `create_hypertable` as `PRIMARY KEY` or `UNIQUE` column (Or general as constraint). Following https://stackoverflow.com/a/55314991/5536006.
