### ISSUE TITLE
[Bug]: 2.8.0 -> 2.9.3 upgrade fails due to `Key (materialization_id)=(174) is not present in table "continuous_agg".`

### ISSUE THREAD

**Issue by kamilgregorczyk** [timescale/timescaledb#5376]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Platform/OS

### What happened?

When upgrading timescaledb cluster from 2.8.0 to 2.9.3 on pg 14 the boot operation fails:

```
root@db-investigate-1:/tmp# sudo -u postgres -- psql -X -c 'ALTER EXTENSION timescaledb UPDATE' -d db_monitoring 
ERROR:  insert or update on table "continuous_aggs_materialization_invalidation_log" violates foreign key constraint "continuous_aggs_materialization_invalid_materialization_id_fkey"
DETAIL:  Key (materialization_id)=(173) is not present in table "continuous_agg".
```

We found that there are 2 corrupted records, after deleting them on a cloned db the update was successful.

What is the good way of fixing it on a real production database? Should we simply delete these 2 records to make the upgrade work or is there something else that's broken? 

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu

### What installation method did you use?

RPM

### What platform did you run on?

Google Cloud Platform (GCP)

### How can we reproduce the bug?

```bash
No idea, it happen only on 1 out of 6 dbs that run on the same image
```

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thanks for reaching out. I would like to understand your TimescaleDB setup better. Could you share the definition of the hypertable, the definition of the affected continuous aggregate, and if it is a multi-node setup the number of data nodes you are using?

**Comment by kamilgregorczyk** [comment]
The problem is that I have plenty of hyper tables and I don’t know which one is related to these corrupted records. It is a multinode setup, one master one read replica, managed by patroni.

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thank you for getting back to us. Can you run the following query on the access node and provide us with the output for further analysis?

```sql
SELECT materialization_id, mat_hypertable_id, user_view_schema, user_view_name
  FROM _timescaledb_catalog.continuous_aggs_materialization_invalidation_log
  FULL JOIN _timescaledb_catalog.continuous_agg
  ON materialization_id = mat_hypertable_id;
```

**Comment by kamilgregorczyk** [comment]
[query_result_2023-03-02T10_59_46.561361Z.csv](https://github.com/timescale/timescaledb/files/10870641/query_result_2023-03-02T10_59_46.561361Z.csv)

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thank you for executing the query and providing us with the result. I have two general questions to understand the situation better:

* Did the error happen during the upgrade of one of the data nodes or during the upgrade of the access node?
* Did you run the query on the affected node or on the access node?

In the query result are two entries without corresponding `mat_hypertable_id`. Could you execute the following query and provide us again with the output?

```sql
SELECT * FROM _timescaledb_catalog.continuous_agg WHERE mat_hypertable_id IN (173, 174);
```

**Comment by kamilgregorczyk** [comment]
query you provided returns nothing, error happen when a master was cloned with the same disk to test the upgrade, queries do run on that master

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thank you for running the query. It seems that invalidation records do exist but no corresponding CAGG definition. Could you run the following query on the access node and provide us again with the output? This would help us to understand the situation better.

```sql
SELECT * FROM _timescaledb_catalog.continuous_aggs_materialization_invalidation_log WHERE materialization_id IN (173, 174) LIMIT 10;
```

**Comment by kamilgregorczyk** [comment]
[query_result_2023-03-03T12_17_19.517701Z.csv](https://github.com/timescale/timescaledb/files/10881908/query_result_2023-03-03T12_17_19.517701Z.csv)

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thank you for getting back to us. There are orphan records in the catalog table `_timescaledb_catalog.continuous_aggs_materialization_invalidation_log`. Please perform a backup of the table and run the following query to remove these records:

```sql
DELETE FROM _timescaledb_catalog.continuous_aggs_materialization_invalidation_log WHERE materialization_id IN (173, 174);
```

Afterward, you should be able to upgrade your TimescaleDB installation.

**Comment by kamilgregorczyk** [comment]
Thanks! This is what I wanted to confirm, whether it’s safe to delete it or not :) Wiadomość napisana przez Jan Nidzwetzki ***@***.***> w dniu 03.03.2023, o godz. 14:38:﻿
Hello @kamilgregorczyk,
Thank you for getting back to us. There are orphan records in the catalog table _timescaledb_catalog.continuous_aggs_materialization_invalidation_log. Please perform a backup of the table and run the following query to remove these records:
DELETE FROM _timescaledb_catalog.continuous_aggs_materialization_invalidation_log WHERE materialization_id IN (173, 174);
Afterward, you should be able to upgrade your TimescaleDB installation.

**Comment by jnidzwetzki** [comment]
Hello @kamilgregorczyk,

Thanks for getting back to us. Was the upgrade to TimescaleDB 2.9.3 successful after you deleted these records? Is there anything else we can do or can we close this issue?
