### ISSUE TITLE
[Bug]: Error when ::timestamp cast is specified for time_bucket when using continuous aggregate view

### ISSUE THREAD

**Issue by voluntas** [timescale/timescaledb#5383]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

As the title says, when using the continuous aggregate view, an error occurs if a ::timestamp cast is specified in the time_bucket function.

```
ERROR: continuous aggregate view must include a valid time bucket function
```

If this is the intended specification, I will create a separate issue as a request.

The reason for specifying ::timestamp is that I use a tool called [sqlc](https://sqlc.dev/) and when generating go code from SQL, it will be able to look at ::timestamp and specify the Time.time type.

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

15.1

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### How can we reproduce the bug?

The SQL that causes the problem is the following when a cast of ::timestamp is specified.

```sql
CREATE MATERIALIZED VIEW spam_minute WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 minute', timestamp)::timestamp AS "time_bucket"
    sum(email)
FROM spam
GROUP BY 1
ORDER BY 1 DESC
WITH NO DATA;
```

If you remove the ::timestamp cast as follows, it works fine.

```sql
CREATE MATERIALIZED VIEW spam_minute WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 minute', timestamp) AS "time_bucket"
    sum(email)
FROM spam
GROUP BY 1
ORDER BY 1 DESC
WITH NO DATA;
```

**Comment by jnidzwetzki** [comment]
Hello @voluntas,

Thank you very much for reaching out. The continuous aggregate expects a function that returns a `timestamptz` (timestamp with time zone). By adding the cast to `timezone,` the continuous aggregate does not consider the function as a _valid_ time bucket function that can be used. If you need a type annotation for the tool you are using, you could add a cast to `timestamptz`.

For example:

```sql
CREATE MATERIALIZED VIEW spam_minute WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 minute', timestamp)::timestamptz AS "time_bucket",
    sum(email)
FROM spam
GROUP BY 1
ORDER BY 1 DESC
WITH NO DATA;
CREATE MATERIALIZED VIEW
```

**Comment by voluntas** [comment]
Oh my God! I see. I immediately used timestamptz and confirmed that it works as expected. Thanks for the quick response.

Now we can incorporate continuous aggregate views into our services :-)

I have no problem having this issue closed. Thank you very much.
