### ISSUE TITLE
millions of metrics = millions of tables?

### ISSUE THREAD

**Issue by ultimoamore** [timescale/timescaledb#540]
Hi,

we store 5000 distinct metrics for 1200 devices; the "usual" use case is to pull 30-40 metrics for one device for a certain time frame. The metrics for the device arrive at different timestamps (that is, we can't have a table with a timestamp column and some column metrics, as the timestamp would be different).
So the schema would be either:

a) (metric name in the table name)
t timestamp,
device text,
metric double

or 
b) (device name + metric name in the table name)
t timestamp,
metric double

I guess this is a bad use scenario for timescaledb? Case "a" would be bad at querying per-device (no way to do a table scan, ever, and data would be not clustered by device as we insert in datetime order); while "b" would be impossible to handle (5M tables...).

**Comment by RobAtticus** [comment]
You can still group metrics into less tables even if most of the rows are sparse. Additionally, another way of doing it would be to so something like:
```
t TIMESTAMPTZ,
device TEXT,
metric_name TEXT,
metric_value DOUBLE
```

I think you might find the first way more performant since sparse/empty columns are pretty cheap on disk, but you can play around with both to see which performs best.

**Comment by saluker** [comment]
@ultimoamore did you come to any conclusions regarding your use case?  I'd like to test something similar and am leaning in the monolith table direction per @RobAtticus

**Comment by ultimoamore** [comment]
didn't have time to make some tests... please post your findings!

**Comment by mfreed** [comment]
As I do not believe there is anything more actionable/open here, closing out the issue.  Please re-open if there is anything else.
