### ISSUE TITLE
[Bug]: Multi-node - text-based data transfer does not work with partial aggregation

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#5407]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable, Multi-node

### What happened?

When doing `SET timescaledb.enable_connection_binary_data=false` and at the same time using partial aggregation on data nodes (with the `partialize_agg()` function), the binary partial result is converted into a text string on the data node. The deserialization then fails on the access node.

### TimescaleDB version affected

2.11.0-dev

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu 22.10

### What installation method did you use?

Source

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
Set `enable_partitionwise_aggregate=on` in  `tsl/text/postgresql.conf.in` and run test suite.
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
