### ISSUE TITLE
[Bug]: Unique index is not freed after DELETE on distributed hypertable

### ISSUE THREAD

**Issue by bielitom** [timescale/timescaledb#5435]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Data node, Distributed hypertable

### What happened?

I have a distributed hyper table on two data nodes with replication factor 2. I also have replicated access node (standby node is currently off).

```
CREATE TABLE public."data" (
	channel int8 NOT NULL,
	device int8 NOT NULL,
	ts timestamp NOT NULL,
	"type" int8 NOT NULL,
	original_ts timestamp NULL,
	source_id int8 NULL,
	string_value text NULL,
	value numeric(53, 20) NULL	
);

alter table data add constraint data_pkey primary key (device, ts, channel, type);
or:
create unique index data_pkey_idx ON public.data USING btree (device, ts, channel, type);

SELECT create_distributed_hypertable('data', 'ts', 'device', 20, chunk_time_interval => INTERVAL '14 days', replication_factor => 2);
```

My service makes insert and delete operations. After a while when there are a few chunks, I make following queries:
```
insert into data(channel, device, ts, type, value) values (1, 1, '2023-03-14 00:00:00', 0, 0);
>> Updated Rows: 1
select * from data where channel = 1 and device = 1 and ts = '2023-03-14 00:00:00' and type = 0
>> 1	1	2023-03-14 00:00:00.000	0
delete from data where channel = 1 and device = 1 and ts = '2023-03-14 00:00:00' and type = 0
>> Updated Rows: 1
select * from data where channel = 1 and device = 1 and ts = '2023-03-14 00:00:00' and type = 0
>> <empty results>
insert into data(channel, device, ts, type, value) values (1, 1, '2023-03-14 00:00:00', 0, 0);
>> SQL Error [23505]: ERROR: [dn2]: duplicate key value violates unique constraint "_dist_hyper_3_109_chunk_data_pkey_idx"
  Detail: Key (device, ts, channel, type)=(1, 2023-03-14 00:00:00, 1, 0) already exists.
```

The problem occurs permanently, and it does not matter if primary key or unique constraint is used. I assume, that the index is not properly freed in all data nodes.
Problem is not reproducible on empty hypertable. 

I tried following on the Access node without any luck:
- Adding dimensions for all the columns used in the primary key (after full recreate)
- `reindex table data;`
- delete and create unique index

### TimescaleDB version affected

2.9.3

### PostgreSQL version used

14.6

### What operating system did you use?

Ubuntu 22.04.1 LTS

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

Access Node:
```
2023-03-14 02:07:16.203 UTC [595510] ERROR:  [dn2]: duplicate key value violates unique constraint "_dist_hyper_3_109_chunk_data_pkey_idx"
2023-03-14 02:07:16.203 UTC [595510] DETAIL:  Key (device, ts, channel, type)=(1, 2023-03-14 00:00:00, 1, 0) already exists.
2023-03-14 02:07:16.203 UTC [595510] STATEMENT:  insert into data(channel, device, ts, type, value) values (1, 1, '2023-03-14 00:00:00', 0, 0)
```

Data node 2:
```
2023-03-14 02:07:16.203 UTC [595695] ERROR:  duplicate key value violates unique constraint "_dist_hyper_3_109_chunk_data_pkey_idx"
2023-03-14 02:07:16.203 UTC [595695] DETAIL:  Key (device, ts, channel, type)=(1, 2023-03-14 00:00:00, 1, 0) already exists.
2023-03-14 02:07:16.203 UTC [595695] CONTEXT:  COPY data, line 1
2023-03-14 02:07:16.203 UTC [595695] STATEMENT:  COPY public.data (channel, device, ts, type, original_ts, source_id, string_value, value) FROM STDIN WITH (FORMAT binary) /* batch 0 conn 0x7f8529363ab0 */
```

### How can we reproduce the bug?

```bash
In the description...
```

**Comment by lkshminarayanan** [comment]
Hi @Tomasz365, 

I was able to reproduce your issue with the following SQL + Bash script.

SQL Setup : 
```sql
-- Setup two data nodes locally
SELECT add_data_node('dn1', host => 'localhost', database => 'db1');
SELECT add_data_node('dn2', host => 'localhost', database => 'db2');

-- Create the table
CREATE TABLE devices (
  device_id int NOT NULL,
  time timestamptz NOT NULL,
  value float
);

-- Create the unique index
CREATE UNIQUE INDEX uidx ON devices(device_id, time);

-- Create the hypertable and populate it
SELECT create_distributed_hypertable('devices', 'time', 
   chunk_time_interval => INTERVAL '1 hour', replication_factor => 2);

INSERT INTO devices
  SELECT id, time, ceil(random() * 100)::int
    FROM generate_series(1,5,1) id,
           generate_series('2000-01-01 0:00:00+0'::timestamptz,
                             '2000-01-01 3:59:59+0','2m') time;
```

Then run the following from a bash terminal : 
```bash
InsertDeleteSQL="DELETE FROM devices \
  WHERE device_id = 1 AND time = TIMESTAMPTZ '2000-01-01 05:35:30+05:30';\
  INSERT INTO devices VALUES (1, TIMESTAMPTZ '2000-01-01 05:35:30+05:30', 100);"

for i in {1..200}
do
  echo "Attempt $i" 
  if ! psql -c "$InsertDeleteSQL"; then
    break;
  fi
done
```

This small bash snippet repeatedly deletes and inserts a tuple with the same device_id, time and breaks as soon as it encounters an error in either of these. 

After few loops, the insert actually fails thrwoing a `duplicate key value violates unique constraint "_dist_hyper_1_1_chunk_uidx"`. But when you do a SELECT for the same device_id, time pair (i.e.) 
`SELECT * FROM devices WHERE device_id = 1 AND time = TIMESTAMPTZ '2000-01-01 05:35:30+05:30';`, it returns 0 rows.

**Comment by Tomasz365** [comment]
Hello @lkshminarayanan,

Thank you for your help with the reproduction of the problem.

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
