### ISSUE TITLE
[Bug]: Planning very slow with integer time type

### ISSUE THREAD

**Issue by DVLP** [timescale/timescaledb#5463]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Query planner

### What happened?

https://docs.timescale.com/api/latest/hypertable/set_integer_now_func/
This example is shoing unix_now function with STABLE but this is cauing very slow planning as described here https://www.timescale.com/forum/t/very-slow-query-planning-time-in-postgresql/255

The example should be updated to IMMUTABLE unix_now function

For context I'm using integer based timestamps and convering all dates and intervals with extract epoch

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

15

### What operating system did you use?

not sure, latest docker image

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Create a table with integer `time` type and `unix_now` with STABLE type. Planning times when querying the hypertable are then very slow.
```

**Comment by lkshminarayanan** [comment]
Hi @DVLP, 

This is a doc bug and I have created an issue for the same at timescale/docs#2158. Thank you for reporting this.
