### ISSUE TITLE
[Bug]: Timscaledb doesn't work with Postgresql15 on macOS

### ISSUE THREAD

**Issue by chiumichael** [timescale/timescaledb#5464]
### What type of bug is this?

Configuration, Other

### What subsystems and features are affected?

Platform/OS

### What happened?

After the following the instructions for install timescaledb on macos via homebrew, the extension cannot be created within postgres (v15.2_3 on macos). Error, below, says that it's missing the symbol `_find_em_expr_for_rel` in postgres. 

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

15.2_3

### What operating system did you use?

macOS

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
tsdb=# CREATE EXTENSION IF NOT EXISTS timescaledb;
ERROR:  could not load library "/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.10.1.so": dlopen(/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.10.1.so, 0x000A): Symbol not found: _find_em_expr_for_rel
  Referenced from: <0C1D2849-EB2D-3810-9973-21849CCEA3AF> /opt/homebrew/Cellar/postgresql@15/15.2_3/lib/postgresql/timescaledb-2.10.1.so
  Expected in:     <D3849D42-6234-3124-A36A-492C0F243A9F> /opt/homebrew/Cellar/postgresql@15/15.2_3/bin/postgres
```

### How can we reproduce the bug?

```bash
Follow the instructions listed in https://docs.timescale.com/install/latest/self-hosted/installation-macos/#set-up-the-timescaledb-extension
```

**Comment by lkshminarayanan** [comment]
Hi @chiumichael 

Thank you for reaching out to Timescale.
The TimescaleDB extension available via homebrew depends on PostgreSQL 14. Can you retry the installation with PostgreSQL 14 and check if it works?

**Comment by lkshminarayanan** [comment]
Hi @chiumichael! 

I'm glad it worked! I'll close this issue for now. Please reopen it if you need any further help with this. Thank you!
