### ISSUE TITLE
How to LIMITED count by time_bucket ?

### ISSUE THREAD

**Issue by dingo9** [timescale/timescaledb#547]
I want to check data which recorded in timescaledb by using time_bucket.

```
SELECT time_bucket('1 hour', timestamp) AS hourly, count(*)
from data_tick.tick_order
where timestamp > '2018-05-18'
group by hourly
order by hourly
```

I got
```
2018-05-18 01:00:00.000000	74817
2018-05-18 02:00:00.000000	101578
2018-05-18 03:00:00.000000	49274
2018-05-18 05:00:00.000000	100337
2018-05-18 06:00:00.000000	107552
2018-05-18 07:00:00.000000	7456
2018-05-20 23:00:00.000000	41
2018-05-21 01:00:00.000000	80696
2018-05-21 02:00:00.000000	103148
2018-05-21 03:00:00.000000	44981
2018-05-21 05:00:00.000000	95883
2018-05-21 06:00:00.000000	98764
2018-05-21 07:00:00.000000	7845
```

It's cool and it is really fast. 

Is there an elegant way to check hourly count LESS than 1000 by using limit to enhance performance?

**Comment by dingo9** [comment]
Yes. But not just like
```
SELECT time_bucket('1 hour', timestamp) AS hourly, count(*)
from data_tick.tick_order
where timestamp > '2018-05-18'
group by hourly
having count(*) < 1000
order by hourly
```
Because this stat seems like calc count(*) first, then calc count(*) < 1000. 


More like (FAKE CODE)
```
FOR ts_bucket IN time_bucket('1 hour', timestamp):
    select count(*) from (
              select 1 from table where timestamp in ts_bucket LIMIT 1000
    )
```
In this statement, SQL stop counting when the bucket size is more than 1000, so it is more effective than just using having statement

**Comment by solugebefola** [comment]
The TimescaleDB/PostgreSQL query planner does not necessarily run through all conditions in order.  If you want to speed up your query you could instead run a [Count estimate](https://wiki.postgresql.org/wiki/Count_estimate)
