### ISSUE TITLE
Extension update from 0.9.1 to 0.9.2 on OSX Homebrew

### ISSUE THREAD

**Issue by avanderpluijm** [timescale/timescaledb#549]
Hi, I just updated to 0.9.2 on OSX using homebrew. 
When running the command `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` it responds with an error: `ERROR:  could not access file "timescaledb-0.9.1": No such file or directory`

Do I need to update this to timescaledb-0.9.1 somewhere?

**Comment by RobAtticus** [comment]
Are you running this on a database that already has timescaledb installed? If so, you would need to run `ALTER EXTENSION timescaledb UPDATE;` rather than `CREATE EXTENSION`. Did you restart PostgreSQL after updating via homebrew?

**Comment by avanderpluijm** [comment]
Thanks @RobAtticus ! I tried to run this on an existing database. 
Running `ALTER EXTENSION timescaledb UPDATE;` showed 

`extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.`

Doing this made it work. Also creating the extension on a new database works.

**Comment by RobAtticus** [comment]
Great, glad to hear it! Feel free to close the issue.
