### ISSUE TITLE
Cannot download TimescaleDB for Windows from website

### ISSUE THREAD

**Issue by frederikhors** [timescale/timescaledb#5491]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

Is there an issue on the website?

![image](https://user-images.githubusercontent.com/41120635/227896533-5847dd65-dc6f-4b06-969d-971c9b5ae356.png)

### TimescaleDB version affected

2

### PostgreSQL version used

15

### What operating system did you use?

WIndows

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Go to https://docs.timescale.com/install/latest/self-hosted/installation-windows/#windows-releases
```

**Comment by lkshminarayanan** [comment]
Hi @frederikhors, @oopsoh, Thank you for reporting the issue. Our team currently working on resolving it. Sorry for the inconvenience!

**Comment by jkhooper** [comment]
Same issue.

**Comment by msolovjev** [comment]
doesn't work yet

**Comment by danielskaare** [comment]
Still not possible to download. Will it be available soon? Is there anywhere else we can download it?

**Comment by aliendrew** [comment]
@danielskaare 
Currently available here: [https://github.com/timescale/timescaledb/releases/tag/2.10.1](https://github.com/timescale/timescaledb/releases/tag/2.10.1)
Ref.: [https://www.timescale.com/forum/t/time-scale-windows-zip-not-available/1460](https://www.timescale.com/forum/t/time-scale-windows-zip-not-available/1460)
