### ISSUE TITLE
[Bug]: Compressed hypertable and toast table always stored in default tablespace

### ISSUE THREAD

**Issue by bearpaws** [timescale/timescaledb#5520]
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression

### What happened?

When attaching a tablespace to a hypertable, not all files related to that hypertable are stored on the tablespace.

After compressing a chunk, the compressed hypertable and toast table are stored on the default tablespace, not the tablespace attached to the hypertable.

It was my assumption that all files related to the hypertable would live on the same tablespace.

This is related to #4000, where compressed chunks were not written to the tablespace, but that appears to have been resolved.

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.7

### What operating system did you use?

Ubuntu

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

Create tables:
```
create table test1 (id int, ts timestamptz, val double precision) tablespace space1; 
create index test1_idx on test1 (id,ts desc) tablespace space1;
select create_hypertable('test1', 'ts', chunk_time_interval => interval '1d', create_default_indexes => false);
select attach_tablespace('space1', 'test1');
alter table test1 set (timescaledb.compress, timescaledb.compress_segmentby='id');
```

Add data and compress a chunk:
```
insert into test1 values (1, now() - interval '1 month', random());
insert into test1 values (1, now(), random());
select * from show_chunks('test1');
select compress_chunk('_timescaledb_internal._hyper_9_14_chunk');
```

Not all tables and indexes are on the expected tablespace:
```
# select schemaname, tablename, tablespace from pg_tables where schemaname='_timescaledb_internal';
      schemaname       |         tablename          | tablespace 
-----------------------+----------------------------+------------
 _timescaledb_internal | _hyper_9_15_chunk          | space1
 _timescaledb_internal | _compressed_hypertable_10  | 
 _timescaledb_internal | compress_hyper_10_16_chunk | space1
 _timescaledb_internal | _hyper_9_14_chunk          | space1


# select schemaname, tablename, indexname, tablespace from pg_indexes where schemaname='_timescaledb_internal';
      schemaname       |         tablename          |                            indexname                            | tablespace 
-----------------------+----------------------------+-----------------------------------------------------------------+------------
 _timescaledb_internal | _hyper_9_15_chunk          | _hyper_9_15_chunk_test1_idx                                     | space1
 _timescaledb_internal | _compressed_hypertable_10  | _compressed_hypertable_10_id__ts_meta_sequence_num_idx          | 
 _timescaledb_internal | compress_hyper_10_16_chunk | compress_hyper_10_16_chunk__compressed_hypertable_10_id__ts_met | space1
 _timescaledb_internal | _hyper_9_14_chunk          | _hyper_9_14_chunk_test1_idx                                     | space1
```

The toast table isn't on the expected tablespace either:
```
# select relname from pg_class where oid=(select reltoastrelid from pg_class where relname='_compressed_hypertable_10');
    relname     
----------------
 pg_toast_17363

#  \d+ pg_toast.pg_toast_17363;
TOAST table "pg_toast.pg_toast_17363"
   Column   |  Type   | Storage 
------------+---------+---------
 chunk_id   | oid     | plain
 chunk_seq  | integer | plain
 chunk_data | bytea   | plain
Owning table: "_timescaledb_internal._compressed_hypertable_10"
Indexes:
    "pg_toast_17363_index" PRIMARY KEY, btree (chunk_id, chunk_seq)
```
```

**Comment by konskov** [comment]
Thank you @bearpaws for providing detailed reproduction steps, I was able to reproduce the issue on my end and will further look into it.

**Comment by remingtonc** [comment]
Does this imply that compressed table data is stored in the default tablespace for a period of time - or is the data stored in a chunk on the correct tablespace?

**Comment by konskov** [comment]
no, the actual data is always stored in the chunks (either uncompressed chunks or compressed chunks). The compressed hypertable does not hold data itself, but it is the parent table of the compressed chunks (like a hypertable in that sense).
