### ISSUE TITLE
[Bug]: `ERROR:  portal snapshots (1) did not account for all active snapshots (2)` when `CALL refresh_continuous_aggregate(...)` dynamically within `EXECUTE` clause

### ISSUE THREAD

**Issue by H25E** [timescale/timescaledb#5529]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

When calling `refresh_continuous_aggregate` dynamically within an `EXECUTE` statement the following error appears: `ERROR:  portal snapshots (1) did not account for all active snapshots (2)`

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

15.2

### What operating system did you use?

Debian 11 (bullseye)

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  portal snapshots (1) did not account for all active snapshots (2)
CONTEXT:  SQL statement " CALL refresh_continuous_aggregate(
	'my_ca',
	NULL,
	'1 minute'::INTERVAL); "
PL/pgSQL function test_refresh_ca() line 3 at EXECUTE
SQL state: XX000
```

### How can we reproduce the bug?

Given a continuous aggregate called `my_ca` and a PL/PGSQL procedure that refreshes the CA, this procedure works properly:

```PLpgSQL
CREATE OR REPLACE PROCEDURE timescale.test_refresh_ca_static(
	)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
CALL refresh_continuous_aggregate(
	'my_ca',
	NULL,
	'1 minute'::INTERVAL); $$;
	
END;
$BODY$;
```
But this one fails with the beforehand said error:

```PLpgSQL
CREATE OR REPLACE PROCEDURE timescale.test_refresh_ca_dynamic(
	)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN

EXECUTE $$ CALL refresh_continuous_aggregate(
	'my_ca',
	NULL,
	'1 minute'::INTERVAL); $$;
	
END;
$BODY$;
```

**Comment by H25E** [comment]
@RafiaSabih What are you missing?

**Comment by jnidzwetzki** [comment]
Hello @H25E,

Could you share the definition of the table / hypertable and the continuous aggregate you use in the example (i.e., the SQL commands needed to create them)? This would help us to reproduce the behavior you are facing in our environment.

**Comment by dberardo-com** [comment]
is this issue still persisting ?

**Comment by aiman-saeed** [comment]
Yes it persists.

**Comment by aiman-saeed** [comment]
Can we please reopen this?

I faced this too on timescale/timescaledb-ha:pg15.8-ts2.17.1 - whenever I prepare a dynamic statement in a procedure.

For instance, this works:
`CALL refresh_continuous_aggregate('visual_ds', NULL, INTERVAL '1 week');`

But, this doesn't:
`EXECUTE format('CALL refresh_continuous_aggregate(%L, NULL, INTERVAL %L)', _cagg.user_view_name, buffer_period);`
