### ISSUE TITLE
Install issue Windows Server Latest Postgresql 10

### ISSUE THREAD

**Issue by MatthiasWeiser** [timescale/timescaledb#555]
I see an installation error on windows - not sure why it is picking the strawberry dir for the timescaledb.control file. Where should I copy the file?
> C:\temp\timescaledb-postgresql-10_0.9.2-windows-amd64\timescaledb>setup.exe
> 2018/06/06 08:32:44 Installing TimescaleDB library files...
> 2018/06/06 08:32:44 Success!
> 2018/06/06 08:32:44 Installing TimescaleDB control file...
> 2018/06/06 08:32:44 Could not install file timescaledb.control: open C:/Strawber
> ry/c/share/extension/timescaledb.control: The system cannot find the path specif
> ied.
> Press ENTER/Return key to close...
> 
>

**Comment by MatthiasWeiser** [comment]
I think the issues comes from having a mixture of a standard Postgresql installation and Strawberry perl which contains mingw on the same box.

**Comment by RobAtticus** [comment]
That would be the case, because it seems to be installing it to Strawberry which has it's own copy of PostgreSQL? If there are multiple copies of PostgreSQL installed it's going to cause problems. You could run setup.exe from the command line and pass it the `-pgconfig` flag that points it to the pg_config binary associated with the correct PG instance.

**Comment by MatthiasWeiser** [comment]
StrawberryPerl has a MinGW, but not a Postgresql install.

**Comment by RobAtticus** [comment]
Hi @MatthiasWeiser , any luck resolving this? I'm afraid I don't know enough about StrawberryPerl to be much help

**Comment by mfreed** [comment]
Hi @MatthiasWeiser Following up on this...?

**Comment by MatthiasWeiser** [comment]
I have installed it successfully using -pgconfig option.

**Comment by gunnihinn** [comment]
I have the same issue.

> I have installed it successfully using -pgconfig option.

Could you give a little more detail @MatthiasWeiser, if you still happen to remember what you did?
