### ISSUE TITLE
[Bug]: Unique constraints are not always respected on compressed tables

### ISSUE THREAD

**Issue by kgyrtkirk** [timescale/timescaledb#5553]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

Successfull insert into compressed chunk which violates unique constraint

Unique constraint violation is detected during decompression.

https://github.com/kgyrtkirk/reprox/blob/compressed-unique-err/unique_err.pgsql

### TimescaleDB version affected

current main

### PostgreSQL version used

15.2

### What operating system did you use?

docker

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
https://github.com/kgyrtkirk/reprox/blob/compressed-unique-err/unique_err.pgsql
```

**Comment by kgyrtkirk** [comment]
* first row
  * loads chunk `C`
  * uncompresses affected rows by `segment_by` cols  (there is none)
  * `C` is placed in a cache [here](https://github.com/timescale/timescaledb/blob/b136bb554baf08bfc7f648a9d5f8ec59402230a3/src/nodes/chunk_dispatch/chunk_dispatch.c#L150)
* second row
  * decides to skip decompression because `C` as its already in the cache
  * violating rows with matching `segment_by` values are not decompressed
* both rows are allowed to be inserted

[compact repro](https://github.com/kgyrtkirk/reprox/blob/compressed-unique-err/unique_err_compact.pgsql)

**Comment by kgyrtkirk** [comment]
options:

## A - disable the cache

* trivially fixes the issue...
* negatively impacts reasonable use cases as well like when 100 rows are inserted with the same segmentby columns

## B - save the segmentby values for the chunk which was covered

* it will still do `distinct segment_by_col` scans (currently seqscan) on the underlying table
* if the seqscan will be replaced by an index scan - it will be good

## C - uncompress more affected rows in one go

* uncompress multiple segmentby batches in on go
* this would kinda mean switching to batch processing and then back
* not neccessarily worth the complexity

## D - fully decompress the chunk in case of an insert

I think from the above `B` is the logical choice; or `A` if needed in a hurry

**Comment by kgyrtkirk** [comment]
@antekresic: Could you think of any other approaches?

**Comment by svenklemm** [comment]
I think we need to trigger decompression independant of whether the chunk comes from cache or not. Since we plan to make decompression more granular not less, decompressing full chunk is not acceptable. Keeping track of only segmentby is also suboptimal since there can be multiple segmentby but also further planned changes to the decompression will only decompress a subset of segmentby.

**Comment by kgyrtkirk** [comment]
> further planned changes to the decompression will only decompress a subset of segmentby.

you mean something like: take into account the columns inside the unique constraint and decompress only a show-case row?

**Comment by svenklemm** [comment]
We dont want to disable the cache altogether but we need to decouple decompression from the cache since their granularity is very different and will even widen with the planned changes to take orderby columns into account as well.
