### ISSUE TITLE
Update Wikipedia article

### ISSUE THREAD

**Issue by kjohnsen** [timescale/timescaledb#558]
Timescale isn't on the Wikipedia [Time series database](https://en.wikipedia.org/wiki/Time_series_database) article

**Comment by mfreed** [comment]
@kjohnsen We would be happy for a community member like yourself to submit a change to Wikipedia!

**Comment by kjohnsen** [comment]
Done. Now Timescale needs its own article, but at least it's referenced on the *Time series database* article

**Comment by mfreed** [comment]
Sorry, you've been reverted.  That seems to happen a *lot* on that page :(

https://en.wikipedia.org/w/index.php?title=Time_series_database&action=history

Maybe something like these news articles would help?

https://techcrunch.com/2018/04/21/timescale-db/
https://www.nextplatform.com/2018/01/25/time-time-series-databases/

**Comment by mfreed** [comment]
Wikipedia page has been updated in later 2018 to include TimescaleDB.
