### ISSUE TITLE
Get chunk time interval

### ISSUE THREAD

**Issue by vanwalj** [timescale/timescaledb#559]
Hello !

Is there any way to get an existing chunk time interval and the current chunk time interval ?

thanks !

**Comment by mfreed** [comment]
Please see http://docs.timescale.com/latest/api#chunk_relation_size_pretty.  E.g.

```
SELECT chunk_table, partitioning_columns, ranges FROM chunk_relation_size_pretty('<HYPERTABLE NAME>');
```

**Comment by vanwalj** [comment]
Perfect, it worked, thanks :)

**Comment by jianhaiqing** [comment]
If the hypertable is created just, we still can't get the chunk time.

**Comment by bboule** [comment]
@jianhaiqing  if you run SELECT * FROM chunk_relation_size_pretty('cpu');  w4and sub cpu for the name of your hypertable you will get the chunk ranges... have you tried that?

**Comment by shane-axiom** [comment]
In 2.x you want

```
SELECT * FROM timescaledb_information.chunks;
```

**Comment by kuchaguangjie** [comment]
It query existing chunk interval, but doesn't show the setting for next new chunk .. any way to query that ?

**Comment by nsmith-griid** [comment]
This selects the interval in days. 

`select dimension.interval_length || ' usec' as interval_days
    from _timescaledb_catalog.hypertable
        left join _timescaledb_catalog.dimension on hypertable.id = dimension.hypertable_id
    where
        _timescaledb_catalog.hypertable.table_name = 'my_table'`
