### ISSUE TITLE
[Bug]: TimescaleDB Hypertable size showing wrongly

### ISSUE THREAD

**Issue by pratapagiri** [timescale/timescaledb#5590]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Configuration

### What happened?

**(1) Problem with table size (bytes)**
I have created hypertable **metric_1** with 4 columns: time, value, quality and series_id
The column types are: time (timestamp without tz), value (double precision), quality (text) and series_id(bigint)

when I calculated the typical row size (in bytes) = 8 (timestamp)  + 8 (double precision) + 12 (text) +8 (bigint) = 36 bytes

I have inserted two rows into the table and checked the size
`
my_timeseries=# select * from hypertable_detailed_size('metric_1');
 table_bytes | index_bytes | toast_bytes | total_bytes | node_name
-------------+-------------+-------------+-------------+-----------
        **8192 |       73728 |       16384 |       98304 |**
(1 row)

my_timeseries=# select * from metric_1;
        time         | value |   quality    | series_id
---------------------+-------+--------------+-----------
 2023-04-19 14:00:00 |  4072 | questionable |         3
 2023-04-19 14:15:00 |  7853 | questionable |         3
(2 rows)

`
I expected the table size (bytes) to be **72** bytes for 2 rows (each row is 36 bytes). But it shows me as 8192 bytes.

Can someone explain me why this is showing different result?

**(2) Storage Capacity Planning**
We are trying to storage capacity planning for the following:
100 assets, one row every 15mins, data retention=5 days

Can someone help me with how to determine the storage size for this requirement?

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.4

### What operating system did you use?

Ubuntu 14.4-1

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
This is in k8s environment. Relevant output attached above.
```

### How can we reproduce the bug?

```bash
(1) Create 'metric_1' hypertable with 4 columns and standard chunk size (timestamp with no tz, double precision, text and bigint)
(2) Insert 2 rows
(3) Check size using hypertable_detailed_size('metric_1');
```

**Comment by akuzm** [comment]
Postgres stores data in pages of 8kB, and it can't use less than one page, so 8kB is the minimum size you're going to see. There might also be some system data associated with the table, which would increase the size even further. This question has some interesting details on how to measure the table or row size in Postgres: https://dba.stackexchange.com/questions/23879/measure-the-size-of-a-postgresql-table-row

**Comment by pratapagiri** [comment]
@akuzm Thanks for your reply.
If one page size is going to be 8kB then is there a way to know how many rows can be fit into each page?
This will help me in planning the storage. 

Can you provide some references on TimescaleDB storage capacity planning ?

**Comment by akuzm** [comment]
For storage capacity estimation, you can follow the general Postgres practice. I would create a representative table with sample data that has many pages (e.g. up to 1MB), and extrapolate from that.  The difference is that TimescaleDB will be significantly more storage-efficient if you enable compression.

**Comment by pratapagiri** [comment]
@akuzm Thanks again for your inputs.
How to determine the number of rows that can be stored in a single Page (8kB)?

**Comment by nikkhils** [comment]
@pratapagiri Alexander has already provided a link to estimate row size.

https://dba.stackexchange.com/questions/23879/measure-the-size-of-a-postgresql-table-row

Please try a few things at your end for your specific hypertable to estimate the number of rows per page for your use case. 

Please insert a few rows and check when the next 8KB page gets used. If I would have to make a rough guess, assuming row headers and page header and line pointer overhead per page, you should get about 100 or so rows in one page for the sample rows that you have provided in your report above.

**Comment by nikkhils** [comment]
To close this issue, please take a look at the [stattuple](https://www.postgresql.org/docs/current/pgstattuple.html) extension as well. It can be used to get the estimates of rows per page. 

So, if for example, you have performed 100K inserts into your table, then you can run:

```
SELECT 100000/ pg_relpages('test');
```

to get the number of rows per page for that specific table. You can also look at this extension for other interesting stats/information.

**Comment by pratapagiri** [comment]
@nikkhils  Thanks for your inputs. This really helps.

Is there any way to estimate the *index size*  ?
