### ISSUE TITLE
Performance on hyper table

### ISSUE THREAD

**Issue by gaush123** [timescale/timescaledb#561]
Hi,

I've been trying out timescaledb for the first time. Though I am not able to perceive any performance improvement on a sample table I generated, both in terms of insertions and queries. I am getting an IOPS of ~950, both on vanilla postgres and timescaledb on a t2.xlarge instance. 

I am using a python script to insert data row by row. Copy command is way faster but that has less practical application in our case.

I've a table with below structure, with about 19 MM rows

                            Table "public.events_5aa7b71bd0df368e46dede9e_hyper"
  Column   |          Type          | Collation | Nullable | Default | Storage  | Stats target | Description 
-----------+------------------------+-----------+----------+---------+----------+--------------+-------------
 appid     | character varying(150) |           |          |         | extended |              | 
 did       | character varying(200) |           |          |         | extended |              | 
 key       | character varying(200) |           |          |         | extended |              | 
 segment   | jsonb                  |           |          |         | extended |              | 
 eventtime | integer                |           | not null |         | plain    |              | 
 dt        | character varying(50)  |           |          |         | extended |              | 

Indexes:
    "events_5aa7b71bd0df368e46dede9e_hyper_eventtime_idx" btree (eventtime)

While creating chunks on 'eventtime' on per day basis, I get about 100 chunks. Insertion and query time are as good as vanilla postgres
I also tried with converting my dt varchar column to date and making chunks based on that, but it didn't improve the performance either. 
Any suggestions on improving performance, specially inserts are appreciated.

**Comment by mfreed** [comment]
Two things:

1. A table of 19M rows is likely too small to see anything in the way of insertion improvements, especially for an .xlarge instance.  You are likely still keeping everything in memory.  See the graphs here:   https://blog.timescale.com/timescaledb-vs-6a696248104e

2. Could you describe a bit more what you mean by "950 IOPS"?  Is this something about the end-to-end insertion (or query) rate?  Or the disk IO as measured by AWS metrics?   How many rows are you inserting in each INSERT command, and what is the speed of rows-per-sec?  

If 1 row per insert -> you should batch.  See https://blog.timescale.com/time-series-data-why-and-how-to-use-a-relational-database-instead-of-nosql-d0cd6975e87c#8369

If you mean 950 rows / second -> This is really low.  I'm not sure about your python setup, or where the writer is located related to the server, but the bottleneck might be on the client side as well.

**Comment by mfreed** [comment]
Hi @gaush123 Following up on my questions last month...  Are you still seeing issues?

**Comment by gaush123** [comment]
Hi @mfreed Thanks for the response.
We're now good with issues related to insert speed. Using copy and insert with batch is faster for sure.  
We've now tested with 350 MM rows table inserts are good. 
There are few issues with query time, but maybe I can post that separately as we progress

**Comment by gaush123** [comment]
Also, I've question regarding distribution of chunks size in a timescaledb table. In my tables which have  data for only 20 days, I can see there are about 900 chunks, which I distributed based on my 'time' column which is unix value, with chunk_time_interval => 86400. 
Number of chunks look to high, also on analyzing sizes of the chunks variance is too high, ranging from 30 MB to 16 GBs (barring outliers, since outliers chunks size is 10Kbs etc). I am very much sure of the flow of the incoming data which is uniform, with low variance, and it doesn't match with variance of chunks sizes @mfreed

**Comment by mfreed** [comment]
Please confirm that your UNIX timestamp is being stored as *seconds*, rather than something highly finer fidelity?  Also, when you have created `create_hypertable`, did you specify any additional space partitioning?  One way to check is to see the details of your partitioning via:  http://docs.timescale.com/latest/api#chunk_relation_size_pretty

**Comment by mfreed** [comment]
Given that this issue seems more like a specific performance tuning example, rather than a general question -- and it's been quiet for more than 2 months -- I'm closing out the issue.
