### ISSUE TITLE
FATAL:  extension "timescaledb" must be preloaded but I have in config file

### ISSUE THREAD

**Issue by dplautjhmi** [timescale/timescaledb#562]
I have the following line in postgresql.conf:
shared_preload_libraries = 'timescaledb'

If I run this: CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
I get: FATAL:  extension "timescaledb" must be preloaded 

in pgAdmin4 if I right click the database and try to add an extension I can see timescaleDB in the drop-down list of extensions. If I proceed I get "Internal server error."

I don't know what I'm doing wrong. Any help appreciated.

v10.4

**Comment by RobAtticus** [comment]
Did you restart PostgreSQL after updating your postgresql.conf?

**Comment by dplautjhmi** [comment]
Maybe I didn't, I have no other explanation. Works now.

**Comment by Rama258** [comment]
> Did you restart PostgreSQL after updating your postgresql.conf?

do you mean to close it and reopen it again ,or there is another way to restart?
