### ISSUE TITLE
[Bug]: Policy refresh window too small for bigint time

### ISSUE THREAD

**Issue by iskyd** [timescale/timescaledb#5620]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I have created an hypertable that stores open, high, low, close and volume every five minutes using time as bigint.
Then I've created a continous aggregation as follow

```
CREATE MATERIALIZED VIEW price_daily
WITH (timescaledb.continuous) AS
SELECT
    time_bucket(86400, time) as interval,
    first(open, time) as o,
    max(high) as h,
    min(low) as l,
    last(close, time) as c,
    sum(volume) as v
FROM dev_index_btceur_300
GROUP by interval;
```

Now I'm trying to add a refresh policy doing

```
SELECT add_continuous_aggregate_policy('price_daily',
  start_offset => EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint - 864000,
  end_offset => EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint - 86400,
  schedule_interval => INTERVAL '1 days');
```

This gives me the error: 

> ERROR:  policy refresh window too small
> DETAIL:  The start and end offsets must cover at least two buckets in the valid time range of type "bigint".

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

12.12

### What operating system did you use?

Debian

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE prices(
  time BIGINT,
  high INT,
  low INT,
  PRIMARY KEY (time)
);

SELECT create_hypertable('prices', 'time', chunk_time_interval => 2592000);

CREATE FUNCTION current_epoch() RETURNS BIGINT
LANGUAGE SQL STABLE AS $$
SELECT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint;$$;

SELECT set_integer_now_func('prices', 'current_epoch');

CREATE MATERIALIZED VIEW prices_daily
WITH (timescaledb.continuous) AS
SELECT
    time_bucket(86400, time) as interval,
    max(high) as h,
    min(low) as l
FROM prices
GROUP by interval;

SELECT add_continuous_aggregate_policy('prices_daily',
  start_offset => EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint - 259200,
  end_offset => EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint - 86400,
  schedule_interval => INTERVAL '1 days');
```

**Comment by konskov** [comment]
hi @iskyd, thank you for the reproduction steps. I am able to reproduce this, and will look further into it.

**Comment by iskyd** [comment]
Hi @konskov I think doing this instead gives no error but I have not tested if it is actually working.

```
SELECT add_continuous_aggregate_policy('prices_daily',
  start_offset => 259200,
  end_offset => 86400,
  schedule_interval => INTERVAL '1 days');
```

**Comment by konskov** [comment]
Ah indeed, this is how you would define your continuous aggregate policy to run every day and refresh data from three days ago to 1 day ago. The `start_offset` and `end_offset` will be subtracted from the current time when executing the policy to compute the refresh window then. Glad you found the solution, and sorry for the confusion before, I was not attentive enough.
