### ISSUE TITLE
[Bug]: error: PostgreSQL/15/lib/timescaledb-2.10.2.dll Unable to load library The specified module could not be found

### ISSUE THREAD

**Issue by lyriumbytes** [timescale/timescaledb#5631]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Seems to be that the dependencies libssl-1_1-x64.dll and libcrypto-1_1-x64.dll are missing after installation. We were able to fix it by adding `C:\Program Files\Git\mingw64\bin` as system variable. Dlls are not present in the lib Folder of the Postgresql installation, only similarly named ones i.e. libssl-3-x64.dll were present. 

### TimescaleDB version affected

2.10.2

### PostgreSQL version used

15.2

### What operating system did you use?

Windows 10

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Clean Windows machine without anything else apart from an installation of PostgreSQL.
```

**Comment by MCH-SMF** [comment]
did you find a solution for this problem , i have the same issue, i'm not able to start my pg server

**Comment by lyriumbytes** [comment]
> 

Installed git, those files are present in mingw64/bin. Either move them to the Postgres lib folder or add the path to env variables.

**Comment by MCH-SMF** [comment]
Thanks but it's working when i installed the last  version of timescaleDB : [https://sourceforge.net/projects/timescaledb.mirror/](url)

**Comment by Vildsvinet** [comment]
" adding C:\Program Files\Git\mingw64\bin as system variable. "
this worked for me too. crazy. original error message wasn't very helpful, was it. but thanks! :)

**Comment by jvanlangen** [comment]
This is still a problem today..

**Comment by jnidzwetzki** [comment]
Hi @jvanlangen,

Thanks for bringing this up. Could you elaborate on which kind of problem you face? Did the installation of OpenSSL not help to load the extension?

**Comment by amiller8605** [comment]
I also had this issue with 2.14.2.   

According to the [Prerequisites](https://docs.timescale.com/self-hosted/latest/install/installation-windows/):
_To install TimescaleDB 2.11.2 or later, make sure you have installed OpenSSL 3.x.
For older versions of TimescaleDB, OpenSSL 1.1.1 is required.

So, I tried with OpenSSL-3 installed but still got the error message:
_ERROR:  could not load library "...timescaledb-2.14.2.dll": The specified module could not be found.

Troubleshooting with Dependency Walker revealed that the library needed OpenSSL-1 dll files, not OpenSSL-3. After I got that in place, it worked.

**Comment by basicbasic** [comment]
Temporary workaround based on Sanprof's comment here: https://stackoverflow.com/questions/76225090/the-specified-module-could-not-be-found-postgres-15-2-with-timescale-2-10-3

For Windows you can download the dlls you need here: https://wiki.overbyte.eu/wiki/index.php/ICS_Download
At this link: https://wiki.overbyte.eu/arch/openssl-1.1.1w-win64.zip

Unzip this and you'll find libcrypto-1_1-x64.dll and lbssl-1_1-x64.dll without having to install anything. Copy them to the your postgres versions lib directory (e.g. C:\Program Files\PostgreSQL\16\lib) and the extension can be created.

V16 of Postgres, V2.14.2 of timescaledb and Windows 11.

**Comment by mosesarigbedered** [comment]
> Temporary workaround based on Sanprof's comment here: https://stackoverflow.com/questions/76225090/the-specified-module-could-not-be-found-postgres-15-2-with-timescale-2-10-3
> 
> For Windows you can download the dlls you need here: https://wiki.overbyte.eu/wiki/index.php/ICS_Download At this link: https://wiki.overbyte.eu/arch/openssl-1.1.1w-win64.zip Needless to say that an unsupported version of SSL will likely be removed sooner rather then later.
> 
> Unzip this and you'll find libcrypto-1_1-x64.dll and lbssl-1_1-x64.dll without having to install anything. Copy them to the your postgres versions lib directory (e.g. C:\Program Files\PostgreSQL\16\lib) and the extension can be created.
> 
> V16 of Postgres, V2.14.2 of timescaledb and Windows 11.

This worked
