### ISSUE TITLE
[Bug]: Segmentation fault + server crash when inserting on a newly restored database.

### ISSUE THREAD

**Issue by JamesC-Conxx** [timescale/timescaledb#5638]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Command processing, Data ingestion, Restore

### What happened?

We are migrating to a new server, and updating things in the process. Following the pg_dump and pg_restore documentation (https://docs.timescale.com/self-hosted/latest/backup-and-restore/pg-dump-and-restore/), we created a database backup from a server with postgresql 11.6 and timescaledb 1.5.1, to a new server using the newer postgresql 14.7 and timescaledb 2.10.1. Everything goes smoothly, we are able to run queries and other commands fine, however when trying to insert into tables using timescaledb, we get an error message that the server closed unexpectedly. Looking into the logs, there is a segmentation fault and it crashes the server. We are able to insert into tables that aren't using timescale, but anything that is fails. The example here is attempting to write test values to the table "syslogd", which is a timescale table. 

I have searched extensively and was not able to find a solution. I am not sure if I have done something wrong, or if there is a bug, but I would appreciate any help. We are not using hypertables or multiple nodes. Thank you!
![image](https://user-images.githubusercontent.com/106363259/235221338-e82d9b72-e99d-4487-84d1-8adfb67a6f19.png)

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.7

### What operating system did you use?

Oracle Linux Server 8.7

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-04-24 13:35:45.162 EDT [247709] LOG:  server process (PID 247723) was terminated by signal 11: Segmentation fault
2023-04-24 13:35:45.162 EDT [247709] DETAIL:  Failed process was running: INSERT INTO syslogd (ip, msgtext, realdate, msgpriority)
        VALUES ('1.1.1.1', 'Test', '2023-01-01 00:00:01.00', '9');
2023-04-24 13:35:45.162 EDT [247709] LOG:  terminating any other active server processes
2023-04-24 13:35:45.167 EDT [247729] FATAL:  the database system is in recovery mode
2023-04-24 13:35:45.173 EDT [247709] LOG:  all server processes terminated; reinitializing
```

### How can we reproduce the bug?

```bash
Probably won't be able to reproduce on your end.
1. Backup from old server using pg_dump (following documentation)
2. Restore to new server using pg_restore (following documentation)
3. Attempt command:
 INSERT INTO syslogd (ip, msttext, realdate, msgpriority)
   VALUES ('1.1.1.1', 'Test', '2023-01-01 00:00:01.00', '9');
4. Crash
```

**Comment by JamesC-Conxx** [comment]
As additional information, I have already removed the "ts_insert_blocker" listed in other issues.

**Comment by nikkhils** [comment]
Hi @JamesC-Conxx 

Will it be possible to get a stack trace of the segmentation fault? Please follow instructions outlined below to get the stack trace:

https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD#On_Ubuntu

**Comment by JamesC-Conxx** [comment]
Hey @nikkhils, thanks for looking into this! 

It looks like I am missing some debug packages, but Oracle isn't finding them through the normal `debuginfo-install`. I might have to add the rpms manually, but here is the debug log for what I have from the test command in the meantime. 
[debuglog.txt](https://github.com/timescale/timescaledb/files/11392320/debuglog.txt)

**Comment by mkindahl** [comment]
@JamesC-Conxx This seems to be a bug in the continuous aggregate invalidation trigger. I assume that you have a continuous aggregate defined on that hypertable? Knowing if you have, would help us understand how to reproduce it and understand what is wrong.

**Comment by JamesC-Conxx** [comment]
@mkindahl Here are the definitions (taken from pgAdmin) from the currently running server on postgresql 11.6 and timescaledb 1.5.1, where things are working as expected. This is what we are backing up and restoring, is it just an issue with things being defined for the older version not working with the new versions?
Syslogd table:
```-- Table: public.syslogd

CREATE TABLE IF NOT EXISTS public.syslogd
(
    msgdate character varying(10) COLLATE pg_catalog."default",
    msgtime character varying(8) COLLATE pg_catalog."default",
    msgpriority character varying(20) COLLATE pg_catalog."default",
    msghostname character varying(200) COLLATE pg_catalog."default",
    msgtext text COLLATE pg_catalog."default",
    id integer NOT NULL,
    realdate timestamp without time zone NOT NULL,
    ip inet,
    tsv tsvector,
    class bigint,
    trap text COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE,
    autovacuum_analyze_scale_factor = 0,
    autovacuum_analyze_threshold = 10000,
    autovacuum_vacuum_scale_factor = 0,
    autovacuum_vacuum_threshold = 1000
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.syslogd
    OWNER to conxx;
-- Index: syslog_id_idx

-- DROP INDEX IF EXISTS public.syslog_id_idx;

CREATE INDEX IF NOT EXISTS syslog_id_idx
    ON public.syslogd USING btree
    (id ASC NULLS LAST, realdate DESC NULLS FIRST)
    TABLESPACE pg_default;
-- Index: syslog_ip_idx

-- DROP INDEX IF EXISTS public.syslog_ip_idx;

CREATE INDEX IF NOT EXISTS syslog_ip_idx
    ON public.syslogd USING btree
    (ip ASC NULLS LAST, realdate DESC NULLS FIRST)
    TABLESPACE pg_default;
-- Index: syslog_trap_idx

-- DROP INDEX IF EXISTS public.syslog_trap_idx;

CREATE INDEX IF NOT EXISTS syslog_trap_idx
    ON public.syslogd USING btree
    (trap COLLATE pg_catalog."default" ASC NULLS LAST, realdate DESC NULLS FIRST)
    TABLESPACE pg_default
    WHERE trap IS NOT NULL;
-- Index: syslogd_transfer_realdate_idx

-- DROP INDEX IF EXISTS public.syslogd_transfer_realdate_idx;

CREATE INDEX IF NOT EXISTS syslogd_transfer_realdate_idx
    ON public.syslogd USING btree
    (realdate DESC NULLS FIRST)
    TABLESPACE pg_default;

-- Trigger: set_trap

-- DROP TRIGGER IF EXISTS set_trap ON public.syslogd;

CREATE TRIGGER set_trap
    BEFORE INSERT OR UPDATE 
    ON public.syslogd
    FOR EACH ROW
    EXECUTE FUNCTION public.set_trap_column();

-- Trigger: ts_cagg_invalidation_trigger

-- DROP TRIGGER IF EXISTS ts_cagg_invalidation_trigger ON public.syslogd;

CREATE TRIGGER ts_cagg_invalidation_trigger
    AFTER INSERT OR DELETE OR UPDATE 
    ON public.syslogd
    FOR EACH ROW
    EXECUTE FUNCTION _timescaledb_internal.continuous_agg_invalidation_trigger('10');

-- Trigger: ts_insert_blocker

-- DROP TRIGGER IF EXISTS ts_insert_blocker ON public.syslogd;

CREATE TRIGGER ts_insert_blocker
    BEFORE INSERT
    ON public.syslogd
    FOR EACH ROW
    EXECUTE FUNCTION _timescaledb_internal.insert_blocker();

-- Trigger: tsvectorupdate

-- DROP TRIGGER IF EXISTS tsvectorupdate ON public.syslogd;

CREATE TRIGGER tsvectorupdate
    BEFORE INSERT OR UPDATE 
    ON public.syslogd
    FOR EACH ROW
    EXECUTE FUNCTION tsvector_update_trigger('tsv', 'pg_catalog.simple', 'msgtext');
```

Continues agg trigger function:
```-- FUNCTION: _timescaledb_internal.continuous_agg_invalidation_trigger()

-- DROP FUNCTION IF EXISTS _timescaledb_internal.continuous_agg_invalidation_trigger();

CREATE OR REPLACE FUNCTION _timescaledb_internal.continuous_agg_invalidation_trigger()
    RETURNS trigger
    LANGUAGE 'c'
    COST 1
    VOLATILE NOT LEAKPROOF
AS '$libdir/timescaledb-1.5.1', 'ts_continuous_agg_invalidation_trigger'
;

ALTER FUNCTION _timescaledb_internal.continuous_agg_invalidation_trigger()
    OWNER TO conxx;
```

**Comment by kgyrtkirk** [comment]
going from `1.5.1-pg11` to `2.10.1-pg14` is quite a leap forward :)

in the above commands I don't see any commands to create the cagg itself on the `syslog` table; but I think since you are coming from `<2.7` ; they should be upgraded to the new format anyway:
https://docs.timescale.com/use-timescale/latest/continuous-aggregates/migrate/

I think it might worth considering to drop the old caggs and re-create them again (note that newly created caggs will be  [realtime by default](https://docs.timescale.com/use-timescale/latest/continuous-aggregates/real-time-aggregates/) )
