### ISSUE TITLE
[Bug]: Not able to create hypertable for non-public schema via pgadmin or timescale api

### ISSUE THREAD

**Issue by oyearunpal** [timescale/timescaledb#5687]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Query executor

### What happened?

Below is my query. I'm able to run it successfully on psql cli.

```sql
CREATE SCHEMA IF NOT EXISTS my_schema;
CREATE TABLE IF NOT EXISTS my_schema.my_table (time timestamp, value double precision);
SELECT create_hypertable('my_schema.my_table', 'time');
```

 however when I'm running it via pgadmin it is giving me below error
 ```
 ERROR:  function create_hypertable(unknown, unknown) does not exist
LINE 3: SELECT create_hypertable('my_schema.my_table', 'time');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
SQL state: 42883
Character: 135
```

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.7

### What operating system did you use?

timescale/timescaledb-ha:pg14-latest

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
You can perform the above query via pgadmin.
```

**Comment by shhnwz** [comment]
Hi @oyearunpal ,

Thanks for contacting Timescale,

Could you share the output of \dx from psql client?

Regards
Shhnwz

**Comment by oyearunpal** [comment]
```
bcast=# \dx
                                                    List of installed extensions
        Name         | Version |   Schema   |                                      Description
---------------------+---------+------------+---------------------------------------------------------------------------------------
 plpgsql             | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb         | 2.10.1  | public     | Enables scalable inserts and complex queries for time-series data
 timescaledb_toolkit | 1.15.0  | public     | Library of analytical hyperfunctions, time-series pipelining, and other SQL utilities
 ```

**Comment by shhnwz** [comment]
Hi Arun,

I have reproduced the problem with the following steps. Please confirm if whether its the same issue or not.

1- created two databases (postgres and mydb) and superuser postgres
2- created timescaledb extension on database postgres through psql or pgadmin
3- login to database mydb with superuser postgres. (any client psql or pgadmin)
4- try to create hypertable on mydb. It gives the same function not found error.

Need some information:
1- Are you also dealing with multiple databases in your case?
2- Can you share your pgadmin screenshot with expanded all the schema for each database along with error.

**Comment by oyearunpal** [comment]
1. Yes, I'm also dealing with multiple database.
2. Not possible to share screenshot as it is production database. However the error is same as I have given above.

**Comment by shhnwz** [comment]
> 1. Yes, I'm also dealing with multiple database.
>  
>  2. Not possible to share screenshot as it is production database. However the error is same as I have given above.

Thanks for the information.
Scope of postgres Extension is at database level. The database you are connecting through pgAdmin doesn't have this extension. 
All you need to run "CREATE EXTENTION IF NOT EXISTS timescaledb with SCHEMA schema_name"
Also add that SCHEMA to your search_path.
Hope this will resolve your issue.

**Comment by oyearunpal** [comment]
I did as you said. But the issue is still persist.

**Comment by oyearunpal** [comment]
Issue gets resolve after migrating dpage/pgadmin4 from version
`6.17 => 7.3`

Thanks.
