### ISSUE TITLE
[Bug]: ERROR:  relation "_timescaledb_internal.saved_privs" does not exist while upgrading TimescaleDB

### ISSUE THREAD

**Issue by mong0520** [timescale/timescaledb#5689]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Access node

### What happened?

I am currently using TimescaleDB 2.5.1 for a while, today I am trying to upgrade it from `timescale/timescaledb:2.5.1-pg14` to `timescale/timescaledb:2.9.3-pg14` which I have done it many times on the other environment.

Steps:
```sh
psql -X "postgres://root:${PGPASSWORD}@${TSDB_HOST}:5432/mydb?sslmode=disable"
ALTER EXTENSION timescaledb UPDATE;
```

After the `ALTER` command, it shows:
```
ERROR:  relation "_timescaledb_internal.saved_privs" does not exist
CONTEXT:  SQL statement "GRANT SELECT ON "_timescaledb_internal.saved_privs" TO public"
PL/pgSQL function public.grant_privilege_func() line 9 at EXECUTE
```

I have no idea why it happens since I have done the upgrading steps many times from different version.

I also found the similar issue here: https://github.com/timescale/timescaledb/issues/5204, would you please share some ideas? thank you.

I also leave post this question on TimescaleDB's slack channel, if you need any debug information, I'd will to provide it.
https://timescaledb.slack.com/archives/C4GT3N90X/p1684237538343819.

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
Not a always reproducible case.
```

**Comment by mong0520** [comment]
more findings:

if I manually create this table into `public` schema, it can succeed
```
mydb> CREATE TABLE public.saved_privs(
       tmpnsp name,
       tmpname name,
       tmpacl aclitem[],
       tmpini aclitem[],
       UNIQUE (tmpnsp, tmpname));

NOTICE:  table
NOTICE:  grant select privilege on _timescaledb_internal.saved_privs
NOTICE:  table
NOTICE:  grant select privilege on saved_privs
NOTICE:  index
```
-----------------
however if I manually create this table for `_timescaledb_internal`, it shows the error the same with `ALTER EXTENSION timescaledb UPDATE;`

```
mydb> CREATE TABLE _timescaledb_internal.saved_privs(
       tmpnsp name,
       tmpname name,
       tmpacl aclitem[],
       tmpini aclitem[],
       UNIQUE (tmpnsp, tmpname));
relation "_timescaledb_internal.saved_privs" does not exist
CONTEXT:  SQL statement "GRANT SELECT ON "_timescaledb_internal.saved_privs" TO public"
PL/pgSQL function grant_privilege_func() line 9 at EXECUTE

```

**Comment by mong0520** [comment]
Thank you!

The db is running in a container environment, what is the log path for it? 

I also checked the standard output but see nothing.

> @mong0520 It should not be necessary to create this table. It is only used to temporarily save away privileges of existing tables while running the upgrade. Can you look in the log and see if you see any other errors that prevents creating this table in the upgrade script?

**Comment by mong0520** [comment]
Here is the logs around `ALTER EXTENSION timescaledb UPDATE;`

```
2023-05-16 09:35:47.152 UTC [30] FATAL:  terminating background worker "TimescaleDB Background Worker Scheduler" due to administrator command
2023-05-16 09:35:47.152 UTC [30] LOG: terminating TimescaleDB job scheduler due to administrator command
69+08:00
2023-05-16 09:35:47.169 UTC [1] LOG: background worker "TimescaleDB Background Worker Scheduler" (PID 30) exited with exit code 1
2023-05-16 09:35:52.986 UTC [82] STATEMENT: ALTER EXTENSION timescaledb UPDATE;
86+08:00
PL/pgSQL function public.grant_privilege_func() line 9 at EXECUTE
2023-05-16 09:35:52.986 UTC [82] CONTEXT: SQL statement "GRANT SELECT ON "_timescaledb_internal.saved_privs" TO public"
2023-05-16 09:35:52.986 UTC [82] ERROR: relation "_timescaledb_internal.saved_privs" does not exist
FROM pg_catalog.pg_extension e LEFT JOIN pg_catalog.pg_namespace n ON n.oid = e.extnamespace LEFT JOIN pg_catalog.pg_description c ON c.objoid = e.oid AND c.classoid = 'pg_catalog.pg_extension'::pg_catalog.regclass
2023-05-16 09:36:02.245 UTC [82] STATEMENT: SELECT e.extname AS "Name", e.extversion AS "Version", n.nspname AS "Schema", c.description AS "Description"
2023-05-16 09:36:02.245 UTC [82] DETAIL: The new version is "2.5.1", this session is using version "2.9.3". The session will be restarted.
2023-05-16 09:36:02.245 UTC [82] FATAL: "timescaledb" already loaded with a different version
```

**Comment by mong0520** [comment]
I'd like to close this issue since the root cause was found: a user defined trigger function that breaks the table creation on shcema `_timescaledb_internal`. After dropping that function, it works correctly.

**Comment by mkindahl** [comment]
@mong0520 Thanks for investigating the issue.
