### ISSUE TITLE
[Enhancement]: Emit a warning when realtime-on-realtime cagg is created

### ISSUE THREAD

**Issue by kgyrtkirk** [timescale/timescaledb#5690]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Continuous aggregate

### What does the enhancement do?

Creating realtime caggs over realtime caggs are possible; however they are not that efficient as planning time goes up by magnitudes in case of 3 level it could become 100s of seconds

Emitting some notice the user that the above happens might help users not get into such trouble that easily.

**Comment by fabriziomello** [comment]
@jnidzwetzki This issue can be closed because as you mentioned in 2.14.0 (not 2.13.0) we introduced planner improvements for realtime caggs and in 2.13.0 we made materialized-only by default when creating a cagg. So closing this issue!
