### ISSUE TITLE
[Bug]: Can't connect database after run VACUUM FULL

### ISSUE THREAD

**Issue by widhaprasa** [timescale/timescaledb#5693]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Access node

### What happened?

I can't connect to my database after run `VACUUM FULL` on my timescaledb run on docker using image `timescale/timescaledb:2.3.0-pg12` and mount volume to host on folder `/docker/platform/db/data-timescaledb/data`

The chronology was I tried to clear unused data from one table/hypertable and delete some retention policy but to regain disk space we need to call `VACUUM FULL`. The vacuum process took a long time and after it finished suddenly I was kicked from database session (I'm using psql) and when I tried to reconnect to my database, it resulted error: `FATAL:  could not open relation with OID 549`

<img width="751" alt="Screen Shot 2023-05-17 at 18 36 18" src="https://github.com/timescale/timescaledb/assets/3860967/0eaa22b8-dc6d-4c58-86a0-28bc9c7b6c72">

I assume, the vacuum command delete some record or index of timescaledb which resulted my database became corrupted.

I need to connect to my database again, because I don't want to lose nearly 200GB of data. Is my data still able to be recovered?

### TimescaleDB version affected

2.3.0

### PostgreSQL version used

12

### What operating system did you use?

Centos 7

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
data-timescaledb_1  | 2023-05-16 22:13:59.161 UTC [8830] LOCATION:  relation_open, relation.c:62
data-timescaledb_1  | 2023-05-16 22:14:09.169 UTC [8834] ERROR:  XX000: could not open relation with OID 549
data-timescaledb_1  | 2023-05-16 22:14:09.169 UTC [8834] LOCATION:  relation_open, relation.c:62
data-timescaledb_1  | 2023-05-16 22:14:19.165 UTC [8838] ERROR:  XX000: could not open relation with OID 549
data-timescaledb_1  | 2023-05-16 22:14:19.165 UTC [8838] LOCATION:  relation_open, relation.c:62
data-timescaledb_1  | 2023-05-16 22:14:29.166 UTC [8842] ERROR:  XX000: could not open relation with OID 549
```

### How can we reproduce the bug?

```bash
I don't know if I can reproduce this

But I did run `VACUUM FULL` after clearing data from table and delete some retention_policy
```

**Comment by shhnwz** [comment]
Hello @widhaprasa ,

Thanks for contacting Timescale!

Before moving forward we need some more information from your end.
1- Please share the complete log file.
2- When was the last backup taken?
3- Please share postgresql.conf file.

In the meantime:
Stop the postmaster and take a file system level copy of your database. Make a copy of all the files in the data directory (the one that contains the "base", "pg_wal" etc folders). Just to make sure to have backup of current filesystem state. 

Regds
shhnwz

**Comment by widhaprasa** [comment]
Hello @shhnwz, thanks for responding

1. Complete log file (from docker)
[log.txt](https://github.com/timescale/timescaledb/files/11514992/log.txt)

2. Unfortunately, I've never done it :(

3. The conf file
[posgresql.conf.txt](https://github.com/timescale/timescaledb/files/11515000/posgresql.conf.txt)

4. `select * from pg_class where oid = 549`
[pg_class.txt](https://github.com/timescale/timescaledb/files/11515038/pg_class.txt)

`Stop the postmaster ` -> I am just gonna stop the docker container, is it enough?
`Make copy of all the files in data directory` -> Okay, I need time to do this, because my VPS storage already full

Regards
Widhaprasa

**Comment by shhnwz** [comment]
> Hello @shhnwz, thanks for responding
> 
>     1. Complete log file (from docker)
>        [log.txt](https://github.com/timescale/timescaledb/files/11514992/log.txt)
> 
>     2. Unfortunately, I've never done it :(
> 
>     3. The conf file
>        [posgresql.conf.txt](https://github.com/timescale/timescaledb/files/11515000/posgresql.conf.txt)
> 
>     4. `select * from pg_class where oid = 549`
>        [pg_class.txt](https://github.com/timescale/timescaledb/files/11515038/pg_class.txt)
> 
> 
> `Stop the postmaster ` -> I am just gonna stop the docker container, is it enough? `Make copy of all the files in data directory` -> Okay, I need time to do this, because my VPS storage already full
> 
> Regards Widhaprasa

Hi @widhaprasa ,

Please share the complete log if possible. I need to backtrack the sequence of events to find something meaningful to speculate the corruption.

**Comment by widhaprasa** [comment]
@shhnwz I'm afraid I can't :( , because the log is only on docker container, when I stopped it, it automatically lose. 

That log above is from when I restarted the container.

**Comment by pdipesh02** [comment]
Hi @widhaprasa,

Thanks for the details. 

> `select * from pg_class where oid = 549`

It seems that this is related to index `pg_foreign_server_name_index` on `pg_foreign_server` table. Could you please check if a file with name `549` exists in `base\<database_oid>` directory?

Thanks,
Dipesh

**Comment by widhaprasa** [comment]
Hi @pdipesh02 

Thanks for the response. I'll try to find 549 directory on postgresql dir

in `base/`

<img width="470" alt="Screen Shot 2023-05-24 at 12 49 34" src="https://github.com/timescale/timescaledb/assets/3860967/e8470265-6382-4d69-bd86-92b0bf37af71">

in each of `base/` subdirectory

<img width="524" alt="Screen Shot 2023-05-24 at 12 50 34" src="https://github.com/timescale/timescaledb/assets/3860967/3fb427f3-3a2b-4cfa-9022-fdfdd914ccd4">

<img width="508" alt="Screen Shot 2023-05-24 at 12 50 52" src="https://github.com/timescale/timescaledb/assets/3860967/dbe37e06-38e3-4420-b497-4de681b5cf96">

<img width="502" alt="Screen Shot 2023-05-24 at 12 51 06" src="https://github.com/timescale/timescaledb/assets/3860967/810bec6c-2697-420d-b217-e3c69b5fe558">

<img width="475" alt="Screen Shot 2023-05-24 at 12 51 36" src="https://github.com/timescale/timescaledb/assets/3860967/40d8c8ce-0ee2-41bf-a480-eaf38229d0bf">

<img width="490" alt="Screen Shot 2023-05-24 at 12 52 04" src="https://github.com/timescale/timescaledb/assets/3860967/05b903ee-7a17-4714-b13c-bababa4f3ecf">

Regards
widhaprasa

**Comment by jnidzwetzki** [comment]
Hello @widhaprasa,

Thank you for providing all the information. It seems the file that contains the `pg_foreign_server_name_index` was deleted. Could you try to reindex the table `foreign_server_name` by running `reindex table pg_catalog.pg_foreign_server;`?  

If you cannot connect to the database with psql due to the missing index file, [please set](https://www.postgresql.org/docs/current/runtime-config-developer.html) `ignore_system_indexes` to `on` in your PostgreSQL config and restart the database server. This should allow you to connect to the database and recreate the index. Once the index is recreated, you can disable the `ignore_system_indexes` setting again.

**Comment by widhaprasa** [comment]
Thanks for answer @jnidzwetzki 

After I add ignore_system_indexes on postgresql.conf, I am now able to connect my database

<img width="633" alt="Screen Shot 2023-06-10 at 08 57 07" src="https://github.com/timescale/timescaledb/assets/3860967/274f8a30-8a16-4d60-b7e2-48e83e4705fd">

Then I execute reindex command you provided

After that I remove the ignore index and run the postgres once again and try to connect the db, it still give me an error, but this time is different oid (2696)

<img width="410" alt="Screen Shot 2023-06-10 at 09 00 17" src="https://github.com/timescale/timescaledb/assets/3860967/579a956c-cf05-4b35-a281-5beb72947ed3">

Maybe I need to reindex every single oid?

Regards

Widhaprasa

**Comment by jnidzwetzki** [comment]
Hello @widhaprasa,

I'm glad to hear that you can now connect to your database. And yes, your assumption is correct. If other errors regarding indexes occur, you also have to perform a reindex operation for them. As mentioned by @pdipesh02, you can execute the following SQL command to get the name of the index that needs to be rebuild:

```sql
SELECT * FROM pg_class WHERE oid = XXX;
```

OID 2696 usually belongs to the system index `pg_statistic_relid_att_inh_index`, which can be reindexed by executing:

```sql
REINDEX INDEX pg_statistic_relid_att_inh_index;
```
