### ISSUE TITLE
[Bug]: Crash in chunk_scan_find

### ISSUE THREAD

**Issue by kgyrtkirk** [timescale/timescaledb#5697]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

crash during the execution of `bgw_db_scheduler`
https://github.com/timescale/timescaledb/actions/runs/5004842080/jobs/8967969652#step:11:640

* assertion fires [here](https://github.com/timescale/timescaledb/blob/2.11.x/src/chunk.c#L2453)
* which could happen if `num_found==1` ; and the chunk collected by the `chunk_scan_internal` function has an invalid type.
* `chunk_scan_internal` method seem to be scanning an internal table(s) - and returns a `Chunk*` in the ctx
* for this returned `Chunk` the type is invalid...

[gdb backtrace](https://gist.github.com/kgyrtkirk/3bc7d302705e4d4e7b11d484c7537915)

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

12

### What operating system did you use?

ubuntu

### What installation method did you use?

Source

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
I was not yet able to replicate locally
```

**Comment by kgyrtkirk** [comment]
it did happened a few [days ago](https://github.com/timescale/timescaledb/actions/runs/4952061833/jobs/8857891184#step:11:640) as well - during `bgw_db_scheduler_fixed`

**Comment by lkshminarayanan** [comment]
Fixed in https://github.com/timescale/timescaledb/pull/5701
