### ISSUE TITLE
[Bug]: Unable to run timescaledb on mac pg15 with error `Symbol not found: _find_em_expr_for_rel`

### ISSUE THREAD

**Issue by tonyalaribe** [timescale/timescaledb#5710]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Build system

### What happened?

I installed timescale via brew with no errors, following the instructions at: https://docs.timescale.com/self-hosted/latest/install/installation-macos/ 

but when I create the extension
```
CREATE EXTENSION IF NOT EXISTS timescaledb;
```
I get the following error:

```sh
ERROR:  could not load library "/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.11.0.so": dlopen(/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.11.0.so, 0x000A): Symbol not found: _find_em_expr_for_rel
  Referenced from: <549C5791-0C09-3F05-8CCE-7D1C491E78BC> /opt/homebrew/Cellar/postgresql@15/15.3/lib/postgresql/timescaledb-2.11.0.so
  Expected in:     <BF2E43B3-C986-3681-A4F4-6A23A00A513E> /opt/homebrew/Cellar/postgresql@15/15.3/bin/postgres 

SQL state: 58P01
```

### TimescaleDB version affected

2.11

### PostgreSQL version used

15

### What operating system did you use?

Mac OS arm64 (apple silicon)

### What installation method did you use?

Homebrew

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
ERROR:  could not load library "/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.11.0.so": dlopen(/opt/homebrew/opt/postgresql@15/lib/postgresql/timescaledb-2.11.0.so, 0x000A): Symbol not found: _find_em_expr_for_rel
  Referenced from: <549C5791-0C09-3F05-8CCE-7D1C491E78BC> /opt/homebrew/Cellar/postgresql@15/15.3/lib/postgresql/timescaledb-2.11.0.so
  Expected in:     <BF2E43B3-C986-3681-A4F4-6A23A00A513E> /opt/homebrew/Cellar/postgresql@15/15.3/bin/postgres 

SQL state: 58P01
```

### How can we reproduce the bug?

```bash
By following the following instructions on apple silicon: https://docs.timescale.com/self-hosted/latest/install/installation-macos/
```

**Comment by pdipesh02** [comment]
Hi @tonyalaribe, Thanks for contacting Timescale!

We need some additional information from your end before moving forward.
1. Have you separately installed Postgres before installing `timescaledb` version 2.11?
2. Have you run all the installation steps upto `./timescaledb_move.sh` mentioned at [1].

[1] -> https://docs.timescale.com/self-hosted/latest/install/installation-macos/

Thanks,
Dipesh

**Comment by tonyalaribe** [comment]
HI @pdipesh02 , 
1. I had postgres 14 installed but uninstalled it and installed postgres 15 before installing timescaledb 
2. I ran all the steps including ./timescaledb_move.sh

**Comment by pdipesh02** [comment]
Hi @tonyalaribe,

> I had postgres 14 installed but uninstalled it and installed postgres 15 before installing timescaledb
It could be related to pre-installed version of Postgresql. I cannot reproduce it at my end.

Could you please try the following steps?

1. Uninstall `timescaledb`
2. Uninstall `Postgresql`
3. Install `timescaledb` using the steps mentioned in the documents. It will automatically install `Postgresql` as part of installing dependencies.  

Thanks,
Dipesh

**Comment by jcoby** [comment]
I have the same issue. It seems to be because the homebrew tap requiring `postgresql@14` for build but timescale is configuring itself for `postgresql@15`.

see: https://github.com/timescale/homebrew-tap/blob/main/timescaledb.rb#L13

Installing the homebrew-installed extension in `postgresql@14` is successful if the `timescaledb_move.sh` file is modified to install in `postgresql@14`.

Dependencies excerpt:
```
$ brew install timescaledb 
==> Fetching dependencies for timescale/tap/timescaledb: cmake, postgresql@14 and timescale/tap/timescaledb-tools
```

.so files are in `postgresql@14`:

```
$ find /opt/homebrew/Cellar/timescaledb/2.11.2/lib -name "timescaledb*.so"
/opt/homebrew/Cellar/timescaledb/2.11.2/lib/timescaledb/postgresql@14/timescaledb-tsl-2.11.2.so
/opt/homebrew/Cellar/timescaledb/2.11.2/lib/timescaledb/postgresql@14/timescaledb-2.11.2.so
/opt/homebrew/Cellar/timescaledb/2.11.2/lib/timescaledb/postgresql@14/timescaledb.so
```

`timescaledb_move.sh` installs them into `postgresql@15`:

```
$ cat timescaledb_move.sh
#!/bin/bash
echo 'Moving files into place...'
/usr/bin/install -c -m 755 $(find /opt/homebrew/Cellar/timescaledb/2.11.2/lib -name timescaledb*.so) /opt/homebrew/opt/postgresql@15/lib/postgresql/
/usr/bin/install -c -m 644 /opt/homebrew/Cellar/timescaledb/2.11.2/share/timescaledb/* /opt/homebrew/opt/postgresql@15/share/postgresql@15/extension/
echo 'Success.'
