### ISSUE TITLE
Failing to install Timescale extension

### ISSUE THREAD

**Issue by Ravisankar97** [timescale/timescaledb#5715]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

I have installed postgres in rancher cluster through bitnami postgres chart.
Now I have executed below query to add timescale extension.
CREATE EXTENSION IF NOT EXISTS timescaledb;

I received below error. How to fix it?
ERROR: extension “timescaledb” is not available
DETAIL: Could not open extension control file “/opt/bitnami/postgresql/share/extension/timescaledb.control”: No such file or directory.
HINT: The extension must first be installed on the system where PostgreSQL is running.

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

15.2.0

### What operating system did you use?

Ubuntu

### What installation method did you use?

Other

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
NA
```

### How can we reproduce the bug?

```bash
NA
```

**Comment by sotirissl** [comment]
Hi @Ravisankar97.
Did you added timescaledb in the postgresql.conf before you execute
CREATE EXTENSION IF NOT EXISTS timescaledb;

Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

Please also check Timescale Documentation
https://docs.timescale.com/self-hosted/latest/install/installation-source/

**Comment by abrownsword** [comment]
I am experiencing the same error, and yes, I have set the shared_preload_libraries in the .conf file.  I tried multiple times, restarting the postgresql database systemd service each time.  This has worked fine in the past on earlier OS version, and with Postgresql 14 + timescaledb 2.0.6.

My system is armbian (Ubuntu on a small board Aarch64 host) 22.x w/ kernel 6.1.x.  I have tried both built from scratch and install from package server.  I am using postgres-15 and timescaledb 2.11.1.

**Comment by mkindahl** [comment]
@Ravisankar97 It's hard to understand what is wrong without having access to the system, but the first step is probably to see if the file `/opt/bitnami/postgresql/share/extension/timescaledb.control` mentioned in the error message actually exists.

**Comment by mkindahl** [comment]
@abrownsword There are many different reasons why starting the server might fail. Knowing the error message you get is a good start, with detailed information if you have that.

**Comment by mkindahl** [comment]
@abrownsword If you're installing from source, you will see where the files are installed. I use multiple versions of PostgreSQL on my system to be able to debug, and occasionally I have the wrong path and for that reason am installing the extension in the wrong location.

**Comment by duven87** [comment]
I have the same Problem:

```
postgres@zabbix-test:~$ cat /etc/postgresql/13/main/postgresql.conf | grep scale
shared_preload_libraries = 'timescaledb'	# (change requires restart)
timescaledb.max_background_workers = 16
timescaledb.last_tuned = '2024-05-22T18:30:25+02:00'
timescaledb.last_tuned_version = '0.15.0'
```

`postgres@zabbix-test:~$ systemctl restart postgresql@13-main.service 
`

```
postgres=# ALTER EXTENSION timescaledb UPDATE TO '2.14.9';
ERROR:  extension "timescaledb" does not exist
```

```
2980376:20240529:155129.661 Unsupported DB! timescaledb version 21500 is newer than maximum allowed 21499
2980376:20240529:155129.661 Recommended version should not be higher than TimescaleDB Community Edition 2.14.
```
