### ISSUE TITLE
[Bug]: approximate_row_count() on compressed hypertable

### ISSUE THREAD

**Issue by melicheradam** [timescale/timescaledb#5724]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Other

### What happened?

I have a hypertable with ~15 million records. When the table is not compressed, the `approximate_row_count()` function gives correct result of ~15mil. When I compress the table (53 out of 54 chunks compressed), it gives result over 300 million, which is very off real result.

If this behavior is intended, it would be good to mention it in the documentation, that you should not use this function if you have compression enabled.

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

15

### What operating system did you use?

Docker Image on MacOS 13.4

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
DROP TABLE test;

CREATE TABLE test(time TIMESTAMPTZ, device INT, temp float8);
SELECT create_hypertable('test', 'time', chunk_time_interval => INTERVAL '2 months');

INSERT INTO test SELECT t, (abs(timestamp_hash(t::timestamp)) % 10) + 1, 0.10 FROM generate_series('2013-03-02 1:00'::TIMESTAMPTZ, '2023-03-08 1:00', '1 minute') t;

ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'time');

SELECT add_compression_policy('test', INTERVAL '60 days');

SELECT approximate_row_count('test');

ANALYZE test;

SELECT approximate_row_count('test');

SELECT count(*) FROM test;

```

**Comment by sotirissl** [comment]
Hi @melicheradam.

Thank you for reporting this.

Can you please run ANALYZE your_hypertable and check again ?

Can you also provide some more information 
about how you created the compressed hypertable ?
It would be very helpful for us.

**Comment by melicheradam** [comment]
Hello @sotirissl ,

I did run the ANALYZE command multiple times, yet the issue persists.

Table creation:
`SELECT create_hypertable('table_name', 'timestamp', chunk_time_interval => INTERVAL '15 days');`

Compression:
`ALTER TABLE timeseries_telemetry SET (timescaledb.compress, timescaledb.compress_segmentby = 'xxx_id');`

Compression policy:
`SELECT add_compression_policy('table_name', INTERVAL '60 days')`

I can provide more information if needed, just tell me what you need :) .Many thanks

`COUNT(*)` : 16 892 105
`approximate_row_count('table_name')` : 346 028 245

`hypertable_compression_stats('table_name')` :
"total_chunks" 54
"number_compressed_chunks" 53
"before_compression_table_bytes" 955826176
"before_compression_index_bytes" 986144768
"before_compression_toast_bytes" 0
"before_compression_total_bytes" 1941970944
"after_compression_table_bytes"	331620352
"after_compression_index_bytes" 15138816
"after_compression_toast_bytes"	16343040
"after_compression_total_bytes"	363102208
"node_name" null

**Comment by pdipesh02** [comment]
Hi @melicheradam,

Thanks for your response. Based on the steps mentioned I have created a SQL script (updated in repro steps) and found that the issue is consistently reproducible with the below steps:

```
tsdb=# DROP TABLE test;
DROP TABLE
tsdb=# CREATE TABLE test(time TIMESTAMPTZ, device INT, temp float8);
CREATE TABLE
tsdb=# SELECT create_hypertable('test', 'time', chunk_time_interval => INTERVAL '2 months');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
 create_hypertable 
-------------------
 (6,public,test,t)
(1 row)

tsdb=# INSERT INTO test SELECT t, (abs(timestamp_hash(t::timestamp)) % 10) + 1, 0.10 FROM generate_series('2013-03-02 1:00'::TIMESTAMPTZ, '2023-03-08 1:00', '1 minute') t;
INSERT 0 5267521
tsdb=# ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'time');
ALTER TABLE
tsdb=# SELECT add_compression_policy('test', INTERVAL '60 days');
 add_compression_policy 
------------------------
                   1002
(1 row)

tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
             798030000
(1 row)

tsdb=# ANALYZE test;
ANALYZE
tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
            4255043491
(1 row)

tsdb=# SELECT count(*) FROM test;
  count  
---------
 5267521
(1 row)

tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
            5267521000
(1 row)
```

Thanks for reporting the issue.

Thanks,
Dipesh

**Comment by pdipesh02** [comment]
In this case `time` column is used as segment by column and the values in this column are unique. The number of tuples in compressed hypertable and original hypertable are same due to the unique values of segment by column. The calculation of approximate row count on compressed hypertable is based on number of `reltuples` value from `pg_class` multiplied by max-compressed-row-count (a constant). Since the effective number of rows in compressed table are same as original one and when it is multiplied by max-compressed-row-count  this leads to a very high value for approximate row count.

However, if we use `device_id` as a segment-by column which has non-unique values then the approximate calculation does not exceed to an arbitrary high value.

  ```
tsdb=# CREATE TABLE test(time TIMESTAMPTZ, device INT, temp float8);
CREATE TABLE
tsdb=# SELECT create_hypertable('test', 'time', chunk_time_interval => INTERVAL '2 months');
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values.
 create_hypertable 
-------------------
 (2,public,test,t)
(1 row)

tsdb=# INSERT INTO test SELECT t, (abs(timestamp_hash(t::timestamp)) % 10) + 1, 0.10 FROM generate_series('2013-03-02 1:00'::TIMESTAMPTZ, '2023-03-08 1:00', '1 minute') t;
INSERT 0 5267521
tsdb=# ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'device');
ALTER TABLE
tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
               5267521
(1 row)

tsdb=# ANALYZE test;
ANALYZE
tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
               5267521
(1 row)

tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
               5267521
(1 row)

tsdb=# SELECT approximate_row_count('test');
 approximate_row_count 
-----------------------
               5267521
(1 row)
```

**Comment by melicheradam** [comment]
Hi @pdipesh02 ,

the example provided in there is incorrect, if you check my comment i have put 
`ALTER TABLE table_name SET (timescaledb.compress, timescaledb.compress_segmentby = 'xxx_id');` in there. But I think the issue does not happen anymore, so we can close this and if I get some more info I will reopen the issue :) thanks for the effort.
