### ISSUE TITLE
MERGE on distributed hypertable report different error on windows.

### ISSUE THREAD

**Issue by sb230132** [timescale/timescaledb#5725]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Distributed hypertable

### What happened?

MERGE command on distributed hypertables is not supported. However the error reported on windows vs linux is different because of which test dist_ref_table_join-15 fails on windows.

Error reported on linux:
ERROR:  cannot execute MERGE on relation "_dist_hyper_1_1_chunk"
DETAIL:  This operation is not supported for foreign tables.

Error reported on windows:
ERROR:  unexpected operation: 5(CMD_MERGE)

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

15.2

### What operating system did you use?

Windows

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Uncomment below test to tsl/test/sql/dist_ref_table_join.sql.in and run the test on windows and linux

-------
-- MERGE is supported in PG >= 15. Currently, it is not supported in TimescaleDB
-- on distributed hypertables. Perform a MERGE here to check if the join pushdown
-- can handle the MERGE command properly. ON_ERROR_STOP is disabled for this test.
-- Older PostgreSQL versions report an error because MERGE is not supported. This
-- will be ignored due to the setting.
-------
\set ON_ERROR_STOP 0
MERGE INTO metric as target_0
USING metric as input_0
    inner join (select id from metric_name as input_1) as subq_0
      ON (TRUE)
ON target_0.id = input_0.id
WHEN MATCHED
   THEN DO NOTHING
WHEN NOT MATCHED
   THEN DO NOTHING;
\set ON_ERROR_STOP 1
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
