### ISSUE TITLE
[Bug]: official .deb incompatible with the latest Debian release 12/bookworm

### ISSUE THREAD

**Issue by nodakai** [timescale/timescaledb#5728]
### What type of bug is this?

Other

### What subsystems and features are affected?

Packaging

### What happened?

https://wiki.debian.org/DebianBookworm will be released in June. It has removed openssl 1.1 in favor of openssl 3, there's no official way to install openssl 1.1 on a Debian bookworm machine, when the official .deb depends on it.

CMake build of Git HEAD or the 2.11 tag just worked fine on a bookworm machine. So the source code is compatible with OpenSSL 3, it's just a matter of packaging

### TimescaleDB version affected

2.11

### PostgreSQL version used

15

### What operating system did you use?

Debian bookworm

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

### Relevant log output and stack trace

```bash
% sudo apt install -y timescaledb-2-postgresql-15 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 timescaledb-2-postgresql-15 : Depends: libssl1.1 (>= 1.1.0) but it is not installable
                               Recommends: timescaledb-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
% apt depends timescaledb-2-postgresql-15 
timescaledb-2-postgresql-15
  Depends: timescaledb-2-loader-postgresql-15 (>= 2.11.0~)
  Depends: postgresql-15 (>= 15.1)
  Depends: libc6 (>= 2.17)
  Depends: libpq5 (>= 9.2~beta3)
  Depends: <libssl1.1> (>= 1.1.0)
  Recommends: timescaledb-tools
```

The angle brackets `<libssl1.1>` (probably) means apt couldn't find it

```
% cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```


### How can we reproduce the bug?

```bash
Launch a bookworm machine (`docker run -ti debian:bookworm /bin/bash` might suffice?)

...follow https://docs.timescale.com/self-hosted/latest/install/installation-linux/ ...
```

**Comment by nodakai** [comment]
Hi team, Debian 12/bookworm with OpenSSL 3 was released 2 weeks ago https://www.debian.org/releases/bookworm/

**Comment by sunny1025g** [comment]
Hi team, please add official deb for Debian 12/bookworm
`root@debian12:~# apt update

E: The repository 'https://packagecloud.io/timescale/timescaledb/debian bookworm Release' does not have a Release file.`

**Comment by juantxorena** [comment]
Debian 12/bookworm was released 3 weeks ago, and it has been with release candidates since April. A new version of timescale in the repos was released a couple of hours ago, and still no bookworm package.

**Comment by Hazpartame** [comment]
Hello, 

This issue impact me. Is a workaround exists or a release date ?

Thank you.

**Comment by juantxorena** [comment]
After almost 2 months of the stable debian release, and a minor version (12.1), not only is this bug still open, but there is absolutely ignored. Not a single feedback or comment by the team. Honestly, that doesn't look very good.

**Comment by svenklemm** [comment]
Debian 12 packages are available now

**Comment by trombonax** [comment]
Hello, 

Do you plan build arm64 packages ? Currently I see only amd64 debian 12 packages.

Thank you.

**Comment by nodakai** [comment]
@svenklemm Just saw your commit https://github.com/timescale/timescaledb/commit/07762ea4cedefc88497f0d1f8712d1515cdc5b6e which enabled amd64 builds for Debian 12/bookworm.

To enable arm64 builds, maybe it just requires a simple update to https://github.com/timescale/timescaledb/blob/07762ea4cedefc88497f0d1f8712d1515cdc5b6e/.github/workflows/apt-arm-packages.yaml#L21 ?

**Comment by trombonax** [comment]
Hello,

If you can publish deb build rules, I will build package for my architecture myself

Thank you.
