### ISSUE TITLE
[Bug]: Monthly continuous aggregate contains two entries instead of one

### ISSUE THREAD

**Issue by lukaskirner** [timescale/timescaledb#5734]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

By creating a stacked continuous aggregate (hourly --> daily --> monthly) the monthly aggregate contains two instead of one entry. By executing the `SELECT` of the continuous aggregate without the view, it only returns one entry on the same data set. This will result into some Problems.

You can verify this on your own by executing the SQL statements from the `How can we reproduce the bug?` section.

### TimescaleDB version affected

2.10.3

### PostgreSQL version used

15.2

### What operating system did you use?

Timescale Cloud

### What installation method did you use?

Other

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```SQL
CREATE TABLE test (
	timestamp TIMESTAMPTZ NOT NULL,
	device_id TEXT NOT NULL,
	value INT NOT NULL,
	
	CONSTRAINT uk_test_timestamp_device_id UNIQUE (timestamp, device_id)
);

SELECT create_hypertable('test', 'timestamp');

INSERT INTO test (timestamp, device_id, value) VALUES 
	('2023-05-01 00:00:00+00', 'sensor0', 1),
	('2023-05-15 00:00:00+00', 'sensor0', 2),
	('2023-05-31 00:00:00+00', 'sensor0', 10);


CREATE MATERIALIZED VIEW IF NOT EXISTS agg_test_hourly WITH (timescaledb.continuous) AS 
    SELECT 
        time_bucket('1 hour'::interval, timestamp) AS hour_timestamp,
        device_id,
        counter_agg(timestamp, value) AS counter_value
    FROM test
    GROUP BY hour_timestamp, device_id
WITH DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS agg_test_daily WITH (timescaledb.continuous) AS 
    SELECT 
        time_bucket('1 day'::interval, hour_timestamp) AS day_timestamp,
        device_id,
        rollup(counter_value) AS counter_value
    FROM agg_test_hourly
    GROUP BY day_timestamp, device_id
WITH DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS agg_test_monthly WITH (timescaledb.continuous) AS 
    SELECT 
        time_bucket('1 month'::interval, day_timestamp) AS month_timestamp,
        device_id,
        rollup(counter_value) AS counter_value
    FROM agg_test_daily
    GROUP BY month_timestamp, device_id
WITH DATA;

SELECT count(*) FROM agg_test_monthly;
-- Will return two rows instead of one
```
```

**Comment by sotirissl** [comment]
Hi @lukaskirner
Thanks for the detailed reproduction steps, I was able to reproduce this.

The result was
psql:test_case.sql:13: WARNING:  column type "character varying" used for "device_id" does not follow best practices
HINT:  Use datatype TEXT instead.
psql:test_case.sql:28: NOTICE:  refreshing continuous aggregate "agg_test_hourly"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
psql:test_case.sql:37: NOTICE:  refreshing continuous aggregate "agg_test_daily"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
psql:test_case.sql:46: NOTICE:  refreshing continuous aggregate "agg_test_monthly"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
psql:test_case.sql:56: **_ERROR:  out of order points: points must be submitted in time-order_**

This error is appeared in timescaledb-toolkit
https://github.com/timescale/timescaledb-toolkit/blob/96c29e085fe743ed8f6b494ff0ce6d8a7251329b/crates/counter-agg/src/lib.rs#L304

Thanks for reporting the issue.

**Comment by lukaskirner** [comment]
@sotirissl Correct the last one is related to the Toolkit, but this problem only appears due to the two entries for the monthly aggregation. This is a continuous aggregate bug not a Toolkit bug.

**Comment by jerryxwu** [comment]
@lukaskirner My understanding is that you are trying to use the Toolkit functions to work around the problem of having two rows from `agg_test_monthly` . The reason that you are getting the error message is that the `rollup` function works for disjoint sets (based on the timestamp column). The two rows that you have in `agg_test_monthly` has an identical timestamp (2023-05-01 00:00:00+00). The rollup function does not know how to combine those two rows. Hopefully that makes sense.

**Comment by lukaskirner** [comment]
@jerryxwu Actually no. Like the Bug Title mentions, the continuous aggregate contains **two** instead of **one** entry. To prevent further misinterpretation, I removed the `counter_agg` from the description.

**Comment by cchenggit** [comment]
Hi, is there any plan to merge this fix into other lower versions release? 
two entries also happened when I alter materialized only from false to true, and set back false, then monthly shows two time bucket which is unexpected.
