### ISSUE TITLE
Crash on pg10.4 on win7x64 on create table inherits|like when one column is text

### ISSUE THREAD

**Issue by pdanpdan** [timescale/timescaledb#574]
Tested and not working on:
- Timescaledb 0.9.2 and 0.10.0
- pg 10.4 (BigSQL build and EnterpriseDB build)
- Windows 7 x64

Tested and working on:
- Timescaledb 0.10.0
- pg 10.4
- Linux

```sql
CREATE DATABASE test_create_inherit;
\c test_create_inherit
DROP TABLE IF EXISTS "ok2";
DROP TABLE IF EXISTS "ok";
CREATE TABLE "ok" ("idef" text default null);
CREATE TABLE "ok2" () INHERITS ("ok");

CREATE EXTENSION "timescaledb";
DROP TABLE IF EXISTS "bad2";
DROP TABLE IF EXISTS "bad";
CREATE TABLE "bad" ("idef" text default null);
CREATE TABLE "bad2" () INHERITS ("bad");
```

This throws:
```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

with log:
```
2018-06-28 09:04:44 EEST [20632]: [12-1] user=,db=,app=,client= LOG:  server process (PID 22388) was terminated by exception 0xC0000005
2018-06-28 09:04:44 EEST [20632]: [13-1] user=,db=,app=,client= DETAIL:  Failed process was running: CREATE TABLE "bad2" () INHERITS ("bad");
2018-06-28 09:04:44 EEST [20632]: [14-1] user=,db=,app=,client= HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2018-06-28 09:04:44 EEST [20632]: [15-1] user=,db=,app=,client= LOG:  terminating any other active server processes
```

**Comment by RobAtticus** [comment]
Was able to reproduce this on 10.4 but not on an earlier version of PG 10 (either 10 or 10.1). Will investigate, thanks!

**Comment by RobAtticus** [comment]
Hi @pdanpdan , thanks again for the report. The problem seems to stem from me building the Windows binaries against 10.1 rather than a post-10.2 version. There was a breaking change in PG in 10.2 that could manifest itself in strange crashes. I have updated the Windows builds for PG10 to be built against 10.4 so this problem should be resolved if you try 0.10.0 again. Please let me know if it is still not resolved.

**Comment by pdanpdan** [comment]
Sure, I'll test it first thing in the morning and report success. Thank you

**Comment by pdanpdan** [comment]
Working as expected now, thank you.
