### ISSUE TITLE
We have deleted all the PVC's of the timescale DB we are looking to get some solution which I can adopt.

### ISSUE THREAD

**Issue by sasikanth5519** [timescale/timescaledb#5746]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Configuration, Data node, Multi-node, Restore

### What happened?

It is observed that when we have deleted the PVC's of time scale DB in Kubernetes cluster. It is not recovering and POD is in semi running state error cannot find the master.

### TimescaleDB version affected

postgres (PostgreSQL) 11.11 (Debian 11.11-1.pgdg100+1)

### PostgreSQL version used

postgres (PostgreSQL) 11.11 (Debian 11.11-1.pgdg100+1)

### What operating system did you use?

RedHat 7.9

### What installation method did you use?

Docker, Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
timescaledb 2023-06-06 01:25:26,716 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1         ││ timescaledb 2023-06-06 01:25:26,716 ERROR: failed to bootstrap (without leader)                                                                                      ││ timescaledb 2023-06-06 01:25:37,111 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1         ││ timescaledb 2023-06-06 01:25:37,112 ERROR: failed to bootstrap (without leader)                                                                                      ││ timescaledb 2023-06-06 01:25:47,111 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1         ││ timescaledb 2023-06-06 01:25:47,111 ERROR: failed to bootstrap (without leader)                                                                                      ││ timescaledb 2023-06-06 01:25:57,111 ERROR: Error creating replica using method pgbackrest: /etc/timescaledb/scripts/pgbackrest_restore.sh exited with code=1         ││ timescaledb 2023-06-06 01:25:57,112 ERROR: failed to bootstrap (without leader)
```

### How can we reproduce the bug?

```bash
Step1: Scale down the time scale pods 
Step2: Remove all related PVC and there it will be.
```

**Comment by sasikanth5519** [comment]
Hi jnidzwetzki,
Thanks for asking the details
Image: Linux phziot-timescaledb-0 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 GNU/Linux
Setup: Three node cluster

**Comment by jnidzwetzki** [comment]
Hello @sasikanth5519,

Thanks for getting back to us. The `Linux phziot-timescaledb-0 3.10.0-1160.el7.x86_64` string looks like the kernel (image) you are using. Which container image (e.g., `timescale/timescaledb-ha:pg14.8-ts2.11.0-all`) are you using in your Kubernetes cluster? 

Regarding your three-node cluster, is it based on a TimescaleDB [multi-node setup](https://docs.timescale.com/self-hosted/latest/multinode-timescaledb/) or is it based on PostgreSQL replication? 

You mentioned that you deleted Persistent Volumes Claims (PVC) before the problem happened. Did you delete the PVCs for all pods in your cluster are there also pods that could keep their persistent volumes?

**Comment by sasikanth5519** [comment]
Hi Jnidzwetzki,
How are you, Thanks for the responce

Here are the details 
Image : timescale/timescaledb-ha:pg11-ts2.0-latest
Cluster: Kubernetes ( One master and three slave nodes)
Regarding PVC's yes, we have deleted unfortunately. Thats actually the issue

Thanks,
Sasikanth

**Comment by sasikanth5519** [comment]
Hello Jan,

This is the first time we have encountered this issue. It was also created by us as a failover case. Previously one or two are down in the actual case. So we want to know how reliable in this type of situations.
Behavior of cluster: Data base is down and is not accepting connections.

**Comment by jnidzwetzki** [comment]
Hello @sasikanth5519,

Thanks for explaining this in more detail. It looks like this issue is more about a configuration advice for a HA solution using the `timescale/timescaledb-ha` container images than an actual software bug in TimescaleDB. I recommend discussing this in the [community Slack or forum](https://www.timescale.com/community/), which are better platforms for this type of question and you will get more help there.

**Comment by svenklemm** [comment]
This issue seems to be related to the multinode code which has been removed from recent timescaledb versions.
