### ISSUE TITLE
[Bug]: CAGGs queries fails after migration to Cloud because watermark is not restored and can't be set

### ISSUE THREAD

**Issue by alejandrodnm** [timescale/timescaledb#5763]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate, Restore

### What happened?

When restoring a DB to Cloud that has a CAGGs defined I get the following error:

```
tsdbadmin@:tsdb> select * from team1.sample_cagg;
watermark not defined for continuous aggregate: 5
```

I saw from https://github.com/timescale/timescaledb/issues/5743#issuecomment-1574208507 that:

> Since 2.11.0 we’re not computing the watermark anymore at the query time (PR #5261) and instead storing it into a catalog table named _timescaledb_catalog.continuous_aggs_watermark.

Since this is not a configuration table, it’s not exported, and I’m left with no watermark after the migration:

```
tsdbadmin@:tsdb> select * from _timescaledb_catalog.continuous_aggs_watermark;
╒═══════════════════╤═══════════╕
│ mat_hypertable_id │ watermark │
╞═══════════════════╪═══════════╡
╘═══════════════════╧═══════════╛
```

I tried the fix, but got permission error on the table:

```
tsdbadmin@:tsdb> UPDATE
   _timescaledb_catalog.continuous_aggs_watermark
 SET
   watermark = _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
 WHERE
   watermark IS DISTINCT FROM _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
   AND mat_hypertable_id = 5;
permission denied for table continuous_aggs_watermark
```

The refresh policy seems to be running fine:

```
-[ RECORD 1 ]-------------------------
hypertable_schema      | _timescaledb_internal
hypertable_name        | _materialized_hypertable_5
job_id                 | 1002
last_run_started_at    | 2023-06-06 13:32:06.109373+00
last_successful_finish | 2023-06-06 13:32:06.117963+00
last_run_status        | Success
job_status             | Scheduled
last_run_duration      | 0:00:00.008590
next_start             | 2023-06-06 13:32:36.117963+00
total_runs             | 1
total_successes        | 1
total_failures         | 0
job_id                 | 1002
application_name       | Refresh Continuous Aggregate Policy [1002]
schedule_interval      | 0:00:30
max_runtime            | 0:00:00
max_retries            | -1
retry_period           | 0:00:30
proc_schema            | _timescaledb_internal
proc_name              | policy_refresh_continuous_aggregate
owner                  | tsdbadmin
scheduled              | True
fixed_schedule         | False
config                 | {"end_offset": "00:01:00", "start_offset": "3 days", "mat_hypertable_id": 5}
next_start             | 2023-06-06 13:32:36.117963+00
initial_start          | <null>
hypertable_schema      | _timescaledb_internal
hypertable_name        | _materialized_hypertable_5
check_schema           | _timescaledb_internal
check_name             | policy_refresh_continuous_aggregate_check```
```

I’m getting this on the logs:

```
2023-06-06 13:32:36 UTC [1073]: LOG: refreshing continuous aggregate "sample_cagg" in window [ 2023-06-04 00:00:00+00, 2023-06-06 00:00:00+00 ]
```

The issue seems to affect only querying the CAGGs.

Maybe an option could be to update the watermark for all the mat_hypertable’s that don’t have a watermark set when calling `timescaledb_post_restore`. That solves the permission error because it’s security definer.

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

15.3

### What operating system did you use?

Cloud

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
tsdbadmin@:tsdb> select * from team1.sample_cagg;
watermark not defined for continuous aggregate: 5

tsdbadmin@j0dxeb1l5b:tsdb> select * from _timescaledb_catalog.continuous_aggs_watermark;
╒═══════════════════╤═══════════╕
│ mat_hypertable_id │ watermark │
╞═══════════════════╪═══════════╡
╘═══════════════════╧═══════════╛

tsdbadmin@:tsdb> UPDATE
   _timescaledb_catalog.continuous_aggs_watermark
 SET
   watermark = _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
 WHERE
   watermark IS DISTINCT FROM _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
   AND mat_hypertable_id = 5;
permission denied for table continuous_aggs_watermark
```

### How can we reproduce the bug?

- Create the following in the source db:

```sql
CREATE table caggs_hypertable (
    time timestamptz not null,
    key int not null,
    value float
);

SELECT create_hypertable('caggs_hypertable', 'time', chunk_time_interval => INTERVAL '1 day');

INSERT INTO caggs_hypertable SELECT time, key, value*100 FROM generate_series('2023-05-20', now(), INTERVAL '8 hours') AS time, generate_series(1, 3, 1) AS key, random() AS value;

CREATE MATERIALIZED VIEW sample_cagg
  WITH (timescaledb.continuous) AS
  SELECT
    time_bucket('1 day', "time") AS day,
    key,
    max(value) AS high
  FROM caggs_hypertable
  GROUP BY day, key;
```

- Create a dump with `pg_dump -d $SOURCE_DB --no-owner -f dump.sql`

- In the cloud service run `select timescaledb_pre_restore()`.

- Import the dump with `psql -d $TARGET_DB < dump.sql`.

- In the cloud service try to query the caggs:

```sql
tsdbadmin@:tsdb> select * from team1.sample_cagg;
watermark not defined for continuous aggregate: 5
```

- In the cloud service try to fix the watermark:

```sql
tsdbadmin@j0dxeb1l5b:tsdb> select * from _timescaledb_catalog.continuous_aggs_watermark;
╒═══════════════════╤═══════════╕
│ mat_hypertable_id │ watermark │
╞═══════════════════╪═══════════╡
╘═══════════════════╧═══════════╛

tsdbadmin@:tsdb> UPDATE
   _timescaledb_catalog.continuous_aggs_watermark
 SET
   watermark = _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
 WHERE
   watermark IS DISTINCT FROM _timescaledb_internal.cagg_watermark_materialized (mat_hypertable_id)
   AND mat_hypertable_id = 5;
permission denied for table continuous_aggs_watermark
```

**Comment by sotirissl** [comment]
Hi @alejandrodnm,
Thank you for reporting this issue
and for the detailed reproduction steps.
We have a merged PR from our Cloud Team for a similar issue.
Some of us believe that maybe have been fixed.
Please check again and let us know if now is working.
Thank you

**Comment by Harkishen-Singh** [comment]
I tried reproducing this on `TimescaleDB 2.11.0` on Cloud.

I was able to successfully query the `sample_cagg` after the migration from MST.

I hope you meant `select * from team1.sample_cagg;` as `select * from sample_cagg;`, just to remove the possibility that the issue was not reproduced when testing out with https://github.com/timescale/timescaledb/issues/5745.

Let's wait on @alejandrodnm to confirm this before closing the issue.

**Comment by JamesGuthrie** [comment]
Some additional input on this topic:

I _was_ able to reproduce the issue that Alejandro reported, but I suspect that it's "working as intended".

Following Alejandro's instructions, I dumped from 2.11 and restored into 2.11 on Timescale, which went smoothly.

I also dumped from 2.10.3 and restored into 2.11 on Timescale, which failed with the above error.

As far as I know, we do not support dumping from one TimescaleDB version and restoring into another, which is why I suspect that this is working as intended.

**Comment by alejandrodnm** [comment]
Nice catch @JamesGuthrie I thought I was running 2.11 but was in-fact running 2.10. The dump from 2.11 has the dump for the watermarks:

```
--
-- Data for Name: continuous_aggs_invalidation_threshold; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: -
--

--
-- Data for Name: continuous_aggs_watermark; Type: TABLE DATA; Schema: _timescaledb_catalog; Owner: -
--

COPY _timescaledb_catalog.continuous_aggs_watermark (mat_hypertable_id, watermark) FROM stdin;
2	1686700800000000
\.
```

**Comment by moracca** [comment]
Is there any recommended solution for restoring a database that was dumped while running 2.10.3 onto a system that is running 2.11.x?  this would be very helpful in situations where we are moving from one OS version to another and/or migrating server, where the version of the extension on the new server is newer than the system the backup came from.  

I worked around it by manually inserting watermark values into _timescaledb_catalog.continuous_aggs_watermark for all _timescaledb_catalog.continuous_agg mat_hypertable_id where one was missing using a timestamp of unix epoch.  I am not sure of the ramifications of doing so, but it allowed me to begin accessing the continuous aggregates again. 
```
INSERT INTO _timescaledb_catalog.continuous_aggs_watermark (mat_hypertable_id, watermark)
SELECT mat_hypertable_id, -210866803200000000 as watermark
FROM _timescaledb_catalog.continuous_agg
WHERE NOT EXISTS (
    SELECT 1
    FROM _timescaledb_catalog.continuous_aggs_watermark
    WHERE mat_hypertable_id = _timescaledb_catalog.continuous_agg.mat_hypertable_id
);
```

Will there be any other consideration given to backwards compatibility when moving to a version that uses the watermark table?

Thanks

**Comment by JamesGuthrie** [comment]
@moracca No, there is no solution. If you dump from one database and restore into the other, the version of the TimescaleDB extension must be identical. Since TimescaleDB 2.13 this is explicitly enforced, and TimescaleDB will complain about a mismatching catalog version (See PR https://github.com/timescale/timescaledb/pull/6185) when you run `SELECT timescaledb_post_restore()`.
