### ISSUE TITLE
[Enhancement]: Remove columns not null on compressed tables

### ISSUE THREAD

**Issue by LukasJerabek** [timescale/timescaledb#5776]
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Compression

### What does the enhancement do?

It would be nice to be able to remove not null on a column in a compressed table without the need to decompress the whole table. For example I cant even do that, because I would run out of space.

### Implementation challenges

Unfortunatelly I dont have necessary knowledge to understand what would it take to implement and why compression prevents user to do that.

**Comment by LukasJerabek** [comment]
@mkindahl thank you! :)

**Comment by mkindahl** [comment]
@LukasJerabek Sorry that it took so long.
