### ISSUE TITLE
[Flaky test] dist_insert - connection to data node lost

### ISSUE THREAD

**Issue by jnidzwetzki** [timescale/timescaledb#5782]
### Which test is flaky?

dist_insert

### Since when has the test been flaky?

13.06.2023

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/5249736210/jobs/9482872451
https://github.com/timescale/timescaledb/actions/runs/5261542022/jobs/9509768151

### Log output

```bash
ERROR:  connection to data node "data_node_2" was lost
```

**Comment by jnidzwetzki** [comment]
Failed again in CI https://github.com/timescale/timescaledb/actions/runs/5271606586/jobs/9532737029

**Comment by jnidzwetzki** [comment]
Failed again  https://github.com/timescale/timescaledb/actions/runs/5284811412/jobs/9562634476

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
