### ISSUE TITLE
[Bug]: Broken upgrade path from 1.7.x to 2.10.2 or later

### ISSUE THREAD

**Issue by mawe42** [timescale/timescaledb#5789]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

During upgrade of a timescaledb-1.7.1 installation to 2.10.3, we got the following error after executing `ALTER EXTENSION timescaledb UPDATE`:

`ERROR:  function _timescaledb_internal.ping_data_node(name) does not exist`

We then tried to upgrade to 2.10.0 instead, which worked flawlessly.

My guess is that the problem is related to commit 12f3131f9, as it introduces the following line in `sql/updates/2.10.1--2.10.2.ql`:
```
DROP FUNCTION _timescaledb_internal.ping_data_node(NAME);
```

### TimescaleDB version affected

2.10.2 and later

### PostgreSQL version used

12.13

### What operating system did you use?

OpenSUSE Leap 15.4

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Upgrade a timescaledb-1.7.1 installation to timescaledb-2.10.2
```

**Comment by jnidzwetzki** [comment]
Hello @mawe42,

Thanks for reporting this behavior. The function `ping_data_node` was introduced in TimescaleDB 2.0.0. So, older installations do not contain this function. Because it is dropped without `IF EXISTS` in the upgrade script, the operation fails and the direct upgrade path to versions > 2.10.2 is broken.

As a workaround, you should be able to upgrade to version 2.11.0 after you upgrade to a version > 2.0.0 and < 2.10.2 (e.g., 2.10.3).

**Comment by svenklemm** [comment]
PostgreSQL 12 is no longer supported with timescaledb.

**Comment by Diego91RA** [comment]
For me on Debian 11 it worked when I installed packages version 2.5.0 first
```
apt install timescaledb-2-postgresql-12=2.5.0~debian11
apt install timescaledb-2-loader-postgresql-12=2.5.0~debian11
```
Result:
```
zabbix=# ALTER EXTENSION timescaledb UPDATE;
ALTER EXTENSION
zabbix=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.5.0   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)
```
After updating packages to 2.11.2:
```
zabbix=# ALTER EXTENSION timescaledb UPDATE;
ALTER EXTENSION
zabbix=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.11.2  | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.

**Comment by RadekFurmanek** [comment]
> Hello @mawe42,
> 
> Thanks for reporting this behavior. The function `ping_data_node` was introduced in TimescaleDB 2.0.0. So, older installations do not contain this function. Because it is dropped without `IF EXISTS` in the upgrade script, the operation fails and the direct upgrade path to versions > 2.10.2 is broken.
> 
> As a workaround, you should be able to upgrade to version 2.11.0 after you upgrade to a version > 2.0.0 and < 2.10.2 (e.g., 2.10.3).

Hello, I just want to write my experience. 
I had the same problem. After install new Major version timescaledb2, the problem with  'function _timescaledb_internal.ping_data_node(name) does not exist' occured. So I findout this solution (first upgrade to 2.0.0), but my paths do not have this particular path from 1.7.5 to 2.0.0 but only straight to 2.11.2 

SO I findout the SQL file with path 1.7.5 to 2.11.2 in '_usr/lib/share/extension_' and findout the line with `DROP FUNCTION ping_data_node()` and just added `IF EXISTS` as you mentioned in the reply. And this worked well for me.

**Comment by rubensbarreto** [comment]
Same here,  upgrading from 1.7.4 to 2.11.2 on postgres 12, ubuntu 20.

Trying to run the command specifying any other version finds no path, and upgrading to 2.11.2 throws the ping_data_node does not exist error.

On ubuntu, just edit the file /usr/lib/share/postgres/12/extension/timescaledb--1.7.4--2.11.2.sql (with your appropriate upgrade path and postgres version)

Edit the DROP FUNCTION  _timescaledb_internal.ping_data_node(NAME); for:
DROP FUNCTION  IF EXISTS _timescaledb_internal.ping_data_node(NAME);

Run the command and it works
