### ISSUE TITLE
[Bug]: Update/Delete still fails on v 2.11 on compressed chunks

### ISSUE THREAD

**Issue by muntdan** [timescale/timescaledb#5794]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

I am using latest docker image from 2 days ago:  timescale/timescaledb-ha:pg15.3-ts2.11.0 with volume to existing compressed data but I tested with new created tables also after they got compressed.

Whenever I try to run  `update public."table" set columnX=columnX+1 where datetime between '2023-04-10' and '2023-04-17'`
or `delete from public."table" where datetime between '2023-04-01' and '2023-04-01 00:01:35'`
I encounter the error:
`ERROR:  cannot update/delete rows from chunk "_hyper_33_39137_chunk" as it is compressed 
SQL state: XX000`

I was expecting according to https://docs.timescale.com/about/latest/release-notes/ to support this now. 

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Use latest image
docker pull timescale/timescaledb-ha:pg15.3-ts2.11.0
```

**Comment by sb230132** [comment]
Hi @muntdan 
With 2.11 this is not correct behaviour with UPDATE/DELETE on compressed chunk.
This error is encountered when one executes UPDATE/DELETE on compressed chunk with timescaledb version < 2.11
Can you please confirm that the installed timescaledb extension version is 2.11.
