### ISSUE TITLE
[Bug]: Too many sub-tables were locked during time range query procedure

### ISSUE THREAD

**Issue by murongfeng66** [timescale/timescaledb#5826]
### What type of bug is this?

Locking issue, Performance issue

### What subsystems and features are affected?

Query executor

### What happened?

When I use the time range seat condition to query the hypertable (block 1h), I find that the query obtains the AccessShareLock lock of the block table outside the time range, such as the time range is: 2022-12-31 23:59:00.000 to 2023-06-28 23:59:59.999, the obtained block table lock is: 2022-07-29 09:00:00.000 to 2023-06-28 11:00:00.000. In fact, you only need to obtain the locks on the 2022-12-31 23:00:00.000 to 2023-06-28 23:00:00.000 block. 
The query lock sql used is:
select pl1.locknum, pl.pid, pl."mode", pc.relname, to_timestamp(tc.range_start_integer/1000) as range_start_integer , to_timestamp(tc.range_end_integer/1000) as range_end_integer, psa.query from pg_locks pl
left join pg_class pc on pl.relation = pc."oid" 
right join (select pid, count(*) as locknum from pg_locks group by pid order by locknum desc limit 1) pl1 on pl1.pid = pl.pid
left join pg_stat_activity psa on psa.pid = pl.pid
left join timescaledb_information.chunks tc on tc.chunk_name = pc.relname
where pc.relam = 2
order by tc.range_start_integer;

### TimescaleDB version affected

2.9.2

### PostgreSQL version used

12.15

### What operating system did you use?

Ubuntu 20.04.2 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
Use the following SQL to query：
select time_bucket('1 minutes', to_timestamp(ts/1000), 'Asia/Shanghai') as time, sum_text(dh.value) as value from data_history dh  where sensor_id = '0453b52b-502e-49d4-a4e7-5a81b458c9b0'  and '2022-12-31 23:59:00.000' <= to_timestamp(ts/1000)  and to_timestamp(ts/1000) <= '2023-06-28 23:59:59.999' group by time  order by time
```

**Comment by lkshminarayanan** [comment]
Hi @murongfeng66,

I ran a small test and I'm unable to reproduce the issue you mention. In my tests, the `AccessShareLock` was taken only on the relevant chunks filtered based on the WHERE clause.

Here is my test setup :
```
-- Create the table
CREATE TABLE devices (
  device_id int NOT NULL,
  time timestamptz NOT NULL,
  value float
);

-- Create hypertable
SELECT create_hypertable('devices', 'time');

-- Populate it
INSERT INTO devices
  SELECT id, time, ceil(random() * 100)::int
    FROM generate_series(1,5,1) id,
           generate_series('2000-01-01 0:00:00+0'::timestamptz,
                           '2000-01-31 23:55:00+0','6h') time;
```

Post insertion, the hypertable had 5 chunks :
```
postgres=# SELECT show_chunks('devices');
              show_chunks               
----------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
 _timescaledb_internal._hyper_1_2_chunk
 _timescaledb_internal._hyper_1_3_chunk
 _timescaledb_internal._hyper_1_4_chunk
 _timescaledb_internal._hyper_1_5_chunk
(5 rows)
```

Consider the following `SELECT time_bucket ...` query very similar to the one you have mentioned in the issue :
```
SELECT time_bucket('1 day', time) AS one_day_bucket, avg(value)
  FROM devices
  WHERE device_id = 3 AND
    '2000-01-10 0:00:00+0'::timestamptz <= time AND
    time < '2000-01-11 0:00:00+0'::timestamptz
  GROUP BY 1 ORDER BY 1;
```

Let's first examine the EXPLAIN output of the above SELECT :
```
postgres=# EXPLAIN SELECT time_bucket('1 day', time) AS one_day_bucket, avg(value)
  FROM devices
  WHERE device_id = 3 AND
    '2000-01-10 0:00:00+0'::timestamptz <= time AND
    time < '2000-01-11 0:00:00+0'::timestamptz
  GROUP BY 1 ORDER BY 1;
                                                                                        QUERY PLAN                                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=3.54..3.63 rows=4 width=16)
   Group Key: (time_bucket('1 day'::interval, _hyper_1_2_chunk."time"))
   ->  Sort  (cost=3.54..3.55 rows=4 width=16)
         Sort Key: (time_bucket('1 day'::interval, _hyper_1_2_chunk."time"))
         ->  Result  (cost=0.00..3.50 rows=4 width=16)
               ->  Seq Scan on _hyper_1_2_chunk  (cost=0.00..3.45 rows=4 width=16)
                     Filter: (('2000-01-10 05:30:00+05:30'::timestamp with time zone <= "time") AND ("time" < '2000-01-11 05:30:00+05:30'::timestamp with time zone) AND (device_id = 3))
(7 rows)

```
This explain shows that the query is sent only to the `_hyper_1_2_chunk` chunk and this implies that postgres will get an AccessShareLock only on that chunk.

I verified this by getting an exclusive lock on all remaining chunks from a different session and then running the SELECT from the initial session, which succeeded.

```
-- Session 2
-- Acquire locks on all other chunks
postgres=# BEGIN;exclusive 
BEGIN
Time: 0.439 ms
postgres=*# LOCK TABLE _timescaledb_internal._hyper_1_1_chunk,
    _timescaledb_internal._hyper_1_3_chunk,
    _timescaledb_internal._hyper_1_4_chunk,
    _timescaledb_internal._hyper_1_5_chunk
  IN ACCESS EXCLUSIVE MODE;
LOCK TABLE
Time: 0.733 ms
```

And then run the SELECT from the initial session :
```
postgres=# SELECT time_bucket('1 day', time) AS one_day_bucket, avg(value)
  FROM devices
  WHERE device_id = 3 AND
    '2000-01-10 0:00:00+0'::timestamptz <= time AND
    time < '2000-01-11 0:00:00+0'::timestamptz
  GROUP BY 1 ORDER BY 1;
      one_day_bucket       | avg 
---------------------------+-----
 2000-01-10 05:30:00+05:30 |  42
(1 row)

Time: 2.976 ms
```

As you can see, the SELECT succeeded despite the other session taking an exclusive lock on all other chunks, which shows that this SELECT never attempted to take an AccessShareLock on the other chunks. 

It could be the case that this issue manifests only under certain conditions. So, can you provide us your hypertable definition and if possible the exact set of queries you executed when running into this issue?

**Comment by murongfeng66** [comment]
It has been verified that this is not the case when I concatenate the time parameters directly in SQL, but it is the case when using JDBC's parameter placeholders.
This does not occur when JDBC is used to execute the following SQL:
```plpgsql
select time_bucket('1 minutes', to_timestamp(ts/1000), 'Asia/Shanghai') as time, sum_text(dh.value) as value from data_history dh  where sensor_id = '0453b52b-502e-49d4-a4e7-5a81b458c9b0'  and '2022-12-31 23:59:00.000' <= to_timestamp(ts/1000)  and to_timestamp(ts/1000) <= '2023-06-28 23:59:59.999' group by time  order by time
``` 
This occurs when the following SQL is executed using JDBC:
```plpgsql
select time_bucket('1 minutes', to_timestamp(ts/1000), 'Asia/Shanghai') as time, sum_text(dh.value) as value from data_history dh  where sensor_id = ?  and ? <= to_timestamp(ts/1000)  and to_timestamp(ts/1000) <= ? group by time  order by time
``` 
My hypertable creation SQL is as follows:
```plpgsql
create table if not exists data_history ( sensor_id varchar(64) not null, ts bigint, value varchar(1024) )
```

**Comment by akuzm** [comment]
I guess with parameter placeholder it uses prepared statements with the generic plan, so the chunks are not excluded at planning time, only at run time, and before that they are locked. So as a workaround, you could set `plan_cache_mode = 'force_custom_plan'` for these statements, or not use prepared statements. Probably we could be smarter there and not lock the chunks we're going to exclude at run time, but not sure how easy this is to implement.
