### ISSUE TITLE
APT: could not access file "timescaledb-0.9.2":

### ISSUE THREAD

**Issue by dima-spire** [timescale/timescaledb#583]
Hello, I had timescaledb installed on Linux Mint, PostgreSQL 9.6 server, from `http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu`, and didn't touch it for a while, while applying all the APT updates.

Now when I try to list all the tables in my databases I get `could not access file "timescaledb-0.9.2":` error:
```
$ psql
psql (10.4 (Ubuntu 10.4-2.pgdg16.04+1), server 9.6.9)
Type "help" for help.

dl=# \dt
ERROR:  could not access file "timescaledb-0.9.2": No such file or directory
dl=# 
```

I see that the current version of timescale installed is 0.10.0:
```
$ apt-cache policy timescaledb-postgresql-9.6
timescaledb-postgresql-9.6:
  Installed: 0.10.0~ubuntu16.04
  Candidate: 0.10.0~ubuntu16.04
  Version table:
 *** 0.10.0~ubuntu16.04 500
        500 http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

I tried to reinstall older version says there's no such version anymore:
```
$ sudo apt install timescaledb-postgresql-9.6:amd64=0.9.2~ubuntu16.04
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '0.9.2~ubuntu16.04' for 'timescaledb-postgresql-9.6' was not found
```

Could you help me with that? While my data is probably save, not being able to get it is pretty much equivalent to lost data.

**Comment by RobAtticus** [comment]
It seems you upgraded the `apt` package but did not update the database itself. When you connect with psql, use `psql -X` and then run as your first command `ALTER EXTENSION timescaledb UPDATE;`

**Comment by dima-spire** [comment]
That worked, thank you. Didn't know I should run `ALTER EXTENSION timescaledb UPDATE;` after updating TimescaleDB.
