### ISSUE TITLE
[Bug]: Which server log is timescaledb_information.job_errors table "job crash detected, see server logs"?

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5853]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Compression, Other

### What happened?

There are "job crash detected, see server logs" records in timescaledb_information.job_errors table
How could we check the server log, what is the server log please? Thanks

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.6

### What operating system did you use?

Centos 7.9

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
N.A
```

**Comment by lkshminarayanan** [comment]
Hi @yinan8128 

It refers to the PostgreSQL server logs. Depending on how you have configured your PostgreSQL logs, you have to access that log to lookup why your job crashed. More info on the logging mechanism : https://www.postgresql.org/docs/current/runtime-config-logging.html. Let me know if you need more information on this.

**Comment by nikkhils** [comment]
@yinan8128 closing this now based on the answer provided above.
