### ISSUE TITLE
[Bug]: Update on compressed chunks results in buffer cache eviction and never caching again

### ISSUE THREAD

**Issue by siraj-mx51** [timescale/timescaledb#5858]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

I executed an update statements which targets a single row, but which resulted in scanning all compressed chunks given that my filters didn't narrow it down to a specified chunk. However it appears this resulted in evicting data from the buffer cache for all chunks. While i can expect this to happen for the chunk that has to be updated as it gets uncompressed and recompressed but i am not sure why would it happen for all chunks.

Subsequent read queries performance degraded dramatically but never improved as it appears the buffer cache is not being repopulated no matter how much i re-run the queries.

### TimescaleDB version affected

2.11

### PostgreSQL version used

14.8

### What operating system did you use?

aarch64-apple-darwin22.4.0

### What installation method did you use?

Homebrew

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
- Run a heavy read query to warm up the caches (my setup had 1.5 billion rows all compressed, but you probably don't need that much to reproduce)
- Confirm with EXPLAIN (ANALYZE,BUFFERS) that data is being served from cache with `Buffer Hits`
- Run an update statement targeting a single row on a compressed chunk but without filters included in the segment-by or order-by, for example update by id while id is not in the segment/order by columns
- Running the same read queries again should result in a huge performance degradation
- EXPLAIN (ANALYZE,BUFFERS) should confirm that `Buffers: shared hit=XXX read=XXXX` values are not changing after re-runs and most data is being read from disk
```

**Comment by fabriziomello** [comment]
@siraj-mx51 can u please provide a reproducible (step by step using SQL scripts) test case.
