### ISSUE TITLE
[Bug]: Stack depth limit exceeded when deleting from compressed hypertable

### ISSUE THREAD

**Issue by melicheradam** [timescale/timescaledb#5866]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

When deleting from compressed chunks of a hypertable using `WHERE ... IN` or `WHERE ... ANY` clauses, the deletion fails with `stack depth limit exceeded` error message. This fails even with 1 element in the statements. When using regular = operator deletion works fine. Also when deleting from non-compressed chunks, the query works fine with IN and ANY.

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

15

### What operating system did you use?

Docker Image on MacOS 13.4

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
ERROR: stack depth limit exceeded
HINT: Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
```

### How can we reproduce the bug?

```bash

Create a hypertable with timestamp, uuid, value columns. Enable compression, insert data into table. Enable compression and compress the data. Try to delete using `IN` or `ANY` statements.

DELETE FROM table WHERE (timestamp, uuid) IN ((xxx, yyy)) - fails

DELETE FROM table WHERE timestamp=xxx AND uuid=yyy  - OK


DROP TABLE test;

CREATE TABLE test(time TIMESTAMPTZ, device INT, temp float8);
SELECT create_hypertable('test', 'time', chunk_time_interval => INTERVAL '2 months');

INSERT INTO test SELECT t, (abs(timestamp_hash(t::timestamp)) % 10) + 1, 0.10 FROM generate_series('2013-07-02 1:00'::TIMESTAMPTZ, '2023-07-08 1:00', '1 minute') t;

ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'device');

SELECT add_compression_policy('test', INTERVAL '60 days');

```

**Comment by RafiaSabih** [comment]
@melicheradam Thanks for reporting this. Could you be please more elaborate and provide the exact steps for this part of your problem,
`Create a hypertable with timestamp, uuid, value columns. Enable compression, insert data into table. Enable compression and compress the data. Try to delete using `IN` or `ANY` statements.

DELETE FROM table WHERE (timestamp, uuid) IN ((xxx, yyy)) - fails

DELETE FROM table WHERE timestamp=xxx AND uuid=yyy  - OK
`
It will help us in faster reproduction of issue at our end and rectifying it then.

**Comment by melicheradam** [comment]
Hey @RafiaSabih 

I dont know what else do you need? I have provided commands to generate the table, populate some data, enable compression, working and non-working WHERE conditions, cannot the person solving this slightly edit the commands if needed?

**Comment by sb230132** [comment]
Hi, 
This issue will be fixed by https://github.com/timescale/eng-database/issues/456
