### ISSUE TITLE
[Bug]: Segmentation fault while runningFETCH FORWARD ALL FROM "fetch_recent_fill_for_BITSTAMP_sweeper"

### ISSUE THREAD

**Issue by Rama-Selvaraj** [timescale/timescaledb#5871]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Data node

### What happened?

We observed segment fault errors in out logs . The below are details observed from log

804STATEMENT:  INSERT INTO trading.client_orders (
time=2023-07-12 14:45:49 UTC, pid=12958 LOG:  00000: server process (PID 10009) was terminated by signal 11: Segmentation fault
time=2023-07-12 14:45:49 UTC, pid=12958 DETAIL:  Failed process was running: SELECT * FROM "trading"."router_execution_reports" ORDER BY "ord_typ
e" DESC LIMIT 400 OFFSET 0;
time=2023-07-12 14:45:49 UTC, pid=12958 LOCATION:  LogChildExit, postmaster.c:3719
time=2023-07-12 14:45:49 UTC, pid=12958 LOG:  00000: terminating any other active server processes
time=2023-07-12 14:45:49 UTC, pid=12958 LOCATION:  HandleChildCrash, postmaster.c:3440
time=2023-07-12 14:45:49 UTC, pid=10631  db=postgres, usr=postgres, client=10.2.77.63 , app=[unknown], line=1WARNING:  57P02: terminating connect
ion because of crash of another server process

Details of pid=10009
cat postgresql-2023-07-11.log|grep "pid=10009"|more

postgres@ip-172-22-10-76:/tsdb_dev/pg_data/pg_log$ cat postgresql-2023-07-11.log|grep "pid=10009"|more
time=2023-07-11 20:48:37 UTC, pid=10009  db=postgres, usr=postgres, client=10.2.77.63 , app=[unknown], line=1LOG:  00000: duration: 2528.783 ms
statement: FETCH FORWARD ALL FROM "fetch_recent_fill_for_COINBASE_sweeper"
time=2023-07-11 20:48:37 UTC, pid=10009  db=postgres, usr=postgres, client=10.2.77.63 , app=[unknown], line=2LOCATION:  exec_simple_query, postgr
es.c:1296

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

12.9

### What operating system did you use?

Ubuntu 18.04.6 LTS

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
NA
```

### How can we reproduce the bug?

```bash
Not sure how to reproduce it. 

The same statement is working perfectly fine sometimes
```

**Comment by pmwkaa** [comment]
Thank you for your report, is that a chance to try a more recent timescaledb version?
