### ISSUE TITLE
[Bug]: LATERAL JOIN queries on compressed data are warning of "TupleDesc reference leaks"

### ISSUE THREAD

**Issue by ajcanterbury** [timescale/timescaledb#5883]
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression

### What happened?

When running LATERAL JOIN queries across multiple columns in a table containing compressed chunks we see this warning message for every column past the first one:

`WARNING:  TupleDesc reference leak: TupleDesc 0x<unique> (<unique>,-1) still referenced`

If there is no compressed chunk within the time range we don't see this warning.
Tested that these warnings are only being seen after the 2.11 update, 2.11.1 is also affected.

### TimescaleDB version affected

2.11

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Docker

### What platform did you run on?

Google Cloud Platform (GCP)

### Relevant log output and stack trace

```bash
WARNING:  TupleDesc reference leak: TupleDesc 0x4147cdd728 (22082,-1) still referenced
WARNING:  TupleDesc reference leak: TupleDesc 0x4147cdd728 (22082,-1) still referenced
```

### How can we reproduce the bug?

```bash
CREATE TABLE IF NOT EXISTS device_states (
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    attr_id SMALLINT NOT NULL,
    number_val DOUBLE PRECISION DEFAULT NULL,
    UNIQUE (attr_id, timestamp)
  );
  SELECT create_hypertable(
    'device_states', 'timestamp',
    create_default_indexes => FALSE, if_not_exists => TRUE, chunk_time_interval => INTERVAL '1 day'
  );
  
alter table device_states set (
      timescaledb.compress,
      timescaledb.compress_segmentby = 'attr_id'
    );

INSERT INTO device_states VALUES ('2023-07-01T22:15:00.046Z', 1, 1),
                                 ('2023-07-01T22:15:00.046Z', 2, 1),
                                 ('2023-07-01T22:15:00.046Z', 3, 1);

SELECT compress_chunk('_timescaledb_internal.' ||
  (SELECT chunk_name FROM timescaledb_information.chunks WHERE hypertable_name = 'device_states'), if_not_compressed => TRUE);

SELECT * FROM (VALUES(1),(2),(3)) AS attr_ids(attr_id)
INNER JOIN LATERAL (
  SELECT * FROM device_states
  WHERE device_states.attr_id = attr_ids.attr_id AND
    timestamp >= '2023-01-18T21:15:00.046Z' AND timestamp <= '2023-07-16T22:15:00.046Z'
ORDER BY timestamp desc  LIMIT 1 ) a ON true;
```

**Comment by RafiaSabih** [comment]
@ajcanterbury Thanks for reporting this. If is it possible for you can you upgrade your extension and check if the issue persists.
