### ISSUE TITLE
creating hypertable with BIGINT datatype for time column

### ISSUE THREAD

**Issue by vinits-lc** [timescale/timescaledb#5887]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

tried to convert postgresql table to hypertable using

`SELECT create_hypertable('augmentedstatetransactions', 'starttime');`

giving 

**ERROR:  integer dimensions require an explicit interval**

then tried 

` SELECT create_hypertable('augmentedstatetransactions', 'starttime', chunk_time_interval >= INTERVAL '7 days');`

gave error

**ERROR:  column "chunk_time_interval" does not exist**

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

15.3

### What operating system did you use?

Windows 11x64

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
create table augmentedstatetransactions (
nodeId INT NOT NULL,
starttime BIGINT NOT NULL,
endtime BIGINT NOT NULL);

SELECT create_hypertable('augmentedstatetransactions', 'starttime');

SELECT create_hypertable('augmentedstatetransactions', 'starttime', chunk_time_interval >= INTERVAL '7 days');
```

**Comment by fvannee** [comment]
You specify `>=` instead of `=>`.

```
SELECT create_hypertable('augmentedstatetransactions', 'starttime', chunk_time_interval => INTERVAL '7 days');
```

I don't think this will work either though, because you need to specify the `chunk_time_interval` in integer as well. Timescale won't know what unit your `starttime` is in: seconds, minutes, hours?

So this should work for example, and would create 1 hour chunks if your unit is in seconds.

```
SELECT create_hypertable('augmentedstatetransactions', 'starttime', chunk_time_interval => 3600);
```

**Comment by vinits-lc** [comment]
Yeah it works, thanks!
