### ISSUE TITLE
[Bug]: Reading from compressed chunk results in "child rel 1 not found in append_rel_array SQL state: XX000"

### ISSUE THREAD

**Issue by TheDromundKaas** [timescale/timescaledb#5895]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

After inserting a row into a compressed chunk, reading any row from that chunk with `extract(epoch from refdate)` in the field list  results in the mentioned error message. We can reliable reproduce the error with a fresh database and table.

The table definition:

>   Column  |           Type           | Collation | Nullable |      Default      | Storage | Compression | Stats target | Description
> ----------+--------------------------+-----------+----------+-------------------+---------+-------------+--------------+-------------
>  refdate  | timestamp with time zone |           | not null |                   | plain   |             |              |
>  tid      | numeric(10,0)            |           | not null |                   | main    |             |              |
>  arcvalue | numeric                  |           |          |                   | main    |             |              |
>  valstat  | numeric(10,0)            |           |          |                   | main    |             |              |
>  herkunft | numeric(2,0)             |           |          |                   | main    |             |              |
>  moddatum | timestamp with time zone |           |          | clock_timestamp() | plain   |             |              |
>  io       | numeric(1,0)             |           |          |                   | main    |             |              |
> Indexes:
>     "arvvalue7_pk" PRIMARY KEY, btree (refdate, tid)
>     "arvvalue7_ta_refdate_idx" btree (refdate DESC)
> Triggers:
>     ts_insert_blocker BEFORE INSERT ON arv.arvvalue7_ta FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
> Child tables: _timescaledb_internal._hyper_7_13_chunk,
>               _timescaledb_internal._hyper_7_18_chunk,
>               _timescaledb_internal._hyper_7_1_chunk,
>               _timescaledb_internal._hyper_7_20_chunk,
>               _timescaledb_internal._hyper_7_22_chunk,
>               _timescaledb_internal._hyper_7_33_chunk,
>               _timescaledb_internal._hyper_7_35_chunk,
>               _timescaledb_internal._hyper_7_37_chunk,
>               _timescaledb_internal._hyper_7_9_chunk
> Access method: heap

The chunks are usually days:

>  hypertable_schema | hypertable_name | primary_dimension |      range_start       |       range_end        | is_compressed
> -------------------+-----------------+-------------------+------------------------+------------------------+---------------
>  arv               | arvvalue7_ta    | refdate           | 2023-07-14 02:00:00+02 | 2023-07-15 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-17 02:00:00+02 | 2023-07-18 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-21 02:00:00+02 | 2023-07-22 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-20 02:00:00+02 | 2023-07-21 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-19 02:00:00+02 | 2023-07-20 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-18 02:00:00+02 | 2023-07-19 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-24 02:00:00+02 | 2023-07-25 02:00:00+02 | t
>  arv               | arvvalue7_ta    | refdate           | 2023-07-26 02:00:00+02 | 2023-07-27 02:00:00+02 | f
>  arv               | arvvalue7_ta    | refdate           | 2023-07-25 02:00:00+02 | 2023-07-26 02:00:00+02 | f
> 

Without data for the chunk, a query over the datetime range works without a problem. Inserting into a compressed chunk works, and the data can be queried:

`select * from arvvalue7_ta where refdate >= '2023-07-18 00:00:00+2' and refdate <= '2023-07-24 00:00:00+2';`

Works.

However, if we add an `extract` function to the query, the query fails:

`select extract(epoch from refdate) from arvvalue7_ta where refdate >= '2023-07-18 00:00:00+2' and refdate <= '2023-07-27 00:00:00+2';`
or
`select *, extract(epoch from refdate) from arvvalue7_ta where refdate >= '2023-07-18 00:00:00+2' and refdate <= '2023-07-27 00:00:00+2';`

Result: SQL-Fehler [XX000]: ERROR: child rel 1 not found in append_rel_array

As an added bonus, while playing around with the statement, we found that we might be able to work around the issue. One of the options was adding a subquery that supplies the row identification, like so:

`select extract(epoch from refdate) from arvvalue7_ta where tid in (select tid from arvvalue7_ta where refdate >= '2023-07-18 00:00:00+2' and refdate <= '2023-07-27 00:00:00+2');`

Works.

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

15.1

### What operating system did you use?

SLES15 SP3

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
1. Create the table as described
2. Add a compression policy that compresses data older than a few days
3. Insert data into an already compressed chunk:

insert into arvvalue7_ta (tid, refdate, arcvalue, valstat, herkunft, moddatum) values (2,'2023-07-18T02:00:06+02:00',1.0,1,1,now());

4. Query any row from the compressed chunk that is now definitely available (because it has at least one row).
```

**Comment by akuzm** [comment]
What is your compression policy, i.e. the `compress_segmentby` and `compress_orderby`? I'm unable to reproduce it with a simple example, do you have some suggestions or maybe sample data? I tried the following:

```
drop table arvvalue7_ta;
create table arvvalue7_ta(refdate timestamptz, tid numeric(10, 0), arcvalue numeric, valstat numeric(10, 0), herkunft numeric(2, 0), moddatum timestamptz, io numeric(1, 0),
    primary key (refdate, tid));
select create_hypertable('arvvalue7_ta', 'refdate');
alter table arvvalue7_ta set (timescaledb.compress, timescaledb.compress_segmentby = 'tid');
insert into arvvalue7_ta values ('2022-02-02 02:02:02', 2, 2, 2, 2, now(), 2);
select compress_chunk(x, true) from show_chunks('arvvalue7_ta') x;

-- now update the compressed chunk in various ways and see if the select works.

-- insert into arvvalue7_ta values ('2022-02-02 03:03:03', 3, 3, 3, 3, now(), 3);
-- insert into arvvalue7_ta values ('2022-02-02 03:03:03', 2, 2, 2, 2, now(), 2);
insert into arvvalue7_ta values ('2022-02-02 02:02:02', 2, 3, 2, 2, now(), 2) on conflict (refdate, tid) do update set arcvalue = excluded.arcvalue;
explain (analyze) select extract(epoch from refdate) from arvvalue7_ta where refdate < '2023-01-01' and refdate > '2022-01-01';
```

As an aside, using numerics as integers (scale 0) will cost you a lot of performance, and make compression worse. The way it is represented in postgres has large storage and computational overhead. Unless you have to use fixed decimal point, e.g. for money, consider just integers instead.

**Comment by TheDromundKaas** [comment]
The tables are created by calling a Liquibase script. The staments that set the mentioned settings and other maybe relevant statements are:

`SELECT create_hypertable('arvvalue7_ta', 'refdate', chunk_time_interval => INTERVAL '1 day', migrate_data => true);`
`ALTER TABLE arvvalue7_ta SET ( timescaledb.compress, timescaledb.compress_orderby = 'refdate', timescaledb.compress_segmentby = 'tid');`

We know about the numeric problems. It currently stems from a conversion from Oracle. We hope to improve on the data types in the future.

**Comment by TheDromundKaas** [comment]
A short update to this issue:

After using the code akuzm wrote down above on the system we had the problem with, we instantly see it appear with the `explain` statement. We tested it on another machine, also SLES, but SP4, with a newer PostgreSQL version (15.4 instead of 15.3), and while both have the same TimescaleDB version, this other test machine did not show the problem.

Any idea of what to check to see what could cause the problem described?
