### ISSUE TITLE
[Bug]: Upgrade from 2.8.1 to 2.11.1 fails

### ISSUE THREAD

**Issue by mrksngl** [timescale/timescaledb#5900]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Access node, Distributed hypertable

### What happened?

I tried to update timescale from 2.8.1 to 2.11.1.
On the data nodes, everything went fine, but the access nodes fails with the error message
`ERROR:  invalid name syntax`

This does not apply for all our databases, more precisely only for one.
The others were updated without any problems.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.8

### What operating system did you use?

Ubuntu 22

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-07-27 19:45:09.362 UTC user=postgres db=sero-services-v3 pid=2392LOG:  connection authorized: user=postgres database=sero-services-v3 application_name=psql
2023-07-27 19:45:09.398 UTC user= db= pid=2311FATAL:  terminating background worker "TimescaleDB Background Worker Scheduler" due to administrator command
2023-07-27 19:45:09.405 UTC user= db= pid=50LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 2311) exited with exit code 1
2023-07-27 19:45:09.934 UTC user=postgres db=sero-services-v3 pid=2392ERROR:  invalid name syntax
2023-07-27 19:45:09.934 UTC user=postgres db=sero-services-v3 pid=2392STATEMENT:  alter extension timescaledb update TO "2.11.1"
2023-07-27 19:45:09.960 UTC user=postgres db=sero-services-v3 pid=2392LOG:  disconnection: session time: 0:00:00.600 user=postgres database=sero-services-v3 host=[local]
```

### How can we reproduce the bug?

I have not yet found a way to trigger the bug.

Since it says "invalid name syntax", I wondered whether it has something to do with the rather unusual names we use in our setup:
* The database name contains dashes
* There are schemata (other than `public`) in use
* Hypertables reside in those schemata
* Name of the owner of the schemata and hypertables also contains dashes

Also, compression is used on some of the hypertables.

I tried to reproduce the bug, rebuilding everything as above:
- I created a new database (with 2.8.1 loaded), schema and distributed hypertable.
- I also used dashes in the data base name and the owner.
- I compressed some chunks after inserting data.
- However, I could update all data nodes and the access node to 2.11.1 without any problem.

I guess that the update script fails somewhere, but without having any context (e.g. where exactly it fails), there is no way (for me) to provide more data.

I wonder if there is any way to get more output from the upgrade process.

**Comment by mrksngl** [comment]
I guess I found it:
using `psql -v VERBOSITY=verbose -v SHOW_CONTEXT=always` when trying to update, it gave me `LOCATION:  regrolein, regproc.c:1637`.
It seems that this function (or some which it calls) cannot handle role names containing a dot.

Now the update script tries to alter table `_timescaledb_config.bgw_job`, setting the owner to a `regrole` using `owner::regrole` and I guess that this triggers function `regrolein`.

In any case, `SELECT 'some.role'::regrole` emits `ERROR:  invalid name syntax`.

Unfortunately, zalando's postgres operator generates those names containing the dot :(

After all, it is not a timescaledb bug, closing.

**Comment by mrksngl** [comment]
Follow up: `select '"some.role"'::regrole` works, but that's terrible ;)

**Comment by mrksngl** [comment]
Sorry for the mess: reopened issue.

I read a bit more about those internals and came to the conclusion that its actually a bug of timescaledb for not properly quoting role names.
Created PR in #5906

**Comment by konskov** [comment]
Thank you for taking the time to investigate and already opening a PR for this @mrksngl, really appreciated! We’ll review it as soon as there is a chance.

**Comment by nikkhils** [comment]
many thanks @mrksngl for the patch. We have merged it now. I am closing this for now. The 2.12.0 release should have it.

**Comment by mkindahl** [comment]
Update tests were added in #5930 to make sure that this does not surface again.
