### ISSUE TITLE
[Bug]: <How to get size and compression_stats for all hypertables and chunks for pgwatch2 usage>

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5911]
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression, Other

### What happened?

Hello,

We proceed to add timescaledb hypertable_detailed_size, chunks_detailed_size, hypertable_compression_stats and chunk_compression_stats to pgwatch2 metrics, but have to pass the hypertable name(not support 1 query get all hypertable or chunk information), and [Informational views](https://docs.timescale.com/api/latest/informational-views/) no the information

pgwatch2 behavior need to select all records no filter in query(filter in grafana side), is there any method to get size and compression_stats for all hypertables or chunks in 1 query like timescaledb_information.hypertables and timescaledb_information.chunks for pgwatch2 usage please? Thanks

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.6

### What operating system did you use?

CentOS Linux release 7.9.2009

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
N.A
```

**Comment by konskov** [comment]
hi @yinan8128, I'm not sure if this is a bug, could you explain more in detail what is the exact information you are looking for or give an example of what the query output you need should look like? Would using `_timescaledb_catalog.hypertable` help you?
