### ISSUE TITLE
[Bug]: There are several hypertables, is it possible to set them compression policy time and retention policy time to different time?

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5949]
### What type of bug is this?

Configuration, Other

### What subsystems and features are affected?

Compression, Configuration

### What happened?

Hello,

There are 24 hypertables in our env, and we used below loop table names logic to add compression policy and add retention policy, 

```
--loop table names
SELECT add_retention_policy('{{.TableName}}', INTERVAL '30 days', if_not_exists => TRUE);
SELECT add_compression_policy('{{.TableName}}', INTERVAL '8 days', if_not_exists => TRUE);
```

We found that the 24 hypertables compression time is almost same time and schedule_interval is "3 days 12:00:00", sometimes some jobs failed, Is it possible that 24 hypertables run compression same time IO high load caused job error?

If we should set hypertables compression policy time and retention policy time to different time and schedule_interval "1 day"?

If yes, could we set by below way please? Set initial_start to '2000-01-01 00:00:00+00'::TIMESTAMPTZ,  then next_start will be the next day '00:00:00+00'? Thanks
```
SELECT add_compression_policy(
    'cpu_t',
    compress_after => INTERVAL '8 days',
    if_not_exists => TRUE,
    schedule_interval => INTERVAL '1 day',
    initial_start => '2000-01-01 00:00:00+00'::TIMESTAMPTZ
);

SELECT add_retention_policy(
    'cpu_t',
    drop_after => INTERVAL '30 days',
    if_not_exists => TRUE,
    schedule_interval => INTERVAL '1 day',
    initial_start => '2000-01-01 00:30:00+00'::TIMESTAMPTZ
);
```

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.6

### What operating system did you use?

CentOS Linux release 7.9.2009

### What installation method did you use?

RPM

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
N.A
```

### How can we reproduce the bug?

```bash
N.A
```

**Comment by konskov** [comment]
Hi @yinan8128 , it’s very likely that if you saw errors with your jobs it is due to the fact that the scheduler is attempting to launch them all at the same time and it’s a good idea to do as you have thought and schedule them further apart. 

Regarding your other question, yes that is the way to define policies that will run every day at 00:30, or you could also set initial start to the actual time you would like the first run of the job to happen (so using tomorrow’s date would work too)
