### ISSUE TITLE
[Bug]: Delete/Update Compressed HyperTables does not work in 2.11.1 ERROR:  cannot update/delete rows from chunk <chunk_name> as it is compressed 

### ISSUE THREAD

**Issue by aarondglover** [timescale/timescaledb#5985]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

After upgrading to version 2.11.1 I would expect being able to delete or update a row but attempting to do so results in the following error;

```
ERROR:  cannot update/delete rows from chunk "<chunk_name>" as it is compressed 
```

I am running version 2.11.1

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

13.12

### What operating system did you use?

???

### What installation method did you use?

Other

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
[server-name]2023-08-18T11:51:00.572448[postgresql-13][748-1] pid=878284,user=tsdbadmin,db=defaultdb,app=pgAdmin 4 - CONN:8528747,client=x.x.x.x ERROR: cannot update/delete rows from chunk "_hyper_14_81_chunk" as it is compressed
```

### How can we reproduce the bug?

```bash
?
```

**Comment by mkindahl** [comment]
@aarondglover Thank you for the bug report! Unfortunately, you need to use PG14 or later to be able to update compressed rows. In PG13 this is still not possible. It is unfortunate that the documentation does not make this clear, so I will file a request to update the documentation.

**Comment by mkindahl** [comment]
Added docs bug https://github.com/timescale/docs/issues/2639.
