### ISSUE TITLE
[Bug]: Deadlock between drop_chunks and query on hypertable

### ISSUE THREAD

**Issue by antekresic** [timescale/timescaledb#5996]
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Policy

### What happened?

Deadlock occurs when running retention policy (and thus drop_chunks function) and a select which uses a time dimension qualifier. One query gets stuck on dimension_slice tuple lock, other trying to lock the chunk thats being dropped.

### TimescaleDB version affected

main branch

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 22

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
postgres=# select * from test_defaults where time <= now();
ERROR:  deadlock detected
DETAIL:  Process 3016685 waits for ShareLock on transaction 778; blocked by process 3038637.
Process 3038637 waits for AccessExclusiveLock on relation 17157 of database 5; blocked by process 3016685.
HINT:  See server log for query details.
CONTEXT:  while locking tuple (0,1) in relation "dimension_slice"
```

### How can we reproduce the bug?

```bash
Setup:
create extension timescaledb;
CREATE TABLE test_defaults(time timestamptz NOT NULL, device_id int);
SELECT create_hypertable('test_defaults','time');
INSERT INTO test_defaults SELECT '2000-01-01', 1;

First session locks up the chunk:
BEGIN;
lock table _timescaledb_internal._hyper_1_1_chunk ;

Second session runs the select query:
select * from test_defaults where time <= now();

Third session runs drop_chunks:
select drop_chunks('test_defaults', now());

First session rollbacks dropping the lock, chunks get dropped but select ends up deadlocking:
postgres=# select * from test_defaults where time <= now();
ERROR:  deadlock detected
DETAIL:  Process 3048114 waits for ShareLock on transaction 740; blocked by process 3048415.
Process 3048415 waits for AccessExclusiveLock on relation 17104 of database 5; blocked by process 3048114.
HINT:  See server log for query details.
CONTEXT:  while locking tuple (0,1) in relation "dimension_slice"
```

**Comment by nwbb** [comment]
I'm not sure if this helps, but in our setup we are seeing the same deadlock occur even when the `SELECT` is querying chunks `>= now()`, and the chunks being dropped are `< now()` (by a large margin).

The `EXPLAIN` of the `SELECT` demonstrates that the chunks being dropped are indeed being skipped by the SELECT, yet a lock still occurs.

To me, this suggests some underlying process (maybe with the index?) at fault... but I'm just going on a hunch.

**Comment by antekresic** [comment]
This seems to be fixed, closing the issue.

Feel free to reopen if you are still having issues @nwbb
