### ISSUE TITLE
chunk exclusion not working when joining multiple hypertables (constraint_aware_append)

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#602]
There's a bug in constraint_aware_append which fails to exclude chunks when joining two hypertables. When you have a query like below, only chunks of one of the hypertables will be excluded.

```
SELECT * FROM ht1
JOIN ht2 on ht1.id=ht2.id
WHERE ht1.time >= now()::date AND ht2.time >= now()::date
```

The constraint_aware_append is created in constraint_aware_append_plan_create. It passes three parameters in the custom_private field when creating the custom scan node. The second parameter is the append_rel_list: a list of all children of *all* parent tables that are referenced in this query. Thus, this list contains both the children of ht1 as well as ht2.

In ca_append_begin this list is extracted into the local variable append_rel_info. The forboth statement in this function loops over the old_appendplans (which only contains the append plans for one of the hypertables) and over append_rel_info (which contains the children of both hypertables). The forboth statement stops as soon as one of the lists is exhausted, so it will only work properly for one of the hypertables.

I think a solution would be to filter the root->append_rel_list in constraint_aware_append_plan_create before copying it into the custom_private field. Only those children must be in this list that inherit from the hypertable that this node is created for.

**Comment by fvannee** [comment]
I confirmed the following seems to fix the issue, but it's just inlining the list_copy function and changing it to filter for reloid. There's probably a nicer way to fix it.

```
static List *
new_list(NodeTag type)
{
	List	   *new_list;
	ListCell   *new_head;

	new_head = (ListCell *) palloc(sizeof(*new_head));
	new_head->next = NULL;
	/* new_head->data is left undefined! */

	new_list = (List *) palloc(sizeof(*new_list));
	new_list->type = type;
	new_list->length = 1;
	new_list->head = new_head;
	new_list->tail = new_head;

	return new_list;
}

/*
 * Return a shallow copy of the specified list.
 */
List *
list_copy_filter(const List *oldlist, Index relid)
{
	List	   *newlist = NIL;
	ListCell   *newlist_prev = NULL;
	ListCell   *oldlist_cur;
	int length = 0;

	if (oldlist == NIL)
		return NIL;

	oldlist_cur = oldlist->head;
	while (oldlist_cur)
	{
		if (((AppendRelInfo*)lfirst(oldlist_cur))->parent_reloid == relid)
		{
			if (newlist == NIL)
			{
				newlist = new_list(oldlist->type);
				newlist->head->data = oldlist_cur->data;
				newlist_prev = newlist->head;
			}
			else
			{
				ListCell* newlist_cur;

				newlist_cur = (ListCell*) palloc(sizeof(*newlist_cur));
				newlist_cur->data = oldlist_cur->data;
				newlist_prev->next = newlist_cur;

				newlist_prev = newlist_cur;
			}
			length++;
		}
		oldlist_cur = oldlist_cur->next;
	}

	if (newlist == NIL)
		return NIL;

	newlist_prev->next = NULL;
	newlist->tail = newlist_prev;
	newlist->length = length;

	return newlist;
}

static Plan *
constraint_aware_append_plan_create(PlannerInfo *root,
									RelOptInfo *rel,
									struct CustomPath *path,
									List *tlist,
									List *clauses,
									List *custom_plans)
{
	CustomScan *cscan = makeNode(CustomScan);
	Plan	   *subplan = linitial(custom_plans);
	RangeTblEntry *rte = planner_rt_fetch(rel->relid, root);

	cscan->scan.scanrelid = 0;	/* Not a real relation we are scanning */
	cscan->scan.plan.targetlist = tlist;	/* Target list we expect as output */
	cscan->custom_plans = custom_plans;
	cscan->custom_private = list_make3(list_make1_oid(rte->relid),
									   list_copy_filter(root->append_rel_list, rte->relid),
									   list_copy(clauses));
	cscan->custom_scan_tlist = subplan->targetlist; /* Target list of tuples
													 * we expect as input */
	cscan->flags = path->flags;
	cscan->methods = &constraint_aware_append_plan_methods;

	return &cscan->scan.plan;
}
```

**Comment by mfreed** [comment]
Hi @fvannee thanks for the report.  We were aware of this, but appreciate both getting it front-and-center as github issue to remind us, as well as explore the code base.

Will see if we could use that fix.  Thanks again!

**Comment by fvannee** [comment]
No problem, I just try to report issues as detailed as possible whenever I encounter them :)

**Comment by svenklemm** [comment]
@fvannee this should be fixed in recent versions, feel free to reopen if you can reproduce in 1.3.0
