### ISSUE TITLE
[Bug]: Crash on insert and decompress of compressed chunk

### ISSUE THREAD

**Issue by philon123** [timescale/timescaledb#6031]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Compression

### What happened?

Our system started inserting old data into compressed chunks, this caused postgres to segfault. 

After ensuring in application logic that we don't insert old data any more, the error went away. Unfortunately, we weren't able to get a core dump of this error. 

However, we now got another segfault crash, possibly related, while decompressing a chunk. The core dump is uploaded here: https://drive.google.com/u/1/open?id=1HOSQL__8-lTlP-ozoys9bVfACkc6bp2T

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

15.3

### What operating system did you use?

NixOS 23.05

### What installation method did you use?

Other

### What platform did you run on?

Google Cloud Platform (GCP)

### Relevant log output and stack trace

```bash
# original (redacted) error on insert, where I cannot provide a core dump:
Aug 31 08:38:30 hexa-db-prod postgres[71497]: [71497] LOG:  server process (PID 434572) was terminated by signal 11: Segmentation fault
Aug 31 08:38:30 hexa-db-prod postgres[71497]: [71497] DETAIL:  Failed process was running:
Aug 31 08:38:30 hexa-db-prod postgres[71497]:                     INSERT INTO our_ts_table("time", device_id, ...)
) VALUES (...)

# second error on decompression, where core dump is provided
Aug 31 10:23:48 hexa-db-prod postgres[71497]: [71497] LOG:  server process (PID 475729) was terminated by signal 11: Segmentation faultAug 31 10:23:48 hexa-db-prod postgres[71497]: [71497] DETAIL:  Failed process was running: SELECT decompress_chunk('_timescaledb_internal._hyper_889_114959_chunk')
```

### How can we reproduce the bug?

```bash
I'm unable to provide a reproduction for this error just because of time contraint. But can answer follow up questions. I'm just hoping to provide value back to community.
```

**Comment by hostops** [comment]
Same problem here.
Could be linked to this:
https://github.com/timescale/timescaledb/issues/6186

**TimescaleDB version affected**
2.12.1
**image:** 
timescale/timescaledb-ha:pg15.4-ts2.12.1-all
**PostgreSQL version used**
15.4
**What installation method did you use?**
Helm
**What platform did you run on?**
Kubernetes kops
**Relevant log output and stack trace**
```

2023-11-09 12:01:17	app= LOG:  server process (PID 716015) was terminated by signal 11: Segmentation fault
2023-11-09 12:01:17	app= DETAIL:  Failed process was running: DELETE FROM aggregated WHERE id = $1 AND level = $2 AND time >= $3 AND time < $4;
2023-11-09 12:01:17	app= LOG:  terminating any other active server processes
2023-11-09 12:01:17	app= FATAL:  could not receive data from WAL stream: server closed the connection unexpectedly
2023-11-09 12:01:17	This probably means the server terminated abnormally
2023-11-09 12:01:17	before or while processing the request.
2023-11-09 12:01:17	Sourcing /home/postgres/.pgbackrest_environment
2023-11-09 12:01:17	Sourcing /home/postgres/.pgbackrest_environment
2023-11-09 12:01:17	app= LOG:  record with incorrect prev-link A0002A5/CB2C156 at 8A06/B2C09A38
2023-11-09 12:01:17	app=[unknown] FATAL:  the database system is in recovery mode

```

**Comment by mahipv** [comment]
The fix for #6186 is merged and should be available in the next release 2.13.0

**Comment by horzsolt** [comment]
Hi,
TimescaleDB 2.13 released. Can you please upgrade and check if the issue is still happening?

**Comment by philon123** [comment]
I can confirm that 2.13 solves this problem for us. We can insert into compressed chunks as expected with the new version. Thanks.
