### ISSUE TITLE
[Bug]: Unable to install TimescaleDB v2.11.2 on PostgreSQL v13.7 (Could not load library)

### ISSUE THREAD

**Issue by rfonsecaBA** [timescale/timescaledb#6057]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

Good afternoon,

I’m unable to install TimescaleDB Extension on PostgreSQL v13.7.

ERROR: could not load library “C:/Program Files/PostgreSQL/13/lib/timescaledb-2.11.2.dll”: The specified module could not be found.

TimescaleDB Version used: https://github.com/timescale/timescaledb/releases/latest/download/timescaledb-postgresql-13-windows-amd64.zip

PostgreSQL Version used: v13.7

OS Version: Windows Server 2016, 64-bit (based on Windows 10)

Notes:

I’ve been reading through several posts related with this topic, and so far I’ve tried to:

- Move the ssleay32.dll to the PostgreSQL/bin folder
- Move the libeay32.dll to the PostgreSQL/bin folder
- Install POSTGIS v3.3.2
- Restarted the PostgreSQL server
- Move the libcrypto-1_1-x64.dll to the PostgreSQL/lib folder
- Move the libssl-1_1-x64.dll to the PostgreSQL/lib folder

Can you please help?

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

13.7

### What operating system did you use?

Windows Server 2016

### What installation method did you use?

Not applicable

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR: could not load library “C:/Program Files/PostgreSQL/13/lib/timescaledb-2.11.2.dll”: The specified module could not be found.
```

### How can we reproduce the bug?

```bash
Install PostgreSQL v13.7. and attempt to install extension TimescaleDB v2.11.2
```

**Comment by rfonsecaBA** [comment]
DependencyWalker shows me a missing reference to libssl-3-x64.dll and libcrypto-3-x64.dll does this version need OpenSSL v3.0 to be installed? It's not referenced anywhere in the documentation, only that we need OpenSSL v1.1.1

![image](https://github.com/timescale/timescaledb/assets/106754302/508a186d-ec15-4b98-b394-621730eeddc0)

**Comment by rfonsecaBA** [comment]
I've updated the Open SSL library to v3.0. DependencyWalker no longer is showing any issues. However, I'm still unable to update to v2.11.2. I will most likely rollback to a previously supported version of TimescaleDB (v2.5 to v2.9 supported by PostgreSQL v13)

**Comment by jnidzwetzki** [comment]
Hello @rfonsecaBA,

Thanks for getting back to us. It's great to hear that DependencyWalker is not showing any issues anymore. Do you still encounter the same error message when updating? Have you also tried to restart PostgreSQL after you have installed the missing libraries?

**Comment by rfonsecaBA** [comment]
Hi @jnidzwetzki I'm still encountering the same error. Now I'm trying to install Timescale DB v2.8.1 on PostgreSQL, which is also resulting in the same error. Dependency Walker is now showing that PostgreSQL.exe (v13) has some missing imports. Open SSL v1 is installed and all system variables are added to PATH. Can you confirm that v2.8 is compatible with PostgreSQL v13?

**Comment by jnidzwetzki** [comment]
Hello @rfonsecaBA,

TimescaleDB 2.8 is compatible with PostgreSQL 13. You can find an overview of the supported PostgreSQL versions on [this page](https://docs.timescale.com/self-hosted/latest/upgrades/upgrade-pg/).

**Comment by rfonsecaBA** [comment]
@jnidzwetzki I'm still unable to install TimescaleDB v2.8.1 using PostgreSQL v13.

I've made sure the correct C++ Redistributable is installed, and that the OpenSSL v1.1.1 is installed and added to the PATH environment variables.

DependencyWalker is specifying that "PostgreSQL.exe" has some missing imports. Even though the documentation says the PostgreSQL v13 is compliant with TimescaleDB v2.8. Can you please ensure that this is the case?

**Comment by rfonsecaBA** [comment]
I can confirm that timescaledb.dll is looking for specific imports on postgresql v13 that he can't find. Please see the image below.

![image](https://github.com/timescale/timescaledb/assets/106754302/b018b174-6d2d-475f-8de5-9c7088ca2bad)

**Comment by erimatnor** [comment]
@rfonsecaBA It was not possible to reproduce the installation issue when following the [instructions](https://docs.timescale.com/self-hosted/latest/install/installation-windows/) on our docs pages.

For further assistance, I suggest asking for help in our community forum: https://slack.timescale.com/
