### ISSUE TITLE
[Bug]: cleanup_copy_chunk_operation fails on compressed chunks if already attached

### ISSUE THREAD

**Issue by mrksngl** [timescale/timescaledb#6066]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Multi-node

### What happened?

When using `timescaledb_experimental.move_chunk()` on a compressed chunk, it is copied to the destination node in several stages.
However, if stage `attach_compressed_chunk` has successfully been completed, but a later stage fails (currently the only applicable stage is `delete_chunk`), the operation cannot be rolled back using `cleanup_copy_chunk_operation`.

This is because in https://github.com/timescale/timescaledb/blob/ef783c4b559e3a10f1274d0aac46fb995230080a/tsl/src/chunk_copy.c#L627 a `DROP <compressed_chunk_name>` is executed on the destination node.
This is correct as long as the compressed chunk has not been attached yet. After it is attached, it can no longer be dropped like this because compressed chunks must be dropped by dropping their uncompressed counterparts.

Thus, `cleanup_copy_chunk_operation` will fail with a error message from the source data node, saying
```
ERROR:  0A000: dropping compressed chunks not supported
HINT:  Please drop the corresponding chunk on the uncompressed hypertable instead.
LOCATION:  process_drop_chunk, process_utility.c:1239
```

I guess the solution would be to replace the `DROP` by a no-op, _if and only if_ the chunk has already been attached, as the next cleanup (drop the non-compressed chunk using `chunk_api_call_chunk_drop_replica`) will take care.

Besides, I wonder whether it wouldn't be more consistent to first attach the compressed chunk on the data node and then make the chunk available as a replica on the access node's `chunk_data_node`. But then again, I think there is a little window between copying and attaching where inconsistencies could occur anyway (i.e. "what if new data is inserted in exactly this window?"). I might be wrong here, I don't know the deeper interna, especially whether there is some locking.

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

15.4

### What operating system did you use?

Official docker image timescale/timescaledb:latest-pg15

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

It is actually not trivial to trigger the bug.

I could only see it when the source chunk could not be deleted because of #5996, so it was rather by accident since there was a query on the chunk in question exactly when the move operation tried to delete it.

**Comment by jnidzwetzki** [comment]
Hello @mrksngl,

Thanks for reporting this behavior and the detailed description. It seems the `chunk_copy_stage_create_empty_compressed_chunk_cleanup` function is not able to clean up the compressed chunk after `chunk_copy_stage_attach_compressed_chunk` was executed and the compressed chunk was attached to the hypertable.

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
