### ISSUE TITLE
Extension update fails if objects reference first() or last()

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#612]
Because TimescaleDB always redefines aggregates in update scripts with a `DROP` followed by `CREATE`. Since aggregates are dropped, updating the extension can fail when DB objects (e.g., views) depend on aggregates, such as `first` and `last`. 

This issue was first reported by @fmacelw on Slack.
```
ERROR:  cannot drop function first(anyelement,"any") because other objects depend on it
DETAIL:  view my_view depends on function first(anyelement,"any")
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

**Comment by mfreed** [comment]
Hi @fmacelw please let us know if you have any more problems with this issue.

**Comment by fmacelw** [comment]
hi @mfreed I'm happy with the resolution.

Thanks for checking!
