### ISSUE TITLE
[Bug]: refresh_continuous_aggregate loop

### ISSUE THREAD

**Issue by Taokhan** [timescale/timescaledb#6124]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Hello I'm trying to use refresh_continuous_aggregate inside the loop 
```sql
DO
$$
DECLARE
  refresh_interval INTERVAL = '12h'::INTERVAL;
  start_timestamp TIMESTAMPTZ = '2022-01-01T00:00:00Z';
  end_timestamp TIMESTAMPTZ = start_timestamp + refresh_interval;
BEGIN
  WHILE start_timestamp < '2022-05-01T00:00:00Z' LOOP
    CALL refresh_continuous_aggregate('carriers_duration_report', start_timestamp, end_timestamp);
    RAISE NOTICE 'finished with timestamp %', end_timestamp;
    start_timestamp = end_timestamp;
    end_timestamp = end_timestamp + refresh_interval;
  END LOOP;
END
$$;
```
After 1 loop I get error with different parameters I get 2 loops then error or at start of loop

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

14.9

### What operating system did you use?

Linux

### What installation method did you use?

Docker

### What platform did you run on?

Microsoft Azure Cloud, On prem/Self-hosted, Other

### Relevant log output and stack trace

```bash
NOTICE:  finished with timestamp 2022-01-01 12:00:00+00

ERROR:  procedure refresh_continuous_aggregate(unknown, timestamp with time zone, timestamp with time zone) does not exist
LINE 1: CALL refresh_continuous_aggregate('carriers_duration'...
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
QUERY:  CALL refresh_continuous_aggregate('carriers_duration_report', start_timestamp, end_timestamp)
CONTEXT:  PL/pgSQL function inline_code_block line 8 at CALL
SQL state: 42883
```

### How can we reproduce the bug?

```bash
Creating a continuous aggregate and run =>
DO
$$
DECLARE
  refresh_interval INTERVAL = '12h'::INTERVAL;
  start_timestamp TIMESTAMPTZ = '2022-01-01T00:00:00Z';
  end_timestamp TIMESTAMPTZ = start_timestamp + refresh_interval;
BEGIN
  WHILE start_timestamp < '2022-05-01T00:00:00Z' LOOP
    CALL refresh_continuous_aggregate('carriers_duration_report', start_timestamp, end_timestamp);
    RAISE NOTICE 'finished with timestamp %', end_timestamp;
    start_timestamp = end_timestamp;
    end_timestamp = end_timestamp + refresh_interval;
  END LOOP;
END
$$;
```

**Comment by antekresic** [comment]
Hi!

If you add a `COMMIT` statement after the refresh call, it should work. That's due to the visibility rules the refresh procedure is using.

Also, I would suggest to fully qualify the view with the proper schema.

Let me know if that works for you.

**Comment by Taokhan** [comment]
Hi!
It works when add COMMIT 
`DO $$
	DECLARE
		refresh_interval INTERVAL = '1day'::INTERVAL;
		start_timestamp TIMESTAMPTZ = NOW() - INTERVAL '2 hours';
		end_timestamp TIMESTAMPTZ = start_timestamp + refresh_interval;
	BEGIN
	WHILE start_timestamp BETWEEN '2023-01-01' AND NOW()
	LOOP
	CALL refresh_continuous_aggregate('carriers_duration_report', start_timestamp, end_timestamp);
	RAISE NOTICE 'policy refreshed between %, %', start_timestamp, end_timestamp;
    COMMIT;
		start_timestamp = start_timestamp - refresh_interval;
		end_timestamp = end_timestamp - refresh_interval;
	END LOOP;
	END $$;`
	Can you guys update docs at site for further problems
	https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/
