### ISSUE TITLE
[Bug]: alter table set compression is not idempotent

### ISSUE THREAD

**Issue by patstrom** [timescale/timescaledb#6137]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Compression

### What happened?

I am executing a query like so

```sql
ALTER TABLE lifecycle_event SET (timescaledb.compress, timescaledb.compress_segmentby = 'gateway_id');
``` 

and the first execution is fine. If I execute it again I get an error

```
psycopg2.errors.FeatureNotSupported: cannot change configuration on already compressed chunks
DETAIL:  There are compressed chunks that prevent changing the existing compression configuration.
```

It's the exact same query twice, so I don't know why it claims I am changing the configuration.

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 22.04 amd64 for host and timescaledb:2.12.0-pg15 tag

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
CREATE TABLE IF NOT EXISTS test (time timestamptz not null, segment_id int, value varchar);
SELECT create_hypertable('test', 'time', if_not_exists => true, chunk_time_interval => INTERVAL '1 DAY');
ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'segment_id');
SELECT add_compression_policy('test', INTERVAL '1d', if_not_exists => true);

INSERT INTO test(time, segment_id, value) values ('2023-09-02 12:00:00.000+00', 2, 'value');
SELECT show_chunks('test', older_than => INTERVAL '1 days');
SELECT compress_chunk('_timescaledb_internal._hyper_2_1_chunk');

ALTER TABLE test SET (timescaledb.compress, timescaledb.compress_segmentby = 'segment_id');
```

**Comment by antekresic** [comment]
Hi,

We block changing of compression settings when there are compressed chunks in the hypertable. This is because we have to have all chunks compressed in the same way in order to preserve system consistency. Even though you are not changing your settings here, we still block the operation.

This might change in the future but for now, that's how the system works.

Hope that makes sense.

**Comment by svenklemm** [comment]
We could add a check here if the new parameter value is equal to current configuration and not error in that case.

**Comment by patstrom** [comment]
> We could add a check here if the new parameter value is equal to current configuration and not error in that case.

Such a check would be perfect for me!

**Comment by fabriziomello** [comment]
@patstrom Closing it because on the upcoming 2.14.0 release you'll be able to set compression settings per chunk, so it means you can will be able to change compression settings any time you want and then the next chunks will use the new settings.
