### ISSUE TITLE
[Bug]: Continuous Aggregate -- Error [XX000]: ERROR: child rel 1 not found in append_rel_array

### ISSUE THREAD

**Issue by webbegole-mr** [timescale/timescaledb#6141]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Continuous aggregate

### The problem
When I'm querying a continuous aggregate with `materialized_only=false` I get 
`Error [XX000]: ERROR: child rel 1 not found in append_rel_array`

The problem goes away if I set it to materialized only.... 

And I think it has to do with the time index and the timescaledb watermark 

### Digging into it

I have a compressed hypertable like so:
````
CREATE TABLE data.market_data (
	time_utc timestamptz NOT NULL,
	entity_id int4 NOT NULL,
	price numeric NULL,
	volume numeric NULL DEFAULT 0
);
SELECT create_hypertable('data.market_data', 'time_utc', chunk_time_interval=>'1 week', if_not_exists => TRUE);
ALTER TABLE data.market_data SET (timescaledb.compress, timescaledb.compress_orderby = 'time_utc DESC', timescaledb.compress_segmentby = 'entity_id');
SELECT add_compression_policy('data.market_data', INTERVAL '4 weeks');
````

I have created a continuous aggregate like below:

```
CREATE MATERIALIZED VIEW data.ohlcv_1min WITH (timescaledb.continuous, timescaledb.materialized_only=false) AS (
	SELECT entity_id
		, time_bucket('1 minute', time_utc) as time_utc
		, candlestick_agg(time_utc, price, coalesce(volume,0)) as ohlcv_agg
		, candlestick_agg(time_utc, price, coalesce(trades,0)) as ohlct_agg
	FROM data.market_data
	GROUP BY 1,2
);
```

When I query the data like this:
`SELECT * FROM marketreader_calc.ohlcv_10min_minute `
I get this error:
`SQL Error [XX000]: ERROR: child rel 1 not found in append_rel_array`

To dissect the problem I look at the continuous aggregate view definition:
```
CREATE OR REPLACE VIEW data.ohlcv_1min
AS SELECT _materialized_hypertable_175.entity_id,
    _materialized_hypertable_175.time_utc,
    _materialized_hypertable_175.ohlcv_agg,
    _materialized_hypertable_175.ohlct_agg,
   FROM _timescaledb_internal._materialized_hypertable_175
  WHERE _materialized_hypertable_175.time_utc < COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(175)), '-infinity'::timestamp with time zone)
UNION ALL
 SELECT market_data.entity_id,
    time_bucket('00:01:00'::interval, market_data.time_utc) AS time_utc,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.volume, 0::numeric)::double precision) AS ohlcv_agg,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.trades, 0::numeric)::double precision) AS ohlct_agg
   FROM data.market_data
  WHERE market_data.time_utc >= COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(175)), '-infinity'::timestamp with time zone)
  GROUP BY market_data.entity_id, (time_bucket('00:01:00'::interval, market_data.time_utc));
```

If I take just the top part of the view:
```
SELECT _materialized_hypertable_175.entity_id,
    _materialized_hypertable_175.time_utc,
    _materialized_hypertable_175.ohlcv_agg,
    _materialized_hypertable_175.ohlct_agg,
   FROM _timescaledb_internal._materialized_hypertable_175
  WHERE _materialized_hypertable_175.time_utc < COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(175)), '-infinity'::timestamp with time zone)
```
The query runs without any issues!

### The interesting bit
But if I try the bottom part:
```
 SELECT market_data.entity_id,
    time_bucket('00:01:00'::interval, market_data.time_utc) AS time_utc,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.volume, 0::numeric)::double precision) AS ohlcv_agg,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.trades, 0::numeric)::double precision) AS ohlct_agg
   FROM data.market_data
  WHERE market_data.time_utc >= COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(175)), '-infinity'::timestamp with time zone)
  GROUP BY market_data.entity_id, (time_bucket('00:01:00'::interval, market_data.time_utc));
  ```
  I get the error: `SQL Error [XX000]: ERROR: child rel 1 not found in append_rel_array`
  
  But if I make a change:
  ```
 SELECT market_data.entity_id,
    time_bucket('00:01:00'::interval, market_data.time_utc) AS time_utc,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.volume, 0::numeric)::double precision) AS ohlcv_agg,
    candlestick_agg(market_data.time_utc, market_data.price::double precision, COALESCE(market_data.trades, 0::numeric)::double precision) AS ohlct_agg
   FROM data.market_data
  WHERE market_data.time_utc >= NOW() - interval '10 minutes'
  GROUP BY market_data.entity_id, (time_bucket('00:01:00'::interval, market_data.time_utc));
  ```
  It works fine!
  
  I can even do `WHERE market_data.time_utc >= '2023-08-01'` and it's fine...
  
  And if I run 
  `SELECT COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(175)), '-infinity'::timestamp with time zone)` I get `2023-10-02 18:58:00.000 -0400` which is fine....
  
  
  ### Conclusion
  So I'm very boggled... I know that this WHERE clause for the time index is the issue specifically... and that it only has a problem when I try to use the watermarked timestamp... but I can't figure out what the difference is between that and a normal timestamp like NOW()
  
  Hopefully this helps the team find the issue!

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 15.4-1.pgdg22.04+1

### What installation method did you use?

Deb/Apt, Source

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
Hopefully the full explanation includes details on that.
```

**Comment by antekresic** [comment]
Hi there.

I was unable to reproduce your issue locally. Would you mind setting the verbosity to verbose and showing the output of the failing query.

You can do it in psql like so:
`\set VERBOSITY verbose`

Thanks!

**Comment by webbegole-mr** [comment]
Welp we tried upgrading to the newest 2.12 and the problem has not returned for now.  So probably something fixed already!

**Comment by webbegole-mr** [comment]
Upgrade seems to have helped!
