### ISSUE TITLE
[Bug]: Installation followed by TimescaleDB documentation is set as Apache 2 Edition, but can compress the table

### ISSUE THREAD

**Issue by igor2x** [timescale/timescaledb#6145]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

1. I was pointed here from the [Timescale forum](https://www.timescale.com/forum/t/installation-problem-one-computer-has-apache-2-extension-and-one-without/2143/3), potentially to be an issue.

2. I have been following installation [Linux instructions on Timescale documentation](https://docs.timescale.com/self-hosted/latest/install/installation-linux/) for self-host and I expected to have Community Edition installed.

3. But in PostgreSQL on my TimescaleDB when I execute:
`\dx`
I get:
```
        Name | Version |   Schema   |                                     Description
-------------+---------+------------+--------------------------------------------------------------------------------------
 timescaledb | 2.12.0  | public     | Enables scalable inserts and complex queries for time-series data (Apache 2 Edition)
```

3. From above it looks like Apache 2 Edition is installed.

4. But following the [bug report 5438](https://github.com/timescale/timescaledb/issues/5438) and [edition comparison documentation](https://docs.timescale.com/about/latest/timescaledb-editions/) compression should not be available in Apache 2 Edition, it should only be available in Community Edition.

5. Lets test "compression":
```
CREATE TABLE public.tab1 (
    time TIMESTAMPTZ NOT NULL,
    location TEXT NOT NULL,
    temperature DOUBLE PRECISION NULL,
    humidity DOUBLE PRECISION NULL
);

SELECT create_hypertable('public.tab1', 'time');

ALTER TABLE public.tab1 SET (timescaledb.compress);
```

and output of above commands is:

```
tsdb=# CREATE TABLE public.tab1 (
tsdb(#     time TIMESTAMPTZ NOT NULL,
tsdb(#     location TEXT NOT NULL,
tsdb(#     temperature DOUBLE PRECISION NULL,
tsdb(#     humidity DOUBLE PRECISION NULL
tsdb(# );
CREATE TABLE
tsdb=#
tsdb=# SELECT create_hypertable('public.tab1', 'time');
 create_hypertable
-------------------
 (8,public,tab1,t)
(1 row)

tsdb=#
tsdb=# ALTER TABLE public.tab1 SET (timescaledb.compress);
ALTER TABLE
```

ALTER TABLE command does not fail, like it should if this is Apache 2 Edition. Now I am wondering: Do I really have Apache 2 Edition installed?

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

15.4

### What operating system did you use?

Red Hat 8.8

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
See instructions in "What happened" section above.
```

**Comment by raulk89** [comment]
How can I be sure that I have timescaledb community edition installed..?
I just installed it, version 2.11.2 for postgresql 15
And I have the same issue, from extension table, it shows Apache 2 Edtition

I mean, where can I even download the community edtion ?

Raul

**Comment by jonatas** [comment]
Looking the code it seems that the packages it seems packagecloud distributes for both oss and tsl:

https://github.com/timescale/timescaledb/blob/6e796878d7ac5a8117c3deca1979e2ffdad06fa9/.github/workflows/apt-packages.yaml#L25

**Comment by raulk89** [comment]
You are specifying apt-packages.yml file. Is it same for rhel8 as well ?
I have RHEL8 distribution (Rocky 8 Linux)

Raul

**Comment by igor2x** [comment]
@jonatas, thanks for digging into code.

Is it possible to look into my first post? I installed TimescaleDB on self-host following official documentation. Looking into extension information with` \dx` command it is displayed "Apache 2" license and I can compress the table. According to license documentation this does not make sense to me.

One of the following is true:
- I have actually Community edition installed, but there is wrong label of Apache 2 license displayed in \dx
- There are errors in documentation and with Apache 2 license you can also create a table compression.
- As always possible, I've done something incorrectly and/or I just don't understand this license assignment.

**Comment by jonatas** [comment]
AFAIU, It's not a problem at your end. It seems like a bug in the building system.

**Comment by igor2x** [comment]
Quick update. I retested:
- Red Hat 8.9
- PostgreSQL v15.5
- TimescaleDB 2.13.0

I did the test from my first post (create table and compress it), but `\dx` command still displays "Apache 2 Edition", despite I can compress the table and installed TimescaleDB from official repo:
```
                                               List of installed extensions
    Name     | Version |   Schema   |                                     Description
-------------+---------+------------+--------------------------------------------------------------------------------------
 timescaledb | 2.13.0  | public     | Enables scalable inserts and complex queries for time-series data (Apache 2 Edition)
```

**Comment by svenklemm** [comment]
You can get the community version of timescaledb from https://packagecloud.io/app/timescale/timescaledb. Instructions for installation on linux are available here: https://docs.timescale.com/self-hosted/latest/install/installation-linux/.

If you initially install apache version and later swap it out with community version the description shown by \dx will not be updated

**Comment by igor2x** [comment]
@svenklemm, see my first post. I fresh installed Timescale and `\dx` displays it is Apache version, but I can do the table compression which is only available in Community Edition.

Don't know why was this issue closed down. Steps to reproduce a problem should be simple to follow from my first post.

**Comment by posuch** [comment]
what about the older versions - like 

https://packagecloud.io/timescale/timescaledb/packages/el/8/timescaledb-2-postgresql-15-2.14.2-0.el8.x86_64.rpm?distro_version_id=205

thanks

**Comment by svenklemm** [comment]
This is the relevant PR: #7201
