### ISSUE TITLE
[Bug]: Unable to create extension timescaledb

### ISSUE THREAD

**Issue by nidhin077** [timescale/timescaledb#6208]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

Following the [instructions](https://github.com/timescale/timescaledb/blob/main/docs/BuildSource.md), I installed the timescaledb on an ubuntu machine and added the entry to the Postgres.conf file. However, when I try to create the extension, I encounter a problem. The error message is attached below. Please have a look and let me know how to resolve the same.

```

FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /etc/postgresql/13/main/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /etc/postgresql/13/main/postgresql.conf 

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
	SET timescaledb.allow_install_without_preload = 'on';
SSL connection has been closed unexpectedly
The connection to the server was lost. Attempting reset: Succeeded.
psql (16.0 (Ubuntu 16.0-1.pgdg22.04+1), server 13.12 (Ubuntu 13.12-1.pgdg22.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
```

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

13

### What operating system did you use?

Ubuntu 20.04

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /etc/postgresql/13/main/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /etc/postgresql/13/main/postgresql.conf 

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
	SET timescaledb.allow_install_without_preload = 'on';
SSL connection has been closed unexpectedly
The connection to the server was lost. Attempting reset: Succeeded.
psql (16.0 (Ubuntu 16.0-1.pgdg22.04+1), server 13.12 (Ubuntu 13.12-1.pgdg22.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
```

### How can we reproduce the bug?

```bash
Try to install the same on a Ubuntu 20.04 machine with Postgres 13.
```

**Comment by konskov** [comment]
hi @nidhin077 , thanks for reaching out. I haven’t tried to reproduce the issue yet, but I wanted to ask if there is a specific reason you are using older versions? Have you tried with the latest supported version (currently pg15) and if so did you again get the error?

**Comment by nidhin077** [comment]
Hi @konskov 
Actually, the process of upgrading to 16 is currently underway.  However, we need to evaluate Timescaledb on postgres-13. So, please offer a solution for the same.

**Comment by fabriziomello** [comment]
@nidhin077 I guess what Konstantina said is not just related to the Postgres version but the TimescaleDB version. Seems you're trying to use an ancient version ([2.5.0 - almost two years old](https://github.com/timescale/timescaledb/releases/tag/2.5.0)). So why don't use more recent releases? https://github.com/timescale/timescaledb/releases

**Comment by fabriziomello** [comment]
Ahh now I see, the building instructions is pointing to the 2.5.0 (pretty old). Can u try the instructions changing the 2.5.0 to 2.12.1 ?

**Comment by nidhin077** [comment]
Hi @fabriziomello 

I tried the most recent version and got the same error. I'm not sure why it says the library is not loaded even if the entry has already been added to the postgres.conf file.

**Comment by mkindahl** [comment]
Hi @nidhin077!

It is not very clear what error message you're referring to. There is only one mentioned that this is the one that tells you to add the error message to the config file. I'm doing this on a regular basis also did this before 2.5.0 and PG13, so there is probably something wrong with your configuration file(s). Either you're not editing the correct file, or the auto file takes precedence, or you have a typo.

Can you check the output of `show config_file` to make sure that you're editing the correct config file, and also check the contents of the directory of the config file (e.g., using `ls`). Here is my output:

```bash
mats@fury:~$ psql -tqc 'show config_file'
 /home/mats/.local/var/lib/postgresql/15/postgresql.conf

mats@fury:~$ ls $(dirname $(psql -tqc 'show config_file'))
base    pg_commit_ts  pg_hba.conf    pg_logical    pg_notify    pg_serial     pg_stat      pg_subtrans  pg_twophase  pg_wal   postgresql.auto.conf  postmaster.opts
global  pg_dynshmem   pg_ident.conf  pg_multixact  pg_replslot  pg_snapshots  pg_stat_tmp  pg_tblspc    PG_VERSION   pg_xact  postgresql.conf       postmaster.pid
mats@fury:~$ cat $(dirname $(psql -tqc 'show config_file'))/postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
```

As you can see, there is a file `postgresql.auto.conf` which can contain overriding parameters, so make sure to check that.

**Comment by nidhin077** [comment]
Hi, I did as you instructed, and the result is attached here for your review. The world looks to be in order. I couldn't understand what the problem was. 

![image](https://github.com/timescale/timescaledb/assets/107123789/91ddda08-09e3-4849-8077-666dd9997750)

![image](https://github.com/timescale/timescaledb/assets/107123789/e079f7b5-f917-4153-9b08-262cdcf1d172)

**Comment by mkindahl** [comment]
@nidhin077 Sorry, but this is something that is impossible to debug without access to your computer. All developers at Timescale are doing this on a regular basis. If you still have issues with this I suggest that you reach out on the forum or slack available on https://www.timescale.com/community.
