### ISSUE TITLE
[Bug]: timescaledb-ha image : Password does not match for user "standby"

### ISSUE THREAD

**Issue by yspassivelogic** [timescale/timescaledb#6213]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Backup, Replication

### What happened?

We are using the timescale/timescaledb-ha:pg14.9-ts2.11.2-all image ane we are experiencing issues with the master node, timescaledb-0 replicated data into timescaledb-1 replica.

We keep seeing this error below
This issue is recent - we hadn't see this issue before when we deployed 1 month ago.

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.9

### What operating system did you use?

Ubuntu 22.04.3 LTS

### What installation method did you use?

Docker

### What platform did you run on?

Google Cloud Platform (GCP)

### Relevant log output and stack trace

```bash
2023-10-10 16:15:57 UTC [161610]: [652578bd.2774a-3] standby@[unknown],app=[unknown] [28P01] DETAIL:  Password does not match for user "standby".
2023-10-10 16:16:02 UTC [161620]: [652578c2.27754-2] standby@[unknown],app=[unknown] [28P01] FATAL:  password authentication failed for user "standby"
2023-10-10 16:16:02 UTC [161620]: [652578c2.27754-3] standby@[unknown],app=[unknown] [28P01] DETAIL:  Password does not match for user "standby".
Connection matched pg_hba.conf line 8: "hostssl   replication     standby            all                md5"
```
```


### How can we reproduce the bug?

```bash
Run timescale/timescaledb-ha:pg14.9-ts2.11.2-all on docker desktop
```

**Comment by konskov** [comment]
hi @yspassivelogic, is this the same issue as https://github.com/timescale/timescaledb/issues/6184?

**Comment by yspassivelogic** [comment]
yes @konskov - i got no response from timescaledb helm charts- https://github.com/timescale/helm-charts/issues/625

**Comment by fabriziomello** [comment]
@yspassivelogic re-creating here this unrelated issue will not help you. 

As I said to you in the previous issue here is not the right place for this kind of issue. I strongly recommend you:
1) wait more time for someone help you, 
2) send a follow-up message on the already opened issue in the timescaledb/helm-charts repo or 
3) ask for help in other channels like slack or forum.
