### ISSUE TITLE
[Bug]: After Hypertable compression is set, two chunks with basically the same amount of data have a significant difference in size before and after compression.

### ISSUE THREAD

**Issue by majun9129** [timescale/timescaledb#6233]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

# basic info
### compress policy: 
ALTER TABLE TABLE_NAME SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'tag_id',
    timescaledb.compress_orderby = 'time DESC'
    );

SELECT add_compression_policy('TABLE_NAME', INTERVAL '365 days');
-----
I used the compression configuration above to compress the data table. After all the data was compressed, I used the following statement to query the data size comparison before and after compression:

select t1.chunk_name,t2.range_start, t2.range_end,
pg_size_pretty(t1.before_compression_total_bytes) as before_total ,
pg_size_pretty(t1.after_compression_total_bytes) as after_total
from chunk_compression_stats('TABLE_NAME') t1 
inner join timescaledb_information.chunks t2 
on t1.chunk_name = t2.chunk_name order by t2.range_start asc;

get this reulst:

chunk_name	     		range_start						range_end					before_total	       after_total
_hyper_1437_24065_chunk	2020-03-09 08:00:00.000 +0800	2020-04-08 08:00:00.000 +0800	7757 MB			211 MB
_hyper_1437_24064_chunk	2020-04-08 08:00:00.000 +0800	2020-05-08 08:00:00.000 +0800	7754 MB			211 MB
_hyper_1437_24063_chunk	2020-05-08 08:00:00.000 +0800	2020-06-07 08:00:00.000 +0800	7718 MB			210 MB
_hyper_1437_24062_chunk	2020-06-07 08:00:00.000 +0800	2020-07-07 08:00:00.000 +0800	7765 MB			212 MB
_hyper_1437_24061_chunk	2020-07-07 08:00:00.000 +0800	2020-08-06 08:00:00.000 +0800	9554 MB			294 MB
_hyper_1437_24060_chunk	2020-08-06 08:00:00.000 +0800	2020-09-05 08:00:00.000 +0800	8800 MB			266 MB
_hyper_1437_24059_chunk	2020-09-05 08:00:00.000 +0800	2020-10-05 08:00:00.000 +0800	10 GB			296 MB
_hyper_1437_24058_chunk	2020-10-05 08:00:00.000 +0800	2020-11-04 08:00:00.000 +0800	10 GB			299 MB
_hyper_1437_24057_chunk	2020-11-04 08:00:00.000 +0800	2020-12-04 08:00:00.000 +0800	11 GB			298 MB
_hyper_1437_24085_chunk	2020-12-04 08:00:00.000 +0800	2021-01-03 08:00:00.000 +0800	19 GB			288 MB
_hyper_1437_24084_chunk	2021-01-03 08:00:00.000 +0800	2021-02-02 08:00:00.000 +0800	18 GB			328 MB
_hyper_1437_25418_chunk	2021-02-02 08:00:00.000 +0800	2021-03-04 08:00:00.000 +0800	12 GB			734 MB
_hyper_1437_27677_chunk	2021-03-04 08:00:00.000 +0800	2021-04-03 08:00:00.000 +0800	12 GB			700 MB
_hyper_1437_32383_chunk	2021-04-03 08:00:00.000 +0800	2021-05-03 08:00:00.000 +0800	12 GB			653 MB
_hyper_1437_44251_chunk	2021-05-03 08:00:00.000 +0800	2021-06-02 08:00:00.000 +0800	17 GB			662 MB
_hyper_1437_45508_chunk	2021-06-02 08:00:00.000 +0800	2021-07-02 08:00:00.000 +0800	23 GB			824 MB
_hyper_1437_47472_chunk	2021-07-02 08:00:00.000 +0800	2021-08-01 08:00:00.000 +0800	14 GB			1042 MB
_hyper_1437_49099_chunk	2021-08-01 08:00:00.000 +0800	2021-08-31 08:00:00.000 +0800	21 GB			1556 MB
_hyper_1437_50877_chunk	2021-08-31 08:00:00.000 +0800	2021-09-30 08:00:00.000 +0800	21 GB			1569 MB
_hyper_1437_52889_chunk	2021-09-30 08:00:00.000 +0800	2021-10-30 08:00:00.000 +0800	21 GB			1587 MB
_hyper_1437_55273_chunk	2021-10-30 08:00:00.000 +0800	2021-11-29 08:00:00.000 +0800	21 GB			1585 MB
_hyper_1437_57150_chunk	2021-11-29 08:00:00.000 +0800	2021-12-29 08:00:00.000 +0800	22 GB			1600 MB
_hyper_1437_59348_chunk	2021-12-29 08:00:00.000 +0800	2022-01-28 08:00:00.000 +0800	19 GB			1611 MB

_ Hyper_ 1437_ 24084_ The pre compressed size of the chunk is 18GB, and the compressed size is 328MB, which is the next chunk_ Hyper_ 1437_ 25418_ The size before chunk compression is 12GB, and after compression, it reaches 734MB.

I searched the data of these two chunks and found that they were in the data entry and tag_id, There is not much difference in the amount of data for the ID, but the size difference between before and after compression is significant. Why is this?

The same problem also exists in subsequent chunks.

Why is there such a gap?

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

12.6

### What operating system did you use?

Debian 10

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
### compress policy: 
ALTER TABLE TABLE_NAME SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'tag_id',
    timescaledb.compress_orderby = 'time DESC'
    );

SELECT add_compression_policy('TABLE_NAME', INTERVAL '365 days');
```

**Comment by mkindahl** [comment]
> I searched the data of these two chunks and found that they were in the data entry and tag_id, There is not much difference in the amount of data for the ID, but the size difference between before and after compression is significant. Why is this?

Compression is affected by a number of factors and segment-by and order-by are two of them. Depending on the order of values in columns, you could get different compression rates. You could have a look at the [compression section in the documentation](https://docs.timescale.com/use-timescale/latest/compression/about-compression/) to see what factors affect compression rate.
