### ISSUE TITLE
Please add support for timescaledb features into pgAdmin

### ISSUE THREAD

**Issue by ecerichter** [timescale/timescaledb#6244]
### What problem does the new feature solve?

To have a GUI to administrate TimescaleDB

### What does the feature do?

Integrate the ability to administrate TimescaleDB in the most commonly supported GUI for PostgreSQL.
The most important features are:
- Being able to identify which tables are Hypertables
- See timescale statistics in proper statistics tab
- Being able to adjust hypertable parameters (or, at least, view them).

### Implementation challenges

Would require a fork of pgAdmin project if they don't accepts a patch.

**Comment by fabriziomello** [comment]
@ecerichter thanks for reaching out. 

We're not responsible for the pgAdmin development so such kind of feature request should be redirected to https://github.com/pgadmin-org/pgadmin4.

**Comment by ecerichter** [comment]
Thanks for your prompt answer.
The team até pgAdmin gave me the same answer. So, as far as I could understand none of the teams will support each other.
Thanks anyway.
