### ISSUE TITLE
[Bug]: jobs for (realtime) continuous aggregates are started somewhat haphazardly

### ISSUE THREAD

**Issue by johanatan** [timescale/timescaledb#6257]
### What type of bug is this?

Other

### What subsystems and features are affected?

Continuous aggregate

### What happened?

It seems that jobs for aggregates are started at seemingly random offsets into "buckets". This has the undesired effect of resulting in "real time" data that is older than one has tried to configure for. The software should rather intelligently start jobs as soon as possible after a "current bucket" begins, in order to start filling the next to last bucket as soon as possible.

See the following supporting data from my live system (it was taken at a few seconds after 19:16, which is when the smallest granularity aggregate (5 minute) started running):

```
options=# select total_runs,last_run_started_at,last_run_duration from timescaledb_information.job_stats where job_id >= 1039;
 total_runs |      last_run_started_at      | last_run_duration 
------------+-------------------------------+-------------------
        149 | 2023-10-31 19:16:58.894786+00 | 
         51 | 2023-10-31 18:57:26.477408+00 | 00:06:40.913332
         14 | 2023-10-31 18:39:18.00181+00  | 00:25:01.973704
          1 | 2023-10-31 04:59:43.229763+00 | 00:00:00.076045
(4 rows)

options=# select max(bucket) from quote_five_minutes;
          max           
------------------------
 2023-10-31 19:00:00+00
(1 row)

options=# select max(bucket) from quote_fifteen_minutes;
          max           
------------------------
 2023-10-31 18:15:00+00
(1 row)

options=# select max(bucket) from quote_one_hour;
          max           
------------------------
 2023-10-31 16:00:00+00
(1 row)

options=# select max(bucket) from quote_one_day;
          max           
------------------------
 2023-10-30 00:00:00+00
(1 row)
```

The other granularities are: 15-minute, 1-hour and 1-day.

The 1-hour job doesn't start until the x:49th minute of every hour (which is obviously less than ideal), for example. 

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

16

### What operating system did you use?

Docker image

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted, Other

### Relevant log output and stack trace

```bash
N/A
```

### How can we reproduce the bug?

```bash
Description says it all. Just create some caggs and attach some refresh policies to them (at some random time).
```

**Comment by mkindahl** [comment]
@johanatan Thank you for the bug report! It looks like what you're experiencing is because the default behavior for a job is to run at a regular pace compared to the end of the previous run, which creates a "drifting" execution. We introduced "fixed schedules" for this purpose, so you might want to try to use that feature. See the `fixed_schedule` parameter in the [add_job](https://docs.timescale.com/api/latest/actions/add_job/) documentation.
