### ISSUE TITLE
[Bug]: Issue with default index size in hypertable

### ISSUE THREAD

**Issue by semabtariq1** [timescale/timescaledb#6258]
### What type of bug is this?

Performance issue, Other

### What subsystems and features are affected?

Data ingestion

### What happened?

Q) What causes the initial index size 23 GB in the Regular PostgreSQL table) to expand to 41 GB in the hypertable? Is there a bloat in hypertable index because when we run REINDEX it size was reduced to 23 GB(Same as original PostgreSQL index)

NOTE: 
- We are following this blog for our benchmark: https://blog.coelho.net/database/2019/09/13/postgresql-vs-timescaledb-data-loading-performance.html
- Github Repo: https://github.com/zx80/pg-ts-tests/tree/master

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

### Relevant log output and stack trace

```bash
Regular PostgreSQL stats
- Table size: 87 GB
- Index size: 23 GB

HyperTable stats:
- Table size: 87 GB
- Index size: 41 GB
```

### How can we reproduce the bug?

```bash
Generate data for Regular PostgreSQL table
- Create a regular table
  Command: psql -v width=5 -f create_table.sql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/create_table.sql

- Create an index on PostgreSQL table(Similar to default hypertable index)
  Command: psql -v index2=false -f create_index.sql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/create_index.sql

- Insert initial 1.1 billion rows
  Command: ./fill.pl --batches 110000 --rows 10000 | psql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/fill.pl

Generate data for hypertable
- Create a regular table
  Command: psql -v width=5 -f create_table.sql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/create_table.sql

- Convert the above-created table to hypertable
  Command: psql -v index2=false -f create_hyper.sql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/create_hyper.sql

- Insert initial 1.1 billion rows
  Command: ./fill.pl --batches 110000 --rows 10000 | psql -p 5432
  File: https://github.com/zx80/pg-ts-tests/blob/master/fill.pl

NOTE: Please run the tests individually. As te above scripts create table with the same name(Conditions)
```

**Comment by svenklemm** [comment]
The index definitions are not the same, the plain postgres table has the index defined on `time` while the hypertable has the index defined as `time DESC`.

**Comment by svenklemm** [comment]
Can you reproduce the result when the index definitions are exactly the same?

**Comment by svenklemm** [comment]
When adjust the index definitions, the index size is the same after the fill script has been run.

Here is the diff i used for the scripts:
```
diff --git create_hyper.sql create_hyper.sql
index 208476d..c969cc8 100644
--- create_hyper.sql
+++ create_hyper.sql
@@ -7,7 +7,9 @@ CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
 -- This creates a hypertable that is partitioned by time
 --   using the values in the `time` column.

-SELECT create_hypertable('conditions', 'time');
+SELECT create_hypertable('conditions', 'time', create_default_indexes:=false);
+
+CREATE INDEX conditions_time_idx ON conditions(time);

 -- and possibly throw in another index
 \if :index2

```

**Comment by nikkhils** [comment]
@semabtariq1 can you please confirm that the sizes are the same after using the exact same index definition? Please close this issue in that case.
