### ISSUE TITLE
[Bug]: compress_chunk_time_interval merges uncompressed chunks 

### ISSUE THREAD

**Issue by DmitriiAn** [timescale/timescaledb#6260]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression, Partitioning

### What happened?

The `timescaledb.compress_chunk_time_interval` compression parameter alters not only compressed but also underlying uncompressed chunks. According to[ this doc](https://docs.timescale.com/api/latest/compression/alter_table_compression/#alter-table-compression) this feature must affect compressed chunks only.  

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 15.4-2.pgdg22.04+1

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

1. Create a hypertable and insert data in it 

```
drop table if exists cpu_raw cascade;

create table if not exists cpu_raw(
	timestamp timestamptz,
	device_id text,
	cpu_usage double precision,
	value_1 double precision,
	value_2 double precision
);
SELECT create_hypertable('cpu_raw', 'timestamp', chunk_time_interval => INTERVAL '1 day');

INSERT INTO cpu_raw(timestamp, device_id, cpu_usage,value_1,value_2)
values (generate_series('2022-01-01 00:00:00','2022-02-01 00:00:00',INTERVAL '1 minute'), repeat('device_id_2. ', 1), random()*100 ,random()*100 , random()*100);
```    
3. Check how many uncompressed chunks we get  
```
SELECT count(*) from timescaledb_information.chunks
where hypertable_name ='cpu_raw'; --> 32 
```  
4. Enable compression and check stats before actually compressing chunks  
```
ALTER TABLE cpu_raw SET (timescaledb.compress=true, timescaledb.compress_chunk_time_interval = '7 days'); 

SELECT * FROM hypertable_compression_stats('cpu_raw'); --> 32 total_chunks / 0 compressed_chunks
``` 
5. Compress all the chunks and check the stats
```
SELECT compress_chunk(i, if_not_compressed => true)
FROM show_chunks('cpu_raw', older_than => now()) i;

SELECT * FROM hypertable_compression_stats('cpu_raw'); --> 5 total_chunks / 5 compressed_chunks
```

We can see that the number of chunks has decreased from 32 to 5

6. Uncompress all the chunks
```
SELECT decompress_chunk(i, true)
FROM show_chunks('cpu_raw', older_than => now()) i;

SELECT * FROM hypertable_compression_stats('cpu_raw'); --> 5 total_chunks / 0 compressed_chunks
```

Even after uncompressing the whole table, we still have 5 chunks, which means this process is irreversible.
```

**Comment by antekresic** [comment]
I've updated the docs page to make it more clear that this will irreversibly create larger chunks by merging them together. 

Hope that helps with the confusion.
