### ISSUE TITLE
[Enhancement]: improve recompression speed & change the behaviour

### ISSUE THREAD

**Issue by Tindarid** [timescale/timescaledb#6267]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Compression

### What does the enhancement do?

Hi!

Any chance, something similar from this PR will be implemented in the future?
https://github.com/timescale/timescaledb/pull/5867

I have a table with segments (1 column) and a lot of chunks (years of data, > 10TB uncompressed). I need to add new data to existing time ranges, Everything related to the new data does not overlap with existing segments (for example: table which is segmented by device_id and we add a new unique device_id).

What I observe from *recompression*:
1) While recompressing the data we try to decompress the existing data and add new rows to already existing segments. In this scenario, nothing happens -> we just decompress and then compress the same.
2) Then we add new segments -> this should be fast, as we just compress new piece of data, which is relatively small if we compare with existing dataset (let's say we had hundreds of device_ids and add only additional 1)
3) During the operation, SELECTs on the affected time range (1 chunk) are blocked
4) After the operation, I need to REINDEX existing index (because after recompression indexes are dropped and it consists only of dead tuples), VACUUM FULL on compressed/previously uncompressed chunk versions (because after recreating the tables -> dead tuples exist).

How this can be improved (happy path):
1) If there are any *affected* segments -> fallback to the slow path
2) If not: compress new data and add new rows to the compressed version of the chunk.

I think this implementation will achieve higher throughput for recompression and also will avoid different possible locks (as we just add new rows to compressed chunk, old rows are not affected)

#### Summary
At the moment, adding new unique segment to hypertable and compressing the associated data afterwards involves __recompression of all data__ in the given hypertable and running maintaince jobs afterwards (VACUUM)

**Comment by antekresic** [comment]
This was implemented in #6351
Should land in our next minor release 2.14

Thanks for requesting!
