### ISSUE TITLE
[Bug]: Some tags are not available in the timescaledev Docker Hub organization

### ISSUE THREAD

**Issue by artursmolarek** [timescale/timescaledb#6268]
### What type of bug is this?

Other

### What subsystems and features are affected?

Multi-node

### What happened?

The TimescaleDB [official docker image](https://hub.docker.com/r/timescale/timescaledb-ha/tags) does not support ARM. To work around this limitation, we are using a [non-production image](https://hub.docker.com/r/timescaledev/timescaledb-ha) for local development and testing purposes, as it is compatible with ARM and it works on our Macs.

Recently, we upgraded our production environment to [pg14.9-ts2.12.2-all,](https://hub.docker.com/layers/timescale/timescaledb-ha/pg14.9-ts2.12.2/images/sha256-1cba4fc02f2c599f5a671fcd32400ca7dee45620335562998c7f5ee9039a1a0d?context=explore) and we attempted to do the same for our local environment, but we could not find the corresponding development image in the registry. We are wondering if this is an expected behavior, and if we should anticipate that some tags from the production Docker Hub organization may not be available in the non-production registry?

It works with no issues for 2.12.1.

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

14.9

### What operating system did you use?

ARM

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

2.12.2:

```bash
docker pull --platform linux/amd64 timescale/timescaledb-ha:pg14.9-ts2.12.2
pg14.9-ts2.12.2: Pulling from timescale/timescaledb-ha
540ff674800e: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:558444314a81f2fc6d2e6c45f257db2542608a10ce6bbbe1d1231ead3fce8394
Status: Downloaded newer image for timescale/timescaledb-ha:pg14.9-ts2.12.2
docker.io/timescale/timescaledb-ha:pg14.9-ts2.12.2

docker pull timescaledev/timescaledb-ha:pg14.9-ts2.12.2
Error response from daemon: manifest for timescaledev/timescaledb-ha:pg14.9-ts2.12.2 not found: manifest unknown: manifest unknown
```

2.12.1:

```
docker pull --platform linux/amd64 timescale/timescaledb-ha:pg14.9-ts2.12.1
pg14.9-ts2.12.1: Pulling from timescale/timescaledb-ha
7c7ac89657ab: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:b52dfec0c7bb63344beb1952a56d8285a583fa6f4e377c808b7c58c6e42887b2
Status: Downloaded newer image for timescale/timescaledb-ha:pg14.9-ts2.12.1
docker.io/timescale/timescaledb-ha:pg14.9-ts2.12.1

docker pull timescaledev/timescaledb-ha:pg14.9-ts2.12.1
pg14.9-ts2.12.1: Pulling from timescaledev/timescaledb-ha
f9a1c4fd423f: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:69762ec924799c98def87b234c85770daeb90477885f6822e8588d389355ca03
Status: Downloaded newer image for timescaledev/timescaledb-ha:pg14.9-ts2.12.1
docker.io/timescaledev/timescaledb-ha:pg14.9-ts2.12.1
```
```

**Comment by akuzm** [comment]
Looks like you're using a wrong tag, I used the one from the dockerhub page and it worked, can you please try it?

```
$ docker pull --platform linux/arm64 timescaledev/timescaledb-ha:pg14.9-ts2.12.2-all
pg14.9-ts2.12.2-all: Pulling from timescaledev/timescaledb-ha
6a385f1911fa: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:67928af42ee32df81d63ad1c0033cb480c681f3218c4efbaf826f5176c197231
Status: Downloaded newer image for timescaledev/timescaledb-ha:pg14.9-ts2.12.2-all
docker.io/timescaledev/timescaledb-ha:pg14.9-ts2.12.2-all
```

**Comment by akuzm** [comment]
This one seems to be correct: https://hub.docker.com/layers/timescaledev/timescaledb-ha/pg14.9-ts2.12.2-all/images/sha256-4c05bdada26fdae4972aceb9b720844b42d18cc2614e1791d212e65a4719bbbf?context=explore

**Comment by artursmolarek** [comment]
It was added three days ago after I created this issue. The question remains - is it expected, that there is discrepancy between the `timescaledev` and `timescale`?

**Comment by graveland** [comment]
It is expected. The dev repo is for non-released development work and is built from non-master branches from this repository and isn't even kept up to date in a best-effort sort of way.

**Comment by richturner** [comment]
Have you considered using your own runner and connecting it to GH?
