### ISSUE TITLE
Performance and scalability with mutable data?

### ISSUE THREAD

**Issue by shahthepro** [timescale/timescaledb#627]
Hi,

I have a table with following columns.

    a: timestamp
    b: string (cardinality = ~200)
    c: string (cardinality = ~10)
    d: numeric
    e: numeric
    f: boolean
    g: numeric
    h: boolean

The dataset will be time-partitioned based on column 'a' and space-partitioned based on columns 'f', 'c' and 'b'.

The first 6 columns are immutable, they will never be updated. However the last two columns, 'g' and 'h', will be updated few times after the data has been inserted into the database. There is no need to index these columns. 

Will there be any performance drops when updating the non-indexed columns? What will happen if I update a row such that the space-partitioned column changes? Will the row be moved to the new space-partition?

I can find benchmarks for INSERT, SELECT and drop_chunks. What about UPDATE?

**Comment by AndyMender** [comment]
What I typically do in such a case is:
```postgresql
INSERT INTO hypertable
VALUES ()
ON CONFLICT DO UPDATE
SET column = EXCLUDED.column
```
Is that how you envision the `UPDATE` statements for this table? Posting the full table schema might be helpful here as well.

**Comment by mfreed** [comment]
The performance implications of these UPDATEs are really based on the memory pressure you are currently seeing, as well as how "old" the partitions are that you are updating.  If they are still fairly recent and still in memory, no problem.   Or in fact there are only a few such elements (disk pages) that need to be updated, or your workload itself doesn't find huge memory pressure, it should have a more limited effect.  On the other hand, if these UPDATES are frequent enough and randomly distributed over all your data, such that are you swapping in new disk pages on each update, then you are going to see performance degradations proportional to your disk IOPS.

As per your last question, we currently return an error if you UPDATE a row that changes its partitioning key in a way that it no longer satisfies its current constraint.  The current workaround is to catch such errors and then transactionally DELETE and (re)INSERT the row.

**Comment by mfreed** [comment]
Probably not, given its likely implications on query performance.  I would stick with the first simpler data model and do some performance testing to determine it if satisfies your requirements.

**Comment by mfreed** [comment]
Anything else or should I close this issue out?
