### ISSUE TITLE
[Bug]: CREATE OR REPLACE TRIGGER on hypertable leads to error

### ISSUE THREAD

**Issue by adrian-gierakowski** [timescale/timescaledb#6319]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

given a hypertable calling: `CREATE OR REPLACE TRIGGER ...` on it twice, leads to error on the second run:

```
trigger "my_trigger_name" for relation "_hyper_1_1_chunk" already exists
```

### TimescaleDB version affected

2.11.0

### PostgreSQL version used

14.9

### What operating system did you use?

unknown (running on managed.timescale.com)

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```bash
create a hypertable

create a trigger on that table with `CREATE OR REPLACE TRIGGER...`
run the trigger creation query again
```

**Comment by fabriziomello** [comment]
@adrian-gierakowski this issue was already fixed by PR #6001 and was already release together with 2.12.0, so I recommend you update your tsdb installation to 2.12.2 (https://github.com/timescale/timescaledb/releases/).

Here is the complete example I've used to check that it work on 2.12.2 and not work on 2.11.2:
```sql
CREATE TABLE metrics(time timestamptz NOT NULL, device_id int, value float);
SELECT create_hypertable('metrics', 'time');

INSERT INTO metrics (time, device_id, value)
SELECT t, s, 1 FROM generate_series('2023-01-09 00:00:00'::timestamptz, '2023-11-09 00:00:00'::timestamptz + interval '1 day', '1 hour') t CROSS JOIN generate_series(1, 10, 1) s;

CREATE FUNCTION trigger_test() RETURNS TRIGGER
AS
$$
BEGIN
  RAISE INFO 'trigger';
  RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_test
  BEFORE INSERT ON metrics
  FOR EACH ROW EXECUTE FUNCTION trigger_test();
```

**Comment by adrian-gierakowski** [comment]
@fabriziomello thank you! I'm using a managed instance on Timescale Cloud so I am not sure I can upgrade myself. I will get in touch with support.

**Comment by adrian-gierakowski** [comment]
Just to confirm: error went away after the upgrade
