### ISSUE TITLE
`pg_isolation_regress` tests wishlist.

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb#632]
After #629 we will have more ability to test the behavior of concurrent transactions. This issue exists to maintain a wishlist of tests to be added.

- [x] #622 test concurrent `create_hypertable`s, they should block _unless_ the hypertable existed before any of the create_hypertables started, in which case they should all proceed.
- [x] #158 Concurrent COPY commands blocking, also an analogous issue with INSERT. We need a minimal test-case for this.

**Comment by NunoFilipeSantos** [comment]
@JLockerman this issues looks done to me.
Please close it.
