### ISSUE TITLE
[Enhancement]: Optimization plan when with using a ‘computed’ timestamp

### ISSUE THREAD

**Issue by loicwinkopp** [timescale/timescaledb#6328]
### What type of enhancement is this?

Performance

### What subsystems and features will be improved?

Query executor, Query planner

### What does the enhancement do?

It seems an improvement can be done in the optimization plan when using a ‘computed’ timestamp

I have an issue with using a ‘computed’ timestamp filter in my query :
If I do that :
```
SELECT activity_id, timestamp
FROM activity_logs
WHERE timestamp > to_timestamp(1699942429.586)
LIMIT 10 ;
```
Then I use the results I have to write this query :
```
SELECT *
FROM activities
WHERE
  (id = '1a9c2bf7-0a80-4ed3-98a6-b01f90e053bb' AND timestamp = '2023-11-14 10:14:53.621+00') OR
  (id = '8415a876-4dd4-4f20-a90e-4f91e8b39b97' AND timestamp = '2023-11-14 10:14:52.125+00') OR [...];
```
The second query uses the timestamp index and this is fast.
But if I run any of these, no one uses the timestamp index and they have to seq scan all the chunks, so this is very slow
```
SELECT *                          
FROM activities a
WHERE (a.id, a.timestamp) IN (
  SELECT                                                               
    activity_id AS id,                                                      
    timestamp
  FROM
    activity_logs
  WHERE timestamp > to_timestamp(1699942429.586)
  LIMIT 10
);
```
```
SELECT a.*
FROM activities a
INNER JOIN (                                                          
  SELECT  
    activity_id, timestamp
  FROM           
    activity_logs
  WHERE timestamp > to_timestamp(1699942429.586)
  LIMIT 10
) as al
ON a.id = al.activity_id
AND a.timestamp = al.timestamp;
```
```
WITH filtered_activity_logs AS (
    SELECT activity_id AS id, timestamp 
    FROM activity_logs
    WHERE timestamp > to_timestamp(1699942429.586)
    LIMIT 10
)
SELECT * 
FROM activities a
WHERE (a.id, a.timestamp) IN (SELECT id, timestamp FROM filtered_activity_logs);
```
So I have to do 2 queries in my backend service for it to be fast

**Comment by nikkhils** [comment]
@loicwinkopp
can you please share the output of below:

```sql
EXPLAIN VERBOSE SELECT activity_id, timestamp
FROM activity_logs
WHERE timestamp > to_timestamp(1699942429.586)
LIMIT 10 ;
```

I don't think this is a problem of constification of the `to_timestamp`. It looks like Postgres thinks that there are a lot of distinct values for this timestamp column and hence a sequential scan will be better.

**Comment by loicwinkopp** [comment]
Sure
`                        QUERY PLAN                                                                                                                                                                                                                                                                                                      
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.05..0.18 rows=10 width=24)
   Output: _hyper_26_407_chunk.activity_id, _hyper_26_407_chunk."timestamp"
   ->  Append  (cost=0.05..54829.23 rows=4245583 width=24)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_407_chunk  (cost=0.05..9.78 rows=204000 width=24)
               Output: _hyper_26_407_chunk.activity_id, _hyper_26_407_chunk."timestamp"
               Filter: (_hyper_26_407_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_427_chunk  (cost=0.00..9.78 rows=204 width=84)
                     Output: compress_hyper_32_427_chunk.activity_id, compress_hyper_32_427_chunk.tenant, compress_hyper_32_427_chunk.environment, compress_hyper_32_427_chunk.tracker_key, compress_hyper_32_427_chunk.level, compress_hyper_32_427_chunk.issue_type, compress_hyper_32_427_chunk.message, compress_hyper_32_427_chunk.action, compress_hyper_32_427_chunk.item_type, compress_hyper_32_427_chunk."timestamp", compress_hyper_32_427_chunk._ts_meta_count, compress_hyper_32_427_chunk._ts_meta_sequence_num, compress_hyper_32_427_chunk._ts_meta_min_1, compress_hyper_32_427_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_427_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_415_chunk  (cost=0.04..14.40 rows=352000 width=24)
               Output: _hyper_26_415_chunk.activity_id, _hyper_26_415_chunk."timestamp"
               Filter: (_hyper_26_415_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_437_chunk  (cost=0.00..14.40 rows=352 width=84)
                     Output: compress_hyper_32_437_chunk.activity_id, compress_hyper_32_437_chunk.tenant, compress_hyper_32_437_chunk.environment, compress_hyper_32_437_chunk.tracker_key, compress_hyper_32_437_chunk.level, compress_hyper_32_437_chunk.issue_type, compress_hyper_32_437_chunk.message, compress_hyper_32_437_chunk.action, compress_hyper_32_437_chunk.item_type, compress_hyper_32_437_chunk."timestamp", compress_hyper_32_437_chunk._ts_meta_count, compress_hyper_32_437_chunk._ts_meta_sequence_num, compress_hyper_32_437_chunk._ts_meta_min_1, compress_hyper_32_437_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_437_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_426_chunk  (cost=0.04..15.91 rows=393000 width=24)
               Output: _hyper_26_426_chunk.activity_id, _hyper_26_426_chunk."timestamp"
               Filter: (_hyper_26_426_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_447_chunk  (cost=0.00..15.91 rows=393 width=84)
                     Output: compress_hyper_32_447_chunk.activity_id, compress_hyper_32_447_chunk.tenant, compress_hyper_32_447_chunk.environment, compress_hyper_32_447_chunk.tracker_key, compress_hyper_32_447_chunk.level, compress_hyper_32_447_chunk.issue_type, compress_hyper_32_447_chunk.message, compress_hyper_32_447_chunk.action, compress_hyper_32_447_chunk.item_type, compress_hyper_32_447_chunk."timestamp", compress_hyper_32_447_chunk._ts_meta_count, compress_hyper_32_447_chunk._ts_meta_sequence_num, compress_hyper_32_447_chunk._ts_meta_min_1, compress_hyper_32_447_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_447_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_435_chunk  (cost=0.04..34.50 rows=840000 width=24)
               Output: _hyper_26_435_chunk.activity_id, _hyper_26_435_chunk."timestamp"
               Filter: (_hyper_26_435_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_461_chunk  (cost=0.00..34.50 rows=840 width=84)
                     Output: compress_hyper_32_461_chunk.activity_id, compress_hyper_32_461_chunk.tenant, compress_hyper_32_461_chunk.environment, compress_hyper_32_461_chunk.tracker_key, compress_hyper_32_461_chunk.level, compress_hyper_32_461_chunk.issue_type, compress_hyper_32_461_chunk.message, compress_hyper_32_461_chunk.action, compress_hyper_32_461_chunk.item_type, compress_hyper_32_461_chunk."timestamp", compress_hyper_32_461_chunk._ts_meta_count, compress_hyper_32_461_chunk._ts_meta_sequence_num, compress_hyper_32_461_chunk._ts_meta_min_1, compress_hyper_32_461_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_461_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_445_chunk  (cost=0.04..23.07 rows=566000 width=24)
               Output: _hyper_26_445_chunk.activity_id, _hyper_26_445_chunk."timestamp"
               Filter: (_hyper_26_445_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_472_chunk  (cost=0.00..23.07 rows=566 width=84)
                     Output: compress_hyper_32_472_chunk.activity_id, compress_hyper_32_472_chunk.tenant, compress_hyper_32_472_chunk.environment, compress_hyper_32_472_chunk.tracker_key, compress_hyper_32_472_chunk.level, compress_hyper_32_472_chunk.issue_type, compress_hyper_32_472_chunk.message, compress_hyper_32_472_chunk.action, compress_hyper_32_472_chunk.item_type, compress_hyper_32_472_chunk."timestamp", compress_hyper_32_472_chunk._ts_meta_count, compress_hyper_32_472_chunk._ts_meta_sequence_num, compress_hyper_32_472_chunk._ts_meta_min_1, compress_hyper_32_472_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_472_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_26_456_chunk  (cost=0.04..26.10 rows=648000 width=24)
               Output: _hyper_26_456_chunk.activity_id, _hyper_26_456_chunk."timestamp"
               Filter: (_hyper_26_456_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
               ->  Seq Scan on _timescaledb_internal.compress_hyper_32_485_chunk  (cost=0.00..26.10 rows=648 width=84)
                     Output: compress_hyper_32_485_chunk.activity_id, compress_hyper_32_485_chunk.tenant, compress_hyper_32_485_chunk.environment, compress_hyper_32_485_chunk.tracker_key, compress_hyper_32_485_chunk.level, compress_hyper_32_485_chunk.issue_type, compress_hyper_32_485_chunk.message, compress_hyper_32_485_chunk.action, compress_hyper_32_485_chunk.item_type, compress_hyper_32_485_chunk."timestamp", compress_hyper_32_485_chunk._ts_meta_count, compress_hyper_32_485_chunk._ts_meta_sequence_num, compress_hyper_32_485_chunk._ts_meta_min_1, compress_hyper_32_485_chunk._ts_meta_max_1
                     Filter: (compress_hyper_32_485_chunk._ts_meta_max_1 > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Index Only Scan using _hyper_26_470_chunk_activity_logs_activity_id_timestamp_idx on _timescaledb_internal._hyper_26_470_chunk  (cost=0.42..21571.77 rows=835957 width=24)
               Output: _hyper_26_470_chunk.activity_id, _hyper_26_470_chunk."timestamp"
               Index Cond: (_hyper_26_470_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
         ->  Index Only Scan using _hyper_26_483_chunk_activity_logs_activity_id_timestamp_idx on _timescaledb_internal._hyper_26_483_chunk  (cost=0.42..11905.78 rows=406626 width=24)
               Output: _hyper_26_483_chunk.activity_id, _hyper_26_483_chunk."timestamp"
               Index Cond: (_hyper_26_483_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
 Query Identifier: -1918877590146894443
(46 rows)

`

**Comment by nikkhils** [comment]
@loicwinkopp as you can see from the output

```
Filter: (_hyper_26_407_chunk."timestamp" > '2023-11-14 06:13:49.586+00'::timestamp with time zone)
```

So, the timestamp is proper enough. 

Also, it's using `Index Only Scans` on regular chunks. I can also see some compressed chunks involved in the query above. Decompression will definitely slow things down for queries.

**Comment by nikkhils** [comment]
@loicwinkopp maybe we should close this since the timestamp is good enough?

**Comment by nikkhils** [comment]
Closing this since the enhancement request is already happening in the code. Please open another request if deemed necessary.
