### ISSUE TITLE
[Bug]: CREATE EXTENSION doesnt seem to work

### ISSUE THREAD

**Issue by fredleeflang** [timescale/timescaledb#6333]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

I installed version  2.12:

rpm -qa|grep timescale
timescaledb-tools-0.15.0-0.el8.x86_64
timescaledb_15-2.12.2-1PGDG.rhel8.x86_64

On postgres 15:

rpm -qa|grep postgres
postgresql15-contrib-15.5-2PGDG.rhel8.x86_64
postgresql15-libs-15.5-2PGDG.rhel8.x86_64
postgresql15-server-15.5-2PGDG.rhel8.x86_64
postgresql15-15.5-2PGDG.rhel8.x86_64

After connecting and creating a database:

-bash-4.4$ psql
psql (15.5)
Type "help" for help.

postgres=# \c timescale
You are now connected to database "timescale" as user "postgres".
timescale=# CREATE EXTENSION IF NOT EXISTS timescaledb
timescale-# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

15.5

### What operating system did you use?

RHEL8

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Not sure. I tried turning the debug level of Postgres to maximum but don't see any mention in the log
```

**Comment by mahipv** [comment]
Hi, 
In the snippet above, looking at the prompt `timescale-# \dx`, it looks like the previous statement of `CREATE EXTENSION ..` is not terminated (with ';') and hence the extension is not created.

Can you please let us know if the extension creation always fails?

**Comment by fredleeflang** [comment]
That was too easy, my apologies it was indeed just the missing semicolon.

**Comment by mahipv** [comment]
No Worries.
