### ISSUE TITLE
[Bug]: Chunk Constraint Add failed If there's a default_tablespace and a DEFERABLE CONSTRAINT

### ISSUE THREAD

**Issue by lyp-bobi** [timescale/timescaledb#6338]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

What I do:
1. create a default tablespace other than pg_default
2. run the constraint-14.sql regress

What I get:
ERROR : syntax error at or near "USING" at character 180
QUERY: ALTER TABLE _timescaledb_internal._hyper_2_4_chunk ADD CONSTRAINT "4_4_hyper_unique_with_looooooooooooooooooooooo_time" UNIQUE ("time") DEFERABLE INITALLY DEFERRED USING INDEX TABLESPACE space

What I think is the problem:
Accordding to PG's document https://www.postgresql.org/docs/current/sql-altertable.html , the format should be  
```
[ CONSTRAINT constraint_name ]
{ NOT NULL |
  NULL |
  CHECK ( expression ) [ NO INHERIT ] |
  DEFAULT default_expr |
  GENERATED ALWAYS AS ( generation_expr ) STORED |
  GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ] |
  UNIQUE [ NULLS [ NOT ] DISTINCT ] index_parameters |
  PRIMARY KEY index_parameters |
  REFERENCES reftable [ ( refcolumn ) ] [ MATCH FULL | MATCH PARTIAL | MATCH SIMPLE ]
    [ ON DELETE referential_action ] [ ON UPDATE referential_action ] }
[ DEFERRABLE | NOT DEFERRABLE ] [ INITIALLY DEFERRED | INITIALLY IMMEDIATE ]
```
i.e., it should be ALTER TABLE xxx UNIQUE ("time") USING INDEX TABLESPACE space DEFERABLE INITALLY DEFERRED, however, the order is wrong in timescaledb.

When I review the code, it shows that in `_timescaledb_internal.chunk_constraint_add_table_constraint`, it use 
```
SELECT T.spcname INTO indx_tablespace
          FROM pg_constraint C, pg_class I, pg_tablespace T
          WHERE C.oid = constraint_oid AND C.contype IN ('p', 'u') AND I.oid = C.conindid AND I.reltablespace = T.oid;

          def := pg_get_constraintdef(constraint_oid);

          IF indx_tablespace IS NOT NULL THEN
            def := format('%s USING INDEX TABLESPACE %I', def, indx_tablespace);
          END IF;
```
Thus, the `USING INDEX TABLESPACE`  will come after the `DEFERABLE`.

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

14.3

### What operating system did you use?

Centos 7

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
please refer to the what happened part.
```

**Comment by nikkhils** [comment]
@lyp-bobi thanks for the report. I can confirm that this is indeed a problem. Will get back.
