### ISSUE TITLE
[Bug]: time_bucket_gapfill with timezones doesn't handle daylight savings

### ISSUE THREAD

**Issue by JerkoNikolic** [timescale/timescaledb#6344]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

When `time_bucket_gapfill` with the optional timezone argument is used on a period which includes a switch between normal and daylight savings time, the gapfill starts in one mode (DST or not) and stays in it for the remainder of gapfills. 
i.e. for the query
```
SELECT
    time_bucket_gapfill('1 month', "timestamp", 'Europe/Berlin','2023-05-01 05:00:00.000', '2023-12-01 05:00:00.000') AS bucket,
    avg(speed) AS value,
    "guid"
FROM
    "events"
WHERE
    "guid" = '8412b80...'
    AND "timestamp" >= '2023-05-01 05:00:00.000'
    AND "timestamp" <= '2023-12-01 05:00:00.000'
GROUP BY
    "guid", "bucket"
ORDER BY
    "bucket" ASC;
```
We can see three issues manifest in the result bellow:

1. Since the bucket size is one month, the buckets are to start at midnight of the `Europe/Berlin` timezone which is 23:00 of the previous day by UTC time. The first three buckets are correct, but the April bucket should have DST applied and thus start at 22:00 like the last three results in the first image.
2. The gapfill continues beyond the buckets which have data and have no need for gapfilling as can be seen in the highlighted results in the first image. This may be due to the bucket timestamps being misaligned by one hour and thus not equal.
3. The duplicate buckets break sorting as can be in the last nine buckets. This happens despite the query clearly having an ORDER BY clause. If an additional order by value is added, the buckets get properly sorted.

![image](https://github.com/timescale/timescaledb/assets/31212245/fa69f262-aaed-4b02-8421-270cf7901929)

To confirm that the gapfill ignores DST and just always uses the same bucket hours, we can change the lower `timestamp` limit to May and get all gapfilled buckets starting at 22:00. We also get the same sorting and duplicate problems as before, but now the gapfilled dates are wrong as well and are all set to the 30th of the month.

![image](https://github.com/timescale/timescaledb/assets/31212245/575584f7-aa6e-433c-b3b2-928ff337cb5b)

The expected behavior would be for the gapfill bucket times to follow the same logic as the normal `time_bucket` buckets and have daylight savings offsets applied to them. I believe this would then solve the issue of multiple buckets for the same bucket period (in this case month), though I'm not sure why the sorting gets broken.

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

13.12

### What operating system did you use?

WSL Ubuntu 18.04 LTS x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
1. Create or have a table with a timestamp column and a value column to aggregate over.
2. Have at least one row in the table that's within the queried period
3. Use a `time_bucket_gapfill` function with timezones in a query over a period which includes a daylight savings switch (2023-03-26 for Europe/Berlin). Bucket can be as little as 1 day to manifest the issue.
```

**Comment by mahipv** [comment]
Hi @JerkoNikolic , Thank you for reaching out. 

Can we know the DB timezone? Just wanted to verify if it is different from  'Europe/Berlin' used for the `time_bucket_gapfill` function.

**Comment by JerkoNikolic** [comment]
Tried it with a UTC zone and Europe/Berlin zone DB setting, both had the same issue

**Comment by mahipv** [comment]
Was able to reproduce the above behaviour when DB timezone is different from the timezone in time_bucket_gapfill().

```
SET timezone='utc';
CREATE TABLE metrics (
    sensor_id INTEGER,
    value DOUBLE PRECISION ,
    timestamp TIMESTAMPTZ,
    CONSTRAINT pk_test PRIMARY KEY (sensor_id, timestamp)
);

INSERT INTO metrics
SELECT
    sensor_id,
    random()*50 + 10,
    timestamp + (INTERVAL '1 second' * random() * 30)
FROM
    generate_series(DATE '2023-06-01', DATE '2023-12-01' - INTERVAL '1 month', INTERVAL '1 month') AS timestamp,
    generate_series(1, 1) AS sensor_id;

SELECT
    time_bucket_gapfill('1 month', "timestamp", 'Europe/Berlin','2023-01-01 00:00:00.000', '2023-12-01 00:00:00.000') AS bucket, 
    avg(value) AS value, sensor_id 
FROM "metrics" 
WHERE  sensor_id = 1 GROUP BY sensor_id, bucket ORDER BY bucket ASC;
```

**Comment by Gray-Wanderer** [comment]
I have the same issue but for `1 day` interval.

**What happened?**

I have simple table `metrics`:
```sql
CREATE TABLE metrics (time TIMESTAMP WITH TIME ZONE, value DOUBLE PRECISION);
```

I have a function `get_day_metric_count` that returns the start of daily intervals with data if it exists. Otherwise the query returns zero for the start of the day:
```sql
CREATE OR REPLACE FUNCTION get_day_metric_count (start TIMESTAMPTZ, finish TIMESTAMPTZ)
RETURNS TABLE (day_bucket TIMESTAMP, val DOUBLE PRECISION)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
    SELECT
      time_bucket_gapfill_query.day_bucket AT TIME ZONE 'Europe/Stockholm' AS day_bucket,
      time_bucket_gapfill_query.val AS val
    FROM (
      SELECT
        time_bucket_gapfill( '1 day', m.time, 'Europe/Stockholm', start, finish) AS day_bucket,
        sum(m.value) as val
      FROM metrics m
      WHERE m.time >= start AND m.time < finish
      GROUP BY day_bucket
    ) AS time_bucket_gapfill_query
    ORDER BY day_bucket;
END;$$;
```

1. Result of a function in an empty table for a "fixed" time zone:
```sql
SELECT * FROM get_day_metric_count(
  '2023-08-27T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm',
  '2023-09-01T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm'
);
```
```
     day_bucket      | val
---------------------+-----
 2023-08-27 00:00:00 |
 2023-08-28 00:00:00 |
 2023-08-29 00:00:00 |
 2023-08-30 00:00:00 |
 2023-08-31 00:00:00 |
(5 rows)
```
In this case, the result is as we expected.
2. The result of the function on an empty table for an interval with daylight saving time:
```sql
SELECT * FROM get_day_metric_count(
  '2023-10-27T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm',
  '2023-11-02T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm'
);
```
```
     day_bucket      | val
---------------------+-----
 2023-10-27 00:00:00 |
 2023-10-28 00:00:00 |
 2023-10-29 00:00:00 |
 2023-10-29 23:00:00 |
 2023-10-30 23:00:00 |
 2023-10-31 23:00:00 |
 2023-11-01 23:00:00 |
(7 rows)
```
In this case, we have 7 rows instead of 6, and after 2023-10-29 all data is shifted by one hour.

3. If we add some data, the result gets worse:
```sql
INSERT INTO metrics
VALUES 
  -- Summer time
  ('2023-10-27T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1),
  ('2023-10-28T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1),
  ('2023-10-29T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1),
  -- Winter time
  ('2023-10-30T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1),
  ('2023-10-31T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1),
  ('2023-11-01T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm', 1);

SELECT * FROM get_day_metric_count(
  '2023-10-27T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm',
  '2023-11-02T00:00:00'::timestamp AT TIME ZONE 'Europe/Stockholm'
);
```
```
     day_bucket      | val
---------------------+-----
 2023-10-27 00:00:00 |   1
 2023-10-28 00:00:00 |   1
 2023-10-29 00:00:00 |   1
 2023-10-29 23:00:00 |
 2023-10-30 00:00:00 |   1
 2023-10-30 23:00:00 |
 2023-10-31 00:00:00 |   1
 2023-10-31 23:00:00 |
 2023-11-01 00:00:00 |   1
 2023-11-01 23:00:00 |
(10 rows)
```
We have correct buckets with the correct date, as well as buckets with the wrong date.

**Comment by bufo24** [comment]
i can also confirm this issue
