### ISSUE TITLE
[Bug]: time_bucket_gapfill ERROR when using DISTINCT

### ISSUE THREAD

**Issue by MA-MacDonald** [timescale/timescaledb#6396]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Gapfill

### What happened?

When using `DISTINCT` in a `time_bucket_gapfill` query I receive the following error.

`ERROR:  could not find pathkey item to sort`

### TimescaleDB version affected

2.13.0 

### PostgreSQL version used

16

### What operating system did you use?

Windows 10 Enterprise x64

### What installation method did you use?

Not applicable

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE stocks_real_time (
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  price DOUBLE PRECISION NULL,
  day_volume INT NULL
);

SELECT create_hypertable('stocks_real_time', by_range('time'));

INSERT INTO stocks_real_time
  VALUES
    (NOW(), 's1', 70.0, 50),
    (NOW(), 's2', 66.5, 60),
    (NOW(), 's3', 77.0, 65);

SELECT
  time_bucket_gapfill('1 day', time) AS day,
  COUNT(DISTINCT symbol) AS symbol_count
FROM stocks_real_time
WHERE time > '2023-12-01'
  AND time < '2023-12-10'
GROUP BY 1
ORDER BY 1 DESC
```

**Comment by gayyappan** [comment]
Unable to reproduce on ubuntu with PG15. Need to check with PG16 next.
```
SELECT
  time_bucket_gapfill('1 day', time) AS day,
  count(*), count(symbol), count(distinct symbol)
FROM stocks_real_time
WHERE time > '2023-12-11'
  AND time < '2023-12-15' group by 1;
          day           | count | count | count 
------------------------+-------+-------+-------
 2023-12-10 19:00:00-05 |     3 |     3 |     3
 2023-12-11 19:00:00-05 |       |       |      
 2023-12-12 19:00:00-05 |       |       |      
 2023-12-13 19:00:00-05 |       |       |      
 2023-12-14 19:00:00-05 |       |       |      
(5 rows)

try=# select * from stocks_real_time ;
             time              | symbol | price | day_volume 
-------------------------------+--------+-------+------------
 2023-12-11 10:49:58.368567-05 | s1     |    70 |         50
 2023-12-11 10:49:58.368567-05 | s2     |  66.5 |         60
 2023-12-11 10:49:58.368567-05 | s3     |    77 |         65
(3 rows)

```

**Comment by MA-MacDonald** [comment]
I also confirmed there is no issue with the above query when I run it on PG15 + v2.13.0

I only see the error on my PG16 + v2.13.0 instance.

**Comment by antekresic** [comment]
Managed to reproduce it myself on PG16. I'll let you know if once I have more updates on this.

Thanks for reporting this!

**Comment by antekresic** [comment]
Seems like this is caused by [one of the new optimizations](https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-ENABLE-PRESORTED-AGGREGATE) in PG16.

If you disable it with: `set enable_presorted_aggregate = off;`

Should work as a workaround until we fix this.

**Comment by antekresic** [comment]
I have a PR up for fixing this issue.

Thanks again for reporting!
