### ISSUE TITLE
[Bug]: compression is not compatible with security_barrier views

### ISSUE THREAD

**Issue by adriangb** [timescale/timescaledb#6425]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

I am trying to combine some sort of multi-tenancy and compression.
It's explicitly called out in the docs that RLS can't be used with compression so I tried the other way around: a `security_barrier` view on top of a compressed hypertable.
It seems like when chunks are compressed the permissions get messed up, presumably because applying the view's security_barrier aspect would need to decompress the entire chunk, which is unsafe.
So I'm not sure if this is expected and not documented or unexpected, but I'd like to get any info on what's going wrong, if it's possible to fix or if you have any other suggestions to achieve the same result.

```sql
SET ROLE postgres;
DROP TABLE IF EXISTS conditions CASCADE;
DROP ROLE IF EXISTS tenant1;
DROP ROLE IF EXISTS tenant2;

CREATE TABLE conditions (
   time        TIMESTAMPTZ       NOT NULL,
   data       TEXT              NOT NULL,
   tenant TEXT           NOT NULL
);

SELECT create_hypertable('conditions', by_range('time'));

INSERT INTO conditions(time, data, tenant) VALUES (NOW() - interval '1 year', 'data1', 'tenant1'), (NOW()- interval '1 year', 'data2', 'tenant2');

CREATE VIEW conditions_view WITH (security_barrier) AS SELECT * FROM conditions WHERE tenant = current_user;

CREATE ROLE tenant1;
GRANT USAGE ON SCHEMA public TO tenant1;
GRANT SELECT ON conditions_view TO tenant1;

CREATE ROLE tenant2;
GRANT USAGE ON SCHEMA public TO tenant2;
GRANT SELECT ON conditions_view TO tenant2;

SET ROLE tenant1;
SELECT * FROM conditions_view; -- works, 1 row
SET ROLE postgres;

SET ROLE tenant2;
SELECT * FROM conditions_view; -- works, 1 row
SET ROLE postgres;

ALTER TABLE conditions SET (
  timescaledb.compress
);

-- Compress the chunk
SELECT show_chunks('conditions');
SELECT compress_chunk('_timescaledb_internal._hyper_1_1_chunk');

SET ROLE tenant1;
SELECT * FROM conditions_view; -- permissions error
SET ROLE postgres;

SET ROLE tenant2;
SELECT * FROM conditions_view; -- permissions error
SET ROLE postgres;

GRANT SELECT ON _timescaledb_internal.compress_hyper_2_2_chunk TO tenant1;

SET ROLE tenant1;
SELECT * FROM conditions_view; -- works but unsafe now, see below
SELECT tenant FROM _timescaledb_internal.compress_hyper_2_2_chunk; -- tenant1 can see tenant2's data!
SET ROLE postgres;
```

### TimescaleDB version affected

v2.13.0

### PostgreSQL version used

16

### What operating system did you use?

Ubuntu

### What installation method did you use?

Docker

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
Included above
```

**Comment by svenklemm** [comment]
Thanks for the bug report, while this does work in PG15 it does not work in PG16.

**Comment by adriangb** [comment]
That's surprising! I expected it to not work in any postgres version.

**Comment by svenklemm** [comment]
There were some upstream changes how permission are handled internally. I'll look into it.
