### ISSUE TITLE
Timescale runs out of shared memory when single INSERT creates millions of chunks

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb#644]
The following code

```SQL
CREATE TABLE test_hyper (i bigint, j double precision, k bigint, ts timestamp);
SELECT create_hypertable('test_hyper', 'ts', chunk_time_interval=>interval '1us');
INSERT INTO test_hyper SELECT random()*101, random()*13, x*10, _timescaledb_internal.to_timestamp(x) FROM generate_series(1,100000000) AS x;
```

errors with the message

```
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```

(while this particular scenario is unlikely, a sufficiently large number of inserts should cause the same problem with a more realistic chunk interval)

**Comment by RobAtticus** [comment]
Isn't that making millions of chunks in a single INSERT? Doesn't that seem really unlikely for any realistic chunk interval/insert load?

**Comment by JLockerman** [comment]
Yup, this is a very unrealistic testcase, and as long as the max number of chunks id documented, and high enough, it's probably a WONTFIX.

**Comment by mfreed** [comment]
How is this different than #643 ?
