### ISSUE TITLE
Converting a table that's referenced by a foreign key into a hypertable succeeds but breaks insert into the child table 

### ISSUE THREAD

**Issue by alejandrodnm** [timescale/timescaledb#6452]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Configuration

### What happened?

testing some of the limitation when creating hypertables, just to check some of the error messages. [The docs state](https://docs.timescale.com/use-timescale/latest/limitations/#hypertable-limitations):

> Foreign key constraints referencing a hypertable are not supported.

I tried creating a foreign key to an existing hypertable and it failed as expected. But, creating a hypertable from a table that’s referenced by a foreign key works, you find out that things are broken when you try to insert into the child table and get the `violates foreign key constraint` error.

I'd expect timescale to check if there are foreign key references pointing to the table and fail with an appropriate error message.

Just as a comparison, using PostgreSQL declarative partition allows foreign keys to the table.

```
> CREATE TABLE public.metrics(
     time int,
     device_id int,
     val FLOAT8, unique(time, device_id)) partition by range(time);
> CREATE TABLE metrics_1 PARTITION OF metrics FOR VALUES FROM (0) TO (42);
> create table device (device_id int, time integer, FOREIGN KEY (device_id, time) REFERENCES metrics(device_id, time));
> insert into metrics (time, device_id) values (1, 1);
INSERT 0 1
> insert into device (device_id, time) values (1, 1)
INSERT 0 1
Time: 0.005s
> select * from device join metrics ON metrics.device_id = device.device_id
╒═══════════╤══════╤══════╤═══════════╤════════╕
│ device_id │ time │ time │ device_id │ val    │
╞═══════════╪══════╪══════╪═══════════╪════════╡
│ 1         │ 1    │ 1    │ 1         │ <null> │
╘═══════════╧══════╧══════╧═══════════╧════════╛
> insert into device (device_id, time) values (1, 3)
insert or update on table "device" violates foreign key constraint "device_device_id_time_fkey"
DETAIL:  Key (device_id, time)=(1, 3) is not present in table "metrics".
```

Partitioning using inheritance allows foreign keys, but it has some [caveats](https://www.postgresql.org/docs/current/ddl-inherit.html#DDL-INHERIT-CAVEATS)

People migrating from PostgreSQL native partitioning into timescale's with a similar schema might only discover the issue once they try to write into the child table.

### TimescaleDB version affected

2.14.0

### PostgreSQL version used

16

### What operating system did you use?

Mac OS 14.0 (23A344) ARM

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```
insert or update on table "device" violates foreign key constraint "device_device_id_time_fkey"
DETAIL:  Key (device_id, time)=(1, 1) is not present in table "metrics".
```

### How can we reproduce the bug?

```bash
create extension if not exists timescaledb;
CREATE TABLE public.metrics(
      time int,
      device_id int,
      val FLOAT8, unique(time, device_id));

create table device (device_id int, time integer, FOREIGN KEY (device_id, time) REFERENCES metrics(device_id, time));

select create_hypertable('metrics', by_range('time', 42), create_default_indexes => false);

insert into metrics (time, device_id) values (1, 1);

insert into device (device_id, time) values (1, 1);
```

This will throw:

```
insert or update on table "device" violates foreign key constraint "device_device_id_time_fkey"
DETAIL:  Key (device_id, time)=(1, 1) is not present in table "metrics".
```

**Comment by jnidzwetzki** [comment]
Hello @alejandrodnm,

Thanks for reporting this problem and the excellent steps to reproduce the issue. I was able to reproduce it in my local environment. When the foreign key it added before the table is converted into a hypertable, no error is raised.

However, if the reference is added after the table is converted into a hypertable, the following error is shown:

```
test2=# ALTER TABLE metrics ADD FOREIGN KEY (device_id, time) REFERENCES metrics(device_id, time);
ERROR:  foreign keys to hypertables are not supported
CONTEXT:  SQL statement " ALTER TABLE _timescaledb_internal._hyper_3_122_chunk ADD CONSTRAINT "122_64_metrics_device_id_time_fkey" FOREIGN KEY (device_id, "time") REFERENCES public.metrics(device_id, "time") "
PL/pgSQL function _timescaledb_functions.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 49 at EXECUTE
```
