### ISSUE TITLE
ARM 64 : Image not available or manifest unknown

### ISSUE THREAD

**Issue by mnes-DT** [timescale/timescaledb#6473]
### What type of bug is this?

Other

### What subsystems and features are affected?

Packaging

### What happened?

I am using Raspberry PI 4 with docker to test my application. I can not pull the image for that ARM based Architecture 
![Screenshot 2023-12-26 043225](https://github.com/timescale/timescaledb/assets/140999504/abf683e3-3e81-4922-a7db-077555390715)
![Screenshot 2023-12-26 041852](https://github.com/timescale/timescaledb/assets/140999504/5f3ebaf0-59ae-4ea6-a41d-d2f93622185a)

### TimescaleDB version affected

2.5

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu 21

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
you can check with Images
```

### How can we reproduce the bug?

```bash
Just Pull the image on a ARM 64 Based device
```

**Comment by mahipv** [comment]
Hi @mnes-DT, 
Thank you for getting in touch. 
Can you please try with the tag `latest-pg14`.  I used the following and it was successful.  `docker pull --platform linux/arm64 timescale/timescaledb:latest-pg14`

**Comment by mnes-DT** [comment]
> Member

Thanks its working

**Comment by mnes-DT** [comment]
> Hi @mnes-DT, Thank you for getting in touch. Can you please try with the tag `latest-pg14`. I used the following and it was successful. `docker pull --platform linux/arm64 timescale/timescaledb:latest-pg14`



> Hi @mnes-DT, Thank you for getting in touch. Can you please try with the tag `latest-pg14`. I used the following and it was successful. `docker pull --platform linux/arm64 timescale/timescaledb:latest-pg14`

Thanks its working
