### ISSUE TITLE
Install problem with Postgres 16.1  installed with Postgres app on a Mac

### ISSUE THREAD

**Issue by nicofr83** [timescale/timescaledb#6474]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Other

### What happened?

I installed timescales 2.13.0 with Postgres 16 (installed with Postgres app), and the server do not start. The log is saying:
  2023-12-28 11:58:43.280 CET [4741] FATAL:  could not access file "timescaledb": No such file or directory
  2023-12-28 11:58:43.280 CET [4741] LOG:  database system is shut down

I used the same installation procedure with postgres15 (installed with Postgres app), and the server works well.

Here is the installation script I used:

brew tap timescale/tap
brew install timescaledb

timescaledb-tune --yes --conf-path=/Users/nico/Library/Application\ Support/Postgres/var-16/postgresql.conf

/usr/bin/install -c -m 755 /opt/homebrew/Cellar/timescaledb/2.13.0/lib/timescaledb/postgresql/timescaledb-2.13.0.so  /Applications/Postgres.app/Contents/Versions/16/lib/postgresql/
/usr/bin/install -c -m 755 /opt/homebrew/Cellar/timescaledb/2.13.0/lib/timescaledb/postgresql/timescaledb-tsl-2.13.0.so  /Applications/Postgres.app/Contents/Versions/16/lib/postgresql/
/usr/bin/install -c -m 755 /opt/homebrew/Cellar/timescaledb/2.13.0/lib/timescaledb/postgresql/timescaledb.so  /Applications/Postgres.app/Contents/Versions/16/lib/postgresql/

/usr/bin/install -c -m 644 /opt/homebrew/Cellar/timescaledb/2.13.0/share/timescaledb/* /Applications/Postgres.app/Contents/Versions/16/share/postgresql/extension/

I am running Mac OS 14.2.1, on an M2 Mac studio
Any idea ?

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

16.1

### What operating system did you use?

Mac OS 14.2.1

### What installation method did you use?

Other

### What platform did you run on?

Not applicable

### How can we reproduce the bug?

```bash
Install and run the postgres app on the Mac (https://postgresapp.com)
  I am using Postgres 11 to 16 config.
  start postgres 16

Run the script given in the description

add in Postgres config file: shared_preload_libraries = 'timescaledb'

restart postgres, you should get the problem
```

**Comment by jnidzwetzki** [comment]
Hello @nicofr83,

Thank you for reaching out. The error message `could not access file "timescaledb": No such file or directory` indicates that  PostgreSQL can not find the timescaledb shared library.

There seems to be a problem with your local TimescaleDB build. According to the output you posted, the created TimescaleDB library is suffixed with `.so`. However, for PG 16 the `.dylib` suffix should be used (https://github.com/postgres/postgres/commit/b55f62abb2c2e07dfae99e19a2b3d7ca9e58dc1a) on OS X.

The Homebrew Tap for TimescaleDB is intended to work with the Homebrew version of PostgreSQL. It seems Homebrew detected a wrong PostgreSQL version when the build was configured. So, I recommend deinstalling the Homebrew build, checking that `pg_conf` points to the proper PostgreSQL version, and reinstalling the Homebrew build again. If this does not help, please use the [source installation method](https://docs.timescale.com/self-hosted/latest/install/installation-source/).

**Comment by pauljsymonds** [comment]
I have a similar problem to this, I installed the PostgresApp (brew install postres@16 errors).

Postgres App is awesome on Mac it just works.

I followed your docs [here](https://docs.timescale.com/self-hosted/latest/install/installation-macos/) then to [Install from Source](https://docs.timescale.com/self-hosted/latest/install/installation-source/)

I had to install CMAKE again as a Mac App and set the path etc.  all good to here.

Then....   

```
git checkout 2.14.0  


Note: switching to '2.14.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5ede37005 Release 2.14.0
(base)  timescaledb % ./bootstrap
cmake is required to build TimescaleDB. Please install via your system's preferred method.
(base)  timescaledb % PATH="/Applications/CMake.app/Contents/bin":"$PATH"
(base)  timescaledb % ./bootstrap                                        
-- The C compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 2.14.0. Can be updated from version 2.13.1
-- Build type is Release
-- Install method is 'source'
-- Performing Test CC_SUPPORTS_NO_UNUSED_CLI_ARG
-- Performing Test CC_SUPPORTS_NO_UNUSED_CLI_ARG - Success
-- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION
-- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION - Failed
-- Compiler does not support -Wno-format-truncation
-- Performing Test CC_STRINGOP_TRUNCATION
-- Performing Test CC_STRINGOP_TRUNCATION - Failed
-- Compiler does not support -Wno-stringop-truncation
-- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH
-- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH - Success
-- Performing Test CC_SUPPORTS_NEWLINE_EOF
-- Performing Test CC_SUPPORTS_NEWLINE_EOF - Success
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success
-- Using compiler AppleClang
-- Found Git: /opt/homebrew/bin/git (found version "2.43.1") 
CMake Error at CMakeLists.txt:350 (message):
  TimescaleDB only supports PostgreSQL 13, 14, 15 and 16


-- Configuring incomplete, errors occurred!
```

The issue is that the user may have Anaconda Installed and this defaults to Postgres 12.5 in some instances or another copy of Postgres.

Also you need a good understanding or a lot of googling around $PATH   Apple have modified this and its not straight forwards.

I used the which command found all paths and rm -rf all postgres and anaconda leaving just the PostgresApp.

```
cd build && make 

[100%] Linking C shared module timescaledb-tsl-2.14.0.dylib
ld: warning: -multiply_defined is obsolete
ld: warning: -multiply_defined is obsolete
[100%] Built target timescaledb-tsl
```

BUT......... Failure Apple locks down the App folder.

```
% make install
[  0%] Built target sqlfile
[ 18%] Built target sqlupdatescripts
[ 18%] Built target gitcheck
[ 66%] Built target timescaledb
[ 70%] Built target timescaledb-loader
[100%] Built target timescaledb-tsl
Install the project...
-- Install configuration: "Release"
-- Installing: /Applications/Postgres.app/Contents/Versions/16/share/postgresql/extension/timescaledb.control
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot copy file
  "/Users/home/Development/timescaledb/build/timescaledb.control" to
  "/Applications/Postgres.app/Contents/Versions/16/share/postgresql/extension/timescaledb.control":
  Operation not permitted.


make: *** [install] Error 1
```

Not solved but a better understanding of what is going on.

You need to update your instructions to point to latest 2.14.0 though.

**Comment by nicofr83** [comment]
Thanks a lotNicolasLe 11 févr. 2024 à 06:45, Paul Symonds ***@***.***> a écrit :﻿
I have a similar problem to this, I installed the PostgresApp (brew install ***@***.*** errors).
Postgres App is awesome on Mac it just works.
I followed your docs here then to Install from Source
I had to install CMAKE again as a Mac App and set the path etc.  all good to here.
Then....
git checkout 2.14.0  


Note: switching to '2.14.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5ede37005 Release 2.14.0
(base)  timescaledb % ./bootstrap
cmake is required to build TimescaleDB. Please install via your system's preferred method.
(base)  timescaledb % PATH="/Applications/CMake.app/Contents/bin":"$PATH"
(base)  timescaledb % ./bootstrap                                        
-- The C compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 2.14.0. Can be updated from version 2.13.1
-- Build type is Release
-- Install method is 'source'
-- Performing Test CC_SUPPORTS_NO_UNUSED_CLI_ARG
-- Performing Test CC_SUPPORTS_NO_UNUSED_CLI_ARG - Success
-- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION
-- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION - Failed
-- Compiler does not support -Wno-format-truncation
-- Performing Test CC_STRINGOP_TRUNCATION
-- Performing Test CC_STRINGOP_TRUNCATION - Failed
-- Compiler does not support -Wno-stringop-truncation
-- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH
-- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH - Success
-- Performing Test CC_SUPPORTS_NEWLINE_EOF
-- Performing Test CC_SUPPORTS_NEWLINE_EOF - Success
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success
-- Using compiler AppleClang
-- Found Git: /opt/homebrew/bin/git (found version "2.43.1") 
CMake Error at CMakeLists.txt:350 (message):
  TimescaleDB only supports PostgreSQL 13, 14, 15 and 16


-- Configuring incomplete, errors occurred!

The issue is that the user may have Anaconda Installed and this defaults to Postgres 12.5 in some instances or another copy of Postgres.
Also you need a good understanding or a lot of googling around $PATH   Apple have modified this and its not straight forwards.
I used the which command found all paths and rm -rf all postgres and anaconda leaving just the PostgresApp.
cd build && make 

[100%] Linking C shared module timescaledb-tsl-2.14.0.dylib
ld: warning: -multiply_defined is obsolete
ld: warning: -multiply_defined is obsolete
[100%] Built target timescaledb-tsl

BUT......... Failure Apple locks down the App folder.
% make install
[  0%] Built target sqlfile
[ 18%] Built target sqlupdatescripts
[ 18%] Built target gitcheck
[ 66%] Built target timescaledb
[ 70%] Built target timescaledb-loader
[100%] Built target timescaledb-tsl
Install the project...
-- Install configuration: "Release"
-- Installing: /Applications/Postgres.app/Contents/Versions/16/share/postgresql/extension/timescaledb.control
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot copy file
  "/Users/home/Development/timescaledb/build/timescaledb.control" to
  "/Applications/Postgres.app/Contents/Versions/16/share/postgresql/extension/timescaledb.control":
  Operation not permitted.


make: *** [install] Error 1

Not solved but a better understanding of what is going on.
You need to update your instructions to point to latest 2.14.0 though.

**Comment by akuzm** [comment]
```
CMake Error at CMakeLists.txt:350 (message):
  TimescaleDB only supports PostgreSQL 13, 14, 15 and 16
```

@nicofr83 This log means it's picking the wrong Postgres version again, you have to set proper path to Postgres as mentioned by @pauljsymonds
