### ISSUE TITLE
how to check created hypertable?

### ISSUE THREAD

**Issue by gadian88** [timescale/timescaledb#648]
You have successfully created a hypertable , as per the corresponding document ( https://docs.timescale.com/v0.10/using-timescaledb/hypertables#create) . But I'd like to know how to make sure we've created that hypervisor.

**Comment by amytai** [comment]
Hi there. If you run the following query in psql, `select * from _timescaledb_catalog.hypertable`, then you should see the hypertable that you just created in the result list.

**Comment by lafrech** [comment]
Is this still the way to go?

Looks like this dates back to v0.10. Latest doc recommend `SELECT * FROM timescaledb_information.hypertables;`.

I'm using Timescale 2 and the command here works while the one from the docs doesn't (`timescaledb_information.hypertable` table doesn't exist), so I'm a bit confused.

Related SO question: https://stackoverflow.com/questions/67089109/.

**Comment by solugebefola** [comment]
Yes, the name has changed post v2.0.  It is now `hypertables` instead of `hypertable`

**Comment by lafrech** [comment]
Yes, sorry. Just got an this answered on SO and forgot to comment here.
Thanks.
