### ISSUE TITLE
[Bug]: Triggers for insertions/updates on materialized view in continuous aggregates

### ISSUE THREAD

**Issue by HollowMan6** [timescale/timescaledb#6500]
### What type of bug is this?

Other

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I use the following SQL commands to define triggers on the materialized view for the continuous aggregates so that we can get notified when new data (latest time bucket) in continuous aggregates becomes available.

```sql
CREATE MATERIALIZED VIEW data_aggregate
WITH (timescaledb.continuous) AS
SELECT time_bucket(INTERVAL '30 seconds', timestamp) AS bucket,
   id,
   AVG(reading) AS reading
FROM data
GROUP BY bucket, id;

ALTER MATERIALIZED VIEW data_aggregate set (timescaledb.materialized_only = false);

SELECT add_continuous_aggregate_policy('data_aggregate',
  start_offset => INTERVAL '1 minute',
  end_offset => NULL,
  schedule_interval => INTERVAL '30 seconds');
CREATE OR REPLACE FUNCTION notify_new_data_aggregate()
  RETURNS trigger AS $notify_new_data_aggregate$
BEGIN
  PERFORM pg_notify('usage_aggregate', (NEW.bucket || ',' || NEW.id || ',' || NEW.reading)::text);
  RETURN NEW;
END;
$notify_new_data_aggregate$ LANGUAGE plpgsql;

CREATE TRIGGER data_aggregate_notify_trigger
INSTEAD OF INSERT ON data_aggregate
FOR EACH ROW EXECUTE FUNCTION notify_new_data_aggregate();
```

But I can see the triggers I defined here never get triggered. Did I do something wrong or is it a bug? Thank you!

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

15.5

### What operating system did you use?

MacOS Sonoma 14.3

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
See the SQL commands I provided above.
```

**Comment by jnidzwetzki** [comment]
Hi @HollowMan6,

Thanks for reaching out and for the detailed steps for reproduction. I could reproduce the behavior in my local environment. Triggers on continuous aggregates are not supported in the current implementation. However, this might be a useful feature. In addition, defining triggers should be rejected by TimescaleDB as long as they are not supported.
