### ISSUE TITLE
Select from table does not show any data after pg_restore 

### ISSUE THREAD

**Issue by suikast42** [timescale/timescaledb#6526]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Backup, Restore

### What happened?

I try to follow the instructions from ts doc [Migrate the entire database at once](https://docs.timescale.com/self-hosted/latest/migration/entire-database/). 

Dump from timescaldb-2.1.8.Pg12 with 
```sql
pg_dump -Fc --disable-triggers  --dbname=postgresql://user:pwd@localhost:5432/db
```

Copy the dump to target machine with fresh timescale-db-ha.2.1.13.pg16 and restore it with 
```sql
pg_restore  -Fc -v  --dbname=postgresql://user:pwd@localhost:5432/db
```
But every select oin a hyper table give no results back. If I take a new dump from the migrated the then the dump has the same size with the imported. It seems that the data is there but can't do any select. 

```sql
select count(*) from eventlog.event_log; -- result: 0
SELECT * FROM approximate_row_count('eventlog.event_log'); -- result: 203012
Delete from eventlog.event_log -- 203012 rows deleted
```

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

16

### What operating system did you use?

Ubuntu 22.04.3 LTS

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
At the end of the restore I see 'pg_restore: warning: errors ignored on restore: 3'
```

### How can we reproduce the bug?

```bash
Dump and restore as described
```

**Comment by konskov** [comment]
hello @suikast42, thank you for reaching out. I see you are dumping from a very old version using PG12 and restoring to the latest version of timescaledb and PG16. You should be using the same versions of TimescaleDB and postgres to dump and restore. Is the objective to upgrade at the same time? I would recommend to either first upgrade and then dump/restore, or the other way around.

**Comment by suikast42** [comment]
PG-12_TS-2.8.1 -> PG-16_TS-2.8.1 -> PG-16_TS-2.13.1 Is that the right migration path ?

**Comment by suikast42** [comment]
PG-12_TS-2.8.1 ->  PG-14_TS-2.8.1 (That's the latest 2.8.1 )  -> PG-14_TS-2.13.1  ->  PG-16_TS-2.13.1  

That is the working migration path. For someone that needed
