### ISSUE TITLE
Query planner visits every chunks when type mismatch with current_date is used

### ISSUE THREAD

**Issue by onesvat** [timescale/timescaledb#656]
Consider a report table with timescale extension and daily partitioned. I would like the query sum of revenue of today. Here is two different queries with same result :

Using current_date
`SELECT SUM(revenue) FROM reports WHERE report_date >= current_date`

Using directly parameter appending from application
`SELECT SUM(revenue) FROM reports WHERE report_date >= '2018-08-10 00:00:00`

First query did lookup all chunks, and takes lots of time, the second query did lookup only right chunk and gave result faster.

I cannot use directly parameter injecting in the application that I used (metabase), how can I transform the first query to lookup only right chunk(s)?

**Comment by svenklemm** [comment]
The problem is the values you are comparing are not of the same datatype so it won't use the index.

What datatype are you using for the reports column? If report_date is timestamptz you could use the following query:

```
SELECT SUM(revenue) FROM reports WHERE report_date >= current_date::timestamptz
```

**Comment by mfreed** [comment]
Such timestamp/timestamptz mismatches for constraint exclusion will be automatically handled in this PR:  https://github.com/timescale/timescaledb/pull/1130
