### ISSUE TITLE
[Bug]: 'ERROR:  tuple already updated by self' after dropping chunks then inserting data

### ISSUE THREAD

**Issue by djzurawski** [timescale/timescaledb#6570]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Data ingestion

### What happened?

Dropped chunks from a hypertable, then tried to insert data that would have existed in those chunks. Getting `ERROR:  tuple already updated by self`. A continuous aggregate existed for the hypertable

Looks like this person ran into the same issue: https://github.com/timescale/timescaledb/issues/5905

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

14.10

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Not applicable

### What platform did you run on?

Timescale Cloud

### How can we reproduce the bug?

```bash
1. <hypertable with data>
2. `SELECT DROP_CHUNKS('sensor_data', newer_than => '2023-12-04 00:00:00+0')`
3.  INSERT INTO sensor_data
(time, sensor_id, value)
VALUES ('2023-12-21T13:00:10.239006+00:00', 9999, 123.4)
```

**Comment by fabriziomello** [comment]
@djzurawski Thanks for reaching out. I was not able to reproduce the problem so can u please create a complete reproducible test case with all DDL (hypertable and cagg definitions)?

**Comment by djzurawski** [comment]
After working with support this PR should fix this issue https://github.com/timescale/timescaledb/pull/6599
