### ISSUE TITLE
[Bug]: Memory leak and slow decompression during upserts into compressed chunks

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#6577]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

Upserts (ON CONFLICT) into a chunk that is compressed can be very slow and consume a lot of memory. From analysis of the code and tests the following can be concluded:

1. The compressed chunk is _fully_ opened and closed (including scan setup) for every inserted tuple. This is quite expensive.
2. The _whole_ compressed chunk is scanned for _every_ inserted tuple, even if all compressed data has already been decompressed. In that case it just scans dead tuples. It should be possible to shortcut this when all data has been decompressed and the compressed chunk is empty.
3. Memory usage grows linearly during the insert processing.  

The above leads to sub-optimal performance, especially compared to the same upserts on a non-compressed chunk. There might also be a memory leak on the insert path, although it is unclear if it is related to upserts/decompression or whether it also affects all inserts in general. 

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

15.5

### What operating system did you use?

Ubuntu 23.10

### What installation method did you use?

Source

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
create table bools (time timestamptz not null, value boolean not null);

select create_hypertable('bools', 'time', chunk_time_interval => interval '1 month');

\timing
insert into bools (time, value)
select t, round(random())::int::boolean
from generate_series('2022-06-28'::timestamptz, '2022-07-27 00:01:00', '0.1s') t;

create index on bools (time desc);
create unique index on bools (time) include (value);

alter table bools set (
      timescaledb.compress,
      timescaledb.compress_orderby = 'time'
);

select show_chunks('bools');
select pg_size_pretty(pg_table_size('_timescaledb_internal._hyper_1_1_chunk'));

-- Upsert #1: insert same data with ON CONFLICT
insert into bools (time, value)
select t, round(random())::int::boolean
from generate_series('2022-06-28'::timestamptz, '2022-07-27 00:01:00', '0.1s') t
on conflict (time) do update set value='t';

select compress_chunk('_timescaledb_internal._hyper_1_1_chunk');
select * from only _timescaledb_internal._hyper_1_1_chunk;

-- Upsert #2: insert same data on compressed data with ON CONFLICT
insert into bools (time, value)
select t, round(random())::int::boolean
from generate_series('2022-06-28'::timestamptz, '2022-07-27 00:01:00', '0.1s') t
on conflict (time) do update set value='t';
```

**Comment by hostops** [comment]
After just simple upgrade from 2.13.0 to 2.13.1 we noticed regular (every 9 hours) OOM kill of Postgres process in our Kubernetes setup.
**We also do not insert into compressed chunks or use ON CONFLICT.**
So this memory leak may affect all inserts.
(or it may be a totally different memory leak after all.)

Old limits:
So I believe it would be worth looking into that.
Memory limit: 8Gi
Memory available to Postgres: 8Gi
Process crash :
![image](https://github.com/timescale/timescaledb/assets/16599456/a96838c0-4b94-49eb-b26a-c8cbe4d10542)

New limits:
Memory limit: 8Gi
Memory available to Postgres: 7Gi

```
                       name       |       
----------------------------------+-------
 effective_cache_size             | 4GB   
 logical_decoding_work_mem        | 64MB  
 maintenance_work_mem             | 64MB  
 shared_buffers                   | 128MB 
 shared_memory_size               | 1392MB
 shared_memory_size_in_huge_pages | 696   
 shared_memory_type               | mmap  
 wal_buffers                      | 4MB   
 work_mem                         | 4MB   
```

![image](https://github.com/timescale/timescaledb/assets/16599456/624c485c-c32f-4084-9b15-16eaea347d08)

You can clearly see memory available to postgresql has been exceeded.

All I get from container logs is `FATAL:  terminating connection due to unexpected postmaster exit`
But when I check node logs, I can clearly see a Postgres process being killed by OOM because it exceeded limits.

**Comment by hostops** [comment]
Even with changed settings, we still get memory leak every few hours.
I think we will have to downgrade since this issue is too serious.
![IMG_20240207_184217](https://github.com/timescale/timescaledb/assets/16599456/c9c19b48-ce35-4602-934f-a6509d994342)

**Comment by hostops** [comment]
We had to downgrade timescaledb to version 1.13.0 - the version we had before those issues.
But to our suprise we still experience this issue.

**Comment by hostops** [comment]
After upgrading to pg15.6-ts2.14.0 problem disappear for us. Probably due to memory leak fixed in pg15.6.
![image](https://github.com/timescale/timescaledb/assets/16599456/1b644127-686a-4e4c-b31a-743863067489)

**Comment by svenklemm** [comment]
Thank you for the update, closing the issue since it seems to be upstream bug.
