### ISSUE TITLE
Support for PG11

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#661]
I didn't see an existing issue for this yet, so I thought I'd create one. Postgres 11 is now in Beta 3, which I think makes it a good time to start supporting it in TimescaleDb. We'd like to start testing the beta of PG11 for bugs/incompatibilities, but currently can't properly test it without TimescaleDb support for it.

**Comment by mfreed** [comment]
Hi @fvannee thanks for creating an issue.  This is on our nearer-term roadmap, just have a few other things that we are prioritizing for the next releases.

**Comment by fvannee** [comment]
Any rough idea what is required to become compatible with PG11? Is it just a matter of including some different headers and renaming some symbols or are there deeper levels of incompatibility?

**Comment by mfreed** [comment]
We haven't really looked into this in any detail.   I can say, however, that with PG10 it was mostly about just going through and updating different headers/symbols, etc. as you point out.  I *expect* it to be more like this for PG11 as well, but that's just the intuition.

**Comment by TimEvens** [comment]
+1 for PG11.  I'm also eager to prepare a release of OpenBMP using PG11 + TimescaleDB 1.0.0.

**Comment by did-g** [comment]
+100 
Are you working on it? 

I'm evaluating replacing some internal in house tools with pg, but it'd be PG11 and I'd like to compare timescaleDB with plain PG11, our needs are basic and PG tables partitioning would be good enough.

For our own internal use I mostly did it. It compiles  but saying there's some rough edges is an understatement.

**Comment by jesperpedersen** [comment]
@mfreed While PostgreSQL 11 support could be a more-or-less straight port it is worth to consider the declarative partition functionality, as it is greatly expanded - see https://www.postgresql.org/about/featurematrix/#partitioning-inheritance - and, with the on-going work for PostgreSQL 12 on partition performance, trigger / inheritance based solutions will become rarer in production deployments IMHO.

**Comment by fvannee** [comment]
Exactly, with PG11 released now and already containing some good improvements on run-time pruning for partitions (only Append node unfortunately though), I expect many of this to be perfected in PG12 (some great partitioning performance improvement patches are open in the commitfest at the moment).
I think it would be possible to switch TimescaleDb to use declarative partioning as implementation rather than inheritance-based solution (especially now that hash partitioning and subpartitioning is also supported), but it would require quite a bit of implementation effort I think. Still I think it will be worth it given the expected performance benefits.

**Comment by syepes** [comment]
+1

**Comment by esatterwhite** [comment]
Yes please

**Comment by phongwingstech** [comment]
+1 
Does dev team have any release plan for PG11 support?

**Comment by UncleAlbie** [comment]
Is there any progress on this?

**Comment by davidkohn88** [comment]
Yep! It's close should be a PR coming in the next few days, just working out a few kinks in handling upserts and updating a few tests.

**Comment by jamessewell** [comment]
Amazing!

**Comment by mfreed** [comment]
Release version 1.1.0 included (beta) support for PG 11.  Closing this issue.

https://github.com/timescale/timescaledb/releases/tag/1.1.0
