### ISSUE TITLE
[Bug]: `created_before` and `compress_created_before` returns wrong chunks

### ISSUE THREAD

**Issue by kevcenteno** [timescale/timescaledb#6611]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Command processing, Compression

### Given 
```sql
SELECT 
  chunk_name,
  range_start,
  range_end,
  chunk_creation_time
FROM timescaledb_information.chunks 
WHERE hypertable_name = 'some_table';
```
with results:
```
_hyper_29_216_chunk,
2023-01-24 19:00:00.000 -0500,
2023-01-25 19:00:00.000 -0500,
2024-02-06 00:56:15.539 -0500
```
and now is `2024-02-06 10:56:15.539 -0500`

### Expect
```sql
SELECT show_chunks('some_table', created_before => INTERVAL '1 year');
```
to return nothing

### Actual
```sql
SELECT show_chunks('some_table', created_before => INTERVAL '1 year');
```
 returns
```
_timescaledb_internal._hyper_29_216_chunk
```

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

16.1

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
See description.
```

**Comment by fabriziomello** [comment]
@kevcenteno Thanks for reaching out. 

There's nothing wrong with the API, I guess you misunderstood it a bit. The parameter you used `created_before => INTERVAL '1 year'` means the `NOW() - '1 year'` that will result in `2023-02-06 10:56:15.539-05`. Then the `show_chunks` will scan all chunks created before of this result timestamp, the similar as this query:
```sql
SELECT * FROM timescaledb_information.chunks WHERE hypertable_name = 'some_table' AND chunk_creation_time < '2023-02-06 10:56:15.539-05'::timestamptz;
```
See our docs for more information: https://docs.timescale.com/api/latest/hypertable/show_chunks/

**Comment by kevcenteno** [comment]
Hmmm... But the `chunk_creation` time in my example was `2024-02-06 00:56:15.539 -0500`, which is _after_ `2023-02-06 10:56:15.539-05`

**Comment by kevcenteno** [comment]
With that said, `SELECT * FROM timescaledb_information.chunks WHERE hypertable_name = 'some_table' AND chunk_creation_time < '2023-02-06 10:56:15.539-05'::timestamptz;` returns nothing, which is expected.

**Comment by fabriziomello** [comment]
You're correct @kevcenteno ... this is bug and my colleague @nikkhils will take care of it. Here a complete reproducible test case:
```sql
fabrizio=# CREATE TABLE issue6611 (
  time TIMESTAMPTZ,
  value DOUBLE PRECISION
);
SELECT create_hypertable('issue6611', 'time');
CREATE TABLE
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Dimensions cannot have NULL values.
   create_hypertable    
------------------------
 (1,public,issue6611,t)
(1 row)

fabrizio=# SELECT now() AS "NOW" \gset
fabrizio=# 
fabrizio=# INSERT INTO issue6611 VALUES (:'NOW', 1);
INSERT 0 1
fabrizio=# SELECT 
  chunk_name,
  range_start,
  range_end,
  chunk_creation_time
FROM timescaledb_information.chunks 
WHERE hypertable_name = 'issue6611';
    chunk_name    |      range_start       |       range_end        |      chunk_creation_time      
------------------+------------------------+------------------------+-------------------------------
 _hyper_1_1_chunk | 2024-01-31 21:00:00-03 | 2024-02-07 21:00:00-03 | 2024-02-06 17:44:29.254208-03
(1 row)

fabrizio=# SELECT show_chunks('issue6611', created_before => INTERVAL '1 year'); -- should not return chunks
              show_chunks               
----------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
(1 row)

fabrizio=# SELECT show_chunks('issue6611', created_before => NOW() - INTERVAL '1 year'); -- should not return chunks
              show_chunks               
----------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
(1 row)
```

**Comment by kevcenteno** [comment]
@fabriziomello thank you for creating a reproducible test case!

**Comment by kevcenteno** [comment]
Woohoo! Thank you @nikkhils!
