### ISSUE TITLE
Wondering if cockroach is possible for easy HA

### ISSUE THREAD

**Issue by gedw99** [timescale/timescaledb#664]
Not sure if worthwhile or possible ?

**Comment by mfreed** [comment]
I'm not sure I understand question.  While CockroachDB speaks the external Postgres protocol, it's own implementation isn't based on Postgres at all, so it's not really compatible/related to TimescaleDB.

If you are looking for HA/failover, we recommend using Postgres streaming replication + Patroni.

https://blog.timescale.com/scalable-postgresql-high-availability-read-scalability-streaming-replication-fb95023e2af
https://github.com/zalando/patroni

**Comment by gedw99** [comment]
Hey @mfreed 
I dont agee.
I have golang code using the  postgresql driver that when pointed to CockroachDB needs zeo change.
Granted not all SQL statements are supported, but most are.
So it seems possible to use Cockroach to me and gain the easy HA.
Doing HA with PostgreSQL is messy. WIth Cockroach its built in.

**Comment by RobAtticus** [comment]
@gedw99, that's actually confirming what was said. Yes, CockroachDB speaks PostgreSQL, which means PG drivers can talk to Cockroach instances. However, the internals of CockroachDB are not PostgreSQL internals, and therefore TimescaleDB cannot be installed with CockroachDB. Basically, to outside programs, like drivers, CockroachDB looks (mostly) like PG; but on the inside it does not support PostgreSQL extensions.

**Comment by RobAtticus** [comment]
Yes, TimescaleDB is loaded as an extension to PostgreSQL
