### ISSUE TITLE
Unable to drop hypertable in non-public schema

### ISSUE THREAD

**Issue by skebanga** [timescale/timescaledb#668]
*Copied from slack at the request of David Kohn*

I'm getting an error when attempting to `DROP TABLE IF EXISTS {schema}.{table}` against a hypertable.

Not sure if this is related to timescale or not, but here is the problem I'm seeing:

I have a number of schemas set up:

*schemas:*

    hg=# \dn
     _timescaledb_cache    | postgres
     _timescaledb_catalog  | postgres
     _timescaledb_internal | postgres
     hg_quotes_raw         | zoolander
     hg_trade_volume_1m    | zoolander
     hg_trade_volume_day   | zoolander
     hg_trades_raw         | zoolander
     public                | postgres

Within each of the `hg_xxx` schemas I have a number of tables (most with common table names):

*hg_quotes_raw:*

    hg=# \dt hg_quotes_raw.*
     hg_quotes_raw | hgf7 | table | zoolander
     hg_quotes_raw | hgf8 | table | zoolander
     ...
     hg_quotes_raw | hgz6 | table | zoolander
     hg_quotes_raw | hgz7 | table | zoolander

*hg_trade_volume_1m:*

    hg=# \dt hg_trade_volume_1m.*
     hg_trade_volume_1m | hgf7 | table | zoolander
     hg_trade_volume_1m | hgf8 | table | zoolander
     ...
     hg_trade_volume_1m | hgz6 | table | zoolander
     hg_trade_volume_1m | hgz7 | table | zoolander

I have one such table, `hg_trade_volume_1m.hgq8`, as detailed below:

    hg=# \d hg_trade_volume_1m.hgq8
     time   | timestamp with time zone |           | not null |
     volume | integer                  |           |          |

    hg=# select * from hg_trade_volume_1m.hgq8 limit 5;
     2016-12-16 09:32:00-05 |     88
     2016-12-16 13:45:00-05 |     88
     2016-12-22 13:42:00-05 |     86
     2017-01-04 11:43:00-05 |     43
     2017-01-04 13:38:00-05 |     22

*Problem:*

When I attempt to *drop* this table, I get an error saying a *different schema* doesn't exist:

    hg=# drop table if exists hg_trade_volume_1m.hgq8;
    ERROR:  schema "hg_raw_quotes" does not exist

My table persists after this drop statement:

    hg=# \d hg_trade_volume_1m.hgq8
     time   | timestamp with time zone |           | not null |
     volume | integer                  |           |          |

    hg=# select * from hg_trade_volume_1m.hgq8 limit 5;
     2016-12-16 09:32:00-05 |     88
     2016-12-16 13:45:00-05 |     88
     2016-12-22 13:42:00-05 |     86
     2017-01-04 11:43:00-05 |     43
     2017-01-04 13:38:00-05 |     22

The issue is I cannot drop the table

Postgres mentions a different schema in the error message.

*Notes:*

Please note the schema mentioned in the error message used to exist in the database, but has since been removed. 

Please also note that the table (and related hypertable) was not originally created in the schema, but rather migrated to a schema after creation. Not sure if this could be an underlying cause?

Although, I see in [the documentation](https://docs.timescale.com/v0.11/using-timescaledb/schema-management#updating-schemas) that ALTER TABLE for a schema change is supported, so perhaps not?

The table is not owned by user postgres

    hg=# \dx timescaledb
     timescaledb | 0.11.0  | public | Enables scalable inserts and complex queries for time-series data

*Attempting to move the tables from the non-public schema back to public also fails:*

    # alter table hg_quotes_raw.hgx6 rename to hg_quotes_raw_hgx6;
    # alter table hg_quotes_raw.hg_quotes_raw_hgx6 set schema public;
    relation "hgx6_time_idx" already exists in schema "public"

Presumably this is because the table name `hgx6` exists in multiple namespaces / schemas?

ie: I used to have `hg_quotes_raw.hgx6`, `hg_trades_raw.hgx6`, `hg_trade_volumn_1m.hgx6`, etc

My approach was to

- a) merge the namespace and table name (eg: `hg_quotes_raw.hgx6` --> `hg_quotes_raw.hg_quotes_raw_hgx6`) to prevent table name clashes
- b) move the table into the public namespace (eg: `hg_quotes_raw.hg_quotes_raw_hgx6` --> `hg_quotes_raw_hgx6`)

However, the step b fails, as it seems the renaming of the table doesn't propagate to the indexes, and so I'm left with dup indexes? (edited)

**Database setup:**

it's a very simple set up, almost as basic as you can get:

    CREATE TABLE IF NOT EXISTS {table}
    (
        time TIMESTAMPTZ NOT NULL,
        volume INTEGER
    );

    SELECT create_hypertable('{table}', 'time', if_not_exists => TRUE);

    COPY {table}(time,volume) FROM '{file}' DELIMITER ',' CSV```

`table` would be `hg_trades_raw.hgx6` (that is, `schema.table`, where `schema`=`hg_trades_raw` and `table`=`hgx6`), or `hg_trade_volumn_1m.hgx6`, etc

there are no relations between tables, there are no special schemas (afaik)

each of the tables is a hypertable

each table represents a single futures contract (eg `hgx6` is the November 2016 Copper future), while each schema represents a particular form that data takes (eg `hg_trades_raw` is the raw trade tick data (unquantised), `hg_trade_volumn_1m` is the total volume traded each minute, etc)

I'm literally just using timecale to store standalone tables of financial market data

One quirk which might shed some light is that I started off creating the tables in the public namespace, then later decided to namespace, so created new schemas, and altered the tables to move them into their respective schemas, and then altered them to rename the table to be just the future code (eg `hgx6`)

**Comment by amytai** [comment]
Hey, Steve. We're trying to reproduce this on our end and need some more information for you. On my end, I'm running something like
```ALTER TABLE mytable SET SCHEMA myschema;
ALTER TABLE myschema.mytable RENAME TO othertable;
```
And then running `DROP TABLE IF EXISTS myschema.othertable`, which goes through fine. 
The difference between my setup and your setup is that I'm running everything as the postgres user. I suspect there's something going on with the permissions of the `zoolander` user you created, so could you post the perms associated with all the roles in Postgres? Something like the output of `\du` would do. Thanks! Any other info on reproducibility would be great as well, such as specific commands you executed to get to that error.

**Comment by skebanga** [comment]
```
hg=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 steve     | Superuser, Create role, Create DB                          | {}
 zoolander | Superuser, Create role, Create DB                          | {}
```

**Comment by skebanga** [comment]
> Any other info on reproducibility would be great as well, such as specific commands you executed to get to that error.

Unfortunately I didn't keep a log of the commands I ran, and have long since blown the whole database away, so beyond what I wrote above I'm afraid I'm not much help. Sorry!

I have since changed to using the postgres user exclusively (not sure if that's good practice from a security perspective?) and have also gone with schema-less to work around this issue.

**Comment by skebanga** [comment]
Fair enough, thanks for trying to repro!

**Comment by skebanga** [comment]
Hmm, actually, I've found some notes I wrote when I was developing this. I'm not sure how accurate they are, but I'll put them down anyway, in case it's of use.

---

# Timescaledb

## Installation

Install timescaledb

    $ sudo add-apt-repository ppa:timescale/timescaledb-ppa
    $ sudo apt update
    $ sudo apt install timescaledb-postgresql-10

Add timescaledb to postgres, and restart

    $ sudo vim /etc/postgresql/10/main/postgresql.conf
    shared_preload_libraries = 'timescaledb'

    $ sudo service postgresql restart

Set a admin password

    $ sudo -u postgres psql postgres
    # \password postgres
    < enter password > (eg: postgres)
    # \q

## Create a new user

in a shell, login as postgres user

    $ sudo -i -u postgres

create a new admin user

    $ createuser -s zoolander

create password for new user

    $ sudo -u postgres psql postgres
    # \password zoolander
    # \q

create a default database for zoolander

    $ createdb zoolander

## Creating a timeseries database

Connect to postgres

    $ psql -U zoolander -h localhost
    < enter password>

Create database

    # CREATE database hg;

Connect to database

    # \c hg

Add timescaledb capabilities to the database

    # CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

### Create a schema

    # CREATE SCHEMA raw_quotes;

### Create a table

Create a normal sql table

    # CREATE TABLE raw_quotes_hgf7 (
        time         TIMESTAMPTZ NOT NULL,
        bid_volume  INTEGER,
        bid_price    DOUBLE PRECISION,
        ask_price    DOUBLE PRECISION,
        ask_volume  INTEGER
        );

Transform it into a [hypertable](https://docs.timescale.com/v0.10/api#create_hypertable)

    # SELECT create_hypertable('raw_quotes_hgf7', 'time');

---

At this point I was populating the database from python using pycopg2

### Query to populate the table:

    copy_quotes_from_csv = '''
    COPY {table}(time,bid_volume,bid_price,ask_price,ask_volume) FROM '{file}' DELIMITER ',' CSV
    '''

(Note table would have been `raw_quotes_hgf7` here)

---

IIRC I believe I now attempted to create a schema `raw_quotes`, and rename the table from `raw_quotes_hgf7` to `raw_quotes.hgf7`

Perhaps this is the cause?

I'm afraid my memory is quite hazy - both postgres and timescale were very new to me at the time (still are!), so I was trying things as I went.

**Comment by amytai** [comment]
These are great! I'll take a look and get back to you, probably tomorrow.

**Comment by amytai** [comment]
Just to update you-- I went through these steps and was still able to drop the table. But like I said, still very curious how the original error happened, so if you ever encounter again, let us know how to reproduce!

**Comment by skebanga** [comment]
Thank you for trying, and sorry I wasn't able to help you repro!

Will definitely let you know if I encountered this again.

Thanks for a great project!

**Comment by mmouterde** [comment]
seen on slack with @mfreed 

Here how I reproduce this issue.

~~~SQL
CREATE SCHEMA IF NOT EXISTS original_name;
CREATE TABLE original_name.my_table (
  date timestamp with time zone NOT NULL,
  quantity double precision
);
SELECT create_hypertable('original_name.my_table','date');

INSERT INTO original_name.my_table (date, quantity) VALUES
                                                           ('2018-07-04T21:00:00+00:00', 8),
                                                           ('2018-07-05T01:00:00+00:00', 15),
                                                           ('2018-07-06T10:00:00+00:00', 15),
                                                           ('2018-07-07T15:00:00+00:00', 95),
                                                           ('2018-07-08T22:00:00+00:00', 8),
                                                           ('2018-07-09T23:00:00+00:00', 2),
                                                           ('2018-07-10T23:00:00+00:00', 20),
                                                           ('2018-08-05T01:00:00+00:00', 15),
                                                           ('2018-08-06T10:00:00+00:00', 15),
                                                           ('2018-08-07T15:00:00+00:00', 95),
                                                           ('2018-08-08T22:00:00+00:00', 8),
                                                           ('2018-08-09T23:00:00+00:00', 2),
                                                           ('2018-08-10T23:00:00+00:00', 20);

ALTER SCHEMA original_name RENAME TO new_name;

DROP TABLE new_name.my_table;
~~~

The `DROP` command produce : 
    [2018-10-09 15:49:33] [3F000] ERROR: schema "original_name" does not exist

**Comment by mfreed** [comment]
More information:  

@mmouterde encountered this problem on TimescaleDB 0.10.1.  We could not replicate this problem on 0.12.1 (i.e., the above instructions executed correctly), so we believe it has been fixed in later versions (some of our fixes did indeed focus on schema & permissions).

**Comment by mmouterde** [comment]
same issue in 0.12.1-pg10

**Comment by mfreed** [comment]
@skebanga Please let me know if this works for you in the 1.0.0 release.

**Comment by RobAtticus** [comment]
@skebanga can you confirm whether this works in 1.0.0? If so, I'll go ahead and close the issue.

**Comment by skebanga** [comment]
@RobAtticus @mfreed I'm afraid the bug caused me to stop using schemas altogether, so I am unable to reproduce.

I'll close the issue for now, and re-open in the future if necessary.

**Comment by RobAtticus** [comment]
Gotcha, well hopefully you can move them back into schemas now. But yes, let us know if it returns.
