### ISSUE TITLE
[Feature]: allow configuring auto_explain format and log_level

### ISSUE THREAD

**Issue by adriangb** [timescale/timescaledb#6685]
### What problem does the new feature solve?

You currently only allow configuring some parameters of `auto_explain` but not all parameters. The ones you do allow configuring are:

```
auto_explain.log_analyze
auto_explain.log_buffers
auto_explain.log_nested_statements
auto_explain.log_settings
auto_explain.log_timing
auto_explain.log_triggers
auto_explain.log_verbose
auto_explain.log_wal
auto_explain.log_min_duration
auto_explain.sample_rate
```

I wanted to configure `auto_explain.log_format` to `json` and needed to configure `auto_explain.log_level` to `NOTICE` (so that I can get `auto_explain` plans in my application without sifting through postgres logs).

I'm guessing this is simply an omission.

### What does the feature do?

Allow configuring some `auto_explain` parameters.

**Comment by adriangb** [comment]
cc @mchristofides

**Comment by adriangb** [comment]
As a side note: it would be awesome if Timescale could integrate with pgMustard to give you analyzed plans. The workflow I envision is having a button in the Insights console that says "visualize plan in pgMustard". Other providers already offer similar features (at least I've used it in [GCP CloudSQL Insights](https://cloud.google.com/sql/docs/postgres/using-query-insights#sample-query-plans)).

**Comment by mchristofides** [comment]
@adriangb nice suggestion, it'd be great if those two could be added 😄 

FYI — I think the `don't` in your original comment is a typo and should say `do`?

**Comment by adriangb** [comment]
The timescale team has resolved this and these parameters are now available in timescale cloud 🥳!

Thank you @iroussos for getting it done so quickly!

**Comment by adriangb** [comment]
I'm hoping I'll get time to package up what we do with this into a nice open source package at some point 😄

**Comment by adriangb** [comment]
Here's something: https://github.com/adriangb/sqltrace/blob/main/test.py

**Comment by adriangb** [comment]
One more parameter request: `auto_explain.log_parameter_max_length`.

I think this is the last one that auto_explain has that timescale doesn't :)

**Comment by mchristofides** [comment]
It looks like `auto_explain.log_parameter_max_length` is supported now 🎉
