### ISSUE TITLE
[Bug]: Install Timescaledb for windows on version 2.14.2 failed, but it is successful on version 2.13.1 

### ISSUE THREAD

**Issue by richwxd** [timescale/timescaledb#6715]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Other

### What happened?

My postgresql with version 16.2 is portable (https://get.enterprisedb.com/postgresql/postgresql-16.2-1-windows-x64-binaries.zip) and it runs under laragon. 
After running "setup.exe", all steps are successful. But when in psql run "create extension timescaledb", it shows "The specified module could not be found".

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

16.2

### What operating system did you use?

Windows

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
1. Prepare laragon, prepare Win64OpenSSL-3_2_1.exe, include "C:\Program Files\OpenSSL-Win64\bin" in the PATH environment
2. Setup windows environment, make sure the postgresql\bin is in the PATH. Probably must restart windows.
3. Start laragon then launch Postgresql to initialize the data directory.
4. Stop PostgreSQL then run timescaledb setup.exe to install TimeScaleDB. It should be successful.
5. Start PostgreSQL
6. Start CMD/Pwsh, type psql -> \c postgres
7. Type "create extension timescaledb;"

For version 2.13.1, it is okay.
For version 2.14.2, it shows "The specified module could not be found".
```

**Comment by jnidzwetzki** [comment]
Hi @richwxd,

Thanks for reaching out. This problem could be related to #6657. Could you install OpenSSL v1.1.1 as well and try to load the extension afterward again?

**Comment by jnidzwetzki** [comment]
Hi @richwxd,

Thanks for getting back. Since TimescaleDB 2.13.2 requires OpenSSL 1.1.1, you should also copy these DLLs (`libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll`) to the PostgreSQL directory. Could you try this and check if this solves the problem in your installation?

**Comment by Ejananee** [comment]
yes

> Hi,
> 
> I have tried OpenSSL v1.1.1 and copy libeay32.dll and ssleay32.dll to postgresql, it still has problem. Then try to remove copied libeay32.dll and ssleay32.dll, and downgrade TimeScaleDB version to 2.13.1, it works. So I opened this ticket.

this one helps me to resolve it . thanks along with SET "timescaledb.allow_install_without_preload = 'on';" on psql shell after that ,extension created successfully
