### ISSUE TITLE
PgSQL has a large number of connections in operator ----"SET application_name = 'PostgreSQL JDBC Driver'"

### ISSUE THREAD

**Issue by wangchuanxiang** [timescale/timescaledb#673]
development language： JAVA
web program connects PgSQL database, the program runs for a period of time, PgSQL generates lots of idle threads  ---  "SET application_name = 'PostgreSQL JDBC Driver'".

Web程序连接Pgsql数据库，运行一段时候后会pgsql会产生大量空闲连接数，造成连接数过多，空闲线程执行的sql语句为："SET application_name = 'PostgreSQL JDBC Driver'"

pgsql数据库配置文件：
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://*******/***

Things are urgent, Expected instruction.
对于该问题我已经黔驴技穷，还望知者不吝赐教。

**Comment by wiselyman** [comment]
@wangchuanxiang 
You must running postgres instance in docker container，change the `maxLifeTime` to 10 minitues will resolve this problem.
