### ISSUE TITLE
[Bug]: Found empty chunks during upgrading. How to recover them?

### ISSUE THREAD

**Issue by ericyu** [timescale/timescaledb#6748]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Compression

### What happened?

When I tried to upgrade Timescale from 2.6.1 to 2.11.2, I encountered the same issue as #5204 and found some duplicated records in _timescaledb_catalog.compression_chunk_size. In that issue a solution was provided: to remove the duplicated records where the compressed chunk was not pointed from the chunk.

However, I found that the chunks are actually empty (which should not be), and here is one example from the orphan chunks:

```
> SELECT * FROM _timescaledb_catalog.chunk WHERE id=48610;
+-------+---------------+-----------------------+----------------------+---------------------+---------+--------+
| id    | hypertable_id | schema_name           | table_name           | compressed_chunk_id | dropped | status |
|-------+---------------+-----------------------+----------------------+---------------------+---------+--------|
| 48610 | 5             | _timescaledb_internal | _hyper_5_48610_chunk | 68782               | False   | 1      |
+-------+---------------+-----------------------+----------------------+---------------------+---------+--------+
```

```
> SELECT * FROM _timescaledb_catalog.compression_chunk_size WHERE chunk_id=48610;
+----------+---------------------+------------------------+-------------------------+-------------------------+----------------------+-----------------------+-----------------------+
| chunk_id | compressed_chunk_id | uncompressed_heap_size | uncompressed_toast_size | uncompressed_index_size | compressed_heap_size | compressed_toast_size | compressed_index_size |
|----------+---------------------+------------------------+-------------------------+-------------------------+----------------------+-----------------------+-----------------------+
| 48610    | 68777               | 2040913920             | 80879616                | 168943616               | 2801664              | 391036928             | 114688                |
| 48610    | 68782               | 0                      | 8192                    | 16384                   | 0                    | 8192                  | 8192                  |
+----------+---------------------+------------------------+-------------------------+-------------------------+----------------------+-----------------------+-----------------------+
```

```
> SELECT COUNT(*) FROM _timescaledb_internal._hyper_5_48610_chunk;
+-------+
| count |
|-------|
| 0     |
+-------+
```

From the result above, we can see that `48610` points to a compressed chunk `68782` which is empty, but it once pointed to another compressed chunk `68777` which still has the data:
```
> SELECT COUNT(*) FROM _timescaledb_internal.compress_hyper_8_68777_chunk
2974
> SELECT COUNT(*) FROM _timescaledb_internal.compress_hyper_8_68782_chunk
0
```

Maybe there was some interruption during the compress process. What if I update the catalog to get it point back to the old compressed chunk? So I tried:
`UPDATE _timescaledb_catalog.chunk SET compressed_chunk_id=68777 WHERE id=48610;`
and it seems working:
```
> SELECT COUNT(*) FROM _timescaledb_internal._hyper_5_48610_chunk;
+---------+
| count   |
|---------|
| 2931108 |
+---------+
```

But I am still concerned if this is the proper way to fix this issue and also worried about data integrity. Would you give me some advice? Thank you!

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

12.14

### What operating system did you use?

Ubuntu 20.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Google Cloud Platform (GCP)

### How can we reproduce the bug?

```bash
See description.
```

**Comment by jnidzwetzki** [comment]
Hi @ericyu,

Thanks for reaching out. The steps you performed look correct for solving this issue. In addition, I suggest decompressing and compressing the affected chunk (see [this](https://docs.timescale.com/api/latest/compression/decompress_chunk/) and [this](https://docs.timescale.com/api/latest/compression/compress_chunk/) command). The recompression ensures that fresh meta-data is written for the affected chunk. 

If the orphan and empty compressed chunk still exist, you could drop it now by executing `DROP TABLE _timescaledb_internal.compress_hyper_8_68782_chunk`. 

However, before you perform any changes, please make sure that you have a backup in place if one of the commands fails due to unexpected catalog inconsistencies.

**Comment by ericyu** [comment]
Hi @jnidzwetzki,
Thank you for response! I have updated the chunk catalog, recompressed affected chunks using the above way. And also dropped the empty chunks, `REINDEX`'ed several Timescale tables as indicated in #5204. It seems the problem has solved. Thank you!
