### ISSUE TITLE
NOTIFY / LISTEN on Hypertables

### ISSUE THREAD

**Issue by Fabioni** [timescale/timescaledb#6757]
### What problem does the new feature solve?

Can I somehow use Postgres' NOTIFY / LISTEN mechanism on TimescaleDBs hypertables?

### What does the feature do?

If not this would be a goof feature.

**Comment by adriangb** [comment]
What do you mean by this? I'm pretty sure you can set a trigger on a hypertable that sends a NOTIFY on every insert or something like that.

**Comment by Fabioni** [comment]
@adriangb that is what I mean.

**Comment by adriangb** [comment]
It works for me:

```sql
CREATE TABLE test (ts TIMESTAMPTZ NOT NULL);

SELECT create_hypertable('test', by_range('ts'));

CREATE OR REPLACE FUNCTION notify_trigger() RETURNS trigger AS $$
DECLARE
    payload JSON;
BEGIN
    PERFORM pg_notify('notify_channel', 'hi!');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER insert_notify_trigger
AFTER INSERT
ON test
FOR EACH ROW
EXECUTE PROCEDURE notify_trigger();

-- On another connection
LISTEN notify_channel;

-- On the first connection
INSERT INTO test (ts) VALUES (NOW());

-- On the second connection
SELECT 1;  -- need to do something to receive the notification
```

There's nothing timescale specific about this, it works just like if it were not a hypertable.

**Comment by nikkhils** [comment]
@Fabioni does the above example as provided by @adriangb meet your requirements?
