### ISSUE TITLE
[Bug]: ERROR XX000 (internal_error) more than one invalidation watermark found 

### ISSUE THREAD

**Issue by bfolkens** [timescale/timescaledb#6762]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

We're seeing an increasing number of the following error during `INSERT` into a table that is the target for 3 continuous aggregates.  We recently upgraded to TimescaleDB 2.14.2 from 2.11.2.

```
ERROR XX000 (internal_error) more than one invalidation watermark found 
```

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

13.14

### What operating system did you use?

Alpine 3.18 x84

### What installation method did you use?

Docker

### What platform did you run on?

Google Cloud Platform (GCP)

### How can we reproduce the bug?

```bash
This is happening during INSERT into a table that is referenced by 3 continuous aggregates.  We recently upgraded to TimescaleDB 2.14.2 from 2.11.2.
```

**Comment by mkindahl** [comment]
This is probably fixed in https://github.com/timescale/timescaledb/pull/6677. It has not been released yet, but should be out in the next release.

**Comment by mkindahl** [comment]
Closing this issue since it seems to be fixed. Please re-open if the fix does not solve the issue.
