### ISSUE TITLE
[Bug]: DELETE FROM compressed chunks ignoring subquery 

### ISSUE THREAD

**Issue by Dzuzepppe** [timescale/timescaledb#6781]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression, Query executor

### What happened?

Problem is related only to compressed chunks.
DELETE calls ignoring subqueries used in conditions of which rows should be removed. 

Below example should delete 0 rows because of defined WHERE conditions:
`DELETE FROM values WHERE signal_id <> ALL(SELECT signal_id FROM values);`

Above call triggered on uncompressed data working as expected: DELETE 0
Above call triggered on compressed data will delete all rows from table 'values'

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

16.2

### What operating system did you use?

Docker image: timescale/timescaledb:2.14.2-pg16

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
\! echo "STEP 1: Create table"
CREATE TABLE IF NOT EXISTS values
(
  "source_timestamp" timestamptz,
  "signal_id" integer,
  "value" float8,
  PRIMARY KEY (signal_id, source_timestamp)
);

\! echo "STEP 2: Create hypertable"
SELECT create_hypertable('values', 'source_timestamp', chunk_time_interval => interval '1 week', if_not_exists => true);

\! echo "STEP 3: Configure compression parameters"
ALTER TABLE values SET (
	timescaledb.compress,
	timescaledb.compress_segmentby = 'signal_id',
	timescaledb.compress_orderby = 'source_timestamp DESC');

\! echo "STEP 4: Setup compression policy"
SELECT add_compression_policy('values', INTERVAL '2 weeks');

\! echo "STEP 5: Insert rows into table"
INSERT INTO values (signal_id, value, source_timestamp) VALUES
	(1, 0, '2000-01-01T00:00:00.000Z'),
	(2, 0, '2000-01-01T00:00:00.000Z');

\! echo "STEP 6 [TEST 1]: Call DELETE which should not delete any rows. Expect message: DELETE 0"
DELETE FROM values WHERE signal_id <> ALL(SELECT signal_id FROM values);

\! echo "STEP 7: Get compress job id and CALL run_job()"
DO $$
DECLARE compress_job_id int;
BEGIN
    compress_job_id = (SELECT job_id FROM timescaledb_information.jobs WHERE proc_name = 'policy_compression' AND hypertable_name = 'values');
	CALL run_job(compress_job_id);
END; $$;

\! echo "STEP 8 [TEST 2]: After compression:"
\! echo "STEP 8 [TEST 2]: Call the same DELETE which also should not delete any rows. Expect message: DELETE 0"
DELETE FROM values WHERE signal_id <> ALL(SELECT signal_id FROM values);

DROP table values
```

**Comment by nikkhils** [comment]
@Dzuzepppe thanks for the repro steps. I can confirm that it's indeed carrying out the delete. We will investigate and get back on this.

**Comment by Dzuzepppe** [comment]
Hi @nikkhils, thank you for fast response. It looks like quite critical bug where you can delete unintended data.

**Comment by nikkhils** [comment]
@Dzuzepppe yeah, it's a critical bug but only for the specific subquery that references itself. For other use-cases where the subquery is something else, the code should work ok enough.

**Comment by Dzuzepppe** [comment]
@nikkhils Yes, it's true, but with more sophisticated DELETE filtering, subquery is the only option. 
My example was just the simplest way to show a problem, and of course, on my production system, I am doing more. 
Nevertheless, can I expect a bug fix in the near future, or is it better if I start thinking about bypassing this problem? 
It is my first bug report, and I don't know how much time a bug fix procedure can take.

**Comment by nikkhils** [comment]
@Dzuzepppe I meant to say that this specific DELETE

`DELETE FROM values WHERE signal_id <> ALL(SELECT signal_id FROM values);`

where the subquery self-references `values` again while doing DELETE from `values` itself is the one that does not work (additionally, if the contains compressed chunks which need to be decompressed). If your subquery references any other table/hypertable `SELECT signal_id from any_other_table_than_values` then that should work as expected is what I meant to indicate the comparative severity of the issue.

I am actively working on a bugfix for this. No fixed ETA right now but we will try to include it in one of the upcoming releases.

**Comment by nikkhils** [comment]
@Dzuzepppe this has been merged into the main branch and will make its way into the next release soon. Thanks for the report!

**Comment by Dzuzepppe** [comment]
Greate news @nikkhils. Thanks for fast fix!
