### ISSUE TITLE
[Bug]: Update for single row on compressed hypertable tries to scan compressed chunks when using date_trunc or time_bucket

### ISSUE THREAD

**Issue by deanna-abrams** [timescale/timescaledb#6785]
### What type of bug is this?

Unexpected error, Other

### What subsystems and features are affected?

Compression, Query executor, Query planner

### What happened?

Postgres stores timestamptz to microsecond precision.

I want to update a row in a compressed hypertable based on timestamp matching to millisecond precision. 

The table is compressed up to the last 60 days, and the row to be updated is from a time within the last 60 days (aka an uncompressed chunk of the hypertable).

Using date_trunc to match the timestamp to millisecond precision causes the planner to try to scan and update every chunk, including compressed chunks, which causes an error.

Using time_bucket instead of date_trunc results in the same failing execution plan.

As an example:
```
-- tries to scan/update irrelevant compressed chunks - ERRORS
EXPLAIN UPDATE table_name 
SET column_name = value 
WHERE time_bucket('1ms', time) = '2024-03-15 14:33:18.008 -0700';

 -- tries to scan/update irrelevant compressed chunks - ERRORS
EXPLAIN UPDATE table_name 
SET column_name = value 
WHERE date_trunc('milliseconds', time) = '2024-03-15 14:33:18.008 -0700';

-- only tries to scan/update relevant uncompressed chunks - SUCCEEDS
EXPLAIN UPDATE table_name 
SET column_name = value 
WHERE date_trunc('1ms', time) = '2024-03-15 14:33:18.008 -0700'
AND time >= '2024-03-15 14:33:18.008 -0700';
```

Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1710886184765899

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

15

### What operating system did you use?

GKE probably ubuntu

### What installation method did you use?

Not applicable

### What platform did you run on?

Google Cloud Platform (GCP)

### How can we reproduce the bug?

```bash
1. create a hypertable with a time column
2. add data to the hypertable
3. compress the hypertable so that there are several compressed chunks, and at least one uncompressed chunk
4. try to update a row in the uncompressed chunk (see update code in description)
```

**Comment by konskov** [comment]
Hello @deanna-abrams , thank you for reaching out!
Version 2.10.0 of TimescaleDB is quite old at this point (latest is currently 2.14.2); and UPDATES on compressed chunks are supported since version 2.11.0. There have also been several planning optimizations since 2.10.0, so I would recommend upgrading your version of TimescaleDB. That should make the error you are seeing go away. Could you check with the latest version and let us know if the problem persists?
