### ISSUE TITLE
[Bug]: pg_upgrade cannot upgrade 2.12.2-pg13 to 2.14.2-pg15

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb#6803]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

I've performed major postgres upgrades with mixed timescaledb versions before. Currently I am unable to upgrade from 2.12.2-pg13 to 2.14.2-pg15 due to this specific error:

`could not load library "$libdir/timescaledb-2.14.2": ERROR:  attempt to redefine parameter "timescaledb.enable_deprecation_warnings"`

Of course if I upgrade the extension to 2.14.2 on the 13 cluster before upgrading to 15, no problem.

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

15.6

### What operating system did you use?

timescaledb-ha

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

**Comment by jflambert** [comment]
Yes I can confirm using same timescaledb versions is successful. No problem.

But in this case I am highlighting a regression. I'll try to dig up some older logs where mixed timescaledb versions were not problematic. Note that I'm using the timescaledb-ha image so all historical versions are in the lib folder.

**Comment by jnidzwetzki** [comment]
https://github.com/timescale/timescaledb/issues/4503 seems to be related.

**Comment by jflambert** [comment]
You're right @jnidzwetzki I might possibly have created a duplicate here. However my error message is slightly different.

What's more I actually posted in that issue that using timescaledb-ha solved my issue at the time. So in fact this might still be a regression. I know you guys made big GUC changes recently.

**Comment by svenklemm** [comment]
When doing major pg version upgrade source and destination version are required to be identical
