### ISSUE TITLE
[Bug]: Upgrade Version From 2.10.1 To 2.14.2 Failing With loader version out-of-date

### ISSUE THREAD

**Issue by adeifeadekunbi** [timescale/timescaledb#6830]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

I ran below command to upgrade 2.10.1 version to 2.14.2 `sudo yum install timescaledb-2-postgresql-14-2.14.2 -y`
After successfully run of the above command and restart of postgresql, i ran the the below command `psql -X -c "ALTER EXTENSION timescaledb UPDATE" database_name;`
The above update command failed with error
`    ERROR:  loader version out-of-date
    HINT:  Please restart the database to upgrade the loader version.`
  
  The upgrade documentation didn't contain the PostgreSQL restart instruction https://docs.timescale.com/self-hosted/latest/upgrades/minor-upgrade/ and when i tested 2.11.1 version PostgreSQL restart was not also requested.
  
Can this upgrade be done with restarting postgresql

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.6

### What operating system did you use?

Centos 7.9

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
STEP 1: upgrade timescaledb to version 2.14.2
STEP 2: Restart PostgreSQL
STEP 3: psql -X -c "ALTER EXTENSION timescaledb UPDATE" database_name;
```

**Comment by erimatnor** [comment]
TimescaleDB consists of multiple shared libraries. It seems the new loader so-file wasn't picked up when you restarted. Make sure that the new loader file from the new package is preloaded as opposed to the old one.

**Comment by adeifeadekunbi** [comment]
Is PostgreSQL restart required for upgrading to 2.14.2 ?  
If run the update without restarting PostgreSQL i get below error
`ERROR:  loader version out-of-date HINT:  Please restart the database to upgrade the loader version.`
but if i restart PostgreSQL after the upgrade, i wont get any error. 
Am asking because PostgreSQL restart was not mentioned in the upgrade guide

**Comment by erimatnor** [comment]
@adeifeadekunbi The loader library was updated as part of the 2.14 release so a restart is required if you are updating from a release older than 2.14, which seems to be the situation in your case. The need to restart was mentioned in the [release notes ](https://github.com/timescale/timescaledb/releases/tag/2.14.0) for 2.14. If you are updating from 2.14 to a later version, no restart is required. That is why it is not mentioned in the general update instructions.

If you want to be careful, you should study the release notes for every release in-between the one you are updating from to the release you are updating to. Then you will catch this information.

**Comment by adeifeadekunbi** [comment]
Thank you for this clerification.

**Comment by phemmer** [comment]
I might recommend putting a notice in the documentation that a restart may be required. The [minor upgrade documentation](https://docs.timescale.com/self-hosted/latest/upgrades/minor-upgrade/) implies that a non-interruptive upgrade is possible between minor versions, making no mention that in some cases a restart may be required.
