### ISSUE TITLE
[Bug]: "chunk_constraint" table constraint error when updating Timescale extension

### ISSUE THREAD

**Issue by hongquan** [timescale/timescaledb#6905]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Restore

### What happened?

Today I upgaded TimescaleDB via `apt` (`timescaledb-2-loader-postgresql-14` `2.15.0~ubuntu22.04` package).

After that, I did in psql

```console
$ psql mydb -Xc 'ALTER EXTENSION timescaledb UPDATE;'
```

and got this error:

```
INFO:  Removing metadata of chunk 1 from hypertable 1
ERROR:  update or delete on table "chunk" violates foreign key constraint "chunk_constraint_chunk_id_fkey" on table "chunk_constraint"
DETAIL:  Key (id)=(1) is still referenced from table "chunk_constraint".
CONTEXT:  SQL statement "DELETE FROM _timescaledb_catalog.chunk
    WHERE chunk.id = _chunk_id
    OR chunk.compressed_chunk_id = _chunk_id"
PL/pgSQL function _timescaledb_functions.remove_dropped_chunk_metadata(integer) line 46 at SQL statement
```

### TimescaleDB version affected

2.15

### PostgreSQL version used

14.11

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
- Install old TimescaleDB from Packagecloud repository, on Ubuntu 22.04.
- `sudo apt upgrade`
- `psql mydb -Xc 'ALTER EXTENSION timescaledb UPDATE;'`
```

**Comment by svenklemm** [comment]
On self-hosted you can manually delete the offending entries as a workaround.

```
DELETE FROM chunk_constraint WHERE chunk_id = 1;
```
