### ISSUE TITLE
[Bug]: Unable to change job owner

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb#6941]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

User-Defined Action (UDA)

### What happened?

I need to be able to change ownership of timescaledb background jobs.

Normally I use `REASSIGN OWNED BY X TO Y;` in order to reassign all objects from role X to role Y, and then drop role Y.

Timescaledb jobs aren't handled by this operation, so I needed to do something like this: `UPDATE _timescaledb_config.bgw_job SET owner='Y';` in order for `DROP ROLE` to work without complaining.

However, the jobs still seem to execute with the older owner.

![image](https://github.com/timescale/timescaledb/assets/11539524/fcc23694-fd8d-4a1e-8fbb-18e5da40815c)

However if I manually use `select run_job(1000);` I don't have an issue. So it's most likely from the scheduler side caching the OID that was used at creation time?

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

16.2

### What operating system did you use?

timescaledb-ha

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
- create database D and owner D
- create role X superuser
- (as X) select add_job('xxx', '5s')
- reassign owned by X to D
- UPDATE _timescaledb_config.bgw_job SET owner='D';
- DROP USER X

and you should get errors in the logs every 5 seconds
```

**Comment by mkindahl** [comment]
@jflambert Thank you for the bug report.

I see two problems here:
1. The cache is not updated.
2. Support for handling role renames were added in https://github.com/timescale/timescaledb/pull/5558 but not support for `REASSIGN`, so this should be fixed.

**Comment by jflambert** [comment]
Do you have more info about 1 for me? I have another related problem, that I'd like to log but I want better replication steps.

A similar issue arises when I temporarily alter user X with SUPERUSER, create some jobs, and then alter user X with NOSUPERUSER. This will bypass the REASSIGN, but now the problem I have is that the jobs don't execute (via scheduler) until I restart the postgres process.

**Comment by mkindahl** [comment]
@jflambert #6987 should fix issue 2.
