### ISSUE TITLE
Questions around use of prometheus / timescaleDB integration

### ISSUE THREAD

**Issue by skilyazhnev** [timescale/timescaledb#701]
hi.
I have several hundred node_exporters, 2 prometheus server and 2 postgresql server (master-slave repl + timescaleDB). 
because the adapter for prometheus can`t run on slave postgresql. I have to use master postgresql as remote.read and remote write node. 
And I ran into several problems:
1)  second prometheus (is used only for sampling from the first promeyheus) must select data across first prometheus, but because of the constant recording of the first prometheus the query time tends to infinity. how can I get around this problem? 
2)  large number of sensors create a lot of Data. (the size of the base increased for one day by 150 gb). considering this, size of the standard prometheus base (for 30 days) ~178gb. That is how it should be? if i use timescaleDB?

**Comment by niksajakovljevic** [comment]
Hi @skilyazhnev ,

what version of the adapter are you using? The most recent version (0.3) comes with significant write performance improvements, but we are aware that read performances are still not great. We have plans on improving the read performances too! 
Regarding pointing the adapter toward read replicas, that is something that we can easily fix in our adapter so stay tuned.
 Prometheus uses a lot of compression tricks(delta encoding, variable length encoding, etc..) to make their samples really tiny - I think they claim taking only 2 bytes to store one sample. On the other side we use around 20 bytes per sample, so roughly 10x more disk space is needed. You can try using ZFS with TimescaleDB and that should give you 4x compression. 
Generally speaking we are not aiming to replace Prometheus, but to provide additional features like full SQL support, different integrations and a lot of things you get for  "free" from SQL ecosystem. So it's all about the trade off.

**Comment by niksajakovljevic** [comment]
@skilyazhnev I've created a PR to fix read replica problem. It needs a bit more testing but hopefully it will be out soon. 
https://github.com/timescale/prometheus-postgresql-adapter/pull/41
