### ISSUE TITLE
[Bug]: Upgradee PostgreSQL 15.3 with TS 2.15 to PostgreSQL 16.3 failed

### ISSUE THREAD

**Issue by pgloader** [timescale/timescaledb#7017]
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

Upgradee PostgreSQL 15.3 with TS 2.15 to PostgreSQL 16.3 failed on RHEL8

Performing Consistency Checks
-----------------------------
Checking cluster versions                                     ok
Checking database user is the install user                    ok
Checking database connection settings                         ok
Checking for prepared transactions                            ok
Checking for system-defined composite types in user tables    ok
Checking for reg* data types in user tables                   fatal

Your installation contains one of the reg* data types in user tables.
These data types reference system OIDs that are not preserved by
pg_upgrade, so this cluster cannot currently be upgraded.  You can
drop the problem columns and restart the upgrade.
A list of the problem columns is in the file:
    /var/opt/data/pgsql_data/5432/dat.16.3/pg_upgrade_output.d/20240607T154928.743/tables_using_reg.txt
Failure, exiting
Fri Jun  7 15:49:32 EDT 2024 ERROR: Please verify the upgrade pre-check result and resolve any issues before continue.

tables_using_reg.txt
In database: test
  _timescaledb_catalog.continuous_aggs_bucket_function.bucket_func

### TimescaleDB version affected

2.15.0

### PostgreSQL version used

16.3

### What operating system did you use?

Red Hat Enterprise Linux release 8.6 (Ootpa)

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
In database: test
  _timescaledb_catalog.continuous_aggs_bucket_function.bucket_func
```

### How can we reproduce the bug?

```bash
run pg_upgrade
```

**Comment by fabriziomello** [comment]
@pgloader this issue was fixed on [2.15.1](https://github.com/timescale/timescaledb/releases/tag/2.15.1). Anyway I strongly recommend you to update to [2.15.2](https://github.com/timescale/timescaledb/releases/tag/2.15.2) becuase of a pontential catalog corruption we found and fixed.
