### ISSUE TITLE
How to perform linear interpolation?

### ISSUE THREAD

**Issue by nieyuan1980** [timescale/timescaledb#7028]
### What type of enhancement is this?

API improvement

### What subsystems and features will be improved?

Gapfill

### What does the enhancement do?

There is a water meter, and the collector records the reading every hour. The data is as follows:

![捕获1](https://github.com/timescale/timescaledb/assets/25432482/2e3d3a97-2200-41ea-b8f8-410dcadc62b8)

It can be seen that there is missing data at 06:00, 07:00, 08:00, and 09:00. How to linearly interpolate the missing data?

**Comment by melicheradam** [comment]
Have you tried this? https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/

Straight from the docs
```
SELECT time_bucket_gapfill('1 hour', time) AS time,
    interpolate(max(value)) as max_reading
    GROUP BY time
    ORDER BY time;
```

**Comment by svenklemm** [comment]
The documentation for interpolate has examples how to do this: https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill#interpolate
