### ISSUE TITLE
[Bug]: SSL connections are not supported using timescaledb

### ISSUE THREAD

**Issue by Abhi4356-S** [timescale/timescaledb#7119]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Telemetry

### What happened?

I have postgresql 14.4. I tried to build timescaledb from source using ./bootstrap -DPG_CONFIG=$PG_CONFIG. It gave below error.

-- Compiling against PostgreSQL version 14.4
-- Assertion checks are OFF
-- Looking for USE_OPENSSL
-- Looking for USE_OPENSSL - not found
CMake Error at CMakeLists.txt:564 (message):
  PostgreSQL was built without OpenSSL support, which TimescaleDB needs for
  full compatibility.  Please rebuild PostgreSQL using `--with-openssl` or if
  you want to continue without OpenSSL, re-run bootstrap with
  `-DUSE_OPENSSL=0`
  
build was successful when I used ./bootstrap -DPG_CONFIG=$PG_CONFIG -DUSE_OPENSSL=0

After the extension is created in the same postgresql 14.4, I get this error

message: LOG:  TimescaleDB background worker launcher connected to shared catalogs
message: -WARNING:  
message: 	WELCOME TO
message: 	 _____ _                               _     ____________  
message: 	|_   _(_)                             | |    |  _  \ ___ \ 
message: 	  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
message: 	  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
message: 	  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
message: 	  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
message: 	               Running version 2.13.1
message: 	For more information on TimescaleDB, please visit the following links:
message: 	
message: 	 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
message: 	 2. API reference documentation: https://docs.timescale.com/api/latest
message: 	
message: 	Note: TimescaleDB collects anonymous reports to better understand and assist our users.
message: 	For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.
message: 	
message: -CONTEXT:  PL/pgSQL function inline_code_block line 16 at RAISE
message: LOG:  job 1 threw an error
message: ERROR:  SSL connections are not supported
message: HINT:  Enable SSL support when compiling the extension.
message: LOG:  background worker "Telemetry Reporter [1]" (PID 611525) exited with exit code 1

It suggested me to build without OpenSSL. Why does it hints to enable SSL support when compiling the extension now? Any suggestions to make it work?

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

14.4

### What operating system did you use?

Ubuntu 22.04.4 LTS

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
-------
```

**Comment by svenklemm** [comment]
Our telemetry functions use SSL, if you disable telemetry the error should disappear, no other feature will be affected by not having SSL enabled.

**Comment by Abhi4356-S** [comment]
Thanks. It worked.
