### ISSUE TITLE
[Bug]: Unknown symbol ts_guc_cagg_max_individual_materializations

### ISSUE THREAD

**Issue by bithead2k** [timescale/timescaledb#7129]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Build system

### What happened?

Attempted to do a compile for CommunityLicense.   Compile came through clean and reported timescaledb-sl1.
make && sudo make install also completed cleanly.
Added timescaledb to shared_preload_libraries
rebooted pg successfully,
psql mydatabase \dx

```
 \dx
ERROR:  could not load library "/usr/local/postgres/15.3/lib/timescaledb-2.15.3.so": /usr/local/postgres/15.3/lib/timescaledb-2.15.3.so: undefined symbol: ts_guc_cagg_max_individual_materializations
```

### TimescaleDB version affected

2.15.3

### PostgreSQL version used

15.3

### What operating system did you use?

OEL 8.6

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
There were no errors in the build, and the log says the same error as the output message in the terminal.
```

### How can we reproduce the bug?

```bash
I think you can reproduce this on Oracle Enterprise Linux on a VM in AWS with a clean build.
```

**Comment by bithead2k** [comment]
Turns out that the existing system was not clean.   There was an Apache installation from PGDG there, and he removal failed. 
The .so from 2.15.3 was left behind.

**Comment by akuzm** [comment]
> Turns out that the existing system was not clean. There was an Apache installation from PGDG there, and he removal failed.
The .so from 2.15.3 was left behind.

Good to know, I'll close the issue then.
