### ISSUE TITLE
[Bug]: ERROR:  unrecognized parameter namespace "timescaledb" when executing example code

### ISSUE THREAD

**Issue by bithead2k** [timescale/timescaledb#7158]
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Compression

### What happened?

CREATE TABLE rides (id bigserial primary key, vendor_id bigint, pickup_datetime timestamptz, origination text, destination text, customer_id bigint);
CREATE TABLE

ALTER TABLE rides
SET (
    timescaledb.compress,
    timescaledb.compress_segmentby='vendor_id',
    timescaledb.compress_orderby='pickup_datetime DESC'
);
ERROR:  unrecognized parameter namespace "timescaledb"

### TimescaleDB version affected

2.16.0-dev (2.15.3?)

### PostgreSQL version used

15.6

### What operating system did you use?

Oracle Enterprise Linux 9.3 and 8.9

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Install OEL 9.3
sudo yum -y install cmake
...Install the PGDG repo...
...Install PostgreSQL 15.6...
...Create clean cluster...
...CREATE DATABASE...
...CREATE TABLE...
sudo dnf install redhat-rpm-config
git clone https://github.com/timescale/timescaledb
./bootstrap -DAPACHE_ONLY=0
cd build
make
sudo make install
...configure postgresql.conf...
load_preshared_libraries='timescaledb'
restart PG
\c newdatabase
ALTER TABLE rides
SET (
    timescaledb.compress,
    timescaledb.compress_segmentby='vendor_id',
    timescaledb.compress_orderby='pickup_datetime DESC'
);
ERROR:  unrecognized parameter namespace "timescaledb"
```

**Comment by fabriziomello** [comment]
@bithead2k compression only work against hypertables. First you should turn your regular Postgres table into a hypertable using the `create_hypertable` API.

**Comment by bithead2k** [comment]
Hello Fabrizio!  Thanks for that.   Can't believe I missed a simple step.   Hope this error helps somebody else.

**Comment by fabriziomello** [comment]
> Hello Fabrizio! Thanks for that. Can't believe I missed a simple step. Hope this error helps somebody else.

Hey mate... no worries. Good to know you still using TimescaleDB. Thanks for reaching out. Closing this issue!
