### ISSUE TITLE
Hypertable ID serial increments although no table created

### ISSUE THREAD

**Issue by erimatnor** [timescale/timescaledb#72]
If `create_hypertable()` is run on an existing hypertable, the hypertable serial ID is still incremented. Although not strictly a bug, it is something we might want to avoid in order to not eat a lot of IDs. For instance, one could first check for an existing hypertable before incrementing the ID.

**Comment by dianasaur323** [comment]
@erimatnor is this still an issue that you think we should address? If not, we can close out. If yes, what would the priority of this be in your mind?

**Comment by svenklemm** [comment]
This seems fixed in recent versions.
```
dev=# select  * from _timescaledb_catalog.hypertable_id_seq;
 last_value | log_cnt | is_called
------------+---------+-----------
          9 |      32 | t
(1 row)

Time: 1.458 ms
dev=# select create_hypertable('metrics','time');
ERROR:  TS110: table "metrics" is already a hypertable
LOCATION:  ts_hypertable_create_from_info, hypertable.c:2006
Time: 12.065 ms
dev=# select  * from _timescaledb_catalog.hypertable_id_seq;
 last_value | log_cnt | is_called
------------+---------+-----------
          9 |      32 | t
(1 row)
```
