### ISSUE TITLE
[Flaky test] Isolation test reorder_vs_select fails with a timeout

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#7206]
### Which test is flaky?

reorder_vs_select

### Since when has the test been flaky?

August 19, 2024

### Link to the failed test run

https://github.com/timescale/timescaledb-private/actions/runs/10449859264/job/28933033398?pr=1186

### Log output

```bash
diff -u /home/runner/work/timescaledb-private/timescaledb-private/tsl/test/isolation/expected/reorder_vs_select.out /home/runner/work/timescaledb-private/timescaledb-private/build/tsl/test/isolation/results/reorder_vs_select.out
--- /home/runner/work/timescaledb-private/timescaledb-private/tsl/test/isolation/expected/reorder_vs_select.out	2024-08-19 08:26:46.103856265 +0000
+++ /home/runner/work/timescaledb-private/timescaledb-private/build/tsl/test/isolation/results/reorder_vs_select.out	2024-08-19 08:36:11.686648575 +0000
@@ -85,13 +85,7 @@
 step S1: SELECT * FROM ts_reorder_test; <waiting ...>
 step Rc: COMMIT;
 step S1: <... completed>
-time|temp|location
-----+----+--------
-   1|23.4|       1
-  11|21.3|       2
-  21|19.5|       3
-(3 rows)
-
+ERROR:  canceling statement due to lock timeout
 step Sc: COMMIT;
 
 starting permutation: Bc R1 S1 Sc Rc
```

### Reason for flakiness

Timeout set too low, so a long-running test will cancel the statement rather than wait for it to finish, leading to flakes.

**Comment by mkindahl** [comment]
https://github.com/timescale/timescaledb-private/actions/runs/11107864760/job/30859511740?pr=1236

**Comment by svenklemm** [comment]
We decided during last retro to stop opening issues for flaky tests. We have a test result database that you can query to check for flaky tests.
