### ISSUE TITLE
Windows installation question/issue, PostGres 10.4

### ISSUE THREAD

**Issue by apiszcz** [timescale/timescaledb#721]
pg_config is in the the path and displays the environment variables.

```
> pg_config --pkglibdir
c:/x/test/lib/pgsql/lib
```

The Timescaledb setup.exe states otherwise.

2018/09/15 12:10:32 Could not get `pg_config --pkglibdir`: exec: "pg_config": executable file not found in %PATH%
Press ENTER/Return key to close...

Are there other install options available, perhaps .zip for manual installation, letting the user copy the folders/files to the pgsql bin and other folders? 

Thank you.

**Comment by apiszcz** [comment]
Setting the global user PATH to the Postgres bin directory resolved the issue.
However it would be good to log or display to the user where the files are installed on the system.

2018/09/15 12:23:43 Installing TimescaleDB library files...
2018/09/15 12:23:43 Success!
2018/09/15 12:23:43 Installing TimescaleDB control file...
2018/09/15 12:23:43 Success!
2018/09/15 12:23:43 Installing TimescaleDB SQL files...
2018/09/15 12:23:44 Success!
TimescaleDB installation completed successfully.
Press ENTER/Return key to close...

**Comment by apiszcz** [comment]
The install locations appear to be as follows.
A zip file with these folders could be another method for distribution on windows.


./lib/timescaledb-0.9.2.dll
./lib/timescaledb.dll
./share/extension/timescaledb--0.1.0--0.9.2.sql
./share/extension/timescaledb--0.2.0--0.9.2.sql
./share/extension/timescaledb--0.3.0--0.9.2.sql
./share/extension/timescaledb--0.4.0--0.9.2.sql
./share/extension/timescaledb--0.4.1--0.9.2.sql
./share/extension/timescaledb--0.4.2--0.9.2.sql
./share/extension/timescaledb--0.5.0--0.9.2.sql
./share/extension/timescaledb--0.6.0--0.9.2.sql
./share/extension/timescaledb--0.6.1--0.9.2.sql
./share/extension/timescaledb--0.7.0--0.9.2.sql
./share/extension/timescaledb--0.7.1--0.9.2.sql
./share/extension/timescaledb--0.8.0--0.9.2.sql
./share/extension/timescaledb--0.9.0--0.9.2.sql
./share/extension/timescaledb--0.9.1--0.9.2.sql
./share/extension/timescaledb--0.9.2.sql
./share/extension/timescaledb.control

**Comment by arul67800** [comment]
needs fix at the installation level...
