### ISSUE TITLE
Windows distribution is 0.92 not 1.0?

### ISSUE THREAD

**Issue by apiszcz** [timescale/timescaledb#722]
Installed and running through tutorial I note the version is 0.9.2 not 1.0. Is 1.0 available for the windows installer?

```

nyc_data-# FROM pg_extension;
   extname   | extowner | extnamespace | extrelocatable | extversion |
-------------+----------+--------------+----------------+------------+---------------------------------------------------------------------------------------+---------------------------------------------
 plpgsql     |       10 |           11 | f              | 1.0        |                                                                                       |
 timescaledb |       10 |         2200 | f              | 0.9.2      |
```

**Comment by mfreed** [comment]
Hi @apiszcz:  Do you mean when *you* ran the tutorial from the latest Windows distribution, or just what's in our tutorial's text?

If the former, we have (purposefully) not released our 1.0 release candidate for all binary distribution channels; currently its just docker and source for testing.  The latest build available on all channel is the "latest release", which is 0.12.0.  You'll see that here:  https://github.com/timescale/timescaledb/releases

If the latter, we just don't rewrite all the tutorials/examples whenever a new release is made.  Is it confusing in some way?

**Comment by apiszcz** [comment]
1. I stepped through the NYC tutorial and it worked fine.

2. Offering a second method for install instead of the setup.exe.
   Copy required files to share and .dlls to lib.

3. 1.0-rc1 understand, so 1.0 should happen in the next month or so.

Thank you for the response.

**Comment by mfreed** [comment]
Sorry, I don't quite understand your answer...

**Comment by apiszcz** [comment]
close.
