### ISSUE TITLE
[Bug]: Insert into hypertable referenced by foreign key gives error

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#7226]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Partitioning

### What happened?

When creating an auxiliary table and referencing a hypertable using a foreign key, it raises the error "index for constraint not found on chunk".

### TimescaleDB version affected

2.16.0-dev

### PostgreSQL version used

16.4

### What operating system did you use?

Ubuntu 24.04.1 LTS

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  XX000: index for constraint not found on chunk
DETAIL:  Assertion 'OidIsValid(indexoid)' failed.
LOCATION:  clone_constraint_on_chunk, foreign_key.c:164
```

### How can we reproduce the bug?

```bash
CREATE TABLE conditions (
    time TIMESTAMPTZ NOT NULL,
    device_id INT NOT NULL,
    temperature DOUBLE PRECISION NULL,
    PRIMARY KEY (device_id, time)  -- Composite primary key
);

-- create hypertable
SELECT create_hypertable('conditions', 'time');

CREATE TABLE valid_conditions (
    time TIMESTAMPTZ NOT NULL,
    device_id INT NOT NULL,
    note TEXT,
    CONSTRAINT fk_conditions
    FOREIGN KEY (time, device_id) REFERENCES conditions(time, device_id)  -- Foreign key constraint
);

-- test insert
INSERT INTO conditions (time, device_id, temperature) VALUES
    ('2024-08-29 12:00:00+00', 1, 22.5),
    ('2024-08-29 13:00:00+00', 2, 24.0);
```

**Comment by svenklemm** [comment]
Currently the code expects the constraint and the index to be defined the same, in your example the primary key and the constraint have the opposite column order
