### ISSUE TITLE
[Bug]: `drop_chunks` and `_timescaledb_functions.drop_chunk` don't respect FKs against `_timescaledb_catalog.chunk`

### ISSUE THREAD

**Issue by brasic** [timescale/timescaledb#7269]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Other

### What happened?

Our application needs to keep an index on a set of per-chunk values stored in compressed hypertable chunks. These values should be dropped when the chunk is dropped, so we created a foreign key from our table to the `_timescaledb_catalog.chunk` table. But when timescale drops chunks either on policy-driven schedule or manually via `public.drop_chunks`/`_timescaledb_functions.drop_chunk`, the foreign key constraint is not respected: chunk ids that are no longer valid continue to exist in the referencing table rather than being deleted on cascade as one would expect.

### TimescaleDB version affected

2.16.1

### PostgreSQL version used

16.3

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Deb/Apt, Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE metrics (
  time timestamptz NOT NULL
);
SELECT create_hypertable('metrics', 'time');
CREATE TABLE chk_ref (
  chunk_id integer NOT NULL REFERENCES _timescaledb_catalog.chunk(id) ON DELETE CASCADE
);
INSERT into metrics(time) values(now()); -- now one chunk exists
INSERT INTO chk_ref(chunk_id) select id from _timescaledb_catalog.chunk;
select drop_chunks('metrics', created_before => now()); -- drops the only chunk,
-- _timescaledb_catalog.chunk is now empty, so should any table referencing it
select * from chk_ref; -- should be empty, instead returns id of nonexistent chunk:
                       --   chunk_id
                       --  ----------
                       --           1
                       --  (1 row)
-- You can also see the issue by forcing a constraint violation like:
insert into chk_ref (chunk_id) select chunk_id from chk_ref;
-- ERROR:  insert or update on table "chk_ref" violates foreign key constraint "chk_ref_chunk_id_fkey"
-- DETAIL:  Key (chunk_id)=(1) is not present in table "chunk".
```

**Comment by mkindahl** [comment]
@brasic The table you create a foreign key on is a catalog table and even if it is theoretically possible to have foreign keys on catalog tables, this is usually not what you do. It is not even possible to create a foreign key on a PostgreSQL table.

Since chunks are just tables it should be possible to register an event trigger on drop and modify your `chk_ref` table there, something like this:

```sql
create table metrics (time timestamptz not null);
select create_hypertable('metrics', 'time');
insert into metrics(time) values(now());

create table chk_ref (chunk_schema text, chunk_name text);
insert into chk_ref values ('public', 'one'), ('public', 'two'), ('public', 'three');

create function unregister_chunk()
        returns event_trigger language plpgsql as $$
declare
    obj record;
begin
    for obj in select * from pg_event_trigger_dropped_objects()
    loop
        if obj.object_type = 'table' then
	   delete from chk_ref where chunk_schema = obj.schema_name and chunk_name = obj.object_name;
	end if;
    end loop;
end;
$$;

create event trigger chunk_drops ON sql_drop EXECUTE FUNCTION unregister_chunk();

select drop_chunks('metrics', created_before => now()); -- drops the only chunk,
```

Unfortunately, dropped chunks are registered using `EventTriggerSQLDropAddObject`, but the `EventTriggerSQLDrop` that does the actual trigger call is not called at the end of the statement.

Right now your best bet is to replace the `drop_chunks` function with your own version and let it unregister the chunk. Unfortunately, it does not solve the problem of registering the chunk when it is created.

**Comment by svenklemm** [comment]
TimescaleDB catalog tables work similar to postgres system tables in that regard and internal modifications do not trigger constraint checks.

**Comment by brasic** [comment]
I see. Thanks for the information!
