### ISSUE TITLE
build 1.0.0-rc1 failed on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by shuge** [timescale/timescaledb#728]
Environment
   
    ubuntu 16.04
    postgresql 10.5
    cmake 3.5.1
    timescaledb 1.0.0-rc1

Output

	[  1%] Built target sqlfile
	[ 24%] Built target sqlupdatescripts
	[ 25%] Building C object src/CMakeFiles/timescaledb.dir/net/conn_ssl.c.o
	In file included from /opt/postgresql-10.5/include/server/c.h:1166:0,
					 from /opt/postgresql-10.5/include/server/postgres.h:47,
					 from /home/ubuntu/downloads/timescaledb/src/net/conn_ssl.c:1:
	/opt/postgresql-10.5/include/server/port.h:422:40: error: expected identifier or ‘(’ before numeric constant
	 #define SSL_get_current_compression(x) 0
											^
	src/CMakeFiles/timescaledb.dir/build.make:1363: recipe for target 'src/CMakeFiles/timescaledb.dir/net/conn_ssl.c.o' failed
	make[2]: *** [src/CMakeFiles/timescaledb.dir/net/conn_ssl.c.o] Error 1
	CMakeFiles/Makefile2:310: recipe for target 'src/CMakeFiles/timescaledb.dir/all' failed
	make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
	Makefile:127: recipe for target 'all' failed
	make: *** [all] Error 2

**Comment by RobAtticus** [comment]
This seems to happen when PostgreSQL was not configured with OpenSSL support. Are you using a pre-packaged version of PostgreSQL or did you build it from source?

You could also try installing `libssl-dev` and see if that helps.

**Comment by shuge** [comment]
Yep, rebuilt it with openssl and everything works as expected

    PREFIX=/opt/postgresql-10.5
    make clean &&  ./configure --prefix=$PREFIX --with-openssl && make && make install
