### ISSUE TITLE
[Bug]: ERROR:  could not access file "$libdir/timescaledb-tsl-2.11.2": No such file or directory

### ISSUE THREAD

**Issue by bagafoot** [timescale/timescaledb#7313]
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression

### What happened?

Hello when I try add compression policy it errors 
`SELECT add_compression_policy('bs_log', compress_after => INTERVAL '6 months');`
`ERROR:  could not access file "$libdir/timescaledb-tsl-2.11.2": No such file or directory`

There are timescaledb-tsl files but different version.
![image](https://github.com/user-attachments/assets/e3849e74-e884-4e49-b19f-04b3b19551c3)

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

12.20

### What operating system did you use?

centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
just installed yum install timescaledb_12.x86_64
change  timescaledb.license = 'timescale' (apache was default)
create a hyper_table and try to compress.
```

**Comment by svenklemm** [comment]
Seems like you are not installing packages provided by timescale.

This is the package you need to install: https://packagecloud.io/timescale/timescaledb/packages/el/7/timescaledb-2-postgresql-12-2.11.2-0.el7.x86_64.rpm?distro_version_id=140

**Comment by bagafoot** [comment]
thank you thats works for me

**Comment by svenklemm** [comment]
Seems to be resolved.
