### ISSUE TITLE
[Bug]: PostgreSQL 14 not working after TimescaleDb 2.17.0 installation

### ISSUE THREAD

**Issue by mike-lock** [timescale/timescaledb#7347]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

After the installation of TimescaleDb 2.17.0, PG14 doesn't start anymore.

This is the log in the eventviewer:
` FATAL:  could not load library "C:/Program Files/PostgreSQL/14/lib/timescaledb.dll": The specified procedure could not be found.`

The dll does exist in the mentioned location.

### TimescaleDB version affected

2.17.0

### PostgreSQL version used

14.11

### What operating system did you use?

Windows 11

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
FATAL:  could not load library "C:/Program Files/PostgreSQL/14/lib/timescaledb.dll": The specified procedure could not be found.
```

### How can we reproduce the bug?

```bash
Install PostgreSQL 14 with an older TimescaleDb
It'll run normally
Stop PostgreSQL 
Install TimescaleDb 2.17.0
Start PostgreSQL 
It now refuses to start
```

**Comment by svenklemm** [comment]
Which version of postgresql 14 are you using. Might be an incompatibility with used ssl version

**Comment by mike-lock** [comment]
> Which version of postgresql 14 are you using. Might be an incompatibility with used ssl version

PostgreSQL 14.11

**Comment by mike-lock** [comment]
Not sure if this is related. But this is the only thing not right when using Dependencies:

![image](https://github.com/user-attachments/assets/f867366d-a16e-45f9-8f68-88ebae99349e)

A google search quickly pointed out that this function is added to PG15.

**Comment by mike-lock** [comment]
I feel so stupid. I downloaded the version for PostgreSQL 17, after downloading the PG14 version it works beautifully.
