### ISSUE TITLE
[Bug]: compressed table size after heavy updates

### ISSUE THREAD

**Issue by t-aistleitner** [timescale/timescaledb#7357]
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

## Problem

Frequent updates to rows in already compressed chunks cause the chunk size to increase. Manually compressing the chunks or relying on the compression policy does not reduce the size back again.

## Example:

**1. Create table and hypertable**

```sql
create table if not exists test_compression (id INT not null,
							date TIMESTAMP not null,
							value INT not null);

create unique index test_compression_idx on test_compression (id, date);

SELECT create_hypertable('test_compression', by_range('date', INTERVAL '1 day'), create_default_indexes => False);
ALTER TABLE test_compression SET (timescaledb.compress, timescaledb.compress_orderby = 'date DESC', timescaledb.compress_segmentby = 'id');
```

**2. Fill table with data**
```sql
INSERT INTO test_compression (id, date, value)
SELECT
    id_val,
    time_val,
    (random()*100)::INT
FROM
    generate_series('2024-10-15 00:00:00'::timestamp, '2024-10-16 23:59:59'::timestamp, '10 minutes') AS time_val
CROSS JOIN
    generate_series(1, 20000) AS id_val;
```

**3. Check size of cunks**
```sql
SELECT c.chunk_name , to_char(range_start, 'YYYYMMDD') as date, pg_size_pretty(total_bytes) as size, is_compressed FROM 
chunks_detailed_size('test_compression ') d, timescaledb_information.chunks c WHERE c.chunk_name = d.chunk_name
ORDER BY date desc;
```

| table_name       | chunk_name            | date     | size   | is_compressed |
|------------------|-----------------------|----------|--------|---------------|
| test_compression | _hyper_279_2975_chunk | 20241016 | 256 MB | false         |
| test_compression | _hyper_279_2974_chunk | 20241015 | 256 MB | false         |

**4. Compress a chunk**
```sql
select compress_chunk(i) from show_chunks('test_compression', older_than => '2024-10-16') i
```

| table_name       | chunk_name            | date     | size    | is_compressed |
|------------------|-----------------------|----------|---------|---------------|
| test_compression | _hyper_279_2975_chunk | 20241016 | 256 MB  | false         |
| test_compression | _hyper_279_2974_chunk | 20241015 | 7176 kB | true          |

**5. Bulk updates**

```sql
set timescaledb.max_tuples_decompressed_per_dml_transaction = 0;
update test_compression set date = '2024-10-15 00:01' where id in (select generate_series(1,1000, 1)) and date = '2024-10-15 00:00';
```

| table_name       | chunk_name            | date     | size   | is_compressed |
|------------------|-----------------------|----------|--------|---------------|
| test_compression | _hyper_279_2975_chunk | 20241016 | 256 MB | false         |
| test_compression | _hyper_279_2974_chunk | 20241015 | 307 MB | true          |

I understand that the table size temporarily increases because many rows need to be decompressed. However, the issue is that I cannot recompress the chunk, and the compression policy does not compress it again either and it is still considered as compressed.

This is of course an extreme example, but in our software, we need to update or insert data in compressed chunks, far back in the data history. The size does not exceed as much as in this example, but it is still noticeable when you have a lot of chunks.

I'm not sure if this is a bug or intended behavior. One possible solution would be to decompress and recompress all chunks, but this would put a heavy load on the database and our software.

Thank you in advance for your help!

### TimescaleDB version affected

2.17

### PostgreSQL version used

14.13

### What operating system did you use?

Ubuntu 20.04.6 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
create table if not exists test_compression (id INT not null,
							date TIMESTAMP not null,
							value INT not null);

						
create unique index test_compression_idx on test_compression (id, date);

SELECT create_hypertable('test_compression', by_range('date', INTERVAL '1 day'), create_default_indexes => False);
ALTER TABLE test_compression SET (timescaledb.compress, timescaledb.compress_orderby = 'date DESC', timescaledb.compress_segmentby = 'id');
INSERT INTO test_compression (id, date, value)
SELECT
    id_val,
    time_val,
    (random()*100)::INT
FROM
    generate_series('2024-10-15 00:00:00'::timestamp, '2024-10-16 23:59:59'::timestamp, '10 minutes') AS time_val
CROSS JOIN
    generate_series(1, 20000) AS id_val;
select compress_chunk(i) from show_chunks('test_compression', older_than => '2024-10-16') i;
select * from  show_chunks('test_compression', older_than => '2024-10-16');
set timescaledb.max_tuples_decompressed_per_dml_transaction = 0;
update test_compression set date = '2024-10-15 00:01' where id in (select generate_series(1,1000, 1)) and date = '2024-10-15 00:00';
```

**Comment by antekresic** [comment]
Compression policy should recompress the updated rows into compress format but it does not immediately release the storage because it has to delete the tuples one by one (which is a key differentiator vs initial compression). I would try vacuuming the chunk after recompression to get rid of the dead tuples, that should reduce the size.

That said, the current implementation of recompression does also create some unnecessary bloat. There is ongoing work at this moment to improve the situation here so I would expect improvements to be released with one of the next minor releases.

**Comment by t-aistleitner** [comment]
Thank you very much for your input. A "full vacuum" indeed reduces the size again, even if I manually compress the chunk beforehand. This resolves my issue. Thanks!
