### ISSUE TITLE
[Bug]: pg_restore cannot restore data correctly after running timescaledb_post_restore, but the right data when running timescaledb_pre_restore

### ISSUE THREAD

**Issue by ruoshui1314** [timescale/timescaledb#7383]
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Backup, Restore

### What happened?

1. running pg_dump to dump database: `pg_dump -h localhost -U username -p 5434 -Fc -f vnpy.back vnpy`
2. running pg_restore to restore database to another machine with the same version of postgresql and timescaledb.
```
CREATE DATABASE vnpy;
\c vnpy
CREATE EXTENSION IF NOT EXISTS timescaledb;
SELECT timescaledb_pre_restore();
\! pg_restore -U postgres --no-owner -Fc -v -d vnpy vnpy.back
SELECT timescaledb_post_restore();
```

3. result:
There is no any data after running 'SELECT timescaledb_post_restore()', but I can get the data when running 'SELECT timescaledb_pre_restore();'
details:
![image](https://github.com/user-attachments/assets/0bd5996f-3967-4240-9b57-07eadb104f35)

### TimescaleDB version affected

2.17.0

### PostgreSQL version used

14.13

### What operating system did you use?

ubuntu 20.04

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
In my environment, the issue is inevitable following steps as above.
How to restore database correctly, please give me advices?
```

**Comment by ruoshui1314** [comment]
Anyone could help ?

**Comment by ruoshui1314** [comment]
I just drop database and do it again, but it still dost not work.

**Comment by antekresic** [comment]
Can you look at and post explain plans before and after  post restore?

```
explain select count(*) from bar_data_1m;
```

**Comment by ruoshui1314** [comment]
before post restore:
![image](https://github.com/user-attachments/assets/1c8360eb-ddfc-41a0-8cfb-d25bc64c3ba6)
after post restore:
![image](https://github.com/user-attachments/assets/682e9d5d-e7df-4b54-a204-9e57d167ae3e)
please help to check...

**Comment by ruoshui1314** [comment]
> Can you look at and post explain plans before and after post restore?
> 
> ```
> explain select count(*) from bar_data_1m;
> ```

results:
before post restore:
![image](https://github.com/user-attachments/assets/1c8360eb-ddfc-41a0-8cfb-d25bc64c3ba6)
after post restore:
![image](https://github.com/user-attachments/assets/682e9d5d-e7df-4b54-a204-9e57d167ae3e)
please help to check...

**Comment by antekresic** [comment]
There is something we are missing here, I have tried doing what you are doing and for me the behavior is opposite. I don't see any rows before post restore and see them after post restore.

Is there anything else you did? Could you do an explain with analyze? Maybe that can give us some hints whats going on here.

**Comment by ruoshui1314** [comment]
> There is something we are missing here, I have tried doing what you are doing and for me the behavior is opposite. I don't see any rows before post restore and see them after post restore.
> 
> Is there anything else you did? Could you do an explain with analyze? Maybe that can give us some hints whats going on here.

I create table and database before "SELECT timescaledb_pre_restore();".
![image](https://github.com/user-attachments/assets/ed44665b-cd9d-47f1-bfc2-3bee4be527c7)

**Comment by ruoshui1314** [comment]
> I don't think you need create tables and run `create_hypertable` in step 2.
> 
> Can you just try without that? Just run on server B:
> 
> ```
> CREATE DATABASE vnpy;
> \c vnpy
> CREATE EXTENSION IF NOT EXISTS timescaledb;
> SELECT timescaledb_pre_restore();
> \! pg_restore -U postgres --no-owner -Fc -v -d vnpy vnpy.back
> SELECT timescaledb_post_restore();
> ```

It works, but there another message. "ERROR:  table "bar_data" is already partitioned\nDETAIL:  It is not possible to turn tables that use inheritance into hypertables.\n

**Comment by antekresic** [comment]
This seems like bar_data_1m is still created before you run pg_restore. Make sure you don't create it manually or drop it if already exists.

**Comment by antekresic** [comment]
This is what I'm suggesting, don't create the table or hypertable, the restore step will do that for you.

**Comment by ruoshui1314** [comment]
> This is what I'm suggesting, don't create the table or hypertable, the restore step will do that for you.

ok.thank you for your support...

**Comment by ruoshui1314** [comment]
> This is what I'm suggesting, don't create the table or hypertable, the restore step will do that for you.

Sorry to open this issue and please help.There are some extract incremental datas from Server A that I need to sync it to Server B.
I use `psql -h "x.x.x.x" -d $DB_NAME -U $DB_USER -c "\copy (SELECT * FROM $TABLE WHERE datetime>='$SPECIAL_TIME') TO '$CSV_FILE' CSV HEADER;"` to generate csv files due to the data not big.
Run `psql -d $DB_NAME -U $DB_USER -c "\COPY $TABLE FROM '$CSV_FILE' DELIMITER ',' CSV HEADER;"` to restore from csv into database and it reports an error and I can get the incremental data in db.
```
Exporting data from bar_data after 2024-10-21
COPY 2306
WARNING:  function _timescaledb_internal.insert_blocker() is deprecated and has been moved to _timescaledb_functions schema. this compatibility function will be removed in a future version.
ERROR:  insert_blocker: not called by trigger manager
CONTEXT:  PL/pgSQL function _timescaledb_internal.insert_blocker() line 6 at RETURN
COPY bar_data, line 2: "IF2412,CFFEX,IF,1h,2024-10-21 10:00:00,24095,28505346840,153278,3952.8,3975.2,3911,3915.4,3914.8,391..."
Exporting data from io_bar_data after 2024-10-21
COPY 6260
```

But I can find these data in csv so there are some incremental datas actually.

**Comment by ruoshui1314** [comment]
> This is what I'm suggesting, don't create the table or hypertable, the restore step will do that for you.

Another question is that tables is not hypertable anymore  when use pg_restore tools to restore data in Server B.
`SELECT * FROM timescaledb_information.hypertables;`
This information is from server A:
![image](https://github.com/user-attachments/assets/b218ebd8-e5df-4e8d-bb0f-cefdc5cf19e5)

but not in Server B
![image](https://github.com/user-attachments/assets/e314047c-5f5a-4d44-a38b-08ed42d70ae2)

How can I restore data from Server A corretly?

**Comment by antekresic** [comment]
I don't think your dump is OK then. There should be hypertables when you restore.

Please take a look at our documentation on how to do dump/restore properly and follow the exact steps:
https://docs.timescale.com/self-hosted/latest/migration/entire-database/

**Comment by ruoshui1314** [comment]
> I don't think your dump is OK then. There should be hypertables when you restore.
> 
> Please take a look at our documentation on how to do dump/restore properly and follow the exact steps: https://docs.timescale.com/self-hosted/latest/migration/entire-database/

Maybe I know the reason. The timescaledb version in Server A is 2.8.1 but version in Server B is 2.17.1.Could you please help 
 to check if it is possible to upgrade timescaledb from 2.8.1 to 2.17.1 directly?
