### ISSUE TITLE
[Bug]: Error while compressing a newly inserted chunk with chunk skipping enabled, but works with chunk skipping disabled

### ISSUE THREAD

**Issue by kunjmehta** [timescale/timescaledb#7496]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression, Other

### What happened?

These are the steps I followed:

I have a hypertable **H** with chunks at intervals of 1 day with existing chunk **X** and columns that is uncompressed. Lets say the existing data is from date October 10, 2024. I add a new blank integer column **C** to this table in anticipation of some new data that has to be inserted into this table that has this column. Every other column remains the same.

Now, I add this new data dated, lets say September 18, 2024 into this hypertable that forms a separate chunk **Y**. The column **C** has data for chunk **Y** but is NULL for chunk **X**.

I alter the table to enable compression with segment set to some other column **D**. Now, if I enable chunk skipping on **C** and call `compress_chunk(X)`, I can see that the values in `_timescaledb_catalog.chunk_column_stats` reflect that minimum and maximum values for **C** in **X**.

However, calling `compress_chunk(Y)` results in the below error. I would have expected it to have the same behaviour as when calling `compress_chunk(X)`

_Other things I have been able to rule out:_
Calling `compress_chunk(X)` and `compress_chunk(Y)` before enabling chunk skipping is able to compress the chunks successfully. Enabling chunk skipping after compression does not throw an error and can see default values in `range_start` and `range_end` in  `_timescaledb_catalog.chunk_column_stats`

### TimescaleDB version affected

2.17.1

### PostgreSQL version used

16.1

### What operating system did you use?

Red Hat Enterprise Linux 8.10

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
WARNING: No index on <C> found for column range on chunk <Y>
ERROR: type with OID 0 does not exist

SQL State: 42704
```

### How can we reproduce the bug?

```bash
- Have an uncompressed hypertable with some existing chunks
- Add a new blank column
- Add a new chunk to the hypertable that has values for the new column. This means that the new column will be NULL for all older chunks
- Enable compression with a segment on some column other than the new column. 
- Enable chunk skipping on the hypertable on the new column
- Call compress_chunk() on the new chunk
```

**Comment by kunjmehta** [comment]
Hi @erimatnor, my apologies. Not the actual column names (confidentiality) but this is how the schema and statements. Hopefully this is more clear.

DDL
```
CREATE TABLE public.tbl
( 
id text,
col2 text,
date date,
col4 text,
col4_id bigint,
col5 text,
col6 bigint,
col7 double precision,
col8 double precision,
col9 text,
col10 text
);

select create_hypertable('tbl', by_range('date', interval '1 day'));
create index on tbl(id);
cluster table using tbl_id_idx;
```


Commands that lead to the error
```
ALTER TABLE tbl add tbl_new_col integer;
INSERT INTO tbl (select * from tbl2);  -- tbl2 is identical to tbl with additional column tbl_new_col and this insert query inserts data for a date not in tbl, creating a new chunk

ALTER TABLE tbl set (
timescaledb.compress, 
timescaledb.compress_segment_by='col4')

select enable_chunk_skipping (tbl, tbl_new_col)
select compress_chunk(tbl_new_chunk)

```

Changing last statement to `select compress_chunk(tbl_old_chunk)` does not throw an error.

Error:
```
WARNING: No index on tbl_new_col found for column range on chunk tbl_new_chunk
ERROR: type with OID 0 does not exist

SQL State: 42704
```

**Comment by erimatnor** [comment]
@kunjmehta Here's a script I created based on your information. Unfortunately, I don't get the error you experience. I only have one row of data per chunk, but usually that doesn't matter for these types of errors. Can you double-check it, test it on your setup, and possibly modify it to trigger the error:

```sql
CREATE TABLE public.tbl
( 
id text,
col2 text,
date date,
col4 text,
col4_id bigint,
col5 text,
col6 bigint,
col7 double precision,
col8 double precision,
col9 text,
col10 text
);

-- suppose has data for Sep 18, 2024
CREATE TABLE public.tbl2
( 
id text,
col2 text,
date timestamptz,
col4 text,
col4_id bigint,
col5 text,
col6 bigint,
col7 double precision,
col8 double precision,
col9 text,
col10 text,
col11 integer -- this maps to tbl_new_col added to tbl below
);

select create_hypertable('tbl', by_range('date', interval '1 day'));
create index on tbl(id);
cluster tbl using tbl_id_idx;

select create_hypertable('tbl2', by_range('date', interval '1 day'));
create index on tbl2 (id);
cluster tbl using tbl2_id_idx;

insert into tbl values ('1', 'a', '2024-10-10', 'b', 1, 'c', 1, 1.0, 1.0, 'd', 'e');
insert into tbl2 values ('1', 'a', '2024-10-20', 'b', 1, 'c', 1, 1.0, 1.0, 'd', 'e', 1);

ALTER TABLE tbl add tbl_new_col integer;
INSERT INTO tbl select id, col2, date, col4, col4_id, col5, col6, col7, col8, col9, col10 from tbl2;  -- tbl2 is identical to tbl with additional column tbl_new_col and this insert query inserts data for a date not in tbl, creating a new chunk

ALTER TABLE tbl set (
timescaledb.compress, 
timescaledb.compress_segmentby='col4');

set timescaledb.enable_chunk_skipping=on;
select enable_chunk_skipping ('tbl', 'tbl_new_col');


select chunk from show_chunks('tbl') chunk order by chunk desc limit 1 \gset
select compress_chunk(:'chunk');
```

**Comment by kunjmehta** [comment]
Hi @erimatnor, I tested the commands above and tried to reproduce the error. This is what I am doing on my end so the commands you sent are okay but I was not able to reproduce the error. After that, I also tried reproducing on a duplicate of the table causing the issue, and other tables - all work fine. 

Seems like a data corruption issue to me and think we can close this. Thanks for your help!
