### ISSUE TITLE
[Bug]: Regression test cases are failing on Postgresql 15.10

### ISSUE THREAD

**Issue by harinath001** [timescale/timescaledb#7518]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Background worker, Compression, Continuous aggregate

### What happened?

Timescaledb regression test cases are failing when we run `make installcheck`.

Following test cases are failing
```
cagg_errors
cagg_policy
cagg_refresh
cagg_union_view-15
compression
compression_bgw
compression_insert
size_utils_tsl
transparent_decompression-15
```

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

15.10

### What operating system did you use?

RHEL8 x86_64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
diff -u /workspace/extensions/timescaledb/tsl/test/expected/cagg_errors.out /workspace/extensions/timescaledb/build/tsl/test/results/cagg_errors.out
     --- /workspace/extensions/timescaledb/tsl/test/expected/cagg_errors.out	2024-11-21 23:01:44.049264150 +0000
     +++ /workspace/extensions/timescaledb/build/tsl/test/results/cagg_errors.out	2024-11-21 23:12:51.047604809 +0000
     @@ -549,20 +549,18 @@
      NOTICE:  defaulting compress_orderby to bucket
      insert into i2980 select now();
      call refresh_continuous_aggregate('i2980_cagg2', NULL, NULL);
     +ERROR:  invalid input syntax for type timestamp with time zone: "Sun Nov 23 16:07:02 4714 LMT BC" at character 86
      SELECT compress_chunk(ch) FROM show_chunks('i2980_cagg2') ch;
     -             compress_chunk              
     ------------------------------------------
     - _timescaledb_internal._hyper_14_3_chunk
     -(1 row)
     + compress_chunk 
     +----------------
     +(0 rows)
```

### How can we reproduce the bug?

```bash
- yum install postgresql15-server (15.10) and postgresql15-devel 
- ./bootstrap 
- cd build && make 
- cd build && make install
- initialize postgres cluster and add timescaledb to the shared_preload_libraries and start postgres
- cd build && make installcheck
```

**Comment by harinath001** [comment]
also i am suspecting these failures are may be due to this commit recently made to postgres

https://github.com/postgres/postgres/commit/2b94ee58bf256e1b4682f21f13d0f2c73e1b0cc2

and the discussion here, 
https://www.postgresql.org/message-id/flat/0a997455-5aba-4cf2-a354-d26d8bcbfae6%40technowledgy.de

**Comment by erimatnor** [comment]
> also i am suspecting these failures are may be due to this commit recently made to postgres
> 
> [postgres/postgres@2b94ee5](https://github.com/postgres/postgres/commit/2b94ee58bf256e1b4682f21f13d0f2c73e1b0cc2)
> 
> and the discussion here, https://www.postgresql.org/message-id/flat/0a997455-5aba-4cf2-a354-d26d8bcbfae6%40technowledgy.de

Yes, pretty sure this is the reason. We've updated recent versions on TimescaleDB to handle these upstream PG changes. TimescaleDB 2.12 is pretty old by now so we recommend updating to a newer TimescaleDB version.
