### ISSUE TITLE
Function to Pre-Emptively Create Hypertable Leading Edge Chunks

### ISSUE THREAD

**Issue by jbylund** [timescale/timescaledb#752]
Transactions which would create new chunks in a hypertable lock the chunk until the transaction either commits or rolls back.  This can cause contention at the leading edge of a hypertable if there are a lot of transactions which would want to operate on those chunks.  It might be useful to have a function related to `drop_chunks` which creates chunks on the leading edge of the hypertable.  Maybe something along the lines of `create_chunks` which accepts an interval for the span of chunks to preemptively create in the future.

**Comment by davidkohn88** [comment]
We have been thinking about different ways to solve this issue, `create_chunks` is one, but there might also be ways to do autonomous chunk creation. We aren't sure how many people run into issues with this though and if anyone has preferences in how something like this would be accomplished. We'd love some feedback on if others are experiencing problems with this and preferred ways to solve if folks have them.

**Comment by meagerman** [comment]
Hi! I've also recently run into this issue. Our use-case is that we do a number of daily loads into a number of hypertables in a single rollup transaction. These loads are split by client, and the client is part of our partition key for timescaledb. Some of these loads take a really long time, so if we are unlucky, a large load will lock a chunk as it is created, then for hours afterward as it completes, blocking other loads that happen to fall on the same chunk. 

I am probably going to try to do something like insert a dummy row in each hypertable before starting the transaction to ensure the chunks are created outside the main large transaction.

I think ideally from my perspective, there would be something like `ensure_chunk_exists(table, partition_key)` that would create the chunk if it does not exist already. Of course, this violates the encapsulation of the partition_key a bit.

**Comment by svenklemm** [comment]
In 2.0 there is an API to create chunks with specific constraints
You can find examples in the tests:
https://github.com/timescale/timescaledb/blob/master/tsl/test/sql/chunk_api.sql.in
