### ISSUE TITLE
Build error against PostgreSQL < 11

### ISSUE THREAD

**Issue by devrimgunduz** [timescale/timescaledb#763]
Hi,

Seeing this while RPMifying 0.12.0:

  PostgreSQL was built without OpenSSL support, which TimescaleDB needs for
  full compatibility.  Please rebuild PostgreSQL using `--with-openssl` or if
  you want to continue without OpenSSL, re-run bootstrap with
  `-DUSE_OPENSSL=0`

However, PostgreSQL is compiled with openssl.

Can you please take a look?

Thanks!

**Comment by cevin** [comment]
also got this error

**Comment by amytai** [comment]
@cevin are you running a version of Postgres that has OpenSSL installed?

**Comment by cevin** [comment]
@amytai 
```
host # . pg_config --configure
'--disable-debug' '--prefix=/usr/local/Cellar/postgresql/10.5' '--datadir=/usr/local/share/postgresql' '--libdir=/usr/local/lib' '--sysconfdir=/usr/local/etc' '--docdir=/usr/local/Cellar/postgresql/10.5/share/doc/postgresql' '--enable-thread-safety' '--with-bonjour' '--with-gssapi' '--with-ldap' '--with-openssl' '--with-pam' '--with-libxml' '--with-libxslt' '--with-icu' '--with-perl' '--with-tcl' '--with-tclconfig=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tcl.framework' '--with-uuid=e2fs' 'CC=clang' 'LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib' 'CPPFLAGS=-I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include' 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13'
```

**Comment by amytai** [comment]
That's odd. You shouldn't be seeing this error, unless cmake is using a different `pg_config` than what you're using. Did you rebuild Postgres in between when you ran bootstrap on Timescale?

To verify that cmake is using the correct `pg_config`, can you rerun whatever `bootstrap` command you ran, and post the output? There should be a printed message giving the path to `pg_config`.

**Comment by cevin** [comment]
@amytai 
```shell
$ ./bootstrap
Build system already initialized in ./build
Do you want to remove it (this is IMMEDIATE and PERMANENT), y/n? y
-- The C compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 1.0.0-dev. Can be updated from version 1.0.0
-- Build type is Release
-- Install method is 'source'
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success
-- Using compiler AppleClang
-- Found Git: /usr/bin/git (found version "2.17.1 (Apple Git-112)")
-- Using pg_config /usr/local/bin/pg_config
-- Compiling against PostgreSQL version 10.5
-- Install pgindent to be able to format C code: https://github.com/postgres/postgres/tree/master/src/tools/pgindent
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:286 (message):
  TimescaleDB requires OpenSSL but it wasn't found.  If you want to continue
  without OpenSSL, re-run bootstrap with `-DUSE_OPENSSL=0`


-- Configuring incomplete, errors occurred!
See also "/Users/cevin/timescaledb/build/CMakeFiles/CMakeOutput.log".
```


> $ /usr/local/bin/pg_config --configure
> '--disable-debug' '--prefix=/usr/local/Cellar/postgresql/10.5' '--datadir=/usr/local/share/postgresql' '--libdir=/usr/local/lib' '--sysconfdir=/usr/local/etc' '--docdir=/usr/local/Cellar/postgresql/10.5/share/doc/postgresql' '--enable-thread-safety' '--with-bonjour' '--with-gssapi' '--with-ldap' '--with-openssl' '--with-pam' '--with-libxml' '--with-libxslt' '--with-icu' '--with-perl' '--with-tcl' '--with-tclconfig=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tcl.framework' '--with-uuid=e2fs' 'CC=clang' 'LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib' 'CPPFLAGS=-I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include' 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13'

**Comment by vigneshrajarr** [comment]
@cevin I too had the same problem and got the same log. I was trying to give the OpenSSL's bin path to global `$PATH` variable. But as per the logs, I added `/usr/local/opt/openssl` (my openssl root folder) to the global variable `OPENSSL_ROOT_DIR`.

TimescaleDB got initialized.

What I have done : 

    #To update Homebrew and install OpenSSL
    brew update
    brew install openssl
    
    #To add the path to global variables
    vim ~/.bash_profile
    export PATH="$PATH:/Library/PostgreSQL/9.6/bin" #Add this line to the file
    export OPENSSL_ROOT_DIR="/usr/local/opt/openssl" #Add this line to the file
    source ~/.bash_profile

    ./bootstrap

**Comment by cevin** [comment]
@amytai @vigneshrajarr it's work
