### ISSUE TITLE
RFC - Table with UUID v1 primary key allows hypertable without time column

### ISSUE THREAD

**Issue by ancoron** [timescale/timescaledb#765]
So, this is more like an idea for optimization of already existing tables to convert seamlessly into hypertables without losing the performance penalty when rows are still accessed (picked) via single primary key and the application accessing the data cannot be adapted (third-party, business reasons, ...).

Specifically, I recently converted some tables of an existing database for a Camunda BPM installation to using timescale for its historic/audit data tables while using generating UUID v1 for the primary key column.

The DDL of one of its tables that is heavily being inserted/updated originally looked as follows:
```sql
create table ACT_HI_ACTINST (
    ID_ uuid not null,
    PARENT_ACT_INST_ID_ uuid,
    PROC_DEF_KEY_ varchar(255),
    PROC_DEF_ID_ uuid not null,
    PROC_INST_ID_ uuid not null,
    EXECUTION_ID_ uuid not null,
    ACT_ID_ varchar(255) not null,
    TASK_ID_ uuid,
    CALL_PROC_INST_ID_ uuid,
    CALL_CASE_INST_ID_ uuid,
    ACT_NAME_ varchar(255),
    ACT_TYPE_ varchar(255) not null,
    ASSIGNEE_ varchar(64),
    START_TIME_ timestamp not null,
    END_TIME_ timestamp,
    DURATION_ bigint,
    ACT_INST_STATE_ integer,
    SEQUENCE_COUNTER_ bigint,
    TENANT_ID_ varchar(64),
    primary key (ID_)
);
```

To convert it into a hypertable I had to modify the primary key and chose the column `START_TIME_` in addition, resulting into a multi-column primary key.

While the conversion into hypertables helped a lot get the PostgreSQL table/index bloat under control and speed up a lot of queries (especially inserts), other frequently executed queries slowed down a lot, most notably:

Selecting a single history entry:
```sql
select HAI.START_TIME_ from ACT_HI_ACTINST HAI where HAI.ID_ = $1
```
Average with regular PostgreSQL 10.5: ~2 ms
Average after conversion into hypertable: ~44 ms

...and updating an entry (in most cases for its `END_TIME_`):
```sql
UPDATE
    ACT_HI_ACTINST
  SET
    EXECUTION_ID_ = $1,
    PROC_DEF_KEY_ = $2,
    PROC_DEF_ID_ = $3,
    ACT_ID_ = $4,
    ACT_NAME_ = $5,
    ACT_TYPE_ = $6,
    PARENT_ACT_INST_ID_ = $7,
    END_TIME_ = $8,
    DURATION_ = $9,
    ACT_INST_STATE_ = $10,
  WHERE
    ID_ = $11
```
Average with regular PostgreSQL 10.5: ~2 ms
Average after conversion into hypertable: ~37 ms

However, as I am using UUID v1 for the original primary key, which already contains the time information, I was wondering whether:

1. Timescale could provide a custom UUID v1 type extending the standard UUID which just guarantees that data must comply to a UUID v1 spec
2. While creating a hypertable on a table that uses such UUID v1 type as primary key, would simply accept that column to be "used" as time column

So although I have additional time column(s) in the table of this specific case and application that should not be relied on as the major impact comes when actually relying on the application-level primary key.

Even further, in this specific case, using a UUID v1 primary key guarantees uniqueness across all partitions due to its time + sequence + space nature (if a collision on a UUID v1 would be detected, it would be an obvious application-level misconfiguration).

**Comment by jbinary** [comment]
I'd like to have the same feature but with a slightly different reasoning: I want to use timescaledb in pair with django ORM of which can't neither do composite PKs nor remove PK entirely.

I ended up with a hack which allows me to remove PK but this is an *extremely* limited solution.

In the same time UUIDv1 looks like a very promising solution for such cases?

**Comment by mfreed** [comment]
Hi @ancoron   I believe this has been addressed with with https://github.com/timescale/timescaledb/pull/639, which was part of our 1.1 release.

Closing this issue for now, feel free to re-open if doesn't solve your problems.

**Comment by adrianog** [comment]
Is there an example of how to use a custom partitioning function if my primary key is a string [containing a ULID](https://pypi.org/project/python-ulid/)

**Comment by ancoron** [comment]
@adrianog : if you're using Python anyway, simply write a little PostgreSQL function for that, e.g.:
```sql
CREATE OR REPLACE FUNCTION time_part_ulid(id varchar)
 RETURNS timestamp without time zone
 LANGUAGE plpython3u
 IMMUTABLE
AS $function$
# parse "id" into a ULID and return the timestamp as a "datetime" object
$function$
```
...and then, create your hypertable as follows:
```sql
SELECT * FROM create_hypertable(<mytable>, <ulid-column>, time_partitioning_func => 'time_part_ulid', ...);
```
But next time, please don't comment on a closed issue and consider other channels for support.
