### ISSUE TITLE
time_bucket('1 week', time) uses saturday instead of monday as week start

### ISSUE THREAD

**Issue by krims0n32** [timescale/timescaledb#768]
```
        SELECT time_bucket('1 week', time) AS period,
               some_value
        FROM table_with_5minute_data
        GROUP BY period, some_value
        ORDER BY period desc
```
This returns records with Saturday as the first day of the week. This does not match with Postgres' default (Monday) as can been seen when using date_trunc('week', time).

Is there a way around this? Am I overlooking something?

I'm using timescale/timescaledb:0.12.1-pg10.

**Comment by cevian** [comment]
This is because this is the 7-day bucket starting  from the Postgres epoch (which starts at 2000-01-01, a Saturday). You can use the offset parameter to move this to Monday (i.e. `time_bucket('1 week', time, '2 day')`. You can also use date_trunc if you will not be needing to analyze on multiple-week-buckets.

**Comment by erimatnor** [comment]
@cevian I think @krims0n32 has a point. `date_trunc` follows ISO8601 standards and uses `isoweek2j()` internally to get the Monday of the given week and year. See comment below from the PostgreSQL source code. I guess it makes sense for us to have the same behavior.

```
/* isoweek2j()
 *
 *	Return the Julian day which corresponds to the first day (Monday) of the given ISO 8601 year and week.
 *	Julian days are used to convert between ISO week dates and Gregorian dates.
 */
```

**Comment by krims0n32** [comment]
Thanks for the quick response. I will use the offset parameter for now.

**Comment by ricky-sb** [comment]
This `offset` parameter doesn't exist in `time_bucket_gapfill()`, nor does the `origin` parameter. What's the fix here if you want to use a gapfill?
