### ISSUE TITLE
Check is hypertable?

### ISSUE THREAD

**Issue by alexpantyukhin** [timescale/timescaledb#779]
Is there a way to check that table is already `hypertable`? I see that there already exists [is_hypertable](https://github.com/timescale/timescaledb/blob/b43574f82e1be9f492059d41a6aed2e8f7de455e/src/hypertable.c#L835) func in C code. But can't find something in sql functions.

**Comment by svenklemm** [comment]
You can check by querying _timescaledb_catalog.hypertable

**Comment by dianasaur323** [comment]
Closing - should be improved here: https://github.com/timescale/timescaledb/commit/d4619598a9aa065c6fb932a778742cbd97305b2c
