### ISSUE TITLE
Static bash path in bootstrap on NixOS

### ISSUE THREAD

**Issue by p-alik** [timescale/timescaledb#782]
`bootstrap` can't be executed on NixOS. (For sure on some other also)
 
```
./bootstrap
bash: ./bootstrap: /bin/bash: bad interpreter: No such file or directory
```

[0001-env-bash.patch.txt](https://github.com/timescale/timescaledb/files/2454191/0001-env-bash.patch.txt)

**Comment by mfreed** [comment]
I'm completely unfamiliar with NixOS; it seems like the problem is that it either doesn't have bash installed or on a different path.  How do you normally exec bash scripts?

**Comment by p-alik** [comment]
there are many other OS's with different path of `bash`. For instance FreeBSD.
Usage of `/usr/bin/env bash` in shebang doesn't do anything wrong, but make the script more portable.
See also https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
