### ISSUE TITLE
could not find function "pg_unix_microseconds_to_timestamp" in file "/usr/lib/postgresql/10/lib/timescaledb-1.0.0-dev.so"

### ISSUE THREAD

**Issue by trevorgfrancis** [timescale/timescaledb#783]
2018-10-08 12:34:15.896920 [0x00007f2727fff700] [error] processor[cvs]: SQL exception: ERROR:  could not find function "pg_unix_microseconds_to_timestamp" in file "/usr/lib/postgresql/10/lib/timescaledb-1.0.0-dev.so"
CONTEXT:  PL/pgSQL function _timescaledb_internal.time_literal_sql(bigint,regtype) line 16 at RETURN
PL/pgSQL function _timescaledb_internal.dimension_slice_get_constraint_sql(integer) line 45 at IF
PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 13 at assignment

**Comment by trevorgfrancis** [comment]
running latest timescale-rc2

**Comment by trevorgfrancis** [comment]
This was upgraded from timescale-r1

**Comment by svenklemm** [comment]
Looks like you are running master, all our exported c functions got recently prefixed with ts_ to prevent name clashed. You need to update your function definitions to reference the new names.

**Comment by RobAtticus** [comment]
Agreed with @svenklemm , did you build from source or from our Docker image? Given the name is 1.0.0-dev.so, that implies it is a build from the master branch and not from the tagged commit for 1.0.0-rc2.

**Comment by nikbyte** [comment]
Do master and tagged builds have different function names? Or function names changed with 1.0.0-rc release?

**Comment by RobAtticus** [comment]
The function names were changed between 1.0.0-rc1 and 1.0.0-rc2, but if you try to run the -dev version it may not have upgraded cleanly and thus didn't pull in all the changes to the names.

**Comment by nikbyte** [comment]
got you. thanks for comment.

**Comment by mfreed** [comment]
Closing out this issue.  Please re-open if you run into problems no related to the RC candidate upgrades.  Thanks.
