### ISSUE TITLE
What is the purpose of the built-in schemas?

### ISSUE THREAD

**Issue by vicochan** [timescale/timescaledb#794]
What is the purpose of the built-in schemas below? 
_timescaledb_internal
_timescaledb_catalog
_timescaledb_cache

Is the newly created time series table built in public or user-defined schemas ?

**Comment by svenklemm** [comment]
By default chunks will be created in _timescaledb_internal but you can overwrite that behaviour and have them created in any schema you like, by specifying a different schema in the create_hypertable call. 

https://docs.timescale.com/v0.12/api#create_hypertable
