### ISSUE TITLE
WARNING: out of shared memory (In docker container) during COUNT(*)

### ISSUE THREAD

**Issue by bs-sdev** [timescale/timescaledb#796]
Hi every one, Actually I need to test performance on TimescaleDB compare to Postgresql. To do this, I ran 2 docker containers for each. For each, databases are identical (except for the chunk size in TDB container)

Every container has a specific postgres conf adapted for my dev laptop (from this website:  https://pgtune.leopard.in.ua/#/) :
```sql
# DB Version: 9.6
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 32 GB
# CPUs num: 4
# Data Storage: hdd

ALTER SYSTEM SET
 max_connections = '200';
ALTER SYSTEM SET
 shared_buffers = '8GB';
ALTER SYSTEM SET
 effective_cache_size = '24GB';
ALTER SYSTEM SET
 maintenance_work_mem = '2GB';
ALTER SYSTEM SET
 checkpoint_completion_target = '0.7';
ALTER SYSTEM SET
 wal_buffers = '16MB';
ALTER SYSTEM SET
 default_statistics_target = '100';
ALTER SYSTEM SET
 random_page_cost = '4';
ALTER SYSTEM SET
 effective_io_concurrency = '2';
ALTER SYSTEM SET
 work_mem = '20971kB';
ALTER SYSTEM SET
 min_wal_size = '1GB';
ALTER SYSTEM SET
 max_wal_size = '2GB';
ALTER SYSTEM SET
 max_worker_processes = '4';
ALTER SYSTEM SET
 max_parallel_workers_per_gather = '2';
```

Also, please find my table structure for Postgresql:
```sql
CREATE TABLE test_table_3
(
    id integer NOT NULL,
    "timestamp" integer NOT NULL,
    value integer NOT NULL,
    status smallint NOT NULL,
    CONSTRAINT primkey_test_table_3 PRIMARY KEY (id)
)
```

And the table structure for TDB:

```sql
CREATE TABLE test_table_3
(
    id integer NOT NULL,
    timestamp integer NOT NULL,
    value integer NOT NULL,
    status smallint NOT NULL
)
```

I chose time interval of an hour (because my timestamp value is in seconds, I specified 3600)

The test I wrote, not particular, I have just wrote a .sql file in which I have 2000 transactions, each transaction contains 10000 inserts commands, for each row I add on second to my timestamp value:

```sql
INSERT INTO test_table_3 (id, timestamp, value, status) VALUES 
(1, 1510869487,20,2),
(2, 1510869488,20,2),
(3, 1510869489,20,2),
(4, 1510869490,20,2),
(5, 1510869491,20,2),
(6, 1510869492,20,2),
(7, 1510869493,20,2),
...
```
So with a psql client (once again, in an other docker container), I send this .sql file (around 569MB) to my both Postgres and TDB databases.

I noticed that in Postgresql it is 30 seconds faster, but I guess with 200Million rows, because of constant rate, TDB should be faster.

But when I simply want to make a **SELECT COUNT(*) FROM test_table_3**,  I got this error:

```bash
...
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
WARNING:  out of shared memory
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
CONTEXT:  parallel worker
```

If I run this command in the Postgres container, it shows me the right result with 20000000 as count(*)

Could you tell me what occurred? Because now, I cannot delete rows or even table anymore, this error message appear all the time ...

Last thing, I am absolutely not SQL expert, so maybe some configuration has been missed, but I took the official containers for both.

Kind regards.

**Comment by svenklemm** [comment]
Did you try to increase max_locks_per_transaction it should be roughly 2 time the number of chunks you have.

https://docs.timescale.com/v0.12/getting-started/configuring#locks

**Comment by nikbyte** [comment]
+1
I have exactly the same issue. And number of my chunks is increasing. How to avoid out of memory in this case?

**Comment by marinakr** [comment]
I have same issue

**Comment by mfreed** [comment]
Closing this issue for now, but can re-open if more information is provided.  Right now it appears chunks are way too small.

**Comment by pmalhaire** [comment]
Hello I am facing the same issue,
But only from the drop chunk fonction.

My hypertable has 400 chunks from few bytes to 15MB and my machine has 1GB memory.

I have arround 65 hypertables of the same type.

DELETE works fine but drop chunk fails.

It looks like this is a sizing issue in my case.

**Comment by yaitskov** [comment]
I noticed same error when truncate a hyper table with 4k chunks and max_locks_per_transaction is set to 128.

**Comment by dss010101** [comment]
I seem to be having this same problem. im using psycopg2, and calling the copy_from function to insert 24k records from a pandas dataframe. doesn't seem like a lot to me..but app stalls and eventually i get this error.  any suggestions?

**Comment by svenklemm** [comment]
> I seem to be having this same problem. im using psycopg2, and calling the copy_from function to insert 24k records from a pandas dataframe. doesn't seem like a lot to me..but app stalls and eventually i get this error. any suggestions?

If you create a large amount of chunks in a single transaction you can run into this. Have you tried increasing the suggested setting? This error is not about the amount of memory used but the amount of locks being held at the same time.

**Comment by dss010101** [comment]
> > I seem to be having this same problem. im using psycopg2, and calling the copy_from function to insert 24k records from a pandas dataframe. doesn't seem like a lot to me..but app stalls and eventually i get this error. any suggestions?
> 
> If you create a large amount of chunks in a single transaction you can run into this. Have you tried increasing the suggested setting? This error is not about the amount of memory used but the amount of locks being held at the same time.

To get around this error, i had change max_locks_per_transaction configuration settings.  even then, im having a horrible experience as far as performance - i've opened an issue here: https://github.com/timescale/timescaledb/issues/5665
