### ISSUE TITLE
how to show table chunks in psql command?

### ISSUE THREAD

**Issue by FunkyYang** [timescale/timescaledb#805]
Hi:
I am new to timescaledb today.and I insert a lot of datas in hyper table,now I want to find how many chunks which be used for that hyper table,somebody can help me??

**Comment by mfreed** [comment]
Hi @FunkyYang Please let me know if that answers your question, and close off the issue if so.  Thanks.

**Comment by jyotibose** [comment]
Get : Schema, Parent , Chunk and Size 

select a.parent_schema,a.parent,a.child,b.total_size from (SELECT nmsp_parent.nspname AS parent_schema,
       parent.relname AS parent,
       nmsp_child.nspname AS child_schema,
       child.relname AS child
FROM pg_inherits
JOIN pg_class parent ON pg_inherits.inhparent = parent.oid
JOIN pg_class child ON pg_inherits.inhrelid = child.oid
JOIN pg_namespace nmsp_parent ON nmsp_parent.oid = parent.relnamespace
JOIN pg_namespace nmsp_child ON nmsp_child.oid = child.relnamespace
WHERE nmsp_parent.nspname='Schema' ) a , (SELECT relname AS "relation", pg_size_pretty(pg_total_relation_size(C.oid)) AS "total_size" FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND C.relkind <> 'i' AND nspname !~ '^pg_toast' ORDER BY pg_total_relation_size(C.oid) DESC  LIMIT 15) b 
where a.child=b.relation;


 parent_schema |           parent            |         child         | total_size
---------------+-----------------------------+-----------------------+------------
 Schema    | TemperatureReading          | _hyper_481_1242_chunk | 22 GB
 Schema    | RPMReading                  | _hyper_456_1166_chunk | 17 GB

**Comment by fingoldo** [comment]
Is this function,**chunk_relation_size_pretty**, removed from TimeScaleDB? Can't find it in current docs.

**Comment by Anonyma** [comment]
> Is this function,**chunk_relation_size_pretty**, removed from TimeScaleDB? Can't find it in current docs.

Yes, it has been removed (among others). Now there's [chunks_detailed_size()](https://docs.timescale.com/api/latest/hypertable/chunks_detailed_size/)
