### ISSUE TITLE
migrations 

### ISSUE THREAD

**Issue by rnukala** [timescale/timescaledb#812]
Hi,
I was wondering if I can run migration scripts for timescaledb using  ORM like sequelize?
If so how do I handle data insertions into chunks?
lets say my  chunk_time_interval is 1 month and I now what to see past 6 months values, how will I retrieve older chunks.

Thank you for your time,
Regards,
RN

**Comment by mfreed** [comment]
I'm not sure I understand the question.  You should be able to use most ORMs with timescaleDB, as long as the ORM doesn't require a primary auto-increment key (there are workarounds, but it's a pain).  I don't recall sequelize offhand.

Regarding your other questions, you don't need to worry about chunking at all in your inserts or queries.  Just insert or query like it's a single table.

e.g.,   `SELECT * from table WHERE time < now() - interval '6 months' and time > now() - interval '9 months'`

**Comment by rnukala** [comment]
@mfreed  thank you clarifying.

A quick question, I have a table with default chunk interval value , if I need to fetch only current chunk data how should I get it.  I am new to using timescaledb.

Thank you

**Comment by rnukala** [comment]
@mfreed  appologies for late reply I  just wanted to know as I am still in learning phase .Thank you

I have a question regarding querying  a hypertable with a jsonb column. Could you please help me with it.

Let say 'value' is the jsonb column in my  'events hypertable. The column has  records {"temperature": "20"},  I want to get stats like average or max , min of the temperature in the last month. I can access the jsonb element by doing  SELECT  value->'temperature' FROM public.events; 

But when I am trying to do average of the temperature I keep getting error " ERROR:  function avg(jsonb) does not exist "
The is my query following timescaledb api.

SELECT time, AVG(value->'temperature') OVER(ORDER BY time
ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)
AS smooth_temp
FROM events
WHERE id= 'e1b6a226-cc79-11e8-a8d5-f2801f1b9fd1' and time > NOW() - interval '1 day'
ORDER BY time DESC;

**Comment by mmariani** [comment]
You are retrieving the values as JSONB objects, not strings or integers, hence the error.
Try this: AVG(value->>'temperature'::float) OVER etc.etc.

**Comment by rnukala** [comment]
@mmariani  thank you
