### ISSUE TITLE
Installing via Homebrew on Linux

### ISSUE THREAD

**Issue by WilliamHoang** [timescale/timescaledb#82]
Description:
Hitting installation issue (see below) against:

1. ubuntu: 14.04
2. Homebrew: 1.2.0
_________________________________________________________
<img width="1015" alt="screen shot 2017-06-05 at 12 15 37 pm" src="https://cloud.githubusercontent.com/assets/898097/26792552/bc39a9cc-49e8-11e7-8af3-de173fefd34f.png">

`ubuntu@ip-172-31-16-101:~$ brew install timescaledb
==> Installing timescaledb from timescale/tap
==> Downloading https://timescalereleases.blob.core.windows.net/homebrew/timescaledb-0.0.11-beta.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/timescaledb-0.0.11-beta.tar.gz
==> make
==> make install DESTDIR=/tmp/timescaledb-20170605-5821-1spkl5u/timescaledb/stage
Warning: tried to install empty array to /home/ubuntu/.linuxbrew/Cellar/timescaledb/0.0.11-beta/lib/postgresql
Warning: tried to install empty array to /home/ubuntu/.linuxbrew/Cellar/timescaledb/0.0.11-beta/share/postgresql/extension
Error: Empty installation`

**Comment by RobAtticus** [comment]
Hmm, not sure what the issue is since I've never tried running homebrew on Linux. Is postgres 9.6 correctly installed on the machine? I've also never tested on 14.04. We do have `apt` and source instructions, but not sure those will help on 14.04.

**Comment by mfreed** [comment]
Hi, did you resolve this or just switch to a different installation method?

**Comment by WilliamHoang** [comment]
@mfreed :  Resolved and switched to a different method.  Will update and closing issue.
