### ISSUE TITLE
git repository maintenance

### ISSUE THREAD

**Issue by jesperpedersen** [timescale/timescaledb#820]
It would be nice to have only active development branches in the official repository.

Currently there are a number of branches that seems out-of-date or really not needed in the official repository.

It would be nice to be able to do `git rebase -i upstream/m<TAB><TAB>`... and get `master`.

Just some feedback, and $0.02 from the peanut gallery...

**Comment by jesperpedersen** [comment]
@RobAtticus Thanks

**Comment by RobAtticus** [comment]
Thanks, I have removed all the branches we deemed fit to remove, leaving just:
- master
- prerelease_test (runs our full test suite before a release)
- several versioned branches

**Comment by jesperpedersen** [comment]
@RobAtticus Cool
