### ISSUE TITLE
Duplicate parameter name in set_adaptive_chunking messes up jOOQ class generator

### ISSUE THREAD

**Issue by cg-d** [timescale/timescaledb#833]
**Relevant system information:**
 We are using docker image timescale/timescaledb:0.12.1-pg10
 
**Describe the bug**
We are using jOOQ 3.11.4 to generate a DSL to access the DB. For each parameter of a routine a member of type Parameter<> is generated. Since set_adaptive_chunking has two params with the same name this results in invalid code.

**To Reproduce**
1. Setup timescaleDB (e.g. via docker)
2. Run jOOQ generator e.g. via the maven plugin with 

mvn jooq-codegen:generate

[plugin config 2.txt](https://github.com/timescale/timescaledb/files/2537979/plugin.config.2.txt)

3. Open target/generated-sources/de/ninjaneers/db/routines/SetAdaptiveChunking.java

I would hereby request that you name one of the params so jOOQ codegen can be used.

**Comment by cg-d** [comment]
The workaround for now is to add set_adaptive_chunking to the excludes

     <excludes>set_adaptive_chunking | flyway_schema_history</excludes>

**Comment by RobAtticus** [comment]
Thanks for reporting this @cg-d, we will look into fixing this!

**Comment by NunoFilipeSantos** [comment]
@cg-d are you still affected by this issue on the newest release?

**Comment by cg-d** [comment]
We just checked with version 1.7.4 and that seems to work fine.
