### ISSUE TITLE
Chunking on secondary column?

### ISSUE THREAD

**Issue by ddebie** [timescale/timescaledb#835]
From the timescale blog:
> Instead of just indexing by time, TimescaleDB builds distinct tables by splitting data according to two dimensions: the time interval and a primary key (e.g., server/device/asset ID).

Is this referring to space partitioning, or is there another way to chunk by a secondary (non-time) column? From reading the timescale best practices, it seems that space partitioning should be used only when separating data amongst multiple physical drives. I'm looking to keep everything on a single drive, but would like it to still be chunked for each unique value in column X.

For example, if I have stock data for multiple symbols (likely thousands):
`DATE, SYMBOL, PRICE`
`2018-10-10, ABC, 123`
`2018-10-10, XYZ, 456`
`2018-10-10, ABC, 124`

I would like to have ABC and XYZ to be in separate chunks. I've put an index on SYMBOL, but it doesn't seem to impact chunking. As I understand it, this makes my queries quite slow, as a simple query like `SELECT * FROM some_table WHERE SYMBOL='ABC' AND DATE>2018-10-10` is forced to load data for all symbols in that time range. Am I missing something?

**Comment by RobAtticus** [comment]
Hey @ddebie,

It is referring to space partitioning. TimescaleDB uses hash partitioning on the space dimension so doing the partition-per-unique-value would be a bit tricky to accomplish (you'd have to write and provide your own hashing function). 

As for your query problem, is your only index on symbol? Have you tried using a `date,symbol` index
or even `symbol,date`? That should allow for more efficient index lookups for your particular type of query.

**Comment by brintal** [comment]
I'm having a similar scenario and am unsure what is the recommended way to create a hypertable for that.
Could someone please confirm that (using the example of @ddebie ) SYMBOL should not be used for partioning?

So doing that is discouraged:
`SELECT create_hypertable('myStockData', 'time', 'symbol', 100);`
But instead we should be creating a hypertable with no partions but add additional indexes:
`SELECT create_hypertable('myStockData', 'time');`

Is my undestanding correct?
Currently (not having migrated to timescaledb yet) I'm using native postgres partial indexes for each SYMBOL to kinda "partition" my data.: `CREATE INDEX my_partial_idx ON my_stock_data (date) WHERE symbol = 'ABC'`
Is this approach still possible/recommended with timescaledb?

**Comment by cercata** [comment]
> Currently (not having migrated to timescaledb yet) I'm using native postgres partial indexes for each SYMBOL to kinda "partition" my data.: `CREATE INDEX my_partial_idx ON my_stock_data (date) WHERE symbol = 'ABC'`
> Is this approach still possible/recommended with timescaledb?

I'm in the same situation, I'm making tests with space partitioning, and seems to be giving better results than multiple indexes ...

**Comment by NunoFilipeSantos** [comment]
@brintal and @cercata this issue has now some time, we're sorry we couldn't get to you in time, we hope this hasn't impacted you too much. 
I'm closing the issue now, but feel free to reopen it, if you are still facing these questions.

**Comment by ybangaru** [comment]
So, what exactly is the solution being suggested here? space partitioning even when on a single drive is helpful?
