### ISSUE TITLE
feedback wanted: start timescaleDB cluster with postgres-xl test

### ISSUE THREAD

**Issue by structure-charger** [timescale/timescaledb#840]
**Relevant system information:**
 - OS: docker or lxc on any platform
 - PostgreSQL version  larger than 10
 - TimescaleDB version future version
 - Installation method: docker or lxc

we are testing both postgres-xl and timescaleDB on ubuntu 16.04 with docker deploy now, we try to test timescaleDB as an extension to postgres-xl, or postgres-xl as an extension to timescaleDB,this will be a more original cluster for postgres extension DBs, LXC container is also the target deploy method for the next test. 
welcome any advise from you.

**Comment by mfreed** [comment]
@furenle We have not tested TimescaleDB on Postgres-XL ourselves.  Welcome any feedback or findings you report.  Thanks!

**Comment by furenle** [comment]
As I known recently , the cluster of postgresql has only one center called gtm for keep cluster  consistency and controll the whole cluster, but there is only one method to keep it alive which is use a standby gtm and keepalived to make a demo like high availability to the gtm and the hole cluster. I think we should try to integrate the gtm with zookeeper or other implementation of  byzantine fault tolerance , I just find another postgresql extension try to solve the problem https://github.com/postgrespro/postgres_cluster , this may be a better way. I prefer to find a way inside postgresql lib to solve byzantine fault tolerance problem. and we try to use TimescaleDB as a extension in postgresql-xl now. I will try to collect the source code into contrib to one postgresql core and compile it , if you have any suggestion, please remind me . Thanks!

**Comment by germandiagogomez** [comment]
I was dropeed here by Google when trying to research about horizontal scalability in TimeScaleDB, something that is a must for my current company.

I am finding quite difficult to know how to scale horizontally TimeScaleDB. It seems to be advertised in vague mentions but nothing concrete. I just found this:

- https://github.com/timescale/timescaledb/issues/13

Is there anything I could rely on to get an idea of whether TimeScaleDB will fullfill our needs for horizontally scaling it?

**Comment by NunoFilipeSantos** [comment]
@germandiagogomez https://docs.timescale.com/latest/tutorials/clustering#react-docs
You can also drop us a note on the Multinode slack channel.
