### ISSUE TITLE
Problem with 10 Millions metrics from Prometheus  every 5 minutes

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [timescale/timescaledb#841]
Hello guys
I am impressed with this product and try to run it on environment that generate 10-11 millions metrics every 5 minutes. And i got problem that database used all disk operations, after 1h of running i got average load 150 on 32 cores cpu. Also notice that not all metrics are ingested from Prometheus to timescale due to strange errors on timescale adapter. Can you give advise what settings i need to use and if its really can handle that number of metrics? 

Here is config

```
listen_addresses = '*'
max_connections = 1100			# (change requires restart)
shared_buffers = 48GB			# min 128kB
maintenance_work_mem = 2GB		# min 1MB
dynamic_shared_memory_type = posix	# the default is the first option
shared_preload_libraries = 'timescaledb'		# (change requires restart)
effective_io_concurrency = 200		# 1-1000; 0 disables prefetching
max_worker_processes = 32		# (change requires restart)
max_parallel_workers_per_gather = 16		# taken from max_parallel_workers
max_parallel_workers = 32		# maximum number of max_worker_processes that
synchronous_commit = off		# synchronization level;
wal_buffers = 16MB			# min 32kB, -1 sets based on shared_buffers
max_wal_size = 4GB
min_wal_size = 2GB
checkpoint_completion_target = 0.7	# checkpoint target duration, 0.0 - 1.0
random_page_cost = 1.1			# same scale as above
effective_cache_size = 144GB
default_statistics_target = 100	# range 1-10000
log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'en_US.utf8'			# locale for system error message
lc_monetary = 'en_US.utf8'			# locale for monetary formatting
lc_numeric = 'en_US.utf8'			# locale for number formatting
lc_time = 'en_US.utf8'				# locale for time formatting
default_text_search_config = 'pg_catalog.english'
```

**Comment by davidkohn88** [comment]
Hmmm...well first thing is I'd want to know a bit more about your disks and also about how the data is coming in (ie are the 10m points spread evenly over the 5 mins or do they all come in simultaneously) but in general, I'd recommend joining our public slack channel slack.timescale.com as it's much easier to have a discussion around issues like this there.

**Comment by dmitriy-lukyanchikov** [comment]
the do not spread over all 5 minutes 10 millions come from 4 instances. disks is simple local ssd storage

**Comment by dianasaur323** [comment]
@dmitriy-lukyanchikov looping in @niksajakovljevic who can provide some advice. Do you also mind pasting the strange error messages you are getting into here?

**Comment by mfreed** [comment]
Closing out issue.  Can re-open if more information is provided.
