### ISSUE TITLE
arm32 image

### ISSUE THREAD

**Issue by rtmaster** [timescale/timescaledb#843]
is there a Docker image for arm32 available? If not, are there instructions how to build? thanks a lot!

**Comment by mfreed** [comment]
We do not currently have a docker image for Arm32, although we have somebody working on fixing any issues for building on it.

**Comment by mfreed** [comment]
@rtmaster We have not yet assigned any milestone to this yet, so I'm not sure.  What are you using TimescaleDB on ARM32 for?

**Comment by rtmaster** [comment]
It would be for IoT use cases on a Rasperry Pi 2 type of device which has armhf architecture. Thank you for working on this

**Comment by ericcurtin** [comment]
Fedora and openSUSE provide aarch64 OS images for Raspberry Pi 3, unless you specifically need to target a 32 bit CPU/OS of course.

**Comment by rtmaster** [comment]
need to target a 32 bit architecture specifically - similar to RPi but not it

**Comment by rtmaster** [comment]
are you going to publish this on docker hub? @Ngalstyan4

**Comment by svenklemm** [comment]
ARM images are available on docker hub: https://hub.docker.com/r/timescale/timescaledb/tags
