### ISSUE TITLE
Support for unsigned int

### ISSUE THREAD

**Issue by pjebs** [timescale/timescaledb#848]
My company is thinking of using this product for a forecasting project.
We currently use MySQL. We are investigating timescale vs influx for this new project.

Given timescale uses postgres, we were thinking _if_ we chose to use timescale, we could migrate our entire database from MySQL to timescale/postgres. It will be a factor in a decision making.

The problem is that we have many unsigned int 64 bit usage.

Will Timescale add unsigned int support for postgres or at least for hypertables?

**Comment by RobAtticus** [comment]
Would using an int type plus a constraint of >=0 be sufficient for your purposes? I am not sure we want to venture into creating a new type like that, even for just hypertables. Of course if it fills a need that can't otherwise be handled we'd certainly consider it.

**Comment by did-g** [comment]
Hi,

For the record there's already an unsupported extension for unsigned type:
https://github.com/petere/pguint.git

**Comment by pjebs** [comment]
@RobAtticus having a constraint still reduces the range. The unsigned 64 bit numbers cover the full range.

@did-g We are aware of that package but because it's not backed by a "reputable" company, we are reluctant to consider it.

On a separate note, I would have thought from a business perspective covering unsigned 64 bit ints is  an important use case for a product that is used for collecting data. We were surprised that it wasn't already there.

**Comment by RobAtticus** [comment]
@pjebs Understood, but then I guess my question is whether that additional range is necessary for your use case? Or are you just making sure you have future proofing?

re: business perspective - it appears from PG discussions and the README on that repo that the benefit of adding uint is usually outweighed by the increased type system complexity and fragility. As far as I know, I don't think anyone else has asked for it. I am also not aware of non-theoretical use cases for it, but happy to hear otherwise.

**Comment by pjebs** [comment]
Well in our case, it's really just about migration from MySQL to Postgres. We have keys that are randomly generated uint64 similar to facebook's appscoped ids in their facebook SDK. 

For us, uint64 provides a large range where are confident of not having collisions and it's simply more efficient to store that string-based uuids.

I don't think it's theoretical given that in mysql, using unsigned ints are super-common and I'm pretty sure uint64 are not uncommon.

**Comment by RobAtticus** [comment]
Okay, will mark as an enhancement (cc @dianasaur323).

I think there are solutions for your current use that don't require uint64 -- e.g., using uuid functionality in PG, convert back and forth from uint64 and int64, etc. But I do see some use cases I hadn't thought of in the influx thread.

**Comment by RobAtticus** [comment]
Perhaps! Thanks for the feedback, we'll look into it!

**Comment by dianasaur323** [comment]
Great - thanks for the feedback. Added to our feature backlog. It sounds like the bigger question here is how to better support better MySQL migration, which we can certainly support when we get some more requests for it.

**Comment by pjebs** [comment]
@dianasaur323 I don't think that's the concern. That was just a factor in our decision making (and possibly a covert selling point for marketing).

The real issue is unsigned integer support (or at least unsigned 64 bit int support) which is directly relevant for your product and your chief competitor influx.

**Comment by phemmer** [comment]
So I attempted to use the pguint extension to obtain uint64 functionality. It does appear to work, but only in single node. If you try to use multi-node you get the error `unsupported integer size 8`. It appears to be an issue when the access node is serializing the data to send to the data node.

**Comment by svenklemm** [comment]
Have you tried using https://github.com/petere/pguint? Non-partitioning columns of hypertables can be any datatype even those added by other extensions.

**Comment by AlexHill** [comment]
Hi @svenklemm or anybody else watching - how does compression work using the pguint types? Will TimescaleDB employ its optimisations for compressing numeric types?
