### ISSUE TITLE
no upgrade path to 1.0

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#851]
What is the recommended way of upgrading to 1.0.0 from the 0.x series? I haven't found any information about upgrading to the 1.0 release, so currently I'm assuming the only way is to basically rebuild the entire database (dropping everything and then importing all tables again)? Is this correct? Isn't there a way that allows us to upgrade without having to do this?

**Comment by RobAtticus** [comment]
You should be able to upgrade from any 0.x series to 1.0.0. What version are you using?

The only exception would be if you checked out `master` and were not on a tagged commit.

**Comment by RobAtticus** [comment]
Basically, the instructions here should work:
https://docs.timescale.com/v1.0/using-timescaledb/update-db

**Comment by fvannee** [comment]
It works now. Sorry for the confusion. I'll close this.
