### ISSUE TITLE
Poor performance in the container

### ISSUE THREAD

**Issue by dreampuf** [timescale/timescaledb#883]
**Relevant system information:**
 - OS: Centos 7
 - PostgreSQL version (output of `postgres --version`): 10.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.0.0
 - Installation method: using Docker

**Describe the bug**
It takes one or two minutes to write the samples into timescaledb.
![image](https://user-images.githubusercontent.com/353644/49550706-88f28200-f8ba-11e8-85f8-33da3709e35c.png)

**To Reproduce**
I set up the timescaledb and Prometheus adaptor by following the document: https://docs.timescale.com/v1.0/tutorials/prometheus-adapter
After adapting my existing Prometheus, the performance shows the adapter takes a lot of time to ingest the samples. I'm not sure if that related to container's overlay of the filesystem. I have configured docker to use device-map rather than overlay2.

**Expected behavior**
I expect that timescaledb can archive 100-200k rows/sec  https://docs.timescale.com/v1.0/faq#scaling

**Actual behavior**
15k/s

**Screenshots**
above

**Comment by niksajakovljevic** [comment]
Hi @dreampuf,
what version of `primetheus-postgresql-adapter` are you using? There have been some performance issues with older versions.
You should also make sure to have properly configured write batch size in Prometheus (remote storage config, recommended size is 1K).
You should definitively be able to get around 100K  inserts with a modest resources ( 2CPU, 4GB RAM).
I don't think this is related to container's overlay of the filesystem. However it's worth checking disk latency and throughput with tools like `ioping`.

**Comment by dreampuf** [comment]
I'm testing `prometheus-postgresql-adapter:latest` which I believe is `0.4.1`.
The hardware spec is overqualified - 24core 62G. I moved timescaledb out of the Prometheus node and allocated it a dedicated node. The tps shows 40k/s maximum. My Prometheus has around 140k/s samples. 
![image](https://user-images.githubusercontent.com/353644/49612303-4a200300-f972-11e8-83a7-3df47b437a87.png)
PostgresSQL status shows it can take 50k tps at maximum. 
![image](https://user-images.githubusercontent.com/353644/49612334-6cb21c00-f972-11e8-8c9a-cc8424408431.png)
From Prometheus remote storage metrics, it shows a lot of samples dropped.
![image](https://user-images.githubusercontent.com/353644/49612455-ca466880-f972-11e8-813c-ae55cd41a74f.png)

Timescaledb shows a lot of COPY tasks, and I was thinking it might be a temporary table write issue, then I tried to set `pg.copy-table` to `metrics` (this makes the adapter not working).

**Comment by niksajakovljevic** [comment]
It seems that something is misconfigured.
Can you verify that in `prometheus.yml` you have `max_samples_per_send: 1000` ( located under `remote_write`/`queue_config`). The default value of 100 is too small.

**Comment by dreampuf** [comment]
I did the change. For the success rate, I enlarged the deadline and reduced the retries.
```remote_write:
 - url: "http://POSTGRESQL_ADAPTER:9201/write"
   queue_config:
     max_samples_per_send: 1000
     batch_send_deadline: 30s
     max_retries: 1```

**Comment by mfreed** [comment]
@dreampuf Did this resolve your problem and we should close the issue?

**Comment by mfreed** [comment]
@dreampuf Has your issue been resolved?

**Comment by dreampuf** [comment]
@mfreed I didn't. And after that, I tested m3db/Tikv/influxDB as the remote storage of Prometheus. InfluxDB has the most overall out-of-box performance. I'm using it as a temporary solution. 
I think we can close this ticket.
