### ISSUE TITLE
HoT update statistics not being updated for hypertables

### ISSUE THREAD

**Issue by netgainsceo** [timescale/timescaledb#884]
**Relevant system information:**
 - OS: [CentOS 7.4.1708]
 - PostgreSQL version (10.3): [e.g. 10.5, 9.6.10]
 - TimescaleDB version (1.0.0): [e.g. 1.0.0]
 - Installation method: ["apt install"]

**Describe the bug**
In a normal postgres database table HoT update works when a recently inserted record is updated.
pg_stat_get_tuples_hot_updated value is updated whenever HoT update is used.

The Heap Only Tuple (HOT) feature eliminates redundant index entries and 
allows the re-use of space taken by DELETEd or obsoleted UPDATEd tuples
without performing a table-wide vacuum.  It does this by allowing
single-page vacuuming, also called "defragmentation".

When this table is converted/recreated as Hypertable using TimeScaleDB v1.0 this value does not get updated indicating HoT update is not working.

**To Reproduce**
1. Create a new table in postgres.
2. Insert few records.
3. Update these records one-by-one and we can see pg_stat_get_tuples_hot_updated changing.
4. Convert the same Table to Hypertable or create a new Hypertable Table.
5. Insert few records.
6. Update these records one-by-one and we can see pg_stat_get_tuples_hot_updated NOT changing.

**Expected behavior**
In ideal scnerio pg_stat_get_tuples_hot_updated should have changed with every update.

**Actual behavior**
In ideal scnerio pg_stat_get_tuples_hot_updated should have changed with every update but it is not changing indicating TimescaleDB is not using HoT update feature of Postgres.

**Screenshots**

**Additional context**

**Comment by fvannee** [comment]
I haven't checked this, but for which table are you looking at the pg_stat_get_tuples_hot_updated statistics? The tuples do not actually get updated in the parent table, because they are stored in one of the child tables (one of the tables in _timescaledb_internal). Are you passing the parent table oid or the child table oid to the pg_stat_get_tuples_hot_updated function?

**Comment by netgainsceo** [comment]
I am passing the parent table oid.

**Comment by fvannee** [comment]
if you do something like 'explain select * from your_hypertable where your_time_column between a and b' (substitute with whatever params you have and have the time period be in the time period of the rows that you're updating), then you see the names of the child tables that the tuples actually get inserted to. If you pass the child table oid to the hot tuple statistics function, do you see updates then?

**Comment by netgainsceo** [comment]
As suggested I identified the chunk using explain analyze and then
used pg_stat_get_tuples_hot_updated on
"_timescaledb_internal._hypertable...", it is returning 0.

**Comment by gayyappan** [comment]
Could you try this example and let us know if it works?  
The last SELECT statement needs modification - use the correct hypertable name as shown by \d+ conditions command.

```
drop table conditions;

create table conditions (
time timestamp with time zone not null,
location text not null,
temperature double precision null,
humidity double precision null);

select create_hypertable('conditions', 'time', 'location') ; 

insert into conditions( time, location)
select timestamp 'epoch' + ( i * INTERVAL '1 second'), 'NYC'
FROM generate_series(0, 100000) as T(i);

\d+ conditions ====> will show you the internal hypertables

update conditions set temperature = 100 where time = '1970-01-01 00:00:19-05';

SELECT pg_stat_get_tuples_hot_updated('conditions'::regclass::oid); ====> should show 0

SELECT pg_stat_get_tuples_hot_updated('_timescaledb_internal._hyper_4_10_chunk'::regclass::oid);
 pg_stat_get_tuples_hot_updated 
--------------------------------
                              1
(1 row)


```

**Comment by netgainsceo** [comment]
Querying the parent table for hot update does not show any result. But
querying the correct timecaledb chunk does show hot updates.

**Comment by davidkohn88** [comment]
Since it seems like HOT is working, just our statistics aren't being updated for the hypertable versus chunks I've changed the name of this issue and marked as an enhancement. Would be good to have correct stats somewhere potentially. Perhaps a convenience function or something.

**Comment by svenklemm** [comment]
@netgainsceo I think this actually works as intented, statistics of the base table do not inherit/accumulate statistics of child tables in inheritance chain in postgres either.

```
sven=# CREATE TABLE hot_test(id int, value int);
CREATE TABLE
sven=# CREATE TABLE hot_test_child() INHERITS(hot_test);
CREATE TABLE
sven=# insert into hot_test_child SELECT 1,2;
INSERT 0 1
sven=# update hot_test_child set value = 3 where id = 1;
UPDATE 1
sven=# select pg_stat_get_tuples_hot_updated('hot_test'::regclass);
 pg_stat_get_tuples_hot_updated
--------------------------------
                              0
(1 row)

sven=# select pg_stat_get_tuples_hot_updated('hot_test_child'::regclass);
 pg_stat_get_tuples_hot_updated
--------------------------------
                              1
(1 row)
```
