### ISSUE TITLE
Installation issue with Mac 

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [timescale/timescaledb#895]
By default, **brew install timescaledb** download **postgres 11** for Mac.  The right way to install postgresql 10 on mac using **brew is brew install postgresql@10**

brew tap timescale/tap
brew install timescaledb

==> Tapping timescale/tap
Cloning into '/usr/local/Homebrew/Library/Taps/timescale/homebrew-tap'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Tapped 1 formula (27 files, 25.8KB).
➜  ~ brew install timescaledb

Updating Homebrew...
==> Installing timescaledb from timescale/tap
==> Installing dependencies for timescale/tap/timescaledb: cmake and postgresql
==> Installing timescale/tap/timescaledb dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.13.1.mojave.bottle.
######################################################################## 100.0%
==> Pouring cmake-3.13.1.mojave.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.13.1: 5,542 files, 50.6MB
==> Installing timescale/tap/timescaledb dependency: postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-11.1.mojave.bott
######################################################################## 100.0%
==> Pouring postgresql-11.1.mojave.bottle.tar.gz
==> Caveats
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database

To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgres start
==> Summary
🍺  /usr/local/Cellar/postgresql/11.1: 3,548 files, 40.3MB
==> Installing timescale/tap/timescaledb
==> Downloading https://timescalereleases.blob.core.windows.net/homebrew/timesca
######################################################################## 100.0%
==> ./bootstrap -DPROJECT_INSTALL_METHOD="brew"
Last 15 lines from /Users/krish/Library/Logs/Homebrew/timescaledb/01.bootstrap:
-- TimescaleDB version 1.0.1. Can be updated from version 1.0.0
-- Build type is Release
-- Install method is 'brew'
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN
-- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success
-- Using compiler AppleClang
-- Found Git: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/git (found version "2.17.2 (Apple Git-113)")
-- Using pg_config /usr/local/bin/pg_config
-- Compiling against PostgreSQL version 11.1
CMake Error at CMakeLists.txt:173 (message):
  TimescaleDB only supports PostgreSQL 9.6 or 10

-- Configuring incomplete, errors occurred!
See also "/tmp/timescaledb-20181212-3282-i530hd/timescaledb/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/timescale/homebrew-tap/issues

**Comment by RobAtticus** [comment]
Thanks. We are aware of the issue and plan to have a new release shortly with PG11 support so that this issue will be moot in (hopefully) a few days.

**Comment by dianasaur323** [comment]
Hi @gopalakrishnan-subramani - 1.1.0 is out! Please go ahead and retry, and file an issue if you hit any errors.

**Comment by RISCfuture** [comment]
I see that the Homebrew recipe requires `postgresql@10` now, but doesn't Timescale work with PostgreSQL 11? (At least, beta support for it?)

**Comment by RobAtticus** [comment]
The formula looks to just depend on `postgresql`, where are you seeing `postgresql@10`?

**Comment by RobAtticus** [comment]
This line in particular:
https://github.com/timescale/homebrew-tap/blob/master/timescaledb.rb#L9

**Comment by RISCfuture** [comment]
```
17:41:50  2.5.3@1ma Programs/Rails/one_mike_alpha timescale ✓ <130> » brew info timescaledb
timescale/tap/timescaledb: stable 1.1.0
An open-source time-series database optimized for fast ingest and complex queries. Fully compatible with PostgreSQL.
https://www.timescaledb.com
Not installed
From: https://github.com/timescale/homebrew-tap/blob/master/timescaledb.rb
==> Dependencies
Build: cmake ✔, postgresql@10 ✘, openssl ✔
==> Caveats
Make sure to update /usr/local/var/postgres/postgresql.conf to include the extension:

  shared_preload_libraries = 'timescaledb'

To finish the installation, you will need to run:

  $ timescaledb_move.sh

This will install the extension files in the proper place. 
If installed via Homebrew:

  $ brew services restart postgresql
```

**Comment by RobAtticus** [comment]
I don't see that:
```
$ brew info timescaledb
timescale/tap/timescaledb: stable 1.1.0
An open-source time-series database optimized for fast ingest and complex queries. Fully compatible with PostgreSQL.
https://www.timescaledb.com
Not installed
From: https://github.com/timescale/homebrew-tap/blob/master/timescaledb.rb
==> Dependencies
Build: cmake ✔, postgresql ✔, openssl ✔
==> Caveats
Make sure to update /usr/local/var/postgres/postgresql.conf to include the extension:

  shared_preload_libraries = 'timescaledb'

To finish the installation, you will need to run:

  $ timescaledb_move.sh

This will install the extension files in the proper place.
If installed via Homebrew:

  $ brew services restart postgresql
```

**Comment by RISCfuture** [comment]
Oh, my bad, completely forgot I edited the recipe 🤦‍♂️

**Comment by RobAtticus** [comment]
No problem :) Hope it works out now!

**Comment by gopalakrishnan-subramani** [comment]
It worked for me, installed correctly.
Happy to see https://docs.timescale.com/v1.1/getting-started/installation/macos/installation-homebrew document updated with   [BETA] 11.0+ support.

**Comment by taf2** [comment]
Seems the same issue is back now with postgresql 12

**Comment by drewtcraft** [comment]
same for postgresql 13
