### ISSUE TITLE
Tablespace for primary key constraint is not been updated by SET TABLESPACE

### ISSUE THREAD

**Issue by eduardotsj** [timescale/timescaledb#903]
**Relevant system information:**
 - OS: Windows Server 2012 x64
 - PostgreSQL version (output of `postgres --version`): 9.6.9
 - TimescaleDB version (output of `\dx` in `psql`): 0.9.2
 - Installation method: Windows installer

**Describe the bug**
The hypertable was created with the wrong PK contraint tablespace, after realizing that, we fixed the tablespaces for all existing chunk indexes and on the hypertable, but new chunks are been created on the old tablespace.

**To Reproduce**
- Create a table with the primary key index on tablespace TABLESPACE_1
- Insert some data so that the initial chunks are created
- Alter the index tablespace for PK constraint using ALTER INDEX ... SET TABLESPACE TABLESPACE_2
- Insert more data in a way that new chunks got created
- New chunks are still been created on TABLESPACE_1 not on current one that is TABLESPACE_2

**Expected behavior**
After updating the tablespace for an Index, new chunks will be created in the current tablespace.

**Actual behavior**
After updating the tablespace for an Index, new chunks are created in the original tablespace.

**Comment by davidkohn88** [comment]
For the behavior, you do mean that new chunks' indexes are created in the original tablespace, the chunks themselves aren't moving around right?

**Comment by eduardotsj** [comment]
I'm not sure about the chunks, because I did not do any tablespace change on them, I just had to change the PK tablespace because it was wrong and when we realized that the table was already too big and deleting the index and creating it again should cause an undesired impact on the near real-time data collection that we are doing.

**Comment by davidkohn88** [comment]
Okay. Got it. Thanks for clarifying!
