### ISSUE TITLE
Is MariaDB support in the pipeline?

### ISSUE THREAD

**Issue by ericcurtin** [timescale/timescaledb#954]
This is a nice project. We have a couple of use cases where timescaledb might be useful (prometheus and some other event logging). But it would be a hard sell to ask the team to introduce a second RDBMS dependency on our backend (we already have MariaDB). Are there any plans to support MariaDB as well as postgresql? Or are there some technical limitations here?

**Comment by davidkohn88** [comment]
Unfortunately, there are definitely some technical issues around that, Maria doesn't, as far as I know, have the same sort of extension framework that Postgres has, and many of our optimizations are built around core Postgres functionality and guarantees. So I'd say it's not in the pipeline. Sorry to disappoint!
 
We do recommend storing your relational data alongside your Time Series data though so if Postgres would work for your normal relational data, you could use it there. Or you can use a foreign data wrapper to query your MariaDB data for the interim, for instance.
