### ISSUE TITLE
financial data : technical indicators

### ISSUE THREAD

**Issue by balajipitchumani** [timescale/timescaledb#970]
Like average, percentile etc..can we look at adding the indicators for stock financial data like these here : https://github.com/lppkarl/Trady/blob/master/supported_indicators.md

**Comment by mfreed** [comment]
Hi @balajipitchumani :  Not sure what question you are asking.  You can certainly compute things like OCHL, average, percentiles histograms, etc. using TimescaleDB.

Please see the docs:  https://docs.timescale.com/v1.1/using-timescaledb/reading-data#advanced-analytics
